### ISSUE TITLE
Upgrading to Docusaurus v3

### ISSUE THREAD

**Issue by Juuddi** [hasura/graphql-engine#10001]
### Is your proposal related to a problem?

Proposal is not related to a problem but rather a new [major release for Docusaurus](https://github.com/facebook/docusaurus/releases/tag/v3.0.0). 

### Describe the solution you'd like

Upgrade to Docusaurus v3. Mostly requires package version changes and optional [visual regression tests](https://docusaurus.io/blog/upgrading-frontend-dependencies-with-confidence-using-visual-regression-testing).

### Describe alternatives you've considered

The only alternative to upgrading Docusaurus is to remain on v2. There is no real issue with remaining on v2 as the Hasura docs function just fine as is right now. Docusaurus v3 upgrades to React v18+, which may cause dependency discrepancies between the docs and other Hasura infra (i.e. the website which runs on React 17.0.2)

### Other notes

Looking through the open issues/PR review it seems the team is quite busy, and this may be a low priority upgrade. I've been interacting quite a bit with the Hasura docs recently + been working on another Docusaurus based project and figured it would be worth it to at least bring it up. Willing to help with the upgrade if needed.

**Comment by seanparkross** [comment]
Hey @Juuddi thanks a ton for suggesting the upgrade to Docusaurus v3 and offering a hand with it. It's great to see you're  involved with the Hasura docs and keen to chip in.

Just a heads up, we've actually been looking into the Docusaurus v3 upgrade already. It's a bit of a tricky one, though. There's a bunch of old config stuff we'd have to sort out, which needs some decisions from our side. Plus our design team is about to roll out a new theme using Tailwind, and that's definitely going to play into how we handle the upgrade.

Given all this, especially the internal stuff and the new theme coming up, tackling the upgrade might be a bit much for external help right now. We've got to make sure everything clicks together just right.

Really appreciate you stepping up to the plate, though. Your input's super valuable, and we totally encourage you to keep the ideas flowing. We'll make sure to keep everyone in the loop about how things are going and if there's a chance for you to jump in down the road. We'll definitely reach out to you if we find somewhere where a Docusaurus & Hasura experienced dev can help. 

Thanks. Sean

**Comment by Juuddi** [comment]
@seanparkross awesome, glad to hear y'all already have the upgrade on the docket! Thanks for the thorough response and looking forward to seeing the new theme roll out. Cheers!
