### ISSUE TITLE
v2.35.0 no longer supports "extensions: null" in query

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#10013]
### Version Information

Server Version: v2.35.0

### Environment

OSS

### What is the current behaviour?

v2.34 and below supported `"extensions": null`
v2.35 and up crashes with: `parsing PersistedQueryRequest failed, expected Object, but encountered Null`

### What is the expected behaviour?

I want the same behaviour as v2.34 in v2.35 and up

### How to reproduce the issue?

1. Query hasura v2.35 with `{"query":"{ __schema { queryType { fields { name  } } } }","variables":null,"operationName":null, "extensions":null}`
2. Fails with `parsing PersistedQueryRequest failed, expected Object, but encountered Null`
3. Remove `"extensions":null` from the query.
4. Query works.

### Screenshots or Screencast

![image](https://github.com/hasura/graphql-engine/assets/11539524/8bfdea69-5a22-4ff0-b5d9-6fa5b7b8937f)

![image](https://github.com/hasura/graphql-engine/assets/11539524/a7c977d3-ab9c-4ce8-8523-d31868839012)

### Any possible solutions/workarounds you're aware of?

Removing `"extensions":null`

**Comment by jflambert** [comment]
This is the commit that broke compatibility with `"extensions": null`

https://github.com/hasura/graphql-engine/commit/203b85af251da058bd2bab17d2b1fc29cfd28456

**Comment by marionschleifer** [comment]
Hi @jflambert, thank you for reporting that. We're looking into this right now and will get back when we have a fix.

**Comment by manasag** [comment]
This fix is going to arrive in 2.36 due to release this week.

**Comment by jflambert** [comment]
@marionschleifer @manasag  you can close this now...
