### ISSUE TITLE
V3: Add docs links for metadata types in VSCode

### ISSUE THREAD

**Issue by manasag** [hasura/graphql-engine#10044]
The metadata structure in V3 is all new. Add easily discoverable and navigable documentation for metadata fields while working with VSCode extension.

**Comment by soorajshankar** [comment]
Here is a short demo from @wawhal on the improvisation on the on hover DX on VS Code.

https://github.com/hasura/graphql-engine/assets/8408875/5ea71324-906f-449a-89a5-0a15c1a48794

**Comment by manasag** [comment]
This is supported in DDN Beta
