### ISSUE TITLE
server: unexpected behavior in pro cache clear API

### ISSUE THREAD

**Issue by meetzaveri** [hasura/graphql-engine#10055]
### Version Information

Server Version: 2.33.4

### Environment

Cloud/EE

### What is the current behaviour?

Let me cover the workings of cache clear API pre- v2.33.

#### For 2.25.1,
Say I have performed a query with cached directive. And then after I added/deleted rows in respective table. So after hitting /pro/cache/clear , it would return a response as
```json
{
 "clearedItemCount": "1",
 "message": "success"
}
```
And it would get reflected when I would perform the cached query call again.

#### For 2.33.4,
I did same procedure as above but when hitting /pro/cache/clear , it would return a response as
```json
{
  "clearedItemCount": "0",
  "message": "success"
}
```
As it shows, zero item were stored in cache but when in reality there was as I had performed the same cached query after restarting engine on 2.33.4 . I had added a new record prior to clearing the cache, but it didn't get reflected in the cached query call after clearing the cache via that endpoint.
- Plus, the results would not get reflected immediate i.e. it would still show old cached result even after retrying query call after clearing cache.
- At some 3rd or 4th attempt, it would reflect the new updated data.
- Whenever I cleared the cache, one of the response would contain "internal redis service error" and then after retry it would work (this is secondary issue to the main primary issue)

**Note**: Remember, that I use `@cached` directive in my query.

### What is the expected behaviour?

The exact behavior which is shown in 2.25 (which I mentioned above) , should be the same behavior in versions > 2.33.

### How to reproduce the issue?

For example, you can try like 
- Perform query with `@cached` directive and see the results
- Add some records to that table (which is queried)
- Clear the cache (via some tools like POSTMAN or CURL) on parallel
- Re-perform the same query and observe the results (it would show still the older cached records).

Also, if you perform cache clear API, you will get response of `clearedItemCount` with value `0`,  which should have been `1`.

### Screenshots or Screencast

2.25.1 Recording

YT link - https://youtu.be/0XkCabjU744

2.33.4 Recording

YT link - https://youtu.be/lSmkUSgONTg

### Any possible solutions/workarounds you're aware of?

There are couple of workarounds.
- Most straight forward, retry the cache clear API multiple times until you observe the newly cached result
- Forcing the cache to refresh, doc - https://hasura.io/docs/latest/caching/caching-config/#forcing-the-cache-to-refresh

### Keywords

cache clear pro API

**Comment by Kashish3009** [comment]
v2.40.0-cloud.1 contains the fix for this issue.

Reference: [The Changelog](https://hasura.io/changelog)
