### ISSUE TITLE
V3/VS Code extension - Allow Directory Selection while track/track all on VS Code actions.

### ISSUE THREAD

**Issue by soorajshankar** [hasura/graphql-engine#10079]
### New Feature Demo: Directory Selection for Enhanced Workflow

We're introducing a practical new feature that allows users to select directories seamlessly, enhancing their workflow for tracking code actions and managing metadata. This will empower developers to scaffold the metadata as they want and equally use the VS Code extension to generate the metadata. 

[Watch the Demo](https://www.loom.com/share/93dac88eae644c009cda0c1e1aee049b)

This functionality will soon be incorporated into the Hasura VS Code extension. Your feedback is valuable, so feel free to share your thoughts or questions!

**Comment by abhi40308** [comment]
closing as outdated
