### ISSUE TITLE
auth url ?

### ISSUE THREAD

**Issue by arpecop** [hasura/graphql-engine#10071]
### What is the current behaviour?
`https://oauth.pro.hasura.io/oauth2/auth?client_id=xxx&code_challenge=xxx&code_challenge_method=S256&redirect_uri=http%3A%2F%2F127.0.0.1%3A42967&response_type=code&state=xxx%3D%3D`

### How to reproduce the issue?

1. run hasura3 login
### Please provide any traces or logs that could help here.

 what is supposed to run on localhost 42967 port to continue?

**Comment by soorajshankar** [comment]
Thanks for reporting the issue! 
While we are looking int this, could you share which version of Hasura CLI are you running? you can check this by running `hasura3 version`

**Comment by soorajshankar** [comment]
I have an update here, and basically the port will be used temporarily to get back the OAuth token from the browser and you don't need to run anything on your side to get this working - as these are automatically taken care by the CLI. This is method is also recommended here - https://www.rfc-editor.org/rfc/rfc8252#section-7.3

Closing this ticket as there is no actionable on this, feel free to re-open this if you have more questions or anything to add here.
