### ISSUE TITLE
Allow automatic authorization import from JWT sub claim

### ISSUE THREAD

**Issue by JCKodel** [hasura/graphql-engine#10086]
### Is your proposal related to a problem?

Accordingly to the official documentation (https://hasura.io/blog/authentication-and-authorization-using-hasura-and-firebase/), I have to write a custom firebase function to append the required Hasura claims on Firebase JWT, problem is: dependending on how much users you have, this could be really expensive.

### Describe the solution you'd like

An option that allows us to configure which field of JWT we want to use as our `X-Hasura-User-Id` and the default role.

For example:

Given this Firebase token:

```json
{
  "name": "My name",
  "picture": "https://my-picture",
  "iss": "issuer,
  "aud": "audience",
  "auth_time": 1704400216,
  "user_id": "hJlmuboFOHhpbwW5cSZbxDa2H4O2",
  "sub": "hJlmuboFOHhpbwW5cSZbxDa2H4O2",
  "iat": 1704400216,
  "exp": 1704403816,
  "email": "email@email.com",
  "email_verified": true,
  "firebase": {
    "identities": {
      "google.com": [
        "1152xxx57206185"
      ],
      "email": [
        "email@email.com"
      ]
    },
    "sign_in_provider": "google.com"
  }
}
```

This is a Firebase sign in using Google, so my User Id for that application is `hJlmuboFOHhpbwW5cSZbxDa2H4O2`.

So, Hasura could have this configuration:

```
HASURA_GRAPHQL_JWT_PATH: sub
HASURA_GRAPHQL_JWT_DEFAULT_ROLE: user
```

So, when passing the unmodified Firebase JWT to Hasura, it considers `X-Hasura-User-Id` as `hJlmuboFOHhpbwW5cSZbxDa2H4O2` (comming from my JWT `sub` claim) and `X-Hasura-Role` as `user`.

### Describe alternatives you've considered

Running a bare metal function (that I already have to pay to run Hasura anyway) to detect and change the Firebase JWT token using Firebase Auth SDK (which adds latency).

It works, but, it could be automatic.

**Comment by krushanbauva** [comment]
Hey @JCKodel, thanks for opening a ticket. We do have a JWT configuration option `claims_map` that allows you to map Hasura session variable to existing JWT claims. `claims_map` is a JSON object where keys are session variables and values can be a JSON path (with a default value option, when the key specified by the JSON path doesn't exist) or a literal value. You can refer to the docs [here](https://hasura.io/docs/latest/auth/authentication/jwt/#claims_map).

**Comment by krushanbauva** [comment]
Closing this ticket as there is no actionable on this, feel free to re-open this if you have more questions or anything to add here.
