### ISSUE TITLE
Order by in query is using ascending order of field names, instead of order of fields in query

### ISSUE THREAD

**Issue by bhanuprasadcherukuvada** [hasura/graphql-engine#10084]
### Version Information

Server Version: v2.36.1-cloud.1
CLI Version (for CLI related issue):

### Environment

present in Cloud and OSS 

### What is the current behaviour?

In generated SQL for query, the `order by` fields are arranged according the ascending order of field names used, as opposed to the order fields declaration

### What is the expected behaviour?

Generated SQL should use the order of fields mentioned, as in the query

### How to reproduce the issue?

1.  create a sample table in free cloud version with neon db 
```sql
create table if not exists phone_numbers (
id uuid NOT NULL DEFAULT uuid_generate_v1mc(),
"number" int not null unique,
"primary" boolean DEFAULT false,
verified boolean DEFAULT false,
created_at timestamp with time zone NOT NULL DEFAULT now(),
updated_at timestamp with time zone NOT NULL DEFAULT now());
```
2. insert values 
```sql
insert into phn_numbers("primary","number",verified)
values (true,1,true),(true,2,false),(false,3,false);
```
3. now in graphql console run this query 
```graphql
query MyQuery {
  phone_numbers(order_by: {primary: desc, verified: desc, created_at: desc}) {
    number
    primary
    verified
    created_at
  }
}
```

Click on the analyze button to see the generated sql, it would look something like this 

```sql

SELECT
  coalesce(
    json_agg(
      "root"
      ORDER BY
        "root.pg.created_at" DESC NULLS FIRST,
        "root.pg.primary" DESC NULLS FIRST,
        "root.pg.verified" DESC NULLS FIRST
    ),
    '[]'
  ) AS "root"
FROM
  (
    SELECT
      row_to_json(
        (
          SELECT
            "_e"
          FROM
            (
              SELECT
                "_root.base"."number" AS "number",
                "_root.base"."primary" AS "primary",
                "_root.base"."verified" AS "verified",
                "_root.base"."created_at" AS "created_at"
            ) AS "_e"
        )
      ) AS "root",
      "_root.base"."created_at" AS "root.pg.created_at",
      "_root.base"."primary" AS "root.pg.primary",
      "_root.base"."verified" AS "root.pg.verified"
    FROM
      (
        SELECT
          *
        FROM
          "public"."phone_numbers"
        WHERE
          ('true')
        ORDER BY
          "created_at" DESC NULLS FIRST,
          "primary" DESC NULLS FIRST,
          "verified" DESC NULLS FIRST
      ) AS "_root.base"
    ORDER BY
      "root.pg.created_at" DESC NULLS FIRST,
      "root.pg.primary" DESC NULLS FIRST,
      "root.pg.verified" DESC NULLS FIRST
  ) AS "_root"
  
  ```
  
  The expected order  in `ORDER BY` Clause should be 
  `primary,verified,created_at`

### Screenshots or Screencast

<img width="1111" alt="image" src="https://github.com/hasura/graphql-engine/assets/47697586/faa9a7f2-9b4b-4e72-8161-4bff1ad18dfe">

its sorting based on `created_at` first which is resulting in `number 3` to appear at first, 

but expected result is to `number 1` to appear at first when we sort according to `primary`, `verified`, `created_at` order

### Keywords

`order_by`

**Comment by krushanbauva** [comment]
Hey @bhanuprasadcherukuvada, thanks for creating a ticket. If you want to sort by multiple fields, you'll have to provide them as a list. Key order in input object for `order_by` is [not preserved](https://github.com/hasura/graphql-engine/releases/tag/v2.0.0). This means you should only have a single key per object, or you may see unexpected behavior. You can refer the docs [here](https://hasura.io/docs/latest/queries/postgres/sorting/#sorting-by-multiple-fields).
```graphql
query MyQuery {
  phone_numbers(order_by: [{primary: desc}, {verified: desc}, {created_at: desc}]) {
    number
    primary
    verified
    created_at
  }
}
```
Changing your query to this should get you the desired result.

**Comment by krushanbauva** [comment]
Closing this ticket as there is no actionable on this, feel free to re-open this if you have more questions or anything to add here.

**Comment by soorajshankar** [comment]
Thanks for bringing this to our attention, I am re-opening this as a Console/GraphiQL DX issue.
(also updating the title to reflect the same)
