### ISSUE TITLE
v3: Add tree view explorer on VS Code extension

### ISSUE THREAD

**Issue by soorajshankar** [hasura/graphql-engine#10095]
### Component

VSCode Extension -> c/v3-lsp

### Is your proposal related to a problem?

Its a little tricky to visualise the supergraph and metadata objects with file system, would be nice to have a tree view explorer on VS Code extension so that metadata objects and trackable objects are easy to visualise and manage. 

Update: we have a prototype working and the demo is here 
<img width="1027" alt="image" src="https://github.com/hasura/graphql-engine/assets/8408875/afa2db93-b5d7-422e-a4e9-98dbde987baa">

https://www.loom.com/share/a23b204a4e644f7f9066ad50beb1b8a3 🎉

**Comment by abhi40308** [comment]
closing as outdated
