### ISSUE TITLE
v3 - hasura3 watch command fails due to "too many open files"

### ISSUE THREAD

**Issue by sghoweri** [hasura/graphql-engine#10106]
### Component
c/v3-cli 

Hasura DDN CLI Version: 2024.01.15

### What is the current behaviour?
I'm unable to use the `hasura3 watch` command in an existing repo (ie. real world use case), likely due to the number of files in the repo (node_modules).

This error occurs whether or not I include the `--dir` and `--profile` CLI params.

### What is the expected behaviour?
1. By default, ignore the `node_modules` folder
2. Provide a way (either via config or via the CLI itself) to omit files / folders from being watched

### Screenshots or Screencast
![CleanShot 2024-01-19 at 17 34 30@2x](https://github.com/hasura/graphql-engine/assets/1617209/386dc70f-73b7-494f-8261-a71c38152195)

### Please provide any traces or logs that could help here.
![CleanShot 2024-01-19 at 17 41 23@2x](https://github.com/hasura/graphql-engine/assets/1617209/9a6babd2-7678-4bed-b785-f6e6f28bff59)

**Comment by harishnair96** [comment]
Hello @sghoweri , thank you for reporting the issue. We were able to identify the problem and we will release an improvement for this feature in a future version of the CLI.

This limit on the number of open files is operating system specific and for now you can try increasing this limit by following the instructions here: <https://github.com/fsnotify/fsnotify?tab=readme-ov-file#platform-specific-notes>

**Comment by manasag** [comment]
Closing this issue as it is fixed in the latest version of v3 cli. Please reopen if this is still an issue.
