### ISSUE TITLE
Cannot execute Queries from Vue.js

### ISSUE THREAD

**Issue by bhaidar** [hasura/graphql-engine#1015]
Hi,
In an application I'm working on, I am using Apollo Client and auth0 to connect to Hasura on Heroku.
I've deployed the auth0 webhook also on Heroku.
I've configured the Hasura app with both the Access and Webhook keys.

When I configure Apollo to send the X-Hasura-Access-Key, the query works and I retrieve results.
When the X-Hasura-Access-Key is omitted, I get the following exception:

```
code: "validation-failed"
error: "field "xxx" not found in type: 'query_root'"
path: "$.selectionSet.xxx"
```

The docs mention the following:

- The configured webhook is called when X-Hasura-Access-Key header is not found in the request.
- The configured webhook is ignored when X-Hasura-Access-Key header is found in the request.

What I understand is that, if I don't send the access-key, Hasura would call the webhook.

Any idea what's going on here?

Thanks

**Comment by bhaidar** [comment]
Hi,
I debugged the auth0 webhook sample and I noticed that I was sending idToken instead of accessToken

It works now, thanks!

**Comment by shahidhk** [comment]
@bhaidar Glad that it worked. Closing this issue now. Feel free to re-open if you have other questions.

**Comment by grp06** [comment]
@michaelgu95 --- also wondering this. I'm able to make requests successfully within GraphiQL in Hasura's UI but when I make requests from the frontend with Apollo I'm not passing the x-hasura-access-key through. Did you figure this out?
