### ISSUE TITLE
hasura-cli v2.38.0 npm installation has no dist folder causing installation issues

### ISSUE THREAD

**Issue by bkniffler** [hasura/graphql-engine#10182]
<img width="769" alt="Bildschirmfoto 2024-03-28 um 13 03 58" src="https://github.com/hasura/graphql-engine/assets/4349324/f57ad9d8-d9f2-45ef-9393-ce597cc3a834">
<img width="824" alt="Bildschirmfoto 2024-03-28 um 13 05 00" src="https://github.com/hasura/graphql-engine/assets/4349324/b5e5d3af-d190-4c01-9e65-d6e69dab74c8">

Causing 
```
  ⚙️  hasura-cli [1/2] node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/Users/.../GitHub/vrplatform/graphql/node_modules/hasura-cli/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.10.0

error: postinstall script from "hasura-cli" exited with 1
```

**Comment by bkniffler** [comment]
Previous versions also fail, e.g. `[2.37.0](https://www.npmjs.com/package/hasura-cli/v/2.37.0)`

Was able to install `hasura-cli@2.36.1`.

**Comment by Oleh-Rudko** [comment]
I have the same issue!

`hasura-cli@2.36.1` works to me

**Comment by abdullah2993** [comment]
`hasura-cli` package is not maintained by hasura, may be report [here](https://github.com/jjangga0214/hasura-cli)

**Comment by bkniffler** [comment]
Oh wow, thanks @abdullah2993, I had no clue!

**Comment by bkniffler** [comment]
https://github.com/jjangga0214/hasura-cli/issues/116

**Comment by loi-avela** [comment]
> Previous versions also fail, e.g. `[2.37.0](https://www.npmjs.com/package/hasura-cli/v/2.37.0)`
> 
> Was able to install `hasura-cli@2.36.1`.

wish i found this post two hours ago!
