### ISSUE TITLE
Getting "Network error: Response not successful: Received status code 400" when there is an error in gql

### ISSUE THREAD

**Issue by pyankoff** [hasura/graphql-engine#1019]
I was getting status code 400 error from Hasura when there was wrong variable in gql. Took me a while to figure out the reason. Is it possible to receive more informative error message?

**Comment by shahidhk** [comment]
@pyankoff Can you take a look at the response body? 400 Bad Requests can happen when the user does not have enough permissions etc. and the details will be in the response body.

**Comment by pyankoff** [comment]
@shahidhk thanks for your prompt response. Yes, response body has more helpful info. I don't have any permissions set up yet, that's why the 400 network error response was very confusing. It would be great if the error message from catchall `catch(e) { console.warn(e) }` had helpful info.

**Comment by shahidhk** [comment]
@pyankoff What is the client library that you are using?

**Comment by pyankoff** [comment]
Apollo

**Comment by dsandip** [comment]
closing this in favor of #1368

**Comment by istreetec** [comment]
This a times happens after deleting a content type and then try referencing it from the frontend. That was my case. Make sure the collection exists before consuming it.
