### ISSUE TITLE
Support for conditional logic during the emission of event triggers 

### ISSUE THREAD

**Issue by pari-m** [hasura/graphql-engine#10203]
### Component

c/v3-engine

### Is your proposal related to a problem?

N/A

### Describe the solution you'd like

Support for adding conditional logic before the event triggers are emitted from Hasura.

### Describe alternatives you've considered

A trigger can be created in the native database with the custom login whose action is to write to a new table. Hasura event triggers can be configured on this new table. This way the conditional logic occurs at the Database layer.

**Comment by tirumaraiselvan** [comment]
Closing as dupe of https://github.com/hasura/graphql-engine/issues/1241
