### ISSUE TITLE
Native query and logical model added using the hasura console (graphql) is not added to metata on disk

### ISSUE THREAD

**Issue by andoks** [hasura/graphql-engine#10217]
### Version Information

Server Version: v2.35.3 (hasura/graphql-engine:v2.35.3.cli-migrations-v2@sha256:bca701bfde562be1de16ea8d34295b5bd17494204151f606fa6656b80baa5ce4)
CLI Version (for CLI related issue): v2.35.3

### Environment

OSS

### What is the current behaviour?

When creating a native query and its required logical model using hasura console, neither the native query nor the logical model are added to the hasura configuration files (metadata).

Note that the native query and logical model does show up when I try to download the metadata from settings in hasura console. Maybe this is related to still using config v2 instead of v3?

### What is the expected behaviour?
When creating native query and logical model using the hasura console, the native query and logical model are added to the metadata files

### How to reproduce the issue?

1. Using the above mentioned version of the cli and server, create a native query, e.g server_time with the query `select now() at time zone 'utc' AS "current_time_utc";`, also add the required logical model
2. After saving both native query and model, go test it in the API tab, observe that it works
3. Observe that none of the metadata files have been updated

### Any possible solutions/workarounds you're aware of?

No

### Keywords

native query, native queries, logical model, cli, console

**Comment by andoks** [comment]
After testing, I can confirm that this only happens if using v2 of the configuration format. It works ok with v3 config format

**Comment by listiani13** [comment]
Fixed this by upgrading to latest CLI (v2.40.0)

**Comment by andoks** [comment]
Confirmed fixed in later version by @listiani13
