### ISSUE TITLE
Supporting auto introspection for Native Queries and more

### ISSUE THREAD

**Issue by manasag** [hasura/graphql-engine#10249]
Currently adding a native query to your schema involves hand typing the input and output types, and in general is hard to test out the query with sample input. This issue is to make this authoring experience much better.

**Comment by soupi** [comment]
Happy to report we've introduced new plugin commands to support authoring of Native Operations for ndc-postgres in a way that does not require manual configuration authoring.

The tl;dr is, write a [SQL query](https://hasura.io/docs/3.0/connectors/postgresql/native-operations/syntax) to a file, then issue an ndc-postgres-cli command to add it to the ndc-postgres configuration.

See [the documentation](https://hasura.io/docs/3.0/connectors/postgresql/native-operations/custom-queries) for more information.
