### ISSUE TITLE
Document client websocket connection details for subscriptions

### ISSUE THREAD

**Issue by Maxpain177** [hasura/graphql-engine#1026]
Now we can specify headers to `payload` in WebSocket message only on `connection_init`.
Please add the ability to specify headers on every request.
It is necessary for schema stitching because at this moment we need to create a separate WebSocket client (our `Apollo server` <-> `Hasura GraphQL engine`) for every external client (`apollo client` <-> `apollo server`)

**Comment by 0x777** [comment]
@Maxpain177 It it totally okay to create a new websocket connection to hasura for every websocket connection to your server. graphql-engine expects a websocket connection to be tied to a user. So when a websocket connection is initialised (with `connection_init` message), the server doesn't need to resolve the user information (calling webhook or resolving jwt) for every message that is sent.

**Comment by rikinsk** [comment]
related: #353 #472 #412 #994

**Comment by rikinsk** [comment]
Tracked here #412
