### ISSUE TITLE
`replace_metadata` requires metadata without resource_version despite what docs imply

### ISSUE THREAD

**Issue by banool** [hasura/graphql-engine#10324]
### Version Information

Server Version: v2.40.2

### Environment

Cloud

### What is the current behaviour?

I'm working with a type like this:
```ts
export type Metadata = {
    resource_version: number;
    metadata: {
        version: 3;
        sources: Source[];
        backend_configs?: BackendConfigs;
        remote_schemas?: RemoteSchema[];
        actions?: Action[];
        query_collections?: QueryCollection[];
        allowlist?: AllowList[];
        inherited_roles?: InheritedRole[];
        custom_types?: CustomTypes;
        cron_triggers?: CronTrigger[];
        network?: Network;
        rest_endpoints?: RestEndpoint[];
        api_limits?: ApiLimits;
        graphql_schema_introspection?: GraphQLSchemaIntrospection;
        opentelemetry?: OpenTelemetry;
    };
};
```

With data like this:
```
{
  "resource_version": 11,
  "metadata": {
    "version": 3,
    "sources": [
      {
        "name": "indexer-v2",
        "kind": "postgres",
        "tables": [
etc.
```

When making a request to `replace_metadata`, I have to do this:
```ts
await client.request({
  url: `${endpoint}/v1/metadata`,
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    // For authing with Hasura.
    "x-hasura-admin-secret": adminSecret,
  },
  body: JSON.stringify({
    type: "replace_metadata",
    // Version of the metadata API to use.
    version: 2,
    args: {
      allow_inconsistent_metadata: false,
      allow_warnings: true,
      // The docs imply I should be able to use inputs.metadata here but I can't.
      // This means checking resource_version doesn't work because we never update it.
      metadata: inputs.metadata.metadata,
    },
  }),
});
```

Note that I have to use `metadata.metadata`, not the whole metadata.

### What is the expected behaviour?

The docs say here (https://hasura.io/docs/latest/api-reference/metadata-api/manage-metadata/#metadata-replace-metadata) say that the `metadata` field of the args should be the output of [export_metadata](https://hasura.io/docs/latest/api-reference/metadata-api/manage-metadata/#metadata-export-metadata). But this is not true, the output of `export_metadata` is the full metadata, with `resource_version` and an outer `metadata` field, but the endpoint expects the "inner" metadata.

If you change the above code to use `inputs.metadata` you get an error like this:
```
{"error":"key \"tables\" not found","path":"$.args.metadata","code":"parse-failed"}
```

The fix for this top level issue would be to fix the docs, but what I wonder is how do I update `resource_version` given this limitation? As it is now, since I'm not providing `resource_version` in my request, `resource_version` just increments monotonically. I don't want this, when I replace the metadata, I want to set the `resource_version` to the given value.

### How to reproduce the issue?

See above.

### Screenshots or Screencast
N/A

### Please provide any traces or logs that could help here.
N/A

### Any possible solutions/workarounds you're aware of?
N/A

### Keywords
Metadata, metadata API, replace_metadata, export_metadata.

**Comment by SamirTalwar** [comment]
Hi, what happens if you put `resource_version` outside (and alongside) the `args`?

Something like:

```
{
  type: "replace_metadata",
  version: 2,
  resource_version: <version from export>,
  args: {
    ...
  }
}
```

You should provide the same `resource_version` you recieved when exporting the metadata. It is there as a lock, to ensure that the data has not changed since you exported. This allows you to perform modifications to the export before replacing, knowing that if changes were made in the mean time from another source, you can abort and retry.

> when I replace the metadata, I want to set the resource_version to the given value.

I'm afraid that's not what it's for. It will always be a monotonically-increasing counter because if we allowed you to specify the value, it would lose its purpose as a locking mechanism.
