### ISSUE TITLE
Docs: Command reference documentation should talk about "why / what is a model" 

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#10330]
On the command documentation https://hasura.io/docs/3.0/supergraph-modeling/commands shouldn't we mention why commands exist and what they do?

For example:

Commands allow you to add custom fields to other types and invoking custom methods. 
Here are some examples of why/what commands:
1. Adding custom field to an existing model for transformation
2. Adding top level methods to the API

And then we go into the reference documentation?

**Comment by seanparkross** [comment]
https://github.com/hasura/v3-docs/pull/501
