### ISSUE TITLE
Unnecessary and unhelpful warning message while creating an empty .hml file

### ISSUE THREAD

**Issue by aayshasura** [hasura/graphql-engine#10336]
### Component
LSP (vscode extension)

### What is the current behaviour?
When creating an empty file in the hasurav3 project directory(created via CLI using getting started), the following warning messages are shown. The warning messages itself is unhelpful and we should allow empty .hml files without warning messages.

### What is the expected behaviour?
No warnings and wherever the warning is applicable the message should be helpful

### How to reproduce the issue?

1. using the latest cli initialize a supergraph(this will either create a dir and create necessary files)
2. add a new .hml file to the above directory

### Screenshots or Screencast

![Screenshot 2024-07-15 at 1 18 19 PM](https://github.com/user-attachments/assets/486ad1f1-1d57-4904-9862-e7fa6719a504)

**Comment by abhi40308** [comment]
fixed in `v2.0.4` of [hasura vscode extension](https://marketplace.visualstudio.com/items?itemName=HasuraHQ.hasura)
