### ISSUE TITLE
`version` suggestion not working in `hasura.yaml`, and incorrect error displayed if `version` key is missing

### ISSUE THREAD

**Issue by m-Bilal** [hasura/graphql-engine#10348]
### What is the current behaviour?
If the `version` key is missing in `hasura.yaml`, there are 2 problems:
1. The auto complete suggestions are incorrect
2. The error shown in wrong

### What is the expected behaviour?
The correct error should be displayed. Also, the missing key should be suggested by LSP

### How to reproduce the issue?

1. Create a new supergraph
2. Remove the `version` key and value from `hasura.yaml`
3. Start typing `version` to get auto complete suggestions and errors

### Screenshots or Screencast
https://github.com/user-attachments/assets/f92d2098-b8cd-493b-9701-42417cd691d9

### Please provide any traces or logs that could help here.
None

### Any possible solutions/workarounds you're aware of?
None

**Comment by abhi40308** [comment]
fixed in `v2.0.5` of [hasura vscode extension](https://marketplace.visualstudio.com/items?itemName=HasuraHQ.hasura)
