### ISSUE TITLE
LSP shows incorrect error if `version` key in `hasura.yaml` does not have a value

### ISSUE THREAD

**Issue by m-Bilal** [hasura/graphql-engine#10345]
### What is the current behaviour?

Screenshot of the current behaviour. Notice that the error is `Missing property "kind"`

### What is the expected behaviour?

The LSP should show the correct error (`A value of either "v1" or "v2" expected`)

### How to reproduce the issue?

1. Create a new project (create a supergraph)
2. Open `hasura.yaml` and remove the version key

### Screenshots or Screencast
<img width="680" alt="image" src="https://github.com/user-attachments/assets/7b876164-9086-4647-a642-55b34f5613e5">

### Please provide any traces or logs that could help here.
None

### Any possible solutions/workarounds you're aware of?
None

**Comment by abhi40308** [comment]
fixed in v2.0.0
