### ISSUE TITLE
docs: (minor) typo in clickhouse docs

### ISSUE THREAD

**Issue by ananya-2410** [hasura/graphql-engine#10351]
https://hasura.io/docs/3.0/getting-started/build/mutate-data?db=ClickHouse

It says: 

>  saved as an environment variables

should be: saved as environment variables

<img width="1048" alt="Screenshot 2024-07-15 at 3 32 40 PM" src="https://github.com/user-attachments/assets/f307240b-7612-4b35-9e71-052ecf4b6a60">

**Comment by seanparkross** [comment]
https://github.com/hasura/v3-docs/pull/496
