### ISSUE TITLE
LSP re-inserts fields that are already present when completing `kind: Subgraph` object in `subgraph.yaml`

### ISSUE THREAD

**Issue by m-Bilal** [hasura/graphql-engine#10354]
### What is the current behaviour?
If the key for `kind` is missing, and there are additional keys in the object, the LSP autocompletes the whole object which results in fields being duplicated

### What is the expected behaviour?
If the `kind` is missing, then when the entire object is inserted, all the previously present keys should be deleted. IMHO we should not suggest completions that result in errors.

### How to reproduce the issue?

1. Remove the value of `kind` in subgraph.yaml
2. Autocomplete the `kind` key

### Screenshots or Screencast
https://github.com/user-attachments/assets/606821c0-3826-4c3e-97bb-889ec6ce42fb

### Please provide any traces or logs that could help here.
None

### Any possible solutions/workarounds you're aware of?
None

**Comment by abhi40308** [comment]
fixed in v2.0.0
