### ISSUE TITLE
Is there a workaround for making GraphQL Engine work with data in an existing MySql database?

### ISSUE THREAD

**Issue by fkpwolf** [hasura/graphql-engine#1035]
Just give a try to the project. Really cool! A combination of different technology.

I just wonder: why not add support to MySql since lt has lots of user? Does feature like event webhook bind with Postgres so it is hard to switch to others?

**Comment by coco98** [comment]
@fkpwolf Thanks for your kind words. No, we're not that deeply tied to Postgres. Most of what we do with Postgres can be done with MySQL as well. But for now our focus to get everything right with Postgres and then a little later add support for other databases. 

I was just chatting with a user recently. They have a system on MS-SQL and they use https://www.symmetricds.org/ to replicate data into a postgres instance on which they have Hasura! So in the short term, that could be a solution till we get to adding more databases!

**Comment by fkpwolf** [comment]
I see. Thanks for the quick response.

**Comment by coco98** [comment]
Postgres FDWs seem like another approach to work on a MySQL database for now.

**Comment by AndryHTC** [comment]
@coco98 please define:
> then a little later add support for other databases

What do you mean with "little later"?
What do you mean with "other databases"?

**Comment by tirumaraiselvan** [comment]
Summarizing workarounds:

1. Replicate data into postgres (see: https://www.symmetricds.org/)
2. Use Postgres Foreign Data Wrappers

For native support, closing in favour of https://github.com/hasura/graphql-engine/issues/1773
