### ISSUE TITLE
No command `ddn supergraph`/`ddn subgraph` but mentioned in docs

### ISSUE THREAD

**Issue by purugupta99** [hasura/graphql-engine#10360]
The command `ddn supergraph`/`ddn subgraph` are mentioned in the docs as separate commands but they work only with corresponding sub commands, so ideally we should not mention them in the left pane or mention them as the parent category and add the related subcommands under it.

![image](https://github.com/user-attachments/assets/57295741-af0d-4546-85ed-662846038c6c)

**Comment by robertjdominguez** [comment]
Thanks for this, @purugupta99. However, any command that has a required subcommand lists what's necessary as a set of "available operations" that are hyperlinked.

As an example, see [here](https://hasura.io/docs/3.0/cli/commands/ddn_subgraph#available-operations).
