### ISSUE TITLE
v3-console: Sample projects, public users can edit subgraph description

### ISSUE THREAD

**Issue by Naveenaidu** [hasura/graphql-engine#10374]
Public users to the sample app https://console.hasura.io/project/vast-buzzard-8147 are able to edit the subgraph description successfully. Only project owners and admin should be allowed to do this.

![image](https://github.com/user-attachments/assets/dc75236e-2340-4a16-842c-711c0308f66f)

Fix: Disable the edit button on console for the `Subgraph` page

**Comment by soorajshankar** [comment]
Edit button is disabled on console now.
