### ISSUE TITLE
Unable to host local DDN API if IPv6 is disabled

### ISSUE THREAD

**Issue by purugupta99** [hasura/graphql-engine#10373]
In a system setting with only IPv4 (IPv6 is disabled), the local DDN API fails to come up with the following error:

![image](https://github.com/user-attachments/assets/d596a2f6-15d5-4b0e-b966-a90edd476681)

Ideally, we should gracefully fallback to IPv4 and ignore IPv6 if it is not enabled.

**Comment by SamirTalwar** [comment]
As a workaround, set the `HASURA_CONNECTOR_HOST` environment variable to `0.0.0.0`.

**Comment by SamirTalwar** [comment]
I looked into this and it's very difficult to determine whether a host will support IPv6 across operating systems. I think the workaround will have to suffice for now.
