### ISSUE TITLE
console: connector builds page consistently errors out

### ISSUE THREAD

**Issue by harishnair96** [hasura/graphql-engine#10375]
### Component

Console

### What is the current behaviour?

<img width="1445" alt="Screenshot 2024-07-15 at 4 22 43 PM" src="https://github.com/user-attachments/assets/5ba1ff86-212c-462b-9cbe-09b2d96d03c8">

It appears as if the error is due to an invalid graphql query.

<img width="960" alt="Screenshot 2024-07-15 at 4 25 09 PM" src="https://github.com/user-attachments/assets/3e181358-fff6-497f-b238-2f4bd3f1ea73">

### What is the expected behaviour?

Do not error out.

### How to reproduce the issue?

Go to connector builds page of the sample e commerce project.

**Comment by soorajshankar** [comment]
Looks like this is resolved, feel free to re-open if you find it persist.
