### ISSUE TITLE
console: traces failing to load

### ISSUE THREAD

**Issue by ananya-2410** [hasura/graphql-engine#10371]
Traces not loading up for a simple query in sample project: tried refreshing, does not work
<img width="1398" alt="Screenshot 2024-07-15 at 4 13 19 PM" src="https://github.com/user-attachments/assets/4d916e53-73b7-4c5c-9783-c31358ff4497">

**Comment by ManushiKhanna** [comment]
@ananya-2410  Please share more details for debugging
