### ISSUE TITLE
LSP does not suggest missing property `date` in `CompatibiltyConfig`

### ISSUE THREAD

**Issue by m-Bilal** [hasura/graphql-engine#10381]
### Component
LSP

### What is the current behaviour?
LSP does not suggest missing property `date` in `CompatibiltyConfig`

### What is the expected behaviour?
LSP should suggest missing property `date` in `CompatibiltyConfig`

### How to reproduce the issue?

1. Remove `date` from `CompatibilityConfig`
2. Try autocompleting `date`

### Screenshots or Screencast
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/8ea29633-3fc3-4075-83df-78f392bbd1d3">

### Please provide any traces or logs that could help here.
None

### Any possible solutions/workarounds you're aware of?
None

**Comment by abhi40308** [comment]
fixed in `v2.0.5` of [hasura vscode extension](https://marketplace.visualstudio.com/items?itemName=HasuraHQ.hasura)
