### ISSUE TITLE
v3-console: Console trace button is not visible

### ISSUE THREAD

**Issue by savanipoojan78** [hasura/graphql-engine#10385]
### What is the current behaviour?

after hitting the graphql not seeing the traces button on the console.

### How to reproduce the issue?

1.
2.
3.

### Screenshots or Screencast
<img width="1352" alt="Screenshot 2024-07-15 at 4 42 44 PM" src="https://github.com/user-attachments/assets/bc0f42c6-cde3-44f7-82ec-8def68accdd5">

**Comment by julian-mayorga** [comment]
The fix is deployed now. Thanks for the help @savanipoojan78!
