### ISSUE TITLE
Docs: Getting Started guide could be less verbose

### ISSUE THREAD

**Issue by nithindv** [hasura/graphql-engine#10391]
### What is the current behaviour?
The current getting started guide seems very verbose spanning multiple pages (~25) / sections making the guide quite lengthy to follow. We are having to sieve through every page trying to find a command to copy paste to get the API up and running. 

### What is the expected behaviour?
In my view, the expectation from the "getting started" guide is to have a set of commands spanning around 1-2 pages which the user can follow to get the API up and running. Different parts of the system can be explained by having hyperlinks (part of core docs) the user can choose to visit and learn more about at any stage but is not forced to read during the getting started.  

We could also add images to depict different concepts such as subgraphs, supergraphs, connectors

### How to reproduce the issue?

1. Follow the docs

**Comment by robertjdominguez** [comment]
Thanks, @nithindv. We definitely have had a lot to say 😅 

However, we won't be acting on this issue during the bug bash. What we will do is continue to evolve this section in line with what's been planned with many folks in the company and ensure that, as convenience commands are released, we make updates to give users shortcuts to speed up their API creation 🤙
