### ISSUE TITLE
v3: unable to create new projects after hitting the limit and deleting

### ISSUE THREAD

**Issue by rohankmr414** [hasura/graphql-engine#10395]
### Component

v3-console

### What is the current behaviour?

I used a script to create max number of projects concurrently, after hitting the limit (150 projects) I was unable to create more projects even after deleting the old ones.

### What is the expected behaviour?

Users should be able to create a project after hitting the limit if they delete the old ones.

### How to reproduce the issue?

1. Create 150 projects.
2. Delete a project.
3. Run `ddn project create`

**Comment by m4ttheweric** [comment]
I'm not sure how this is a console issue. Can you clarify? Based on your description, it seems like you were using a script and after hitting a limit, the script does not work?

**Comment by rohankmr414** [comment]
@m4ttheweric the script allowed me to create 150 projects which I suppose is the limit, I deleted 1 project which brought the project count to 149 and then tried to create a new project using `ddn project create` and it failed.

**Comment by soorajshankar** [comment]
@rohankmr414 it sounds like a CLI/cloud side issue- removing the console tag from this.

**Comment by krushanbauva** [comment]
Max project limit per user is 100 and not 150.
