### ISSUE TITLE
Docs: incorrect connector specification in cli for mysql

### ISSUE THREAD

**Issue by ashwiniag** [hasura/graphql-engine#10402]
<img width="1228" alt="Screenshot 2024-07-15 at 5 26 45 PM" src="https://github.com/user-attachments/assets/8854c0b9-ebc2-4ff2-81ef-7e68efb4498c">

The [doc](https://hasura.io/connectors/mysql) suggest connector as `hasura/MySQL` which throws above error. Whereas it should be hasura/mysql (all small case letters). 

This is consistent across connectors documents 
[](url)

<img width="1249" alt="Screenshot 2024-07-15 at 8 56 30 PM" src="https://github.com/user-attachments/assets/b2d20410-6654-4908-8b97-2ef4d28465b7">

**Comment by seanparkross** [comment]
https://github.com/hasura/ndc-hub/pull/206
