### ISSUE TITLE
Support DISTINCT ON

### ISSUE THREAD

**Issue by dmoiseenko** [hasura/graphql-engine#1040]
DISTINCT ON is a really powerful Postgres feature to perform aggregation-like(pick first in group). It can be used in plain SELECT queries without window function or GROUP BY. 
It will be great to see support of DISTINCT ON since Hasura has excellent support of ORDER BY.

e.g.
We need to get the cheapest fruits in groups by color(see sudo SQL<=>GraphQL below)
```
SELECT DISTINCT ON
  (color)
  color,
  name,
  price
FROM
  fruit
ORDER BY price;
```

```
query {
  fruit(distinct_on: [color], order_by: {price: asc}) {
    color
    name
    price
  }
}
```

Postgres documentation https://www.postgresql.org/docs/11/sql-select.html#SQL-DISTINCT
Usage example https://medium.com/statuscode/the-many-faces-of-distinct-in-postgresql-c52490de5954

**Comment by dmoiseenko** [comment]
@0x777 
WOW! Works great!

**Comment by anonrose** [comment]
Thanks for the insight @0x777

**Comment by cleivson** [comment]
Hi, I know this has been closed already, but is it supposed to work with multiple columns like the postgres query does? I can only use it for a single column

**Comment by rakeshkky** [comment]
Hi @cleivson, please note that this issue was related to Postgres. By the time this was closed, we only support single Postgres source (version 1.x). Thank you.
