### ISSUE TITLE
Build not going through if the value expression contains `BooleanExpression`

### ISSUE THREAD

**Issue by aayshasura** [hasura/graphql-engine#10407]
### What is the current behaviour?
when a modelPermission.select.filter.filedComparison.value uses `BooleanExpression` the build doesnt go through and shows error

### What is the expected behaviour?
Build going through with the given boolean expression evaluated as true or false

### How to reproduce the issue?

1. have a field say isCompleted  in a table say invoice in your pg database with type boolean
2. do the necessary steps from from supergraph init to add all resources from the getting started guide
3. add resources step will create an Invoice.hml file with modelPermissions looking like this
![image](https://github.com/user-attachments/assets/9e6d38e4-5276-4bac-8098-b742cb618746)
4. edit the ModelPermissions manually to the below form (this is valid because isCompleted field is of type Bool
![image](https://github.com/user-attachments/assets/a7e27c8f-79f4-4645-bcb8-17224de51eda)
5. run the `ddn supergraph build local` command with apt flags
### Screenshots or Screencast
![image](https://github.com/user-attachments/assets/a4c95c60-23cb-4a15-bbf9-4c884c1e71e0)

https://github.com/user-attachments/assets/f9749591-fbc4-4247-a36c-cca31b6548e3

### Keywords
BooleanExpression

**Comment by danieljharvey** [comment]
Is this

**Comment by danieljharvey** [comment]
This was never possible, but the JSONSchema suggested it was. When we noticed this, we changed this type so a `BooleanExpressionType` could not be passed in this place, hence this error.
