### ISSUE TITLE
GraphQL connector: No way to debug graphql connector errors 

### ISSUE THREAD

**Issue by soorajshankar** [hasura/graphql-engine#10416]
### What is the current behaviour?

Tried connecting to https://countries.trevorblades.com/, introspection is successful, but cant execute queries, no way to debug further as I don't have any further traces/logs to debug. 

Trace ID 6890b17e60ddf773afc81000b3117005

### What is the expected behaviour?

Upon error, the connector should emit some ways to help debug either in the form of container logs or in trace if applicable. 

### How to reproduce the issue?

1. Follow steps mentioned here https://github.com/hasura/ndc-graphql but use https://countries.trevorblades.com/

### Screenshots or Screencast
<img width="1448" alt="image" src="https://github.com/user-attachments/assets/9bf25f7a-e6ce-46aa-b490-30993b5e66cd">

<img width="1334" alt="image" src="https://github.com/user-attachments/assets/1d2f7c5e-a9a2-434d-ab3f-b232f75d6ec4">
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/b41113d5-af48-4602-9c30-634bb241ef74">

### Any possible solutions/workarounds you're aware of?

May be I need NDC query to debug further so that I can make direct NDC queries locally to try things, but as neither engine nor NDC log the NDC query, I don't have direct visibility to the NDC request. 

Extensive workaround is to proxy and log NDC queries but in real world this would be more difficult to our users.

**Comment by soorajshankar** [comment]
created a repo to recreate https://github.com/hasura/graphql_connector_test

**Comment by codedmart** [comment]
Fixed here: https://github.com/hasura/ndc-graphql/commit/a4cae1da2b122c00aa8e37b0b0be8655499ea35f
