### ISSUE TITLE
docs: typo in clickhouse connector getting started docs

### ISSUE THREAD

**Issue by imperfect-fourth** [hasura/graphql-engine#10413]
the env var in [docs](https://hasura.io/docs/3.0/getting-started/build/connect-to-data/connect-a-source#step-2-add-the-required-environment-variables) reads `CONNECTION_URL` instead of `CLICKHOUSE_URL`. 

![image](https://github.com/user-attachments/assets/4b12555b-a9eb-4292-bc2e-3684408e0a45)

The clickhouse connector expects `CLICKHOUSE_URL`

![image](https://github.com/user-attachments/assets/351995eb-4c37-4807-84a8-410ff12ced8a)

**Comment by seanparkross** [comment]
https://github.com/hasura/v3-docs/pull/480
