### ISSUE TITLE
CLI: While trying to add a model from an invalid connection name, I get a really bad error message

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#10419]
<img width="858" alt="Screenshot 2024-07-15 at 7 16 54 PM" src="https://github.com/user-attachments/assets/890068e5-aff8-4c1d-8a29-8ec00467ff72">

Ideally, I should just see: `"Carts" does not exist. Did you mean "carts"?`

**Comment by manasag** [comment]
This is now `WARNING NDC Collection not found for pattern Carts`. We are closing this issue at this moment.
