### ISSUE TITLE
v3-console: unable to collapse a trace span after expanding it

### ISSUE THREAD

**Issue by rohankmr414** [hasura/graphql-engine#10412]
### Component

v3-console

### What is the current behaviour?

While viewing a trace if we expand a span we cannot collapse it using the collapse button, the only way to collapse it is by expanding some other span.

### What is the expected behaviour?

The collapse button should fold the span.

### How to reproduce the issue?

1. Open a trace from the insights section.
2. Open a span.
3. Click on collapse button of the same span.

### Screenshots or Screencast

https://www.loom.com/share/7f8d1f441dbf4449ace0ed8ef593230f?sid=8fbddcd5-d947-4304-aeee-850c6f9f94a0

**Comment by julian-mayorga** [comment]
Thanks for the report @rohankmr414! Reproduced the issue and worked on a fix. Will let you know once it's live

**Comment by julian-mayorga** [comment]
The fix is deployed now. Thanks for the help @rohankmr414!
