### ISSUE TITLE
ddn-api: internal server error reported during create build

### ISSUE THREAD

**Issue by shukla2112** [hasura/graphql-engine#10426]
### Component
ddn-api

### What is the current behaviour?

while creating the build on cloud, internal-server error is reported

```shell
nikunjshukla@Nikunjs-MacBook-Pro ddn-bug % ddn supergraph build create \
  --supergraph supergraph.cloud.yaml \
  --subgraph-env-file my_subgraph:my_subgraph/.env.my_subgraph.cloud \
  --subgraph-env-file subgraph2:subgraph2/.env.subgraph2.cloud
7:50PM INF Using Project name "beloved-meerkat-9488" found in the context
7:50PM ERR input: there was an internal error while serving your request
```

The same thing works on the local

zip file is passed to @SandeepSamba 

### How to reproduce the issue?

1.
2.
3.

**Comment by SamirTalwar** [comment]
Can you please share reproduction steps on this ticket.

**Comment by SamirTalwar** [comment]
Closing this. If you can reproduce it, please feel free to open it again.
