### ISSUE TITLE
CLI: CLI commands take a really long time run!

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#10420]
Experience feels really slow.
There's a lag both before the print and after the print.

<img width="863" alt="Screenshot 2024-07-15 at 7 22 01 PM" src="https://github.com/user-attachments/assets/b3526b10-a054-4110-846a-9cff3202af3d">

To reproduce:
```
$ time ddn model add --name products --connector-link my_pg --subgraph my_subgraph/subgraph.yaml
        LOAD  Project
         ADD  Model for collection products, connector my_pg
    GENERATE    Model Products
    MODIFIED    (+6 more)
              WRITING changes

real	0m6.112s
user	0m0.663s
sys	0m0.093s
```

**Comment by coco98** [comment]
```
$ time ddn connector-link update my_pg --subgraph my_subgraph/subgraph.yaml --env-file my_subgraph/.env.my_subgraph.local --add-all-resources
```

This takes 6.3s

**Comment by manasag** [comment]
This is less than 3 seconds now. Further efforts are being tracked internally. Closing this issue.
