### ISSUE TITLE
MYSQL connector deployments are failing. 

### ISSUE THREAD

**Issue by ashwiniag** [hasura/graphql-engine#10425]
MYSQL connector deployments are failing with the following error.
<img width="992" alt="Screenshot 2024-07-15 at 7 54 57 PM" src="https://github.com/user-attachments/assets/74cf2e6c-7e09-4791-b316-1326e41621e7">

**Comment by gneeri** [comment]
@ashwiniag, is there any chance you have a Github PAT (access token) in the shell that you are using to run this? If so, please try in a shell where that is not defined and see if that resolves your issue.
