### ISSUE TITLE
Docs: Missing a subgraph set context?

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#10422]
Setting a context for subgraph allows me to not need the subgraph flag in subsequent commands. 
Perhaps the last thing on this page should be doing that: https://hasura.io/docs/3.0/getting-started/build/init-subgraph

Given that we're doing this for supergraph, might as well do this for subgraph!

**Comment by seanparkross** [comment]
Can do. Although we took the conscious decision to leave this in so that users grok the composability of the supergraph. Now that this is going to be the "advanced getting started" should we leave it in?

CC: @rikinsk who we had context with on this.

**Comment by rikinsk** [comment]
We set the supergraph to context [here](https://hasura.io/docs/3.0/getting-started/build/init-supergraph#step-4-set-the-supergraph-context) so having a section to set the subgraph as well seems logical. it educates the user that they can do so if nothing else
