### ISSUE TITLE
CLI: For my default subgraph, let's not add the mySubgraph prefix

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#10421]
For a project that I'm getting started with, it's quite inconvenient to see so many prefixes getting added.

What's also a little disconcerting is that there's a mix of camel casing and underscoring which makes the API look even worse.

**Comment by nullxone** [comment]
The default prefix is now removed, and can be customized through [the subgraph.yaml file](https://hasura.io/docs/3.0/supergraph-modeling/build-configs#subgraph-subgraphgeneratorconfig).

**Comment by coco98** [comment]
Woot! This is live?
