### ISSUE TITLE
LSP: missing validation for Relationship.mapping.source

### ISSUE THREAD

**Issue by aayshasura** [hasura/graphql-engine#10424]
### Component
c/v3-lsp

### What is the current behaviour?
![image](https://github.com/user-attachments/assets/ec709709-3754-4c37-bdde-d789121e98a2)
Relationship.mapping.source.value is allowed to be a valueExpression with no validation errors. But local engine build will fail with the error
![image](https://github.com/user-attachments/assets/e910a060-6072-4f45-9862-3b25a01ccce2)

### What is the expected behaviour?
There should be validation error if the user fills in relationship.mapping.source.value as it will result in error while running local build .

### How to reproduce the issue?

1. navigate to a ddn project with valid metadata (say to the file named Album.hml which tracks the dataConnector objectType album)
2. define a relationship to any other Model where relationship.mapping.source.value defined instead of relationship.mapping.source.fieldPath
![image](https://github.com/user-attachments/assets/c8d8100c-1071-4c68-b06f-878f7020d8b6)

3. attempt to do a local build using command `ddn supergraph build local`with apt flags.

### Screenshots or Screencast
![image](https://github.com/user-attachments/assets/8c2429d7-8b4e-4487-a320-905e992219bc)

### Any possible solutions/workarounds you're aware of?
add validation relationship to show error when user uses the field

### Keywords
relationship source mapping

**Comment by abhi40308** [comment]
fixed in v2.0.0
