### ISSUE TITLE
ndc-postgres: issue connecting to neon database (works locally but cloud deployment fails)

### ISSUE THREAD

**Issue by soorajshankar** [hasura/graphql-engine#10430]
### How to reproduce the issue?

1. Try creating a neon DB free tier
2. use pooled connection 
3. works locally, but on cloud query execution fails

Trace ID : db15394b7a4fc4c2125a16f01f23fb38

### Screenshots or Screencast

<img width="1448" alt="image" src="https://github.com/user-attachments/assets/03933d35-cea2-4ea4-9389-05b6616446e6">

**Comment by soupi** [comment]
I tried to reproduce the issue but could not. Is this still happening?
