### ISSUE TITLE
Docs: typo in description for the schema of `ResponseHeaders`

### ISSUE THREAD

**Issue by paritosh-08** [hasura/graphql-engine#10433]
### Component

V3-docs

There is a typo in https://hasura.io/docs/3.0/supergraph-modeling/data-connector-links#dataconnectorlink-responseheaders:
![image](https://github.com/user-attachments/assets/73f0f035-d5a4-40d4-b11b-d53a77b72ec9)

**Comment by abhi40308** [comment]
should be fixed on the json schema https://github.com/hasura/hasura-lsp-server/pull/582#issuecomment-2229981171
