### ISSUE TITLE
docs: typo on Add Authorization page

### ISSUE THREAD

**Issue by imperfect-fourth** [hasura/graphql-engine#10444]
https://hasura.io/docs/3.0/getting-started/build/add-permissions#what-did-this-do

in this para, it should be `typePermissions` instead of `modelPermissions`

![image](https://github.com/user-attachments/assets/536e64a9-f2df-4a81-8ea2-ee72db4e39e0)

**Comment by robertjdominguez** [comment]
@imperfect-fourth — I believe this should be `modelPermissions`.

- As we've stated in the introduction for the permission section, there's [this parallel](https://hasura.io/docs/3.0/supergraph-modeling/permissions#introduction) to draw from.
- And [the filter definition](https://hasura.io/docs/3.0/supergraph-modeling/permissions#modelpermissions-modelpermissions) by which we're applying to return only certain rows.

If we've misunderstood something, please let us know 🙏
