### ISSUE TITLE
Console: Commands relationships do not show up in visualization

### ISSUE THREAD

**Issue by rahulagarwal13** [hasura/graphql-engine#10451]
### What is the current behaviour?

Commands with relationships - visualization and ERD sections are blank
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/a90026d8-1c8b-417c-beb1-774655bca2ee">

### What is the expected behaviour?

Visualization and ERD should show up as for models

### How to reproduce the issue?

build https://github.com/hasura/ddn-sample-app and then go to commands 'to date string' for example

**Comment by soorajshankar** [comment]
Related to https://github.com/hasura/graphql-engine/issues/10452, and tracking there.
