### ISSUE TITLE
VScode: Extension looking into others yaml files

### ISSUE THREAD

**Issue by savanipoojan78** [hasura/graphql-engine#10458]
### What is the current behaviour?

![Screenshot 2024-07-16 at 5 42 45 PM](https://github.com/user-attachments/assets/d5cc18df-ba7e-4700-9e8e-d64d4a4014d1)

### What is the expected behaviour?

Why the hasura extension is looking at other yaml files where its not related to graphql

**Comment by abhi40308** [comment]
fixed in v2.0.0
