### ISSUE TITLE
Error running `compose.yaml` with `docker compose` 

### ISSUE THREAD

**Issue by SandeepSamba** [hasura/graphql-engine#10469]
### Component
CLI

### What is the current behaviour?
Running `docker compose -f compose.yaml up --build --watch` gives the following error:
```
[+] Running 2/0
 ✔ Container ddn-clockradio-otel-collector-1      Running                                   0.0s 
 ✔ Container ddn-clockradio-auth_hook-1           Running                                   0.0s 
 
Container ddn-clockradio-clockradio_primary-1  Recreate                                  0.0s 
Container ddn-clockradio-engine-1              Re...                                     0.0s
Error response from daemon: invalid IP address in add-host: ""
```

### What is the expected behaviour?
Running the compose file should work

### How to reproduce the issue?

1. Init a DDN project with `v1.0.0` by following the docs
2. Do `docker compose up --build --watch` with `docker` version `<=2.24`

### Please provide any traces or logs that could help here.
```
docker compose -f docker-compose.mongotestcloud.yaml up
[+] Running 1/0
 :heavy_check_mark: Network mongotestcloud_default                 Created                                                                      0.0s
 - Container mongotestcloud-app_mongotestcloud-1  Creating                                                                     0.0s
Error response from daemon: invalid IP address in add-host: ""
```

### Any possible solutions/workarounds you're aware of?
1. Update the version of `docker` and `docker compose` to the latest GA version.
2. In all `compose.yaml` files, modify the `extra_hosts` field to have the mapping with `:` instead of `=`. The following would work:
```yaml
extra_hosts:
      - local.hasura.dev:host-gateway
```

### Keywords
invalid IP address, docker compose

**Comment by Segfaultd** [comment]
Same error here, on a fresh setup.

**Comment by selwyn-mccracken** [comment]
Upgrading docker compose resolved this issue for me (via a docker desktop upgrade) - the [docs say that docker compose >= v2.27.1 is required]( https://hasura.io/docs/3.0/getting-started/build/prerequisites#step-3-install-docker-compose-v2271-or-greater )
