### ISSUE TITLE
Editting REST Endpoints returning a 404 not found page

### ISSUE THREAD

**Issue by TristenHarr** [hasura/graphql-engine#10484]
This issue was originally surfaced on Discord [here](https://discord.com/channels/407792526867693568/1143557219510665286/1265336251376996392). 

I have this running on Docker using this image hasura/graphql-engine:v2.41.0.cli-migrations-v3, then I open up http://localhost:9695/ and I go to API tab, right there I click REST and then later on any REST Endpoint I click the Edit button and it inmediatly loads the 404 page, the url that is loaded is http://localhost:9695/api/rest/edit//config (yes, with the double slash //), I tried to remove one of the duplicated slashes but it loaded me the page but with all fields empty.

These are the environmental variables I'm currently using for configurating hasura.

hasura:
    container_name: "hasura"
    image: hasura/graphql-engine:v2.41.0.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./hasura/migrations:/migrations
      - ./hasura/metadata:/metadata
      - ./hasura/seeds:/seeds
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL}"
      HASURA_GRAPHQL_MIGRATIONS_DIR: /migrations
      HASURA_GRAPHQL_METADATA_DIR: /metadata
      HASURA_GRAPHQL_SEEDS_DIR: /seeds
      HASURA_GRAPHQL_ACTION_BASE_URL: "${HASURA_GRAPHQL_ACTION_BASE_URL}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      # Local Development Configurations It is recommended to disable this in production
      # HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_LOGGING: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}"
      HASURA_GRAPHQL_JWT_SECRET: "${HASURA_GRAPHQL_JWT_SECRET}"

**Comment by Varun-Choudhary** [comment]
Hey @TristenHarr, thanks for raising the issue.
I tried reproducing the issue with image `hasura/graphql-engine:v2.41.0.cli-migrations-v3` on Hasura cli but it seems working for me. Can we ask the user for more details or a small video of their actions?

https://github.com/user-attachments/assets/4eec4762-770a-467f-994a-f425dc9f9df3

**Comment by TristenHarr** [comment]
Hello, it seems this issue occurs when the user tries to edit an endpoint with a / in the name. Please see this thread on Discord: https://discord.com/channels/407792526867693568/1204932258897854504/1284177462951153706

If the endpoint is named: `v1/some-specific-route` it will fail.

**Comment by Varun-Choudhary** [comment]
Hey @TristenHarr this issue is fixed for v2.43 the latest version. Also, cherry-picked v2.41 for the user.
