### ISSUE TITLE
Alphabetical ordering on event triggers list in the Hasura Console

### ISSUE THREAD

**Issue by TristenHarr** [hasura/graphql-engine#10483]
It would be nice if it was possible to have the event triggers list in the Hasura console be ordered alphabetically. This request was originally surfaced on Discord [here](https://discord.com/channels/407792526867693568/1143557219510665286/1265731638848000072).

**Comment by Varun-Choudhary** [comment]
Thanks @TristenHarr for raising this issue. We opened a [pull request](https://github.com/hasura/graphql-engine-mono/pull/11021) that will have a fix. 
We'll have Event triggers sorted in alphabetical order.

**Comment by Varun-Choudhary** [comment]
This is issue is fixed and live on `v2.43`
