### ISSUE TITLE
Scroll bar overlaps with last row on the browse data page

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1049]
Refer screenshot:
<img width="924" alt="screenshot 2018-11-16 at 4 56 42 pm" src="https://user-images.githubusercontent.com/131160/48654331-e03eba00-e9c0-11e8-96da-da33fb1c8606.png">

**Comment by WickedBrat1** [comment]
@coco98 It appears to be fixed.
Screenshot:
![screenshot from 2018-12-16 01-16-35](https://user-images.githubusercontent.com/45864807/50046854-6b01fa00-00d0-11e9-92d9-49a3d99536ea.png)
