### ISSUE TITLE
Sort Over JSONB Internal Props

### ISSUE THREAD

**Issue by bmacwoo** [hasura/graphql-engine#10509]
### Component

PostgreSQL JSONB

### Is your proposal related to a problem?

Requesting the ability to sort the results of a query based on the values of specific keys (see below) within a JSONB column in PostgreSQL.

### Describe the solution you'd like

Would like to use certain field operators such as: _gt, _like, _ilike, _lt 
Instead of:  _contains, _has_key

For example:

"_contains": {
"modelName": "Charger"
}

Looking to transform the filter object into:

{
"_contains": {
"modelName" : {
"_ilke": "%Charger%"
}
}

**Comment by manasag** [comment]
Hi @bmacwoo your request relates to #10138 and #10018 . We don't have a plan to solve this in Hasura V2. Hasura V3 has foundational concepts that enables us to bring this feature in a better manner. Please note that Hasura V3 is GA and available to try https://hasura.io/docs/3.0/getting-started/quickstart .
You can track the issue #10018 for updates, as this is part of the V3 [roadmap](https://github.com/orgs/hasura/projects/201).
