### ISSUE TITLE
CLI feedback when starting to use typescript

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#10502]
I felt like I added the postgres connector and it worked. This felt really good. So now I wanted to add typescript as well.

1. ❤️ I added the TS connector
2. **💔 I didn't know what to do next [suggestion: link me to TS connector docs after connector init]**
3. ❤️ did command add 
4. 💔 **went back to my ddn console. nothing had happened [suggestion: tell me to build supergraph again]**
5. ❤️ did supergraph build local
4. 💔 **went back to my ddn console. I see the command. Run it, get an error. I get lost on how to find logs**
5. 💔 **looked at traces. took me a long time to drill down to the right trace, and then in very tiny font saw some connection refused problem [suggestion: when there's an error suggest that I look at the trace. Furthermore, bring up the right error as a log-line at the very top level]**
6. ❤️ guessed that nodejs was not running 
7. ❤️ `npm i && npm run watch`
8. **💔  went back to my ddn console. Run the graphql query again, doesn't work. again do the drill down in trace thing and see the same error**
9. **💔 finally give up and then decide to go back and search for typescript docs. Google for hasura ddn typescript docs and land up on this page: https://hasura.io/docs/3.0/connectors/typescript/ which leads to this page > https://hasura.io/docs/3.0/business-logic/typescript which is wrong [suggestion: lets update the docs pages]**
10. ❤️ go back to getting started and then I find this https://hasura.io/docs/3.0/getting-started/build/add-business-logic?db=TypeScript
11. **💔 I figure out it's this CLI command, but I have no idea what this CLI command means.`ddn connector setenv --connector connector.yaml -- npm run start`. [suggestion: let's break this into 2 commands. also, why doesn't npm start just work?]** 
12. ❤️ finally it works

 cc: @nullxone @SandeepSamba

**Comment by nullxone** [comment]
Thanks for the feedback, have resolved this into more specific issues for our next release.
