### ISSUE TITLE
Custom Permissions UI doesn't support Sessions Variables in Data Tab Performance Mode

### ISSUE THREAD

**Issue by th3coop** [hasura/graphql-engine#10518]
### Version Information

Server Version: v2.42.0

### Environment

CE (I think?)

### What is the current behaviour?

Yes, I realize this is an experimental feature.  All good.

In *Data Tab Performance Mode* try to set a custom permission check for a table row using `_in` and a session variable. 
The value section does not allow a session variable and turns into a  list.  Manually writing the JSON causes the UI to break.

### What is the expected behaviour?

I can create the check in the UI

### How to reproduce the issue?

1. Enable `Data Tab Performance Mode`
2. Try to set a custom permission check for a table row using `_in` and a session variable.
5. value section does not allow a session variable and turns into a  list.  Manually writing the JSON causes the UI to break.

### Screenshots or Screencast

https://github.com/user-attachments/assets/fc4fe4f3-891a-4acf-a025-028c1336244c

*Working Screenshot.  Not In Performance Mode*
![image](https://github.com/user-attachments/assets/fe795273-adb4-4353-9c95-a1ee7da95cd0)

### Any possible solutions/workarounds you're aware of?

Editing the JSON by hand and saving.  This appears to work as expect.  I see the filter in the schema when I export it.

### Keywords

- session variables
- _in
- custom permissions

**Comment by manasag** [comment]
Hello, thanks for raising this issue. The team is currently working on address this.

**Comment by Varun-Choudhary** [comment]
Hi @th3coop,

Thank you for bringing this issue to our attention! It's now fixed, and the data tab performance feature supports session variables for custom permissions. This is available starting from v2.44.

We appreciate your patience! 😊

**Comment by th3coop** [comment]
Thanks for the heads up!
