### ISSUE TITLE
REST endpoints do not send request body to auth webhook

### ISSUE THREAD

**Issue by ProfXponent** [hasura/graphql-engine#10512]
### Version Information

Server Version: v2.37.0

### Environment

CE

### What is the current behaviour?

When authenticating REST endpoint calls hasura does not sent the REST request body.

This causes problems with platforms like `stripe` where you need to verify the `stripe` webhook request body with their `stripe-signature` header.

Using hasura in the POST auth webhook configuration just passes a `null` request body to the auth webhook making it impossible to verify that validity of the `stripe` webhook call.

### What is the expected behaviour?

That hasura would pass along the gql request body for the underlying REST endpoint as the documentation describes.

### How to reproduce the issue?

1. Create an auth webhook and run hasura in POST auth webhook mode
2. Create a REST endpoint in hasura making a authenticated gql query
3. Log the request body of the auth webhook call.
4. Verify the `headers` property and note the `null` value of the `request` property.

### Please provide any traces or logs that could help here.

```sh
web                             | [NEXT] body {
web                             | [NEXT]   headers: {
web                             | [NEXT]     Accept: '*/*; q=0.5, application/xml',
web                             | [NEXT]     'Accept-Encoding': 'gzip',
web                             | [NEXT]     'Cache-Control': 'no-cache',
web                             | [NEXT]     'Content-Length': '7159',
web                             | [NEXT]     'Content-Type': 'application/json; charset=utf-8',
web                             | [NEXT]     Host: 'graphql-engine.prof.dev.x.sh',
web                             | [NEXT]     'Stripe-Signature': 't=1724395973,v1=xxx',
web                             | [NEXT]     'User-Agent': 'Stripe/1.0 (+https://stripe.com/docs/webhooks)',
web                             | [NEXT]     'X-Forwarded-For': '192.168.65.1',
web                             | [NEXT]     'X-Forwarded-Host': 'graphql-engine.prof.dev.x.sh',
web                             | [NEXT]     'X-Forwarded-Port': '443',
web                             | [NEXT]     'X-Forwarded-Proto': 'https',
web                             | [NEXT]     'X-Forwarded-Server': '01b8639a93c8',
web                             | [NEXT]     'X-Real-Ip': '192.168.65.1',
web                             | [NEXT]     'x-request-id': 'c7764582-44fc-491c-b186-ab7f8c1986b1'
web                             | [NEXT]   },
web                             | [NEXT]   request: null
web                             | [NEXT] }
```

### Any possible solutions/workarounds you're aware of?

Writing a Go service to do this instead.

**Comment by rakeshkky** [comment]
Hi @ProfXponent, please check the following server flag or env var is configured.
- `--auth-hook-send-request-body`
- `HASURA_GRAPHQL_AUTH_HOOK_SEND_REQUEST_BODY`.

Configure them to `true`. 
Ref: https://hasura.io/docs/2.0/deployment/graphql-engine-flags/reference/#send-request-body-to-auth-hook

**Comment by ProfXponent** [comment]
> Hi @ProfXponent, please check the following server flag or env var is configured.
> 
> * `--auth-hook-send-request-body`
> * `HASURA_GRAPHQL_AUTH_HOOK_SEND_REQUEST_BODY`.
> 
> Configure them to `true`. Ref: https://hasura.io/docs/2.0/deployment/graphql-engine-flags/reference/#send-request-body-to-auth-hook

the example above has that flag enabled

**Comment by ProfXponent** [comment]
@rakeshkky thank you, I think this resolves the issue for me

**Comment by dereky565** [comment]
Hi @ProfXponent, was the `HASURA_GRAPHQL_AUTH_HOOK_SEND_REQUEST_BODY=true` the fix to your problem or did you have additional configurations? I have the same issue as you described wherein I am also expecting the underlying graphql to be present in the `request` but it is null.

**Comment by ProfXponent** [comment]
> Hi @ProfXponent, was the `HASURA_GRAPHQL_AUTH_HOOK_SEND_REQUEST_BODY=true` the fix to your problem or did you have additional configurations? I have the same issue as you described wherein I am also expecting the underlying graphql to be present in the `request` but it is null.

yeah it works, but only in post web hook mode

```yaml
HASURA_GRAPHQL_AUTH_HOOK_MODE: "POST"
HASURA_GRAPHQL_AUTH_HOOK_SEND_REQUEST_BODY: "true"
```

```shell
graphql-engine-hooks  | 2024/12/13 12:21:26 Request Body as JSON: map[headers:map[Accept:*/* Accept-Encoding:gzip, deflate, br, zstd Accept-Language:en-US,en;q=0.5 Content-Length:126 Content-Type:application/json Cookie: example_cookie Dnt:1 Host:web.public.example.sh Origin:https://web.public.example.sh Priority:u=4 Referer:https://web.public.example.sh/ Sec-Fetch-Dest:empty Sec-Fetch-Mode:cors Sec-Fetch-Site:same-origin Sec-Gpc:1 Te:trailers User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0 X-Forwarded-For:172.22.0.1 X-Forwarded-Host:web.public.example.sh X-Forwarded-Port:443 X-Forwarded-Prefix:/api X-Forwarded-Proto:https X-Forwarded-Server:ccd7cea09300 X-Real-Ip:172.22.0.1 x-request-id:977e73ae-16c7-4387-abba-1ecfea46ad5b] request:map[query:
graphql-engine-hooks  | query UserQuery {
graphql-engine-hooks  |   app {
graphql-engine-hooks  |     users {
graphql-engine-hooks  |       created_at
graphql-engine-hooks  |       id
graphql-engine-hooks  |       subscription_tier_id
graphql-engine-hooks  |     }
graphql-engine-hooks  |   }
graphql-engine-hooks  | }
graphql-engine-hooks  | ]]
```

**Comment by dereky565** [comment]
I see, then your RESTified endpoint's underlying GraphQL is then visible in that request field? Just clarifying because I still receive null whenever it's a RESTified endpoint request but just using a GraphQL request shows the query in the request field.

**Comment by ProfXponent** [comment]
@dereky565 sorry about the confusion

request body REST endpoints using auth hook is still `null`

For GraphQL queries the request body is populated as you would expect

@rakeshkky can we reopen this issue as the original topic I discussed is still causing confusion?

**Comment by dereky565** [comment]
Hi @ProfXponent, thank you for the reply. I think I may have misunderstood step 2 in how to reproduce the issue which is: "Create a REST endpoint in hasura making a authenticated gql query". I understood this as RESTified Hasura Endpoint requests.

So now I am wondering if this is actually the expected behavior for Auth Webhooks in POST mode when it comes to the request body, @rakeshkky? Thanks!

**Comment by dereky565** [comment]
Hi, I got an answer in my thread here: https://github.com/hasura/graphql-engine/discussions/10623#discussioncomment-11625598. Thanks, everyone!
