### ISSUE TITLE
PostGIS topology operator

### ISSUE THREAD

**Issue by arszp10** [hasura/graphql-engine#1051]
for GIS user important topology operator
list operator follow
http://postgis.net/workshops/postgis-intro/spatial_relationships.html

for example
client.js query
```js
query inter($bbox: geojson){
  my_table(where: {geom: {bbox: $bbox}}){
    id
  }
}
```

table in postgres
```sql
create table my_table (
  id serial primary key,
  geom geometry('POINT', 32635)
)
```

sql
```sql
select id
from my_table
where geom && 'geommetry from varible $bbox'
```

**Comment by asindl** [comment]
GIS topology operators would be a very important feature for me as well. Are there any plans to include those in Hasura?
