### ISSUE TITLE
v3 docker compose expects git directory

### ISSUE THREAD

**Issue by ggadwa** [hasura/graphql-engine#10529]
### Component

Graphql Engine

### What is the current behaviour?

Attempting to install v3 engine through docker compose.  Note this is on a windows machine, through desktop docker / WSL 2.  It fails attempting to do some git work; first attempting to copy a .git directory, and then later issuing a git command.

### What is the expected behaviour?

That it would install v3 on my local docker desktop.

### How to reproduce the issue?

Setup:

Windows, docker desktop / WSL 2.
Pull the hasura / graphql-engine (this is the complete repository, with v3 as a sub directory)
Rust already installed (1.81)

Run:

Go to the repository /v3 directory
set the required variables (as described in the v3 readme)
docker compose up

What is happening is the docker script attempts to copy a .git directory which does not exist -- remember that the v3 is a sub directory of the repository so no .git

There might be a v3 stand alone repository I'm missing, or this might be an artifact or that directory being moved, etc.  Doing work with the .git is the current problem.

### Screenshots or Screencast

n/a

### Please provide any traces or logs that could help here.

"docker compose up" within the v3 directory fails with "COPY .git ./.git".

### Any possible solutions/workarounds you're aware of?

Sort of -- you can create a fake .git directory to get by this, but then it fails when it calls git to do a "git rev-parse HEAD" as it's not a real git directory.

### Keywords

v3 docker .git

**Comment by ggadwa** [comment]
Edit, missing info: This is an attempt at a Postgres installation as per the v3 readme.

**Comment by ecthiender** [comment]
@ggadwa thanks for the report. We'll look into this.

In the meantime, you can use `ghcr.io/hasura/v3-engine` image directly in the docker-compose definition (replacing the build definition).

**Comment by danieljharvey** [comment]
Hello! The Dockerfile in question is only used for local development now, so we don't need to involve git at all. Have updated it in [this commit](https://github.com/hasura/graphql-engine/commit/3e2a0ed69022cd337f4933a5dc0fb06ecead9078), so that `.git` is no longer required.

Hopefully this solves your problem, feel free to reopen this if you are still having issues.
