### ISSUE TITLE
v3 engine-1 fails with 400 / Unexpected / OCI runtime

### ISSUE THREAD

**Issue by ggadwa** [hasura/graphql-engine#10539]
### Component

engine-1

### What is the current behaviour?

With the docker compose, all the components compile and install and are running except:

dev-setup-1 : exited -- you can run this and it exits without error, so if it was meant to run once then it worked right
engine-1: error -- "(HTTP code 400) unexpected - failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./bin/engine": stat ./bin/engine: no such file or directory: unknown"

### What is the expected behaviour?

That I have a functioning h3 environment in docker.

### How to reproduce the issue?

Setup:

Windows, docker desktop / WSL 2.
Pull the hasura / graphql-engine (this is the complete repository, with v3 as a sub directory)
Rust already installed (1.81)

Run:

Go to the repository /v3 directory
set the required variables (as described in the v3 readme)
note I am following the postgresql setup docs
docker compose up

Note:

For some reason the high external port set for postgres (64001:5432) flakes on my box; as I don't need to reach it externally I just removed the 64001.  As it's external I doubt this is the cause but need to note the single change I made to the compose yaml.

### Screenshots or Screencast

n/a

### Please provide any traces or logs that could help here.

Docker desktop and the console returns this notification:

(HTTP code 400) unexpected - failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./bin/engine": stat ./bin/engine: no such file or directory: unknown

There seems to be no other logs of any use; running it in a console just shows everything is ok and started messages until this ultimately fails.  More than willing to help out with a debug version!

### Any possible solutions/workarounds you're aware of?

None that I know of.

### Keywords

v3 OCI engine-1

**Comment by Odex64** [comment]
Same error here.

**Comment by ggadwa** [comment]
Tried this again with the newest code; I see you have updated and fixed the bad port (on windows) in the docker compose so thank you.  Still same error, though, so this is an outstanding ticket for any of us trying to run v3 locally.

Want to note there's a problem with pulling the newest code, it's in test folders so it's not a big deal but I suspect there's errant spaces in your paths, these files fail to pull:

error: invalid path 'v3/crates/metadata-resolve/tests/failing/aggregate_boolean_expressions/object/count_distinct_bool_exp_missing /metadata.json'
error: invalid path 'v3/crates/metadata-resolve/tests/failing/aggregate_boolean_expressions/object/count_distinct_bool_exp_missing /resolve_error.snap'
error: invalid path 'v3/crates/metadata-resolve/tests/failing/aggregate_boolean_expressions/scalar/count_distinct_bool_exp_missing /metadata.json'
error: invalid path 'v3/crates/metadata-resolve/tests/failing/aggregate_boolean_expressions/scalar/count_distinct_bool_exp_missing /resolve_error.snap'

Notice the spaces after "count_distinct_bool_exp_missing".

**Comment by codedmart** [comment]
@ggadwa is this still an issue for you. We have continued to make improvements.

**Comment by ggadwa** [comment]
> @ggadwa is this still an issue for you. We have continued to make improvements.

Yes, same problem.  Both engine-1 not running and the problem with the repository above.  It's possible that the problem with pulling the repository means I'm not getting updates, though, and possibly a fix has come in that I can't receive.

**Comment by danieljharvey** [comment]
@ggadwa Good spot on the folder paths - these are removed now as per https://github.com/hasura/graphql-engine/commit/9863eceada006aa2417aec08a1aece8c7c8750af

Let me know if this fixes your issue!

**Comment by ggadwa** [comment]
> @ggadwa Good spot on the folder paths - these are removed now as per [9863ece](https://github.com/hasura/graphql-engine/commit/9863eceada006aa2417aec08a1aece8c7c8750af)
> 
> Let me know if this fixes your issue!

@danieljharvey It fixed those paths, but now there's a couple new ones that fail the pull:

error: invalid path 'v3/crates/metadata-resolve/tests/passing/command_permissions/predicate_args_can_be_preset /metadata.json'
error: invalid path 'v3/crates/metadata-resolve/tests/passing/command_permissions/predicate_args_can_be_preset /resolved.snap'

The space is after "_be_preset" (it's hard to see actually, I originally have to cursor over it to see!)

**Comment by danieljharvey** [comment]
Oh no! OK - I think I've found them all now, pull request incoming!

**Comment by ggadwa** [comment]
@danieljharvey Yes, you got them all, I can now successfully do a pull.

It's still not starting, but the error has changed.

engine-1              | Error while starting up the engine: failed to build engine state - unexpected keys: logical_operators_in_scalar_boolean_expressions, require_unique_model_graphql_names, allow_boolean_expression_fields_without_graphql, require_nested_array_filtering_capability, disallow_scalar_type_names_conflicting_with_inbuilt_types, propagate_boolean_expression_deprecation_status, require_unique_command_graphql_names, allow_partial_supergraph, json_session_variables, disallow_array_field_compared_with_scalar_boolean_type; expecting: require_graphql_config, require_valid_ndc_v01_version, bypass_relation_comparisons_ndc_capability at path $.flags

A couple notes:

The readme has changed, but I'm still setting these before docker compose up (within v3 directory):

set METADATA_PATH=crates/engine/tests/schema.json
set AUTHN_CONFIG_PATH=static/auth/auth_config.json

Note that schema.json is a blank folder (this was from the original readme.). I also tried pointing METADAT_PATH at a metadata json I used in v2, assuming the format was the same (example below with stuff cut out, I tested this and it works with v2.). It is very possible this is a bad idea on my part but I was trying things.
 
```
{
    "type": "replace_metadata",
    "version": 2,
    "args": {
        "resource_version": 138,
        "metadata": {
            "version": 3,
            "sources": [
                           ….
                    ],
                    "configuration": {
                        "connection_info": {
                            ....
                        }
                    },
                    "customization": {
                        .....
                    }
                }
            ]
        }
    }
}
```

I'd like to be able to start it with no metadata and then just send in metadata json to rest calls, but I'm just trying to get it to start at this point.

This might be that there is some information missing in the readme and I don't have some configuration set, or I just missed something, but I have no idea what that is.

**Comment by danieljharvey** [comment]
What happens if you run `docker compose up --build` in the `v3-engine` folder without setting any env vars etc? It _should_ start everything with a sample project and DB.

**Comment by ggadwa** [comment]
That's it -- you've fixed it but I forgot to rebuild the code.  It runs, I can play around in the web interface.  I'm going to see if the metadata rest calls still exist and play with those.  This ticket can be closed as completed.
