### ISSUE TITLE
relationships with two fields

### ISSUE THREAD

**Issue by Maxpain177** [hasura/graphql-engine#1053]
We have three tables:
`matches (id)`
`match_rounds (id, match_id)` (field `id` is non unique)
`match_round_events (round_id, match_id)`

How to create a relationship (join) for `events` in `match_rounds`?
Like this:
```sql
JOIN match_round_events match_round_events.match_id = match_rounds.match_id AND
match_round_events.round_id = match_rounds.id
```

**Comment by dsandip** [comment]
@Maxpain177 The console currently doesn't let you do this and we're tracking the issue here #506. @rakeshkky @0x777 is there a workaround available using the API?

**Comment by dsandip** [comment]
@Maxpain177 you can create the relationship manually using the API (without having to create a Fkey constraint): https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/relationship.html#manual-configuration

This is how your API payload may look like:
```JSON
{
    "type": "create_array_relationship",
    "args": {
        "table": "match_rounds",
        "name": "round_events",
        "using": {
            "manual_configuration" : {
                "remote_table" : "match_round_events",
                "column_mapping" : {
                    "id" : "round_id",
                    "match_id":"match_id"
                }
            }
        }
    }
}
```

You should then be able to run queries such as:
```graphql
{
  match_rounds {
    id
    match_id
    round_events {
      event_name
    }
  }
}
```

**Comment by Maxpain177** [comment]
Sorry, my mistake.
