### ISSUE TITLE
Error trying to introspect hasura/openapi

### ISSUE THREAD

**Issue by beddows** [hasura/graphql-engine#10530]
### Component

c/v3-cli, c/v3-ndc-openapi

### What is the current behaviour?
When running the following:
<details><summary>ddn supergraph init .</summary>
<p>
6:45PM INF Created file "hasura.yaml"<br>
6:45PM INF Created file "supergraph.yaml"<br>
6:45PM INF Created file ".env"<br>
6:45PM INF Created file "compose.yaml"<br>
6:45PM INF Created directory "engine"<br>
6:45PM INF Created file "engine/.env.engine"<br>
6:45PM INF Created file "otel-collector-config.yaml"<br>
6:45PM INF Created file ".gitignore"<br>
6:45PM INF Created file ".gitattributes"<br>
6:45PM INF Created directory ".vscode"<br>
6:45PM INF Created file ".vscode/launch.json"<br>
6:45PM INF Created file ".vscode/extensions.json"<br>
6:45PM INF Created file ".vscode/tasks.json"<br>
6:45PM INF Created directory ".devcontainer"<br>
6:45PM INF Created file ".devcontainer/devcontainer.json"<br>
6:45PM INF Created directory "globals"<br>
6:45PM INF Created file "globals/subgraph.yaml"<br>
6:45PM INF Created file "globals/auth-config.hml"<br>
6:45PM INF Created file "globals/compatibility-config.hml"<br>
6:45PM INF Created file "globals/graphql-config.hml"<br>
6:45PM INF Created directory "engine/build"<br>
6:45PM INF Created file "engine/build/auth_config.json"<br>
6:45PM INF Created file "engine/build/open_dd.json"<br>
6:45PM INF Created file "engine/build/metadata.json"<br>
6:45PM INF Created directory "app"<br>
6:45PM INF Created file "app/subgraph.yaml"<br>
6:45PM INF Created file ".hasura/context.yaml"<br>
6:45PM INF Key "subgraph" set to "app/subgraph.yaml" in the context.<br>
6:45PM INF Key "supergraph" set to "supergraph.yaml" in the context.<br>
6:45PM INF Key "localEnvFile" set to ".env" in the context.<br>
6:45PM INF Supergraph initialized in directory "." successfully<br>
6:45PM INF A Subgraph "globals" was created with the supergraph-level metadata objects.<br>
6:45PM INF A Subgraph "app" was created to get you started with building your API.<br>
HINT Add a Connector to the Subgraph: ddn connector init -i<br>
</p>
</details> 

<details><summary>ddn connector init my_connector -i</summary>
<p>
6:45PM INF Using Subgraph "app/subgraph.yaml" found in context.<br>
? Hub Connector hasura/openapi<br>
? Port 4502<br>
Provide the env vars for the connector. Press enter to use the default value or if no default is available, then nil value<br>
? NDC_OAS_DOCUMENT_URI (The URI of OAS Document. If not provided, the connector will look for<br>  `/etc/connector/swagger.json` by default) ./trilium.yaml<br>
? NDC_OAS_BASE_URL (Base url of the API) http://localhost:8080/etapi<br>
? NDC_OAS_LAMBDA_PRETTY_LOGS (Print logs in a human readable format instead of JSON) true<br>
? NDC_OAS_FILE_OVERWRITE (Overwrite previously generated functions.ts file and api.ts file) false<br>
7:05PM INF Using localEnvFile ".env" found in context.<br>
7:05PM INF Created directory "app/connector/my_connector"<br>
7:05PM INF Created file "app/connector/my_connector/connector.yaml"<br>
7:05PM INF Created file "app/connector/my_connector/compose.yaml"<br>
7:05PM INF Created file "app/connector/my_connector/.ddnignore"<br>
7:05PM INF Created file "app/metadata/my_connector.hml"<br>
7:05PM INF Connector URLs added to env file ".env" successfully<br>
7:05PM INF Connector "my_connector" initialized in Subgraph "app" successfully<br>
HINT Introspect data source: ddn connector introspect my_connector<br>
</p>
</details> 

<details><summary>ERROR: ddn connector introspect my_connector</summary>
<p>

7:06PM INF Using Subgraph "app/subgraph.yaml" found in context.
7:06PM INF Using localEnvFile ".env" found in context.
[23:06:50.421] FATAL (1): Cannot create property 'info' on string 'error while fetching data from URL ""'
    err: {
      "type": "TypeError",
      "message": "Cannot create property 'info' on string 'error while fetching data from URL \"\"'",
      "stack":
          TypeError: Cannot create property 'info' on string 'error while fetching data from URL ""'
              at /app/node_modules/swagger-typescript-api/src/swagger-schema-resolver.js:71:19
              at new Promise (<anonymous>)
              at SwaggerSchemaResolver.convertSwaggerObject (/app/node_modules/swagger-typescript-api/src/swagger-schema-resolver.js:69:12)
              at SwaggerSchemaResolver.create (/app/node_modules/swagger-typescript-api/src/swagger-schema-resolver.js:59:23)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async CodeGenProcess.start (/app/node_modules/swagger-typescript-api/src/code-gen-process.js:86:21)
              at async Object.generateApi (/app/node_modules/swagger-typescript-api/src/index.js:21:12)
              at async Object.generateApiTsCode (/app/dist/app/generator/api-ts-generator.js:46:34)
              at async Object.generateCode (/app/dist/app/generator/index.js:35:23)
              at async Object.runApp (/app/dist/app/index.js:44:27)
    }
Cannot create property 'info' on string 'error while fetching data from URL ""'
7:06PM ERR introspect failed with error: exit status 1
</p>
</details> 

The image ghcr.io/hasura/ndc-open-api-lambda:v0.1.2 is in Docker.

### What is the expected behaviour?

Expected the introspection to complete.

### How to reproduce the issue?

I've tried this with several validated OpenAPI specs, same error. Using macOS Sonoma 14.5, Docker Desktop 4.34.0.

**Comment by m-Bilal** [comment]
@beddows Hi! Thank you for reporting this. Can you please point  me to any OpenAPI Document URL that gives you this error?

**Comment by beddows** [comment]
@m-Bilal  Apologies, I should have attached it. Please rename to yaml.

[trilum.txt](https://github.com/user-attachments/files/16908043/trilum.txt)

**Comment by m-Bilal** [comment]
Found the issue! It's here:

> NDC_OAS_DOCUMENT_URI (The URI of OAS Document. If not provided, the connector will look for
`/etc/connector/swagger.json` by default) ./trilium.yaml

What's happening here, is that this file (`trilium.yaml`) is not being mounted to the container as `swagger.json`. If you want the connector to the OpenAPI Spec from a file, it must be named `swagger.json`, and it must be mounted to `/etc/connector/`. Otherwise, the connector will expect a URL from which it can fetch the OpenAPI Spec.

**Comment by m-Bilal** [comment]
@beddows  let me know please if the explanation helps with the fix

**Comment by beddows** [comment]
@m-Bilal Just seeing this now, will try it out. Thanks!
