### ISSUE TITLE
Monitoring Client and Role are reversed

### ISSUE THREAD

**Issue by James-Firth** [hasura/graphql-engine#10541]
### Version Information

Server Version: [v2.43.0-cloud.1](https://cloud.hasura.io/project/ff5973b8-dc28-43e8-82eb-c9fbee78dfed/console/)
CLI Version (for CLI related issue):

### Environment

Cloud

### What is the current behaviour?

When viewing the Operations page under Monitoring each request is listed as a row in a table which includes columns `Client Name` and `Role`.
Clicking the 🔍 to "Inspect" also shows `Client Name` and `Role` but the values are reversed (incorrectly) compared to the table view.

### What is the expected behaviour?

That the `Client Name` and `Role` data in the "Inspect" modal would be correct

### How to reproduce the issue?

1. Navigate to Monitoring
2. Click Operations
3. Take note of the Role and Client Name values
4. Click the 🔍 on a row to open a detailed modal
5. Observe that the values are flipped in detailed modal

### Screenshots or Screencast
![image](https://github.com/user-attachments/assets/299c3dff-799d-4856-8400-06d029a040d8)

### Keywords

monitoring client name role flipped reversed operations

**Comment by manasag** [comment]
Hi @James-Firth, thanks for opening the issue. This currently is not prioritised and will be in our backlog.

**Comment by Varun-Choudhary** [comment]
Hey @James-Firth , this issue is fixed and the fix will be reflected in the next release.

**Comment by James-Firth** [comment]
Awesome thanks for the quick turnaround @Varun-Choudhary ! 
Should avoid confusion, however brief, for anyone looking at that view
