### ISSUE TITLE
Live reload of metadata

### ISSUE THREAD

**Issue by alejandrojnm** [hasura/graphql-engine#1055]
It would be interesting, that Hasura detected the changes in the db and made a reload of the metadata automatically, I put this example because in my case I use django to manage the system and maintain the models of the db and when I do a makemigration and a migrate, It would be great if Hasura automatically refreshed the changes, I have not looked at the code, but I guess there is a way to know if something has changed in the DB

**Comment by 0x777** [comment]
Apart from polling, the only other way to get ddl changes on the database is through an [event trigger](https://www.postgresql.org/docs/current/sql-createeventtrigger.html). However they are only allowed for superusers and generally preferred in advanced usecases. 

graphql-engine has an API to refresh the metadata, POST to `/v1/query` endpoint as an admin with 
```json
{
  "type" : "reload_metadata",
  "args" : "{}"
}
```
If you can add this step to your workflow you can get the similar effect of graphql-engine detecting the changes from the database.
