### ISSUE TITLE
Hasura Console Permissions + Composite Keys | TypeError: Cannot read properties of null (reading 'schema')

### ISSUE THREAD

**Issue by nyoung697** [hasura/graphql-engine#10576]
### Version Information

Server Version: v2.42.0 (tested on 2.40 as well)
CLI Version (for CLI related issue): v2.42.0

### Environment

All

### What is the current behaviour?

When using a composite foreign key, the permission builder throws an error: **TypeError: Cannot read properties of null (reading 'schema')**

For example, I have the tables: `project`, `scene`, `resource`, and `scene_resource`.  
- `scene` and `resource` both reference project with a FK. 
- `scene_resource` references all the tables. 
- On `scene_resource` I have composite FKs of:
  - **( project_id, resource_id ) → resource . ( project_id, id )**
  - **( project_id, scene_id ) → scene . ( project_id, id )**.
- I also have a FK of **project_id → project . id**

After adding the Hasura relationships, in the permission builder for `scene_resource`, I can select `project` no problem, but if I select either `scene` or `resource`, the console throws the error.

<img width="1462" alt="Screenshot 2024-10-26 at 9 31 10 AM" src="https://github.com/user-attachments/assets/aa05ca19-e444-47f8-9cd4-351b3d3dad0c">

### What is the expected behaviour?

That it doesn't throw an error and I can build a permission through the console...

### How to reproduce the issue?

https://github.com/nyoung697/hasura-bug

### Screenshots or Screencast

https://github.com/user-attachments/assets/e735ee84-5b77-4aa5-b917-8fc2f0aca02b

### Please provide any traces or logs that could help here.

<img width="567" alt="Screenshot 2024-10-26 at 9 37 10 AM" src="https://github.com/user-attachments/assets/189001a6-b94d-402e-abf2-8a49b68b81a4">
<img width="514" alt="Screenshot 2024-10-26 at 9 37 22 AM" src="https://github.com/user-attachments/assets/cf9bceb6-3d5d-4536-97d2-80633ee8cee0">

### Any possible solutions/workarounds you're aware of?

I am able to create the permissions by manually modifying the .yaml file directly, then calling `hasura deploy`

### Keywords

hasura console, TypeError: Cannot read properties of null (reading 'schema'), composite keys

**Comment by Varun-Choudhary** [comment]
Hey @nyoung697, we have fixed this issue. The fix will be available from v2.45.
You can now create permissions that involve composite foreign keys in your relationship definitions. Let me know if you run into any issues!
