### ISSUE TITLE
Permissions for remote relationships are not functioning.

### ISSUE THREAD

**Issue by kimyvgy** [hasura/graphql-engine#10572]
### Version Information

Server Version: v2.33.0, v2.38.1, v2.41.0, v2.44.0
CLI Version (for CLI related issue): v2.44.0

### Environment

OSS, PostgreSQL

### What is the current behaviour?

[Permissions for remote relationships](https://hasura.io/docs/2.0/auth/authorization/permissions/row-level-permissions/#remote-relationships-in-permission) are not functioning. Same issue with #8679.

> If I create two databases with tables and create a cross DB relationship on one of these tables, it is not available as an option when building custom permissions in the console UI.

### What is the expected behaviour?

> I should be able to use this relationship in custom permissions as I would any other relationship

### How to reproduce the issue?

1. Create an Hasura instance with 2 DBs and a table in each
2. Create a relationship across these tables
3. Observe your inability to use that relationship in a permission

### Keywords

permissions, relationships, cross database, multi database

**Comment by Varun-Choudhary** [comment]
Hi @kimyvgy,

We do support permissions for cross-database relationships! To enable this in the console, please turn on the new "Data Tab Performance Mode" in the settings tab. This should allow you to create permissions for cross-database relationships as needed.

I’m closing this issue for now, but please feel free to reopen it if you encounter any further issues. 😊



https://github.com/user-attachments/assets/3efd2d9a-908f-4f07-bb96-2ac5be107939
