### ISSUE TITLE
Why release 2.44.0 is missing from the GitHub release page?

### ISSUE THREAD

**Issue by stephane-klein** [hasura/graphql-engine#10580]
Hello,

I see that Hasura `graphql-engine` version 2.44.0 has been published on :

- https://hasura.io/changelog/community-edition/v2.44.0
- and Docker Hub : https://hub.docker.com/layers/hasura/graphql-engine/v2.44.0/images/sha256-81c38723690396a424230b132c9b166c9da3b88f4f94b2835bc5a20e14723aab

But this version is missing on https://github.com/hasura/graphql-engine/releases

Is this an oversight? Or is there a particular reason?

Best regards,
Stéphane

**Comment by manasag** [comment]
Hi, thanks for raising this. We fixed the automation issue and this v2.44.0 has been released on Github https://github.com/hasura/graphql-engine/releases/tag/v2.44.0
