### ISSUE TITLE
Lambda connector runs if the `functions.ts` file is invalid syntactically, but serves empty schema

### ISSUE THREAD

**Issue by SandeepSamba** [hasura/graphql-engine#10590]
With the following `functions.ts` , the connector starts up, even though it is syntactically invalid (two functions named `hello` with the same signature)
```typescript
/**
 * @readonly Exposes the function as an NDC function (the function should only query data without making modifications)
 */
export function hello(name?: string) {
  return `HELLO ${name ?? "world"}`;
}

/**
 * @readonly Exposes the function as an NDC function (the function should only query data without making modifications)
 */
export function hello(name?: string) {
  return {greeting: name};
}
```

I would expect the connector to crash if it encounters a project where TS encounters errors on compilation. This behavior is misleading as currently with this `functions.ts` , `ddn connector introspect <connector-name>`  goes through without error but gets empty `schema` and updates the DataConnectorLink with it (removing my old schema, if any)

**Comment by daniel-chambers** [comment]
This was fixed in the [v1.10.0 release](https://github.com/hasura/ndc-nodejs-lambda/releases/tag/v1.10.0).
