### ISSUE TITLE
Feedback for “Starting from scratch”

### ISSUE THREAD

**Issue by arilishu** [hasura/graphql-engine#10597]
I am following all the steps, no errors, and then I get this:
<img width="1302" alt="Screenshot 2024-11-13 at 2 36 40 PM" src="https://github.com/user-attachments/assets/66ab4996-663c-44d5-a639-e6ad7aa9f5d4">

**Comment by robertjdominguez** [comment]
In your screenshot, I notice you don't have `PromptQL: http://localhost:3282` listed as connected in the top-left corner by your Engine address. When you [started from scratch](https://promptql.hasura.io/docs/guides/start-scratch), did you pass the `--with-promptql` flag?

Based on the error and the lack of this address present on the console, I'd say the PromptQL service isn't running.
