### ISSUE TITLE
Feedback for “Connecting Structured Data”

### ISSUE THREAD

**Issue by autodidactable** [hasura/graphql-engine#10603]
I ran into issues with the container (it went into a perpetual restarting state )when I changed the image to `pgvector/pgvector:pg16`. I had to look into container logs to see a compatibility error and I had to change it to `pgvector/pgvector:pg17`.

**Comment by robertjdominguez** [comment]
@autodidactable — thanks for this!

The latest version of the CLI (`v2.13.0`) ships with `image: pgvector/pgvector:pg17` when initializing a local PostgreSQL DB with your connector. I'll remove the note from the page 👍
