### ISSUE TITLE
Data Tab Performance Mode permission loads very slow

### ISSUE THREAD

**Issue by dohomi** [hasura/graphql-engine#10612]
### Version Information

Server Version:
CLI Version (for CLI related issue): 2.44.0-ce

### Environment

OSS / Nhost
 
### What is the current behaviour?

The feature "Data Tab Performance Mode" takes minutes to load, the JSON builder runs in a endless queue of calling `getTableColumns`

### What is the expected behaviour?

The JSON builder should load immediately like in the previous version.

### How to reproduce the issue?

Navigate to permission of a table and hit any permission tab.

### Screenshots or Screencast

[Screen Recording 2024-11-27 at 10.40.04.webm](https://github.com/user-attachments/assets/80875dd1-84c7-41df-af70-102e019c4fbe)

### Please provide any traces or logs that could help here.

see video

### Any possible solutions/workarounds you're aware of?

Dont activate the performance mode

### Keywords

Data Tab Performance Mode

**Comment by seanparkross** [comment]
Thanks for this @dohomi 
Investigating...

**Comment by Varun-Choudhary** [comment]
Hi @dohomi,

Thank you for bringing this to our attention! We’ve tried to reproduce the issue on our end but haven’t been able to so far.

It would be really helpful if you could share more details with us, such as the exact steps to reproduce, your database schema or metadata, and a copy of the JSON permissions you’ve set in the permissions input.

**Comment by dohomi** [comment]
Hi @Varun-Choudhary 
After enabling the performance tab mode every single click on any permission tabs takes long time to load based on the video. the schema is very large as the project has over 60 tables and the permission JSON looks like this, but it actually doesnt matter as all my permissions take long time to load:

```json
{"document":{"_and":[{"club":{"_and":[{"payments":{"_or":[{"active":{"_eq":true}},{"valid_until":{"_gte":"now()"}}]}},{"members":{"_and":[{"user_id":{"_eq":"X-Hasura-User-Id"}},{"member_permissions":{"role":{"_in":["CLUB_ADMIN"]}}}]}}]}}]}}
```

**Comment by julian-mayorga** [comment]
Thanks for the report and help @dohomi! If possible, could you share with us a bit more info about your setup? Asking because the error you're seeing does not happen on all projects.

A DB schema (with a tool like `pg_dump`) and Hasura metadata (with `hasura metadata export `) would help us a lot

**Comment by dohomi** [comment]
hi there, 

this is the metadata export 
[hasura_metadata_2024_12_02_09_41_31_485.json](https://github.com/user-attachments/files/17971444/hasura_metadata_2024_12_02_09_41_31_485.json)

**Comment by julian-mayorga** [comment]
Thank you so much @dohomi! Will get back to you as soon as we can

**Comment by julian-mayorga** [comment]
https://github.com/user-attachments/assets/06ca9153-3c8c-478e-aa58-a0ccda988d77

Hi again @dohomi and thanks so much for your patience!

I reproduced your scenario, but I don't see an endless queue of calling `getTableColumns `. We do recurse through the JSON permission, so that's why you see a lot of logs for that function.

We already cleaned up the logs in a new version of hasura, but there are no endless loops in this situation. Would you agree with this, or did I miss something on my reproduction?

**Comment by julian-mayorga** [comment]
For reference this is the schema dump I created to reproduce this scenario:
[schema_dump.sql.zip](https://github.com/user-attachments/files/18009983/schema_dump.sql.zip)

**Comment by dohomi** [comment]
I am happy to try out the new version, I am using Nhost so I will try it out as soon it lands. What was bugging me is that while it fetches recursely it pulsates and it takes as you could see in my shared video that it takes almost 1min to load. In the current version a click on each tab is instantly available, it would be great if this could be speed up

**Comment by dohomi** [comment]
is there a PR or version I should look out when improvements about this lands?
