### ISSUE TITLE
Add support for an "includeDeprecated" argument to the IntrospectionQuery's types' fields' args

### ISSUE THREAD

**Issue by xojc** [hasura/graphql-engine#10610]
### Is your proposal related to a problem?

The [NPM graphql library](https://www.npmjs.com/package/graphql) provides a function for getting an IntrospectionQuery, with [configurable support](https://github.com/graphql/graphql-js/blob/main/src/utilities/getIntrospectionQuery.ts#L107) for the includeDeprecated argument, but the Hasura schema has [no support for the argument](https://github.com/hasura/graphql-engine/blob/master/server/src-lib/Hasura/GraphQL/Schema/Introspect.hs#L547) at all.

### Describe the solution you'd like

Add support for an "includeDeprecated" argument to the [IntrospectionQuery's types' fields' args property](https://github.com/hasura/graphql-engine/blob/master/server/src-lib/Hasura/GraphQL/Schema/Introspect.hs#L547).

**Comment by robertjdominguez** [comment]
Hiya, @xojc 👋 

We offer [deprecation](https://hasura.io/docs/3.0/supergraph-modeling/types/#objecttype-objectfielddefinition) via Hasura DDN, the next generation of our product. Does this satisfy what you're looking for?

**Comment by robertjdominguez** [comment]
@xojc — if this doesn't cover your issue, please re-open! 🙂  However, I'm closing this now due to inactivity.

**Comment by xojc** [comment]
I'm actually trying to use v2 of your product at the moment, and the schema's lack of support for the "includeDeprecated" argument at the "fields" level of the introspection query is my only problem. The argument doesn't need to do anything, but if the schema supported it, then I believe the query would succeed.

**Comment by gilbahat** [comment]
This is still an open issue / problem, why is it closed?
