### ISSUE TITLE
Don't send request type headers in GET webhooks

### ISSUE THREAD

**Issue by pari-m** [hasura/graphql-engine#10632]

**Comment by robertjdominguez** [comment]
Thanks for this addition, @pari-m 🙏 

Could you flesh out the request a bit more with details in the description?

**Comment by pari-m** [comment]
When GET requests are made using the a REST connector, by default we sent the "content-type: application/json" header in the webhook request. It would be nice to have a way to disable this behavior as some servers reject requests where this header is set.

PS - This feature already exists  please see - [disabling-request-body](https://hasura.io/docs/2.0/event-triggers/rest-connectors/#disabling-request-body)

`If you are using a GET request, you might want to not send any request body, and additionally not send a content-type header to the webhook. You can do that using the disable body feature.`

@robertjdominguez This can be closed.
