### ISSUE TITLE
fix(c/v3-engine): introspection does not work for project's main url (non-immutable url)

### ISSUE THREAD

**Issue by jjangga0214** [hasura/graphql-engine#10635]
### Component

c/v3-engine

### Is your proposal related to a problem?

There're immutable build URL and main URL.
For example, when a project's name is `foo`, they would be like

```
https://foo-21febdeaa7.ddn.hasura.app/graphql
https://foo.ddn.hasura.app/graphql
```

But when I use the 'main' URL for introspection, it does not work.
It works for an immutable build URL.

### Describe the solution you'd like

The main URL should also work.

**Comment by seanparkross** [comment]
Hi @jjangga0214 Have you applied your build to your project? `ddn supergraph build apply <supergraph-build-version> --project <project-name>`

**Comment by jjangga0214** [comment]
Oh, it works. Thanks!
