### ISSUE TITLE
Link to webhook configuration section, or sample code in webhook docs

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1064]
Via intercom/discord.

Also update webhook boilerplate READMEs to tell users how to configure webhook.

**Comment by marionschleifer** [comment]
@RanadeepPolavarapu great! 🙂 let us know if you have any questions.

**Comment by sameshl** [comment]
I would love to work on this @coco98. Can you elaborate on which section you want me to add the link to the webhook configuration section?

Thanks!

**Comment by marionschleifer** [comment]
@RanadeepPolavarapu @sameshl we realized that we actually have all the required documentation on this now. So there is no work required at the moment. If you'd like to contribute, please pick another issue labelled `Hacktoberfest` 🙂
