### ISSUE TITLE
Multi App on single Hasura instance

### ISSUE THREAD

**Issue by mnlbox** [hasura/graphql-engine#1067]
Hi guys,

Is it possible to use a single instance of Hasura for multi apps?
I want to host multi app on a single instance because I want SSO (Single Sign On) and share e-wallet between apps.

Is it possible now in Hasura? How?

**Comment by 0x777** [comment]
You can use a single instance of hasura if all these apps use the same database. 

> Is it possible now in Hasura? How?
Can you expand a bit more on your architecture? What are the apps? How is data accessed? How is SSO used?

**Comment by mnlbox** [comment]
@0x777 I want create 3 mobile app backend with Hasura. I want separate apart table from each other for simpler access to each app data. Is it possible through schema option like below or any other setting are needs:
![screenshot from 2019-01-24 08-25-46](https://user-images.githubusercontent.com/25859075/51655442-ea2cfc80-1fb1-11e9-8951-4efc41d0de98.png)

For example If we have ability to group tables together (with ability to add some tag or category to each table) we can show table as a tree in left menu in console.
something like this:
![react-bootstrap-treeview](https://user-images.githubusercontent.com/25859075/51655605-9f5fb480-1fb2-11e9-929f-f8c07901c605.jpg)

**Comment by mnlbox** [comment]
@0x777, @tirumaraiselvan can you guide me about this?

**Comment by tirumaraiselvan** [comment]
@mnlbox Yes you can use separate schemas in the same database!

**Comment by mnlbox** [comment]
Thanks @tirumaraiselvan.
So the best practise is to split each app to separate schema. yes?

How we can create schema?
Is it possible through Hasura console?

**Comment by tirumaraiselvan** [comment]
@mnlbox The best practise, I think, would be to use different databases and different Hasuras. But in case your apps are related and might share data at some point or you just want to use one Hasura for operational convenience then yes, you can use separate schemas. You can create a schema through hasura console in the SQL tab (`CREATE SCHEMA myschema;
`)  and then just switch the schemas through the button on the top left.

**Comment by mnlbox** [comment]
Thanks man.
I think we can close this issue and discuss about **table grouping** feature in separate issue for this:
![react-bootstrap-treeview](https://user-images.githubusercontent.com/25859075/51655605-9f5fb480-1fb2-11e9-929f-f8c07901c605.jpg)

**Comment by mnlbox** [comment]
Let's talk more about table grouping here: #1945
