### ISSUE TITLE
Add guide for helping with created_at and updated_at timestamps

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1077]
Let's add a guide to help users model `created_at` and `updated_at` timestamps.

For `created_at` a default value of `now()` works.
For `updated_at` a trigger on the lines of: https://x-team.com/blog/automatic-timestamps-with-postgresql/

**Comment by sebastianmacias** [comment]
```created_at``` and  ```updated_at``` automatic timestamps are so commonly used. I think there should be an option to set the timestamp field to automatically handle this when creating the schema. 

By the way the link posted is broken, this is the working link: https://x-team.com/blog/automatic-timestamps-with-postgresql/

**Comment by marionschleifer** [comment]
This issue is solved with the last release showing frequently used columns:

![image](https://user-images.githubusercontent.com/5722022/61951707-6f2fb780-afcf-11e9-93a6-472bff83c8a7.png)

Closing this issue.

**Comment by hrmoller** [comment]
Thanks for the _Frequently used columns_ feature👍However, it would be super nice if this feature was also available on the Modify so it be used on tables already created.

https://www.dropbox.com/s/4gd6u5xs6gj7hg1/Screenshot%202019-07-28%2019.34.30.png?raw=1

**Comment by rikinsk** [comment]
@hrmoller There is already a PR raised for this. It should go live in a day or two.

**Comment by tsaiDavid** [comment]
@rikinsk (cc: @dmi3y) - thanks for this feature - my manager is worried about the use of triggers on the db level, is there any risk of doing so? Just trying to wrap my head around this. Would rather not use external hasura event triggers (effectively turning 1 write into 2 distinctly separate ones)

**Comment by 0x777** [comment]
@tsaiDavid
> my manager is worried about the use of triggers on the db level, is there any risk of doing so?

Triggers are the only reliable way to ensure that fields like `updated_at` are set correctly for a row, otherwise you have to ensure that every client which connects to the database sets this value as expected.

**Comment by gentleShark** [comment]
One improvement would be to allow for the use of any column name. Currently if you change the column name to anything other than "updated_at" (such as updatedAt), you'll get an error on insert.
"error": {
            "exec_status": "FatalError",
            "hint": null,
            "message": "record \"_new\" has no field \"updated_at\"",

**Comment by verekia** [comment]
Correct me if I'm wrong but there is currently still no way to modify an existing `updated_at` column to add a trigger? I guess we have to create a new `updated_at` column with the Frequently used feature and copy the data?

**Comment by verekia** [comment]
I don't know if that's the right way to do it, but I've added the trigger directly on the database (using TablePlus), and it shows up in the Hasura interface. I simply copied the code of the frequently used column on v1.2.2 of Hasura.

```
CREATE OR REPLACE FUNCTION public."set_current_timestamp_updated_at"()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  _new record;
BEGIN
  _new := NEW;
  _new."updated_at" = NOW();
  RETURN _new;
END;
$function$
```

And created the trigger: `set_public_YOURTABLENAME_updated_at` on the table with:
`BEFORE UPDATE, FOR EACH ROW`
`EXECUTE FUNCTION "set_current_timestamp_updated_at"()`

It seems to be working.

**Comment by petegriffith** [comment]
Hi, is there a way to modify existing `updated_at` columns with the trigger? I'm not seeing it if there is.

**Comment by dmi3y** [comment]
> Hi, is there a way to modify existing `updated_at` columns with the trigger? I'm not seeing it if there is.

Sure you can, you have to write some sql for this. Also depends on what do you mean by "a way to modify existing `updated_at`".

**Comment by petegriffith** [comment]
I just meant that while there is a way to add the trigger to a new `updated_at` field via the console, there doesn't seem to be a way to modify an existing `updated_at` field to take the trigger.

**Comment by dmi3y** [comment]
> I just meant that while there is a way to add the trigger to a new `updated_at` field via the console, there doesn't seem to be a way to modify an existing `updated_at` field to take the trigger.

I see now, looks like catch 21 scenario, lol.

I still think it's possible with some conditional event logic or something though.
