### ISSUE TITLE
Add a basic guide on scaling Hasura

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1078]
Scaling Hasura is as simple as scaling up the number of instances. If the metadata or schema is updated, a rollout (or metadata refresh) should be triggered.

Let's document the process (2 commands basically, but still ;)) for various platforms:
1. Docker
2. Heroku
3. Kubernetes
4. Fargate

This is an urgent hole in our current docs.

**Comment by dsandip** [comment]
closing this in favor of #940
