### ISSUE TITLE
Support for range types

### ISSUE THREAD

**Issue by benbro** [hasura/graphql-engine#1079]
Is it possible to support [PostgreSQL range types](https://www.postgresql.org/docs/11/rangetypes.html#RANGETYPES-BUILTIN)?
They are not listed [here](https://docs.hasura.io/1.0/graphql/manual/api-reference/postgresql-types.html).

**Comment by 0x777** [comment]
@benbro They aren't explicitly supported so you won't be able to use operators specific to such columns, but everything else should work as expected, i.e, you can select and insert data.

**Comment by benbro** [comment]
I won't be able to use [Range Functions and Operators](https://www.postgresql.org/docs/11/functions-range.html)?

**Comment by 0x777** [comment]
Currently no. We'll add support soon.

**Comment by 0x777** [comment]
You can follow the progress here: https://github.com/hasura/graphql-engine/issues/1082

**Comment by benbro** [comment]
Thanks

**Comment by slimlime** [comment]
Current usability workarounds?

https://github.com/WhoopInc/node-pg-range
