### ISSUE TITLE
support all operators on all types

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#1082]
So far we've been explicitly supporting types and their operators. This is not a scalable approach, we should instead support all operators from `pg_catalog.pg_operator`.

**Comment by 0x777** [comment]
Related #625, #1079

**Comment by pronevich** [comment]
Is it going some progress on this issue? Just want to know, because of the need to use ltree module

**Comment by 0x777** [comment]
@pronevich We will pick this up soon. Can you help us by providing a few examples of the necessary operators and how they should be in graphql?

**Comment by litchfield** [comment]
@0x777 Easy win here would be to support `ltree` type using the existing graphql lt/lte/etc. This would cover the basic operators `<, <=, =, >=, >`. We're starting a major new project and would love this! Where do we sign for a paid plan? :-) 

Full support with all the operators supported by GIST indexes `<, <=, =, >=, >, @>, <@, @, ~, ?` would be amazing though!

https://www.postgresql.org/docs/current/ltree.html#LTREE-OP-TABLE

**Comment by roycastro** [comment]
@0x777 is ltree support being actively developed? Can you give some feedback at this point?
By the way, great job with Hasura!!!

**Comment by tirumaraiselvan** [comment]
@pronevich @litchfield @roycastro Will appreciate using #625 for discussing `ltree` specific support.

**Comment by magick93** [comment]
Just realized that Hasura doesnt support all pg operators. 

And there hasnt been any updates to this issue in 2 years. 

Thats very concerning. Is full support of Postgres no longer a priority?

**Comment by soupi** [comment]
This issue is already addressed in the new Hasura V3 [ndc-postgres](https://github.com/hasura/ndc-postgres), hence closing this. Please follow the [guide](https://hasura.io/docs/3.0/getting-started/overview/) here for Alpha access to Hasura V3.
