### ISSUE TITLE
Document techniques for data validation & integrity, especially for mutations

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1087]
- In postgres: constraints, check constraints, triggers
- In custom resolvers / remote schema

Some useful links:
http://shuber.io/porting-activerecord-validations-to-postgres/
https://stackoverflow.com/a/12521563/3364697
https://karolgalanciak.com/blog/2016/05/06/when-validation-is-not-enough-postgresql-triggers-for-data-integrity/

**Comment by coco98** [comment]
TEXT + check constraint vs varchar is an especially important one.

**Comment by marionschleifer** [comment]
This has been added [here](https://hasura.io/docs/1.0/graphql/core/schema/data-validations.html).
