### ISSUE TITLE
change the notes under 'Raw SQL'

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#1093]

**Comment by wawhal** [comment]
Old notes:

1. You can create views, alter tables or just use any SQL syntax to communicate with the database.
2. If you plan to create a Table/View using Raw SQL, remember to link it to Hasura DB using Add Existing Table View functionality.
3. Please note that if the migrations are enabled,downmigrations will not be generated for SQL statements.

New notes:
1. You can create views, alter tables or just use any SQL syntax to communicate with the database.
2. If you plan to create a Table/View using Raw SQL, remember to link it to Hasura DB by checking the "Track table" checkbox
3. Please note that if the migrations are enabled, `down` migrations will not be generated when you change the schema using Raw SQL.
