### ISSUE TITLE
UI improvements in Modify section of a table

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#1096]
![image](https://user-images.githubusercontent.com/6562944/48896469-b2002500-ee6d-11e8-9913-148b66ac80e4.png)
The 'add new column' section kind of suggests that it describes the properties of the last column.

**Comment by praveenweb** [comment]
We can add a separator line between the last column and the add new column section. May be a hr element would do. 

Additionally we can also label that section with Add a new column at the top.

<img width="815" alt="modify table" src="https://user-images.githubusercontent.com/14110316/50135075-ec5db600-02a3-11e9-824b-6733e581f9c8.png">

Roughly the code would look like this:

```
<hr/>
<h4 className=''>Add a new column</h4>
```

**Comment by wawhal** [comment]
@praveenweb I suggest we should come up with a design to add a new column in the same section. Something like a plus button near the `Columns` heading. A separate section just for adding a new column doesn't look good IMO.

@dsandip ideas?

**Comment by WickedBrat1** [comment]
Hi what about having a "Add new column" or just "+ Add" after the `Columns` and toggle the section when the button is clicked.
