### ISSUE TITLE
Undocumented feature: single row inserts?

### ISSUE THREAD

**Issue by jlowin** [hasura/graphql-engine#1106]
Running alpha-30, I accidentally discovered that inserting a single row works fine, though I can't find any confirmation of this in the docs (or in the tests):

For example -- notice that `objects` is a single row, not an array of rows:
```
mutation {
  insert_x(objects: {id: 1}) {
	returning {
		id
	}
  }
}
```

Perhaps I'm overlooking it in the docs, but every example [here](https://docs.hasura.io/1.0/graphql/manual/mutations/insert.html) uses the `objects: []` syntax. The schema browser (in GraphiQL or Playground) also shows that the input is a required array, not a single object. Please let me know if I'm looking in the wrong place!

However, this still returns an array of results, so one must still access `returning[0]` for the first result. If this is, in fact, a feature, it would be nice if returned an object instead of an array.

In any case, just wanted to point it out.

**Comment by benjie** [comment]
This is a standard feature of GraphQL - where a list is specified you may instead pass a non-null value and it will be coerced into a list of size one. Here's the relevant part of the spec, see "Input Coercion":

https://facebook.github.io/graphql/draft/#sec-Type-System.List

**Comment by jlowin** [comment]
TIL, thanks @benjie!
