### ISSUE TITLE
merge remote types if their name and structure are same

### ISSUE THREAD

**Issue by ecthiender** [hasura/graphql-engine#1112]
In remote schemas, right now we don't merge types if they have the same name. If the types have same name and exact same structure we should merge them.

**Comment by revskill10** [comment]
This behaviour should be configurable, because in some cases, the stitched server could manipulate to behave differently even if remote types are the same (like changing types)

**Comment by 0x777** [comment]
@revskill10 If two types have the same structure, it doesn't matter.

**Comment by 0x777** [comment]
Related: https://github.com/hasura/graphql-engine/issues/1135
