### ISSUE TITLE
Hasura on PostgreSQL 10.5 is stuck at Attaching to docker-compose_graphql-engine

### ISSUE THREAD

**Issue by rinfimate** [hasura/graphql-engine#1114]
I have just started using Hasura and wanted to try it out in PostgreSQL 10.5 using a Docker container in Mac. It seems to be stuck in "Attaching to docker-compose_graphql-engine". I have confirmed this is the same issue in AWS Aurora with PostgreSQL 10.5. Hasura builds its 2 schemas and necessary Tables etc. in the Database but does not go ahead after this

**Comment by shahidhk** [comment]
@rinfimate, Can you give us the output of `docker-compose ps` and `docker-compose logs`?

**Comment by rinfimate** [comment]
Sorry, my bad. I was using an older docker-compose file from one of your blogs, the container was trying to attach port 80 and not 8080. Its working with PG 10.5 locally. Will try on AWS Aurora PG 10.5 later. Please close the case. Thanks for the quick response though.

**Comment by shahidhk** [comment]
:+1: 

There is already a known issue AWS RDS 10.4 (#417). Do let us know how 10.5 works.
