### ISSUE TITLE
Feature Request: SQLite connector

### ISSUE THREAD

**Issue by benoror** [hasura/graphql-engine#1119]
# Feature Request

**What feature are you missing?**

Support for local databases such as SQLite

**How could this feature look like in detail? Tradeoffs?**

Should be straightforward since it's kinda standard.

My main use-case would be to create decentralized/portable/client-side-only (d)apps.

Similar to: https://github.com/prisma/prisma/issues/2460

**Comment by daneroo** [comment]
This is a great idea, would accelerate integration testing.

**Comment by ch4rl3s** [comment]
Hi, some news about sqlite connector ? thanks.

**Comment by jeffreygray** [comment]
Sorry to gravedig but any update here on the sqlite integration? This seems incredibly useful.

**Comment by tombohub** [comment]
yes, i am subscribing to this

**Comment by dvasdekis** [comment]
Hi guys, with the new Alpha releases that include MySQL and MSSQL, I'm hoping this could be included as well!

SQLite supports use cases like [LiteStream](https://litestream.io/) and decentralized databases, which is super useful for building Web3 applications.

Thanks!

**Comment by louy2** [comment]
They are going to do this for a HasuraCon workshop LOL
https://hasura.io/events/hasura-con-2021/talks/sqlite-implementing-a-new-hasura-backend/

**Comment by lilred** [comment]
@daneroo

>This is a great idea, would accelerate integration testing.

@radojko 

>Great for ARM devices like Rpi

Note that even with different connectors Hasura still needs a Postgres database to manage its metadata, so a SQLite connector would not immediately make Hasura completely portable. You'll still need a Postgres database for integration testing and embedded devices.

**Comment by marceloverdijk** [comment]
This could also help building a (SSG) Next.js website where the static data (`getStaticProps`) is retrieved from a local GraphQL server using a local sqlite database.

**Comment by dvasdekis** [comment]
With the announcement of [Cloudflare D1](https://blog.cloudflare.com/introducing-d1/), this would be more useful than ever!

**Comment by Adron** [comment]
Hello all, check out this [path here to explore](https://github.com/hasura/graphql-engine/tree/master/dc-agents/sqlite) and check out our SQLite connector for Hasura!  So far it's just read only queries, but it's a start toward eventual full support!

Hey @dvasdekis would love to see what you'd put together with SQLite and the Cloudflare D1, several of us were pondering what could be done with that and other options out there.

Also for ARM devices/embedded devices, I'd be curious what else everybody else is thinking about, ping me if you've got time to discuss. Here or even ping me direct [@Adron](https://twitter.com/adron).
