### ISSUE TITLE
bug with alpha30 remote_schemas key not found

### ISSUE THREAD

**Issue by billyfung** [hasura/graphql-engine#1120]
Tried out the realtime poll example with latest engine version as per README
Migration gave me the error 

```
Error: apply failed: [parse-failed] the key 'remote_schemas' was not present ($[2])
File: ''
```

**Comment by shahidhk** [comment]
We should be able to make a release by EOD. A workaround is to add `remote_schemas: []` as a top-level key to the metadata file.
