### ISSUE TITLE
Feature Request:Send schema name and table name to authentication webhook

### ISSUE THREAD

**Issue by rinfimate** [hasura/graphql-engine#1159]

**Comment by 0x777** [comment]
@rinfimate Can you describe your use case where this information is needed? It is not as simple a single graphql query could potentially access any number of tables.

**Comment by manasag** [comment]
This issue has not attracted significant attention for a long period of time, and since alternatives are available, we are closing this.
Please feel free to reopen if the issue is still relevant for you.
