### ISSUE TITLE
Dockerless setup

### ISSUE THREAD

**Issue by lucca65** [hasura/graphql-engine#1164]
Hi! I'm trying to run Hasura on my productions servers and for some reasons that aren't relevant to this issue, I'm unable to use docker. Is there a way to use Hasura without using it? Thanks!

My prod servers are running Ubuntu bionic

**Comment by lucca65** [comment]
Got help on discord, thanks a lot @coco98

**Comment by colundrum** [comment]
Can you post the solution in this issue please ?
I search the official link where I can download graphql-engine binary without compiling it.

**Comment by lucca65** [comment]
they sent me a binary at the time.

**Comment by colundrum** [comment]
Thank you and anyone search the direct link to latest build: https://graphql-engine-cdn.hasura.io/server/latest/linux-amd64

**Comment by eduardosanzb** [comment]
how did you ended up running the binary!?

**Comment by lucca65** [comment]
like all normal binaries... 

```sh
./file-name
```

You can always google it, here is the first result I got: https://stackoverflow.com/questions/9477157/how-to-run-binary-file-in-linux
