### ISSUE TITLE
hasura not track tables with plural name ?

### ISSUE THREAD

**Issue by dfang** [hasura/graphql-engine#1166]
this is not an issue but a question.
table name must be singular ?
is there any documentation about names standard.

thanks

**Comment by shahidhk** [comment]
@dfang There is no such restriction. Some of us prefer to use singular table names, but we have seen many users using plural names.

Are facing any issues?

**Comment by dfang** [comment]
yes, i'm following naming convention in ruby on rails, tables is a collection of rows, a row is an object, so i prefer plural table names. had issues when trying to hasura cluster on minikube.
minikube is buggy,  now i'm trying graphql engine with docker-compose. it's ok for plural names.

thanks !

**Comment by dukedave** [comment]
@dfang FYI #1542 makes this a little easier.
