### ISSUE TITLE
support for postgresql ARRAYS []

### ISSUE THREAD

**Issue by sulliwane** [hasura/graphql-engine#1170]
Given this SQL schema:
```SQL
CREATE TABLE public."table" (
    "textArray" text[]
)
```
Graphql engine returns an error when trying to mutate:
```js
{ 
  name: 'FormatedError',
  message: 'Unknown error',
  originalError: 
    { 
       path: '$.variableValues[0].textArray',
       error: 'A string is expected for type : _text',
       code: 'parse-failed'
     }
}
```
Is there a workaround? Many thanks

**Comment by shahidhk** [comment]
@sulliwane You can pass the array value as text since all postgres types which are natively supported by GraphQL Engine are treated as text. 

This mutation will go through:
```graphql
mutation {
  insert_table(objects:[{
    textArray: "{'hello', 'world'}"
  }]) {
    returning {
      textArray
    }
  }
}
```

**Comment by sulliwane** [comment]
thanks a lot, it works perfectly!

About the curly brackets `{}` for the array, may I ask what kind of "standard" is that (obviously not JSON format) is it related to graphql or postgres or hasura?

**Comment by shahidhk** [comment]
`{}` is how arrays are represented in Postgres [1]

[1] https://www.postgresql.org/docs/9.1/arrays.html

**Comment by sulliwane** [comment]
Ok, got it. closing then, thanks a lot @shahidhk
