### ISSUE TITLE
accept query params for preloading queries/mutations in console graphiql

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#1179]
It would be nice to have the console accept query parameters to preload queries/mutations.

Right now `query_file` pointing to a github link works. But lets also accept `query` parameter directly with support for variables too.

So it would support the following:

1) `query` param for actual query
2) `headers` param for a list of headers to be templated

**Comment by CodHeK** [comment]
@praveenweb could you please explain a little more what is the issue about?
 I don't quite get what preloading queries/mutations mean here

**Comment by manasag** [comment]
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.
