### ISSUE TITLE
Example for using auth with AWS Cognito

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#1180]
Document/illustrate https://aws.amazon.com/cognito/ as auth webhook.

**Comment by Nomad-Go** [comment]
https://github.com/hasura/graphql-engine/pull/1544

**Comment by dsandip** [comment]
@tirumaraiselvan Can we change the scope of this issue to have an end to end guide for Cognito after an update from #1176 is available in the next release (*currently WIP*), instead of using a webhook for it? cc: @rikinsk

**Comment by Rigel772** [comment]
Any update on this?
