### ISSUE TITLE
enable up down arrows in dropdown+textbox inputs (event trigger, remote schemas)

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#1210]

**Comment by pradeepgangwar** [comment]
@wawhal Let me fix this up.

**Comment by pradeepgangwar** [comment]
@wawhal Dropdowns in event trigger form are working with up-down arrow keys. Please let me know the area where this issue exists.

**Comment by pradeepgangwar** [comment]
@wawhal I went through dropdown code and found that there is no default option in react-bootstrap that enables arrow keys. So I guess I have to add it manually by adding a function that acts on arrow key. This is my first issue on this repo so pls let me know if I am thinking in right direction. 😅

**Comment by wawhal** [comment]
@pradeepgangwar yes you'll have to write a key handler.

**Comment by thangngoc89** [comment]
https://github.com/paypal/downshift is a good library for handling these kind of things

**Comment by jeremie1112** [comment]
Hi, is someone working on this? @wawhal 
else let me know if I can work on this issue.

**Comment by wawhal** [comment]
Go for it @jeremie1112 :+1:

**Comment by wawhal** [comment]
@jeremie1112 yes @codingdefined has opened [a PR](#3105)

**Comment by jeremie1112** [comment]
> @jeremie1112 yes @codingdefined has opened [a PR](#3105)

@wawhal Can you recommend me any "good first issue" tag please?

**Comment by marionschleifer** [comment]
@jeremie1112 here is a list of good first issues: https://github.com/hasura/graphql-engine/issues?q=is%3Aopen+is%3Aissue+label%3Ap%2Fmedium+sort%3Aupdated-desc. Here are some guidelines for contributing: https://github.com/hasura/graphql-engine/wiki/Hacktoberfest-2019-%F0%9F%8E%89 🙂
