### ISSUE TITLE
Support api to generate json-schema from pg tables

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#1219]
SHould we add api to generate json-schema for pg-tables ? 
One use case is to use https://github.com/mozilla-services/react-jsonschema-form to generate frontend React forms from an API endpoint.

Note: Currently in order to generate json-schema, one must access `pg_url` to generate statically.
So this feature will allow runtime json-schema-form generation for all pg tables.

**Comment by 0x777** [comment]
Outside the scope of this project.
