### ISSUE TITLE
Feedback on hasura init command

### ISSUE THREAD

**Issue by akiran** [hasura/graphql-engine#1220]
1) I tried to run `hasura init` on root folder of existing project so that I can run hasura cli commands from root folder of project instead of going to subfolder 
But, I get an error *Error: directory 'folder-name' already exist*

CLI could give a warning saying `folder already exist. Do you want to continue ? Y/N`
and allow creating hasura setup in a existing project.

2) Config file name is very generic ("config.yaml"). It could conflict with  config file name of other tools.  Names like graphql-engine-config.yaml or hasura-config.yaml can be more specific.

**Comment by shahidhk** [comment]
Split into https://github.com/hasura/graphql-engine/issues/4560 and https://github.com/hasura/graphql-engine/issues/4561
