### ISSUE TITLE
how to graphql mutation on non-public schema

### ISSUE THREAD

**Issue by sulliwane** [hasura/graphql-engine#1242]
what is the graphql mutation format to interact with non-public schema?

I tried adding my schema name `123` before the mutation name: `123_insert_object()` but I get an error:
```
GraphQLError: Syntax Error: Expected Name, found Int 
```

Is it related to the fact that I'm using number in schema names?

Many thanks!

**Comment by coco98** [comment]
> Is it related to the fact that I'm using number in schema names?

@sulliwane Yep. I think it is. 

Could you temporarily try creating another schema and trying it out? Everything should work.

@0x777 @rakeshkky should be able to comment on whether numbers can be used in the graphql schema name or not.

**Comment by praveenweb** [comment]
@shahidhk  - There is a relevant issue #212 for handling GraphQL name scheme for identifiers.

**Comment by sulliwane** [comment]
@shahidhk my bad, it works perfectly when schema name is not starting with a number.

The thing is, even if it's a non valid name, postgres still allows its creation. In Hasura, the schema is listed and it's possible to add tables, but nothing is displayed in graphiql schema (which is normal).
