### ISSUE TITLE
validate and clean GraphQL types along with fields

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#1247]
The server is prone to generate GraphQL types with empty fields. This happens if a table doesn't have fields (columns and relations) whose names conform to GraphQL spec.

Need to validate and clean such types with cascading.

**Comment by dsandip** [comment]
@rakeshkky to comment on linking this to incremental building of cache

**Comment by rakeshkky** [comment]
Refer https://github.com/hasura/graphql-engine/issues/1584 which also solves this.
