### ISSUE TITLE
add gzip compression

### ISSUE THREAD

**Issue by jvice152** [hasura/graphql-engine#1253]
perhaps someone could point me in the right direction.... is there a way to enable gzip compression on queries?

https://blog.hasura.io/architecture-of-a-high-performance-graphql-to-sql-server-58d9944b8a87 

I see it being referred to, but cant find any examples of it. When doing large requests, i see the accept-encoding header of gzip, deflate but not on the response at all (content-encoding). Am i looking at this correctly?

TIA

**Comment by 0x777** [comment]
Hi, graphql-engine doesn't do any sort gzip compression of the response. However you can add a reverse proxy like caddy or nginx to do this.

**Comment by marionschleifer** [comment]
I'm closing this issue. @jvice152 if you have any further questions, please re-open it 🙂

**Comment by Toub** [comment]
I guess this issue should be closed as it has been fixed by https://github.com/hasura/graphql-engine/pull/2751 ?

**Comment by rikinsk** [comment]
Yes indeed.
