### ISSUE TITLE
Docker image for arm

### ISSUE THREAD

**Issue by fayad** [hasura/graphql-engine#1266]
We have built an inhouse RPi cluster for production and currently testing the Hasura docker image. But it seems an image for arm is not available yet. 

It will be a great addition as the platform is popular among servers.

Thanks.

**Comment by 0x777** [comment]
This is not an easy task. Also, ARM is still a [Tier 2 architecture](https://ghc.haskell.org/trac/ghc/wiki/Platforms) for GHC

**Comment by coco98** [comment]
Adding keywords to make this easier to find:
arm64, raspberry pi

**Comment by albertobissacco** [comment]
I wanted try hasura on my raspberry pi but I stopped when I found that I can't run the docker image.
Do you have news about this?

**Comment by kwe** [comment]
An arm docker image would be great, not just for Rasberry pi, but also for Windows arm and (shortly) MacOS arm

**Comment by joshuarobs** [comment]
Maybe it might be possible with Docker's experimental `buildx` feature?

https://docs.docker.com/docker-for-mac/multi-arch/

Not sure if its similar to a write once (for one architecture), create multiple architectures kind of thing.

**Comment by MrBlenny** [comment]
How would I go about building graphql-engine on ARM, specifically arm64v8? I'm willing to do a heap of testing - from my preliminary research it looks like the GHC ARM support has improved quite a lot in the last year or so.

I've gotten quite a way through an embedded computer vision project that was using hasura and running on a Jeton Xavier AGX only to find this out quite late :cry:

**Comment by hanlyjiang** [comment]
I had build a graphql-engine docker image for arm，upload to https://hub.docker.com/r/hanlyjiang/graphql-engine-base

**Comment by melehin** [comment]
I had build the graphql-engine **v1.3.1** docker image and upload to https://hub.docker.com/r/fedormelexin/graphql-engine-arm64
Static assets for hasura console included and enabled by default!

Dockerfile to build on own Rpi4 (4GB/8GB) or Jetson Nano or other machines: https://github.com/melehin/graphql-engine-arm64

**Comment by joshuarobs** [comment]
@hanlyjiang 
@melehin 
It seems you guys figured out a way to build hasura for arm. If its doable, then surely the staff at hasura can make official versions of these images too?

**Comment by melehin** [comment]
@joshuarobs
Sure, but ARM is still a Tier 2 architecture for GHC and may contain platform-specific bugs or other vulnerabilities.
Thereby builded images for ARM also may contains the same.

For pet projects or development on ARM is good alternative.
I have rpi3, rpi4 and Jetson Nano and hasura works well on them.

**Comment by shantiscript** [comment]
@joshuarobs if you could turn the mentioned solutions into official images even just for raspberry pi and Jetson nano, i think there is so much potential to use Hasura in edge, ai and IOT applications. Booth platforms have a strong and growing user base in hobby and commercial applications.I think a lot of people would be very interested in using Hasura in their projects. I for example am currently exploring the option to use it in a commercial project next year that would run on jetson or raspberry compute module as i can then use the same tooling for cloud as well as edge infrastructure

**Comment by shantiscript** [comment]
also looks like there is some good progress on ghc on arm
https://www.haskell.org/ghc/blog/20200515-ghc-on-arm.html

**Comment by seanaye** [comment]
I'm trying to get the hasura image to run on my M1 Mac. According to the Docker M1 docs you can set the `--platform` flag for emulation under rosetta (https://docs.docker.com/docker-for-mac/apple-m1/). The container still fails with docker exit code 137. Has anyone successfully run a docker container with linx/amd64 emulation? It appears like it should be possible according to the docker docs.

**Comment by SergeBregliano** [comment]
> I'm trying to get the hasura image to run on my M1 Mac. According to the Docker M1 docs you can set the `--platform` flag for emulation under rosetta (https://docs.docker.com/docker-for-mac/apple-m1/). The container still fails with docker exit code 137. Has anyone successfully run a docker container with linx/amd64 emulation? It appears like it should be possible according to the docker docs.

@seanaye : This is not related to ARM image, Docker can natively run x86 images. The 137 error code is due to Docker's memory : Docker has not enough memory to run properly. Hasura run fine for me on M1 without mentioning the `--platform` flag. Try again allowing more memory to Docker (I'm at 6GB).

**Comment by ddomingues** [comment]
> > I'm trying to get the hasura image to run on my M1 Mac. According to the Docker M1 docs you can set the `--platform` flag for emulation under rosetta (https://docs.docker.com/docker-for-mac/apple-m1/). The container still fails with docker exit code 137. Has anyone successfully run a docker container with linx/amd64 emulation? It appears like it should be possible according to the docker docs.
> 
> @seanaye : This is not related to ARM image, Docker can natively run x86 images. The 137 error code is due to Docker's memory : Docker has not enough memory to run properly. Hasura run fine for me on M1 without mentioning the `--platform` flag. Try again allowing more memory to Docker (I'm at 6GB).

Hi @SergeBregliano . Nice!

Could you give more information about what you did in order to have Hasura run fine on M1? 🙏  
I.e `hasura-cli`, settings, etc. 

It will help us a lot

**Comment by SergeBregliano** [comment]
Hi @ddomingues,
For Docker, I use [the official preview](https://docs.docker.com/docker-for-mac/apple-m1/). My Docker's preferences ressources settings are : 4 CPU, 6GB of RAM and 1GB of Swap.
For Postgres & Hasura, I use a classical `docker-compose`. I've just test the [official docker-compose](https://github.com/hasura/graphql-engine/blob/stable/install-manifests/docker-compose/docker-compose.yaml) and it worked for me. If you need mine, I can clean it a little bit and publish it, just let me know.
For `hasura-cli`... It's another thing ! I dont use `hasura-cli` as it's not available on ARM. I play with metadata imports / exports and database dumps to make the job. Not very clean, but useful for my little needs.
Reading your post, I tried to make and amd64 container and install `hasura-cli` on it. I didn't manage to make it run clean but I think it's possible. [Some containers on the Docker Hub](https://hub.docker.com/search?q=hasura-cli&type=image) seems to work as independent `hasura-cli` servers.
[This one](https://hub.docker.com/r/sharescape/hasura-cli-docker) has a short documentation.
Hope this can help. Tell me if you need more precisions ;-)

**Comment by ddomingues** [comment]
> Hi @ddomingues,
> For Docker, I use [the official preview](https://docs.docker.com/docker-for-mac/apple-m1/). My Docker's preferences ressources settings are : 4 CPU, 6GB of RAM and 1GB of Swap.
> For Postgres & Hasura, I use a classical `docker-compose`. I've just test the [official docker-compose](https://github.com/hasura/graphql-engine/blob/stable/install-manifests/docker-compose/docker-compose.yaml) and it worked for me. If you need mine, I can clean it a little bit and publish it, just let me know.
> For `hasura-cli`... It's another thing ! I dont use `hasura-cli` as it's not available on ARM. I play with metadata imports / exports and database dumps to make the job. Not very clean, but useful for my little needs.
> Reading your post, I tried to make and amd64 container and install `hasura-cli` on it. I didn't manage to make it run clean but I think it's possible. [Some containers on the Docker Hub](https://hub.docker.com/search?q=hasura-cli&type=image) seems to work as independent `hasura-cli` servers.
> [This one](https://hub.docker.com/r/sharescape/hasura-cli-docker) has a short documentation.
> Hope this can help. Tell me if you need more precisions ;-)

Hi @SergeBregliano 

Thank you so much for your time and informations.

For `graphql-engine` I used the @melehin image  https://hub.docker.com/r/fedormelexin/graphql-engine-arm64
For `hasura-cli` I used the npm alternative

I change the docker settings as you suggested and it works fine 🎉

**Comment by Caperious** [comment]
@SergeBregliano Thank you for your comment. After bumping up the allocated memory for docker to 6gb, the graphql-engine started working. 🥳

**Comment by damiensedgwick** [comment]
I've also been having the above issue and whilst it runs just fine with 6gb of ram I feel like it is overkill! Is there any hope of perf improvements for this?

**Comment by snipebin** [comment]
Would be awesome if you guys could publish multi arch images at https://hub.docker.com/r/hasura/graphql-engine so it works without additional hassle across different platforms we use in development

**Comment by MarkNBroadhead** [comment]
🎉 v2.1.0.beta.3 and up are now being compiled for ARM. The latest as of today is 2.1.1 which I can confirm is running without QEMU crashes on my M1 MacBook Pro. Thank you for your hard work, Hasura team!

**Comment by ddelange** [comment]
Since v2.1.0 and later have `linux/arm64` images available at https://hub.docker.com/r/hasura/graphql-engine, can this issue be closed?

**Comment by scriptnull** [comment]
We started pushing multi-arch images to `hasura/graphql-engine` for supporting `linux/arm64` starting from `v2.1.0-beta.3` version. So, closing this.
