### ISSUE TITLE
Event Trigger throttle configuration ?

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#1268]
Let's say we want to send an email to user after successful registration into users table.
Is it possible to configure throttling configuration so that we could limit number of triggers per secs/mins ?

**Comment by revskill10** [comment]
@coco98 The use case is in case we want to send bulk email to many users at once.
In this case, could Hasura send event triggers in bulks, too ?
For example, Gmail has a limit about some dozens of email could be sent per seconds/minutes/hours,...
It could be useful if we could control this from event triggers, too.

**Comment by tirumaraiselvan** [comment]
@revskill10 Like @coco98 mentioned, you can achieve this via 'Retry-After' header in your webhook. This will involve having a table in your db though. 

Suppose you want to process 100 requests/minute, then you can have a table say 'throttle'  with columns 'begin_timestamp' and 'count'. In your email trigger function:

1) make a query to 'throttle' and check if there is a 'begin_timestamp' which is less than 60 seconds than current_time.
2) If there is such a timestamp, then check 'count' else create a entry with begin_timestamp = current_time and count = 0
3) If count is less than 100, then process the request and increment the count else return with HTTP status code 429 and Retry-After header of 60 seconds.

If you do the above steps in a **transaction** then this will guarantee that you achieve 100req/min considering tolerable clock-skew. If you don't do this in a transaction then it will still be fine unless you have very high volume of concurrent requests.

Let me know if this is clear.

**Comment by tirumaraiselvan** [comment]
^ Updated the math a bit.

**Comment by marionschleifer** [comment]
I'm closing this issue. If something is not clear or if you have additional questions, please feel free to re-open it 🙂
