### ISSUE TITLE
Table Tracked without PK

### ISSUE THREAD

**Issue by go4cas** [hasura/graphql-engine#1269]
I have created my DB schema using a SQL client. Then in Hasura console, i selected to track all tables. All tables and columns are added successfully, but the primary keys are not tracked.

Sample of create:
```SQL
CREATE TABLE users
(
   id                serial         NOT NULL,
   email             varchar(50)    NOT NULL,
   password          varchar(200)   NOT NULL,
   user_status_id    int            NOT NULL,
   created_at        timestamptz,
   updated_at        timestamptz
);

ALTER TABLE users
   ADD CONSTRAINT users_pkey
   PRIMARY KEY (id);

ALTER TABLE users
   ADD CONSTRAINT users_email_unique
   UNIQUE (email);
```
In Hasuar console, I get the following message: "There is no unique identifier (primary Key) for a row. You need at-least one primary key to allow editing,".

**Comment by coco98** [comment]
That's super weird and should not be happening.
Can you try to reload metadata via the console?

**Comment by go4cas** [comment]
@coco98 ... I have already tried that.

I have also tried creating anew table, using the SQL client, and then tracking the table through console - it has the same behavior.

The only way I can get PK to work, is by creating the table directly in console.

**Comment by coco98** [comment]
@karthikvt26 @praveenweb @rakeshkky Can you folks verify? This is unexpected right.

**Comment by iamareebjamal** [comment]
Facing the same issue. Used older metadata, created new db and used older metadata, and created new db and tracked from scratch. Same issue in all 3 cases.

alpha v33

**Comment by iamareebjamal** [comment]
So, my issue was that I was using a different user which was not the owner of the database but still had all privileges on the database, usage on schema public as well as on SEQUENCES and FUNCTIONS.

For now, I have resorted to using the DB owner as the user in DATABASE URI. However, I think this issue should be fixed. 

Note that foreign keys are correctly listed, just primary keys aren't. However, I am able to check primary keys of the tables when logged in as the new user

**Comment by go4cas** [comment]
I can confirm @iamareebjamal's feedback. I have created all my DB's and tables using the `postgres` user, and then subsequently ran the permissions script for the `HasuraUser` user.

So, when I log on using the `postgres` user, I can see the PK, and have access to the `_by_pk` helpers. But, when I use the `HasuraUser` login, I cannot.

**Comment by go4cas** [comment]
Confirmed that `alpha34` fixes this issue.
