### ISSUE TITLE
Memory usage for schema migration has increased from alpha31 to alpha33

### ISSUE THREAD

**Issue by elgordino** [hasura/graphql-engine#1273]
I have a fairly large migrations file (8751 lines) which is applied to an empty schema. Between alpha-31 and 33 the RAM needed to apply the migration has increased by over 100%.

In alpha-31 it was possible to successfully apply this to a Hasura Fargate task running in 0.5GB RAM.

In alpha-33 trying to apply the migration with a 1GB task or less causes the task to be terminated for using too much RAM. Adjusting the task to run in a 2GB task allows the migrations file to be applied successfully.

After the schema is applied the task will run successfully in 0.5GB.

The migrations file has been posted in a private discord chat, LMK if you want a copy.

**Comment by 0x777** [comment]
Fixed in 7b5bbb758a14d775f4ca2d1b5f9f8570972f6624
