### ISSUE TITLE
delete mutation error can be unclear

### ISSUE THREAD

**Issue by elgordino** [hasura/graphql-engine#1274]
I have a `bar` that has a join table entry in `foos_bars`. There are delete security rules on both the `bar` and the `foos_bars` tables. The `bar` table simply checks the `user` relationship, the `foos_bars` traverses the `bar` relationship to also check the same `user` relationship.

It is understandable that the `foos_bars` record must be removed first so its security rules can be validated and indeed that works fine.

While developing I had the mutation try to delete `bar` before `foos_bars` eg:

```mutation delete_bar {
  delete_bar(where: {id: {_eq: "1"}}) {
    affected_rows
  }
  delete_foos_bars(where: {barId: {_eq: "1"}, fooId: {_eq: "2"}}) {
    affected_rows
  }
}
```

and this was the error given

    {"path":"$","error":"postgres tx error","code":"postgres-error"}]

Is it possible to improve this error so that it is clearer it is being caused by the security rules? The mutation with `bar` before `foos_bars` works fine for the admin user because the relationship is `deferrable initially deferred`

**Comment by m-haziq** [comment]
You can improve the message by setting "On Delete Violation"  and "On Update Violation" on foreign key fields. For example, in my case I had it set at "No Action", which gave this error from postgres. I improved the error message in my case by changing it to "Restrict."
![image](https://user-images.githubusercontent.com/20089858/75227827-ba61b100-57d0-11ea-8e20-2cfca2e4ba57.png)

**Comment by manasag** [comment]
This issue has not attracted significant attention for a long period of time, and since alternatives are available, we are closing this.
Please feel free to reopen if the issue is still relevant for you.
