### ISSUE TITLE
GraphQL schema export error

### ISSUE THREAD

**Issue by hotgen** [hasura/graphql-engine#1275]
I'm following this steps:

https://docs.hasura.io/1.0/graphql/manual/schema/export-graphql-schema.html

```
gq http://localhost:8080/v1alpha1/graphql --introspect > schema.graphql
Executing query... error
Error:  Error: temp_user_avg_order_by fields must be an object with field names as keys or a function which returns such an object.
```

temp_user is the table name

hasura v1.0.0-alpha33

**Comment by hotgen** [comment]
The error shows up when i add this table:
```
create table "temp_user" (
  email varchar(320) primary key,
  ...
);
```

**Comment by 0x777** [comment]
@hotgen This is related to https://github.com/hasura/graphql-engine/issues/1247

**Comment by 0x777** [comment]
Closing in favor of #1247
