### ISSUE TITLE
support interface and union types for remote graphql schemas

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1276]
Currently if remote schemas has interfaces, hasura throws an error.

**Comment by ecthiender** [comment]
@coco98 this is current limitation which is mentioned in the docs: https://docs.hasura.io/1.0/graphql/manual/remote-schemas/index.html#step-1-write-a-custom-graphql-server

The relay spec needs support for interfaces, hence with the support for relay spec interfaces will be supported.

**Comment by dsandip** [comment]
@coco98 @ecthiender @0x777 From our recent conversations, it didn't look like there's a hard dependency on Relay for supporting interfaces in remote graphql schemas.
