### ISSUE TITLE
Remote Schema aliasing bug

### ISSUE THREAD

**Issue by ronanyeah** [hasura/graphql-engine#1277]
`hasura/graphql-engine:v1.0.0-alpha33`
```
{
  search(query: "yeah") {
    name
  }
}

// returns

{
  "data": {
    "search": [
      {
        "name": "songname"
      }
    ]
  }
}
```
vs
```
{
  search(query: "yeah") {
    nameTest: name
  }
}

// returns

{
  "data": {
    "search": [
      {
        "nameTest": null
      }
    ]
  }
}
```
This query is handled by a remote schema using Node.js + https://github.com/prisma/graphql-yoga.

**Comment by ecthiender** [comment]
Hi @ronanyeah ! I was unable to reproduce the issue.

I tried https://demo-graphql-yoga.glitch.me/ as a remote schema and both the following queries work:

```graphql
query {
  hello
}
```
results in:
```json
{
  "data": {
    "hello": "Hello World"
  }
}
```
and then with aliasing:
```graphql
query {
  foo: hello
}
```
with the result:
```json
{
  "data": {
    "foo": "Hello World"
  }
}
```

I also added a custom graphql server (with graphene), and the following queries work:

```graphql
query {
  person_ {
    id
    name
  }
}
```
results in:
```json
{
  "data": {
    "person_": {
      "id": 42,
      "name": "Arthur Dent"
    }
  }
}
```
and then with aliasing:
```graphql
query {
  person: person_ {
    user_id: id
    name
  }
}
```
with the result:
```json
{
  "data": {
    "person": {
      "user_id": 42,
      "name": "Arthur Dent"
    }
  }
}
```
--
 
Can you check if your remote server responds correctly if you query it directly? Let me know if there are more specific details that I'm missing.

**Comment by ronanyeah** [comment]
Thank you for the fast response. I'll will provide more information this evening.

**Comment by ronanyeah** [comment]
My apologies, I can replicate the error hitting the api directly so it appears to be a problem on the `graphql-yoga` side. I should have caught this :disappointed:
