### ISSUE TITLE
Data UI JS error on relation with a view without FK

### ISSUE THREAD

**Issue by iam4x** [hasura/graphql-engine#1278]
Follow up from here: https://github.com/hasura/graphql-engine/issues/1167

Hi 👋 

I have an issue, after creating my new relationship the UI for data schema crash (JS error) with the message "Something went wrong"

If I remove the relationship directly in the database it works again. I've traced the JS error to this line: https://github.com/hasura/graphql-engine/blob/c3f4c35141f1187fc2f0f107158c1dff26f34568/console/src/components/Services/Data/TableRelationships/autoRelations.js#L110

Here is my faulty `hdb_relationship` row:

<table>
    <tr>
        <th>table_schema</th>
        <th>table_name</th>
        <th>rel_name</th>
        <th>rel_type</th>
        <th>rel_def</th>
        <th>comment</th>
        <th>is_system_defined</th>
    </tr>
    <tr>
        <td>public</td>
        <td>orders</td>
        <td>states</td>
        <td>array</td>
        <td>&#123;&#34;manual_configuration&#34;: &#123;&#34;remote_table&#34;: &#34;orders_states&#34;&#44; &#34;column_mapping&#34;: &#123;&#34;id&#34;: &#34;resource_id&#34;&#125;&#125;&#125;</td>
        <td>NULL</td>
        <td>f</td>
    </tr>
</table>

Did I missed something or this is a bug? Thank you.

**Comment by iam4x** [comment]
Hi,

* table order: id, code
* table states: id, name, resource_id, resource_type
* view order_states: 
	* `create view order_states as select * from states where resource_type = 'orders'`;

This should do the trick, do you want a .sql to import? I can do a minimal-repro case.

**Comment by iam4x** [comment]
Huh, with this simple example I submitted, I cannot reproduce the bug.

My database is pretty complex, I'm going to investigate more and find out what is causing the bug 👍

**Comment by iam4x** [comment]
Okey @karthikvt26 this is happening when the table where you create the relation has a foreign_key that references itself:

```
Human
-----
id: int
child: fk -> human.id
parent: fk -> human.id



Names (polymorphic)
-----
id: int
value: text
resource_id: int
resource_type: text (ex: human)



Human_Names (PostgreSQL view)
-----------
create view human_names as select * from names where resource_type = 'human';
```

When you create the array relationship of human (table) <-> human_names (view) the error happens.

If you need more informations I'll be happy to help.

**Comment by iam4x** [comment]
This introduce another bug, the relation is not tracked correctly after added (the foreign_key referencing the same table)

![jan-04-2019 16-04-12](https://user-images.githubusercontent.com/893837/50694542-6c24a800-103a-11e9-8cac-b9209b1b3d97.gif)

It's easier to explain with a GIF, I think it's related.

**Comment by iam4x** [comment]
I've fixed the two bugs into my PR, looks good to me, waiting on you answer 👍

**Comment by dsandip** [comment]
@karthikvt26 @arvi3411301 Can this issue be closed? The associated PR has been marked as closed as Arvi's already taken care of it.
