### ISSUE TITLE
Support OpenAPI/Swagger for remote schemas

### ISSUE THREAD

**Issue by patcito** [hasura/graphql-engine#1279]
OpenAPI is a standard based on swagger and many API providers support it such as [Stripe](https://github.com/stripe/openapi). 

This would allow instant access to [many legacy REST APIs](https://github.com/APIs-guru/openapi-directory/tree/master/APIs) that have openapi specs 

The feature would work as such:
- add remote schema
- instead of setting a remote url, the user would upload an openAPI yaml spec file such as this one from [Stripe](https://github.com/stripe/openapi/blob/master/openapi/spec3.yaml)
- hasura generates a graphql schema from this file

Prior art:
There are already a few openapi to graphql libraries including:
- https://github.com/graphql-perl/GraphQL-Plugin-Convert-OpenAPI
- https://github.com/apollographql/swapi-rest-graphql
- https://github.com/graphql-binding/graphql-binding-openapi

Bonus: the cool thing about this is that if we get openapi + #1225 implemented, we could get something like https://www.onegraph.com/ for free with Hasura.

**Comment by tirumaraiselvan** [comment]
This might be helpful: https://github.com/strongloop/oasgraph

**Comment by jasonmccallister** [comment]
@patcito I am sitting at GlueCon Unconference and OpenAPI is here discussing how this should be an option for GraphQL Engines to integrate with existing Open APIs.

**Comment by DblK** [comment]
In the REST service I develop, I always add an endpoint `/swagger.yaml` to expose the documentation of the service.
In the step 2 of the issue, I would suggest to either upload the yaml or to specify and endpoint to let hasura download and maybe upload by itself in case of remote service changes.
The copy/paste could be there too.

Thanks

**Comment by rahulagarwal13** [comment]
Hey folks, thanks for your interest in this feature. Wanted to provide an update that in the [2.16 release](https://hasura.io/changelog/cloud/v2.16.0-cloud.1), we have introduced a console-based feature (as alpha/experimental) to import an OpenAPI spec.

You need to first turn it on by going to the feature flag section under settings and then head over to create action form where you will see a new button "Import from OpenAPI" in the Action definition section. [Here](https://hasura.io/docs/latest/actions/open-api/) is the doc page for it. 

We have begun work on the beta version (which includes enhanced console design and support of new types of OAS endpoints) and will soon share a detailed RFC for it. Would love to get you as a design partner. Please try the feature out using OAS endpoints (such as [petstore](https://petstore3.swagger.io/)) and let us know any feedback that will help us improve.

![image](https://user-images.githubusercontent.com/111393043/209882494-70efd805-82ff-4648-9de8-137c33f0b206.png)

**Comment by manasag** [comment]
The feature has been delivered (See Rahul's note above), hence closing this.
