### ISSUE TITLE
Bug report: Invalid type with introspection query

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#1281]
When i make an introspection query to find out fields and its type 
```
query {
  __type(name: "table_name") {
    fields {
      name
      type {
        name
        kind
      }
    }
  }
```
There're some fields which returns valid type name, but there're some fields which returns `null` for type name.

Expected behaviour: `type name` should return valid type which's defined in Console UI.

**Comment by 0x777** [comment]
@revskill10 The behavior is as per the GraphQL spec. The fields for which you are seeing `name` as `null` are either non-null/list types ([4.5.2.7](https://facebook.github.io/graphql/June2018/#sec-Type-Kinds.List), [4.5.2.8](https://facebook.github.io/graphql/June2018/#sec-Type-Kinds.Non-Null)). You'll need to use `ofType` field to dig into a list/non-null type. Something like this probably (you can take a look at the introspection query used by the official graphiql package): 
```graphql
query {
  __type(name: "albums") {
    fields {
      name
      type {
        name
        kind
        ofType {
          name
          kind
          ofType {
            name
            kind
          }
        }
      }
    }
  }
}
```

**Comment by PierBover** [comment]
In case anyone stumbles upon this, here is another explanation for this behavior:

> id looks a bit weird there, it has no name for the type. That's because it's a "wrapper" type of kind NON_NULL. If we queried for ofType on that field's type, we would find the ID type there, telling us that this is a non-null ID.

https://graphql.org/learn/introspection/
