### ISSUE TITLE
Enhancements for production use

### ISSUE THREAD

**Issue by theshire-io** [hasura/graphql-engine#1283]
A list of would-be-great-to-have features for production use, via flags:

#### Denial of service attack prevention:

- Query depth limit.
- Transparently enforce pagination via limit on all queries.
- Query cost analysis - if a query is too expensive, block it. 

The last one superceeds the other but I suppose is much more complex to implement.

#### Limiting information disclosure:
- Disable introspection.

**Comment by 0x777** [comment]
@theshire-io Would query white listing solve these issues for you? You get to specify the list of queries that are allowed and every other query is denied.

**Comment by theshire-io** [comment]
@0x777 That's a great idea!

**Comment by cj** [comment]
It would be great to hide the visibility based on the user (or white-list it as you suggested) i.e. http://graphql-ruby.org/authorization/visibility.html, http://graphql-ruby.org/authorization/accessibility.html and http://graphql-ruby.org/pro/authorization.html#visibility-authorization.

@0x777 is it currently possible to disable introspection in production?

**Comment by dsandip** [comment]
@theshire-io @cj @arpitjacob query whitelisting is being tracked here #989. Closing this issue in favor of that one and tagging you'll there so you can subscribe to updates.

**Comment by kriswep** [comment]
I feel there's a different, but important, use case for the features mentioned by @theshire-io above. These would help to secure against arbitrary queries, e.g you have an open APi and don't control the clients.
Query whitelisting would only be useful for known / your own clients.
Would love to see solutions for the open clients use case, like the ones mentioned above. See Max Stoibers' [securing GraphQL APIs article](https://blog.apollographql.com/securing-your-graphql-api-from-malicious-queries-16130a324a6b) for further information. 

Right know I guess you would need to add another public facing server...
