### ISSUE TITLE
Todo app auth0 database migration doesn't work. Table created, but metadata missing

### ISSUE THREAD

**Issue by DerekLiang** [hasura/graphql-engine#1290]
I followed the todo-auth0 README. 

The migration was applied successfully shown below. 

However when I went to the Hasura Console, under the data Tab, it prompted me that the `todo` table was in the **Untracked tables or views**. After the `todo` table was added, there was no user role under the permissions tab, and all the settings in `1536761653464_init.up.yaml` was **not** applied.

Help is much appreciated!

```
>hasura version
hasura CLI version: v0.4.25
GraphQL Engine CLI version:  v1.0.0-alpha33
GraphQL Engine Server [https://***.herokuapp.com] version: v1.0.0-alpha33

>hasura migrate status 
VERSION        SOURCE STATUS  DATABASE STATUS
1536761653464  Present        Not Present

>hasura migrate apply
• migrations applied

>hasura migrate status
VERSION        SOURCE STATUS  DATABASE STATUS
1536761653464  Present        Present
```

**Comment by praveenweb** [comment]
Seems like the metadata.yaml file is missing. It should ideally have the tables, relationships and permissions to be tracked. The yaml file inside the migrations folder currently sets only permissions. Will update that file to include the necessary table/relationship tracking queries.
