### ISSUE TITLE
[Event Triggers] delivered time on console is off

### ISSUE THREAD

**Issue by moksahero** [hasura/graphql-engine#1309]
![processed savealgoliauser event triggers hasura 1](https://user-images.githubusercontent.com/700960/50687672-3218cd80-105d-11e9-96aa-94244bad7111.png)
![processed savealgoliauser event triggers hasura](https://user-images.githubusercontent.com/700960/50687673-3218cd80-105d-11e9-8211-0a7053c80bd7.png)

**Comment by tirumaraiselvan** [comment]
@moksahero Are you by any chance at GMT + 8  hours?

**Comment by tirumaraiselvan** [comment]
Seems like the time is parsed in local time but incorrectly shows GMT. @arvi3411301 Can you please take a look?

**Comment by moksahero** [comment]
yes I'm in Malaysia now so I'm in GMT+8
