### ISSUE TITLE
Integrating Hasura with cloud image service

### ISSUE THREAD

**Issue by hooopo** [hasura/graphql-engine#1318]
is there a sample or doc for image uploading? I don't know if i miss it. thanks.

**Comment by 0x777** [comment]
You have a couple of options:
1. If you are storing very small files (~1MB), you can save it as a `base64` encoded text. Please read the caveats [here](https://wiki.postgresql.org/wiki/BinaryFilesInDB).
2. Save it using a non-GraphQL interface (your own custom rest endpoint or an external service) and then save the unique id in the database using GraphQL.

There seems to be some community work in making files work with GraphQL with projects such as [this](https://github.com/jaydenseric/graphql-multipart-request-spec) but we don't support it [yet](https://github.com/hasura/graphql-engine/issues/1326).

**Comment by hooopo** [comment]
Thanks, is there plans to integrate cloudinary or aws s3 service in Hasura?

**Comment by marionschleifer** [comment]
@hooopo please find a blog post about building file uploads/downloads [here](https://blog.hasura.io/building-file-upload-downloads-for-your-hasura-app/). I'm changing this issue to be a feature request for a possible integration.

**Comment by tirumaraiselvan** [comment]
I don't think we will have a native integration with a image upload service. This will have to be done through community tooling over the graphql interface that hasura provides.

I am closing this issue because it isn't part of roadmap.
