### ISSUE TITLE
Error in log "pgcrytpo"

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [hasura/graphql-engine#1322]
![image](https://user-images.githubusercontent.com/696713/50737469-63ff7080-11d2-11e9-9643-f59026d8dac4.png)

**Comment by Pomazan-Bogdan** [comment]
I like this newbie confused

**Comment by shahidhk** [comment]
@Pomazan-Bogdan Can you execute this SQL on the database?

```
psql <database-url> -c 'CREATE EXTENSION pgcrypto;'
```

Hasura needs this extension to handle UUID types. 

If you're connecting as a non-super user, checkout this guide to see what are the required permissions etc: https://docs.hasura.io/1.0/graphql/manual/deployment/postgres-permissions.html

**Comment by Pomazan-Bogdan** [comment]
pgcry**TP**o

see screenshot

**Comment by 0x777** [comment]
The help message has the typo. We'll fix this. However if you create the extension as Shahidh has suggested/or start graphql-engine with a superuser, you shouldn't be seeing this error.

**Comment by ecthiender** [comment]
@Pomazan-Bogdan it looks this error will only occur if the postgres instance does not have the pgcrypto extension available. Usually, pgcrypto extension is available by default. 

Would you comment on what postgres distribution you are using (such that the pgcrypto extension is not available by default)?

**Comment by Pomazan-Bogdan** [comment]
I've put the expansion through the addition of a bundle of contributions.
There are no problems with this

The problem was simply a typo in the log, because I did not want to gobble up what I needed, and after 5 minutes I realized that something was wrong.

**Comment by ecthiender** [comment]
Absolutely, understand the issue with the typo.

Just wanted to know how did you install postgres. Or what distribution you
are using.

**Comment by Pomazan-Bogdan** [comment]
centos 7
add repo postgress 11
just in all the installation instructions did not mention the -contrib package
