### ISSUE TITLE
support blacklisted JWTs

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#1327]
If JWTs are blacklisted, currently we don't have a mechanism to let the developer disallow these tokens in graphql-engine. A simple implementation is to poll an endpoint for blacklisted tokens. These tokens can be stored in a hashset.

**Comment by manasag** [comment]
At industry level, it's not best practise to store JWTs, as it comes at the cost of querying the datastore for the blacklisted tokens. It's recommended to issue short lived tokens instead.
We don't plan to support this feature, hence closing this issue.
