### ISSUE TITLE
Renaming Relationship

### ISSUE THREAD

**Issue by DblK** [hasura/graphql-engine#1329]
When I added all relationships available, there are all name *table*By*key* or something similar.
Sometime the name please me sometime not. But I can't rename the field.

The only way to "rename" it, is to delete and make it again manually including the finding of the key and table. A rename button would help a lot.

**Comment by coco98** [comment]
@praveenweb @0x777 Any comments on whether we can have a rename relationship metadata API?

**Comment by 0x777** [comment]
It is about time we had this. However this will take some effort as we will also need to rewrite the permissions with the new name.

**Comment by 0x777** [comment]
@DblK Closing this in favor of https://github.com/hasura/graphql-engine/issues/79

**Comment by DblK** [comment]
Since there were no description inside the #79 I thought it was renaming table from the source and not from hasura perspective (graphql only). If it's the case, that is fine for me ;)
