### ISSUE TITLE
Clarify the scope of the license

### ISSUE THREAD

**Issue by kulshekhar** [hasura/graphql-engine#133]
With most of us not being lawyers, it might be helpful to have a simple explanation on the obligations and permissions that come with the AGPL license for the graphql engine.

Based on a discussion in Discord, I understand that this is supposed to be similar to MongoDB in that 
- any modifications/improvements to the graphql-engine itself must be released as open source
- it doesn't require user apps to release the source code if they're merely using the graphql-engine and don't offer the engine's functionality (as is or improved) as a service.

Maybe adding something similar to the following might help?
- https://www.mongodb.com/community/licensing
- https://www.mongodb.com/community/licensing/faq
- https://www.mongodb.com/blog/post/the-agpl

**Comment by shahidhk** [comment]
Hello @kulshekhar, thanks for bringing this up. We have added some clarifications as a [wiki page](https://github.com/hasura/graphql-engine/wiki/License-Explained) and linked it on the readme. Hope it makes sense.

**Comment by masonhensley** [comment]
Thanks for pointing this out @kuldhekhar - currently, this would be a deal breaker for many organizations based on my previous experience with internal open source compliance rules. 

The commercial licensing reference in the readme could also give many pause since I didn’t see a “pro” offering or is it commercial support? What are the requirements for commercial use?

Hopefully this provides some context to the hasura team. Cool project!

**Comment by kulshekhar** [comment]
@shahidhk thanks for the quick response. The update addresses this issue, hence closing this :slightly_smiling_face:

**Comment by dsandip** [comment]
@masonhensley Thank you! Yes, the README needs to further clarify the commercial license bit. FYI, you can check out the [pricing page](https://hasura.io/pricing) for the "Pro" offering. Will keep this issue open till that happens.

**Comment by dsandip** [comment]
@masonhensley The [README](https://github.com/hasura/graphql-engine/blob/master/README.md#license) and the [license wiki](https://github.com/hasura/graphql-engine/wiki/License-Explained) have both been updated. Please comment or reopen the issue if you think more information is needed.
