### ISSUE TITLE
support user info variables as lists to be used in permissions

### ISSUE THREAD

**Issue by ecthiender** [hasura/graphql-engine#1333]
Right now the user info variables (as headers, from JWT claims or from webhook response) are converted into map of strings to strings. Support should be added for lists as well. Then in the permission system `_in` can be used with session variables.

See #1314

**Comment by lanex-victor** [comment]
Definitely looking forward for this to be added. Hope sooner..

**Comment by belgiancoder** [comment]
For string columns you can send `"X-Hasura-Variable"`:`(${IdArray.join("|")})`
Then restrict
```
{
    id: _similar: "X-Hasura-Variable"
}
```
It is a REGEX-like. `id1` will match `(id1|id2|id3)` but not `id4`
Only works for strings tho.

**Comment by 0x777** [comment]
added in https://github.com/hasura/graphql-engine/commit/f1cf6d0b172e99e439c0a4d5157293422f4a4e59. See #2475
