### ISSUE TITLE
Improve console crash page

### ISSUE THREAD

**Issue by karthikvt26** [hasura/graphql-engine#1340]
Need to have an informative page instead of the following

![screenshot 637](https://user-images.githubusercontent.com/25095884/50817630-74d2f200-134a-11e9-845e-0401f40d2f59.jpg)

@dsandip can you take a look at this? 

one idea praveen suggested is: Have a link on the page which will take you to graphql engine issues page?

**Comment by coco98** [comment]
Yeah. A nice looking page with an option to create an issue on github or talk to us on discord might work well.

**Comment by Pomazan-Bogdan** [comment]
i del all table scheme
![image](https://user-images.githubusercontent.com/696713/50859556-585fa580-139c-11e9-892f-e2cbd91d52bf.png)

**Comment by AnnieAtHasura** [comment]
Assigning to you, requesting you close as dup #272
