### ISSUE TITLE
Log and views  "more than one foreign key constraint exists on the given column"?

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [hasura/graphql-engine#1346]
Good afternoon, I model the database in an external designer, where I create links between tables.

![image](https://user-images.githubusercontent.com/696713/50851843-a1a4fa80-1386-11e9-90bd-bbce04dd4814.png)
After synchronizing the database schema with the database itself, I successfully initialize the tables in hasura
![image](https://user-images.githubusercontent.com/696713/50851928-d4e78980-1386-11e9-9ab6-ccc6163f6244.png)

Immediately after synchronization, if you look at the console, dependencies in the tables do exist.
But, in itself, Hasura offers to implement the track dependencies
But they are not "tied", since they already exist.
![image](https://user-images.githubusercontent.com/696713/50852041-28f26e00-1387-11e9-8fb9-1496f9d64b56.png)

**Comment by coco98** [comment]
@Pomazan-Bogdan Hm..this should not be happening. Hasura's GraphQL relationships are not dependent on foreign keys, but Hasura will suggest that you can create relationships based on the foreign keys. You can create relationships on Hasura by manually specifying join columns even if there are no foreign keys.

Can you paste a screenshot of what your relationships tab on the hasura console for the `content_news` table looks like? Might help us understand what's going wrong.

**Comment by Pomazan-Bogdan** [comment]
![image](https://user-images.githubusercontent.com/696713/50858921-8ba13500-139a-11e9-9b50-949e90832982.png)

**Comment by Pomazan-Bogdan** [comment]
I previously modeled on two tables and a related key, and hasura tracked connections successfully.


I need to find a working principle, according to which I can successfully connect a Hasura from scratch to an already developed database.

**Comment by Pomazan-Bogdan** [comment]
add manual
![image](https://user-images.githubusercontent.com/696713/50859207-68c35080-139b-11e9-93c5-0a29a3b5a9d0.png)

**Comment by Pomazan-Bogdan** [comment]
![image](https://user-images.githubusercontent.com/696713/50859288-a7f1a180-139b-11e9-9d2e-f365b5051eb7.png)

**Comment by Pomazan-Bogdan** [comment]
But I remember exactly that Hasura was able to create connections herself before, and called them herself and could be used in queries.

**Comment by Pomazan-Bogdan** [comment]
If I add tables one by one, one by one, and after adding this I add links, then everything happens well.
![image](https://user-images.githubusercontent.com/696713/50861735-46810100-13a2-11e9-8dc4-834abf7e40f6.png)

**Comment by Pomazan-Bogdan** [comment]
If I generate a request in the SQL designer, I make it in phppgadmin, with this I build all the tables and links, then all the tables are tracked and the links to them are also

**Comment by Pomazan-Bogdan** [comment]
Again.
1. Reset
2. Reload page /data
3. 
![image](https://user-images.githubusercontent.com/696713/50954665-ba64fb80-14bf-11e9-9d5c-4b37d62819e7.png)
4. Untracked tables or views "Add All"
![image](https://user-images.githubusercontent.com/696713/50954694-d1a3e900-14bf-11e9-82a8-d32bce821a05.png)
5. There are 110 untracked relations "Track All Relationships"
6. Fail
![image](https://user-images.githubusercontent.com/696713/50954721-dcf71480-14bf-11e9-8c99-6236d817d5a2.png)
7. Views table for relationship:
![image](https://user-images.githubusercontent.com/696713/50954803-192a7500-14c0-11e9-8d4e-d79da911e308.png)

Yesterday I did this procedure many times with success.

**Comment by Pomazan-Bogdan** [comment]
I anderstend
"more than one foreign key constraint exists on the given column"

Need log this key

**Comment by Pomazan-Bogdan** [comment]
Yes. I manual add key end find block key.
Del, and all ok.

Sorry)

**Comment by marionschleifer** [comment]
Hi @Pomazan-Bogdan, I'm closing this issue. If you have any additional questions, please feel free to re-open it 🙂
