### ISSUE TITLE
 X-Hasura-Access-Key should be renamed to X-Hasura-Secret-Key to make it more obvious

### ISSUE THREAD

**Issue by patcito** [hasura/graphql-engine#1347]
Maybe X-Hasura-Access-Key should be renamed to X-Hasura-Secret-Key to make it more obvious. Like all oauth providers (google, github etc) tend to call their private keys secret_<provider>_key and their public key public_<provider>_id.

Also, maybe the permissions tab should be disabled when access key is not set to make it more obvious.

**Comment by ecthiender** [comment]
We are probably renaming it to `X-Hasura-Admin-Secret` to make it super explicit. @nizar-m pls to confirm.
