### ISSUE TITLE
Feature request: Allow option to expose an event trigger as subscription

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#1355]
Currently, Hasura only exposes event trigger to another backend via HTTP request.

My request is, allow configure for an event trigger to be exposed as a subscription also.

Why ?
In some cases, we want the frontend to be informed directly from any changes from database, no need for 3rd backend to do process, or no need to create another table to store that events, for example, stale notification.

Spec:
No change to existing system, just add one more option to specify should current event trigger be exposed through subscription or not.
```
subscription {
users_created {
<current event data}
}
}

**Comment by revskill10** [comment]
This is invalid for large number of http client. Close now.

**Comment by coco98** [comment]
As per discussion with @revskill10 on discord this is hard for the graphql client because this will inevitably result in dropped events. 
Live queries are easier to reason about on the client. 

We should definitely talk about the design & the workaround to achieve the same behaviour as what @revskill10 wanted using live-queries.

**Comment by jafri** [comment]
This is an interesting problem, we want to send a custom message to all clients connected to Hasura when a custom event is triggerred. It doesn't have to be part of the live query, but perhaps some other way over the same websocket?

**Comment by coco98** [comment]
@jafri Why not create a notifications table and just add a notification to it with a created timestamp. You can keep the notification table public and any client can subscribe to it for `notifications.created_at > last_seen_timestamp_on_client`.

**Comment by revskill10** [comment]
@coco98 A documentation on this issue is helpful i think. I'll try to implement and contribute if possible.
