### ISSUE TITLE
Update deploy on kubernetes docs with a section on how to use secrets

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1356]
Via email:
> Just to give you some context, I'm following https://docs.hasura.io/1.0/graphql/manual/deployment/kubernetes/index.html, and I see that the only way - in my understanding - to set up the DB connection with kubernetes is to use the HASURA_GRAPHQL_DATABASE_URL. However, I already have some secrets set up with dbname/username/password and I didn't want to create yet another secret when I could (in theory) just interpolate the data I have. I've tried this:
> 
> 
>         - name: POSTGRES_DATABASE
>           valueFrom:
>             secretKeyRef:
>               name: secret-name
>               key: db
>         - name: POSTGRES_USERNAME
>           valueFrom:
>             secretKeyRef:
>               name: secret-name
>               key: username
>         - name: POSTGRES_PASSWORD
>           valueFrom:
>             secretKeyRef:
>               name: secret-name
>               key: password
>         - name: HASURA_GRAPHQL_DATABASE_URL
>           value: postgres://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@server:5432/$(POSTGRES_DATABASE)
> 
> but I'm getting a Fatal Error : Invalid database-url (HASURA_GRAPHQL_DATABASE_URL). Example postgres://foo:bar@example.com:2345/database
> long story short: string interpolation works, but not with secrets :)
> 
> Is there any way I can just specify env variables for username/pwd/dbname? 

--------------------

Fix:

> I might have found an issue :) I had a pwd with special chars (!@ etc), using another user without special chars in the pass worked :) shame

@shahidhk the direct env vars should have worked no?
@rakeshkky Is there a problem with handling special characters in the `database_url` string

**Comment by MelaHub** [comment]
I experienced this behavior today - let me know if I can help you reproducing it! Password had ! ] * < in it, I was able to launch Hasura correctly after removing those chars.

**Comment by shahidhk** [comment]
@coco98 @MelaHub Special characters in the database url should be URL encoded. E.g. `%40` for `@`.

In case of secrets, the actual secret (say password) should be url encoded and then saved into the k8s object.

Using separate flags (`--host`, `--user` etc.) does not have to be url encoded.

**Comment by coco98** [comment]
Shouldn’t we update docs with a few example use cases?
Using K8s secrets
Using database URLs with special characters

Let’s create 2 docs issues?

**Comment by shahidhk** [comment]
@rikinsk already added database url use-cases: #1359

Using k8s secret in deployment is considered common knowledge. We can provide a detailed guide on GKE instructions. #1386

**Comment by MelaHub** [comment]
@shahidhk of course my password was encoded :) when using kubectl create secret the pwd is automatically encoded in base64!
And this problem does not happen with a alphanum pwd

**Comment by shahidhk** [comment]
@MelaHub You password was URL encoded (`%24` for `$`, `%40` for `@` etc.) and yet it didn't work?
