### ISSUE TITLE
compatibility with OpenCRUD

### ISSUE THREAD

**Issue by mingzhou** [hasura/graphql-engine#1358]
Is Hasura GraphQL-Engine compatible with [OpenCRUD](https://github.com/opencrud/opencrud) or any plan about this?

**Comment by lishine** [comment]
Please answer

**Comment by 0x777** [comment]
No. The spec currently looks like work in progress and it'll not be easy for us to support something which might change in future. We'll maybe revisit this when there is a release to see if it's viable to implement the spec.

**Comment by mcmar** [comment]
@0x777 
There's no chance that OpenCRUD will change in the future because Prisma is officially abandoning GraphQL and will no longer support OpenCRUD. If you supported it according to the current spec, then I'm sure plenty of Prisma customers would move over to Hasura. Don't you want their business?

**Comment by mcmar** [comment]
@0x777 If you're not going to support it, then can you at least provide examples of how to migrate from OpenCRUD with `prisma-binding` to HasuraCRUD™ with `graphql-binding`. I can setup all the tooling, but what I can't figure out is how to use the `info` object that's expecting a schema like `{ id, name }` with HasuraCRUD, which expects a schema like `{ returning { id, name } }`. I've never found a good tool to modify the info object, which means that I would have to modify my API's schema to also wrap everything inside `returning`, which would mean changing my frontend. I'd like to avoid changing the frontend, which means keeping my API schema the same, which means somehow wrapping/unwrapping the `info` object of my resolver with `returning`. If that's not possible, then there's no way for anybody to migrate smoothly from Prisma to Hasura.

**Comment by marionschleifer** [comment]
Closing this issue to keep the conversation in one place at #1358.

**Comment by coco98** [comment]
Closing this issue, because support for OpenCRUD is not planned.
We can also keep the discussion about migration from prisma in #2448 so that everything is in one place :)

**Comment by alan345** [comment]
@mcmar, what did you finally do? Have you considered migrating to prisma2 or it is not an option? Have you managed to migrate to hasura?
