### ISSUE TITLE
Without a column that can be aggregated, all introspections break.

### ISSUE THREAD

**Issue by MooreDevelopment** [hasura/graphql-engine#1365]
Figured this out today as i was working through building custom resolvers. If you have a table of all UUIDs/Timestamps then graphql-engine creates a type definition that is empty for the aggregated queries. Due to the empty type def, the schema can no longer be introspected. 

To recreate you should be able to just  create a table with all UUIDs that has data in it. then user graphcurl to introspect it and it will give you an error of "[Table_name]_avg_order_by fields must be an object with field names as keys or a function which returns such an object." because it is an empty type definition. This should be able to be fixed by using a place holder in the schema or don't generate aggregate type definitions on tables without data that can be aggregated. I worked around this by adding a random column filled with 1s.

This also breaks graphql-tools for custom-resolvers because it relies on introspection.

**Comment by coco98** [comment]
@MooreDevelopment Thanks for letting us know! We'll try to fix this asap.
@ecthiender Can you check this out?

**Comment by shahidhk** [comment]
This should have been fixed in https://github.com/hasura/graphql-engine/pull/1248 and released in `alpha34`. @rakeshkky isn't that right?

@MooreDevelopment What version are you on?

**Comment by MooreDevelopment** [comment]
I am using alpha33! I will update to alpha34 and test!
