### ISSUE TITLE
Status codes for non-fatal properties

### ISSUE THREAD

**Issue by phated** [hasura/graphql-engine#1368]
I just ran into an issue while using Apollo Client with Hasura.  Since Hasura always returns a 400 status code when there's an error in the query, Apollo Client will **always** treat that error as a `networkError` and not pull the graphql errors out of the response.

Apollo client expects a query with non-fatal errors (it seems like that means if there's a query with optional fields that fail) to return as a 200 with the `errors` property instead of the `data` property.

Can the status codes be changed in Hasura to have full compatibility with Apollo Client?

**Comment by 0x777** [comment]
The GraphQL spec doesn't say anything about the transport layer and the [HTTP best practices section](https://graphql.org/learn/serving-over-http/) on graphql.org doesn't talk about status codes. I think the only sane option left is to check what the most popular graphql clients expect and decide based on that? @coco98 @shahidhk

**Comment by pyankoff** [comment]
Related: https://github.com/hasura/graphql-engine/issues/1019
Makes hard debugging Apollo requests :(

**Comment by revskill10** [comment]
Since graphql spec supports `errors` in body response, i think treating it as error or not is client's responsibility, not server's responsibility.

Only `network error` (like being offline) is the only type of error to me.

**Comment by 0x777** [comment]
The new `/v1/graphql` will have this behaviour. Will be part of the next release.

**Comment by nlhnt** [comment]
I got the same issue when trying to use tornado.httpclient. It just tells me there's an error but doesn't say what it is.
Body seems fine- doing same request through postman works. Seems like a permission issue but I have no clue which permissions I might be lacking.

**Comment by carlosoliveiradev** [comment]
Leave a comment
