### ISSUE TITLE
Add jwt inspector to hasura console

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1369]
It would be super nice if we had a little JWT inspector within the console and also a test endpoint to test if the JWT was being verified and accepted by Hasura (to verify hasura configuration). 
Maybe a little inspect icon next to the JWT authorization header if the console detects it?

@rikinsk @karthikvt26 @praveenweb @wawhal thoughts?

**Comment by praveenweb** [comment]
@coco98 - It would be a nice feature.

However the console currently doesn't know if JWT is configured or not. If the server provides an endpoint or templates it on console, that would be easy. 

Even if JWT is configured, inspect icon next to Authorization Header will only show up when user decides to add the header manually.

So i'm thinking, may be we can have a JWT Configured badge just above the headers with Add Auth Header button which will just prefill `Authorization: Bearer ` and the user will add the token. This can also have the test endpoint.

**Comment by dsandip** [comment]
Based on a chat with @rikinsk :

1. We don't a server endpoint, if we see an `Authorization` header with a `BEARER <token>`value, we can show a `Decode` icon (tooltip: `Decode JWT`) as shown here:

![jwt inspect](https://user-images.githubusercontent.com/24300818/52952406-67c60b80-33aa-11e9-8338-d9292fe5c6d3.png)

1. From @ecthiender Use library from https://jwt.io/.

**Comment by rikinsk** [comment]
https://github.com/auth0/node-jsonwebtoken seems to be the library to use (9.6k stars)

**Comment by coco98** [comment]
Brief guide here: https://blog.hasura.io/jwt-analyzer-in-hasura-console/
