### ISSUE TITLE
Current Schema Export isn't working

### ISSUE THREAD

**Issue by estsauver** [hasura/graphql-engine#138]
Schema export is commented out in the current App.hs. I tried uncommenting it, but it seems the schema export code might have been removed?

**Comment by 0x777** [comment]
You can do this with curl: 

```
curl -XPOST -d '{"type":"export_metadata","args":{}}' <graphql-engine-url>/v1/query
```

**Comment by 0x777** [comment]
If you have added an access key, you can specify it using `-H 'Authorization: access-key'`

**Comment by estsauver** [comment]
It looks like that isn't exporting a graphql schema, it looks like it's all of the hasura metadata?

**Comment by coco98** [comment]
Just referencing the docs here too: https://docs.hasura.io/1.0/graphql/manual/schema/export-graphql-schema.html

**Comment by 0x777** [comment]
@coco98 The docs have to be updated with the commands from my comment. We removed the `schema` endpoint from the current releases as there is enough community tooling around this.

**Comment by shahidhk** [comment]
Docs have been updated.
