### ISSUE TITLE
allow disabling prepared statements globally

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#1392]
It helps us to debug issues with prepared statements.

**Comment by nizar-m** [comment]
hasura/pg-client-hs#3

**Comment by beepsoft** [comment]
Will this be also settable via an environment variable in docker?

**Comment by nizar-m** [comment]
> Will this be also settable via an environment variable in docker?

Yes, by setting 
`HASURA_GRAPHQL_USE_PREPARED_STATEMENTS=false`
