### ISSUE TITLE
condition based on table data itself

### ISSUE THREAD

**Issue by deemaagog** [hasura/graphql-engine#1394]
Hi. First of all thank you for this wonderful project

It's unclear from documentation how do I query like this one:
sql: 
Select first_name from users where first_name = last_name
graphql: 
query {
   users (where: {first_name : {????} ) {
   first_name
  }
}

**Comment by 0x777** [comment]
Hi @deemaagog, currently we do not have support for operators which work on columns of same table. This is being tracked [here](https://github.com/hasura/graphql-engine/issues/457). 

A quick and dirty workaround is to use a view as follows:

```sql
create view users_v as select u.*, (u.first_name = u.last_name) as has_same_name from users u;
```

Then you can query it as follows:
```graphql
{
  users_v(where: {same_name: {_eq: true}}) {
    first_name
  }
}
```
