### ISSUE TITLE
Can't delete column because of select permissions on the column

### ISSUE THREAD

**Issue by nukinuki** [hasura/graphql-engine#1395]
Can you remove permissions automatically prior to column deletion?

The pain is with column rename, which is not supported yet. Process of renaming a column is really cumbersome:
1. Add new column
2. Remove Select permissions for every role on the old column
3. Delete old column
4. Add Select permissions for every role on the new column

**Comment by coco98** [comment]
@0x777 @praveenweb There is an API call to cascade delete to permissions right? Can you put an example and link to docs?
Also related to landing #244

**Comment by coco98** [comment]
Till we support this with a rename API, this might be a _mildly_ more convenient workflow:

1. Add new column
2. Remove old col, add new col to permission
3. Delete old column

**Comment by 0x777** [comment]
This has been one of our longstanding issues. We'll try to fix this as soon as possible. You can track this [here](https://github.com/hasura/graphql-engine/issues/79).

**Comment by dsandip** [comment]
@nukinuki Tagged you on #79 and closing this.
