### ISSUE TITLE
support uuid type in console

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#142]
While `UUID` type is natively supported in Postgres, `pgcrypto` extension has to be enabled to add a default value.

Without default value: 
```plpgsql
CREATE TABLE article ( 
  id UUID PRIMARY KEY,
  title TEXT NOT NULL
)
```

With default value:
```plpgsql
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE article (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL
);
```

**Comment by shahidhk** [comment]
via [michael](https://app.intercom.io/a/apps/rucirpb3/users/5b4ccdd3283a498d379728a0/all-conversations) in intercom.
