### ISSUE TITLE
How to use x-hasura-allowed-roles with webhooks

### ISSUE THREAD

**Issue by plmercereau** [hasura/graphql-engine#1420]
Hello,
I see there is some documentation on how to use 'x-hasura-allowed-roles' with JWT, but I can't make it work with webhooks.
My use case is that each user can have multiple roles, and that I would like to test each of the permissions defined in the console.
Here is an example of the payload:
```json
{
  "X-Hasura-Role": "user",
  "X-Hasura-User-Id": "an-user-id",
  "X-Hasura-Allowed-Roles": [
    "manager",
    "user"
  ]
}
```
In this case, I have an error "expected Text, encountered Array". But even if I pass a stringified value such as `"[manager,user]"` or `"[\"manager\",\"user\"]"` the 'manager' permissions don't apply...
Can you tell me if it could work, and if it can, what would be the way to proceed?
Thanks in advance!

**Comment by coco98** [comment]
Hi!

Allowed Roles is used only for JWTs and not webhooks. The idea with a
webhook is that you  should know exactly which role you want to run as.

So, your webhook should return only a particular x-hasura-role that you
want to use at that instant. Which means either manager or user.

**Comment by plmercereau** [comment]
Thanks for the prompt reply!
I don't get why this is not something I should not try do to with webhooks, but at least I now know I am trying to do something that is not possible!
Thanks anyway, I will think about a workaround in my application logic.
Cheers!

**Comment by plmercereau** [comment]
Thanks for the clarification @ecthiender ! I think it makes sense!
I am prototyping a stack that can be embedded into a local docker swarm with no or little access to the internet. As I am not really good at configuring a JWT server (and a bit lazy to be honest), I went to the webhook path as it was way easier for me to implement...
Still looking for a good JWT server that could generate the corresponding X-Hasura-* claims with little efforts...
Will try [loginsr](https://github.com/tarent/loginsr) I think. Thanks anyway!

**Comment by coco98** [comment]
@plmercereau Let us know if you need any help getting loginsrv to work! And if you have any notes to share, please do post them here. We'd love to put together a guide/blog/docs so that it's useful to anyone else with this stack :)

**Comment by plmercereau** [comment]
Hello guys,
I could not find a way to overload the JWT payload with the Hasura claims in loginsrv...
So I created [this small boilerplate](https://github.com/platyplus/authentication-server) inspired from your [webhook passport boilerplate](https://github.com/hasura/graphql-engine/tree/master/community/boilerplates/auth-webhooks/passport-js). I basically rewrote an basic auth server that stores user/password in a `user` table, `roles` in one another, and creates a many to many relationship through a `user_role` table.
It creates the JWT and maps the roles into `x-hasura-allowed-roles`.
There are of course a few limitations, (those identified are details in the [README](https://github.com/platyplus/authentication-server#limitations), but I hope this will help.
