### ISSUE TITLE
Add repository topic "automatic-api"

### ISSUE THREAD

**Issue by dbohdan** [hasura/graphql-engine#143]
Could you add `automatic-api` to your repository's topics? Software that automatically exposes APIs for databases is an interest of mine (I maintain a [list](https://github.com/dbohdan/automatic-api)). It will be easier for me and others to discover it if there is a standard GitHub topic. 20 projects [already use it](https://github.com/topics/automatic-api).

**Comment by 0x777** [comment]
Sure. Why not !
