### ISSUE TITLE
Feature request: Export data via console in json/csv etc

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#1438]
In some cases, it could be convenient to export data into json, csv, excel format to easily migrate just the data between systems.

**Comment by amaymakhija1** [comment]
Honestly would be a lifesaver, can you please add

**Comment by revskill10** [comment]
One more addition if you don't mind, is to add `importing` as well besides `exporting` (why not :D )

**Comment by martavis** [comment]
Just to clarify, are we not able to import `schema.graphql` or `schema.json` that's downloaded from the export tool `graphqurl`?

**Comment by sharshub** [comment]
Has this feature been implemented? I am also looking to export CSV from hasura directly.
