### ISSUE TITLE
proxy all requests from console through cli

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#1440]
For CLI hosted console, only migration requests are procured through CLI. To host this console on a server, all requests should go through CLI protected by the access key.

**Comment by thedeeno** [comment]
Very handy in dockerized dev environments where the ui and cli see different addresses for the graphql-engine. This change would make it so the host browser only needs to care about 1 of those addresses.

**Comment by dsandip** [comment]
cc: @danielcompton

**Comment by shahidhk** [comment]
```bash
hasura console --endpoint http://graphql-engine:8080 --address 0.0.0.0 --console-port 8080 --api-port 8081 --api-external-host https://my-hasura-cli-host.com
```

**Comment by shahidhk** [comment]
Closed in favor of https://github.com/hasura/graphql-engine/issues/2824 which will allow running CLI on docker containers or elsewhere.
