### ISSUE TITLE
[Console] Can we show postgres connection string in settings?

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#1447]
This way people can directly connect to psql easily without having to look anywhere else.

**Comment by coco98** [comment]
I think we should definitely do this. We can do it on the run-sql window perhaps? More natural UX.
@0x777 @praveenweb Any security implications to this?

**Comment by coco98** [comment]
Hm...this is not untrue. :(

**Comment by tirumaraiselvan** [comment]
But Docker compose is also the case where they want the postgres connection the most. So ...

**Comment by tirumaraiselvan** [comment]
We can just put in the docs. Let's expose the postgres atleast.

**Comment by praveenweb** [comment]
I would still like this feature on the console despite the above caveats. This comes handy if i had deployed on Heroku or have Postgres in managed services like RDS etc.

We can have a warning note in the console saying this may not be the right DATABASE_URL if it was setup using docker-compose etc. This warning need not be even there if console displays them as just Environment Variables in the UI that is used by the server.

**Comment by 0x777** [comment]
Great care has to be taken with Postgres connection strings. It is best if we never expose this out of the server.

**Comment by 0x777** [comment]
Great care has to be taken with Postgres connection strings. It is best if we never expose this out of the server.
