### ISSUE TITLE
Support for column presets in UPDATES

### ISSUE THREAD

**Issue by dafrie** [hasura/graphql-engine#1449]
From discussion on Discord:
If you want to automatically set a column to a session variable (such as the current X-Hasura-User-Id), you can do this on **INSERT** with the column presets functionality below
https://docs.hasura.io/1.0/graphql/manual/schema/default-values/column-presets.html

Is there a specific reason, why the same functionality is not supported on **UPDATE**? If not, could this feature be added?
My use case: User A creates record 1. User B later updates record 1. Ideally, there is a column who tracks who created and who last edited the record.

**Comment by 0x777** [comment]
We can add this to update permissions too. No one has asked for it before. Till we implement this, you can use a Postgres trigger to access the session variables (`current_setting('hasura.user')`) and update the column.

**Comment by dafrie** [comment]
Great thanks for the feedback, would be really helpful if this could be added!
In case someone else requires it meanwhile, shahidhk shared the part of the docs on how to access session variables:
https://docs.hasura.io/1.0/graphql/manual/guides/auditing-tables.html#auditing-actions-on-tables-in-postgres
