### ISSUE TITLE
Postgres 9.4: can't add a permission (with preset value) with insert

### ISSUE THREAD

**Issue by erikhSSI** [hasura/graphql-engine#1450]
Another Postgres 9.4 issue:  Adding a permission on INSERT in the hasura data dashboard also fails because adding a function/procedure to use as a trigger fails because "ON CONFLICT ON CONSTRAINT" is not valid syntax until Postgres 9.5.   The rest of the function definition it tries to create is fine in 9.4 syntax.

**Comment by tirumaraiselvan** [comment]
Unfortunately, Hasura only supports PG 9.5 and above. See the note here: https://hasura.io/docs/1.0/graphql/manual/getting-started/index.html
