### ISSUE TITLE
Allow arrays as data for access control

### ISSUE THREAD

**Issue by danielcompton** [hasura/graphql-engine#1452]
In the application I'm building, each database row has a field which indicates which group can view it. Each user can be a member of one or more groups simultaneously.

It would be very handy to be able to provide a JSON array of groups that a user is part of in an `X-Hasura-Groups` header/JWT claim. I could then add a custom permissions check (perhaps with `_in`?) to be able to say that the group for a row has to be one of the groups in the user's authentication headers.

It is possible to also express this by setting up relationships, but this feels like it could get quite repetitive over time.

**Comment by revskill10** [comment]
Hi @danielcompton , flexible access control is hard to be done right. I have two related issues for this problem as well.
https://github.com/hasura/graphql-engine/issues/1342 --> This one allows for flexible returning columns .
https://github.com/hasura/graphql-engine/issues/877 --> This one is the same with your issue as well to allow array of roles to be accepted.

**Comment by coco98** [comment]
Closing this in favour of #1333.
