### ISSUE TITLE
Does JSONB as array have relationship to ID?

### ISSUE THREAD

**Issue by hengsovandara** [hasura/graphql-engine#1453]
I have JSONB as array field that contains bunch of user's id, and I want to create relationship to table User, connect to user's id. But when I do query, it raise error like this _operator does not exist: jsonb = uuid_. Anyone has experience and know the solution?

**Comment by revskill10** [comment]
I think it's impossible currently, because Hasura only accept session variables as string.
To solve your issue, hasura needs two things:
- Allow json operator in permission custom check.
- Allow more json types to be accepted in custom permission check.

**Comment by 0x777** [comment]
@hengsovandara We don't support such relationships. We suggest you to use an intermediate table to model many to many relationships.
