### ISSUE TITLE
cli's README should contain build instruction

### ISSUE THREAD

**Issue by skrat** [hasura/graphql-engine#146]
Having there instructions on how to download binary from internets without any verification is ridiculous. Been fiddling with the make for a while, the thing still doesn't build.

**Comment by shahidhk** [comment]
@skrat You can download the latest release from [github releases]()

[cli's contributing guide](https://github.com/hasura/graphql-engine/blob/master/cli/CONTRIBUTING.md) has instructions on building it.

Here's the gist:

```bash
cd cli
make deps
make build
```

This will output cli binaries to `_output/<branch-commit>/hasura-*>`

You can also do `go run cmd/hasura/main.go`

Will update the readme and contributing guide to make these more clear.

**Comment by shahidhk** [comment]
Updated in https://github.com/hasura/graphql-engine/commit/24c13c04d4dbe8067a04619a7c632a6a2f26003b
