### ISSUE TITLE
enable automatic addition of commonly used fields when creating tables

### ISSUE THREAD

**Issue by tombroens** [hasura/graphql-engine#1462]
Corresponds to idea's raised in #1077.

Currently can be implemented with a default now() for created_at and an update trigger for updated_at. Nevertheless, this has to be added manually for every table.

Add an option to be ticked by the developer in the console when creating a table that adds these fields, default and trigger automatically.

**Comment by tombroens** [comment]
I see (for now already) two options to alter the console:

1. add a checkbox 'add created and updated timestaps' to the checkboxes while creating a table
2. add a button to the modify table page 'add created and update timestamps'
3. more....

The first only enables the user to add them at creation time of the table. The second enables the user to add them at anytime but requires some more logic to check if the fields where already added previously.

**Comment by mnlbox** [comment]
@tombroens, @0x777 Any news about this?
I think it can be very useful. :wink:

**Comment by 0x777** [comment]
You can use this for now till we add it in the console:

**Comment by dsandip** [comment]
Commonly used fields:
1) created_at (timestamp; defaults to `now()`)
2) updated_at (timestamp; defaults to `now()`)
3) Primary Key - Id (Integer auto-increment; automatically added as PKey)
4) Primary Key - UUID (UUID; automatically added as PKey)

**Comment by mnlbox** [comment]
Maybe relate: #1936, #1980
Add `deleted_at` for soft delete support based on current docs.

**Comment by napalm272** [comment]
Is there an eta for this?

**Comment by rikinsk** [comment]
@napalm272 This feature has been implemented and is under review. It should be released sometime next week

**Comment by napalm272** [comment]
has this been released yet?

**Comment by rikinsk** [comment]
@napalm272 Sorry for the delay in this. There were a couple of issues which had been highlighted during the review. Hence some further changes needed to be made. They are done now and this is back up for review. It should be released in a day or two now ideally.
