### ISSUE TITLE
Fix setState spread operator usage

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1467]
`this.setState` shouldn't/needn't be spreading across the entire state object?
Places to check (esp. in console):

https://github.com/hasura/graphql-engine/blob/fb842fde6f2292255e7ea3f9bf0b8e76f010a39f/console/src/components/Common/InputChecker/InputChecker.js#L20

https://github.com/hasura/graphql-engine/blob/8b0082eac16afeda18b86ceb3d575162b6906f8a/console/src/components/ApiExplorer/GraphiQLWrapper.js#L32

https://github.com/hasura/graphql-engine/blob/3cfeb6064a90023a8d6c50d62fb79a3c8d9fccfc/console/src/components/Services/EventTrigger/Modify/Editor.js#L14

**Comment by coco98** [comment]
https://github.com/hasura/graphql-engine/search?q=%22...this.state%22&unscoped_q=%22...this.state%22

Via isomorpheus on discord.

**Comment by Kacppian** [comment]
Can I work on this?

**Comment by wawhal** [comment]
@Kacppian this issue is already being fixed in #1608 
Thanks for your interest in contributing :)
