### ISSUE TITLE
showing unique: false for primary key column is confusing

### ISSUE THREAD

**Issue by samuela** [hasura/graphql-engine#1468]
This is just kinda weird... Not sure how postgres handles it under-the-hood, but seems like something that the hasura console should not allow.

![screen shot 2019-01-24 at 4 03 57 pm](https://user-images.githubusercontent.com/226872/51716480-c7223d00-1ff1-11e9-8437-c9632987d4f5.png)

**Comment by samuela** [comment]
Not only is this allowed, it's not possible to create a primary key that is marked as unique in hasura! See https://imgur.com/a/RMVJOY5.

**Comment by shahidhk** [comment]
Thanks for the feedback @samuela. Primary keys in Postgres are always unique. The field `Unique` on the console is inferred by looking at the unique constraint defined on the column, which does not care about the primary key. 

Setting Unique on a primary key column has no effect as it is already unique by definition. 

The console should hide this field for primary key columns - I am changing the scope of the issue to do that. :smile:

**Comment by samuela** [comment]
@shahidhk Makes sense!
