### ISSUE TITLE
make ux for destructive actions consistent

### ISSUE THREAD

**Issue by samuela** [hasura/graphql-engine#1469]
Right now the hasura console displays a "Delete Table" button directly on the modify table view. Clicking this pops up a generic browser confirmation dialog which is pretty easy to instinctively agree to. Other UIs like GitHub require you to enter a "Danger Zone" and then enter the name of your project exactly in order to be able to delete anything. Considering the potential for very bad, no fun, super sad data loss something similar would be nice in hasura.

**Comment by samuela** [comment]
Same thing goes from deleting a column, and untracking a table. These things are shockingly easy to accomplish but could have major repercussions in a production environment.

**Comment by shahidhk** [comment]
Thanks for the suggestion @samuela. I am changing the scope of this issue to overhaul all destructive actions on the console to a consistent, noticeable UX.

**Comment by samuela** [comment]
Sounds good, I also noticed this the other day when deleting a row.
