### ISSUE TITLE
hint that permissions need to be added for a role to traverse a relationship

### ISSUE THREAD

**Issue by danielcompton** [hasura/graphql-engine#1470]
Using Hasura v1.0.0-alpha35, if you use the admin role, your GraphQL queries can traverse fields that are part of a Relationship. However, if the request uses a non-admin role, and you set permissions on one table and not the linked tables then the query can only view fields on the original table. You will get an error saying `"field \"<your_relationship>\" not found in type: '<your_table>'"`.

It could be helpful in the GUI to show the relations next to the "Allow access to these columns" section:

<img width="693" alt="screenshot of google chrome 25-01-19 3-32-24 pm" src="https://user-images.githubusercontent.com/811954/51721391-76284c80-20b6-11e9-8d82-61d0e0f5d266.png">

If that role doesn't have permissions on the related tables, you could then hint to them that the relations aren't traversable, due to the role not being specified/not having enough permissions.

It took me a while to figure out that my query was failing because the role was missing permissions on the linked table (obvious in hindsight).

**Comment by rikinsk** [comment]
Added a note for relationships in #1605
