### ISSUE TITLE
[feature req] Enable different relation naming scheme

### ISSUE THREAD

**Issue by tombroens** [hasura/graphql-engine#1479]
When pushing track from the schema page, this now results in a name 'relatingtableByforeignkeyfieldname'. Why not give the user the opportunity to change the naming scheme of the relation in only 'relatingtable'. (Which needs some logic to prevent duplicates e.g. by putting an int after the name in case there is a duplicate). Results in a much clearer auto-API (where the user does not need to change all relation names in most cases)?

**Comment by marionschleifer** [comment]
I'm closing this issue. @tombroens please feel free to re-open if you have any follow-ups 🙂
