### ISSUE TITLE
change favicon on the console

### ISSUE THREAD

**Issue by samuela** [hasura/graphql-engine#1485]
Right now it's quite difficult to glance across a bunch of tabs and figure out which ones are hasura documentation and which are actual console tabs. May seem minor, but it's the little things that make life so much more annoying sometimes.

**Comment by shahidhk** [comment]
### Website
![white svg-250](https://user-images.githubusercontent.com/4124733/53160583-42294400-35ee-11e9-9604-888bbfe4a1cc.png)

### Console
![yellow svg-250](https://user-images.githubusercontent.com/4124733/53160606-4ead9c80-35ee-11e9-91bb-5714b058094c.png)

### Docs
![green svg-250](https://user-images.githubusercontent.com/4124733/53160617-55d4aa80-35ee-11e9-8486-7ccde6a235f0.png)

@dsandip Suggestions?

**Comment by dsandip** [comment]
@shahidhk green for console (active) and yellow for docs? And some other color for the blog? cc: @rikinsk

**Comment by samuela** [comment]
Another option (generally speaking) is to invert colors for one of the icons. That way it would be very clearly different but could retain the same general color scheme. Just thought I'd throw the idea out there.

**Comment by nithindavid** [comment]
@samuela @shahidhk Anyone working on this ? Can pick this up ?

**Comment by shahidhk** [comment]
@nithindavid Feel free to take this up. You can work on Docs and Console as mentioned in https://github.com/hasura/graphql-engine/issues/1485#issuecomment-465939467

We'll have to do the website as it's an internal repo.

Here are the SVGs:
https://storage.googleapis.com/graphql-engine-cdn.hasura.io/img/hasura_icon_green.svg
https://storage.googleapis.com/graphql-engine-cdn.hasura.io/img/hasura_icon_yello.svg

**Comment by rikinsk** [comment]
@nithindavid Hey. Sorry but I already had this lying around in some git stash. Pushed it now. Thanks for wanting to take this up anyway.

**Comment by nithindavid** [comment]
@rikinsk Sure :D I’ll pick some other ‘good first issue’.
