### ISSUE TITLE
add list with values from foreign table in console when adding a row

### ISSUE THREAD

**Issue by PierBover** [hasura/graphql-engine#1487]
When a table has a foreign key it would be great to be able to select a value from the foreign table when creating a new row instead of writing the value manually.

**Comment by Pomazan-Bogdan** [comment]
I do not think that this functionality is needed for hasura.
Since this functionality is more for testing and not for database development.
Maybe it's better to use external environments for this?
I use https://www.dbschema.com/

**Comment by PierBover** [comment]
I see your point.

OTOH considering Hasura already has the functionality of managing DB structure and content it would be a nice-to-have.

**Comment by mnlbox** [comment]
@praveenweb , @dsandip, @PierBover I have some idea about this and post some mock about this here: https://github.com/hasura/graphql-engine/issues/506#issuecomment-471521156

**Comment by mnlbox** [comment]
I this this issue has a more complete proposal for this feature: #2296

**Comment by rikinsk** [comment]
Closing in favour of #2296.
