### ISSUE TITLE
Allow json2graphql db.js to export a function to do async stuff inside

### ISSUE THREAD

**Issue by dariocravero** [hasura/graphql-engine#1488]
Hi,

I needed to do some async operations before creating the DB, so I've added the ability to export a function in json2graphql as well as an object, so we can await on it.

https://github.com/dariocravero/graphql-engine/commit/3f2ec33a12be4b7810a234339b5054b5d879f9c0

Is that something that would be of interest?

I was going to open a PR but the template suggested I opened an issue first, so here it is :).

Cheers!
Darío

**Comment by wawhal** [comment]
Hey @dariocravero 
It is a nice idea :)
Please make this change, write about this feature in the README.md of `json2graphql and submit a PR.

Thanks for contributing :D

**Comment by dariocravero** [comment]
Done @wawhal! :)

**Comment by wawhal** [comment]
Closed in #1543 
Thanks for contributing @dariocravero :-)
