### ISSUE TITLE
Show additional help in graphiql for error messages

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#1495]
Using the error code and a currently incomplete list in the troubleshooting section of docs, show additional information on troubleshooting. For e.g. for a role-based access violation, I see the following error:

```json
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.article.selectionSet.name",
        "code": "validation-failed"
      },
      "message": "field \"name\" not found in type: 'article'"
    }
  ]
}
```
Using the `code`, the console/graphiql should be able to tell me to check the role's access to this field or if the table has this column

**Comment by dsandip** [comment]
Adding more information from chat about #1649: Can we have more information show up in the response itself (using extensions according to @shahidhk). cc: @coco98 @nizar-m

**Comment by dsandip** [comment]
Use-cases
1) Field not found when the `x-hasura-role` session variable is passed
  Options:
    * Permissions issue: Try running as admin, if it works, you have a permissions issue
    * Type issue: Use docs to figure out the right types to use

**Comment by dsandip** [comment]
Show an "additional information" persistent notification with this information

**Comment by rikinsk** [comment]
related #1737
