### ISSUE TITLE
Feature request: Support aggregate(count, max, min...) in where clause

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#1498]
Currently, there's no support for aggregate fields in `where` and `order_by` clause, which means it's impossible to do filtering on aggregation.

Suggestion: Support aggregated fields on where and order_by clause when we query from a `table_aggregate`.

Example:
```
query {
users_aggregate {
aggregate(where: {count: {_gt: 0} }) 
  { 
    count 
  }
}
}
```
or
```
query {
users_aggregate(where: {aggregate {count: {_gt: 0} }})  {
aggregate
  { 
    count 
  }
}
}
```

**Comment by phated** [comment]
This feature would be huge for me!

**Comment by karibertils** [comment]
I keep running into scenarios where this is required.

**Comment by jkossis** [comment]
Any news on this? This seems like a big deal, and not terribly hard to translate to sql under the hood:

```
SELECT COUNT(*)
FROM blah
WHERE blah = blah
```

**Comment by hellsan631** [comment]
Adding a voice of support here. You can already do aggregate queries with a where clause inside of the object.

```gql
investigation {
  investigation_history_aggregate(where: {interaction: {_eq: "added_note"}}) {
    aggregate {
      max {
        created_on
      }
    }
  }
}
```

Found it weird that you couldn't do that in the order/where clause.

**Comment by dsandip** [comment]
Use case:
> Fetch a list of authors (who have published more than 10 articles ever) and their articles (published between dates a and b). The list of authors is to be sorted based on the count of articles published between dates a and b

**Comment by stefan1968** [comment]
Really need this, for instance if I'm doing a search and I still want to paginate the results I need to return the count of the searched items, not the whole table.

**Comment by karibertils** [comment]
+1 again from me.

It's already possible to do very complex queries and filtering with awesome results. But as soon as it comes to sorting the results it is impossible. In many cases there is no good workaround and you need to bypass Hasura.

**Comment by AdityaAnand1** [comment]
@rikinsk @shahidhk @rakeshkky @wawhal @arvi3411301 

Can we please pick this up next? There seems to be huge demand for this 🚀

**Comment by AdityaAnand1** [comment]
Does anybody know any temporary hacks to get this done? I really don't want to stink up my project with raw SQL scattered about (which hasura was supposed to solve completely 😋)

**Comment by erikasakire** [comment]
Currently I am using this kind of work around for aggregation inside of query. Hope it helps.

```javascript
query statistics {
  FindOutFrom(where:{ Patients: {id: { _is_null: false }}}) {
    name,
    Patients_aggregate {
      aggregate {
        count
      }
    }
  }
}
```

**Comment by groksrc** [comment]
+1 here

I need this feature please.

**Comment by jondashkyle** [comment]
Echoing this! Would be super useful. Have run into needing this several times now.

**Comment by marcfalk** [comment]
+1 would be really useful!

**Comment by aotradovec** [comment]
**+1**

**Comment by nestarz** [comment]
> Currently I am using this kind of work around for aggregation inside of query. Hope it helps.
> 
> ```js
> query statistics {
>   FindOutFrom(where:{ Patients: {id: { _is_null: false }}}) {
>     name,
>     Patients_aggregate {
>       aggregate {
>         count
>       }
>     }
>   }
> }
> ```

This workaround is not working in my case.

**Comment by adventurini** [comment]
+1 (sort of) Looking to be able to achieve multiple counts based off of different where clauses in a single aggregation query. The following workaround is terribly non performant.

```
query MyQuery($input_start_date: date, $input_end_date: date) {
  
  count1: keyword(args: {input_end_date: $input_end_date, input_start_date: $input_start_date}, where: {bid_diff: {_gt: "0"}}) {
    aggregate {
      count
      
    }
  }
  count2: keyword(args: {input_end_date: $input_end_date, input_start_date: $input_start_date}, where: {bid_diff: {_lt: "0"}}) {
    aggregate {
      count
      
    }
  }
  count3: keyword(args: {input_end_date: $input_end_date, input_start_date: $input_start_date}) {
    aggregate {
      count
      avg {
        recommended_bid
        bid_diff
      }
    }
    
  }
}
```

**Comment by jonathan-bibas** [comment]
+1

**Comment by lakhansamani** [comment]
+1

**Comment by machouz** [comment]
+1

**Comment by karibertils** [comment]
+1

**Comment by icodeforlove** [comment]
Ended up having to use a view with aggregations, and then setting up a relation.

Ideally we get proper support.

**Comment by 12bchl** [comment]
+1 Also really need this!

**Comment by paulzakin** [comment]
+1 this would really help

**Comment by wackyapps** [comment]
+1 really need this. This would really help.

**Comment by KillianGDK-FDTI** [comment]
+1, that would be super cool

**Comment by austin-coffman** [comment]
+1, would be a massive improvement to server side pagination with filters on aggregate fields

**Comment by ArzamastsevVladislav** [comment]
+1, Need this really bad

**Comment by WGTW** [comment]
What's the standing on this issue @Hasura? The feature request is widely wanted. Would love to use it, thanks.

**Comment by dennislaviolette** [comment]
Hello @revskill10 or anyone interested in this feature!

For further clarification of the request would this query also be an example of what you're looking for?

`author (where: {articles_aggregate: {count: {_gt: 5}}) 
       { id name }`

Plus if there ae any other additional user story level example that would be very helpful.  

One clarifying question:
Are you considering querying the aggregate AND what is inside the aggregate?

Thanks!

**Comment by revskill10** [comment]
@dennislaviolette Yes, it's one of the query that i want.

The goal, is to build a search interface which shows facet statistics, for example, in an ecommerce, in search result, we want to show categories (count) of the search result.

**Comment by ryparker** [comment]
In my scenario I have a table with every US Congress committee and a table for committee memberships. Each committee has members, related via a one-to-many bridge table from my committees table to the comittee_memberships table.

Tables:
- committees
- elected_officials
- committee_memberships (one-to-many bridge table for the 2 tables above)

I'd like to be able to query Hasura for all the committees that have more than x number of members and less than y number of members.

i.g.
```gql
query getCommitteesByMemberCount(
	$minMembers: Int
	$maxMembers: Int
) {
    committees(
	  where: {
	       committee_memberships_aggregate: {
	          _count: {
	            _gte: $minMembers,
	            _lte: $maxMembers,
	          },
	        },
	  }
	)
	{
		...
	}
```

**Comment by austin-coffman** [comment]
> In my scenario I have a table with every US Congress committee. Each committee has members, related via a many-to-many bridge table `committee_memberships` from my `committees` table to the `elected_officials` table.
> 
> Tables:
> 
> * committees
> * elected_officials
> * committee_memberships (many-to-many bridge table for the 2 tables above)
> 
> I'd like to be able to query Hasura for all the committees that have more than x number of members and less than y number of members.
> 
> i.g.
> 
> ```graphql
> query getCommitteesByMemberCount(
>   $minMembers: Int
>   $maxMembers: Int
> ) {
>   committees(
>     where: {
>       committee_memberships_aggregate: {
>         _count: {
>           _gte: $minMembers,
>           _lte: $maxMembers,
>         },
>       },
>     }
> ) {
>   ...
> }
> ```

@ryparker - what we did as a workaround is created a materialized view that stored the counts of those relationships.

id (PK) | member_key (FK) | count_relations (int)

Such that we could make a query like:

`query getMemberRelations(
  $min: Int
  $max: Int
) {
  committess(
    where: {
      member_to_view_relations: {
        count_relations: {
          _gte: $min, 
          _lte: $max
        },
      },
    }
  ) {
    ...
  }`

**Comment by ryparker** [comment]
Thanks for the workaround @austin-coffman 👍🏻 . I'll probably do this until Hasura adds support.

**Comment by yairopro** [comment]
✚ 𝟏

**Comment by rakeshkky** [comment]
Hi @revskill10, we do have [support](https://github.com/hasura/graphql-engine/pull/1042) for aggregate fields in `order_by`. I'm changing the issue title accordingly. 
cc @dennislaviolette

**Comment by mvaivre** [comment]
Also interested in this one! Thanks team!

**Comment by ljwolford** [comment]
This would be huge for us as well. Thank you.

**Comment by maxgfr** [comment]
✚ 𝟏

**Comment by sassela** [comment]
hey folks, thanks for your interest and patience with this! The team's actively working on this feature and a demo of WIP will be available in [August's community call](https://hasura.io/community/community-call/) recording.

**Comment by RodriguezLucha** [comment]
> hey folks, thanks for your interest and patience with this! The team's actively working on this feature and a demo of WIP will be available in [August's community call](https://hasura.io/community/community-call/) recording.

I couldn't find the link on the Hasura site seems the website hasn't been updated yet for past recordings but I did find the YouTube link here https://www.youtube.com/watch?v=4LUiztVe8EA

**Comment by plcplc** [comment]
This feature has now been implemented and merged!
Have a look at the Docs for details: https://hasura.io/docs/latest/queries/postgres/query-filters/#filter-based-on-aggregations-of-nested-array-fields

**Comment by sassela** [comment]
This feature will be available from `v2.14.0-beta.1` onwards, within the next 1-2 weeks. https://github.com/hasura/graphql-engine/releases/

**Comment by deathemperor** [comment]
@sassela not sure what's the limitation but upgrading to 2.14 we can only see count in aggregate clause
![image](https://user-images.githubusercontent.com/4255482/199675405-8a9b6fdb-d189-4838-9158-42c7284c49f2.png)

**Comment by plcplc** [comment]
@deathemperor: What types of column does your table have, and what aggregation functions are you expecting to see for that table?

Note that an aggregation function is only present in the schema if:
1. There are fields in the table it might be applied to, and
2. The current role has permissions to access those fields.

**Comment by deathemperor** [comment]
> @deathemperor: What types of column does your table have, and what aggregation functions are you expecting to see for that table?
> 
> Note that an aggregation function is only present in the schema if:
> 
> 1. There are fields in the table it might be applied to, and
> 2. The current role has permissions to access those fields.

I actually got the function figured out. thanks for the support

**Comment by tuanalumi** [comment]
> This feature has now been implemented and merged! Have a look at the Docs for details: https://hasura.io/docs/latest/queries/postgres/query-filters/#filter-based-on-aggregations-of-nested-array-fields

The link is now https://hasura.io/docs/2.0/queries/postgres/filters/using-nested-objects/#filter-based-on-aggregations-of-nested-array-fields
