### ISSUE TITLE
Track relations error: json ->> boolean

### ISSUE THREAD

**Issue by shaded-enmity** [hasura/graphql-engine#150]
I'm trying to use the `graphql-engine` on top of my Django application, however I'm getting the following error when I try to add *any* relation (even ones that don't really use the `JSON` type). This is happening on PostgreSQL 9.4 -- is there a minum version requirement?

```json
{
    "statement": "\n           SELECT constraint_name, ref_table_table_schema, ref_table, column_mapping\n             FROM hdb_catalog.hdb_foreign_key_constraint\n            WHERE table_schema = $1\n              AND table_name = $2\n              AND column_mapping ->> $3 IS NOT NULL\n                ",
    "prepared": false,
    "error": {
        "exec_status": "FatalError",
        "hint": "No operator matches the given name and argument type(s). You might need to add explicit type casts.",
        "message": "operator does not exist: json ->> boolean",
        "status_code": "42883",
        "description": null
    },
    "arguments": [
        "(Oid 25,Just (\"public\",Binary))",
        "(Oid 25,Just (\"auth_permission\",Binary))",
        "(Oid 25,Just (\"content_type_id\",Binary))"
    ]
}```

**Comment by 0x777** [comment]
This looks like a bug in the server. The minimum required version of Postgres is 9.4. So this should work. We'll get back to you as soon as possible.

**Comment by 0x777** [comment]
I was able to reproduce this. This only happens with Postgres 9.4. The precedence of `IS` changed [since 9.5](https://www.postgresql.org/message-id/CAEzk6fe-oPwmShJ6vf5h5POGV7j_ucaLv1evkV16%2BC8%3D86dyBQ%40mail.gmail.com) and hence the above query (used internally when relationships are added) only works from 9.5 and above. A fix will be deployed soon.

**Comment by shahidhk** [comment]
@shaded-enmity, `v1.0.0-alpha08` will be available soon with the fix

**Comment by shahidhk** [comment]
@shaded-enmity `v1.0.0-alpha08` is released with a fix to this issue. You can update the docker image to the this tag and update the cli using `hasura update-cli` if using the cli.

Do try it out and let us know if it works.

Please re-open if there are any issues.

**Comment by shaded-enmity** [comment]
Thank you very much @0x777 @shahidhk for the prompt response, I can confirm that this has fixed the issue. :tada:
