### ISSUE TITLE
How to workaround Big INT in JS?

### ISSUE THREAD

**Issue by sulliwane** [hasura/graphql-engine#1504]
Hello, I posted this question in the apollo-link repo: https://github.com/apollographql/apollo-link/issues/924

But I'd be interested to have Hasura's team insight on this. Basically, I'm currently storing this kind of things in postgre:
```SQL
amount numeric(36) NOT NULL,
```
But, If I store a Big Int such as `900719925474099101` and query this value from JS, it will lose precision and become `900719925474099100`. 

I'm wondering if storing big numbers as a string in postgre is the ONLY workaround? 

As I believe there are advantages of storing `amount numeric(36)` over `amount text` in postgre, wouldn't be a better solution to use a Big Int library on the JS client side when parsing the JSON data sent by Hasura? (the idea being to handle JS limitations in JS, so that JS limitations do not impact SQL schemas).

Thank you for your advices on this!

**Comment by 0x777** [comment]
I agree. The limitations of JSON should not impact how we store data in Postgres. For example, if the column type is say `numeric`/`decimal`/`bigint`/`double precision`, the JSON type should be `String` and not `Number`. PG types like `smallint`, `integer`, `real` can fit into a JSON `Number`. 

graphql-engine should ideally choose the 'correct' format for each column type. But currently we rely on `row_to_json`/`json_build_object` postgres functions which don't seem to do the right thing. We added a hard coded rule for `bigint` which is converted into a JSON `String` in this [PR](https://github.com/hasura/graphql-engine/pull/640). We should have handled all the numeric types in that PR but we didn't. We will fix this as soon as possible. 

> wouldn't be a better solution to use a Big Int library on the JS client side when parsing the JSON data sent by Hasura?

I don't think this is the right approach. All client libraries may not let you customise how the JSON is parsed.

**Comment by 0x777** [comment]
I've opened a new issue for this: https://github.com/hasura/graphql-engine/issues/1523

**Comment by sulliwane** [comment]
Sounds great! Thanks a lot for your answer, can't wait to have this implemented :) (Please close the issue if needed, or let me know)
