### ISSUE TITLE
How to get analytics from Hasura instance

### ISSUE THREAD

**Issue by alejandrojnm** [hasura/graphql-engine#1509]
It is possible to obtain hasura Analytics, such as requests per second, query per second, most used query, etc

**Comment by praveenweb** [comment]
@alejandrojnm - Hasura GraphQL Engine outputs structured logs which can be stored and analyzed.

Here's [docs](https://docs.hasura.io/1.0/graphql/manual/deployment/logging.html) on how to access the logs.

This is an [example setup](https://blog.hasura.io/graphql-observability-with-hasura-graphql-engine-and-honeycomb-ee0a1a836c41/) of GraphQL Observability with Hasura and Honeycomb.

**Comment by marionschleifer** [comment]
I'm closing this issue. @alejandrojnm feel free to re-open this if you have any additional questions 🙂
