### ISSUE TITLE
Run GraphQL Engine console in 'migrations watching' mode

### ISSUE THREAD

**Issue by danielcompton** [hasura/graphql-engine#1510]
I am running a suite of Docker containers in development which make up a running application. We are managing the containers via Docker Compose. The GraphQL engine Docker container can serve the console but doesn't automatically create migrations for any changes made via the console. 

It is possible to run the Hasura CLI manually on the host machine and have it create the migrations as you make changes. However, I'd rather not have my colleagues all need to install and run the console manually. I've tried to run the Hasura CLI in another Docker container but I had issues getting them connected and accessing the CLI based console from the host. 

When running the CLI console, you need to specify the endpoint. If the CLI is running in a container then you need to use http://graphql-engine:8080 to point to the other container. However, that address isn't valid from the host computer, so when you try and login via the console served by the CLI, the host tries to connect to http://graphql-engine:8080 and fails.

It would be great if I could enable migration tracking mode when running the GraphQL engine. Then I could run a single container which runs migrations on startup, serves the GraphQL API, serves the Hasura console, and tracks which migrations need to be made.

Here's my docker-compose.yml file for reference.

<details>
<pre>
version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    # https://docs.hasura.io/1.0/graphql/manual/migrations/auto-apply-migrations.html
    image: hasura/graphql-engine:v1.0.0-alpha35.cli-migrations
    volumes:
      - ./hasura/migrations:/hasura-migrations
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ACCESS_KEY: sekrit
  graphql-console:
    image: hasura/graphql-engine:v1.0.0-alpha35.cli-migrations
    entrypoint: "hasura-cli console --no-browser --address 0.0.0.0"
    working_dir: "/data/hasura"
    ports:
      - "9695:9695"
    volumes:
      - ./hasura:/data/hasura
    links:
      - graphql-engine
    environment:
      HASURA_GRAPHQL_ACCESS_KEY: sekrit

volumes:
  db_data:
</pre>
</details>

**Comment by shahidhk** [comment]
@danielcompton Thanks for getting in touch. Would you mind giving a :+1: at https://github.com/hasura/graphql-engine/issues/1440 ?

I am closing this issue marking as a duplicate.
