### ISSUE TITLE
How to do case-insensitive query

### ISSUE THREAD

**Issue by Mike-Van** [hasura/graphql-engine#1516]
I understand that according to [GraphQL documentation].(https://facebook.github.io/graphql/June2018/#sec-Names) names is case-sensitive. But is there anyway i can bypass that to do the case-insensitive query.

**Comment by coco98** [comment]
@Mike-Van Do you have a use-case in mind? Something like a text/pattern search query? 
Check out the text operators in this section: https://docs.hasura.io/1.0/graphql/manual/api-reference/query.html#operator

**Comment by Mike-Van** [comment]
Yes...thanks you. the `_ilike` operator suits my purpose just fine.
