### ISSUE TITLE
[Idea] implicit where { field: { _eq: value } }

### ISSUE THREAD

**Issue by HelloEdit** [hasura/graphql-engine#1521]
Hi,

I was wondering if it was possible to make the equality operator implicit, as it is on some graphql APIs. How about something like 

```graphql
album(where: {year: {_eq: 2018}) {
   title
   tracks {
     id
     title
   }
 }
}
```

will be the same thing as

```graphql
album(where: {data: {year: 2018}}) {
   title
   tracks {
     id
     title
   }
 }
}
```

Where data: {} is to search for an exact match of the given values.

Thank you for Hasura

**Comment by revskill10** [comment]
This will make the API more confusing than it should be. 
By default, we all understand that, every keys in `where` means an existing column for that table, so make an implicit field like `data` is not better option in this case.
