### ISSUE TITLE
correct (de)serialisation of postgres numeric types in JSON

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#1523]
The json functions in Postgres that we use for serialisation don't seem to generate valid JSON. See https://github.com/hasura/graphql-engine/issues/1504.

**Comment by rakeshkky** [comment]
We'll introduce a new flag `--stringify-numerics` to the server. If enabled, the server sends [numeric types](https://www.postgresql.org/docs/current/datatype-numeric.html) which do not fit into [`IEEE 754`](https://tools.ietf.org/html/rfc7159#ref-IEEE754) binary64 (double precision) range as `String`

**Comment by waterdrop01** [comment]
When using `--stringify-numerics` with this schema in DB: `"balance" numeric(17,8)`, the returned JSON for `balance` is a string. 

Just to be sure, is it normal? (I'm surprised double precision can't represent this kind of number: `100000000.00000001`)

Thank you

**Comment by 0x777** [comment]
`numeric` type is explicitly stringified as it is the safest option.

Postgres loses the precision if it is converted into double
```sql
db=# select '100000000.00000001'::double precision;
  float8   
-----------
 100000000
(1 row)
```
Haskell doesn't seem to
```haskell
Prelude> read @Double "100000000.00000001"
1.0000000000000001e8
```

If we can precisely determine when a numeric value will lose its precision when converted into a double precision value, we can maybe relax this a bit.

**Comment by waterdrop01** [comment]
Oh I see, so you mean that "any" Postgres numeric type will be converted to string.

I thought that only Postgres numeric types that have more than 15 digits precision (=double precision) would be converted to string. Ex of the behavior I expected:

```
"balance" numeric(17,8)  #  17 > 15, converted to string
"balance" numeric(14,8)  #  14 < 15, not converted to string
"balance" numeric(6,2)  #  6 < 15, not converted to string
```

If all numeric types are converted to string, I agree that it's indeed simple to reason about and very safe.

On the other hand it's not very convenient for all the "small" numerics like `"balance" numeric(6,2)` , that will need to be converted from string to the language floating number (ex: `parseFloat(string)` for Javascript) before doing any operation.

I think that If 80% of my Postgres numerics are below 15 digits precision, that makes it very cumbersome to add `parseFloat()` at each calculation step.

For all the numerics above 15 digits precision, I'll have to use [a specific library](https://github.com/MikeMcl/bignumber.js) anyway.

Thank you @0x777 for the precisions!
