### ISSUE TITLE
run customised Algolia DocSearch crawler 

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#1525]
The current frequency for docs' index being updated seems to be ~ ~~30~~ 40hrs. We can run the scraping tool on our own infrastructure to increase this frequency. Also, we can hook this service up to the prod deployment process for docs.

[Docs for DocSearch](https://community.algolia.com/docsearch/run-your-own.html)

cc: @anandfeb25 @coco98

**Comment by rikinsk** [comment]
This is done
