### ISSUE TITLE
Add an architecture and best-practices guide for running Hasura GraphQL engine on Kubernetes

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1527]
Update: a detailed K8s guide is available here: https://github.com/hasura/hasura-k8s-stack

Via Davie, Chillong on discord.

These are the topics that would be good to cover:
1. Architecture diagram of running a Hasura + Postgres stack
2. Options for adding custom business logic via remote schemas and event-triggers
4. Options for setting up DNS, SSL and service routing
5. CI/CD options: Migrations, testing, deployment

Please do let us know if there other topics we should cover.

**Comment by davie-robertson** [comment]
great - it seems this is really closely aligned with https://3factor.app/.

I would also like to see how to incorporate an external Auth provider in there too and how that should be applied to securing data.

**Comment by plmercereau** [comment]
I think this is somehow what the [Hasura platform](https://platform.hasura.io/) intends to do but I am not sure this is open source though.
I would be very, very interested... I have a very simple docker stack to share as a basis for templating a Helm Chart:
<script src="https://gist.github.com/plmercereau/b8503c869ffa2b5d4e42dc9137b56ae1.js"></script>

**Comment by shahidhk** [comment]
We have written a detailed guide on Hasura with Kubernetes here: https://github.com/hasura/hasura-k8s-stack

**Comment by coco98** [comment]
A guide on using Hasura with a postgres replicaset on kubernetes!
(via @bappr; sorry moved your note on the other issue to here!)

**Comment by praveenweb** [comment]
Closing this as we have https://github.com/hasura/hasura-k8s-stack for setting up Hasura on Kubernetes.
