### ISSUE TITLE
Api-console, working with permissions

### ISSUE THREAD

**Issue by nukinuki** [hasura/graphql-engine#1529]
Hello there.
I have 7 roles besides Admin: user, anonymous, client, contractor, manager, chief, moderator (it's complicated, i know). I am using Hasura Platform and its included Auth tables.

In some old versions of api-console all of the roles was present as soon as I created a new table, like this: https://w6y.ru/?img=/Permissions_-_country_-_Data__Hasura_2019-01-30_17-27-48.png 

Now, every new table comes with empty permissions set: https://w6y.ru/?img=/Permissions_-_legal_form_-_Data__Hasura_2019-01-30_17-28-55.png

The point is: I cannot use APPLY permissions which make this function useless for new table: https://w6y.ru/?img=/Permissions_-_route_-_Data__Hasura_2019-01-30_17-30-19.png

Proposed solutions:
1. Make "Apply" function available for all the roles, whether the roles is added to the table or not (role should be added as soon as I apply same permissions to it)
2. Make all of the roles auto-added to the table how it was before, so I will not need to remember how to spell "anonymous" every time i create a new table.
3. Make a button "Apply permisions from template" or something. Most of the time i want "Read only for everyone" or "Read for everyone, Write and update my own" rules.

For now working with permissions is very unproductive.

Concern n.2

It is unclear, should i save first and then reopen and apply, or Apply will also save it for me.
https://w6y.ru/?img=/Permissions_-_route_-_Data__Hasura_2019-01-30_17-33-55.png

Make it "Save and Apply", that's 99% usecase.

Concern n.3

Conditions with Boolean type fields are written as "_eq": "false" which make me uncomfortable — I am not sure if condition will be correctly resolved while comparing to string.
https://w6y.ru/?img=/Permissions_-_route_-_Data__Hasura_2019-01-30_17-43-53.png

**Comment by rikinsk** [comment]
Concern n.3 fixed in #1605

**Comment by nukinuki** [comment]
Good.
By the way, concern n.2, i've tested what happens when you press "Apply" — it applies new permissions to all roles EXCEPT the one i'm editing ))

**Comment by rikinsk** [comment]
Fixed concerns 1 and 2 as well in #1605
