### ISSUE TITLE
graphiql suggestion box persists even on tab change

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#1530]
![screenshot from 2019-01-30 20-23-05](https://user-images.githubusercontent.com/153602/51989416-03abd800-24cd-11e9-8d8c-5c775856a3e8.png)

**Comment by praveenweb** [comment]
The GraphiQL suggestion box that appears is out of react's DOM and gets appended just before </body>.

**Comment by karthikvt26** [comment]
Yes we should definitely do it.
