### ISSUE TITLE
tests should run across all supported postgres versions (>= 9.4)

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#154]
To catch errors like #150

**Comment by shahidhk** [comment]
@0x777 @ecthiender Can we build the binary once and then test across multiple pg versions? If yes, we can parallelize the tests across different versions.

**Comment by 0x777** [comment]
Yes

**Comment by ecthiender** [comment]
Taking this up

**Comment by shahidhk** [comment]
@ecthiender If you can just split the build and test into two steps in the existing job, I can parallelize it.
