### ISSUE TITLE
update postgres-permissions docs to add GRANT ALL PRIVILEGES when using schemas

### ISSUE THREAD

**Issue by go4cas** [hasura/graphql-engine#1545]
When using schemas, other than `public` you need to grant the following to your user (`hasurauser`):
```sql
GRANT ALL PRIVILEGES ON SCHEMA {{schema_name}} TO hasurauser;
```
I think this should be added to the [docs](https://docs.hasura.io/1.0/graphql/manual/deployment/postgres-permissions.html).

**Comment by rikinsk** [comment]
Added in #1535.

Closing this.
