### ISSUE TITLE
ra-data-hasura: datafield

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [hasura/graphql-engine#1554]
Hello.
For some reason, it does not output the Date format values to react-admin through Datafield.

![image](https://user-images.githubusercontent.com/696713/52176056-567bdd00-27b6-11e9-8037-babb4171d965.png)

**Comment by shahidhk** [comment]
Thanks for letting us know @Pomazan-Bogdan.
@praveenweb Can you take a look?

**Comment by praveenweb** [comment]
@Pomazan-Bogdan - Can you share the react code (especially `<DateField>` usage) to understand better? In my test, the usage of DateField seems to work as expected.

**Comment by praveenweb** [comment]
@Pomazan-Bogdan - According to the above code snippet, the source of the DateField is `data` where as the response from the API is `date`. Can you change the source to match the response fields and see if it works?

**Comment by Pomazan-Bogdan** [comment]
https://marmelab.com/react-admin/Fields.html#datefield

_Displays a date or datetime_
Probably only works with **timestamp** type field

**Comment by praveenweb** [comment]
@Pomazan-Bogdan - Hey, it works with Date type field too. You seem to have a typo in your code.

Go to https://gitea.misto.site/EMisto/app/src/branch/master/src/app/ds5.js#L19 and change the source to `source="date"`

It should work

**Comment by Pomazan-Bogdan** [comment]
Yes.
And there is.
Thank you very much, my mistake.
