### ISSUE TITLE
issue with modifying custom function 

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#1560]
modifying custom function not functioning as expected

- running with `Track this` enabled throws error
- modifying arguments doesnt do anything (edit: seems to be creating a duplicate fn in the background)

**Comment by rikinsk** [comment]
The `Track this` behaviour is consistent with modifying views as well. Altleast that's a good thing. 

But I am not a fan of the experience. If something is already tracked and I send a modify request with `track this` enabled, the action shouldn't fail. 

@0x777 Thoughts?

**Comment by 0x777** [comment]
Maybe we can add `ignore_if_tracked` flag to `track_table` and `track_function` queries, similar to `IF NOT EXISTS` in sql?

**Comment by 0x777** [comment]
I think the root cause is our current solution of redirecting to the SQL page for modifying a view/function.
