### ISSUE TITLE
in console, if input box is empty, hitting tab should fill it with its placeholder value 

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#1577]

**Comment by coco98** [comment]
This is not intuitive. Tabs cycle through form elements no?

**Comment by rikinsk** [comment]
Yeah. True. 

Actually what I wanted was a little different. I want some way to define some default values that I can easily apply. Will be useful setting default values of fields of different types, or to set some default url value, etc. 

Requires more thought so closing this for now.
