### ISSUE TITLE
Hide request headers in Graphql API query window in hasura 

### ISSUE THREAD

**Issue by ptrobert** [hasura/graphql-engine#1580]
The graphql api query window in hasura is wasting realestate, there is too much space on the top of the page, and also the request headers are occupying much of the space.

Can we just use one or two lines for displaying the endpoint etc and then have a provision to hide the headers

**Comment by marionschleifer** [comment]
@ptrobert It is now possible to hide the endpoint and the headers. I'm closing this issue 🙂
