### ISSUE TITLE
support passing session variables through "extensions" key

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#1587]
We use http headers to pass session variables in these two scenarios:
1. admin/insecure mode
2. `x-hasura-role` in all other modes

This results in issues such as #213. We should start supporting sending these variables in the `extensions` key.

**Comment by 0x777** [comment]
We should check if the popular client libraries allow customising `extensions` value.

**Comment by manasag** [comment]
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.
