### ISSUE TITLE
support various operators in update mutations

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#159]
For example: 

```graphql
mutation update {
  update_tags ( 
    _concat: { tags: ["a", "b"] }, 
    where { id: { _eq: some_id } }
  ) {
    affected_rows
  }
}
```
The operators that I can think of which will be useful during updates:

### `_inc`
increments the column by a value

```graphql
_inc: { clicks: 1 }
```

## jsonb columns:
https://www.postgresql.org/docs/10/static/functions-json.html
### `_concat`
Equivalent to `||` postgres operator

### `_delete_key`
Equivalent to `-` postgres operator

### `_delete_elem` 
Equivalent to `-` postgres operator

### `_delete_at_path`
Equivalent to `#-` postgres operator

**Comment by shahidhk** [comment]
[via Amos#0753 on Discord #general]
