### ISSUE TITLE
allow auto-complete of default options in create/modify table with some predefined values

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#1591]
e.g. now() for timestampz/time/date, gen_random_uuid() for uuid, etc.

**Comment by CuriousLearner** [comment]
Hello @rikinsk-zz ,

I'm trying to use `gen_random_uuid` in a mutation from Hasura. I've set-it up as a static value in Permissions tab under column preset.

The value for `datetime` column mapping to `timestampz` in Hasura are working fine using now(), but I want to get similar result for a uuid field.

I've also ensured that I can go in my postgres and use select `gen_random_uuid()` but it doesn't work from Hasura. I get the following error:

```
{
  "errors": [
    {
      "extensions": {
        "code": "data-exception",
        "path": "$.selectionSet.insert_action_one.args.object"
      },
      "message": "invalid input syntax for type uuid: \"gen_random_uuid()\""
    }
  ]
}
```

I then also tried to use `public.gen_random_uuid()` but that also didn't work.

Can someone please point out if I'm doing something wrong here, or missing out on something?
