### ISSUE TITLE
improve dependency management experience on console

### ISSUE THREAD

**Issue by rikinsk-zz** [hasura/graphql-engine#1593]
- [ ] Cascade deletes for untrack table
- [ ] Cascade delete for delete table
- [x] Cascade update for column update (from #1597)
- [x] Cascade delete for column delete
- [x] Updating field types with dependenices
- [x] Deleting foreign-keys

**Comment by tirumaraiselvan** [comment]
Please note that when we drop cascade a columns, we need to change event trigger as well.

**Comment by tirumaraiselvan** [comment]
Related: https://github.com/hasura/graphql-engine/issues/248
