### ISSUE TITLE
graphiql docs improvement

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#1594]
Schema/docs in graphiql ala 
1. graphql playground.
~~2. https://github.com/2fd/graphdoc~~
~~3. https://github.com/gjtorikian/graphql-docs~~

**Comment by BenoitRanque** [comment]
Is this not more of a GraphiQL issue? For now, you can simply open your graphql endpoint in graphql playground, and you get all the docs

**Comment by rikinsk** [comment]
Limiting scope to just improving the existing GraphiQL docs section
 
- Add breadcrumbs to make navigation easier
- Make the default opening width a little larger
- Fix spacing issues
  - between search bar and description

**Comment by manasag** [comment]
This issue has not attracted significant attention for a long period of time, and also docs section has been redesigned in [Hasura V3](https://hasura.io/docs/3.0/getting-started/overview/) Console.
Please feel free to reopen if the issue is still relevant for you.
