### ISSUE TITLE
Console should be able capture migrations even when running on the hosted, non-CLI version

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1595]
It might be simple to use the hosted console that can record actions done on the console in the browser itself (localstorage types), during a particular session, that can then be exported/downloaded and checked in to git.

Thoughts?

**Comment by manasag** [comment]
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.
