### ISSUE TITLE
GraphQL Query JSON?

### ISSUE THREAD

**Issue by corysimmons** [hasura/graphql-engine#1598]
It'd be really cool if we could declare a field as JSON/B and query it per usual. My reasons for thinking this is that sifting through 50 columns in a table for misc stuff—or having 10 tables all revolving around the same concept—seems messy and hard to navigate.

In contrast, dumping things that are related to a concept, but not big enough to warrant their own table, might clean a db up. For instance, a _User_ might have a _profile_ with some addresses, names, and such in it... A _User_ might also have a bunch of stuff related to _auth_ (e.g. tokens, providers, roles, etc.). If you break those out into their own columns on the _User_ table, you end up with 50 columns. If you break them out to their own tables, you end up stitching together all those tables with relationships.

Open to discussion/suggestions/critique, but the generic query syntax might look like this:

(https://www.db-fiddle.com/f/UsVwfCin7LFLZbAuW691G/2)

```gql
{
  user {
    profile {
      name
    }
  }
}
```

And `where` syntax might look like this:

```gql
{
  user {
    profile(where: {
      addresses: {
        _contains: {
          type: "billing"
        }
      }
    }) {
      name
    }
  }
}
```

So I suppose arrays could do `_contains` where the param is part of an object?

Feel free to poke holes in this. No rush. I'm slightly concerned what performance would be, and if perf is fine, then nailing the syntax might be tricky if there isn't some GraphQL spec for it already.

---

**Resources:**

- https://blog.hasura.io/postgres-json-and-jsonb-type-support-on-graphql-41f586e47536/ (can `where`; can't generic query)
- https://github.com/taion/graphql-type-json (not sure what this is exactly, but it has 200k+ weekly downloads so might be relevant 😅)

**Comment by coco98** [comment]
I think using directives for this might be nice.

```graphql
query {
  user {
    id
    username
    street : address @jsonpath(path: ".street")
  }
}
```

Can use `jq` syntax for the path https://stedolan.github.io/jq/manual/#Basicfilters ?

**Comment by 0x777** [comment]
Why not use arguments?

```graphql
query {
  user {
    id
    username
    street : address(path: ".street")
  }
}
```

**Comment by corysimmons** [comment]
I like that this syntax is more terse than the `_contains` syntax, but I think people are already familiar with the comparison tools in Hasura whereas directives look like a completely new thing to learn.

I'm not opposed to learning the new thing, but could you guys provide return values from now on? I'm not sure what `street: street` is supposed to find.

Either way, glad there's interest. =)

Still worried about the perf of querying through a table with 80,000 users with a profile JSON object in it. 😬

**Comment by corysimmons** [comment]
Thank you! Can't wait to play with this. What was the verdict on performance @hgiasac ?

**Comment by hgiasac** [comment]
@corysimmons The GraphQL query is translated to native Postgres query. Therefore the performance will be near to Postgres level .

**Comment by aboutaaron** [comment]
Hi all, has this feature been documented yet? I'd love to use it!

**Comment by hgiasac** [comment]
@aboutaaron You can find documentation and sample here
https://docs.hasura.io/1.0/graphql/manual/api-reference/query.html#simple-object

**Comment by corysimmons** [comment]
Are JSONPath filter expressions also supported? :o

**Comment by hgiasac** [comment]
@corysimmons We only support simple query expression for object and array, for example: obj.property, obj[0].prop, [0].prop... However, you can filter JSON in where clause to ensure the output result. GraphQL Engine supports JSONB filter already.

https://docs.hasura.io/1.0/graphql/manual/queries/query-filters.html#jsonb-operators-contains-has-key-etc

**Comment by ethanabrooks** [comment]
Is there a way to use the postgres `->>` and `#>>` operators in query filters, e.g.

```graphql
{
  user {
    profile(where: {
      addresses: {
        path: ".street",
        _like: "Virginia %"
      }
    }) {
      name
    }
  }
}
```

**Comment by ConProgramming** [comment]
Does the JSONPath in hasura support multiple children? (the spec for jsonpath includes this) E.g. "$[0]" works but "$[0,1]" doesn't for some reason
