### ISSUE TITLE
delete table with dependencies console behavior confusing

### ISSUE THREAD

**Issue by AnnieAtHasura** [hasura/graphql-engine#1602]
1. make a table a with a primary id
2. make a table that has a foreign key relationship to table a
3. attempt to delete table a
EXPECTED: grayed out button telling me I can't delete (and, ideally, why)
OBSERVED: Delete key simply missing. For new user, no clue that this is it's usual location.

**Comment by rikinsk** [comment]
@AnnieAtHasura Couldnt reproduce this. Can you share a screenshot?

**Comment by marionschleifer** [comment]
I'm closing this issue 🙂 @AnnieAtHasura please feel free to re-open if you would like to add something :)
