### ISSUE TITLE
Allow query_by_pk style queries for unique constraints also

### ISSUE THREAD

**Issue by alaarihan** [hasura/graphql-engine#1606]
Hi,

I set multiple primary key for user table (id and email) I want to query user_by_pk with either id or email but when I tried I found that the schema require both of the primary columns values to query, it should allow query with one key only.

**Comment by coco98** [comment]
@alaarihan A multiple primary key is not 2 primary keys, but it's that the combination of (id, email) is a primary key. 
I think what you were looking for is making id a primary key, and email a unique index!

**Comment by alaarihan** [comment]
@coco98 I just want to query a single item with one parameter just like Prisma, I need to query by id or email (in Prisma I just make id and email fields as unique)

**Comment by coco98** [comment]
@alaarihan The easiest way to do this right now is:

```graphql
query {
  user (where: {email: {_eq: "xx"}}) {
    id
    email
  }
}
```

You'll get a list and you'll have to do get the first element from the result. (Just like you'll have to check to see if the result is null if you'd received a single object in a by_pk kind of query).

Although, making it easy to query single objects might be a nice feature to add to the by_pk style querying! @0x777 @rakeshkky Any thoughts on querying single items by a unique constraint?

**Comment by alaarihan** [comment]
Yes I did it this way for now but I just thought it will be great if we can query a single item by any unique field in the table.

**Comment by coco98** [comment]
@alaarihan Sounds like a great idea! Let's see what @0x777 @rakeshkky say :)

**Comment by tirumaraiselvan** [comment]
Dup of https://github.com/hasura/graphql-engine/issues/519

**Comment by marionschleifer** [comment]
Closing this in favour of #519.
