### ISSUE TITLE
Question: Subscription with token from secure cookies

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#1611]
Currently, the only way for us to make subscription from browser is to manually set headers when initializing connection to Hasura.
Should Hasura server allows to automatically accept cookies from websocket connection and use it to authorize request ?
The reason is that, it's safe to save token in a httpOnly, secure cookie, rather than localStorage.

@coco98 Do you have any thought on this ?

**Comment by coco98** [comment]
This will not work with subscription clients that are commonly used which are based on the apollo subscriptions over websockets spec.

**Comment by 0x777** [comment]
This is added in 02d80c9ac6d5852c90708d30fe3509fbfd3b8e3f
