### ISSUE TITLE
Cannot connect to existing database on localhost on Mac

### ISSUE THREAD

**Issue by ashishwadekar** [hasura/graphql-engine#1612]
Hi Team,

I am really excited about Hasura & the features it provides. Kudos to all for bringing this to life.

I was not able to connect local database on Mac using the docker-run script provided. A long string was generated as output of script but docker ps shows no running container.

The hostname has to updated as **docker.for.mac.host.internal** instead of **host.docker.internal**, which solved the problem for me.

Sharing a PR with this change.

Let me know if something needs to be changed.

Cheers,
Ashish

**Comment by shahidhk** [comment]
@ashishwadekar Thanks for the PR. Can you link us to the documentation? [This](https://docs.docker.com/docker-for-mac/networking/) page still says its `host.docker.internal`.

**Comment by tirumaraiselvan** [comment]
Could it be that @ashishwadekar is running docker < 18.03?

**Comment by ashishwadekar** [comment]
@tirumaraiselvan @shahidhk 

Upgraded my docker version & it is working fine now.

@shahidhk You are right `host.docker.internal` was made available/default in this [release](https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-18030-ce-mac59-2018-03-26)

Thanks for the follow up team.

Cheers,
Ashish

**Comment by shahidhk** [comment]
I'll mark the issue as closed in that case. Thanks @ashishwadekar.
