### ISSUE TITLE
Allow Foreign Key Constraints between tables in multiple Schemas

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#1617]
Currently the user interface does not allow creating a foreign key constraint between tables in different schema. This because the user cannot select the schema when setting the constraint.

![image](https://user-images.githubusercontent.com/25712958/52931353-6f41d200-3322-11e9-9469-fbaaabb36488.png)

Related & similar to issue #562

**Comment by mnlbox** [comment]
@shahidhk, @coco98 Guys any news or roadmap about this feature request?
I think something like below mock can very useful:
![hasura foreign key](https://user-images.githubusercontent.com/25859075/55130335-1ee73c80-5138-11e9-8e11-9fe94bbfc40d.png)

**use case:**
I have three schemas:
1. `basic_data` contain my basic tables and some constant, ... for example: a `person` table contain any person info in my system.
2. `online_exam` It's contain one of my system tables. For example: `students, teachers, exam, result, ...`
3. `user_management` schema contains my authentication server tables.
& more

Now I want create a foreign-key between `student` table (from `online_exam` schema) to `person` from `basic_data`.

**Comment by rikinsk** [comment]
Depends on: #2016
