### ISSUE TITLE
graphiql UI improvements

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#1624]
1. Basic`query variables` section visibility by default
1. If `query variables` are defined, increase min. height of the section
1. Reduce height of graphiql window to 80 vh
1. Make the API and headers sections collapsible and at the same hierarchy like this:

![screenshot 2019-02-19 at 3 28 13 pm](https://user-images.githubusercontent.com/24300818/53006353-11fd6c00-345b-11e9-8893-085a8ce1a690.png)

**Comment by coco98** [comment]
@dsandip @rikinsk Shouldn't we also reduce the height of the query window in graphiql to make sure that you see query variables in the first fold?
