### ISSUE TITLE
JWT roles and security concern

### ISSUE THREAD

**Issue by plmercereau** [hasura/graphql-engine#1631]
Hello guys,

While working on a small authentication JWT service, I discovered one major concern.
When encrypted, the JWT contains the roles of the user, i.e. its authorizations. If by any chance the roles change, there is no way to invalidate the JWT in the meantime.
Practically, it means the user will keep its initial role until the expiry of the user.
I see two workarounds, but I find them both unsatisfying:
- To remove the JWT from the client, and therefore ask a new JWT with the updated Hasura claim. I don't like this solution at all as security relies on the client, which is untrustworthy
- To set a proxy before HGE (e.g. Apollo Server) that checks the validity of the JWT from a white list or a black list. I don't like this solution either as we are putting Hasura far from the client, putting an additional layer of complexity and hampering performance, and I think this is kind of against HGE philosophy that is to put Postgres data as close as possible to the client.

I think the ideal solution would be to have kind of a blacklist/white list JWT system in HGE core, with an endpoint or a mutation to validate/invalidate JWTs... I don't know any Haskell so I won't be able to contribute...

Does this reflection make sense? I feel there is a real security issue here. I will be happy to be proven wrong!

**Comment by coco98** [comment]
@plmercereau This is a valid concerns with JWTs in general. The way most JWT users handle this is by having a short expiry time and refreshing the token often that fetches the latest information. 

@ecthiender Any other pointers for these kinds of use-cases?

**Comment by plmercereau** [comment]
Thanks @coco98 for your reply. To refresh the JWT on a regular basis with a short expiry time would be indeed a compromise, but I fear it would decrease the UX as if your client missed the private key rotation he would need to login as well.
About this, I tried to implement aa JWKS endpoint in [the boilerplate](https://github.com/hasura/graphql-engine/pull/1570) @shahidhk is about to merge, but could not find a way to make it work with HGE - I failed to send the modulus in the right way. If there is a way to tackle the issue, I would be happy to complete the boilerplate with a rotation of private keys and an expiry time, coupled with a refresh endpoint so the client can get the newest JWT based on the last (and potentially stale) one.

Still, this way to proceed would only decrease the window of discrepancy between the former user permissions and the new ones, but not reduce the risk to 0.

Cheers

**Comment by leoalves** [comment]
@plmercereau  @coco98  
I didn't try this but if you store the allowed-roles in the database.  And validate it against the allowed-roles in the token it should work, no?

In the table permissions validate:
x-hasura-user-id against user_id in the database
and
x-hasura-allowed-roles or x-hasura-default-role against allowed_roles field in the database.

**Comment by plmercereau** [comment]
Hello @leoalves 
Yes I guess it would work, but only if you have a user_id field or a role_id, a group of roles accessible through a relation in the table you are querying/mutating on.

**Comment by marionschleifer** [comment]
Hi everyone 👋 we published a guide on JWTs that includes token expiration, as well as refreshing tokens: https://blog.hasura.io/best-practices-of-using-jwt-with-graphql/. I'm closing this. Feel free to re-open in case you would like to add something 🙂
