### ISSUE TITLE
Error connecting to postgresql instance on Azure

### ISSUE THREAD

**Issue by gaboesquivel** [hasura/graphql-engine#1648]
I have postgresql instance on Azure with ssl disabled.

and this is my connection string

```
HASURA_GRAPHQL_DATABASE_URL: postgres://name%40development-postgresql:pass@development-postgresql.postgres.database.azure.com:5432/name?sslmode=disable
```

and I keep getting 

```
 {"internal":"FATAL:  no pg_hba.conf entry for host \"xxx.xx.xx.xx\", user \"interxpgadmin\", database \"interx\", SSL on\nFATAL:  no pg_hba.conf entry for host \"190.10.10.147\", user \"interxpgadmin\", database \"interx\", SSL on\n","path":"$","error":"connection error","code":"postgres-error"}
```

**Comment by 0x777** [comment]
@gaboesquivel Are you still facing this issue? Looks like an issue with firewall settings?

**Comment by pyankoff** [comment]
Had the same issue some time after updating to `alpha:39` seems like `pg_hba.conf` settings were changed to disallow unprotected connections?

**Comment by celvin** [comment]
@shahidhk you said that if the password has special characters we need to escape them, but what if the user name has @ or other characters? is hasura able to manage that type of usernames in the database? I have the same trouble and maybe is because azure creates the user with "@"

**Comment by shahidhk** [comment]
You need to encode them too.

**Comment by celvin** [comment]
I am doing it, but the result is the same

**Comment by shahidhk** [comment]
@celvin The error says `Fatal Error: JWT conf: Error in $: endOfInput`. Can you double check the JWT secret env var?

**Comment by celvin** [comment]
I am using the service url jwks that I am using in for development http://<publicIP>:8081/jwks

**Comment by celvin** [comment]
but you are right, I have removed the JWT option and it worked well even with the azure database.

but now I can't see why is working in local host with docker-compose but not in azure with kubernetes,

this is the key in kubernetes environment vars:

{
  "name": "HASURA_GRAPHQL_JWT_SECRET",
  "value": "'{ \"type\": \"RS256\", \"jwk_url\": \"http://{myPublicIP}:8081/jwks\" }'"
},

**Comment by shahidhk** [comment]
That's awesome. If the questions have been answered, can you close the issue @celvin?

**Comment by celvin** [comment]
For me is working perfectly, but It was @gaboesquivel who opened this issue.

**Comment by marionschleifer** [comment]
I'm closing this issue now. Should any of you have any more questions regarding this, please do feel free to re-open it 🙂
