### ISSUE TITLE
Hasura doesn't forward Set-Cookie headers set by remote schemas

### ISSUE THREAD

**Issue by sastraxi** [hasura/graphql-engine#1654]
Hasura should forward `Set-Cookie` headers back to the client that are set in Remote Schemas, so that the consumer of the GraphQL API receives them.

* In order to use cookie-based authentication with Hasura, we need to make sure `Cookie:` headers are successfully passed to the GraphQL endpoint, so our auth webhook can extract useful information and pass in `X-Hasura-*` headers back to Hasura.
* One of the primary reasons to use cookies is the `HttpOnly` flag, which prevents against vendor javascript running on the same page from stealing our sessions.
* If `Set-Cookie:` headers don't come from the same origin as Hasura, something like `credentials: 'include'` is necessary for cookies to actually be included in GraphQL requests, at least over HTTP (Queries and Mutations).
* Unfortunately, WebSockets don't seem to have any ability to `credentials: 'include'` and simply will not pass cookies from different origins no matter what, which means that there is *currently no way to use http-only cookie-based authentication and subscriptions at the same time with Hasura*.
* Manually adding the `Cookie:` header to the WebSocket client could be an option, but we lose the ability to use `HttpOnly` cookies as client-side javascript would be required to parse them to build this header.
* This also allows a cleaner front-end coding experience; all calls can be done via GraphQL.

**Comment by sastraxi** [comment]
Might be a duplicate of #1611.

**Comment by coco98** [comment]
@0x777 @rakeshkky @ecthiender Thoughts? I feel like selectively allowing a few response headers might be very useful.

**Comment by 0x777** [comment]
> Hasura should forward `Set-Cookie` headers back to the client that are set in Remote Schemas, so that the consumer of the GraphQL API receives them.

Yes. We should definitely have this.

And coming to Cookie based authentication with the websocket protocol. The browser websocket API doesn't let you send a header like `Authorization` as part of the Upgrade request but secure cookies are passed. Given this inconsistency we decided at that time that we will have a common pattern i.e, send the required headers as part of the `connection_init` payload. However, we can definitely support collecting the `Cookie` header sent as part of the `Upgrade` request and add it to the headers that are sent to the webhook.

**Comment by sastraxi** [comment]
@0x777 thanks for the background!

> we decided at that time that we will have a common pattern i.e, send the required headers as part of the `connection_init` payload

If I'm understanding this correctly, there might be a way to do this without HttpOnly right now? Do you have an example of what kind of payload from the client will successfully get passed by Hasura to the auth webhook so it can be unpacked?

**Comment by thezjy** [comment]
@sastraxi I guess you just sent it like this:
```js
 const wsClient = new SubscriptionClient(
    process.env.REACT_APP_GRAPHQL_WEBSOCKET_URL,
    {
      reconnect: true,
      connectionParams: { headers: { 'Authorization': 'some token' } },
    },
  )
```

**Comment by sastraxi** [comment]
@thezjy thanks for the sample! I'll try passing `document.cookie` this way and see if my auth endpoint picks it up.

**Comment by ecthiender** [comment]
This is actually necessary for adding auth endpoints via schema stitching. 

One caveat: sending back response headers from a remote server won't work if the query was sent over websocket transport.

**Comment by shahidhk** [comment]
The commit that closed this issue is reverted as we need further information about the use cases - https://github.com/hasura/graphql-engine/commit/097bfb6bfac7236b47353c350fa6a296f847fa88

**Comment by sastraxi** [comment]
@shahidhk sure, what other information can I provide?

**Comment by 0x777** [comment]
@sastraxi There are couple of problems with forwarding the remote server's headers to the client. So we haven't merged this yet.
1. This is transport dependent. i.e, only if you make the mutation over http this comes into picture. If the same mutation happens over websocket, there is no way to send the response headers
2. What should the behavior be when the mutation uses fields from different remote servers (which we'll support in the near future). For example,
```graphql
mutation m {
  login(..args..)
  register_device(..args..)
}
```
`login` is by remote schema 'a', and 'register_device' is by remote schema 'b'. What should the behavior be in this case when both the servers respond with a `Set-Cookie` header?

**Comment by sastraxi** [comment]
Gotcha. Here's some thoughts:

1. It's unfortunate that this wouldn't work over ws, but I'm not sure I follow why this is an issue; the auth webhook is transport-dependent as well, isn't it? Seems like documentation is the way to solve this part (and something I'd be happy to contribute via PR).

Your second point is interesting. Multiple `Set-Cookie` headers are absolutely fine in an HTTP response; however, there may be clashes if they share the same cookie name. RFC 6265 says:

> Servers SHOULD NOT include more than one Set-Cookie header field in the same response with the same cookie-name. (https://tools.ietf.org/html/rfc6265#section-4.1.1)

However, the spec does suggest client behaviour in case a server does this in [Section 5.3](https://tools.ietf.org/html/rfc6265#section-5.3). My interpretation of the algorithm in this section is that earlier `Set-Cookie` headers should be overwritten by later ones with the same cookie-name. My suggestion would be that the headers be returned in the same order as the mutations, in order to allow developers to express ordering via the mutation / query they send to Hasura. Given the different specs for different headers, a whitelist of proxy-able headers probably makes sense to make sure Hasura can properly merge / overwrite depending on whether multiple versions of the same header are allowed in the spec.

So in your example, both `Set-Cookie` headers would be passed back to the GraphQL client; this behaviour is consistent with the `Set-Cookie` RFC.

**Comment by thezjy** [comment]
Seems like this issue was solved by 39? Just tested, it works fine.

**Comment by campie** [comment]
> Seems like this issue was solved by 39? Just tested, it works fine.

Please, could you explain what you mean by "solved by 39"? I'm still struggling with this issue.

**The Case**

I've created a simple apollo server to handle authentication in my app then added it as a remote schema using the Hasura console.

The login mutation creates a jwt and sets two cookies:

1 - a secure http-only same-site cookie containing the jwt header and signature (domain = api.foo.com)
2 - a secure same-site max-age cookie containing the jwt payload (domain = .foo.com so the client hosted in a CDN at www.foo.com can read it and know when it's logged in)

By the way, this is the best approach I found to store jwt token on the client. JS never has access to the full jwt, only the payload which improves UX a lot. The payload contains a csrf token which apollo client adds to a csrf-token header to protect browsers without same-site cookies support. So in case of a xss attack, the attacker can never steal the full jwt and has to do all his evil job through my domain. 

My auth webhook is pretty simple: 

1 - it reads the csrf-token directly from a crsf-token header
2 - it reads the jwt payload from js-available cookie and the jwt header and signature from the http-only cookie
3 - it verifies the jwt 
4 - it checks if the verified jwt contains the same csrf-token as the one in the headers.

This is awesome: no csrf, no jwt stealing, xss mitigation and great UX because the payload has info to update the UI accordingly.

This approach is inspired in the post below:

[(https://medium.com/@jcbaey/authentication-in-spa-reactjs-and-vuejs-the-right-way-e4a9ac5cd9a3)]

**The Problem**

My web app is using Vue and apollo client (pointing to the hasura endpoint). But this doesn't work: calling the login mutation does not set the jwt cookie.

**A workaround**

Having 2 apollo clients. The default apollo client points to the hasura endpoint. The auth client bypass the hasura endpoint, pointing directly to the apollo auth server.

It works, but it would be great to have only one graphql endpoint.

**Comment by BenoitRanque** [comment]
There is a common pattern that I can't find a workaround for without this feature.

The pattern is simple: session cookie, which expires after 30 minutes. Reset the 30 minutes on each request.
This means if the user is inactive for 30 minutes or more, they are automatically logged out.

Currently, I can work around this limitation by initially handling login and setting the session cookie on a separate, dedicated endpoint on the same domain.

But I can't reset the cookie expiring time on each request to my api. I see no practical workaround, and the webhook seems to be the only logical place to do this.

**Comment by 0x777** [comment]
We'll get this in by the next release or two.

**Comment by BenoitRanque** [comment]
I have just noticed the issue I mentioned above is related but different.
1 is about setting cookies from remote schemas
2 is about setting cookies from auth webhook

Should I open a new issue?

**Comment by mduecker** [comment]
I can't get Hasura to forward the set-cookie header from my remote schema query.
- I checked the box to "Forward all headers"

What does this part in the documentation mean?
> Set-Cookie headers from your remote schema servers are sent back to the client over HTTP transport. Over websocket transport there exists no means to send headers after a query/mutation and hence ``Set-Cookie`` headers are not sent to the client. Use HTTP transport if your remote servers set cookies.

I tried both, sending a GraphQL request and sending a POST request to my GraphQL Endpoint.

**Comment by coco98** [comment]
@tirumaraiselvan @ecthiender 👆

**Comment by tirumaraiselvan** [comment]
@mduecker What version of Hasura are you on?

**Comment by mduecker** [comment]
@tirumaraiselvan 
v1.0.0-beta.4

I found out that the problem wasn't with Hasura, instead my remote schema (GraphQL resolver for a REST API) wasn't forwarding the cookie. 

Also it's a bit confusing that Google Chrome Dev Tools don't show "set-cookie" headers.

I found the solution, how to configure my Apollo Server here:
https://spectrum.chat/apollo/apollo-server/how-to-configure-apollo-to-set-response-headers-from-resolver-requests~68878c02-13cb-4a3b-aafa-2df6815251a9

**Comment by BenoitRanque** [comment]
I've found a peculiar issue with this: I can set one cookie, but if I atempt to set multiple cookies only the first one is set. Have not had the time to study more in dept

**Comment by tirumaraiselvan** [comment]
@BenoitRanque This has been fixed in `v1.0.0-beta.5` via https://github.com/hasura/graphql-engine/pull/2739

**Comment by weyert** [comment]
@campie  I was wondering if you have an example of cookie auth via auth webhook like you described?

**Comment by callmeberzerker** [comment]
I am having the same problem at the moment. It seems that `hasura` doesn't forward cookies to the `web_auth_hook`.
