### ISSUE TITLE
Use with VSCode-graphql

### ISSUE THREAD

**Issue by Jayphen** [hasura/graphql-engine#1656]
I am trying to use https://github.com/prismagraphql/vscode-graphql for Intellisense autocompletion/in-editor queries etc.

When executing a query using the extension, I get the following error:

```
Error: Network error: When parsing the constructor GraphQLRequest of type Hasura.GraphQL.Transport.HTTP.Protocol.GraphQLRequest expected Object but got Array.
```

My .graphqlconfig looks like this:

```
{
  "projects": {
    "Faberge": {
      "schemaPath": "./schema.graphql",
      "extensions": {
        "endpoints": {
          "default": "http://localhost:8080/v1alpha1/graphql"
        }
      }
    }
  }
}
```

Is there something more I need to do in order to get the correct response ?

**Comment by coco98** [comment]
@wawhal Have you tried this out with vscode?

**Comment by buzinas** [comment]
@Jayphen I know you asked specifically about `stpn.vscode-graphql`, but I use `apollographql.vscode-apollo`, and it works like a charm for me. This is my `apollo.config.js` file:

```js
module.exports = {
  client: {
    service: {
      name: 'your-project-name',
      url: 'http://localhost:8080/v1alpha1/graphql',
    },
    includes: ['**/queries/**/*.{gql,graphql}'], // change this to your pattern
  },
}
```

![apollo-vscode](https://user-images.githubusercontent.com/7298695/53380692-06bfaa00-394d-11e9-9362-71eb790be36d.gif)

**Comment by Jayphen** [comment]
Actually, that is the extension I was asking about. The intellisense does work as intended in `.gql` or `.graphql` files.

However, if you attempt to execute the query, it will fail with the error I mentioned above.

**Comment by shahidhk** [comment]
@Jayphen What do you mean by execute? You can run the query against the server from VSCode?

**Comment by Jayphen** [comment]
Yes, the extension adds an 'execute query' CodeLens link/button:
https://github.com/prisma/vscode-graphql/search?q=execute&type=Issues

https://user-images.githubusercontent.com/15905/47411584-82c0a000-d769-11e8-983b-f2ed49bea922.png

**Comment by wawhal** [comment]
I am able to replicate this.
Investigating what the problem is.

**Comment by shahidhk** [comment]
An integration guide for VSCode is added at https://docs.hasura.io/1.0/graphql/manual/guides/code-editor-integrations/visual-studio-code.html

**Comment by m4ttheweric** [comment]
> ```js
> module.exports = {
>   client: {
>     service: {
>       name: 'your-project-name',
>       url: 'http://localhost:8080/v1alpha1/graphql',
>     },
>     includes: ['**/queries/**/*.{gql,graphql}'], // change this to your pattern
>   },
> }
> ```

What do you put for your project name? I am not sure what to put in there.

**Comment by m4ttheweric** [comment]
> An integration guide for VSCode is added at https://docs.hasura.io/1.0/graphql/manual/guides/code-editor-integrations/visual-studio-code.html

What do you put for service.name? I am running hasura core locally and I have no idea what project/service name would be...
