### ISSUE TITLE
Improve auto/suggested relationship names generated via console

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1665]
1. For any FK in an object relationship, generate a relationship name that is the singular form of the table name (remove `s` if that is the last letter).
2. For any FK in an array relationship, generate a relationship name that is the singular form of the table name (add `s` if that is _not_ the last letter).
3. If there is already a relationship to the same table via another FK use the current naming scheme (XByYId)

This should be used in "track all relationships" and in the relationships pane as well.

**Comment by coco98** [comment]
@praveenweb @rikinsk thoughts?

**Comment by rikinsk** [comment]
Definitely seems aesthetically better than what we have now. 

But *(playing devil's advocate here)* this doesn't work for how I generally name my relationships. I would like it to be derived from the foreign-key. e.g. `users(id)` and `articles(id, author_id)`, I would like the relationship to be `author` and not `user`. 

Ideally I would somehow like this to be customizable by the user based on their naming scheme. Maybe using regex with table name as foreign-key as input? Can't think of a clean way to achieve this though. Just a thought.

**Comment by coco98** [comment]
Considering that our relationship names are meant to be indicative anyway,
wouldn’t it be nice just to have this heuristic work for that initial
delight. The renaming thing we have now works well in any case.

**Comment by dsandip** [comment]
From @wawhal in #1444:

The logic for generating relationship names lives in `console/src/components/Services/Data/TableRelationships/Actions.js`.

Ref: [node inflection](https://www.npmjs.com/package/inflection)

**Comment by karthikvt26** [comment]
Folks, how do we resolve collisions?

Lets say the suggested relationship name is already taken for the table?

@dsandip @rikinsk

**Comment by dsandip** [comment]
@karthikvt26 You will also need to handle suggestions for multi-column foreign keys.

**Comment by wawhal** [comment]
@karthikvt26 you can append numbers if there is a collision.
We allow renaming the relationships. So they can rename it if need be.
