### ISSUE TITLE
Support for PostGIS geography types is missing

### ISSUE THREAD

**Issue by ekamil** [hasura/graphql-engine#1674]
There are two type groups (?) in PostGIS - geometry and geography. Geometry is supported by Hasura and even documented.
Support for geography is missing.
Example working query:
```
query queryPointsOK($point: geometry) {
  points(where: {point_geom: {_st_d_within: {distance: 3, from: $point}}}) {
    id
  }
}
```
Variables:
```
{
  "point": {
    "type": "Point",
    "coordinates": [ 1, 50 ],
    "crs": {
  		"type": "name",
      "properties": {
        "name": "urn:ogc:def:crs:EPSG::4326"
      }
		}
  }
}
 ```
BTW: this variable definition is marked as invalid in the console with message: "Expected value of type "geometry""

Not working versions:
```
query queryPointsNOK($point: geography) {
  points(where: {point_geog: {_st_d_within: {distance: 3, from: $point}}}) {
    id
  }
}
```
Notice changed type to geography and a different column.
(The same variable definition was used)
I attach minimal compose allowing to reproduce. The only thing to do after `docker-compose up` is making Hasura watch the table `public.points`.
[hasura.zip](https://github.com/hasura/graphql-engine/files/2913930/hasura.zip)

**Comment by 0x777** [comment]
@ekamil This should be trivial to add. We only generate the operators if the column is of `geometry` type. We should do the same for `geography` types too.

**Comment by shahidhk** [comment]
@ekamil Can you use this image and see if your use case is covered? `hasura/graphql-engine:pull1735-f8280b2`

**Comment by ekamil** [comment]
@shahidhk It does, I can filter on geography field. One thing is off - I still get a warning in the console with variable like this one:
```{
  "point": {
    "type": "Point",
    "coordinates": [
      18.6093997955322,
      54.3773002624512
    ]
  }
}```
"Expected value of type "geography"."
I tried sorting using geo function but that's unsupported, right?

**Comment by shahidhk** [comment]
Can you give more details, like the query, variables etc. with which I can repro?

**Comment by ekamil** [comment]
Regarding sorting - not really, I don't know how to express SQL `order by st_distance(place_point, ST_GeomFromText('POINT(2.3522 48.8566)') );` with GQL.
Regarding the console warning - the above is only variable definition I've used.

**Comment by asindl** [comment]
Any news here? This is a very interesting feature to have...

**Comment by shahidhk** [comment]
@asindl Yes, this is going out in next release.
