### ISSUE TITLE
How to revoke the admin access ?

### ISSUE THREAD

**Issue by jamsheer-thottathil** [hasura/graphql-engine#1675]
I have created different roles as per my requirement and all role-based access is working as expected.
But if I do not pass the X-Hasura-Role key   then it will return all data (default admin role may execute.)
Can anyone tell me how to disable the default admin access?

**Comment by coco98** [comment]
@jamsheer-thottathil Have you setup an admin-secret and then an authentication method? With webhook or with JWT?

Once you have that setup, your webhook or JWT will contain the right x-hasura-role and x-hasura-user-id values and stuff like that a user logged in on your app will have.

https://docs.hasura.io/1.0/graphql/manual/deployment/securing-graphql-endpoint.html
https://docs.hasura.io/1.0/graphql/manual/auth/index.html

**Comment by marionschleifer** [comment]
I'm closing this issue. @jamsheer-thottathil please feel free to re-open should you have any further questions 🙂

**Comment by penumbra23** [comment]
Want to ask a similar (or even the same question), is there a possibility to disable the admin access at all?
