### ISSUE TITLE
Using postgres permissions from docs does not work on RDS

### ISSUE THREAD

**Issue by ecthiender** [hasura/graphql-engine#1677]
via `fusillicode#3122` on Discord.

Following the instructions [here](https://docs.hasura.io/1.0/graphql/manual/deployment/postgres-permissions.html#postgres-permissions) does not work on RDS. 

Results in error:
```
sql> GRANT SELECT ON ALL TABLES IN SCHEMA information_schema TO hasurauser
[2019-02-28 13:03:13] [42501] ERROR: permission denied for relation sql_parts
sql> GRANT SELECT ON ALL TABLES IN SCHEMA pg_catalog TO hasurauser
[2019-02-28 13:03:17] [42501] ERROR: permission denied for relation pg_statistic
```

Probably because RDS restricts specific tables in `pg_catalog` and `information_schema`.

**Comment by ecthiender** [comment]
Granting selects explicitly to the relations used by hasura in `pg_catalog` and `information_schema` should work.

```
pg_catalog.pg_constraint
pg_catalog.pg_class
pg_catalog.pg_namespace
pg_catalog.pg_attribute
pg_catalog.pg_get_constraintdef
pg_catalog.pg_proc
pg_catalog.pg_available_extensions
pg_catalog.pg_statio_all_tables
pg_catalog.pg_description

information_schema.tables
information_schema.table_constraints
information_schema.key_column_usage
information_schema.columns
information_schema.views
information_schema.schemata
information_schema.routines
```

**Comment by fusillicode** [comment]
The following DDLs doesn't raise any errors from the db side:
```
GRANT SELECT ON information_schema.table_constraints, information_schema.key_column_usage, information_schema.columns, information_schema.views, information_schema.schemata, information_schema.routines TO <hasura-username>;

GRANT SELECT ON pg_catalog.pg_constraint, pg_catalog.pg_class, pg_catalog.pg_namespace, pg_catalog.pg_attribute, pg_catalog.pg_proc, pg_catalog.pg_available_extensions, pg_catalog.pg_statio_all_tables, pg_catalog.pg_description TO <hasura-username>;
```

Regarding the `pg_catalog` tables I've just found this thread but it doesn't explains much about the issue:
https://stackoverflow.com/questions/45095211/amazon-rds-postgres-give-permission-to-pg-catalog

**Comment by dvasdekis** [comment]
Same problem occurred on Google Cloud SQL, with the same solution. I think the documentation should be updated.

**Comment by denisotari** [comment]
> The following DDLs doesn't raise any errors from the db side:
> 
> ```
> GRANT SELECT ON information_schema.table_constraints, information_schema.key_column_usage, information_schema.columns, information_schema.views, information_schema.schemata, information_schema.routines TO <hasura-username>;
> 
> GRANT SELECT ON pg_catalog.pg_constraint, pg_catalog.pg_class, pg_catalog.pg_namespace, pg_catalog.pg_attribute, pg_catalog.pg_proc, pg_catalog.pg_available_extensions, pg_catalog.pg_statio_all_tables, pg_catalog.pg_description TO <hasura-username>;
> ```
> 
> Regarding the `pg_catalog` tables I've just found this thread but it doesn't explains much about the issue:
> https://stackoverflow.com/questions/45095211/amazon-rds-postgres-give-permission-to-pg-catalog

In my case GCP CloudSQL PostgreSQL 9.6.15 return error:

`WARNING:  no privileges were granted for "table_constraints"
WARNING:  no privileges were granted for "key_column_usage"
WARNING:  no privileges were granted for "columns"
WARNING:  no privileges were granted for "views"
WARNING:  no privileges were granted for "schemata"
WARNING:  no privileges were granted for "routines"
WARNING:  no privileges were granted for "pg_constraint"
WARNING:  no privileges were granted for "pg_class"
WARNING:  no privileges were granted for "pg_namespace"
WARNING:  no privileges were granted for "pg_attribute"
WARNING:  no privileges were granted for "pg_proc"
WARNING:  no privileges were granted for "pg_available_extensions"
WARNING:  no privileges were granted for "pg_statio_all_tables"
WARNING:  no privileges were granted for "pg_description"
GRANT

Query returned successfully in 148 msec.`

**Comment by koienergyspa** [comment]
> The following DDLs doesn't raise any errors from the db side:
> 
> ```
> GRANT SELECT ON information_schema.table_constraints, information_schema.key_column_usage, information_schema.columns, information_schema.views, information_schema.schemata, information_schema.routines TO <hasura-username>;
> 
> GRANT SELECT ON pg_catalog.pg_constraint, pg_catalog.pg_class, pg_catalog.pg_namespace, pg_catalog.pg_attribute, pg_catalog.pg_proc, pg_catalog.pg_available_extensions, pg_catalog.pg_statio_all_tables, pg_catalog.pg_description TO <hasura-username>;
> ```
> 
> Regarding the `pg_catalog` tables I've just found this thread but it doesn't explains much about the issue:
> https://stackoverflow.com/questions/45095211/amazon-rds-postgres-give-permission-to-pg-catalog

Using AWS Amazon RDS PostgreSQL 12 returns this:
```
postgres=> GRANT SELECT ON pg_catalog.pg_constraint, pg_catalog.pg_class, pg_catalog.pg_namespace, pg_catalog.pg_attribute, pg_catalog.pg_proc, pg_catalog.pg_available_extensions, pg_catalog.pg_statio_all_tables, pg_catalog.pg_description TO hasurauser;

WARNING:  no privileges were granted for "pg_constraint"
WARNING:  no privileges were granted for "pg_class"
WARNING:  no privileges were granted for "pg_namespace"
WARNING:  no privileges were granted for "pg_attribute"
WARNING:  no privileges were granted for "pg_proc"
WARNING:  no privileges were granted for "pg_available_extensions"
WARNING:  no privileges were granted for "pg_statio_all_tables"
WARNING:  no privileges were granted for "pg_description"
GRANT
```

**Comment by matthewsommer** [comment]
I have this issue as well on AWS RDS Postgres 12. When I try the proposed workaround I also get 'no priviledges were granted for...'

**Comment by seifip** [comment]
Got the same problem on GCP/Postgres 12 with Hasura Cloud. Workaround above does not work.

**Comment by caleb15** [comment]
I'm not even able to grant usage on the pg_catalog schema as root:
```
fifteen5_test=> GRANT USAGE ON SCHEMA pg_catalog TO test_user;
WARNING:  no privileges were granted for "pg_catalog"
```
