### ISSUE TITLE
close gaps between metadata apis and console

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#1683]
There are still some things like creating composite foreign keys etc. that are possible via the API, but through the console. These gaps should be addressed immediately.

**Comment by rikinsk** [comment]
Step 1: make a list of all gaps
Step 2: fork off individual issues for each gap

**Comment by rikinsk** [comment]
Raw SQL
- [ ] `check_metadata_consistency` flag in `run_sql`

Table modify
- [ ] `cascade` flag in `untrack_table` _(console should give option to drop dependants after showing list)_

Relationships
- [ ] comments for relationships
- [ ] `cascade` flag in `drop_relationship` _(console should give option to drop dependants after  after showing list)_

Permissions
- [ ] comments for permissions
- [ ] '*' in permission columns

**Comment by manasag** [comment]
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.
