### ISSUE TITLE
Console Triggers

### ISSUE THREAD

**Issue by hmexx** [hasura/graphql-engine#1687]
Hasura already has a feature to browse your data, as well as a way to Trigger webhooks when CRUD operations are fired. The idea is to combine the two features to support building CMS-y like actions (flag, ban, activate, view, etc) that a user can run from the console, for a specific table/row.

V1 could be as simple as marking an event trigger's operation as "console".
--- 
![image](https://user-images.githubusercontent.com/3520226/53638437-26d9bc80-3c1e-11e9-81dd-f9a2eb8a36f4.png)

... and then adding a drop-down that fires the event, on the 'browse rows' screen.
---

![image](https://user-images.githubusercontent.com/3520226/53639660-c0569d80-3c21-11e9-9778-18d652780130.png)

There's a lot of bells and whistles that could be added, but the above is probably a good MVP.

**Comment by tirumaraiselvan** [comment]
![image](https://user-images.githubusercontent.com/8663570/54993695-7a0a1980-4fe8-11e9-877e-82ed41ca1260.png)

This should open the same modal as "retry" delivery in Invocation Logs tab:

![image](https://user-images.githubusercontent.com/8663570/54993813-bdfd1e80-4fe8-11e9-9551-4ba245a28ee9.png)

We need to change the title and some minor fixes on this modal.
