### ISSUE TITLE
Pass authorization header with HaProxy for Websockets

### ISSUE THREAD

**Issue by fmilkovic** [hasura/graphql-engine#1693]
Our Hasura instances sit behind HaProxy for High Availability and scaling reasons.

When client visits /graphql url, request will be initiated to HaProxy. 
HaProxy reads http-only cookie and appends it to request towards Hasura as Authorization header.
We also append x-forwarded-for which is used to validate token.
This works great for HTTP queries but it's not possible to achieve this with WS subscriptions.

It seems that only possible way to send Authorization info is via Websockets client, but this is not really option for us since we also need to pass x-forwarded-for and client-ip headers, all generated by HaProxy.

Is there a way to send this info when trying to authenticate via Websockets? We could implement authentication on HaProxy side but it will still be problem to resolve users info on Hasura side.

Thank you in advance!

**Comment by coco98** [comment]
@ecthiender Any suggestions for 👆 ?

**Comment by 0x777** [comment]
@fmilkovic The latest release (alpha39) reads websocket headers (from the http upgrade request) and unifies them with the headers sent through client. So your approach should work with websockets too

**Comment by fmilkovic** [comment]
Awesome team, thank you. I'm closing this ticket then.
