### ISSUE TITLE
UI for adding field-level validations to mutations

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#1700]
Currently there are multiple ways to perform validations before mutations:

1) add check constraints on postgres explicitly
2) create postgres triggers
3) remote-schemas 

Many use-cases can be solved using 1 and 2 but its not easy to use them currently. 

We can solve the problem of 1) more efficiently: In the data tab, we should be able to "select" check constraints during table create/modify. We can keep this similar to permissions UI but underneath it will translate to a simple "ADD CONSTRAINT" query.

**Comment by mnlbox** [comment]
Woooo, @tirumaraiselvan I love this idea man :wink: :heart:

**Comment by yasinarik** [comment]
This can be extended per suggested in #3536

**Comment by shahidhk** [comment]
closed with https://github.com/hasura/graphql-engine/commit/71240f310dff17e876bd1bdcf28cddf7871461c1
