### ISSUE TITLE
Link to  inconsistent state/metadata github issue in server logs whenever this happens

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1721]
Instead of just saying "X table not found" , the server logs can also point to
https://github.com/hasura/graphql-engine/issues/231

@shahidhk Also, please update the #231 with a link to the troubleshooting guide on docs.

**Comment by manasag** [comment]
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.
