### ISSUE TITLE
docs: add top level entry on configuring hasura CLI with admin secret

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1725]
Many different ways of doing it right? 
1. `.env` file
2. `--admin-secret` flag
3. `config.yaml` entry, but this is not good for version control
4. env var on bash, `export` or prepend to command

@shahidhk  I couldn't find a quick reference in the docs.

**Comment by shahidhk** [comment]
`.env` is not supported. We can add the other docs soon.

**Comment by r-moore** [comment]
Would be nice if you could load vars from .env in config.yaml, e.g.

```
# config.yaml (checked in to git repo)
endpoint: https://xxxxxxxx
admin_secret: ${HASURA-ADMIN-SECRET}
```

```
# .env (not in git repo)
HASURA-ADMIN-SECRET=xxxxxxxxxxxxxxx
```

**Comment by marionschleifer** [comment]
This has been documented [here](https://hasura.io/docs/1.0/graphql/core/hasura-cli/config-reference.html).
