### ISSUE TITLE
Data Diagram or Entity-Relationship (ER) chart

### ISSUE THREAD

**Issue by mnlbox** [hasura/graphql-engine#1731]
Hi guys,
I think it's very handy and have good UX if we can have a simple Data Diagram or Entity-Relationship (ER) chart of the current state in `http://localhost:8080/console/data/schema/<schema name>` page.
Something like this:

![01-entity-relationship-diagram](https://user-images.githubusercontent.com/25859075/46664944-3d2f9f00-cbcf-11e8-9e8b-6d6f008c4ef1.png)

**Comment by mnlbox** [comment]
Maybe related: https://github.com/hasura/graphql-engine/pull/799

**Comment by dsandip** [comment]
Closing this in favor of #314
