### ISSUE TITLE
Only show migration name text box on the Run SQL window if current SQL statement is a migration

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1732]
<img width="525" alt="Screenshot 2019-03-11 at 4 11 21 PM" src="https://user-images.githubusercontent.com/131160/54164043-65d6f180-4418-11e9-9313-43d4fb93f541.png">

The text box can be hidden if this is a migration is not checked right?
@rikinsk thoughts?

**Comment by rikinsk** [comment]
Yeah. Totally.
