### ISSUE TITLE
Add a sample JWT creator on the console to make it easy to try different permissions

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1733]
Kind of a corollary to #1369 

Using the JWT configuration on the server, allow a user to create sample JWTs. Allow user to play around with `x-hasura-*` values. 

The console can create a JWT token (or maybe make an API call to the server to avoid this code being written on the console?) and then put it in as an auth header in the headers section of the console.

**Comment by coco98** [comment]
@rikinsk @ecthiender @karthikvt26 thoughts?

@tirumaraiselvan This is similar to our discussion of using jwt.io in the docs to create sample tokens, but now, we can just create those sample tokens via the console.

**Comment by ekamil** [comment]
Where would the secret to sign this new JWT come from? This would require "leaking" the private key to hasura. Which is definitely not desired.

**Comment by ecthiender** [comment]
@ekamil I think this is meant as a playground. So you would use this during development, where you would add a "throwaway" secret to create tokens.

**Comment by ekamil** [comment]
There's jwt.io to use as playground in a similar vein. I see two downsides here: feature creep and the risk of playgrounding with this feature into production :)
Correct me if I'm wrong but can't we alredy play with `x-hasura-*` using headers?

**Comment by coco98** [comment]
@ekamil Yes, you're quite right :)
For the JWT config, I was thinking of using the JWT_SECRET that the hasura server itself is configured with. That way you can put in a few sample claims, create a valid JWT and then use that to test stuff. 

But, using jwt.io is also totally fine! Perhaps it'd be better to add documentation to use jwt.io to do this sample jwt creation and then use that. :)

**Comment by coco98** [comment]
Closing this in favour of #1768
