### ISSUE TITLE
cascade as a query parameter in delete mutation

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#1736]
I would like to specify a parameter called `cascade:true` in my delete mutation which will delete all related rows in other tables.

There's one way to specify this by configuring `ON DELETE` cascade constraint. (#225)

But it would be nice to have this as a parameter in my graphql mutation, if i have not setup those constraints in postgres.

**Comment by mnlbox** [comment]
I love this idea. It can be very useful :wink:

**Comment by 0x777** [comment]
This is not easy to do (if it is possible at all). The dependency tree computation and its traversal are best left to Postgres with the `cascade` option in the foreign key constraint.

**Comment by MarcelloTheArcane** [comment]
@0x777 is the `cascade` option something you can set?

**Comment by MarcelloTheArcane** [comment]
@0x777 Don't worry, I found it - 
![image](https://user-images.githubusercontent.com/21159570/62132912-da320480-b2d5-11e9-8c46-3d5795f669e8.png)
