### ISSUE TITLE
docs: document error codes and messages for graphql queries

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#1738]
Error codes that are currently available in [docs](https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/index.html#error-codes) are valid for the JSON API.

We need to document the error codes and message strings that are received in responses for graphql queries.

**Comment by jasonferrier** [comment]
Has there been any progress on this ~1.5 years later?
Even just posting a CSV of the values in `errors[i].extensions.code` would be helpful at this point.

**Comment by marionschleifer** [comment]
Closing this in favour of https://github.com/hasura/graphql-engine/issues/2871.
