### ISSUE TITLE
docs: document nested mutations for transactional use-cases

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#1741]
Consider the case of article and author. When i'm inserting an article for which an author doesn't exist.
The following nested mutation works.
```
mutation {
  insert_article(objects:[{
    title: "some title", content:"some content", rating: 5, author: {data:{name:"Praveen"}}
  }]) {
    affected_rows
  }
}
```

Typically, i would have first created the author and used the author_id in article mutation. This would have been two queries and not a transaction, hence requiring a remote schema.

We need to document the fact that `Nested Mutations` can solve a lot of postgres transactional use-cases by adding specific examples and custom APIs are actually not required.

**Comment by tirumaraiselvan** [comment]
Documented here: https://hasura.io/docs/1.0/graphql/core/mutations/multiple-mutations.html#insert-an-object-and-a-nested-object-in-the-same-mutation
