### ISSUE TITLE
enable inserting multi line data in tables through console

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#1742]
Issue comes from @henriquea on Discord

He wanted to store markdown input into the database and wanted to test by inserting values from the console but the console strips out line breaks.

**Comment by henriquea** [comment]
Thanks for this @wawhal! I think a good rule of thumb here is that console apart from sanitising and preventing XSS, it shouldn't mutate the data at all. Empty spaces, new lines, etc should be handled by the developer itself.

**Comment by rohitsanj** [comment]
I'd like to work on this issue. Can anyone guide me as to how I can go about enabling multi-line inserts? I'm assuming I'll have to **delete some part of the code** which strips new lines. 

As @henriquea said, it should be up to the developer to control the type of data being input.

**Comment by rikinsk** [comment]
related to: #504

**Comment by mnlbox** [comment]
@rikinsk It's not only about JSON editor. Multi line text input (textarea) also very useful for simple Text column for example like `description` fields in many tables. :wink:

**Comment by mnlbox** [comment]
@rikinsk we have open PR here: #1155

**Comment by rikinsk** [comment]
closing in favour of #458
