### ISSUE TITLE
cli does not execute on alpine

### ISSUE THREAD

**Issue by mterron** [hasura/graphql-engine#175]
See [https://github.com/hasura/graphql-engine-docs/issues/41](https://github.com/hasura/graphql-engine-docs/issues/41)

**Comment by shahidhk** [comment]
You can find direct download links for binary here: https://github.com/hasura/graphql-engine/releases

**Comment by shahidhk** [comment]
`hasura` on alpine linux exits with code 127

@mterron Just curious, and particular reason for running the cli inside an alpine linux container?

**Comment by mterron** [comment]
Not a container, my host is Alpine.

**Comment by shahidhk** [comment]
Ah, okay. And you're running the cli for migrations, right? The issue is the alpine doesn't have libc. I will enable static linking of all the dependencies in the next build. It should be fine then.

**Comment by shahidhk** [comment]
@mterron The latest version is statically linked for libc also. I have tested this on an alpine container. Cab you check on your host and reopen the issue if it's not executing?

**Comment by mterron** [comment]
Seems to be working. I haven't done in depth testing though. 

Thanks!

**Comment by celvin** [comment]
@mterron  did it work?

Alpine Linux spends less resources, do we have any official Alpine Linux image for Hasura graphql-engine?

**Comment by shahidhk** [comment]
@celvin We've been shipping statically compiled binaries for CLI since July 2018 and have been verified to work with Apline. 

The Hasura GraphQL Engine server image is ~20MB in size and is a stripped down docker image. It cannot get smaller than this :smile:

**Comment by celvin** [comment]
Thanks, great job.
