### ISSUE TITLE
angular 7 subscriptions not reloading

### ISSUE THREAD

**Issue by cedricve** [hasura/graphql-engine#1751]
Hello, 

Im trying out Hasura and it works instantly. I can query my tables and filter them cool.
The only thing I'm struggling with is to setup the subscription feature in my app.

I deployed Hasura to Heroku, and managed to get the watchQuery working. However when I  call the subscribeMore method I'm not getting new data. Any idea?

Everything looks good. But maybe Im missing something (I see the websocket initiated and so on).

Kind regards
Cédric

**Comment by coco98** [comment]
@cedricve That's weird, I recently did a demo with angular and things seemed to work fine. Can you paste your code here? Or perhaps in codesandbox?

**Comment by cedricve** [comment]
thanks @coco98, hmm ok sounds good.

This is what I'm doing in the module to initiailize both the http and the ws bindings..

    import { NgModule }      from '@angular/core';
    import { FormsModule } from '@angular/forms';
    import { CommonModule } from '@angular/common';
    import { HttpClientModule } from "@angular/common/http";
    import { Apollo, ApolloModule } from "apollo-angular";
    import { HttpLinkModule, HttpLink } from "apollo-angular-link-http";
    import { WebSocketLink } from 'apollo-link-ws';
    import { InMemoryCache } from "apollo-cache-inmemory";
    import { split } from 'apollo-link';
    import { getMainDefinition } from 'apollo-utilities';
    import { LoggingRoutes } from './logging.routes';
    import { LoggingComponent } from './logging.component';
    import { SubscriptionClient } from "subscriptions-transport-ws";

    @NgModule({
      imports: [
        LoggingRoutes.getAppRoutes(),
        FormsModule,
        CommonModule,
        HttpClientModule,
        HttpLinkModule,
        ApolloModule
      ],
      declarations: LoggingRoutes.getDeclarations()
    })
    export class LoggingModule {
      constructor(
        apollo: Apollo,
        httpLink: HttpLink
      ) {
        // Create an http link:
        const http = httpLink.create({
          uri: 'https://xxx.herokuapp.com/v1alpha1/graphql'
        });

        // Create a WebSocket link:
        const ws = new WebSocketLink({
          uri: `ws://xxx.herokuapp.com/v1alpha1/graphql`,
          options: {
            reconnect: true
          }
        });

        // using the ability to split links, you can send data to each link
        // depending on what kind of operation is being sent
        const link = split(
          // split based on operation type
          ({ query }) => {
            const { kind, operation } = getMainDefinition(query);
            return kind === 'OperationDefinition' && operation === 'subscription';
          },
          ws,
          http,
        );

        apollo.create({
          link,
          cache: new InMemoryCache(),
        });
      }

Afterwards in the related component I start the query and the subscription like this.

    ...
    import gql from 'graphql-tag';
    import { Apollo, QueryRef } from 'apollo-angular';

    const GET_EVENTS = gql`
      query getEvents {
        events {
          id
          event
        }
      }
    `;

    const GET_EVENTS_SUBSCRIPTION = gql`
      subscription getEvents {
        events {
          id
          event
        }
      }
    `;

    @Component({
      selector: 'Logging',
      templateUrl: './logging.component.html',
      styleUrls: ['./logging.component.scss']
    })
    export class LoggingComponent implements OnInit {

      public events: Observable<any>;
      public eventsQuery: QueryRef<any>;

      constructor(private apollo: Apollo){}

      ngOnInit() {

        this.eventsQuery = this.apollo.watchQuery({
          query: GET_EVENTS,
        });

        this.events = this.eventsQuery.valueChanges.pipe(map(result => {
          return result.data && (result.data as any).events
        }));

        this.eventsQuery.subscribeToMore({
           document: GET_EVENTS_SUBSCRIPTION,
           updateQuery: (prev, {subscriptionData}) => {
             // ... i never hit this
           }
         });
      }

      ngOnDestroy() {
        ...
      }
    }

**Comment by coco98** [comment]
@cedricve I'm unfortunately not an angular expert, but I was doing some experiments and this works for me.
Let me know if this helps. Perhaps @vnovick can put some 👀 on it if this doesn't help.

```javascript
import { Component, OnInit } from '@angular/core';
import { Apollo } from 'apollo-angular';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { Subscription } from 'rxjs/Subscription';

import gql from 'graphql-tag';

import { Todo, Query } from './types';

@Component({
  selector: 'app-list',
  template: `
    <ul>
      <li *ngFor="let todo of todos">
        {{todo.title}} by author-name
      </li>
    </ul>
    <add-todo></add-todo>
  `
})
export class ListComponent implements OnInit {
  todoSubscription: Subscription;
  todos: Observable<Todo[]>;
  constructor(private apollo: Apollo) {}

  ngOnInit() {
     this.todoSubscription = this.apollo
      .subscribe({
        query:  gql`
        subscription  {
          todos {
            id
            title
          }
        }
      `
      })
      .subscribe(({data}) => {
        this.todos = data.todos;
      })
  }

  ngOnDestroy() {
    this.todoSubscription.unsubscribe();
  }
}```

**Comment by cedricve** [comment]
Thanks @coco98, this doesn't work in my codebase. The subscribe function isn't fired. 

One side question from the network tab, do you see 101 calls (switching protocol) from the graphql websocket endpoint?

**Comment by coco98** [comment]
@cedricve 
I have a working example here: 
https://stackblitz.com/edit/simple-apollo-angular-example-g8ftxx?file=app%2Flist.component.ts
Heroku app is here (no auth setup): https://gdg-bkp.herokuapp.com/console

Perhaps we can play around there :)

**Comment by cedricve** [comment]
Hey, thanks indeed this works. What I see is I do not get a connection_ack on my side. Any ideas?  A collision with another package/lib?

<img width="902" alt="Screen Shot 2019-03-15 at 16 00 46" src="https://user-images.githubusercontent.com/1546779/54440832-bf525f80-473b-11e9-8cff-d3f5d3914c6d.png">

**Comment by marionschleifer** [comment]
Hi @cedricve, just checking in if you were able to resolve your issue? Or do you have any more questions? 🙂

**Comment by marionschleifer** [comment]
Closing this issue. @cedricve feel free to re-open if you have any more questions.

**Comment by ConProgramming** [comment]
Seeing this issue right now. Anyone else find anything similar? Many of our devices often aren't seeing {"type":"connection_ack"}, just message: {"type":"ka"}
