### ISSUE TITLE
where query for related tables

### ISSUE THREAD

**Issue by glw** [hasura/graphql-engine#1764]
This appears to be a valid query according to the documentation [here](https://docs.hasura.io/1.0/graphql/manual/queries/query-filters.html)
```
{
  quercus_poi_info 
  {
    poi_info_id
    namesBynameid (where: {name: {_eq:"Some Name"}}){
      name 
    }
    pointsofinterestBypointsofinterestId {
      geom
    }
  }
}
```

But I am getting an error
```
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.quercus_poi_info.selectionSet.namesBynameid.args.where",
        "code": "validation-failed"
      },
      "message": "no such argument \"where\" is expected"
    }
  ]
}
```
Is this due to the fact that I am asking it to filter on a related table rather than directly on the parent table? How could I go about filtering on fields in related tables?

**Comment by coco98** [comment]
@glw You can filter the records returned in a relationship if the relationship is an array relationship.
> I want parents and children, but only those children that are older than 5 years.

If you want to use the relationship fields to filter the parent node, then apply the where clause on the parent node.
> I want parents and children, but only those parents that have children older than 5 years

Maybe this?

```graphql
{
  quercus_poi_info (where: {namesBynameid: {name: {_eq:"Some Name"}}})
  {
    poi_info_id
    namesBynameid {
      name 
    }
    pointsofinterestBypointsofinterestId {
      geom
    }
  }
}
```

Also, if you're trying these queries in the Hasura console you should be seeing the right autocomplete and errors and so on.

**Comment by glw** [comment]
Thanks @coco98 this worked! Based on the documentation I just wasnt sure how it would work. I appreciate your help!
