### ISSUE TITLE
InternalException (HandshakeFailed)

### ISSUE THREAD

**Issue by thebetterjort** [hasura/graphql-engine#1765]
{"timestamp":"2019-03-13T22:04:04.212+0000","level":"info","type":"telemetry-log","detail":{"http_error":{"response":null,"url":"https://telemetry.hasura.io/v1/http","http_exception":{"type":"http_exception","message":"InternalException (HandshakeFailed (Error_Protocol (\"certificate rejected: [SelfSigned]\",True,CertificateUnknown)))"},"status_code":null},"type":"http_exception","message":"http exception occurred"}}

I'm behind a corporate proxy and have self signed certs. 

 errno: 'ECONNREFUSED',
dev_1  |      code: 'ECONNREFUSED' },

**Comment by 0x777** [comment]
@thebetterjort You can disable telemetry by setting this environment variable `HASURA_GRAPHQL_ENABLE_TELEMETRY` to `false`. However you may still see errors from update checks. We'll add a flag to disable that in the next release.
