### ISSUE TITLE
Add video guide to show end to end auth0 setup with testing and debugging

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1768]
Video should cover:
- Create hasura app
- Create auth0 app
- Configure rules for adding roles
- Configure hasura to use auth0 jwt config
- Login with auth0 web kit (without having to build a full UI)
- Use the JWT from auth0 and then use it on hasura console

Also:
https://github.com/hasura/graphql-engine/tree/master/community/sample-apps/todo-auth0-jwt

**Comment by mnlbox** [comment]
@coco98 I love this idea. Some video content for general use case can be very useful for anyone. Thanks for this idea :wink:

**Comment by praveenweb** [comment]
We have added the guide to setup Auth0 from scratch. The tutorial is available on the [Hasura backend course](https://hasura.io/learn/graphql/hasura/authentication/1-create-auth0-app/) on learn. And the video playlist is available on [Youtube](https://youtu.be/BXJk0wao42U?list=PLTRTpHrUcSB_NphLWLqfuqL4smr0Mly9K)
