### ISSUE TITLE
Use postgres triggers on views over multiple tables

### ISSUE THREAD

**Issue by ceracera** [hasura/graphql-engine#1774]
Currently, it's possible to use triggers only on simple views (not accross related tables). It would be great if we could use triggers on views like `person_with_address` where data is comming from two tables, `person` and `address`. Common use case is to eg. insert person and its address at once.

I tried to do it now with postgres function and `INSTEAD OF` trigger on such view and hasura returns error that view is not insertable.

I also tried setting a trigger on a table `person` but hasura returns an error since there are no columns for `address` table in the one being inserted in (eg. no `street_name` in `person` table).

Isn't hasura limiting postgres that way? Given those limitation how could that be done?

**Comment by tirumaraiselvan** [comment]
@ceracera This should be possible with `INSTEAD OF` on the view. Can you give a repro where it doesn't work?

I created a view like

```
create view users_with_address as
select users.id, users.name, users.is_active, addresses.address from users join addresses on users.id = addresses.user_id
```

This is the trigger function:

```
CREATE OR REPLACE FUNCTION add_user_with_address() RETURNS TRIGGER  as
$$
BEGIN
INSERT INTO "users" (is_active) values ('t') RETURNING id INTO NEW.id;
INSERT INTO "addresses" (user_id, address) values (NEW.id, 'empty') RETURNING address INTO NEW.address;
RETURN NEW;
END; $$ LANGUAGE plpgsql;
```

And I can now insert on this view.
