### ISSUE TITLE
Issue updating table_name when it is linked to a function

### ISSUE THREAD

**Issue by karthikvt26** [hasura/graphql-engine#1775]
![screenshot 780](https://user-images.githubusercontent.com/25095884/54353420-08da7600-467a-11e9-8df4-5e84366c3621.jpg)

In the above screenshot, `search_posts` is a function which returns `setof post`. I get an error when trying to update the `table_name` of the `post` table

**Comment by manasag** [comment]
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.
