### ISSUE TITLE
Issue updating relationship name

### ISSUE THREAD

**Issue by go4cas** [hasura/graphql-engine#1777]
When trying to update the name of an array relationship, I get the following error: "Renaming relationship failed. table "team" does not exist."

I am using v1.0.0-alpha40.

**Comment by rakeshkky** [comment]
@go4cas Please post minimal schema with relationships and permissions so that we can reproduce this.

**Comment by go4cas** [comment]
@rakeshkky , as requested:

Table Schema:
```SQL
CREATE TABLE team
(
   id                serial         NOT NULL,
   name              varchar(20)    NOT NULL,
   brand_id          int            NOT NULL,
   team_type_id      int            NOT NULL,
   parent_team_id    int,
   owner_employee_id int,
   created_at        timestamptz    DEFAULT NOW(),
   updated_at        timestamptz
);

ALTER TABLE team
   ADD CONSTRAINT team_pkey
   PRIMARY KEY (id);

ALTER TABLE team
   ADD CONSTRAINT team_name_unique
   UNIQUE (name);

ALTER TABLE team
  ADD CONSTRAINT team_brand_id_foreign FOREIGN KEY (brand_id)
  REFERENCES brand (id)
  ON UPDATE NO ACTION
  ON DELETE CASCADE;

ALTER TABLE team
  ADD CONSTRAINT team_team_type_id_foreign FOREIGN KEY (team_type_id)
  REFERENCES team_type (id)
  ON UPDATE NO ACTION
  ON DELETE CASCADE;

ALTER TABLE team
  ADD CONSTRAINT team_parent_team_id_foreign FOREIGN KEY (parent_team_id)
  REFERENCES team (id)
  ON UPDATE NO ACTION
  ON DELETE CASCADE;

ALTER TABLE team
  ADD CONSTRAINT team_owner_employee_id_foreign FOREIGN KEY (owner_employee_id)
  REFERENCES employee (id)
  ON UPDATE NO ACTION
  ON DELETE CASCADE;
```

Screenshot of Hasura relationships:
![2019-03-15_13-13-17](https://user-images.githubusercontent.com/12674784/54427776-23692980-4724-11e9-82f5-3820610784bc.png)

Steps to reproduce:
![2019-03-15_13-13-59](https://user-images.githubusercontent.com/12674784/54427885-72af5a00-4724-11e9-9bc4-bbe22fa9fcca.png)

Error:
![2019-03-15_13-16-18](https://user-images.githubusercontent.com/12674784/54427924-8b1f7480-4724-11e9-9317-343c634f43db.png)

**Comment by tobymarsden** [comment]
From my testing, this bug only seems to crop up when the referenced table is in a schema other than `public` -- the `rename_relationships` query fired by the console doesn't seem to include a `schema` field.

**Comment by tobymarsden** [comment]
@rikinsk @wawhal Brilliant, thank you! This makes life easier :-)
