### ISSUE TITLE
provide an option to override limit in select permissions

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#178]
Let's say a limit of `100` is enforced for `anonymous` role on the `article` table. 

When a query `q` on `article` table is made with role `anonymous`, the behavior will be as follows:
1. When `q.limit <= limit`: query goes through.
2. When `q.limit is null OR q.limit > limit`: `q.limit = limit`.

From [delynn](https://app.intercom.io/a/apps/rucirpb3/inbox/inbox/all/conversations/17572719226) on intercom

**Comment by delynn** [comment]
This sounds like a per table permission, which would definitely handle my reported use case. Thanks for tracking this!

That said, any chance this could also be set globally (i.e. for all roles and tables) maybe via an environment variable? For existing systems with really large datasets, I think being able to set a global limit maximum/default would help to avoid timeouts or clients being able to inadvertently request an obscene response graph.

**Comment by coco98** [comment]
@0x777 @rakeshkky What is the latest on this? Let's merge it so that @delynn can try it out!

**Comment by shahidhk** [comment]
@delynn @coco98 This is included in `v1.0.0-alpha12`

**Comment by delynn** [comment]
@shahidhk Thanks for the update! I have just updated our instance to run alpha12. I will let you know how it goes.

Any thoughts on making this available at a global level that is inherited by each exposed table? Maybe through an environment variable?

**Comment by shahidhk** [comment]
@0x777 @coco98  Thoughts?

**Comment by 0x777** [comment]
@delynn This is being tracked at https://github.com/hasura/graphql-engine/issues/280

**Comment by delynn** [comment]
@0x777 @shahidhk So, I've had some time to play with this now, and it's working great. I'm looking forward to seeing #280 get applied however, as I've made the mistake as an admin of leaving off `limit` when doing a quick query and hitting one of my large tables that causes the query to timeout.

I do have some UX feedback for you on the implementation. It's a little odd that the "Limit the no of rows" checkbox is always checked even if a value isn't in the text field. Unchecking the box also doesn't seem to cause the form to be saved:

<img width="388" alt="screen shot 2018-08-13 at 9 38 44 am" src="https://user-images.githubusercontent.com/221/44042677-1c996d84-9ede-11e8-9b72-709c60459653.png">

This option feels to me like it belongs at the top of the permissions area (even above "Allow selecting rows for role:") and could just be the text box and not have the checkbox associated with it.

**Comment by shahidhk** [comment]
@delynn Thanks for the feedback, tracking at #205
