### ISSUE TITLE
Save queries that can be run in the hasura graphql console

### ISSUE THREAD

**Issue by jstansbe** [hasura/graphql-engine#1781]
I found my self typing several queries/mutations into Hasura because it's very handy, has formatting, and intelliSense.

The issue is i have to comment out all code but what i want to run. This is manageable but not ideal. It would be great to have the ability to save and load queries/mutations. If you're trying to get an idea of what im thinking of.... open up PostMan and look into how easy it is to save requests into collections and folders. 

P.S. Hasura is awesome

**Comment by iamareebjamal** [comment]
Hasura uses graphiql which has option for favoriting your previous queries

**Comment by rikinsk** [comment]
Closing in favour of #336
