### ISSUE TITLE
does not exist (Connection refused) when remote_schemas setup but not running on startup

### ISSUE THREAD

**Issue by silasb** [hasura/graphql-engine#1782]
When doing local development I will setup a `remote_schema` to point to my dev machine.  When I restart hasura and that `remote_schema` isn't started hasura will fail to start and exit with error below.  This prevents me from logging into the admin to update the `remote_schema` to point to my production environment.  The only work around is logging into postgresql and modifying the `hdb_catalog.migration_settings` schema, but this is a pain.

I'd love for it to still startup without the `remote_schema` being present so I can manually update it through admin.

```
{"path":"$","error":"HttpExceptionRequest Request {\n  host                 = \"10.5.5.15\"\n  port                 = 3001\n  secure               = False\n  requestHeaders       = [(\"Content-Type\",\"application/json\"),(\"User-Agent\",\"hasura-graphql-engine/v1.0.0-alpha40\")]\n  path                 = \"/graphql\"\n  queryString          = \"\"\n  method
           = \"POST\"\n  proxy                = Nothing\n  rawBody              = False\n  redirectCount        = 10\n  responseTimeout      = ResponseTimeoutDefault\n  requestVersion       = HTTP/1.1\n}\n (ConnectionFailure Network.Socket.connect: <socket: 12>: does not exist (Connection refused))","code":"remote-schema-error"}
```

**Comment by dimitar-nikovski** [comment]
I can confirm reproducing this a few times on `alpha-0.41`

**Comment by rakeshkky** [comment]
@silasb Please refer https://github.com/hasura/graphql-engine/issues/1638. If fixing that issue helps you give it a :+1: .

**Comment by marionschleifer** [comment]
I'm closing this issue. @silasb feel free to re-open it if you continue to experience any problems 🙂
