### ISSUE TITLE
The remote schema use 3rd party rest APIs or restful APIs

### ISSUE THREAD

**Issue by Eden-Harris** [hasura/graphql-engine#1783]
### I want to use hasura to integrate existing REST APIs and third-party REST APIs.
![image](https://user-images.githubusercontent.com/28903167/54404412-4d175600-470e-11e9-8f98-2e954300b912.png)

> #### In my company, we have many rest and restFul APIs, and we often use 3rd party rest or restful APIs, the APIs is not graphql...

> #### I think other developers also will have this trouble, we usually use a lot of old REST-API from 3rd party SDK, and my company 's APIs, It's all rest or restful APIs

> #### If i create a remote schema has the body's field from rest API's field, it is amazing!!!

**Comment by 0x777** [comment]
@Eden-Harris Closing this in favor of https://github.com/hasura/graphql-engine/issues/1279.
