### ISSUE TITLE
How to track upstream changes 

### ISSUE THREAD

**Issue by 1zaak** [hasura/graphql-engine#1784]
I plan to develop on top of this, but I don't think the "master" branch is a proper way to track any upstream changes. 

Should we have a "stable" branch to track changes upstream?

**Comment by shahidhk** [comment]
@1zaak `release-v1.0` can be considered as a stable branch.

**Comment by shahidhk** [comment]
Also, `master` should always be stable - we don't merge anything to master without all the tests passing.

**Comment by marionschleifer** [comment]
I'm closing this issue. @1zaak please feel to re-open if you would like to add anything 🙂
