### ISSUE TITLE
Generate relationship to child_aggregate fields also?

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1786]
I want to fetch the number of comments for every post I have.

```graphql
query {
  blog {
    id
    title
    posts {
      id
      title
      comments_aggregate {
        aggregate { count }
     }
  }
}
```

Refer to @vnovick's video at: https://www.youtube.com/watch?v=HTEGGndT3zY&feature=youtu.be&t=3461

**Comment by 0x777** [comment]
We already support this. You'll need to allow aggregates on the remote table in the select permission for this to be generated
