### ISSUE TITLE
Feature Request: Pre-fill default values for UUID and Timestamp columns

### ISSUE THREAD

**Issue by jasonmccallister** [hasura/graphql-engine#1793]
Hi! First of all this is such an amazing tool and it has truly changed the way I build APIs... Love it.

I have built a few APIs this week, which itself is amazing, and one of the things I found myself doing the most was created UUID and Timestamp columns. This left me wishing for a few features, the first having the default values for UUID be pre-filled with `gen_random_uuid()` and timestamps with `now()`. I find it easier to hit the delete key as opposed to typing `gen_random_uuid()` or `now()`.

Any thoughts on having this as a feature?

<img width="1007" alt="Screen Shot 2019-03-16 at 9 18 29 PM" src="https://user-images.githubusercontent.com/5354908/54483880-b8a61400-4831-11e9-8a9b-0e61d466d55a.png">

**Comment by rikinsk** [comment]
Closing in favour of #1591
