### ISSUE TITLE
allow rearranging column rows via drag-and-drop when creating new tables

### ISSUE THREAD

**Issue by jasonmccallister** [hasura/graphql-engine#1795]
It would be great when designing tables if you could rearrange the columns after you entered them, I know it may be a nitpick, but when designing large tables I tend to have a specific order for columns (e.g. the id column is first, timestamps are last, and everything else is in-between). As it stands now, if I forget a field, it is a manual process to copy and paste each column to shift it down and make space.

**Comment by rikinsk** [comment]
Closing in favour of #1622. 
@jasonmccallister Please add a thumbs up to the above issue, Will help us prioritise.

**Comment by rikinsk** [comment]
Just noticed this issue is for the create table section and not modify section. 

Reopening
