### ISSUE TITLE
ability to copy types from graphiql docs

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#1806]
In remote schemas, we may need to copy types to build custom functionality over existing types. Currently, there is no way to copy this easily:

![graphiql](https://user-images.githubusercontent.com/8663570/54529394-ced4e100-49a5-11e9-8d94-d5fdac3864a1.png)

**Comment by rikinsk** [comment]
Tracking this with #1594

**Comment by manasag** [comment]
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.
