### ISSUE TITLE
Feature Request: Batching queries

### ISSUE THREAD

**Issue by Kairowa** [hasura/graphql-engine#1812]
As it currently stands, the graphql-engine is unable to process batched queries ([batched query example](https://blog.apollographql.com/batching-client-graphql-queries-a685f5bcd41b)). The following response is returned when attempting to batch queries through Apollo: 
`{"errors":[{"extensions":{"path":"$","code":"parse-failed"},"message":"When parsing the constructor GraphQLRequest of type Hasura.GraphQL.Transport.HTTP.Protocol.GraphQLRequest expected Object but got Array."}]}`

**Comment by madhujahagirdar** [comment]
I would love to have this feature so that i can integrate Prisma plugin in VSCode.

**Comment by EddieVallejos** [comment]
+1

**Comment by nmaquet** [comment]
+1

**Comment by Kairowa** [comment]
What's the status on this?

**Comment by OLDIN** [comment]
+1

**Comment by Scong** [comment]
+1

**Comment by OliverLeighC** [comment]
+1

**Comment by bkniffler** [comment]
Common guys, there is things like reactions now build into github. I'd rather have notifications for important messages only and these '+1' add no substantial value to an issue. God knows how many people are subscribed and will be unnecessarily bothered.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments

**Comment by lexi-lambda** [comment]
Reopening this issue after some discussion in #3490 pending a further decision about what we want to do.
