### ISSUE TITLE
Insert mutation problem 

### ISSUE THREAD

**Issue by siddhant1** [hasura/graphql-engine#1823]
I am not able to make a mutaion and is getting the error:-

Message: field "todo_user" not found in type: 'todos_insert_input', Location: undefined, Path: undefined

Explorer :- 
![image](https://user-images.githubusercontent.com/30566406/54629180-04102a80-4a9d-11e9-8b4b-d30eadccbcb4.png)

```
export const addTodo = gql`
  mutation($objects: [todos_insert_input]) {
    insert_todos(objects: $objects) {
      affected_rows
    }
  }
`;


insert_todos({
        variables: {
          objects: [
            {
              todo_text: "12",
              todo_user: "oauth12"
            }
          ]
        }
,

**Comment by shahidhk** [comment]
@siddhant1 The screenshot shows no error?

If you've setup permissions, please check if the current role is allowed to insert on that column.

**Comment by siddhant1** [comment]
Exactly , I am running the mutation in the graphiql and it runs perfectly (it's admin now) , when I tried running it from the frontend using a webhook it throws this error , also I have worked around with permissions and no luck (it throws different error) , but even if there is a permission error (I will look into it) the error is not helping me in this case

**Comment by elitan** [comment]
It is a common pattern with Hasura. If you try to update a field you do not have permission to, Hasura will return back that the field does not exists. Because for that particular role (in your front end client), the field does not exist.

**Comment by siddhant1** [comment]
Thanks for the help , it got solved  :)

**Comment by sbussard** [comment]
I'm having the same problem even though the jwt is valid and the permissions line up. This error is baffling

**Comment by elitan** [comment]
> I'm having the same problem even though the jwt is valid and the permissions line up. This error is baffling

There are three potential problems:

1. JWT claims are not correct
2. Permissions are not correct
3. Bug in Hasura

I encourage you to double check 1. and 2.

**Comment by sbussard** [comment]
Thank you for helping me understand the problem space. It turned out to be a permissions error.

**Comment by BrianHung** [comment]
Just ran into this issue because I updated the table columns without updating the permissions. Why not use a less obscure error message than field doesn't exist?
