### ISSUE TITLE
Localization (l11n) strategy with Hasura for getting data in given locale

### ISSUE THREAD

**Issue by pronevich** [hasura/graphql-engine#1824]
Hi, I'm thinking about how to better implement localization with Hasura Engine and my thought that this should be implemented on HE side somehow. 

One possible solution is by send `-H "Accept-Language: en_US"` header for example, but what will do with this HE to get right localized data from the right column  - I have no idea :) This way works [Yelp GraphQL API](https://www.yelp.com/developers/graphql/guides/localization)

Currently, I'm sending locale in `where` clause of GQL input. Here is an example:

Table products: `id PK, price, type`
Table products_translation:` product_id FK, lang, name, description`
Hasura array relationship: `productValues products_translation :: product_id  →  id`

Query:
```
{
  products {
    id
    type
    productValues(where: {lang: {_eq: "en_US"}}) {
      name
      description
    }
  }
}
```

**Comment by coco98** [comment]
@pronevich You can set up hasura permissions that pick this up from the header which would have a similar effect to sending the `Accept-Language` header.

Check it out here:
https://l11n-hasura.herokuapp.com/console/api-explorer
https://l11n-hasura.herokuapp.com/console/data/schema/public/tables/products/permissions

If you look at the user role's select permission you'll see a header `x-hasura-lang` is used.

Now if you try a graphql query with the right headers (these headers can be sent along with the auth token in production, or can be sent as is if you're using `HASURA_GRAPHQL_UNAUTHORIZED_ROLE`) 

<img width="991" alt="Screenshot 2019-03-20 at 4 36 37 PM" src="https://user-images.githubusercontent.com/131160/54717414-54c36a00-4b15-11e9-9875-f8bed8627782.png">
<img width="998" alt="Screenshot 2019-03-20 at 4 36 50 PM" src="https://user-images.githubusercontent.com/131160/54717415-555c0080-4b15-11e9-995c-3600da8086d8.png">

**Comment by pronevich** [comment]
Thanks, @coco98 I was thinking that it is not possible to set _x-hasura_ headers from a client, now I see that this is possible and works great!

**Comment by barbaraDorame** [comment]
Do you guys have any project example configuration for this? I want to accomplish something like @coco98 but the links in his post are broken. Thanks for the help in advance

**Comment by Bessonov** [comment]
@pronevich @coco98 the example doesn't work anymore. Can you please document it here for further reference?

**Comment by pronevich** [comment]
@Bessonov send x-hasura-lang header from client and configure SELECT permissions in console based on x-hasura-lang

**Comment by jd88** [comment]
@pronevich I am sorry but I still not entirely clear how you do this. How do I define a select permission that returns a value based on a hasura request header? Currently I can only think of using a jsonb and a corresponding path-input.

**Comment by antonioberetini** [comment]
You could write a function that's cloning all string types into a separate table called "language" from individual tables. Use that language table to save English as a base language and cloned versions of it for each other language. Then create action to bind all of the request against individual tables to include all variants per each language in your output.

End result would be a single table for all translations and unified responses with all language variants unless you specific just one in your request.

In my implementation we have additional metadata table which collects all string fields from other tables. Then we have a Boolean field to define if a field should be localized or not.

I like the idea of passing language string via headers in addition to this.

**Comment by antonioberetini** [comment]
Yes that’s the best approach. I would also suggest automating creation of that field based on new records in your translation table.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CodingWithTashi** [comment]
> @antonioberetini Many Thanks for getting back to me. I have now created computed fields based on a header variable that uses returns a translated value based on a jsonb field. This has initially been proposed in [this talk](https://hasura.io/events/hasura-con-2021/talks/internationalization-with-hasura-how-to-make-your-backend-almost-as-smart-as-google-translate/).

@jd88 It works only with hasura-admin-secret, it does not work with jwt, can you confirm and share

**Comment by jd88** [comment]
@CodingWithTashi it‘s been quite some time that I have implemented it, but I think it worked with jwt as well.
