### ISSUE TITLE
Typo Hasura blogpost

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#1830]
Hi everyone,

I found a typo in the following blogpost: 
https://blog.hasura.io/architecture-of-a-high-performance-graphql-to-sql-server-58d9944b8a87/

In this sentence: 
"This gives roughly gives us a boost of 10–20% depending on the complexity of the GraphQL query."

_Gives_ is used twice.

**Comment by coco98** [comment]
Fixed! Thanks @marionschleifer :)
