### ISSUE TITLE
Integrate explorer into graphiql online

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1838]
graphiql online currently does not have explorer. We should integrate it asap.

**Comment by praveenweb** [comment]
@coco98 - It has already been integrated in this PR https://github.com/hasura/graphql-engine/pull/1817

We just haven't deployed it yet. It is currently hosted on Now 1.0 and we have to move to v2.0 and deploy this. Keeping this issue open until deployment is done.
