### ISSUE TITLE
Allow metadata reset CLI command to work even when metadata is inconsistent

### ISSUE THREAD

**Issue by danielcompton** [hasura/graphql-engine#1839]
We are managing our database schema in Django using Django models and migrations, and using Hasura for serving some of that data by GraphQL.

If we make a change in Django that is not backwards compatible with metadata we had stored in Hasura, Hasura is not able to boot. We are also not able to use `hasura metadata reset` or `hasura metadata apply` to reset the metadata. As far as I'm aware, there is no way to recover from this situation unless we reset the Hasura metadata before we shut down the graphql-engine, or perhaps by deleting the internal Hasura tables/schema.

It would be great if a version of `hasura metadata reset` was able to handle the engine not being able to start, and was able to delete any existing metadata directly out of the DB, then boot the graphql-engine to apply the new metadata. 

This relates to #231, but may be a much simpler fix as it doesn't require any UI or handling any inconsistency, just deleting the entire metadata DB.

**Comment by coco98** [comment]
@danielcompton For now, just go ahead and run these commands and then when hasura starts or reboots they'll be initialised again:

```sql
drop schema hdb_views cascade;
drop schema hdb_catalog cascade;
```

I'm adding a note in #231 that recovery should allow hasura metadata commands to be run at the very least.

**Comment by shahidhk** [comment]
Since #231 is merged, resetting metadata when it is inconsistent is possible from the CLI.

Closing the issue.
