### ISSUE TITLE
subscription on graphiql not working anymore

### ISSUE THREAD

**Issue by alanpog** [hasura/graphql-engine#1843]
When I try any subscription on the graphiql console I get:

```
{
  "errors": [
    "cannot start as connection_init failed with : invalid x-hasura-admin-secret/x-hasura-access-key"
  ]
}
```
Everything else works fine (eg. queries).
I'm using `v1.0.0-alpha40`. I know about #166 so this should be working.

**Comment by coco98** [comment]
If you’ve setup an admin secret have you enabled that on the header? Can
you send across a screenshot of the Hasura graphiql console when you’re
getting this error?

**Comment by alanpog** [comment]
Yes, it's on the header and working well for queries and mutations. A screenshot is attached.
![hasura subscription screenshot](https://user-images.githubusercontent.com/265086/54856439-46be4680-4cd9-11e9-95a0-0b66b6596e17.jpg)

**Comment by coco98** [comment]
Hm...it seems like the key is wrong. Can you double check with what you’ve
set in the env var, check for special characters etc?

**Comment by alanpog** [comment]
The key has to be right because it works for everything that is not a subscription.
This very screenshot is a regular query that I ran and worked right before substituting for s subscription to take the screenshot.

**Comment by coco98** [comment]
@alanpog 
Just tried it out here with https://subscription-test-hasura.herokuapp.com/console with the secret `helloyo` and running a subscription:

```
subscription {
  users {
    id
  }
}```

Are you sure your env var is named correctly? `HASURA_GRAPHQL_ADMIN_SECRET` ?

<img width="922" alt="Screenshot 2019-03-22 at 7 46 27 PM" src="https://user-images.githubusercontent.com/131160/54858457-40c96500-4cdb-11e9-8bfa-473c7014b084.png">

**Comment by alanpog** [comment]
Yes, it's all spelled out right. I've been using this instance for about a month, playing with graphiql on a daily basis with no problem (but hadn't tried subscriptions before). It was an `alpha39` instance which I upgraded wen `alpha40` came out.

I tried your example instance and subscriptions are working there indeed. Could it be that something else that mine has, but is absent in that simple instance, is interfering, like enabling JWT tokens?

<img width="378" alt="Screen Shot 2019-03-22 at 10 34 10 PM" src="https://user-images.githubusercontent.com/265086/54860041-27341780-4cf3-11e9-9463-0ee6f36e57b0.png">

**Comment by alanpog** [comment]
Weird. I created a new hasura heroku instance, same `alpha40` version, and `pg:copy` my db to it and copied the ENV vars, only changing the access key value. It's a perfect clone, did nothing else. However, subscriptions **work** there!
@coco98 , I'm closing this as I found a workaround, but if you think it's worth further investigating what's going on with the old instance let me know.

**Comment by ghyath5** [comment]
did you find a solution ?

**Comment by alanpog** [comment]
Yes, don’t remember now exactly what it was but ended up working it out.
Thanks for following up!
