### ISSUE TITLE
Extend table tracking API method so that we can name the table.

### ISSUE THREAD

**Issue by chrisnurse** [hasura/graphql-engine#1845]
## Extend table tracking API method so that we can name the table.

Why? If I have a db schema - hasura prefixes every table with the schema name, we could extend hasura-auto-tracker to allow a table name to be specified. This could lead to much more intuitive queries, the same way we have improved relationship naming (e.g. customer_orders)

```
{
    "type": "track_table",
    "args": {
        "schema": "myCrazySchemaName",
        "name": "customers"
        "table_name": "customers"  <- i.e. not myCrazySchemaName_customers
    }
}
```

**Comment by tirumaraiselvan** [comment]
Tracking this here: https://github.com/hasura/graphql-engine/issues/3811
