### ISSUE TITLE
Remote relationships

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#1846]
Since Hasura already supports schema stitching, are we able to specify relationship to remote tables ?

Suggestion:
When specifying manual relationship, options for remote table should also include remote tables from remote schemas.

**Comment by tirumaraiselvan** [comment]
This is an exciting new feature we are working on. A preview is also available here: https://github.com/hasura/graphql-engine/pull/1990

Happy to get feedback and use-cases for this feature.

**Comment by tirumaraiselvan** [comment]
Duplicate of #1225
