### ISSUE TITLE
CLI should rename metadata reset to metadata clear

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#1851]
The word "reset" is little ambiguous (reset to scratch or reset to last known consistent state). `metadata reset` clears the all the metadata to mimic a  freshly installed hasura instance. This actually invokes the `clear_metadata` API in the backend and hence should also be called `metadata clear` for perfect clarity.

All references to `metadata reset` should be changed to `metadata clear` i.e. docs, blogs, etc

**Comment by tirumaraiselvan** [comment]
cc: @0x777

**Comment by shahidhk** [comment]
@arvi3411301 We should rename the command to `metadata clear` and then add `reset` as an alias. Also, print a deprecation notice if we see that `reset` is used.
