### ISSUE TITLE
Unable to add primary key by pressing `tab` key

### ISSUE THREAD

**Issue by karthikvt26** [hasura/graphql-engine#1859]
Unable to create multiple primary key in a table by pressing tab key. Getting the following error

![screenshot 800](https://user-images.githubusercontent.com/25095884/54912422-9fc6ee00-4f16-11e9-8dab-72c23fc5e529.jpg)

**Comment by rikinsk** [comment]
@karthikvt26 Is this still happening? Couldn't reproduce

**Comment by karthikvt26** [comment]
I couldn't reproduce too. Its fixed now I think.
