### ISSUE TITLE
Different flags for delete_event_trigger query

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#1860]
The allowed flags will define the behaviour of existing event data when a trigger is deleted.

```
   clear_pending: true
   clear_processed: true
```

The behaviour for down_migration and replace_metadata should be fixed.

**Comment by manasag** [comment]
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.
