### ISSUE TITLE
"query_root fields must be an object with field names as keys..." on get-graphql-schema

### ISSUE THREAD

**Issue by krishkumar** [hasura/graphql-engine#187]
get-graphql-schema on Hasura GraphQL endpoints fails with the following error - 

`query_root fields must be an object with field names as keys or a function which returns such an object`

Getting the schema using Apollo works but fails with following error during Apollo codegen. 

`Syntax Error: Expected Name, found String "directives"`

**Comment by krishkumar** [comment]
This seems to be an issue with Apollo. Closing.

**Comment by coco98** [comment]
@wawhal can we check this issue in more detail and see if we need to submit a PR to apollo to get this to work seamlessly?

**Comment by wawhal** [comment]
@coco98 it is not really an issue with Apollo. This happens when the schema that it receives and tries to parse is empty.

For example, this error comes up in cases where access key is set and you try to get the schema without any headers. Or, if you are making the query as a certain role, and nothing is exposed to that role, this error will be thrown.

**Comment by coco98** [comment]
@krishkumar Would you recommend any changes we can make to our docs to make this more clear / easier? 

These are the current docs:
https://docs.hasura.io/1.0/graphql/manual/schema/export-graphql-schema.html

**Comment by krishkumar** [comment]
The issue really is with error messages of graphql itself, rather than Apollo or Hasura. 

@coco98 Your documentation itself I would not change, its minimal and good.

Consider adding a download schema functionality within Hasura itself. The Hasura web console or cli are good candidates to host this. Say - 

`hasura schema:download`

**Comment by coco98** [comment]
@shahidhk your thoughts?

**Comment by shahidhk** [comment]
Let me check how schema is exposed by the API.

**Comment by shahidhk** [comment]
tracked at #218
