### ISSUE TITLE
verify if curl respose is 200 in cli download script

### ISSUE THREAD

**Issue by martimatix** [hasura/graphql-engine#1871]
Following the instructions on [Installing Hasura CLI](https://docs.hasura.io/1.0/graphql/manual/hasura-cli/install-hasura-cli.html) is failing on OS X.

Steps to reproduce:

1. Below is the shell output of following the instructions form the above page

```
$ sudo curl -L https://github.com/hasura/graphql-engine/raw/master/cli/get.sh | bash

Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   139  100   139    0     0     21      0  0:00:06  0:00:06 --:--:--    39
100  3476  100  3476    0     0    424      0  0:00:08  0:00:08 --:--:--  6263
--> Getting latest version...
--> Latest version is v1.0.0-alpha41
--> Downloading hasura for darwin-amd64 to /tmp/cli-hasura-darwin-amd64
######################################################################## 100.0%
--> Download complete!
--> Moving cli from /tmp/cli-hasura-darwin-amd64 to /usr/local/bin
-->
--> hasura cli installed to /usr/local/bin
-->
/usr/local/bin/hasura: line 1: Not: command not found
```

2. Running `$ cat /usr/local/bin/hasura` outputs the following:

```
Not Found
```

**Comment by shahidhk** [comment]
Hello @martimatix. We were unable to reproduce this on a Mac. Can you try again and if it happens again, give us more details?

**Comment by martimatix** [comment]
It's working now.

Before I close this issue, is it worth raising an issue about not creating a file if the download failed? For example, in case of download failure, the installer could say something like "Something went wrong with installing Hasura CLI -- try again later."

Getting a "Not Found" file was not a great first experience of using Hasura CLI.

**Comment by shahidhk** [comment]
Indeed, we could verify the curl command gets a 200 response.

**Comment by shahidhk** [comment]
Changed the scope of issue to check if a 200 response is received while downloading the CLI
