### ISSUE TITLE
Enable event triggers & remote schemas even if migrations mode is off

### ISSUE THREAD

**Issue by jsleeuw** [hasura/graphql-engine#1875]
v1.0.0-alpha41 running on Heroku

Accessing the console using `hasura cli console` results in the Add CT on the remote schemas tab not appearing. Accessing the app directly (via the heroku url) renders the correct / expected behaviour

**Comment by coco98** [comment]
@rikinsk @shahidhk 👆

**Comment by rikinsk** [comment]
We just need to remove the check for migrations mode off and test everything works fine

**Comment by shahidhk** [comment]
Also need to make sure that the metadata file re-written for each action.

**Comment by AnnieAtHasura** [comment]
shahidhkToday at 11:49 AM
For every mutating action on the console (when migration mode is turned off) the CLI will export and save the metadata.yaml file automatically
Need to make sure that is happening
