### ISSUE TITLE
Minor UI glitch while browsing docs on different browsers

### ISSUE THREAD

**Issue by anubhav8421** [hasura/graphql-engine#1878]
I dont know if this will qualify as a valid issue or not, I am just sharing what I observed while I was browsing hasura graphql-engine docs, few days back.

Follow this [link](https://drive.google.com/openid=1zWhMQhhnzwIjCrksze66VzwJ7W0lUWzg) to see the glitch.

I did some research to find a fix. Found out that this drop down arrow (of the select tag) is the most difficult thing to be customized with css. Browsers are not uniform wrt its implementation.

[Stackoverflow question (1,413,121 views)](https://stackoverflow.com/questions/1895476/how-to-style-a-select-dropdown-with-only-css)

This is minor little thing to be observed by people, usually people use only one type of browser. 
My intention is to bring about uniformity among browsing experiences. 

There is a workaround I have found out, i.e to just remove the arrow with 3-4 lines of css. (Have to figure out how to do that in sphinx)

We only have v1.0 for the docs as of now, so arrow is also not that useful, and probably not clicked so often (my thoughts).

If this is accepted as a bug, I will submit a PR.

**Comment by rikinsk** [comment]
@anubhav8421 The link above leads to a 404 page. Could you verify it or simply just share screenshots if that's easier.

**Comment by anubhav8421** [comment]
Sorry, I didn't verify the link. Find the screenshot below 

![hasura_docs_glitch](https://user-images.githubusercontent.com/18699797/55084895-ba8e9380-50cb-11e9-94c1-1505791ee932.png)

**Comment by vijaybritto** [comment]
```appearance: none; ``` should fix this.

**Comment by anubhav8421** [comment]
Thanks for merging
