### ISSUE TITLE
Auto Save last written queries without needing to run the it first

### ISSUE THREAD

**Issue by Mike-Van** [hasura/graphql-engine#1879]

**Comment by shahidhk** [comment]
@Mike-Van I am guessing this is on the GraphiQL tab?

**Comment by rikinsk** [comment]
@Mike-Van Can you give more info on what you were expecting?

**Comment by marionschleifer** [comment]
I'm closing this issue. @Mike-Van please feel free to re-open if you would like to add anything 🙂

**Comment by rikinsk** [comment]
I kind of faced this myself and understood the issue. 
Currently any query written in GraphiQL does not persist in history unless you actually run it. 

I think #336 should take care of this issue
