### ISSUE TITLE
Don't show relationship suggestions to untracked table

### ISSUE THREAD

**Issue by karthikvt26** [hasura/graphql-engine#1882]
![screenshot 809](https://user-images.githubusercontent.com/25095884/55067048-037f2180-50a5-11e9-9c92-5bb568c1baad.jpg)

In the above screenshot table_2 has an object relationship which is not tracked. Clicking on `Track All Relations` throws error

**Comment by arvi3411301** [comment]
Tracking with PR https://github.com/hasura/graphql-engine/pull/2016
