### ISSUE TITLE
deploy a short lived app on heroku to manually test pull requests

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#189]

**Comment by arvi3411301** [comment]
@coco98 Force deploying a Heroku app via a comment is possible only if the status check for the latest commit is a success.

**Comment by arvi3411301** [comment]
Checklist for deploying Heroku app

- [ ] For every PR create a Heroku app, as the PR updates, update the app
- [ ] Whenever the PR gets merged the Heroku app can get deleted
- [ ] Force deploy Heroku app via a comment `/test-heroku`
