### ISSUE TITLE
alternate input type for types supporting _eq

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#1896]
Currently, the input syntax for giving equality is:

```
query {
  usermetadata(where: {type: {_eq : "something"}}) {
    id
    info
  }
}
```

It would be nice if an input type supporting `_eq` could also be represented as:

```
query {
  usermetadata(where: {type: "something"}) {
    id
    info
  }
}
```

**Comment by tirumaraiselvan** [comment]
Turns out GraphQL Spec does not allow SUM types for input fields :(

**Comment by picosam** [comment]
@tirumaraiselvan https://github.com/graphql/graphql-spec/blob/master/rfcs/InputUnion.md
