### ISSUE TITLE
_st_d_within function generates error

### ISSUE THREAD

**Issue by asindl** [hasura/graphql-engine#1899]
I can't execute the _st_d_within function successfully. All other spatial function do work though.
`query geom_table($polygon: geometry) {
  poi(where: {wkb_geometry: {_st_d_within: {distance: 5, from: $polygon}}}, limit: 5) {
    wkb_geometry
  }
}`
`{"polygon": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              133.59375,
              31.653381399664
            ],
            [
              146.25,
              31.653381399664
            ],
            [
              146.25,
              37.996162679728116
            ],
            [
              133.59375,
              37.996162679728116
            ],
            [
              133.59375,
              31.653381399664
            ]
          ]
        ]
  ,
    "crs":{
			"type":"name",
			"properties":{
				"name":"EPSG:4326"
			}
		}
      }
      }`

The error I get is:
`{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.poi.args.where.wkb_geometry._st_d_within.from",
        "code": "validation-failed"
      },
      "message": "variable polygon of type geometry is used in position expecting geometry!"
    }
  ]
}`

It works well for `query geom_table($polygon: geometry) {
  poi(where: {wkb_geometry: {_st_within: $polygon}}, limit: 5) {
    wkb_geometry
  }
}`

- Hasura 1.0.0 alpha41
- Postgres 10.5
- Hosted on Azure Container service

**Comment by shahidhk** [comment]
@asindl I think it's complaining that variable `polygon` is of type `geometry` while it is expecting `geometry!`. Can you edit the query to have the correct types and try again?

```graphql
query geom_table($polygon: geometry!) {...}
```

**Comment by asindl** [comment]
@shahidhk Thanks, it now does something. I will investigate the results later, but the `geometry!` helped.
Could you help me understand, what that `geometry!` means in contrast to `geometry` without the exclamation mark?

**Comment by asindl** [comment]
@shahidhk Found it: the exclamation mark indicates a non-nullable field.
I also got the geography type tested now and all works well.
So this can be closed.
