### ISSUE TITLE
document creating a view for public private data on the same table

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#1905]
e.g. user table, some fields can be public, like name, but some others are private and only corresponding users will be able to see them

**Comment by rikinsk** [comment]
https://docs.hasura.io/1.0/graphql/manual/queries/control-access.html ?

**Comment by shahidhk** [comment]
@rikinsk Maybe a more related user_profile table example?

**Comment by shahidhk** [comment]
This was added in https://github.com/hasura/graphql-engine/commit/d740de9ae2b9fd60deb27700e5f67cef286fa39a
