### ISSUE TITLE
Have separate tabs for database and graphql in console

### ISSUE THREAD

**Issue by rikinsk-zz** [hasura/graphql-engine#1906]
- The database tab can be used to handle all Postgres specific actions (think replacement for PGAdmin or adminer)

   This will allow users to do actions on tables/views/functions etc. like browsing rows, altering schema, adding indexes, adding constraints, etc. without having to track them

- The GraphQL tab will allow you to expose the database over GraphQL

  This will have actions to track tables/views/functions to expose over GraphQL, give aliases, set relationships/permissions, etc. Basically everything to do with the GraphQL API.

- The Database tab can have additional quick actions to link with the GraphQL tab in case the object is tracked.

**Comment by manasag** [comment]
Closing this as completed.
