### ISSUE TITLE
track metadata api throws bad request if object is already tracked

### ISSUE THREAD

**Issue by rikinsk-zz** [hasura/graphql-engine#1907]
Can it just respond with 200 with a message saying "already tracked".

The purpose of the API is to track an object and if the object is already tracked, technically the actions is done and hence should be a 200.

The problem is when multiple queries are being run as a transaction (like from console raw SQL),
the entire action fails if an object is already tracked. 

I cant think of a case where this being a bad request helps a user

**Comment by tirumaraiselvan** [comment]
Closing in favour of https://github.com/hasura/graphql-engine/issues/3959
