### ISSUE TITLE
Add support for single item inserts and selects

### ISSUE THREAD

**Issue by agstover** [hasura/graphql-engine#1910]
There's an issue when working with Hasura inserts and selects where the return formats for single items actions come back stuffed in a {returning: [item]} format. This adds to the complexity of handling the data client side. For most GraphQL Apollo examples on the web you'll see pretty straightforward data transfer between functions, as an example:
![image](https://user-images.githubusercontent.com/5091808/55263405-d9f9fd80-523e-11e9-9070-4ba2c75cea5f.png)

Doing it similarly with Hasura requires:
![image](https://user-images.githubusercontent.com/5091808/55263422-eed69100-523e-11e9-8f1b-d9631a662988.png)

And then handling the results of a getItemById query in UI components have to be carefully checked for existing properties. For example I basically have a List entity that has a Post entity in an array inside of it so if I want to map through the posts, you end up having to do things like this

```if(lists && lists[0] && lists[0].posts && lists[0].posts[0])```

as opposed to if the query just returned the single list entity you could do 
```if(list.posts[0]) {map(lists.post[0]) => (post => return post.title)```

**Comment by marionschleifer** [comment]
Closing this in favour of https://github.com/hasura/graphql-engine/issues/2047.
