### ISSUE TITLE
Cannot proceed to insert object X relation since insert to table X affects zero rows

### ISSUE THREAD

**Issue by danghung-dev** [hasura/graphql-engine#1911]
![image](https://user-images.githubusercontent.com/5670932/55270855-e92c8a00-52d6-11e9-8ecc-97597be2cb7d.png)

I want to insert a new opsOrder, and vehicle in single mutation.
It runs without error if vehicle does not exist.
But when vehicle is exist, it cannot be done. The return error message: `cannot proceed to insert object relation \"vehicle\" since insert to table \"vehicle\" affects zero rows`

I also added on_conflict constraint.

What should I do in above situation. 
Thanks.

**Comment by danghung-dev** [comment]
![image](https://user-images.githubusercontent.com/5670932/55271805-8bec0500-52e5-11e9-9cf7-5af0cba32b43.png)

I solved problem by change query like above

**Comment by 0x777** [comment]
@danghung-dev When `on_conflict` is set to `[]`, it is translated to `on update do nothing returning id` in sql which doesn't return the `id` on a conflict. But by explicitly setting `update_columns` to a non empty array, the row gets updated and the row information is returned which is then used to populate the top level row.

**Comment by tirumaraiselvan** [comment]
@samuela The workaround is to use the same column(s) that determine the uniqueness constraint. This way no new row is added. Although, this may have the side effect of executing any triggers on the underlying table.

**Comment by bitjson** [comment]
Is there some way to ignore this error? I would prefer that no columns are updated and the mutation continue.

In my data model, if the top-level insert affects zero rows, the nested object inserts are also guaranteed to affect zero rows. This sometimes occurs in a multi-step mutation, and it would be great if the rest of the transaction would continue so the whole mutation can be idempotent.

The workaround in [`Nested upsert caveats`](https://hasura.io/docs/1.0/graphql/core/mutations/upsert.html#nested-upsert-caveats) can cause thousands of unnecessary column updates and triggers (which can require cleanup too), so I'd prefer some way to completely skip the insert on conflict.

**Comment by FickleLife** [comment]
I have a unique constraint on a generated field (which stores the lower case version of the name of the record) - so that cannot be updated. My (ugly) workaround is to have a blank field that I write null to....

**Comment by rocketraman** [comment]
This workaround also does not work when users have insert permissions, but no update permissions. Even if both values being inserted already exist, and so the insert should silently succeed, Hasura fails because the user has no permissions to update the parent table, even though the update is a no-op.

This can be seen even with an insert on a single non-nested table -- except there the solution of using an empty `update_columns` works ok.

**Comment by Kirill89** [comment]
Why is this issue closed? Any solution beyond the workaround mentioned here?

**Comment by WynnD** [comment]
+1 for re-opening this issue. There is a workaround, but this is clearly not intended behavior.
