### ISSUE TITLE
JWT authentication fails using Firebase

### ISSUE THREAD

**Issue by chimame** [hasura/graphql-engine#1912]
## Overview
If you authenticate using Firebase's JWT as in [this](https://github.com/hasura/graphql-engine/tree/master/community/sample-apps/firebase-jwt) example or [here](https://blog.hasura.io/authentication-and-authorization-using-hasura-and-firebase/), the following message will be output and it will fail.

```
Could not verify JWT: JWTIssuedAtFuture
```

## Problems and suggestions
The interesting thing about this authentication failure is that if you make the same request several minutes after the authentication failure, the authentication will succeed.

Of course without changing the client program at all.

So I thought that the time zone was affecting, but the cause has not been identified yet.
I am using Firebase in the region of `asia-northeast1`. Hasura is used by Docker, but the time zone looks like UTC. Is this relevant?

By the way, the Function registered in Firebase is the same as the [sample](https://github.com/hasura/graphql-engine/blob/master/community/sample-apps/firebase-jwt/functions/index.js).

## Environment
docker:
- hasura: hasura/graphql-engine:v1.0.0-alpha41.cli-migrations
- postgres: postgres:11.1-alpine

**Comment by ecthiender** [comment]
Can you paste the offending JWT token? And also the corresponding logs on the hasura server (including the timestamp)?

**Comment by chimame** [comment]
@ecthiender Thanks for the response!

It is a JWT and a log created for the test.

#### First time
The response header is set to token.
```
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImZmMWRmNWExNWI1Y2Y1ODJiNjFhMjEzODVjMGNmYWVkZmRiNmE3NDgiLCJ0eXAiOiJKV1QifQ.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiXSwieC1oYXN1cmEtdXNlci1pZCI6InJmQ0E0RVdtajlPdEtKZExDV0JuSVI2RmxkeTIifSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2Nvbm5lY3Qtc29jaWV0eS1kZXZlbG9wbWVudCIsImF1ZCI6ImNvbm5lY3Qtc29jaWV0eS1kZXZlbG9wbWVudCIsImF1dGhfdGltZSI6MTU1NDExNjcwMSwidXNlcl9pZCI6InJmQ0E0RVdtajlPdEtKZExDV0JuSVI2RmxkeTIiLCJzdWIiOiJyZkNBNEVXbWo5T3RLSmRMQ1dCbklSNkZsZHkyIiwiaWF0IjoxNTU0MTE2NzAxLCJleHAiOjE1NTQxMjAzMDEsImVtYWlsIjoidGVzdEBob2dlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QGhvZ2UuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.i1rzhDL3xx8JNQsNoi9ERUMZgHafUG37BM4mEbsMODOaLutHL-bBcg4ndzsC9_GOYv6g0inaJ_4TSQ6_Yn_ufh_key9CWD7uGpLztNBe1GrVMz15BkkBnbkiCiwzQkUlLOtS9I-1h-VDExr_mDJHdUkUctZ-ByAH-93fuz5faO4uLjzqOhdA__FHTb6o-EzAJj-h983biZh3V2smX6ra7NXBNiY2c6TVFAAEbWQWkvRqeD7XWii4vQ-xUG98y9WpPyqi2Rp2wFNoAvOlLSV6vxeZu0Es5iQJ0Och9bzBDS8_HQqTFvYfwd_wWAVFyy2xMc5Q8RXjIb28OGak_jWjiA
```

It is a log of Hasura.
```
graphql-engine_1  | {"timestamp":"2019-04-01T11:00:54.201+0000","level":"info","type":"startup","detail":{"kind":"threads","info":{"thread_id":"ThreadId 26","instance_id":"057dca00-f592-41cf-b14b-319130cfb581","message":"listener thread started"}}}
graphql-engine_1  | {"timestamp":"2019-04-01T11:00:54.201+0000","level":"info","type":"startup","detail":{"kind":"threads","info":{"thread_id":"ThreadId 27","instance_id":"057dca00-f592-41cf-b14b-319130cfb581","message":"processor thread started"}}}
graphql-engine_1  | {"timestamp":"2019-04-01T11:00:54.201+0000","level":"info","type":"startup","detail":{"kind":"event_triggers","info":"starting workers"}}
graphql-engine_1  | {"timestamp":"2019-04-01T11:00:54.201+0000","level":"info","type":"startup","detail":{"kind":"telemetry","info":"Help us improve Hasura! The graphql-engine server collects anonymized usage stats which allows us to keep improving Hasura at warp speed. To read more or opt-out, visit https://docs.hasura.io/1.0/graphql/manual/guides/telemetry.html"}}
graphql-engine_1  | {"timestamp":"2019-04-01T11:00:54.201+0000","level":"info","type":"startup","detail":{"kind":"server","info":"starting API server"}}
graphql-engine_1  | {"timestamp":"2019-04-01T11:02:40.006+0000","level":"info","type":"http-log","detail":{"status":200,"query_hash":"ee249214255a3cb6e1464b5cdc06eda956f3c829","http_version":"HTTP/1.1","query_execution_time":2.844452e-3,"request_id":null,"url":"/v1alpha1/graphql","ip":"172.27.0.1","response_size":170,"user":{"x-hasura-role":"anonymous"},"method":"POST","detail":null}}
graphql-engine_1  | {"timestamp":"2019-04-01T11:02:40.006+0000","level":"info","type":"http-log","detail":{"status":400,"query_hash":"ee249214255a3cb6e1464b5cdc06eda956f3c829","http_version":"HTTP/1.1","query_execution_time":null,"request_id":null,"url":"/v1alpha1/graphql","ip":"172.27.0.1","response_size":83,"user":null,"method":"POST","detail":{"error":{"path":"$","error":"Could not verify JWT: JWTIssuedAtFuture","code":"invalid-jwt"},"request":"{\"operationName\":null,\"variables\":{},\"query\":\"{\\n  communities {\\n    id\\n    name\\n    description\\n    __typename\\n  }\\n}\\n\"}"}}}
```

It is the response contents in the browser.
![image](https://user-images.githubusercontent.com/7520815/55323255-8ba46300-54b9-11e9-94e8-1cc1a94f7363.png)

![image](https://user-images.githubusercontent.com/7520815/55323282-9f4fc980-54b9-11e9-8be4-ea5a6930e5ea.png)


#### Second time
The response header is set to token.
```
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImZmMWRmNWExNWI1Y2Y1ODJiNjFhMjEzODVjMGNmYWVkZmRiNmE3NDgiLCJ0eXAiOiJKV1QifQ.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiXSwieC1oYXN1cmEtdXNlci1pZCI6InJmQ0E0RVdtajlPdEtKZExDV0JuSVI2RmxkeTIifSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2Nvbm5lY3Qtc29jaWV0eS1kZXZlbG9wbWVudCIsImF1ZCI6ImNvbm5lY3Qtc29jaWV0eS1kZXZlbG9wbWVudCIsImF1dGhfdGltZSI6MTU1NDExNjcwMSwidXNlcl9pZCI6InJmQ0E0RVdtajlPdEtKZExDV0JuSVI2RmxkeTIiLCJzdWIiOiJyZkNBNEVXbWo5T3RLSmRMQ1dCbklSNkZsZHkyIiwiaWF0IjoxNTU0MTE2NzAxLCJleHAiOjE1NTQxMjAzMDEsImVtYWlsIjoidGVzdEBob2dlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QGhvZ2UuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.i1rzhDL3xx8JNQsNoi9ERUMZgHafUG37BM4mEbsMODOaLutHL-bBcg4ndzsC9_GOYv6g0inaJ_4TSQ6_Yn_ufh_key9CWD7uGpLztNBe1GrVMz15BkkBnbkiCiwzQkUlLOtS9I-1h-VDExr_mDJHdUkUctZ-ByAH-93fuz5faO4uLjzqOhdA__FHTb6o-EzAJj-h983biZh3V2smX6ra7NXBNiY2c6TVFAAEbWQWkvRqeD7XWii4vQ-xUG98y9WpPyqi2Rp2wFNoAvOlLSV6vxeZu0Es5iQJ0Och9bzBDS8_HQqTFvYfwd_wWAVFyy2xMc5Q8RXjIb28OGak_jWjiA
```

It is a log of Hasura.
```
graphql-engine_1  | {"timestamp":"2019-04-01T11:06:14.467+0000","level":"info","type":"http-log","detail":{"status":200,"query_hash":"ee249214255a3cb6e1464b5cdc06eda956f3c829","http_version":"HTTP/1.1","query_execution_time":6.76404e-4,"request_id":null,"url":"/v1alpha1/graphql","ip":"172.27.0.1","response_size":170,"user":{"x-hasura-role":"user","x-hasura-user-id":"rfCA4EWmj9OtKJdLCWBnIR6Fldy2"},"method":"POST","detail":null}}
```

It is the response contents in the browser.
![image](https://user-images.githubusercontent.com/7520815/55323416-fd7cac80-54b9-11e9-8a5d-92c151bc4643.png)

![image](https://user-images.githubusercontent.com/7520815/55323446-0cfbf580-54ba-11e9-9839-f70a43d283fe.png)

**Comment by ecthiender** [comment]
@chimame 

From your  "First time" section:

I pasted the JWT token in https://jwt.io/ to decode it. Looks like the token was issued at Monday, April 1, 2019 11:05:01 UTC (1554116701), the `iat` field in the token payload. But the timestamp in the log (where the error message occurs) is 2019-04-01T11:02:40.006+0000 UTC. So, indeed it looks the (from the server's point of view) that the token was issued in the future. (One reason could be the machine where the container is running has misconfigured time?)

Second time, you used the same token on the same server, without any changes, and it worked?

**Comment by chimame** [comment]
@ecthiender 
Thank you for your help

I am using the same token for the second time and processing it on the same server. I just reloaded on F5.

Since I live in Japan, I am 9 hours ahead of JST, that is UTC. Therefore I understand that there is a difference of 9 hours. It is strange that there is a difference of about 2 minutes and 20 seconds.
The cause was that my PC time was not correct. By setting the time correctly, we were able to confirm that we were correctly authenticated.

Thank you!

**Comment by ElixirMike** [comment]
I am seeing this exact same issue. When you reload the page, the getIDToken() method generates a new token to use..and I believe the timing of generating the token, then calling Hasura causes the issue. If you keep the same token and call the api a few seconds later, it works...

IS there any workaround/update for this?

**Comment by brush701** [comment]
I was also having this issue, but found a solution. I'm running on WSL2, and interestingly there are clock-sync issues that arise. In my case, the WSL clock was a few seconds behind NTP time. Updating the Windows clock made no difference, but running ntpdate from the bash prompt worked like a charm. A simple workaround is to add `sudo ntpdate -sb time.nist.gov` to .bashrc and edit sudoers to grant permissions.

**Comment by surkat919** [comment]
@brush701 Did you have to run `sudo ntpdate -sb time.nist.gov`  on Hasura docker  frontend web app docker containers?

**Comment by vectrobyte** [comment]
I'm having this same issue on macbook pro as well. Looks like this is not just the issue on WSL2 after all.

**Comment by spencerpauly** [comment]
I'm having the same issue on a 16" Macbook Pro as-well using NextAuth and Hasura on DigitalOcean. Here is the code for the formatting of the JWT for me. When I decrypt the JWT it appears the timestamp is correct:
```
		encode: async ({ token, secret }: { token: Token; secret: string }) => {
			const tokenContents = {
				id: `${token.id}`,
				name: token.name,
				email: token.email,
				picture: token.picture,
				'https://hasura.io/jwt/claims': {
					'x-hasura-allowed-roles': ['admin', 'user'],
					'x-hasura-default-role': 'user',
					'x-hasura-role': 'user',
					'x-hasura-user-id': `${token.id}`,
				},
				iat: Date.now() / 1000,
				exp: Math.floor(Date.now() / 1000) + 72 * 60 * 60,
				sub: `${token.id}`,
			};

			const encodedToken = jwt.sign(tokenContents, jwtSecret.key, {
				algorithm: jwtSecret.type,
			});

			return encodedToken;
		},
```

**Comment by ericksonc** [comment]
I have the same issue on a MacBook Pro as well. In my case the JWT is issued just a few moments in the "future," so the initial load triggers this error, but any interaction using the same token is fine.

**Comment by cpursley** [comment]
Same here. Any work-around suggestions?

**Comment by ryparker** [comment]
For Mac users: Running `sudo sntp -sS time.apple.com` resolved this for me.

**Comment by magidandrew** [comment]
For me, it was even simpler (on mac):

1. `podman machine ssh`
2. restart the time sync service: `sudo systemctl restart chronyd.service`
3. exit the vm with: `exit`
