### ISSUE TITLE
Add documentation for soft deletes

### ISSUE THREAD

**Issue by jasonmccallister** [hasura/graphql-engine#1936]
This is from a conversation within Discord.

> I know this may get a little out of scope and enforce some "specifics" on database design... but has anyone thought about the concept of soft deletes? Specifically right now we keep items with a "deleted_at" timestamp that is nullable... to show non-deleted items we have to add that as a query (where deleted_at is null). What if we had a type of soft deletes that specifically excluded those items from the query when that field/type is present?

A lot of modern database design is to include a "soft deletes" column, applications like Laravel adopt this Active Record pattern (I think it comes from active record).

Given the following table:

Users
- id: UUID
- name: Text
- deleted_at: Timestamp (nullable)
- created_at: Timestamp
- updated_at: Timestamp 

When you write the mutation to make deleted_at with a current timestamp, you have to ensure you exclude that from the initial query. If there was a type of field for "soft deletes", it would automatically exclude the records with a non-null value from the query.

Also, it would be amazing to have a field type that supported "with deleted" as a boolean to make the query include soft deleted items. Laravel has a nice fluent issue method to handle this: https://laravel.com/docs/5.8/eloquent#soft-deleting

**Comment by jasonmccallister** [comment]
Closing this ticket out per conversation in Discord, this is achievable with permissions... You can add a custom check where `deleted_at` is null.

![unknown](https://user-images.githubusercontent.com/5354908/55439915-0c279a00-5574-11e9-9880-8fe70ed2cee1.png)

**Comment by dariocravero** [comment]
If your policy is to use soft deletes, I wonder how can we enforce them in Hasura. A couple of questions come to mind:

- Would we need to restrict delete operations in favour of updates?
- Would it be possible to instruct delete operations to work on a soft delete mode? That would allow us to keep the semantics of delete without having to worry about the implementation details when consuming the API.

I wonder what people's thoughts are on this or if there's a way to do it already.
Thanks!

**Comment by OLDIN** [comment]
I am also interested to receive answers to the questions above.

**Comment by jasonmccallister** [comment]
I made a PR for the documentation here #1980.

In the application we would just allow that user role to update, and only set the deleted_at, when updating.

**Comment by rikinsk** [comment]
Closed in #1980

**Comment by jdinartejesus** [comment]
@jasonmccallister but there's an issue when using unique, if I want to have column + column + delete_at as unique doesn't work. Since in PostgreSQL, the NULL value isn't equal to each other.
