### ISSUE TITLE
add an api which can execute pg_dump on the database

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#1939]
Using this API, a user should be able to get the Postgres schema dump.

```http
POST /v1alpha1/pg_dump
Content-Type: application/json

{
  "schema": "public"
}
```

response will be a file download

**Comment by mnlbox** [comment]
@shahidhk Any guide or docs about how we can use this with CLI?

**Comment by shahidhk** [comment]
@mnlbox The migration related command is documented here: https://docs.hasura.io/1.0/graphql/manual/migrations/existing-database.html#step-3-initialize-the-migrations-as-per-your-current-state

The API documentation is here: https://docs.hasura.io/1.0/graphql/manual/api-reference/pgdump.html
