### ISSUE TITLE
permissions role name once created cannot be edited or deleted

### ISSUE THREAD

**Issue by moksahero** [hasura/graphql-engine#194]
Can'e edit permission name or delete it once created.

**Comment by praveenweb** [comment]
Hi @moksahero - You won't be able to edit the role name for an existing permission.
You can delete the permission for a particular role by clicking on ``Remove all access`` button. 

<img width="685" alt="permission_remove" src="https://user-images.githubusercontent.com/14110316/43121127-4f4e1a26-8f3a-11e8-9e65-0ea9bbc0142a.png">
