### ISSUE TITLE
Signed in user without 'https://hasura.io/jwt/claims' should have API access as anonymous

### ISSUE THREAD

**Issue by pronevich** [hasura/graphql-engine#1944]
Maybe there is a reason how it works now, here what is going on:

1. Anonymous user get data which has _select_ permission for 'anonymous' role
2. Then user Registered/Signed In, but still hasn't Hasura claims, because role will be added later.
3. After that API generate error: 
```{"errors":[{"extensions":{"path":"$","code":"jwt-invalid-claims"},"message":"claims key: 'https://hasura.io/jwt/claims' not found"}]}``` 
and we can't use it: `...compute.amazonaws.com/v1alpha1/graphql 400 (Bad Request)`
4. But user still should see data available for _anonymous_

**Comment by shahidhk** [comment]
@pronevich Have you set `HASURA_GRAPHQL_UNAUTHORIZED_ROLE=anonymous`? If yes, all requests without the `Authorization` or `X-Hasura-Admin-Secret` header will get this role.

If you'd still like to issue JWT for anonymous role, you can add the following claims: 
```json
  "https://hasura.io/jwt/claims": {
    "x-hasura-role": "anonymous"
  }
```

**Comment by pronevich** [comment]
Thanks, @shahidhk I will try to add role to claims on user registration.
