### ISSUE TITLE
Force enable metadata API when running temp server in cli-migrations container ?

### ISSUE THREAD

**Issue by elnygren** [hasura/graphql-engine#1946]
Hasura allows applying metadata and migrations via the CLI container which is excellent for real-life production usecases.

Hasura also allows disabling console and its endpoints for security. However, this (I presume) blocks the CLI from applying migrations and metadata.

Since the CLI container's entrypoint script already spins a temporary hasura server for applying the metadata & migrations, perhaps we can just force the metadata API for that temp server?

https://github.com/hasura/graphql-engine/blob/c964c90a7b96ff4eeba6581b1acd40acae7ad589/scripts/cli-migrations/docker-entrypoint.sh#L32

I confirmed the issue with:

```bash
docker run -p 8888:8080 \
 -v $PWD:/hasura-migrations \
 -e HASURA_GRAPHQL_DATABASE_URL=my-db \
 -e HASURA_GRAPHQL_ENABLED_APIS=graphql\
 --name hasura-cli-test \
 hasura/graphql-engine:v1.0.0-alpha41.cli-migrations
```

Fixing this would allow disabling `metadata` APIs while still applying the newest metadata configs, which would be great for proper CI/CD flows.

An alternative solution would be, that Hasura server looks for metadata from a specific location without any need for running the metadata APIs.

**Comment by shahidhk** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/b7fb4eb13e255eec498f1ded795db76e7fbcb9de
