### ISSUE TITLE
Default value of boolean in console data entry not reflected in dropdown

### ISSUE THREAD

**Issue by michaelhayman** [hasura/graphql-engine#1948]
When doing data entry via the console, the selected value for a boolean field is true always, even when the default value for that field is false.

I don't know Haskell but I'll have a crack at fixing this later.

**Comment by mnlbox** [comment]
@michaelhayman Are you sure?
It's OK in my side :thinking:

**Comment by michaelhayman** [comment]
Yep, even after upgrading to latest.  Perhaps I'm entering 'false' improperly as a default value, but Postgres accepts it.

<img width="853" alt="Screen Shot 2019-04-09 at 06 39 57" src="https://user-images.githubusercontent.com/1134239/55769588-65bb2780-5a92-11e9-9df0-a8cd9f02c011.png">
<img width="621" alt="Screen Shot 2019-04-09 at 06 39 53" src="https://user-images.githubusercontent.com/1134239/55769589-6653be00-5a92-11e9-9bb3-a257b9f452a6.png">

**Comment by rikinsk** [comment]
This is fixed in #1985
