### ISSUE TITLE
server configured with https webhooks throws exception

### ISSUE THREAD

**Issue by moksahero** [hasura/graphql-engine#195]
Calling auth webhook from Heroku instance with Authorization header returns correct X-Hasura-User-Id and X-Hasura-Role from GraphiQL page.

However a call to the same webhook URL from docker instance on Ubuntu 16.04 server gives me this error and can't get correct X-Hasura headers sent back.

{
  "errors": [
    {
      "path": "$",
      "error": "HTTP Exception from Webhook",
      "code": "unexpected"
    }
  ]
}

webhook URL used: https://us-central1-vue-hasura-auth.cloudfunctions.net/hasuraWebhook

**Comment by ecthiender** [comment]
@moksahero 
Have you checked the logs of your webhook service? The error "HTTP exception from webhook" usually means it received a 500 from the webhook.

**Comment by shahidhk** [comment]
@0x777 @rakeshkky @ecthiender There is something wrong here. I couldn't get webhook working on Heroku. Hook is deployed on glitch. @wawhal tried with a localhost webhook, that is also throwing same error. 

Server logs are not helping much, one thing we noted is that webhook is not getting called.

**Comment by shahidhk** [comment]
Are there CA certs in the docker image for server?

**Comment by shahidhk** [comment]
Okay, @wawhal says, HTTP works, HTTPS webhooks throw the exception.

Missing CA certs
