### ISSUE TITLE
Autoincrement field in console gets lost over time

### ISSUE THREAD

**Issue by michaelhayman** [hasura/graphql-engine#1951]
When repeatedly entering data, sometimes an autoincrement integer field shows as a normal integer and it takes having to click on the table name on the left hand side and refreshing the component to get it back to the normal behaviour of not needing to enter an integer there.

**Comment by rikinsk** [comment]
@michaelhayman Hi. Thanks for reporting this. Unfortunately I couldn't reproduce this situation on my system. If you can recreate this, can you give more details on how you end up in this situation?

**Comment by michaelhayman** [comment]
I think it's an error on my end - must have had something to do with editing then inserting.  If I legitimately run into it again I'll reopen.
