### ISSUE TITLE
Documentation code wrapping is confusing for commands

### ISSUE THREAD

**Issue by kigiri** [hasura/graphql-engine#1954]
### Actual:
![wrap-before](https://user-images.githubusercontent.com/231748/55645585-e519d400-57d0-11e9-9f5f-ba21050b7739.png)
> here, `migration file` look like possible command arguments.

### Wanted:
![wrap-after](https://user-images.githubusercontent.com/231748/55645584-e519d400-57d0-11e9-81bd-cda6805d0b6d.png)

The css rule is applied by the normalize embed in `/_static/djangosite.css`

I can make a pull request if you agree this is an issue, but I'm not sure were should I override it, `/_static/hasura-custom.css` maybe ?

**Comment by shahidhk** [comment]
Thanks @kigiri! @rikinsk Please point @kigiri to the right file?

**Comment by rikinsk** [comment]
@kigiri Thanks for wanting to fix this. It is indeed a problem. You can add the override in `/_static/hasura-custom.css` as you mentioned.
