### ISSUE TITLE
Filed level access based on role

### ISSUE THREAD

**Issue by jeronimo13** [hasura/graphql-engine#1957]
Hi 

I have a role ‘user’ and a db ‘users’:
- id
- name
- secret_field

Is it possible to limit ‘read’ operation of ‘secret_field’ only to owner of account(I’m ok with secret_field resolving with null to other users)?

**Comment by amanvishnani** [comment]
You can assign multiple roles to a user. Add the secret field to select permission of that `new role`, set checks for `user_id` equals to `x-hasura-user-id` and access that field using new role.

Or create a new table with name `user_secrets`, set permission to allow access to object to only that user.
### Schema
![image](https://user-images.githubusercontent.com/8425802/55688569-8d799500-5997-11e9-8b6a-f44cee89c609.png)

### Permissions
![image](https://user-images.githubusercontent.com/8425802/55688575-979b9380-5997-11e9-8143-a558b50b939d.png)

**Comment by jeronimo13** [comment]
Thank you @amanvishnani for the quick response!
Regarding your first proposition: as far as I understood from documentation multiple roles resolve to only one role(X-HASURA-ROLE.) And hasura creates a different graphql scheme depending on role, which I'm not a big fan of. This is what I end up with:
<img width="1304" alt="изображение" src="https://user-images.githubusercontent.com/13887712/55689652-e2b1a880-598f-11e9-8ef2-8a9744652afd.png">
<img width="1253" alt="изображение" src="https://user-images.githubusercontent.com/13887712/55689657-f6f5a580-598f-11e9-9e79-ea11f8c03e55.png">
<img width="584" alt="изображение" src="https://user-images.githubusercontent.com/13887712/55689663-05dc5800-5990-11e9-9c26-0731bb975bdd.png">
<img width="578" alt="изображение" src="https://user-images.githubusercontent.com/13887712/55689665-0b39a280-5990-11e9-9451-5813c6452607.png">
Fields `id` and `email` are private and they are not present in graphql in case role is `user`

Is it OK for client to manage field base access?

I like your second approach better, because in that case user don't have to "remember" which role map to which request

Would like to hear your comments on that

**Comment by amanvishnani** [comment]
I personally like the second approach but I find a drawback with it. You need to maintain two tables.
If that's fine go ahead with it.

**Comment by jeronimo13** [comment]
I think you mean “close”. Yes, feel free to close. Thank you for help!

**Comment by marionschleifer** [comment]
Alright, I'm closing this issue 🙂 @jeronimo13 feel free to re-open it if you would like to add anything.
