### ISSUE TITLE
Exhaustive tests for HGE

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#196]
**Tests**

- [x] Port existing tests
- [ ] Subscriptions tests are absent
- [ ] Boolean expressions not exhaustive
- [ ] Permissions system not exhaustive
- [ ] /v1/query tests
- [ ] /api/1/table tests
- [ ] tests with access key
- [ ] tests with https webhook (https://us-central1-hasura-io.cloudfunctions.net/graphql-engine-webhook-test)

**Comment by ecthiender** [comment]
@nizar-m can you do this in the python tests? As we no longer haskell tests.

**Comment by 0x777** [comment]
closed with #710
