### ISSUE TITLE
hasura query using heroku scheduler

### ISSUE THREAD

**Issue by bisyonary** [hasura/graphql-engine#1961]
Is there a way to run scheduled SQL query on Hasura running on Heroku?

Tried installing Heroku Scheduler add-on but I can't seem to get past pg:sql command. Error is command not found.

https://devcenter.heroku.com/articles/scheduler
Docs on heroku describes Rails>rake tasks but I can't seem to push bin files to the heroku container. Any ideas? 

Thank you so much.

**Comment by tirumaraiselvan** [comment]
There is no native way in hasura to schedule queries yet. You may be interested in #1914 though.

You are right in your Heroku Scheduler approach but I haven't played with it much so you may ask about in https://discord.gg/hasura or Heroku support channels.
