### ISSUE TITLE
Hasura logs return postgres-error

### ISSUE THREAD

**Issue by szhang-ezypay** [hasura/graphql-engine#1966]
Hi, I'm having an issue with Hasura docker logs. We have several Hasura servers connected to our postgres. But lately, some of them start to generate error logs every second.

I don't know why this is happening as we haven't changed our DB or Hasura servers. And funny thing is Hasura servers work absolutely fine even with these errors.

The only way to stop the log is to config everything from scratch. But the log will come back in a short while. I have checked the DB and the `event_log` and `event_triggers` tables are all there.

`{"timestamp":"2019-04-09T02:05:32.377+0000","level":"error","type":"event-trigger","detail":{"internal":{"statement":"\n      UPDATE hdb_catalog.event_log\n      SET locked = 't'\n      WHERE id IN ( SELECT l.id\n                    FROM hdb_catalog.event_log l\n                    JOIN hdb_catalog.event_triggers e\n                    ON (l.trigger_id = e.id)\n                    WHERE l.delivered ='f' and l.error = 'f' and l.locked = 'f' and (l.next_retry_at is NULL or l.next_retry_at <= now())\n                    LIMIT 100 )\n      RETURNING id, schema_name, table_name, trigger_id, trigger_name, payload::json, tries, created_at\n      ","prepared":true,"error":{"exec_status":"FatalError","hint":null,"message":"column l.trigger_id does not exist","status_code":"42703","description":null},"arguments":[]},"path":"$","error":"postgres query error","code":"postgres-error"}}`

**Comment by tirumaraiselvan** [comment]
Are all the instances running at alpha41 or higher versions? 

This happens when Hasura is migrated to alpha41 but still few replicas are running at lower versions.

**Comment by marionschleifer** [comment]
I'm closing this. @szhang-ezypay please feel free to re-open if you would like to add anything 🙂
