### ISSUE TITLE
Bug report: invalid analyze SQL when use '_or' in query

### ISSUE THREAD

**Issue by Tsui89** [hasura/graphql-engine#1973]
this is bug, when use '_or', the analyze SQL use ‘AND‘.
![image](https://user-images.githubusercontent.com/6268537/55860406-ba4fc700-5ba6-11e9-9ff8-ed3b6bb19fe2.png)
![image](https://user-images.githubusercontent.com/6268537/55860508-faaf4500-5ba6-11e9-850f-e64081a2fada.png)

**Comment by 0x777** [comment]
Hi, the where condition should be:
```graphql
{
  _or: [
    {eqp_name: {_ilike: "%a%"}}, 
    {eqp_id: {_ilike: "%a%"}}
  ]
}
```
`_or` takes a list of boolean expressions and `OR`s them. In your case, you have provided one boolean expression, which is `{eqp_name: {_ilike: "%a%"} eqp_id: {_ilike: "%a%"}}`. All fields provided in a boolean expression are `AND`ed and hence the behavior that you are seeing.

**Comment by Tsui89** [comment]
@0x777 thanks, that's right.

**Comment by ibash** [comment]
@0x777 FWIW this is currently what the hasura console produces for `_or` queries
