### ISSUE TITLE
query execution failed :   "message": "there is no unique ed table \"xxxx\   "status_code": "42830",

### ISSUE THREAD

**Issue by rasheedk** [hasura/graphql-engine#1989]
Error on presence of json objects , please see this sample json data

    "prepared": false,
    "error": {
      "exec_status": "FatalError",
      "hint": null,
      "message": "there is no uniqueed table \"users\"",
      "status_code": "42830",
      "description": null
    },
    "arguments": []
  },
  "path": "$.args",
  "error": "query execution failed",
  "code": "postgres-error"
}

**Comment by 0x777** [comment]
@rasheedk How was this error triggered? Can you provide the schema and the query to reproduce this?

**Comment by marionschleifer** [comment]
@rasheedk any update on this? 🙂

**Comment by 0x777** [comment]
@rasheedk closing this for now. Please feel free to open this issue with more information.
