### ISSUE TITLE
expected Text, encountered Number : Please add support for numbers in json

### ISSUE THREAD

**Issue by rasheedk** [hasura/graphql-engine#1998]
firebasetographql issue:

Verifying URL... Done!
Processing Firebase JSON... Done!
Checking database... Skipped!
Creating tables... Done!
Tracking tables... Done!
Creating relationships... Done!
Inserting 0 to 5 rows of 5 in table _Kjm__mNnUKDs1qGuC4M... Error
Restoring database to a safe state... Done!
Message: Schema has been imported. But the data could not be imported due to the
 following error.

{
  "graphQLErrors": [],
  "networkError": {
    "name": "ServerError",
    "response": {
      "size": 0,
      "timeout": 0
    },
    "statusCode": 400,
    "result": {
      "errors": [
        {
          "extensions": {
            "path": "$.variableValues[3]._value",
            "code": "parse-failed"
          },
          "message": "expected Text, encountered Number"
        }
      ]
    }
  },
  "message": "Network error: Response not successful: Received status code 400"
}

I could not import the data due to number in the json.

**Comment by wawhal** [comment]
@rasheedk this happens mostly because of inconsistency in the data. `firebase2graphql` expects a field to have data of a single data type. Can you give me an example dataset so that  I can tell you the exact problem?

**Comment by marionschleifer** [comment]
I'm closing this issue. @rasheedk feel free to re-open it if you would like to add anything 🙂
