### ISSUE TITLE
docs: add docs on hasura deploy regions

### ISSUE THREAD

**Issue by jeronimo13** [hasura/graphql-engine#2013]
I've been experimenting with Hasura and Heroku and found out that when you create RDS instance on AWS one should consider creating it on us-east-1 because us Heroku region is basically the same
I've migrated my RDS from us-west-2 to us-east-1 and latency decreased 4 times
Maybe somebody could note it in documentation?

**Comment by robertjdominguez** [comment]
Thanks for this @jeronimo13. Even though it's been a while since you opened this issue, we now have several places in docs pointing this out 👍
