### ISSUE TITLE
The remote schema use 3rd party rest APIs, please！🙏

### ISSUE THREAD

**Issue by Eden-Harris** [hasura/graphql-engine#2014]
> ### it's very basic and important，we have much old rest APIs and restFul APIs, and we often use 3rd party rest or restful APIs, the APIs is not graphql, if the remote schema can edit body, that's great!!!
> ### the APIs from other company and not running on our own server, we cannot Convert to graphql or is will cause a lot of bugs, it's too complicated and heavy!
> #### the APIs like this:
```json
{
    "url": "https://b.dgacel.com.co/crm/so/edOrderProdDtl?MmEwMD=3_b5qGLGovpMIFQok4",
    "headers":{
        "Cookie":"JSESSIONID=187579F31AF43519349F92DF73C07740;FSSBBIl1UgzbN7N8443T=38BZs26UppWli4EPN3c6jG.dzaq;",
        "X-Requested-With":"XMLHttpRequest"
    },
    "body":{
        "prodInstId":12,
        "installArea":"rJjY3KmDUXPQ35aqdp+JSw==",
        "inFrame":["a","b","c"]
    }
}
// -----------------------------------------------------------------------------------------------
{
    "url": "https://apis.g2r3557oe.com",
    "headers":{
        "token":"rshbt5rt45edmlkfm.gklfdmje2343tk5rmhyftsgfdsmfesfdbgfh23y43o54egvfn",
        "Content-Type":" application/json; charset=UTF-8"
    },
    "body":{
        "name":"Sam",
        "gander":"male",
        "age":19,
        "studentID":245120180912887634592,
        "science": false //  default is true
    }
}
```

## I want to use hasura to integrate existing REST APIs and third-party REST APIs.

![image](https://user-images.githubusercontent.com/28903167/54404412-4d175600-470e-11e9-8f98-2e954300b912.png)

> #### I think other developers also will have this trouble, we usually use a lot of old REST-API from 3rd party SDK, and my company 's APIs, It's all rest or restful APIs

> #### If I create a remote schema has the body's field from rest API's field, this will greatly reduce the workload and unify `old API` to `graphql`, I hope that hasura provide such a function, thanks!

**Comment by ecthiender** [comment]
We already have an issue to support this feature. Ref: #1279 . Please upvote and/or comment on that issue.

In the meantime, you can write your own custom graphql server, which wraps over these REST APIs.

**Comment by tirumaraiselvan** [comment]
Meanwhile, here is a blogpost for wrapping REST apis through Remote Schemas: https://blog.hasura.io/create-a-remote-schema-to-wrap-a-rest-api-hasura/

**Comment by mnlbox** [comment]
@ecthiender, @tirumaraiselvan Wrapping graphQL over REST APIs is a solution but it's a repetitive task and can be automate with tools like Hasura.
We can talking more about this in #1279

**Comment by Eden-Harris** [comment]
@ecthiender @tirumaraiselvan @mnlbox  😢  Yeah, I Kwon, but #1279 is not an elegant and simple way, it is too cumbersome and error-prone, especially when faced with a large number of old APIs. If you write in `remote schema `, you can guarantee higher performance and quick and easy packaging of these `rest APIs`, maybe it's right?  Especially in the face of transforming many old programs and integrating third-party service APIs, maybe this is really a good proposal.  🙏 However, thank you for your help.

**Comment by coco98** [comment]
@Eden-Harris Would love to discuss your use-case in more detail in the meanwhile. I'm @tanmaig on our discord. Please do ping me there! https://discord.gg/hasura
