### ISSUE TITLE
fix foreign tables on console (misclassified as views)

### ISSUE THREAD

**Issue by psychodad71** [hasura/graphql-engine#2017]
Support for foreign tables would help hasura to become a skyscraper without guard-rails. Postgres would act as a proxy between a foreign database (clickhouse, mssql,db2,mysql...) and the graphql-engine of hasura.
![Screenshot_20190416-154842](https://user-images.githubusercontent.com/20539095/56215498-12cc0c00-6060-11e9-8a05-542cc1682d95.png)

**Comment by tirumaraiselvan** [comment]
We do support foreign tables but currently they are misclassified as views. See PR here for more explanation: https://github.com/hasura/graphql-engine/pull/4742 

Changing the title to reflect the same.

**Comment by beerose** [comment]
Solved in https://github.com/hasura/graphql-engine/pull/5258
