### ISSUE TITLE
support columns comparison on permission rules 

### ISSUE THREAD

**Issue by 22mahmoud** [hasura/graphql-engine#2040]
In my case, I have "bid" table has  "amount" column and I want to check if that amount greater than the current "price" in the "auction" table.

expected query
```
{"auction":{"price":{"_lt":"current bid amount"}}}
```

**Comment by rakeshkky** [comment]
Hi @22mahmoud, currently we do not have support for operators which work on columns of the same table. This is being tracked [here](https://github.com/hasura/graphql-engine/issues/457). 

A quick and dirty workaround is to use a view as follows:

```sql
create view bid_v as select u.*, (u.amount > u.price) as is_amount_greater from bid u;
```
Then you can query it as follows:

```graphql
{
  bid_v(where: {is_amount_greater: {_eq: true}}) {
    amount
  }
}
```

**Comment by coco98** [comment]
@rakeshkky Given the conversation with @22mahmoud I think @22mahmoud wants to use it in a permission rule as a check constraint.

**Comment by 22mahmoud** [comment]
as @coco98  said I want to use it in a permission rule as a check

**Comment by 0x777** [comment]
@rikinsk We already support column operators in permission definitions on server side, the operators are `_ceq`, `_cne`, `_cgt`, `_clt`, `_cgte` and `_clte`. We need to add these in the console?

**Comment by 22mahmoud** [comment]
do you mean with console the front end part? if yes I can take this issue :smiley:
