### ISSUE TITLE
Error while loading schema

### ISSUE THREAD

**Issue by bvpillai** [hasura/graphql-engine#2045]
Showing error while choose a new schema. But it is working with all the other scheme.  Not showing any specific reason or anything as a cause for this error. The error making schema doesnt have any specialty.  It is same as all the other working schema. Only thing is it has some XML data and the schema name ends with '_xml'

Does anybody have any idea about this issue or a solution ?
Am using latest version of Hasura on Docker

**Comment by ecthiender** [comment]
@bvpillai  Can you paste the error here? Also, if you are seeing the error in console, a screenshot would also help.

**Comment by marionschleifer** [comment]
Closing this issue. @bvpillai feel free to re-open if you would like to add more information 🙂
