### ISSUE TITLE
permissions ui improvements

### ISSUE THREAD

**Issue by nukinuki** [hasura/graphql-engine#205]
Hello.
Setting permissions for 8 roles is troublesome. I have lots of tables. Need a way to apply same permissions to multiple roles.
https://monosnap.com/file/ngeIFVbq3SkNsDF0KphmlgBwZPCBz2

**Comment by shahidhk** [comment]
- [ ] apply same permissions for multiple roles
- [ ] delete all permissions for single/multiple roles
- [ ] edit role name after creating

**Comment by shahidhk** [comment]
More feedback from @delynn at https://github.com/hasura/graphql-engine/issues/178#issuecomment-412571620

**Comment by nukinuki** [comment]
Unusable, actually. Current version of api-console doesn't show all the roles by default, so I can't apply same permissions to other roles, because there are no other roles. http://take.ms/jnAIn
