### ISSUE TITLE
What's the goal of 'getIdToken' ?

### ISSUE THREAD

**Issue by realtebo** [hasura/graphql-engine#2052]
In your auth service, you have the 'standard'  getIdToken function, but this is not called from anypoint.

https://github.com/hasura/graphql-engine/blob/8e78e27707deaac76d52193f7ac7549005446b9b/community/sample-apps/vuejs-auth0-graphql/app/src/auth/authService.js#L68 

What was the supposed goal?

**Comment by ecthiender** [comment]
@praveenweb can you take a look at this?

**Comment by praveenweb** [comment]
@realtebo - You can use this function to get the token value and add it to the headers before making requests. In the app, the token is fetched from localStorage and hence this function was not used. [Source code](https://github.com/hasura/graphql-engine/blob/8e78e27707deaac76d52193f7ac7549005446b9b/community/sample-apps/vuejs-auth0-graphql/app/src/vue-apollo.js#L56)

You can replace localStorage code snippet with this wherever you are making authenticated requests to servers. Hope this helps.

**Comment by marionschleifer** [comment]
I'm closing this issue. @realtebo feel free to re-open it if you have anything else to add 🙂
