### ISSUE TITLE
Comments for tables and columns

### ISSUE THREAD

**Issue by nukinuki** [hasura/graphql-engine#206]
Greetings!
Please, add a way to edit comments through ui.
Like this: http://take.ms/oOo1d
And like this: http://take.ms/DhT10
It is possible to add them through SQL query but it's not very friendly

**Comment by praveenweb** [comment]
Hi @nukinuki 

Thanks for the suggestion. 
Broadly listing out the feature set for comments on console.

- [ ] - Add comment during create table / after creating table
- [ ] - Edit comment for table
- [ ] - Add/edit comment for columns

**Comment by praveenweb** [comment]
Fixed in 2e58483af3b96427398b2d8b7dac1446f02e327a
