### ISSUE TITLE
Authentication feature for Hasura

### ISSUE THREAD

**Issue by httpsOmkar** [hasura/graphql-engine#2065]
Currently, Hasura doesn't support the authentication by default.
There is one project by RedHay named as Keycloak.
It is an open source authentication provider it supports the OpenId and OAuth 2.0.
also, it has social login and LDAP support also and has great other features. Support mobile platform too.
So I have connected the Keycloak and Hasura. The connector can found at https://github.com/httpsOmkar/keycloak-hasura-connector.
This is a really good alternative for the Auth0.

The connector has support for Group level authentication and Single user authentication.
Role management is integrated too.

**Comment by mnlbox** [comment]
@httpsOmkar you are a hero and I think you are done a great job about one of the biggest part of Hasura ecosystem.
I think it can be awesome if Hasura support Keycloak as a official and default authentication approach.
We can embed @httpsOmkar solution to Hasura core. It's the most robust and scable solution for Hasura until now.
We can also have another officiall docker image contain embeded keycloak.

**Comment by marionschleifer** [comment]
@httpsOmkar thank you for the Keyclock + Hasura boilerplate 🙏 We added it to our community wiki: https://github.com/hasura/graphql-engine/issues/2619. I'm closing this issue.
