### ISSUE TITLE
Permissions: allow select in subquery only

### ISSUE THREAD

**Issue by nukinuki** [hasura/graphql-engine#207]
I need the data of a table to be available for anonymous but not as a direct query (I don't want it to be able to pull my whole knowledgebase).

Not allowed:
```
query getClients {
  client { ... }
}
```

Allowed:
```
query getProjects {
   projects {
      client { ... }
   }
}
```

**Comment by praveenweb** [comment]
Hi @nukinuki, i understand the use-case. 
@0x777 will explore the feasibility of implementing such a permission feature.

Meanwhile just curious; would you be able to solve your requirement by creating a Postgres VIEW and setting up anonymous permission for that VIEW? Or do you prefer it to be able to set this up via permissions directly?

**Comment by 0x777** [comment]
@nukinuki Are there any permissions on the projects table? If there aren't then it doesn't matter whether clients can be queried directly or not, you can indirectly just fetch all the clients by fetching all the projects.

**Comment by T-Specht** [comment]
I would also find such a feature quite useful.

**Comment by tirumaraiselvan** [comment]
An RFC for hiding top-level fields is published here: https://github.com/0x777/graphql-engine/blob/select-permission-improvements/rfcs/disable-query-and-subscription-root-fields.md

Please feel free to give your comments here: https://github.com/hasura/graphql-engine/pull/4110/files

**Comment by tirumaraiselvan** [comment]
Closing this in favour of #696
