### ISSUE TITLE
AWS Cognito multiple JWT keys 

### ISSUE THREAD

**Issue by ptrobert** [hasura/graphql-engine#2071]
AWS COGNTIO userpools by default supply two public keys, and the idtoken generated by cognito userpools will be  from either of the keys, the user has to ensure which one was used by following a procedure explained in below links and then decode the jwt, 

https://aws.amazon.com/premiumsupport/knowledge-center/decode-verify-cognito-json-token/

https://github.com/awslabs/aws-support-tools/blob/master/Cognito/decode-verify-jwt/decode-verify-jwt.js

Right now hasura doesnt have this capability to handle this situation which will lead to invalid signature situation.

**Comment by ecthiender** [comment]
Does Cognito provide a JWK URL, like how Firebase, Auth0 etc. does? See https://docs.hasura.io/1.0/graphql/manual/auth/jwt.html#jwk-url

**Comment by dsandip** [comment]
@vnovick 👆

**Comment by ptrobert** [comment]
Yes it does, https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json

> Does Cognito provide a JWK URL, like how Firebase, Auth0 etc. does? See https://docs.hasura.io/1.0/graphql/manual/auth/jwt.html#jwk-url

Yes it does https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json

**Comment by ptrobert** [comment]
> Does Cognito provide a JWK URL, like how Firebase, Auth0 etc. does? See https://docs.hasura.io/1.0/graphql/manual/auth/jwt.html#jwk-url

https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json

**Comment by ecthiender** [comment]
@ptrobert apologies for the delay in response. Did your problem get resolved?

If the above URL responds in the standard JWK format then it shouldn't be a problem with Hasura. Having 2 keys also shouldn't be a problem.

Most of the providers have atleast 2 RSA keys in their JWK response (for example, see Firebase: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com), and these work with Hasura.

Said that, it is strange that you are getting a invalid signature error. Can you share the JWT and the contents of `HASURA_GRAPHQL_JWT_SECRET` (hiding sensitive info of course)? You are using the JWK url in the configuration right?

**Comment by marionschleifer** [comment]
@ptrobert I'm closing this now. If you would like to add something to this or have any more questions, please feel free to re-open 🙂
