### ISSUE TITLE
Regex in jsonb

### ISSUE THREAD

**Issue by Rasarts** [hasura/graphql-engine#2080]
How can I use regex for column jsonb fields?

Something looks like: 
```
query getTaskDoneTime($jsonBFilter: jsonb) {
  logs(limit: 100, where: {data: {_contains: $jsonBFilter}}) {
    id
    data
  }
}
```
```

{
  "jsonBFilter": {
    "environment": "production",
    "message":{regex: "/task/i"}
  }
```

In sql I do it like:
`data#>>'{message}' LIKE '%task%'`

**Comment by marionschleifer** [comment]
@Rasarts I added an issue to implement support for regex for column jsonb fields here https://github.com/hasura/graphql-engine/issues/2602. Closing this issue 🙂
