### ISSUE TITLE
docs: guide on handling basic database operations with hasura

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#2092]
1. How to open psql on heroku, digitalocean one-click and other providers
2. How to export/import data
3. How to export/import schema
4. How to do data backups

**Comment by gagandeepp** [comment]
@marionschleifer  assign this to me

**Comment by marionschleifer** [comment]
@gagandeepp done. Let us know if you have questions 🙂

**Comment by tacoelho** [comment]
@marionschleifer assign this to me please.

**Comment by shivamkainth** [comment]
@marionschleifer I will take care of guide on import/export of data.

**Comment by tacoelho** [comment]
> @marionschleifer assign this to me please.

Number 1 is sent.

**Comment by marionschleifer** [comment]
Hi everyone, I created [this PR](https://github.com/hasura/graphql-engine/pull/2984) that provides the structure of the guide. Please branch off this PR and then we'll merge it as one in the end 🙂

**Comment by marionschleifer** [comment]
Closing this issue as outdated since we're focusing on our new Hasura version that makes this issue irrelevant. [Check out the getting started guide for Hasura DDN](https://hasura.io/docs/3.0/local-dev/). 

Feel free to re-open if this still causes an issue.
