### ISSUE TITLE
Add instructions on opening psql on digitalocean one-click droplet

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#2093]
Related to #2092 

We should update this guide: https://docs.hasura.io/1.0/graphql/manual/guides/deployment/digital-ocean-one-click.html#using-digitalocean-managed-postgres-database

with a reference of how to access psql. 

(Via LKMist#3400 on discord)

**Comment by L-K-Mist** [comment]
LKMist... PRESENT!!   :man_student:
