### ISSUE TITLE
ReferenceField permanent loading bar with ra-data-hasura

### ISSUE THREAD

**Issue by comontes** [hasura/graphql-engine#2095]
Hi, So I'm trying ra-data-hasura with React-Admin but I have an issue with ReferenceField. 
This is my code for App.js: 

```JSX
import React from 'react';
import { Admin, Resource } from 'react-admin';
import hasuraDataProvider from 'ra-data-hasura';
import { AttendanceList } from './attendance';

const hasuraUrl = 'https://hasura-preu.herokuapp.com';
const headers = {}

const App = () => (
    <Admin
        dataProvider={hasuraDataProvider(hasuraUrl, headers)}
    >
        <Resource name="attendance" list={AttendanceList} />
    </Admin>
);
export default App;
```

and my code for attendance.js:
```JSX
import React from 'react';
import { List, Datagrid, TextField, ReferenceField, DateField } from 'react-admin';

export const AttendanceList = props => (
    <List {...props}>
        <Datagrid rowClick="edit">
            <TextField source="id" />
            <ReferenceField source="course_id" reference="course"><TextField source="id" /></ReferenceField>
            <ReferenceField source="student_id" reference="student"><TextField source="id" /></ReferenceField>
            <DateField source="date" />
            <ReferenceField label="Attendance Status" source="status_id" reference="attendance_status"><TextField source="id" /></ReferenceField>
        </Datagrid>
    </List>
);
```

From 'network' in Chrome dev tools I see no errors. Still I just get loading bars forever:
<img width="1139" alt="Screen Shot 2019-04-29 at 19 37 42" src="https://user-images.githubusercontent.com/1701089/56933557-6275f300-6ab6-11e9-8c2c-b18be7678e7b.png">

I have Hasura running without admin secret in in https://hasura-preu.herokuapp.com

I have tried making a project from scratch with every package at the latest version, and I've also tried https://github.com/praveenweb/react-admin-hasura-demo and I still get the same loading bars.

you can see my code and run it here: https://glitch.com/edit/#!/noble-sink

What should I be trying next?

**Comment by praveenweb** [comment]
@comontes - Hi, you are missing some piece of code. You need to include all the reference fields under `<Resource>`. 

Update your `App.js` to:

```javascript
const App = () => (
    <Admin
        dataProvider={hasuraDataProvider(hasuraUrl, headers)}
    >
        <Resource name="attendance" list={AttendanceList} />
        <Resource name="course" />
        <Resource name="student" />
        <Resource name="attendance_status" />
    </Admin>
);
```

Note the inclusion of additional resources for the reference fields.

Docs reference for this implementation - https://marmelab.com/react-admin/Fields.html#referencefield

From react-admin docs
`Note: You must add a <Resource> for the reference resource - react-admin needs it to fetch the reference data. You can omit the list prop in this reference if you want to hide it in the sidebar menu.`
