### ISSUE TITLE
Modifying unique column does not work on console

### ISSUE THREAD

**Issue by mnlbox** [hasura/graphql-engine#2096]
Hi guys,
In new version (v1.0.0-alpha44) modify unique for fields not working. See bellow gif:
![unique edit](https://user-images.githubusercontent.com/25859075/56939950-bc130780-6b20-11e9-91d8-b011c2e575da.gif)

**Comment by ecthiender** [comment]
I could reproduce this

**Comment by mnlbox** [comment]
@ecthiender It seems field rename also doesn't work in new version :thinking:

**Comment by mnlbox** [comment]
This console error occurred in when I press save button after rename field:
![Screenshot from 2019-04-30 16-17-43](https://user-images.githubusercontent.com/25859075/56959692-893e3300-6b63-11e9-9b93-7e5ece766175.png)

**Comment by rikinsk** [comment]
@mnlbox I couldn't replicate the field rename bug. can you share more details
