### ISSUE TITLE
Changing a field from nullable to not nullable doesn't update the graphql schema

### ISSUE THREAD

**Issue by anisjonischkeit** [hasura/graphql-engine#2101]
Steps to reproduce:

using the console:
1. create table with nullable bool column
2. update column to be NOT NULL

the docs show `Boolean` instead of `Boolean!`.

Is this by design to stop breaking changes or is it a bug?

**Comment by mnlbox** [comment]
Related issue: #2096

**Comment by wawhal** [comment]
I can replicate this. We're fixing this soon.
@anisjonischkeit as a current workaround, you can reload the metadata from `/metadata/actions` ( the settings icon that you can see on the top right of the console) for rebuilding your GraphQL schema

cc: @rakeshkky

**Comment by wawhal** [comment]
I can replicate this. We're fixing this soon.
@anisjonischkeit as a current workaround, you can reload the metadata from `/metadata/actions` ( the settings icon that you can see on the top right of the console) for rebuilding your GraphQL schema

cc: @rakeshkky

**Comment by anisjonischkeit** [comment]
Wow, that was quick. Thanks everyone!
