### ISSUE TITLE
docs: migration / metadata related use-case guides

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#2103]
- Migrating from Heroku to DigitalOcean (x to y)
- Tracking tables, adding relationships and permissions on another instance
- Track tables, create relationships or permissions without console
- Moving from a UI-driven workflow to version controlled declarative workflow with Hasura
- How to setup GraphQL (or E2E) testing with Hasura on a CI/CD platform
- How to apply changes on dev to prod (dev - staging - prod workflows)
- How to apply changes from a Hasura console to another
- How to combine migrations to a single one
- How to reduce the number of migration files
- How to reset / prune migrations
- I have my app running locally, how do I deploy this to Heroku (or DigitalOcean, or X)
- How to migrate data
- How to use Hasura alongside Django (migrations pov) (#1184)
- How to use Hasura alongside Rails (migrations pov) (#1186)
- How to use Hasura alongside X ORM/Database tool
- How to load sample data when running tests
- How to copy a Hasura setup to another database
- Use migrations to seed data

**Comment by mnlbox** [comment]
@shahidhk If we have a UI for #1967 and another API for restore database then I think many of use case can be done because we can create system on local or heruko free tier and then dump entire database and restore in production environment.

**Comment by petecorreia** [comment]
It would be amazing to have docs on the items on this list (especially workflow related). Any ETA on this?

**Comment by shahidhk** [comment]
@petecorreia I recently did a stream on migration workflows: https://www.youtube.com/watch?v=4Gktdliyc2E

In the stream, I setup a git repo with a branch per env and use circle ci to apply the migrations.

We're starting to write up some of the as byte-sized blogs etc. starting with https://blog.hasura.io/resetting-hasura-migrations/

We'll get to the other ones over this month.

**Comment by petecorreia** [comment]
@shahidhk this helped me a lot! Thank you 🙏 

I'm super happy with the gitops workflow I've set up with Heroku. Might write up about it when I get some time.

**Comment by marionschleifer** [comment]
Closing this issue as outdated since we're focusing on our new Hasura version now. [Check out the getting started guide for Hasura DDN](https://hasura.io/docs/3.0/local-dev/). [It includes a comprehensive section on CI/CD](https://hasura.io/docs/3.0/ci-cd/overview/).

Feel free to re-open if this still causes an issue.
