### ISSUE TITLE
"hasura init" failing on Windows 10

### ISSUE THREAD

**Issue by tomsutton1984** [hasura/graphql-engine#2107]
I cannot run hasura init using the cli on Windows, or Ubuntu (WSL). Both fail with what I suspect may be a permissions issue when attempting to create the folders/files.

```bash
hasura init
v Name of project directory : hasura
?[31mFATA?[0m[0001] error creating setup directories: mkdir hasura: The system cannot find the file specified.
```

**Comment by tomsutton1984** [comment]
Probably a duplicate of #1558

**Comment by shahidhk** [comment]
@tomsutton1984 We have tried executing the CLI on both WSL and Windows CMD and both works fine. Can you give exact instructions to reproduce the error? Any info on your environment will also help.

**Comment by marionschleifer** [comment]
@tomsutton1984 any update on this? 🙂

**Comment by tomsutton1984** [comment]
No longer an issue
