### ISSUE TITLE
show warning for identifiers which do not conform to GraphQL name scheme

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#212]
Show warnings for table, column and relationship names which are not conform to GraphQL naming scheme. For details refer [here](http://facebook.github.io/graphql/June2018/#sec-Names).

**Comment by shahidhk** [comment]
@praveenweb This is quite urgent. Can we fetch names from information schema and show the ones that doesn't comp;y with GraphQL spec as greyed out or sth?

**Comment by dsandip** [comment]
@arvi3411301 As we discussed some time back, the UI for this is to color the non-conforming identifiers in a different color (#FFC200) and add our usual "i" icon next to it with a tool tip:

This identifier name does not conform to the GraphQL naming standard. 
Names in GraphQL should be limited to this ASCII subset:  `/[_A-Za-z][_0-9A-Za-z]*/`. [Reference](https://facebook.github.io/graphql/June2018/#sec-Names).
