### ISSUE TITLE
Add "Edit on Github" button to all pages on docs

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#2122]
Add a Edit on Github button page on all docs pages that automatically links to the right rst file so that making docs contributions are easy.

**Comment by rikinsk** [comment]
Its already there 
![Screenshot from 2019-05-06 13-41-06](https://user-images.githubusercontent.com/153602/57213498-a449f080-7004-11e9-9082-12bd621b1dd1.png)

**Comment by angad777** [comment]
@coco98 - Are you referring to https://learn.hasura.io/ docs? Let me know, Happy to help.
