### ISSUE TITLE
Ability to configure Hasura server's subscription debounce delay

### ISSUE THREAD

**Issue by eliezedeck** [hasura/graphql-engine#2125]
Hi, I have once stated this in the discord chat and one of the team said it will be in the next release. That was in release `alpha41`.

At this point, I don't think we have the ability to configure the amount of time Hasure will delay subscription responses (debouncing). I find the delay very very long for my use cases.

Think multiplayer games and the likes of true realtime apps. The reactivity is pretty laggy with the current configuration. I think many will find this configuration very useful too, not just me. Hopefully, this will finally get into the next release.

Thanks.

**Comment by coco98** [comment]
@eliezedeck It's already released. Updating the docs and sending across a link :)

**Comment by 0x777** [comment]
https://deploy-preview-2126--hasura-docs.netlify.com/graphql/manual/deployment/graphql-engine-flags/reference.html. Search for `LIVE_QUERIES`.

**Comment by eliezedeck** [comment]
Wonderful guys! Thanks.
