### ISSUE TITLE
Integrate GraphQL Voyager into GraphiQL Online

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [hasura/graphql-engine#2128]
Please integrate [GraphQL Voayger](https://github.com/APIs-guru/graphql-voyager) into [GraphiQL Online](https://graphiql-online.com).

**Comment by mnlbox** [comment]
Related PR: #799

**Comment by rikinsk** [comment]
Related issue #314

**Comment by dsandip** [comment]
closing this in favour of #314.
