### ISSUE TITLE
Add ability to hide the endpoint and headers sections in GraphiQL Online

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [hasura/graphql-engine#2129]
What about to add "Endpoint" and "Headers" button to hide/show the endpoint and headers sections in GraphiQL Explorer?

(They take up too much screen space.)

Before:

![before](https://user-images.githubusercontent.com/7892779/57243555-1a6b4900-703f-11e9-9ef9-71af3f015661.png)

After:

![after1](https://user-images.githubusercontent.com/7892779/57243562-21925700-703f-11e9-976f-110ef430b81f.png)

![after2](https://user-images.githubusercontent.com/7892779/57243567-2525de00-703f-11e9-8cd2-7233f1bebc1f.png)

**Comment by shahidhk** [comment]
Closed in https://github.com/hasura/graphql-engine/commit/1418b43c525eafe83218d42916f22ecfface8e78
