### ISSUE TITLE
Authentication header contains   chinese but it throw exceptions 

### ISSUE THREAD

**Issue by rongfengliang** [hasura/graphql-engine#213]
see the pictures
<img width="1018" alt="wx20180726-104553 2x" src="https://user-images.githubusercontent.com/2312287/43238514-1a4978ce-90c1-11e8-9cf8-d52206d582e5.png">
<img width="1162" alt="wx20180726-104322 2x" src="https://user-images.githubusercontent.com/2312287/43238515-1a750fb6-90c1-11e8-9731-f0ad8dced953.png">

**Comment by shahidhk** [comment]
Looks like a unicode parsing issue. @praveenweb @wawhal ?

**Comment by shahidhk** [comment]
@praveenweb @wawhal Is this issue resolved?

**Comment by aswinmprabhu** [comment]
I think it's a fetch API issue. I tried to run a similar query in the chrome dev console
```
fetch("http://localhost:8080/v1alpha1/graphql", { 
    method: "POST", 
    headers: { "Content-Type": "application/json", "X-hasura-app-name": "提" }, 
    body: JSON.stringify({"query":"query {\n  author{\n    id\n}\n}","variables":null})
});
```
This gives me the same error that's being shown in the hasura console.
```
Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Value is not a valid ByteString.
    at <anonymous>:1:1
```
The first answer to [this](https://stackoverflow.com/questions/46137990/send-emoji-in-http-header-ionic2) stackoverflow question says that only ASCII is supported for headers by most http clients. I guess fetch doesn't support non-ASCII chars and curl does.

**Comment by dsandip** [comment]
Hey everyone, thank you for reporting this. Closing this in favor #1587 (please see for details)
