### ISSUE TITLE
Hasura docker without network connection

### ISSUE THREAD

**Issue by Zoharos** [hasura/graphql-engine#2130]
Hi guys,
how can i create a docker image of hasura that doesn't make request for the vendor.js, main.js and main.css etc. ?

**Comment by maxcan** [comment]
there's a `--static-files` command line option for the CLI.  the best way that I've found to download them is to go to localhost:9695 when you have network connectivity and go File -> Save in chrome or firefox and save a complete web archive. this will save all the assets then you can point to that file when you `hasura console --static-files <path to the web archive>`

**Comment by mnlbox** [comment]
Related: #521

**Comment by Zoharos** [comment]
I tried using the cli in the cli-migration docker, but got this error:
`preparing execution context failed: setting up global confog failed: cannot create global config directory: mkdir/.hasura: permission denied`

**Comment by shahidhk** [comment]
@Zoharos Looks like a permission issue. We're bundling assets into the docker image for the next release. Should work fine with that.
