### ISSUE TITLE
docker run fails with: "cannot continue due to inconsistent metadata"

### ISSUE THREAD

**Issue by mwMichaelSchnabel** [hasura/graphql-engine#2132]
Hi, when I run "docker run" I get the following error:
`graphql-engine_1  | {"timestamp":"2019-05-06T22:56:11.003+0000","level":"info","type":"startup","detail":{"kind":"serve_options","info":{"auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enable_telemetry":true,"enable_console":true,"auth_hook":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"admin_secret_set":false,"port":8080}}}
graphql-engine_1  | {"internal":[{"definition":{"definition":{"url":"https://hasura-sample-remote-schema.glitch.me/","headers":[],"url_from_env":null,"forward_client_headers":true},"name":"RemoteSchema","comment":null},"reason":"HTTP exception occurred while sending the request to https://hasura-sample-remote-schema.glitch.me/","type":"remote_schema"}],"path":"$","error":"cannot continue due to inconsistent metadata","code":"unexpected"}
lieferscheine_graphql-engine_1 exited with code 1
`

Connecting with pgAdmin4 works like a charm.

The docker run command is:
`docker run -d -p 8085:8080 -e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:@XXXmyipXXX:5432/DBname -e HASURA_GRAPHQL_ENABLE_CONSOLE=true hasura/graphql-engine:v1.0.0-alpha45`

Any help appreciated :)

Info: I am running Postgres v10.3 and I copied the database from another computer where hasura works - is it possible that some matadata was added there by running Hasura that I have to delete to make it run?

**Comment by 0x777** [comment]
@mwMichaelSchnabel Looks like your remote schema is down. The error from the logs is `HTTP exception occurred while sending the request to https://hasura-sample-remote-schema.glitch.me/`

**Comment by mwMichaelSchnabel** [comment]
Thank you very much for the answer. I think you are right. I figured the remote schema is not reachable due to a proxy misconfiguration which I cannot solve right now.
Can I just delete the remote schema information in the postgres database to make the hasura container start again or is that a very bad idea?

**Comment by 0x777** [comment]
@mwMichaelSchnabel You can delete it from the database. It'll be present in `hdb_catalog.remote_schemas`. 

P.S graphql-engine starts when there are errors except in one case, which is when it is upgrading from an older version. Looks like that's the case here.

**Comment by mwMichaelSchnabel** [comment]
Thank you very much. Deleting the remote_schema manually worked. I was able to start the hasura container again and recreate the schema.
I consider this as solved.
