### ISSUE TITLE
Add ability to have multiple schemas, based on roles, for Remote Schemas

### ISSUE THREAD

**Issue by leoalves** [hasura/graphql-engine#2139]
Hasura creates different schemas based on each role.

A nice to have feature, would be to allow Remote Schemas to also have a role based schema.

This has the benefit to block requests directly in the Hasura side, without reaching the remote server.

And also making it easier for developers and 3rd parties to only see the schema they have access to.

**Comment by marionschleifer** [comment]
Closing in favor of #2461.
