### ISSUE TITLE
Allow Date/Time Functions timestamptz types

### ISSUE THREAD

**Issue by leoalves** [hasura/graphql-engine#2140]
Currently we can use "now()" in timestamptz columns, from GraphQL. 

But when trying to use other functions like interval returns an error.

```javascript
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "data-exception"
      },
      "message": "invalid input syntax for type timestamp with time zone: \"now() - interval '1 day\""
    }
  ]
}
```

I think it would be very useful to allow PostgreSQL date/time functions in the GraphQL timestampz data type.
https://www.postgresql.org/docs/9.1/functions-datetime.html

**Comment by 0x777** [comment]
`now()` just happens to be a special literal accepted by postgres for time/date values. We just send the literal as a parameter to postgres so unless postgres supports such literals we can't do much at the graphql-engine layer.

**Comment by leoalves** [comment]
@0x777 That makes sense.
Will close it.
thanks

**Comment by mitar** [comment]
Could the fact that `now()` is accepted be documented somewhere?

**Comment by aman-atomicwork** [comment]
were you able to figure it out yet
