### ISSUE TITLE
Azure deploy template missing the ability to set up an access key

### ISSUE THREAD

**Issue by sheldonj** [hasura/graphql-engine#2153]
The azure one click template that is used in all the examples works great (for the most part). But it's missing clear direction on how we should go about setting up an ACCESSKEY for an Azure deployment. 

Am I missing something in the docs or is this a gap with an azure deployment.

It seems like this would be a big issue for deploying to azure as everyone would have access to the hasura console? Im pretty new to hasura and containers on azure but am I missing something?

**Comment by rikinsk** [comment]
related: #1710

**Comment by dsandip** [comment]
@sheldonj closing this in favor of #1710 (*also tagging you there so you can follow the issue*).
