### ISSUE TITLE
"Forward all headers from client" breaking requests on remote schema when content-type header is sent

### ISSUE THREAD

**Issue by karibertils** [hasura/graphql-engine#2159]
When i enable "Forward all headers from client" the remote endpoint receives 2 content-type headers with different casing. One is from the client and another one from Hasura.

"Content-Type: application/json"
"content-type: application/json"

I am using absinthe (an elixir graphql library) for remote. And the double content-type causes the server to respond with syntax error. When not forwarding the headers, the remote schema works fine.

Maybe those headers should be merged, or add a way to ignore specific client headers would be one way to deal with this ?

**Comment by coco98** [comment]
This might have been the same issue as https://github.com/hasura/graphql-engine/pull/2118. 

Could you try the docker image version tagged on the PR and test?

**Comment by karibertils** [comment]
Problem confirmed to remain on hasura/graphql-engine:pull2118-25a118ed

**Comment by karibertils** [comment]
Tested & working on hasura/graphql-engine:pull2170-f17debe0
