### ISSUE TITLE
custom SQL functions do not get saved to metadata.json if you're running uBlock Origin

### ISSUE THREAD

**Issue by Dacturne** [hasura/graphql-engine#2163]
[Using Custom SQL functions for queries with Postgres and GraphQL](https://blog.hasura.io/using-custom-sql-functions-for-queries-with-postgres-and-graphql-ddca6caf6681/)

Took me a while to figure it out, so I thought I'd share.
It seems that custom SQL functions do not get saved to `metadata.json` if you're running `uBlock Origin` on `Chrome` (74.0.3729.131).
I've created a sample `article` table and added the corresponding function with
- [x] Track this

to a fresh docker container.
```
CREATE FUNCTION search_articles(search text)
...
```
Metadata upon export:
```
{
  "functions": [],
  ...
}
```
Adding it manually fixes the issue, same as disabling `uBlock Origin`
```
"functions": [
  "search_articles"
],
```

**Comment by rikinsk** [comment]
Reopening this to track the `uBlock Origin` issue

**Comment by karthikvt26** [comment]
@Dacturne I tried to replicate this. Please let me know if I am doing anything different from what you did. 

I created a table called `article` with `id`, `title` and `content` as columns and created the following function with `track this` checked

```
CREATE FUNCTION search_articles(search text)
RETURNS SETOF article AS $$
    SELECT *
    FROM article
    WHERE
      title ilike ('%' || search || '%')
      OR content ilike ('%' || search || '%')
$$ LANGUAGE sql STABLE;
```

When I look at the exported JSON. Here is what I see

![screenshot 901](https://user-images.githubusercontent.com/25095884/57676823-0e851580-7643-11e9-989a-e83945411359.jpg)

PS: I have installed uBlock from (https://github.com/gorhill/uBlock). Let me know if this is the one I should test with.

**Comment by Dacturne** [comment]
@karthikvt26 yes, that's exactly what I did before. I've tried replicating it again right now and it comes out without the issue. I've also reinstalled uBlock and spawned a fresh container instance since yesterday - perhaps this solved it. Nothing else really changed...

**Comment by karthikvt26** [comment]
Thanks @Dacturne. I am closing this issue for now. Feel free to reopen if you are able to replicate this issue again!
