### ISSUE TITLE
table column modify not working if column comment is present

### ISSUE THREAD

**Issue by mnlbox** [hasura/graphql-engine#2164]
Hi guys,
In new version sometimes column modify not working.
I think maybe it's related to this: #2096
For example I give this error when I want rename one field: (other finctionality like set `Unique` and `Default` also not working for me)
```
TypeError: v.trim is not a function[Learn More] main.js:1:250282
```

**/CC:** @wawhal, @praveenweb, @shahidhk

**Comment by shahidhk** [comment]
@mnlbox Please give reproductions instructions as we're unable to trigger this.

**Comment by mnlbox** [comment]
I show this issue on share screen to @wawhal If needs I can show you too.

**Comment by rikinsk** [comment]
I suspect there might be an older version of console somehow being served. Might be some cache in between.

**Comment by mnlbox** [comment]
I also try clear cache in browser. Also I try with Firefox and Chromium and it\s happens in both.

**Comment by mnlbox** [comment]
@rikinsk Maybe related to this: #521
Is it possbile that CDN serve legacy version of `main.js` and `vendor.js` for me?

**Comment by rikinsk** [comment]
Could reproduce this by adding a column comment in arabic and trying to modify column after save

**Comment by rikinsk** [comment]
Nothing to do with arabic :). happens if you have any comment added
