### ISSUE TITLE
how to insert or set "null" values in mutations

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#217]
Via moe#8021 on discord.

> So, would be nice if somewhere in the docs there was a mention regarding saving null values to the database (to the default null field) - you should pass undefined, not actual null.

**Comment by 0x777** [comment]
Currently, the server doesn't expose a way to insert SQL `NULL`s. If the default value of a column happens to be `NULL` (which is the case unless it is explicitly set) then `NULL` can be inserted by not providing a value to the column in the input. We'll have to clean this up. 

```json
{
  "title": "article title",
  "content": null
}
```
```json
{
  "title": "article title"
}
```

Currently both these json values for the input type for inserting into `article` table behave the same way. i.e, the field `content` is ignored if it is explicitly set to `null`.

**Comment by shahidhk** [comment]
moved to https://github.com/hasura/graphql-engine-docs/issues/58

**Comment by rikinsk** [comment]
I am getting a type error when I pass value as `null` to a nullable field while using insert and update mutations.

**Comment by MarcelloTheArcane** [comment]
Why is this closed? I need to update an existing value to `null`, but it doesn't work.

**Comment by rikinsk** [comment]
@MarcelloTheArcane Passing a `null` value in the insert and update mutations sets a value to `null in the database. Can you share some more information if you are not observing the same

**Comment by yashbpolynomial** [comment]
@rikinsk I m passing null to mutation query still null is not getting set in sql table

**Comment by AbdallahAbis** [comment]
Any Updates On This!
```invalid input syntax for type timestamp with time zone: NULL```

**Comment by idesignpixels** [comment]
Also having the above problem when using soft delete following this article, I can't undo a delete https://hasura.io/docs/latest/schema/common-patterns/data-modeling/soft-deletes/

**Comment by idesignpixels** [comment]
I found the solution to our problem after a wild goose chase there was a trigger on `deleted_at` : `UPDATE ON meetings FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_deleted_at()`

I think this could be down to selecting "Frequently used columns > updated_at" as a starting point for the `deleted_at` field and unknowingly adding a trigger further down.
After removing the trigger it fixed out problem and now the timestamp field is nullable.
