### ISSUE TITLE
Function permission details navigation breaks between schemas

### ISSUE THREAD

**Issue by Dacturne** [hasura/graphql-engine#2174]
Navigation seems to break when acessing `{function} > permissions > here` details of a table in a different schema. Refreshing the page makes it work just fine.
I'm using docker `image: hasura/graphql-engine:v1.0.0-alpha45`
Demo:
![hasura_permission_details](https://user-images.githubusercontent.com/32225868/57630012-21dda580-759d-11e9-9525-4365df5aced3.gif)

**Comment by arvi3411301** [comment]
Tracking with PR #2016
