### ISSUE TITLE
[Feature Request] add more view mode for GraphiQL query result in console (DataGrid, Tree, ...)

### ISSUE THREAD

**Issue by mnlbox** [hasura/graphql-engine#2179]
Hi,
I think `table view` also useful for GraphiQL query result page.
For example we can have some view mode:
* JSON (default mode that we have now)
* **Data Grid mode (this issue suggestion)**
* **Tree mode (this issue suggestion)**
* add more view mode later here...

**Comment by mnlbox** [comment]
@marionschleifer @rikinsk-zz Any update/plan on this feature?

**Comment by manasag** [comment]
Hasura depends on the GraphiQL library for the API explorer page, which do not support such requirement. We are closing this issue and would recommend opening an issue with GraphiQL for a better support. Thanks.
