### ISSUE TITLE
How subscription works?

### ISSUE THREAD

**Issue by yuvalgut** [hasura/graphql-engine#2189]
Regarding subscriptions the docs say that Hasura will wait for update from the db when related data to the subscription changes.
When I look at the pgadmin dashboard I see that when there is a live subscription - the graph looks like that:
![image](https://user-images.githubusercontent.com/11994190/57705644-f0cca600-766c-11e9-9494-c565b6026a18.png)

I see that the queries always get "hit" from cache so its not that expensive but I still try to figure out why the query is executed every second.

**Comment by coco98** [comment]
@yuvalgut We're almost done with a doc on how live-queries work, including benchmarks, horizontal scalability tests etc. Will cover this there!

Related #2190
