### ISSUE TITLE
Improve hasura version CLI command output

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#219]
Currently output looks like:
hasura GraphQL Engine CLI version: v1.0.0-alpha10
hasura CLI version: v0.3.11

It shows only the CLI version which is confusing with the GraphQL engine version that is running.
Need to have the actual GraphQL engine version that is running or instructions to find it.

**Comment by shahidhk** [comment]
@rikinsk The `version` command on graphql-engine cli output cli and server versions. We need to update the `version` command for hasuractl for the same. Moved to https://github.com/hasura/hasuractl/issues/842
