### ISSUE TITLE
docs: guide docs on subscriptions and live-queries

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#2190]
Document should cover:
1. Benchmarks
2. Scalability
3. How it works
4. What are the tradeoffs
5. Tuning performance

**Comment by robertjdominguez** [comment]
Closing this as we now have pages in docs for [subscriptions](https://hasura.io/docs/latest/subscriptions/index/) and [live-queries](https://hasura.io/docs/latest/subscriptions/postgres/livequery/index/) 👍
