### ISSUE TITLE
How to make custom query without Postgres knowledge?

### ISSUE THREAD

**Issue by dalisoft** [hasura/graphql-engine#2191]
Hi and thanks for amazing tool. With JWT + CORS + Hasura = Amazing combo (for me at least).
I loved and i already learned the basics with local Docker container. Now i need some feature

1. Making custom functions without Postgres knowledge (or builder for Postgres functions)
2. Making alias functions at server level (with some changes)
3. Managing permission for custom alias and functions like default schemas (returning, arguments permission)
4. Add `encryption` for row values / table items

Is that's possible? These features would be great.

_I know, i should ask this on StackOverflow, but sorry, please, i hope i get more and fast help from authors/community_

**Who also wants this features, please add ❤️ emoji to this post instead of adding comment like** _+1_ **or something else**

**Comment by dalisoft** [comment]
@shahidhk any news? can i wait there features soon? thanks

**Comment by shahidhk** [comment]
@dalisoft I have added the `ideas` label for this issue. Let's wait for others to pitch in :smile:

**Comment by dalisoft** [comment]
Okay, thank you 😉

**Comment by marionschleifer** [comment]
Closing this issue as outdated since we're focusing on our new Hasura version now. Check out the getting started guide for Hasura DDN. 

Feel free to re-open if this still causes an issue.
