### ISSUE TITLE
[Feature request] Clone row data in Console

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#2193]
In Console, it could be convenient to have a `clone` button for all rows in a table.
When cloning, all data will appear in the `insert` tab, so that user could modify changed fields before inserting into database.

**Comment by wawhal** [comment]
@revskill10 there is already a clone button for every row in the table.
Please could you give more details about what you mean by this feature request?

**Comment by mnlbox** [comment]
@wawhal I don't see that later. Thanks brow :wink:

**Comment by revskill10** [comment]
@wawhal Ah, my bad. It's exactly what i want !
