### ISSUE TITLE
Feature request: Multi-column unique constraint 

### ISSUE THREAD

**Issue by sebastianmacias** [hasura/graphql-engine#2200]
Currently Hasura allows having multiple single field unique constraints like this:
![Multiple unique constraints ](https://i.imgur.com/cZxDTEZ.png)

However there is not an option to define multi-column unique constraints. 

for instance:

```
ALTER TABLE someTable
ADD UNIQUE (col1, col2)
```  

Are there any plans to support this?

**Comment by dimitar-nikovski** [comment]
#506 #2148 

Delivered in https://github.com/hasura/graphql-engine/releases/tag/v1.0.0-beta.01 about 10 min before this issue was opened

😄

**Comment by sebastianmacias** [comment]
Amazing, what a coincidence! v1.0.0-beta.01 is looking good.

**Comment by rmonteroarkus** [comment]
Any clue on why the page is not longer available?

**Comment by rikinsk** [comment]
@rmonteroarkus Multi column unique constraints can be created from the Create table and Modify table pages. Are you looking for something else?

**Comment by rikinsk** [comment]
just realised the linked release page is broken. Updated the link now

**Comment by FracaShaw** [comment]
Hey, can't find how to add column unique constrains on the UI ?
![Screen Shot 2024-09-23 at 14 59 27](https://github.com/user-attachments/assets/b4e04a94-9910-4b48-9671-7ec4b02d9ad2)

**Comment by callmekatootie** [comment]
Interested in knowing this too - as of now, I was able to create a composite unique key only through the primary key where I could select multiple columns
