### ISSUE TITLE
blank image on remote schemas section

### ISSUE THREAD

**Issue by jasonmccallister** [hasura/graphql-engine#2209]
When selecting remote schemas, the image is broken and is looking for undefined in the URL.

Not a major issue, but wanted to document. Great work on tagging beta!!

<img width="1920" alt="Screen Shot 2019-05-16 at 9 08 37 PM" src="https://user-images.githubusercontent.com/5354908/57896471-ee11b280-781e-11e9-8a1b-fefdaab1836c.png">

**Comment by shahidhk** [comment]
@jasonmccallister Is the console being served by CLI or Server?

**Comment by jasonmccallister** [comment]
@shahidhk its from `hasura console`

**Comment by shahidhk** [comment]
Thanks @jasonmccallister! I think it is an issue with the console template on cli. Will push a fix soon.

**Comment by shahidhk** [comment]
closed in https://github.com/hasura/graphql-engine/commit/f8ffbda11897983adffd5a5d00f077da92f618ba
