### ISSUE TITLE
Ability to change assets like main.css.gz

### ISSUE THREAD

**Issue by Zoharos** [hasura/graphql-engine#2213]
Hi guys,
I tried changing the main.css.gz that used by the console and copy it to /srv/console-assets/versioned with the help of a dockerfile. then tried using HASURA_GRAPHQL_CONSOLE_ASSETS_DIR ENV var but it won't load the main.css.gz file.
Thanks.

**Comment by shahidhk** [comment]
@Zoharos What are you trying to achieve? If you trying get the console to load assets from server instead of the CDN, just set the env var `HASURA_GRAPHQL_CONSOLE_ASSETS_DIR=/srv/console-assets`. You don't need to copy any files.

**Comment by Zoharos** [comment]
@shahidhk for example the main.css calls https://fonts.googleapis.com/css?family=Gudea:400,700 to get some css, which I don't want it to.

**Comment by shahidhk** [comment]
You can just ignore it - font would fail to load. We will soon move the Google Fonts also into the assets.

But in any case, if you are over-riding `/srv/console-assets`, make sure you keep the file structure as it is and keep them gzipped.

Let me know how it goes and what the error is if it fails.

**Comment by Zoharos** [comment]
this is the error I get:
The webpage at https://hasura-console-hasura.1d35.starter-us-east-1.openshiftapps.com/console/assets/versioned/main.css.gz might be temporarily down or it may have moved permanently to a new web address.
But as in the picture:
![Screenshot from 2019-05-17 17-34-23](https://user-images.githubusercontent.com/19515774/57935294-24f0d280-78ca-11e9-971a-23b8229c7960.png)
it is there.

**Comment by shahidhk** [comment]
It is a content encoding error, the server sets `content-encoding: gzip` if it sees a `.gz` extension. You just need to gzip the `main.css.gz` file and then put it inside the docker image.

Execute `gzip -f main.css.gz && mv main.css.gz.gz main.css.gz` in the terminal

**Comment by Zoharos** [comment]
THANK YOU!! it's worked
