### ISSUE TITLE
[Feature Request] Add possability to query own permissions for users

### ISSUE THREAD

**Issue by mahald** [hasura/graphql-engine#2214]
Hi Guys,

I need the possibility to know what permissions the own role (used for the query) has.

Because I don't want to display the 'delete button' in the Web-Frontend, if the user has no delete permission or no 'add button' if there is no permission for add. 

This must be query able by each role for the own (currently active role) role and not only by the admin.

This seems not to be possible currently.

The easiest way to do this would be to have a filed '_permissions' (or what every u want to call it) in any query.

For example, I have an alarm query, to get it I could add it to the query like so:

```
{
  alarms {
    id
    _permissions
  }
}
```

the reply for _permissions would then be some kind of: 
`{"insert":"true", "select":"true", "update":"true", "delete":"true"}`

Is this currently possible somehow ?
If not, could this be implemented as a Feature Request ?

**Comment by leoalves** [comment]
@mahald 

You can do that with the introspection query.  

The Hasura GraphQL schema is generated based on role making the request.  In that case you can make an introspection query, loop through the schema and check what queries/mutations the user/role have access to it.  

You could even write an utility where you pass the table name and can it checks for permissions in the schema, following the Hasura naming conventions.

For ex:

```javascript
getPermissions('alarms')
```
Would check the schema and return true/false for each operation
```
{
insert: schema_has_in_the__mutation_root_insert_alarms,
delete: schema_has_in_the__mutation_root_delete_alarms,
update: schema_has_in_the__mutation_root_update_alarms,
select:  schema_has_in_the__query_root_alarms
}
```

You could even go deeper into the schema and check the fields the role has access to it.

**Comment by mahald** [comment]
@leoalves thx for the reply, that should do the trick thank you!
