### ISSUE TITLE
Issues after removing environment variables and event triggers

### ISSUE THREAD

**Issue by jasonmccallister** [hasura/graphql-engine#2216]
This kind of makes sense, but I felt it should be noted.

We added event triggers for auditing tables, but decided not to use them (really we are changing the webhook to a Laravel API), but quickly ran into an issue. Removing the environment variable will cause an issue for anyone new to the project when they run migrations, since the environment variables are no longer defined.

Our fix was to add the environment variables back to the config but made me think if there is a better way to handle this?

**Comment by tirumaraiselvan** [comment]
Thanks for reporting. So the repro is:

1. Create event-trigger with ENV variable(s).
2. Drop event-trigger
3. Run migrations on a fresh instance.
4. Failure?

**Comment by jasonmccallister** [comment]
That is correct, except between step 2 and 3 remove the environment variables for the trigger.

It’s almost as if the migrations need to look into the future migrations and determine if it gets dropped.

**Comment by tirumaraiselvan** [comment]
The problem can only be solved if we change the migrations architecture significantly. Currently, the migrations system is incremental. It applies each migrations one-by-one and expects to get from one consistent state to next. 

The solution is perhaps to:

1. Write one sql per migration
2. Export the complete metadata after the migration

Then the migration system can apply the SQL incrementally and at the end apply the metadata completely.

@0x777 @shahidhk Thoughts. @0x777 had concerns about backwards compatibility.

**Comment by jasonmccallister** [comment]
Good point, that is the traditional migration flow. Maybe removing the triggers and squashing commits? This might not need to be solved with tech, but maybe documentation?

**Comment by jasonmccallister** [comment]
Just following up here, we resolved this by resetting migrations as per this guide https://blog.hasura.io/resetting-hasura-migrations/

Only key step was to remove all event triggers before pulling the migrations from the server.

**Comment by flybayer** [comment]
This has been causing me a bunch of pain.

I'm early in development of an app, so I'm often changing event triggers, environment variables, etc. as I figure out the best way to build my app. 

I have to be super careful to leave old environment variables in my build config until I have a successful deploy, then I can remove the old env variable.

The problem is I keep forgetting to do that, resulting in failed deploys.

**Comment by tirumaraiselvan** [comment]
Using config-v2 of metadata will resolve this issue as it depends on applying the full current state of the system: https://hasura.io/docs/1.0/graphql/core/migrations/upgrade-v2.html
