### ISSUE TITLE
Create indexes using the Console

### ISSUE THREAD

**Issue by eliezedeck** [hasura/graphql-engine#2219]
Hi,

I know you can do that on PostgreSQL, but manually. It would be handy to be able to rely on the Console to do that instead, and also get the `up` and `down` migration files along the way.

As far as I know, at this time, you'll have to craft your own SQL query. That is not only time consuming, but **very error-prone**. Being able to create indexes, even basic ones, right from the Console would help much.

Thanks.

**Comment by sn-kaier** [comment]
Places where I'd absolutely love to see such a feature in the console would be:

- At add/modify table eg. below "Unique Keys"
- at Data > Schemas near "Untracked foreign-key relations" as suggestions for foreign keys on one-to-many relations
- at "Query Analysis" for easy query performance improvement (might be more complex, but verry nice to have for people with less experience with PostgreSQL).

Additionally it would be handy to see existing indexes in the modify-table section.

**Comment by maxcan** [comment]
yes please.  definitely prefer this to manually creating indices.

**Comment by AdityaAnand1** [comment]
Any updates on this? Can't believe this hasn't been implemented :(

I just found out that you are forced to do everything via console for migrations and I had to give up my beloved DataGrip, which was a massive productivity hit. And now I find out the console isn't even built completely! Kind of rethinking hasura entirely tbh.

**Comment by AdityaAnand1** [comment]
Any updates on this? It's been almost 2 years now :( 

Ideally, we should be able to create and manage indices within the console and it should be handled as part of hasura config/metadata itself, not as manual Raw SQL migrations.

**Comment by kolharsam** [comment]
3f35a9a adds support for the creation and deletion of indexes via the console for Postgres data sources. You can expect it to be out in one of the upcoming releases.
Please let us know if you've got any feedback regarding the same. We'd love to hear from you!
The same support will land for other data sources supported by Hasura in future releases soon!

**Comment by eliezedeck** [comment]
That took a long time to land, but still excited it's finally here. Looking forward for the release.
