### ISSUE TITLE
node engines  must 8.9.1 for build  console ?

### ISSUE THREAD

**Issue by rongfengliang** [hasura/graphql-engine#222]
this is  my local install deps
```code
info No lockfile found.[1/5] 🔍  Validating package.json...
error hasura-console@0.1.0: The engine "node" is incompatible with this module. Expected version "8.9.1".error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by praveenweb** [comment]
Hi @rongfengliang , to run console locally, we require the node version to be >= v8.9.1.

Node v8.9.1 is an LTS version and hence recommended. If you are on a lower version of node, please upgrade at least to v8.9.1 to build/test console. 

You can use [nvm](https://github.com/creationix/nvm) to maintain multiple node versions on your machine.

**Comment by shahidhk** [comment]
@praveenweb What is the action here? Update contributing guide?

**Comment by praveenweb** [comment]
@shahidhk - [Contributing guide](https://github.com/hasura/graphql-engine/blob/master/console/CONTRIBUTING.md) already mentions pre-requisite as Node v8.9+

**Comment by shahidhk** [comment]
Okay.

@rongfengliang Hope the requirements are clear. Please re-open in case you have other questions.

**Comment by shahidhk** [comment]
@praveenweb Do we plan to support yarn?

**Comment by rongfengliang** [comment]
@shahidhk  @praveenweb  i suggest  maybe change the  package.json  

```code
 "engines": {
    "node": "8.9.1"
  }
```
to 
```code
 "engines": {
    "node": "^8.9.1"
  }
```

**Comment by praveenweb** [comment]
@rongfengliang @shahidhk - The change to package.json would be 

```code
 "engines": {
    "node": ">=8.9.1"
  }
```
Fixing it in #220
