### ISSUE TITLE
Add --docker flag to CLI for init

### ISSUE THREAD

**Issue by jasonmccallister** [hasura/graphql-engine#2224]
When scaffolding new projects, it would be really helpful to include the Docker files as part of the init. I think something like this:

`hasura init --docker`

Which in the CLI will just run the command from the [Quickstart with Docker](https://docs.hasura.io/1.0/graphql/manual/getting-started/docker-simple.html#step-1-get-the-docker-compose-file).

`wget https://raw.githubusercontent.com/hasura/graphql-engine/master/install-manifests/docker-compose/docker-compose.yaml`

Is there any interest in adding this to the CLI?

**Comment by shahidhk** [comment]
A modified version of this has been added to `1.2.0-beta.1` release.
