### ISSUE TITLE
Postgres 9.4: syntax error at or near \"SKIP\"

### ISSUE THREAD

**Issue by datakurre** [hasura/graphql-engine#2236]
I just upgraded from Hasura v1.0.0-alpha40 to v1.0.0-beta.1 on PostgreSQL 9.4 and started seeing the following error on server logs:

```
{"timestamp":"2019-05-20T12:32:23.976+0000","level":"error","type":"event-trigger","detail":{"internal":{"statement":"
      UPDATE hdb_catalog.event_log
      SET locked = 't'
      WHERE id IN ( SELECT l.id
                    FROM hdb_catalog.event_log l
                    JOIN hdb_catalog.event_triggers e
                    ON (l.trigger_name = e.name)
                    WHERE l.delivered ='f' and l.error = 'f' and l.locked = 'f'
                          and (l.next_retry_at is NULL or l.next_retry_at <= now())
                    FOR UPDATE SKIP LOCKED
                    LIMIT 100 )
      RETURNING id, schema_name, table_name, trigger_name, payload::json, tries, created_at
      ","prepared":true,"error":{"exec_status":"FatalError","hint":null,"message":"syntax error at or near \"SKIP\"","status_code":"42601","description":null},"arguments":[]},"path":"$","error":"postgres query error","code":"unexpected"}}
```
I assume that this was introduced in https://github.com/hasura/graphql-engine/pull/1798 and from the pull it is not obvious if this is an intentional incompatibility with old PostgreSQL 9.4.

**Comment by ecthiender** [comment]
@datakurre thanks for the info. Hasura does not support Postgres 9.4 completely [1]. We will try to fix this.

In the meantime, is it possible for you to use Postgres >= 9.5 ?

[1] See #1450, #210

**Comment by datakurre** [comment]
Thanks. I guess I manage with a self-built image without that line until our migration to pg11 is completed.

**Comment by tirumaraiselvan** [comment]
Closing as compatibility below 9.4 (including) is not guranteed.
