### ISSUE TITLE
Feature Request: Add a (+) button for specifying conditions on permissions

### ISSUE THREAD

**Issue by timminkov** [hasura/graphql-engine#2237]
Right now the `or` modifier is buried a bit in the dropdown for permissions:
<img width="538" alt="Screen Shot 2019-05-20 at 11 34 59 AM" src="https://user-images.githubusercontent.com/3485060/58043926-5a2c3900-7af3-11e9-9714-36d25b69f564.png">

It would be really nice if there were something like this instead (placed in the appropriate spot):
<img width="446" alt="Screen Shot 2019-05-20 at 11 36 29 AM" src="https://user-images.githubusercontent.com/3485060/58044002-8fd12200-7af3-11e9-88f3-1044895def71.png">

**Comment by dsandip** [comment]
A quickfix can be to flip the order to have the operators first and the columns next.

**Comment by 0x777** [comment]
@rikinsk I like the idea of having `_and`/`_or`/`_not` on the top. What do you think?

**Comment by rikinsk** [comment]
@0x777 This is already done and live.
