### ISSUE TITLE
create foreign key during create table

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#224]
Clicking on FK then throws up a list of the potential candidates to other tables in a dropdown.

**Comment by dsandip** [comment]
@praveenweb This gets handled in #506. Closing this.

**Comment by ecthiender** [comment]
@dsandip but #506 is about supporting "composite" primary keys and foreign keys in the console. This issue is about creating a foreign key in the "Create table" step itself. 

Let me know if that's not the case and I missed something.

**Comment by dsandip** [comment]
@ecthiender #506 has taken a life of its own and is trying to do a whole bunch of things. I am blaming @arvi3411301 's enthusiam for it :) . See https://github.com/hasura/graphql-engine/issues/506#issuecomment-433328426

**Comment by ecthiender** [comment]
Ah ok. Sorry my bad.
