### ISSUE TITLE
Embed custom header in logs

### ISSUE THREAD

**Issue by Krever** [hasura/graphql-engine#2244]
Hey, 

in our system we use trace ids encoded as http headers to trace the traffic across microservices. Do you think it would be possible to somehow configure hasura so that given http header should be embedded inside log messages? 

I expect its not already implemented but would like to learn how much work would it be to add such feature and if it makes sense from your perspective.

**Comment by ecthiender** [comment]
@Krever we log `x-request-id` header, if sent from client. It gets logged as `request_id`. Does this solve your use-case?

**Comment by Krever** [comment]
@ecthiender oh, thats a great news. It helps indeed! Thanks!
