### ISSUE TITLE
subscriptions on remote GraphQL servers

### ISSUE THREAD

**Issue by cescoferraro** [hasura/graphql-engine#2247]
The docs clearly states that I should not work. But I found out about the repo here https://github.com/hasura/custom-resolvers-boilerplate. And a issue that implies it works with a bug here #2246. I am trying to follow the customer-resolver example with no luck. Queries work fine. Subscriptions do not work though the merged API. I can still subscribe through Hasura itself. 

Should it work? If so, what I am doing wrong? I get the following error 
```
{
  "error": "Could not connect to websocket endpoint ws://localhost:4000/graphql. Please check if the endpoint url is correct."
}
```

## Hasura
`docker run -d -p 8080:8080 --net host -e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:docker@localhost:5432/dvdrental  -e HASURA_GRAPHQL_ENABLE_CONSOLE=true  hasura/graphql-engine:latest`

## Express
```
import pg from 'pg';
import ws from 'ws';
import knex from 'knex';
import express from 'express';
import fetch from 'node-fetch';
import { split } from 'apollo-link';
import { HttpLink } from 'apollo-link-http';
import { WebSocketLink } from 'apollo-link-ws';
import { ApolloServer } from 'apollo-server-express';
import { getMainDefinition } from 'apollo-utilities';
import { SubscriptionClient } from 'subscriptions-transport-ws';
import { mergeSchemas, makeExecutableSchema } from 'graphql-tools';
import { makeRemoteExecutableSchema, introspectSchema } from 'graphql-tools';

const pgURL = ()=>{
    let url = "postgres://postgres:docker@localhost:5432/dvdrental";
    return url;
};

const HASURA_GRAPHQL_ENGINE_URL = `http://localhost:8080`;
const HASURA_GRAPHQL_API_URL = HASURA_GRAPHQL_ENGINE_URL + '/v1/graphql';

let count = 0;

const resolvers = {
    Query: {
	hello: (root, args, context, info) => {
	    return 'Hello world!';
	},
	count: (root, args, context, info) => {
	    return count++;
	},
	user_average_age: async (root, args, context, info) => {
	    const knexClient = knex({client: 'pg', connection: pgURL()});
	    const response = await knexClient('film').avg('film_id');
	    return response[0].avg;
	}
    },
    Mutation: {
	increment_counter: (root, args, context, info) => {
	    return { new_count: ++count };
	}
    }
};


const typeDefs = `
  type Query {
    hello: String,
    count: Int,
    user_average_age: Float
  }
  type Mutation {
    increment_counter: MutationResp
  }
  type MutationResp {
    new_count: Int
  }
`;

const chooser = ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    return kind === 'OperationDefinition' && operation === 'subscription';
}

const makeHttpAndWsLink = (uri, headers) => {
    const httpLink = new HttpLink({uri, fetch, headers}); 
    const wsLink = new WebSocketLink(new SubscriptionClient(uri, {reconnect: true,}, ws));
    const link = split(chooser, wsLink, httpLink,);
    return link;
};

// util function to fetch and create remote schema
export const getRemoteSchema = async (uri, headers) => {
    const link = makeHttpAndWsLink(uri, headers);
    const schema = await introspectSchema(link);
    return makeRemoteExecutableSchema({schema, link});
}

const runServer = async () => {
    const executableHasuraSchema = await getRemoteSchema(HASURA_GRAPHQL_API_URL, { });
    const executableCustomSchema = makeExecutableSchema({typeDefs, resolvers,}); 
    const finalSchema = mergeSchemas({schemas: [executableCustomSchema, executableHasuraSchema,]});
    const server = new ApolloServer({schema: finalSchema, introspection: true, playground: true});
    const app = express();
    server.applyMiddleware({ app, path: '/graphql' });
    app.listen({ port: 4000 }, () => {console.log('Apollo Server on http://localhost:4000/graphql');});
}

try {
    runServer();
} catch (e) {
    console.log(e, e.message, e.stack);
}
```

**Comment by ecthiender** [comment]
@cescoferraro as you have guessed, subscriptions on remote servers are not supported currently. https://docs.hasura.io/1.0/graphql/manual/remote-schemas/index.html#current-limitations

But it is being worked on and will be released soon. You can check out the PR build to test things out in the meanwhile. PR: #1802 (`hasura/graphql-engine:pull1802-602e0ef7`)

**Comment by cescoferraro** [comment]
@ecthiender I got the engine working at #1802 with the following command

`stack exec graphql-engine -- --database-url=postgres://postgres:docker@localhost:5432/dvdrental serve --enable-console --console-assets-dir ../console/static/dist `

But the merged express api shows all kinds of errors. Queries still work, even though the UI says the server is not reachable.

![hasura](https://user-images.githubusercontent.com/6259987/58181121-968d9f80-7c81-11e9-80d1-65620eac953b.png)

**Comment by ecthiender** [comment]
@cescoferraro are you merging the hasura server schema to your own express-graphql server? Ah, I thought you were using the "Remote Schemas" feature of Hasura to add your own GraphQL server.

So you have added Hasura to your own express-graphql server, and now want to make subscriptions to Hasura via your own GraphQL server? Is my understanding correct?

**Comment by cescoferraro** [comment]
> So you have added Hasura to your own express-graphql server, and now want to make subscriptions to Hasura via your own GraphQL server? Is my understanding correct?

@ecthiender yes! I need to extend the generated schema.

**Comment by ecthiender** [comment]
@cescoferraro ah then you should look at Hasura logs to figure out what is the exact error. 

The above PR and issues I have mentioned are for Hasura's built-in "Remote Schema" feature. Those won't apply here.

**Comment by cescoferraro** [comment]
@ecthiender I have cloned the customemr-resolver boilerplate and narrowed down the problem to the apollo-server-express library. I am using the @rc tag that exposes the ApolloServer constructor but still no luck.

```
import fetch from 'node-fetch';
import http from 'http';
import express from 'express';

import { mergeSchemas, makeExecutableSchema } from 'graphql-tools';
import { getRemoteSchema } from './utils';
import typeDefs from './customTypeDefs';
import resolvers from './customResolvers';

const HASURA_GRAPHQL_ENGINE_URL = `http://localhost:8080`;
const HASURA_GRAPHQL_API_URL = HASURA_GRAPHQL_ENGINE_URL + '/v1/graphql';

const runServer = async () => {
    const executableHasuraSchema = await getRemoteSchema(HASURA_GRAPHQL_API_URL, { });
    const executableCustomSchema = makeExecutableSchema({typeDefs, resolvers});
    const finalSchema = mergeSchemas({schemas: [executableCustomSchema, executableHasuraSchema,]});

    // Works
    // const { ApolloServer }  = require('apollo-server');
    // const server = new ApolloServer({schema: finalSchema, introspection: true, playground: true});
    // server.listen({port: 4000}) .then(({url}) => {console.log('Server running. Open ' + url + ' to run queries.');});

    // Fails for websocket connection
    // const { ApolloServer }  = require('apollo-server-express');
    // const server = new ApolloServer({schema: finalSchema, introspection: true, playground: true});
    // const app = express();
    // server.applyMiddleware({ app,path:"/graphql" });
    // app.listen({ port: 4000 }, () => console.log(`🚀 Server ready at http://localhost:4000${server.graphqlPath}`));


    // Fails playground is invisible 
    const { ApolloServer }  = require('apollo-server-express');
    const server = new ApolloServer({schema: finalSchema, introspection: true, playground: true});
    const app = express();
    const httpServer = http.createServer(app);
    server.installSubscriptionHandlers(httpServer);
    httpServer.listen(4000, () => {
    	console.log(`🚀 Server ready at http://localhost:${4000}${server.graphqlPath}`);
    	console.log(`🚀 Subscriptions ready at ws://localhost:${4000}${server.subscriptionsPath}`);
    });
};

try {
    runServer();
} catch (e) {
    console.log(e, e.message, e.stack);
}

```

**Comment by cescoferraro** [comment]
turns out apollo-server-express changed a bit.
One need to call applyMiddleware and installSubscriptionHandlers on the server before running the http server

```
const runServer = async () => {
    const executableHasuraSchema = await getRemoteSchema(HASURA_GRAPHQL_API_URL, { });
    const executableCustomSchema = makeExecutableSchema({typeDefs, resolvers});
    const finalSchema = mergeSchemas({schemas: [executableCustomSchema, executableHasuraSchema,]});
    const server = new ApolloServer({schema: finalSchema, introspection: true, playground: true});
    const app = express();
    server.applyMiddleware({ app});
    const httpServer = http.createServer(app);
    server.installSubscriptionHandlers(httpServer);
    httpServer.listen(4000, () => {
    	console.log(`🚀 Server ready at http://localhost:${4000}${server.graphqlPath}`);
    	console.log(`🚀 Subscriptions ready at ws://localhost:${4000}${server.subscriptionsPath}`);
    });
};

```

**Comment by szhang-ezypay** [comment]
Hi @cescoferraro 
I'm trying to do the same. I have several hasura servers and I use apollo schema stitching to group them together.
In my vue app, I'm using vue-apollo to make requests to apollo.
The error I'm getting is `subscriptions are not supported over HTTP, use websockets instead`.

**Comment by TheRohitSharma** [comment]
> Hi @cescoferraro
> I'm trying to do the same. I have several hasura servers and I use apollo schema stitching to group them together.
> In my vue app, I'm using vue-apollo to make requests to apollo.
> Query and mutation work fine. But with subscription, the error I'm getting is `subscriptions are not supported over HTTP, use websockets instead`.

Did you ever have any luck with this, @szhang-ezypay ? I just started with Hasura a few days ago, and I'm not sure how to get subscriptions working because of that error.

**Comment by mehmetekinci** [comment]
@TheRohitSharma It comes mostly from a small typo. I had same error today. I noticed that I have a typo.
