### ISSUE TITLE
Keep untracked custom functions visible in the UI and explain function requirements

### ISSUE THREAD

**Issue by waynebloss** [hasura/graphql-engine#2249]
When there are no compatible custom functions defined in the database, Hasura does not even show the section entitled **Untracked custom functions** in the *Data / Schema* view. Instead, I think it should always show that section with a note stating the strict requirements for functions to show up there.

I had a pre-existing custom function and I didn't understand immediately why it wasn't showing up. I thought it was a bug or a not-yet-released feature.

**Comment by dsandip** [comment]
@AnnieAtHasura @anubhuti-mishra 

![untrackable-functions](https://user-images.githubusercontent.com/24300818/60951064-f6193a80-a315-11e9-97c4-0fb1542226cb.png)

**Comment by AnnieAtHasura** [comment]
ok, implementing as per Sandip's screenshot

**Comment by rikinsk** [comment]
Proposed solution:
- fetch all user defined functions via sql
- remove already tracked functions
- remove trackable functions
- display the rest as untrackable functions
