### ISSUE TITLE
[BUG] [UI] SQL query result table

### ISSUE THREAD

**Issue by mnlbox** [hasura/graphql-engine#2253]
Hi,
I run a query in SQL window in console app but it seems result section has a little buggy UI.
It shows boolean field with `t` and `f` rather than `true`, `false` for a big query result `t` & `f` is a little confusing.
See this image:
![Screenshot from 2019-05-23 10-01-42](https://user-images.githubusercontent.com/25859075/58227913-1418e480-7d42-11e9-92e4-61be8061c90b.png)

**Comment by mnlbox** [comment]
@0x777 , @marionschleifer Any news about this bug?

**Comment by rikinsk** [comment]
@mnlbox This is how postgres returns values of [boolean columns](https://www.postgresql.org/docs/current/datatype-boolean.html). Hasura just relays the values returned by Postgres without any modification. If you need the values to be returned as `true` and `false` you need to make the query with appropraite casting (see [this stackoverflow page](https://stackoverflow.com/questions/34440068/return-boolean-value-as-true-or-false-in-select-postgresql-pgadmin/34440193) for some ideas around this)
