### ISSUE TITLE
Disable Mutations vs Mutation Authorization

### ISSUE THREAD

**Issue by cescoferraro** [hasura/graphql-engine#2257]
I am loving Hasura, but the project I am trying to use Hasura has many security concerns.
I am able to authenticate both http and ws very nicely.

I want to disabled the migrations all together. I am extending the schema so I wish to write my own mutations since the algorithms will most likely involve other API calls. Is there a way to do it? Could not find it on the docs.

Maybe I am approaching the problem the wrong way, but the other major issue is that not everybody authenticated on my api has the right to insert_user ou cannot update_user other than himself. Any pointers?

**Comment by shahidhk** [comment]
@cescoferraro You can disable mutations altogether if you add permissions and disallow inserts, updates and deletes. 

You can find some examples here: https://docs.hasura.io/1.0/graphql/manual/auth/authorization/common-roles-auth-examples.html

To write your own mutations, you can use Remote Schemas: https://docs.hasura.io/1.0/graphql/manual/remote-schemas/index.html

Check out the authentication and authorization part of the docs for a more comprehensive guide: https://docs.hasura.io/1.0/graphql/manual/auth/index.html

You could join our Discord server for a more one-on-one conversation with the community: https://discord.gg/hasura

**Comment by marionschleifer** [comment]
I'm closing this. @cescoferraro if you have any more questions regarding this, please feel free to re-open this issue 🙂
