### ISSUE TITLE
error on editing a uuid column

### ISSUE THREAD

**Issue by yuuuxt** [hasura/graphql-engine#2258]
Hasura goes to the error page when I click "edit" on a uuid column. 

To reproduce: create a table with column "id"(integer, primary key) and a column "test"(uuid), and click "edit" on column "test" in "modify" tab. 

hasura version: beta.2

**Comment by shahidhk** [comment]
verified bug.

**Comment by thetre97** [comment]
I also get this when trying to edit a column with an ENUM type - as per https://docs.hasura.io/1.0/graphql/manual/schema/enums.html#option-1-using-native-postgres-enum-type. Not sure if they are related?

**Comment by thetre97** [comment]
The console shows `TypeError: Cannot read property 'slice' of undefined`
