### ISSUE TITLE
Show unique & primary constraint name

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#226]
GraphQL upsert queries may need the name of unique constraints. This information is not available in the console.

**Comment by WickedBrat1** [comment]
Hi @praveenweb I'd like to work on this. What is the expected outcome for this?

**Comment by coco98** [comment]
Hi folks, I would like to bump up priority on this. It is very inconvenient to not see the constraint names when it comes to modifying primary keys, or looking and on-conflict clauses.

**Comment by rikinsk** [comment]
Also add this in the same effort https://github.com/hasura/graphql-engine/issues/506#issuecomment-458890695

**Comment by rikinsk** [comment]
@WickedBrat We can show this information as a comma separated list in the modify section of a table next to each column like we show _primary key._ 

![screenshot from 2019-02-08 14-58-32](https://user-images.githubusercontent.com/153602/52469682-25364f00-2bb2-11e9-8694-884544644bd0.png)

@praveenweb Sounds good?

**Comment by rikinsk** [comment]
For example, for `article`:

**id** - _uuid, primary-key (article_pkey), default: gen_random_uuid();_
**title** - _text, unique (article_title_key)_
**author_id** - _uuid, foreign-key (author : id)_
**published_on** - _timestamp, nullable_
**created_at** - timestamp, _default: now()_

**Comment by shahidhk** [comment]
@dsandip @rikinsk Should we work on a Table based screen here instead of overloading single line?

**Comment by rikinsk** [comment]
@shahidhk You'll need to be a little more specific. How will the edit interaction work? 

I'd rather not think of a huge design change for now. Will take longer to implement and I sense a design overhaul is on the cards soon enough anyways. Quick and dirty which does the job works for me now.

**Comment by dsandip** [comment]
@rikinsk @shahidhk Wawhal is thulping #506 out for the next sprint. Do we need anything other than the type and the default values here? Also, I am okay with Rikin's quick and dirty approach™, except for some color coding (_for types and diff color for the default value text_?) or gap betwen rows perhaps? Readability is going to be a nightmare for tables with > 10 columns.
