### ISSUE TITLE
Track tables created from SQL migrations by default

### ISSUE THREAD

**Issue by tmattio** [hasura/graphql-engine#2277]
I write my migrations using SQL. Unfortunately, I still have to create YAML migrations for every table that I create because the tables created from the SQL migrations are not tracked by default.

I think it is fair to assume that the user wants to track the tables created in the migrations.

I don't know how difficult it would be to implement, but it would definitely improve the migration experience :)

**Comment by manasag** [comment]
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.
