### ISSUE TITLE
Dropping a column does not generate appropriate down migration

### ISSUE THREAD

**Issue by avimoondra** [hasura/graphql-engine#2291]
Dropping a column from a table does not generate down migration, which is expected to be an alter table/ add column? 

`ALTER TABLE table_name ADD COLUMN new_column_name data_type;`

Here's an example (Github screenshot)

![image](https://user-images.githubusercontent.com/2534903/58494867-e4475380-812a-11e9-862d-cf7eddc64987.png)

**Comment by ecthiender** [comment]
@avimoondra if you're using the SQL window on console, down migrations are not generated. This is because, arbitrary SQL can be run and we have no way of knowing what the down migration for it would be.

**Comment by ecthiender** [comment]
There is a note in the SQL window, but I guess its not very apparent.

**Comment by ecthiender** [comment]
@rikinsk @shahidhk @coco98 @0x777 is it a good idea to prompt the user to enter another SQL for down migration?

**Comment by avimoondra** [comment]
@ecthiender I think it's relatively clear from the SQL window, but the migrations in the diff pasted were generated from deleting a column via this interface:

![image](https://user-images.githubusercontent.com/2534903/58570751-5a13f380-81ed-11e9-868b-63b285b3fb7c.png)
