### ISSUE TITLE
Possible to insert object with many-to-many relation in one query?

### ISSUE THREAD

**Issue by nolandg** [hasura/graphql-engine#2293]
I already have many `tag` objects defined. I have a `tag_to_post` many-to-many table defined. A user creates a `post`, sets the title, body, etc. and tags it with 3 `tag`s.

If I insert the `post`  and make 3 insertions into the `tag_to_post` table in the same query...it can't work because the `tag_to_post` insert mutation requires the primary key (`id` say) of the new `post` object.

Is there any way to access the last inserted primary key (like `RETURNING id`) in the same graphql mutation that inserted it?

The only option I see is abandoning Postgres-generated primary keys (auto inc ids, series, etc) and managing random uuids on the app end.

It could be split into 2 queries but then it loses transactionality.

**Comment by thefliik** [comment]
> The only option I see is abandoning Postgres-generated primary keys (auto inc ids, series, etc) and managing random uuids on the app end.

Just in case you aren't aware, postgres can also generate uuids for you if you set the `id` column default to `gen_random_uuid()`.

**Comment by rikinsk** [comment]
@nolandg this might be of help. <https://docs.hasura.io/1.0/graphql/manual/mutations/insert.html#insert-an-object-and-its-nested-object-in-the-same-mutation>

If you have a relationhip called `post_tags` from `post` to `post_to_tag` table, you can enter a `post` along with its nested `post_tags` into the `tag_to_post` table in a single query. The `tag_to_post:id` will automatically be filled in with the `post:id` via the relationship definition.

Let us know if you need any more clarification

**Comment by nolandg** [comment]
Thanks @rikinsk, that example is for a one-to-many relationship and I assumed there was no support for many-to-many if it wasn't documented. Thanks for letting me know, I'll try it out.

**Comment by msmedes** [comment]
@rikinsk what if you want to upsert multiple `post_tags` when creating a `post`? The way the docs have it if even if generating `uuid`'s or `int` ids client side you would still need to query the db for each `id` to see if it exists, if so return the `id`, then if not generate a new `uuid` for each new `post_tag` then add it to the `insert`.  I know there is the `on_conflict` option but as far as I can tell it just considers that an error and cancels the entire `mutation`.  Am I reading this wrong or is there a better way?

**Comment by rikinsk** [comment]
@msmedes I am not sure I completely understand your use case. But `on_conflict` seems to be what you are looking for. `on_conflict` does not cancel a mutation as you mentioned but lets you decide what the action should be based on the `update_columns` field. In case of nested upserts like our case here, if you pass the `update_column` field as `[<conflict-column>]` the insert should go through as expected.

The following is the query I would run to insert a post along with its tags (given `tag` has a unique field called `value`)

```graphql
mutation {
  insert_post(
    objects: [
      {
        title: "new post",
        post_tags: {
          data: [
            {
              tag: {
                data: {
                  value: "tech"
                },
                on_conflict: {
                  constraint: tag_value_key,
                  update_columns: [value]
                }
              }
            },
            {
              tag: {
                data: {
                  value: "blog"
                }
                on_conflict: {
                  constraint: tag_value_key,
                  update_columns: [value]
                }
              }
            }
          ]
        }
      }
    ]
  ) {
    returning {
      id
      title
      post_tags {
        id
        tag {
          id
          value
        }
      }
    }
  }
}
```
with response

```json
{
  "data": {
    "insert_post": {
      "returning": [
        {
          "id": "f03bdccf-6344-4771-851b-efdd9bc5f4fc",
          "title": "new post",
          "post_tags": [
            {
              "tag": {
                "value": "tech",
                "id": "5e8f15fe-c187-4961-940e-d45206a7ff05"
              },
              "id": "99694d90-245b-4157-9496-a630b563ebd7"
            },
            {
              "tag": {
                "value": "blog",
                "id": "dedd495b-fb2c-4b7f-8989-73b67908352d"
              },
              "id": "fa3d372c-2102-40a2-8892-54bb8cd93e58"
            }
          ]
        }
      ]
    }
  }
}
```
Hope this clarifies things

**Comment by msmedes** [comment]
@rikinsk Reading my question back I wasn't that clear, apologies.  You still managed to answer my question though!  I missed the part of the docs where you can set `update_columns` to the `on_conflict` column (before I was setting it to an empty array but that was just canceling the entire insert).  Also did not realize you can do an array of `many_to_many``upserts`.  All sorted, thanks!

**Comment by marionschleifer** [comment]
I'm closing this. @msmedes if you have any more questions or anything to add, feel free to re-open this issue 🙂

**Comment by rikinsk** [comment]
@marionschleifer Reopening this to track the docs enhancements. We should add an example for many-to-many relationship in nested inserts.

**Comment by dohomi** [comment]
@rikinsk I stumbled about this exact issue and was looking inside of the Hasura docs for some insights. It would be helpful to showcase mutations/updates of mn relations inside of your docs

**Comment by rikinsk13** [comment]
@dohomi Sure thing. I am sure @marionschleifer will get around to adding this soon. Maintaining a good priority queue is a hard task :)

**Comment by rikinsk13** [comment]
Related to #1310

**Comment by marionschleifer** [comment]
@dohomi @rikinsk thank you for the reminder. I will get this done within the next two weeks 🙂

**Comment by dohomi** [comment]
@marionschleifer thanks a lot that will be helpful!

**Comment by dohomi** [comment]
I am currently understood following create statement. But lets say one part of the mn-table would need to change: an update on Article and their responding tags would need to get updated. How would that statement looks like? I tried an "upsert" and "update" statement but with both I can't update / set the post_tag relation.

Could you maybe post an example I am kind of stuck how to proceed.

**Comment by mitar** [comment]
I have a slightly related question. How could I prevent related documents to be inserted and allow just the main one to be? So in example above, let's imagine that I do not want to allow defining new tags in such ad-hoc manner. I would only want a M2M relation so that I can select among existing tags. In a way, I would want that only the `on_conflict` case is allowed to be run.

**Comment by marionschleifer** [comment]
This has been added to the documentation.

@mitar could you please ask this and other specific questions on our [Discord channel](http://hasura.io/discord) 🙂

**Comment by mitar** [comment]
To [answer my question from above](https://github.com/hasura/graphql-engine/issues/2293#issuecomment-554702829), this can be done through permissions. Or user has permissions to insert new tags or not.
