### ISSUE TITLE
Supporting Directives similar to graphql lodash

### ISSUE THREAD

**Issue by 240226068** [hasura/graphql-engine#2301]
Supporting Directives similar to graphql lodash

**Comment by 0x777** [comment]
I'm assuming you are referring to this project: https://github.com/APIs-guru/graphql-lodash. The directives in the examples manipulate the shape of the response which may not conform with the published schema. This is acknowledged in the project's readme:

> In theory, this tool can be used on the server. But this will break the contract and, most likely, will break all the GraphQL tooling you use. Use it on server-side only if you know what you do.
