### ISSUE TITLE
Remote schema issues during failure events

### ISSUE THREAD

**Issue by karthikvt26** [hasura/graphql-engine#2303]
I am facing bunch of issues in remote schema.

1) If I try to add a remote schema and if it fails with some error. It still comes up in the left side bar,  deleting which throws an error saying schema doesn't exist.
2) Post addition of a remote schema. If I delete the remote schema graphql server (on heroku) but haven't refreshed the schema yet on the graphql engine side. My table creation fails with an encrypted error (I am guessing remote schema is being fetched at this step as I could see not found heroku error).

Is this intended?

@dsandip

**Comment by dsandip** [comment]
@0x777 @rakeshkky FYI

**Comment by napalm272** [comment]
I just ran into this today. The first item is definitely a bug.

**Comment by tirumaraiselvan** [comment]
@wawhal Could you look at bug 1) pls. I have noticed this too from before Remote Joins.

**Comment by rikinsk** [comment]
The first issue is fixed in a PR awaiting merge @rakeshkky can link to it.

**Comment by tirumaraiselvan** [comment]
Yeah this is definitely a server side bug happening during the "schema generation" phase.

**Comment by rikinsk** [comment]
Verified both issues. They seem to be fixed now.
Closing this
