### ISSUE TITLE
Documentation apollo subscription 

### ISSUE THREAD

**Issue by dietergoetelen** [hasura/graphql-engine#2308]
The following file indicates GraphQL subscriptions do not return data when first connected: 
https://github.com/hasura/graphql-engine/blob/master/community/learn/graphql-tutorials/tutorials/vue-apollo/tutorial-site/content/subscriptions/2-apollo-subscription.md

If I recall correctly this is true according the apollo spec but not for Hasura. In Hasura the subscription acts more like a Live query by returning an initial result. Is this something we should improve/adjust in the tutorials?

**Comment by praveenweb** [comment]
Hi @dietergoetelen - You are right. In Hasura, it's a live query. But in general Vue Apollo Subscription context, there is no initial result. The course doesn't assume that the server is Hasura. But there is room for improvement in the tutorial. We will make an update.
