### ISSUE TITLE
Recover from an inconsistent database state

### ISSUE THREAD

**Issue by karthikvt26** [hasura/graphql-engine#231]
@0x777 suggested that graphql-engine will ignore the errors ( Due to inconsistent db state ) if it has occured due to updates to db via psql or any client. Graphql engine will provide an endpoint which will be called by console to show instructions to the user on how to fix it.

@praveenweb

**Comment by karthikvt26** [comment]
- Create a column on adminer
  - Result: 
    - Console: doesn't load because it requests for the column added to adminer and graphql engine returns 400
    - Graphql Engine: No issues
  - Solution:
    - Restarting graphql-engine solves the problem

- Delete a column from adminer
  - Result: 
    - Console: if it is already opened will not work when the tab changed to `Browse Rows`. If refreshed works
    - Graphql Engine: No issues
  - Solution:
    - Console: Refreshing console solves the problem

- Create a foreign key to a table, add a relationship to that table, remove the foreign key
  - Result: 
    - Console: crashes with error: 'something went wrong' since graphql engine still has that relationship.
    - Graphql Engine: If graphql engine is restarted, it crashes: 2018-07-31T10:07:24.206251+00:00 app[web.1]: QErr {qePath = [], qeStatus = Status {statusCode = 400, statusMessage = "Bad Request"}, qeError = "table \"hasura_user\"; rel \"address_fk\"; no foreign constraint exists on the given column", qeCode = constraint-error, qeInternal = Nothing}
  - Solution:
    - Add the foreign key again on adminer to solve the issue

- Create a table using console and delete it from adminer
  - Result:
    - Console: data tab crashes with error: 'something went wrong'
    - Graphql Engine: If graphql engine is restarted, it crashes: QErr {qePath = [], qeStatus = Status {statusCode = 400, statusMessage = "Bad Request"}, qeError = "table \"hasura_user\"; no such table/view exists in postgres : \"hasura_user\"", qeCode = not-exists, qeInternal = Nothing}
  - Solution: 
    - Fix: Create the table again to solve the issue

- Create a field with same name as relationship
  - Result: 
    - Console: No UI ( as the graphql engine doesn't start )
    - Graphql Engine: QErr {qePath = [], qeStatus = Status {statusCode = 500, statusMessage = "Internal Server Error"}, qeError = "table \"user_address\"; rel \"address\"; field already exists ", qeCode = unexpected, qeInternal = Nothing}
  - Solution: 
    - Drop the created column

- Create a new column in adminer, go to console, refresh the page, the `Browse rows` tab will fail. Switch to Permissions tab and it should show the new column.

- Rename a column on adminer
  - Result:
    - Console: the table in which column has been renamed doesn't update in the GraphiQL.

- Create a column in both parent and child table and create a manual relationship from child to parent. Delete both the columns
  - Result:
    - Console: the manual relationship created above shows up in GraphiQL.


@praveenweb @rakeshkky 

@0x777

**Comment by karthikvt26** [comment]
For this to work GraphQL engine should listen to postgres events to identify `DDL` statements executed via psql or adminer

Workflow

1. When console is loaded, it pings an endpoint `/current_state` which returns either
  ```
     {
       is_valid: false,
       suggestions: [.....]
     }
  ```

   or 

   ```
      {
        is_valid: true
      }
   ```
2. If the state is invalid, console takes the user to a new route `/resolution_steps` and provide sql statements which can be executed via `psql` or `adminer` to fix.

3. Whenever user resolves one issue, console will check for the state again and continue.

@0x777 your views?

**Comment by rakeshkky** [comment]
@praveenweb @karthikvt26 
API `v1/current_state` is changed to query type `current_state`.

Spec:-
```http
POST /v1/query

{
  "type": "current_state",
  "args": {}
}
```
Branch [issue-231](https://github.com/rakeshkky/graphql-engine/tree/issue-231) is updated with above changes.

**Comment by dsandip** [comment]
This will need a dedicated health-check endpoint #1532 
cc: @0x777 @shahidhk

**Comment by chunsli** [comment]
any updates on this?

**Comment by dsandip** [comment]
@rakeshkky 1)

**Comment by dsandip** [comment]
@rakeshkky @rikinsk This "soft" start feature will have to feature gated with an environment variable/flag

**Comment by coco98** [comment]
We should have a basic "soft" start out. Perhaps for the initial features:

1. Allow `hasura metadata apply` and `hasura metadata reset` commands to be run so that atleast an older version of the metadata can be applied
2. Show list of invalid metadata rules that the console can show

**Comment by dsandip** [comment]
# Wireframes for console

If there's an inconsistent state, the server will apply the consistent subset of metadata and let the console know that there's another subset that is inconsistent. Based on this, the console will show the `console/metadata` page with the following updates:

**Consistent state**
![6inconsistentmetadatapagelanding](https://user-images.githubusercontent.com/24300818/54898503-9a57ac80-4ef2-11e9-803d-71f34c21c1f3.png)

**Inconsistent state**
![7inconsistentmetadatapagelandinginconstate](https://user-images.githubusercontent.com/24300818/54898649-1f42c600-4ef3-11e9-8aac-4e39704c94da.png)

Users will have an option to either manage inconsistent objects and apply metadata again or delete all the objects, with a confirmation for the latter:

![8inconsistentmetadatapagedelete_confirmation](https://user-images.githubusercontent.com/24300818/54898797-92e4d300-4ef3-11e9-8ca8-1e6a04f06cdc.png)

Post-confirmation, there should be feedback that all inconsistent objects have been deleted and the state is now consistent:

![9inconsistentmetadatapagepostdeletemessage](https://user-images.githubusercontent.com/24300818/54899039-7e550a80-4ef4-11e9-923c-a14294c56224.png)

@rakeshkky @shahidhk

**Comment by dsandip** [comment]
To indicate inconsistent state, the color of the settings icon will be changed with a tooltip "Metadata is inconsistent!".

**Comment by dsandip** [comment]
@wawhal Text updates:

 ![7inconsistentmetadatapagelandinginconstate](https://user-images.githubusercontent.com/24300818/55475328-46a33c80-5631-11e9-9f73-6db97cb87301.png)
