### ISSUE TITLE
Add ability to untrack existing tracked foreign-key relations

### ISSUE THREAD

**Issue by aszenz** [hasura/graphql-engine#2312]

**Comment by dsandip** [comment]
@aszenz You can drop relationships (*manual or foreign-key-based*) both via the console and the [Metadata API](https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/relationship.html#drop-relationship). Is there any enhancement you are looking for in either/both of these?

**Comment by aszenz** [comment]
> @aszenz You can drop relationships (_manual or foreign-key-based_) both via the console and the [Metadata API](https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/relationship.html#drop-relationship). Is there any enhancement you are looking for in either/both of these?

Instead of dropping a relationship, I want to untrack a certain relationship from the api.
From your example:
`todos{
  users{
    name
  }
}`
How can I untrack the users relationship above, so it isn't shown in the api?

**Comment by rikinsk** [comment]
@aszenz Just to clarify, tracking a postgres foreign-key creates a hasura relationship (ie. exposes it over the GraphQL API). Hence, removing a relationship untracks the foreign-key and stops exposing it over the GraphQL API

Just hit the `Remove` button as shown below:
![Screenshot from 2019-06-03 15-16-56](https://user-images.githubusercontent.com/153602/58792975-d2761c80-8612-11e9-9afe-5de03e045710.png)

**Comment by aszenz** [comment]
> @aszenz Just to clarify, tracking a postgres foreign-key creates a hasura relationship (ie. exposes it over the GraphQL API). Hence, removing a relationship untracks the foreign-key and stops exposing it over the GraphQL API
> 
> Just hit the `Remove` button as shown below:
> ![Screenshot from 2019-06-03 15-16-56](https://user-images.githubusercontent.com/153602/58792975-d2761c80-8612-11e9-9afe-5de03e045710.png)

thanks finally understood it now.
