### ISSUE TITLE
bug: attempting to edit uuid column with citext extension installed throws error

### ISSUE THREAD

**Issue by thefliik** [hasura/graphql-engine#2314]
The following produces an error and prompts me to report the issue:

1. Create a new table in Hasura web console and save it
2. Modify the table to add a new column `user_id`, specify that the column is not `nullable` (so uncheck the nullable box).
3. Click the "edit" button next to the new `user_id` column.
4. An error page appears, preventing the `user_id` column from being edited.

Editing other columns of the table seems to work fine.

(Using Hasura v1.0.0-beta.2)

**Comment by rikinsk** [comment]
@thefliik Hi. Thanks for reporting this. Unfortunately I couldn't reproduce this on my end. 
There should ideally be an error logged in your browser console when the error page appears. It would be really helpful if you could share that.

**Comment by thefliik** [comment]
@rikinsk ok. Just testing again I found that my reproduction instructions were incomplete. I'm not sure which of the following steps are important, but *I think this correctly triggers the error*:

1. Go to data > sql > run `create extension citext`.
2. Create a new table in Hasura's web console named `user_email_addresses`
   - The table should have an `id` column of type `uuid` and default `gen_random_uuid()`. This is the primary key.
   - An `email_address` column of type `citext` which is `unique`.
   - A `label` column of type `citext` which is `nullable`.
   - Save the table.
3. Modify the table to add a new column `user_sensitive_profile_id ` of type `uuid`. Specify that the column is not nullable (so uncheck the nullable box).
3. Click the "edit" button next to the new `user_sensitive_profile_id` column.
4. An error page appears, preventing the user_id column from being edited.

Here is the error:

![Screen Shot 2019-06-03 at 7 43 42 AM](https://user-images.githubusercontent.com/12599934/58811116-0ed65800-85d4-11e9-955e-23d344c0468a.png)

Additionally, here is a reproduction I created using the "deploy to heroku" button in the docs. Feel free to do whatever you want with the reproduction, but I'll be deleting it in about a week: https://hasura-issue-2314.herokuapp.com/console/data/schema/public/tables/user_email_addresses/modify

- Clicking the `edit` button next to `user_sensitive_profile_id` should throw an error

**Comment by rikinsk** [comment]
This seems to be happening for UUID type columns if citext extension is installed
