### ISSUE TITLE
bug/feature: nested mutation with a circular foreign key dependency

### ISSUE THREAD

**Issue by thefliik** [hasura/graphql-engine#2315]
Not sure if this is a feature request or a bug report.

I'm having trouble inserting a nested mutation with a circular foreign key dependency (document A has a foreign key dependency on document B which has a foreign key dependency on document A).

The schema:

```graphql
type user_profile {
  id: UUID!
  user_sensitive_profile_id: UUID!

  user_sensitive_profile: user_sensitive_profile! # from user_profile.user_sensitive_profile_id
}

type user_sensitive_profile {
    id: UUID!
    primary_user_email_address_id: UUID!

    primary_user_email_address: user_email_address! # from user_sensitive_profile.primary_user_email_address_id
    user_email_addresses: [user_email_address!]! # from user_email_address.user_sensitive_profile_id
}

type user_email_address {
  id: UUID!
  user_sensitive_profile_id: UUID!
  email_address: String!

  user_sensitive_profile: user_sensitive_profile! # from user_email_address.user_sensitive_profile_id
}
```

A `user_profile` has a single `user_sensitive_profile`. A `user_sensitive_profile` has one or more `user_email_addresses`, of which one is marked as the `primary_user_email_address`.

The following nested mutation fails:

```graphql
mutation {
  insert_user_profiles(objects: {
    user_sensitive_profile: {
      data: {
        primary_user_email_address: {
          data: {
          	email_address: "bob@email.com",
          }
        }
      }
    }
  }) {
    returning {
      id
      user_sensitive_profile {
        id
        primary_user_email_address {
          id
          email_address
        }
        user_email_addresses {
          id
          email_address
        }
      }
    }
  }
}
```

The error:

```bash
"Not-NULL violation. null value in column \"user_sensitive_profile_id\" violates not-null constraint"
```

It appears that `user_profile.user_sensitive_profile.primary_user_email_address.user_sensitive_profile_id` is not being set.

I think the challenge is that `user_sensitive_profile` requires a `primary_user_email_address_id` as a foreign key and `user_email_address` requires `user_sensitive_profile_id` as a foreign key creating a circular dependency. To address this issue, I manually altered the `user_email_addresses` table so that the `user_sensitive_profile_id` foreign key constraint is `DEFERRABLE INITIALLY DEFERRED`, however the error is still appearing.

It does not appear that Hasura is setting the `user_sensitive_profile_id` value. I imagine Hasura is not aware that setting the `user_sensitive_profile.primary_user_email_address` relation should also add the `user_email_address` to the `user_sensitive_profile.user_email_addresses` array.

**Comment by thefliik** [comment]
I may have mis-diagnosed this issue.

I was able to work around this issue by setting all foreign key constraints to `DEFERRABLE INITIALLY DEFERRED` and manually specifying UUID values. I believe this solution only works if someone is using UUID values for ids rather than incrementing integers.

The working query:

```graphql
mutation {
  insert_user_profiles(objects: {
    id: "74770b77-ff95-4505-abf9-31fd1e6cbc04"
    user_sensitive_profile: {
      data: {
	  id: "5a0ba27a-a6f1-489e-9ef7-115854a42934",
          user_profile_id: "74770b77-ff95-4505-abf9-31fd1e6cbc04",
          primary_user_email_address: {
            data: {
	      user_sensitive_profile_id: "5a0ba27a-a6f1-489e-9ef7-115854a42934",
              email_address: "bob@email.com",
            }
          }        
       }
    }
  }) {
    returning {
      id
      user_sensitive_profile {
        id
        primary_user_email_address {
          id
          email_address
        }
        user_email_addresses {
          id
          email_address
        }
      }
    }
  }
}
```

Importantly, I was also forced to manually specify `user_sensitive_profile.user_profile_id`, even though it is not a circular dependency.

_The `user_profiles`, `user_sensitive_profiles`, and `user_email_addresses` tables each have non-nullable constraints on the foreign keys._

I was under the (perhaps mistaken) impression that Hasura would automatically set foreign keys when performing a nested mutation, but when I try and rely on automatically set foreign keys I receive a `Not-NULL violation`.

**Comment by thefliik** [comment]
It's possible this issue is actually the same as #2337. If/when #2337 is fixed, it's worth seeing if it also fixes this issue.

**Comment by 0x777** [comment]
@thefliik Can you post your sql schema for the tables that are involved and also the relationships?

**Comment by thefliik** [comment]
@0x777 I can but I've become convinced that this issue is actually the same as #2337 (which includes a schema / reproduction). This issue was complicated by the circular foreign key dependency, which I've come to realize is a feature request. I'm going to create a new issue focused on that feature request.

**Comment by thefliik** [comment]
I added a feature request for the circular foreign key dependency, along with a sql schema, here: #2345.
