### ISSUE TITLE
Using variables destroys performance

### ISSUE THREAD

**Issue by wooque** [hasura/graphql-engine#2316]
Query without variables:
```
{
  user_news(where: {user_id: {_eq: 1}, status: {_eq: 0}}, limit: 10, order_by: {id: desc}) {
    id
  }
}
```
Throughput: **3800** req/s

Query with variables:
```
query($user:Int, $status: Int){
  user_news(where: {user_id: {_eq: $user}, status: {_eq: $status}}, limit: 10, order_by: {id: desc}) {
    id
  }
}
```
Variables:
```
{
  "user":1,
  "status":0
}
```
Throughput: **980** req/s

In more complex example where I first noticed this performance drop it went from ~1500req/s to ~250req/s.

**Comment by 0x777** [comment]
Use non nullable variables. The query plan caching kicks in when all the variables are non-nullable scalars. 

```graphql
query($user:Int!, $status: Int!){
  user_news(where: {user_id: {_eq: $user}, status: {_eq: $status}}, limit: 10, order_by: {id: desc}) {
    id
  }
}
```

**Comment by 0x777** [comment]
Also, if you can spare more than one core to graphql-engine, you can set `GHCRTS` environment variable to `-N` (uses all available cores, you can restrict it by `-N<n>`, like `-N2`).

**Comment by wooque** [comment]
Yep, non nullable variables brought it to 90+% of non variable query performance.
This should really be in documentation because it will byte a lot of people, I didn't even know that variables could be nullable, let alone that there is big difference in performance.

The trick with with `GHCRTS` also improved performance for quite a bit, I'm surprised it's not default

**Comment by 0x777** [comment]
>  This should really be in documentation because it will byte a lot of people, I didn't even know that variables could be nullable, let alone that there is big difference in performance.

We'll add this to documentation. 

> The trick with GHCRTS also improved performance for quite a bit, I'm surprised it's not default

Historical reasons. We'll set it as the default in the next release.

**Comment by wooque** [comment]
Thanks. I would leave this open as reminder
