### ISSUE TITLE
Decent support of hstore and geometry data types

### ISSUE THREAD

**Issue by sfkeller** [hasura/graphql-engine#2324]
I'm submitting a feature request, newest Hasura version.

I'd like to make a query which is typical for a database derived from OpenStreetMap and I've read the issues, the docs and made several tests without success so far.

Prerequisites: PostgreSQL 11 and PostGIS 2.5. Datatype hstore requires "CREATE EXTENSION hstore;" and geometry/geograph requires "CREATE EXTENSION postgis;" .

The OSM/PostGIS dataset can be generated using https://wiki.openstreetmap.org/wiki/Osm2pgsql#Installation with a OSM PBF file (e.g. Switzerland) from http://download.geofabrik.de/ . The resulting schema in PostgreSQL contains among others a table planet_osm_point (short: osm_point) and the attributes tags (type hstore), and attribute geom (type geography or geometry).

Let's say we want to get all bakeries in Uster (Switzerland) and a resultset in GeoJSON containing osm_id, name, street and geometry.

This is a solution in SQL (Query with PostgreSQL/PostGIS): 
```sql
with boundary as ( -- bbox of Uster 
	select st_geomfromtext('POLYGON((8.677501 47.383873, 8.760421 47.383873, 8.760421 47.320153, 8.677501 47.320153, 8.677501 47.383873))',4326) as geom
)
select osm_id, name, tags->'addr:street' as street, geom 
from osm_point
where name is not null
and (tags->'shop') = 'bakery'
and st_intersects(geom, (select geom from boundary))
--and st_within(geom::geometry, (select geom from boundary)::geometry)
```

This is the GraphQL query I think which would come close to what we want:

Query:
```
query osm_point($boundary: geometry){
  osm_point(
    where: {
      name: {_is_null: false},
      tags: {_contains: {"shop": "bakery"}},
      geom: {_st_within: $polygon}
    }
  ){
    id
    name
    tags  # want not all kv pairs only value_of (tags->'addr:street'): how?
    geom
  }
}
```

Query variables:
```
{
  "boundary": {
    "type": "Polygon",
    "coordinates": [
      [
        [8.677501,47.320153],
        [8.760421,47.320153],
        [8.760421,47.383873],
        [8.677501,47.383873],
        [8.677501,47.320153]
      ]
    ]
  }
}
```

This is a typical GeoJSON dataset containing bakeries in Uster: [uster_bakeries_geojson.txt](https://github.com/hasura/graphql-engine/files/3249434/uster_bakeries_geojson.txt)

**Comment by 0x777** [comment]
The support for `hstore` is no where near to what we have for `json(b)` columns. The query above is possible currently if `tags` is of `jsonb` type instead of `hstore`.

**Comment by sfkeller** [comment]
Ok. Can you give me a correct query given my GraphQL example above? 

Did you see the SQL projection clause and the remark in the the output section of my GraphQL query there?
```
    tags  # want not all kv pairs only value_of (tags->'addr:street'): how?
    geom
```
I'd like to output not the whole tags (hstore or json) but only the addr:street value. Similar to this SQL projection in OSM many POIs (including bakeries) are either captured as point or as polygon (OSM area). So in order to union those polygons with the points one can apply st_centroid. So the above query would looke something like this: 
```
query osm_polygon($boundary: geometry){
  osm_polygon(
    where: {
      name: {_is_null: false},
      tags: {_contains: {"shop": "bakery"}},
      geom: {_st_within: $polygon}
    }
  ){
    id
    name
    _value_of: 'addr:street'  # correct?
    _st_centroid: geom  # correct?
  }
}
```

**Comment by 0x777** [comment]
>     tags  # want not all kv pairs only value_of (tags->'addr:street'): how?

```graphql
query osm_polygon($boundary: geometry){
  osm_polygon(
    where: {
      name: {_is_null: false},
      tags: {_contains: {"shop": "bakery"}},
      geom: {_st_within: $polygon}
    }
  ){
    id
    name
    tags(path: ".addr.street")
  }
}
```
> So in order to union those polygons with the points one can apply st_centroid.

You can't do this directly in the graphql api that we expose. Views are a perfect fit for this (we are also adding support for computed columns which will make this better). You can define a view as follows:

```sql
create view osm_point_view as
select
  osm_id,
  name,
  tags -> 'addr:street' as street,
  tags -> 'shop' as shop,
  geom,
  st_centroid(geom) as centroid
from
  osm_point
```

and then query the view as follows:

```graphql
query osm_polygon($boundary: geometry){
  osm_polygon_view(
    where: {
      geom: {_st_within: $polygon}
      shop: {_eq: "bakery"}
    }
  ){
    osm_id
    name
    street
    centroid
  }
}
```

**Comment by 0x777** [comment]
@sfkeller Hasura has no understanding that the response is needed as a `FeatureCollection`. We can only return a GeoJSON representation for columns of type geography/geometry. If you need such customisation you have two options:
1. Custom functions: https://docs.hasura.io/1.0/graphql/manual/queries/custom-functions.html
2. Remote schemas: https://docs.hasura.io/1.0/graphql/manual/remote-schemas/index.html

Please feel free to open a feature request for supporting feature collections.

**Comment by marionschleifer** [comment]
I'm closing this. @sfkeller feel free to re-open if you have any more questions or want to add anything else 🙂
