### ISSUE TITLE
Authorization based on roles table

### ISSUE THREAD

**Issue by natvaldev** [hasura/graphql-engine#2328]
Is it possible to set the permission for a certain table (`posts` for instance)
using a different table instead the dynamic headers on the request?

For example, testing the user `status` from `users` table when querying `posts`.

**Comment by thefliik** [comment]
The docs describe how to do this: https://docs.hasura.io/1.0/graphql/manual/auth/authorization/permission-rules.html#using-relationships-or-nested-objects

**Comment by rikinsk** [comment]
Might be related to #2297

**Comment by rikinsk** [comment]
@natvaldev Can you share more details on the behaviour you would expect

**Comment by marionschleifer** [comment]
I'm closing this. @natvaldev if you have further questions or would like to add more details, please feel free to re-open this issue 🙂
