### ISSUE TITLE
CLI console subscriptions connect via WS instead of WSS on HTTPS/WSS Endpoints

### ISSUE THREAD

**Issue by respectTheCode** [hasura/graphql-engine#2330]
I have a hasura server running behind Traefik and configured to require HTTPS/WSS connections. In Chrome the console works correctly, in Safari queries and mutations work but subscriptions don't connect.

**Comment by ecthiender** [comment]
@respectTheCode do you see any error in the network tab (of developer console) ? Can you paste the error if any?

**Comment by respectTheCode** [comment]
Yeah the error is the 301 because it is connecting to ws:// instead of wss://

```WebSocket connection to 'ws://graphql.xxx/v1/graphql' failed: Unexpected response code: 301```

**Comment by rikinsk** [comment]
@respectTheCode We could not reproduce this on our end. The calls via Safari seem to be being made with the `wss` protocol as expected. Can you confirm if your GraphQL API endpoint is also `https`

![Screenshot from 2019-06-11 14-49-54](https://user-images.githubusercontent.com/153602/59259918-425e5580-8c58-11e9-83ee-b23dc28ec6a0.png)

**Comment by respectTheCode** [comment]
The endpoint is https but it looks like both chrome and safari are connecting to `ws://`. The difference appears to be that chrome is following the 301 redirect and safari is not.

I am starting the client with ```hasura console --endpoint https://graphql...```

![image](https://user-images.githubusercontent.com/610704/59294120-88ee8880-8c35-11e9-91a1-8647f6f0f707.png)

**Comment by rikinsk** [comment]
@respectTheCode Thanks for the extra information. I could reproduce this on the CLI console. We'll fix this soon.

**Comment by rikinsk** [comment]
Expected behaviour:
If GraphQL endpoint is `http`, protocols used should be `http  / ws`
If GraphQL endpoint is `https`, protocols used should be `https  / wss`
