### ISSUE TITLE
[Event Triggers] HTTP 201 'created' response has negative status icon in logs

### ISSUE THREAD

**Issue by johnrees** [hasura/graphql-engine#2335]
If the HTTP response code of a webhook is [201](https://httpstatuses.com/201), it shows a negative red cross icon in the Invocation Logs table.

Perhaps all `HTTP 2xx` status codes should show a positive green check icon?

e.g. first row returned a 200, the second returned a 201

![Screenshot 2019-06-05 at 2 24 15 PM](https://user-images.githubusercontent.com/601961/58959832-cff3fe00-879d-11e9-9859-d280293cbfb9.png)

**Comment by tirumaraiselvan** [comment]
True!

Thanks for reporting! We will fix ASAP.
