### ISSUE TITLE
docker-compose-postgis SQL Execution Failed on Win 10

### ISSUE THREAD

**Issue by scheung38** [hasura/graphql-engine#2336]
SQL:

CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;

Returns 

postgres-error: could not open extension control file
"usr/share/postgresql/11/extension/postgis.control": No such file or directory

**Comment by ecthiender** [comment]
@scheung38 what is the docker image you are using in your docker-compose file? The default [postgres image](https://hub.docker.com/_/postgres) does not have Postgis extension.

Use this image instead https://hub.docker.com/r/mdillon/postgis/

**Comment by marionschleifer** [comment]
@scheung38 is your question answered? If yes, we can close the issue 🙂

**Comment by marionschleifer** [comment]
I will close this issue. @scheung38 feel free to re-open if you would like to add something.
