### ISSUE TITLE
Apollo client and __typename

### ISSUE THREAD

**Issue by plmercereau** [hasura/graphql-engine#234]
Hello Hasura team!
First of all, many thanks and congrats on the wonderful work you did to deliver his engine (and of course your platform!)
I am running a cluster on v0.15.34 and try to connect to the data graphql endpoint (running on graphql-engine then).
I cannot run a query with '__typename' in it, for example:
```
query Profile {
  profile {
    id
    first_name
    __typename
  }
}
```

it sends me back that I have no permission to access '__typename' column:
```
{
  "errors": [
    {
      "path": "$[0].args.columns[2]",
      "error": "no such column exists : \"__typename\"",
      "code": "permission-denied"
    }
  ]
}
```
I assume the use of __typename is not implemented, but this is a big problem to me, as the entire apollo case system relies on the use of this property...
Have I missed something? If not, any plan to add this into your product?
Once again, many thanks for this project, I dreamt of it and you are making it real!

**Comment by plmercereau** [comment]
That is great news! I was actually wondering how to upgrade / know the version of graphql-engine that is embedded in the platform. Looking forward!
I'd rather wait for it instead of swapping to a standalone graphql-engine, as there are very interesting features, e.g. your auth microservice that works perfectly with a Vue microservice. Btw, I plan to share a template in the hub that integrates Vue, Apollo, Hasura auth and data MS, most likely in September as I will be out for the next 6 weeks.
Other technology I found in love over the past weeks: jenkins-x. I am dreaming about taking advantage of both Hasura platform and gql engine, and jenkins-x CI/CD and their elegant way of generating environment on-the-fly GitOps mode.... Definitely above my skills to contribute, though.
Thanks for your prompt reply, and good luck with your products full of promises!

**Comment by shahidhk** [comment]
@plmercereau Hasura Platform v0.16.1 packs the latest release GraphQL Engine. Here is the guide to upgrade: https://docs.platform.hasura.io/0.15/platform/manual/migration-v0_16/index.html

Let me know if you have any questions.

**Comment by plmercereau** [comment]
Great! Thanks for this @shahidhk !
