### ISSUE TITLE
feature: reference objects created by a mutation from within the mutation

### ISSUE THREAD

**Issue by thefliik** [hasura/graphql-engine#2345]
Take the following schema with a circular foreign key dependency: the `people` table has a column with a `NOT NULL` foreign key to the `addresses` table, and the `addresses` table has a column with a `NOT NULL` foreign key to the `people` table:

```sql
CREATE TABLE "people" (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  primary_address_id uuid NOT NULL,

  name text
);

CREATE TABLE addresses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id uuid NOT NULL REFERENCES "people" ("id") ON DELETE CASCADE,
  street text,
  city text
);

ALTER TABLE people ADD CONSTRAINT people_primary_address_id_fkey FOREIGN KEY (primary_address_id)
  REFERENCES addresses (id) ON DELETE RESTRICT;
```

Currently, in this situation, there is not a way to have graphql-engine automatically populate `id` values in a nested mutation. i.e. the following query will fail:

```graphql
mutation {
  insert_people(objects: [{
    name: "Bob",
    addresses: {
      data: [
        {
          street: "123 Awesome Street",
          city: "Amazing City"
        }
      ]
    },
    primary_address_id: ????
  }]) {
    returning {
      id
      name
      primary_address {
        id
      }
      addresses {
        id
        street
        city
      }
    }
  }
}
```

in order to make this query work, you must use `uuid` ids and the client must manually supply ID values (which in my case, is not a problem).

A "nice to have" feature would be the ability to somehow get that `primary_address_id` field auto-populated.

**Comment by thefliik** [comment]
I've learned that this is a postgres limitation: non-null circular foreign keys are not supported:
- https://dba.stackexchange.com/questions/102903/is-it-acceptable-to-have-circular-foreign-key-references-how-to-avoid-them

Given that the only use case I have for this feature request was concerning circular foreign keys, I'll close this issue.

**Comment by bartenra** [comment]
It is actually possible: https://blog.sql-workbench.eu/post/cyclic-foreign-keys/

I had to modify the constraint manually to make it possible and generate the UUID client side (as you say):

```
ALTER TABLE enra.expo_translation ALTER CONSTRAINT expo_translation_expo_fkey DEFERRABLE INITIALLY DEFERRED;
```
