### ISSUE TITLE
How to decide 'Role' in webhook?

### ISSUE THREAD

**Issue by roytan883** [hasura/graphql-engine#236]
Graphql-engine only pass `HEADERS` to webhook server,  how can i decide which ROLE to return? 

Let's assume `uid-3` is `MANAGER` role in `todo` table, and `USER` role in `comments` table. The HTTP only has `access-token` header which parse to valid `uid-3`.  At webhook server side can't know this request is access to `todo` table or `comments` table, which ROLE should i return?
```http
HTTP/1.1 200 OK
Content-Type: application/json

{
    "X-Hasura-User-Id": "uid-3",
    "X-Hasura-Role": "???"
}
```

**Comment by shahidhk** [comment]
@roytan883 Your auth system should be able to resolve a token to user id and role. When a user signup/login etc. you should save the role information with the auth system.

What auth-provider are you using here?

**Comment by 0x777** [comment]
@roytan883 How is the role determined for a table given an authorization token?

**Comment by roytan883** [comment]
@0x777 for example：
In `todo` table, if `managerId ==  userId`, then ROLE is  `MANAGER `
In `comments`, if `authorId == userId`, then ROLE is `USER`

The problem is that at `webhook server`, it don't know the `query` target is `todo` or `comments`. Because the query is inside `HTTP POST body` which not pass to `webhook server`. Graphql-engine only pass `HEADERS` by `GET` to `webhook server`

**Comment by roytan883** [comment]
Do i need add `X-Hasura-Target-Table` to `HTTP Headers` ? 
It looks strange, but i can't find a way let `webhook server` know which `table` is requested.

**Comment by 0x777** [comment]
Another quick question before I can answer this. Does the manager role have access across tables or only the `todo` table?

**Comment by roytan883** [comment]
only for `todo` table

**Comment by 0x777** [comment]
You can send `X-Hasura-Role`, the role with which you are trying to execute the query from the client. Now your webhook has `Authorization` token and the `X-Hasura-Role`. Check if the token is valid, resolve it to user-id and check if this user-id can make a request as this role. 

```json
{
    "X-Hasura-User-Id": "uid-3",
    "X-Hasura-Role": "X-Hasura-Role from client"
}
```

The permissions on the `todo` table for `manager` role can be as follows:
select:
filter: ```{ "managerId" : "x-hasura-user-id" }```

The permissions on the `comments` table for `user` role can be as follows:

filter: ```{ "authorId" : "x-hasura-user-id" }```

**Comment by roytan883** [comment]
what if the `query` is mixed? like this:
```
{
  getTodo(id:"abc") {
    id
    title
  }
  getComments(id:"def"){
    id
    body
  }  
}
```

**Comment by roytan883** [comment]
BTW, is the `admin` ROLE default ? means if not provide ROLE define, any operation is allowed? How to disable it ?

**Comment by 0x777** [comment]
Currently you can't execute different fields of a query with different roles. We are working to improve this experience. 

The only case where admin role is assumed as default is when **both** access key and webhook modes are **not** configured (dev environments). 

If you have configured a webhook, you'll need to return an x-hasura-role  (no defaults will be assumed and an error will be raised if it is not found).

**Comment by shahidhk** [comment]
@roytan883 please re-open if you have further questions.
