### ISSUE TITLE
Allow/limit related object insert

### ISSUE THREAD

**Issue by jjacobson93** [hasura/graphql-engine#2370]
I have similar use-case to the one described [here](https://docs.hasura.io/1.0/graphql/manual/mutations/multiple-mutations.html#insert-an-object-and-a-nested-object-in-the-same-mutation). I have a `projects` table and a `members` table where each member has a specific role in the project. Only an owner/admin role can add new members to the project.

The issue is I want to create a `member` with the current user ID and "owner" role when a `project` is created. If I add insert permissions to only allow owners/admins to add subsequent members, then it will prevent a user from adding themselves as an owner to a new project.

The permissions logic is something as follows:
```json
{
  "_and": [
    {
      "project": { "members": { "user_id": { "_eq": "X-Hasura-User-Id" } } }
    },
    {
      "project": { "members": { "role": { "_in": ["owner", "admin"] } } }
    }
  ]
}
```

I essentially need some condition that checks if the the project is "new" and allow the owner member to be created with the project.

**Comment by rikinsk** [comment]
@jjacobson93 This seems like something that should be possible. Can you share some more information on your tables structure and relationships along with the final query you plan to execute to create the projects and members. It would help to have a more precise discussion and solution.

**Comment by jjacobson93** [comment]
The projects table:
```sql
CREATE TABLE public.projects (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    title text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
```

The users table:
```sql
CREATE TABLE public.users (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    email text NOT NULL,
    password text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
```

And the project members:
```sql
CREATE TABLE public.project_members (
    user_id uuid NOT NULL,
    project_id uuid NOT NULL,
    role text DEFAULT 'member'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
```

The mutation is this:
```graphql
mutation {
    insert_projects(objects: {
        title: "Test",
        members: {
            data: { role: "owner", user_id: "9c973c1b-d54a-4957-a04b-16a87a918c7d" }
        }
    }) {
        affected_rows
    }
}
```

**Comment by rikinsk** [comment]
@jjacobson93 This is the permission rule you need. Its a little complicated so bear with me while I try to explain the logic below.
```json
{  
   "_or":[  
      {  
         "_and":[  
            {  
               "user_id":{  
                  "_eq":"X-Hasura-User-Id"
               }
            },
            {  
               "_not":{  
                  "project":{  
                     "members":{  
                        "role":{  
                           "_in":[  
                              "admin",
                              "owner"
                           ]
                        }
                     }
                  }
               }
            }
         ]
      },
      {  
         "project":{  
            "members":{  
               "_and":[  
                  {  
                     "user_id":{  
                        "_eq":"X-Hasura-User-Id"
                     }
                  },
                  {  
                     "role":{  
                        "_in":[  
                           "admin",
                           "owner"
                        ]
                     }
                  }
               ]
            }
         }
      }
   ]
}
```
This translates to:

Allow inserting into members table if:

The `user_id` of the `member` being inserted is the same as the `request-user-id` **AND** the member's `project ` does not have any `member` yet with `role` admin or owner (ie: project has no owner/admin and request user is inserting themself as member)

**OR**  

The `project` of the `member` being inserted has another `member` that has `user_id` same as the `request-user-id` **AND** has ``role`` admin or owner (ie: request user is admin/owner)

Hope this made sense

**Comment by jjacobson93** [comment]
Thank you, @rikinsk! This works perfectly. Closing this issue.
