### ISSUE TITLE
Add names to `hasura migrate status` command output

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#2376]
The output for this command currently lists the version, database and source status. It would be nice if it showed the name of migration as well.

**Comment by macalinao** [comment]
this would be amazing if implemented!

**Comment by gagandeepp** [comment]
assign this to me

**Comment by marionschleifer** [comment]
@gagandeepp done 🙂 let us know if you have any questions.

**Comment by gagandeepp** [comment]
how to run migrations??

**Comment by marionschleifer** [comment]
@gagandeepp you can read all about migrations in our docs: https://docs.hasura.io/1.0/graphql/manual/migrations/index.html.
