### ISSUE TITLE
improve logging for webhook errors

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#238]
`{"errors":[{"path":"$","error":"HTTP Exception from Webhook","code":"unexpected"}]}` is not really useful to identify what is wrong.

The above error message was thrown when the address was not reachable.

Expected to see `localhost:3000, connection refused` or something similar

[via moe on discord]

**Comment by moedusa** [comment]
Also it would be nice if you could see webhook url from the error message (to match against url from the config e.g. when you forgot to restart docker after changing webhook url or smth.)

**Comment by shahidhk** [comment]
@moedusa Better logging for webhook errors, including url and response body have been included in `v1.0.0-alpha12`
