### ISSUE TITLE
While writing custom sql function I want to pass array as parameter. I could not figure out if it is supported and if it supported what type should I use.

### ISSUE THREAD

**Issue by ajit-hi** [hasura/graphql-engine#2381]
CREATE FUNCTION search_cities(queue  int ARRAY)
RETURNS SETOF cities AS $$
    SELECT * FROM cities where id IN queue

$$ LANGUAGE sql STABLE;

What should i replace int ARRAY with

**Comment by leoalves** [comment]
Hi @ajit-hi,

I know this was not your question.  But maybe you don't know.  This is supported by default in Hasura.

`
query {
  cities (where: {id: {_id: [1,2,3,4,5]}}) {
    id
    name
  }
}
`

If you already knew that.  And you can only solve your issue with a function. My apologies.

Here is how you would solve it with a function.

SQL to create the function

`
CREATE FUNCTION public.search_cities(queues INT[])
RETURNS SETOF public.cities AS $$
SELECT * FROM public.cities where id = ANY(queues);
$$ LANGUAGE sql STABLE;
`
and your query should be something like:

`
query {
  cities (where: {id: {_id: '{1,2,3,4,5}'}}) {
    id
    name
  }
}

`

**Comment by ajit-hi** [comment]
Thank you @leoalves .  I'm now able to pass arrays as arguments to custom functions.
