### ISSUE TITLE
Console: edit icon is unclickable when assets are not loaded

### ISSUE THREAD

**Issue by ajeetdsouza** [hasura/graphql-engine#2389]
![image](https://user-images.githubusercontent.com/1777663/59662947-9ffc2000-91cb-11e9-96e2-5c906564f11a.png)

The "edit" action for changing table name and adding a comment uses a simple icon, which is unclickable when assets are not loaded. It would be much better if this was changed to a button, which would remain visible even without the loaded assets.

**Comment by strongSoda** [comment]
This is related to this #2198

**Comment by rikinsk** [comment]
Closing in favour of #2198
