### ISSUE TITLE
add custom names to root level types

### ISSUE THREAD

**Issue by cwartel** [hasura/graphql-engine#241]
Hi,
Great product and service you are building there,
https://docs.hasura.io/1.0/graphql/manual/queries/index.html says : 

> ...query and insert/update/delete mutations each are added as nested fields under the root level types, query_root and mutation_root respectively.

Is there a way to configure/change those type names for "Query" and "Mutation" as some graphql consuming projects rely on those naming conventions ?

Thanks for your answer

**Comment by 0x777** [comment]
You would like to change the names `query_root` and `mutation_root` to something else? The GraphQL spec doesn't enforce any restrictions what these type names should be. Can you point us to a project where this is causing an issues? We can definitely add a couple of command line flags to change this.

**Comment by cwartel** [comment]
Thanks for your answer,
I'm trying to plug hasura and https://github.com/wittydeveloper/react-apollo-form/
That tool parses the schema on the assumption that mutations root type is named "Mutation".
See here : https://github.com/wittydeveloper/react-apollo-form/blob/88f7ca37a56c15d9f150a4a2f3cc06178ad9e4fb/lib/forms/definitions.ts#L38

**Comment by 0x777** [comment]
Okay. We'll add `--query-root-name`, `--mutation-root-name`, `--subscription-root-name` flags to the server.

**Comment by cwartel** [comment]
Great thing :+1:  thanks

**Comment by cwartel** [comment]
Hi Vamshi,
To get a glimpse on this, could you tell me rough steps to implement renaming hard coding it ?
I've located where those root names are defined : https://github.com/hasura/graphql-engine/search?q=mutation_root&type=Code
But I cant see what I need to do to get to a modified docker version of graphql-engine. How do I go from code modification to a running docker version of hasura ?
Thanks in advance

**Comment by 0x777** [comment]
You can cd into the server directory and run `make image`. A fair warning, this step will download a docker image which is 2-3 GB and the compilation could take a while.

**Comment by coco98** [comment]
@cwartel I completely forgot to mention if you make a change and then submit a PR you’ll get a build and a sample heroku app deployed automatically that you can test with! And of course the docker image gets built too once the tests pass automatically

Do try it out and let me know if you need help!

**Comment by cwartel** [comment]
Hi Tanmai I'll do it the PR way as I had no success building from source as Vamshi suggested

**Comment by rwoody** [comment]
For anyone that comes here for the error `query_root must define one or more fields`, I received this because the admin authorization header is not set for the GraphQL Playground after running `hasura api-console`. I grabbed the admin token from local storage and put it in the `Authorization: Bearer <token>` header.

**Comment by dilame** [comment]
Cant connect my angular app with apollo to hasura because of this issue

**Comment by marionschleifer** [comment]
@dilame This issue is something we would like to pick up and we are figuring out its priority 🙂

**Comment by BrianHung** [comment]
If anyone is using `@apollo/client` and would like to make re-usable fragments for top-level queries, mutations, subscriptions, you can work around hasura by configuring the apollo cache settings to support this: https://www.apollographql.com/docs/react/caching/cache-configuration/#overriding-root-operation-types-uncommon. 

I was initially confused because in general, graphql supports top-level fragments, but the **root names have to match up between hasura and apollo**.

For example, the following will give you a correct _network_ response: if you pop open the network tab in dev tools, you will find the data returned is correct.

```js
export const post_by_pk_fragment = gql`
  fragment PostsByPk on query_root {
    posts_by_pk (post_id: $post_id) {
      ...PostFragment
      doc_state
    }
  }
  ${post_fragment}
`

export const GET_POST_BY_POST_ID_AND_LIKE = gql`
  query MyQuery ($post_id: uuid!, $signed_in: Boolean!, $user_id: uuid!) {
    ...PostsByPk
    likes_by_pk (post_id: $post_id, user_id: $user_id) @include (if: $signed_in) {
      ...LikeFragment
    }
  }
  ${post_by_pk_fragment}
  ${like_fragment}
`;
```

However, without changing the expected `__typename` for the query root in the apollo cache settings, apollo would not find the data

```js
// posts_by_pk would be null even though network response contains posts_by_pk
const {error, data: {posts_by_pk}} = client.query({...})
```

as it expects "Query" to be the name of the query root instead of "query_root".

```js
// https://www.apollographql.com/docs/react/caching/cache-configuration/#overriding-root-operation-types-uncommon
const inMemoryCacheOptions = {
  typePolicies: {
    query_root: {
      queryType: true,
    },
    mutation_root: {
      mutationType: true,
    },
    subscription_root: {
      subscriptionType: true,
    }
  }
}

const cache = new InMemoryCache(inMemoryCacheOptions);
const client = new ApolloClient({cache})
```

**Comment by ahmadalibaloch** [comment]
Update?

**Comment by kdawgwilk** [comment]
This is also an issue when trying to merge schemas together for apollo federation where hasura is a subgraph.  Using tools like graphql-codegen also expect these type names to line up so this breaks various community tools

**Comment by rahulagarwal13** [comment]
Hey @kdawgwilk  - can you please share more details about your schema (including samples) and setup config with us so that we can investigate the issue you are facing? Feel free to email us with the details for us to look into it. Thanks!

**Comment by kdawgwilk** [comment]
Details are in this issue with graphql-codegen https://github.com/dotansimha/graphql-code-generator/issues/8735

**Comment by rahulagarwal13** [comment]
got it thanks, will take a look and get back to you

**Comment by manasag** [comment]
Thanks everyone for your comments and patience on this issue. We have been closely listening into all the feedback and requests from the community, and have been working on a re-imagined, re-architectured Hasura, that tackles many of these from ground up.
We are pleased to announce that we are launching V3-Alpha of Hasura ([Data Delivery Network](https://hasura.io/ddn)) on our next Community call on Nov 30. 
The new metadata structure in V3 is designed to be highly flexible and declarative, to support the perfect GraphQL schema you would like to achieve. In V3, we provide the control to override autogenerated names and use any value as you need.
We would request to join this [community call](https://hasura.io/events/community-call/latest) to learn more about Hasura V3. Post launch, we will update this issue with relevant details.

**Comment by manasag** [comment]
This issue is already addressed in the new Hasura V3, hence closing this. Please follow the [guide](https://hasura.io/docs/3.0/getting-started/overview/) here for Alpha access to Hasura V3.
