### ISSUE TITLE
remake modify remote schemas page

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#2411]
The UI is totally different than rest of the console app.
It should either use editors like we do in ModifyTable and ModifyTrigger page, or a single current page that is already in editable mode (shouldn't need to click the modify button at the bottom of the page to toggle into the modify mode).

Suggestions are welcome @rikinsk @karthikvt26 @coco98 @dsandip

**Comment by rikinsk** [comment]
We should just enable the edit mode by default

**Comment by rikinsk** [comment]
Tracking via #1193
