### ISSUE TITLE
Support table_by_unique_constraint query

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#2418]
Currently, Hasura only supports `table_by_pk` query, which returns singular response.

Current feature request suggest adding `table_by_unique_constraint` query, which is similar to `table_by_pk` query.

Example:

```
users_by_email_and_code_unique_key(email:"test@test.com", code: "test_code"){
id
}
```
This query fetch single user by two fields (email and code), which is a unique constraint.

**Comment by rikinsk** [comment]
dup of #1606

**Comment by rikinsk** [comment]
CLosing this. Let's track the feature request at #1606
