### ISSUE TITLE
When you rename tables and columns, error messages still use their initial names

### ISSUE THREAD

**Issue by earslap** [hasura/graphql-engine#2420]
If you rename a table and / or a column, when you have errors, the engine sends error messages while referring them with their former (maybe only initial?) names. So for example this is an expected error:

```
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.insert_user.args.objects",
        "code": "constraint-violation"
      },
      "message": "Uniqueness violation. duplicate key value violates unique constraint \"auser_authprovider_id_key\""
    }
  ]
}
```

See "auser_authprovider_id_key"

In this case, auser table has been renamed to user and authprovider_id column is renamed to auth_id already but the error message refers to them with their old names.

**Comment by 0x777** [comment]
@earslap What you see in the error message is the constraint name, and when you rename a column, the constraint name doesn't change. You can drop the constraint and create it again.

**Comment by earslap** [comment]
Thank you I somehow missed that.
