### ISSUE TITLE
Pass through errors from remote join

### ISSUE THREAD

**Issue by sgrove** [hasura/graphql-engine#2433]
It seems that with remote joins, errors aren't propagated through in the result (I'll admit I'm not sure how to handle the `path` mapping here

**Comment by tirumaraiselvan** [comment]
@sgrove What's the docker version? Can you show the screenshot of the query and the response?

**Comment by marionschleifer** [comment]
@sgrove any update here? 🙂

**Comment by marionschleifer** [comment]
@sgrove I'm closing this. Feel free to re-open if you'd like to add anything 🙂
