### ISSUE TITLE
Hasura console doesnt shows error notifications in RUN SQL in CLI mode

### ISSUE THREAD

**Issue by fedorg** [hasura/graphql-engine#2438]
I'm running Hasura 1.0.0-beta.2
When I happen to run an invalid SQL statement, for example, the error notification never pops up. There are runtime errors in the console:
`Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 0`
which is caused by trying to read a `message` property on a JSON return object that doesn't exist.
This occurs in both latest Chrome and Firefox.

![image](https://user-images.githubusercontent.com/4352852/60254015-ce69b180-98d5-11e9-9392-e89d9524cc08.png)
![image](https://user-images.githubusercontent.com/4352852/60254081-eccfad00-98d5-11e9-87b3-2e80542a4989.png)
![image](https://user-images.githubusercontent.com/4352852/60254187-20123c00-98d6-11e9-8649-3a84cca9d881.png)

**Comment by rikinsk** [comment]
Could reproduce this in CLI mode

@fedorg Can you confirm if you were running the console via the CLI?

**Comment by fedorg** [comment]
Yes, this was running in the CLI mode (on Windows 10, in Git Bash)
