### ISSUE TITLE
Auth servers must return `X-Hasura-User-Id` even if doing so doesn't make sense

### ISSUE THREAD

**Issue by ndarilek** [hasura/graphql-engine#2442]
Getting the following error:

```
{"timestamp":"2019-06-27T18:44:04.850+0000","level":"info","type":"ws-handler","detail":{"event":{"type":"operation","detail":["3","import",{"type":"query_err","detail":{"path":"$","err
or":"\"x-hasura-user-id\" header is expected but not found","code":"not-found"}}]},"websocket_id":"cdb8bd0f-211b-419e-83a3-748b18edcc70","jwt_expiry":null,"msg":null,"user":{"x-hasura-role":"anonymous"}}}
```

I'm not clear on what's happening there, but my intent is for my auth server to just return `{"X-Hasura-Role": "anonymous"}`. There is no user ID for this particular endpoint.

I'm unclear on whether the auth server is expected to return `X-Hasura-User-Id`, or whether some permission in my anonymous role is requesting this variable. I did clone my permissions, but to the best of my knowledge I've removed all references to `X-Hasura-User-Id` from these checks.

Ideally, I could make it explicit that no user ID is associated with the anonymous role by not returning one. Then, any code or permissions checking for that variable would fail, and the crash/exception would highlight what specific sections of my code expect a user ID. For the moment, I'll work around this by returning an empty string, but learning whether this is a bug in my schema or a Hasura issue would be helpful.

Thanks.

**Comment by shahidhk** [comment]
@ndarilek That particular error is thrown when the query is trying to access a table for which, the permission rule contains a reference to `x-hasura-user-id`. Hence Hasura is saying that it needs the user-id parameter to decide whether to allow this query or not.

Can you confirm that the permission rule does not refer to `x-hasura-user-id`?

**Comment by ndarilek** [comment]
I had in fact been missing a rule on a related row. It would be nice if 
this error included the rule that failed. Initially I thought a mutation 
was failing, so spent lots of time clicking through mutation-related 
permissions on all my rows. Turns out it was a select permission on a query.

**Comment by 0x777** [comment]
@ndarilek Just to confirm, you don't need to provide any more session variables that what are required for the query/mutation. Closing this in favour of #2469
