### ISSUE TITLE
OpenCRUD Support

### ISSUE THREAD

**Issue by mcmar** [hasura/graphql-engine#2447]
My company ([Vibely](https://www.crunchbase.com/organization/vibely)) is looking to migrate away from Prisma because they're abandoning their current customers with Prisma2, which won't support any of the current functionality of Prisma1. The difficulty we have with migrating to Hasura is that the generated graphql API is very different from Prisma1. If the Hasura team is able to support creating an OpenCRUD compliant API, that would ease our migration path to Hasura and we'd be huge fans 🙏

**Comment by shahidhk** [comment]
Hi @mcmar, quoting our response from https://github.com/hasura/graphql-engine/issues/1358#issuecomment-456286941:
> The OpenCRUD spec currently is a work in progress and it'll not be easy for us to support something which might change in future. We may revisit this when there is a release of OpenCRUD to see if it's viable to implement the spec.

Also, closing in favor of https://github.com/hasura/graphql-engine/issues/1358.

**Comment by shahidhk** [comment]
@mcmar Feel free to ping us for any help in re-writing the queries, if at all you're planning to move to Hasura.

**Comment by mcmar** [comment]
@shahidhk
I don't think that's really a good answer because OpenCRUD isn't going to be iterated on by the Prisma team any more in the future since Prisma is officially abandoning GraphQL and will no longer support OpenCRUD. If you supported it, then I'm sure plenty of Prisma customers would move over to Hasura. Don't you want their business?

**Comment by mcmar** [comment]
@shahidhk If you're not going to support it, then can you at least provide examples of how to migrate from OpenCRUD with `prisma-binding` to HasuraCRUD™ with `graphql-binding`. I can setup all the tooling, but what I can't figure out is how to use the `info` object that's expecting a schema like `{ id, name }` with HasuraCRUD, which expects a schema like `{ returning { id, name } }`. I've never found a good tool to modify the info object, which means that I would have to modify my API's schema to also wrap everything inside `returning`, which would mean changing my frontend. I'd like to avoid changing the frontend, which means keeping my API schema the same, which means somehow wrapping/unwrapping the `info` object of my resolver with `returning`. If that's not possible, then there's no way for anybody to migrate smoothly from Prisma to Hasura.
