### ISSUE TITLE
Permissions for Remote Schemas

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#2461]
v1 (wip #2690):

Schema masking: Role-based types for `query_root`, `mutation_root` and `subscription_root` fields
Deep schema masking: Role-based type for anything (object type, input object type, scalars?). 

v2:

Input argument presets.

**Comment by leoalves** [comment]
Hi @tirumaraiselvan,

One idea, that I think would be easier, is to let the Remote Schema generate different schemas, for each role.

If Hasura sends the role, in the headers, when doing the introspection query.  The Remote Schema could return different schemas, based on each role.

I created an issue about that a while ago.
https://github.com/hasura/graphql-engine/issues/2139

**Comment by tirumaraiselvan** [comment]
@leoalves Cool, 1) is actually the exact duplicate of #2139 . 

I will let both these issues open and use this as an umbrella issue for remote schema permissions.

**Comment by bobberkarl** [comment]
Anything new regarding that?

**Comment by tirumaraiselvan** [comment]
@bobberkarl This is WIP currently. It would be great if you could explain some more details of what kind of permissions you expect for Remote Schemas. Does the description of this issue satisfy your use-cases?

**Comment by cjonestcgsi** [comment]
@tirumaraiselvan  Answering for a different company/use case.. In the case of an integration with Stripe - we would want to let a user see their own transactions and balance and certain status related details - such as the 'requirements' that Stripe may have for them, so we would want to query the remote schema using the stripe-customer-id, associated with the X-Hasura-User-Id, and to allow queries to certain tables and columns, where we force it to return results only for that particular stripe-customer-id.

**Comment by leoalves** [comment]
@cjonestcgsi 
I think the use case you explained will be solved with Remote Joins, when that gets released.
https://hasura.io/remote-joins

**Comment by tirumaraiselvan** [comment]
@cjonestcgsi leoalves is right. Remote joins allows you to join tables with remote data. So if you have access to only `stripe-customer-id` (which is `x-hasura-user-id`) then you will get joined data corresponding to only that. The strip use-case is also presented here: https://hasura.io/blog/remote-joins-a-graphql-api-to-join-database-and-other-data-sources/

**Comment by jacdx** [comment]
My use case is to extend the same header-based role permissions that I use across Hasura to my remote schema, which doesn't provide any usable access control other than CORS and tokens. I wish I could go into Data, see the entities from my Remote Schemas there, and be able to at least set high level query, mutation subscription permissions per entity. The closer it is to what Hasura does for it's own tables, the better.

**Comment by tirumaraiselvan** [comment]
@jacdx That's what we will aim to provide as well :)

**Comment by FickleLife** [comment]
Just wondering where this is sitting in the list of priorities? Thanks

**Comment by jorisw** [comment]
Will Remote Schema Permissions allow us to entirely hide part of our sub tree from public vs private clients (via roles)? We're trying to do this:

Roles
- Public consumer (i.e. a web app)
- Internal Service (non-Hasura GraphQL service)

Schemas to be unified:
- Internal Service A
- Internal Service B
- Internal Service C

Desired permissions:
- Internal services see the entire graph, unifying A, B, C's graphs
- Public consumers can only see the graph of Internal Service A
- Public consumers don't see anything Service B or C related when introspecting the graph
  - Therefore public consumers can't directly call operations on Service B or C

Will Remote Schema Permissions facilitate this? 
Or will Remote Schema Permissions only disallow _operations_ on a field level?

**Comment by tirumaraiselvan** [comment]
Remote schema permissions has been released in v2.0.0 (currently in alpha)
