### ISSUE TITLE
Remote Schema Tables Empty

### ISSUE THREAD

**Issue by cport1** [hasura/graphql-engine#2462]
After setting up a remote schema to onegraph, I can see the introspection working correctly. However, when I try to add a relationship to the remote schema, the tables are empty.

![image](https://user-images.githubusercontent.com/1678629/60531487-ba042b00-9cc0-11e9-9880-26d384ce834b.png)

**Comment by cport1** [comment]
I changed my docker image to pull2395-31a51dcd and now see the remote relationships UI which is different than what was in beta.

**Comment by tirumaraiselvan** [comment]
Just FYI, Remote Relationships is only available in preview. You can pick up the latest build from #2395
