### ISSUE TITLE
Hasura is not work offline

### ISSUE THREAD

**Issue by timeshift92** [hasura/graphql-engine#2477]
Hello, I have a weak internet and sometimes completely disconnects, so is it possible to make hasura work offline?

**Comment by shahidhk** [comment]
@timeshift92 If you're running a local docker image, you can follow this guide to load console assets from the docker image itself, instead of the CDN: https://docs.hasura.io/1.0/graphql/manual/deployment/graphql-engine-flags/config-examples.html#console-assets-on-server

**Comment by timeshift92** [comment]
thanks

**Comment by aislanmaia** [comment]
Since hasura is many times compared to firebase, is possible to Hasura offers offline out-of-box as firebase offers ?

**Comment by toanhonestbee** [comment]
@aislanmaia Firebase offline is under the hood a client SDK that store data cache in local storage. Hasura is a backend solution only, however, you can use Apollo client cache https://github.com/apollographql/apollo-cache-persist to do similar mechanism.

**Comment by hgiasac** [comment]
@aislanmaia Firebase offline is under the hood a client SDK that store data cache in local storage. Hasura is a backend solution only, however, you can use Apollo client cache https://github.com/apollographql/apollo-cache-persist to do similar mechanism.

**Comment by aislanmaia** [comment]
@hgiasac thanks for reply me. I wanting to use Hasura with Flutter, so I think Apollo is not in my rescue, unfortunately.

**Comment by shahidhk** [comment]
@aislanmaia Take a look at https://github.com/Flutterando/hasura_connect

**Comment by aislanmaia** [comment]
@shahidhk I mean something regarding offline capabilities. I know how to connect hasura + flutter.

**Comment by shahidhk** [comment]
The hasura_connect package above exposes certain caching capabilities which might come in handy in offline situations.

**Comment by aislanmaia** [comment]
Ah, I see.
