### ISSUE TITLE
Increase query limit from 25 to another higher value

### ISSUE THREAD

**Issue by bernardbaker** [hasura/graphql-engine#2479]
How can I increase the limit on a query of a table that contains more than 25 entries?

**Comment by shahidhk** [comment]
@bernardbaker Hasura does not enforce a limit by default. The response size is only limited only if a permission is set on that table for a particular user role. Can you check if the number of rows are limited in the permission rule?

**Comment by bernardbaker** [comment]
Hi, thanks for your reply. Where can I find the permission rule?

Regards,

Bernard T. A. Baker

**Comment by bernardbaker** [comment]
Hi again, maybe I can be more specific. I'm using the ra-data-hasura module
with React Admin as a UI.
I have a select control which should display all 52 options, but only
displays 25.

Any help would be appreciated...

Regards,

Bernard T. A. Baker

**Comment by bernardbaker** [comment]
Managed to resolve it. It was a component in `react-admin` that was causing the query to be capped at 25.

I added a `prop` to it with the higher value and it returned the correct results.

**Comment by shahidhk** [comment]
Glad that you figured it out @bernardbaker. Closing this issue now. :smile:
