### ISSUE TITLE
Can't do multiple operations on console after deleting all columns from a table through the Hasura console.

### ISSUE THREAD

**Issue by Rey1213** [hasura/graphql-engine#2481]
<h2>Bug</h2>
After deleting all the columns of a table through the console I:

- Can't do anything with the table which had all of its columns deleted
- Can't create new tables
- Can't modify other tables
- Can't check relationships. 

Each time I try I just get redirected to the error screen. 

<h2>Steps to Reproduce</h2>

**Hasura:** _v1.0.0-beta.2_
**PostgreSQL:** _v11.4_
**Provider:** _Heroku_

1. Create a Table through the Console
2. Create Columns for that Table through the Console
3. Delete all the Columns through the Console

**Comment by rikinsk** [comment]
When table has no columns, console gets the list of columns as `[null]` which breaks parsing. The columns should be `[]`
