### ISSUE TITLE
add action-style templating of webhook URL for event trigger and remote schemas

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#2483]
So far, when creating an event trigger and select a webhook url, we have the option to use environment variables but we cannot use string templates yet. Add support to be able to use string templates.

**Comment by tirumaraiselvan** [comment]
TBD:

1. What are the constraints on the template?

Do we allow `${WEBHOOK_BASE_DOMAIN}/hook-1` and also `http://something.com/${NAMESPACE}/hook-2`

2. What is the templating syntax? BASH like variable expansion?
So `${WEBHOOK_BASE_DOMAIN}/hook-3`

**Comment by flybayer** [comment]
I would very much appreciate this feature! Currently I'm adding a new env variable for every single event.

**Comment by carllippert** [comment]
+1 This would be an excellent addition for those heavily leaning on events and solve some of the whole metadata swaps people have been talking about to get around env var problems with migrations

**Comment by gunar** [comment]
**Alternative**: The payload includes `trigger.name` so you could point all events to a single endpoint and do the routing on the server side.

```js
if (payload.trigger.name === "user_added") {
  // ...
} else if (payload.trigger.name === "user_removed") {
  // ...
} else {
  throw Error("unexpected event");
}
```

**Comment by jchonde** [comment]
I would expect the webhook url to behave like the action's http handler. eg: `{{SERVICE_BASE_URL}}/my_endpoint`

**Comment by tirumaraiselvan** [comment]
Yes, making it consistent is definitely something that should be done. The `webhook` key in [event trigger APIs](https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/event-triggers.html#id1) can take a templated url, just like in Actions. 

Changing title to reflect this feature

**Comment by amille14** [comment]
@tirumaraiselvan is your last comments saying that this already exists for the `webhook` key for event triggers, or just that it is a planned feature? I need this feature as well to enable working with a vercel serverless api for my events. Having it work exactly like action webhook templated urls would be great.

When I tested it on v1.2.2 it didn't seem to work for events.

**Comment by rikinsk** [comment]
@amille14 This is not available now. Its a planned feature.

**Comment by sahanatroam** [comment]
similar issue: https://github.com/hasura/graphql-engine/issues/5090

**Comment by dan-lee** [comment]
@gunar That's a great workaround! Should be easy to migrate after this feature's available

**Comment by ancs21** [comment]
**Amazing method for DX.** 
Currently, my team is migrating manual metadata.

Please update ASAP. Thanks.

**Comment by nksaraf** [comment]
Would love to have this feature!!  Using remote schemas and events extensively.

**Comment by smblee** [comment]
What's the status on this issue? I see the pull request but I am unable to use handlebars to set the URLs still

**Comment by ancs21** [comment]
@smblee I think this feature release in the next version.

**Comment by adventurini** [comment]
Is this feature released yet?

**Comment by picosam** [comment]
@tirumaraiselvan I'm unable to use this even though you supposedly released it in v1.3.3 -- am I missing something?

**Comment by kedarguy** [comment]
@adventurini @tirumaraiselvan It's working for me on 1.3.3

**Comment by tobiastornros** [comment]
Thanks for including this in 1.3.3 @tirumaraiselvan 

I think that both Hasura UI and Docs should be updated to reflect this change. 

Here is how you use it @adventurini @picosam 

![image](https://user-images.githubusercontent.com/17402497/105021395-c7226f80-5a48-11eb-802b-069adc19aacd.png)

**Comment by picosam** [comment]
Ohhhh so we should use URL. Sorry, I kept using environment variables!

**Comment by adventurini** [comment]
Yes, I was doing the same thing @picosam. Also, docs should be updated for the current language of:

```Alternatively, environment variables can also be read from the .env file, created manually by the user, at the **_project root directory._** A global flag, --envfile, is available to explicitly get the .env file created by the user, which defaults to .env if no flag is provided.```

The project root directory is confusing. It should state the hasura generated root directory -- I also understand that many people will understand the difference and what the docs meant, but it is still not clear.

**Comment by ericxiao251** [comment]
Hey folks, is there an example of the `env` file structure? I'm getting `Value for environment variables not found:` errors when trying to access my webhook. This is an example URL:

```
{
  "SOME_WEBHOOK_URL": "https://some_url",
}
```
