### ISSUE TITLE
Error with WebSockets and headers containing arrays

### ISSUE THREAD

**Issue by codeithuman** [hasura/graphql-engine#2487]
**Expected Behavior**
I expect to be able to connect to the server via WebSocketLink with authentication headers.

**Actual Behavior**
When I have an array in my headers parameters I get the error "start received before the connection is initialised". 

This may be an error with Hasura or the GraphQL engine. I found the error message in the source here, https://github.com/hasura/graphql-engine/blob/master/server/src-lib/Hasura/GraphQL/Transport/WebSocket.hs#L239.

I've submitted an issue to `apollographql/apollo-link` as well, https://github.com/apollographql/apollo-link/issues/1109.

**A _simple_ reproduction**
When including `x-hasura-allowed-roles` as an array, I get the mentioned error. When I remove `x-hasura-allowed-roles` and/or replace the array with an empty string, everything works as expected. 

```js
  const wsLink = new WebSocketLink({
    uri: GRAPHQL_WSS_DEVELOPMENT,
    options: {
      lazy: true,
      reconnect: true,
      connectionParams: {
        headers: {
          'authorization': "Bearer eyJ0eX...",
          'x-hasura-auth0-user-id': "auth0|5d1...",
          'x-hasura-default-role': "userFree",
          'x-hasura-allowed-roles': ["admin", "driver", "userFree", "userPaid"],
          'x-hasura-email': "aj+d01@riffcreativestudio.com",
          'x-hasura-role': "driver",
        }
      }
    }
  })
```

**Comment by 0x777** [comment]
@codeithuman What is the authn mode that you are using? JWT? If so why are you passing the `x-hasura-*` headers? They have to be part of the JWT. Note that `headers` has to be a map of String to String.

**Comment by codeithuman** [comment]
@0x777, Yes, I'm using Auth0 with Hasura. Hasura doesn't read the variables out of the token. Therefore, I am decoding the token clientside, adding the information to the header and then making the request. 

Sounds like this is incorrect. Should I just be putting `'authorization': "Bearer eyJ0eX..."` into the header and having Hasura read information out of the encrypted token? If so, how do I go about doing this?

Thanks for your time, I really appreciate it!

**Comment by 0x777** [comment]
Sorry I missed this.
> Should I just be putting 'authorization': "Bearer eyJ0eX..." into the header and having Hasura read information out of the encrypted token?

Yes, graphql-engine will [read the session data from the token](https://docs.hasura.io/1.0/graphql/manual/auth/authentication/jwt.html) (the token isn't encrypted, it is signed).

**Comment by marionschleifer** [comment]
I'm closing this issue. @codeithuman feel free to re-open if you'd like to add something 🙂

**Comment by mehtadev17** [comment]
This is still a bug in how that information is processed regardless of where it reads this data from. @marionschleifer we are experiencing this same issue with the data being within the token. 

If you are following DRY (Don't Repeat Yourself) and don't have duplicate code, then whichever function is used to process this claim or header is causing this bug.

**Comment by mehtadev17** [comment]
@marionschleifer When you say "string array" https://hasura.io/docs/1.0/graphql/core/auth/authentication/jwt.html#claims-map

does it mean an array of strings: `["editor","user", "mod"]` 
or a string containing an array: `"[\"editor\",\"user\", \"mod\"]"`

**Comment by ighormartins** [comment]
> Sorry I missed this.
> 
> > Should I just be putting 'authorization': "Bearer eyJ0eX..." into the header and having Hasura read information out of the encrypted token?
> 
> Yes, graphql-engine will [read the session data from the token](https://docs.hasura.io/1.0/graphql/manual/auth/authentication/jwt.html) (the token isn't encrypted, it is signed).

Actually, I think this might be a problem in some cases.
I'm using JWT auth mode, however, for anonymous users before signing-in, I have to send a header with the x-hasura-org-id.
How can I do it?
