### ISSUE TITLE
Troubles connecting to DigitalOcean managed database connection pool

### ISSUE THREAD

**Issue by tvansteelandt** [hasura/graphql-engine#2491]
I'm having difficulties connecting to a Digital Ocean managed database, using a connection pool.
We're using Hasura for a couple of months now, same database, but without connection pool.
We ran into some connection limit issues, so created a pool.
Hasura keeps restarting, using docker, giving the following log:

`{"internal":{"statement":"BEGIN ISOLATION LEVEL SERIALIZABLE ","prepared":true,"error":{"exec_status":"FatalError","hint":null,"message":"prepared statement \"0\" already exists","status_code":"42P05","description":null},"arguments":[]},"path":"$","error":"postgres tx error","code":"postgres-error"}`

So an error with postgres.
Anyone any ideas?

**Comment by 0x777** [comment]
>  We ran into some connection limit issues, so created a pool.

graphql-engine already has connection pooling built in. What issue did you run into? You can configure these two env variables:

`HASURA_GRAPHQL_PG_CONNECTIONS`: Number of connections per stripe that need to be opened to Postgres (default: 50)
`HASURA_GRAPHQL_PG_TIMEOUT`: Each connection’s idle time before it is closed (default: 180 sec)

Reading through [digital ocean's connection pool docs](https://www.digitalocean.com/docs/databases/how-to/postgresql/manage-connection-pools/) you'll need to use the `session` mode for it work with graphql-engine. However I suggest you to use graphql-engine's built-in pooling unless you have other applications which need to connect to Postgres and cannot do pooling on their own.

**Comment by tvansteelandt** [comment]
@0x777 Oh okay, didn't know it had pooling.
We also have an api connecting to the same database.
We have hit the connection limit a few times, must have been from the api then.
Thanks for the explanation!
