### ISSUE TITLE
How to install CLI on windows? 

### ISSUE THREAD

**Issue by vonwao** [hasura/graphql-engine#2497]
I couldn't find anything on how to do it. 

I could install Cygwin if needed?  Will this work?  Thanks.

**Comment by leoalves** [comment]
@vonwao 
You can download the windows binary from here:
https://cli.hasura.io/install/windows-amd64

**Comment by thetre97** [comment]
@vonwao You will need to run it in Powershell/CMD etc - 

```powershell
.\cli-hasura-windows-amd64.exe console
```

**Comment by marionschleifer** [comment]
@vonwao I hope your question has been answered. I'm closing this. Feel free to re-open if you have any more questions on this 🙂

**Comment by bharathvenkata12** [comment]
change the name of the exe file to hasura.exe in cmd use the below command 
.\hasura.exe console

**Comment by TresorRw** [comment]
How about running it globally not just folder it is located
