### ISSUE TITLE
allow specifying a list of columns that can be inserted

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#250]
https://github.com/hasura/graphql-engine/issues/239 needs a change in the implementation of insert permissions. This feature is needed for the new implementation to play well with user defined triggers.

**Comment by xvaara** [comment]
This is a kind of a show stopper for me. Any progress on this?

**Comment by 0x777** [comment]
This should be trivial to implement on the server side. We need to think about the UX on the console though. @rikinsk
