### ISSUE TITLE
[RFC] Permissions: allow conditions spanning tables without relationships

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#2512]
Let's say reading from a table `accounts` should be allowed if there exists a row where `id = x-hasura-user-id AND is_admin = 'true'` in table `users`. Such a condition cannot be expressed as a boolean expression on `accounts` table.

Note that it is possible to workaround this by having an array relationship called `account_admins` to a view which cross joins `accounts` and `users` as follows:

```sql
create view account_admins as
select accounts.id as account_id, users.id as admin_id
from accounts, users
where users.is_admin = 'true';
```
However it is cumbersome to define such views and even the performance suffers. Let's say a user with `id=2` is reading from table `accounts`:

```sql
explain analyze
select
  *
from
  accounts
where
  exists (
    select
      1
    from
      users
    where
      is_admin = true
      AND id = 2
  );
```
has this query plan
```
Result  (cost=2.37..25.07 rows=1270 width=36) (actual time=0.025..0.025 rows=1 loops=1)
  One-Time Filter: $0
  InitPlan 1 (returns $0)
    ->  Index Scan using users_pkey on users  (cost=0.15..2.37 rows=1 width=0) (actual time=0.017..0.018 rows=1 loops=1)
          Index Cond: (id = 2)
          Filter: is_admin
  ->  Seq Scan on accounts  (cost=2.37..25.07 rows=1270 width=36) (actual time=0.005..0.006 rows=1 loops=1)
Planning time: 0.144 ms
Execution time: 0.055 ms
```

while

```sql
explain analyze
select
  *
from
  accounts a
where
  exists (
    select
      1
    from
      account_admins aa
    where
      aa.account_id = a.id
      AND aa.admin_id = 2
  );
```

has
```
Hash Semi Join  (cost=53.65..93.81 rows=1270 width=36) (actual time=0.126..0.128 rows=1 loops=1)
  Hash Cond: (a.id = accounts.id)
  ->  Seq Scan on accounts a  (cost=0.00..22.70 rows=1270 width=36) (actual time=0.010..0.010 rows=1 loops=1)
  ->  Hash  (cost=37.77..37.77 rows=1270 width=4) (actual time=0.041..0.041 rows=1 loops=1)
        Buckets: 2048  Batches: 1  Memory Usage: 17kB
        ->  Nested Loop  (cost=0.15..37.77 rows=1270 width=4) (actual time=0.032..0.036 rows=1 loops=1)
              ->  Index Scan using users_pkey on users  (cost=0.15..2.37 rows=1 width=0) (actual time=0.027..0.028 rows=1 loops=1)
                    Index Cond: (id = 2)
                    Filter: is_admin
              ->  Seq Scan on accounts  (cost=0.00..22.70 rows=1270 width=4) (actual time=0.003..0.004 rows=1 loops=1)
Planning time: 0.322 ms
Execution time: 0.179 ms
```

## Proposed solution

Extend RQL's boolean expression syntax with a new operator, say `_exists` (operates at the same level as `_and`, `_or`, `_not`) which has a schema as follows:

```
{
  "_table" : QualifiedTable,
  "_where" : BoolExp(_table)
}
```

For example, the above condition can now be represented as:

```json
{
  "_exists": {
    "_table" : "users",
    "_where" : {
      "id": "x-hasura-user-id",
      "is_admin": true
    }
  }
}
```

Implementing this as a operator also allows composing expressions across tables. For example:

```json
{
  "_or": [
    { "is_public": true},
    {
      "_exists": {
        "_table" : "users",
        "_where" : {
          "id": "x-hasura-user-id",
          "is_admin": true
        }
      }
    }
  ]
}
```
This says that a row is allowed to be read if `is_public` column is set to `true` or if it is being requested by an admin user.

See #2297 for the original issue which prompted this RFC.

**Comment by leoalves** [comment]
@0x777,

That will simplify some complex permissions I have.
 
Can queries from custom stable functions work too?

```javascript
{
  "_or": [
    { "is_public": true},
    {
      "_exists": {
        "_function" : "isAdmin",
         "_args": { "id" : "x-hasura-id"},
          "_where" : { "isAdmin": true }
        }
      }
    }
  ]
}
```

**Comment by lexi-lambda** [comment]
@leoalves What condition would you expect that to generate? Something like this?

```sql
WHERE EXISTS (SELECT 1 FROM isAdmin(id => $1) WHERE isAdmin = true)
```

That seems a bit indirect, doesn’t it? If `isAdmin` just returns a boolean, a more logical condition would just be

```sql
WHERE isAdmin(id => $1) = true
```

so it seems like maybe that should be a separate feature request for something with slightly different syntax… unless your `isAdmin` function really is returning a set of rows, in which case you could probably make it a view instead of a function.

**Comment by leoalves** [comment]
Hi @lexi-lambda,

> @leoalves What condition would you expect that to generate? Something like this?
> 
> ```sql
> WHERE EXISTS (SELECT 1 FROM isAdmin(id => $1) WHERE isAdmin = true)
> ```

Yes, I think that looks correct.

> 
> That seems a bit indirect, doesn’t it? If `isAdmin` just returns a boolean, a more logical condition would just be
> 
> ```sql
> WHERE isAdmin(id => $1) = true
> ```

Sorry, I don't think the example I used was the best one.  I used the same criteria of @0x777 post.

>unless your `isAdmin` function really is returning a set of rows, in which case you could probably make it a view instead of a function.

It's returning a set of rows.  Sometimes a function gives more flexibility than views.  And we can use it to avoid calling an external endpoints (remote schema).

Since Hasura already supports functions for queries. 
https://docs.hasura.io/1.0/graphql/manual/queries/custom-functions.html#query-custom-sql-functions

I think the permissions can be a lot more powerful if they are included in the validations.

**Comment by karibertils** [comment]
The proposed solution with "_exists" operator looks good to me and would be an exciting change that makes the permission system even more awesome.
