### ISSUE TITLE
unexpected null for tytext

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#252]
Consider this mutation

```
mutation ($id:Int, $nullabletext:String, $nonnullabletext:String) {
    insert_test_table(objects: [
      {
        id: $id,
        text: $nullabletext,
        textnotnull:$nonnullabletext
      }
    ]) {
      returning{
        id
      }
    }
 }
```

In the `test_table` table, `text` is a nullable field. But when I send these variables:

```
{
  id: 232,
  nullabletext: null,
  nonnullabletext: 'sometext'
}
```

It throws a 500 with error message `unexpected null for tytext`.

Issues:
1. How to send null values?
2. Is it possible to have a clearer error message?

Workaround:

The exact above mutation can be achieved by sending the object variable instead of sending the variables separately

```
mutation ($objects: [test_table_insert_input!]!) {
    insert_test_table(objects: $objects]) {
      returning{
        id
      }
    }
 }
```

```
{
    objects: {
       id: 232,
       textnotnull: "sometext"
   }
}
```

**Comment by 0x777** [comment]
https://github.com/hasura/graphql-engine/issues/21

**Comment by ryparker** [comment]
This is still an issue when sending queries.

**Comment by zmjmvp** [comment]
This is still an issue when sending queries.
