### ISSUE TITLE
Failed to build schema-cache because of inconsistent metadata: postgres query error

### ISSUE THREAD

**Issue by meotimdihia** [hasura/graphql-engine#2521]
I stopped running container `hasura/graphql-engine:v1.0.0-beta.2` and start a new container with image `hasura/graphql-engine:v1.0.0-beta.3` , can't start container and get this error.

Do we have any documentation about how to fix this error?

**Comment by shahidhk** [comment]
@meotimdihia When version upgrades happen, Hasura needs to migrate its internal metadata schema. But this cannot happen if there are metadata inconsistencies. Can you provide complete logs?

**Comment by meotimdihia** [comment]
@shahidhk This is docker logs: 
```
{"timestamp":"2019-07-12T08:44:09.380+0000","level":"info","type":"startup","detail":{"kind":"server_configuration","info":{"live_query_options":{"fallback_options":{"refetch_delay":1000},"multiplexed_options":{"batch_size":100,"refetch_delay":1000}},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","enabled_log_types":["unstructured","jwk-refresh-log","ws-server","http-log","schema-sync-thread","websocket-log","startup","webhook-log","pg-client","telemetry-log","metadata","event-trigger"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":"public","stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":true,"port":8080}}}
{"timestamp":"2019-07-12T08:44:09.380+0000","level":"info","type":"startup","detail":{"kind":"postgres_connection","info":{"database":"comic","retries":1,"user":"comic","host":"docker.for.win.localhost","port":54320}}}
{"timestamp":"2019-07-12T08:44:10.427+0000","level":"info","type":"startup","detail":{"kind":"db_init","info":"the state is already initialised"}}
{"timestamp":"2019-07-12T08:44:10.427+0000","level":"info","type":"startup","detail":{"kind":"db_migrate","info":"already at the latest version. current version: \"17\""}}
failed to build schema-cache because of inconsistent metadata: postgres query error
```

**Comment by shahidhk** [comment]
That doesn't look right! There should be more stuff before or after. 

Can you switch back to `beta.2` and then see if server is starting up?

If not, share the logs?
If beta2 server starts up without any issue, please share the Postgres schema and metadata export (or the migration files).

**Comment by meotimdihia** [comment]
This is metadata:
https://gist.github.com/meotimdihia/62f384a870c3412f3c7efa03d855e694
Please copy it. I will remove it later.

**Comment by meotimdihia** [comment]
@shahidhk: this is my database schema: 
https://gist.github.com/meotimdihia/9aafb010330c4f2506698428a71ec14a

**Comment by shahidhk** [comment]
I will check it out and get back.

**Comment by shahidhk** [comment]
@meotimdihia I am unable to import the SQL. Can you share the output of `curl -d'{"opts":["-O","-x", "--schema-only", "--schema" ,"public"], "clean_output":true}' http://localhost:8080/v1alpha1/pg_dump` from your beta2 instance?

**Comment by rakeshkky** [comment]
@meotimdihia Hi, you've empty strings as roles in your metadata. We added a check to look for empty strings for role names in `beta.3`. Refer https://github.com/hasura/graphql-engine/pull/2300 for more details. Please remove them and give a valid role name while you're in `beta.2` and upgrade to `beta.3`. Hope this helps you.

**Comment by meotimdihia** [comment]
Hi, thanks for the help. I fixed by remove role empty `""` as @rakeshkky suggested.
I close this issue.
