### ISSUE TITLE
If a role isn't in `x-hasura-default-role` but `x-hasura-allowed-roles`, then the schema for this role will not be compiled

### ISSUE THREAD

**Issue by Albert-Gao** [hasura/graphql-engine#2535]
I use `v1.0.0-beta.3`

1. Create a `manager` role for a table
![image](https://user-images.githubusercontent.com/18282328/61180420-217b8c80-a66a-11e9-9d1c-7223d3155763.png)

2. use an idToken like this:
![image](https://user-images.githubusercontent.com/18282328/61180440-73bcad80-a66a-11e9-9077-2612a256c5f1.png)

3. Go to the GraphQL panel, the query panel is empty
![image](https://user-images.githubusercontent.com/18282328/61180449-8a630480-a66a-11e9-8709-6ed0711ed43a.png)

**Which seems, when the default role does not match, the role in the `allow-roles` array is not been evaluated.**

Creating a `ceo` will solve the problem, but that indicates the bug here. Seems the `allowed-roles` is actually just `allowed-role` now. :D

Is this related to https://github.com/hasura/graphql-engine/issues/877 ?

**Comment by shahidhk** [comment]
@Albert-Gao Hasura's GraphQL schema is specific to a role. If an introspection query is made with a particular `x-hasura-role` header, only the schema the particular role is allowed to access will be provided.


In JWT mode, `x-hasura-allowed-roles` indicates that the bearer of this token can make requests as these roles. You can choose any of the role required by setting `x-hasura-role` header along with `authorization` header. If you don't send a `x-hasura-role` header with the HTTP request, the role defaults to `x-hasura-default-role` in the JWT claims. Hence you're seeing the schema only for `ceo`.

**Comment by shahidhk** [comment]
In short, if you need to see the schema for the manager, add `x-hasura-role: manager`.

**Comment by Albert-Gao** [comment]
Ah, I see! Thanks.

Furthermore, do you think we should add this to the doc, love to add a PR, seems I can't find it on the doc, or I miss something.
