### ISSUE TITLE
bug: cannot edit boolean properties of records when using Chrome

### ISSUE THREAD

**Issue by thefliik** [hasura/graphql-engine#2536]
Using Google Chrome 75, I cannot edit boolean properties of individual records (I *can* edit them if I use Firefox 68). Clicking once to edit a boolean property opens a selection menu that immediately closes again. See GIF demonstrating problem (note, in the video I am only clicking the mouse *once* in an attempt to open the menu):

![hasura_issue](https://user-images.githubusercontent.com/12599934/61180506-1a05a600-a5cc-11e9-8590-a46a8710ebf7.gif)

This problem occurs with the following setup:

1. Create a new table named `user_profile` using the Hasura web console GUI. The table should have:
   1. An `id` column of type `uuid` and default `gen_random_uuid()`. This is the primary key.
   2. An `admin` column of type `boolean` and default `false`.
2. Save the table.
3. Use the web console GUI to insert a new row for the table using default values.
4. Navigate to the "browse rows" tab for the table and click to edit the row we just inserted.
5. Attempt to edit the `admin` boolean property (you can't).

This problem exists in Hasura v1.0.0-beta.3 using Google Chrome 75 (I've also tested with extensions disabled). The problem also exists in Hasura v1.0.0-beta.2, I've just dragged my feet on reporting it. The problem does not appear to exist in Firefox 68.

A reproduction of the problem can be seen here: https://hasura-issue-dfdeax.herokuapp.com/console/data/schema/public/tables/user_profile/browse.

- Using Google Chrome, simply click to edit the only table row. I'll take this reproduction down in about a week.

**Comment by shahidhk** [comment]
cc @rikinsk.

As a workaround till this is fixed, can you confirm if the arrow keys work? @thefliik

**Comment by thefliik** [comment]
@shahidhk ah clever. Yes, using the arrow keys is a workaround.

Note for others: you must focus the field (by either attempting to click it or using tab) before then using the arrow keys to change the value.
