### ISSUE TITLE
Has the ability to export or create infrastructure from code

### ISSUE THREAD

**Issue by Albert-Gao** [hasura/graphql-engine#2537]
Permission, Relationships, Schemas

It would be great that we can use pure code to import to the platform, and export from the platform as a backup.

IaC is the future :D

**Comment by mnlbox** [comment]
@Albert-Gao Maybe related: #2121
We have a `dump api` now, we just need a `restore api` and add some UI in console about `dump` and `restore`

**Comment by Albert-Gao** [comment]
Ah, thanks, saw them, so pretty much cover all of them, I think I can just close this one. I have some ideas of creating database from graphql schema so people do not need to have DB knowledge to start. But that requires a lot of work.

**Comment by shahidhk** [comment]
@Albert-Gao All Hasura configuration can be managed as code. See https://docs.hasura.io/1.0/graphql/manual/migrations/index.html
