### ISSUE TITLE
Performance issue with subscription

### ISSUE THREAD

**Issue by kpysniak** [hasura/graphql-engine#2538]
Hi all,

We've recently started using Hasura engine for GraphQL subscriptions. The experience so far has been great. However, we've noticed a problem with CPU usage on our postgres db. The CPU usage for Hasura server seems absolutely fine, but it looks like graphql subscriptions via websocket use a lot of resources. Is it the case? If so, is there any way to optimize? Would anyone recommend any ways of debugging why Hasura uses so much cpu on postgres db? Not sure if it matters, but our graphql subscriptions are on views, not tables.

Thanks

**Comment by 0x777** [comment]
@kpysniak I've opened #2541 to improve the DX around debugging subscriptions performance. To understand your issue better we will need the subscriptions and probably the schema too. You can share them here or you can reach out to me on our [discord server](https://discord.gg/hasura).

**Comment by kpysniak** [comment]
Sure, I will send it. However, just wondering, is there any difference in how subscriptions are implemented for tables vs views? You cannot set up triggers on views so I would imagine it might a bit less efficient to views vs tables?

**Comment by marionschleifer** [comment]
Closing this issue now, as a solution will be implemented here: https://github.com/hasura/graphql-engine/issues/2541. @kpysniak feel free to re-open if you would like to share any more details 🙂

**Comment by mrgusev** [comment]
@kpysniak if you remember by chance, were you able to identify what was your subscription performance issue after all?
