### ISSUE TITLE
extend support for subscriptions in 'analyze'

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#2541]
Currently the 'Analyze' button in GraphiQL only works with queries. We need to add support for analysing subscriptions. The relevant information would be whether a subscription can use the multiplexed backend or not and if not what are the changes that need to be done to the subscription.

**Comment by 0x777** [comment]
@rikinsk The server provides explain output for subscriptions now (since beta-8 if I'm not wrong). However the explain response is an object instead of an array when the operation is a subscription. Looks like the console crashes currently when I hit `explain` on a subscription.

**Comment by tsaiDavid** [comment]
@0x777 - just want to point out this still happens for us, using `v1.0.0-pro.3`

**Comment by rikinsk** [comment]
Implementing this was blocked on #3073 which is now finally merged. We'll be picking this issue up soon.
