### ISSUE TITLE
handle array data types in console 

### ISSUE THREAD

**Issue by rikinsk-zz** [hasura/graphql-engine#2544]
Currently the console doesn't handle array type columns properly. 

Need to add support for:
- create array type columns
- allow modifying array type columns ie: array type casts
- display type of array type columns as `type[]` (eg: `int[]`) everywhere

**Comment by tirumaraiselvan** [comment]
![image](https://user-images.githubusercontent.com/8663570/76189948-d9653780-6201-11ea-9958-11b8c62ea18c.png)


Currently, an `integer[]` column appears as `_int4` in the console. This should also be fixed.
