### ISSUE TITLE
allow adding freq used columns in modify table 

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#2545]
Similar to the create table page, add support for adding frequently used columns on the table modify page.

Columns:
- created_at
- updated_at

**Comment by mnlbox** [comment]
@rikinsk Thanks for this suggestion. I think it's an important issue because now many of us have many tables that need add `created_at`, `updated_at` because it's created in previous version If this feature present we can add these fields more simpler. :wink:

**Comment by suhuaixing** [comment]
thanks guys. I forgot to add created_at and updated_at colomns
