### ISSUE TITLE
Api explorer generates invalid insert query

### ISSUE THREAD

**Issue by franciscolourenco** [hasura/graphql-engine#2548]
<img width="836" alt="Screen Shot 2019-07-15 at 19 45 47" src="https://user-images.githubusercontent.com/208149/61236937-881bab80-a739-11e9-8319-4f182858e0f4.png">

**Comment by shahidhk** [comment]
@franciscolourenco This is invalid because it is missing `affected_rows` or `returning` sub fields.

**Comment by franciscolourenco** [comment]
Thanks
