### ISSUE TITLE
Aggregate count queries must be not limited by limit parameter

### ISSUE THREAD

**Issue by endigo** [hasura/graphql-engine#2549]
Aggregate count queries must be not limited by the `limit` parameter.

**Comment by endigo** [comment]
https://aggregate-test.herokuapp.com/console/api-explorer

There is a total of 8 product. 

```graphql
{
  product_aggregate(limit: 5) {
    aggregate {
      count
    }
  }
}

```

**Comment by shahidhk** [comment]
@endigo `limit` is applied on aggregates too to cover use cases that might involve arguments like `limit`, `where` etc.

Can you elaborate a little more on your use case?

**Comment by endigo** [comment]
I want to paginate in 1 query

**Comment by shahidhk** [comment]
```gql
{
  product_aggregate(limit: 5) {
    aggregate {
      count
    }
  }
  product(limit: 5) {
    id
    name
  }
}
```
Wouldn't this work?

**Comment by endigo** [comment]
@shahidhk Yes, this should work.

**Comment by marionschleifer** [comment]
I'm closing this issue. @endigo should you have any follow-up questions, please feel free to re-open 🙂
