### ISSUE TITLE
cli console behaviour when metadata is inconsistent

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#2552]
There seem to be some issues with the console served by CLI when the metadata is inconsistent. This needs to be checked out.

**Comment by rikinsk** [comment]
cant seem to observe anything unexpected

**Comment by marionschleifer** [comment]
@shahidhk is this still an issue? Do we have any more info on this?

**Comment by shahidhk** [comment]
@marionschleifer We can try to repro and close this if all is well.
