### ISSUE TITLE
generated types should respect the nullability of columns

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#256]
currently, we have 
```graphql
type article {
  id Int
  title String
}
```

If `id` and `title` have been declared `NOT NULL`, the types that are generated should be:
```graphql
type article {
  id Int!
  title String!
}
```

**Comment by shahidhk** [comment]
[via thangngoc89#8365 on discord]

**Comment by thangngoc89** [comment]
subscribed to this thread

**Comment by shahidhk** [comment]
@thangngoc89 This is fixed and will be available in aplha13

**Comment by thangngoc89** [comment]
@shahidhk thank you very much
