### ISSUE TITLE
document a guide or checklist for production deployment

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#2561]
Topics to be covered:
1) Using a reverse proxy with links to a nginx, caddy template
2) Command/Server flags to configure from [this](https://docs.hasura.io/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html). 
   - Logging
   - Console availability
   - Admin endpoints to enable/disable
   - Allow-list
   (not exhaustive)
3) Optimisations (subscriptions) ?

@shahidhk Anything you'd want to add to the above?

**Comment by mnlbox** [comment]
Related: #1917    ->     Using reverse proxy with Traefik with Let's encrypt SSL

**Comment by tirumaraiselvan** [comment]
Mostly overlapping with the main comment but slightly more detailed:

1. Security (admin secret, etc), CORS domains, etc
2. API security: a) allow-list, b) limit rows, etc
3. Gateway: Gzip responses for speed, load-balance etc
