### ISSUE TITLE
Insert permisson not applied to renamed column

### ISSUE THREAD

**Issue by matejbasic** [hasura/graphql-engine#2566]
Insert permission is not applied to renamed column, I guess Hasura treats it as a new column. Update and select permissions are updated correctly

**Comment by matejbasic** [comment]
Actually it seems I'm wrong, I apologize. Insert permission is not applied to renamed column, I guess Hasura treats it as a new column.

**Comment by rikinsk** [comment]
@matejbasic I tried to rename a column and the insert permissions were updated as well. Could you confirm this is still happening for you. If yes, exact steps to reproduce this along with the GraphQL engine version would help debug this.

**Comment by marionschleifer** [comment]
@matejbasic any updates here? 🙂

**Comment by matejbasic** [comment]
Hi! I was also unable to reproduce it again. 
So as it was one time event, source of this bug could actually be somewhere else in our pipeline.
If it happens again I will get back to you on this issue.

Thank you
