### ISSUE TITLE
bug in pg_dump api when there are unicode characters in the dump

### ISSUE THREAD

**Issue by houkk** [hasura/graphql-engine#2571]
Runing in docker. Migrate init failed(`pg_dump` failed).

### Version
Graphql-engine: v1.0.0-beta.3 (upgrade from 1.0.0-beta.2)
hasura-cli: 1.0.0-beta.3

### Command
Excute follow command:
```
$ hasura migrate create "init" --from-server
```
And then get `pg_dump` error:
```
FATA[0084] cannot fetch schema dump: [unexpected] internal exception while executing pg_dump ($)
```

### Make pg_dump post request
```
POST url: http://localhost:8081/v1alpha1/pg_dump
Body: {
  "opts": ["-O", "-x", "--schema-only", "--schema", "public"],
  "clean_output": true
}
```
`Response`
```
status: 500
body: {
    "path": "$",
    "error": "internal exception while executing pg_dump",
    "code": "unexpected"
}
```

**Comment by mnlbox** [comment]
@houkk I also have same issue and report it in Discord.
@shahidhk are you any idea.
Anything worked later in Beta.2 and break on Beta.3

**Comment by shahidhk** [comment]
@houkk @mnlbox I started with a beta2 instance and then upgraded it to beta3. I was unable to reproduce the bug.

Can you give a docker-compose file and a schema so that I can reproduce the issue to investigate further?

**Comment by mnlbox** [comment]
Hi man,
I can send my schema to you in Discord DM :wink: Let me an hour.

**Comment by bkstorm** [comment]
I have the same issue.

**Comment by houkk** [comment]
Hi @shahidhk ,
My test, do not need upgrade. 
Just In the `1.0.0-beta.3`. 
When table field `comments` are not in English or Numbers, such as Chinese ...
The above questions will arise.

**Comment by mnlbox** [comment]
@houkk Oh maybe because I have many non-english comments.

**Comment by houkk** [comment]
@mnlbox @shahidhk 
Please verify it. 
If this is the reason, this problem will be fixed in the future ? 
Or is it a special function ? 😅

**Comment by shahidhk** [comment]
Thanks, @houkk. I can reproduce this when there are Unicode characters in comments.

Simple repro instuctions:

```sql
CREATE TABLE test (
    id serial primary key
);
COMMENT ON TABLE test IS 'سطح دسترسی های سیستم';
```

@lexi-lambda Can you check if this is something related to the latest refactor?
