### ISSUE TITLE
Remote schema forward original user-agent

### ISSUE THREAD

**Issue by danghung-dev** [hasura/graphql-engine#2572]
Hi everyone, 

I have to save all request ip address and user-agent.
Because all request is behind aws load balancer, so i can see original ip address in "x-forwarded-for" in headers. But user-agent is always "hasura-graphql-engine/v1.0.0-alpha44"

How can I forward original user-agent. Thank you very much.

**Comment by tirumaraiselvan** [comment]
Thanks, we will add this as soon as possible.

**Comment by danghung-dev** [comment]
Fantastic!
That's great!

**Comment by RodolfoSilva** [comment]
@tirumaraiselvan @0x777 this is a great enhancement to use with auth systems.

**Comment by tirumaraiselvan** [comment]
Thanks for the suggestions everyone. This is going to be part of the upcoming release: https://github.com/hasura/graphql-engine/pull/2753

**Comment by danghung-dev** [comment]
Do we have any update? @tirumaraiselvan @RodolfoSilva 
Thanks.

**Comment by RodolfoSilva** [comment]
@danghung-dev No, I don't. Maybe @tirumaraiselvan.

**Comment by tirumaraiselvan** [comment]
@danghung-dev Sorry for the delay. We will definitely make it part of the next release.

**Comment by RodolfoSilva** [comment]
@tirumaraiselvan thanks. :P

**Comment by danghung-dev** [comment]
Do we have any update? @tirumaraiselvan

**Comment by tirumaraiselvan** [comment]
@lexi-lambda Can we call this `X-Hasura-Original-User-Agent` and close this case? Not sure if this needs to be thought more than fixing a convention.

**Comment by lexi-lambda** [comment]
Personally, I think we should just use `X-Forwarded-User-Agent`. It’s consistent with the meaning of the other de-facto standard headers like `X-Forwarded-For`, `X-Forwarded-Host`, and `X-Forwarded-Proto`, and it’s extremely unlikely to cause any trouble.

On a semi-tangential note, until very recently, I thought proprietary headers were supposed to be prefixed by `X-`, but I recently found out that convention was deprecated in 2012 in [RFC 6648](https://tools.ietf.org/html/rfc6648). So if we introduce Hasura-specific headers in the future, we should probably just prefix them with `Hasura-`, not `X-Hasura-`… but in this case I think `X-Forwarded-` is still the natural prefix to use here by convention.

**Comment by danghung-dev** [comment]
Hello @tirumaraiselvan,

Do we have any update?

**Comment by tirumaraiselvan** [comment]
@danghung-dev Sorry for the delay! Have raised a PR here #3347 

Will make sure it gets out in the next release.

**Comment by danghung-dev** [comment]
@tirumaraiselvan **Happy new year !!!**

I do not see X-Forwarded-Host and X-Forwarded-User-Agent when sent event. How can I add it to there? 

As I said above I have log who change value in database. 
> I have to save all request ip address and user-agent.


![image](https://user-images.githubusercontent.com/5670932/71706614-ad4fc380-2e18-11ea-9c37-6745b58dcd99.png)

**Comment by tirumaraiselvan** [comment]
@danghung-dev That's true. We only added the headers for remote schemas. I don't see a reason why we shouldn't add them for event triggers as well. Could you open an issue for the same?

**Comment by tirumaraiselvan** [comment]
Actually, now that I think more about it. It might be much harder to add them for event triggers. This is because event trigger payloads are generated by the database and are only aware of hasura session variables i.e `x-hasura-*` variables. Any other client side information is unavailable.
