### ISSUE TITLE
Auth Webhooks The client get data from authentication server

### ISSUE THREAD

**Issue by sayi65** [hasura/graphql-engine#2574]
hasura graphql auth webhooks.

Look at the image below
Is it possible to obtain authentication server data from the client?

### e.g
```
**request**
`client -> {header: Authorization} -> hasura(webhook URL : GET) -> authentication server`

**response** 
`authentication server -> {data} -> hasura ->  client`
```

We think that jwt can be updated more easily if we can handle it this way.

![webhook](https://docs.hasura.io/1.0/_images/auth-high-level-overview1.png)

**Comment by ecthiender** [comment]
@sayi65 can you explain your use-case for this in a bit more detail? That would help us understand the purpose of the feature.

The current purpose of auth webhook is to authorize the request and return `x-hasura-*` session variables back to Hasura. Infact Hasura will reject if the response is of not that format. Do you want the same format of response (`x-hasura-*` values) to be returned to the client?

**Comment by sayi65** [comment]
@ecthiender  
The authentication server does not communicate directly with the application, but wants to pass data to the client side via graphql-engine.
I am currently using webhook-auth, but when token is expired, I want to issue a refresh token via graphql-engine.
Is this possible?

**Comment by ecthiender** [comment]
@sayi65 
> I am currently using webhook-auth, but when token is expired...

How do you get the token on the client-side, in the first place? You can continue using that mechanism for refreshing tokens?

**Comment by sayi65** [comment]
@ecthiender 
In the First Place. i was created an authentication server. then request to the authentication server and get the token. use this toke to request the hasura graphql engine.
In hasura graphql engine use the webhook-auth to validate the Authorization.

when the token is expired. I don`t know how to refresh the token.

**Comment by ecthiender** [comment]
When you get the token on the client side for the first time, you should run a `setInterval` with interval of the expiry of the token. When the token is expires the callback to `setInterval` will make request to your auth server and can get a new token.

Although this blog is not about webhook, but the above pattern is documented in the "Silent Refresh" section: https://blog.hasura.io/best-practices-of-using-jwt-with-graphql/#silent_refresh

**Comment by sayi65** [comment]
@ecthiender 

Thank you for your comment.
I will try this way.
