### ISSUE TITLE
Add a section on Table relationships modelling guides about relationship with multiple tables

### ISSUE THREAD

**Issue by Urigo** [hasura/graphql-engine#2579]
Something like Transaction <-> Financial Entity

Financial entity can be of a number of tables like people or businesses

**Comment by Urigo** [comment]
I guess it's related to [this](https://github.com/hasura/graphql-engine/issues/2323) but until and if you decide to introduce something like that, maybe just a doc section about how you recommend the user to implement it

**Comment by coco98** [comment]
@Urigo We should definitely do a blogpost and think about creating a union/interface type thing in Hasura to make that modelling easier. :)

If I understand correctly, there are 2 options you can use currently: 

## Option 1
For now, you can create a relationship from Transactions to Persons and from Transactions to Businesses. When you do `transaction.person` or `transaction.business` the relationship will be traversed, although none, one or both could be null.

## Option 2
However, assuming that a particular transaction can only belong to one particular Financial Entity. Let's say, either a Person or Business. Then this could be a way of modelling this:

1. Transactions table has: `id, name, amount, financial_entity_type, financial_entity_id`
  - `financial_entity_type` can be one of `person` or `business`
2. Persons table has: `id, name, age, email, financial_entity_type`
  - `financial_entity_type` is always set to `person`
3. Businesses table has: `id, name, location, financial_entity_type`
  - `financial_entity_type` is always set to `business`
4. Transaction.person is an object relationship using the foreign-key `Transactions . (financial_type_id, financial_entity_id)` to `Persons . (id, financial_entity_type)`
5. Transaction.business is an object relationship using the foreign-key `Transaction . (financial_type_id, financial_entity_id)` to `Businesses . (id, financial_entity_type)`

This has the following properties:
1. One transaction can only belong to either a person or a business but can't point to both simultaneously
2. If you make the `transactions . financial_entity_type` column a foreign key to an enum table, they will automatically be validated at the data model level and exposed as GraphQL enums.

**Comment by Urigo** [comment]
hi @coco98 ❤️ 

OK got it! it is much better then what I started doing myself :)

My solution was something like that:
Let's say we are talking about `Transaction.sender` (just to separate the type name and the field).

I've created a `Financial_Entities` table with `id, type_id, type` (am I doing the case of the table right?)

Had an object relationship using the foreign-key `Transactions . sender_id` to `Financial_Entities . id`
and then I connected them to the `Persons` and `Businesses` tables with logic to find it = 💩 

Your solution is much nicer.....
Going to do that now

**Comment by coco98** [comment]
Awesome :)

On the case of the tables, camel casing everything with pluralised naming for the table names is the best. Sorry for my weird naming in the comment above.
`financial_entities` would be better than `Financial_Entities`, I think. We're working on exposing the GraphQL schema generation better so that you can switch to SnakeCase from camel_case and things like that, but for now, the camel casing with pluralised table names should generate the best schema! :)

**Comment by Urigo** [comment]
mmm sorry in advance for the stupid questions....

Just to make sure - I don't actually create a foreign-key on the table itself (the `Modify` tab) but just on the `relationship` tab right?

also, that means that I have 2 different fields on the GraphQL schema, I will query them both but I will know only in my mind that I will get a result only in one

**Comment by coco98** [comment]
Closing this in favour of #2323 (creating a polymorphic relations guide).
