### ISSUE TITLE
Disable graphql-engine flag

### ISSUE THREAD

**Issue by bartjuh4** [hasura/graphql-engine#2580]
Let first begin to start thanking you guys for this great tool! At this moment we are only using the webhooks feature. We started with Skor but because of missing the retry feature we needed something more reliable.

But it would be nice if you can add a flag to disable the graphql server. Is that possible?

**Comment by coco98** [comment]
@bartjuh4 You can just set up a very secure 64 character admin secret and that will prevent the API being used by anyone else, but the console etc will continue to work.

**Comment by bartjuh4** [comment]
Thanks!
