### ISSUE TITLE
suggest text type for column edits of any type in console

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#2583]
When the column type is integer and i would like to convert to text, the suggestion box for column type doesn't show the option.

**Comment by apvarun** [comment]
Any update on this issue?

**Comment by rikinsk** [comment]
A workaround till this issue is fixed is to run the following SQL statement directly on the RawSQL page:

```sql
alter table <table> alter column <column> type text;
```

**Comment by adrianoresende** [comment]
The same here, If I type text, don't work.

![image](https://user-images.githubusercontent.com/798755/79049880-929d9f80-7bfc-11ea-9800-fbef9a3fda2e.png)

**Comment by beerose** [comment]
Closed via https://github.com/hasura/graphql-engine/pull/4546
