### ISSUE TITLE
Error when trying to modify permissions

### ISSUE THREAD

**Issue by mouneshg** [hasura/graphql-engine#2586]
See attached images.
Occurs when trying to select permissions to modify.

Requst Payload:
{"type":"bulk","args":[{"type":"reload_metadata","args":{}},{"type":"get_inconsistent_metadata","args":{}}]}

![image](https://user-images.githubusercontent.com/35033188/61633381-970bdc00-acac-11e9-85fc-acec7f537cf3.png)

**Comment by rikinsk** [comment]
@mouneshg Thanks for reporting this. There should be error details logged in the browser console / dev tools. Could you please share a screenshot of the error. It would help debug this faster.

**Comment by marionschleifer** [comment]
@mouneshg any update on this? 🙂

**Comment by marionschleifer** [comment]
@mouneshg I'm closing this issue. Feel free to re-open any time if you'd like to add details on this error 🙂
