### ISSUE TITLE
Permissions screen: Multiple conditions using and/or check are not re-populated in the UI

### ISSUE THREAD

**Issue by sairam** [hasura/graphql-engine#259]
see sample image for reference:

![image](https://user-images.githubusercontent.com/163584/43712884-59b86fb0-9995-11e8-9ec8-f8cd499a45a8.png)

**Comment by praveenweb** [comment]
@sairam - Thanks for pointing out. This was a UI issue with the way our legacy operators were handled.

Fixed in 816b480df3c8d7bb1bb60a016ac7e0cf2eeb68b6

**Comment by mjonas87** [comment]
Looks like this might still be happening?

![image](https://user-images.githubusercontent.com/1400552/61335895-f7e67080-a7e3-11e9-9ec7-1dd55dc258dd.png)

![image](https://user-images.githubusercontent.com/1400552/61335908-0a60aa00-a7e4-11e9-86e8-8bfe0b972c76.png)
