### ISSUE TITLE
hasura/graphql-engine:latest.cli-migrations not found 

### ISSUE THREAD

**Issue by dvasdekis** [hasura/graphql-engine#2591]
I want to use graphql-engine:latest in my Docker images (via docker-compose) due to frequent upgrades and great work by your team. However, I can't combine this with the .cli-migrations image descriptor.

Attempt and failed docker container pull with `hasura/graphql-engine:latest.cli-migrations` in `docker-compose.yaml` below:
```
PS C:\Users\Balsamic State\proj\hasura-jwt-auth\quickstart> docker-compose up -d --force-recreate
Pulling graphql-engine (hasura/graphql-engine:latest.cli-migrations)...
ERROR: manifest for hasura/graphql-engine:latest.cli-migrations not found
```
Successful docker container pull when specifying a version number below:
```
PS C:\Users\Balsamic State\proj\hasura-jwt-auth\quickstart> docker-compose up -d --force-recreate
Pulling graphql-engine (hasura/graphql-engine:v1.0.0-beta.3.cli-migrations)...
v1.0.0-beta.3.cli-migrations: Pulling from hasura/graphql-engine
```
Suggest that images could be consolidated - e.g. [Postgres docker](https://docs.docker.com/samples/library/postgres/#initialization-scripts) looks for a folder mapped to `/docker-entrypoint-initdb.d` and doesn't run scripts if this isn't found. In the same way, the existing Hasura Docker image could look for migrations in `/hasura-migrations` and ignore them if this folder isn't found/isn't mapped as a volume in Docker.

Thank you!!

**Comment by shahidhk** [comment]
We don't publish a `latest.cli-migrations` image. Will add from the next release.

**Comment by shahidhk** [comment]
@dvasdekis As of now, I have pushed `hasura/graphql-engine:v1.0.0-beta.4.cli-migrations` as `hasura/graphql-engine:latest.cli-migrations` to docker hub.
