### ISSUE TITLE
automatic radio btn switching not happening on edit row page on data input

### ISSUE THREAD

**Issue by michaelhayman** [hasura/graphql-engine#2595]
First off, thanks again for Hasura I love it <3

Ran into a bit of a weird bug - editing a nullable text column (it's about 8th or 9th in the list of columns in the table) (when it starts from NULL) using the Hasura editor doesn't save the information (record always shows NULL).  But running an SQL command directly does save it.  Interestingly, if I create the record with Hasura ediotr it saves the information.  Also if I edit the record when it doesn't start with NULL in the field, it saves properly.  If I reset the column to NULL it's broken again.  There's other columns which are nullable which save the information if I change it using the editor.  There's no triggers on the table.

Here's an example :)  Try adding a column with NULL 'profile_questionnaire_id' or 'customer_questionnaire_id' then editing them so they have values.  Interestingly 'parent' works and displays the expected behaviour.
https://heroku-testing-ground.herokuapp.com/console/data/schema/public/tables/categories/browse

**Comment by rikinsk** [comment]
@michaelhayman I think I might have figured out the exact issue  here. 

When you type values in the input box, the radio btn doesn't move to the input field and stays on the Null option. If you manually select the radio btn before the input, the value updates.

![Screenshot from 2019-07-25 17-23-10](https://user-images.githubusercontent.com/153602/61872466-01b55580-af01-11e9-9bbf-3fc69b8e2079.png)
vs
![Screenshot from 2019-07-25 17-23-35](https://user-images.githubusercontent.com/153602/61872473-0aa62700-af01-11e9-8db9-bb814937b9c7.png)



Can you confirm if this is indeed the issue?

**Comment by michaelhayman** [comment]
Yep that seems to be the issue.  Didn't really notice the radio button next to the input field :)

**Comment by rikinsk** [comment]
That's great! Updating issue title to reflect that.
