### ISSUE TITLE
Regex for column jsonb fields

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#2602]
Adding support to use regex for jsonb fields in database columns.

https://github.com/hasura/graphql-engine/issues/2080

**Comment by yasinarik** [comment]
Any news about this? I want something similar to implement multilingual text searching in most of the tables of my database.

I gave an example in this issue: #6577

**Comment by rikinsk** [comment]
Fixed via https://github.com/hasura/graphql-engine/commit/4ec9229f155858cc214db564f3a2e63c662e6a31
