### ISSUE TITLE
Support Raster Queries

### ISSUE THREAD

**Issue by friend0** [hasura/graphql-engine#2613]
This is a **Feature Request**. Raster support seems to be lacking from all postgis functions supporting it. They are a critical part of many geospatial services. Most needed is the ability to retrieve raster data with `st_intersects`. In particular, with the signature `ST_Intersects( geometry geommin , raster rast , integer nband=NULL )`

This functionality would support queries like this:
```
query getIntersectingField($input: geometry) {
  2d_field(where: {rast: {_st_intersects: {from: $input, args: ...}}}) {
    rid
    rast
}
}
```

**Comment by dsandip** [comment]
Adding more context from Discord here 

## From @friend0 :

I'd be looking for functionality like 3 signatures found [here](https://postgis.net/docs/RT_ST_Intersects.html). Namely, 

```
boolean ST_Intersects( raster rastA , raster rastB );
boolean ST_Intersects( raster rast , integer nband , geometry geommin );
boolean ST_Intersects( raster rast , geometry geommin , integer nband=NULL );
```
I guess the GQL would look something like:

```JSON
query getNearbyObjects($flightPlan: raster/geometry) {
  airbus_2d_field(where: {rast: {_st_intersects: {from: $flightPlan, args: ...}}}) {
    rid
    rast
}
}
```
functionality most closely matching the top sig would be what we're looking for as the base `_st_intersects`. The more specific cases could be backburnered for sure.

## from @0x777 :
There is no equivalent construct of overloaded functions in gql.
So, it is not quite possible to map all the functionality of `ST_Intersects` under the same operator, `_st_intersects`. However we can have multiple operators, each implementing the appropriate overload variant of `ST_Intersects`.

---
@lexi-lambda You can take a call on whether to add the other operators for the overloaded variants based on the additional effort for them (once the base function is available).
