### ISSUE TITLE
permission check cannot be defined on citext type fields

### ISSUE THREAD

**Issue by sachinbhutani** [hasura/graphql-engine#2614]
If a field to be matched against x-hasura-xxxx environment variable is defined with type citext, permission check settings do not allow selection of any comparison operators. 
for example: 
Table: Users, field: username, type: citext. 
I want to check this against environment variable x-Hasura-Username, to allow update to Users table. 
this permission cannot be defined in console as list of operators is blank

![Screen Shot 2019-07-27 at 10 57 02 PM](https://user-images.githubusercontent.com/6120010/62002909-52c07780-b0c2-11e9-9d8e-144834ecf4dd.png)

**Comment by rikinsk** [comment]
closed via #2622
