### ISSUE TITLE
debug mode is not printing debug lines in cli

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#2637]
Somehow enabling debug logs using `--log-level debug` is not printing the debug log lines.

**Comment by dlemstra** [comment]
Is this still an issue? I ran the following command: `make build && _output/cli-hasura-linux-amd64 version --log-level=DEBUG` and I got `DEBU` in the output.

**Comment by shahidhk** [comment]
This has been fixed since.
