### ISSUE TITLE
API isn't generated when the schema name contains symbols

### ISSUE THREAD

**Issue by ardsh** [hasura/graphql-engine#2639]
If the schema name contains symbols like `$`, the schema for it doesn't get generated, I'm assuming due to graphql field names being unable to contain symbols, and the schema name being used as a prefix.

This is a problem because I'm attempting to migrate to hasura from prisma, with an existing prisma schema, and by default the prisma schema names have a name that contains a `$` symbol, and it can't be changed.

The query generation works very well when I manually rename the schema name to not have a symbol, but prisma can't work with a renamed schema.

This issue seems related or possibly a duplicate to #981 but the current pull request doesn't seem to address the prefixing with the schema name (close this issue if I'm wrong)

A possible fix would be to disable prefixing, or remove all symbols from the schema name when generating the query names.

**Comment by brunoprela** [comment]
I am also having this problem, would like to move from using prisma to using hasura while still using prisma for my table creation and migration. This issue can be reproduced when you execute `CREATE SCHEMA symbol$name` in the sql execution console, and then the tables that get tracked don't show up as queries .

**Comment by 0x777** [comment]
@rakeshkky From what I understand in #2509 we allow customising the field names which implies that whether schema name is part of the field name is a decision that is completely under user's control (assuming the console presents these options). However I'm not sure what happens to the generated types? Do we use the schema name in generated types?

**Comment by rakeshkky** [comment]
@0x777 

> From what I understand in #2509 we allow customising the field names which implies that whether schema name is part of the field name is a decision that is completely under user's control (assuming the console presents these options)

Yes

As of now in https://github.com/hasura/graphql-engine/pull/2509 we're allowing users to customise the root field names (resolvers) and column fields. This will not affect the generated type names. Hence, API is generated to tables whose Postgres schema is not GraphQL compliant.

**Comment by tirumaraiselvan** [comment]
Thanks for the issue @ardsh 

This is being tracked here: https://github.com/hasura/graphql-engine/issues/3811
