### ISSUE TITLE
Date type is inconsistently cased

### ISSUE THREAD

**Issue by nextmat** [hasura/graphql-engine#2643]
From the [Hasura doc reference for supported types](https://docs.hasura.io/1.0/graphql/manual/api-reference/postgresql-types.html):

![API Reference - Supported PostgreSQL Types _ Hasura 1 0 documentation 2019-07-30 14-07-19](https://user-images.githubusercontent.com/3279/62165852-3562f780-b2d4-11e9-8bc9-9b88a9f1a7fd.png)

However, when this type is used, the query fails:

![overview 2019-07-30 14-13-55](https://user-images.githubusercontent.com/3279/62165903-50356c00-b2d4-11e9-9fb4-92f70e34fdfb.png)

`date` works - is this a doc bug or should Postgres primitive types be capitalized per your docs?

**Comment by Stefmore02** [comment]
`date` works and docs are clear. Feel free to re-open if still confused and/or if needed.
