### ISSUE TITLE
implement readiness and liveness proble endpoints

### ISSUE THREAD

**Issue by hafizio** [hasura/graphql-engine#2645]
I'm using `hasura/graphql-engine:v1.0.0-beta.3` with Kubernetes.

In the Kubernetes deployment for a Hasura instance, I see that the `/healthz` endpoint is returning `500` when there are inconsistencies in the metadata.

Logs:

```
{"timestamp":"2019-07-31T05:43:21.049+0000","level":"warn","type":"metadata","detail":{"message":"Inconsistent Metadata!","info":{"objects":[{"definition":{"using":{"foreign_key_constraint_on":{"column":"city_id","table":"offers"}},"name":"offers","comment":null,"table":"cities"},"reason":"column \"city_id\" does not exist","type":"array_relation"},{"definition":{"using":{"foreign_key_constraint_on":{"column":"store_id","table":"offers"}},"name":"offers","comment":null,"table":"stores"},"reason":"column \"store_id\" does not exist","type":"array_relation"},{"definition":{"using":{"foreign_key_constraint_on":"store_id"},"name":"store","comment":null,"table":"offers"},"reason":"column \"store_id\" does not exist","type":"object_relation"},{"definition":{"using":{"foreign_key_constraint_on":"city_id"},"name":"city","comment":null,"table":"offers"},"reason":"column \"city_id\" does not exist","type":"object_relation"}]}}}
```

Quoting @shahidhk from the Discord discussion:

```
The pod is starting, but the health endpoint is more like a liveness probe
```

**Comment by shahidhk** [comment]
We need to define what "ready" and "live" means for GraphQL Engine and provide endpoints to probe them. 

ref https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes

**Comment by hafizio** [comment]
I upgraded the image to `hasura/graphql-engine:v1.0.0-beta.4` and there's another instance of metadata inconsistencies. But now, even when the readiness/liveness probes are disabled, the engine failed to start (so I can't port forward and resolve the inconsistencies).

**Comment by shahidhk** [comment]
@hafizio Upgrades will fail if there are metadata inconsistencies. You need to go back to the old version, fix the inconsistencies and then upgrade.
