### ISSUE TITLE
Win 10 powershell: Cannot update to v1.0.0-beta.4 from 3?

### ISSUE THREAD

**Issue by scheung38** [hasura/graphql-engine#2653]
heroku --version
heroku/7.24.4 win32-x64 node-v11.14.0

Tried to update hasura version to v1.0.0-beta.3 to v1.0.0-beta.4:

Powershell :

heroku git:remote -a my-test-app

warning: heroku update available from 7.24.4 to 7.27.1,

Error: unable  to verify the first certificate

Could this be related to corporate firewall etc issue?

**Comment by marionschleifer** [comment]
@scheung38 this seems like a Heroku issue rather than a Hasura issue. I'm closing this. Feel free to re-open if you want to add something 🙂
