### ISSUE TITLE
Heroku deployed app strange behavior

### ISSUE THREAD

**Issue by scheung38** [hasura/graphql-engine#2654]
Win 10, powershell non-admin mode:

hasura console

sometimes

INFO console running at http://localhost:9695/

but sometimes I needed to restart Herokuapp from dashboard.heroku.com

sometimes I get:

FATA[0001] version checkL failed to get version from server: GET: https://my-test-app.herokuapp.com/v1/version failed - [401]

and it seems that I first need to pre-open in Chrome https://my-test-app.herokuapp.com/console.login first, before I can issue another

hasura console 

since hasura console opens by default in IE?

???

**Comment by callmekatootie** [comment]
Is your heroku instance on a paid tier? If not, then heroku tends to put your instance to sleep in the free version if it is not interacted with frequently (I think if there is no interaction within 30 minutes or something like that). So what you might be facing is that the instance is asleep and is being awaken but not in time for hasura to detect that it is active and thus it complains. When you visit the website (does not have to be in chrome, can be in any browser), the instance is awoken and changes state from asleep to active and thus hasura console works after that.

**Comment by marionschleifer** [comment]
@scheung38 I hope your problem is resolved with @callmekatootie's answer 🙂 I'm closing this now. Feel free to re-open if you have more questions.
