### ISSUE TITLE
Error when using "_in" operator to query an enum type

### ISSUE THREAD

**Issue by waterdrop01** [hasura/graphql-engine#2659]
Hi,

Seems I can't use the **"_in"** operator on an column whose type is a postgres **enum**!

I have an enum type in postgres:
```SQL
CREATE TYPE "month_enum" AS ENUM (
    'january',
    'february',
    'march'
);
```
But when I'm querying from graphiql like this:
```gql
query month_query {
  month(where: { currency : { _in : ["january", "february"]}} {
    month
  }
}
```
I get this error:
```
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "constraint-error"
      },
      "message": "type \"month_enum[]\" does not exist"
    }
  ]
}
```
I'm quite sure it was working a few months ago...

Any idea?

Thanks a lot!

Note: I'm using **pg11** and hasura/graphql-engine:**v1.0.0-beta.4**

**Comment by marionschleifer** [comment]
Hi @waterdrop01 🙂 we are currently working on supporting Postgres ENUM types: https://github.com/hasura/graphql-engine/issues/982. It will be part of one of the next releases.

You can use [single-column tables](https://docs.hasura.io/1.0/graphql/manual/schema/enums.html) until that time. Let us know if you have any more questions.

**Comment by waterdrop01** [comment]
Hi @marionschleifer, got it. Looking forward the next release then :) Thank you for your answer
