### ISSUE TITLE
After Hasura login the credentials remain visible?

### ISSUE THREAD

**Issue by scheung38** [hasura/graphql-engine#2660]
After login to Hasura with the Hasura admin secret, this now becomes visible inside the Request Headers Value field?

**Comment by marionschleifer** [comment]
@scheung38 thank you for reporting this issue. 

I was able to reproduce this on Chrome with one of my projects:

![image](https://user-images.githubusercontent.com/5722022/62413081-cd7e1b00-b60b-11e9-8cf2-564db8105149.png)

However, if I open the console in another browser or in incognito mode, the admin secret is not visible.

**Comment by wawhal** [comment]
Hey people! Sorry for the delay in response.
[This PR](https://github.com/hasura/graphql-engine/pull/2686) fixes all these issues related to admin-secret, login and graphiql headers. It set to be merged soon.

Thanks for reporting the issue @scheung38 :)

**Comment by rikinsk** [comment]
closed via #2686
