### ISSUE TITLE
`--down` option for `hasura migrate apply` ignores other options

### ISSUE THREAD

**Issue by aprakash-sovrn** [hasura/graphql-engine#2662]
When running `hasura migrate apply --down`, options such as `--project` and `--endpoint` seem to be ignored, such that the command has to be run from the directory that contains `config.yaml` and `migrations/`, and cannot be overridden on the command line. `hasura migrate apply` does not exhibit this behavior, and both options can successfully be provided and are applied.

```
$ hasura version
hasura CLI version: v0.4.45
GraphQL Engine CLI version:  v1.0.0-beta.4
GraphQL Engine Server [omitted] version: v1.0.0-beta.2 
```

**Comment by shahidhk** [comment]
Can you download the latest CLI from https://docs.hasura.io/1.0/graphql/manual/hasura-cli/install-hasura-cli.html and see if the issue is still present?
You seem to be using an older build of the CLI.

**Comment by aprakash-sovrn** [comment]
looks like this works now, thanks!
