### ISSUE TITLE
issue in login-logout between beta.3 and beta.4

### ISSUE THREAD

**Issue by MarkusFaatz** [hasura/graphql-engine#2663]
Hey there!

First of all: Thanks a lot, I love exploring this project!
I am running it using your provided docker-compose file and connecting it to my platform (based on nginx-proxy-companion).

I think I found a mini-bug and it could help to clean up some more data from local storage on logout!
I started with version beta.3 and switched to beta.4 (of course I did not logout before :smiley: ). After logging in, I had full access to my database but could not use graphiql (unauthorized). 

Logging out didn't help me out, but to clear the local storage "by hand" worked fine!

[docker-compose-copy.txt](https://github.com/hasura/graphql-engine/files/3462469/docker-compose-copy.txt)

**Comment by rikinsk** [comment]
Should be resolved in #2686

**Comment by rikinsk** [comment]
Closedc via #2686
