### ISSUE TITLE
pass query/mutation into webhook auth post body

### ISSUE THREAD

**Issue by ptrobert** [hasura/graphql-engine#2666]
Feature request : can we get the query/mutation as part of hasura webhook auth post body,  we can use webhook auth as a firewall for monitoring user realted activities, restrict him for per minute allowed queries , stop abuse of sms remote schemas etc

For Remote schemas we can use graphql query limiter etc, but Hasura queries it self will be left alone.

By Having a web hook auth based moniroting system, we can monitor and enforce all types of security rules

**Comment by harryc9** [comment]
@0x777 Hi, this feature is important, it avoids the use of another server as proxy to act as firewall

If not assigned yet, maybe I could help take a look? Could you point me to a direction in the repo where I can get started? Thanks

**Comment by tirumaraiselvan** [comment]
Hi folks

What kind of interface would you expect the query/mutation to be provided in the webhook payload? Just the operation string would be hard to use as it would need to be parsed at the minimum. 

Does something like a JSON version of selection set be more useful (this is a simple Graphql AST) ? For example:


```
operation: query
operationName: myQuery
selectionSet: [
  { 
    name: "select_users", 
    type: "Users", 
    selectionSet : [ ... ]    # <this will have selection set of select_users>
  }
]

**Comment by tanmaypatil** [comment]
Hi @tirumaraiselvan  , would like to give a concrete example .
```
query vam_virt($account_id : String ) {
  vam_virtual_account(where  : { account_id : {_eq :   $account_id }}) {
    account_id
    account_name
    prefix
    currency
    context_id
  }
}.

In this query from application permission point of view 

- query field , vam_virtual_account is important element to be available to auth hook , as it denotes the domain which user is trying to access

-  query variable account_id is important . User might have access on account_id : ABC but may not have access on account_id : DEF 

- selectionSet of fields would be important. would it be array [ 'account_id', 'account_name'] 

-  Implicitly we will have where clause added to query `{ where : { account_id :  {_in  :  x-hasura-account_id }`

One query , can computed field have access to hasura session variables .

Regards
Tanmay

**Comment by caipirginka** [comment]
I see docs here: https://hasura.io/docs/latest/graphql/core/auth/authentication/webhook.html
mentioning passing of variables to the Authentication Webhook, but is it actually implemented?

Trying from the Hasura Console it seems that only "headers" are passed to the Authentication Webhook (using Hasura v1.3.3).

**Comment by SGChristianMP** [comment]
> I see docs here: https://hasura.io/docs/latest/graphql/core/auth/authentication/webhook.html
> mentioning passing of variables to the Authentication Webhook, but is it actually implemented?
> 
> Trying from the Hasura Console it seems that only "headers" are passed to the Authentication Webhook (using Hasura v1.3.3).

Same experience here, I've been unable to get anything but headers.

**Comment by khan297** [comment]
F

**Comment by SGChristianMP** [comment]
> I see docs here: https://hasura.io/docs/latest/graphql/core/auth/authentication/webhook.html
> mentioning passing of variables to the Authentication Webhook, but is it actually implemented?
> 
> Trying from the Hasura Console it seems that only "headers" are passed to the Authentication Webhook (using Hasura v1.3.3).

This is only from v.2.0.0-alpha.1 apparently, documentation just doesn't state this.
