### ISSUE TITLE
Allow compressing all responses from Hasura via a server flag

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#2674]
The console, and I am sure some client apps, struggles with the quantum of data in `/v1/query` and `v1/graphql` responses with any decently sized schema. Allowing compression via a server flag/env var is required to smoothen this experience a bit.

To be researched: What's the impact on client-side tools like Apollo, urql, etc.? Do they handle this without any additional configuration and with what compression? Also, how useful is the compression?

**Comment by coco98** [comment]
The browser should take care of gzipped responses automatically, so I don't think this will impact graphql clients. @dsandip

**Comment by praveenweb** [comment]
Would like to have `brotli` with a fallback to `gzip` compression.

**Comment by Toub** [comment]
Duplicate of https://github.com/hasura/graphql-engine/issues/1253 ?
