### ISSUE TITLE
Support multiple Set-Cookie headers in remote schemas

### ISSUE THREAD

**Issue by macalinao** [hasura/graphql-engine#2688]
If my remote schema returns multiple Set-Cookie headers (as in the case of `cookie` and `cookie.sig` when using https://github.com/pillarjs/cookies) only one of the headers goes through.

Is there a way to fix this?

**Comment by tirumaraiselvan** [comment]
Sure, we will add this ASAP.

**Comment by macalinao** [comment]
is there an ETA on when this is going to be released? :smile:

**Comment by tirumaraiselvan** [comment]
@macalinao This has been fixed here https://github.com/hasura/graphql-engine/pull/2739 and should be out in the next release
