### ISSUE TITLE
add a `--goto` flag for migrate apply

### ISSUE THREAD

**Issue by joshainglis** [hasura/graphql-engine#2689]
Given an initial state of
```bash
$ hasura migrate status
VERSION        SOURCE STATUS  DATABASE STATUS
...
1564701126000  Present        Present
1564701547000  Present        Present
1564702123000  Present        Present
1564702123002  Present        Present
1564702123003  Present        Present
1564738682051  Present        Present
1564738682052  Present        Not Present
1564738682053  Present        Not Present
```
If I want to migrate back to `1564702123002`, I would expect to run: `hasura migrate apply --type down --version 1564702123002`

I would expect the resultant state to be:
```bash
$ hasura migrate status
VERSION        SOURCE STATUS  DATABASE STATUS
...
1564701126000  Present        Present
1564701547000  Present        Present
1564702123000  Present        Present
1564702123002  Present        Present
1564702123003  Present        Not Present
1564738682051  Present        Not Present
1564738682052  Present        Not Present
1564738682053  Present        Not Present
```

However, the actual resultant state is:
```bash
$ hasura migrate status
VERSION        SOURCE STATUS  DATABASE STATUS
...
1564701126000  Present        Present
1564701547000  Present        Present
1564702123000  Present        Present
1564702123002  Present        Not Present
1564702123003  Present        Present
1564738682051  Present        Present
1564738682052  Present        Not Present
1564738682053  Present        Not Present
```
The documentation currently says: `--version string        migrate the database to a specific version`
but it appears that using `--version` just applies the specific migration without the chain leading up to it.

Is this intended?
If so I think this may need some explicit documentation as it's a potentially dangerous operation breaking the migration chain.
It would also be nice to have an easy way of migrating to a specific migration version without needing to count migrations or loop, and the `--version` flag feels like the natural way of achieving this.

**Comment by shahidhk** [comment]
Thanks for bringing this to our notice @joshainglis.

The help message is indeed misleading. We'll fix it ASAP. It is a remnant from the `--goto` flag that we had earlier, which would have the expected behaviour where all the migrations leading up to that particular version is applied.

@arvi3411301 Can we introduce `--goto` and keep the behaviour of `--version` as it is?

**Comment by arvi3411301** [comment]
@shahidhk Ya we can add `--goto` flag.

```bash
hasura migration apply --goto [version] --type [up|down]
```

**Comment by hiovi** [comment]
a --goto flag would save a lot of time when setting up a project on a new machine. At the moment I cannot apply all migrations in one go as they run out of memory on execution. So applying all versions up to a specific one would help.
