### ISSUE TITLE
Support for users with multiple identity providers? 

### ISSUE THREAD

**Issue by mavenraven** [hasura/graphql-engine#2700]
Hi! First off, I think this is amazing project that has a lot of potential!

One use case that I'm worried about is a user that has linked their account with multiple identity provides, e.g. https://auth0.com/docs/link-accounts: 

```
{
  "email": "your0@email.com",
  "email_verified": true,
  "name": "John Doe",
  "given_name": "John",
  "family_name": "Doe",
  "picture": "https://lh3.googleusercontent..../photo.jpg",
  "gender": "male",
  "locale": "en",
  "user_id": "google-oauth2|115015401343387192604",
  "identities": [
    {
      "provider": "google-oauth2",
      "user_id": "115015401343387192604",
      "connection": "google-oauth2",
      "isSocial": true
    },
    {
      "profileData": {
        "phone_number": "+14258831929",
        "phone_verified": true,
        "name": "+14258831929"
      },
      "user_id": "560ebaeef609ee1adaa7c551",
      "provider": "sms",
      "connection": "sms",
      "isSocial": false
    }
  ],
  "user_metadata": {
    "color": "red"
  },
  "app_metadata": {
    "roles": [
      "Admin"
    ]
  },
  ...
}
 ```
If I wanted to handle this use case today [allowing to use their secondary provider as well], what would be the best way to handle it? Use jsonb for the user column?

**Comment by ecthiender** [comment]
@mavenraven I'm assuming you meant how to store the profile data of the user. As there are multiple providers, users' profile data schema can vary. 

It depends on your use-case.

I can think of 2 options:
1. As you already pointed out, you can use `jsonb`. Hasura has support for querying `jsonb` fields in the GraphQL query (https://docs.hasura.io/1.0/graphql/manual/queries/query-filters.html#jsonb-operators-contains-has-key-etc).

2. If you know all the providers before-hand and want to have a relational structure for your user data, then you can model all the possible fields (across all providers) and have a `provider` column.

**Comment by mavenraven** [comment]
Thanks @ecthiender . Can you give a bit more detail about option 2? Would I need to have those columns in every table that I'm doing RBAC on, or is there a way I could do a join to a provider like table?

**Comment by ecthiender** [comment]
Hi @mavenraven , sorry for the delay in response.

>  Can you give a bit more detail about option 2?

Let's say you have two providers: Google login and Mobile login. Then you can have a user table like so:
```
User:
  - user_id: text, primary key -> provider specific ID, so in Google it can be google_user_id, in mobile it can be phone number
  - provider: string (non-nullable) -> indicates which provider
  - google_specific_profile_col1
  - google_specific_profile_col2
  - mobile_specific_profile_col1
```
Then upon login to your identity provider, you can set the session variable `x-hasura-user-id` to be the provider specific ID. And you can have permission defined like:

```json
{"user_id":{"_eq":"x-hasura-user-id"}}
```

> Would I need to have those columns in every table that I'm doing RBAC on, or is there a way I could do a join to a provider like table?

No, you need to have columns only in your user table. Then you can define relationships to the user table from your other tables. And then you can use them in the permission. This is not different for your use-case, this is the common pattern in Hasura. (Check out related blogs: https://blog.hasura.io/access-control-patterns-with-hasura-graphql-engine/ , https://blog.hasura.io/tagged/authorization/)

Does this help? Let me know.

**Comment by marionschleifer** [comment]
I'm closing this issue. @mavenraven feel free to re-open if you have any more questions on this 🙂

**Comment by mavenraven** [comment]
Just to follow up on this, this is what I was actually looking for https://docs.hasura.io/1.0/graphql/manual/auth/authorization/permission-rules.html#using-relationships-or-nested-objects
