### ISSUE TITLE
Support relationship value for column preset

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#2705]
Currently there're only two kinds of column presets: from static value or from session variables.

This feature request allows setting column preset from relationship value.

For example, if we have the following relationship:

```
school {
  id
  district { 
    id
    province {
       id
    }
  }
}
```
The `users` table has `school_id` , when creating new user, i'd love to set `district_id` and `province_id` from the relationship `school`, too.

**Comment by 0x777** [comment]
@revskill10 This cannot be done at graphql-engine's layer. You are better off using Postgres triggers for this which are ideal for such use cases.
