### ISSUE TITLE
update checker bottom-bar hiding the run button under sql tab

### ISSUE THREAD

**Issue by karthikvt26** [hasura/graphql-engine#271]
The update checker bottom bar is hiding the Run button on SQL page. PFA the screenshot of the same.

The update checker bar height need to be decreased a little and then proper CSS need to be added for it not to cover any important content.

![screenshot 410](https://user-images.githubusercontent.com/25095884/43822165-ec8c2128-9b08-11e8-8293-bc7072d52db2.jpg)

**Comment by akash1997** [comment]
I would like to work on this.

**Comment by michizhou** [comment]
Hi @shahidhk, do you mind if I have a go at it? Also, do you have any preferences for how the CSS element should be formatted on the webpage? Let me know!

**Comment by shahidhk** [comment]
@michizhou It should appear as a footer, not overlaying anything. @karthikvt26 Can provide specific info.

**Comment by michizhou** [comment]
@karthikvt26 Could you provide some more context on the repo path for the file that contains the CSS elements for the SQL tab you referenced in the issue description? I would also appreciate having other important information that could help me with tackling this issue. Thanks!

**Comment by sdabhi23** [comment]
@shahidhk @karthikvt26 any suggestions on how I can reproduce the issue to test if the CSS fix is working?

**Comment by akshitbhalla** [comment]
Hi, I came across this issue while working with the graphql-engine myself and have been working on a fix too. 

Is it alright if I go ahead and make a pull request for the same?

**Comment by akshitbhalla** [comment]
Okay, I'm going ahead and making the pull request so you can all see the changes I made to the repo.

[This is a link](https://codesandbox.io/s/34m0qm93vm) to the sandbox in which I was trying to replicate the issue and fix it.

**Comment by akshitbhalla** [comment]
@karthikvt26 @michizhou I couldn't help but notice that you raised a pull request 5 hours after I raised mine against this issue, with the same code changes. 

What's going on?

**Comment by shahidhk** [comment]
@akshitbhalla @michizhou Don't worry about that, we'll figure this out.

**Comment by akshitbhalla** [comment]
Okay, thanks for the response.
