### ISSUE TITLE
List of Hasura Footprints

### ISSUE THREAD

**Issue by mnlbox** [hasura/graphql-engine#2711]
Can you guide me how to detect from footprints that one app is using Hasura?
I want a list of Hasura footprints.
For example, one way is check the Query/Mutation function name conventions, or the other is to check the token JWT content (for example the `x-hasura` prefix)
Is any tools like [wappalyzer](https://www.wappalyzer.com) available for detect Hasura back-ends now?

**Comment by marionschleifer** [comment]
@mnlbox what exactly do you mean with "Hasura footprints"? Can you elaborate please?

**Comment by marionschleifer** [comment]
@mnlbox I'm closing this issue. Feel free to re-open if you have anything to add 🙂
