### ISSUE TITLE
componentWillReceiveProps  warning

### ISSUE THREAD

**Issue by ZBr14n** [hasura/graphql-engine#2714]
Hello, I was able to compile and run this boilerplate nextjs-postgres-graphql, but when I inspect the console, it is throwing a warning. How do I resolve this?

https://github.com/hasura/graphql-engine/tree/master/community/sample-apps/nextjs-postgres-graphql

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Query

![image](https://user-images.githubusercontent.com/5561950/62834676-d2e7f080-bc1d-11e9-92b8-1249a9dbb97e.png)

**Comment by marionschleifer** [comment]
@ZBr14n thank you for reporting this. This is a deprecation warning because of using a newer version of React. We will update this in the boilerplate and let you know 🙂
