### ISSUE TITLE
[optimisation] select only required columns on sql

### ISSUE THREAD

**Issue by jjangga0214** [hasura/graphql-engine#2716]
Hi, 

I found a behavior that can be possibly easily optimized. 

Let's say I have a table named `article` and it has 100 columns including `id`. I wanted to query `id` of every articles, so I requested like this. 
 
```gql
query {
  article {
    id
  }
}
```

And the executed query is like this. 

```sql
SELECT
  coalesce(json_agg("root"), '[]') AS "root"
FROM
  (
    SELECT
      row_to_json(
        (
          SELECT
            "_1_e"
          FROM
            (
              SELECT
                "_0_root.base"."id" AS "id"
            ) AS "_1_e"
        )
      ) AS "root"
    FROM
      (
        SELECT
          *
        FROM
          "public"."article"
        WHERE
          ('true')
      ) AS "_0_root.base"
  ) AS "_2_root"
```

The problem is that it selects every columns `*`.

```sql
SELECT
  *
FROM 
  "public"."article"
```

And it actually could and should select columns only requested from a client, like this. 

```sql
SELECT
  id
FROM 
  "public"."article"
```

This might be a quite considerable performance problem in some cases. For example, my table `article` has 100 columns. So, the simple query only searching for one column `id` actually results 100 times higher IO, memory usage, and time on the database than expected. 

If resolving this is not as easy as users might think, then let me know how I can help, in a concrete way, so that I might make a PR if my time is applicable. Or If I misunderstood about how postgres would work with the sql, I'd be thankful if letting me know it as well!

**Comment by 0x777** [comment]
Postgres treats
```sql
select id from article;
```
and 
```sql
select id from (select * from article) a;
```
as the same as can be seen from their plans:
```
=# explain select id,name from article;
                        QUERY PLAN                         
-----------------------------------------------------------
 Seq Scan on article  (cost=0.00..80.05 rows=3505 width=20)
(1 row)

=# explain select id,name from (select * from article) q;
                        QUERY PLAN                         
-----------------------------------------------------------
 Seq Scan on article  (cost=0.00..80.05 rows=3505 width=20)
```

This optimisation is called 'projection pushdown' and almost all databases do this. I can't find a reference in official postgres docs but [this](https://modern-sql.com/feature/with/performance) seems to suggest that it has been part of Postgres since 9.0.

**Comment by jjangga0214** [comment]
@0x777 Great to know that! Thank you :)

**Comment by jjangga0214** [comment]
@0x777  Then what if docs mentions about this for making users feel certain? For example, some manually written graphql APIs do select unnecessary columns, and if users know hasura solves the issue, it could be helpful for them to decide using hasura.

**Comment by jjangga0214** [comment]
@0x777 May I ping?

**Comment by marionschleifer** [comment]
@jjangga0214 sorry for the delay in response.

Hasura GraphQL engine does not have any resolvers. The Hasura GraphQL engine is actually a compiler that compiles your GraphQL query into a very efficient SQL query.

Hasura’s GraphQL syntax is also optimized to expose the power of the underlying SQL so that you can make powerful queries via GraphQL.

**Comment by jjangga0214** [comment]
@marionschleifer Uh.. no. Thank you for the response, but you misunderstood what I meant. 

> For example, some manually written graphql APIs do select unnecessary columns

This means, literally, many people write resolvers that selects columns even not requested from client. For example, when there's a query `articles`, which selects every articles, then a resolver for Article would like this. 
```js
const resolvers = {
  Query: {
    articles: () => sql('SELECT * from article')
  },
  Article: {
    id: (parent) => parent.id,
    title: (parent) => parent.title,
    content: (parent) => parent.content,
  }
}
```
A resolver chain is a tree, which seperates field resolvers from sql. This typically results in selecting every columns. People do know its inefficiency. However, this is easy and they don't care micro optimization in many cases. But this can become a problem when working with a table with lots of (more than a hundred) columns. 

> and if users know hasura solves the issue, it could be helpful for them to decide using hasura.

So, if people with the problem understand hasura guarentees selecting only requested columns, then they might be able to easily decide to use hasura. 

> What if docs mentions about this for making users feel certain?

That's why I suggested explicitly mentioning this fact("hasura only select columns requested from graphql query, as it's a graphql compiler to sql.") would be good.

**Comment by marionschleifer** [comment]
@jjangga0214 thank you for clarifying. I just edited my previous comment and now I've seen that you clarified. Sorry for the confusion 🙏 

Yes, we'll definitely add it to the documentation. Thank you again for your input!
