### ISSUE TITLE
improve the UI for ErrorBoundary

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#272]
Make a common error component and render that whenever an error is caught.

**Comment by praveenweb** [comment]
[ErrorBoundary](https://github.com/hasura/graphql-engine/blob/master/console/src/components/App/ErrorBoundary.js) is implemented at the global level.

What we can do is, improve the UI and show the error message neatly instead of returning `Something went wrong` message.

**Comment by thangngoc89** [comment]
@praveenweb ErrorBoundary is like try..catch. the closer to the error location, the more accurate error report you can provide.

**Comment by AnnieAtHasura** [comment]
Reproduction steps (Via Rikin):
Edit the table name in the url with something that doesnt exist. e.g. https://rikinsk-hge.herokuapp.com/console/data/schema/public/tables/booboo/browse

This does a weird 404 redirect before blowing up. Error handling in console is  quite depressing

**Observed**: taken to 404 page that says "something went wrong"

**Expected**:    ????


RikinSKToday at 7:24 AM
Hmm. We need to basically try and give an error message if we can find out whats wrong
and then lead the user to homepage maybe
In an ideal case a user should never see this page

**Comment by coco98** [comment]
Via @AnnieAtHasura 

**Reproduction steps (via @rikinsk ):**
1. Edit the table name in the url with something that doesnt exist. e.g. https://rikinsk-hge.herokuapp.com/console/data/schema/public/tables/booboo/browse
2. This does a weird 404 redirect before blowing up.

**Observed**: taken to 404 page that says "something went wrong"
**Expected**: ????

Via @rikinsk:
> Hmm. We need to basically try and give an error message if we can find out whats wrong
> and then lead the user to homepage maybe
> In an ideal case a user should never see this page

**Comment by AnnieAtHasura** [comment]
Note, I've just submitted a PR that actually fixes this per the original issue statement, but I suggest we either leave it open or make a macro issue to coordinate all the remaining issues with this area.
