### ISSUE TITLE
[cli] npm package

### ISSUE THREAD

**Issue by jjangga0214** [hasura/graphql-engine#2720]
My project is based on nodejs, and I think adding hasura cli as devDependency would be convenient for colleagues. Then they don't have to install hasura cli on their system, and `npm install` will only be needed.

I found <https://www.npmjs.com/package/hasura>. Was this planned but cancled?

**Comment by marionschleifer** [comment]
@jjangga0214 this package was not added by us. I now contacted the author and asked if he would transfer the package to us 🙂

**Comment by jjangga0214** [comment]
@marionschleifer I think it'd be convenient to publish npm hasura by wrapping hasura cli.

**Comment by jjangga0214** [comment]
I developed it. 

[jjangga0214/hasura-cli](https://github.com/jjangga0214/hasura-cli) is an npm package that automatically installs by detecting OS and wraps Hasura CLI binary in isolated manner. 

![hasura-cli](https://user-images.githubusercontent.com/28584151/65924503-fbbf8180-e427-11e9-95b3-785fad98e1c4.gif)

Now we can just add hasura cli to devDependency.

```bash
npm install --save-dev hasura-cli
# or
yarn add --dev hasura-cli
```

I'd be glad to get some feedback :)

**Comment by jjangga0214** [comment]
@simoneb 
@patcito 
@cos 
@marionschleifer 

I developed it. 

[jjangga0214/hasura-cli](https://github.com/jjangga0214/hasura-cli) is an npm package that automatically installs by detecting OS and wraps Hasura CLI binary in isolated manner. 

![hasura-cli](https://user-images.githubusercontent.com/28584151/65924503-fbbf8180-e427-11e9-95b3-785fad98e1c4.gif)

Now we can just add hasura cli to devDependency.

```bash
npm install --save-dev hasura-cli
# or
yarn add --dev hasura-cli
```

I'd be glad to get some feedback :)
