### ISSUE TITLE
[docker] cli-migrations

### ISSUE THREAD

**Issue by jjangga0214** [hasura/graphql-engine#2721]
In my opinion, integrating the feature of **cli-migrations** into plain `hasura/graphql-engine` is more simpler, yet makes sense as well. The thing `hasura/graphql-engine` would do more than now is just to check if `/hasura-migrations` contains valid migration files and execute them.

This solves a problem like this example as well. Assume I want to use the latest version of `hasura/graphql-engine` WITH `cli-migrations`. However both of `hasura/graphql-engine:latest.cli-migrations` and `hasura/graphql-engine.cli-migrations` are invalid. If `hasura/graphql-engine` just contains the auto migration feature, then simply using `hasura/graphql-engine:latest` would work.

**Comment by marionschleifer** [comment]
Closing this issue as outdated since we're focusing on our new Hasura version now. Check out the [getting started guide for Hasura DDN](https://hasura.io/docs/3.0/local-dev/). 

Feel free to re-open if this still causes an issue.
