### ISSUE TITLE
Support for persisted queries

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#273]
Via @sairam#2567 on discord, ben from cherre.

Support persisted queries to hide the raw queries from the client for performance/security reasons and also prevent information about the underlying postgres schema getting leaked.

**Comment by 0x777** [comment]
https://blog.apollographql.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5?gi=40b0ffd344c6
https://blog.apollographql.com/improve-graphql-performance-with-automatic-persisted-queries-c31d27b8e6ea
https://github.com/apollographql/persistgraphql/issues/66
https://github.com/apollographql/apollo-link-persisted-queries

**Comment by revskill10** [comment]
This should support persisted subscription also.

**Comment by BenHizak** [comment]
This would be a great feature to have. Thank you.

**Comment by thefliik** [comment]
I imagine hasura's allow-list could be re-purposed to help support this feature.

**Comment by Maxpain177** [comment]
Would be cool to see CDN caching[ like in ApolloServer](https://blog.apollographql.com/automatic-persisted-queries-and-cdn-caching-with-apollo-server-2-0-bf42b3a313de)

**Comment by jkossis** [comment]
@marionschleifer any plans on this becoming part of hasura's offering?

**Comment by alireza-ahmadi** [comment]
@marionschleifer Are there any updates on this?

**Comment by jozef-slezak** [comment]
Hasura 1.4 is able to save GraphQL queries therefore persisted queries could be easier to achieve. Is it right?

"The RESTified GraphQL API allows for the use of a REST interface to saved GraphQL queries and mutations."
https://github.com/hasura/graphql-engine/blob/master/CHANGELOG.md#rest-endpoints

**Comment by joanrodriguez** [comment]
Any news on that front?

**Comment by bbigras** [comment]
Any progress on this? :pray:

**Comment by bbigras** [comment]
@0x777 friendly ping

**Comment by braco** [comment]
For anyone searching for this, we went with Postgraphile for a project because of this missing feature.

https://github.com/graphile/persisted-operations

**Comment by Bessonov** [comment]
I'm not sure that it should be a part of any product. From my point of view it should be handled by something like a proxy. In this way it can be used with any product.

**Comment by deathemperor** [comment]
Would love to have this for an increased in performance!

**Comment by dameleney** [comment]
We understand your need for persisted queries comes from the fact that your CDNs can only cache responses to requests with a GET HTTP method, while standard GraphQL requests served by Hasura are made via the POST method.

We recommend using our [RESTified GraphQL endpoints](https://hasura.io/docs/latest/graphql/core/api-reference/restified/) which use a REST API interface and the GET method for saved GraphQL queries.

Persisted queries are a feature of Apollo and are not a part of the standard GraphQL Schema Definition Language and we’ll continue to assess the need to develop similar functionality as we get requests from other customers.

[RESTified GraphQL Endpoints API Reference | Hasura GraphQL Docs](https://hasura.io/docs/latest/graphql/core/api-reference/restified/)

**Comment by manasag** [comment]
We have also recently added support for automated persisted queries, same as what Apollo [supports](https://www.apollographql.com/docs/apollo-server/performance/apq/). Enable persisted queries using the environment variable `HASURA_GRAPHQL_ENABLE_PERSISTED_QUERIES `(`--enable-persisted-queries`) to `true` (default: `false`), and the query TTL in the cache store can be set using the environment variable `HASURA_GRAPHQL_PERSISTED_QUERIES_TTL` (`--persisted-queries-ttl`). This feature is available in EE version of Hasura only.

**Comment by deathemperor** [comment]
@manasag you've made my day! Been dreaming about this for a long time

**Comment by joanrodriguez** [comment]
> We have also recently added support for automated persisted queries, same as what Apollo [supports](https://www.apollographql.com/docs/apollo-server/performance/apq/). Enable persisted queries using the environment variable `HASURA_GRAPHQL_ENABLE_PERSISTED_QUERIES `(`--enable-persisted-queries`) to `true` (default: `false`), and the query TTL in the cache store can be set using the environment variable `HASURA_GRAPHQL_PERSISTED_QUERIES_TTL` (`--persisted-queries-ttl`). This feature is available in EE version of Hasura only.

Can't find anything about that in the docs.... When will we get this?

**Comment by deathemperor** [comment]
> This feature is available in EE version of Hasura only.

@joanrodriguez this is the keyword

**Comment by barbalex** [comment]
> This feature is available in EE version of Hasura only

Unfortunate for urql users, as that now uses GET queries by default: https://github.com/urql-graphql/urql/pull/3789.

Well, whatever the EE version is, as I don't know that name. But I guess that is not what we are using as we now get this error, after upgrading urql:
```
CombinedError: [GraphQL] PersistedQueryNotSupported
```
(we use `hasura/graphql-engine:v2.48.4` in docker)

**Comment by deathemperor** [comment]
> > This feature is available in EE version of Hasura only
> 
> Unfortunate for urql users, as that now uses GET queries by default: https://github.com/urql-graphql/urql/pull/3789.
> 
> Well, whatever the EE version is, as I don't know that name. But I guess that is not what we are using as we now get this error, after upgrading urql:
> ```
> CombinedError: [GraphQL] PersistedQueryNotSupported
> ```
> (we use `hasura/graphql-engine:v2.48.4` in docker)

EE stands for Enterprise Edition.

**Comment by timesy** [comment]
> > This feature is available in EE version of Hasura only
> 
> Unfortunate for urql users, as that now uses GET queries by default: [urql-graphql/urql#3789](https://github.com/urql-graphql/urql/pull/3789).
> 
> Well, whatever the EE version is, as I don't know that name. But I guess that is not what we are using as we now get this error, after upgrading urql:
> 
> ```
> CombinedError: [GraphQL] PersistedQueryNotSupported
> ```
> 
> (we use `hasura/graphql-engine:v2.48.4` in docker)

You can set `preferGetMethod: false` in `createClient` to have the old behaviour.

**Comment by barbalex** [comment]
> You can set preferGetMethod: false in createClient to have the old behaviour

Thanks so much!
