### ISSUE TITLE
Postgres query error after implement audit

### ISSUE THREAD

**Issue by hynra** [hasura/graphql-engine#2732]
Version: `v1.0.0-beta.4`

Steps to reproduce: 
  
  * Apply log audit with guide from [Documentation](https://docs.hasura.io/1.0/graphql/manual/guides/auditing-tables.html)

  * Audit a table: `select audit.audit_table('users');`

  * Run mutation via console: 

  ```graphql
  mutation {
    update_users(_set: {biography: "test"}, where: {email: {_eq: "test@mail.com"}}) {
      returning {
        biography
      }
    }
  }

  ```

  * Return error with the result:
  ```json
{
	"errors": [{
		"extensions": {
			"internal": {
				"statement": "WITH \"users__mutation_result_alias\" AS (UPDATE \"public\".\"users\" SET \"biography\" = $1  WHERE (('true') AND (((((\"public\".\"users\".\"email\") = ($2)) AND ('true')) AND ('true')) AND ('true'))) RETURNING * ) SELECT  json_build_object('returning', (SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_1_e\"  FROM  (SELECT  \"_0_root.base\".\"biography\" AS \"biography\"       ) AS \"_1_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"users__mutation_result_alias\" WHERE ('true')     ) AS \"_0_root.base\"      ) AS \"_2_root\"      ) )        ",
				"prepared": true,
				"error": {
					"exec_status": "FatalError",
					"hint": "No operator matches the given name and argument type(s). You might need to add explicit type casts.",
					"message": "operator does not exist: jsonb - text[]",
					"status_code": "42883",
					"description": null
				},
				"arguments": [
					"(Oid 25,Just (\"test\",Binary))",
					"(Oid 25,Just (\"test@mail.com\",Binary))"
				]
			},
			"path": "$",
			"code": "unexpected"
		},
		"message": "postgres query error"
	}]
}
  ```

After apply `audit` on a table, cannot operate `mutations`, but `query` is fine

**Comment by hynra** [comment]
I resolve this issue by adding compatibility in PostgreSQL 9.6 operation in `jsonb` - `text[]`. I also create pull request to `audit log` [repository](https://github.com/hasura/audit-trigger).

**Comment by 0x777** [comment]
This isn't an issue with graphql-engine. Closing this in favour of https://github.com/hasura/audit-trigger/issues/2.

**Comment by hynra** [comment]
There is no `issue` tab in https://github.com/hasura/audit-trigger before, so I created the issue here. Thanks.

**Comment by jpvx** [comment]
> I resolve this issue by adding compatibility in PostgreSQL 9.6 operation in `jsonb` - `text[]`. I also create pull request to `audit log` [repository](https://github.com/hasura/audit-trigger).

How did you make this work in 9.6?

**Comment by hynra** [comment]
@jpvx see this https://github.com/hasura/audit-trigger/pull/1
