### ISSUE TITLE
Sudden unexpected : permission denied for table hdb_schema_update_event

### ISSUE THREAD

**Issue by bkniffler** [hasura/graphql-engine#2733]
Hi, 
I'm using graphql-engine (beta.3) deployed via 1-button from your docs. It has been running nicely for a couple of weeks and I created a schema, inserted data etc. Now, all of a sudden, I'm getting the following error on admin console:

```
DB schema loading failed
unexpected : permission denied for table hdb_schema_update_event
{
    "statement": "\n             INSERT INTO hdb_catalog.hdb_schema_update_event\n               (instance_id, occurred_at) VALUES ($1::uuid, DEFAULT)\n             ON CONFLICT ((occurred_at IS NOT NULL))\n             DO UPDATE SET instance_id = $1::uuid, occurred_at = DEFAULT\n            ",
    "prepared": true,
    "error": {
        "exec_status": "FatalError",
        "hint": null,
        "message": "permission denied for table hdb_schema_update_event",
        "status_code": "42501",
        "description": null
    },
    "arguments": [
        "(Oid 25,Just (\"bbf93b41-cf33-437d-b099-0e23be9c2639\",Binary))"
    ]
}
```

I've cleared my browser cache and logged in again (I'm using a secret to protect the database instance), I've updated to beta.4, restart the dyno, nothing works. I've never touched the actual database, so I've no idea where this could come from all of a sudden.

**Comment by bkniffler** [comment]
Nevermind, this error pops up if the database exceeds the heroku limits :)

**Comment by ajjunaedi** [comment]
Hi @bkniffler, i have same issue too. Can you tell me how to fix this? Thank you.

**Comment by bkniffler** [comment]
Upgrade your Heroku database to a bigger tier or remove data.
