### ISSUE TITLE
[Feature request] Customize context URL

### ISSUE THREAD

**Issue by Toub** [hasura/graphql-engine#2744]
Is it possible to customize context url, so I can have something different from `/v1/graphql`, without using a proxy to rewrite the request.

Maybe by adding a custom context prefix (e.g. hasura): `/v1/graphql` => `/hasura/v1/graphql`

Useful to deploy to a domain hosting other services too.

**Comment by mnlbox** [comment]
I think an environment variable for endpoint url can be very useful.

**Comment by mnlbox** [comment]
@marionschleifer Any update on this feature?

**Comment by marionschleifer** [comment]
Closing this issue as outdated since we're focusing on our new Hasura version now. Check out the [getting started guide for Hasura DDN](https://hasura.io/docs/3.0/local-dev/). 

Feel free to re-open if this still causes an issue.
