### ISSUE TITLE
Feature request: persist headers setting in graphiQL tab

### ISSUE THREAD

**Issue by thangngoc89** [hasura/graphql-engine#275]
I think syncing the headers to localStorage is a reasonable choice.

**Comment by revskill10** [comment]
If Hasura uses a true `multi tab` interface, this will automatically get supported.

**Comment by akash1997** [comment]
I would like to work on it. Can you provide a little more clarity on the contents of header settings and perhaps some idea on how I may proceed with the solution. Thanks.

**Comment by karthikvt26** [comment]
@akash1997 header is an array of objects. Check [this](https://github.com/hasura/graphql-engine/blob/master/console/src/components/ApiExplorer/state.js#L3) out for info.

FYI this [function](https://github.com/hasura/graphql-engine/blob/master/console/src/components/ApiExplorer/Actions.js#L229) is used to update the header depending on dynamic data like `access-key`. 

Hope this helps.

**Comment by akash1997** [comment]
So, as I understand it, I have to modify all the header related functions so that add/select/edit/delete of headers is updated in the localStorage.

**Comment by karthikvt26** [comment]
So you need to come up with the list of cases where headers will be accessed/modified (add/select/edit/delete) from `localStorage`. 

One of the case where headers will be accessed is onLoad where the `request.headers` should be updated with all the headers stored in `localStorage`. And a case to modify will be whenever headers are added/deleted.

**Comment by karthikvt26** [comment]
@akash1997 Are you working on this issue?

**Comment by akash1997** [comment]
Yes @karthikvt26 Actually I'm done halfway through, just need some more time to complete it. I have my exams currently, so I will make a PR as soon as I'm done with the exams by next week.

**Comment by akash1997** [comment]
@karthikvt26 I'm facing some difficulty understanding [this](https://github.com/hasura/graphql-engine/blob/5e1eec80180bef692c9b2f2cea50174dfc29fee7/console/src/components/ApiExplorer/Actions.js#L586). Rest part is almost done. Can you help me out in understanding what is done here. Thanks.

**Comment by karthikvt26** [comment]
@akash1997 It removes the appropriate header value from the state. Could you also provide how you have planned to solve this?
