### ISSUE TITLE
restoring from a digital ocean droplet snapshot

### ISSUE THREAD

**Issue by R-D-P** [hasura/graphql-engine#2750]
Creating a digital ocean droplet using a snapshot of an existing droplet running hasura graphql engine results in a fresh install instead of using the information in the dockercompose.yaml file of the snapshot.

**Comment by TAnas0** [comment]
I can confirm experiencing the same behavior on Digitalocean

**Comment by shahidhk** [comment]
requires https://github.com/hasura/do-marketplace/issues/1

**Comment by shahidhk** [comment]
Close when the latest snapshot is published on digitalocean: `hasura-marketplace-snapshot-1578731957`

**Comment by shahidhk** [comment]
Request submitted to update the image.

**Comment by shahidhk** [comment]
Image is updated.
