### ISSUE TITLE
[GraphiQL Online] View in Voyager doesn't work

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [hasura/graphql-engine#2758]
Just tested after this feature has been implemented via #2737. And… it doesn't work.

![screenshot](https://user-images.githubusercontent.com/7892779/63380487-55e81400-c39f-11e9-844b-f6a49f2eba44.png)

Maybe, ZEIT hosting configuration issue.

**Comment by praveenweb** [comment]
@FluorescentHallucinogen - Hey, tested this. Works fine locally. It's a Zeit serverless deployment configuration issue. Will push a fix.

**Comment by praveenweb** [comment]
This has been fixed now.
