### ISSUE TITLE
Add support to drop metadata inconsistency to the CLI

### ISSUE THREAD

**Issue by hafizio** [hasura/graphql-engine#2766]
Right now the only way to drop metadata inconsistency is by using the REST API (https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/manage-metadata.html#drop-inconsistent-metadata), it'd be ideal if this feature can be supported in the CLI (e.g `hasura metadata ...`)

**Comment by pradeepmurugesan** [comment]
I can work on this 👍

**Comment by marionschleifer** [comment]
@pradeepmurugesan that is great 🙂 I assigned you to the issue. Let us know if you have any questions.

**Comment by pradeepmurugesan** [comment]
@marionschleifer Hello. can you kindly help me to simulate an inconsistent metadata for testing out the command..

**Comment by marionschleifer** [comment]
@pradeepmurugesan sure 🙂 

1. You can create permissions on a column in the console
2. You delete the column directly in Postgres (not on the console)
3. Then your metadata will show as inconsistent

**Comment by pradeepmurugesan** [comment]
Yes.. I figured that out.. was thinking more about integration test setup..

**Comment by shahidhk** [comment]
```
hasura metadata inconsistency list
hasura metadata inconsistencies list
hasura metadata ic list

hasura metadata ic drop
```

**Comment by RodolfoSilva** [comment]
> Yes.. I figured that out.. was thinking more about integration test setup..

Hey @pradeepmurugesan did you have figured out more about integration test setup?
