### ISSUE TITLE
ra-data-hasura: lazy header

### ISSUE THREAD

**Issue by heyrict** [hasura/graphql-engine#2771]
Currently, updating cookie or localStorage in authProvider will not update the headers in `hasuraDataProvider` in `ra-data-hasura`.

Since header contents can have authentication information stored in cookies or localStorage sometimes, may be we can add a callable as the `headers` argument aside from a constant object. Using `httpClient` similar to simpleRestProvider [described here](https://marmelab.com/react-admin/Authentication.html#sending-credentials-to-the-api) as the second argument is also acceptable.

**Comment by shahidhk** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/0a64ef99b5ab9d4968de241a1166ab9024e6d261
