### ISSUE TITLE
escaping \n inside TEXT field

### ISSUE THREAD

**Issue by dijam** [hasura/graphql-engine#2774]
I have a text field that contains `\n`. When I access my data via Hasura, it adds extra slash to it resulting: `\\n`.
I tried couple of ways to work around it like adding `/\n` but that resulted to `/\\n`.
All I need to have my text exactly the way I inserted but I assume as you convert value to json friendly, it escapes.
Any idea how I can work around it? (Not sure if it is intended or a bug)

**Comment by 0x777** [comment]
@dijam This is as per to the json spec, `\n` has to be escaped as `\\n`. Any library which lets you read a json string as a native string will automatically un-escape it to `\n`. i.e, you'll only see `\\n` in the raw response.

**Comment by dijam** [comment]
@0x777 Totally understand. I assumed the same. 
I think there are some replacements happening when Hasura loads data from DB for the first time it boots up. I do not have the same issue if I insert data with mutation and everything seems natural and it encode and decodes fine.

**Comment by dijam** [comment]
Step 1: Create a table with TEXT field inside

```
CREATE SCHEMA test;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE test.mytable (
  id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
  title TEXT NOT NULL,
  description TEXT
);

INSERT INTO test.mytable (title, description)
  VALUES ('title1', 'Some text bla bla bla \n\n and some other');
```


Step 2: Connect hasura and run the console. Do a query like this:

```
{
  test_mytable {
    id
    title
    description
  }
}

```
which results to:
```
{
  "data": {
    "test_mytable": [
      {
        "id": "5488565f-3990-44d7-8258-08158cb67d05",
        "title": "title1",
        "description": "Some text bla bla bla \\n\\n and some other"
      }
    ]
  }
}
```

If I use Hasura console and do a mutation like this:
``` 
mutation {
  update_test_mytable(where: {id: {_eq: "5488565f-3990-44d7-8258-08158cb67d05"}}, _set: {description: "Some text bla bla bla \n\n and some other"}) {
    returning {
      id
      description
    }
  }
}
``` 

will return desired results of:
```
{
  "data": {
    "update_test_mytable": {
      "returning": [
        {
          "id": "5488565f-3990-44d7-8258-08158cb67d05",
          "description": "Some text bla bla bla \n\n and some other"
        }
      ]
    }
  }
} 
```

**Comment by dijam** [comment]
aaa, true :) Thanks for the fast response. That explains a lot 💯

**Comment by yogeshwar607** [comment]
> Ah—the issue you’re having is that Postgres does not support `\n` escapes in ordinary string literals (because SQL does not). So when you write
> 
> ```sql
> INSERT INTO test.mytable (title, description)
>   VALUES ('title1', 'Some text bla bla bla \n\n and some other');
> ```
> 
> you’re actually inserting a string with the character sequence “backslash n backslash n” into your database, not a string with newlines. If you want to include newlines in string literals, you can use [“‘escape’ string constants,”](https://www.postgresql.org/docs/11/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS-ESCAPE) which are prefixed with the letter `E`. For example,
> 
> ```sql
> INSERT INTO test.mytable (title, description)
>   VALUES ('title1', E'Some text bla bla bla \n\n and some other');
> ```
> 
> will do what you want.

How we do it in hasura query ?
