### ISSUE TITLE
Mutation with variable declaration and with no variable JSON attached deletes all table records

### ISSUE THREAD

**Issue by matjazrak** [hasura/graphql-engine#2785]
Hello,
I have a **cost** table defined (**Hasura v1.0.0-beta.4**) with two fields:

id: Integer
description: Text

If I run the mutation on cost table with variable ID declaration:

mutation ($ID: Int) {
  delete_cost(where: {id: {_eq: $ID}}) {
    returning {
      id
    }
  }
}

and no variable JSON is attached, the mutation **deletes ALL RECORDS** in the table cost.
It should not delete any records.

**Comment by matjazrak** [comment]
Hi @leoalves,

thank you for your feedback. I agree with the others: the {} should be treated as NULL and not as %. (I’m comming from T-SQL world :)).

Kind regards, Matjaz

**Comment by marionschleifer** [comment]
I'm closing this in favour of https://github.com/hasura/graphql-engine/issues/704.
