### ISSUE TITLE
Large text loading in user interface 

### ISSUE THREAD

**Issue by nyamba** [hasura/graphql-engine#2796]
It's taking long time when I select column which has large text data. It's loading all data for displaying. Can we make it selecting only some of them when showing table data which has too big data column.

**Comment by rikinsk13** [comment]
@nyamba Can you let us know how large the text you are storing actually is? It will help understand the root problem better.

Your feature request is already being tracked in #2168.

**Comment by nyamba** [comment]
Hello @rikinsk13, we a table for storing book information. This is including text column which store all text of that book. So when I click that table it's taking long over 1 minute and looks like loading 8.5MB data to show that table for first time. 
About #2168, even I hide that column, it's taking long time to go to next page of the table.

**Comment by rikinsk13** [comment]
Thanks for the info @nyamba . #2168 will let you choose which columns to fetch from the DB. That should resolve your issue. We will try to prioritize it to be taken up soon.

**Comment by rikinsk** [comment]
Closing in favour of #2168
