### ISSUE TITLE
where: {key: {_in: ["string"]}} results in _type "_text[]" does not exist

### ISSUE THREAD

**Issue by datakurre** [hasura/graphql-engine#2797]
After updating v1.0.0-beta.2 to v.1.0.0-beta.5 seemingly all GraphQL queries with `_in`-filters for text array columns started failing with error

```
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "constraint-error"
      },
      "message": "type \"_text[]\" does not exist"
    }
  ]
}
```

I'm sorry that I don't have more detailed report yet, nor I have manage to reproduce this from scratch.

**Comment by leoalves** [comment]
@datakurre,

v1.0.0.beta.3 had some breaking changes with _in queries.
https://github.com/hasura/graphql-engine/releases/tag/v1.0.0-beta.3

If you can post your query and the variables your are using. I might be able to check if it is related to this change or not.

Cheers

**Comment by datakurre** [comment]
Thanks. I’m quite sure my issue is that... will report back and the change seems reasonsble.

**Comment by Israel-Laguan** [comment]
Also new release `beta-6` was incompatible with `beta-5`.

**Comment by datakurre** [comment]
Unfortunately, i was still unable to make `_in` queries work. This is a minimal query (even without use of variables) that fails for column with `text[]`type

```graphql
{
  MyResource(
    where: {ids: {_nin: ["foobar"]}}) {
    ids
  }
}
```

**Comment by datakurre** [comment]
Oh, but that query does not make sense, does it? My table has column of `text[]` and I want to query for rows where that column contains a certain value. Most probably `_in` worked for that just by accident before beta.3 and should really be doing something completely different.

**Comment by datakurre** [comment]
So, we were doing something unsupported and that worked just by accident. My current workaround is a custom operator allowing us to use `where: {ids: {_eq: "id"}}`. We could probably also use JSONB column instead of text[] to be able to use JSON operators.

Thanks a lot for help with this. Now I close this as "invalid".
