### ISSUE TITLE
Boolean dropdown on console not wokring

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#2798]
When trying to change the value of a boolean field in the console, the dropdown doesn't work. It has to be inserted by typing.

Browser: Chrome 76

![logging](https://media.giphy.com/media/kfdcOKp77Z0EmtajaV/giphy.gif)

**Comment by mnlbox** [comment]
I have same issue with Firefox 68.0.2

**Comment by rikinsk13** [comment]
closed via #2765
