### ISSUE TITLE
"unexpected variables in variableValues" on every relation query

### ISSUE THREAD

**Issue by codepunkt** [hasura/graphql-engine#2806]
I've added relations to my schema, and every query that i run with these relations gets this error:
`unexpected variables in variableValues`

What can i do?

**Comment by shahidhk** [comment]
Can you share the query, variables, and the exact error response?

**Comment by codepunkt** [comment]
sure thing! 👍 

query:
```graphql
{
  b {
    a {
      id
    }
  }
}
```

no variables.

error response
```json
{
  "errors": [
    {
      "extensions": {
        "path": "$.variableValues",
        "code": "validation-failed"
      },
      "message": "unexpected variables in variableValues: products"
    }
  ]
}
```

**Comment by codepunkt** [comment]
I'm confused. There were variables in there from a previous query, but graphiQL didn't show them.
Deleting them solved my problem 🤣
