### ISSUE TITLE
Native Postgres enum types is not working now.

### ISSUE THREAD

**Issue by OLDIN** [hasura/graphql-engine#2807]
Graphql enum types is not generated automatically.

**postgres enum type:**
`CREATE TYPE "public"."discount_type_enum" AS ENUM ('percent', 'equal', 'minus');`

**Expected graphql enum:**
```
enum discount_type_enum {
   percent
   equal
   minus
}
```
**Found graphql type:**
`scalar discount_type_enum`

![image](https://user-images.githubusercontent.com/15104330/64063703-80886700-cc00-11e9-9f95-fc4edd6998eb.png)

**Versions:**

- hasura/graphql-engine: hasura/graphql-engine:v1.0.0-beta.6 (docker)
- postgres: postgres:10.3-alpine (docker)

**Comment by dsandip** [comment]
Hi @OLDIN, GraphQL enums are not generated for Postgres enums by design. This has been documented in the [docs](https://docs.hasura.io/1.0/graphql/manual/schema/enums.html) and in the [PR](https://github.com/hasura/graphql-engine/pull/2672).
