### ISSUE TITLE
Questions about the many-to-many documentation

### ISSUE THREAD

**Issue by Albert-Gao** [hasura/graphql-engine#2808]
https://docs.hasura.io/1.0/graphql/manual/schema/relationships/database-modelling/many-to-many.html

>Array relationship, `tag_articles` from `tag` table using `article_tag :: tag_id -> id`

1. Where is this `tag_articles` been referred? I know there is an `article_tag` bridge table, but not sure about this `tag_articles`, isn't `article_tag` been enough to represent the relationship here? Why do we need to add another table? What is the design for this?

2. For this `article_tag` table, why do we need `id`, can't we just use `article_id` and `tag_id` as a composite primary key?

Don't know what I am missing here, I use NoSQL too long, so ask to make sure I am on the right track?

**Comment by marionschleifer** [comment]
Hi @Albert-Gao 👋 

1. Please note that we are talking about the name of the relationship here, not the bridge table. So from the point of the `article` table, we have an array relationship to the `article_tag` table, which we call `article_tags`. From the `tags` table, we have an array relationship to the `article_tag` table, which we call `tag_articles`. The following query illustrates that `tag_articles` is used to access articles for a tag.

```
{ tag {tag_articles { article {} }}}
```

Both relationships refer to the same bridge table.

2. You are correct, it's not necessary to add an `id` to a bridge table. You can use a composite primary key, which is indeed neater. I will update this in the docs.

Let me know if something is not yet clear 🙂

**Comment by Albert-Gao** [comment]
@marionschleifer 

Ah. it is a hasura-`relationship`, I thought it is the bridge table, now it makes sense.
Thanks for the answer!
