### ISSUE TITLE
Possibility to ignore some tables of the schema by server configuration on the GUI

### ISSUE THREAD

**Issue by sebathi** [hasura/graphql-engine#2815]
I have some tables that are for the oauth that share my database (the database is also used for a regular and simple mvc app for user management / reporting).

I think something like HASURA_IGNORED_TABLES=user_logins,oauth_clients,.... etc

Thanks for this great framework

**Comment by shahidhk** [comment]
@sebathi Can you not track these table? If you don't track them, they won't appear anywhere in the GraphQL Schema.

**Comment by marionschleifer** [comment]
@sebathi just checking in if you have been able to solve this problem? 🙂 if yes, we can close the issue.

**Comment by marionschleifer** [comment]
I'm closing this. @sebathi feel free to re-open if you would like to add something 🙂
