### ISSUE TITLE
citext being cast to text

### ISSUE THREAD

**Issue by shanetierney** [hasura/graphql-engine#2818]
I have several citext columns and because I was not getting expected results for a query, I analyzed the SQL and it was casting my citext column to case-sensitive text type. Obviously this defeats the purpose of having a case insensitive field.

**Comment by 0x777** [comment]
@shanetierney We do not do any `citext` to `text` casting at graphql-engine layer. What you are seeing is probably something that is implicitly done by Postgres? Can you post your table schema, query, expected and actual output?

**Comment by marionschleifer** [comment]
@shanetierney any update on this? 🙂

**Comment by marionschleifer** [comment]
I'm closing this issue. @shanetierney feel free to re-open if you'd like to add anything to it 🙂

**Comment by romcok** [comment]
Hi, I have a problem with citext in Hasura. Hasura is casting slug value to a string and I get an empty result.

This is working with a raw query: 

> SELECT * FROM users WHERE slug='johndoe'
> SELECT * FROM channels WHERE slug='zollo'::citext

But hasura is doing something like this and I get an empty result:

> SELECT * FROM users WHERE slug='johndoe'**::text**

So, how to make a case insensitive condition?

**Comment by 0x777** [comment]
@shanetierney @romcok Can you share the table's schema, the query that you are running and the expected results?

**Comment by marionschleifer** [comment]
I'm closing this. Feel free to re-open if there is anything to add to this 🙂

**Comment by kpala** [comment]
Having the same issue. We have a `citext` username field which works nicely with raw SQL queries. Using the GraphiQL tool in Hasura console shows the the following info in Analyze view:

Generated SQL:

```
SELECT
  coalesce(json_agg("root"), '[]') AS "root"
FROM
  (
    SELECT
      row_to_json(
        (
          SELECT
            "_1_e"
          FROM
            (
              SELECT
                "_0_root.base"."id" AS "id"
            ) AS "_1_e"
        )
      ) AS "root"
    FROM
      (
        SELECT
          *
        FROM
          "user"
        WHERE
          (
            ("user"."username") = (('Test') :: text)
          )
      ) AS "_0_root.base"
  ) AS "_2_root"
```

Execution plan:

```
Aggregate  (cost=10.64..10.65 rows=1 width=32)
  ->  Seq Scan on "user"  (cost=0.00..10.62 rows=1 width=4)
        Filter: ((username)::text = 'Test'::text)
  SubPlan 1
    ->  Result  (cost=0.00..0.01 rows=1 width=32)
```

I.e. as @romcok mentioned, the generated SQL treats the columns as text instead of as citext.

Currently, I'm considering to use `_ilike` as a workaround but we should be able to use the equality comparison here.
