### ISSUE TITLE
Introspection fails without select permission for enum type.

### ISSUE THREAD

**Issue by vlandres** [hasura/graphql-engine#2820]
When trying out the new enum type in beta.6 I stumbled upon an issue that for non-admin role the introspection fails when the role has no select permission for the role. When trying to query the enum with a role that has no select permission I got an error `type info not found for: 'some_enum'`. This also leads to an empty explorer / schema in Hasura console when x-hasura-role is used.

I'm not sure what the solution to the problem is as the enum type is not indeed defined for that role, but maybe just add a note to documentation that select permission has to be defined on the enum for relevant roles.

Thanks for the awesome product.

**Comment by lexi-lambda** [comment]
This sounds like it’s just a bug. We should still generate the enum type even if the enum table itself isn’t selectable by the current role if there are any selectable columns that reference the enum table.

**Comment by cantaspinar** [comment]
I was messing around with the explorer to check permissions for non admin roles but as @vlandres said, explorer in the console was empty. I was about to freak out when I also realised that I had to give select permissions to enum tables.
