### ISSUE TITLE
upgrading from alpha45 to beta.6 fails

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#2826]
You'll need to first upgrade to `beta.5` and then upgrade to `beta.6`. The reason why this doesn't work has very little to do with `beta.6`. The root cause is the catalog migrations which add admin metadata using `yaml` files (an RQL query); these `RQL` queries require schema cache to run but building schema cache could fail because the function which does this assumes the latest catalog's schema. 

The conclusion is that we can't use RQL queries in catalog migrations and we'll need to rewrite these migrations using only SQL. 

This happened earlier too in one of the `alpha` versions.

**Comment by lexi-lambda** [comment]
FWIW, we’d have seen this issue much earlier if we initialized the schema and metadata by running every migration rather than using the separate `initialize.sql` and `hdb_metadata.yaml` files.

**Comment by codeithuman** [comment]
I ran into this issue as well when upgrading from `alpha40` to `beta.6`.
