### ISSUE TITLE
Question: recommended approach to save data from back end

### ISSUE THREAD

**Issue by rrjanbiah** [hasura/graphql-engine#2828]
When saving data from back end, what is the recommended approach?

Directly saving in Postgres using ORM or so. 

Or

Saving through Hasura.

TIA

**Comment by 0x777** [comment]
It depends on your use case. You can use `hasura` as an ORM if it works for you. In cases where you have to deal with complex transactions you might want to use an ORM.

**Comment by rrjanbiah** [comment]
@0x777 Thank you so much for your quick reply. Just wanted to check if it is OK to bypass Hasura layer
