### ISSUE TITLE
[ Tbale ] have mismatch with current graphql schema. HINT: Types must be same

### ISSUE THREAD

**Issue by The-planet** [hasura/graphql-engine#2832]
hello everyone
This problem occurred when I tried to track existing data tables from the database and then add my own business logic from the remote schema. Why is that?

**Comment by tirumaraiselvan** [comment]
This error implies that there is a type conflict. Ther might already be a type named `Tbale` coming from your database (is there a table called `Tbale`? ) and also the same type (with different schema) in your remote schema (have you defined `type Tbale` in your schema). Can you confirm this is the case?

**Comment by marionschleifer** [comment]
@The-planet any update on this? Otherwise we can close the issue 🙂

**Comment by marionschleifer** [comment]
I'm closing this issue. @The-planet feel free to re-open if you'd like to add anything to it 🙂

**Comment by celvin** [comment]
When adding another hasura engine as remote schema:

When you have same table name in local and remote schema:


 HINT: Types must be same.",
        "type": "remote_schema"
    }
]
