### ISSUE TITLE
Where is cli-hasura-windows-amd64.exe

### ISSUE THREAD

**Issue by ChineseHero** [hasura/graphql-engine#2833]
I`m come https://docs.hasura.io/1.0/graphql/manual/hasura-cli/install-hasura-cli.html url(I need cli-hasura-windows-amd64.exe), but I not see. please tell me,Where is it?
I couldn't find it on the “https://github.com/hasura/graphql-engine/releases” page.

**Comment by shahidhk** [comment]
You can find it under "Assets" section for each release.

Here is a direct link: https://github.com/hasura/graphql-engine/releases/download/v1.0.0-beta.6/cli-hasura-windows-amd64.exe

**Comment by ChineseHero** [comment]
thank you
