### ISSUE TITLE
'default' radio button is disabled for identity columns

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#2840]
Create a table as follows:
```sql
CREATE TABLE public.page (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL
);
```
Head to insert row and try to insert data into it, you see that the 'default' is disabled:

![image](https://user-images.githubusercontent.com/6562944/64405943-21ae6c00-d09e-11e9-968f-a73a33df4a87.png)

If I try to insert data, I'll see this error:
```json
{
    "statement": "...",
    "prepared": true,
    "error": {
        "exec_status": "FatalError",
        "hint": "Use OVERRIDING SYSTEM VALUE to override.",
        "message": "cannot insert into column \"id\"",
        "status_code": "428C9",
        "description": "Column \"id\" is an identity column defined as GENERATED ALWAYS."
    },
    "arguments": [
        "(Oid 0,Just (\"\",Text))",
        "(Oid 25,Just (\"hello\",Binary))"
    ]
}
```
If you edit the radio button and enable it you can insert into this table. I'm guessing the console disables the `default` radio button if it can't find a default value for columns. With identity columns, there is no default as such. I guess we can always enable the `default` radio button in the console.

**Comment by HelloEdit** [comment]
Thanks so much
