### ISSUE TITLE
Timestamp without time zone column offers no options in permission builder

### ISSUE THREAD

**Issue by benkimpel** [hasura/graphql-engine#2842]
Issue noticed on...
v1.0.0-beta.4
v1.0.0-beta.6

postgres server 11.2

I had hoped to build a permission to only allow access when this column is not null, but I'm unable to do so.

Is it something to do with the column type of `timestamp without time zone`? Is this expected?

![Screenshot from 2019-09-06 12-06-04](https://user-images.githubusercontent.com/3131496/64446574-c3ce5400-d09e-11e9-843f-128b9e3c7cb5.png)

**Comment by benkimpel** [comment]
Ok, I manually created the filter in the `metadata.json` and imported it. The filter works when present, so I believe this is just a UI issue.

![Screenshot from 2019-09-06 12-37-21](https://user-images.githubusercontent.com/3131496/64448374-26c1ea00-d0a3-11e9-8bf2-37aff90a1725.png)

![Screenshot from 2019-09-06 12-27-45](https://user-images.githubusercontent.com/3131496/64448377-29bcda80-d0a3-11e9-92cf-567fd6c97e5e.png)

**Comment by benkimpel** [comment]
Seems like it might just be missing here: https://github.com/hasura/graphql-engine/blob/master/console/src/components/Services/Data/TablePermissions/PermissionBuilder/utils.js#L7

**Comment by benkimpel** [comment]
@rikinsk13 Just opened a PR for this. But not sure if I was on the right track with it. It's running through CI now.

**Comment by benkimpel** [comment]
I'm happy to either close my PR or make changes. Up to you!

**Comment by rikinsk13** [comment]
@benkimpel Your solution was perfect. A new console build with the fix should be out in sometime. 

Thanks for your contribution!

**Comment by benkimpel** [comment]
Cool. Thank _you_. I love this project. Completely amazing.
