### ISSUE TITLE
x-hasura-default-role is prefered over x-hasura-role

### ISSUE THREAD

**Issue by ifdotpy** [hasura/graphql-engine#2849]
Hi! Thank you for your awesome work.

I have an issue with jwt. While using this  _HASURA CLAIMS_:

`{
    "x-hasura-default-role": "anonymous",
    "x-hasura-allowed-roles": [
        "user",
        "anonymous",
        "admin",
        "institution-admin"
    ],
    "x-hasura-role": "user",
    "x-hasura-user-id": "rglCjqnVAKbBx0Q7jke73blCKmu1"
}` 

Hasura identifies request sender as **anonymous**

When changed to this _HASURA CLAIMS_:
`{
    "x-hasura-default-role": "user",
    "x-hasura-allowed-roles": [
        "user",
        "anonymous",
        "admin",
        "institution-admin"
    ],
    "x-hasura-role": "user",
    "x-hasura-user-id": "rglCjqnVAKbBx0Q7jke73blCKmu1"
}` 

Hasura identifies request sender as **user**

![image](https://user-images.githubusercontent.com/17163504/64532260-d2746f80-d319-11e9-97a3-6f5346671184.png)

Why can this be happening?

**Comment by 0x777** [comment]
`x-hasura-role` has to be sent with the http request. It is not expected to be part of the JWT's hasura claims and as such it is ignored. The `x-hasura-role` sent with the request is checked to see if it is part of the `x-hasura-allowed-roles` and if yes, the request is executed as that role. In case the `x-hasura-role` is missing, the `x-hasura-default-role` from the JWT is used.

**Comment by dohomi** [comment]
In my opinion / besides the confusion I had just now, the developer needs to verify the HTTP header again - I thought this would be done directly in the JSON token already. It leads to slightly more written code - the client side needs to attach the header, the server side needs to validate if the Authentication + x-hasura-role is actually still valid

**Comment by ifdotpy** [comment]
@dohomi Initially I also thought it is a security issue. But then realized that auth server should return correct role list (`x-hasura-allowed-roles`). Which means that the roles in the list are the only roles that can be put into `x-hasura-role` header.

**Comment by dohomi** [comment]
yes.. I was a bit slow in my head and initially thought that allowed-roles should be same across all created JWT tokens. But now I prepare the JWT on the server that the default-role and allowed-roles are directly connected to the user and the security flaw I had in mind before is gone. A `user` only has `allowed-roles:["user"]` while an `admin` potentially could verify himself as `user-role:["admin","user","manager"]` and set the `default-role:"admin"`

**Comment by ifdotpy** [comment]
@dohomi I thought same when created the issue.

**Comment by galipmedia** [comment]
This has really thrown me. I have my headers set in a boot file that gets setup once and checks if there is a jwt or not which is fine because that is either there or not. But say I want a 'user' to be able to see all his own details based on his x-hasura-id, but i also want him to be able to see as 'public' all the other users usernames and avatars he cannot, he only sees his own in the list. It means I will have to carefully chain all my queries and for each one set some state of x-user-role and inject it in the headers, that seems like a nightmare. Surely your average Joe using vue-apollo or something is not going to want to do this. Does anyone know a better way? Is it bad practice to have 2 apollos setup, one for each user role ?

**Comment by galipmedia** [comment]
It just occurred to me that I have to use a view in the database and give it different permissions, with just the fields I want them to see and allow public and user to view that table too.

**Comment by ivan-kleshnin** [comment]
Something's fundamentally wrong with the names and the docs here. 

> `x-user-role` is optional, but it has to override `x-hasura-default-role`, but it doesn't.
> You can send it, and it will be applied, but it will be ignored.

Sorry, what? 🤔 🤡

**Comment by tjad** [comment]
Are these headers case sensitive (traditionally headers shouldn't be case sensitive, but depend on the server impl) ? 
I am having similar issue. I send X-Hasura-Role as a header, it is completely ignored in favour of the default-role inside the token?
