### ISSUE TITLE
create object/array relationship using foreign key constraint name

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#285]
[ObjRelUsing](https://docs.platform.hasura.io/0.15/platform/manual/api-reference/data/query/relationship.html#objrelusing) should also support `foreign_key_constraint_name`

**Comment by dsandip** [comment]
@shahidhk @0x777 @praveenweb This requires a change in the JSON API with type `create_object_relationship`, right? Does this have an impact on the console?

**Comment by shahidhk** [comment]
@rakeshkky Can you confirm if the API changes are required?

**Comment by manasag** [comment]
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.
