### ISSUE TITLE
how to use $exist and $notexist on where clause

### ISSUE THREAD

**Issue by c19** [hasura/graphql-engine#2853]
Or any other way to implement this scenario?
```
update users set coins = coins - 50 where users.id = 85 and
not exists (select 1 from purchased_chapter where user_id=85 and chapter_id=3); 
```

**Comment by 0x777** [comment]
Create an array relationship called `purchased_chapters` on `users` table. Your query will then be:
```graphql
mutation m {
  update_users(
    where: { id: {_eq: 85}, _not: {purchased_chapters: {chapter_id: {_eq: 3}}},
    _inc: {coins: -50}
  ) {
    affected_rows
  }
}
```
`{ array_relationship: expression}` returns `true` if `expression` is valid on any of the relationship entries. So, `purchased_chapters: {chapter_id: {_eq: 3}}` returns `true` if there exists a `purchased_chapter` for the user with `chapter_id=3`.

**Comment by marionschleifer** [comment]
I'm closing this issue. @c19 feel free to re-open if you'd like to add something 🙂
