### ISSUE TITLE
update digitalocean docs to add a note about connection pooling

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#2860]
ref: https://discordapp.com/channels/407792526867693568/586606982077874176/621144673129332748

> I am trying out connection pool feature of Digital Ocean. Thus after applying the connection data the server only receives 502 bad gateway issue. Does anybody set this up before?
```
graphql-engine_1  | {"internal":{"statement":"BEGIN ISOLATION LEVEL SERIALIZABLE ","prepared":true,"error":{"exec_status":"FatalError","hint":null,"message":"prepared statement \"0\" already exists","status_code":"42P05","description":null},"arguments":[]},"path":"$","error":"postgres tx error","code":"postgres-error"}
```
> Oh I just realized that connection pooling is built-in at hasura: https://github.com/hasura/graphql-engine/issues/2491 So maybe a little side note at the DO docs (https://docs.hasura.io/1.0/graphql/manual/guides/deployment/digital-ocean-one-click.html#using-digitalocean-managed-postgres-database) would be helpful for users to make sure they use `session` mode.

**Comment by santoshyadav198613** [comment]
I will take it.

**Comment by marionschleifer** [comment]
@santoshyadav198613 how is it going? Let us know if you have any questions 🙂

**Comment by santoshyadav198613** [comment]
PR om the way @marionschleifer
