### ISSUE TITLE
Hasura data browser doesn't emit generated_sql log events

### ISSUE THREAD

**Issue by david-studyblue** [hasura/graphql-engine#2863]
Hi!  When I issue GraphQL queries either via GraphiQL or directly, I get generated_sql entries in the log (provided I have that turned on).  However, when I browse the data in the console, no such generated_sql entries are emitted into the log.  It would be useful if it did, in order to troubleshoot any problems that occur.  Here's a video that illustrates this:

https://youtu.be/pAIdaSst_Mo

**Comment by ecthiender** [comment]
Hi @david-studyblue! The generated SQL is only logged only for GraphQL operations, not on metadata API queries (the queries that are made while browsing the Data tab) (https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/index.html).

**Comment by marionschleifer** [comment]
@david-studyblue is your issue resolved? If yes, we can close the issue 🙂

**Comment by marionschleifer** [comment]
@david-studyblue Im closing this. Feel free to re-open if you have any more questions 🙂
