### ISSUE TITLE
Multiple permission rules?

### ISSUE THREAD

**Issue by leopsidom** [hasura/graphql-engine#2867]
New to hasura graphql-engine. It looks like an awesome solution so far. But I am having one issue regarding the permissions. So currently I can only set the rule on a set of columns and rows. what if I need rows to have different permissions for different columns? For instance for column A and B, I need to have one set of row permissions and for column C and D, I need to have another set of row permissions which might be more strict than A and B. Is this currently possible? Thank you.

**Comment by 0x777** [comment]
Hi @leopsidom, I'm pasting an answer to a similar question on our discord support channel. Hopefully you can extrapolate from this. 

---
Let's say you have a users table of which some fields (id, username) can be queried for all rows but other private fields like (email) should only be allowed for the current user's row.

Create a view called `users_private` with the private fields like `email`. Also include the primary key, for example: 
```sql
create view users_private as select id, email from users;
```

Now, create a manual object relationship from users table to users_private called `private_data` (`users.id` -> `users_private.id`)

Permissions for user role on these tables/views will be as follows:

1. For `users_private`, allow all the private columns with the filter set to `{"id": {"_eq": "x-hasura-user-id"}}`

2. For `users` table, allow all publicly accessible columns without any restriction on the rows (i.e, filter will be `{}` which translates to a boolean `true`).

Now, let's say we are fetching data from the table posts(id, title, content, user_id) which has an object relationship called user to users table.

```graphql
{
  posts {
    id
    title
    content
    user {
      id
      username
      private_data {
        email
      }
    }
  }
}
```

If you are making this query as a `user`, the `post.user.private_data` field will be `null` for all posts not written by this user.
Now suppose you also have unauthorized users accessing these tables. Let's capture these class of users under the `anonymous` role. 

On `users` table, for `anonymous` role, add the same permissions as the `user` role. So, any user with `anonymous` will now be able to make this query:

```graphql
{
  posts {
    id
    title
    content
    user {
      id
      username
    }
  }
}
```

Notice they can't access the `private_data` field as permissions for `anonymous` role are not given to the `users_private` view.

Let's say you do not want to make different queries for `anonymous` and `user` role, i.e, you would want the first query (one with `private_data`) to work for both `user` and `anonymous` roles. In this case, just add the permissions for `anonymous` role on `users_private` view allowing all columns but no rows. The filter expression would be `{"_not": {}}` which basically translates to a boolean `false`. This means that the `post.user.private_data` field will be `null` for all posts.

**Comment by tirumaraiselvan** [comment]
Closing this in favour of #3442 (although this was created first, for some reason that has more upvotes).
