### ISSUE TITLE
docs: update metadata schema docs

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#2875]
Docs here: https://docs.hasura.io/1.0/graphql/manual/how-it-works/metadata-schema.html are outdated. 

The task is to generate the Postgres (only `hdb_catalog` schema) docs on a local machine using a fresh Postgres database initialised by the latest Hasura server. And embed those docs in Hasura docs.

Note: Generated docs can be in any format which can be seamlessly integrated with Hasura docs. Hasura docs are in [reStructuredText](http://docutils.sourceforge.net/rst.html) format

**Comment by Parikshit-Hooda** [comment]
@marionschleifer  looks like rakeshkky is not working on this issue anymore. Would you please assign this issue to me?
Also, please label this as hacktoberfest, in that case.

**Comment by rakeshkky** [comment]
@Parikshit-Hooda I updated the description. Please assign yourself :). Thank you.

**Comment by Parikshit-Hooda** [comment]
Thanks. I will get started.

**Comment by Parikshit-Hooda** [comment]
You may assign it to me.

**Comment by marionschleifer** [comment]
@Parikshit-Hooda we don't assign issues. See here the guide on how to contribute to Hasura: https://github.com/hasura/graphql-engine/wiki/Hacktoberfest-2019-%F0%9F%8E%89 🙂

**Comment by Parikshit-Hooda** [comment]
Ok, Thanks! I will get started.

**Comment by Stefmore02** [comment]
Due to recent docs changes, this has been resolved 👍
