### ISSUE TITLE
webhook cacert error 

### ISSUE THREAD

**Issue by vikastomar5983** [hasura/graphql-engine#2876]
The issue is similar to - https://github.com/hasura/graphql-engine/issues/2553

Getting below error when trying to connect to webhook (oauth server with self signed cert).

`message: "InternalException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa)))"`

String Hasura with :
`-e HASURA_GRAPHQL_JWT_SECRET='{"type":"RS512","jwk_url": "**https**://oauth.xxxx:xxxx/oauth/token_keyset"}'`

the webhook is using self signed cert. How to start Hasura with somehting like - javax.net.ssl.trustStore=cacerts

I have also tried mounting the self cacert docker run` -v /tmp/test/cacerts:/etc/ssl/certs/java/cacerts` with no success

**Comment by ecthiender** [comment]
Closing this in favour of #2553
