### ISSUE TITLE
Make information about created_at and updated_at columns more easily accessible.

### ISSUE THREAD

**Issue by edmundmunday** [hasura/graphql-engine#2880]
When looking around for information, or anything in the official docs (particularly when using the search), it's next to impossible to find out how to actually set up the created_at and updated_at columns.

It's not clear at all that these need to be set up explicitly using the "Frequently Used Columns" functionality.

Suggestion: Make sure that if someone searches the terms "createdAt", "created_at", "updatedAt", "updated_at", "lastUpdated", "last_updated" using the search in docs - useful information is actually shown.

Information about this functionality can pretty much only be found here: https://github.com/hasura/graphql-engine/issues/1077

![image](https://user-images.githubusercontent.com/20222644/64903219-581c6480-d6f8-11e9-9984-8444e8e85739.png)

**Comment by marionschleifer** [comment]
@edmundmunday thank you for bringing this to our attention. We will update the docs accordingly 🙂

**Comment by shahidhk** [comment]
I was searching for this info :smile:

**Comment by gunar-gessner-qatalog** [comment]
I was searching for this info :smile: (2)

**Comment by gunar** [comment]
I was searching for this info :smile: (2)

**Comment by duskmoon314** [comment]
Thank goodness I found this issue. 👍 

I manually added `createdAt` and `updatedAt`, then searched for a long time. :joy:

:smile: 👍
