### ISSUE TITLE
Hasura vs Cayley vs Dgraph ?

### ISSUE THREAD

**Issue by rrjanbiah** [hasura/graphql-engine#2883]
Can we please get some comparison? TIA

**Comment by hgiasac** [comment]
@rrjanbiah This may be out of topic. GraphQL Engine is a GraphQL server wrapper over PostgreSQL. It follows GraphQL specification.

Cayley vs Dgraph are graph databases with different mechanism. You should look at comparison papers between graph database vs relational database vs noSQL, etc.

**Comment by marionschleifer** [comment]
I'm closing this. @rrjanbiah feel free to re-open if you have any more questions 🙂
