### ISSUE TITLE
Event triggers delivery failure

### ISSUE THREAD

**Issue by phoenix1796** [hasura/graphql-engine#2896]
We created an internal hooks handler using express which is using res.json to return the following object :
{"success": true, "data": "test data" }

and we can see that the request is returning a 200 OK

![image](https://user-images.githubusercontent.com/9111802/65031881-b39c5b80-d95f-11e9-9230-61bf9093e4b5.png)

But, in the Event trigger , we still see the event under pending events, with the following output :

![image](https://user-images.githubusercontent.com/9111802/65031984-e5adbd80-d95f-11e9-8296-781d91c07c9a.png)

I have double checked the HTTP response and this issue seems to have come when we upgraded from beta v2 to beta v6

Any clue why this might be happening ?

**Comment by tirumaraiselvan** [comment]
Hi @phoenix1796 

This is strange and I can think of an edge case due to network failure which may cause this kind of thing but if you could provide the following info then it would help pin-point:

Run the following query on your db where `event-id` is the event_id you see in your screenshot above.
```
select event_id, status, response, created_at
from hdb_catalog.event_invocation_logs
where event_id = '<event-id>'
```

**Comment by phoenix1796** [comment]
@tirumaraiselvan I checked out the above query with multiple event-ids and this is the result I get for all of them,
![image](https://user-images.githubusercontent.com/9111802/65392603-3ecc8580-dd94-11e9-85fa-f327a34ddbce.png)

I had multiple event triggers setup for different tables and this identical issue is happening with each and every one of them.

**Comment by tirumaraiselvan** [comment]
Very strange. Do you have any entries in the table at all?

```
select count(*), event_id
from hdb_catalog.event_invocation_logs
group by event_id
```

**Comment by tafelito** [comment]
I'm experiencing the same issue. I have a lot of pending events that for some reason are not being executed.

![image](https://user-images.githubusercontent.com/5973652/69683121-a26b7b80-1081-11ea-908f-f69db4568a4a.png)

Here's the queries from the `event_invocation_logs` table

![image](https://user-images.githubusercontent.com/5973652/69683364-9207d080-1082-11ea-9d11-3bc614be8a0e.png)


![image](https://user-images.githubusercontent.com/5973652/69683269-435a3680-1082-11ea-82eb-8bc0c564e660.png)



Btw I'm on beta.10

**Comment by tirumaraiselvan** [comment]
@tafelito Can you see the invocation logs tab as well? Are there only 2 entries there (i.e. corresponding to the delivered events)

**Comment by tafelito** [comment]
yes, same entries as the processed events

**Comment by tirumaraiselvan** [comment]
@tafelito can you try to make a fresh insert/update/delete just to check if it is stalled for only these events or for newly created events as well?

**Comment by tafelito** [comment]
I already tried that and it doesn't change. I clear all events from the db. Delete all rows from the table and still, sometimes the wh gets called, sometimes is not, but it seems to be random when is actually called

**Comment by tirumaraiselvan** [comment]
@tafelito Where is Hasura deployed?

**Comment by tafelito** [comment]
The reason this was happening was because I had 2 instances of hasura, 1 running locally and the another on heroku but both where pointing to the same DB and the events were mixing up btw the hasura instances

**Comment by tirumaraiselvan** [comment]
Is everything fine now?

**Comment by tafelito** [comment]
yes it works fine for me now

**Comment by garlou** [comment]
I'm having the same problem with an insert trigger. The insertions made on hasura console trigger the event successfully but outside requests (live app or postman) all go to pending.
I have the server deployed on a AWS ECS without any concurrency (apparently).

**Comment by garlou** [comment]
I think there is a possible bug. I had only INSERT operation selected, once I selected all operations all events are triggered correctly:
https://www.dropbox.com/s/com9z6kqb8i5zie/Screenshot%202019-12-12%2019.22.03.png?dl=0

**Comment by garlou** [comment]
> I have the server deployed on a AWS ECS without any concurrency (apparently).

This was not true. I had the AWS ECS config to escalate into multiple instances when needed. Once I forced ECS to use only a maximum of 1 instance I got no more pending events. 
This works for me now but can be a problem for systems that need to escalate.

Thanks for the awesome work guys.

**Comment by tirumaraiselvan** [comment]
@garlou This is not supposed to happen even with > 1 instances. I would really appreciate if it's possible for you to describe a minimal repro, maybe with 2 instances. If you need you can open a new issue with more specific title. This issue has kind of become a sink for all kinds of issues ;)

**Comment by tirumaraiselvan** [comment]
Actually, I think, this is possible in a scale-down scenario. Suppose there were N instances and each was processing events but because of scaling configuration, few instances were killed in the middle of processing. I will open an issue for this.

**Comment by tirumaraiselvan** [comment]
Closing and locking this issue because it has diverged to lot of separate issues.
