### ISSUE TITLE
Error in https://learn.hasura.io/graphql/reason-react-apollo/intro-to-graphql/3-writing-data-mutations

### ISSUE THREAD

**Issue by joshuayoerger** [hasura/graphql-engine#2901]
The "Parametrise (sic) what you insert" portion of [this page](https://learn.hasura.io/graphql/reason-react-apollo/intro-to-graphql/3-writing-data-mutations) does not use the correct query variable type.

Navigating to https://learn.hasura.io/graphql/graphiql and submitting this query:
```graphql
mutation($todo: insert_todo_input!){
  insert_todos(objects: [$todo]) {
    returning {
      id
    }
  }
}
```

Produces this error:
```javascript
{
  "errors": [
    {
      "extensions": {
        "path": "$.variableValues",
        "code": "validation-failed"
      },
      "message": "no such type exists in the schema: 'insert_todo_input'"
    }
  ]
}
```

**Comment by praveenweb** [comment]
Fixed via https://github.com/hasura/graphql-engine/pull/2902
