### ISSUE TITLE
Subscription but with delta changes?

### ISSUE THREAD

**Issue by rrjanbiah** [hasura/graphql-engine#2907]
Is there anyway to get only the delta of data changes? For example, in nested structure, we get all root data unnecessarily--instead the required child data

**Comment by coco98** [comment]
@rrjanbiah We do this because sometime when websocket connections get interrupted or if clients reconnect after a while, it is hard to know what the last client side state is, so that we can diff. Ideally, you can subscribe to something like a `limit: 1, order_by: updated_at, desc` so that you get a notification that something has changed, and then you can make a precise query to refetch exactly the data that you want.

The data that you're subscribing to, is it more like a feed where things are continuously getting added (like a chat feed say), or is it more like a piece of state and parts of the state keep changing?

**Comment by rrjanbiah** [comment]
@coco98 Thank you so much for you yourself trying to help here.

> is it more like a piece of state and parts of the state keep changing?

Yes, it is more like a todo list with nested data, say `users->todos->comments->votes`

Will also try your idea and update in couple of days. But, it looks like we have to have double request for same payload and not effectively using WebSocket for realtime update. 

Thanks again

**Comment by marionschleifer** [comment]
@rrjanbiah just checking in to see if your problem is solved? 🙂

**Comment by rrjanbiah** [comment]
@marionschleifer Thanks for checking. But, unfortunately no. With huge data, we're now getting another previously noted issue #2735

**Comment by rrjanbiah** [comment]
Just a clarification... it is not just for huge data, but even for small data with short interval, data are getting skipped in subscription... when we use  `limit: 1, order_by: updated_at, desc` logic (As noted in #2736) Also, unfortunately, finding ideal `k` in `limit: k` to solve the issue is not possible. Perhaps the only possible solution is to find another approach.

Also, anyone ever used subscription must have come across this data skipping issue, as it is very easy to reproduce this issue in 'normal' environment.

**Comment by dsandip** [comment]
@rrjanbiah let's get on a short call to troubleshoot this? If this works for you, please help schedule this chat using [this](https://calendly.com/team-hasura/graphql-helpline).

**Comment by rrjanbiah** [comment]
@dsandip Thanks for your offer. Will try for a call. But, it is very very easy to reproduce it in any normal environment. Say, users ~ 5000, comments ~1 lakh, number of live users ~5. Basically, anyone using subscription for live update should get it often.

**Comment by 0x777** [comment]
@rrjanbiah Your use case can't be accurately captured with live queries as it looks like you need to subscribe to changes in data, which requires instrumentation around database events. Closing this in favour of #2317.

**Comment by rrjanbiah** [comment]
@0x777 

Looks like you overlooked #2736 My additional notes https://github.com/hasura/graphql-engine/issues/2907#issuecomment-539862305 are related to #2736 which is very very easy to reproduce. I'm not sure if #2317 will address that issue (but it is upto you)

**Comment by 0x777** [comment]
@rrjanbiah I'm sorry I wasn't clear in my previous comment. The current [subscriptions implementation](https://github.com/hasura/graphql-engine/blob/master/architecture/live-queries.md) is not event based and hence does not capture all the changes, for example, if two changes happen quickly to a row, you'll only see the latest change. You can lower the 'refetch interval' from the default `1000`ms to reduce the chance of missing an event as suggested [here](https://github.com/hasura/graphql-engine/issues/2735#issuecomment-522927329)
