### ISSUE TITLE
Have the option to completly remove serial primary key argument for generated Graphql insert methods

### ISSUE THREAD

**Issue by wu-s-john** [hasura/graphql-engine#2908]
For a table, I have my primary key set as a serial type. So for my cases, I would not have to fill the serial type at anytime. Can I generate a graphql schema that omits the input of this primary key type for insert functions?

This is important because I created an introspective query from Hasura's generated graphql schema. I am using this introspective query to write my hasura insert mutations in a type safe manner in OCaml. It accomplishes this by automatically generating these insert mutations through the ppx, [graphql_ppx](https://github.com/mhallin/graphql_ppx). When I do an insert, I am forced to input a value for the primary key. I thought in my head that this is unnecessary so I input it as a None/Null value. I send my query to Hasura, which sends it to Postgres and it thinks I am setting my primary key to null. Postgres thinks I am violating a Non-null constraint and ultimately rejects my insert query.

This is unfortunate to see because it limits the integration usage of Hasura with strongly typed languages, like OCaml. I hope to see this issue addressed soon.

**Comment by coco98** [comment]
If you go to the permissions section for the particular table, you can create a role for which the insert mutation does not allow setting values for some columns. You can omit id from there. 
Will that address the issue?

<img width="513" alt="Screenshot 2019-09-18 at 10 41 58 AM" src="https://user-images.githubusercontent.com/131160/65171977-f5311300-da00-11e9-8509-12f82cbc685e.png">

**Comment by wu-s-john** [comment]
Yes. This worked! However, this was not clear to do from the docs. Maybe there should be documentation using this trick.

**Comment by tirumaraiselvan** [comment]
The docs are here: https://hasura.io/docs/1.0/graphql/manual/auth/authorization/permission-rules.html#column-level-permissions
