### ISSUE TITLE
How to filter and THEN sort, with one-many relationship

### ISSUE THREAD

**Issue by chrisheseltine** [hasura/graphql-engine#2912]
Hi,

I'm new to Hasura, but I feel what I am trying to do should be pretty commonplace...

What I am trying to achieve is to allow a user to apply both a price range filter and a price sort to the results that my site fetches for them. So I want to find all prices within the specified price range, and then sort them by price, either asc or desc.

I have a Hasura Engine running on Heroku Postgres. The DB has two tables, seeds and prices. One row in seeds table, i.e. one seed, can be related to multiple rows in the prices tables, i.e. many prices. They are joined by a foreign key constraint and a one-many relationship, or Object to Array.

I am attempting to query seeds using the following GraphQL query:

```
{
  seeds(
    where: {prices: {price: {_gte: "10", _lte: "200"}}}, 
    order_by: {prices_aggregate: {min: {price: asc_nulls_last}}}
  ) {
    product_name
    prices {
      price
    }
  }
}
```

What I want this query to do is to filter out all prices.price that are not within the valid range (10, 200), and then sort them in order of prices.price ascending. However what happens is that the results are sorted by prices.price ascending INCLUDING values that are not within the range, then the results are filtered.

I will give an example to clarify. Consider the following results from the above query:

```
{
  "data": {
    "seeds": [
      {
        "product_name": "Northern Lights Auto Feminised Seeds",
        "prices": [
          {
            "price": 3.48
          },
          {
            "price": 6.79
          },
          {
            "price": 9.58
          },
          {
            "price": 104.5
          }
        ]
      },
      {
        "product_name": "The White OG Feminised Seeds",
        "prices": [
          {
            "price": 3.48
          },
          {
            "price": 6.79
          },
          {
            "price": 15.68
          }
        ]
      },
      {
        "product_name": "Special Kush #1 Feminised Seeds from Royal Queen Seeds",
        "prices": [
          {
            "price": 3.49
          },
          {
            "price": 13.53
          },
          {
            "price": 8.29
          }
        ]
      }
    ]
  }
}
```

The above results are correct, because there are valid values for prices.price within the range specified (104.5, 15.68, 13.53) respectively, however the results are not in the right order. They are instead ordered by the lowest price.prices, regardless of the filter which was specified (10, 200).

The correct order for the results would be:

```
{
  "data": {
    "seeds": [
      {
        "product_name": "Special Kush #1 Feminised Seeds from Royal Queen Seeds",
        "prices": [
          {
            "price": 3.49
          },
          {
            "price": 13.53
          },
          {
            "price": 8.29
          }
        ]
      },
      {
        "product_name": "The White OG Feminised Seeds",
        "prices": [
          {
            "price": 3.48
          },
          {
            "price": 6.79
          },
          {
            "price": 15.68
          }
        ]
      },
      {
        "product_name": "Northern Lights Auto Feminised Seeds",
        "prices": [
          {
            "price": 3.48
          },
          {
            "price": 6.79
          },
          {
            "price": 9.58
          },
          {
            "price": 104.5
          }
        ]
      }
    ]
  }
}
```

Can anyone help me, and explain how I can achieve these correct results? It is worth mentioning that it is not possible to sort the results after the query as there are thousands and the sort will definitely affect which results are returned from the DB.

Thanks, in advance!

**Comment by chrisheseltine** [comment]
To clarify, if you visit this site: 
https://www.seedsman.com/en/cannabis-seeds/variety?dir=asc&order=price&p=3&price=241-304
You'll notice that the filter is set at 241-304, and the sort is set to price ascending. 

The first result is £6.94, the second is £7.81, the third is £8.36, and so forth. This is WRONG. On my site, using the same filter and sort, I'd like my results to be, for example: £241.10, £249.50, £252, and so forth. 

Can anyone help me achieve this?

Thanks

**Comment by chrisheseltine** [comment]
The following works:
```
{
  prices(order_by: {price: asc}, where: {price: {_gte: "10", _lte: "200"}}) {
    seed {
      product_name
      prices {
        price
      }
    }
  }
}
```
This returns the correct results, however if I query the prices table like this I cannot handle filters on the seeds table. Say for example I wanted to filter by product_name and price, if I query the prices table I cannot add the product_name filter to the seeds table. So I cannot handle multiple filters simultaneously.

**Comment by rikinsk** [comment]
@chrisheseltine would the following solve your requirements?
```
{
  prices(
    order_by: { price: asc }, 
    where: {
      _and: [
        {
          price: {_gte: "10", _lte: "200"}
        },
        {
          seed: {
            product_name: {_eq: "boo"}
          }
        }
      ]
    }
  ) {
    seed {
      product_name
      prices {
        price
      }
    }
  }
}
```

**Comment by marionschleifer** [comment]
@chrisheseltine just checking in to see if your problem is solved? 🙂

**Comment by chrisheseltine** [comment]
I started working on another area of my project which is why I left this thread until I was ready. Thanks for the suggestion, I think this will work for my criteria. I will try it shortly and update with the results.

Thanks for helping me, even SO couldn't solve this one!

P.S I won't mark as resolved until I have tested and given feedback.

**Comment by chrisheseltine** [comment]
Hi there! I finally got back around to this... Sorry for the delay.

This is working, however it's returning one seed for each price, instead of all the prices grouped together under one seed record. What this means is that I get the results, but if the seed has 5 prices then I get 5 records of the same seed returned. 

Is there a way to merge them by seed.product_name before they are returned? If not I can handle it client-side but it seems less than ideal. I imagined the distinct_on will allow me to do this, but distinct_on when querying the prices table doesn't allow a seeds table field.

Any suggestions?

P.S. This is my query now:
```
{
  prices(limit: 18, order_by: {seed: {popularity: desc_nulls_last}, price: asc}, where: {price: {_gte: "10", _lte: "200"}}) {
    seed {
      product_name
    }
    price
  }
}
```

**Comment by chrisheseltine** [comment]
Actually now that I think about it, manually merging the copies on the client-side would be a problem because it would throw pagination way out (I use the offset for pagination). So really I need to find a way to merge the results by common seed.product_name, before they are returned.

**Comment by rikinsk** [comment]
@chrisheseltine Seems like you need to use a group_by. Hasura currently doesn't have a native support for group_by queries. As an alternative, if you can represent the query you need in SQL, you could create a view and then use that to make your query

**Comment by chrisheseltine** [comment]
@rikinsk So I'd create a custom SQL query as suggested in the Hasura docs, then query that via the API? Do you have any basic examples of how I can us group_by? I was actually using Hasura to avoid SQL, so I'm not sure where to start with this.

Thanks for the help thus far, I'd really like to crack the back of this, as my competitors have given up getting this working, so I'll be ahead of the game if I can swing it ⚔️

**Comment by chrisheseltine** [comment]
@rikinsk I have implemented as mentioned above, however I get an error when trying to group by name. The error states that [table].id must be used in GROUP BY or aggregate. This makes no sense to me, why would I group by on a key? Every group will still be a single record. Do you have any advice on this error? Thanks.

**Comment by rikinsk** [comment]
@chrisheseltine Can you share the query you have come up with to help us debug better

**Comment by chrisheseltine** [comment]
@rikinsk Sure thing.

The following is the original query I was using, which returns correct results, but many duplicates (one for each price that was queried):

```
query {
  prices (
    limit: 18,
    offset: 0,
    order_by: {order_by_query},
    where: {where_query}
  ){
    seed {
      product_name,
      prices {
        price
      }
    }
  }
}
```

The following is what I am guessing I need to convert it to. This was based on the Hasura docs on creating custom SQL functions.

```
CREATE FUNCTION seeds_by_price_as_prices(minPrice numeric, maxPrice numeric)
RETURNS SETOF prices AS $$
    SELECT *
    FROM prices
    GROUP BY name
$$ LANGUAGE sql STABLE;

query {
  seeds_by_price_as_prices (
    limit: 18,
    offset: 0,
    order_by: {order_by_query},
    where: {where_query}
  ){
    seed {
      product_name,
      prices {
        price
      }
    }
  }
}
```

This gives me the error: `SQL Execution Failed: postgres-error : column "prices.id" must appear in the GROUP BY clause or be used in an aggregate function`.
What I'm trying to do is instead of querying prices table I query a function which queries prices table and adds a GROUP BY into the mix. The created function in this case is `seeds_by_price_as_prices`.

Thanks.

**Comment by rikinsk** [comment]
@chrisheseltine I was just going through your requirements once again and felt we might be overcomplicating the solution.

As I understand, every seed can have multiple prices associated with it and we are attempting to set up pagination, sort and filtering for seeds based on the seed or its price list. When sorted and filtered by price, we would like the seeds to be sorted by the min/max (depending on sort order) of its prices which satisfy the price filter defined. 

If my understanding of the expectations is accurate, the following query **should** have been our solution:

```gql
query fetchSeedsPriceAsc($limit: Int, $offset: Int,  $priceMin: float8, $priceMax: float8, $seedFilter: seeds_bool_exp) {
  seeds(
    limit: $limit, offset: $offset,
    order_by: {
      # where in the aggregate is currently NOT supported
      prices_aggregate: {where: {_gt: $priceMin, _lt: $priceMax}, using: {min: {price: asc}}}  # min / max depends on sort order
    }
    where: {
    _and: [
      $seedFilter,
      {
        prices: {price: {_gt: $priceMin, _lt: $priceMax}}
      }
    ] 
  }
  ) {
    product_name 
    prices(
      where: {price: {_gt: $priceMin, _lt: $priceMax}}, 
      order_by: {price: asc}
    ) {
      price
    }
  }
}
```
with variables:
```json
{
  "limit": 20,
  "offset": 0,
  "priceMin": 5,
  "priceMax": 100,
  "seedFilter": {}
}
```
Unfortunately `where` in an aggregation during `order_by` is currently not supported. It's being tracked at #1357.

For now I believe we will just have to create a custom SQL function which does this for us:

```sql
CREATE OR REPLACE FUNCTION filter_seeds_price_asc(price_min double precision, price_max double precision)
 RETURNS SETOF seeds
 LANGUAGE sql
 STABLE
AS $function$
    SELECT seeds.* FROM 
(
    SELECT
       seeds.*, min(price) min_price
    FROM
      seeds,
      prices
    WHERE
      prices.seed_id = seeds.id
      AND prices.price > price_min
      AND prices.price < price_max
    GROUP BY
      seeds.id
) as seed_agg, seeds
WHERE seed_agg.id = seeds.id
ORDER BY min_price

$function$
```

You can then make the GraphQL query as:

```gql
query fetchSeedsPriceAsc ($limit: Int, $offset: Int, $priceMin: float8, $priceMax: float8, , $seedFilter: seeds_bool_exp) {
  filter_seeds_price_asc(
    args: {price_min: $priceMin, price_max: $priceMax },
    limit: $limit, offset: $offset,
    where: $seedFilter
  ) {
    product_name
    prices (
      where: {price: {_gt: $priceMin, _lt: $priceMax}}
      order_by: {price: asc}
    ) {
      price
    }
  }
}
```
with variables:
```json
{
  "limit": 20,
  "offset": 0,
  "priceMin": 5,
  "priceMax": 100,
  "seedFilter": {}
}
```
This is a little crude and doesn't handle `asc` and `desc` in the same function. I leave it to you to make it into one common funcion if you really want. You can always have 2 separate functions based on the sort order as I have done here.

**Comment by chrisheseltine** [comment]
@rikinsk I want to use this solution but I barely understand it tbh, and I wanna take caution adding code to my ecosystem that I don't understand. I have a few questions regarding your solution, perhaps you can help me gain more understanding and I can implement it (I have so many stacks to learn I really don't have time to learn SQL as well, which is ironically why I chose Hasura).

1. Why do you use SELECT inside another SELECT?
2. What does min() do, and how can it refer to price, and not prices.price?
3. How come when you call the function via the API you are stating a where clause inside the returning fields part of the query?
4. How come you have no issues using GROUP BY without the id column?

If I can understand these points maybe I can strip this query down into a more basic one, then build it back up again, to understand it.

Thanks a lot for your help thus far, it really is appreciated.

**Comment by rikinsk** [comment]
Sorry for the delayed response. I should have added an explanation for the query to begin with. Here it is now anyway.

Here's the SQL with inline explanation.
```sql
-- create a function that takes the seed price limits as input and return rows of "seeds" table in response
CREATE OR REPLACE FUNCTION filter_seeds_price_asc(price_min double precision, price_max double precision)
 RETURNS SETOF seeds
 LANGUAGE sql
 STABLE
AS $function$
    -- using the result set of the nested select below, sort the rows by min_price 
    -- as the function needs to return rows of seeds table exactly, ie: without the min_price, we need to remove it from our results
    -- we remove the min_price by joining with the seeds table again using seed.id and just return the columns of the seed table. This is just an SQL hack I came up with to achieve this. There could be better ways.
    -- result would be set of filtered and sorted seeds of the format {id: 1, product_name: 'xyz'}
    SELECT seeds.* FROM 
    (
        -- join the seeds and prices tables based on seed_id and apply price filters
        -- then group by seed ids and only keep the min price value for every seed id
        -- result would be set of rows of the format {id: 1, product_name: 'xyz', min_price: 12.34}
        SELECT
           seeds.*, min(price) min_price
        FROM
          seeds,
          prices
        WHERE
          prices.seed_id = seeds.id
          AND prices.price > price_min
          AND prices.price < price_max
        GROUP BY
          seeds.id
    ) as seed_agg, seeds
    WHERE seed_agg.id = seeds.id
    ORDER BY min_price ASC

$function$
```

To summarise what this does:
- we first join the seeds and prices tables, apply our price filters and then collect the min price for each seed
- then we sort the results by the min price and then remove the min price from our results before returning the results

I would like to add that this is probably one of many possible SQL solutions to achieve the same result. 

Now for your specific questions:

> Why do you use SELECT inside another SELECT?

I believe I might have answered this in the explanation above. It was to first do a filter and aggregate based on price and then to sort and return just the required fields

> What does min() do, and how can it refer to price, and not prices.price?

min() is an aggregate function which can be used when you do a group by. In our case as we are grouping by seed.id, we will have multiple values of price for each row which we can aggregate over and just keep the minimum value of.
Using price in place of prices.price is just an SQL feature where you dont need to qualify the source table of a column in a join as long as it doesnt conflict with a column of the other table. you can also use min(prices.price). they are the same thing in our case. 

> How come when you call the function via the API you are stating a where clause inside the returning fields part of the query?

Our function just returns the seeds with the correct filters and order. While fetching its nested prices we still need to apply our price filters and sort order for the prices as otherwise the query would just return all the prices of the seed

> How come you have no issues using GROUP BY without the id column?

the group by is done using seeds.id. Am I missing something here?

Hope this clarifies things. Do let me know if something is still not clear.

**Comment by marionschleifer** [comment]
@chrisheseltine just checking if your problem is solved? 🙂

**Comment by chrisheseltine** [comment]
Hi guys, sorry again for the late reply. I have started a new job and unable to find the time to test this right now, but I think it's safe to say this will work.

You can close it for now, and I will come back when I have time and implement. I will inform if it didn't work.

Thanks again for your time and help everyone, especially in helping me understand the SQL! <3
