### ISSUE TITLE
Migration SQL script wrong order : functions creation before tables are creation  

### ISSUE THREAD

**Issue by arpitjacob** [hasura/graphql-engine#2914]
Migration SQL script trying to create functions before the tables are created. 

`[42P01] FatalError: relation "Addresses" does not exist `

Resolved it by moving the function creation scripts after the table creation.

**Comment by shahidhk** [comment]
Unfortunately, this is how Postgres generates the output while using `pg_dump`

**Comment by marionschleifer** [comment]
I'm closing this issue. @arpitjacob feel free to re-open if you have anything to add to this 🙂
