### ISSUE TITLE
Disabling CORS still sends CORS headers

### ISSUE THREAD

**Issue by analytically** [hasura/graphql-engine#2918]

**Comment by ecthiender** [comment]
Hi @analytically I am unable to reproduce this. I set the `--disable-cors` flag and sent a request from browser. I can see the server does not send any CORS headers in the response.

Also, note that there is no corresponding env var for this setting. (https://docs.hasura.io/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html#command-flags) . We will fix that ASAP.

**Comment by marionschleifer** [comment]
I created a new issue to add an env var to disable cors headers: https://github.com/hasura/graphql-engine/issues/3782. Closing this one.
