### ISSUE TITLE
Add a console button and an API endpoint to force HGE to reload or atleast refresh schema-cache

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#292]
It'll be nice to have a UI feature and an API endpoint to force HGE to refresh its schema cache or reload entirely. In particular this is because #240 is still open.

Edit: Via @trash_art#6846 on discord

**Comment by rakeshkky** [comment]
@praveenweb 
I added a query type to reload metadata:
```http
POST /v1/query
{
  "type": "reload_metadata",
  "args": {}
}
```
Please push console changes to this [branch](https://github.com/rakeshkky/graphql-engine/tree/issue-292)

**Comment by coco98** [comment]
Oh man. I'm very lost. Hasura metadata and then a heading called metadata cache is very confusing.
I'm thinking we should just have the hasura metadata heading and then different headings:

**Import/export**
Get Hasura metadata as JSON
`<import> <export>`

**Refresh**
Refresh Hasura metadata, typically required if you have changed the underlying postgres schema.
`<refresh>`

**Comment by dsandip** [comment]
`..changed the underlying postgres schema`: Do we need to qualify this with " without using the GraphQL Engine console"?

**Comment by coco98** [comment]
Not really. Because you won't be at this page unless you've made an error.

Also, please note in the screenshot below:
@karthikvt26 @surendran82 

I've added 2 subheadings. Gap between buttons reduced from 60px to 30px.


<img width="1440" alt="screen shot 2018-08-29 at 5 12 28 pm" src="https://user-images.githubusercontent.com/131160/44785537-e20d9400-abae-11e8-9a6c-d6633a3d9968.png">

**Comment by shahidhk** [comment]
Added in https://github.com/hasura/graphql-engine/commit/e3102dfd5e8e5a10dd5775eb6ee82956a5d872a9
