### ISSUE TITLE
Document error-codes returned by Hasura GraphQL API

### ISSUE THREAD

**Issue by abhi40308** [hasura/graphql-engine#2920]
Error codes returned by Schema/metadata API are documented [here](https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/index.html#error-codes), but not for Hasura GraphQL api.

Also, one may confuse that the error codes returned by schema/metadata api are the same as those returned by GraphQL API, but it is not the case. For example, codes : `constraint-violation` and `validation-failed` are not in schema/metadata api but are returned by GraphQL API.

**Comment by jasonferrier** [comment]
Has there been any progress on this - almost 1 year later?
Even just posting a CSV of the values in `errors[i].extensions.code` would be helpful at this point.

**Comment by marionschleifer** [comment]
Closing this in favour of https://github.com/hasura/graphql-engine/issues/1738.
