### ISSUE TITLE
Hasura executed trigger functions instead of event trigger web hooks

### ISSUE THREAD

**Issue by beepsoft** [hasura/graphql-engine#2940]
When creating a new record I would like to create some related records at the same time the INSERT occurs. The related records would be used for permission control, so these must be created at INSERT time - in the same transaction - and it cannot be created by the calling users on their own, of course.

The options I have with Hasura at the moment:
1. Creating a Postgresql trigger function. The problem with that is that it cannot access the session variables like the x-hasura-user-id that were passed during the INSERT, which I would need to create the permission record.
2. Using an event trigger web hook. This works, because it can receive the session variables, however it runs async to the main record INSERT and therefore when the caller gets back the result from Hasura the permission records may not be ready

My question is: would it be possible some ways to run a user defined psql function before/after an INSERT(/UPDATE/DELETE). But not a usual psql trigger, which cannot access the session variables, but a function which would be invoked by Hasura itself and which could receive details of the INSERTed record as well as the session variables. This could be very much similar to how an event trigger URL is invoked now, but instead a psql function would be called.

**Comment by tirumaraiselvan** [comment]
@beepsoft You can actually implement Option 1) . You have access to all sessions variables in your postgres functions using the `current_setting('hasura.user')` function.

```
...
DECLARE
  session_variables json;
BEGIN
  session_variables := current_setting('hasura.user', 't');
  ...
END;
```

**Comment by beepsoft** [comment]
@tirumaraiselvan Oh, great, thank you! I didn't find that in the trigger documentation. But as I see others have the same problem too: https://github.com/hasura/graphql-engine/issues/1582 ;-)

**Comment by beepsoft** [comment]
Can I ask for some clarifications?

So is every `x-hasura-XXX` session variable mapped to a `hasura.XXX` psql config setting?  If I have `x-hasura-myfield` in the JWT claims, then it will appear as `hasura.myfield` in the config settings. Am I right about this?

I'm asking because your example and the "Auditing actions on tables in Postgres" documentation has this example with `'hasura.user'`, which I guess is mapped to `x-hasura-user-id`. There seems to be some mismatch here for me. 

So, what are the mapping rules here?

**Comment by tirumaraiselvan** [comment]
@beepsoft 

current_setting('hasura.user') will return a json where each key is the session variable, just like you get in event trigger payload.

**Comment by beepsoft** [comment]
@tirumaraiselvan Ok, now I get it, thanks!
