### ISSUE TITLE
Add x-hasura-allowed-header-variables functionality JWT Auth

### ISSUE THREAD

**Issue by leoalves** [hasura/graphql-engine#2951]
Sometimes we need header information to validate requests. But with JWT Auth we are limited to whatever is in the custom_claim, and those values cannot be changed on each request.

My suggestion is to add a property to the JWT token, to forward header properties as session variables in Hasura. 

For example, the following token:
```javascript
{
  "sub": "1234567890",
  "name": "John Doe",
  "admin": true,
  "iat": 1516239022,
  "https://hasura.io/jwt/claims": {
    "x-hasura-allowed-roles": ["editor","user", "mod"],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": "1234567890",
    "x-hasura-org-id": "123",
    "x-hasura-custom": "custom-value",
    "x-hasura-allowed-header-variables": ["origin", "user-agent", "request-ip*"]
  }
}
```
*ip from the request (this is not a header variable but would be useful to also have it)

With this token the user session variables would be:

```javascript
{
     "x-hasura-allowed-roles": ["editor","user", "mod"],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": "1234567890",
    "x-hasura-org-id": "123",
    "x-hasura-custom": "custom-value",
    "x-hasura-origin": "https://www.example.com",
    "x-hasura-user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
    "x-hasura-request-ip": "0.0.0.0"    
}
```

This allows us to user header values in the permissions.  And also in PostgreSQL, since that information would be populated in PostgreSQL ```current_setting('hasura.user')``` variable

I have a specific use-case where I need to rate limit requests from each ip address.  And only allow requests from a specific origin.  

With this feature I coud keep my Authentication with JWT.  

Otherwise I need to move it to Webhooks.

Thanks

**Comment by beepsoft** [comment]
This would be a really useful feature indeed!

**Comment by 0x777** [comment]
> I have a specific use-case where I need to rate limit requests from each ip address. And only allow requests from a specific origin.

@leoalves Aren't these constraints better enforced at the gateway layer like nginx/caddy? I feel that adding these features (rate limiting/header based restrictions) directly to graphql-engine is better than extending the permissions system as it increases the complexity. My point I guess is that we don't mind adding this feature if it helps you write more access control rules but the above use case I don't feel warrants this. 

What do you think about a docker image which packages both graphql-engine and nginx? You can easily specify such restrictions in `nginx.conf`.

**Comment by leoalves** [comment]
@0x777,

In my specific use case the values are dynamic. I haven't dig too deep into Nginx.  But I think making those values dynamic is harder and more prone to errors, specially with my lack of experience with it.  For other projects, I have it in Nginx, but they are static.

This is not a road block for me. Right now I am doing it with Webhooks.  I just think it would be useful to also have this option with JWT.

I think the benefits outweigh the complexity. 

Thanks

**Comment by dminkovsky** [comment]
Access to HTTP headers in mutations would, indeed, be really nice. For example, how do I log a user's IP (`x-forwarded-ip`) or a request ID (`x-request-id`). This seems really basic/fundamental? Asked on SO today, too: https://stackoverflow.com/q/60725224/741970

**Comment by leoalves** [comment]
I think this issue is related to this other one
https://github.com/hasura/graphql-engine/issues/1601

**Comment by tirumaraiselvan** [comment]
@leoalves Will #1601 work for you? Can I close this as it's dupe or do you think the differences are worth keeping this open?

**Comment by leoalves** [comment]
Yeah. I will close this issue.
Thanks
