### ISSUE TITLE
better api error handling on the cli

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#2954]
If any of the API calls throw 504 etc or a non-JSON response, the CLI errors out saying 
```
FATA[0031] apply failed: invalid character '<' looking for beginning of value
```
which is not really helpful for a user.

For all unknown API-errors, the CLI should print out the response code and body.

**Comment by santoshyadav198613** [comment]
I will take it @marionschleifer

**Comment by marionschleifer** [comment]
@santoshyadav198613 great, I assigned it to you. Let us know if you have any questions 🙂

**Comment by dotslash21** [comment]
@marionschleifer I'd like to give this issue a try. I'm a beginner, so please guide me :smiley:

**Comment by marionschleifer** [comment]
@dotslash21 we have created a wiki describing everything you need to know about Hasura & Hacktoberfest: https://github.com/hasura/graphql-engine/wiki/Hacktoberfest-2019-%F0%9F%8E%89 🙂

**Comment by santoshyadav198613** [comment]
Hi @marionschleifer ,
I am using windows and getting lot of issues while running it locally, maybe this time I will pass it. Can we have docs on how to build it on windows, the docs refer to commands which are compatible on Linux.

**Comment by tingaloo** [comment]
```
commands git:(master) $ go test migrate_apply_test.go
# command-line-arguments [command-line-arguments.test]
./migrate_apply_test.go:20:11: undefined: migrateApplyOptions
./migrate_apply_test.go:52:11: undefined: migrateApplyOptions
./migrate_apply_test.go:79:11: undefined: migrateApplyOptions
FAIL	command-line-arguments [build failed]
```

I'm trying to run some tests, but i keep getting an undefined variable. Am I missing a step in the testing process?

**Comment by rv404674** [comment]
@marionschleifer Is this issue assigned to someone. I can see from the comments santoshyadav198613 has left this issue due to os problems. If someone is already not working on it, can I take it?

**Comment by shahidhk** [comment]
@santoshyadav198613 Building on Windows is no different than building on a *nix machine as Go has good cross-platform support. If your hiccup is with `make`, I suggest you executing the commands in the make rules manually or using something like [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) where most of the bash tools are available.

**Comment by shahidhk** [comment]
@tingaloo Some tests depend on other tests, it is better if you run them together. Like `go test -ldflags "-X github.com/hasura/graphql-engine/cli/version.BuildVersion=$(VERSION)" ./...`

**Comment by marionschleifer** [comment]
@rv404674 we decided not to assign issues. People who want to contribute can just follow these guidelines: https://github.com/hasura/graphql-engine/wiki/Hacktoberfest-2019-%F0%9F%8E%89. If a draft PR is linked to an issue, it means someone is already working on it 🙂

**Comment by shahidhk** [comment]
closed in https://github.com/hasura/graphql-engine/commit/c6ab1014affa8ec96c3f9edd1d549bbb40bfacfb
