### ISSUE TITLE
docs: update google cloud guide to expose hasura on https instead of http

### ISSUE THREAD

**Issue by kevinrodriguez-io** [hasura/graphql-engine#2956]
The following document is a great guide to set up a k8s endpoint with load balancing, but the load balancer exposes only the port:80.

I'm having lot's of issues now trying to add https/ssl to the k8s cluster. I think it should be good to add documentation on the guide about it so it can be more complete. No one exposes a database-consuming service trough http these days.

https://github.com/hasura/graphql-engine/blob/master/docs/graphql/manual/guides/deployment/google-kubernetes-engine-cloud-sql.rst

**Comment by vitaliytv** [comment]
simplest way use  Google-managed SSL certificates
https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs

**Comment by kevinrodriguez-io** [comment]
Yeah! I added my Google-managed SSL certificate by adding an Ingress above the LoadBalancer. That worked!

**Comment by buzinas** [comment]
@kevinrodriguez-io would you mind explaining how you did?

**Comment by hg2355** [comment]
yeah I'm with @buzinas , @kevinrodriguez-io can you shed some light on how you managed to do this?

**Comment by kevinrodriguez-io** [comment]
I'll upload a little video guide since I did this using the UI

**Comment by hg2355** [comment]
@kevinrodriguez-io @buzinas 

this video explains how to do it around 26:30

https://www.youtube.com/watch?v=APnXlMiKBWg

**Comment by hg2355** [comment]
@kevinrodriguez-io did you ever get around to posting any videos about this? the resource I found is not very helpful

**Comment by kevinrodriguez-io** [comment]
Sorry @hg2355 , I haven't had the time but thanks for reminding me, I'll update this thread as soon as I have it
