### ISSUE TITLE
Does Hasura Engine support groupBy in GraphQL query?

### ISSUE THREAD

**Issue by yyuankm1976** [hasura/graphql-engine#2965]
I need to run the SQL statement by using Group By. Does Hasura Engine support GroupBy in GraphQL query and map to SQL GroupBy? Thanks!

**Comment by marionschleifer** [comment]
Hi @yyuankm1976, it's not possible to use `GROUP BY` inside queries. You have to create a view for that: https://docs.hasura.io/1.0/graphql/manual/queries/derived-data.html#step-1-create-a-view.

**Comment by yyuankm1976** [comment]
Thanks marionschleifer, sure we can create a view for this purpose. but as I know, groupby can also be integrated into graphql. One example is as below. Do we plan to add this support in future? 

query {
  postsConnection(where: {
    someField: true,
  }) {
    groupBy {
      authorName {
        key
      	connection {
          aggregate {
            count
            avg {
              nb_likes
            }
          }
        }
      }
    }
  }
}

**Comment by 0x777** [comment]
@yyuankm1976 The reason why we didn't implement this is because the above approach only works when you want to group by a single column.

**Comment by marionschleifer** [comment]
@yyuankm1976 I'm closing this issue. Feel free to re-open if you have any additional questions 🙂

**Comment by nolandg** [comment]
Example using a postgres function is here: https://github.com/hasura/graphql-engine/issues/3478#issuecomment-620313590

**Comment by agam-singsys** [comment]
Find duplicate entries in a column in PostgreSQL graphql hasura?

**Comment by Mingyang-Li** [comment]
> @yyuankm1976 The reason why we didn't implement this is because the above approach only works when you want to group by a single column.

Not everyone needs to group data by 2 or 3 columns - I'm trying to build some simple data-visualisation on the UI and it would be a huge blessing if we're able to just group data by even ONE column (with `where` filters etc)

**Comment by tirumaraiselvan** [comment]
Discussion on implementing various workaround are here: https://github.com/hasura/graphql-engine/discussions/3478

An easy approach is here: https://github.com/hasura/graphql-engine/discussions/3478#discussioncomment-2521254
