### ISSUE TITLE
GNU AGPL-3.0 licence listed on Dockerhub

### ISSUE THREAD

**Issue by kelly-ry4n** [hasura/graphql-engine#2976]
Hi, I think you have an out of date licence listed on dockerhub at https://hub.docker.com/r/hasura/graphql-engine.

```
The core GraphQL Engine is available under the GNU Affero General Public License v3 (AGPL-3.0). We have written more about what you can and cannot do under AGPL here.
```

This was almost a non-starter for my project, and I only happened to read in a comment that the licence had changed, so you might was to update it!

**Comment by shahidhk** [comment]
Thanks for reporting this @kelly-ry4n! :pray: 

I have revamped the description at https://hub.docker.com/r/hasura/graphql-engine
