### ISSUE TITLE
[Question] Adding custom url prefix for console and graphql-engine

### ISSUE THREAD

**Issue by bynov** [hasura/graphql-engine#2983]
Hi!
I want to deploy Hasura under API Gateway, in my case Krakend.
In our case one Gateway proxying several apps. Each application should have some base prefix for urls.

I want to specify somehow a base prefix, for example `/hasura`.

I expect that all console urls will be similar to:  `http://127.0.0.1:8080/hasura/console/data/schema/public`
and graphql urls something like:
`http://127.0.0.1:8080/hasura/v1/query`

I tried to make some changes in client and haskell part, simply replacing all urls & build docker, but it did not help.

Maybe you can point me where I should make such changes, or maybe there is exist a more simpler way to do it.
Thanks!

**Comment by shahidhk** [comment]
@bynov You don't have to change anything at the Hasura layer. Just use your gateway to manage the URLs.

On nginx, this would look like:

```
location /hasura/ {
  proxy_pass http://localhost:8080/;
}
```

Now, console will be at `your-domain.com/hasura/console` and the API will be `your-domain.com/hasura/v1/graphql`

**Comment by bynov** [comment]
Thanks for a reply, @shahidhk !
Btw I don't understand how to manage link urls in Hasura Client App?
I mean, when I click on links inside application, there will be no '/hasura' prefix in it.

**Comment by shahidhk** [comment]
@bynov Hasura's console understands the URL prefix. The links inside the console will have `/hasura` prefix. We built it that way :smile: 

Do try it out and let us know if it is not working as expected.

**Comment by bynov** [comment]
Thanks @shahidhk for explanation and help!
It works :)

**Comment by shahidhk** [comment]
I am closing this issue. Feel free to reopen in case you have more questions :)

**Comment by moshtab** [comment]
Hi shahid

Where we have to write this nginx configuration...

**Comment by moshtab** [comment]
Hi @shahidhk 
Where we have to write this nginx configuration....
