### ISSUE TITLE
Add advanced example for aggregation queries

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#2987]
The examples we have here: https://docs.hasura.io/1.0/graphql/manual/queries/aggregation-queries.html#aggregation-queries are quite basic.

We can add a more advanced example here.

**Comment by wdtamagi** [comment]
Hello, can I work on this issue?

**Comment by marionschleifer** [comment]
@wdtamagi sure you can work on it. We created a wiki that describes how to contribute: https://github.com/hasura/graphql-engine/wiki/Hacktoberfest-2019-%F0%9F%8E%89 🙂

**Comment by wdtamagi** [comment]
Thanks @marionschleifer

**Comment by wdtamagi** [comment]
I need create new advanced example or change current examples?

Creating a new item in the table of contents, such as "Fetch Aggregate Data - Advanced Example"?

**Comment by wdtamagi** [comment]
Or just need update documentation based on https://docs.hasura.io/1.0/graphql/manual/api-reference/graphql-api/query.html#aggregateobject
?

**Comment by coco98** [comment]
@marionschleifer Let's talk to other folks on the team to discuss what kinds of examples we should add for aggregations? I think @rikinsk and @0x777 had a list...

**Comment by wdtamagi** [comment]
Great, I included the other aggregation functions: ``stddev``, ``stddev_samp``, ``stddev_pop``, ``variance``, ``var_samp``, ``var_pop`` on documentation page.

Current documentation only displays functions: ``count``, ``sum``, ``avg``, ``max`` and ``min``.
https://docs.hasura.io/1.0/graphql/manual/queries/aggregation-queries.html#aggregation-queries

**Comment by marionschleifer** [comment]
Hi everyone, we couldn't come up with an example to improve this. So I'm closing this now. Sorry to those who wanted to work on this 🙏
