### ISSUE TITLE
Where is hasura remote schema relationship?

### ISSUE THREAD

**Issue by leejh10003** [hasura/graphql-engine#2995]
I'm using hasura and added remote schema(Apollo based GraphQL server) and querying to that schema works well. Now I'm trying to make a relationship between postgresql schema record and remote schema record base on https://blog.hasura.io/remote-joins-a-graphql-api-to-join-database-and-other-data-sources/ . But relationship set feature between local schema and remote schema doesn't appears. I reloaded all remote schema again but it still not appears. Is there a way to make them appear? I'm searching them in data-><specific schema>

P.S.: Is it requires filter function to be implemented on remote schema?

**Comment by tirumaraiselvan** [comment]
@leejh10003 Are you using the Remote joins PR build?

Remote joins is in preview only and it is available here: https://github.com/hasura/graphql-engine/pull/2395 (see the docker comment here for the image: https://github.com/hasura/graphql-engine/pull/2395#issuecomment-533048840)

**Comment by leejh10003** [comment]
Oh, thanks @tirumaraiselvan ! Finally found the solution!

**Comment by marionschleifer** [comment]
@leejh10003 Happy that your problem is solved 🙂 I'm closing this issue. Feel free to re-open if you have any more questions.

**Comment by joni7777** [comment]
Any updates on when to expect this to be delivered? Really need this amazing feature!

Thanks
