### ISSUE TITLE
Distributed Tracing

### ISSUE THREAD

**Issue by PlamenHristov** [hasura/graphql-engine#3011]
Have any of you guys been able to forward trace Ids from Zipkin or Jaeger or add some kind of distributed tracing on the event callbacks?

**Comment by Maxpain177** [comment]
+1

Instana offers a nice way to do distributed traces across all microservices in a project.

In our case, we have a lot of queries via graphql-engine and it will be cool to see SQL queries, made by hasura, in our distributed traces.

Is it possible to implement the support of this plugin in graphql-engine?
https://docs.instana.io/ecosystem/haskell/

Or maybe support of Jaeger/Zipkin/opentracing?

**Comment by leejh10003** [comment]
+1
I want to use some kind of monitoring platform like https://www.datadoghq.com!. It would be cool to profile backend for optimizing service.

**Comment by gunar** [comment]
Inspiration: https://www.apollographql.com/docs/apollo-server/federation/metrics/

**Comment by polRk** [comment]
https://www.apollographql.com/docs/graph-manager/setup-analytics/#graph-manager-reporting-endpoint

**Comment by paf31** [comment]
There is some information on trace propagation [here](https://hasura.io/docs/cloud/1.0/manual/tracing.html#trace-propagation). The beta version of Hasura Cloud used custom HTTP headers but going forward, we'll be using the B3 propagation format, so it should be possible to integrate with ZipKin relatively easily.

**Comment by Bessonov** [comment]
Hey @paf31 thank you for your response! Is there any plan make it usable with own instance? If I understand correctly, traces are stored in the database, but I'm not sure how to activate it.

**Comment by jsalva** [comment]
+1

**Comment by paf31** [comment]
> Is there any plan make it usable with own instance?

I'm sorry that I'm just getting to this. Trace propagation via B3 headers is already supported in the open source edition of Hasura. Hasura Cloud will support trace span delivery to your APM system, and already supports trace visualization in the Cloud console.

**Comment by nvcnvn** [comment]
Hi @paf31 just for clarification, Hasura have B3 header propagation but do Hasura support pushing trace data to collectors?
