### ISSUE TITLE
Document workaround for array input

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#3018]
Until the time [this](https://github.com/hasura/graphql-engine/issues/348) is implemented, we should document how to pass array as literals.

Could be a section after [this](https://docs.hasura.io/1.0/graphql/manual/mutations/insert.html#insert-an-object-with-a-jsonb-column): called "Insert an object with an array column".

**Comment by lacexd** [comment]
I'd love to do it! :)

**Comment by michizhou** [comment]
Hey @marionschleifer, I would be happy to take up this issue. If there is any additional supplemental information or background you can provide to help me write up the docs, I'd appreciate it.

**Comment by marionschleifer** [comment]
@michizhou there are already two PRs for this issue: https://github.com/hasura/graphql-engine/pull/3019 and https://github.com/hasura/graphql-engine/pull/3038. 

If you would like to contribute, you can follow [this link](https://github.com/hasura/graphql-engine/wiki/Hacktoberfest-2019-%F0%9F%8E%89). There is also a link to a list of `Hacktoberfest` issues 🙂
