### ISSUE TITLE
more operators on array relationships

### ISSUE THREAD

**Issue by nukinuki** [hasura/graphql-engine#302]
Table 'first' has array relationship with table 'second'.

Would like a graphql like this:
```
query getFirst {
   first(where: {second: {id: {_isnull: true}}}) {
      id
   }
}
```

Or may be `where: {second: {id: {_eq: _null}}}`

This SQL query works:
```
SELECT first.id FROM first
LEFT JOIN second ON first.id = second.first_id
WHERE second.id IS NULL
```

This graphql hack doesn't work: `where: {second: {_not: {id:{_gte: 0}}}}`

**Comment by nukinuki** [comment]
@praveenweb Oh, you're right! It actually works ) Will use it for now

Would be good to have a solid way to check for NULL though )

**Comment by coco98** [comment]
@0x777 Can you add a note on more operators here? What other operators would you like to have?

**Comment by maxcan** [comment]
Documenting this would be 👍

**Comment by 0x777** [comment]
Documented here: https://hasura.io/docs/latest/graphql/core/databases/postgres/queries/query-filters.html#fetch-if-nested-object-s-exist-do-not-exist

**Comment by dohomi** [comment]
the link is returning 404
