### ISSUE TITLE
Creating relationship failed. table not exists when creating manual relation

### ISSUE THREAD

**Issue by tafelito** [hasura/graphql-engine#3022]
I have a table of users and a table followers with user_id and follower_id

I'm trying to create a view so I can see from a user who users he/she follows and also who follows him/her?

Table users
```
id
email
```

Table users_followers
```
id 
user_id FK --> users
follower_id FK --> users
```

To see the followers of a user, I created an array relationship followers on users table
`users_followers . user_id  → users . id`

and then to be able to see who is following a user, I created the following view
```sql
CREATE VIEW following_me AS 
  SELECT u.id as user_id,
    u1.*
    FROM users u 
    LEFT JOIN users_followers f ON u.id = f.follower_id 
    INNER JOIN users u1 ON f.user_id = u1.id;
```

and then when I try to create a manual relation from the users table to the following_me view as a reference table (`users.id --> following_me.user_id`), even tho it does appear on the tables dropdown with all the correct fields, when I save, I get and error that says `following_me table does not exists`

**Comment by rikinsk** [comment]
@tafelito seems like you might not have tracked the view `following_me` in Hasura. You can do so on the schema page by hitting the `Track` button next to the view. Tracking implies Hasura will expose the view over the GraphQL API. 

Untracked tables are not be allowed in relationships (as they aren't exposed over the API) which seems to be a bug in the console which we'll be fixing.

Do let us know if this was indeed the issue.

**Comment by tafelito** [comment]
@rikinsk If I try to track the view when I create it, it throws an error saying `function does not return a "COMPOSITE" type`

I following the documentation as it says [here](https://docs.hasura.io/1.0/graphql/manual/queries/derived-data.html)

**Comment by rikinsk** [comment]
Was a function definition part of your SQL? This error should not be thrown if we are defining the view you described above.

Nevertheless you can track an existing view from the schema page:
![Screenshot from 2019-10-08 13-39-00](https://user-images.githubusercontent.com/54616969/66378480-22099200-e9d1-11e9-8a32-94552f2f9f5c.png)

**Comment by tafelito** [comment]
I was indeed just creating the view as I mentioned before. I was not creating a function. 
Doing what you suggested actually worked. So the view was created and now I'm able to track it. It just won't allow me to track it when I create it from the SQL editor. 
I can do more tests if you need me to.
Thanks @rikinsk
