### ISSUE TITLE
The github social icon is not displaying correctly

### ISSUE THREAD

**Issue by imagentleman** [hasura/graphql-engine#3024]
The github social icon in the header of the docs (https://docs.hasura.io/1.0/graphql/manual/index.html) is not displaying the star counter properly.

Screenshot:
<img width="216" alt="Screen Shot 2019-10-04 at 9 00 49 PM" src="https://user-images.githubusercontent.com/2272928/66248309-ec238f80-e6ea-11e9-875d-38dc4f88de5a.png">

**Comment by shahidhk** [comment]
This is happening on the website too. cc @surendran82 
![image](https://user-images.githubusercontent.com/4124733/66289283-d9cb7080-e8f9-11e9-87c8-089297665e33.png)
