### ISSUE TITLE
console: server-build script fails to download assets

### ISSUE THREAD

**Issue by lexi-lambda** [hasura/graphql-engine#3026]
As of https://github.com/hasura/graphql-engine/commit/eb0c1f66425568c5fcf32c882223a2e92503412d, I get the following error when I run `npm run server-build`:

```
CommandException: No URLs matched: gs://hasura-graphql-engine/console/assets/common
CommandException: 1 file/object could not be transferred.
mv: rename ./static/dist/common/css/font-awesome.min.css.gz to ./static/dist/common/css/font-awesome.min.css: No such file or directory
gzip: can't stat: ./static/dist/common/css/font-awesome.min.css (./static/dist/common/css/font-awesome.min.css): No such file or directory
make: *** [server-build] Error 1
```

Do I need credentials to access the `gs://hasura-graphql-engine` bucket? And if so, is it intentional? It seems important that the `server-build` script be accessible to OSS contributors.

**Comment by jberryman** [comment]
Also it would be nice if we can avoid using `gsutil` at all here (at least I haven't needed to install it until now), and just use curl or wget. Here's an example https://github.com/openai/gpt-2/pull/39/files

**Comment by nathanstitt** [comment]
I also encountered this and managed to work around it by reverting the commit:

`git revert eb0c1f6`

**Comment by shahidhk** [comment]
@jberryman Can't change to curl or wget, because we need a folder downloaded, not just a file :)
