### ISSUE TITLE
Warn about problematic role permission metadata mismatch

### ISSUE THREAD

**Issue by tsujp** [hasura/graphql-engine#3037]
Hasura version: hasura/graphql-engine:v1.0.0-beta.2

Not tested on hasura/graphql-engine:v1.0.0-beta.6 as this was during an upgrade to beta.6

If you have a role that references a column name `foo` and change that column name to `bar` such that no column `foo` exists on the table that role references then Hasura will not start up upon restart due to metadata inconsistency – however doing such changes through the console does not bring up any warning. Those changes being that deleting or renaming the column `bar` does not automatically update, or give warning, about roles depending on it.

Example error:
```
{"internal":[{"definition":{"role":"foo-hook","comment":null,"permission":{"set":{},"check":{},"columns":["foo","bar","baz"]},"table":"users"},"reason":"column \"foo\" does not exist","type":"insert_permission"}],"path":"$","error":"cannot continue due to inconsistent metadata","code":"unexpected"}
```

This can be fixed by manually going into postgres and creating the appropriate column `foo` on the appropriate table and then deleting the role once Hasura starts.

Shoutout to elitan#8042 for suggesting just manually creating the column instead of trying to edit Hasura metadata directly.

**Comment by 0x777** [comment]
>however doing such changes through the console does not bring up any warning. Those changes being that deleting or renaming the column bar does not automatically update, or give warning, about roles depending on it

Hi @tsujp, this issue has been fixed in `beta.6`, the server will appropriately edit the underlying permissions now.
