### ISSUE TITLE
deploy to heroku button does not work for teams

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#305]
From Dan on intercom

**Comment by dsandip** [comment]
If this is a limitation, let's add a caveat to docs?

**Comment by shahidhk** [comment]
Let's close this issue until another report comes.

**Comment by meerasndr** [comment]
This issue came up today on Discord: 
https://discordapp.com/channels/407792526867693568/535727661167673364/664486463014043668

**Comment by areeba-arshad** [comment]
Hi, I have faced the same issue, is there any update on it. or perhaps is there any other work around.

**Comment by shahidhk** [comment]
@areeba-arshad I have just made a fix in https://github.com/hasura/graphql-engine-heroku/commit/783dfa55048816c853414189fdb4b6292d59a0a7

Can you try it out and let me know if it works on Heroku Teams now?

**Comment by areeba-arshad** [comment]
@shahidhk yes its working now, thanks

**Comment by shahidhk** [comment]
Awesome! Closing this issue now.

Fixed in https://github.com/hasura/graphql-engine-heroku/commit/783dfa55048816c853414189fdb4b6292d59a0a7
