### ISSUE TITLE
Auth webhook - self signed certificate support

### ISSUE THREAD

**Issue by Zoharos** [hasura/graphql-engine#3053]
Hi,
I'm developing using hasura and a service with a self signed certificate. When hasura webhook this service for authentication it fails because of if is a self signed certificate.
Can you create an env variable that will allow to use self signed certs like in this case?

**Comment by ecthiender** [comment]
@Zoharos take a look at this: https://github.com/hasura/graphql-engine/issues/2553#issuecomment-531171075

Can you confirm if the above solves your issue?

**Comment by thebetterjort** [comment]
No it doesn't solve the problem of SSL decyption. I'm in a large corporation and I have no way around this since I don't have access to the certs.

**Comment by shahidhk** [comment]
@thebetterjort If your organisation uses self-signed certificates, there should be a way to access them and add the ca cert (not the private key) to you client applications. Are you saying you don't have access to the ca cert at all? And all your appications disable cert validation?

As @ecthiender mentioned, you can mount the `.crt` file in `/etc/ssl/certs` directory. The tls manager that we use adds all `.crt` files under `/etc/ssl/certs` into its certificate store.

**Comment by marionschleifer** [comment]
@Zoharos just checking in if your issue is resolved? If yes, we can close this issue 🙂

**Comment by marionschleifer** [comment]
I'm closing this. @Zoharos feel free to re-open if you'd like to add anything 🙂
