### ISSUE TITLE
Besides the remote schema method, is it also possible to add apollo-server-express on top of hasura to extend the functions?

### ISSUE THREAD

**Issue by yyuankm1976** [hasura/graphql-engine#3057]
1) Want to have the customized design of schema name instead of using table name. 
2) Want to integrate business logic, such as calling REST API to integrate data and provide common graphql interface for frontend. 
Thanks!

**Comment by tirumaraiselvan** [comment]
I think you are asking, in general, how do you extend/customize the Hasura GraphQL Engine.

1. You can customize the query, mutation and subscription fields using: #2509

2. You can use apollo-server to write custom logic and add it to Hasura using Remote Schema (like you said). But you can also create relationships between your tables and remote schemas using #2395 . This is similar to extending the type with additional fields.

3. You can do further custom business logic (without remote schemas) using Actions (preview in few days)

**Comment by tirumaraiselvan** [comment]
You might notice that all of these are in PR currently but rest assured that they will be released in the next 2 or 3 releases.

**Comment by yyuankm1976** [comment]
Thanks tirumaraiselvan. I knew the integration pattern based on remote schema. What I am looking for is another pattern, that is to make hausura as a source of another apollo-server. The reason is that we want to do some joint processing from different data sources before presenting to the front-end. For example, after getting from postgresql db, we will send REST api calls to another microservice based on the acquired data. The feedback from the microservice will respond to the front-end as the response to its graphql query. Can we provide this function by adding another apollo-server on top of hausura? Thanks!

**Comment by yyuankm1976** [comment]
In addition, for the remote schema, besides the UI configuration, can I put it somewhere in the docker container during the building process? You may know the running of docker container is mostly based on the temporary storage. The rescheduling of the docker container, such as in ECS, the things configured through UI may get lost.

**Comment by tirumaraiselvan** [comment]
@yyuankm1976

>  For example, after getting from postgresql db, we will send REST api calls to another microservice based on the acquired data. The feedback from the microservice will respond to the front-end as the response to its graphql query.

The best integration pattern for this use-case can be based on Remote Joins. For e.g., you can create an apollo-server which exposes a field like the following

```
query {
  restAPIProxy(input: $InputData) {
     resultField1
     resultField2
  }
}
```
where `$InputData` is the expected input for the REST API (which would come from the hasura query as per your use-case). This value can be automatically set if you set up a remote relationship between your table and this `restAPIProxy`. Let's say you named your remote relationship `myRestAPI`, then from your client you can simply run:

```
query {
  my_hasura_table {
    field1
    field2
    myRestAPI {
      resultField1
      resultField2
     }
  }
}
```

This will make the hasura query, join the result with the remote schema and give you the combined result with a single query!

**Comment by tirumaraiselvan** [comment]
@yyuankm1976 

> In addition, for the remote schema, besides the UI configuration, can I put it somewhere in the docker container during the building process? 

You should set up migrations, so you can reproduce the exact environment anytime and anywhere. Please see: https://docs.hasura.io/1.0/graphql/manual/migrations/index.html

**Comment by marionschleifer** [comment]
@yyuankm1976 I'm closing this issue. If you would like to add something, feel free to re-open 🙂
