### ISSUE TITLE
Hasura Platform: fail to install cluster on minikube

### ISSUE THREAD

**Issue by thavorac** [hasura/graphql-engine#3060]
I'm following this tutorial [https://docs.platform.hasura.io/0.15/platform/manual/index.html](url) which show how to set up Hasura as a platform and deploy it on Kubernetes.

I'm trying to set up minikube for my development k8s cluster by following this guideline: [https://docs.platform.hasura.io/0.15/platform/manual/install-hasura/minikube.html](url). After i config everything and then try to install the cluster: 

`hasura cluster install \
  --name=minikube-hasura-cluster \
  --provider=minikube \
  --kube-context=minikube \
  --data-path=/data/hasura-data \
  --domain=$(minikube ip).xip.io \
  --external-ip=$(minikube ip)`

i always get this error:

<img width="1146" alt="Screen Shot 2019-10-08 at 4 45 49 PM" src="https://user-images.githubusercontent.com/670387/66386158-ea5c1380-e9eb-11e9-8aa8-ca714800fec6.png">

Can anyone tell me what i'm doing wrong?
By the way, here is my hasura-cli version:

<img width="354" alt="Screen Shot 2019-10-08 at 4 54 27 PM" src="https://user-images.githubusercontent.com/670387/66386560-a289bc00-e9ec-11e9-977d-091c720bbd76.png">

**Comment by marionschleifer** [comment]
@thavorac I think this question has been answered on Crip, is that correct? If your problem is solved, could you please close the issue? 🙂

**Comment by axelolsson** [comment]
@thavorac & @marionschleifer sorry for commenting on a closed issue but I'm experiencing the exact same issue – can you please provide a link to this "Crip" answer or whatever it is you're referring to?

**Comment by marionschleifer** [comment]
@axelolsson this was the answer on Crisp:

`Seems like you're using the Hasura Kubernetes platform and not the GraphQL engine. We're moving the Hasura kuberntes platform o a new location and making a lot of underlying changes. Currently, we're only actively support existing users of the kubernetes platform so I'd recommend not using the kubernetes platform for a while.`

Are you trying to setup just the GraphQL engine?
