### ISSUE TITLE
How to activate the JWT Analyzer/Inspector

### ISSUE THREAD

**Issue by bitjson** [hasura/graphql-engine#3068]
I saw [this blog post](https://blog.hasura.io/jwt-analyzer-in-hasura-console/) about the built-in JWT Analyzer/Inspector, but I can't seem to activate it in `v1.0.0-beta.6`. When I paste the JWT (and even set the Key to `Authorization`), I'm not seeing the rectangular icon.

![Screen Shot 2019-10-08 at 8 21 49 PM](https://user-images.githubusercontent.com/904007/66442563-4719f700-ea09-11e9-9399-349a2a5c3721.png)

Is this a regression, or am I doing something wrong?

Thanks!

**Comment by rikinsk** [comment]
The Authorization header should be a  Bearer token . ie. its value should be of the form `Bearer <token>`

**Comment by bitjson** [comment]
Pasting in the below doesn't seem to trigger the rectangular icon (example from jwt.io). Should this work?
```
# Key:
Authorization
# Value:
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```

**Comment by rikinsk** [comment]
@bitjson Your key and value seem correct. 

There are 2 requirements for the JWT inspector icon to show up:
- the header is an authorization header (this seems to be satisfied)
- Hasura is configured to run with JWT authentication (as described [here](https://docs.hasura.io/1.0/graphql/manual/auth/authentication/jwt.html#configuring-jwt-mode))

Can you confirm that you have configured Hasura to use JWT authentication?

**Comment by bitjson** [comment]
Ah! That's what I was missing – I was trying to use Hasura to inspect a JWT before configuring Hasura to use JWT authentication. Thanks!
