### ISSUE TITLE
Console > Data > Schema -- Selecting public schema shows ALL untracked tables

### ISSUE THREAD

**Issue by benkimpel** [hasura/graphql-engine#3078]
Selecting the public schema in Console > Data > Schema shows all untracked tables, including tables from other schemas.

I poked around at it in Web Inspector/React Devtools and I can see that the props suggest that it knows the correct schema, but is maybe just not filtering it when public is selected.

Note that `blog_posts` is in the app schema, not public.

![Screenshot from 2019-10-09 14-48-54](https://user-images.githubusercontent.com/3131496/66515053-fefbe280-eaa3-11e9-9469-fed2d38bafd2.png)

![Screenshot from 2019-10-09 14-50-15](https://user-images.githubusercontent.com/3131496/66515164-2eaaea80-eaa4-11e9-90c5-0ef1c1ba226c.png)

**Comment by rikinsk** [comment]
@benkimpel This is quite odd. We do actually filter the untracked tables to display only the ones from the current schema. Could you confirm if this is happening to you for other schemas as well eg: do you see untracked tables of public schema when you have chosen the "app" schema

**Comment by benkimpel** [comment]
@rikinsk I'll see if I can put together a small repo that reproduces the issue in isolation.

**Comment by benkimpel** [comment]
@rikinsk This issue is totally on my side. It was a migration gone awry with duplicated tables in several schemas. So sorry for the false alarm! Thanks for looking into it. Closing.
