### ISSUE TITLE
Docker with https

### ISSUE THREAD

**Issue by skunkwerk** [hasura/graphql-engine#3080]
I have hasura working using the docker image, but it doesn't work with HTTPS traffic.  How do I get Hasura to work with HTTPS traffic on port 443?  Thanks

**Comment by shahidhk** [comment]
@skunkwerk You can use something like Caddy to do HTTPS: https://github.com/hasura/graphql-engine/tree/master/install-manifests/docker-compose-https

**Comment by marionschleifer** [comment]
@skunkwerk is your question answered? If yes, could you please close the issue? 🙂

**Comment by marionschleifer** [comment]
@skunkwerk I'm closing this issue. Feel free to re-open if you'd like to add something 🙂

**Comment by wackyapps** [comment]
@marionschleifer Does this docker image also renew Let's Encrypt certs before they expire. As i know that Let's Encrypt certs expire after 90 days.
