### ISSUE TITLE
add guides/boilerplates for auth webhooks

### ISSUE THREAD

**Issue by rajoshighosh** [hasura/graphql-engine#309]
Custom auth providers and services written by users might need to store generated tokens/sessions back in the DB. 
Also perhaps create guides for different providers like auth0, firebase auth, nodejs-passport etc.

(via @jimjam on discord)

**Comment by shahidhk** [comment]
moved back here since https://github.com/hasura/graphql-engine-docs/issues/79 is archived

**Comment by Soundug** [comment]
Hi! Can I take up this issue? I would like to work on it.

**Comment by shahidhk** [comment]
We already have some boilerplates for auth webhooks: https://github.com/hasura/graphql-engine/tree/master/community/boilerplates/auth-webhooks

JWT examples are also present: https://github.com/hasura/graphql-engine/tree/master/community/examples

@rajoshighosh All the examples mentioned above are covered.
