### ISSUE TITLE
Easy way to add metadata.json to AWS ECS instances

### ISSUE THREAD

**Issue by ajhool** [hasura/graphql-engine#3091]
Hasura suggests using ECS/Fargate for production deployment. However, we're finding that adding a `metadata.json` file to the ecs containers is a major painpoint. It requires managing either a separate EBS volume, separate Docker image (and figuring out how to build it correctly), or other ad hoc solution. It's unclear what the recommended strategy is for managing metadata in a fargate deployment -- this seems like a basic, critical necessity for using hasura.

We believe that the simplest solution would be a url pointer for the metadata file; on AWS, this would probably be an S3 url where the `metadata.json` file is hosted. Restarting the ECS task or running `metadata refresh` would force a refresh on this file.

Currently, we implement this by extending the hasura graphql-server with a Dockerfile that adds the metadata into `hasura-migrations/metadata.json' into the docker image. We're not sure that this is a documented, fully-supported way to achieve this, so native support would be helpful. 

Our current Dockerfile looks like so:

```
FROM hasura/graphql-engine:v1.0.0-beta.6

# this step could be replaced with a way to retrieve a file from S3
COPY metadata.json ./hasura-migrations/metadata.json

ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["graphql-engine", "serve"]
```

**Comment by ajhool** [comment]
Another implementation might be to use the `replace_metadata` (https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/manage-metadata.html#replace-metadata) logic to execute a GET request to the desired endpoint

**Comment by shahidhk** [comment]
@ajhool Your current solution looks good, we do the same on some of our deployments too.

**Comment by marionschleifer** [comment]
@ajhool I'm closing this issue. If you'd like to add something, feel free to re-open 🙂
