### ISSUE TITLE
Feature request: support JWT keyType "EdDSA"

### ISSUE THREAD

**Issue by bitjson** [hasura/graphql-engine#3100]
It would be great if Hasura supported the [`EdDSA` JWT type](https://tools.ietf.org/html/rfc8037). It looks like the [`jose`](https://github.com/frasertweedale/hs-jose) library Hasura is using already supports it.

For any non-legacy application needing asymmetric keys, `EdDSA` (`Ed25519`) is probably the best choice. It produces much smaller signatures than RSA keys, performs well, and has [stronger security properties](https://safecurves.cr.yp.to/) than any other standardized asymmetric algorithms.

(For anyone else looking, here are a few libraries which support it:)
- [Haskell: hs-jose](https://github.com/frasertweedale/hs-jose)
- [Go: jwt](https://github.com/pascaldekloe/jwt)
- [NPM: jose](https://github.com/panva/jose)
- [PHP: jwt-signature-algorithm-eddsa](https://github.com/web-token/jwt-signature-algorithm-eddsa)

**Comment by tirumaraiselvan** [comment]
We are using `hs-jose` library and it will work automatically if you give a jwk url.

**Comment by munjalpatel** [comment]
@bitjson any updates here? What about `ECDSA`?

**Comment by pranshi06** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/d179a6f2ec357e1e25b158ff4c95b0b6f13f1174
