### ISSUE TITLE
Translation For  Readme (#HacktoberFest)

### ISSUE THREAD

**Issue by root-ansh** [hasura/graphql-engine#3106]
Hi. Can I make a PR for  translating this repo's readme to Hindi? It's the world's 3rd morst spoken language, maybe you would want it.
Thankyou

**Comment by shahidhk** [comment]
@root-ansh Go for it!

**Comment by ChiragAgarwal7** [comment]
Can I translate the security file to Hindi then?

**Comment by marionschleifer** [comment]
@ChiragAgarwal7 yes you can 🙂

**Comment by ChiragAgarwal7** [comment]
@marionschleifer can you add the Hacktoberfest label to it

**Comment by josecmj** [comment]
Would you like a translation for Portuguese also?

**Comment by marionschleifer** [comment]
@josecmj we already have a lot of Portuguese translation PRs open: https://github.com/hasura/graphql-engine/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+portuguese. If you find something that has not been translated yet, go ahead 🙂

**Comment by root-ansh** [comment]
Yeah Apologies i got busy.  @ChiragAgarwal7  Carry on with the hindi translation, good luck!

**Comment by anwari666** [comment]
I'd be happy to help with Indonesian translation too

**Comment by highflyer910** [comment]
I'd like to translate it to Russian

**Comment by maxdevjs** [comment]
Italian, si or no?

**Comment by marionschleifer** [comment]
@maxdevjs sure, go ahead 🙂

**Comment by anchal7299** [comment]
Can i translate remote-schemas file to hindi ?

**Comment by marionschleifer** [comment]
@anchal7299 sure you can 🙂
