### ISSUE TITLE
add a dry-run flag to metadata apply command

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#3127]
`hasura metadata apply` command should have a `--dry-run` flag, which will just print out the diff of the metadata being applied and the metadata on the server.

Depends on #3126 

Usage:
```
# prints out the changes that are going to be applied
hasura metadata apply --dry-run
```

**Comment by yakovleva-tanya** [comment]
Hi, I'd like to work on this one if it's still available :)

**Comment by vgvenkat** [comment]
Hi, I can work on this. I see there is a PR already for the dependant issue?

**Comment by marionschleifer** [comment]
@vgvenkat yes, there is a PR on this already open here: https://github.com/hasura/graphql-engine/pull/3157. Please have a look at our [wiki](https://github.com/hasura/graphql-engine/wiki/Hacktoberfest-2019-%F0%9F%8E%89) for more details on contributing 🙂
