### ISSUE TITLE
add a dry-run flag to migrate apply command

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#3128]
`hasura migrate apply` command should have a --dry-run flag, which will just print out the name/versions of the migrations that are going to be applied.
Usage:

```
# prints out the names of migrations are going to be applied
hasura migrate apply --dry-run
```

**Comment by kabirbaidhya** [comment]
@shahidhk Can I work on this? Please assign it to me if it's available. 

Also, it would be helpful if you can provide an example case for this - let's say how do you want the output to look like. Thanks!

**Comment by nishu88** [comment]
@shahidhk would like to work on this too.

**Comment by marionschleifer** [comment]
I don't think anyone is working on this. If you're interested in taking this up, please follow the [contributing wiki](https://github.com/hasura/graphql-engine/wiki/Hacktoberfest-2019-%F0%9F%8E%89) 🙂

**Comment by svetlasyrimis** [comment]
what would be even cooler if this command was also attempting to apply the migrations and if it doesn't succeed, rolls transaction back this way you know you have some migration that may cause inconsistency.

**Comment by meyvan** [comment]
@svetlasyrimis mentioned this command should make a transaction, apply all migrations, get the results BUT rollback immediately irrespective of whether they succeed or not. This boosts confidence that whether the migrations work or not
