### ISSUE TITLE
Downgrade from beta.7 to beta.6 fails

### ISSUE THREAD

**Issue by tejpochiraju** [hasura/graphql-engine#3129]
One of our hasura instances had been upgraded to beta.7 and now migrating to a new instance keeps failing due to issues related to #3083. 

As noted in the release notes, we are trying to run the SQL script [linked here](https://gist.github.com/0x777/4e608a975ed4efeef6ac94ea329a4e80#file-beta_7_to_beta_6-sql) to downgrade to beta.6. However, this fails with the message:

`{
    "statement": "SELECT\n  t.table_schema,\n  t.table_name,\n  t.table_oid,\n  t.description,\n  coalesce(c.columns, '[]') as columns,\n  coalesce(f.constraints, '[]') as constraints,\n  coalesce(fk.fkeys, '[]') as foreign_keys\nFROM\n  (\n    SELECT\n      c.oid as table_oid,\n      c.relname as table_name,\n      n.nspname as table_schema,\n      pd.description as description\n    FROM\n      pg_catalog.pg_class c\n      JOIN pg_catalog.pg_namespace as n ON c.relnamespace = n.oid\n      LEFT JOIN pg_catalog.pg_description pd on (c.oid = pd.objoid and pd.objsubid = 0)\n  ) t\n  LEFT OUTER JOIN (\n    SELECT\n      table_schema,\n      table_name,\n      json_agg(\n        json_build_object(\n          'column_name', name,\n          'data_type', type,\n          'is_nullable', is_nullable :: boolean,\n          'ordinal_position', ordinal_position,\n          'references', primary_key_references,\n          'description', description\n        )\n      ) as columns\n    FROM\n      hdb_catalog.hdb_column\n    GROUP BY\n      table_schema,\n      table_name\n  ) c ON (\n    t.table_schema = c.table_schema\n    AND t.table_name = c.table_name\n  )\n  LEFT OUTER JOIN (\n    SELECT\n      tc.table_schema,\n      tc.table_name,\n      json_agg(\n        json_build_object(\n          'name',\n          tc.constraint_name,\n          'oid',\n          r.oid :: integer,\n          'type',\n          tc.constraint_type\n        )\n      ) as constraints\n    FROM\n      information_schema.table_constraints tc\n      JOIN pg_catalog.pg_constraint r ON tc.constraint_name = r.conname\n    GROUP BY\n      table_schema,\n      table_name\n  ) f ON (\n    t.table_schema = f.table_schema\n    AND t.table_name = f.table_name\n  )\n  LEFT OUTER JOIN (\n    SELECT\n      f.table_schema,\n      f.table_name,\n      json_agg(\n        json_build_object(\n          'table',\n          json_build_object(\n            'schema',\n            f.table_schema,\n            'name',\n            f.table_name\n          ),\n          'ref_table',\n          json_build_object(\n            'schema',\n            f.ref_table_table_schema,\n            'name',\n            f.ref_table\n          ),\n          'oid',\n          f.constraint_oid,\n          'constraint',\n          f.constraint_name,\n          'column_mapping',\n          f.column_mapping\n        )\n      ) as fkeys\n    FROM\n      hdb_catalog.hdb_foreign_key_constraint f\n    GROUP BY\n      table_schema,\n      table_name\n  ) fk ON (\n    fk.table_schema = t.table_schema\n    AND fk.table_name = t.table_name\n  )\nWHERE\n  t.table_schema NOT LIKE 'pg_%'\n  AND t.table_schema <> 'information_schema'\n  AND t.table_schema <> 'hdb_catalog'\n",
    "prepared": false,
    "error": {
        "exec_status": "FatalError",
        "hint": "There is a column named \"description\" in table \"t\", but it cannot be referenced from this part of the query.",
        "message": "column \"description\" does not exist",
        "status_code": "42703",
        "description": null
    },
    "arguments": []
}`

`description` is a column in a couple of our tables. I am not fluent enough at SQL to decipher where this error could be coming from. 

However, this is blocking us from migrating a pretty large schema and metadata to a staging server. Any help would be appreciated!

**Comment by rakeshkky** [comment]
@tejpochiraju Hi, try running downgrade script directly on the database. Downgrade scripts may not work running in the GraphQL Engine console. 

For example using `psql`:
```bash
psql -f beta_7_to_beta_6.sql <your-database-url>
```

**Comment by tejpochiraju** [comment]
Thanks @rakeshkky - that worked.
