### ISSUE TITLE
New custom field API odd behaviour

### ISSUE THREAD

**Issue by RoryDH** [hasura/graphql-engine#3137]
The new API added in #2509 adds `track_table` (version 2) and `set_table_custom_fields` which both allow setting `custom_root_fields` and `custom_column_names`.

Attempting to set my fields to exposed as `camelCase` today revealed some odd behaviours.

I am aware this is unreleased functionality! Just want to raise the bug and suggest my opinions with regards it :) 

Tested on docker tag `hasura/graphql-engine:pull3135-9926e789` and `postgres:12`

#### Firstly,

when using `track_table`, including some of the one-word columns without changes to their name threw an error. (e.g. this request errors until you remove the fields with the <--)

```
{
  "type": "track_table",
  "version": 2,
  "args": {
    "table": "users",
    "configuration": {
        "custom_root_fields": {
          ...
        },
        "custom_column_names": {
          "created_at": "createdAt",
          "id": "id", <--
          "email": "email", <--
          "verified_at": "verifiedAt",
        }
    }
  }
}
```

`"column/relationship "id" of table "users" already exists"`

It's understandable if this is the intended behaviour. It was confusing/annoying to deal with  when wanting to update lots of fields to `camelCase` via modifying the metadata file. It could make sense to instead write the identical settings or just ignore them without throwing an error.

When the console has functionality for managing these custom names, it will obviously need to deal with excluding non-changing names.

#### Secondly,

(and more importantly) the `set_table_custom_fields` type seems to always return

```
{
  "message": "success"
}
```

whether or not I include the identical fields and it *removes* all of the `custom_root_fields` and `custom_column_names` back to defaults if it's a _"success"_ (rather than giving some sort of error).

#### Current workflow

Given what I described above, to add a new snake columns that are exposed as `camel` and have two or more words, I currently have to do the following:

- Add the col via the console (e.g. `created_at`)
- Do an `untrack_table` via an external gql console on `http://localhost:8080/v1/query`
- And then do `track_table` including the `{"created_at": "createdAt"}`

**Suggestion**

(this section should likely be a new issue but unsure what I or hasura might want)

My use case is here is that I want my JS/TS clients to be completely `camelCase` based. I like `snake_case` coming from a Rails/PG background, however, I hate mixing them! JS + graphql land seems to be in favour of `camelCase`.

One suggestion I'd like to make for a feature is to be able to pass a header (or some other per-client option) which specifies the field names it wants. This might seem a bit crazy but if I begin to write data processing service in a Python (for example), it would be cool to let it consume the API using the _real_ `snake_case` fields!

A few ideas for implementation of this might be:

- _Automagically_ convert the schema fields and types based on `X-Hasura-Graphql-Casing` passed as either `snake` or `camel`. This would mean not having to deal with setting up custom column and root fields which would be useful for me (and I assume, many others). It also would allow avoiding creating complex UI in the console for something that is quite simple.
- Keep the current system introduced in #2509 but allow a header such as `X-Hasura-Ignore-Custom-Fields` to disable/enable use of them when the client loads the schema and queries.
- Rather than custom field names being a single object associated with a table, a concept of "transformers"? could be introduced.
  - One way to think of them may simply just be **named** `custom_ root_field/column_name` configurations. However, they could possibly be far more extensible.
  - This sort of functionality is found in some gql clients already. I was looking use it as a solution to my problem here initially. It got too messy when needing also to do it consistently for codegen too...
  - I believe other people deal with this by placing a transform "proxy" of sorts in front of hasura. Although, for hasura to be the main GraphQL joiner of remote schemas that it seems to want to be, I bet some form of _graph transformation_ functionality will eventually be required!

**Comment by rakeshkky** [comment]
Hi @RoryDH 
> It's understandable if this is the intended behaviour

Yes, it is intended. If you want to keep the Postgres name as GraphQL name then omit the column in `custom_column_names`. 

> it will obviously need to deal with excluding non-changing names.

We will make a note of it. cc @wawhal 

> whether or not I include the identical fields ...

When I'm trying to reproduce in my local setup, I'm able to get the error if I include identical names in `custom_column_names`. The query type `set_table_custom_fields` will *replace* the existing configuration with the new one. See [docs](https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/table-view.html#set-table-custom-fields). 

We didn't think of generating GraphQL schema based on headers. Currently, the server maintains an in-memory cache of generated GraphQL schema and serves accordingly. If we need to generate GraphQL schema based on request headers then there will be a significant performance overhead since we need to compute entire GraphQL schema on each and every request to `/v1/graphql` endpoint.

**Comment by RoryDH** [comment]
Hey @rakeshkky, thanks for your detailed reply!

Re: the schema config files, glad you guys are thinking about this stuff!
If you were to allow different versions of the schema to be used, each version could be cached I assume. Anyway, if I need this now, what I might do is have two deployments of hasura, one that removes the custom fields (or updates them differently).


Re: `set_table_custom_fields` I maybe wasn't clear. 

When I do a `"type": "track_table"` and get a `"message": "success"` and refresh graphiql in the console, the custom fields are updated accordingly!

However, running the command with the exact same `"configuration": {` but with `"type": "set_table_custom_fields"` deletes all custom configurations and gives  (whether or not I leave in the identical fields or not).

For `set_table_custom_fields` however, using the same parameters as `track_table` it gives me `"message": "success"` but instead deletes all custom configurations every time instead of replacing or updating it to the ones I pass. i.e. it is doing `UNset_table_custom_fields` and returning 200.

(Whether or not I include the identical parameters or not it does not complain, but that's the separate and less important!)

Hope this makes it clear.

I tested there again on `pull3154-f3626247` (1hr ago) and pg12.

**Comment by rakeshkky** [comment]
Hi @RoryDH,

I'm unable to reproduce the `set_table_custom_fields` bug you're reporting. Please give me the Postgres schema and APIs you executed against the server (in sequence).

**Comment by RoryDH** [comment]
Here is how to replicate it:

**docker-compose.yml**

```yml
services:
  hasura:
    depends_on:
    - postgres
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_LOG_LEVEL: debug
    image: hasura/graphql-engine:pull3154-f3626247
    ports:
    - "8080:8080"
    restart: always
  postgres:
    image: postgres:12
    ports:
    - "5432:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data:rw
version: '3.7'
volumes:
  db_data: {}
```

1. `docker-compose up`
2. Open console and create table named `things`.
3. Add "Frequently used columns `id` and `created_at`.
4. Run the following query against the API:
    - **URL:** `http://localhost:8080/v1/query`
    - **x-hasura-admin-secret**: secret
    - JSON body:

```
{
  "type": "set_table_custom_fields",
  "version": 2,
  "args": {
    "table": "things",
    "configuration": {
       "custom_root_fields": {
          "select": "things",
          "select_by_pk": "thing",
          "select_aggregate": "thingsAggregate",
          "insert": "insertThings",
          "update": "updateThings",
          "delete": "deleteThings"
        },
        "custom_column_names": {
          "created_at": "createdAt"
        }
    }
  }
}
```

But refreshing the GraphiQL tab in the console still shows the snake case schema in the left side.

Calling the API again with

```
{
  "type": "untrack_table",
  "args": {
    "table": "things"
  }
}
```

followed by

```
{
  "type": "track_table",
  "version": 2,
  "args": {
    "table": "things",
    "configuration": {
       "custom_root_fields": {
          "select": "things",
          "select_by_pk": "thing",
          "select_aggregate": "thingsAggregate",
          "insert": "insertThings",
          "update": "updateThings",
          "delete": "deleteThings"
        },
        "custom_column_names": {
          "created_at": "createdAt"
        }
    }
  }
}
```

works as expected. Refreshing the GraphiQL shows the custom fields in the left sidebar.

Finally, run the first `set_table_custom_fields` query again. It clears the configuration completely.

The response to every query is
```
{
  "message": "success"
}
```

The following query accesses what I beleive is the source of truth for the configuration (rather than the schema in the console).

```
SELECT "configuration" FROM hdb_catalog.hdb_table WHERE table_name='things';
```

I can see how all tests might pass bar this one:
https://github.com/hasura/graphql-engine/blob/master/server/tests-py/queries/v1/set_table_custom_fields/set_and_unset.yaml#L18-L31

**Comment by rakeshkky** [comment]
Hi @RoryDH 

The request `args` for query type `set_table_custom_fields` is not correct! Please refer to [docs](https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/table-view.html#set-table-custom-fields)

**Comment by RoryDH** [comment]
🤦‍♂️

I guess I was so sure there was an issue when it was giving me success.

Not sure if stricter `args` validation is a good idea... but it would have saved me here :)

Sorry for wasting your time.
