### ISSUE TITLE
View in voyager [proposal]

### ISSUE THREAD

**Issue by joserochadocarmo** [hasura/graphql-engine#314]
What about something like a button “View in voyager” that opens up the Schema in an embedded voyager screen!

[link to graphql-voyager!](https://github.com/APIs-guru/graphql-voyager)

**Comment by vshelke** [comment]
Hi @shahidhk can i take this one up ?

**Comment by shahidhk** [comment]
@vshelke Sure, go for it. Come up with an implementation which opens voyager by clicking a new tab / button on the console. We'll iterate on the UI.

**Comment by vshelke** [comment]
ok cool @shahidhk
