### ISSUE TITLE
Migration fails because the enum needs at least one row, but my data has rows?

### ISSUE THREAD

**Issue by joshuarobs** [hasura/graphql-engine#3142]
I'm trying to migrate data from Heroku to Docker, following the guide from here https://docs.hasura.io/1.0/graphql/manual/migrations/existing-database.html.

This is what I get when I run ` hasura migrate apply --endpoint http://localhost:8080`: 
`FATA[0002] apply failed: [constraint-violation] the table "frequency" cannot be used as an enum because the table must have at least one row ($.args[2].args.tables[4])
`

Additional information:
1. The table `frequency` doesn't have zero rows, it actually has 10 rows, at least that's what I see on the original Heroku db that I ran `hasura migrate create` from.
2. `frequency` isn't the only enum table, nor was it the first one that was created. I had another enum called `archive_types` and this was created first and is alphabetically earlier than `frequency`. This enum table also has values, but the console error doesn't seem to mention it. Why would Hasura complain that that is something wrong with `frequency` but not with `archive_types`?
3. The only thing I did past `hasura migrate create "init"` was just create a test table, as stated in the guide.

Also I checked the files generated by the `hasura migrate create "init"` command, and it only seems to contain data about the whole Graphql/postgres schema itself (both the yaml and sql file). It doesn't even contain a single actual row, i.e. my test data. Is there a way to migrate the data themselves too? It seems like migration isn't that useful if it can't do this.

**Comment by coco98** [comment]
@joshuarobs In the meantime, you can add the raw SQL values for inserting enum data in the SQL file that is created for the migration. I will also try this out and get back to you with an exact set of steps you can follow!

On the Hasura side, I'm not sure why, but I'm guessing because the track as enum request for the frequency table probably happened before archive_types.

**Comment by Inch4Tk** [comment]
@joshuarobs you can check this issue for more explanations https://github.com/hasura/graphql-engine/issues/2817
In the end I also wrote a potential workaround for this problem:

> My current workaround is to simply keep a separate file around with all the sql insert statements for inserting the enums and copy pasting that to the end of the created init file.

**Comment by coco98** [comment]
@joshuarobs This should work (while we fix this with something better):

1. `hasura migrate create "init" --from-server`
2. `pg_dump <postgres-url> --column-inserts --data-only -t frequency -t archive_types >> 15xxxx_init.sql`
3. `hasura migrate apply --endpoint prod-endpoint.com`

You can add multiple -t flags for all the enum tables. Hope this helps!

**Comment by joshuarobs** [comment]
@Inch4Tk I'll try that out, thanks!
@coco98 Thanks for the response! I'm new to postgres and I am not sure where I should be calling that `pg_dump` command. If my Hasura db is on Heroku, do I call that method on the Heroku server (there's the server itself and the postgres add on), or do I call that locally? I tried running it locally and it didn't work, so would I have to install some postgres library on my machine to make it work?

**Comment by joshuarobs** [comment]
@Inch4Tk I'm sorry to ask of this, but do you have some example SQL code that you appended that pastes the values for the enums? I'm new to postgres and I have doubts that inserting data into the table the typical way may not work, thanks!

**Comment by coco98** [comment]
@joshuarobs The SQL you need to add is like this:

```
INSERT INTO public.frequency (value, description) VALUES ('HIGH', 'high frequency');
INSERT INTO public.frequency (value, description) VALUES ('MEDIUM', 'medium frequency');
INSERT INTO public.frequency (value, description) VALUES ('LOW', 'low frequency');
```

Don't worry if your SQL has some errors because the migration will fail and rollback.

The pg_dump tool would have generated those lines for you :) And yes, you'll have to install postgres on your machine to get `pg_dump` and other utilities.

**Comment by joshuarobs** [comment]
@coco98 I added those values manually and it worked, thanks!

**Comment by joshuarobs** [comment]
@coco98 I modified your statement in step 2 seeing as I am unable to install postgres locally on my machine (thereby unable to call pg_dump), and instead done it so I can call pg_dump on my docker container which contains the database.

`docker exec docker_postgres_1 pg_dump -U postgres -d postgres --column-inserts --data-only -t frequency -t archive_types >> 15xxxx_init.sql`

This can be run locally as long as you have an instance of Hasura running on docker (I believe I got it from here: https://docs.hasura.io/1.0/graphql/manual/getting-started/docker-simple.html)

I think it will only work on a local docker instance, and this data can be migrated to another docker instance or a cloud server, using step 3 `Hasura migrate...`. Not sure how I would do this to migrate from a Heroku server to a local docker one, maybe the same command, except on the server itself?

Hopefully this may help other people as well who aren't able to use pg_dump directly on their machine.

**Comment by reinvanimschoot** [comment]
Is there any update on a better solution to this problem?

**Comment by nomocas** [comment]
Hello,

I've been in the same case.

So, in fact, the _only clean solution_, which allow to keep full automation, or even which simply makes things working without any need of hand writing and/or hand copy pasting, is that the first migration (on creation) output automatically the INSERT statements for the enum values (so when the table has the "enum" flag).

**Comment by joshuarobs** [comment]
@nomocas What do you do if in the first migration, there is no table for the enums? i.e. in migration 1, you have your init, with most of your tables and enum data, and in migration 2, you have the enum tables. Will migration work if you can call INSERT statements on tables that don't exist (yet)?

**Comment by nomocas** [comment]
@joshuarobs In that case (first migration), there is no issue when applying migration/metadata, as the enum does not exists yet.

But indeed, as soon as you have enums and related relations, you'll need to have somewhere in the migration files some INSERT (which could insert only one dummy value) to those enum tables before applying metadata (or it will fail). 

So, as every db schema modification is written as a migration file, each time we insert/update/delete something in the enum tables, it should be treated as a db schema modification, and stored as a regular migration file.

Which makes sens because enums are schema related (they are "types"), not data related.

**Comment by joshuarobs** [comment]
@nomocas Do you manually create a new folder in `migrations/` every time you insert/update/delete a row in an enum table? How do you automatically handle storing insert/update/delete of rows, since Hasura doesn't have this functionality yet?

**Comment by nomocas** [comment]
@joshuarobs Yep I'm treating it by hand... That's the only solution for now.
This is not a big issue in my case, until now, because all my enums are fixed.

But, who knows what will I need tomorrow... ;)

**Comment by deathemperor** [comment]
this really needs a fix. It's troublesome if you create the migration after making the enum tables or when refreshing the migration from scratch.

**Comment by joshuarobs** [comment]
I'm not sure if this is the best approach, but i'm leaving it here incase others may run into this issue, and for further discussion of potential better options.

Currently I use this shell script to generate a unique migration that combines all migrations, but appends enums at the end. The result is that when applying this to a new fresh hasura server, everything works fine and the server has the bare minimum data it needs to operate. User generated data is not included.

I'm currently WIP making this approach work in a production setting alongside CI/CD and I'm unsure if its optimal.

````
# hasura-create-prod-migration-with-seeds.sh
# Creates a Hasura migration folder with some SQL enums in it so that it
# may be applied to another server.
#
# (Note) This is required as there's no built-in functionality for Hasura to
#        migrate seed data longside the database schema
#        Issue tracking: https://github.com/hasura/graphql-engine/issues/2431
#
# Summary:
# 1. Obtains seed data from tables defined in `seed-tables`
# 2. Generates a migration in Hasura
# 3. Adds the seed data to the migration

# The name of the docker container running the Postgres database
# Usually it's named after this repo folder's name, so we get that
DOCKER_CONTAINER=${PWD##*/}_postgres_cms_1

## Go inside the hasura/ directory or exit if there isn't any
cd hasura || exit
# ls
# docker ps
# Get a pg_dump of the whole Postgres database running locally on Docker...
# ...whilst getting only the enum tables from the "seed-tables" file
# and removing the comments in that file
docker exec $DOCKER_CONTAINER pg_dump -U postgres -d postgres \
--column-inserts --data-only $(< "seed-tables" sed '/^#/ d' | \
# Add `-t ` in front of every table name, to prepare for the command
sed -e's/^/-t /' | \
# Put everything in one line,
sed 's/$/ /' | \
# ???
tr -d '\n') | \
# Obtain only the INSERT INTO statements, i.e. the enum data
# (ignoring the schema) and put it in a temporary dump file
sed -n -e '/^INSERT INTO public/p' > .temp-dump
# Run the Hasura migration code as usual and save the result in the variable
SQL=$(hasura migrate create "init" --from-server --skip-update-check --database-name default |& \
# Obtain the version number as described in the output...
 grep -E -o '[0-9]+' | \
# ...obtaining the last number, since it outputs some extra numbers in front
# which are bugged, incorrect and useless
tail -1 | \
# Append to the number, `_init/up.sql` to create the filename of the newly
# created .sql file from the `hasura migrate`
sed -e 's/$/_init\/up.sql/')
# Go to the migrations folder
cd migrations/default || exit
# And the default database folder as of migrations v3
# cd default || exit
# Add the enums we obtained at the end of the new SQL file
echo "SQL: $SQL"
cat ../../.temp-dump >> "$SQL"

# Clean up by deleting the temporary dump file we made
rm ../../.temp-dump

# Finally, print to the console indicating the migration creation was successful
echo 'Successfully created new migration:' $SQL

````

You'll need a `seed-tables` file in the same folder as `config.yaml` in the `hasura/` folder. An example I have is:

````
colours
countries
````

It's just a text file with a list of tables that I consider enums. Most of these tables are considered enum tables within Hasura, but some are enum-like which aren't technically enums under hasura, but essentially act like an enum. In order to cater to this flexibility that I need, I put all the tables names that are considered enum-enough in this `seed-tables` file.

Running the script should work in my `project` directory, which has a `project/hasura` folder with all my hasura stuff in it. If it works without error, a new migration should be created in the `migrations` folder and you can find appended to the end of the file, all the seed data that the server needs. When applying this to a new fresh instance of a server, it loads all essential data for the server to work.

**Comment by RobSchilderr** [comment]
> I'm not sure if this is the best approach, but i'm leaving it here incase others may run into this issue, and for further discussion of potential better options.
> 
> Currently I use this shell script to generate a unique migration that combines all migrations, but appends enums at the end. The result is that when applying this to a new fresh hasura server, everything works fine and the server has the bare minimum data it needs to operate. User generated data is not included.
> 
> I'm currently WIP making this approach work in a production setting alongside CI/CD and I'm unsure if its optimal.
> 
> ```
> # hasura-create-prod-migration-with-seeds.sh
> # Creates a Hasura migration folder with some SQL enums in it so that it
> # may be applied to another server.
> #
> # (Note) This is required as there's no built-in functionality for Hasura to
> #        migrate seed data longside the database schema
> #        Issue tracking: https://github.com/hasura/graphql-engine/issues/2431
> #
> # Summary:
> # 1. Obtains seed data from tables defined in `seed-tables`
> # 2. Generates a migration in Hasura
> # 3. Adds the seed data to the migration
> 
> # The name of the docker container running the Postgres database
> # Usually it's named after this repo folder's name, so we get that
> DOCKER_CONTAINER=${PWD##*/}_postgres_cms_1
> 
> ## Go inside the hasura/ directory or exit if there isn't any
> cd hasura || exit
> # ls
> # docker ps
> # Get a pg_dump of the whole Postgres database running locally on Docker...
> # ...whilst getting only the enum tables from the "seed-tables" file
> # and removing the comments in that file
> docker exec $DOCKER_CONTAINER pg_dump -U postgres -d postgres \
> --column-inserts --data-only $(< "seed-tables" sed '/^#/ d' | \
> # Add `-t ` in front of every table name, to prepare for the command
> sed -e's/^/-t /' | \
> # Put everything in one line,
> sed 's/$/ /' | \
> # ???
> tr -d '\n') | \
> # Obtain only the INSERT INTO statements, i.e. the enum data
> # (ignoring the schema) and put it in a temporary dump file
> sed -n -e '/^INSERT INTO public/p' > .temp-dump
> # Run the Hasura migration code as usual and save the result in the variable
> SQL=$(hasura migrate create "init" --from-server --skip-update-check --database-name default |& \
> # Obtain the version number as described in the output...
>  grep -E -o '[0-9]+' | \
> # ...obtaining the last number, since it outputs some extra numbers in front
> # which are bugged, incorrect and useless
> tail -1 | \
> # Append to the number, `_init/up.sql` to create the filename of the newly
> # created .sql file from the `hasura migrate`
> sed -e 's/$/_init\/up.sql/')
> # Go to the migrations folder
> cd migrations/default || exit
> # And the default database folder as of migrations v3
> # cd default || exit
> # Add the enums we obtained at the end of the new SQL file
> echo "SQL: $SQL"
> cat ../../.temp-dump >> "$SQL"
> 
> # Clean up by deleting the temporary dump file we made
> rm ../../.temp-dump
> 
> # Finally, print to the console indicating the migration creation was successful
> echo 'Successfully created new migration:' $SQL
> ```
> 
> You'll need a `seed-tables` file in the same folder as `config.yaml` in the `hasura/` folder. An example I have is:
> 
> ```
> colours
> countries
> ```
> 
> It's just a text file with a list of tables that I consider enums. Most of these tables are considered enum tables within Hasura, but some are enum-like which aren't technically enums under hasura, but essentially act like an enum. In order to cater to this flexibility that I need, I put all the tables names that are considered enum-enough in this `seed-tables` file.
> 
> Running the script should work in my `project` directory, which has a `project/hasura` folder with all my hasura stuff in it. If it works without error, a new migration should be created in the `migrations` folder and you can find appended to the end of the file, all the seed data that the server needs. When applying this to a new fresh instance of a server, it loads all essential data for the server to work.

It amazes we need this amount of effort to simply manage enums. Thank you for typing this out.
