### ISSUE TITLE
Insert with nested returning clause fails alongside text[] column

### ISSUE THREAD

**Issue by codonnell-reify** [hasura/graphql-engine#3148]
Attempting to add a nested query inside the `returning` clause of an insert mutation fails when the table being inserted into has a `text[]` column. I've created a minimal reproduction at https://returning-bug-repro.herokuapp.com/. This bug is present on at least `v1.0.0-beta.2` and `v1.0.0-beta.6`.

Running an insert mutation without a nested returning clause succeeds. For example:
```
mutation MyMutation {
  insert_site(objects: {name: "My Site"}, on_conflict: {constraint: site_name_key, update_columns: name}) {
    returning {
      id
      name
    }
  }
}
```

However, when I add a nested query to the returning clause, the query fails. For example:
```
mutation MyMutation {
  insert_site(objects: {name: "My Site"}, on_conflict: {constraint: site_name_key, update_columns: name}) {
    returning {
      id
      name
      site_trials {
        id
      }
    }
  }
}
```
results in the error:
```
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.insert_site.args.objects",
        "code": "parse-failed"
      },
      "message": "A string is expected for type : _text"
    }
  ]
}
```

The same query with a nested returning clause runs successfully when the `site` table does not include the `emails` column. The `email` column was added with the statement
```sql
alter table site add column emails text[] not null default '{}'::text[];
```

**Comment by chunsli** [comment]
@rakeshkky just checking to see when do you think this issue can be resolved, it is affecting parts of our production deployment. thanks for working on it.
