### ISSUE TITLE
Mutations should return the same types that the query is on to leverage client cache like apollo

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#315]
(via @thangngoc89#8365)

> Is there a way to return the real type on mutation
> for example, a mutation with that add a new note returns note_no_rels  type
> I understand why is that happens from PostgreSQL perspective
> but this makes apollo cache very hard to use
> in other projects, when the returning type is the same as query type
> simply return the correct will update apollo cache

@0x777 this seems to be an important request. What are your thoughts?

**Comment by 0x777** [comment]
Yes, this has been on my mind for a while. The return type of a query and a mutation on a table should have the same types. Currently, the return type of a mutation is based on the `returning` clause of a Postgres DML mutation.
