### ISSUE TITLE
Disable CLI animations/interactivity for CI/CD

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#3151]
Flag to disable (or use a CI env var) animations type stuff on the CLI to prevent things like:
![3GjG8YwI jpg large](https://user-images.githubusercontent.com/131160/66879222-19d1c980-ef72-11e9-9478-101ec9514419.jpeg)

**Comment by lexi-lambda** [comment]
Generally, well-behaved tools auto-detect this based on whether stdout is an interactive terminal using the [`isatty` syscall](https://pubs.opengroup.org/onlinepubs/009695399/functions/isatty.html), with a flag to override the auto-detection if necessary.

**Comment by shahidhk** [comment]
This is released with https://github.com/hasura/graphql-engine/releases/tag/v1.1.0-beta.1
