### ISSUE TITLE
guide on integrating hasura with an existing nodejs backend

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#316]
(via matt donis through rajoshi)

> We currently make db calls directly from nodejs, can we replaces this with hasura?

**Comment by shahidhk** [comment]
re-opening since https://github.com/hasura/graphql-engine-docs/issues/80 have been archived

**Comment by razi-ed** [comment]
hi folks,
can I please claim this?

**Comment by shahidhk** [comment]
Sure, follow this guide and make sure that you have a draft PR open with
your plan
https://github.com/hasura/graphql-engine/wiki/Hacktoberfest-2019-%F0%9F%8E%89

**Comment by razi-ed** [comment]
I have opened a [PR](https://github.com/hasura/graphql-engine/pull/3242). Please review and point out any changes required. 

@marionschleifer 
@shahidhk

**Comment by marionschleifer** [comment]
A guide has been added to the blog: https://hasura.io/blog/turn-your-node-js-rest-api-to-graphql/. The sample app in the PR is separate from this issue and can be completed independently.
