### ISSUE TITLE
In raw SQL editor the cursor is left behind after bold characters.

### ISSUE THREAD

**Issue by trustedtomato** [hasura/graphql-engine#3160]
OS: Arch Linux
Browser: Firefox 69.0.3

As I present in this GIF, after bold characters the cursor is left behind.

![Peek2019-10-1620-04](https://user-images.githubusercontent.com/18383428/66946134-98049d80-f050-11e9-95bb-02a1ef7115df.gif)

The more bold characters are behind the cursor the more it will lag behind.

**Comment by beerose** [comment]
We've done several improvements to the Raw SQL page in the meantime and the problem looks to be solved. I'm therefore closing this issue. Please reopen it if it happens again.
