### ISSUE TITLE
Filtering when using remote relationships

### ISSUE THREAD

**Issue by fatmirsukaliq** [hasura/graphql-engine#3181]
Hi there,

Great work on Hasura!
While testing all the possible use cases that my project needs, I encountered an obstacle that I can't resolve - and I'm not sure if this is possible, therefore I'm writing you here.

I have 2 different databases, and I created the Hasura instances for each.
Then from one of them I added the other instance as a remote schema.
On the first one I'm using a table called **cars** and on the second I'm using a table called stores.

Cars have a column called **store_id**, so I created a relationship column called **store**.

```graphql
query getData {
  cars {
    id
    type
    store {
      id
      location
    }
  }
}
```
And this works as expected, it returns the **cars** with the data from remote schema **store**.

What I'm trying to accomplish is filtering the results of cars based on the store location for example:

```graphql
query getData {
  cars {
    id
    type
    store(where: { location: { _eq: "New York" } }) {
      id
      location
    }
  }
}
```
But this won't work, because this will return a list of cars and then store will return an empty object / array if it doesn't match the query.

I would expect this to be possible the same way it is possible with local relationships:

```graphql
query getData {
  cars(where: { store: { location: {_eq: "New York"} } }) {
    id
    type
    store {
      id
      location
    }
  }
}
```

But this throws an error saying that store is not defined in the schema.

I would really appreciate it if you could advise if there are plans to add support for this or any other clarification.

Thanks.

**Comment by tirumaraiselvan** [comment]
Hey @fatmirsukaliq 

That's a valid use-case that is not supported right now. This is because `store` is a remote field and `cars` is a hasura field. Now, the question is how do we merge the input arguments of a hasura field with the input arguments of a remote field. Not sure if that is easy.

**Comment by fatmirsukaliq** [comment]
Thank you on your response @tirumaraiselvan 

For now, we solved this by using Foreign Data Wrappers.

**Comment by JCMais** [comment]
@tirumaraiselvan are there plans for implementing this in the future? Or it is not even possible given what you said above?
