### ISSUE TITLE
What version of postgres is Hasura using?

### ISSUE THREAD

**Issue by joshuarobs** [hasura/graphql-engine#3182]
I can't seem to find what version of postgres Hasura is using, so what version is it?

**Comment by hgiasac** [comment]
@joshuarobs Hasura supports Postgres >= 9.5. However, it's better to use latest version, because Hasura is still improving up-to-date newest Postgres features.

If you start project from scratch, just go ahead with latest PG (currently 12)

**Comment by joshuarobs** [comment]
@hgiasac What version of postgres is used for the one-click Heroku option?

**Comment by hgiasac** [comment]
@joshuarobs You can use Postgres 11 version on Heroku
