### ISSUE TITLE
c/server + hacktoberfest

### ISSUE THREAD

**Issue by gahag** [hasura/graphql-engine#3187]
I'm a haskell programmer, and I would like to collaborate with the server component for hacktoberfest. I've seen a few issues tagged with c/server that I would be willing to work at, but there is not a single issue for the server tagged with hacktoberfest. Is the server component not participating?

**Comment by marionschleifer** [comment]
@gahag we are happy about any open source contributions, also for the server 🙂 you can pick any `server` issue that is not yet assigned and comment on it, saying that you'd like to work on it. Someone from the server team will respond to you. If you have questions, you can ask in the respective issue or in the #contrib channel of our [Discord server](http://hasura.io/discord). I'm closing this issue for now.
