### ISSUE TITLE
docs: update docs on auth webhook

### ISSUE THREAD

**Issue by dionjwa** [hasura/graphql-engine#3200]
The glitch example in the docs gives the webhook express JSON response like so:
```
// Return appropriate response to Hasura
    var hasuraVariables = {
      'X-Hasura-Role': 'user',  // result.role
      'X-Hasura-User-Id': '183b228f-8a8a-45d2-bddc-0ab3b01bbe44'    // result.user_id
    };
    response.json(hasuraVariables);
```

And this works. Great! But the docs gives the JSON format like so:
```
POST https://<your-custom-webhook>/ HTTP/1.1
Content-Type: application/json

{
 "headers": {
     "header-key1": "header-value1",
     "header-key2": "header-value2"
   }
}
```

And that extra "headers" key was giving me confusing error messages.

**Comment by marionschleifer** [comment]
The whole [auth section in docs](https://hasura.io/docs/latest/auth/overview/) has been re-written and should resolve the above issue. If you're still facing it, please feel free to re-open 🙂
