### ISSUE TITLE
Error: x-hasura-* claims: expected Text, encountered Array

### ISSUE THREAD

**Issue by ericklind** [hasura/graphql-engine#3201]
I've been trying to get a list of organizations to work, a but I keep running into this issue. In the [documentation](https://docs.hasura.io/1.0/graphql/manual/auth/authorization/roles-variables.html) is shows that  x-hasura-allowed-organisations should be able to work as an array. If I remove the claim x-hasura-allowed-organisations, I don't get any errors. This was supposed to be resolved per issues #1902. I'm on v1.0.0-beta.6

Here's the error:
```
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "jwt-invalid-claims"
      },
      "message": "x-hasura-* claims: expected Text, encountered Array"
    }
  ]
}
```

Here are the custom claims.
```
"https://hasura.io/jwt/claims": {
    "x-hasura-default-role": "user",
    "x-hasura-allowed-roles": [
      "admin",
      "owner",
      "manager"
    ],
    "x-hasura-allowed-organisations": [
      "dfd89cb1-ec34-4ff3-a7f8-22e54bce66bf"
    ],
    "x-hasura-user-id": "c02b49b3-78d6-4acd-8d81-bed07e3f161d"
  }

```
Has this actually been fixed or is there something missing on the docs on how to implement this?

**Comment by rikinsk** [comment]
This docs section might help https://docs.hasura.io/1.0/graphql/manual/auth/authorization/roles-variables.html#format-of-session-variables

**Comment by ericklind** [comment]
I was working off that as well. When I try to pass in 'x-hasura-allowed-organisations' in the header using graphiql, I get the following:

```
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "not-found"
      },
      "message": "\"x-hasura-allowed-organisations\" header is expected but not found"
    }
  ]
}
```

If I have them in the claims, it gives me an error saying that it is in a object if use `{}`, but has above array error if I use `[]`.

How are we supposed to actually pass them in if they can't be recognized from the header, but cause errors in the claims?

**Comment by ecthiender** [comment]
@ericklind #1902 was closed by mistake. We don't have support for arrays in JWT claims yet. I have added a comment there https://github.com/hasura/graphql-engine/issues/1902#issuecomment-546312118

**Comment by marionschleifer** [comment]
I'm closing this, as it's tracked here: https://github.com/hasura/graphql-engine/issues/1902.
