### ISSUE TITLE
Add full text search operator 

### ISSUE THREAD

**Issue by paranoidsp** [hasura/graphql-engine#321]
(Via reactiflux user, JPMC)

A simple operator for full text search.
https://www.postgresql.org/docs/current/static/textsearch.html

**Comment by 0x777** [comment]
This is better handled with custom functions added since `alpha37`. For example https://docs.hasura.io/1.0/graphql/manual/queries/custom-functions.html#example-text-search-functions

**Comment by Hardik-hi** [comment]
You can refer here if above URL gives 404

https://hasura.io/docs/latest/schema/postgres/custom-functions/#example-text-search-functions

@0x777 Kindly update the same in your comment
