### ISSUE TITLE
Querying based on UNIQUE constraint

### ISSUE THREAD

**Issue by xorander00** [hasura/graphql-engine#3210]
Per discussion on Discord #general...  
  
It would be nice to be able to query a single (or empty) record that is filtered by a UNIQUE constraint instead of just the primary key.  In my case, I'm using an INT PRIMARY KEY that is only visible within the database and a UNIQUE UUID that is used externally by clients.
  
As it is currently, you either have to use table_by_pk or table(...), the latter of which always returns an array of records, and the former of which clients cannot use because they only have a UUID.
  
The suggestion in Discord by Tiru was table_by_unique(...), which would take as parameters the auto-generated UNIQUE constraints that are on the table.

**Comment by rikinsk** [comment]
Already requested for in #2418, #1606

**Comment by ecthiender** [comment]
We can close this issue then?
