### ISSUE TITLE
Update Readme.md file

### ISSUE THREAD

**Issue by jddeep** [hasura/graphql-engine#3215]
The documentation of the project/ the readme file needs some updates:
1. A branch policy can be added.
2. The best practices for contributing section can be updated and some points can be reformed.
3. Redundancy under Table of contents as the heading is itself stated twice.

**Comment by jddeep** [comment]
@rikinsk Can I work on this? This might be a small contribution to the project. But will help me get started with it at least. Please do let me know. Thanks.

**Comment by rikinsk** [comment]
@jddeep Thank you for thinking about contributing to Hasura. Unfortuntely the changes you've suggested are not of any real value to the product. If you are really willing to contribute I would suggest you to pick up an issue labelled ``good first issue`` or ``hacktoberfest``
