### ISSUE TITLE
add guidelines to report security issues

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#322]
README has to be updated with a section that lays out guidelines to report security issues, preferably an email address.

**Comment by vipulgupta2048** [comment]
Should I take this up?

**Comment by shahidhk** [comment]
Thanks for your interest @vipulgupta2048. @dsandip can put the content here and you can create a PR.

@dsandip Does that work?

**Comment by dsandip** [comment]
@shahidhk @vipulgupta2048 : @shark-h had done some work on this a while back here: https://github.com/shark-h/graphql-engine/tree/sec_info. Check out https://github.com/shark-h/graphql-engine/tree/sec_info#contributing and the linked .github/SECURITY.md. 

@vipulgupta2048 : Will you review/revise that and submit a P.R?

**Comment by vipulgupta2048** [comment]
I have written a considerable amount of open-source documentation now. I will see what I can pull :hatching_chick: 
Taking it up.
