### ISSUE TITLE
Support args in computed columns

### ISSUE THREAD

**Issue by leoalves** [hasura/graphql-engine#3222]
In the computed column function we only have access to the database row values.  I think it would be useful to also pass some arguments in the query, in the same way we do with functions.  

I was thinking something like:

```SQL
CREATE FUNCTION calc_distance(user_row user, location json )
 RETURNS NUMERIC AS $$
   SELECT ST_DISTANCE(user_row.location::geography, ST_GeomFromGeoJSON(location)::geography)
 $$ LANGUAGE sql STABLE;
```

and the query

```javascript
query {
  user ({
    args: {
    location: {
     type: "Point",
     coordinates: [-79.3741255,43.64272],
      crs: {
        type: "name",
        properties: {
          name: "EPSG:4326"
         }
      }
    }
  }) {
    name
    address
    distance
  }
}
```

Thanks

**Comment by rikinsk** [comment]
@leoalves I believe you can already do this. Check out [this example](https://docs.hasura.io/1.0/graphql/manual/schema/computed-fields.html#table-computed-fields) in the docs. It adds a computed field which accepts a `search` as argument

**Comment by leoalves** [comment]
@rikinsk 
LOL. I guess reading the documentation helps.
I was reading the how to only from the release notes.
Thanks
