### ISSUE TITLE
CLI doesn't support passwords with $ when you do `hasura init`

### ISSUE THREAD

**Issue by KevinColemanInc** [hasura/graphql-engine#3235]
For those of you that have a $ in your password, running `hasura init`

```
FATA[0001] failed to export metadata: cannot create migrate instance: [access-denied] invalid x-hasura-admin-secret/x-hasura-access-key ($)
```

To reproduced:
```
hasura init --endpoint https://my-graphql-engine.com --admin-secret a$bcd
```

Your config.yaml will look like:
```
admin_secret: a
endpoint: https://my-graphql-engine.com
```

Running version `v1.0.0-beta.8`

**Comment by shahidhk** [comment]
This is because bash is doing $expansion.

Escape the $ and try again?

`hasura init --endpoint https://my-graphql-engine.com --admin-secret a$$bcd`

**Comment by KevinColemanInc** [comment]
I tried that as well. here is the config.yaml of your command.

```
admin_secret: a73385bcd
endpoint: https://my-graphql-engine.com
```

**Comment by KevinColemanInc** [comment]
I see this is more of a bash issue than a CLI issue :-/ I just tested this with a simple ruby script and it has the same issue :-/.

I will close the issue and hopefully this will help other people.
