### ISSUE TITLE
Add aggregation queries for computed fields

### ISSUE THREAD

**Issue by tafelito** [hasura/graphql-engine#3238]
Are you planning to add aggregation queries to computed fields?

**Comment by rakeshkky** [comment]
@tafelito  Yes, indeed. We will add support to aggregation on computed fields returning set of table rows. :slightly_smiling_face:

**Comment by pankgeorg** [comment]
Is there a timeline for that?

**Comment by janhaa** [comment]
Any update on this?

**Comment by hthillman** [comment]
Seconded, it's possible to work around this using a view but allowing aggregations on computed fields would make it *much* easier

**Comment by muhajirdev** [comment]
no update yet?

**Comment by CloudPower97** [comment]
Just stumbled upon this issue myself... Are there any updates on this? 🙏🏻

**Comment by lewi6** [comment]
Heyy is there anyone who found a way to tackle this ??

**Comment by vinodhj** [comment]
there is no update yet ?

**Comment by OgiBalboa** [comment]
Hey! We're looking forward to this feature!

**Comment by vxm5091** [comment]
+1 This would be super helpful to have

**Comment by AndRud** [comment]
Please, add this feature. It will be really helpful

**Comment by sudorafa** [comment]
up

**Comment by rikardwissing** [comment]
+1

**Comment by dameleney** [comment]
We are happy to report this enhancement should be going into version 2.27.

**Comment by vinodhj** [comment]
You intend to make this improvement three and a half years after this request was made.

**Comment by manasag** [comment]
This is now supported in [v2.27.0-beta.1](https://github.com/hasura/graphql-engine/releases/tag/v2.27.0-beta.1)

**Comment by marionschleifer** [comment]
Hey folks, we will present aggregation queries for computed fields in our upcoming community call on Thursday, July 27 at 9am PT. Sign up [here](https://hasura.io/community/community-call/). We hope to see you there!
