### ISSUE TITLE
Working with Postgres dates and times in queries

### ISSUE THREAD

**Issue by bitjson** [hasura/graphql-engine#3244]
Is there any documentation on what Postgres operators are available when querying/setting dates/times? It's awesome that I can make a query like this (note the `now()` in `where` and `_set`):
```gql
 mutation ConfirmEmail($token: String!) {
        update_email_confirmation(
          where: { token: { _eq: $token }, created_at: { _lt: "now()" } }
          _set: { confirmed_at: "now()" }
        ) {
          returning {
            email_confirmation_id
            email
            created_at
            confirmed_at
          }
        }
      }
```

I'd love to be able to [subtract 30 days](https://www.postgresql.org/docs/current/functions-datetime.html) from the `now()` in the where clause, e.g.:
```gql
 mutation ConfirmEmail($token: String!) {
        update_email_confirmation(
          where: { token: { _eq: $token }, created_at: { _gt: "now() - interval '29' day" } }
          _set: { confirmed_at: "now()" }
        ) {
          returning {
            email_confirmation_id
            email
            created_at
            confirmed_at
          }
        }
      }
```
But I'm missing something, or this isn't yet supported:
```json
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "data-exception"
      },
      "message": "invalid input syntax for type timestamp with time zone: \"now() - interval '29' day\""
    }
  ]
}
```

Anyone have any hints on how I can query for something "within the past 30 days"?

**Comment by yuvalgut** [comment]
Make a view that filters by 30 day, thats one option.

**Comment by rikinsk** [comment]
Related to #2699

**Comment by marionschleifer** [comment]
Closing this in favour of #2699 🙂

**Comment by Taho2007** [comment]
This big issue makes "Hasura" almost worthless thing. We may not use "intervals" for datetime comparisons in "where" clause. BAD.

**Comment by dan-lee** [comment]
@Taho2007 your comment sounds like a typical donald trump tweet..

anyway, the date functionality would be greatly appreciated. though, it's not too hard to make it work on implementation side.

**Comment by jawang94** [comment]
bump - is this working yet?

**Comment by Anteloper** [comment]
+1

**Comment by yangyang480** [comment]
Does anyone figured out how to do it?

**Comment by nbouvrette** [comment]
One way to work around this would be to set an `expires_at` column where you predefine the time of the expiration. To ensure that the column has the correct value, you need to let Hasura set its value based on the server time by using a column default value like this:

`(now() + '1 day'::interval)`

And then you can make queries like `expires_at > now()`
