### ISSUE TITLE
[Question] Insert multiple objects at once with variables

### ISSUE THREAD

**Issue by divramod** [hasura/graphql-engine#3254]
Hey, thx for the awesome project!

I'm a hasura / graphql beginner and like to ask, if it is possible to insert multiple objects at once with graphql-request using variables and how it should look like.

I was able to successful insert a single entity like that:
```
  import { request } from 'graphql-request'
  const variables = { id: 123, name: "test" }
  const gql = `mutation insert_test(
    $id: Int!
    $name: String! 
  ) {
    insert_test(
      objects: {
        id: $id,
        name: $name
      }
    ) {
      returning {
        id
      }
    }
  }`
  const res = await request(HASURA_URL_GRAPHQL, gql, variables)
```
But when changing the variables to an array i got an error.

```
  import { request } from 'graphql-request'
  const variables = [{ id: 123, name: "test" }, { id: 456, name: "test1" }]
  const gql = `mutation insert_test(
    $id: Int!
    $name: String! 
  ) {
    insert_test(
      objects: {
        id: $id,
        name: $name
      }
    ) {
      returning {
        id
      }
    }
  }`
  const res = await request(HASURA_URL_GRAPHQL, gql, variables)
```

Can someone give me a hint into the right direction here? Thx in advance!

**Comment by marionschleifer** [comment]
@divramod Hasura doesn't support Postgres arrays yet. There is an open issue [here](https://github.com/hasura/graphql-engine/issues/348). [This docs page](https://docs.hasura.io/1.0/graphql/manual/mutations/insert.html) shows how to insert multiple objects at once. Let us know if you have any more questions 🙂

**Comment by coco98** [comment]
@divramod You can change your variables input to be the object type and it should be fine after that:

```
 import { request } from 'graphql-request'
  const variables = [{ id: 123, name: "test" }, { id: 456, name: "test1" }]
  const gql = `mutation insert_test($objects: [test_insert_input!]!)
  ) {
    insert_test(
      objects: $objects
    ) {
      returning {
        id
      }
    }
  }`
  const res = await request(HASURA_URL_GRAPHQL, gql, variables)
```

To get the exact type name there (test_insert_input) you can use the "docs" tab on the hasura graphiql console :)

**Comment by marionschleifer** [comment]
@divramod I'm closing this issue. Feel free to re-open if you'd like to add anything to it 🙂

**Comment by evertonfoz** [comment]
Hello @marionschleifer.

I am following your guidance to perform the following insert

`mutation insertUserTags ($ user_tags_insert_input: [user_tags_insert_input!]!) {
    insert_user_tags (objects: [$ user_tags_insert_input]) {
            affected_rows
    }
}`

with the variable

`{"user_tags_insert_input":
  [{"name": "Study", "userId": "a"}, {"name": "Study", "userId": "a"}]
}`

but I get the error

`variable user_tags_insert_input of type [user_tags_insert_input!]! is used in position expecting user_tags_insert_input! "`

Can you help me, please?

**Comment by hafiztahajamil** [comment]
Hi @evertonfoz 
You have to remove array brackets around $user_tags_insert_input.

If a variable is declared as an array  then brackets aren't required while passing the value to objects
mutation insertUserTags ($ user_tags_insert_input: **[**user_tags_insert_input!**]**!)

- What you are doing (Wrong): insert_user_tags (objects: **[**$ user_tags_insert_input**]**) {             affected_rows     } }
- What you should do (Right) :  insert_user_tags (objects: $ user_tags_insert_input) {             affected_rows     } }

**Comment by evertonfoz** [comment]
Hi @hafiztahajamil 

Thanks for the feedback. When I use

`mutation insert User Tags ($ objects: user tags_insert_input) {
   insert_user_tags (objects: $ objects) {
      affected_rows
   }
} `

with the variables

`{
    "objects":
    [{
      "name": "Study", "userId": "a"},
    {"name": "Study", "userId": "a"}
    ]
  } `

I get the error

`{
  "errors": [
    {
      "extensions": {
        "path": "$ .variableValues.objects",
        "code": "validation-failed"
      },
      "message": "expecting a JSON object"
    }
  ]
} `

And already in the fields where I inform the mutation and variables, there is an error about sending an unexpected array in the mutation.

**Comment by hafiztahajamil** [comment]
Hi,
You shouldn't change this: *mutation insert User Tags ($ objects: user
tags_insert_input)*
This should remain: mutation insert User Tags ($ objects: [user
tags_insert_input!]!)

Final Mutation:

mutation insert User Tags ($ objects: [user tags_insert_input!]!) {
insert_user_tags (objects: $objects) { affected_rows } }

Let me know if it works for you :)

**Comment by evertonfoz** [comment]
It Works. Thanks a lot :-)

**Comment by hafiztahajamil** [comment]
👍

**Comment by iamsahu** [comment]
I am getting the following error 
Error: GraphQL error: 0 is not valid GraphQL name

I am passing the following:
`[{tag: "test1", curator: "26b4e98c-b5dc-4810-97b9-909ddc74c4f0"},{tag: "test2", curator: "26b4e98c-b5dc-4810-97b9-909ddc74c4f0"}]`

Here is my query:
```
export const INSERT_TAGS2 = gql`
    mutation MyMutation($objects: [tag_insert_input!]!) {
        insert_tag(objects: $objects) {
            returning {
            name
            }
        }
    }
`
```

Here is how I am trying to call it:
`const [createTag,{errorTag}] = useMutation(INSERT_TAGS2,{
        variables:[{tag: "test1", curator: "26b4e98c-b5dc-4810-97b9-909ddc74c4f0"},{tag: "test2", curator: "26b4e98c-b5dc-4810-97b9-909ddc74c4f0"}],
        onError:(error,variables)=>{
            console.log(error)
            // console.log(variables)
        }`

**Comment by justdvl** [comment]
I am getting same error as @iamsahu  and help would be greately appreciated.

**Comment by iamsahu** [comment]
Sure.

Here is a piece of code that let me achieve it.

The query:
`
const INSERT_TAGS = gql`
	mutation MyMutation($objects: [tag_insert_input!]!) {
		insert_tag(objects: $objects) {
			returning {
				id
				name
				user_id
			}
		}
	}
`;
`

The code to run the query:
`
function InsertNewTags(tags, curator_id) {
	return client
		.mutate({
			mutation: INSERT_TAGS,
			variables: {
				objects: tags,
			},
		})
		.catch((error) => {
			console.log(error);
		});
}
`

In the tags parameter of the above function an array of objects is passed.
`
tags = [{ name: values.selTags[a], user_id: values.curator_id },{ name: values.selTags[a], user_id: values.curator_id }]
`

I hope this helps.

**Comment by justdvl** [comment]
Thank you.. Right. I figured it out finally. I was inputting into variables directly an array of my stuff to insert; while I should have give it an object with key "objects" and value that array. Like:

` insertCompanyCategories({
                variables: {
                  objects: [
                    {
                      category_id: "9d854204-ace4-11ea-8e47-02420aff0066",
                      company_id: "5b675516-8baa-11ea-97ad-02420aff0004",
                    },
                    {
                      category_id: "d287c566-aafb-11ea-b094-02420aff0004",
                      company_id: "5b675516-8baa-11ea-97ad-02420aff0004",
                    },
                  ],
                },
              });`

**Comment by suganth745** [comment]
@iamsahu Awesome, it works for me. @justdvl thanks you too.

**Comment by harshitagupta6** [comment]
Schema: 
input  AppformixReportsInput {
    timestamp: String!
    }

type AppformixReports {
timestamp: String!
}

type CreateAppformixPayload {
  single: AppformixReports!
}

type CreateMutlipleAppformixPayload {
  multiple: [AppformixReports]
}

type Mutation {
    CreateSinglePayload(input: AppformixReportsInput!): CreateAppformixPayload
    CreateMultiplePayload(input: [AppformixReportsInput!]!): CreateMutlipleAppformixPayload
}

mutation:
mutation CreateMultiplePayload($input: [AppformixReportsInput!]!){
  CreateMultiplePayload(input: $input) {
   _id
  }
}

query variables:
{
	"input": [
		{
			"timestamp": "14/31/2020 14:37"
		},
		{
			"timestamp": "14/31/2020 14:37"
		},
		{
			"timestamp": "14/31/2020 14:37"
		},
		{
			"timestamp": "14/31/2020 14:37"
		}
	]
}

Output:
{
  "data": {
    "CreateMultiplePayload": {
      "_id": "66"
    }
  }
}

This is the output, but no data is populated in the database.
Any kind of help is greatly appreciated.

**Comment by yogeshwar607** [comment]
> "docs" tab on the hasura graphiql console

Any reference to get this value using hasura cloud  ?
