### ISSUE TITLE
Incorrect ordering in returned JSON from nested mutation

### ISSUE THREAD

**Issue by jberryman** [hasura/graphql-engine#3271]
We get failures from these two queries

	   server/tests-py/queries/graphql_mutation/insert/nested/articles_with_author.yaml
	   server/tests-py/queries/graphql_mutation/insert/nested/author_with_articles.yaml

after https://github.com/hasura/graphql-engine/pull/2831

Marked `xfail` in that branch

**Comment by 0x777** [comment]
Fixed with https://github.com/hasura/graphql-engine/commit/53b9cabd88d61f7ffbf8720b201410ea2d0bace2
