### ISSUE TITLE
make cursor pointer on "track" and "cascade" checkboxes on sql page

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#3276]
![SQL Page](https://user-images.githubusercontent.com/27274869/68106578-0b8b2380-ff08-11e9-830d-8745155b2437.png)

In the above image, the cursor needs to be made a "pointer" on the checkboxes: `Track this` and `Cascade Metadata` .

You can find this page at the `/data/sql` route of the console.

**Comment by coco98** [comment]
I think this refers to making the cursor a "pointer" on the relevant checkboxes. @wawhal @rikinsk ?

**Comment by wawhal** [comment]
@nik72619c I have updated the description. Apologies for the delay.
