### ISSUE TITLE
Manual Hasura schema creation, or separate schema vs. read/write IDs?

### ISSUE THREAD

**Issue by Android3000** [hasura/graphql-engine#3279]
We have an environment that is fairly locked down for access. We have very short lived "deploy" IDs that can create tables/objects etc., and separate IDs for CRUD operations that are long lived. Typically, we manage DB migrations through something like Flyway: upon deploy of a build, Flyway will use the deploy ID to create any necessary tables, and then the app itself uses the CRUD ID.

You can probably see where this is going. For the tables and triggers and functions and things that support Hasura, we're trying to find a way to be able to get that stuff created upon deploy of a build. We don't use the console in a deployed environment to do any updates after that point; everything is managed via imports of a new versioned metadata file. What we need to do is something like one of the following:

1. Pre-stage all necessary Hasura tables for first deployment. Also, pre-stage any subsequent triggers/functions/etc. for migrations so that Hasura can just use what's there vs. trying to create the triggers/functions on its own. This definitely could be fragile if there are any changes to things in Hasura version upgrades.

or

2. Provide Hasura with separate IDs for schema creation operations versus CRUD operations. That way, we could have Hasura do its work upon deployment/migrations using the deploy ID, while using the CRUD ID for subsequent graphql operations. This probably seems the more stable of the options in terms of maintaining future compatibility.

Any thoughts on how we might accomplish something like this? Or are there others out there who might be able to benefit from having something like this in place?

**Comment by rakeshkky** [comment]
Hi, @Android3000

You can start up the server with "Deploy" Ids to initialise/migrate the database and import the necessary metadata. After bringing down the instance, start another instance with CRUD Ids by configuring only GraphQL API (See [docs](https://docs.hasura.io/1.0/graphql/manual/deployment/production-checklist.html#disable-apis))

**Comment by Android3000** [comment]
Thanks @rakeshkky! That does work, and we may end up going that route. Appreciate the feedback!
