### ISSUE TITLE
a major bug with queries using where

### ISSUE THREAD

**Issue by forkandfix** [hasura/graphql-engine#3283]
I'm using v1.0.0-beta.8

Here's the query I'm trying to execute

```graphql
query MyQuery {
  Order(where: {_or: {status: {_eq: SUBMITTED}}, status: {_eq: ACCEPTED}}) {
    id
    status
    createdAt
  }
}
```

Here's the generated SQL

```SQL
SELECT
  coalesce(json_agg("root"), '[]') AS "root"
FROM
  (
    SELECT
      row_to_json(
        (
          SELECT
            "_1_e"
          FROM
            (
              SELECT
                "_0_root.base"."id" AS "id",
                "_0_root.base"."status" AS "status",
                "_0_root.base"."createdAt" AS "createdAt"
            ) AS "_1_e"
        )
      ) AS "root"
    FROM
      (
        SELECT
          *
        FROM
          "public"."Order"
        WHERE
          (
            (
              ("public"."Order"."status") = (('SUBMITTED') :: text)
            )
            AND (
              ("public"."Order"."status") = (('ACCEPTED') :: text)
            )
          )
      ) AS "_0_root.base"
  ) AS "_2_root"
```

why is it using the AND operator ??

**Comment by ecthiender** [comment]
The syntax you have, is not what you want, I think. Right now it is:

```graphql
{
  _or: {
    status: {
      _eq: SUBMITTED
    }
  },
  status: {
    _eq: ACCEPTED
  }
}
```
You have two expressions in the object:

1. `_or: { status: { _eq: SUBMITTED  } }`
2. `status: { _eq: ACCEPTED }`

When you have two expressions in the where object, like `{ exp1, exp2}`, it is assumed to be an `AND` operation. In your expression 1, `_or` has only one sub-expression so it is equivalent to `status: { _eq: SUBMITTED }`. And you expression 2 is `status: { _eq: ACCEPTED }`. Hence, it generates an `AND` expression with those two.

Also note, that the syntax for `_or` is, that it takes a list of expressions. Like `{_or: [ exp1, exp2 ]}`. (https://docs.hasura.io/1.0/graphql/manual/api-reference/graphql-api/query.html#orexp)

What you want, I think, is:

```graphql
{
  _or: [
    {status: {_eq: SUBMITTED}},
    {status: {_eq: ACCEPTED}}
  ]
}
```
Let me know if this helps.

**Comment by forkandfix** [comment]
@ecthiender It does. Thank you very much.

sorry my bad 😅
