### ISSUE TITLE
Can't find type array in Hasura UI

### ISSUE THREAD

**Issue by deadcoder0904** [hasura/graphql-engine#3284]
I have a `tags` column which will have values like `dev`, `design`, etc...

So it makes sense to use array.

But the problem is I can't find anything in the UI with that type. How do I do it?

**Comment by victorferreira** [comment]
What's ```tags``` column type? Hasura will treat each column on your schema as an attribute in you GraphQL object. To use a column you could use a JSON array on a JSONB column, or you could have a separated table for tags and define the the relationship as ```one-to-many``` or ```many-to-many``` and track the relationship between the tables to have the tags listed as an array.

You can find more info about relationship in the [docs](https://docs.hasura.io/1.0/graphql/manual/schema/relationships/index.html).

**Comment by deadcoder0904** [comment]
Thanks that worked. I made `tags` a JSON array & could paste in `["dev", "design"]` to insert data.

I didn't want to create another table for just 1 field so was curious. Thank you so much :)
