### ISSUE TITLE
[Question] How activate compression on subscriptions

### ISSUE THREAD

**Issue by juniorUsca** [hasura/graphql-engine#3292]
Hi

I'm starting with Hasura and I found compression for queries over http

https://docs.hasura.io/1.0/graphql/manual/deployment/compression.html

but I don't know if hasura engine has compression for subscriptions enabled over web sockets

If not, how can I enable it?

**Comment by 0x777** [comment]
@juniorUsca Thanks for pointing this out. Looks like we will need to support the extension `permessage-deflate` in our websockets server as per [RFC7692](https://tools.ietf.org/html/rfc7692). Your client will also need to support this extension for compression to kick in.

**Comment by nolandg** [comment]
This would be a big help for reducing mobile data usage.

**Comment by abooij** [comment]
The websockets Haskell package [seems to support compression](https://hackage.haskell.org/package/websockets-0.12.7.1/docs/Network-WebSockets-Connection.html#t:ConnectionOptions). The code path through which it's currently disabled is our use of `defaultConnectionOptions` in `server/src-lib/Hasura/Server/App.hs`. So I think the steps towards implementing this would be:

1. Expand the `ServeOptions` data type in `server/src-lib/Hasura/Server/Init/Config.hs` to additionally store a `ConnectionOptions` (from the [websockets](https://hackage.haskell.org/package/websockets-0.12.7.1/docs/Network-WebSockets-Connection.html#t:ConnectionOptions) package).
2. Add a command-line flag for setting compression options: a simple on/off switch that uses sensible defaults for the value of `PermessageDeflate`. Expand `server/src-lib/Hasura/Server/Init.hs` to support parsing this flag, and store a corresponding value in the `ServeOptions` object. The default value should be `defaultConnectionOptions`, and enabling the compression flag should merely change the `connectionCompressionOptions` field of that `defaultConnectionOptions`.
3. Somehow pass this value to `mkWaiApp` in `server/src-lib/Hasura/Server/App.hs`, replacing our usage of `defaultConnectionOptions`.
4. Write a sample application that shows a huge response being transferred in the fraction of the time it would take without compression. (An extremely repetitive string should compress well.) This will require figuring out which websocket client libraries support compression.

**Comment by gahag** [comment]
Can I work on this?

**Comment by abooij** [comment]
@gahag Everybody's welcome to work on any issue! You don't need to ask for permission before you start. You can open a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to show any partial work.

**Comment by nolandg** [comment]
Has anyone got Apollo Client to and `subscriptions-transport-ws` Node.js package to talk nice with this compression?
