### ISSUE TITLE
Configure trigger to add related data in payload

### ISSUE THREAD

**Issue by tombroens** [hasura/graphql-engine#3298]
Related to #3247, to make the payload of a firing trigger a bit more elaborate.

Add to trigger configuration (in the console) the ability to select the relation to be added in the payload. E.g. set trigger on table Article (which has a relationship with table User), select User(firstname, lastname) to be added in the payload when the trigger on Article fires.

Possible challenge is to support n:m relationships as they probably include 2 levels of releationships. But 1:n would already be very helpfull.

**Comment by fbrbovic** [comment]
This would help greatly in reducing the number of calls back to Hasura server in my use case so got my vote for this :)

**Comment by sobrinho** [comment]
That's important here as well!

We can easily trigger hundreds of events here that needs to go back to Hasura to pull a specific field of our table (a computed one, of course).

**Comment by tirumaraiselvan** [comment]
Going to close this as dupe of: https://github.com/hasura/graphql-engine/issues/3298

Pls comment/reopen if you feel otherwise!

**Comment by sobrinho** [comment]
That's the #3298 😂
