### ISSUE TITLE
Parse failed on correct query?

### ISSUE THREAD

**Issue by boydenhartog** [hasura/graphql-engine#3300]
I'm trying to connect my application to my hasura app. I've tested the query in graphiql and it works as expected. When I use the same query from my frontend application, I get this 400 error:
` {"path":"$","error":"key \"type\" not present","code":"parse-failed"}`

I'm not really sure why I'm getting this error? There is no field called type on my resource.

This is my query: 
```
const QUERY = gql`
  query MyQuery {
    cards {
      id
      name
      number
      deck_id
      description
     }
    }
`;
```

**Comment by 0x777** [comment]
Looks like you are sending the query to `/v1/query` which is an internal interface for the console, it should instead be to `/v1/graphql`.

**Comment by ecthiender** [comment]
@boydenhartog hope this resolves your issue. If not, you can comment or reopen the issue.

**Comment by boydenhartog** [comment]
@ecthiender thank you. I decided to move on with a different backend because of a tight deadline. I will give Hasura another try for my next project as it looks great!
