### ISSUE TITLE
Error: "Unsupported Version: 26"

### ISSUE THREAD

**Issue by jeremy-london** [hasura/graphql-engine#3302]
* **I'm submitting a ...**
  - [x] bug report/support request

* **What is the current behavior?**
Hasura fails to start due to unsupported version error

* **Please tell us about your environment:**
  
  - Version: 1.0.0-beta.9 (Upgraded from -beat.5)
  - Browser: all
  - Deployment: Openshift (on k8s)

* **Other information** 
```
  | {"path":"$","error":"unsupported version : 26","code":"not-supported"}
```

* Background
I have had hasura running on `-beta.5` for a month with no issues. 
Recently upgraded to `-beta.9` and seeing this error intermittently as a new container starts..

**Comment by jeremy-london** [comment]
After additional troubleshooting, it was found my deployment process was not pulling the correct image during its re-deployment.

Hence the error found while looking at the catalog version.

**Comment by Ant59** [comment]
Getting this problem. Image correct. Deploying version beta.4.
