### ISSUE TITLE
creating permission through the API leaves metadata inconsistent

### ISSUE THREAD

**Issue by tafelito** [hasura/graphql-engine#3319]
Adding a permission to a computed field through the API leaves the metadata inconsistent

Since there is no way right now to add a computed filed permission through the console, I'm using the create_select_permission API to add the permission to the table. 

Here's the request to add permission
```
{
    "type" : "create_select_permission",
    "args" : {
        "table" : "clients",
        "role" : "user",
        "permission" : {
            "columns" : ["description", "id", "logo_url", "name", "website_url"],
            "filter" : {
                "users" : {"id":{"_eq":"X-Hasura-User-Id"}}
            },
            "computed_fields": ["sections"]
        }
    }
}
```

After this, everything works fine. But when I restart the console, I get the inconsistent metadata error. 
Then I try to remove the permission through the API and I get this error
request
```
{
    "type" : "drop_select_permission",
    "args" : {
        "table" : "clients",
        "role" : "user"
    }
}
```
response
```
{
    "path": "$.args",
    "error": "select permission on \"clients\" for role \"user\" does not exist",
    "code": "permission-denied"
}
```

In order to get everything work again, I have to manually delete the permission from the DB and then add it again using the API

**Comment by rakeshkky** [comment]
Hi @tafelito,

This bug has been identified earlier and fix is currently live in `master` via https://github.com/hasura/graphql-engine/pull/3211. The very next release will have the fix. I'd request you to try the PR image `hasura/graphql-engine:pull3211-b56063a7`. Please to close the issue if the bug is fixed. 

Thank you. :slightly_smiling_face:

**Comment by tafelito** [comment]
I updated the server to the PR image but now I can start the console due to this error 
`FATA[0001] version check: [cli: v1.0.0-beta.9] [server: pull3211-b56063a7] versions incompatible: for untagged builds, server and cli versions should match`

**Comment by tafelito** [comment]
@rakeshkky I wasn't able to test the PR you suggested because the error I posted above. The computed does return a SETOF table and I set the permissions for that table  but I still get an error when I try to query that field, it says it does not exist. If then I add the field through the API, it works until the server is restarted and then I get the inconsistent metadata error.

**Comment by rakeshkky** [comment]
@tafelito You've to set the select permissions on the table which the computed field is returning. Only then you could able to query the computed field. 
> If then I add the field through the API, it works until the server is restarted and then I get the inconsistent metadata error.

Please give me the error message.

**Comment by tafelito** [comment]
@rakeshkky my function returns a set of a view and IO already set the permissions for that view.

and this is the error I get every time it restarts

![image](https://user-images.githubusercontent.com/5973652/68793375-171ece80-061b-11ea-9306-33264d9f0a9f.png)

**Comment by rakeshkky** [comment]
@tafelito May I know the version of the server? If it is `<= beta.9`, it is known bug and is fixed with `beta.10` via https://github.com/hasura/graphql-engine/pull/3211/commits/6e4cc4b5d06a844feaadefe053eb38c102a59d40.

**Comment by tafelito** [comment]
I tested with both beta.8 and beta.9

I will test with beta.10 as soon as is published if it's not yet and I'll let you know

**Comment by tafelito** [comment]
@rakeshkky I just updated to beta.10 and it's working now and I didn't have to manually add the computed field through the API 

Thanks for the quick response!

**Comment by rakeshkky** [comment]
@tafelito Great to know that. Thank you :slightly_smiling_face:. Closing the issue now.
