### ISSUE TITLE
hasura container increase size ( on  disk) is very large

### ISSUE THREAD

**Issue by mshanak** [hasura/graphql-engine#3326]
hello
I am using hasur in a real-time game, after 1 week I discovered that the hasura container size is **36GB** which is very large, and I noticed an increase of about **5 GB** in one day.

my question is: 
-- what is the cause for this large disk usage? 
-- How can I reduce the size?

regards

**Comment by shahidhk** [comment]
Are you receiving a lot of traffic? The size usage can be due to the logs being written. Are the logs being managed somehow?

**Comment by shahidhk** [comment]
@lexi-lambda @0x777 We write the logs onto stdout, right? So that can't possibly affect the disk usage.

@mshanak Where is the container deployed?

**Comment by mshanak** [comment]
@shahidhk i found that the log file was very larg, so i disabled the logs for now
Is there a good way to manage logs that you recommend?

**Comment by yuvalgut** [comment]
The container log is managed by docker, if that is the case you can follow https://medium.com/@Quigley_Ja/rotating-docker-logs-keeping-your-overlay-folder-small-40cfa2155412

**Comment by ecthiender** [comment]
@mshanak could you resolve your issue?

**Comment by marionschleifer** [comment]
@mshanak I'm closing this issue. Feel free to re-open if you'd like to add something 🙂
