### ISSUE TITLE
Static value in configure a manual relationship

### ISSUE THREAD

**Issue by PedramMarandi** [hasura/graphql-engine#3329]
Hi Everyone

I have the following tables Labels and Labelables.
For my lableable table, I have the following columns `id, labelable_id, label_id, type`

The Labelanles table has a relation to other tables like products, stores and etc ... 

In this case, I tried to create a manual relationship using the Hasura console. And this is what U have done.
![Screen Shot 2019-11-11 at 5 18 15 pm](https://user-images.githubusercontent.com/7813872/68565602-26313f80-04a8-11ea-86e1-50f2e447ff5b.png)

Now I need a static value for the type column in the lableable table which is `product`. It would be so nice and useful if Hasura provides such a feature. However, I am not really sure if it is possible to implement such a feature.

Meanwhile, I'm using filters to grab the labels for products.

**Comment by rikinsk** [comment]
I believe the functionality you need is the same as described in #2298. 

Unfortunately you can't do this currently. Workarounds could be to create a view called `product_labelables` which has just the `labelables` with `type = product` and defining a relationship to it or just filtering based on `type` in your query like you are doing now

**Comment by PedramMarandi** [comment]
Yes it is similar. I'll stick to the API filters for now but thank you for you help.
