### ISSUE TITLE
expose postgres functions as queries and mutations

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#333]
This is kind of an escape hatch for some of the features that we do not support out of the box.

**Comment by revskill10** [comment]
This is a very important feature, with it we could incrementally adapt it for more stable solutions in future.

**Comment by shahidhk** [comment]
[via 5b5e3ac6f396c9d6783af009 on intercom]

**Comment by sfcgeorge** [comment]
It would be neat to use a custom function as a way of wrapping [ZomboDB]( https://github.com/zombodb/zombodb) queries — effectively letting you do ElasticSearch queries on your Postgres database over GraphQL. The tricky bit I see to get right would be access control on the function's parameters.

**Comment by coco98** [comment]
@sfcgeorge This is on the roadmap and work has just started. Should be out in a 1-2 weeks!

Like you said, access control is the tricky bit. The access control around functions is that you can "set" some parameters of the function to come in directly from the auth/session headers.

The super cool thing is that you can have relationships on the functions output type. So you can have other tables have relationships to this function and vice-versa. I can't wait for this to be out!

**Comment by deinspanjer** [comment]
The part I'm most interested in here are ways to support new WHERE clause criteria for currently unsupported or custom data types.  A good example is the ltree data type which is very powerful and useful when dealing with tree like data.  Using that, you have a new set of operators that let you compare an ltree column with an lquery.  Most of those operators look and behave similar to the JSON(B) operators.

**Comment by dsandip** [comment]
notes on console changes [here](https://docs.google.com/document/d/12A2oNNegF7O3Qv1dgdYWdMO0cM2I3DpI4VLSehwGXko)
(not mocking it up as it's pretty much the same as the UI for handling tables)

@shahidhk @rikinsk @0x777 @rakeshkky @coco98

**Comment by haasel77** [comment]
@dsandip I can see this issue being re-assigned many times between consecutive milestones. Let me kindly ask what are the chances that this and #1073 are closed soon within the [v1.0.0-alpha34](https://github.com/hasura/graphql-engine/milestone/15) so that the postgres functions support is enabled?

**Comment by dsandip** [comment]
@rakeshkky Please to include 👆 in your outline and docs content.

**Comment by phated** [comment]
It seems like the implementation in #1073 won't support mutations because the functions must be `STABLE` or `IMMUTABLE`, is this correct?
