### ISSUE TITLE
GUI forces to fill in a non-nullable field on 'Insert Row' tab even if there is BEFORE INSERT trigger

### ISSUE THREAD

**Issue by piroszhog** [hasura/graphql-engine#3332]
My BEFORE INSERT trigger will correctly fill in this field, but I can't insert a new row via GUI.
I don't think, that there is need any pre-validation before processing request to Postgre.

Version: v1.0.0-beta.9

**Comment by rikinsk** [comment]
A solution to this would be to add another radio button called "skip" which will not send the column in the insert

**Comment by NikPaushkin** [comment]
Any updates on that? It makes GUI really unusable in a part of inserting new rows. You could simple enable 'Default' option for any field and not to do one more 'Skip' option.

**Comment by lucarestagno** [comment]
The insert with BEFORE INSERT trigger correctly works in Hasura v2.32 (latest version).
Closing this issue.
