### ISSUE TITLE
Not possible to set the length of variable char columns?

### ISSUE THREAD

**Issue by mitar** [hasura/graphql-engine#3335]
I am using Hasura console to create SQL tables, but I do not see a way to set the length of the variable char data type.

**Comment by HyeokSuLee** [comment]
Hey. Anyone solve this problem?

**Comment by rikinsk** [comment]
This will be fixed soon on the console. For now you could directly use SQL via the `Data -> SQL` to do this. 
```sql
ALTER TABLE table_name
  ALTER COLUMN column_name TYPE new_data_type 
```

**Comment by mitar** [comment]
> For now you could directly use SQL

One has also add it to a migration.

**Comment by beerose** [comment]
Closed via https://github.com/hasura/graphql-engine/pull/4546
