### ISSUE TITLE
Invalid link in documentation

### ISSUE THREAD

**Issue by mitar** [hasura/graphql-engine#3337]
I am reading [here](https://github.com/hasura/graphql-engine/blob/master/remote-schemas.md). And here:

> Regular boilerplates that can be deployed anywhere.

It links to [this location](https://github.com/hasura/graphql-engine/blob/master/community/boilerplates/graphql-servers) but it does not exist anymore.

Same for [link here](https://github.com/hasura/custom-resolvers-boilerplate):

> The contents of this repo have been moved to hasura/graphql-engine. Please create all issues and pull requests there.

Points to [this location](https://github.com/hasura/graphql-engine/tree/master/community/boilerplates/custom-resolvers) which does not exist anymore either.

**Comment by devesh-verma** [comment]
@marionschleifer I would like to start contributing to hasura, starting with this.
can you tell what is the correct link to be used for the below mentioned?
> Regular boilerplates that can be deployed anywhere.

**Comment by marionschleifer** [comment]
@devesh-verma that is great 😃 

Sure, I can help you:

For [this page](https://github.com/hasura/graphql-engine/blob/master/remote-schemas.md): [this is the correct link](https://github.com/hasura/graphql-engine/tree/master/community/boilerplates) for the *Regular boilerplates* link.

For the [second page](https://github.com/hasura/custom-resolvers-boilerplate), you can also use [this link](https://github.com/hasura/graphql-engine/tree/master/community/boilerplates).
