### ISSUE TITLE
/v1/version failed - [403] using hasura console --admin-secret

### ISSUE THREAD

**Issue by coffenbacher** [hasura/graphql-engine#3343]
Steps to reproduce:

1) start graphql-engine with 

   1. `--allow-unauthenticated` option **unset** (i.e. authenticated only)
   2. `--set-env-vars HASURAL_GRAPHQL_ADMIN_SECRET=$ADMIN_SECRET`

2) try to access it using `hasura console --admin-secret $ADMIN_SECRET`

This fails when trying to access /v1/version with a 403 error:

```
FATA[0001] version check: failed to get version from server: GET https://...- [403]
```

If I --allow-unauthenticated, it works, which tells me that my admin secret is correct so that's not the issue. I think this is a bug with the headers on the version check.

**Comment by shahidhk** [comment]
@coffenbacher What is `--allow-unauthenticated`? There is no such flag on graphql-engine. Are you running this on some platform which block unauthenticated access?

**Comment by coffenbacher** [comment]
Hahaha :man_facepalming: Thanks @shahidhk . `--allow-unauthenticated` is a Cloud Run parameter, not a Hasura parameter, so the request was getting blocked before it even reached Hasura. I define them all in the same command so I got them confused.

Sorry :blush:
