### ISSUE TITLE
Allow Edit for GraphQL field names on Views

### ISSUE THREAD

**Issue by alexhafner** [hasura/graphql-engine#3346]
In v1.0.0-beta.9, the Hasura GUI Console allows providing alternative Field Names for Table fields and root fields. It would be grand if this features could also be enabled for view GraphQL fields and view root fields, as there are situations where data has to be obtained on views where Hasura has no direct DDL access, but has been provided with a view by the owners of the relevant schema. 

Being able to modify root and view fields, those views could be presented with more friendly names than those that may be used within the data model.

**Comment by flybayer** [comment]
I also need this. I'm renaming all my root fields to be camelCase. I have views that are camelCased but then the view's aggregate doesn't match: `camelCased_aggregate` instead of `camelCasedAggregate`

**Comment by rikinsk** [comment]
We'll add support for this via the console soon. In the meanwhile you can use [this](https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/table-view.html#set-table-custom-fields) metadata API to do this (the API works for views as well) .

**Comment by rikinsk** [comment]
Closing this as support for root level fields is added. Updating GraphQL field names for views is tracked in #3689
