### ISSUE TITLE
Multiple `_and` or `_or` in same query are considered duplicated.

### ISSUE THREAD

**Issue by just4fun** [hasura/graphql-engine#3348]
Hi there,

Currently I'm using `v1.0.0-beta.6`, now I have a query like

```sql
select first_name, last_name
from user 
where (a=1 or b=1) and (c=2 or d=2) and (e=3 or f=3) and z=4
```

When I wrote query for graphql, I think it should be something like

```graphql
query {
  user (
    _or: [
      { a: { _eq: 1 } }
      { b: { _eq: 1 } }
    ]
    _or: [
      { c: { _eq: 2 } }
      { d: { _eq: 2 } }
    ]
    _or: [
      { e: { _eq: 3 } }
      { f: { _eq: 3 } }
    ]
    _and: {
      z: { _eq: 4 }
    }
  )
}
```

With the query above, I will get `when parsing a value of type: 'user_bool_exp', the following fields are duplicated: _or`.

Then I found a workaround,

```graphql
query {
  user (
    _and: {
      z: { _eq: 4 }
      _and: {
        _or: [
          { a: { _eq: 1 } }
          { b: { _eq: 1 } }
        ]
        _and: {
          _or: [
            { c: { _eq: 2 } }
            { d: { _eq: 2 } }
          ]
          _and: {
             _or: [
              { e: { _eq: 3 } }
              { f: { _eq: 3 } }
            ]
          }
        }
      }
    }
  )
}
```

The workaround above works but really looks weird and not straightforward, it seems like we could not keep multiple `_and` and `_or` in same query level.

Since I could not simply upgrade hasura engine to latest version `v1.0.0-beta.9` (it was maintained by separate team while I have no access), so in addition to write custom queries, just want to know whether `v1.0.0-beta.9` enhance it, or I used the query in wrong way, or the `weird` workaround above is the correct way.

Thanks in advance.

**Comment by rikinsk** [comment]
The query you are looking for is:

```gql
query {
  authors (
    where: {
      _and: [
        {
          z: {_eq: 4}
        },
        {
          _or: [
      	    { a: { _eq: 1 } }
      	    { b: { _eq: 1 } }
    	  ]
        },
        {
          _or: [
      	    { c: { _eq: 2 } }
      	    { d: { _eq: 2 } }
    	  ]
        },
        {
          _or: [
      	    { e: { _eq: 3 } }
      	    { f: { _eq: 3 } }
    	  ]
        }
      ]
    }  
  ) {
    first_name
    last_name
  }
}

```

**Comment by just4fun** [comment]
@rikinsk - The syntax makes sense, so I missed two things.

- `_and` also supports array
- Each condition logic should be put into separate `{}` to avoid duplicate `_and` and `_or`

Thanks for your kindly help.
