### ISSUE TITLE
Allow creation of SQL View right from UI (not via SQL script)

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#335]
SQL View is nesessary in Hasura for powerful queries. 
We need a way to declaratively create sql views through UI, like we do with SQL Tables.
Some features:
- Allow choosing aggregation functions from chosen list.
- Allow specify joining multiple tables with aliasing fields from those tables.

This feature requires huge amount of frontend work, but it's a powerful feature to have.

**Comment by Maxpain177** [comment]
+1

**Comment by jasonmccallister** [comment]
Was just looking to make this request but found this issue! It would be great for those of us that are less SQL inclined. 

Also, it would be really useful to "preview" this view (showing the results in the UI) before committing the view.

Additionally, it might be helpful to expose creating a view when using the query functionality in the data tab? So users can use the data tab to select their "view" and then click a button to automatically create the review.

**Comment by rikinsk** [comment]
We should facilitate generating views for standard tasks like
- exposing subset of columns
- data aggregations
- joining tables
- using group_by

**Comment by manasag** [comment]
Thanks everyone for your comments and patience on this issue. We plan to provide a more mature database management experience in Hasura V3.
We would be closing this issue in favor of a much better experience in Hasura V3 (See this new [issue](https://github.com/hasura/graphql-engine/issues/10076))
