### ISSUE TITLE
allow renaming or deleting roles globally in console

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#3353]
In the console, `Schema permissions summary` page, i'm allowed to create new roles by cloning permission data from an existing role. I would like a way to delete the old role once i have cloned it to a new one. Or even better if i'm allowed to rename an existing role.

Right now the only way to delete a role completely is to manually go to every table's permission page and remove them one by one.

**Comment by ekifox** [comment]
up

**Comment by darrenbutcher** [comment]
Any updates on this? Would be really helpful to have this kind of functionality.

**Comment by WGTW** [comment]
Deleting roles was added in this issue which is great, but renaming was not yet achieved. Can we see the role renaming feature being implemented?
