### ISSUE TITLE
It is support set the value like "nextval('xxx_seq')"?

### ISSUE THREAD

**Issue by chinapenser** [hasura/graphql-engine#3357]
for example, a table had two fields A and B，I'd like to set B=nextval('a1_seq') when A=a1, and set B=nextval('a2_seq') when A=a2.
Thanks !

**Comment by chinapenser** [comment]
otherwise, it's a partition table.

**Comment by ecthiender** [comment]
If you know how to do it in Postgres, you can do it in Hasura via the "SQL" window in "Data" tab.

**Comment by chinapenser** [comment]
https://docs.hasura.io/1.0/graphql/manual/queries/custom-functions.html
The document said "Function behaviour: ONLY STABLE or IMMUTABLE", is it means I can not insert/update with the "SQL"? @ecthiender

**Comment by marionschleifer** [comment]
@chinapenser We only support `STABLE` and `IMMUTABLE` functions which means the function cannot modify (mutate) any data. Only reading is possible. Also, we only support functions for queries, hence we don't support any function that can mutate.

**Comment by rikinsk** [comment]
As Marion mentioned we don't support such a functioanlity at the GraphQL layer. You can use Postgres directly to achieve this. See https://docs.hasura.io/1.0/graphql/manual/schema/default-values/sql-functions.html for a guide on how to do this

**Comment by akhil-naidu** [comment]
New Documentation Link: https://hasura.io/docs/latest/schema/postgres/default-values/sql-functions
