### ISSUE TITLE
Append Mutation Returning JSONB as String

### ISSUE THREAD

**Issue by jcmoore0** [hasura/graphql-engine#3365]
I am finding an issue in v1.0.0-beta.10
Problem: Update mutation returns a jsonb field as string type.
The Json data is inserted into the database successfully.
Other (non json) fields in the reponse are ok.
The json field in the reponse is a proper string representation of the json and can be successfully parsed into an object with JSON.parse()

```
mutation update_something($id: Int!, $value: jsonb!) {
  update_something(where: { id: { _eq: $id } }, _append: { something_jsonb: $value }) {
    affected_rows
    returning {
      ...fields
    }
  }
}

response:
{"data":{"update_something":{"affected_rows" : 1, "returning" : [{"id":2,"something_jsonb":"{\"key1\": [{\"type\": \"id\", \"field\": \"id\", \"headerName\": \"ID\",   ...
```

**Comment by rakeshkky** [comment]
@jcmoore0, Thanks for reporting.
Please test the preview app in https://github.com/hasura/graphql-engine/pull/3375.

**Comment by jcmoore0** [comment]
Hi @rakeshkky- Thanks for the quick response.
I tried this one:  
Docker image for server: hasura/graphql-engine:pull3375-e8fa447e
The issue is still present in this image.
Is this the right image where the fix is?

**Comment by rakeshkky** [comment]
Hi @jcmoore0, Apologies. I didn't push my complete work. I force pushed the PR commit. Please check the preview app.
