### ISSUE TITLE
Add Postgres schema operations to console UI (create, delete, duplicate etc...)

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#337]
Schema is a powerful feature of PostgreSQL , which supports many use cases where we need better isolation stories.
For example, in a multi-tenant application, we might need isolated schema for each tenant. It will allow us to easily import, export, clone, destroy, edit a specific schema whenever we want.
Feature i'd love to have:
- Allow cloning schema, which included everything the cloned schema currently has.
- Allow export, import and destroy specific schema right from UI.

**Comment by manasag** [comment]
Thanks for your patience on this issue. We plan to provide a more mature database management experience in Hasura V3.
We would be closing this issue in favor of a much better experience in Hasura V3 (See this new https://github.com/hasura/graphql-engine/issues/10076)
