### ISSUE TITLE
Order of multiple mutations in a request might be unspecified

### ISSUE THREAD

**Issue by mitar** [hasura/graphql-engine#3373]
The example [here](https://docs.hasura.io/1.0/graphql/manual/mutations/multiple-mutations.html#run-multiple-top-level-mutations-transactionally) has:

```
mutation reset_author {
  delete_article (
    where: {author_id: {_eq: 6}}
  ) {
    affected_rows
  }
  update_author (
    where: {id: {_eq: 6}}
    _set: {name: "Cory"}
  ) {
    returning {
      id
      name
      articles {
        id
        title
      }
    }
  }
}
```

But JSON generally does not have an order specified for keys of an object. So this means that it can happen that the order of `delete_article` and `update_author` is swapped. This can then lead to strange behavior.

**Comment by lexi-lambda** [comment]
> But JSON generally does not have an order specified for keys of an object.

That is true. However, GraphQL queries are not JSON! Their *results* are encoded as JSON, but the queries themselves have a well-defined order. In fact, [the GraphQL spec](https://graphql.github.io/graphql-spec/draft/#sec-Mutation) specifies this behavior:

> If the operation is a mutation, the result of the operation is the result of executing the mutation’s top level selection set on the mutation root object type. This selection set should be executed serially.

Therefore, there’s not actually any possibility for nondeterminism here—`delete_article` will always be executed before `update_author`.
