### ISSUE TITLE
Need example for `hasura console --static-dir <path>`

### ISSUE THREAD

**Issue by tibotiber** [hasura/graphql-engine#3379]
Hi,

In #521, @shahidhk [commented](https://github.com/hasura/graphql-engine/issues/521#issuecomment-471462897) that we could get the CLI console to serve static files while offline by running `hasura console --static-dir <path>`. I've been trying to use that but can't figure out a correct `path` value.

Is this approach still valid? Would you mind providing an example path?

Thanks!

**Comment by rikinsk** [comment]
this might help https://docs.hasura.io/1.0/graphql/manual/deployment/graphql-engine-flags/config-examples.html#load-console-assets-from-server-instead-of-cdn

**Comment by tibotiber** [comment]
Thanks @rikinsk. 

So I had seen this and my setup is based on it. I have the following in my hasura engine config
```yaml
- name: HASURA_GRAPHQL_CONSOLE_ASSETS_DIR
  value: /srv/console-assets
```
and I open the console with
```
hasura console --static-dir "/console/assets"
```
What am I getting wrong?

**Comment by shahidhk** [comment]
@tibotiber `--static-dir` for the Hasura CLI refers to a local directory where console assets are present. You can get these assets by cloning the graphql engine repo and building the console yourself.

```
cd ~
git clone https://github.com/hasura/graphql-engine
cd graphql-engine/console
npm ci
make server-build
```

Now go to your Hasura project and execute the console command:
```
cd hasura-project
hasura console --static-dir ~/graphql-engine/console/static/dist

```

Here is a zip file in case you don't want to build them: [dist.zip](https://github.com/hasura/graphql-engine/files/3867496/dist.zip)

Unzip them and use it as the `dist` directory.

**Comment by rikinsk** [comment]
I would like to add a note that I would have expected the CLI console to also use the local assets from the docker image like the server console does. Tracking this via #3382

**Comment by tibotiber** [comment]
Thanks @shahidhk, the dist archive is empty but i've cloned and built and it works. 

I'll support @rikinsk's issue as this is extra setup that could be improved and to avoid having the engine / cli / local assets end up at different versions and causing hard to debug issues. Really cool that I can work offline already though :)
