### ISSUE TITLE
create pgcrypto extension by default for uuid support

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#338]
Right now, when a UUID column is created from console, console executes `CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;`

But if the user try to create a table with UUID column from run SQL or psql, as shown in [this blog](https://blog.hasura.io/graphql-and-uuid-type-on-postgres-767f016479e9) it will fail.

We should create the pgcrypto extension on graphql engine init step.

**Comment by tirumaraiselvan** [comment]
I am actually installing pgcrypto for event engine in init step : https://github.com/tirumaraiselvan/graphql-engine/blob/4e8a1617f3956439bd33fe0aa5245bf282732497/server/src-rsr/initialise.sql#L205

**Comment by revskill10** [comment]
@shahidhk  @tirumaraiselvan How about passing array of extensions as argument when running graphql-engine ?

**Comment by shahidhk** [comment]
Added in https://github.com/hasura/graphql-engine/commit/82e09efce68f7b771338079564db1edc7919f9c7

**Comment by shahidhk** [comment]
Thanks for reporting this @jasonmorganson. We're working on a fix.

**Comment by 0x777** [comment]
We should check if the extension is already loaded, if it is not, try to create it and if it fails, we exit by saying that `pgcrypto` extension has to be loaded for graphql-engine to work.

**Comment by shahidhk** [comment]
@jasonmorganson If you haven't already done so, you can fix this issue by executing the following statement as a superuser:

```sql
CREATE EXTENSION IF NOT EXISTS pgcrypto;
```
