### ISSUE TITLE
persist columns order / collapsed status in console browse rows section

### ISSUE THREAD

**Issue by vonwao** [hasura/graphql-engine#3390]
It would be nice to order columns in some persistent way so that important data can be always seen without horizontal scrolling in data table.  

AND/OR saving collapsed columns in data table across page refreshes.

**Comment by pnappa** [comment]
I would also like to see columns in the drop downs when defining permissions to be consistent too (preferably alphabetic ordering!). :)

**Comment by praveenweb** [comment]
Duplicate of #1622

**Comment by rikinsk** [comment]
Just adding a note to avoid confusions. The scope of issue seems to be to add a feature where the status of columns order/collapsed is persisted on the UI in the Browse rows screen.

#1622 is looking to update the order of columns in the postgres database via the UI

**Comment by vonwao** [comment]
I suppose something similar could be achieved by creating a view from a table, then I assume you can specify the order of columns in the results.  But, it's kind of a pain and you end up with extra stuff in your DB.

**Comment by MarcelloTheArcane** [comment]
It would be nice to add column sorting and filters in this too
