### ISSUE TITLE
immutability of images published

### ISSUE THREAD

**Issue by uniyalaa** [hasura/graphql-engine#3392]
Hello,

Could you please confirm that if a patched version of the image is released, e.g. for an OS patch or a software patch, is it re-released with the same tag (effectively over the top of the previous tag) or is it always given a new tag (e.g. traditional semantic versioning)?

We want to ensure that we have an immutable copy of every image we import.

Thanks,
Aastha

**Comment by shahidhk** [comment]
We will not make updates to the released images. We'll follow semantic versioning and a new tag will be issued for all patches.

**Comment by shahidhk** [comment]
@uniyalaa Closing the issue as the question is answered. Feel free to re-open if you have any follow-ups.

**Comment by uniyalaa** [comment]
@shahidhk - Many thanks. This helps progress things on our side to get using it.
