### ISSUE TITLE
Running hasura as a dependency service in an gitlab CI job

### ISSUE THREAD

**Issue by matejbasic** [hasura/graphql-engine#3395]
Hi,

does somebody have example of running hasura graphql engine as a service in some job?
Concretely, I want to run two services, psql DB and graphql engine (CLI migrations image)  as services for one pytest job. Problem is that I'm not able to set psql DB as a dependecy for graphql engine.

Thank you,
Matej

**Comment by matejbasic** [comment]
Just fyi, as I only need to apply migrations to DB so I can make sql queries in tests against it, I have wrote a script to do it before running a test job. So, you can close this issue as it's resolved for me.

**Comment by shahidhk** [comment]
@matejbasic The script could also make use of hasura CLI to apply migrations. :) Let me know if you have other questions around this. Closing the issue as you suggested.
