### ISSUE TITLE
Access hasura console remotely

### ISSUE THREAD

**Issue by divramod** [hasura/graphql-engine#3396]
Hey, 

i have hasura running on a remote server for development.
i can successfully access hasura via my.ip:9080 and the console with http://my.ip:9080/console

now i stumbled over the awesome hasura migrations feature and followed the guide here: https://docs.hasura.io/1.0/graphql/manual/migrations/existing-database.html

I reached step 4 successfully, but have a problem from there: 
![image](https://user-images.githubusercontent.com/1331662/69360025-14128680-0c8a-11ea-9beb-efa08ab85733.png)

This breaks, because its remote (i am connecting via ssh), and i do not have a browser installed. Am i right?
When i now try to open my.ip:9695 i get an ```ERR_CONNECTION_REFUSED``` error.

Can anyone help me out here?

I need to know, how i can reach the server which is running on my remote machine (http://localhost:9695) via my local web browser.

Or is it somehow possible to tell xdg-open on the remote machine to open the browser on my local machine?

Is the command which starts the server and xdg-open sending some credentials with it, so that maybe this is the reason, that i cannot access the console ui via my ip+port?

thx in advance for any hint in the right direction and thx again for the awesome project!

**Comment by shahidhk** [comment]
@divramod You should execute `hasura console` from your development machine or the client machine. It will contact Hasura using `my.ip:9080`. You should not execute `hasura console` on the same server as Hasura GraphQL Engine is running.

**Comment by divramod** [comment]
hmm, ok. i thought, i could somehow avoid that. 
i am developing remote only. 
so to have the migrations directory tracked by my git rep i now need to clone it to my local machine too.

is there a reason i should avoid to run hasura console on the same machine as the graphql engine?

**Comment by rikinsk** [comment]
There is no real reason to avoid running the console for migrations on the same machine as the graphql engine. The only caveat being that the location where the migrations are being generated should be persistent for obvious reasons.

Will use this issue to track this as a feature request.

**Comment by shahidhk** [comment]
Tracked in https://github.com/hasura/graphql-engine/issues/2824

Closing this as duplicate
