### ISSUE TITLE
TypeError: "t[n] is undefined"

### ISSUE THREAD

**Issue by zolamk** [hasura/graphql-engine#3397]
hasura beta.10 displays the following error when removing id field

`n/<@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/main.js.gz:1:1711267
n@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/main.js.gz:1:1710230
n@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/main.js.gz:1:1711458
pa@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:2629509
Va@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:2636387
Ya@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:2642737
fs@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:2665233
ds@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:2665621
Zs@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:2672797
Ys@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:2672167
Ws@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:2671172
bs@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:2669974
enqueueSetState@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:2620954
k.prototype.setState@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:2568014
e@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:81140
r@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:76106
e@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:76588
e@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:81045
g@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:443278
R/</<@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/main.js.gz:1:4117195
a/</</<@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:2709200
n/</</<@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:2331179
e@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:447915
n/</<@https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/main.js.gz:1:43847
`

**Comment by rikinsk** [comment]
@zolamk Can you describe in more detail what exactly you were trying to do. a sample schema and directions to replicate the issue will help

**Comment by marionschleifer** [comment]
@zolamk I'm closing this issue. If you would like to provide more information, please feel free to re-open 🙂
