### ISSUE TITLE
Trying to squash all migrations into one migration hungs

### ISSUE THREAD

**Issue by mitar** [hasura/graphql-engine#3401]
I want to squash all migrations into one migration. I run:

```
$ hasura migrate squash --delete-source --from 1573758077021
```

Where `1573758077021` is timestamp of the first migration. And it just runs and hangs at:

```
WARN This command is currently experimental and hence in preview, correctness of squashed migration is not guaranteed! 
Squashing migrations from 1573758077021 to latest...◓ 
```

And rotates but does not do anything. Does `hasura console` has to be running?

**Comment by shahidhk** [comment]
@mitar There are some known issues with `squash` command that we are working on. Is it possible for you to share your migrations so that we can run some tests locally? You can either emaik it to me at shahidh@hasura.io or DM me on https://hasura.io/discord at `shahidhk#0931`.

**Comment by mitar** [comment]
I just sent them to your e-mail.

**Comment by shahidhk** [comment]
Will check and get back.

**Comment by eziante** [comment]
We are having the same issue if one of the migrations contains a relationship rename.

**Comment by danharsanyi** [comment]
@shahidhk I'm getting the same issue. Would you like more example migrations emailed to you?

**Comment by shahidhk** [comment]
https://github.com/hasura/graphql-engine/pull/3569 should fix this.
