### ISSUE TITLE
Flag a table as a many to many (m2m) bridge/junction/join table to allow automatic flattening

### ISSUE THREAD

**Issue by wc-matteo** [hasura/graphql-engine#3404]
I read the [docs](https://docs.hasura.io/1.0/graphql/manual/schema/relationships/database-modelling/many-to-many.html#flattening-a-many-to-many-relationship-query) about manually creating views to flatten m2m relationships. But that's cumbersome and discouraged.

What about a way to flag a table as bridge/junction/join table? Then the graphql engine could flatten the result automatically.

**Comment by tirumaraiselvan** [comment]
Related (almost dupe): https://github.com/hasura/graphql-engine/issues/360

**Comment by manasag** [comment]
Closing in favor of #360
