### ISSUE TITLE
how to get all query_root ?

### ISSUE THREAD

**Issue by timeshift92** [hasura/graphql-engine#3409]
hello i have write admin template with crud and i need to get all queries in hasura.

**Comment by Albert-Gao** [comment]
You just use the apollo command:
**If you want a JSON output:**
`apollo client:download-schema ./src/graphql-schema.json`

**If you want a GraphQL schema output:**
`apollo client:download-schema ./src/graphql-schema.graphql`

You need to setup your apollo CLI with your hasura admin key

**Comment by timeshift92** [comment]
thanks =)

**Comment by tirumaraiselvan** [comment]
You can also use graphqurl : https://github.com/hasura/graphqurl#export-schema
