### ISSUE TITLE
v1 beta 9 after running for ~10 days, won't returning anything for a particular subscription.

### ISSUE THREAD

**Issue by c19** [hasura/graphql-engine#3411]
I have 4 subscription. 
all 4 are working fine yesterday.
today I found that the 4th one won't return anything, no matter how. all code checkouted as it is yesterday.
hasura logs show that I mistakenly send a "1" as id arg instead of int 1. Also I mistakenly send  the 4th subscription twice.
Don't know if that has something to do with it.
no errors ever shown. It just didn't respond, but hasura logs shows that it did received the request.

Restart hasura and it's working again.

**Comment by 0x777** [comment]
@c19 Can you give us a minimal reproduction (or your schema + query if that's an option)?

**Comment by lexi-lambda** [comment]
I am going to close this issue, as I don’t think it’s currently possible for us to reproduce it with the information provided. If you think it’s still an issue, and you can provide a little more information, feel free to reopen it.
