### ISSUE TITLE
User impersonation when x-hasura-admin-secret is present

### ISSUE THREAD

**Issue by bkniffler** [hasura/graphql-engine#3417]
Hey, 
I'd like to know if it is possible to set x-hasura-user-id without embedding it in an accessToken if the x-hasura-admin-secret is present, effectively bypassing the Authorization header. The use case is a server that, on behalf of the user and with the admin-secret, would access the database and the data would be filtered in a way as if the it was the actual user accessing it, respecting the authorization rules.

So what I'd love to know is if something like this works or could be made possible:
```json
{
  "headers": { "x-hasura-admin-secret": "secretPassword", "x-hasura-user-id": "user:12" }
}
```

**Comment by ecthiender** [comment]
Yes, this works. Because you are the admin, you can impersonate other users. You also need to include the non-admin role in the headers

```json
{
  "headers": { 
    "x-hasura-admin-secret": "secretPassword", 
    "x-hasura-role": "user",
    "x-hasura-user-id": "user:12" 
  }
}
```

**Comment by bkniffler** [comment]
Ah, so cool, cheers! I forgot to add the `x-hasura-role` header. Thanks a ton for the quick help!

**Comment by AThilenius** [comment]
Follow up question: can the same be done with JWTs, assuming `admin` is in the allowed roles? This doesn't seem to work from my testing, but would be very useful for API-level user impersonation.

Basically the header `x-hasura-user-id` and `x-hasura-role` can override the JWT claim as long as `admin` is in the `x-hasura-allowed-roles`.
