### ISSUE TITLE
when user has more than one roles , what should be response in the webhook?

### ISSUE THREAD

**Issue by susen4517x** [hasura/graphql-engine#3418]
when user has more than one roles , what should be response in the webhook?

**Comment by ecthiender** [comment]
The webhook doesn't support passing multiple roles. As the webhook is called per request, it can resolve what the user's current role would be for that request.

If you are looking for multiple roles in a single request, Hasura doesn't support them yet. There is #877 open to add support for it.

**Comment by susen4517x** [comment]
@ecthiender thanks

**Comment by marionschleifer** [comment]
Closing this issue. @susen4517x feel free to re-open if you would like to add anything 🙂
