### ISSUE TITLE
Primary key changing on Upsert

### ISSUE THREAD

**Issue by GollyJer** [hasura/graphql-engine#342]
Hi. I've discussed this in discord with `tanmaig` aka @coco98.

I have the following table structure.
![2018-08-31_14h03_41](https://user-images.githubusercontent.com/689204/44931350-f1afe880-ad26-11e8-9485-08a209272a4d.png)

A tweet can contain many symbols and a symbol can be in many tweets. Classic many to many relationship.

The problem. If I try to `upsert` anything to an existing row in the `symbol` table graphql wants to change the primary key which will break the relationship to tweets.

```javascript
  mutation upsert_symbol {
    insert_symbol(
      objects: [{ symbol: "INTC", is_stock: true, is_crypto: false }]
      on_conflict: { constraint: symbol_symbol_key, action: update }
    ) {
    returning {
      id
      symbol
    }
      affected_rows
    }
  }
```

In this case, if `INTC` already exists and `is_crypto` is being changed then the row is deleted and recreated with a new primary key. 😳

The same thing happens **even if `[{ symbol: "INTC", is_stock: true, is_crypto: false }]` already have the same values**.

@coco98 and @0x777 have discussed and plan on releasing a fix shortly.  
![2018-08-31_14h14_10](https://user-images.githubusercontent.com/689204/44931683-2cfee700-ad28-11e8-84c1-689415d6ac74.png)
![2018-08-31_14h17_44](https://user-images.githubusercontent.com/689204/44931881-c6c69400-ad28-11e8-89d8-9c711c05446d.png)

They asked me to make this issue so they have something to attach to the PR.

Thanks!
Jeremy

**Comment by coco98** [comment]
@rakeshkky @0x777 Please take note.

**Comment by 0x777** [comment]
@GollyJer The proposed syntax is as follows:

```graphql
  mutation upsert_symbol {
    insert_symbol(
      objects: [{ symbol: "INTC", is_stock: true, is_crypto: false }]
      on_conflict: { constraint: symbol_symbol_key, update_columns: [symbol] }
    ) {
    returning {
      id
      symbol
    }
      affected_rows
    }
  }
```
Will this work for you? 

@rakeshkky we will still need to maintain backwards compatibility by supporting the `action` argument.

**Comment by GollyJer** [comment]
Hi @0x777. Sorry for the delayed response. I was offline yesterday.

Will the `update_columns` parameter need to specify every possible column change? 
i.e. - if all three in the example could be different would it need to look like this?
```graphql
  mutation upsert_symbol {
    insert_symbol(
      objects: [{ symbol: "INTC", is_stock: true, is_crypto: false }]
      on_conflict: { constraint: symbol_symbol_key, update_columns: [symbol, is_stock, is_crypto] }
    )
  }
```
Could there be a way to say "any with a different value"?
Maybe like 
```graphql
  mutation upsert_symbol {
    insert_symbol(
      objects: [{ symbol: "INTC", is_stock: true, is_crypto: false }]
      on_conflict: { constraint: symbol_symbol_key, update_columns: [*] }
    )
  }
```

**Comment by 0x777** [comment]
@GollyJer 
When you don't explicitly specify `update_columns`, the columns that are given in `objects` are updated (it doesn't matter if they are different, you should see the same end result). 

```graphql
  mutation upsert_symbol {
    insert_symbol(
      objects: [{ symbol: "INTC", is_stock: true, is_crypto: false }]
      on_conflict: { constraint: symbol_symbol_key }
    )
  }
```
A small **caveat**: you'll need to ensure that all objects have the same set of columns. If not, the union of  column sets across all objects is the set of columns that is updated. For example, if your query is as follows: 

```graphql
  mutation upsert_symbol {
    insert_symbol(
      objects: [
        { symbol: "INTC", is_stock: true, is_crypto: false },
        { symbol: "GOOG", is_stock: true }
      ]
      on_conflict: { constraint: symbol_symbol_key }
    )
  }
```

The column `"is_crypto"` for the `"GOOG"` row is set to its `DEFAULT` value because the union of all columns across objects is `{symbol,is_stock,is_crypto}`. However you can explicitly control the columns that are updated on conflict by using `"update_columns"`. 

```graphql
  mutation upsert_symbol {
    insert_symbol(
      objects: [
        { symbol: "INTC", is_stock: true, is_crypto: false },
        { symbol: "GOOG", is_stock: true }
      ]
      on_conflict: { constraint: symbol_symbol_key update_columns: [is_stock]}
    )
  }
```

This will only update `is_stock` column if a row with the same `symbol` already exists.

**Comment by GollyJer** [comment]
I love it.  This is great.  Thank you!

Let me know when you want me to test.

**Comment by 0x777** [comment]
@GollyJer This feature is already out in the latest release. https://github.com/hasura/graphql-engine/releases/tag/v1.0.0-alpha16
