### ISSUE TITLE
Regression in connect to Postgres instances after beta.6

### ISSUE THREAD

**Issue by ziahamza** [hasura/graphql-engine#3420]
We have deployed Hasura on top of a GCP backed Cloud SQP Postgres instances for > 6 months. But we are unable to upgrade above beta 6 release. 

After that, the connection always times out:

```
hasura_1  | {"timestamp":"2019-11-25T18:24:23.763+0000","level":"warn","type":"pg-client","detail":{"message":"postgres connection failed, retrying(0)."}}
hasura_1  | {"timestamp":"2019-11-25T18:24:23.763+0000","level":"warn","type":"pg-client","detail":{"message":"postgres connection failed, retrying(0)."}}
hasura_1  | {"timestamp":"2019-11-25T18:24:23.763+0000","level":"warn","type":"pg-client","detail":{"message":"postgres connection failed, retrying(1)."}}
hasura_1  | {"timestamp":"2019-11-25T18:24:23.763+0000","level":"error","type":"schema-sync-thread","detail":{"thread_type":"listener","info":{"error":{"type":"query_error","info":{"internal":"could not connect to server: Connection refused\n\tIs the server running on host \"x.y.z\" and accepting\n\tTCP/IP connections on port 5432?\n","path":"$","error":"connection error","code":"postgres-error"}}}}}
hasura_1  | {"timestamp":"2019-11-25T18:24:23.763+0000","level":"warn","type":"schema-sync-thread","detail":{"thread_type":"listener","info":"error occurred, retrying postgres listen after 1 second"}}
hasura_1  | {"timestamp":"2019-11-25T18:24:25.613+0000","level":"warn","type":"pg-client","detail":{"message":"postgres connection failed, retrying(0)."}}
hasura_1  | {"timestamp":"2019-11-25T18:24:25.613+0000","level":"warn","type":"pg-client","detail":{"message":"postgres connection failed, retrying(0)."}}
```

We initially thought perhaps updated hasura only worked with SSL, so tried with our DATABASE_URL to contain `?sslmode=disable` but no avail. 

The whole setup works fine on `hasura/graphql-engine:v1.0.0-beta.6` but breaks with any version above that. Whats the best way to nail down this regression even further?

We currently do not have SSL enabled for our DB.

**Comment by shahidhk** [comment]
Are there any interesting logs on the Postgres side?

**Comment by ziahamza** [comment]
After the v1 release we wanted to try this again. After debugging more, I think the issue is not necessarily tied to connection but the upgrade itself. 

Hasura logs consistently dont print anything after mentioning the first retry:

```
{"type":"startup","timestamp":"2019-12-21T00:55:20.690+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":"/srv/console-assets","admin_secret_set":true,"port":3131}}}
{"type":"startup","timestamp":"2019-12-21T00:55:20.690+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://hasura:...@35.233.137.248:5432/engine"}}}
```

The small snapshot of postgres logs themselves are attached in the following file csv file:

[cloudsql_database_database_id_murcul-205921%3Amurcul-engine-clone-hasura__logs__2019-12-21T05-58.txt](https://github.com/hasura/graphql-engine/files/3990862/cloudsql_database_database_id_murcul-205921.3Amurcul-engine-clone-hasura__logs__2019-12-21T05-58.txt)

**Comment by shahidhk** [comment]
@rakeshkky Can you take a look at this? 

@ziahamza How long does it stay like this? Is the database and Hasura on the same region?

**Comment by ziahamza** [comment]
Actually waiting solved the issue. It took 35 mins (our CI step was timing out so had to run from a local machine). All migrated!

I think some sort of progress while this migration is happening would be needed (especially as most CI steps would continue to run and not time out if stdout is changing)
