### ISSUE TITLE
docs: add guide on locally developing applications with hasura

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#3427]
Things to be covered in this doc:

1. Running hasura locally using docker-compose
2. Creating and running migrations (and rollback)
3. Source code organization
4. Adding actions, remote-schemas, event-triggers etc

**Comment by marionschleifer** [comment]
We have this guide: https://hasura.io/docs/latest/getting-started/docker-simple/. And another guide on managing development environments (including managing source code) is on the way.
