### ISSUE TITLE
#2508 did this bug fixed

### ISSUE THREAD

**Issue by susen4517x** [hasura/graphql-engine#3429]
{
	"timestamp": "2019-11-27T06:26:12.247+0000",
	"level": "error",
	"type": "http-log",
	"detail": {
		"operation": {
			"query_execution_time": null,
			"user_vars": {
				"x-hasura-role": "creative_designer",
				"x-hasura-custom": "zhangwuji",
				"x-hasura-is-owner": "false",
				"x-hasura-user-id": "1"
			},
			"error": {
				"internal": {
					"statement": "WITH \"ad_item__mutation_result\" AS (INSERT INTO \"hdb_views\".\"creative_designer__insert__public__ad_item\" ( \"status\", \"json\", \"name\", \"designer_id\", \"file_uri\", \"id\", \"description\" ) VALUES (DEFAULT, DEFAULT, $1, ((current_setting('hasura.user')::json->>'x-hasura-user-id'))::integer, $2, DEFAULT, $3)  RETURNING * ) SELECT  json_build_object('affected_rows', (SELECT  COUNT(*)  FROM \"ad_item__mutation_result\"      ), 'returning_columns', (SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_1_e\"  FROM  (SELECT  \"_0_root.base\".\"status\" AS \"status\", \"_0_root.base\".\"json\" AS \"json\", \"_0_root.base\".\"name\" AS \"name\", \"_0_root.base\".\"designer_id\" AS \"designer_id\", \"_0_root.base\".\"file_uri\" AS \"file_uri\", \"_0_root.base\".\"id\" AS \"id\", \"_0_root.base\".\"description\" AS \"description\"       ) AS \"_1_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"ad_item__mutation_result\" WHERE ('true')     ) AS \"_0_root.base\"      ) AS \"_2_root\"      ) )        ",
					"prepared": true,
					"error": {
						"exec_status": "FatalError",
						"hint": "Use OVERRIDING SYSTEM VALUE to override.",
						"message": "cannot insert into column \"id\"",
						"status_code": "428C9",
						"description": "Column \"id\" is an identity column defined as GENERATED ALWAYS."
					},
					"arguments": ["(Oid 25,Just (\"456235\",Binary))", "(Oid 25,Nothing)", "(Oid 25,Just (\"345235\",Binary))"]
				},
				"path": "$.selectionSet.insert_ad_item.args.objects[0]",
				"error": "postgres query error",
				"code": "unexpected"
			},
			"request_id": "f5f977b9-3863-45d4-bcbc-15503cfd5f03",
			"response_size": 1551,
			"query": {
				"variables": {
					"ad_item_tags": [{
						"weight": 1,
						"tag_id": 14
					}],
					"name": "456235",
					"description": "345235"
				},
				"operationName": "insert_item",
				"query": "mutation insert_item($name: String!, $file_uri: String, $description: String, $ad_item_tags: [ad_item_tag_insert_input!]!) {\n  __typename\n  insert_ad_item(objects: {name: $name, file_uri: $file_uri, description: $description, ad_item_tags: {data: $ad_item_tags}}) {\n    returning {\n      id\n      __typename\n    }\n    affected_rows\n    __typename\n  }\n}\n"
			}
		},
		"http_info": {
			"status": 200,
			"http_version": "HTTP/1.1",
			"url": "/v1/graphql",
			"ip": "171.217.104.54",
			"method": "POST"
		}
	}
}

**Comment by rikinsk** [comment]
Tracked at #2508. Closing this is a duplicate.
