### ISSUE TITLE
nested object mutation for inserting related objects

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#343]
Via @GollyJer 

Given this schema:
![](https://cdn.discordapp.com/attachments/428469959530643466/485169564276228115/2018-08-31_14h03_41.png)

What's the perfect GraphQL query for:
- Insert to tweet
- Upsert to symbol
- Create relationship

All IDs are auto-incrementing integers.

@rakeshkky @0x777

**Comment by GollyJer** [comment]
@coco98 asked me to expand on our use case more if possible.  

We store a tweet and analyze the text, breaking it into:
 - a list of one or more symbols.
 - a list of one or more urls.

For each `url_starting` we scrape the page text and store it. This way, if 10,000 tweets contain the same url we aren't scraping the same page again.

The table structure looks like this.
![image](https://user-images.githubusercontent.com/689204/44937350-722e1380-ad3e-11e8-8ca7-2371169e4bfd.png)

As you can see we have a lot of "if it already exists, create a relationship, else insert then create the relationship" happening. 

I'm hoping to find some beautiful hasura graphql functionality to help. 🙂

**Comment by dsandip** [comment]
Notify lukeyb#6105 (Discord) on release
