### ISSUE TITLE
Automatically add column permission when creating a new column in console

### ISSUE THREAD

**Issue by Motoxpro** [hasura/graphql-engine#3430]
First of all, thank you for the amazing tool, docs, and support! Truly great idea and execution.

If you have a table with a role that has "All Columns" permissions and then you add a new column to that table. That role then doesn't have permission to view that column.

I just spent some time debugging a problem only to realize what had happened.

At first glance, if I have "All Columns" selected, it seems like it should automatically add any newly created columns to that role's permission.

I can see the case for wanting to be explicit, so maybe a "(Newly created columns will need to be added)" or something of the sort near the "Toggle All" button?

Thanks again!

**Comment by rikinsk** [comment]
This is a valid expectation. This feature request is being tracked at #2104. Closing this as a dup and tracking this there.
