### ISSUE TITLE
Permission metadata name cropped after 63 characters

### ISSUE THREAD

**Issue by pnappa** [hasura/graphql-engine#3444]
Hi,

I'm currently writing custom migrations, and am generating permissions combinatorially to populate Hasura as manually doing them would take too long. 

A problem I hit is this error:
```
FATA[0006] apply failed: [unexpected] postgres query error ($.args[184].args)
File: '1575004447175_generate_permissions/up.yaml'
{
    "permission": {
        "check": {},
        "columns": "*"
    },
    "role": "supermanadmin.researcheradmin.user.useradmin",
    "table": {
        "name": "QuestionnaireQuestionOnQuestionnaireSubscale",
        "schema": "public"
    }
}
[42P07] FatalError: relation "supermanadmin.researcheradmin.user.useradmin__insert__public__Q" already exists 
```

This appears to fail because it sees that another permission exists (although it's a different table - I have many tables starting with Q, it just happens to crop off at the same position). 

I have a work-around which is, don't make the names of the tables and/or permissions that long, but it would be nice not to hit this in the future.

Cheers,
Patrick

**Comment by rakeshkky** [comment]
Hi @pnappa,

The server defines a view `<role>__insert__<schema>__<table>` with a custom insert trigger for insert permissions. Any insert mutations by the user with the `role` is made into the view.

It is [Postgres limitation](https://til.hashrocket.com/posts/8f87c65a0a-postgresqls-max-identifier-length-is-63-bytes) where all _identifiers_ length is capped to 63 characters.
