### ISSUE TITLE
Problem with postGresQL trigger.

### ISSUE THREAD

**Issue by stefan1968** [hasura/graphql-engine#3448]
I've tried several variations of this, all resulting in the same error.
This worked fine under postgraphile, but having a real headache trying to get it to work under hasura.

I want to update the tsvector when I insert a message. Below is the trigger and the invocation.

CREATE FUNCTION influence.update_search_messages()
      RETURNS TRIGGER
      LANGUAGE PLPGSQL AS $BODY$
      begin
          new.tsv = setweight(to_tsvector('english', body), 'A');
          return new;
      END; 
      $BODY$;

And the invocation here: - 
CREATE TRIGGER message_search_default BEFORE
      INSERT
      OR
      UPDATE ON influence_comms.messages
      FOR EACH ROW  EXECUTE PROCEDURE influence.update_search_messages();

This migrates fine, however when i insert a message via graphQl, I get the following error:-

<img width="984" alt="Screenshot 2019-11-29 at 10 39 38" src="https://user-images.githubusercontent.com/5500038/69864000-01094300-1296-11ea-8712-742ff56ff308.png">

**Comment by ecthiender** [comment]
@stefan1968 the logs on the docker container should have more details about the postgres error. Can you check the logs?

Also, does the trigger work as expected when you insert data directly into the table?

**Comment by marionschleifer** [comment]
@stefan1968 were you able to resolve this issue? If yes, we can close this 🙂

**Comment by stefan1968** [comment]
Yes, you can close. I resolved it.

Thanks.
