### ISSUE TITLE
limit query depth

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#346]
At permission level and global level

[via 7777#7777 on discord]

**Comment by revskill10** [comment]
@shahidhk Any roadmap for this ?

**Comment by shahidhk** [comment]
We are looking at 2-3 weeks.

**Comment by Giorat** [comment]
Is there any news on this feature?

Just having a simple number of the max depth in hasura settings would be perfect! 

![image](https://user-images.githubusercontent.com/4527364/63518121-a327cb00-c4f0-11e9-8716-e65fdaa147ed.png)

**Comment by sahanatroam** [comment]
It seems that you need to have a PRO account to enable the query depth https://hasura.io/hasura-pro/#security :/ 

@shahidhk @Giorat @marionschleifer @kriswep
I think this is a vital piece of control you need to have on your "Production ready" GraphQL setup.

**Comment by GV14982** [comment]
Is there any update on this?

**Comment by alherd-by** [comment]
Does this feature will be available for Cloud version only?

**Comment by rikinsk** [comment]
Hey. Yes, unfortunately this feature is only available in the cloud and enterprise versions.

**Comment by rikinsk** [comment]
Here are the [docs](https://hasura.io/docs/latest/graphql/cloud/security/api-limits.html) regarding the same for the clooud/enterprise versions
