### ISSUE TITLE
"no foreign constraint exists on the given column" after upgrade to rc.1

### ISSUE THREAD

**Issue by shripadk** [hasura/graphql-engine#3463]
I have the following error show up in the logs after upgrading to rc.1 from beta.10:

```
graphql-engine_1  | {"path":"$.args[24].args","error":"no foreign constraint exists on the given column","code":"constraint-error"}
hasura_graphql-engine_1 exited with code 1
```

I checked the `hdb_catalog.hdb_relationship` table to see if any such relationship exists that I could remove but couldn't find one.

So have rolled back to beta.10 for now. If you need any other inputs from my end please let me know. Thanks!

**Comment by rakeshkky** [comment]
Hi @shripadk,

Please perform the following SQL query and comment on the results.

```sql
          SELECT f.constraint_name,
                 f.ref_table_table_schema,
                 f.ref_table,
                 f.constraint_oid,
                 f.column_mapping
            FROM hdb_catalog.hdb_foreign_key_constraint f
           WHERE f.table_schema = 'hdb_catalog' AND f.table_name = 'event_invocation_logs'
```

**Comment by shripadk** [comment]
Hi @rakeshkky 

This is the result of the running the query:

```
tcsm=>           SELECT f.constraint_name,
tcsm->                  f.ref_table_table_schema,
tcsm->                  f.ref_table,
tcsm->                  f.constraint_oid,
tcsm->                  f.column_mapping
tcsm->             FROM hdb_catalog.hdb_foreign_key_constraint f
tcsm->            WHERE f.table_schema = 'hdb_catalog' AND f.table_name = 'event_invocation_logs';
 constraint_name | ref_table_table_schema | ref_table | constraint_oid | column_mapping
-----------------+------------------------+-----------+----------------+----------------
(0 rows)
```

**Comment by rakeshkky** [comment]
@shripadk I'm not sure how, but a foreign key is missing on one of the `hdb_catalog` schema tables. It is `hdb_catalog.event_invocation_logs.event_id -> hdb_catalog.event_log.id`.

Alter the table to create the foreign key.
```sql
ALTER TABLE hdb_catalog.event_invocation_logs ADD CONSTRAINT event_invocation_logs_event_id_fkey FOREIGN KEY (event_id) REFERENCES hdb_catalog.event_log(id) ;
```

Now, upgrading to rc.1 and let us know if it works :slightly_smiling_face:

**Comment by shripadk** [comment]
@rakeshkky That did the trick. I am sure it must have been due to me using a database modeler and it dropping the foreign key while diffing changes. Will check if that is the case the next time I run the modeler after schema changes and report back.

Thank you so much for the help!  😄

**Comment by BenoitRanque** [comment]
@rakeshkky Do you know why this foreign key can be missing? The only references to that constrain name I can find in the repo are this issue, and a [migration that removes this constraint](https://github.com/hasura/graphql-engine/blob/master/server/src-rsr/pg_source_migrations/2_to_3.sql).

**Comment by rakeshkky** [comment]
@BenoitRanque From the reference you shared in the comment, it is clear that the said foreign key is no longer required in Postgres source database. Regarding this issue, I'm not sure about the missing foreign key. However, please let me know the specific issue (if any) you're looking at.

**Comment by BenoitRanque** [comment]
@rakeshkky correct, the constraint is no longer required.
However, [this migration](https://github.com/hasura/graphql-engine/blob/master/server/src-rsr/pg_source_migrations/2_to_3.sql) assumes that constraint exists, and we're trying to understand how we get in that state.

**Comment by rakeshkky** [comment]
@BenoitRanque Ah, you're right. I browsed through the source code, except the migration you mentioned, I cannot find any other instance where we drop the constraint. I really don't know the cause for the missing foreign key, within the scope of Hasura.

Let me know if any user is being affected of missing foreign key.

**Comment by BenoitRanque** [comment]
@rakeshkky do we know under what circumstances we would expect the constraint to be (and not be) created? I could not find the create statement.

**Comment by rakeshkky** [comment]
@BenoitRanque The fkey is created while adding the table `hdb_catalog.event_invocation_logs`. With the recent [migration](https://github.com/hasura/graphql-engine/blob/master/server/src-rsr/pg_source_migrations/2_to_3.sql), we're dropping the constraint.
