### ISSUE TITLE
Allow custom namespace for JWT session variables

### ISSUE THREAD

**Issue by dsemenovsky** [hasura/graphql-engine#350]
Hi!

We are exploring an option of using Auth0 + Hasura JWT authorization and there is a small, but very important piece that is missing.

Auth0 does not allow to have claims directly in the root of idToken object as Hasura docs ask:
```
{
  "sub": "1234567890",
  "name": "John Doe",
  "admin": true,
  "iat": 1516239022,
  "x-hasura-allowed-roles": ["editor","user", "mod"],
  "x-hasura-default-role": "user",
  "x-hasura-user-id": "1234567890",
  "x-hasura-org-id": "123",
  "x-hasura-custom": "custom-value"
}
```

Instead, Auth0 suggests creating custom namespace as follows:

```
{
  "sub": "1234567890",
  "name": "John Doe",
  "admin": true,
  "iat": 1516239022,
  "https://example.com/claims/hasura": {
    "x-hasura-default-role": "user",
    "x-hasura-allowed-roles": [
      "user"
    ],
    "x-hasura-user-id": "google-oauth2|000111222333444555666"
  }
}
```

Is it possible to add a configuration argument so it will be possible to specify a custom namespace to look for Hasura session variables, like this:

--jwt-claim-namespace "https://example.com/claims/hasura"

Thank you for you help!

Best,
Dmitry

**Comment by ecthiender** [comment]
Hey @dsemenovsky thanks for reporting this. Do you think there will be a problem, if we "fix" the name of the claim. Like:
```json
{
  "sub": "1234567890",
  "name": "John Doe",
  "admin": true,
  "iat": 1516239022,
  "hasura_claims": {
    "x-hasura-default-role": "user",
    "x-hasura-allowed-roles": [
      "user"
    ],
    "x-hasura-user-id": "google-oauth2|000111222333444555666"
  }
}
```
Or do you think its important that the namespace should be configurable. One disadvantage of configuration is, more things for the user to configure and understand.

cc @coco98

**Comment by coco98** [comment]
I think parametrising it makes sense because the jwt config is an
environment variable anyway that will differ in different environments and
so on.

 Is this the standard way to add custom claims to JWT?

**Comment by dsemenovsky** [comment]
From Auth0 docs (https://auth0.com/docs/scopes/current/custom-claims):

**Comment by ecthiender** [comment]
@dsemenovsky we will go ahead with an optional config which will default to `https://hasura.io/jwt/claims`

**Comment by dsemenovsky** [comment]
@ecthiender Thanks a lot! Can you then describe how to use it in the documentation?

**Comment by ecthiender** [comment]
@dsemenovsky we have fixed this. As soon as we release this and the docs, I will link to relevant docs here.

**Comment by ecthiender** [comment]
@dsemenovsky here is the docs link: https://docs.hasura.io/1.0/graphql/manual/auth/jwt.html

Let me know if the docs can be improved.

**Comment by aurokk** [comment]
Hello! 

I am using http://docs.identityserver.io (written on c#/.net core) and can't add namespaced claims (by design claims can contain only string values) :( 
IdentityServer is a most popular auth solution in .net community.

Can i configure HGE to look for claims in the access token root (and may be with namespace) ?
