### ISSUE TITLE
Unexpected Ordering When Using Variables

### ISSUE THREAD

**Issue by heliocaruccio** [hasura/graphql-engine#3501]
**Hi in console** 

`
query org {
  org(order_by: {deleted_at: desc, name: asc}){
    name
    deleted_at
  }
}
`

Produce

`SELECT name, deleted_at FROM org ORDER BY deleted_at DESC NULLS FIRST, name ASC NULLS LAST`

**AND**

`query org($orderBy: [org_order_by!]) {
  org(order_by: $orderBy){
    name
    deleted_at
  }
}
`
Variables => `{
  "orderBy": {"deleted_at":"asc", "name": "asc"}
}`

Produce

`SELECT * FROM org ORDER BY name ASC NULLS LAST deleted_at ASC NULLS LAST`

is this to be expected? I missed something?

**Comment by 0x777** [comment]
Hi, since the `variables` are sent as JSON, there is no guarantee about the order of keys in the object `{"deleted_at":"asc", "name": "asc"}`. However `order_by` can take an array of these clauses, so you should use `{"orderBy": [{"deleted_at":"asc"}, {"name": "asc"}]}`.

**Comment by heliocaruccio** [comment]
Perfect my friend @0x777 . Thank
