### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by lishine** [hasura/graphql-engine#3502]
Graph db vs on top of Postgres:
Dgraph vs Hasura

Another on top of Postgres:
Edgedb vs Hasura

Dgraph claim better performance because it eliminates many database access to db. Please see their linked blog and screenshot through this link:
https://github.com/edgedb/edgedb/issues/950#issuecomment-562848803

**Comment by marionschleifer** [comment]
@lishine could you please elaborate on what your intent is with this issue? Thank you 🙂

**Comment by lishine** [comment]
Sorry, didn't see your question.
I am planning db solution for next project and interested to know how hasura compars to similar solutions, regarding performance

**Comment by coco98** [comment]
@lishine We've talked about Hasura's performance and how it works. https://blog.hasura.io/architecture-of-a-high-performance-graphql-to-sql-server-58d9944b8a87/
I also did a talk at GraphQL Summit 2019 talking about the underlying architecture: https://www.youtube.com/watch?v=HOKMJkBYaqQ

Best way to compare the various systems would be to setup a sample schema in the different databases and then run some graphql queries against it. 

Some tools that might help in the benchmarking setup:
- https://github.com/hasura/graphql-backend-benchmarks
- https://github.com/hasura/graphql-bench
