### ISSUE TITLE
better UX for adding same permissions across several tables

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#351]
From intercom: 

> It'll be much more awesome if permissions could be grouped or inherited somehow. Right now I have to add the same rules for every table `X-hasura-org-id _eq org_id`

> I would say an another tab "Permissions".
There I add a permission "Tenant-only" f.e. with `X-hasura-org-id _eq org_id`
After that when I create/edit a table I see a list of available permissions and select "Tenant-only" with a checkbox

**Comment by rikinsk** [comment]
Added clone section in #1924 to apply across tables.

**Comment by rikinsk** [comment]
Tracking this with #280

**Comment by dsandip** [comment]
Closing this in favour of #611
