### ISSUE TITLE
Console shows error logs

### ISSUE THREAD

**Issue by flashspys** [hasura/graphql-engine#3512]
I followed the docker quickstart tutorial by installing a postgres and hasura via docker-compose. I could open the console, but the following error messages show up:
![image](https://user-images.githubusercontent.com/1114404/70552642-1164cc00-1b7a-11ea-8c34-58c05d41c681.png)

This happens every time I access the site. In fact, a /query call is not responding and thus the site takes minutes to load.
![image](https://user-images.githubusercontent.com/1114404/70552862-67d20a80-1b7a-11ea-8185-4b1042fd1f40.png)

**Comment by shahidhk** [comment]
@flashspys Can you give us more information on your environment? Hasura version, where is it deployed, how big is your schema?

**Comment by flashspys** [comment]
I used [this official docker-compose.yaml](https://github.com/hasura/graphql-engine/tree/master/install-manifests/docker-compose). The installed versions are, according to docker-compose, the postgres:latest and hasura/graphql-engine:v1.0.0 image. I've done nothing but run docker-compose up, so the database is clean.

**Comment by morbatex** [comment]
Hi,

I've got the same problem...

**Comment by flashspys** [comment]
@morbatex and me used both the eduroam network and if we were *not* using a HTTPS proxy, this problem occurs. So enabled HTTPS or changing the network helped.
