### ISSUE TITLE
Question: How to only allow joins on owned rows?

### ISSUE THREAD

**Issue by chmac** [hasura/graphql-engine#3514]
Example collections, `posts` and `tags`, and they're linked together with a `posts_to_tags` table which is a many to many join table. I want to set the permissions such that a user can only assign tags to their own posts. Is there a way to implement this with the hasura permission system?

I've set my insert / select permissions based on a column `user_id` that has to match the user from the JWT. But I can't figure out how to set the permissions on the join table...

**Comment by elitan** [comment]
![Screenshot 2019-12-11 at 13 35 23](https://user-images.githubusercontent.com/331818/70622293-e8951300-1c1b-11ea-9e8e-7a8ddd053b82.png)

Does this match what you are trying to do?

**Comment by chmac** [comment]
@elitan Awesome, thanks for sharing this.

The crucial piece I was missing is that it's possible to express permission on linked tables.

For anybody stumbling upon this issue in the future, the key steps I had to complete were:

* Ensure that the Relationships tab has the link between all related tables (so A -> join, join -> A)
* Then the option to set permissions based on linked values (as per the screenshot above) was available

Awesome, thanks @elitan. I'm increasingly impressed with hasura the more I dive into it.
