### ISSUE TITLE
docker image doesn't stop on failed migrations

### ISSUE THREAD

**Issue by Krever** [hasura/graphql-engine#3520]
When applying migrations fail its reasonable to assume the docker will stop. Such behaviour is critical for production run. Right now if you deploy the application on different environment its almost impossible to spot the failure until the downstream system fails. 

Fix is probably very simple, in bash startup script just detect the exit code of `migration apply` and stop if its !=0. Or add `set -e` at the top.

**Comment by shahidhk** [comment]
@Krever Considering you're talking about the `cli-migrations` image, the container indeed exits if migration apply fails, see (https://github.com/hasura/graphql-engine/blob/master/scripts/cli-migrations/docker-entrypoint.sh#L3) 

Check you Kubernetes/Docker Compose configuration to see if the restart policies are starting it again.

**Comment by Krever** [comment]
Hmm, that's weird indeed and I will investigate it further on my end. Thanks and sorry for trouble.

**Comment by Krever** [comment]
I can reproduce it now, sorry for bothering.
