### ISSUE TITLE
Bug: Equality checks on optional parameter don't work when it's undefined. Can't check if undefined.

### ISSUE THREAD

**Issue by rccoe** [hasura/graphql-engine#3523]
I'm running this query:

`
GetUserFromList($user_id: Int) {
  list(
    where: {_and: [{ user_id: { _eq: $user_id }}, {user_id:{_neq:null}}]} 
  ) {
    user_id
  }
}
`

and getting these results

`
"data": {
    "list": [
      {
        "user_id": 14
      },
...
`

How can I filter out where the user_id = null? I'm running a mutation using this logic and it's updating everything in the table when user_id = null

Thanks!

**Comment by rccoe** [comment]
Dupe of #704

**Comment by paf31** [comment]
I don't think this is a duplicate, since that issue refers to `undefined`, not `null`. However, the part of the manual I think you need is [here](https://docs.hasura.io/1.0/graphql/manual/queries/query-filters.html#filter-or-check-for-null-values-is-null).

**Comment by rccoe** [comment]
That logic can't be used on parameters. If you do

`
{$user_id:{_neq:null}}
`
or
`
{$user_id:{_is_null: false}}
`

It evaluates to true, which doesn't seem right. Reopening as I think you're right.

**Comment by paf31** [comment]
What about making the type non-nullable? i.e. `GetUserFromList($user_id: Int!) { ... }`

**Comment by rccoe** [comment]
The use case is an upsert mutation. I have relationships between 3 tables. The situation is I want to upsert users, and if they've changed orgs, transfer their lists to the new org.

Relationships:
org -> list[]
user -> list[]
org -> user[]

```
mutation UpsertUser($user: user_insert_input!, $org_id: Int, $user_id: Int) {
  insert_auth_user(
    objects: [$user]
    on_conflict: {
      constraint: user_pkey
      update_columns: [first_name, last_name, email, org_id]
    }
  ) {
    affected_rows
    returning {
      id
    }
  }
  update_list(
    where: { user_id: { _eq: $user_id } }
    _set: { org_id: $org_id }
  ) {
    affected_rows
    returning {
      id
    }
  }
}
```

In the case of the new user, this will update all lists org_id to $org_id.

Due to this bug, doing what I want either requires 2 calls, or including all lists in the $user payload with the new org_id.

**Comment by paf31** [comment]
I think I understand the problem then. Would something like the following work?

```
query GetUserFromList($user_id: Int, $allow_nulls: Boolean) {
  list(where: {id: {_eq: $user_id, _is_null: $allow_nulls}}) {
    id
  }
}
```

You could then query with parameters `{"user_id": 42}` for a specific user, or `{"allow_nulls": true}` for a new user, instead of passing `{"user_id": null}`.

The reason `{"user_id": null}` isn't working is that, as we see if we substitute the inputs into the query definition, it's the same as asking for:

```
query Inlined {
  list(where: {id: {_eq: null}}) {
    id
  }
}
```

which is equivalent to no filter at all. @0x777 might have a more informed opinion on whether that's a bug or not?

**Comment by marionschleifer** [comment]
@rccoe is your question answered? If yes, we can close this issue 🙂

**Comment by marionschleifer** [comment]
@rccoe I'm closing this issue. Feel free to re-open if you'd like to add anything 🙂
