### ISSUE TITLE
WebSocket connection fails.

### ISSUE THREAD

**Issue by dsemenovsky** [hasura/graphql-engine#353]
Hi,

I am trying to implement WebSocket subscriptions to Hasura and here is my client setup:

```
import ApolloClient from 'apollo-client';
import { WebSocketLink } from 'apollo-link-ws';
import { HttpLink } from 'apollo-link-http';
import { split } from 'apollo-link';
import { getMainDefinition } from 'apollo-utilities';
import { InMemoryCache } from 'apollo-cache-inmemory';

import { getToken } from 'services/auth0'
import { hasura } from 'config'

class HasuraDAO {
  constructor() {
    const wsLink = new WebSocketLink({
      uri: hasura.wsUrl,
      options: {
        reconnect: true,
        timeout: 30000
      }
    });
    const httpLink = new HttpLink({
      uri: hasura.httpUrl,
      headers: {
        'Authorization': `Bearer ${getToken()}`
      }
    })

    const link = split(
      ({ query }) => {
        const { kind, operation } = getMainDefinition(query);
        return kind === 'OperationDefinition' && operation === 'subscription';
      },
      wsLink,
      httpLink,
    )
    
    this.client = new ApolloClient({
      link,
      cache: new InMemoryCache()
    });
  }
}

export default new HasuraDAO()
```

This is the call of client.subscribe function:

```
import Hasura from 'dao/hasura/HasuraDAO';
import gql from 'graphql-tag';

const query = gql`subscription {
  users {
    id
  }
}`

const observable = Hasura.client.subscribe({ query });
observable.subscribe({
  next: ({ data }) => console.log(data)
});
```

I think I'm doing it all right, but still getting this error:

```
client.js:426 WebSocket connection to 'ws://localhost:8081/v1alpha1/graphql' failed: Data frame received after close
```

Can you please help me finding my mistake?

**Comment by dsemenovsky** [comment]
Resolved with:

```

**Comment by 0x777** [comment]
@rikinsk Should this be documented somewhere?

**Comment by coco98** [comment]
@rikinsk I had this question for adding auth to subscriptions also. I’m not sure if that’s documented either.

**Comment by russc** [comment]
I had this problem too and went looking for some more context for the connectionParams snippet above.  The example below is taken from [Actions.js](https://github.com/hasura/graphql-engine/blob/6ba9c759e6ea739fdf91ff17379bae9fb646f5b6/console/src/components/ApiExplorer/Actions.js) in the Api Explore.  This was enough to help me refactor for my needs.  Hopefully we can get this documented somewhere as well.  
```
const client = new SubscriptionClient(graphqlUrl, {
    connectionParams: {
      headers: {
        ...headersFinal,
      },
    },
    reconnect: true,
  });
```

**Comment by coco98** [comment]
Re-opening this issue so that we add it to our docs! Thanks @russc for bringing it back up.

**Comment by rikinsk** [comment]
related: #994 #472

**Comment by rikinsk** [comment]
Tracked here #412

**Comment by louisdvs** [comment]
For anyone else who gets a little stuck on this, took me a bit of playing to get it working, but my config looks like:
```
const wsLink = new WebSocketLink({
  uri: `ws://${window.location.hostname}/gql/v1/graphql`,
  options: {
    reconnect: true,
    connectionParams: {
      headers: {
        Authorization: `Bearer ${getAccessToken()}`
      }
    }
  }
})

**Comment by dedan** [comment]
Even with the solution of @louisdvs I still get this error when using `wss:` instead of `ws:`. 

Does anybody know how to fix this?

**Comment by ashish-beetle** [comment]
For me the error was due to the expired accessToken. I checked the ws request was able to see that the request was using old access tokens instead of the newly generated ones. The access token was not getting updated.
