### ISSUE TITLE
Recursive object as a graphql field

### ISSUE THREAD

**Issue by Tbaut** [hasura/graphql-engine#3531]
Is there a way to add a recursive object type as a field as explained here: https://github.com/graphql/graphql-spec/issues/91#issuecomment-197860064 ?
The idea is to have replies on comments in a forum (like reddit, you can reply to a comment, which can be replied to etc.)

So that I could do the following query:
```gql
{
  messages {
    ...CommentsRecursive
  }
}

fragment CommentsRecursive on Message {
  comments {
    ...CommentFields
    comments {
      ...CommentFields
      comments {
        ...CommentFields
      }
    }
  }
}

fragment CommentFields on Comment {
  id
  content
}
```

In the link I posted above, managing your own graphql server, they achieve it by using a function as a field that returns some other fields:
```js
const Message = new GraphQLObjectType({
  name: 'Message',
  fields: () => ({
    comments: {
      type: new GraphQLList(Message),
      resolve(message) {
        return getComments(message.id);
      },
    },
    content: {
      type: GraphQLString,
    },
  }),
});
```

I wonder how I could achieve something similar with hasura.

**Comment by ecthiender** [comment]
You can have a Postgres table which is recursive.

E.g. - 

```sql
CREATE TABLE messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content text NOT NULL,
  parent_message UUID REFERENCES messages(id)
);
```
Then in the Hasura console, if you go to the relationships tab of the messages table, you can see that both object and array relationships are suggested on the same table. You can add them both, name the object relationship as `parent` and the array relationship as `children`.

Now you can make the following query:

```graphql
query {
  messages {
    id 
    content
    children {
      id
      content
    }
  }
}
```

This fetches all messages and all their children. 

PS: beware that this query can be quite expensive on large data set. You would add limits etc. when using the query in production.

**Comment by Tbaut** [comment]
Thank you so much. A simple foreign key is indeed doing the job perfectly.
