### ISSUE TITLE
WebSockets socket hang up

### ISSUE THREAD

**Issue by spiffytech** [hasura/graphql-engine#3538]
I have a Node.js server that connects to Hasura using subscriptions-transport-ws. Over the course of processing hundreds of thousands of event triggers, the connection will periodically get terminated with `ECONNRESET`. I have the Hasura loglevel set to `warn` and nothing is printed out. This is all local using Docker Desktop for Windows and WSL., so there shouldn't be any actual network issue going on.

**Comment by marionschleifer** [comment]
@spiffytech can you give us a reproduction case, e.g. can you paste some logs here on the issue please? It will make it easier for us to help 🙂

**Comment by marionschleifer** [comment]
@spiffytech just wanted to follow up on this. Is your issue resolved? If yes, we can close this issue 🙂

**Comment by marionschleifer** [comment]
I'm closing this issue. @spiffytech feel free to re-open if you'd like to add something 🙂
