### ISSUE TITLE
How to use graphiql console with another schema?

### ISSUE THREAD

**Issue by joshuarobs** [hasura/graphql-engine#3541]
In the Data tab, I have multiple schemas. When I go to the Grahiql tab, all of the queries and mutations done are all from the the `public` schema and not the other schemas. How can I do some queries with other schemas?

**Comment by rikinsk** [comment]
You should be able to use Graphiql for tables from all schemas. Do note that for a table in a non public-schema, the field names are of the format `schema_table`

**Comment by marionschleifer** [comment]
@joshuarobs I'm closing this issue. Feel free to re-open, should you have any more questions 🙂
