### ISSUE TITLE
missing semi-colon in create table down migration

### ISSUE THREAD

**Issue by nirvdrum** [hasura/graphql-engine#3543]
I squashed my migrations and ended up with a `down.sql` file that looks like:

```
DROP TABLE "public"."todos"
DROP TABLE "public"."users"
```

There is no semi-colon after the statements and so when running the down migration, I get the following error:

```
FATA[0000] apply failed: [postgres-error] query execution failed ($.args[58].args)
File: '1576429237138_init/down.sql'
{
    "sql": "\nDROP TABLE \"public\".\"todos\"\nDROP TABLE \"public\".\"users\"\n"
}
[42601] FatalError: syntax error at or near "DROP" 
```

Terminating the statements with a semi-colon fixes the problem for me.

**Comment by rikinsk** [comment]
This is due to a bug with the individual down migrations that were and not the squash command.

**Comment by nirvdrum** [comment]
I started to suspect as much. I squashed another set of migrations and this time the `up.sql` file was broken. Beyond the problem with the missing semi-colons, In that one the casing of the SQL statements was not consistent either. Some statements used `ALTER` while others used `alter`. And they weren't all left-justified.
