### ISSUE TITLE
split metadata into multiple files

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#3545]
If there is a key named `metadata_dir` in `config.yaml`, we should read all the files in that directory and merge them to construct the Hasura Metadata object to be sent in `replace_metadata` query to server.

This should be used in the `metadata apply` command. 

The motivation is to let the user split the metadata files however they seem fit and the CLI will take care of merging them to a single object.

We can probably use https://github.com/imdario/mergo

**Comment by arvi3411301** [comment]
@shahidhk  Can we close this?

**Comment by marionschleifer** [comment]
This feature has been implemented in `1.2beta`. Closing this issue.
