### ISSUE TITLE
Cannot ssh into the VM on Heroku

### ISSUE THREAD

**Issue by scribahti** [hasura/graphql-engine#3559]
Hasura Version: v1.0.0-beta.6
Deployment platform: Heroku (using the provided template)
Dyno Type: Hobby

```
$ heroku ps:exec -a app-name
Establishing credentials... error
 ▸    Could not connect to dyno!
 ▸    Check if the dyno is running with `heroku ps'
```

I've tried restarting the dyno, with the same result.

Please let me know if https://github.com/hasura/graphql-engine-heroku is the appropriate repo for this issue.

**Comment by shahidhk** [comment]
For Heroku Exec to work on Docker containers there are some pre-requisites that the container image needs to satisfy as indicated here: https://devcenter.heroku.com/articles/exec#using-with-docker

Hasura's container does not satisfy these requirements. What is your use-case with exec? Maybe you can build a custom image using Hasura's container as a base image?

**Comment by scribahti** [comment]
Thanks, I suspected this might be the case. I need to pull the access logs for http requests against the Hasura server. 

I see your pinned issue here: https://github.com/hasura/graphql-engine/issues/3374 and will reach out via that form.

**Comment by marionschleifer** [comment]
@scribahti you can access the logs with the `heroku logs` command as described [here](https://docs.hasura.io/1.0/graphql/manual/deployment/heroku/logging.html#hasura-graphql-engine-server-logs-heroku) 🙂

**Comment by marionschleifer** [comment]
@scribahti I'm closing this issue. Feel free to re-open if you would like to add something 🙂

**Comment by mike-boost** [comment]
is there an available qualified image?
