### ISSUE TITLE
Add a 'retry' to hasura-cli for `migrate` command

### ISSUE THREAD

**Issue by dvasdekis** [hasura/graphql-engine#3560]
I am using hasura-cli to apply migrations [in a separate container](https://github.com/dvasdekis/hasura-cli-docker) in a secure environment, similar to how [Flyway docker containers](https://github.com/flyway/flyway-docker) can migrate my database. This avoids me having to give the Hasura user any CREATE SCHEMA permissions in my database. 

Right now however, if hasura-cli can't find the Hasura server immediately upon first ping, the migrations fail and the cli exits. This isn't a problem with [Flyway's docker container](https://github.com/flyway/flyway-docker), as Flyway has a `-connectRetries=N` parameter, which lets Flyway retry its migrations N times.

As such, I'd like to request that the Hasura CLI gets a `-connectRetries=N` parameter or similar, which adds N retries to `migrate apply` and `metadata apply`.

Thanks!!

**Comment by shahidhk** [comment]
The typicall pattern in the container world is to tell the orchestrator to restart the container if it fails. Kubernetes does always and can be enabled on docker compose with `restart: always`.

Will this not work for you?

**Comment by dvasdekis** [comment]
So simple! I found that Docker Run likewise accepts an `--on-restart` flag, which is good when deploying to other forms of infrastructure. Thank you.
