### ISSUE TITLE
Computed field not working with a role

### ISSUE THREAD

**Issue by santicomp2014** [hasura/graphql-engine#3565]
The computed field appears correctly when using admin, but when I try using the same query with a role, the computed field is not event selectable.

This would go in hand with #3522 by adding computed field permission on a specific role.

**Comment by fred8617** [comment]
![image](https://user-images.githubusercontent.com/35049517/71777464-4dede100-2fdb-11ea-93de-faa0f9d659bb.png)
my temp solution is apply the permission via cli

**Comment by rikinsk** [comment]
closed this in https://github.com/hasura/graphql-engine/commit/db6b2aa3781201b05e98e292a3a4ca13a0057e00
