### ISSUE TITLE
In Zhengzhou, China, CDN resource loading is too slow

### ISSUE THREAD

**Issue by einsqing** [hasura/graphql-engine#3568]
In Zhengzhou, China, CDN resource loading is too slow

**Comment by shahidhk** [comment]
@epicalyx use this to load assets from server itself instead of the cdn https://docs.hasura.io/1.0/graphql/manual/deployment/graphql-engine-flags/config-examples.html#run-console-offline-i-e-load-console-assets-from-server-instead-of-cdn
