### ISSUE TITLE
Return non 200 http status code on error

### ISSUE THREAD

**Issue by Oleg2tor** [hasura/graphql-engine#3571]
From version 6 hasura starts to respond 200 http status code at error requests.

**Comment by shahidhk** [comment]
@Oleg2tor Most GraphQL clients expect all responses to be 200, hence this change was introduced in https://github.com/hasura/graphql-engine/pull/2064 only for `/v1/graphql` API.

The `/v1alpha1/graphql` API still responds with non-200 status codes.

**Comment by Oleg2tor** [comment]
@shahidhk Thank you for response.
I can't say about GraphQL clients, but most of fetch clients working with status code.
For example in axios:

```javascript
axios({...params})
    .then(({ data }) => 
        dispatch({
            type: `${type}_success`,
            data
       })
    )
    .catch(({ message }) => 
        dispatch({
            type: `${type}_error`,
           message
        })
    )
```

As far as there can be not only GraphQL responses,
and some of they can send data.errors too - there can be collisions,
so the middleware that handle responses should know if there was
an hasura request or something else to choose correct way.

in variant with "always 200" code should look like:

```javascript
axios({ ...params })
  .then(({ request, data }) => {
    const isHasuraRequest = GRAPHQL_URLS.includes(request.url);
    const isDataExists = !!data;

    let parsed = data;
    let isDataJson = false;

    // Who know's may be there 500 errors with 200 status code
    // Or you ment to avoid only 4xx errors but not 5xx?
    try {
      parsed = JSON.parse(data);
      isDataJson = true;
    } catch (err) {
      throw new Error({ message: err });
    }

    if (isHasuraRequest && isDataExists && isDataJson && data && data.errors) {
      dispatch({
        type: `${type}_error`,
        data
      });
    } else {
      dispatch({
        type: `${type}_success`,
        data
      });
    }
  })
  .catch(({ message }) =>
    dispatch({
      type: "error",
      message
    })
  );
```

Obviously there performance impact because of try / catch and extra json parsing.

I realise there can be counter arguments, but I think there should be at least option for this.

**Comment by Oleg2tor** [comment]
There few more things:
Browsers highlights error responses by red color. So there easy to debugging during development.
Also some cache layers can decide when to invalidate itself by http status code.

**Comment by tirumaraiselvan** [comment]
I think this could be a server-flag.

**Comment by marionschleifer** [comment]
@Oleg2tor you can use `/v1alpha1/graphql` endpoint which will respond with non 200 status codes for errors 🙂

**Comment by 0x777** [comment]
@Oleg2tor The idea behind `200` for error responses is that the error reporting mechanism is not dependent on the transport (http/websocket). The GraphQL spec also accommodates for returning partial data for a request, in this case you will have both `data` and `errors` in the response. Unfortunately you can't represent such cases with `2xx` and non-`2xx` error codes. 

For now, you can use the `/v1alpha1/graphql` endpoint (will be deprecated eventually) which reports errors with a non `200` error code, however the typical pattern in the GraphQL ecosystem is to use `200` for a response (on `http` transport) and then check for `errors` inside the response, so it might be better to stick to this pattern as much as possible.

**Comment by ecthiender** [comment]
I would like to add to what @0x777 already said, that it's not just a typical pattern but rather it is the convention in the GraphQL ecosystem. For example, apollo-client (and other popular client libraries) will not even show the HTTP response in-case of a non-200 response, and will only show a "network error". Those libraries rely on the `error` key in the response JSON. This makes sense - as GraphQL kind of sits on top of HTTP as an application layer by itself and abstracts the transport (HTTP in this case), hence the transport's error reporting mechanism is not used to report GraphQL query/operation errors at all.

**Comment by Oleg2tor** [comment]
@ecthiender well as you can see apollo-client users have some troubles because of this decision https://github.com/apollographql/apollo-client/issues/5656
And based on this issue there some sandbox server that response 400 error, so that convention you point (never heard about it) seems like not applicable wildly.
Anyway I'm not arguing about correctness just asking to leave option for those, who prefer to make HTTP status code based architecture.

@marionschleifer @0x777 Thank you, @shahidhk already pointed me that v1alpha url. I worried because it's seem like something deprecated rather optionable.

**Comment by eugenijusr** [comment]
Alternatively you can also retrieve `graphQLErrors` from `ApolloError` via `networkError` property even when response code is not `200`.

```typescript
export const handleApolloError = (error: ApolloError) => {
  var graphQLErrors = error.graphQLErrors;
  if (graphQLErrors.length === 0) {
    const serverError = error.networkError as ServerError;
    graphQLErrors = serverError.result.errors as ReadonlyArray<GraphQLError>;
  }

  console.log(graphQLErrors);
}
```

**Comment by praveenweb** [comment]
Closing this with reasoning provided in https://github.com/hasura/graphql-engine/issues/3571#issuecomment-568425942 and https://github.com/hasura/graphql-engine/issues/3571#issuecomment-568668932

The convention in GraphQL is to return a 200 and check for `errors` inside the response on the client.

**Comment by brauliobo** [comment]
that is quite unfortunate, as integrating to other APIs might involve just using the HTTP status code

**Comment by omerlugov** [comment]
As [Phil Sturgeon](https://apisyouwonthate.com/authors/phil-sturgeon) put it: "**_Do. Not. Use. 200. For. Errors. Ok?!_**"
Full article: [Creating Good API Errors in REST, GraphQL and gRPC](https://apisyouwonthate.com/blog/useful-api-errors-for-rest-graphql-and-grpc), April 15, 2019

**Comment by zhang-wenchao** [comment]
I think I want to re-open this problem.
