### ISSUE TITLE
_inc operator works only for Int fields

### ISSUE THREAD

**Issue by piroszhog** [hasura/graphql-engine#3573]
In Hasura console I see the following description for _inc opertor: 
> input type for incrementing integer columne

But I read in your blog [here](https://blog.hasura.io/updating-data-using-mutations-on-hasura-graphql-87c7e22503bc/), that it should work for any numeric field. Where is the truth?

**Comment by piroszhog** [comment]
@marionschleifer if it's a right behaviour now, I would convert this issue to an enhancement request, to extrapolate the _inc operator to all numeric fields, not only Int.

**Comment by gvNN7** [comment]
Any **update** on this? I'm facing the same issue, trying to using _inc in a numeric field like sayed on blog..

> Using the "_inc" operator
The _inc operator atomically increments the existing value of one or more columns by a given amount. This operator is only for columns that have a “numeric” type, **like integer, numeric, float, double etc.**

**Comment by marionschleifer** [comment]
@gvNN7 This issue is something we would like to pick up and we are figuring out its priority.

**Comment by perrosnk** [comment]
This issue is a blocker for us because we work with money transactions with lots of numeric fields and for that reason we cannot yet adopt hasura!
Is there any workaround? Any timeline on when will this be fixed?

**Comment by tirumaraiselvan** [comment]
@perrosnk We will pick this up ASAP.

**Comment by perrosnk** [comment]
@tirumaraiselvan Is there any chance that this gets included in v.1.2?

**Comment by tirumaraiselvan** [comment]
@perrosnk There is a slim chance but it will definitely be included in v1.3.

**Comment by abooij** [comment]
I've created a table with various field types to see which column types support `_inc`. The results are as follows:

Column types that appear to support `_inc`: `smallint`, `integer`, `bigint`.

Column types that do not yet appear to support `_inc`: `real`, `doubleprec`, `money`, `numeric`.
