### ISSUE TITLE
Support for PostgreSQL High-Availability with Load Balancing

### ISSUE THREAD

**Issue by colundrum** [hasura/graphql-engine#3581]
Hello,

I run a PostgreSQL cluster similar to https://github.com/vitabaks/postgresql_cluster#type-a-postgresql-high-availability-with-load-balancing

So I've nodes ready for read only and the master for read&write.

Can you support this setup which is the best for maximum performance and scaling ?

Regards

**Comment by colundrum** [comment]
Hello @bappr ,  Have you any solution about this deployment?

**Comment by shahidhk** [comment]
@colundrum This will require implementing https://github.com/hasura/graphql-engine/issues/1847 or something similar.

Can I close this as a duplicate for the mentioned issue?

**Comment by colundrum** [comment]
Ow yes, sorry for the duplicate.
Have you an ETA about this implementation ?

**Comment by marionschleifer** [comment]
@colundrum we don't have an ETA at the moment. Please do upvote the issue and describe your use case in a comment, so that we can consider it for the next iterations 🙂 closing this issue.

**Comment by tirumaraiselvan** [comment]
@colundrum I would love to get some more input in prioritising and giving an ETA. Could you ping me on Discord (https://discordapp.com/invite/hasura), my handle is `@tiru` and we can chat over there ?

**Comment by Gerharddc** [comment]
I've managed to work around this issue by placing pgpool before Hasura. For anyone trying to do the same you can check out the Docker image I made for this at https://hub.docker.com/r/gerharddc/pgpool .
