### ISSUE TITLE
Updating instructions on Heroku not clear enough

### ISSUE THREAD

**Issue by joshuarobs** [hasura/graphql-engine#3582]
I tried looking at the page https://docs.hasura.io/1.0/graphql/manual/deployment/heroku/updating.html to update Hasura on an already live instance of Hasura, but I can't get it to work.

I tried running: `
heroku git:remote -a <hasura-heroku>
` but it's not working.

I get this:
`
Error: Command failed: git remote
fatal: not a git repository (or any of the parent directories): .git
`

I guess I just tried installing the Heroku CLI, logging in and trying to run that command, but it doesn't work. I guess that's the first command I ran, without trying the instructions in step 1, but I don't even know what I should be doing.

Is there a step by step process, from 0 (i.e. opening up a new terminal window) on what commands to specifically run to update Hasura on Heroku?

Thanks

**Comment by shahidhk** [comment]
Hi, you should go through step 1, without which the rest won't work. For step 1, you should clone the graphql-engine-heroku repo:
```
git clone https://github.com/hasura/graphql-engine-heroku
cd graphql-engine-heroku
```

and then move on to step 2
