### ISSUE TITLE
Claims key: 'https://hasura.io/jwt/claims' not found

### ISSUE THREAD

**Issue by ChaituVR** [hasura/graphql-engine#3589]
i am getting following error: 
```
"claims key: 'https://hasura.io/jwt/claims' not found"
```
![image](https://user-images.githubusercontent.com/15967809/71436093-d2a24a80-2711-11ea-9e99-89aa1231eab1.png)

**Comment by shahidhk** [comment]
@ChaituVR What service are you using to issue JWTs? Have you configured it to add the claims as mentioned here: https://docs.hasura.io/1.0/graphql/manual/auth/authentication/jwt.html#the-spec

**Comment by ChaituVR** [comment]
Sorry my bad...  i was using Firebase existing project.. and i was using existing email which doesn't have custom claims, after checking with new emails that has customClaims.. it is working :stuck_out_tongue: 
```
return admin
    .auth()
    .setCustomUserClaims(user.uid, customClaims)
    .then(() => {
```

do we have any option to add custom claims to existing users ? (Just curious)

**Comment by shahidhk** [comment]
I think you can go through all users once using the admin sdk and add the required claims as a one-time job.

**Comment by tonyjmartinez** [comment]
Hi, I'm experiencing this issue and would appreciate some help. I have a nextjs application using auth0. I'm trying to add auth0 authentication similar to this tutorial https://github.com/hasura/learn-graphql/tree/master/tutorials/frontend/nextjs/app-final

I'm able to login successfully and get my auth0 profile with `auth0.handleProfile`. I get back a `user` object with `https://hasura.io/jwt/claims` as one of the keys.

However, when I try to run a graphql query (by navigating to `/posts` in my case), I get the following error:
```
error Error: Network error: cannot start as connection_init failed with : claims key: 'https://hasura.io/jwt/claims' not found
    at new ApolloError (bundle.esm.js?74ca:63)
```

So it seems like my claim isn't being added. I know I have the rule setup on auth0 to add the claim. And I see the claim in the user object when calling `auth0.handleProfile`.

I'm not sure what I'm doing wrong.

Here's the repo: https://github.com/tonyjmartinez/from-way-downtown-next

**Comment by luistak** [comment]
@tonyjmartinez  try to check your auth0 rules, it was happening with me but I saw it was a typo in this section:
https://hasura.io/learn/graphql/nexatjs-fullstack-serverless/auth0-setup/1-custom-claims/

**Comment by keremgocen** [comment]
@tonyjmartinez I have the same problem, were you able to resolve it?

**Comment by markau** [comment]
For others stuck doing the Hasura tutorials: thanks @tonyjmartinez, I updated the Auth0 rule to apply the claims to the idToken as well, problem solved, i.e. I added

````
    context.idToken[namespace] =
    {
      'x-hasura-default-role': 'user',
      // do some custom logic to decide allowed roles
      'x-hasura-allowed-roles': ['user'],
      'x-hasura-user-id': user.user_id
    };
````

**Comment by bryanyanay** [comment]
@markau Hello! I'm doing the Hasura Basics tutorial, and I believe I'm stuck with the same problem. 

After implementing the action that gets auth0 profile info (according to the tutorials instructions), I keep getting the `"claims key: 'https://hasura.io/jwt/claims' not found"` error.

From your comment it seems that you solved it by adding the claims to the idToken as well as the accessToken, but that doesn't seem to work for me. Could you detail how you solved this a bit more?
