### ISSUE TITLE
Can deploy hasura on openfaas ?

### ISSUE THREAD

**Issue by KaKaVip** [hasura/graphql-engine#3591]
Hi,
I have a question
Có thể triển khai hasura trên openfaas ?

**Comment by darknoon** [comment]
Phạm, I am not super familiar with OpenFaaS but it sounds like something for situations where you have a pure function on the server ie responding to an HTTP request. Hasura is unique in that it gives your serverless functions a place to maintain a persistent connection to the db, process events reliably etc. So you want a persistent container and database.

It's pretty easy to just run hasura on Kubernetes / docker. I am using the Heroku free tier and it's plenty fast for my site (you could just as easily host yourself or run on AWS / GCE, etc).

I'll let someone on the team explain more.

**Comment by shahidhk** [comment]
@KaKaVip, as @darknoon mentioned, while Hasura can indeed run in serverless environments, it is best if we run it as a long running service so that subscriptions and event triggers can work reliably.

**Comment by denizkenan** [comment]
We use both Hasura and OpenFaaS. Super happy...

**Comment by L-U-C-K-Y** [comment]
Hi @denizkenan would you mind sharing the YAML for deploying Hasura as a sidecar?

Thanks!
