### ISSUE TITLE
Support of field-to-field comparison in where argument

### ISSUE THREAD

**Issue by piroszhog** [hasura/graphql-engine#3595]
For example, I have a table contains `date1` and `date2` fields. I want to select all the rows, where `date1` < `date2`. I can easily do it in SQL like this
```sql
SELECT * FROM TableName WHERE date1 < date2;
```

But there is no syntax in Hasura to create query like that.

P.S. If I missed something in docs, I will be glad for help and it would be great to add examples to docs.

**Comment by marionschleifer** [comment]
@piroszhog thank you for reporting this issue. It's already tracked here: https://github.com/hasura/graphql-engine/issues/457. I'm closing this as a duplicate.
