### ISSUE TITLE
Different value in db vs what's returned from hasura

### ISSUE THREAD

**Issue by pcmaffey** [hasura/graphql-engine#3596]
When I insert a record using a custom Id generator function, Hasura returns a value that's different from what's actually in the db (inspected with pgadmin).

Here's my custom id generator:
```
DECLARE
    our_epoch bigint := 1314220021721;
    seq_id bigint;
    now_millis bigint;
    -- the id of this DB shard, must be set for each
    -- schema shard you have - you could pass this as a parameter too
    shard_id int := 1;
BEGIN
    SELECT nextval('global_id_sequence') % 1024 INTO seq_id;

    SELECT FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000) INTO now_millis;
    result := (now_millis - our_epoch) << 23;
    result := result | (shard_id << 10);
    result := result | (seq_id);
END;
```

2207616964346512600 <- example result returned by Hasura
2207616964346512664 <- what's actually in the db

Playing around with this, I can see that the difference is in the bitwise shift left operator. Lowering 23 to 12 or so, stabilizes the values.

But this brings up 2 major concerns:
1. Why is the bitwise left operator resulting in a different value in Hasura vs db?
2. How is it possible that Hasura is returning a different value than what is in the db?

**Comment by pcmaffey** [comment]
Also, here's a screenshot of attempting to query (not found) for an id using the values returned (cached?) by hasura.
![Screen Shot 2019-12-26 at 11 50 51 AM](https://user-images.githubusercontent.com/14334017/71490710-86c2d480-27e9-11ea-8151-10cd4c2a69fd.png)

**Comment by pleclech** [comment]
You can try to enable  --stringify-numeric-types or HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES because bigint don’t fit into the IEEE-754 for json.

See documentation reference :  https://docs.hasura.io/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html

**Comment by pcmaffey** [comment]
Thanks! That solved it
