### ISSUE TITLE
Using permissions with Postgres enum field doesn't show comparing options

### ISSUE THREAD

**Issue by garlou** [hasura/graphql-engine#3603]
I'm using typeorm to manage my database migrations and when I use typescript enums, typeorm generates a Postgres table like this:
<img width="601" alt="Screenshot 2019-12-30 11 42 23" src="https://user-images.githubusercontent.com/1465244/71578862-2a69f880-2afa-11ea-97a4-cf197008d1d2.png">

When I try to setup a permission, the dropdown select is empty:
<img width="386" alt="Screenshot 2019-12-30 11 43 01" src="https://user-images.githubusercontent.com/1465244/71579018-dc092980-2afa-11ea-9472-fe88e20fed36.png">

Workaround:
Save permission as it is, export hasura metadata and then manually edit the metadata.yaml:
<img width="232" alt="Screenshot 2019-12-30 11 44 32" src="https://user-images.githubusercontent.com/1465244/71579122-723d4f80-2afb-11ea-80fe-24b180378db8.png">
to
<img width="239" alt="Screenshot 2019-12-30 11 44 50" src="https://user-images.githubusercontent.com/1465244/71579130-7a958a80-2afb-11ea-966f-3c9018487714.png">

Then apply the fixed metadata file on server.

**Comment by nick4u** [comment]
Any chance for having this in 1.1?

**Comment by rikinsk** [comment]
@nick4u Unfortunately the feature set for v1.1 is already frozen. We'll aim to get this fixed in v1.2
