### ISSUE TITLE
Cannot create view, "already tracked"

### ISSUE THREAD

**Issue by spiffytech** [hasura/graphql-engine#3607]
I have a tracked view named `line_items`. I'm now trying to create another tracked view derived from `line_items`, like so:

```
create or replace view envelope_activity_by_month as 
select accounts_and_months.user_id, accounts_and_months.account_id, accounts_and_months.month, case when total is null then 0 else total end as total from accounts_and_months left outer join (
select * from (
select user_id, account_id, date_trunc('month', date)::date as month, sum(amount) over w as total, row_number() over w as row_num
from line_items 
where virtual=true and account_id is not null and type='banktxn'
window w as (partition by user_id, account_id, date_trunc('month', date)::date)
order by date desc
) line_items where row_num = 1
) line_items on (accounts_and_months.account_id=line_items.account_id and accounts_and_months.month=line_items.month) 
```

This gives the error, `view/table already tracked : "line_items"`.

Is this a bug, or is there another way I should be creating my view?

**Comment by rikinsk** [comment]
@spiffytech This should not be happening ideally. We'll take a look into the actual cause.

In the meanwhile, you can uncheck the `Track this` checkbox and create the view. You can then track the view from the `Schema` page

**Comment by beerose** [comment]
I recreated `accounts_and_months` and `line_items` tables based on the view definition, and executed the SQL from the issue description. It worked fine, the view was tracked. 

I'm therefore closing this issue. Please reopen if the problem happens again.
