### ISSUE TITLE
Insert mutation with returning computed field and nested insert gives error

### ISSUE THREAD

**Issue by naveennazimudeen** [hasura/graphql-engine#3609]
I am facing an issue with insert mutation that has a relationship based nested insert together with a returning computed field. A sample insert mutation query below:
 
`insert account ( objects: {
     name: nameValue,
     nestedAddress: { data : { street : streetValue }}}){
         returning {
            accountId
            addressId
           computedField
        }
   }`

The error I get is "cannot cast type record to ... "

If the computedField is removed from the returning field, or if the computedField is retained but the relationship based nested insert is removed, the mutation works. 

I am using Hasura v1.0.0-rc.1, on Fargate, connected to Aurora Postgres 10.7

**Comment by rakeshkky** [comment]
Hi @naveennazimudeen, thank you for reporting the issue. 

The fix is being made in #3618. Please try out the preview app in https://github.com/hasura/graphql-engine/pull/3618#issuecomment-570474663 and confirm the fix.

**Comment by naveennazimudeen** [comment]
Thanks for the fixing the bug quickly, @rakeshkky. I tested with both object and array relationships and it works fine 👍
