### ISSUE TITLE
Cannot clone this repo on Windows

### ISSUE THREAD

**Issue by danhogan** [hasura/graphql-engine#3610]
On Windows 10, I cannot successfully checkout the repo.

`fatal: cannot create directory at '.circleci/postgres:12.0-alpine-postgis3': Invalid argument`
`warning: Clone succeeded, but checkout failed.`

Perhaps it's an issue with certain characters/Windows. My initial search didn't get me anywhere.

**Comment by denizkenan** [comment]
@danhogan
Now a windows user to be honest. But, have you tried to run `mkdir .circleci/postgres:12.0-alpine-postgis3` ?

if it fails, you get your answer. 

Why not use a docker container to develop hasura on?

**Comment by danhogan** [comment]
I was just trying to follow the directions. It worked after I downloaded the whole thing as a zip.

**Comment by ecthiender** [comment]
@danhogan seems like you're issue is resolved. Closing this then, feel free to reopen if you want to add anything.
