### ISSUE TITLE
history tab is broken on graphiql

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#363]
Make couple of named queries, one with query variable, click on another query in the list, component resets

**Comment by praveenweb** [comment]
This seems to have been fixed in GraphiQL in this [commit](https://github.com/graphql/graphiql/commit/1453b946abb1e57d96e82132ac7459ddfd9b02bc). We need to update our [graphiql fork](https://github.com/hasura/graphiql) to take the latest commit from GraphiQL as releases happen slowly.
@wawhal

**Comment by coco98** [comment]
Yeah. I noticed this too. Please mark as urgent/bug/quickfix and let’s
release this asap.

**Comment by karthikvt26** [comment]
This happened to me only once when tried multiple times. Need a proper way to replicate the issue. @shahidhk let me know.

**Comment by shahidhk** [comment]
1. Write and execute a named query without any variables. The query appears in History tab.
2. Now, write and execute a named query (with a different name) with variables. This query also appears on the history tab
3. Click on the first query on history tab

the entire component rests

**Comment by karthikvt26** [comment]
Closing this. Will open once there is a definitive way to reproduce the issue.
