### ISSUE TITLE
Receiving `TypeError: JSONObject cannot represent non-object value:` for mutations queries against remote schema

### ISSUE THREAD

**Issue by denizkenan** [hasura/graphql-engine#3630]
I have a working query (as of `v1.0.0-beta.9`):

```
mutation($dataID:ID ,$appID:ID, $orgID:ID, $val:JSONObject) {
    update_data(
      data: {application_id: $appID, id: $dataID,  organization_id: $orgID, value: $val},
      data_type: {name: "file_data"}) {
      _id
      _time
      _uuid
  }
```

with params:

```
{
  "dataID": 1,
  "appID": 1,
  "val": {
    "test": "object"
  }
}
```

`update_data` is a mutation provided by a remote schema based on (NestJS/Node).
`scalar JSONObject` is provided by https://www.npmjs.com/package/graphql-type-json

This query is failing with version `v1.0.0`

received error is:
`
{
  "errors": [
    {
      "message": "JSONObject cannot represent non-object value: {\"test\": \"object\"}",
      "locations": [
        {
          "line": 15,
          "column": 7
        }
      ],
      "path": [
        "update_data",
        "value"
      ],
...
`

it seems Hasura is passing a stringified object where a JSON object is needed.
Any idea how to mitigate such problem?

**Comment by 0x777** [comment]
@denizkenan Are you sure that graphql-engine is passing a stringified object to the upstream server? Can you dump the request on the remote server to see if that's the case?

**Comment by tirumaraiselvan** [comment]
@denizkenan Sending a ping to get an update on the issue.

**Comment by denizkenan** [comment]
Thank you. I will investigate this use case next week. And I will provide dump. I"m very sorry for the delay

**Comment by marionschleifer** [comment]
I'm closing this issue for now. @denizkenan feel free to re-open if you have anything to add to it 🙂

**Comment by gauravsaluja2006** [comment]
Also, it has to be an object, not an array. That's what i had to change in my case.
