### ISSUE TITLE
Using column presets with session variables (X-Hasura-User-Id)

### ISSUE THREAD

**Issue by sseppola** [hasura/graphql-engine#3637]
I've got a simple setup with a Users table. I'm testing out Hasura, and just want an authenticated user to be able to insert their own user row (if it doesn't exist), however they cannot set their own `id` column, that will be set from the session variables.

This is my config:
<img width="1157" alt="Screenshot 2020-01-05 at 20 06 14" src="https://user-images.githubusercontent.com/4065840/71784732-ff4e4000-2ff6-11ea-92ca-6a084e821562.png">

It never works, even when it's suggested in the console to use `X-Hasura-User-Id`. Any ideas why this is not working?

I've previously configured the id column as a UUID with a random generator as default, however, when I wanted to use the firebase id I changed this from uuid to text and removed the default generation of uuid in favor of using the session variable.

Edit:
Static values doesn't work either, with or without the previously mentioned column preset.

**Comment by snazzypants** [comment]
Did you include `x-hasura-role` with your corresponding role (it looks like it's `user`)?  Omitting this has bitten me several times in the past.

**Comment by sseppola** [comment]
Good call @snazzypants! I'm expecting it to execute user presets, but I'm actually admin 🤦‍♂ 
```
"https://hasura.io/jwt/claims": {
​​​  "x-hasura-allowed-roles": Array [ "admin" ]
  "x-hasura-default-role": "admin"
​​​  "x-hasura-user-id": "QT6kNjalNSbGWZu4y4UwoDx479P2"
}
```

Thanks!
