### ISSUE TITLE
Unable to Upgrade Hasura Docker Container pointed at External Database

### ISSUE THREAD

**Issue by JoshuaJarman** [hasura/graphql-engine#3646]
**PROBLEM:** Upgrading from beta10 to release1 latest gives:
```
{"path":"$","error":"unsupported version : 27","code":"not-supported"}
```

I have not for the life of me been able to figure out the proper upgrade path for hasura docker instances that connect to external databases.

we get the unsupported version error any time we recreate a docker container with a new version of hasura that points at an existing database. :-(

What is the correct way to upgrade a hasura instance (docker container pointed at an external db) like ours?  How do we fix this issue without losing data?  I cannot find any documentation and searches all turn up people with the same issue and no resolution.  If anyone can please help with info that would be greatly appreciated.

**Comment by JoshuaJarman** [comment]
switched to explicit version hasura/graphql-engine:v1.0.0 instead of latest and issue resolved.
what triggers this message/issue?  Any ideas?

**Comment by denizkenan** [comment]
this message is thrown, when hasura doesn't know what to do with your catalog version.  beta releases and rc releases are showing weird incompatibilities. I do upgrades manually by clearing catalog schemas (hdb_*) in database and reload metadata. There Hasura recreates catalog, instead of trying to update it.

**Comment by JoshuaJarman** [comment]
thank you, that is very helpful.

**Comment by 0x777** [comment]
> we get the unsupported version error any time we recreate a docker container with a new version of hasura that points at an existing database. :-(

This error message is thrown when an graphql-engine is run against a database which was initialized by a newer version. You shouldn't be seeing this message unless you are downgrading. 

> switched to explicit version hasura/graphql-engine:v1.0.0 instead of latest and issue resolved.
`latest` tag is not a good idea with docker images as docker wouldn't pull the latest version of the image (and will use an older cached image) unless asked explicitly. We recommend you to use the exact version number in your docker images.

Upgrading is as simple as changing the version number, however downgrading needs a bit of manual intervention but we are planning to fix it very soon.

**Comment by JoshuaJarman** [comment]
Ah, so this only happens on downgrades? hmmm.
Maybe latest wasn't grabbing the latest locally, because the explicit number version worked, that makes a lot of sense.  👍 

This really helped clear up this mysterious error, when one might experience this, what the cause is, and ways to resolve it.  👏

1. The unsupported version error occurs when a container is applied to a database that has already had a new hasura version applied to it. (downgrades)

2. To fix one can change the version being used to a new version.

3. If really needing to downgrade one can try removing the hdb_* tables and reimporting or reloading the metadata.

4. The hasura team plans on making this easier/cleaner to eliminate the issue and/or ?improving? the error message and documentation so that people can figure out what to do when this occurs.  sounds fantastic!

Thanks for chiming in and clearing this up

A little knowledge took this from scary mysterious breakage and appearance of fragility to relatively  simple thing to deal, once we knew what was happening and why.  Kudos.
