### ISSUE TITLE
How to connect multiple databases on a host through a single husura instance?

### ISSUE THREAD

**Issue by tianguohui** [hasura/graphql-engine#3647]
hello!
          I have multiple databases on one host. I want to connect them through a hasura instance, but I can't find a way to configure it. Can such a configuration be implemented?  Thanks
 
![image](https://user-images.githubusercontent.com/59588791/71863230-2f9cf800-3137-11ea-9a23-530d7a593144.png)

@nirvdrum @lorenzo

**Comment by tirumaraiselvan** [comment]
Closing this in lieu of https://github.com/hasura/graphql-engine/issues/821
