### ISSUE TITLE
server regression: JWK is rejected due to Cache-Control header parsing

### ISSUE THREAD

**Issue by lexi-lambda** [hasura/graphql-engine#3655]
As reported on Discord, the changes in #3446 do not always properly parse the value of the `Cache-Control` header, causing the server to fail to start. For example, the response returned by Google Cloud IAM includes a header of the shape

```
cache-control: public, max-age=18341, must-revalidate, no-transform
```

and this is rejected by `graphql-engine` on startup, causing it to exit with the following somewhat unhelpful message:

```
Failed parsing Cache-Control header from JWK response. Could not find max-age or s-maxage
```

It would be nice if we could use some existing, off-the-shelf parser to parse this information, not roll our own.

**Comment by plouh** [comment]
The problem still persists when server replies with `cache-control: no-cache` -header

**Comment by ecthiender** [comment]
@plouh thanks for reporting and sorry for the inconvenience! My bad I should have tested that case. I will try to push a fix by today.

**Comment by plouh** [comment]
No problem at all, it's been a great pleasure to use hasura. We use keycloak as our identity provider, if it helps to reproduce the issue.
