### ISSUE TITLE
Better logging/telemetry for subscriptions

### ISSUE THREAD

**Issue by jberryman** [hasura/graphql-engine#3656]
The way we collect metrics for subscriptions doesn't permit us to sample and get the information we need to debug issues like e.g. https://discordapp.com/channels/407792526867693568/631379389111599114 (from Jan 6)

https://github.com/hasura/graphql-engine/blob/master/server/src-lib/Hasura/GraphQL/Execute/LiveQuery/Poll.hs#L210

Related: https://github.com/hasura/graphql-engine/pull/3622

**Comment by hgiasac** [comment]
@jberryman I have implement more log metrics for subscription (`query_execution_time`, `response_size`) PR. I don't know if it helps this issue. 
https://github.com/hasura/graphql-engine/pull/3584

If you need to update more logs metrics, I hope the payload format shouldn't be breaking change.

**Comment by jberryman** [comment]
@0x777 does Toan's #3584 get you all the way there? We now log elapsed time for queries over websocket

**Comment by hgiasac** [comment]
@jberryman Currently the live query cycle is:

1. Execute PG/Remote schema query
2. Send message to STM Queue
3. Send data sequentially from queue to client

Currently I estimate execution time at step 1 and 2. Do you think if we need to estimate step 3 too?

**Comment by jberryman** [comment]
@hgiasac I'm in the process of rebasing/rewriting my PR for #3552 so I can take a closer look there. As part of that PR we try to record time for network IO separately to be able to distinguish a slow network from slow hasura performance, so we should probably do something similar for the live query code paths. I'll take a look and ping you for review on the PR.

My other thought is that not measuring (3) could give an inaccurate view if there are thunks in the structure that gets put on the queue.

**Comment by jberryman** [comment]
This was resolved
