### ISSUE TITLE
pg_dump and pg_restore with hasura schemas

### ISSUE THREAD

**Issue by dostalradim** [hasura/graphql-engine#3661]
Hi, I have a problem with connecting new Hasura instance (graphql-engine) to my existing database with Hasura schemas created. Is it right way how to move my database to another place? Or what is the right to accomplish this task? :) Is required to always move only my schema and run graphql-engine always again?

Thank you

**Comment by 0x777** [comment]
> Hi, I have a problem with connecting new Hasura instance (graphql-engine) to my existing database with Hasura schemas created

What are the exact steps that you followed?

>  Is it right way how to move my database to another place? 

(I'm answering based on the assumption that you want to copy an existing database which is being served by graphql-engine to a new database)

You can always pg_dump your entire database, import it into a new database and **then** start graphql-engine on the new database. This will work as expected. 

However, if you have already started graphql-engine on an empty database, you wouldn't be able to import a database dump as graphql-engine would have already created `hdb_catalog` and `hdb_views` schemas in the new database. In such cases, your `pg_dump` invocation should **exclude** both the `hdb_*` schemas and then export the metadata from the old database and import it into the new database.

**Comment by dostalradim** [comment]
Hi, thank you for your reply.

I just run this command "pg_dump -Fc --no-privileges --no-owner mydatabase" in production environment and this database is already tracked with hasura instance. After this I run "pg_restore -d mydatabase dump.bin" to test environment and create new hasura instance in another docker and put to it configuration for the restored database but new hasura failed to start because of hasura schemas existing.

So it means we have to copy only our schemas and run database objects to track again or use metadatas to accomplish this. I want to solve this becasuse our database is bigger and its tracking is not fast enough.

**Comment by dostalradim** [comment]
There is no chance to copy everything and just start new hasura graphql-engine process? I hoped that the graphql-engine doesnot have any configuration in container and is using just his schemas in PSQL. So it means that the graphq-engine knows that it is not author of schemas?

**Comment by dostalradim** [comment]
You are right, I am really sorry for this issue I did mistake with restoring and permissions.

Thank you! Have a nice day.
