### ISSUE TITLE
add skip execution steps to migrate squash help examples

### ISSUE THREAD

**Issue by webdeb** [hasura/graphql-engine#3665]
Squashed migrations are breaking the system.

Bug description: 

After squashing migrations (also already migrated ones) the system cannot apply this migration to the database, because the newly created migration includes already migrated stuff.
You basically get a bunch of "already exists" errors.. 

I think, I understand where this kind of migrations makes sense. 
It will work if you squash new migrations, which were not applied to the system yet, like migrations from a developer, to have them all in single folder in a commit, but you should't touch older migrations

One possible solution would be to put them in a single file, but keep the migration id, so you would have just a couple of files, with multiple migrations in it. maybe with a flag `--keep-ids` and without this flag just use the current behaviour of creating a fresh migration. Although it could make sense to keep-ids by default, so the above bug would't be possible, unless you provide something like `--no-ids`

Another improvement for squashing would be naming, instead of 123_squashed provide a `--name` option, to organise them semantically.

`hasura migration squash --name create-profile-api --from 123`

**Comment by webdeb** [comment]
... and include a Readme inside the generated migrations folder, I think this would provide enormous help and prevent from common mistakes

**Comment by shahidhk** [comment]
@webdeb `--name` flag already exists.

After you squash a migration, you should mark that migration as applied:

```bash
# squash all migrations from version 1572238297262 to the latest one:
hasura migrate squash --from 1572238297262

# mark the squashed one as applied
hasura migrate apply --version 1572238297262 --skip-execution
```
Will add this to the command help. Renaming the issue for that purpose.

**Comment by webdeb** [comment]
@shahidhk thanks, adding to the readme would be really helpful.

One question though, to `migrate apply --version --skip-execution` you have to be connected to the server?

**Comment by webdeb** [comment]
Because I am using the `auto-migration` docker container to apply migrations.

**Comment by shahidhk** [comment]
Yes, you need to be connected to the server to do this one-time action.

**Comment by webdeb** [comment]
@shahidhk this will not work with graphql-engine:v1.0.0.cli-migrations container. 
I would suggest to put the squashed `versions: [123, 124]` into the squashed_migration yaml.

**Comment by webdeb** [comment]
> Yes, you need to be connected to the server to do this one-time action.

human interactions should't be required to make rollouts, this is dangerous.

**Comment by webdeb** [comment]
@shahidhk / @0x777 

Guys, let me add a proposal here:

1. Remove this `squash` feature, as this is not stable and dangerous to use
2. Instead add a group feature, keep the ids for each action.

```
migrations/
  profile/
    123_add_profile_table.up.yaml
    123_add_profile_table.down.yaml
    234_seed.up.sql
    234_seed.down.sql
```

So simply do not try to put them in one file, as it is error prone as we saw. It would be enough to keep the id for each action, and just group into folders, because I think this adds the value of organising stuff, without loosing the information what was applied, and what not.

**Comment by shahidhk** [comment]
Migrations are supposed to be squashed on dev and then applied to a deployed instance. 

You're not supposed to squash migrations that are already applied to the deployed instance. Hence the squash workflow doesn't affect the rollouts.

If at all you want to clean-up a broken migrations state on an instance, follow this guide: https://blog.hasura.io/resetting-hasura-migrations/

**Comment by webdeb** [comment]
@shahidhk thank you for the link to the blog post, this is helpful!

I was hoping to get a semantical feature based squash-workflow.
But if I understood correctly this is not the purpose of `squash`.

The purpose of squash is making one file from many and removing unnecessary commands, which happened during development.

Please correct me, if thats wrong. Thank you

**Comment by shahidhk** [comment]
> The purpose of squash is making one file from many and removing unnecessary commands, which happened during development.

:+1:
