### ISSUE TITLE
Store hasura metadata in a different database

### ISSUE THREAD

**Issue by dtheodor** [hasura/graphql-engine#3670]
Is it possible to have the hasura metadata (hdb_catalog, hdb_views) stored in a different database? It's my understanding that they need to reside in the same database with the actual business data. It may be desirable to decouple the database that hasura has read-only access, with the database that hasura writes to. An example where this could make sense is when business data have different availability guarantees and backup schedules that the hasura metadata, they may need to run on separate hardware, etc.

**Comment by mblhaunted** [comment]
This should be more than an "idea" - this seems like an anti-pattern in your product.

Example -- dumping/importing databases in multiple directions through say dev,stage,prod isn't fun. 

For this reason we have to drop the tool. Engineering that process ourselves isn't worth it when you could simply configure your engine to use it's own DB.

**Comment by tirumaraiselvan** [comment]
@mblhaunted For dev/stage/prod migrations, we encourage you to use any of the hasura migrations workflows described here: https://hasura.io/docs/1.0/graphql/manual/migrations/index.html

The basic idea is  that you can track the sql migrations (either using hasura or through any of your existing tooling) and generate a corresponding hasura metadata file. This is enough for you to reproduce hasura setup in other environments (you need not import/export databases).

Let us know if you have any questions regarding this.

**Comment by tirumaraiselvan** [comment]
Yes, v1.4 will do exactly this. You can specify the database url using `HASURA_GRAPHQL_METADATA_DATABASE_URL`. 

I am closing this issue (for admin purposes :) ) as this is the next planned release.
