### ISSUE TITLE
docs: improve docs for "metadata reload" for databases migrations and a separate hasurauser

### ISSUE THREAD

**Issue by erikhSSI** [hasura/graphql-engine#3671]
Is this the right place to report this?  It relates to docs for "reload" which I think was added here?
https://github.com/hasura/graphql-engine/pull/3264

A Very Important Thing is missing in the docs
-------------
specifically at 
https://docs.hasura.io/1.0/graphql/manual/migrations/manage-metadata.html

For someone who is managing their database schema with Rails migrations...

After doing the migration (especially one that adds a table) be sure to also run:
```
GRANT ALL ON ALL TABLES IN SCHEMA public TO hasurauser; 
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO hasurauser;
```
(per https://docs.hasura.io/1.0/graphql/manual/deployment/postgres-permissions.html )

otherwise the new table you just added in Rails will not show in hasura after doing a 'reload metadata' in the dashboard.  And if you do not do the "ON ALL SEQUENCES" one, it will fail/error when inserting.

(That was me a minute ago!)

**Comment by rikinsk** [comment]
@erikhSSI The permissions mentioned are necessary for Hasura to work with a database (and hence are necessary for most actions and not just the Reload metadata functionality explicitly). Hence they are mentioned as notes in our getting started workflows. 

Just for our understanding, could you share your experience in some more detail. Were you trying to hit Reload metadata to set up Hasura for the first time or was your intent something else? Your thought process might help us improving the docs better.

**Comment by erikhSSI** [comment]
We manage migrations for our postgres database used within HGE via a separate Rails installation. (And Rails uses a different postgres user than hasurauser.)

So whenever one does a rails migration that ADDS a new postgres table (as one adds new functionality to an app under development), then one needs to re-run:

```
GRANT ALL ON ALL TABLES IN SCHEMA public TO hasurauser; 
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO hasurauser;
```

on one's postgres installation.  Otherwise that table does not have the proper permissions when you pull it into HGE using reload metadata (easy to test -- one gets error messages within the HGE console if you try doing anything with that new table like add a record if you haven't yet re-run the 2 GRANT ALL statements (to cover the newly added table).

IOW, it should be mentioned at 
https://docs.hasura.io/1.0/graphql/manual/migrations/manage-metadata.html
because one needs to do it after every new TABLE CREATE (using a different user than hasurauser)  and the corresponding HGE "reload metadata", not just the first time during "getting started".

**Comment by rikinsk** [comment]
Right, understood! This is indeed a problem and an interesting one. Thanks for reporting this. 

Though granting permissions on every metadata reload would solve this issue, it seems like quite an inconvenience. 

We'll see if there is a better experience possible and get back to you. Or else we'll definitely add a note in the docs.

**Comment by 0x777** [comment]
@erikhSSI 
> Otherwise that table does not have the proper permissions when you pull it into HGE using reload metadata

This is possible with default privileges: https://www.postgresql.org/docs/current/sql-alterdefaultprivileges.html. The idea is that you configure the 'default privileges' that are given to a table/sequence created by railsuser. Something like this:

```sql
railsuser> ALTER DEFAULT PRIVILEGES IN SCHEMA schema_name GRANT ALL ON ALL TABLES TO hasurauser;
```

**Comment by erikh60** [comment]
Thanks @0x777,
Q: how would you alter the block of SQL "Here’s a sample SQL block that you can run..." at the postgres permissions doc:
https://hasura.io/docs/1.0/graphql/manual/deployment/postgres-permissions.html#postgres-permissions 
to use your `ALTER DEFAULT PRIVILEGES` approach?
