### ISSUE TITLE
Q/docs:  best practices for handling metadata.json file with git

### ISSUE THREAD

**Issue by erikhSSI** [hasura/graphql-engine#3678]
My scenario is
--------
1. Using hasura 1.0.0
2. The postgres is originally part of a rails app that we still use as an admin dashboard for the project and for doing our db migrations
3. Our rails code is in a git/github repo
4. I am adding our hasura metadata.json to our repository for tracking -- to go along with the migrations and the schema.rb

My question is
-----------
Is there any reason not to use a JSON PRETTIFY routine on the metadata.json file before putting it into git?  (so that doing diffs will return a useful result. right now in hasura v1.0.0 the metadata file is all 1 line)
 Will the metadata.json file load back into hasura OK after being made pretty / prettified?  If not, I will keep a separate pretty version.

And... can the metadata.json file that is exported by hasura be made prettified by default?

Thanks!

**Comment by shahidhk** [comment]
@erikhSSI You can use any JSON prettification tools to prettify the output. It should load back fine as long as it is a valid JSON document. Feel free to open a feature request to make the default export from console prettified.

You can also use the Hasura CLI to export metadata in YAML format. 

- [Install the CLI](https://docs.hasura.io/1.0/graphql/manual/hasura-cli/install-hasura-cli.html#install-hasura-cli)
- Create a project: `hasura init`
- Export metadata: `hasura metadata export`
- Apply metadata elsewhere: `hasura metadata apply`

**Comment by rikinsk** [comment]
Created https://github.com/hasura/graphql-engine/issues/3690 to prettify metadata.json by default

**Comment by marionschleifer** [comment]
Closing this, since https://github.com/hasura/graphql-engine/issues/3690 was implemented.
