### ISSUE TITLE
support jsonb boolean operators

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#369]
we need to support the following operators `@>`, `<@`, `?`, `?|`, `?&` in the where clause for jsonb columns. 

```
@> | _contains
<@ | _contained_in
?  | _has_key
?| | _has_keys_any
?& | _has_keys_all

```

**Comment by brucx** [comment]
considering add `->`, `->>`, `#>`, `#>>` operators at the same time?

**Comment by 0x777** [comment]
@brucx 
This is how I expect the first set of operators to be used:
```graphql
query {
  articles (where: {tags: {_contains: "latest"}}}) {
    id
    title
    tags
  }
}
```
Can you provide an example with `->`, `->>` ...?
