### ISSUE TITLE
Remote relationship with prisma: ExpectedTypeButGot

### ISSUE THREAD

**Issue by Tbaut** [hasura/graphql-engine#3695]
we're using remote joint with a graphQL server from Prisma.

Adding the remote schema is working well, adding a remote relationship fails with:
```
"path": "$.args[0].args",
"error": "ExpectedTypeButGot (TypeNamed (Nullability {unNullability = True}) (NamedType {unNamedType = Name {unName = "ID"}})) (TypeNamed (Nullability {unNullability = True}) (NamedType {unNamedType = Name {unName = "Int"}})) :| []",
"code": "remote-schema-error"
```

Example:
Demo prisma endpoint: https://test-c8a6790725.herokuapp.com/test-prisma/dev
Demo hasura with super simple schema: https://github.com/Tbaut/hasura-prisma-test.git
```bash
git clone https://github.com/Tbaut/hasura-prisma-test.git
cd hasura-prisma-test
docker-compose up
# ^ this needs to be done twice sometimes... ¯\_(ツ)_/¯
```
Hasura console will be on http://localhost:8888

Then apply the migration
```
cd hasura-migration
hasura-dev migrate apply
```

From the console try to add a remote relationship :
![image](https://user-images.githubusercontent.com/33178835/72279213-f03e4200-3635-11ea-83e7-33de950b7794.png)

**Comment by tirumaraiselvan** [comment]
Sorry for the bad error messages, this will be fixed before the release.

The error (though cryptic) suggests that you are trying to join a `ID` type with an `Int` type. There is an open issue related to this: https://github.com/hasura/graphql-engine/issues/3578 , which potentially allows marking any "unique" column to have type `ID`.

But the current workaround is probably going to be to use an `Int` column in your remote schemas as the join column.

**Comment by Tbaut** [comment]
Thanks Tiru working well with Int! indeed. 
In case that helps anyone, it's defined this way on Prisma:
```bash
id: Int! @id(strategy: SEQUENCE) @sequence(name: "MY_SEQUENCE" initialValue:1 allocationSize:1)
```

**Comment by Tbaut** [comment]
pretty sure this is now solved, similar as https://github.com/hasura/graphql-engine/issues/5133
