### ISSUE TITLE
event trigger gives incorrect bigint value in payload

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#3697]
From https://stackoverflow.com/questions/59708004/hasura-event-trigger-with-incorrect-bigint-value

> The row's id is a big int, e.g. "50755254975729665" but is being passed in the event as a modified version of that id "50755254975729660".

Maybe we need to type-cast such "special" columns while creating the event trigger? 

This kind of type-casting was also considered for #2036

**Comment by rikinsk** [comment]
Might make sense to just make it respect the existing `--stringify-numeric-types` flag

**Comment by pcmaffey** [comment]
Related: looks like the console also does not respect the `--stringify-numeric-types` flag. ie when manually inserting a foreign key, will modify the bigint and error with foreign key violations.

**Comment by rikinsk** [comment]
@pcmaffey This is being tracked in #3667

**Comment by iCrawl** [comment]
I don't want to unnecessarily bump this issue, but is there any time resolution on this?

I am by far not proficient enough in Haskell to even attempt a PR, but this is a big blocker in 2 applications of mine which would mean I would have to convert all of my columns back to strings as I get incorrect values from the hooks.

**Comment by wzulfikar** [comment]
Hello, any update on this? 

I've set `HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES=true` in my instance. Bigint fields in hasura console are correctly represented in string but in events, they are still numeric (which makes the data inaccurate because of json limitation).

Maybe @marionschleifer has an info on this?

**Comment by ecthiender** [comment]
Fixed via d8d4626ba3c4dcac494977d5d391346914fcb5a8
