### ISSUE TITLE
version check bugs on cli

### ISSUE THREAD

**Issue by fred8617** [hasura/graphql-engine#3706]
![image](https://user-images.githubusercontent.com/35049517/72394824-837c9200-3772-11ea-9f1e-deafb70bb85e.png)
![image](https://user-images.githubusercontent.com/35049517/72394834-8e372700-3772-11ea-9491-84ccda7ef0ad.png)

**Comment by shahidhk** [comment]
@fred8617 This is a bug in the CLI on how versions are compared. We missed a pre-release nuance while building the constraint for comparision.

Please install the CLI again to get the latest version: https://docs.hasura.io/1.0/graphql/manual/hasura-cli/install-hasura-cli.html

**Comment by lukaspili** [comment]
Installing the CLI from scratch does not solve the issue.

**Comment by heliocaruccio** [comment]
https://www.npmjs.com/package/hasura-cli is out of date

**Comment by shahidhk** [comment]
We've identified an issue with `v1.1.0-beta.1` release adn it is recommended that you downgrade to `v1.0.0` - instructions here: https://github.com/hasura/graphql-engine/issues/3710#issuecomment-574973318

**Comment by jjangga0214** [comment]
@heliocaruccio Hi! I'll publish the package soon :)
