### ISSUE TITLE
Metadata becomes out of sync on multiple instances

### ISSUE THREAD

**Issue by Gerharddc** [hasura/graphql-engine#3720]
When running multiple instances of Hasura (like in a Kubernetes cluster), changing the Hasura metadata (like adding a table) causes the metadata of all other instances to become outdated. In a case where the instances are load balanced this for instances causes a situation where right after creating a new table, the Hasura console starts to complain that the table does not exist even though it is just a case of another instance not knowing about the change in metadata. I guess a solution to this might be to use the LISTEN/NOTIFY mechanism in Postgres to listen for metadata changes on all Hasura instances in order to avoid this.

**Comment by shahidhk** [comment]
@Gerharddc Hasura instances already use LISTEN/NOTIFY to sync the metadata. Can you tell us your Hasura and Postgres version?

**Comment by tirumaraiselvan** [comment]
@Gerharddc Are you on Google Cloud?

**Comment by Gerharddc** [comment]
@shahidhk I am using Hasura 1.0 with Postgres 11.6 (plus TimescaleDB).

@tirumaraiselvan No, I am running a local K8s cluster using Microk8s

**Comment by tirumaraiselvan** [comment]
This has been seen in GKE because of quotas (https://cloud.google.com/vpc/docs/quota)

> VPC networks automatically drop idle TCP connections after ten minutes. You cannot change this limit, but you can use TCP keepalives to prevent connections to instances from becoming idle. See the Compute Engine tips and troubleshooting page for details.

Is it possible that your k8s network is also somehow closing idle connections?

**Comment by Gerharddc** [comment]
Having now found out that Hasura already supports this, I have done some more investigation and found that I only get this problem when connecting Hasura to my DB through Pgpool and not when connecting it directly. So I guess its then a case of Pgpool not handling LISTEN/NOTIFY correctly?

I haven't checked out `keepalives_idle` yet but I guess that won't help if this is indeed a Pgpool issue?

**Comment by tirumaraiselvan** [comment]
I am not sure, but you can try :)

Also, Hasura does pg connection pooling itself. So, you may choose to connect Hasura directly to Postgres.

**Comment by Gerharddc** [comment]
I have now tested `keepalives_idle` and it makes now difference.

I have tried to test LISTEN/NOTIFY through Pgpool by connecting a few psql terminal sessions to Pgpool and they all actually seem to receive notifications just fine so its now looking like there is something special going on only when Hasura tries to LISTEN/NOTIFY through Pgpool. I will try to write my own little application using LISTEN/NOTIFY to see if it has issues as well.

@tirumaraiselvan The reason I want to use Pgpool is so that I can direct most read traffic to read replicas of my DB. As far as I could determine, Hasura does not support this natively?

**Comment by tirumaraiselvan** [comment]
@Gerharddc It would be great if you could explain your pgpool setup so that others can build their own read/write replicate setup with Hasura.

**Comment by Gerharddc** [comment]
As luck would have it, it seems there was actually just a bug in Pgpool 4.1 with LISTEN/NOTIFY causing this strange behaviour https://www.pgpool.net/mantisbt/view.php?id=573 . Using 4.0 solved my problems. After some reading I also found out that Pgpool does actually direct all LISTEN/NOTIFY traffic to the master anyway...

**Comment by msannikov** [comment]
Hey @Gerharddc, have you eventually written a blog post about pgpool + hasura setup?
