### ISSUE TITLE
Support for 3D geometries

### ISSUE THREAD

**Issue by sarendsen** [hasura/graphql-engine#3721]
2D geometries are supported. How about 3d geometries? ST_3DDWithin etc

**Comment by Ugoline** [comment]
Nice

**Comment by NicoleAnn926** [comment]
Huh?? I'm a middle aged woman, struggling to understand this new "language". I'll take the time to read the Git Handbook, but I don't know if programming is "my thing." I'm in no position to be of service to anyone at this point since I kinda need some help here. I'm clueless!

**Comment by meldb1976** [comment]
I'm just trying to get the stalker ware my boyfriend put on my phone

**Comment by Ugoline** [comment]
Same as I,  am clueless about this whole thing

**Comment by sarendsen** [comment]
Is there a way to move this forward? do you guys allow merge requests?

**Comment by rikinsk** [comment]
@sarendsen Yes we do accept merge requests in case you would like to take a stab at this

**Comment by abooij** [comment]
As a clarification to this, we currently support certain geometric conditions in `where` clauses. The relevant code is in `server/src-lib/Hasura/GraphQL/Schema/BoolExp.hs`. See for `comparisonExps`. For instance, `st_d_within` is encoded internally as an `ASTDWithinGeom` AST entry. So supporting 3D geometries would involve the following steps:

1. Extend the `OpExpG` data type defined in `server/src-lib/Hasura/RQL/Types/BoolExp.hs`.
2. Having added this code, the compiler will point you to where you will need to add code to translate these new AST entries to our internal representation of SQL. You can follow the example of `st_d_within`.
3. Having enabled the internal representation of 3D geometry conditions in the previous two steps, one can now extend the code in `server/src-lib/Hasura/GraphQL/Schema/BoolExp.hs` to expose new GraphQL schema that makes use of this.
4. Add new tests to `server/tests-py/` that set up a table that makes use of 3D geometry, that inserts some data into it, and tests that the newly introduced where clauses indeed select the right data.

**Comment by sassela** [comment]
Addressed in https://github.com/hasura/graphql-engine/commit/4cb224afd84671ec88f14b0a93e012bee34880bd
