### ISSUE TITLE
Using Hasura alongside an express app

### ISSUE THREAD

**Issue by erikshestopal** [hasura/graphql-engine#3741]
(I apologize in advance for the silly question but I couldn't any resources online to answer my question.

Given that I already have an express app running on `http://localhost:8000` and supporting endpoints such as `/v1/users`, `/v1/posts`, etc, how can I mount the Hasura engine on the same port (`8000`) at the `/v1/graphql` endpoint? 

Is this even possible?

**Comment by hgiasac** [comment]
Hi @erikshestopal 

You can use API Gateway or reversed proxy such as nginx for proxy routing. For example, with nginx config (not test, you will need to read nginx documentation)

```nginx
server {
    listen       8000;
    ...
    location /v1/graphql {
        proxy_pass http://127.0.0.1:8080; # graphql engine 
    }
    
    location / {
        proxy_pass http://127.0.0.1:8181; # express app, fallback to default
    }
}
```
Note: `nginx` will listen at port 8000, and redirect to different services (HGE, express) with different ports.

**Comment by erikshestopal** [comment]
Thank you.
