### ISSUE TITLE
FATAL  [Apollo module] errorHandler should be a path to an exported error handler config.      

### ISSUE THREAD

**Issue by donPuerto** [hasura/graphql-engine#3743]
Weird error
![image](https://user-images.githubusercontent.com/9329005/72683600-c09aa880-3b13-11ea-9e00-ee6242bb6f1d.png)

**Comment by donPuerto** [comment]
![image](https://user-images.githubusercontent.com/9329005/72684386-3f471400-3b1b-11ea-87ba-f65faf42f792.png)

**Comment by praveenweb** [comment]
@donPuerto - This happens particularly on running the app with yarn and not npm. But either way, the `errorHandler` should point to a config file according to the docs in latest versions. The #3765 PR should address this.
