### ISSUE TITLE
Add select input to enum fields

### ISSUE THREAD

**Issue by almassapargali** [hasura/graphql-engine#3748]
Hello, we're using Hasura console as a simple admin interface, and it's great so far. We have a small enhancement we'd like to see though.

We have a enum table called `business_entity_types`, which have limited set of values:
<img width="633" alt="Screen Shot 2020-01-21 at 14 36 25" src="https://user-images.githubusercontent.com/1816725/72788803-b89a5000-3c5c-11ea-9ba1-26f202e92608.png">

And we have a `partners` table, which contains text field called `business_entity` with foreign key to `business_entity_types`, so it can take only one of those values:
<img width="564" alt="Screen Shot 2020-01-21 at 14 36 42" src="https://user-images.githubusercontent.com/1816725/72788926-e97a8500-3c5c-11ea-9d3f-081ac250bde2.png">

Now, when modifying partners through console, can we have a select as input type for `business_entity` field, so managers don't have to type in `business_entity_types` values:
<img width="822" alt="Screen Shot 2020-01-21 at 14 37 33" src="https://user-images.githubusercontent.com/1816725/72789002-06af5380-3c5d-11ea-9e71-51913653d2fe.png">

**Comment by rikinsk** [comment]
Seems to be the same as https://github.com/hasura/graphql-engine/issues/2296.

Cloisng this issue in favour of that. Please feel free to reopen if you have something else to add.

**Comment by beerose** [comment]
I'm reopening since this is slightly different and much easier to implement than #2296 so it will probably be handled in different PR.

**Comment by beerose** [comment]
Solved in this PR: https://github.com/hasura/graphql-engine/pull/3810
