### ISSUE TITLE
Row in event trigger does not present in DB

### ISSUE THREAD

**Issue by tafelito** [hasura/graphql-engine#3764]
I have an event trigger that runs on insert. When my web-hook gets called, the data that I get from the event, even tho it has an id, when I query the data with the received id, nothing comes back 

This is what I get from the event trigger

```
req.body {
  id: '2ac20b04-34d7-4c43-82e8-5820c6d7e383',
  table: { schema: 'public', name: 'orders' },
  trigger: { name: 'process_order' },
  event: {
    session_variables: {
      'x-hasura-role': 'user',
      'x-hasura-user-id': 'b7e20ab9-b690-4f69-9d7c-60e5c5aa7b34'
    },
    op: 'INSERT',
    data: { old: null, new: [Object] }
  },
  delivery_info: { current_retry: 0, max_retries: 0 },
  created_at: '2020-01-23T13:20:26.916303Z'
}
```

where `new` is 

```
  {
    ...
    id: 'db363c91-7cf3-4ebb-9d3f-2622fe95dd89',
    ...
  }
```

then I call `orders_by_pk` with id `db363c91-7cf3-4ebb-9d3f-2622fe95dd89` from the WH and I get `null`

To query hasura from the WH I use the admin secret in the header, so it shouldn't be a permission issue

Hasura v1.0.0

**Comment by nason** [comment]
I am running into the same issue on hasura v1.3.3. My handler is configured to retry a few times, and It gets `null` back each time when I get one of the "ghost inserts". I also don't see the inserted record when I try to find it myself, so I'm very confused about whats going on here.

This is very intermittent and most of our insert events are real and can be handled normally...

@tafelito do you have any tips for figuring this out?
