### ISSUE TITLE
Allow filtering by computed fields

### ISSUE THREAD

**Issue by mikyoengine** [hasura/graphql-engine#3772]
If you have a computed field such as `full_name`, it would be very useful to be able to filter by this value. E.g.

```graphql
{
  users(where: { full_name: { _eq: "John Smith"}) {
  ...UserDetails
  }
}
```

**Comment by MatthiasGrandl** [comment]
Yes exactly the same usecase for me. I output a datatable module and I want the user to be able to filter and sort by any value inside the datatable. Right now I have to disable those features for any computed field, which is really unintuitive.

**Comment by barmaley443-sfdev** [comment]
+1
now receiving "field "computed" not found in type: 'table_order_by'" when trying to sort by computed field.
any chance to get this feature?

**Comment by esseswann** [comment]
Interestingly on surface there are no visible limitations because this is working
```
SELECT public.calculate_something(entity) AS status FROM entity
WHERE public.calculate_something(entity) = 'something'
```

**Comment by Kosai106** [comment]
Just to add in on this, it could be useful to use a computed field as primary key
Example: I generate a `slug` for my `projects` and I want to get them with a query like:

```gql
query {
  projects_by_pk(slug: "example") {
    id
    name
  }
}
```

Or

```gql
query {
  projects(where: {slug: { _eq: "example"}}) {
    id
    name
  }
}
```

**Comment by MatthiasGrandl** [comment]
Also related, it would be neat if we could select computed columns for permission checks.

**Comment by maxcan** [comment]
@marionschleifer @coco98 any chance of getting this into 1.3?

**Comment by mkalayci35** [comment]
+1

**Comment by MarcelloTheArcane** [comment]
> Just to add in on this, it could be useful to use a computed field as primary key
> Example: I generate a `slug` for my `projects` and I want to get them with a query like:
> 
> ```graphql
> query {
>   projects_by_pk(slug: "example") {
>     id
>     name
>   }
> }
> ```
> 
> Or
> 
> ```graphql
> query {
>   projects(where: {slug: { _eq: "example"}}) {
>     id
>     name
>   }
> }
> ```

@Kosai106  Does this actually work?

**Comment by Kosai106** [comment]
@MarcelloTheArcane No, it's a request.

**Comment by TheMrZZ** [comment]
It looks fairly simple to implement, even though I might be mistaken.

Currently, my workaround is to create a SQL View, with all my table's field, and the computed field itself.

That's ugly, and prevents you from updating the whole view (you need to switch between two GraphQL root fields), but hey at least it works in queries.

If you need it to work in mutations, you need to create a new view with your computed field, add a relationship between your root table and the view, and filter from there. It requires a JOIN, which could hurt performance on an often queried table, and will be ugly, but it will work.

Since we're already at v1.3.0-betav4, I wouldn't expect the Hasura's team to ship this feature in v1.3.0.

**Comment by brittanyroddy** [comment]
This would be a great feature!!

**Comment by gengue** [comment]
This is a must-have for my team

**Comment by marcfalk** [comment]
+1 is much needed to have this!

**Comment by crieggalder** [comment]
+1 - very important for our team.

**Comment by alisonvalente** [comment]
+1

**Comment by coloradocolby** [comment]
Adding my voice to this. Would really love to see this added!

**Comment by sawankumarbundelkhandi** [comment]
This issue is the 4th most upvoted feature. Do you have any update on when this will be available? Please help us.

**Comment by alexmarqs** [comment]
+1

**Comment by cardosojc** [comment]
+1

**Comment by Victormeriqui** [comment]
+1

**Comment by IsaacLeeWebDev** [comment]
+1

**Comment by alukos** [comment]
+1

**Comment by christophediprima** [comment]
+1

**Comment by ChristopherTadaweb** [comment]
+1

**Comment by NathanDeveloping** [comment]
+1

**Comment by Kosai106** [comment]
I just want to chime in here to say that leaving `+1` comments do not help. If you want to show support, give a 👍 to the initial post instead.

**Comment by treystout** [comment]
any news on this for 2021? Would help get rid of a lot of weird 1-off views and other functions.

**Comment by willyxiao** [comment]
+1

**Comment by amnaveenriaz** [comment]
@tirumaraiselvan Any update on this? Would be really helpful to reduce extra views and functions.

**Comment by KirillSuhodolov** [comment]
+ 1 for adding

**Comment by lukeomalley** [comment]
+1 would love to see this feature

**Comment by 0x777** [comment]
This is available from v2.0.3. Further improvements will be landing in the next release or two:
1. Using computed fields in permission boolean expressions
2. Using computed fields in order_by expressions

**Comment by dariocravero** [comment]
@0x777 we've been trying the new computed fields filter feature and it's amazing! One thing I've noticed though is that if the computed field contains an extra argument, eg:
```
create or replace function comms.threads_updated_ago(thread comms.threads, ago text default '7 days')
returns boolean language sql stable as $$
  select thread.updated_at > (now() - ago::interval);
$$;
```

Then the computed field doesn't show up in the `where` filters (or in `order_by` for that sake).

Is that something you'd consider supporting? It'll be a great workaround for dynamic date operators for example like that one above.

Thanks!

**Comment by esseswann** [comment]
@dariocravero Supporting this would raise a question on how would you pass this extra argument within `where` query

**Comment by dariocravero** [comment]
@esseswann that's a fair question. For clarity, this is the syntax I was thinking about:
```
query {
  comms_threads(where: {
    updated_ago(args: { ago: "1 day" }): { _eq: true }
  }) {
    id
  }
}
```

Ideally, `"1 day"` could also be a var `$interval: text` too.

If I'm getting that right, in the definitions [ColumnExp](https://hasura.io/docs/latest/graphql/core/api-reference/syntax-defs.html#columnexp) takes a PGColumn which is a String. Couldn't easily find how fields support the arguments but I guess it'd be something similar? What do you think?

**Comment by esseswann** [comment]
@dariocravero Input Objects can't have an argument as per GraphQL [spec](https://spec.graphql.org/June2018/#sec-Input-Object-Values)
