### ISSUE TITLE
[Feature] Rest Support, Add Sofa, or Provide docs for how to make an integration with the Sofa

### ISSUE THREAD

**Issue by fastengineer** [hasura/graphql-engine#3775]
Sofa is super, awesome GraphQL to REST gateway. Everybody have customers using rest, they never even heard of GraphQL. Sofa solves the problem with one line code. See example below.
https://medium.com/the-guild/sofa-the-best-way-to-rest-is-graphql-d9da6e8e7693

And feature 2: We have the opposite use case of this topic. We have old rest apis. We don't want reimplement them. So we need to rest to graphql gateway. Without extra coding for CRUD actions. Example solution below.
https://github.com/apollographql/apollo-link-rest

**Comment by marionschleifer** [comment]
@fastengineer we have a blogpost on how create a remote schema to wrap a REST API with Hasura: https://blog.hasura.io/create-a-remote-schema-to-wrap-a-rest-api-hasura/.

Also, there is this tool: https://github.com/IBM/openapi-to-graphql. It allows you to get a GraphQL schema which you then can add as a remote schema.

Our recommended approach to solve this is the upcoming actions feature. You can get the preview here: https://github.com/hasura/preview-actions. Let us know if you have any questions in setting it up 🙂 cc @tirumaraiselvan

**Comment by sobrinho** [comment]
@fastengineer can this be closed?

**Comment by fastengineer** [comment]
@sobrinho Closed. Actions provides this feature.
