### ISSUE TITLE
v1.1.0-beta.2 not starting?  

### ISSUE THREAD

**Issue by mwarger** [hasura/graphql-engine#3776]
Possibly related to https://github.com/hasura/graphql-engine/issues/3734

I updated my docker image to the beta, and now it appears the server won't start.  It seems like it just kind of stops doing anything.  Any advice is appreciated.  The logs are below.

Relatedly, it would be helpful if there were downgrade instructions for the latest catalog versions: (https://docs.hasura.io/1.0/graphql/manual/deployment/downgrading.html#step-2-downgrade-hasura-catalogue-version).  I tried to downgrade back to just 1.0.0 and got some errors about incorrect metadata even after updated the catalog version back to 28.  How can I downgrade this version correctly?

Thank you.

logs: 
```
{"type":"startup","timestamp":"2020-01-25T02:15:13.567+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":"anonymous","stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":false,"port":8080}}}
{"type":"startup","timestamp":"2020-01-25T02:15:13.567+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:@postgres:5432/hasura"}}}
{"type":"startup","timestamp":"2020-01-25T02:15:13.567+0000","level":"info","detail":{"kind":"db_migrate","info":"Already at the latest catalog version (30); nothing to do."}}
{"type":"startup","timestamp":"2020-01-25T02:15:13.567+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 26","instance_id":"16410387-8d22-4101-bb0d-819878917820","message":"listener thread started"}}}
{"type":"startup","timestamp":"2020-01-25T02:15:13.567+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 27","instance_id":"16410387-8d22-4101-bb0d-819878917820","message":"processor thread started"}}}
{"type":"startup","timestamp":"2020-01-25T02:15:13.567+0000","level":"info","detail":{"kind":"event_triggers","info":"preparing data"}}
{"type":"startup","timestamp":"2020-01-25T02:15:13.567+0000","level":"info","detail":{"kind":"event_triggers","info":"starting workers"}}
{"type":"startup","timestamp":"2020-01-25T02:15:13.567+0000","level":"info","detail":{"kind":"telemetry","info":"Help us improve Hasura! The graphql-engine server collects anonymized usage stats which allows us to keep improving Hasura at warp speed. To read more or opt-out, visit https://docs.hasura.io/1.0/graphql/manual/guides/telemetry.html"}}
{"type":"startup","timestamp":"2020-01-25T02:15:13.567+0000","level":"info","detail":{"kind":"server","info":{"time_taken":0.6163331,"message":"starting API server"}}}
```

**Comment by lexi-lambda** [comment]
It’s admittedly not terribly well-worded, but your server seems to be starting just fine. The “starting API server” message means the setup has finished successfully, and it’s now starting to listen for connections. That message is the last message logged as part of a successful startup sequence. Maybe we should another one that says “started API server” or something like that?

Anyway, if you’re having trouble connecting to the instance, I’m not immediately sure what the trouble is, but those log messages don’t indicate anything is amiss, so it’d be helpful if you could provide more information!

**Comment by mwarger** [comment]
Awesome, thank you.  My app is indeed running.  I went back and just looked I thought I had previously seen the logs say something like "Started console at address 192.168.1.1:PORT" or similar.  I didn't see that, so I thought it had stopped short.

I was trying to access the wrong port number, so I didn't see the console as I expected.

I guess it's a good sign i need to take a break.  Thanks again.
