### ISSUE TITLE
Make Console UI realtime by default

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#378]
Currently, the console UI is not realtime, so when two or more people work on it at the same time, it's hard to detect changes without refreshing browser.

One typical example, is when to detect changes in new tables creation/edition (which leads to schema changes)

We should (or Should we) make the console UI realtime by default ?

**Comment by 0x777** [comment]
> when two or more people work on it at the same time, it's hard to detect changes without refreshing browser.

This particular issue is now resolved. console will prompt you to reload the metadata if it detects that a change has been made outside of the current console.
