### ISSUE TITLE
Cannot GRANT SELECT on schemas "information_schema" & "pg_catalog"  in GCP CloudSQL Postgres 11

### ISSUE THREAD

**Issue by DanieltheYogi** [hasura/graphql-engine#3783]
Similar/related to:
#1677 
#3460

It does not seem possible to grant SELECT permissions on information_schema.* tables nor pg_catalog.* tables in GCP's CloudSQL's managed PostreSQL server. Users don't actually have superuser privileges and these tables seem to be protected against changing their permissions.  

The documentation on [this page in your documentation](https://docs.hasura.io/1.0/graphql/manual/deployment/postgres-permissions.html) is therefore not accurate. Can you please provide a workaround / fix?

**Comment by 0x777** [comment]
The workaround suggested [here](https://github.com/hasura/graphql-engine/issues/1677#issuecomment-468273423) didn't work?

**Comment by seifip** [comment]
Got the same problem on GCP/Postgres 12 with Hasura Cloud
