### ISSUE TITLE
Event trigger migrations not working in v1.1.0-beta.2

### ISSUE THREAD

**Issue by nowylie** [hasura/graphql-engine#3784]
When applying migrations to a fresh database using server and cli version `v1.1.0-beta.2` the postgres triggers for the event trigger functionality do not appear to be created.

Here is a screenshot of the hasura console showing the event trigger after applying migrations:
![Screenshot from 2020-01-28 17-03-28](https://user-images.githubusercontent.com/5195341/73242225-780c7a80-41f8-11ea-9614-39f12d3088fa.png)

and a screenshot showing the triggers for the same table from pgAdmin:
![Screenshot from 2020-01-28 17-04-07](https://user-images.githubusercontent.com/5195341/73242270-a2f6ce80-41f8-11ea-96c5-b10a8b3d04ef.png)

**Comment by flybayer** [comment]
I think I'm seeing the same thing, but it happens a bit differently for me.

I upgrade to `v1.1.0-beta.2` with an existing DB including insert triggers. Somehow my insert triggers have been lost from the DB. I'm able to fix them by removing the insert trigger and then adding it back.

**Comment by tirumaraiselvan** [comment]
Thanks for reporting.

This happens when the migrations have `run_sql` statements.

**Comment by flybayer** [comment]
This happened for me again. All insert event triggers were lost while the server was running. I had a few failed graphql mutations around this time, but no DB crashes or other DB errors.

Is mine issue the same thing or should I open a new issue?

**Comment by tirumaraiselvan** [comment]
It's mostly the same (or atleast the same class of bug). 

If you are using ET extensively, I'd advice to downgrade #3822 .

**Comment by 0x777** [comment]
Closed with https://github.com/hasura/graphql-engine/commit/7fb6577924535ce3bf86bb7da24a0c9aa5604618
