### ISSUE TITLE
Why don't you provide a debian or ubuntu package?

### ISSUE THREAD

**Issue by maarekj** [hasura/graphql-engine#3786]
Hi, I love project hasura.

But my server architect doesn't want to use docker (for various internal reasons).

Is there a way to install hasura on a debian/ubuntu server without using docker ?

Thank's you.

**Comment by tirumaraiselvan** [comment]
Hi @maarekj 

Packaging binaries for different OSs is non-trivial and requires high maintenance and something we are not currently keen on doing.

Although, if you would be interested in a special arrangement pls get in touch with me at `tiru@hasura.io` and we can see what we can do.

**Comment by tirumaraiselvan** [comment]
Closing this in favour of: https://github.com/hasura/graphql-engine/issues/4837
