### ISSUE TITLE
Server builds the GraphQL schema before performing dependency resolution, causing startup failures

### ISSUE THREAD

**Issue by lexi-lambda** [hasura/graphql-engine#3791]
As reported by @rikinsk [on slack](https://hasurahq.slack.com/archives/CKMR0FAKE/p1580216046009900), the metadata build process has a minor bug that can cause inconsistent metadata to cause startup failures. The new build process performs schema integrity checking in two phases:

  1. First, it validates the internal consistency of metadata objects and collects information about their dependencies.

  2. Second, it performs *dependency resolution*, which ensures that all metadata objects’ dependencies actually exist. If any of them don’t, it marks them inconsistent and drops them from the schema.

Currently, we call `mkGCtxMap` to build the GraphQL schema *before* doing dependency resolution, but this is a Bad Idea, since we haven’t pruned dangling dependents yet. This can trigger errors in the schema build process, and those errors are fatal, which prevents the server from even starting up.

The original example given involved an enum table that was modified to include an invalid value, causing the table to be marked inconsistent. Since tables that define a relationship on that enum table via foreign key were not pruned, the GraphQL schema build process failed.

**Comment by tirumaraiselvan** [comment]
@lexi-lambda Will this issue also be related to  https://github.com/hasura/graphql-engine/issues/3729#issuecomment-576907256

**Comment by lexi-lambda** [comment]
@tirumaraiselvan I think you’re right that it’s somewhat related. I’m not sure what the right behavior should be for remote schemas, though, so I probably won’t resolve that issue as part of this fix.
