### ISSUE TITLE
reload_metadata API should take optional argument to reload Remote Schemas

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#3792]
The `reload_metadata` API does not reload Remote Schemas as it is a costly step (and might be unnecessary). For reloading remote schemas, there is the explicit `reload_remote_schema` API.

But there might be a need to `reload_metadata` while also reloading Remote Schemas. Hence, an optional argument could be provided to `reload_metadata` like `reload_remote_schemas: true` to achieve this.

Side note: While writing down this issue, I noticed a small inconsistency in the behaviour (before v1.1):

1. Suppose you reload_metadata or reload_remote_schema in one Hasura instance, this changed the schema cache and triggered a postgres event to refresh other instances.
2. The other instances build schema cache from scratch and hence have up-to-date schema. Whereas the originator instance may not have up-to-date remote schema or up-to-date postgres schema (as it only did a partial reload).

@lexi-lambda  Is this issue moot after v1.1 because of incremental schema cache building?

**Comment by lexi-lambda** [comment]
> Is this issue moot after v1.1 because of incremental schema cache building?

Definitely still relevant! `reload_metadata` still doesn’t refresh remote schemas by default (unless their metadata changed). Admittedly the caching is much less sophisticated right now than it ought to be and ends up reloading things more than it ought to, but fixing that will only make this even more relevant.

**Comment by tirumaraiselvan** [comment]
@lexi-lambda I was more concerned about the consistency of schema across all instances.

As opposed to the behaviour mentioned in the Side Note in OP, I guess the schema would atleast be consistent across all schemas?

**Comment by lexi-lambda** [comment]
Ah, no, that issue is still relevant as well. The logic around schema syncing isn’t any cleverer even with the incremental metadata changes.
