### ISSUE TITLE
Remove mutations from the schema

### ISSUE THREAD

**Issue by mitar** [hasura/graphql-engine#3799]
I would like to simply remove all mutations from the schema so that they are not even shown in the GraphQL. I know that I can disable them through permissions so nobody can call them, but I would like to simply remove them altogether. Is this possible?

**Comment by 0x777** [comment]
A query or mutation is only exposed if it is explicitly enabled by allowing permissions for a role (only the default `admin` role has access to all the queries and mutations).

**Comment by mitar** [comment]
So the schema introspection is dynamic given the current role? Is this documented somewhere?

**Comment by rikinsk** [comment]
Not in detail but there is a note [here](https://docs.hasura.io/1.0/graphql/manual/auth/authorization/roles-variables.html#roles)

**Comment by mitar** [comment]
Awesome. Thanks.
