### ISSUE TITLE
[event-triggers] Hasura not triggering webhook

### ISSUE THREAD

**Issue by raitucarp** [hasura/graphql-engine#3803]
When I  change the webhook URL in event triggers. Hasura does not call this webhook anymore. I have to delete the event trigger and create a new one with the same configuration except for its URL.

I am curious about what's happening there? Because I see no logs regarding this issue.

**Comment by tirumaraiselvan** [comment]
@raitucarp Which version of Hasura are you running?

**Comment by raitucarp** [comment]
I've tried v1.0.0, v1.1.0-beta.1 and v1.1.0-beta.2. I don't know-how behind the scene of postgre notify works. But it seems, after updating the URL, PostgreSQL stop send the notify. Correct me if I'm wrong

**Comment by raitucarp** [comment]
My case was, I've tried to restart Hasura and Postgres after changing the URL.

**Comment by tirumaraiselvan** [comment]
@raitucarp I have repro'ed this problem in `v1.1.0-beta*` . This should not happen in `v1.0.0` though.

**Comment by raitucarp** [comment]
Ok thank you for your confirmation, maybe I forgot the version. Because right now I already used v.1.1.0-beta. I can't go back though. I hope I can help you guys.

**Comment by tirumaraiselvan** [comment]
@raitucarp We have identified the issue and will roll out a fix ASAP. One fix is to recreate the event trigger. But, I will admit that's not the best fix because of a related bug : https://github.com/hasura/graphql-engine/issues/3784

If you need to downgrade, pls contact me on Discord. My handle is `@Tiru`

**Comment by raitucarp** [comment]
Hi tiru, hows progress? Should I downgrade now? because every docker compose up, I need to recreate the trigger.

**Comment by tirumaraiselvan** [comment]
@raitucarp The fix will be out in the next beta release (few days), but yes pls downgrade if you can. Instructions are here: https://github.com/hasura/graphql-engine/issues/3822

**Comment by raitucarp** [comment]
OK thank you very much. I wish I can submit PR but I didn't read the source code much. Thank you again
