### ISSUE TITLE
Tests for `/explain` API

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#3806]
We need to add tests for the `/explain` API.

Docs for explain API: https://hasura.io/docs/1.0/graphql/manual/api-reference/explain.html

The point of this issue is that we currently have a test suite, in the `server/tests-py/` directory, for the backend, which tests input-output behavior for a variety of queries including many GraphQL queries. However, the `v1/graphql/explain` API, which is used to run the `Analyze` feature in the console, is not tested at the moment. This can be fixed by writing a handful of tests that call the Explain API, and compare received output with expected output. The above documentation can be used for some inspiration for sample queries which should certainly work (i.e. should be tested).

**Comment by vishnugt** [comment]
I will start working on this and send a PR to add test cases for this

**Comment by jmakhack** [comment]
@marionschleifer, I'd like work on this issue. Can you assign it to me?

**Comment by marionschleifer** [comment]
@jmakhack as explained in [our Hacktoberfest blogpost](https://hasura.io/blog/hasura-joins-hacktoberfest-3rd-year-in-a-row/), we don't assign issues. However, it doesn't seem that anyone else is working on this, so feel free to take it up and link a PR to this issue 🙂

**Comment by jmakhack** [comment]
I've been hitting many issues with cabal no being able to resolve dependencies for this project so just want to update that I am currently not actively looking into this issue and it is up for grabs for anyone else to take on.

**Comment by harshxtanwar** [comment]
@Stefmore02 can I get assigned to this issue ? I'd love to work on it.

**Comment by marionschleifer** [comment]
@harshxtanwar feel free to pick this up. We don't assign issues. The PR that is submitted first will also be the one to be reviewed first 🙂 so far, nobody has raised a PR on this.

**Comment by chaiwattsw** [comment]
Do you have test that I can reference to write explain api ?

**Comment by marionschleifer** [comment]
@chaiwattsw unfortunately not. Writing tests for the Explain API is another [Hacktoberfest issue](https://github.com/hasura/graphql-engine/issues/3806).

**Comment by JoelleNdiriraMusangie** [comment]
Bonjour, Hello, does any body do the test or I can do it? thank you.

**Comment by JoelleNdiriraMusangie** [comment]
Good morning,
I started the tests. I installed all the requirements from the requierements.txt file. But dependence sqlalchemy
gives me an error despite updating the version.  
here is an excerpt of the error , thanks :


================================================== test teardown duration top =================================================== 
total          name         num avg            min
       0:00:00  grand total   4        0:00:00        0:00:00
==================================================== short test summary info ==================================================== 
ERROR test_explain_api.py::test_successful_query - sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:pos...
ERROR test_explain_api.py::test_invalid_query - sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres 
ERROR test_explain_api.py::test_missing_operation_name - sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialec...
ERROR test_explain_api.py::test_unauthorized_access - sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:...
======================================================= 4 errors in 2.06s =======================================================

**Comment by JoelleNdiriraMusangie** [comment]
Good morning @marionschleifer ,

 I started implementing the tests with pytest.
 I installed all the requirements from the requierements.txt file. But dependence sqlalchemy
gives me an error despite updating the version even installing sqlacodegen. Do you have any idea of ​​the source of these errors that i have?
here is an excerpt of the error , thank you.

================================================== test teardown duration top ===================================================
total name num avg min
0:00:00 grand total 4 0:00:00 0:00:00
==================================================== short test summary info ====================================================
ERROR test_explain_api.py::test_successful_query - sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:pos...
ERROR test_explain_api.py::test_invalid_query - sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
ERROR test_explain_api.py::test_missing_operation_name - sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialec...
ERROR test_explain_api.py::test_unauthorized_access - sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:...
======================================================= 4 errors in 2.06s =======================================================

**Comment by marionschleifer** [comment]
Thank you for your efforts @JoelleNdiriraMusangie. This issue is actually not relevant anymore since tests for the `/explain` API have already been added 🙂

**Comment by JoelleNdiriraMusangie** [comment]
Okay, thank you for closing this issue in this case because otherwise many will have had the pleasure of working there like me :)
