### ISSUE TITLE
returning relationship field after insert error(v1.1.0.beta2)

### ISSUE THREAD

**Issue by hengsovandara** [hasura/graphql-engine#3807]
While upgrading to to latest version( I mean v1.1.0.beta2 ), which cause error when I have the query insert and returning the relationship field( which I didn't provide in values ) and expected as null, but got error that `No operator matches the given name and argument type(s). You might need to add explicit type casts.`

**Comment by tirumaraiselvan** [comment]
Dup of https://github.com/hasura/graphql-engine/issues/3754 ?

**Comment by hengsovandara** [comment]
@tirumaraiselvan yeah exactly, sorry because I cannot find the issue last morning. So I could close the issue.
