### ISSUE TITLE
Inserting value into Enum table and reloading metadata takes server down

### ISSUE THREAD

**Issue by Motoxpro** [hasura/graphql-engine#3820]
I have an enum table "discipline" with a "name" column. If I insert "Community/Casual" and click "Reload enum values" it takes the server down. This happened once and It took me a while to find out through the logs that the server couldn't find table "discipline". Seemed like it got deleted?

I restored a backup on my cloud-sql instance and did the same, added "Community/Casual" but instead reloaded metadata from the settings page and it went through.

I tried to insert another row and again do "Reload enum values" from the table and again the server went down.

This is on v1.0.0. Not sure if this has been fixed on 1.10

**Comment by Motoxpro** [comment]
`jsonPayload: {
  detail: {
   info: {
    error: {
     info: {
      code: "postgres-error"       
      error: "connection error"       
      internal: "consuming input failed from postgres connection"       
      path: "$"       
     }
     type: "query_error"      
    }
   }
   thread_type: "listener"    
  }
  level: "error"   
  timestamp: "2020-02-02T21:44:27.538+0000"   
  type: "schema-sync-thread"   
 }`

`{"error":"table not found: \"discipline\"","code":"unexpected","path":"$"}`

**Comment by tirumaraiselvan** [comment]
@lexi-lambda Is this dup of https://github.com/hasura/graphql-engine/issues/3759 ?

**Comment by Motoxpro** [comment]
Just a little more insight. I had changed disciplineName to be the enum table and discipline to the a many to many intermediary table.

I added "Community/Casual" to the disciplineName table. No errors. Went to add it to discipline and reload metadata and got these errors


disciplines | array_relation | relationship of table "disciplineName" | table "disciplineName" does not exist
-- | -- | -- | --
disciplineName | object_relation | relationship of table "discipline" | table "disciplineName" does not exist
disciplineName | table | disciplineName | the table "disciplineName" cannot be used as an enum because the value "Community/Casual" is not a valid GraphQL enum value name

So I was wrong about what was causing it. Does it seem like if you use an invalid enum value as a foreign key it deletes the table?

**Comment by Motoxpro** [comment]
Again, after this, the DB goes into an inconsistent state and I have to reload a backup.

I realize I can't use "/" for an enum value now also, but hopefully this process helps solve this issue

**Comment by 0x777** [comment]
@Motoxpro Can you try out the build it https://github.com/hasura/graphql-engine/pull/3798 to check if this issue is fixed?

**Comment by Motoxpro** [comment]
Sure! I'm using kubernetes to deploy. Has this been merged into 1.1.0-beta.2?

**Comment by lexi-lambda** [comment]
No, but it has been merged to master and will be in the next beta release.

**Comment by 0x777** [comment]
@Motoxpro This should be fixed in `v1.1.0-beta.3`, please try it out and let us know if the issue still persists.

**Comment by Motoxpro** [comment]
@0x777 All fixed! Thank you!
