### ISSUE TITLE
Invocation log search always returns first row

### ISSUE THREAD

**Issue by rjansen91** [hasura/graphql-engine#3826]
First row of invocation log is always returned, regardless of search term.
Using v1.0.0, version 28

![event-search](https://user-images.githubusercontent.com/43191611/73676196-cf7f7000-4668-11ea-8cb3-e5b2d4dc8b7b.gif)

**Comment by wawhal** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/aaab6d3eb6e1ff902c567b5d6e9502b55af3dde7.
