### ISSUE TITLE
Don't include 'range types' as a column type in console

### ISSUE THREAD

**Issue by dukedave** [hasura/graphql-engine#3831]
I propose that **RANGE TYPES** should not be selectable in the **Add a new column** select for `column_type` until #1082 is complete.

Without any support for the non-trivial [range functions](https://www.postgresql.org/docs/12/functions-range.html), I don't believe there is any reason to prefer them over two separate (`upper-bound` and `lower-bound`) columns of the corresponding type.

---

On seeing **RANGE TYPES**  as an option, I naively added a column with `tstzrange`, and then had to reimplement later using individual `upper` and `lower` columns when I discovered that `<@` (_element is contained by_) is not only unsupported, but is impossible (AFAICT) to implement using current GraphQL interface.

**Comment by rikinsk** [comment]
I would still leave the options there even though Hasura doesnt have the best support for them yet. Some users use the console as a DB management tool as well and it wouldnt be fair to limit that. Hasura is built to work with any database and shouldn't have a say in how users model their PG schema.
