### ISSUE TITLE
JWK parsing error after update to v1.1.0-beta.2

### ISSUE THREAD

**Issue by MatthiasGrandl** [hasura/graphql-engine#3834]
`Failed parsing Cache-Control header from JWK response. Could not find max-age or s-maxage`

This error wasn't present before. Updated from `v1.0.0`. I am using native Keycloak without the third-party hasura connector. 

My JWK response headers look like this:

```
cache-control: no-cache
content-length: 1470
content-type: application/json
date: Wed, 05 Feb 2020 09:12:05 GMT
referrer-policy: no-referrer-when-downgrade
status: 200
strict-transport-security: max-age=31536000;
x-content-type-options: nosniff
X-DNS-Prefetch-Control: off
x-xss-protection: 1; mode=block
```

**Comment by ecthiender** [comment]
Thanks for reporting! This has already been reported (https://github.com/hasura/graphql-engine/issues/3655#issuecomment-575100575) and fixed. It should be out in the next release.

**Comment by ecthiender** [comment]
@MatthiasGrandl if possible you can also try out the docker image from the [this PR's](https://github.com/hasura/graphql-engine/pull/3779) build and report any issues.

**Comment by MatthiasGrandl** [comment]
Oh, didn't find that. Thanks for the answer.
