### ISSUE TITLE
Does the upsert mutation make an  event trigger call

### ISSUE THREAD

**Issue by polRk** [hasura/graphql-engine#3836]
I want to add a row to contact_tag if not exists. And i want to call an event trigger ( insert mutation ) Under all conditions.

<img width="231" alt="Снимок экрана 2020-02-05 в 2 21 29 PM" src="https://user-images.githubusercontent.com/39828645/73837578-cf2ad480-4822-11ea-828a-0cd283820037.png">

```
mutation insertContactTag($input: [contact_tag_insert_input!]!) {
    insert_contact_tag(objects: $input, on_conflict: {constraint: contact_tag_pkey, update_columns: [tag_id, contact_id]}) {
        affected_rows
    }
}
```
Will my mutation trigger an insert event trigger ?

Upd:
```
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.insert_contact_tag.args.objects",
        "code": "constraint-violation"
      },
      "message": "Uniqueness violation. duplicate key value violates unique constraint \"contact_tag_user_id_contact_id_tag_id_key\""
    }
  ]
}
```

Upd2: change **contact_tag_pkey** by **contact_tag_user_id_contact_id_tag_id_key**
```
{
  "data": {
    "insert_contact_tag": {
      "affected_rows": 1
    }
  }
}
```
But no trigger event call
<img width="1273" alt="Снимок экрана 2020-02-05 в 5 06 37 PM" src="https://user-images.githubusercontent.com/39828645/73848814-e2956a00-4839-11ea-89a2-da958123d8ed.png">

Maybe should add **Upsert** trigger ?
<img width="401" alt="Снимок экрана 2020-02-05 в 5 07 34 PM" src="https://user-images.githubusercontent.com/39828645/73848888-0953a080-483a-11ea-94d9-d768e5aae12e.png">

**Comment by 0x777** [comment]
@polRk When a conflict occurs, Postgres treats the operation as an 'update' on the table, so you'll also need to listen to 'update' events.

**Comment by polRk** [comment]
Thank you, 0x777!
I need an insert trigger. Can i use 2 mutations in 1 request ? Delete and insert mutations ?

**Comment by marionschleifer** [comment]
@polRk Yes, you can do two mutations in one request. They will run as a transaction. Please find the corresponding docs [here](https://docs.hasura.io/1.0/graphql/manual/mutations/multiple-mutations.html).

**Comment by polRk** [comment]
@marionschleifer Can I be sure that they are executed in spelling order?

**Comment by marionschleifer** [comment]
@polRk yes, you can be sure 🙂
