### ISSUE TITLE
Row select permissions using column values

### ISSUE THREAD

**Issue by seltsamonkel** [hasura/graphql-engine#3841]
Hi!

I would like to construct a row select permission rule comparing the values of 2 columns.

For example, say there are column A and B with integer type, and I want to allow users to insert/select/update the rows where the value of A equals to the value of B.

I've read the docs several times, but it seems like this is not possible at the moment?

**Comment by tirumaraiselvan** [comment]
If it's the same table, then you can use the `_ceq` operator : https://docs.hasura.io/1.0/graphql/manual/api-reference/graphql-api/mutation.html#operator

**Comment by marionschleifer** [comment]
@seltsamonkel in case you're referring to other tables, we have an open issue here: https://github.com/hasura/graphql-engine/issues/3459. Please upvote if this is what you're interested in 🙂  I'm closing this issue.

**Comment by seltsamonkel** [comment]
Thank you all for your help :)
