### ISSUE TITLE
How to add permission to computed field?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [hasura/graphql-engine#3842]
### SQL
```
CREATE FUNCTION user_default_warehouse_id(user_row "user") RETURNS integer
    STABLE
    LANGUAGE SQL
AS
$$
SELECT oc.warehouse_id
FROM user_operation_center
         LEFT JOIN operation_center oc ON user_operation_center.operation_center_id = oc.id
WHERE user_id = user_row.id
  AND is_default = TRUE
$$;
```
### Meatadata
```
{
    "type":"add_computed_field",
    "args":{
        "table":{
            "name":"user",
            "schema":"public"
        },
        "name":"defaultWarehouseId",
        "definition":{
            "function":{
                "name":"user_default_warehouse_id",
                "schema":"public"
            },
            "table_argument":"user_row"
        }
    }
}
```

Got error: field "defaultWarehouseId" not found in type: 'user'.

it looks like only admin role can access computed field.

![image](https://user-images.githubusercontent.com/33362998/73903074-8f351300-485d-11ea-8978-a47c3a5252d8.png)

But I can't find default_warehouse_id column under user permission fields

**Comment by marionschleifer** [comment]
@xiaoyu-tamu there seems to be a naming issue. `defaultWarehouseId` seems to be the name of the computed field, and then `default_warehouse_id` is expected under the select permission fields but it's not there. 

Can you fix the naming and confirm that that was the issue?

**Comment by tobiastornros** [comment]
Same problem here. Can´t find the computed field column in the permission fields and when fetching as user I have no access to the fields in graphql.

**Comment by rikinsk** [comment]
Just wanted to add a note that support for computed fields in the console is expected to be released in v1.1.0. In the meanwhile one can use the [beta versions of v1.1.0](https://github.com/hasura/graphql-engine/releases) to manage computed fields via console or use the [permissions metadata API](https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/permission.html#create-select-permission) directly to add permissions for computed fields

**Comment by tobiastornros** [comment]
Ok! Thanks @rikinsk 

Should I provide the the computed_field name in the "columns" value?

**Comment by rikinsk** [comment]
@tobiastornros You need to pass it under the "computed_fields" key as mentioned [here](https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/permission.html#selectpermission)
