### ISSUE TITLE
Question: Is there a way to track number of views of a record?

### ISSUE THREAD

**Issue by tibotiber** [hasura/graphql-engine#3843]
Hi,

I was wondering if there is any way to track the number of "views" of a record. Like every time a specific query is executed and returns a record, we would increment the number of views of that record.

SQL views and functions cannot update the table, triggers cannot be set for a select query, presets are not expressive enough to "+1" a column, and permissions do not support math operators under `$ceq` (to restrict to +1 update only e.g.).

So far, my workaround is to post a mutation that increment the "view" column and return the data that I want, but the endpoint is neither restricted to `_inc` operations, nor to a value of 1 :\ .

Any idea?

**Comment by tirumaraiselvan** [comment]
As described [here](https://wiki.postgresql.org/wiki/Audit_trigger#Limitation:_Cannot_audit_SELECT):

`The only way to audit SELECT in PostgreSQL is via the system logs`

You have to make some workarounds, similar to what you are doing already. You can perhaps use our upcoming `Actions` feature to derive from the `update_table` field to create your own API, that only has the `where` clause and internally does a `_inc: 1`.

**Comment by tibotiber** [comment]
Thanks for reverting. Any good place to read about the upcoming actions feature?

**Comment by tirumaraiselvan** [comment]
It will be out in few days but you can check the preview docs here: https://deploy-preview-3252--hasura-docs.netlify.com/graphql/manual/actions/getting-started.html

**Comment by tibotiber** [comment]
Thanks for the link. 

Actions look really cool, it’s kind of adaptors to non graphql services (as long as they respect the req/res interface) if I get it right? That’s a super powerful addition to remote schemas 🥳.

Do you see a possibility to add SQL (or native?) Actions at some point? It would be similar in I/O definition but instead of giving the url of a function I’d give the SQL request I want to execute. It would be an escape path to the fact that SQL functions cannot update the tables. The point being to keep things blazing fast as long as I’m just touch the db. Maybe that’s already possible and I missed it?

Cheers!

**Comment by tirumaraiselvan** [comment]
@tibotiber Yes! Soon after the first release, you will also have the ability to create action handlers which are postgres functions.

**Comment by tibotiber** [comment]
Would that include mutable functions?

That’s really cool. Super impressed with Hasura already and the stuff you have in the works is amazing. You guys are on fire!

**Comment by tirumaraiselvan** [comment]
@tibotiber Yes.

**Comment by tibotiber** [comment]
Neat! Thanks for the details @tirumaraiselvan :). Looking forward to this feature. Feel free to close this.

**Comment by tirumaraiselvan** [comment]
Thank you for your kind words @tibotiber .
