### ISSUE TITLE
accessing session variables in function via computed field 

### ISSUE THREAD

**Issue by sincraianul** [hasura/graphql-engine#3846]
It would be really cool to be able to define a function like

```
CREATE OR REPLACE FUNCTION article_liked(article_row article, hasura_session json)
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1
    FROM liked_article A
    WHERE A.user_id = hasura_session ->> 'x-hasura-user-id' AND A.article_id = article_row.id
  );
$$ LANGUAGE sql STABLE;
```

and use it via a computed field without any args.

I know that in order to get `hasura_session` injected the function needs to be tracked, but tracked functions only support `SETOF` return types.

I can dive in a try to do a PR if there's interest in this kind of functionality.

**Comment by coco98** [comment]
@rikinsk @marionschleifer there are lots of powerful use-cases here exactly like the one @sincraianul mentioned. We should add this to our docs as well and document this as a `XByCurrentViewer` (`likedByCurrentViewer`) feature that folks need to add.

@sincraianul would absolutely love a PR for this feature. @rakeshkky should be able to help and guide you :)

**Comment by sincraianul** [comment]
@coco98 Wow, thanks for the really positive response! I'll get started right away.

**Comment by reinvanimschoot** [comment]
Also really looking forward to this implementation! It would be extremely powerful! Good luck!

**Comment by reinvanimschoot** [comment]
Is there any update on this? Or any workaround currently?

**Comment by ivan333m** [comment]
We love this feature very much.
This will be extremely useful with regards to data privacy (GDPR, PPI), e.g. We will be able to decrypt privacy information for appropriate user.
It would be nice if you add this feature to the next release.

Thanks

**Comment by 0x62** [comment]
Any update on this? Really needed

**Comment by marcfalk** [comment]
Looking forward to this as well!
