### ISSUE TITLE
Bugs: Lots of UI and UX inconvenience

### ISSUE THREAD

**Issue by polRk** [hasura/graphql-engine#3849]
After using hasura actively in manual mode (about 100 hours), I highlighted things that annoyed me very much and would soon force me to remove hasura. Explain, indicate the place in the code where I can add the saving of collapsed columns and the number of lines in the pagination by default (10 just infuriates). With any action, the state of collapsed columns is reset. With any action, the pagination state is reset.

**Comment by polRk** [comment]
PS. I want the block to occupy the entire available width
<img width="1154" alt="Снимок экрана 2020-02-07 в 11 53 05 AM" src="https://user-images.githubusercontent.com/39828645/74014773-6a958400-49a0-11ea-819e-194ecac8e141.png">

<img width="1149" alt="Снимок экрана 2020-02-07 в 11 54 08 AM" src="https://user-images.githubusercontent.com/39828645/74014848-8ef16080-49a0-11ea-8cc9-8289baf13824.png">

**Comment by polRk** [comment]
PS. 

Often when editing json, the field is not marked as changed and the changes are not applied. I have to always check radio button

**Comment by polRk** [comment]
Explain, please,  the place in the code where I can fix some frontend ui, ux errors

**Comment by ecthiender** [comment]
@polRk Thanks for reporting these! Appreciate the great feedback! We are already working on improving the UI and UX, and we will make sure to incorporate these changes as well.

I see there are 2 UI/UX issues reported:
1. Code text editors and input boxes do not take the full width available, clipping the text and forcing the user to scroll horizontally.
2. Often when editing json, the field is not marked as changed and the changes are not applied. One has to always check radio button.

I think it makes sense to create separate issues for these.

cc @rikinsk  @beerose - should we incorporate this feedback in the current work ?

**Comment by beerose** [comment]
Another issues that @polRk mentioned are:
* State of collapsed columns is reset — I am currently working on this (https://github.com/hasura/graphql-engine/pull/3753)
* The pagination state is reset — I think we can add it to the scope of the PR I mentioned above. 

For the two issues from @ecthiender comment — yes, we can do two separate issues, but I don't think there's a need for that since it should be rather small fixes.

**Comment by polRk** [comment]
You need to make the collapse button larger, I often click on the table sorting, instead of collapse column

**Comment by polRk** [comment]
And left sidebar should be collapsible

**Comment by beerose** [comment]
This is where you can change the default pagination: https://github.com/hasura/graphql-engine/blob/master/console/src/components/Services/Data/DataState.js#L3

**Comment by beerose** [comment]
Hey @polRk, we fixed the issues that you reported, and we made a bunch of additional improvements in the meantime. I'm therefore closing this issue. Please reopen if you want to add something.
