### ISSUE TITLE
cli migrations beta version not installing

### ISSUE THREAD

**Issue by d4n13lbc** [hasura/graphql-engine#3856]
When trying to install hasura cli beta version v1.1.0.beta.3 for testing, default v1.0.0 version is being installed. 

This is the command I'm using
```
sudo curl -L https://github.com/hasura/graphql-engine/raw/v1.1.0-beta.3/cli/get.sh | bash
```

**Comment by shahidhk** [comment]
Please download directly from release page, install script only downloads stable versions.

https://github.com/hasura/graphql-engine/releases/tag/v1.1.0-beta.3

**Comment by d4n13lbc** [comment]
Understood, thanks for the quick response
