### ISSUE TITLE
Computed fields as default

### ISSUE THREAD

**Issue by tcaraccia** [hasura/graphql-engine#3857]
Hi all, i'm really enjoying development over hasura so far.
I would love to use a computed field as a default value for a column when doing an insert mutation.
Basicaly what my computed field does in querying is calculate a price based on two other fields.
Is that possible or should I use a postgres function ?

Keep it up! Great technology

**Comment by marionschleifer** [comment]
Hi @tcaraccia 👋 currently, this is not possible. Computed fields can be used only when querying the table. You can create an insert trigger to fill up the default value in a column. Or you can make use of the Postgres 12 feature called generated columns (https://www.postgresql.org/docs/12/ddl-generated-columns.html). I hope this helps 🙂

**Comment by tobiastornros** [comment]
Can´t you just return your default value in the postgres function if fields x and y is null

**Comment by 0x777** [comment]
@tcaraccia Postgres triggers are also good fit for this use case: https://dba.stackexchange.com/questions/21897/set-a-columns-default-value-to-the-concatenation-of-two-other-columns-values

**Comment by sobrinho** [comment]
Yep, seems like that generated columns, default value as a function call or even an action in a more complex scenario would do the job perfectly.

@tcaraccia @0x777 that can be closed, I think.
