### ISSUE TITLE
Browser Response Differs from Dashboard GraphiQl Response

### ISSUE THREAD

**Issue by carlmeriksen** [hasura/graphql-engine#3858]
timeStart is being swapped with the previous entries DateTimeEnd attribute.
[qraphiqlResponse.txt](https://github.com/hasura/graphql-engine/files/4180102/qraphiqlResponse.txt)
[graphiqlVariables.txt](https://github.com/hasura/graphql-engine/files/4180114/graphiqlVariables.txt)
[graphiqlQuery.txt](https://github.com/hasura/graphql-engine/files/4180115/graphiqlQuery.txt)
[browserResponse.txt](https://github.com/hasura/graphql-engine/files/4180116/browserResponse.txt)

**Comment by carlmeriksen** [comment]
![image](https://user-images.githubusercontent.com/50176018/74141721-21436f80-4c00-11ea-8aa0-07cc462041f9.png)
When I look at the browser response copied from the network tab it appears correct. However in the image above the browser appears to be interpreting the data incorrectly. This occurs in both Chrome and Mozilla. This is how I am querying and logging:

`client
      .query({
        query: SHIFT_QUERY,
        variables: {
          id: 186,
          exclId: 1,
          date: "2020-02-04T00:00:00+00:00"
        }
      })
      .then(res => {
        console.log(res);
...
`

**Comment by tirumaraiselvan** [comment]
Hi @carlmeriksen 

I did a JSON diff of the two outputs above:

`diff <(jq -S . qraphiqlResponse.txt) <(jq -S . browserResponse.txt) > diff.output`

The only difference seems to be the inclusion of `__typename` field in the browser response.

Could you verify that you are comparing identical JSON paths in both results?

**Comment by carlmeriksen** [comment]
After running a bunch of scenarios managed to find that somehow one of the React components was causing the response to be changed. I have no idea how this happens as that component is only rendered after the response is received. Removing the component has solved the problem.
