### ISSUE TITLE
Enum is not reloaded

### ISSUE THREAD

**Issue by polRk** [hasura/graphql-engine#3862]
I have an error when i tried to insert data in table
```
Insert failed!
Internal Server Error
```

Server logs
```
Spock Error while handling ["v1","query"]: expected one of the values "viber_bot", "telegram_bot", 
"schedule", "statement", "system", "delay" for type "_action_type", given "tool"
```

Database
<img width="366" alt="Снимок экрана 2020-02-11 в 1 56 35 PM" src="https://user-images.githubusercontent.com/39828645/74230879-53bf9c00-4cd6-11ea-939b-96fbbef551d3.png">

Query 
<img width="1088" alt="Снимок экрана 2020-02-11 в 1 57 30 PM" src="https://user-images.githubusercontent.com/39828645/74230995-91bcc000-4cd6-11ea-9e18-1e4e2508ae97.png">

Database public._action_type
<img width="285" alt="Снимок экрана 2020-02-11 в 2 02 10 PM" src="https://user-images.githubusercontent.com/39828645/74231224-29221300-4cd7-11ea-9a67-c6181ad38710.png">

hdb_catalog
INSERT INTO hdb_catalog.hdb_table (table_schema, table_name, configuration, is_system_defined, is_enum) VALUES ('public', '_action_type', '{"custom_root_fields": {}, "custom_column_names": {}}', false, true);

hdb_table_info_agg
```
INSERT INTO hdb_catalog.hdb_table_info_agg (table_schema, table_name, info) VALUES ('public', '_action_type', '{"oid": 17135, "columns": [{"name": "comment", "type": "text", "position": 2, "description": null, "is_nullable": true}, {"name": "value", "type": "text", "position": 1, "description": null, "is_nullable": false}], "view_info": null, "description": null, "primary_key": {"columns": ["value"], "constraint": {"oid": 18003, "name": "_action_type_pkey"}}, "foreign_keys": [], "unique_constraints": [{"oid": 18005, "name": "_action_type_value_key"}]}');
```

**Comment by polRk** [comment]
Reload enum button (Set table as enum) solved the problem

**Comment by rocketraman** [comment]
I had the same issue and Reload enum button did not solve it... however, restarting Hasura did.
