### ISSUE TITLE
Adding new field to table programmatically loses permissions

### ISSUE THREAD

**Issue by ElixirMike** [hasura/graphql-engine#3870]
I believe this is a known issue, but am hoping a fix and/or product feature can be added to resolve.
I am use permissions via Hasura and programmatically adding tables, fields, etc. When I first create a table, I assign all proper permissions and specify * for the fields. This works fine.

However, when I add new field to table, by default, it's not included in permissions, but it should be, as I specified * for all fields initially. 
The only current work around is that I then need to send all delete permissions for select, insert, update,delete and then re-send create permissions for select, insert, update, delete.

This is a heavy transaction which can be quite slow. Ultimately, I just want to be able to add a field and have it toggled to selected, as all other fields are. This makes the transaction much faster and removes the need for the constant deleting/inserting of permissions.

Is this somehow possible to do today? Would we be able to tweak the code so new fields that are added are by default included in the permissions that are already defined?

**Comment by rikinsk** [comment]
Dup of #2104

**Comment by tirumaraiselvan** [comment]
Closing as dupe

**Comment by phxgbl** [comment]
@ElixirMike I would like to know how you added new field (column) programatically. I have a requirement where when a user creates a table, column 'TENANT_ID' should be added from the backend. Can u give insight on that?
