### ISSUE TITLE
Input field for permissions does not remove whitespace

### ISSUE THREAD

**Issue by reinvanimschoot** [hasura/graphql-engine#3871]
I noticed today when I was adding a 'user' role and I accidentally added it as 'user ' in the permission table that this was reflected in my exported metadata and subsequently resulted in no queries/mutations showing up.

Luckily @coco98 was able to help me debug and we came to this conclusion! Thanks again for the help!

**Comment by coco98** [comment]
@rikinsk I think the form validation (when a user enters the name of the role) doesn't strip/trim spaces. `user  ` should not be allowed `user` should be.
