### ISSUE TITLE
docs: reload and reset metadata from the console

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#3874]
Currently, docs only explain the API and the CLI.

We should also put screenshots of the console so it's easier to show.

**Comment by marionschleifer** [comment]
Reloading metadata is covered [here](https://hasura.io/docs/1.0/graphql/core/migrations/manage-metadata.html#reloading-hasura-metadata). What is missing is adding a section on how to reset metadata.
