### ISSUE TITLE
Optional conditions for nested relationships improperly execute in search queries

### ISSUE THREAD

**Issue by nikolaykhodov** [hasura/graphql-engine#3878]
Hi folks, I think Hasura improperly or undocumentedly applies optional conditions for relationship fields. Let me provide an example. Say we have two types Pet and Owner:
```
type owner {
  id
  name
}
```

and

```
type pet {
  id
  name
  ownerId

  # pet.ownerId === owner.id / might be NULL
  owner { 
    id
    name
  }
}
```

We have a search screen with two optional filters (`$petName` and `$ownerName`) with the following query:

```
query PetSearchScreen(
  $petName: String
  $ownerName: String
) {
  pets: pet(
    where: {
      _and: { 
        name: { _ilike: $petName }
        owner: { 
          name: { _ilike: $ownerName } 
        } 
      }
    }
  ) {
    id
    ...
  }
}
```

Hasura seems to expectedly (according to us of coures) handles if `$petName` is undefined: it just ignores `name: { _ilike: $petName }`.

Though it turns out to search for pet records with non-null ownerId even if `$ownerName` is undefined. Ideally Hasura would have interpreted the condition:

```
owner: { 
  name: { _ilike: $undefined } 
} 
```
as `owner: {}` which seems to mean any owner.

Is this documented or it a bug?

**Comment by leoalves** [comment]
@nikolaykhodov,

The issue here is that `owner: {}` will evaluate to true and will return all records.  There is an open issue about it. 
https://github.com/hasura/graphql-engine/issues/704

If the value is mandatory you can add `!` to tell GraphQL. With `!` GraphQL will reject the query.

Also `_and` expects an array.  I think that is why the first value is being ignored. 

Your query should be:
```javascript
query PetSearchScreen(
  $petName: String!
  $ownerName: String!
) {
  pets: pet(
    where: {
      _and: [
       {name: { _ilike: $petName }},  
        {owner: { name: { _ilike: $ownerName }}
       ]
    }
  ) {
    id
    ...
  }
}
```

**Comment by nikolaykhodov** [comment]
@leoalves Thanks a lot for your explanation.

> The issue here is that owner: {} will evaluate to true and will return all records

I understand it returns all `owner` records, though what we'd like to is to get all `pet` records with any `ownerId` value (defined/not defined). If both `$petName` and `$ownerName` are `undefined`, Hasura generates the following SQL query returning only pets with owners:

```
SELECT
  coalesce(json_agg("root"), '[]') AS "root" 
FROM
  (
    SELECT
      row_to_json( ( 
      SELECT
        "_2_e" 
      FROM
        (
          SELECT
            "_1_root.base"."id" AS "id" 
        )
        AS "_2_e" ) ) AS "root" 
      FROM
        (
          SELECT
            * 
          FROM
            "public"."pet" 
          WHERE
            (
              EXISTS 
              (
                SELECT
                  1 
                FROM
                  "public"."owner" AS "_0__be_0_public_owner" 
                WHERE
                 # Here it checks an owner of the pet, though we'd like to see pets with no owners.
                  (
( ( ("_0__be_0_public_owner"."id") = 
                    (
                      "public"."pet"."ownerId"
                    )
) 
                    AND 
                    (
                      'true'
                    )
) 
                    AND 
                    (
( ('true') 
                      AND 
                      (
                        'true'
                      )
) 
                      AND 
                      (
('true') 
                        AND 
                        (
                          'true'
                        )
                      )
                    )
                  )
              )
            )
        )
        AS "_1_root.base" 
  )
  AS "_3_root"
```

Any hint how to make Hasura completely ignore the condition `{owner: { name: { _ilike: $ownerName }}` if `$ownerName` is undefined or restructure the query?

**Comment by leoalves** [comment]
Hi @nikolaykhodov,

Hasura returns everything if the value is undefined.  

As I said, `_and` expects and array and not an object.  If you pass and array to it it should work as expected.

Here is an example in Heroku:

https://testtesttesttettest.herokuapp.com/console

If you do the following query:
```javascript
query ($petName: String, $ownerName: String ) {
  pet (where: {
    _and: [{
      name:{_ilike: $petName}
    },
    {owner: {
      name: { _ilike: $ownerName}
    }}]
    
  }) {
    id
    name
    owner {
      name
    }
  }
}
```
And pass no variables to the query it will return everything.
If you pass only the variable petName like:
```javascript
{
"petName": "%1"%
}
```
It will return only the record where the pet name is `Pet 1`, is you pass the variable 
```javascript
{
"petName": "%pet"%
}
```
it will return everything

**Comment by nikolaykhodov** [comment]
@leoalves Wow, that's a really great example! There is still one minor question.

You provided an example for non-NULLable `ownerId`. I am also thinking how to handle if it could be nullable. I am not sure if Hasura'd return all pet records in this case since there is a `inner join` statement in the generated query:

```
SELECT
                  1 
                FROM
                  "public"."owner" AS "_0__be_0_public_owner" 
                WHERE
                 # Here it checks an owner of the pet, though we'd like to see pets with no owners.
                  (
( ( ("_0__be_0_public_owner"."id") = 
                    (
                      "public"."pet"."ownerId"
                    )
) 
```

Can you please help find a solution for this case?

**Comment by leoalves** [comment]
@nikolaykhodov,

If you add an `_or` condition to the query it should also return all pets that don't have an owner.  Something like:

```javascript
query($petName: String, $ownerName: String) {
	pet(
		where: {
			_or: [
				{ _not: { owner: {} } },
				{
					_and: [
						{ name: { _ilike: $petName } },
						{ owner: { name: { _ilike: $ownerName } } }
					]
				}
			]
		}
	) {
		id
		name
		owner {
			name
		}
	}
}

```

**Comment by nikolaykhodov** [comment]
@leoalves The enhanced query with `{ _not: { owner: {} } }` requests for `all pets without an owner` + `pets (whose name is like $petName) AND (who have an owner) AND (whose owner's name is like $ownerName)`. We know that `(whose name is like $petName)` is ignored if `$petName` is absent.

I am trying to build a request which requests for `all pets (whose name is like $petName) AND (who have an owner AND whose owner's name is like $ownerName IF $ownerName is present/defined)`.

If I could use variables in the `where` clause, I would rewrite your query as the following:


```
query($petName: String, $ownerName: String) {
  pet(
    where: {
      _or: [
        { _not: { owner: {} } }
        {
          _and: [
            { name: { _ilike: $petName } }
            {
              _or: [
                { owner: { name: { _ilike: $ownerName } } }
                { $ownerName: { _is_null: true } }
              ]
            }
          ]
        }
      ]
    }
  ) {
    id
    name
    owner {
      name
    }
  }
}

```

**Comment by leoalves** [comment]
You can use variable as the where.
Check the where type, with the GraphiQL docs. It should be `pet_bool_exp`
or something like that

` query petname ($where: pet_bool_exp) {
  pet { where: $where) {
  }
}
`

**Comment by nikolaykhodov** [comment]
@leoalves I am not sure I can test query variable values solely. Of course, I can use refer to them in operator statements:

```
{ name: { _ilike: $petName } }
```
but I believe I can't build a filter which applies an operator just for the variable:

```
          _or: [
            { owner: { name: { _ilike: $ownerName } } },
            { $ownerName: { _is_null: true } } # <------ pseudocode goes here
          ]
```

**Comment by nikolaykhodov** [comment]
@leoalves Any idea how to work around?
