### ISSUE TITLE
Console opens a new websocket connection for every subscription, all remain open

### ISSUE THREAD

**Issue by jberryman** [hasura/graphql-engine#3879]
I think subscriptions should either re-use an existing connection we hold open, or close the connection when "stop" is pressed.

To repro: start subscription, stop subscription (a few times), observe "stop" logs. Close window, observe several "close" logs for each subscription you stopped and started. This is a space leak, but I'm not sure if it's a production concern for folks (probably not related to #3388)

**Comment by beerose** [comment]
Closing as a duplicate of https://github.com/hasura/graphql-engine/issues/3918
