### ISSUE TITLE
sudden spike in Postgres and gradual increase in kubernetes

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#3884]
SOS issue from intercom [here](https://app.intercom.io/a/apps/rucirpb3/inbox/inbox/conversation/25696972291) 

[example_execution_plan.txt](https://github.com/hasura/graphql-engine/files/4202595/example_execution_plan.txt)
[example_query.txt](https://github.com/hasura/graphql-engine/files/4202596/example_query.txt)
[example_slow_query.txt](https://github.com/hasura/graphql-engine/files/4202597/example_slow_query.txt)
[example_sql.txt](https://github.com/hasura/graphql-engine/files/4202598/example_sql.txt)
![kubernetes_cpu](https://user-images.githubusercontent.com/8663570/74500376-b306f180-4f0c-11ea-85fa-5b30965b5303.png)
![kubernetes_ram](https://user-images.githubusercontent.com/8663570/74500378-b601e200-4f0c-11ea-881f-d1b17facbaa0.png)
![postgres_cpu](https://user-images.githubusercontent.com/8663570/74500380-b69a7880-4f0c-11ea-9dd8-9a96ea6580c5.png)
![postgres_ram](https://user-images.githubusercontent.com/8663570/74500383-b7330f00-4f0c-11ea-98b1-278cb4ac4bb1.png)
![query_stats](https://user-images.githubusercontent.com/8663570/74500384-b7cba580-4f0c-11ea-8ffb-8c927eb4b9fc.png)
---

First of thanks for creating and maintaining such an awesome work as Hasura. This is much appreciated by me and my team.

Now to the issue.
My setup is on DigitalOcean

Kubernetes 2 droplets - 1vCPU 2GB ram each
Postgres 2vCPU 4GB ram with standby

At about 8 February 2020, at 3:30 pm +5:30 UTC, there was a sudden spike in postgres CPU (5% -> 70%) and RAM(18% -> 75%), kubernetes was increasing gradually from 12:30 PM (cpu - 10% ram - 60% at 3:30pm).

That came down suddenly at 8:05 PM (everything went to as it was before spike)
I am attaching engine logs and some screenshots from DO insights

Also attached is a typical query and example sql
also I have attached a slow query

Thanks for your help

Vaibhav Singh

**Comment by marionschleifer** [comment]
Closing this since Vaibhav reported on Intercom that the issue has been resolved by simplifying the table permissions.
