### ISSUE TITLE
heap exhausted calling /v1alpha1/pg_dump

### ISSUE THREAD

**Issue by yaroot** [hasura/graphql-engine#3886]
`readProcessWithExitCode` holds the output from pg_dump in memory, causing the crash. Shouldn't the output be streamed back to caller?

**Comment by lexi-lambda** [comment]
If we were to stream the output back to the caller, what would we do if we received a nonzero exit code? To stream data, we have to have already sent HTTP status/headers, so we can’t back that out at that point.

The `pg_dump` API is really intended for debugging. I think if you need streaming, you should probably run `pg_dump` yourself, or use some other mechanism of dumping the database more directly. Could you say more about why this is a problem for you?

**Comment by yaroot** [comment]
I'm dumping data from staging for local development and since the api is already there I tried it without too much thought. Running pg_dump directly right now, not really an issue for me.

**Comment by lexi-lambda** [comment]
Alright, I think I’m going to close this then, since I think it’s not clear what the right thing to do is. If other people think it’s important (and have a good idea about how it should work) we can revisit it.
