### ISSUE TITLE
I will translate to Turkish from English.

### ISSUE THREAD

**Issue by berat** [hasura/graphql-engine#3891]
Get ready to send me Folded Hands. I will translate soon :) Is there any permission?

**Comment by marionschleifer** [comment]
Hey @berat, you can just open a pull request on our [repo](https://github.com/hasura/graphql-engine) and add your translation. Please find here our [contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md) 🙂 closing this issue.
