### ISSUE TITLE
docker-compose file for use in the quickstart docs for docker-compose missing postgres password

### ISSUE THREAD

**Issue by silky** [hasura/graphql-engine#3894]
from a comment i made on the discord, here's the error you get when you use the present version of the docker-compose.yaml from the docs here - https://docs.hasura.io/1.0/graphql/manual/getting-started/docker-simple.html

```
postgres_1        |        You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
postgres_1        |        without a password. This is *not* recommended. See PostgreSQL
postgres_1        |        documentation about "trust":
postgres_1        |        https://www.postgresql.org/docs/current/auth-trust.html
postgres_1        | Error: Database is uninitialized and superuser password is not specified.
postgres_1        |        You must specify POSTGRES_PASSWORD for the superuser. Use
postgres_1        |        "-e POSTGRES_PASSWORD=password" to set it in "docker run".
```

fix is just to add the password to the env section.

**Comment by israelidanny** [comment]
Same issue I'm having:
https://github.com/hasura/graphql-engine/issues/3893

**Comment by silky** [comment]
@israelidanny ah, sorry i missed that one when searching!

**Comment by israelidanny** [comment]
@silky no problem at all! :) I tagged it here so people who look from now on will be able to see a full picture of progress on this.
