### ISSUE TITLE
Improve docs for computed fields for the table row argument in the console/metadata API

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#3896]
It's not clear what I should enter as a user for this input. 

<img width="726" alt="Screenshot 2020-02-16 at 3 45 06 PM" src="https://user-images.githubusercontent.com/131160/74602882-5a358580-50d3-11ea-9cec-f858566e8b43.png">

**Comment by BayCo** [comment]
@coco98 did you resolve this question???

**Comment by kolharsam** [comment]
With regards to this issue, there's a tooltip available now which explains what needs to be done with regards to this input.

![image](https://user-images.githubusercontent.com/6604943/90522052-e3b03800-e188-11ea-8dd2-30af8f1f921b.png)

**Comment by ShawnToubeau** [comment]
Hi, for some clarification, does this support passing specific fields from a row? So for example if my table `author` has fields `id`, `name`, `last_name` could I tell it to only use `id`? And if so what would that look like? The docs weren't too clear about this. Thanks!

**Comment by kolharsam** [comment]
@ShawnToubeau you can use specific properties of the table from within the function body. As specified in [here](https://hasura.io/docs/1.0/graphql/core/schema/computed-fields.html#supported-sql-functions) we need to have one of the arguments as the table row to qualify as a computed field. Take a look at the example [here](https://hasura.io/docs/1.0/graphql/core/schema/computed-fields.html#scalar-computed-fields).
