### ISSUE TITLE
Enable custom "Domain" data type

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#391]
In PostgreSQL, Domain is a way to manage  constraints, for example:

```sql
CREATE DOMAIN domain_email AS TEXT
CHECK(
   VALUE ~ '^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$'
);
CREATE TABLE tbl_TestEmail
(
    ID INT
    ,Email domain_email
);
```

`domain_email` doesn’t allow numbers in the domain name and doesn’t allow for top level domains that are less than 2 or more than 3 letters.
Currently, all of `domain_emai`l and `tbl_TestEmail` are ignored in Hasura.

Suggestions:
* [ ] There're a tab to manage domains for constraints management
* [ ] Allow custom data type when creating tables.
* [ ] Expose custom data types in GraphQL query.

**Comment by 0x777** [comment]
@revskill10 

Hasura works with custom domains too. For example, this will work:

```sql
CREATE DOMAIN domain_email AS TEXT
CHECK(
   VALUE ~ '^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$'
);
CREATE TABLE tbl_test_email
(
    ID INT
    ,Email domain_email
);
```

**Note** the case of the table name. You ran into this issue (https://github.com/hasura/graphql-engine/issues/392). 

About supporting creation of domains in the console, we are not particularly sure (see #395). However I agree that domains have to be listed under the types as part of the table creation UI. You can look at this #394. 

Closing this issue in favor of more specific issues.
