### ISSUE TITLE
websocket isn't closed after stopped subscription on console graphiql

### ISSUE THREAD

**Issue by hgiasac** [hasura/graphql-engine#3918]
In console's graphiql, after the user stopped subscription, the websocket is still alive. If he starts new subscription, new websocket will be created for it. It leaks websocket connections

#### Reproduce steps
- Open chrome/firefox dev tools - Tab Network - `ws` filter
- Start a subscription
- Stop it
- Start another subscription
- Look at the dev tool

![websocket_bug](https://user-images.githubusercontent.com/1615675/74933504-b3c0eb80-5416-11ea-8583-9864ede6779b.png)

**Comment by ecthiender** [comment]
When we stop a subscription and then start again on graphiql, it doesn't re-use the existing connection, but opens another new connection.
