### ISSUE TITLE
McAfee LiveSafe marks hasura-cli as virus 

### ISSUE THREAD

**Issue by manisundaram** [hasura/graphql-engine#3922]
**Environment:** Windows 10, VS Code
**AntiVirus:** McAfee LiveSafe, Chrome browser plugin is also enabled
**Setup:**
1. Follow instructions to create a new project from VS Code terminal https://docs.hasura.io/1.0/graphql/manual/migrations/new-database.html
2. Install hasura-cli by running "npm install --global hasura-cli"
3. Update config.yaml in the new project

**Steps to Repeat:**
a) run hasura console from VS Code terminal
b) The hasura console opens in chrome.  After few seconds,  McAfee Live Safe shows a warning that a Virus has been detected.  
c) In VS Code,  hasura console has now exited.  Running the hasura command again will give an error
```
The term 'C:\Users\xxxx\AppData\Roaming\npm/node_modules/hasura-cli/hasura' is not recognized as the name of a cmdlet, function, script file, 
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by shahidhk** [comment]
I am not sure what we can do here. If anyone with experience on Windows can help, that would be great. 

The CLI runs webservers on port 9693 and 9695, this could be the reason why McAfee flags it as suspicious.

@manisundaram For now, I can only suggest to mark Hasura CLI as safe to use on your McAfee program. And make sure you download it only from GitHub Releases page.

**Comment by Luifr** [comment]
FATA[0014] apply update: rename new to exe: rename C:\Users...\Hasura\.hasura.new C:\Users\...\Hasura\hasura: Operation did not complete successfully because the file contains a virus or potentially unwanted software

**Comment by shahidhk** [comment]
We're working on getting the binary whitelisted, and have submitted a detection dispute with https://www.mcafee.com/enterprise/en-us/threat-center/detection-dispute-form.html

**Comment by miqvo** [comment]
Any update on this? I'm surprised not more people are affected by this.

I'd like to help with the details, but none of the McAfee products on that page matches what's on my laptop. (Work laptop with McAfee managed by IT).

**Comment by MONKATRON** [comment]
Also an issue with bitdefender

**Comment by jeffmath** [comment]
I'm still seeing this issue with McAfee.

**Comment by scriptonist** [comment]
Closing in favour of https://github.com/hasura/graphql-engine/issues/7147, which aims to add a solution for this issue.
