### ISSUE TITLE
[Feature Request]: Add GraphQL-Event-Stream for schema hot reloading

### ISSUE THREAD

**Issue by marvin-hansen** [hasura/graphql-engine#3924]
Let's suppose you update your GraphQL schema and let's suppose you add or modify some fields. 
Usually, your client has to reload the schema to see the changes. However, there is a mechanism to push schema changes from the server to the client through server-side events. 

so please take a look if / whether Hasura can support this really useful feature:

Blog post

https://sirmuel.design/a-better-graphql-developer-experience-with-x-graphql-event-stream-1256aef96f24   

Server-site event sample implementation in TS:

https://github.com/graphile/postgraphile/blob/ede614c5eeb11556dea6f079b98e4f53e5a92439/src/postgraphile/http/setupServerSentEvents.ts

**Comment by tirumaraiselvan** [comment]
Indeed, it would be nice to have a way for the client to detect if the schema has changed.

A current workaround that we have seen people use is poll the introspection query (say every 5 seconds) and do a diff to figure out if the schema has changed. Not very ideal for large schemas but just wanted to point it out.

**Comment by marvin-hansen** [comment]
@tirumaraiselvan 

Altair already supports schema auto-refresh through an http header, so the client already can do it, but there aren't many servers out there supporting the matching server-side functionality, and I guess, supporting that is up to the Hasura engineers.  

https://altair.sirmuel.design/docs/features/schema-auto-refresh.html

Thinking one step further, exposing the GraphQL schema as a GraphQL endpoint would allow a very simple subscription so that all clients get change notification in real-time. Just saying...

**Comment by tirumaraiselvan** [comment]
@marvin-hansen I agree !

**Comment by tirumaraiselvan** [comment]
Similar to https://github.com/hasura/graphql-engine/issues/3297

**Comment by marvin-hansen** [comment]
Closing issue as it seems to be stalled after 2 years.
