### ISSUE TITLE
[Feature Request] generate custom dataIdFromObject function

### ISSUE THREAD

**Issue by adwd** [hasura/graphql-engine#3925]
Apollo client uses `dataIdFromObject` function to identify cached object.
https://www.apollographql.com/docs/react/caching/cache-configuration/#assigning-unique-identifiers

I think hasura can automatically generate this function because hasura knows primary key of table.
To work with Apollo client object identifier, another way is to use computed field but it's verbose I think.

**Comment by wawhal** [comment]
@adwd `dataIdFromObject` must be used while configuring the `InMemoryCache` of ApolloClient if you wish to have a unique identifiers than `id` or `_id` for some types.

If the name of the primary key of the table `customers` is `uid`. You'd want to configure something like:

```js
import { InMemoryCache, defaultDataIdFromObject } from 'apollo-cache-inmemory';

const cache = new InMemoryCache({
  dataIdFromObject: object => {
    switch (object.__typename) {
      case 'customers': return object.uid; // use the `uid` field as the identifier for `customers` type
      default: return defaultDataIdFromObject(object); // fall back to default handling
    }
  }
});
```

Reference: https://www.apollographql.com/docs/react/caching/cache-configuration/#custom-identifiers

Closing this. Please reopen if there're more ideas/questions.

**Comment by christophediprima** [comment]
I would like to reopen this one as I think @adwd idea is super nice.

Hasura could automatically generate a `_primaryKeyFields` field that would be an array of strings we could simply use like following in Apollo:

```javascript
import { InMemoryCache, defaultDataIdFromObject } from 'apollo-cache-inmemory';

const cache = new InMemoryCache({
  dataIdFromObject: object => {
    if (object._primaryKeyFields && object._primaryKeyFields.length) {
      return object._primaryKeyFields.map(keyField => object[keyField]).join(':');
    }
    return defaultDataIdFromObject(object); // fall back to default handling
  }
});
```
