### ISSUE TITLE
skip ci for docs-only changes

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#3929]
Currently, all tests are run for only docs changes.

**Comment by shahidhk** [comment]
Tests are skipped (marked as passed without actually running them) if the diff of the PR with master only contains things mentioned in https://github.com/hasura/graphql-engine/blob/master/.circleci/ciignore.sh

The PR needs to be up-to-date with master.

**Comment by shahidhk** [comment]
Also, feel free to use `[skip ci]` in commit messages.
