### ISSUE TITLE
Console\GraphQL URL configuration

### ISSUE THREAD

**Issue by esseswann** [hasura/graphql-engine#3936]
We have a problem that we're serving `hasura` on `/api/v2/` through traefik and it creates this horrible path `/api/v2/graphql/v1/graphql` because there is no configuration for graphql endpoint url.
Is it possible to set it up somehow without extra stuff in the reverse-proxy?
The result we're trying to achieve is having graphql endpoint on `/api/v2/graphql`

**Comment by shahidhk** [comment]
You can do this with any reverse proxy, here is an example with nginx:

```
server {
  listen 80;

  location /api/v2/graphql {
    proxy_pass http://localhost:8080/v1/graphql;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
```
