### ISSUE TITLE
allow management of postgres domains

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#395]
https://www.postgresql.org/docs/9.5/static/sql-createdomain.html

From: #391

**Comment by revskill10** [comment]
Let me be more specific, this feature will allow us:

* Create, edit and query all `constraints` and `domains`, because `domain` is to be shared between tables.
* Some domains require composition of other `domains` and  `extension` to work, for example:
```sql
CREATE EXTENSION uri;

CREATE DOMAIN http_uri AS uri CHECK (
      uri_scheme(VALUE) IS NOT NULL
  AND uri_scheme(VALUE) IN ('http', 'https')
  AND uri_host(VALUE) IS NOT NULL
  AND uri_host(VALUE) <> ''
);

-- works great
SELECT 'https://www.foo.com/bar/baz'::http_uri;

-- forbidden
SELECT 'ftp://www.foo.com/bar/baz'::http_uri;
```

**Comment by manasag** [comment]
Thanks everyone for your comments and patience on this issue. We plan to provide a more mature database management experience in Hasura V3, by integrating a full feature database manager within Console. Closing this issue, in favor of this new V3 [issue](https://github.com/hasura/graphql-engine/issues/10076)
