### ISSUE TITLE
Console dropdowns are serif in Firefox

### ISSUE THREAD

**Issue by dminkovsky** [hasura/graphql-engine#3955]
1.1.0-beta2, the dropdowns look like this in FF:

<img width="311" alt="Screen Shot 2020-02-25 at 5 38 00 PM" src="https://user-images.githubusercontent.com/218725/75294692-12aba980-57f7-11ea-94f5-7151e768fb06.png">
<img width="432" alt="Screen Shot 2020-02-25 at 5 37 51 PM" src="https://user-images.githubusercontent.com/218725/75294699-150e0380-57f7-11ea-918c-9b14b1aea856.png">

Would be nice if they were sans-serif like in Chrome. Much easier to read that way.

**Comment by MathWhiz** [comment]
Is this still an issue? If so, may I work on it?

**Comment by dminkovsky** [comment]
Still an issue

**Comment by beerose** [comment]
Solved in https://github.com/hasura/graphql-engine/commit/0c1133b3933e6e9362231869551235fd73403a69
