### ISSUE TITLE
Actions: Forward client headers to webhook option not working

### ISSUE THREAD

**Issue by toddheslin** [hasura/graphql-engine#3956]
@0x777 adding you as I saw that actions was your PR.

I'm testing out docker image `hasura-graphql-engine/v1.2.0-beta.1`.

This is set:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/1883112/75302546-09781680-58a3-11ea-8e07-5ee1f78a0e27.png">

Custom headers go through but not the hasura headers:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/1883112/75302571-18f75f80-58a3-11ea-9051-61f6920bb7ca.png">

This was the request:
<img width="761" alt="image" src="https://user-images.githubusercontent.com/1883112/75302615-2f9db680-58a3-11ea-8c84-1e22af043890.png">

Tested both:
`X-Hasura-User-Id` and `x-hasura-user-Id`
`X-Hasura-Role` and `x-hasura-role`
but neither worked.

Let me know if you need any more info.

**Comment by toddheslin** [comment]
OK, sorry about this. I now realise in [the docs](https://docs.hasura.io/1.0/graphql/manual/actions/action-handlers.html) it says these variables are part of the payload, not the headers. Confirmed this is true:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/1883112/75303471-af2c8500-58a5-11ea-8bc0-b35425e5a956.png">

I think this could be considered more of a UX issue. It's not entirely clear that the headers are transformed into the body and not passed along as headers like they are for remote schemas:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/1883112/75303555-e9962200-58a5-11ea-878e-6415336e9c87.png">

**Comment by rikinsk** [comment]
@toddheslin Hasura assumes any header starting `x-hasura-` as a hasura session variable and strips them from the headers and includes them in the payload instead. Any other headers should be passed as headers as expected. 

This does need to be clarified better in the documentation.

**Comment by tirumaraiselvan** [comment]
I am closing this in favour of https://github.com/hasura/graphql-engine/issues/4101
