### ISSUE TITLE
Hasura Actions: invalid input syntax for type json

### ISSUE THREAD

**Issue by tomasherout** [hasura/graphql-engine#3962]
Hello,

I have tried Hasura Actions and I discovered strange issue.

According to examples in Hasura Doc I have userLogin mutation (action) returning:

```
type UserInfo {
  accessToken : String!
  userId : Int!
}
```
Handled by following code:

```
app.post("/hasura-handler", (req, res) => {
    console.log(req.body);
    return res.json({
        "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVC",
        "userId": 4829
    });
});
```
Postman shows correct JSON, Content-Type header has value "application/json; charset=utf-8".

Call this mutation results to following error response:

```
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "data-exception"
      },
      "message": "invalid input syntax for type json"
    }
  ]
}
```

Many thanks for help,
Tomas

**Comment by tomasherout** [comment]
I have also discovered, that it is correct for JSON numbers (Int type in GraphQL schema) and not working for boolean.

Strings a Booleans _works_ only if field contains JSON, e.g. handler:

```
app.post("/hasura-handler", (req, res) => {
    return res.json({
        "accessToken": {
            "uselessField": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVC"
        },
        "userId": 4829
    });
});
```

causes response without errors:

```
{
  "data": {
    "userLogin": {
      "accessToken": {
        "uselessField": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVC"
      },
      "userId": 4829
    }
  }
}
```

... so Hasura expects JSON object when scalar types like String or Boolean are defined in schema for action.

**Comment by tirumaraiselvan** [comment]
Hey @tomasherout Might seem like a strange question but what version of Postgres are you using?

**Comment by dostalradim** [comment]
Hi @tirumaraiselvan I am @tomasherout colleague and I can describe you our test environment.

Graphql-engine version is v1.2.0-beta.1
Postgresql version is 9.6.16-1.pgdg90+1

Both is running in docker container which is 19.03.3 but it does not interest you propably.

Will be helpful database dump or something what I can provide to you? Should we try it against new Postgresql? Which Postgresql version is used to test graphql-engine releases?

Thank you for your reaction!

**Comment by tirumaraiselvan** [comment]
@dostalradim Can you try running this with Postgres 10+ . This is a known issue with json types in postgres prior to v10. @rakeshkky can tell more.

**Comment by tomasherout** [comment]
It works correctly with Postgres 12.2

**Comment by tirumaraiselvan** [comment]
I am going to re-open the issue so we can document this.

**Comment by tirumaraiselvan** [comment]
This is now documented in the note titled `Postgres support` here: https://hasura.io/docs/1.0/graphql/manual/actions/index.html
