### ISSUE TITLE
Unable to add Remote Schema on v1.2.0-beta.1

### ISSUE THREAD

**Issue by samuelcastro** [hasura/graphql-engine#3963]
When attempting to add a new remote schema I'm getting this error:

```
main.js.gz:1 POST http://localhost:9693/apis/migrate 500 (Internal Server Error)
...
main.js.gz:1 Uncaught (in promise) SyntaxError: Unexpected token i in JSON at position 2
...
```

Any ideas?

**Comment by samuelcastro** [comment]
For now I just downgraded to `v1.1.0` it's working just fine.

**Comment by rikinsk** [comment]
@samuelcastro I just tried to add a remote schema and it worked for me. Could you share some more information around this. 

Is this happening for all remote schemas? (you could try adding a public GraphQL API such as https://countries.trevorblades.com to confirm). It would also help if you could share more information about the error you're observing. The payload & response of the failing API call should be helpful.

**Comment by samuelcastro** [comment]
So I destroyed all docker containers and started it from scratch and it worked now, I don't know what happened. I can confirm that remote schema is working on v1.2.0-beta.1.

Thanks!
