### ISSUE TITLE
Hasura Actions: non-nullable fields can return null

### ISSUE THREAD

**Issue by tomasherout** [hasura/graphql-engine#3977]
Hasura is not checking response from action handler. Field in schema marked as non nullable, e.g.:

```
type SampleOutput {
  accessToken : String!
  userId : Int!
}
```

and badly implemented handler which doesn't return mandatory fields cause response:

```
{
  "data": {
    "actionName": {
      "accessToken": null,
      "userId": null
    }
  }
}
```

Schema should be accepted and thus bad answer from resolver can be ignored. In this way works other GraphQL servers like Apollo or GraphQL JS.

**Comment by tirumaraiselvan** [comment]
@rakeshkky Can you determine `e/` label for this?
