### ISSUE TITLE
:bug: 1.2.0-beta.1 Linux CLI

### ISSUE THREAD

**Issue by Disturbing** [hasura/graphql-engine#3982]
Right now --endpoint {url} is not working for the `hasura-dev migrate apply` command in new beta v1.2.0-beta.1 build.

It use to work fine in the preview-actions.

**Comment by Disturbing** [comment]
I just confirmed it works fine in the mac version, but not the linux version.

**Comment by EmrysMyrddin** [comment]
It's not working for me on macOs version. `--endpoint` is ingored in favor of config's endpoint.

**Comment by Disturbing** [comment]
Ah yeah it's not working. `console --endpoint` works fine, but not migrate, thanks for that @EmrysMyrddin
