### ISSUE TITLE
FATA[0000] unknown command "actions" for "hasura"

### ISSUE THREAD

**Issue by kemicofa** [hasura/graphql-engine#3987]
I've installed the latest version of hasura-cli (tried with `npm` and `wget/bash`) as mentioned in the dcoumentation.

It would appear some commands are missing?

> FATA[0000] unknown command "actions" for "hasura"

OS:
macOS High Sierra 10.13.6

hasura version :

```
INFO hasura cli                                    version=v1.1.0
INFO hasura graphql engine                         endpoint="http://localhost:8080" version=v1.1.0
```
Either this is a bug or a step is missing (or I missed a step) in the documentation. Anyone know if this is normal?

When I run `hasura console` it works as expected and redirects me to running application.

**Comment by shahidhk** [comment]
@kemicofa Actions are introduced in `v1.2.0-beta.1` and you should download the CLI from https://github.com/hasura/graphql-engine/releases/tag/v1.2.0-beta.1

The stable CLI will not update automatically to pre-release versions.
