### ISSUE TITLE
How to set permission: Find a value in array

### ISSUE THREAD

**Issue by vctqs1** [hasura/graphql-engine#3994]
My table have a field ids: [1,2,3]
I want to find all record have id = 1.

How to find `id` - single value in `ids` - array field.
Can not use ANY, ALL because operator for case `find array value of single field`

**Comment by marionschleifer** [comment]
@vctqs1 we don't have array support for permissions yet.

A workaround is to convert the Postgres array to a JSONB field and then use the `_contains` operator to find an ID in the array.

This is how you can convert the array:

```
alter table mytable 
  alter column somearray type jsonb using array_to_json(somearray);
```

Let me know if this helps 🙂

**Comment by tirumaraiselvan** [comment]
Closing this as feature request is tracked in #348
