### ISSUE TITLE
create migration doesn't backup metadata in v1.2.0-beta.1

### ISSUE THREAD

**Issue by EmrysMyrddin** [hasura/graphql-engine#3997]
Using the latest `v1.2.0-beta.1` cli and server, the command `hasura migrate create "init" --from-server` doesn't store metadata files.

Steps to reproduce:
 - Create a fresh instance with docker for example
 - Add a table
 - Track it
 - run `hasura init --directory hasura --endpoint http://localhost:8080`
 - run `hasura migrate create "init" --from-server`

It creates an SQL migration script as expected in the `migration` folder. But the files under `metada` are not touched. for example, `tables.yam` contains only `[]`.

Am I missing something ?

**Comment by shahidhk** [comment]
@EmrysMyrddin The new workflow introduced with 1.2.0-beta.1 moves all metadata related actions under `metadata` command. `migrate` command is exclusively used for managing SQL migrations.

To export both SQL schema and Hasura metadata, you should execute the follwing commands:

```
hasura migrate create init --from-server
hasura metadata export
```

We'll be adding proper docs for this soon.

**Comment by marionschleifer** [comment]
@EmrysMyrddin glad to here it's working now. I'm closing this issue 🙂
