### ISSUE TITLE
[Documentation] Postgres TLS by default?

### ISSUE THREAD

**Issue by jmoseley** [hasura/graphql-engine#3999]
I can't find it documented anywhere, but I need to verify that the Postgres connection from Hasura will use TLS by default. Or does it need to be configured?

Thanks

**Comment by tirumaraiselvan** [comment]
@jmoseley Graphql Engine expects a valid postgres connection string. Your connection string can supply `sslmode` parameter with values as described here: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING

**Comment by tirumaraiselvan** [comment]
@rikinsk @marionschleifer Can this link https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING be mentioned in the docs under `--database-url` here: https://hasura.io/docs/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html#server-flags

**Comment by jmoseley** [comment]
That answers my question perfectly. Thanks.
