### ISSUE TITLE
document the yaml file generated by metadata export command

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#400]
Document what's insied the `metadata.yaml` file exported by `hasura metadata export` command.

This should be a docs page which explains Hasura metadata in detail.

**Comment by shahidhk** [comment]
Re-opening as this is meant to be a docs issue.

**Comment by marionschleifer** [comment]
This has been documented [here](https://hasura.io/docs/1.0/graphql/core/migrations/reference/metadata-format.html).
