### ISSUE TITLE
Mutations have disappeared?

### ISSUE THREAD

**Issue by andrisole92** [hasura/graphql-engine#4012]
Hey guys,

I have just tried launching Hasura over the new schema, and I can't see any mutations or subscriptions queries available?

Was it removed? Or is it only available in PRO now?

Looking forward to hearing from you soon.

**Comment by rikinsk** [comment]
@andrisole92 Mutations have not actually dissappeared from Hasura :). Can you share some more information around this.

**Comment by coco98** [comment]
@andrisole92 Are you using the explorer in GraphiQL and not able to find the mutations?
