### ISSUE TITLE
Graphql error: enum type does not exist because case sensitivity was not recognized

### ISSUE THREAD

**Issue by gentleShark** [hasura/graphql-engine#4014]
I have an existing postgres DB with an enum (native Postgres enum type) named "enum_Motivations_desired_solution" on a table named "Motivations". When I try to insert into the table, Hasura throws an error indicating it is looking for an enum of the same name but in lower case. If I re-name the enum in Postgres to be lower case, it solves the problem. 
The error:
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.insert_Interactions.args.objects[0].Motivations.data",
        "code": "constraint-error"
      },
      "message": "type \"enum_motivations_desired_solution\" does not exist"
    }
  ]
} 

The query:
```
mutation InteractionTest {
  insert_Interactions(objects: [
    {
      OwnerId: 5,
      forUserId: 1,
      initiatedByUserId: 1,
      Motivations: {
      data: [
        {
          desired_solution: "solution A",
          MotivatingFactors: {
            data: [{
              isCurrentFactor: true,
              commonFactor: "A"
            },
            {
              isCurrentFactor: true,
              commonFactor: "B"
            }]
          }
        }
      ]
    }
    }
  ]) {
    affected_rows
    returning {
      Motivations {
        desired_solution
        MotivatingFactors {
          commonFactor
          isCurrentFactor
        }
      }
    }
  }
}

**Comment by perrosnk** [comment]
Did you find any solution to this?

**Comment by gentleShark** [comment]
@perrosnk No. I've just been manually renaming the enum to lower case in Postgres to get past the problem.

**Comment by abooij** [comment]
I am trying to reproduce this issue, so that I can create a minimum working example of this, and figure out what is happening here. Could you please tell me some details?

1. What version of GraphQL Engine you are running?
2. Can you describe your Postgres tables? Which columns do your tables have, and what foreign keys have you set up?
3. Which relations have you configured in GraphQL engine?

**Comment by ravikiran438** [comment]
Refer to [enums in the hasura graphql engine](https://hasura.io/docs/1.0/graphql/core/schema/enums.html#enums-in-the-hasura-graphql-engine) section of the documentation. You may have to copy native PG enum types to referenced tables approach. After that alter existing column to TEXT data type and add foreign key to the new referenced table.

**Comment by dariusj18** [comment]
This should be as simple as ensuring that the enum type name is wrapped in double quotes.

**Comment by docforcedev** [comment]
@ravikiran438 This is a bug. If the enum name contains an uppercase letter, it will be flattened to lowercase and then this error will appear. We had `EnumName` and changed it to `enumname` and it worked. Hasura does not properly handle case sensitivity on enum fields.

**Comment by sassela** [comment]
hey folks, thanks for your patience. We'll be triaging this bug shortly. I believe I'm able to reproduce with the following setup on [v2.3.1](https://github.com/hasura/graphql-engine/releases/tag/v2.3.1). Please take a look and let me know if this seems like a reasonable minimal repro, or if I've missed anything compared to the original bug report?

_DDL statements on a Postgres DB, using example from [Hasura docs](https://hasura.io/docs/1.0/graphql/core/schema/enums.html#enums-in-the-hasura-graphql-engine)_
```sql
CREATE TABLE MixedCase (
  value text PRIMARY KEY,
  comment text
);

INSERT INTO MixedCase (value, comment) VALUES
  ('user', 'Ordinary users'),
  ('moderator', 'Users with the privilege to ban users'),
  ('administrator', 'Users with the privilege to set users’ roles');
```

_GraphQL query via Hasura console_
```graphql
{
  MixedCase {
    comment
    value
  }
}
```

_Expected response_
```json
{
  "data": {
    "MixedCase": [
      {
        "comment": "Ordinary users",
        "value": "user"
      },
      {
        "comment": "Users with the privilege to ban users",
        "value": "moderator"
      },
      {
        "comment": "Users with the privilege to set users’ roles",
        "value": "administrator"
      }
    ]
  }
}
```

_Actual response_
```json
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.MixedCase",
        "code": "validation-failed"
      },
      "message": "field \"MixedCase\" not found in type: 'query_root'"
    }
  ]
}
```

cc @gentleShark @lohazo @docforcedev @dariusj18 @perrosnk

**Comment by dariusj18** [comment]
When executing your queries you will want to use double quotes (and you might as well add a mixed case column while you are at it)

ex.

```sql
CREATE TABLE "MixedCase" (
  value text PRIMARY KEY,
  "Comment" text
);

INSERT INTO "MixedCase" (value, "Comment") VALUES
  ('user', 'Ordinary users'),
  ('moderator', 'Users with the privilege to ban users'),
  ('administrator', 'Users with the privilege to set users’ roles');
```

**Comment by rakeshkky** [comment]
Additional context: We don't generate GraphQL enum types out of Postgres enums instead we generate simple custom scalar type. We treat them as `Unknown` type and insert data with String literals (`''`).
