### ISSUE TITLE
add guide on creating auto-updating id, timestamp etc.

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#402]
Guides/tutorials on

- Auto-updating IDs
- Timestamp on_created, on_updated

Via dylanjones on discord / email.

**Comment by shahidhk** [comment]
@rikinsk When you close issues, can you also indicate which commit is was included in?

Or conversely, denote the issue the commit closes in the commit message itself.

**Comment by bhushankumarl** [comment]
@rikinsk @shahidhk 
Setting up the `CURRENT_TIMESTAMP` as default value and column type as `Type` is not updating the column value automatically updatable on record insert/update.

**Comment by shahidhk** [comment]
@bhushankumarl You need to set `now()` as the default value and then when you insert a new row, current server timestamp will be added. 

To update the column to latest timestamp, you can execute a mutation with value as `now()`, or set up a Postgres trigger which updates the column when an update happens to the row.
