### ISSUE TITLE
what's the meaning of JWTIssuedAtFuture

### ISSUE THREAD

**Issue by fred8617** [hasura/graphql-engine#4025]
sometimes this issue crash the hasura server and i need restart server to solve it
![image](https://user-images.githubusercontent.com/35049517/75954010-9d725f80-5eed-11ea-9b4c-a8fd506a9a6d.png)

**Comment by ecthiender** [comment]
It means clocks on one of the servers is not correct. Check similar issues #2109 and #1912 .

**Comment by fred8617** [comment]
yh,i found that the server time is half an hour before my windows system,is there any enviroment variable or configuration in docker-compose?

**Comment by wemersonrv** [comment]
> he server time is half an hour b

Same problem here. I found a lot of "tips" on google, on how to change the containers date and timezone, but nothing works...

Adding `TZ` env variable, run commands to change date... nope!!! nothing works!

**Comment by 0x777** [comment]
@ecthiender If we were to add a `clock_skew_tolerance_jwt` option server side option, can it be implemented by ourselves or do we need support from the underlying JWT library?

**Comment by ecthiender** [comment]
@0x777 , not sure about this. I will check and report on this thread.

**Comment by ecthiender** [comment]
Looks like its a simple setting on the library: https://hackage.haskell.org/package/jose-0.7.0.0/docs/Crypto-JWT.html#t:HasJWTValidationSettings

**Comment by ecthiender** [comment]
@0x777 @tirumaraiselvan  @hasura/hge-server I am closing this issue. #2109 is already tracking this.

**Comment by Aarbel** [comment]
Adding this to my docker-compose file solved the problem to sync well the containers of docker with the system:

```
 volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
```

**Comment by sundaycrafts** [comment]
Thanks Aarbel, but it didn't work for me (macOS 12.3.1).

I put here the shortcut of the (temporary) solution to this issue.

But DO NOT DO THIS FOR PRODUCTION.

> adding allowed_skew to the JWT issuer fixes it.
> such as this in my docker-compose.yml for Hasura:
> `HASURA_GRAPHQL_JWT_SECRET: '{"jwk_url":"JWT_ISSUER_URL/api/auth/jwt/jwks.json", "allowed_skew": 86400}'`

#467

**Comment by arslanakhtar61** [comment]
@sundaycrafts Amazing. Thanks for the solution
