### ISSUE TITLE
Making action webhook debugging easy

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#4031]
Currently there isn't enough information logged to figure out what went wrong with an action's handler. We'll need to capture the raw http request and response (headers + body) in our internal error's detail, so that they are logged and sent to the client when requested with admin credentials. Maybe something like this along with our current error message?
```json
{
  "request": {"headers": {}, "body": ".."},
  "response": {"headers": {}, "body": ".." }
}
```
We'll need to be a little careful about logging headers which are derived from environment variables.

**Comment by tirumaraiselvan** [comment]
FYI, redtaping environment variable values is part of Event Triggers logging infra.

**Comment by coco98** [comment]
Current suggestion:
1. Add a header called debug mode that is respected for the admin role only
2. Console should allow a convenient debug mode toggle

**Comment by tirumaraiselvan** [comment]
Spec:

1. When `HASURA_GRAPHQL_LOG_LEVEL` is set to `debug`, then log the *response* of the action webhook call. The log-type of this should be `action` (similar to `event-trigger` log-type for event trigger responses). The request is already logged as `http-log` so we don't need to log the request again.

2. Watching the logs can be hard during dev, so we will read a header called `X-Hasura-Debug-Mode` which when set to `true` will also show the response body, response headers and response status in the `extensions` key of the error.

**Comment by coco98** [comment]
@tirumaraiselvan Why can't we just do the header debug mode, and not worry about the log-level for now?

> Watching the logs can be hard during dev, so read a header called X-Hasura-Debug-Mode which when set to true alongwith admin role will also show the response body, response headers and response status in the extensions key of the error.
> Note: In future, X-Hasura-Debug-Mode can be used in other places too where we currently throw something like postgres query error, internal error etc.

**Comment by tirumaraiselvan** [comment]
Yes, we can do them independently. But I also *think* log-level bit is not hard at all. The infra is already present.

But we can prioritise `X-Hasura-Debug-Mode` first.

**Comment by tirumaraiselvan** [comment]
Spec:

1. The server accepts a startup env/flag `HASURA_GRAPHQL_DEBUG_MODE` which can be set to `true` (default: `false`). 

2. When server runs with the above flag and a session variable `x-hasura-debug-mode: true` is given (irrespective of role), action response should have the following response:

(This is the same response as `admin` role but with extra keys `request` and `response`)

```
{
  "errors": [
    {
      "extensions": {
        "internal": {
          "type": "http_exception",
          "message": "ConnectionFailure Network.Socket.connect: <socket: 32>: does not exist (Connection refused)"
          "request": {
                "body": {..},
                "headers": [..]
          },
          "response": {
                "status" : 404,
                "body": {..},
                "headers": [..]
          }
        },
        "path": "$",
        "code": "unexpected"
      },
      "message": "http exception when calling webhook"
    }
  ]
}
```

The capture of `headers` in `request`  should follow the guidelines here: https://github.com/hasura/graphql-engine/issues/4171

**Comment by 0x777** [comment]
After having a conversation with @rikinsk and @tirumaraiselvan, we decided on the following implementation: 

Currently, `internal` is returned in a responses with `500` status code only if the request is made by an `admin`, now we change the behaviour to include `internal` only if `dev` mode is enabled, so when `DEV_MODE` is set to `false`, even if an `admin` role makes a request, `internal` should not be included. However, this will be a breaking change in cases where our users are relying on `admin` requests returning `internal` key, so, we will need to introduce an extra flag which will enable the old behaviour. We introduce these two new options:
1. `HASURA_GRAPHQL_DEV_MODE`: `Boolean`, when missing it is assumed to be `false`. 
2. `HASURA_GRAPHQL_PRE_DEV_MODE_INTERNAL_ERRORS`: `Boolean`, when missing it is assumed to be `false`. 

So the final behaviour is as follows: Include `internal` if 
```
dev-mode is set to true 
OR (current_role is admin AND pre-dev-mode behaviour is enabled)
```

**Comment by 0x777** [comment]
I did not address the actual issue in my above comment. If in an action, we have to return an internal error because of the response from the handler, we will need to include the `request` and `response` bodies of the actual call made to the handler in our `internal` object.

**Comment by fr8in** [comment]
@0x777 this is not working as expected in Hasura Cloud. Even with environmental variable HASURA_GRAPHQL_DEV_MODE set as dev. Cloud does not returns internal error for non admin roles. We use triggers for some unique validations and we are not able to show these validation outputs to users.
