### ISSUE TITLE
support custom query fields through actions

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#4032]
Currently actions are only limited to mutations.

**Comment by rakeshkky** [comment]
By default `/v1/query` `create_action` API creates a custom action in mutation root. See [API reference](https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/actions.html#id1). Update the API to create actions in query root. The `definition` will be same as mutation ones except the queries don't have the `kind` (synchronous or asynchronous). To differentiate the actions, introduce the optional `type` in in action `definition` whose value is either `query` or `mutation` and defaults to the later, which enables the backward compatibility. The specimen request as follows

```http
POST /v1/query HTTP/1.1
{
   "type":"create_action",
   "args":{
      "name":"get_weather",
      "definition":{
         "type":"query",
         "arguments":[
            {
               "name":"city",
               "type":"String!"
            },
            {
               "name":"time",
               "type":"String!"
            }
         ],
         "output_type":"WeatherOutput",
         "handler":"https://action.my_app.com/get-weather"
      },
      "comment": "Custom action to fetch weather"
   }
}
```
The `FromJSON` for `definition` has to be custom written in Haskell. First consider `type` and based on this then parse `kind`.

**Comment by shahidhk** [comment]
re-opened for server pr
