### ISSUE TITLE
document using custom graphql types with variables in mutations

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#405]

**Comment by pdobrigkeit** [comment]
I guess this addresses a question that I am having. Is there a way to define or use custom scalars in the graphql schema like for example https://github.com/okgrow/graphql-scalars

**Comment by shahidhk** [comment]
@pdobrigkeit GraphQL types defined in the schema generated by Hasura comes from Postgres types. But you could use those custom scalars in a custom GraphQL server and add it as a remote schema to Hasura.

**Comment by shahidhk** [comment]
@rikinsk I guess this is already documented? Shall we close this issue?

**Comment by marionschleifer** [comment]
I will close this issue as it looks like everything is documented. Feel free to re-open 🙂
