### ISSUE TITLE
docs: improve documentation on metadata / migrations ☂️

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#4050]
We need to document the new metadata / migration workflow.

Along with it, the following issues can be solved:
- Explain migrations vs. metadata
- https://github.com/hasura/graphql-engine/issues/3671
- https://github.com/hasura/graphql-engine/issues/3454
- https://github.com/hasura/graphql-engine/issues/2875
- https://github.com/hasura/graphql-engine/issues/2103
- https://github.com/hasura/graphql-engine/issues/1211
- https://stackoverflow.com/questions/60569095/why-do-automated-hasura-migrations-output-a-metadata-yaml-file

**Comment by dminkovsky** [comment]
If [**this**](https://stackoverflow.com/questions/60569095/why-do-automated-hasura-migrations-output-a-metadata-yaml-file) isn't covered in any of the issues above, please explain that too.
