### ISSUE TITLE
document that event triggers are called via post requests only

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#406]
(Via @bumblebeetuna on discord)

<img width="763" alt="screen shot 2018-09-11 at 5 01 26 pm" src="https://user-images.githubusercontent.com/131160/45357635-77b01700-b5e4-11e8-9568-90091eb97887.png">

**Comment by corysimmons** [comment]
I think it might be worth discussing pros and cons of allowing more than just `POST` endpoints.

Coming from a REST background, I'm inclined to do stuff like `PUT` on updates.

**Comment by shahidhk** [comment]
@corysimmons Let's have the discussion on allowing other methods here: https://github.com/hasura/graphql-engine/issues/416 

Give a :+1: and comment?
