### ISSUE TITLE
ID Scalar does not work when defining Custom Types in Actions

### ISSUE THREAD

**Issue by richardgirges** [hasura/graphql-engine#4061]
### Problem
When attempting to use the `ID` or `uuid` Scalars in the "Actions -> Custom types" section, I'm getting the following error:

```
{
    "path": "$.args[0].args",
    "error": "validation for the given custom types failed because the type \"ID\" for field \"profileId\" in  input object type \"UpdateProfileInput\" does not exist",
    "code": "constraint-violation"
}
```

I assume perhaps Hasrua's `uuid` Scalar is not going to be accessible (although that would be nice), but the docs do mention that `ID` should be useable [here](https://hasura.io/docs/1.0/graphql/manual/actions/types/index.html#inbuilt-scalars).  For now, I'm forced to simply use `String` types in place of `ID` or `uuid` types. 

### Steps to Reproduce
1. Go to `Actions`
2. Go to `Custom Types`
3. Create a new custom type or input that utilizes `ID` or `uuid` as a field type

### Version
graphql-engine:v1.2.0-beta.2

**Comment by tirumaraiselvan** [comment]
@rakeshkky I believe `ID` scalars are supported to be used in custom types. Can you see if this is a bug?

**Comment by rakeshkky** [comment]
@tirumaraiselvan Ideally we should allow all default scalars (defined in GraphQL spec) to be used in custom types without explicitly declaring them.

**Comment by wawhal** [comment]
@rakeshkky I'd like to add, currently Hasura allows using `ID` type of action arguments. But you can't use it in the fields of object types.

**Comment by tirumaraiselvan** [comment]
@rakeshkky Can you determine an `e/` label for this?
