### ISSUE TITLE
console: allow editing action relationship names 

### ISSUE THREAD

**Issue by richardgirges** [hasura/graphql-engine#4062]
### Problem
Whenever I rename the relationship within the `Actions -> [actionName] -> Relationships` tab, a new relationship is inserted instead of updating the old relationship.

### Steps to Reproduce
1. Go to "Actions" in the console
2. Click on an existing action from the left-hand menu
3. Click on the "Relationships" tab
4. Click "Edit" on an existing relationship
5. Change the name of the relationship and hit "Save"
6. A new relationship is created instead of updating the initial relationship.

### Version
graphql-engine:v1.2.0-beta.2

P.S.: thank you all so much for building this amazing feature - it's going to simplify our architecture immensely!

**Comment by wawhal** [comment]
@richardgirges it is a bug. We'll fix it soon. Thanks for reporting :)

**Comment by rikinsk** [comment]
#4072 disables allowing edits to actions relationships. Rescoping this issue to allow editing actions realtionships
