### ISSUE TITLE
create tutorials/guides section

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#407]
Create a tutorials/guides/cookbooks section to show various examples built using graphql engine

**Comment by shahidhk** [comment]
That will be awesome :tada: @mateoholman!

@rikinsk Do you already have some skeleton in mind?

**Comment by rikinsk** [comment]
@shahidhk Don't really have a skeleton in mind. The idea was to put in some content on how Hasura / GraphQL can be used to solve common use cases most app developers face. We can then organise the content if we see better groupings possible.

@mateoholman What sort of sub-sections did you have in mind? Also which tutorial / guides do you think would be a good fit for them? We could definitely do with some help and suggestions.

**Comment by mateoholman** [comment]
@rikinsk @shahidhk I'll put together a rough draft populated with tutorials / guides and open a 'WIP' PR for you to review / comment.
