### ISSUE TITLE
docs: provide examples for URL templating of action handler

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#4073]
There are a lot of queries on discord about this. The current docs reference is just [this](https://hasura.io/docs/1.0/graphql/manual/actions/create.html#set-the-handler). I think this deserves it's own section with an example or two.

cc: @rikinsk @marionschleifer

**Comment by rikinsk** [comment]
@wawhal Can you share links of the questions on discord or what all examples need to be added

**Comment by marionschleifer** [comment]
Closing this in favour of https://github.com/hasura/graphql-engine/issues/4713.
