### ISSUE TITLE
Input for default column value is unnecessarily disabled for PK columns

### ISSUE THREAD

**Issue by beerose** [hasura/graphql-engine#4075]
When modifying the table's columns `default` input field is disabled for columns that are the primary keys. At the same time, it's possible to work around this (by enabling the input) and provide a default value. 

### How to reproduce?

I created a new table with a UUID field, which is also a primary key.  
<img width="904" alt="Screenshot 2020-03-10 at 13 25 18" src="https://user-images.githubusercontent.com/9019397/76312703-e4889800-62d3-11ea-9a16-c62119f10ebd.png">

Then I wanted to modify `default` value for this field, but it is disabled in the UI:
<img width="645" alt="Screenshot 2020-03-10 at 13 25 45" src="https://user-images.githubusercontent.com/9019397/76312711-e7838880-62d3-11ea-812e-be0b470d520a.png">

So I removed `disabled` from this element:
<img width="471" alt="Screenshot 2020-03-10 at 13 27 08" src="https://user-images.githubusercontent.com/9019397/76312710-e7838880-62d3-11ea-8464-d69720923377.png">

I provided `gen_random_uuid()`,  and successfully saved changes:
<img width="642" alt="Screenshot 2020-03-10 at 13 27 21" src="https://user-images.githubusercontent.com/9019397/76312708-e6525b80-62d3-11ea-91a4-0c31924c8252.png">

**Comment by fkhadra** [comment]
Are the screenshots below displaying the expected result ? If yes, I can submit a PR for this :)

<img width="800" alt="Screen Shot 2020-05-04 at 6 39 28 PM" src="https://user-images.githubusercontent.com/5574267/80990600-db7cf880-8e36-11ea-9962-b5fb41bd0c3c.png">

I've tested with different types just to be sure.
<img width="784" alt="Screen Shot 2020-05-04 at 6 40 24 PM" src="https://user-images.githubusercontent.com/5574267/80990625-e899e780-8e36-11ea-8c99-97d5bd53c6d4.png">

**Comment by beerose** [comment]
@fkhadra Yes, for primary key columns only `Nullable` and `Unique` should be disabled, and `Default` should be enabled. For non-primary-key columns everything stays the same.

**Comment by fkhadra** [comment]
Ok cool. You can assign me the issue then :)
