### ISSUE TITLE
Custom errors for constraint violations

### ISSUE THREAD

**Issue by matomesc** [hasura/graphql-engine#4091]
postgres: 11.6
graphql-engine: v1.2.0-beta.1.cli-migrations
provider: docker

Currently if a constraint fails when inserting data the following graphql error is returned:

```js
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "permission-error"
      },
      "message": "Check constraint violation. new row for relation \"user\" violates check constraint \"CHK_user_name_isValid\""
    }
  ]
}
```

This makes error handling and user feedback a nightmare since the client needs to be aware of the database check constraints (not to mention leaking table & constraint name).

It would be better to support custom error for each constraint so that a message and fields affected can be set, for example:

```js
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "permission-error",
        // Optional: custom message for fields affected
        "fields": {
          "firstName": "First name must be longer than 3 characters",
          "lastName": "Last name cannot be empty"
        }
      },
      // Custom constraint message
      "message": "Invalid name"
    }
  ]
}
```

**Comment by tirumaraiselvan** [comment]
Related to https://github.com/hasura/graphql-engine/issues/3658

**Comment by tirumaraiselvan** [comment]
Copying this suggestion in #3658 and closing this one for easier tracking.
