### ISSUE TITLE
add guide on using graphql-engine with flutter

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#410]
https://flutter.io/
https://github.com/zino-app/graphql-flutter

**Comment by jamesgeorge007** [comment]
@shahidhk Is this about updating docs with the respective content?

**Comment by shahidhk** [comment]
@jamesgeorge007, it can be an example flutter project (say a to-do app, with auth) that can go into the `community/examples` directory. A detailed guide can be added as the readme. Let me know if you'd like to pick it up.

**Comment by shahidhk** [comment]
@jamesgeorge007 Are you working on this?

**Comment by ryuzaki3** [comment]
@shahidhk I would like to work on this!

**Comment by shahidhk** [comment]
Go for it @ryuzaki3!

**Comment by jamesgeorge007** [comment]
@shahidhk I would like to work on it as well. But, it's been a while since I had worked with Flutter. So it might take time.

**Comment by shahidhk** [comment]
@ryuzaki3 @jamesgeorge007 I have an idea so that both of you can work on this.

@ryuzaki3 You can work on a building a To-Do application where there are users and users will have to-dos.

@jamesgeorge007 You can work on a blog application where there are authors and articles and author creates articles.

What say?

**Comment by jamesgeorge007** [comment]
@shahidhk I would rather prefer to work with the ToDo App if @ryuzaki3 is Okay :smile:

**Comment by ryuzaki3** [comment]
@jamesgeorge007 I'm ok with anything!. So, yes, I've no problem in working with blog application (:

**Comment by ryuzaki3** [comment]
@jamesgeorge007 I've no problem in working with blog application.. Infact, it's interesting! (:

**Comment by shahidhk** [comment]
@jamesgeorge007 @ryuzaki3 Any updates on this :rofl: ?

**Comment by ryuzaki3** [comment]
@shahidhk Working on it. Will upload it soon 😅

**Comment by jamesgeorge007** [comment]
@shahidhk I'm super busy these days with couple of other works. I'm not sure if I'll be able to work on it anytime soon!

**Comment by marionschleifer** [comment]
We have just released a guide for Hasura + Flutter here: https://learn.hasura.io/graphql/flutter-graphql/introduction 🎉 I'm closing this issue now 🙂
