### ISSUE TITLE
docs: document support for different postgres flavours

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#411]
There are many flavors of postgresql which `graphql-engine` might support out of the box or with slight configuration/modifications. We need to document for each of them.

[TimescaleDB](https://github.com/timescale/timescaledb)
[Yugabyte](https://docs.yugabyte.com/latest/develop/graphql/hasura)
[Aurora - Postgres](https://aws.amazon.com/rds/aurora/postgresql-features/)
[CockroachDB](https://github.com/cockroachdb/cockroach)
[CitusDB](https://github.com/citusdata/citus)
[CrateDB](https://github.com/crate/crate)
[PipelineDB](https://github.com/pipelinedb/pipelinedb)

Current status (note that these have not been officially tested by Hasura and are based on empirical usage):

* Timescale: Fully works
* Yugabyte: Fully works ([officially supported](https://docs.yugabyte.com/latest/develop/graphql/hasura))
* Aurora: Fully works
* Citus: Our permission system doesn't work
* Cockroach: Internals are quite different from postgres (see: #678 )

**Comment by duyleekun** [comment]
CockroachDB hasn't support user defined schema

```
 {"internal":{"statement":"CREATE SCHEMA hdb_catalog","prepared":false,"error":{"exec_status":"FatalError","hint":"See: https://github.com/cockroachdb/cockroach/issues/26443","message":"unimplemented at or near \"hdb_catalog\"","status_code":"0A000","description":"source SQL:\nCREATE SCHEMA hdb_catalog\n              ^"},"arguments":[]},"path":"$","error":"postgres query error","code":"postgres-error"}
```

**Comment by Smerity** [comment]
I could imagine scenarios where as a start-up scales they might shift to CockroachDB from Postgres. From a read and most of a write point of view would it not remain compatible with GraphQL? How frequently are user defined schema changes required in standard Hasura + Postgres operation?

The other feature that would disappear is the live subscription capability but that is an optional extra and Hasura has strong value even without it.

**Comment by shahidhk** [comment]
Thanks for reporting this @duyleekun. 

@Smerity Hasura stores all the metadata on a separate schema called `hdb_catalog`.

Looks like this is a planned feature on CockroachDB. Should land soon.

See https://github.com/cockroachdb/cockroach/issues/26443 and https://github.com/cockroachdb/cockroach/pull/30916

**Comment by Disturbing** [comment]
Hey Guys - is it possible to do the creation of the `hdb_catalog` as a create db versus create schema to support cockroach?

**Comment by shahidhk** [comment]
@Disturbing It will be a big change to the internals. Not something we can immediately support.

**Comment by Disturbing** [comment]
Ok, thanks for the quick response.

Out of curiosity, is there a specific reason why you guys when with SCHEMA
> Table? I personally dont have much knowledge over this, but would love to
hear your perspective

**Comment by shahidhk** [comment]
@Disturbing When Hasura connects to a Postgres instance, the connection is database scoped. It cannot access another database outside of the given one. Hence the logical choice would be to use the namespacing available within a database which is a schema.

**Comment by Disturbing** [comment]
Thanks - makes sense.

**Comment by adamfeldman** [comment]
Hasura is now supported by YugaByte (Postgres-based distributed SQL DB):

https://docs.yugabyte.com/latest/develop/graphql/hasura

(I haven't personally tested this yet)

**Comment by adamfeldman** [comment]
> Looks like this is a planned feature on CockroachDB. Should land soon.
> 
> See [cockroachdb/cockroach#26443](https://github.com/cockroachdb/cockroach/issues/26443) and [cockroachdb/cockroach#30916](https://github.com/cockroachdb/cockroach/pull/30916)

FYI for others who are waiting for this: CockroachDB might implement user-defined schemas sometime this year: https://github.com/cockroachdb/cockroach/pull/30916#issuecomment-600722261

**Comment by zicklag** [comment]
Do all features of Hasura work on Yugabyte? What about this issue: https://github.com/YugaByte/yugabyte-db/issues/1872?

**Comment by gagandeep** [comment]
CockroachDB user-defined schemas RFC got merged in May. https://github.com/cockroachdb/cockroach/pull/30916

Should Hasura works on CockroachDB now?

**Comment by marionschleifer** [comment]
We document Postgres + compatible databases [here](https://hasura.io/docs/latest/databases/postgres/index/).
