### ISSUE TITLE
Current user subscription

### ISSUE THREAD

**Issue by Maxpain177** [hasura/graphql-engine#4112]
We have these tables:

`users (id, user_name)`
`user_stats (user_id, rating, matches_count, etc.)`

We want to make a subscription to the current user (with some relations, like `user_stats`) with this query:

```pgsql
SELECT *
FROM users
WHERE id = X-Hasura-User-Id
```

So, we have two ways to do that:

#### 1.  Make a custom function, using `X-Hasura-User-Id` session variable.

**Pros**:
- We get right typename (`users`)
- We don't have to recreate all permissions for all roles
- We don't have to recreate all relations for other tables

**Cons**:
- This way works only for queries. In subscriptions, this way doesn't support batching/multiplexing

So we can't use this way due to performance reasons.

#### 2.  Make a view, using custom check (`{"id":{"_eq":"X-Hasura-User-Id"}}`) 

**Pros**:
- Subscriptions are multiplexed

**Cons**:
- We get different typename (`users_current` instead of `users`), so we can't reuse cache and the same fragments on our react/apollo frontend. 
- We have to recreate all permissions
- We have to recreate all relations and maintain them.

What we can do?

**Comment by rikinsk** [comment]
@Maxpain177 Any reason you aren't setting the `{"id":{"_eq":"X-Hasura-User-Id"}}` check as a permission rule and then using subscriptions on the `users` table directly?

**Comment by rikinsk** [comment]
@0x777 any insights on the subscriptions bit?

**Comment by Maxpain177** [comment]
@rikinsk Because we want to get not only current user from `users` table

**Comment by kelly-ry4n** [comment]
Can you get the user id from the JWT or otherwise from your auth server, and query users using that and 2 different subscriptions / queries?

```graphql
subscription currentUser {
  currentUser:user(where: {id: {_eq: 1}}) {
    id
    email
  }

}

subscription otherUsers {
    otherUsers:user(where: {id: {_neq: 1}}) {
    id
    email
  }
}
```

**Comment by lexi-lambda** [comment]
I agree with @kelly-ry4n: why not just look up the current user’s id and create a subscription on `users` filtered by that id?

**Comment by 0x777** [comment]
@Maxpain177 

Both the solutions you suggested work (with small changes)

### Using functions:

Subscriptions on functions which accept session variables as their arguments are multiplexed. The function should look something like this:

```sql
create function get_current_user(hasura_session json) returns setof users as $$
  select * from users where id = (hasura_session ->> 'x-hasura-user-id')::Int
$$ language sql stable;
```

Console doesn't yet support tracking functions which require session variables so you'll need to manually hit `/v1/query` endpoint with this query:

```json
{
  "type": "track_function",
  "version": 2,
  "args": {
    "function": {
      "schema": "public",
      "name": "get_current_user"
    },
    "configuration": {
      "session_argument": "hasura_session"
    }
  }
}
```

or it can also be made part of metadata as follows:

```json
{
  "version": 2,
  "tables": [
    {
      "table": {
        "schema": "public",
        "name": "users"
      }
    }
  ],
  "functions": [
    {
      "function": {
        "schema": "public",
        "name": "get_current_user"
      },
      "configuration": {
        "session_argument": "hasura_session"
      }
    }
  ]
}
```

### Using views

To avoid the cons that you listed, you just need to create an object relationship to the users table. So this will be the workflow:

1. create a view called `current_user` as follows:
   ```sql
   create view current_user as select * from users
   ````
2. Create permission on `current_user` for `user` roles as `{"user_id": {"_eq": "x-hasura-user-id"}}`

3. Create a manual object relationship from `current_user` view to `user` table so that you can access all the relationships defined on the user table. Your subscription would look something like this:
   ```graphql
   subscription current_user {
     current_user {
       user {
         id
         stats {
           
         }
       }
     }
   }

You can use any of the above approaches.

**Comment by langfors** [comment]
@0x777 this is massively useful thank you - My team has followed these steps but cannot seem to get the manually created object relation working when using the "Using Views" approach above:

```
{
  current_user {
    id 
    user {
      id
    }
  }
}
```

We are getting the following error:
```
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.current_user.selectionSet.user",
        "code": "validation-failed"
      },
      "message": "field \"user\" not found in type: 'current_user'"
    }
  ]
}
```

We're using the docker image versioned: `hasura/graphql-engine:v1.2.0-beta.2.cli-migrations`.  This is very urgent for us as we're migrating a large project to hasura and have hundreds of queries which rely on a 'get current user' root level query which automatically incorporates JWT identity data.  Thanks so much for hasura - love it so far.

**Comment by makinde** [comment]
In case it is useful to anyone, I'm currently doing the second solution that @0x777 suggested with the views, but with a slightly different approach. I have an object relationship from `users` to `current_user` labeled `isCurrentUser`. That allows me to write queries that don't start with `current_user` at the root. So I can do something like, 
```gql
query MyQuery {
  users(where: { isCurrentUser: {} }) {
    id
    stats {
      ...
    }
  }
}
```

that where clause can use used in any larger query where I need to filter for the current user.

**Comment by wenerme** [comment]
@0x777 method 2 is failed for 2.20

the relationships page is failed with follow request

```http
POST /v1/metadata
```

```json
{"type":"pg_suggest_relationships","args":{"omit_tracked":true,"tables":[null],"source":"App"}}
```

```json
{
  "code": "parse-failed",
  "error": "Error when parsing command suggest_relationships.\nSee our documentation at https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/index.html#metadata-apis.\nInternal error message: \n  Previous branch failure: Error in $: expected Null, but encountered Array\n  Previous branch failure: Error in $: parsing PostgresQualified_TableName failed, expected Object, but encountered Null\nparsing Text failed, expected String, but encountered Null",
  "path": "$.args.tables[0]"
}

```
