### ISSUE TITLE
Get Max value on a distinct field in Hasura GraphQL

### ISSUE THREAD

**Issue by toton6868** [hasura/graphql-engine#4113]
Here is the SQL that is giving the perfect result in General SQL query But I am not able to convert it to Hasura GraphQL

`    select country, max(new_share) from stock_data where date_key > 297 and date_key < 384 group by country order by max(new_share) desc`

I am trying something like this

```
    query CountryNewShare($max_date_key: Int, $min_date_key: Int) {
      stock_data_aggregate(distinct_on: country, where: {date_key: {_gt: $min_date_key}, _and: {date_key: {_lt: $max_date_key}}}) {
        aggregate {
          max {
            country
            new_share
            share_val
          }
        }
      }
    }
```

Unfortunately, It is returning only one value of each field

```
    {
      "data": {
        "stock_data_aggregate": {
          "aggregate": {
            "max": {
              "country": "Vietnam",
              "new_share": 34.2,
              "share_val": 0.63
            }
          }
        }
      }
    }
```

**Comment by rikinsk** [comment]
@toton6868 Seems like you've used `distinct_on` in your query which will just return one result for each country. 

The group_by operation isnt supported and it is recommended to use views to achieve them as demonstrated [here](https://hasura.io/docs/1.0/graphql/manual/schema/views.html#example-group-by-and-then-aggregate)
