### ISSUE TITLE
add option to reload remote schema from inconsistent metadata page

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#4115]
If Hasura cannot reach a remote schema when it starts up, that is marked as inconsistent metadata. 

But, console does not provide an option to reload the remote schema on the inconsistent metadata page.

Was remote schema ever reloaded on the `reload_metadata` action?

If yes, this is a regression (see https://github.com/hasura/graphql-engine/issues/3983) and a fix needs to be applied immediately (or maybe something like what is mentioned in https://github.com/hasura/graphql-engine/issues/3792)

If not, there should a separate button to reload a remote schema when it is part of the inconsistent objects. This needs to be added to CLI too.

**Comment by tirumaraiselvan** [comment]
Yes, this is a console version for the API mentioned in #3792

**Comment by tirumaraiselvan** [comment]
There is also a bug in `reload_remote_schema` which leads to much confusion: https://github.com/hasura/graphql-engine/issues/4117

**Comment by rikinsk** [comment]
Related Server PR: https://github.com/hasura/graphql-engine/pull/4141
 
Update API call on inconsistent metadata page to use the extra config to reload remote schemas if any remote schema is in inconsistent objects

**Comment by beerose** [comment]
Solved by #4141.
