### ISSUE TITLE
document making queries over websockets

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#412]
Document the usage of queries and mutations over websockets.

Apollo's [subscription-transport-ws](
https://github.com/apollographql/subscriptions-transport-ws#full-websocket-transport) supports this.

**Comment by rikinsk** [comment]
related: #353 #472 #994

**Comment by praveenweb** [comment]
The frontend learn tutorials demonstrates the usage of websockets for making queries and mutations as well. For example here's the [reference for the React app](https://hasura.io/learn/graphql/react/subscriptions/1-subscription/) using websockets to make all GraphQL queries.
