### ISSUE TITLE
capture actions telemetry on CLI and server

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#4127]

**Comment by tirumaraiselvan** [comment]
@wawhal Can you suggest what needs to be tracked in server ?

Number of custom types, number of actions, number of action relationships?

**Comment by wawhal** [comment]
Yes @tirumaraiselvan. I want these fields to come in metrics:

```
  actions: { synchronous: <n>, asyncronous: <n> },
  action_relationships: <n>,
  custom_types: <n>
```

**Comment by shahidhk** [comment]
reopening to track server PR

**Comment by tirumaraiselvan** [comment]
server side closed via https://github.com/hasura/graphql-engine/pull/4139
