### ISSUE TITLE
document using variables/aliases/fragments/directives

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#413]

**Comment by dziamid** [comment]
Is it even possible to define a fragment right now?

**Comment by shahidhk** [comment]
@dziamid You can define and use fragments in the GraphQL query. Are you facing any issues?

**Comment by dziamid** [comment]
I surely can, but that would be scoped to a specific query. I was hoping to use a fragment in multiple queries

**Comment by shahidhk** [comment]
@dziamid Can you elaborate on the use case?

**Comment by dziamid** [comment]
Sure, this is essentially from the perspective of DRY and consistency of interfaces. 
e.g I have typescript types like this that I use throughout the app:

```
//global types
type Product = { id: number; title: string; manager: User; ... }
type ProductItem = { id: number; title: string; ... }
type User = {id: number; name: string; email: string;.. }

// component-specific types
type ProductFormValues = Product & {manager: User };
type ProductTableItem = Product & { items: ProductItem[], manager: User }
````

I'm looking to mirror this in queries with fragments like this:

```
// in global scope
fragment product_all { id title }
fragment product_item_all { id title  }
fragment user_all { id name email }

// component specific queries
query ProductFormQuery {
  product {
     ...product_all
     manager { ... user_all }  
  }
}
query ProductTableQuery {
  product {
     ...product_all
     items: { ...product_all }
     manager { ... user_all }  
  }
}
```

I know this comes with a cost of over-fetching, but this is not something I care about, not at least during the prototyping phase.

**Comment by bernardbaker** [comment]
I'm using the online Hasura dashboard to play with GraphQL. But I can't seem to get variables working on the dashboard. Any help ???

**Comment by dziamid** [comment]
‘’’
query ($word: String) { 
  about ...
}
‘’’

**Comment by dziamid** [comment]
I'm currently working around this by interpolating fragments in queries:

```
export const userSelf = gql`
  fragment user_self on user {
    id
    name
    email
    picture
    role
    created_at
    store_id
  }
`;

const projectItemsQuery = gql`
  ${projectSelf}
  ${projectItemSelf}
  ${userSelf}
  query($measuring_not_completed: Boolean) {
    project_item {
      ...project_item_self
      project {
        ...project_self
        manager {
          ...user_self
        }
      }
    }
  }
`;
```

But this comes with a cost of increased payloads. Also feels verbose. Would be nice to merge my custom fragments with the rest of the schema.

**Comment by dziamid** [comment]
For clarity, fragments have to be sent along with every single request and there isn't a way to add them to the schema on serverside?

**Comment by shahidhk** [comment]
@dziamid Yes, fragments have to be sent along with every single request.

**Comment by dziamid** [comment]
This doesn't sound right, can we extend the schema instead on the server so there's no need to send the fragments?

**Comment by shahidhk** [comment]
Doing that would not be spec-compliant: https://graphql.github.io/graphql-spec/draft/#sec-Language.Fragments

**Comment by yaynick** [comment]
@dziamid @shahidhk 
Any advice on optimization techinques if there's really no way to store fragment schema server-side?

Use case: We have a real-time application that involves high frequency queries and mutations on a subset of 17 columns. Our network requirements are fairly strict and it would be great to avoid having to specify all 17 columns along with every http request.

We've already converted all the columns in this subset to bytea, and rolled out our own UDP layer for client to auth server communication and vice versa. But going from client and/or server to the Hasura endpoint seems to leave a lot of potential on the table.

String interpolation and all the abstractions provided by client libraries don't really solve the issue here.

**Comment by jcalfee** [comment]
Anyone have a quick example on how to post the variables for a query?

Still missing..  https://hasura.io/docs/1.0/graphql/core/api-reference/graphql-api/index.html#endpoint

**Comment by jcalfee** [comment]
I get the impression that it is not possible to have a one-off post.  The libraries are keeping a connection open so I suspect curl may not even be easily durable and maybe this is why it is so long trying to get an example added to the docs.
