### ISSUE TITLE
Using SQL where clause in Data tab throws error

### ISSUE THREAD

**Issue by michielmulders** [hasura/graphql-engine#4132]
First of all, I want to thank you for creating a great product! :) 

Today, I wanted to use an SQL statement in the data tab to update one field (I'm not using the GUI for editing a value as I wanted to do a batch of autogenerated SQL statements).

```sql
UPDATE schema.table SET "picture" = "https://some-url" WHERE "address" = "abcde";
```

However, Hasura throws me the following error:
`postgres-error : column "abcde" does not exist`

Can someone point me out if this is a bug or what am I doing wrong?
Thanks!

**Comment by shahidhk** [comment]
@michielmulders In SQL, single quotes (`'somevalue'`) should be used for values and double quotes (`"somecolumn"`) should be used for identifiers like table/column names. 

Your statement should be:
```sql
UPDATE "schema"."table" SET "picture" = 'https://some-url' WHERE "address" = 'abcde';
```
