### ISSUE TITLE
console: design refactor

### ISSUE THREAD

**Issue by beerose** [hasura/graphql-engine#4136]
As we have a design system library, the next step is to start integrating it with the console and replace existing components with the ones from the library. 

The following list is prioritized by the impact (from smallest to biggest) as we want to introduce the design system starting from the least significant components. 

1. No or small impact on the UI:
      - [x] Icon Component
      - [x] Spinner
      - [x] ToolTip
      - [x] Heading

2. Moderate impact:
      - [ ] Text
        - [ ] Text type=explain
        - [ ] Text type=link

4. Significant impact:
    - [ ] Button
    - [ ] AlertBox
    - [ ] Tabs

**Comment by wawhal** [comment]
@beerose should we scope the facilitation of the telemetry events in this PR too?

**Comment by beerose** [comment]
@wawhal How is see it is a bunch of smaller PRs, rather than one covering all of the things above. Unless, of course, someone has time to take care of it all at once. 

We can add more things to the scope of this issue, sure.  Could you also elaborate on what _facilitation of the telemetry events_ means?

**Comment by wawhal** [comment]
@beerose The main idea is to improve our telemetry system by tying it with the user events. Currently redux actions are sent as telemetry events which causes a lot of noise in the database. Instead, if we gather data about the user events, it would make reading the analytics much cleaner and straight forward.

For example: every button can have an identifier. And onClick/onHover/onSomeAction, we can send a telemetry event with that identifier. So currently, when we start integrating the design system, we might want to start passing every button with an identifier.
