### ISSUE TITLE
Console Allowed Queries shows only collections named allowed-queries

### ISSUE THREAD

**Issue by walokra** [hasura/graphql-engine#4138]
Adding query collections to allow-list with using metadata APIs with [add_collection_to_allowlist
](https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/query-collections.html#add-collection-to-allowlist) don't end up showing in Hasura console Allowed Queries list if the collection name is something other than "allowed-queries".

Now the only way to see your collections and allow-list query collections (other than named as "allowed-queries") seems to be is to make SQL queries to HDB talbes.

SELECT * FROM hdb_catalog.hdb_allowlist;
SELECT * FROM hdb_catalog.hdb_query_collection;

Shouldn't the console show all collections from the "hdb_allowlist"?

**Comment by sccalabr** [comment]
I'd like to give this a try. Could you point me in the direction of where the fix would need to be made.

**Comment by bertyhell** [comment]
@sccalabr probably somewhere here: https://github.com/hasura/graphql-engine/blob/527530704d00ebb3c2be807b3ecfc3325e2957ea/console/src/components/Services/Settings/AllowedQueries/AllowedQueriesList.js

**Comment by beerose** [comment]
Solution (first iteration):

Fetch allowed queries from **all** collections and display them in the list (along with information about collection name).

Designs: https://github.com/hasura/product-design/blob/10-enhancements-sm-indexes-allow-list/10-indexes-allow-list/mockups/

**Comment by bertyhell** [comment]
@beerose any chance you could post some of those mockups here, since the link is internal?

**Comment by beerose** [comment]
Closed in https://github.com/hasura/graphql-engine/commit/c597efb65edf71b1b2aa3969a00065cbb47b86c3
