### ISSUE TITLE
API for CI/CD updates to actions

### ISSUE THREAD

**Issue by dazza-codes** [hasura/graphql-engine#4147]
When an action depends on an API handler, updates to anything on the handler need to be updated in the action.  The request/response contract could change and the graphQL types need to be updated.  The handler endpoint or authz headers might need to be updated.  For automation of such updates, is there an API on an hasura instance to target these updates for actions?

**Comment by dazza-codes** [comment]
A related question:  is it possible to define an environment variable or something that can hold some generic elements of action handlers?  If many actions all need to use the same API endpoint and the same request headers, it would be convenient to define these in one place and refer to them in action definitions.  Is this possible?

**Comment by rikinsk** [comment]
@dazza-codes 
- It is possible to template the base url used for actions based on ENV vars as mentioned [here](https://hasura.io/docs/1.0/graphql/manual/actions/create.html#set-the-handler). 

- It is also possible to use ENV vars to template headers across environments. 

  ![Screenshot from 2020-03-23 16-29-33](https://user-images.githubusercontent.com/54616969/77310063-af446700-6d23-11ea-995e-202dcd227eb5.png)

- It is currently not possible to automatically apply the same headers across all actions. But you can manually set up workflows to achieve this either via the metadata apis or by manually editing the metadata files and applying them.

  **Metadata API**: You can use the [update_action](https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/actions.html#update-action) metadata API to set the headers for an action.

  **Metadata file**: If you are using [migrations](https://hasura.io/docs/1.0/graphql/manual/migrations/index.html), you can export the Hasura metadata via the **CLI** with the [metadata export](https://hasura.io/docs/1.0/graphql/manual/hasura-cli/hasura_metadata_export.html) command. If not you can export the metadata via the **console** as shown [here](https://hasura.io/docs/1.0/graphql/manual/migrations/manage-metadata.html#exporting-hasura-metadata).  
  You can then update the metadata for all actions with the corresponding headers and re-apply the metadata.

Hope this helps. Do let us know if you're looking for something more.
