### ISSUE TITLE
type info not found for: 'bigint'

### ISSUE THREAD

**Issue by maarekj** [hasura/graphql-engine#4153]
Hello,
On hasura 1.0.0, I have this error when I use a column of type **bigint** (or return type of function bigint) in my sql.

`{"errors":[{"extensions":{"path":"$","code":"unexpected"},"message":"type info not found for: 'bigint'"}]}`

**Comment by 0x777** [comment]
@maarekj This has been fixed in `1.1.0`, can you try it out and let us know?

**Comment by maarekj** [comment]
Maybe I try it next monday.
Thanks you. 

On my local computer it is good with 1.1.0.
But on the server, it is version 1.0.0

**Comment by 0x777** [comment]
@maarekj I'm closing this for now, please feel free to re-open this if the issue persists.
