### ISSUE TITLE
Cannot rename table with manual relationship to another table

### ISSUE THREAD

**Issue by mklueh** [hasura/graphql-engine#4158]
I´ve created a table "user" and I do want to rename it into something else, as I´ve found out that "user" is a reserved by Postgres.

Trying to rename that leads to

```
[
    {
        "definition": {
            "using": {
                "manual_configuration": {
                    "remote_table": {
                        "schema": "public",
                        "name": "user"
                    },
                    "column_mapping": {
                        "id": "user_id"
                    }
                }
            },
            "name": "user_setting",
            "comment": null,
            "table": {
                "schema": "public",
                "name": "user2"
            }
        },
        "reason": "table \"user\" is not tracked",
        "type": "object_relation"
    }
]
```

According to the Hasura console, table "user" is tracked.

If user is reserved by Postgres and the reason for this issue, Hasura should not allow to create a table with that name.

**Comment by mklueh** [comment]
As a quick fix to not have to recreate every relation in the console I´ve created a backup migration and replaced

in up.sql all

public."user" with public."customer"

and in up.yaml all

- name: user with - name: customer

and restored my schema.

**Comment by 0x777** [comment]
@mklueh Which version of graphql-engine are you using?

**Comment by mklueh** [comment]
@0x777 v1.1.0

**Comment by rikinsk** [comment]
I can confirm that this happens for any table with a manual relationship to another table. The keyword "user" is not related to the issue
