### ISSUE TITLE
Declarative Database Management 

### ISSUE THREAD

**Issue by rohanmuplara** [hasura/graphql-engine#4159]
I want to manage the database with a tool like https://lift.prisma.io/ or sqlalchemy, where the database schema is managed and declared in code. Furthermore, when I make changes to this code, I want easy ways to manage this migration. What is the best way to do this with hasura?

**Comment by rohanmuplara** [comment]
Another thing is that sometimes we have some hasura metadata that gets added and if I am using these external tools to manage the schema, how would that integrate with that metadata

**Comment by rikinsk** [comment]
The [metadata management](https://hasura.io/docs/1.0/graphql/manual/migrations/manage-metadata.html) docs page might be of help. 

You can use your tool of choice to manage the postgres schema migrations across environments. On the Hasura front you will only need to manage the Hasura metadata migrations.
 
In case you have made any changes to the underlying database, you just need to **reload the Hasura metadata** to load the fresh information. In case there is a change that causes an inconsistency between the Hasura metadata and the PG schema, Hasura will go into an inconsistent state which you might have to resolve (by updating/deleting parts of the metadata as required).

**Comment by tirumaraiselvan** [comment]
Closing this as the question has been answered above. Pls comment/reopen if you have further questions.
