### ISSUE TITLE
hasura.exe getting detected as Trojan:Win32/Zpevdo.A and removed by Windows Defender

### ISSUE THREAD

**Issue by mklueh** [hasura/graphql-engine#4161]
I´ve installed the Hasura CLI via **yarn global add hasura-cli** and the contained hasura.exe is frequently getting removed by Windows Defender and marked as Trojan:Win32/Zpevdo.A.

Why is it detected as a trojan and can you do something against it?

**Comment by rikinsk** [comment]
Related #3922

**Comment by shahidhk** [comment]
closed as duplicate
