### ISSUE TITLE
amazon rds postgres 10.4 issue

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#417]
From David on intercom

Add table doesn't work. Seems to be an issue with information schema permissions
https://forums.aws.amazon.com/thread.jspa?threadID=286822

**Comment by ecthiender** [comment]
There are other problems with RDS 10.4 as well (https://forums.aws.amazon.com/thread.jspa?threadID=286822). But they are RDS specific.

[This blog](https://blog.hasura.io/instant-graphql-on-aws-rds-1edfb85b5985) mentions that 10.4 won't work.

**Comment by coco98** [comment]
For those curious, this is the underlying AWS issue: https://forums.aws.amazon.com/thread.jspa?threadID=286822

**Comment by 0x777** [comment]
Works with 10.5 and above
