### ISSUE TITLE
"Remove all permissions" button not working

### ISSUE THREAD

**Issue by sobrinho** [hasura/graphql-engine#4178]
Not sure what's going on, selecting one or many permissions.

![Screen Shot 2020-03-24 at 15 49 19](https://user-images.githubusercontent.com/26460/77465193-08290380-6de7-11ea-923b-105445da729e.png)

Browser: Safari
Hasura: v1.1.0

**Comment by rikinsk** [comment]
@sobrinho Can you confirm if the role for which you were removing all permissions actually had some permissions set for that table?

**Comment by sobrinho** [comment]
@rikinsk there isn't, it is showing the role but without any permission set.

I will make a PR.

**Comment by sobrinho** [comment]
@rikinsk actually, what should happen here?

**Comment by rikinsk** [comment]
@sobrinho Thanks for raising a PR to fix this! In place of hiding the checkbox completely, it would be nicer if we could disable it with a title "No permissions exist".
