### ISSUE TITLE
Valid JWT but hasura still complains about "missing headers"

### ISSUE THREAD

**Issue by elmehalawi** [hasura/graphql-engine#4179]
In the Hasura console, I added a valid JWT that seems to include the required fields:

![Screen Shot 2020-03-24 at 2 54 37 PM](https://user-images.githubusercontent.com/2058016/77471211-e24c3080-6ddf-11ea-91e3-109951b2fce4.png)

The JWT seems to include `x-hasura-user-id`. However, when I run a query, I get the following error:

```json
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "not-found"
      },
      "message": "\"x-hasura-user-id\" header is expected but not found"
    }
  ]
}
```

I don't get this error when I copy and paste the `x-hasura-user-id` into a regular HTTP header under "Request Headers".

Why is Hasura not reading the user id from the JWT as well?

**Comment by ecthiender** [comment]
Hi @elmehalawi ,

Can you share a screenshot of -

1. all the request headers you are sending
2. the query you are making
3. the permissions on the relevant tables

That will help us to debug this

**Comment by elmehalawi** [comment]
Thanks for the reply, @ecthiender. Sure thing. Here are my headers:

![Screen Shot 2020-03-25 at 11 58 32 AM](https://user-images.githubusercontent.com/2058016/77563941-f51e3e00-6e8f-11ea-9cf3-16a5fe0e0154.png)

Here is the query I'm making:

```gql
{
  profile {
    phone
    email
    user_id
  }
}
```

Here are the permissions for the profile table:

![Screen Shot 2020-03-25 at 12 00 54 PM](https://user-images.githubusercontent.com/2058016/77564177-4a5a4f80-6e90-11ea-93b8-3c613bee3d64.png)

---

When I check the last request header, `x-hasura-user-id`, the query runs as expected and only gives me rows that belong to that user.

**Comment by ecthiender** [comment]
@elmehalawi thanks for the info. 

So if you send the `x-hasura-admin-secret` header ,then the JWT is not considered and then it expects you to send other `x-hasura-*` headers directly (hence it complains, it expected `x-hasura-user-id` header as required by the permission).

You should uncheck the `x-hasura-admin-secret` header when sending the `Authorization` header and it should work!

**Comment by elmehalawi** [comment]
That did work. Can't believe I missed that in the docs. Thank you!

**Comment by andywong418** [comment]
@ecthiender How does this work when I have a remote schema though?
