### ISSUE TITLE
console: investigate and possibly update dependencies

### ISSUE THREAD

**Issue by beerose** [hasura/graphql-engine#4189]
In the console, we have a lot of outdated dependencies, which may lead to some security vulnerabilities or issues with the library in the older version not being maintained anymore. From the TypeScript point of view, we may face problems like missing typings or not maintained typings for older versions. 

Updating dependencies will also require an investigation and further discussion with the team, because even if some of the updates will be relatively straightforward, some of them may introduce significant breaking changes. How can we go about that?
a) If we can benefit from the breaking change — we should go with an update and preferably create a new issue for that if this update requires rewriting major parts of the project.
b) If there are no benefits or there are some disadvantages for us coming with the new version (like entirely new API that we don't want to use), we don't have to update this dependency. We can leave it or think about removing this library from the project or replacing it with an alternative.

Example
We are using `react-table` in version v.6.x, but in the newest v7.x, the library API completely changed (from React components to hooks). If (after discussion) we are okay with the new API and see it as an improvement, then there should be an issue created for this describing how we go about the refactor — whether we want to use `react-table` in our design system or use it somehow else.

Otherwise, if we decide we don't want to go with the new `react-table` API, we can either leave it as it is (as long as it doesn't make any troubles) or get rid of it by a) using other similar solution, b) creating our abstraction on tables. The second option (getting rid of the lib) would also require creating a separate issue for it. 

---

The point of this issue is to investigate which libs are straightforward to update and update them. For the rest, decide whether we want to leave it or upgrade it. Choosing the second option requires creating a new issue for a particular lib.

**Comment by lastnamearya** [comment]
also while updating move <code>prettier</code> from dependencies to devDependencies.
