### ISSUE TITLE
I try the hello query remote schema from glitch and now I cant deleted

### ISSUE THREAD

**Issue by brokercl** [hasura/graphql-engine#4192]
I try the hello query remote schema from glitch and now I cant deleted

**Comment by rikinsk** [comment]
@brokercl Can you share some more details. What exactly are you not able to delete? Some steps to reproduce the issue will be of great help

**Comment by praveenweb** [comment]
@brokercl - If you are looking to delete the remote schema that you added, you can do so via the Console Remote Schemas page. 

Closing this. Feel free to re-open if you have more specific details.
