### ISSUE TITLE
docs: add docs for setting up the actions service for using codegen efficiently

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#4198]
We provide starter-kti with some of the codegen frameworks and runtimes. It will be helpful to have a end to end guide where the user:
1. Starts from scratch and sets up the action service (using the starter-kit)
2. Creates an action
3. Sets up the action handler in the action service

**Comment by coco98** [comment]
@wawhal Please do put in a few lines of description for this issue. 😭
