### ISSUE TITLE
Can't write to table directly when event trigger is set up

### ISSUE THREAD

**Issue by dysrama** [hasura/graphql-engine#4199]
I have a number of schemas owned by a specific service and Hasura on top.
Each service connects to postgres with it's own user that only allows access to its specific schema.
My issue is, that even since setting up events in Hasura, the owner of the schema can't do writes to any tables with an event attached anymore.
The specific error is "pq: permission denied for schema hdb_catalog".

I've tried granting permissions for the schema owner to hdb_catalog, they are listed in information_schema.role_table_grants but is_grantable is set to NO. I don't know why this doesn't work.

I could have my services connect with the same user as Hasura, but the schema separation is there for a reason, and I would prefer to keep this as is.

Any suggestions on how to fix this?

**Comment by dysrama** [comment]
To reproduce (might also better explain the issue): 
- add role X and role Hasura
- add a schema with owner X
- give role Hasura access to schema
- expose schema in Hasura and add an event trigger to update
- add some records
- use postgres to update a record directly to cause the "pq: permission denied for schema hdb_catalog" error

**Comment by tirumaraiselvan** [comment]
@dysrama Thanks for the instructions. I will try to repro this, there might be few other permissions required.

**Comment by tirumaraiselvan** [comment]
@dysrama Event triggers work by inserting an event log into the `hdb_catalog.event_log` table.

For your role X, granting the following permissions should do the trick:

```
GRANT USAGE ON SCHEMA schema hdb_catalog TO X;
GRANT INSERT ON hdb_catalog.event_log TO X;
```

**Comment by dysrama** [comment]
@tirumaraiselvan 
Thanks, that did the trick. I had given GRANT all to hdb_catalog, but apparently I was missing usage.
Thanks for the quick help :)
