### ISSUE TITLE
react-router should be upgraded to react-router 4

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#42]

**Comment by praveenweb** [comment]
- [ ] Change `<Link>` imports
- [ ] `onEnter` is not supported in v4. Move all onEnter to react's lifecycle methods.
- [ ] Update HTML structure
- [ ] Update dependencies like react-router-redux

**Comment by wawhal** [comment]
@praveenweb this can’t be done. react-router-redux does not work with v4. However, keeping this issue open to see if anybody has alternatives.

**Comment by abenhamdine** [comment]
https://github.com/supasate/connected-react-router works with react-router (and AFAIK is the only alternative since react-router-redux is deprecated).

It works with react-router v4 but you have to install from git for that : see https://github.com/supasate/connected-react-router/issues/80

**Comment by abraha2d** [comment]
supasate has released a new version of connected-react-router on npm that works with react-router v4.  No more need to install from git.

**Comment by abenhamdine** [comment]
> supasate has released a new version of connected-react-router on npm that works with react-router v4. No more need to install from git.  

Yes, good catch.
