### ISSUE TITLE
console: allow customising root fields of single row mutations

### ISSUE THREAD

**Issue by vhiairrassary** [hasura/graphql-engine#4203]
First of all, thanks for Hasura ❤️

I am using Typescript and I would like to use camel case convention. As of 1.2.0-beta.2, I can set some `Custom GraphQL Root Fields` for a table but it seems the following are missing (screenshot attached):
- Delete By PK
- Insert One
- Update By PK

Also, I am currently using (abusing?) the `Custom GraphQL Root Fields` feature for camel case support. Would love to have a setting to set this convention globally and everything is automatically converted. Linked issue: https://github.com/hasura/graphql-engine/issues/3320

<img width="402" alt="Screenshot 2020-03-26 at 18 09 05" src="https://user-images.githubusercontent.com/6972399/77675189-e5385400-6f8c-11ea-8471-cb373d7abee3.png">

**Comment by vhiairrassary** [comment]
It seems there is also the same issue with `<relationship_name>_aggregate` field as well:
<img width="373" alt="Screenshot 2020-03-26 at 18 36 26" src="https://user-images.githubusercontent.com/6972399/77677944-bcb25900-6f90-11ea-8a12-b7ab5389646a.png">

**Comment by wawhal** [comment]
Hey! Thanks for reporting :)
GraphQL Engine actually supports customising root fields for single row mutations as well. It is just not implemented on the console UI. We are working on it.

In the meanwhile, you can use this API as a workaround:

```
POST /v1/query HTTP/1.1
Content-Type: application/json
X-Hasura-Role: admin

{
   "type": "set_table_custom_fields",
   "version": 2,
   "args": {
     "table": "author",
     "custom_root_fields": {
        "select": "Authors",
        "select_by_pk": "Author",
        "select_aggregate": "AuthorAggregate",
        "insert": "AddAuthors",
        "insert_one": "AddOneAuthor",
        "update": "UpdateAuthors",
        "update_by_pk": "UpdateAuthor",
        "delete": "DeleteAuthors",
        "delete_by_pk": "DeleteAuthor"
     },
     "custom_column_names": {
        "id": "authorId"
     }
   }
}
```

As for `relationship_aggregate` customisation, @rakeshkky can you look at this?

**Comment by vhiairrassary** [comment]
Thanks!
