### ISSUE TITLE
fail to connect no WebHook url endpoint in docker toolbox (windows)

### ISSUE THREAD

**Issue by wemersonrv** [hasura/graphql-engine#4206]
Hello, i would like to report an issue on version 1.1.0 when try to fire an Event Trigger.

Environment:

OS: Windows 10 64 Bits
Docker Environment: Docker Toolbox with Virtualbox
Hasura: v1.1.0
Webhook URL: http://host.docker.internal:8000/api/client-cache-reset 

The webhook is working in OS host outsite docker containers... at:  http://127.0.0.1:8000 so i need to use internal network address (**host.docker.internal**) to sent it to host on windows. Try access via IP... not works too!

**IMPORTANT: Try to access webhooks from anoter remote endpoints, locally on my network and on internet too. It's not connecting. Something is blocking hasura to connect outside the container.**

```json
{
    "message": "\"HttpExceptionRequest Request {
        host                 = \"host.docker.internal\"
        port                 = 8000
        secure               = False
        requestHeaders       = [(\"Content-Type\",\"application/json\"),(\"User-Agent\",\"hasura-graphql-engine/v1.1.0\")]
        path                 = \"/api/client-cache-reset\"
        queryString          = \"\"
        method               = \"POST\"
        proxy                = Nothing
        rawBody              = False
        redirectCount        = 10
        responseTimeout      = ResponseTimeoutMicro 60000000
        requestVersion       = HTTP/1.1
    }
        (ConnectionFailure** Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just \"host.docker.internal\", service name: Just \"8000\"): does not exist (Temporary failure in name resolution))\""
}
```

**Comment by tirumaraiselvan** [comment]
@wemersonrv This is a little off-topic but from https://docs.docker.com/toolbox/toolbox_install_windows/, it says

> Docker Toolbox is for older Mac and Windows systems that do not meet the requirements of Docker Desktop for Mac and Docker Desktop for Windows. We recommend updating to the newer applications, if possible.

Regardless of the problem in hand, is it possible to use Docker Desktop for Windows?

**Comment by wemersonrv** [comment]
> @wemersonrv This is a little off-topic but from https://docs.docker.com/toolbox/toolbox_install_windows/, it says
> 
> > Docker Toolbox is for older Mac and Windows systems that do not meet the requirements of Docker Desktop for Mac and Docker Desktop for Windows. We recommend updating to the newer applications, if possible.
> 
> Regardless of the problem in hand, is it possible to use Docker Desktop for Windows?

Nope! No Docker Desktop!

I'm using Docker Toolbox just to not use HyperV. I use Genymotion for android emulation, so need Virtualbox and it not works fine when HyperV is enabled. So, the solition is to use Docker Toolbox.

**Comment by tirumaraiselvan** [comment]
From a quick Google search, it doesn't seem easy to connect to host machine from inside the container on Docker Toolbox. `host.docker.internal` also appears to be a `Docker for Windows` thing.

You can look through the options here: https://forums.docker.com/t/accessing-host-machine-from-within-docker-container/14248/15 

You can also ask for a suggestion from Docker support/community channels.

**Comment by praveenweb** [comment]
@wemersonrv - Closing this as it's more of a Docker Toolbox issue than a Hasura issue.
