### ISSUE TITLE
How can i simplify queries

### ISSUE THREAD

**Issue by Bwolfs2** [hasura/graphql-engine#4218]
I have something like this:
products {
  name,
  price,
  brand {
    name
  }
}

Which produces this response:

{
  "data": {
    "products": [
      {
        "name": "Black Dress",
        "price": 520,
        "brand": {
          "name": "Coach"
        }
      }
    ]
  }
}

so, can this:
"brand": {
  "name": "Coach"
}

be simplified to this somehow?

"brandName": "Coach"

I find somthing using "_get" but i don't know how to reply on Hasura something like that.

I find graphQl solution here: 
https://stackoverflow.com/questions/54251285/how-to-simplify-graphql-response

**Comment by 0x777** [comment]
@Bwolfs2 
> I find somthing using "_get" but i don't know how to reply on Hasura something like that.

This isn't standard GraphQL and we don't support it. If you want to flatten the fields, you can use views. Assuming you have a table called `product` and `brand`, create a view as follows:
```sql
create view product_brand as
select product.*, brand.name as brandName
from product 
left outer join brand
on (product.brand_id = brand.id)
```
From the console, track this view and then you can query it as follows:
```graphql
query {
  product_brand {
    name
    price
    brandName
  }
}
```

**Comment by tirumaraiselvan** [comment]
Closing this now. Pls feel free to reopen if you have any followup questions regarding this.
