### ISSUE TITLE
add a current version badge to readme

### ISSUE THREAD

**Issue by mklueh** [hasura/graphql-engine#4225]
Just a small request. Would it be possible to show the current build version the last docker image is based on somewhere? Because one always has to navigate through the documentation just to land on

https://github.com/hasura/graphql-engine/blob/master/install-manifests/docker-compose/docker-compose.yaml

to look it up in the yaml file.

**Comment by shahidhk** [comment]
@mklueh What about the releases page? https://github.com/hasura/graphql-engine/releases

**Comment by mklueh** [comment]
@shahidhk sure, but you could also just put a badge in your readme so everyone can see it immediately like:

![Current Hasura version](https://img.shields.io/github/v/release/hasura/graphql-engine?label=version&style=for-the-badge)

from

https://shields.io/category/version
