### ISSUE TITLE
Multiple OR relationships not working

### ISSUE THREAD

**Issue by himat** [hasura/graphql-engine#4230]
Hi, I want to connect a table with filters in my frontend to a graphql hasura query.

When I try the below, I get error: "There can only be one input field named _or"

But in my frontend I allow people to filter by both distance and weight columns, and if a field is null, I still want it to be returned, which is why I want to put _or's around both fields.

```
{
  loads(limit: 3, 
    where: 
    	{origin_loc: {_ilike: "%gatos%"}, 
       dest_loc: {_ilike: "%%"},
       origin_cost: {_lte: 200},
       dest_cost: {_lte: 200},
       _or: [
       {distance: {_lte: 20000}},
       {distance: {_is_null: true}}
      ],
       _or: [
       {weight: {_lte: 20000}},
       {weight: {_is_null: true}}
      ]
       
      }
  ) 
  {
    id
    load_id
  }
}
```

Is there any way to achieve what I'm trying by filtering multiple fields and including all null values?

**Comment by karthikvt26** [comment]
You can add multiple `_or` inside `_and`
```
_and: [
  {
    _or: ...
  }
  {
    _or: ...
  }
]
```

The above roughly translates to
```
Filter by applying the first `_or` condition `and` filter by applying the second `_or` condition
```
