### ISSUE TITLE
How to properly build filter queries

### ISSUE THREAD

**Issue by himat** [hasura/graphql-engine#4231]
Is there a good way to build filter queries?

I have a frontend table with search filters on each column. And when new text is typed in one of the filters, I want to send it to my backend to filter the data server-side (on Hasura)

Should I just use a base gql query string in my code, and then somehow insert new lines in the `where` clause every time a new filter gets added?

For example, I could use this as my base query string
```
{
  boxes( 
    where: 
     {
      }
  ) 
  {
    id
    origin_loc
    dest_loc
    pickup_datetime
    pickup_datetime_end
    dropoff_datetime
    dropoff_datetime_end
    price
    weight
    details
    load_source
    load_url
  }
}

```

And then if the user inputs something in the price filter, I then add `price: {_lte: 200},` into my base query?
So that it looks like 
```
boxes( 
    where: 
     {
        price: {_lte: 200},
      }
  ) 
```

How would I do this? Is this the best way to do this (this seems pretty weird/inefficient) to me.

**Comment by gradinarot** [comment]
I dont know if I'm getting you right but you can try to use the include if directive. hope this helps

**Comment by himat** [comment]
@gradinarot  I think the directives only work for including fields to be return, you can't use them for including where clauses. So that wouldn't work here.

**Comment by karthikvt26** [comment]
@himat You can configure `variables` in your `where` clause and send appropriate `variables` at query invocation site. You can also mark a particular variable as optional. 

Take a look at this link for ref: https://hasura.io/docs/1.0/graphql/manual/queries/variables-aliases-fragments-directives.html#using-variables
