### ISSUE TITLE
Hasura-cli downloading from github

### ISSUE THREAD

**Issue by dostalradim** [hasura/graphql-engine#4233]
Hi, when I install hasura-cli with npm, the package is trying to download binary from github. But my servers are behind proxy, how can I tell the hasura-cli package to use my http/s proxy? I put proxy setting in npm config but it did not help.

Thank you

**Comment by shahidhk** [comment]
@dostalradim Please open the issue here: https://github.com/jjangga0214/hasura-cli

The npm package is maintained by community contributors :smile: They'll be able to help you.

**Comment by dostalradim** [comment]
Oh, sorry
