### ISSUE TITLE
Explorer:_or: square brackets are not generated

### ISSUE THREAD

**Issue by alukos** [hasura/graphql-engine#4234]
graphql-engine v.1.1.1
When press in Explorer: when > _or:
expected: ```query MyQuery {
  users(where: {_or: [{}]})
}```
actually:```query MyQuery {
  users(where: {_or: {}})
}```

**Comment by rikinsk** [comment]
@alukos Thanks for reporting this. This issue is already being tracked at #3322.

Closing this as a dup.
