### ISSUE TITLE
event triggers invocation log broken with `Cannot read property 'columns' of null`

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#4243]
Repro app here: http://hasura-v1.herokuapp.com/console/events/manage/triggers/testtrigger/logs

![image](https://user-images.githubusercontent.com/8663570/77935979-d8d73280-72cf-11ea-8ce5-73037dfb2e62.png)

**Comment by beerose** [comment]
It looks like it's solved now. Closing the issue.
