### ISSUE TITLE
console: search implementation in invocation logs of event triggers

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#4244]
Currently, the search in event triggers is broken.
As we fix it, we should decide how the search must be implemented. Just providing the filter query like we do for other tables is good IMO, just there are a bunch of more clicks involved.

Ideas? @rikinsk @tirumaraiselvan

**Comment by beerose** [comment]
What about creating a new column that concatenates information from all other columns that we want to search by and filter only by this new column?

I wrote about this solution some time ago [here](https://www.aleksandra.codes/speed-up-query).

**Comment by beerose** [comment]
Solved in https://github.com/hasura/graphql-engine/pull/4732.
