### ISSUE TITLE
Possible to use fragments for where filters?

### ISSUE THREAD

**Issue by himat** [hasura/graphql-engine#4247]
I need to get an aggregate count in addition to the objects of my graphql query.
Is it possible to make a fragment for the `where` filter fields so that I can reuse those in both `loads_aggregate` and `loads` so that I don't have to duplicate all the `where` filters?

I tried to in the hasura graphiql editor, but was getting syntax errors.

```javascript
query main($limit: Int, $origin_loc_filter: String, $distanceFilter: Float, $weightFilter: money) {
  loads_aggregate (where: {
    origin_loc: {_ilike: $origin_loc_filter},
     dest_loc: {_ilike: "%%"},
      distance: {_lte: $distanceFilter},
      weight: {_lte: $weightFilter} 
  }) {
    aggregate {
      totalCount: count
    }
  }
  loads(limit: $limit, offset: 0,
  	where: {
      origin_loc: {_ilike: $origin_loc_filter},
         dest_loc: {_ilike: "%%"},
      distance: {_lte: $distanceFilter},
      weight: {_lte: $weightFilter} 
    }) {
  id
  price
  weight
  distance
}

}
```

**Comment by rikinsk** [comment]
Fragments in arguments are not in the graphql spec. To get around this, you can form the entire where clause on the client and pass it as a variable and which you can use in both the queries.

**Comment by tirumaraiselvan** [comment]
Closing this as the question has been answered above. Pls comment/reopen if you have further questions.
