### ISSUE TITLE
Can you pass variables to order_by?

### ISSUE THREAD

**Issue by himat** [hasura/graphql-engine#4249]
Is it possible to pass a variable to use as a field name when sorting?

```javascript
query($order_by_key: String)
{
 tables (order_by: {$order_by_key: desc}) // I want to put a variable here
  {
  ...
  }
}
```

This is a pretty critical operation for me to allow my users to sort by whatever column they want in a table. So if this is not possible, this seems like a huge failing on the part of graphql?

**Comment by himat** [comment]
Solved with help by nwylie 

```
query ($order_by: tables_order_by!) {
  tables(order_by: $[order_by]) {
    ...
  }
}
```

with variables:
```
{
  "order_by": {
    "column": "asc"
  }
}
```

**Comment by s-kris** [comment]
Corrected query format for future readers:
```
query ($order_by: tables_order_by!) {
  tables(order_by: [$order_by]) {
    ...
  }
}

```

**Comment by en-ahsanali** [comment]
How can we do with the nested tables.?
I want to apply orderBy in this type of scenario.
tables -> subTables -> columnName
