### ISSUE TITLE
indicate access key is set in the console context

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#426]
server:

add a variable `isAccessKeySet: true` to the context if access key is set so that console can prompt the login page.

console:

show login page when the variable is set to true

**Comment by shahidhk** [comment]
re-opening for console changes

**Comment by dsandip** [comment]
@karthikvt26 You need to triage this or pick it up this week. @coco98

**Comment by shahidhk** [comment]
Re-opening to add the same variable in CLI also.

**Comment by shahidhk** [comment]
CLI cannot add the variable as it does not know if access key has been set or not! Better handling on console side is required.
