### ISSUE TITLE
add "identity" column ID + PK in frequently used columns list

### ISSUE THREAD

**Issue by GavinRay97** [hasura/graphql-engine#4279]
In Postgres 10, a feature called "identity columns" was released:
https://www.2ndquadrant.com/en/blog/postgresql-10-identity-columns

The difference is:
```sql
CREATE TABLE test_old (
    id serial PRIMARY KEY,
    payload text
);

CREATE TABLE test_new (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload text
);
```

The issue with "serial", is that it's expanded into this:
```sql
CREATE SEQUENCE test_old_id_seq;

CREATE TABLE test_old (
    id int NOT NULL PRIMARY KEY,
    payload text
);

ALTER TABLE test_old
    ALTER COLUMN id SET DEFAULT nextval('test_old_id_seq');

ALTER SEQUENCE test_old_id_seq OWNED BY test_old.id;
```

Besides that it creates a lot of unnecessary overhead as a side-effect, the permissions on sequences need to be managed separately/individually, and it makes for a huge pain when attempting to do something like this:

```sql
INSERT INTO test_old (payload) VALUES ('a'), ('b'), ('c') RETURNING *;

CREATE TABLE test_old2 (LIKE test_old INCLUDING ALL);
INSERT INTO test_old2 (payload) VALUES ('e') RETURNING *;
 id | payload
----+---------
  4 | e          <-- keeps the sequence from the parent table
```

Because Hasura doesn't currently have a button to copy an existing table structure, and `serial` expands into an owned-sequence so you can't use `LIKE some_table`, it becomes tedious to make variants of tables.

Now the tables are undesirably/unintentionally linked, and trying to fix your mistake becomes another pain-point:
```sql
=> DROP TABLE test_old;
ERROR:  cannot drop table test_old because other objects depend on it
DETAIL:  default for table test_old2 column id depends on sequence test_old_id_seq
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

It would be really nice to have `int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY` be the default option (because I assume this is what most people would rather have) or at least a Frequently-used option :pray:

**Comment by tirumaraiselvan** [comment]
We should definitely have this as an option in frequently used list. But I am not sure of the effort involved in replacing this over `serial` as that would involve PG version >= 10 check.

Hasura supports PG >= 9.5
