### ISSUE TITLE
Update logs for better analysis

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#428]
Having the following information in logs will make it convenient to analyze the performance of frequently run queries (and subsequently tune by tweaking Postgres indices, etc.):

* total query response time
* query parsing time 
* R.T.T from Postgres
* query hash + name

**Comment by ecthiender** [comment]
@dsandip we already have query hash + name, and total query response time. 

Also, wouldn't Postgres tweaking be more easily done by `explain/analyze`-ing the generated sql?

**Comment by dsandip** [comment]
`we already have query hash + name, and total query response time.` - Cool. Just the other 2 then.

@ecthiender @0x777 @coco98 I believe the idea was to have an interface in the console (GraphiQL) itself where this can be looked at/ analyzed.

**Comment by dsandip** [comment]
Closing this in favor of #507
