### ISSUE TITLE
Firefox Can't establish connection with ws adress

### ISSUE THREAD

**Issue by clementvp** [hasura/graphql-engine#4289]
I'm using Hasura with Caprover (A self Hosted Heroku like).

My app (create react app) use subscriptions with some tables.
I use Appolo Graphql (create connection with wslink)

Everythings works fine with Chrome or in the Hasura console (No error at all, loaded data, realtime data), but in Firefox (latest version), console says:  Firefox cant'establish a connection with the ws://<my-hasura-endpoint>

Caprover use nginx hunder the hood as a reverse proxy with a good configuration for websockets.

I'm missing something ? It is a Firefox bug?  A appoloGraphql bug ?

**Comment by johnniehard** [comment]
@clementvp What was the issue? Having similar trouble.

**Comment by clementvp** [comment]
That is i'm a bad developer who let Ublock Origin activated in his dev environment.
I feel such ashamed.

Good to know, Ublock Origin block ALL the websocket connexions. AdBlock don't.

Sorry for the inconvenience.

**Comment by johnniehard** [comment]
No worries, there's so much to keep track of, and many opportunities for making mistakes.

But I don't think it's true that Ublock Origin blocks websocket connections by default. For example: https://www.websocket.org/echo.html runs just fine for me, and I've done no configuration of Ublock.

I think my problem was that I was using `ws://` and not `wss://` for the url. Working fine now.
