### ISSUE TITLE
Problem querying bigint field

### ISSUE THREAD

**Issue by garlou** [hasura/graphql-engine#4291]
Hi guys.
I'm having empty results on a query like this when there is valid instances on database:
```
query($id: bigint!) {
  Trips(where: {vehicleId: {_eq: $id}}) {
    id
  }
}
------------------------------------
{
  "id": 17037803064488544
}
```
If I change _eq to _gte it returns some values but _lte doesn't. I think the arguments must be suffering some internal conversion to a smaller number.
The only workaround for this I found is to change database fields from bigint to string.
I haven't found any duplicated issue. 
Thanks

**Comment by tirumaraiselvan** [comment]
@garlou Can you check if your server is running with the `--stringify-numeric-types` flag? https://hasura.io/docs/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html#command-flags

**Comment by garlou** [comment]
@tirumaraiselvan thanks. I did not know about that flag. I haven't tried yet but I definitely will. I'll post here the results when I do.

**Comment by garlou** [comment]
Thanks @tirumaraiselvan it worked!
