### ISSUE TITLE
Column type selection does not cover all cases

### ISSUE THREAD

**Issue by SnirShechter** [hasura/graphql-engine#4300]
When creating/altering a column, the column type selection is **not flexible enough** to contain all types, specifically the **types' arguments**.

### Example
Through the specific use-case in which I've encountered the error:
- We have an existing database with a column of type `varchar(64)`
- When trying to alter a column, the update is set to change (by default) the `varchar(64)` to `character varying()`, even if nothing was actually edited.

### Steps to reproduce
- Setup
  - Postgres
    - Create a Postgres database
    - Add a table with a column of type `varchar(64)`
  - Hasura
    - Run an instance and connect to the database
    - Track the table you created
- Reproduce
  - Click on the table -> _Modify_ -> click on the column's _Edit_
  - Click on _Save_ (without changing anything)

The update will try to change the type from `varchar(64)` to `character varying()`.

### Expected behavior
Probably one of two solutions (or a mix):
- A custom `<input>` for type selection in case the `<select>` is not flexible enough.
- An extra `<input>` for type arguments.

**Comment by felipedaraujo** [comment]
@SnirShechter Hasura documentation says that `character varying` is an alias of `varchar` https://hasura.io/docs/1.0/graphql/manual/api-reference/postgresql-types.html#string. The Postgres documentation also says that https://www.postgresql.org/docs/9.1/datatype-character.html.

**Comment by rikinsk** [comment]
Related to #4215

**Comment by rikinsk** [comment]
Ideally the console should not have modified the the column type unless intended. This is a bug which we'll fix soon.

**Comment by rikinsk** [comment]
I am closing this issue in favour of #4215. Please reopen this is you are expecting a different behaviour.
