### ISSUE TITLE
Safe way to delete redundant migration

### ISSUE THREAD

**Issue by schwichti** [hasura/graphql-engine#4305]
Hi,

Is it safe to delete a migration from the hard disk?
Me and my collegue created the same migration on our respective local development environment and pushed them to our shared git repository.
Now, we want to delete one of these redudant migrations.
Is that a safe way to fix this?
* Rolling back redundant migration on local Hasura
* Delete migration folder from local hard disk
* Push changes to git

Thanks for giving us hasura.

**Comment by GavinRay97** [comment]
If the migrations are entirely identical, it's completely safe to delete one of the copies from your code and source control.

You can also delete migrations that negate each other. For example:
- Sometimes you may create a relationship, maybe do a few things in-between, and then decide that wasn't the right relationship and remove it. 

Now you have two migrations that combined effectively do nothing and negate each other. You can either go through and manually delete this, or attempt to `squash` them with the CLI.

**Comment by GavinRay97** [comment]
I want to follow up with a comment about workflows when developing and generating migrations:

If you are in early stages, and you don't have a Hasura instance live in Production that needs isolated migrations, it can be easier to use a flow where you do a daily (or more) "save"/"checkpoint" of the database by using `init --from-server`. Especially if you are iterating heavily on your data models.

With this, you would do some work on your schema and relationships/permissions, **not with the CLI and generating migrations**, but from the web console. After you are satisfied with the progress you have made, you can do an `init --from-server`, and replace the old "checkpoint" with the new one. If you commit these, you have single-file "save states" that can replicate your DB state at one point in time.

Or, **you can use the `squash` command and try to merge all the migrations into one, or segment them out and comment them by logical function.** For example, `all_users_columns_and_metadata` migration containing the table create + relationships + permissions. This is a lot cleaner and easier to work with that dozens or hundreds of migration files.

This is only the case if you don't have something in production already though unfortunately :sweat_smile:

**Comment by tirumaraiselvan** [comment]
Closing this as the question has been answered above. Pls comment/reopen if you have further questions.
