### ISSUE TITLE
cli: actions_use_codegen, clone the starter kit before asking for output_dir

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#4311]
Currently, the starter-kit is cloned after all the inputs are taken from the user. This causes bad DX because the user cannot input the `output_dir` as the path to the starter-kit's src.

**Comment by coco98** [comment]
@wawhal By clone you mean download zip and uncompress right?

**Comment by wawhal** [comment]
@coco98 the repo is cloned and updated by the CLI. So by clone, I mean copy the starter kit directory.

**Comment by rikinsk** [comment]
closed via https://github.com/hasura/graphql-engine/commit/8a5cc73ae6ec77ae72b10d2892021755d1a0a9df
