### ISSUE TITLE
posix regular expression operator 

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#4317]
Currently, for regex match operations we have `_similar` and `_nsimilar` operators. These are based on Postgres' SIMILAR operator which is based on SQL standard definition of regular expression.

Postgres also has POSIX regular expression which might be more common in usage: https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP

We can add these operators to permissions and graphql schema.

**Comment by christophediprima** [comment]
Is there some progress ont that? 
It looks like nobody is interested in searching with regular expressions? Is there another way to do it?

We wanted to use  `SIMILAR %(b|d)%` but it is not key sensitive and `ILIKE` doesn't look to support regular expressions.

**Comment by trevordilley** [comment]
Would make a text search of users against both their first and last names much more straightforward!

**Comment by christophediprima** [comment]
Is there any progress on this issue? It would help a lot in making searches faster.

**Comment by christophediprima** [comment]
We cannot use lookAhead properly with SIMILAR TO
