### ISSUE TITLE
After  creating x-hasura-admin-secret , not able to add any data in Hasura table from flutter frontend

### ISSUE THREAD

**Issue by kiran321** [hasura/graphql-engine#4331]
After adding x-hasura-admin-secret in hasura, not able to perform any operation from Flutter, manually  I am able to add data in the table .

**Comment by rikinsk** [comment]
Hey. After setting an admin secret your GraphQL endpoint is protected from unauthorized access. See docs on [Hasura auth](https://hasura.io/docs/1.0/graphql/manual/auth/index.html) for more information on setting up authorization. If you would like your GraphQL API to be public see docs on [Unauthenticated access](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/unauthenticated-access.html) 

Hope this helps
