### ISSUE TITLE
workaround jwk_url non-conformance for Auth0

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#4335]
Auth0 doesn't publish JWK which is conformant to RFC. 

The [library](https://hackage.haskell.org/package/jose-0.8.0.0) that we use mentions this:

> The Auth0 software produces objects with an [invalid "x5t" parameter]( https://community.auth0.com/questions/7227/certificate-thumbprint-is-longer-than-20-bytes). The datum [should be a base64url-encoded SHA-1 digest]( https://tools.ietf.org/html/rfc7515#section-4.1.7), but Auth0 produces a base64url-encoded hex-encoded SHA-1 digest. The object can be repaired (example) so that this library will admit it, unless the offending parameter is part of the JWS Protected Header in which case you are out of luck (until Auth0 bring their implementation into compliance).

A (partial) workaround is mentioned here: https://github.com/frasertweedale/hs-jose/issues/54#issuecomment-356460452

We can think about incorporating this as a special case.

**Comment by ecthiender** [comment]
I have an issue tracked in Auth0 community:
https://community.auth0.com/t/jwk-certificate-thumbprint-is-invalid/16070/19

The last update is that the Auth0 engineering team is working on the fix.

**Comment by tirumaraiselvan** [comment]
Seems like Auth0 has fixed the jwk_url : https://community.auth0.com/t/jwk-certificate-thumbprint-is-invalid/16070/22
