### ISSUE TITLE
ConnectionFailure Network.Socket.connect: <socket: 42>: does not exist when i try to access action from graphiql

### ISSUE THREAD

**Issue by Relaxe111** [hasura/graphql-engine#4340]
hello I've followed tutorial for creating a action (hasura 1.2. beta 3) and ive get following error when i try to call it from graphiql:

```
{
  "errors": [
    {
      "extensions": {
        "internal": {
          "type": "http_exception",
          "message": "ConnectionFailure Network.Socket.connect: <socket: 42>: does not exist (Connection refused)"
        },
        "path": "$",
        "code": "unexpected"
      },
      "message": "http exception when calling webhook"
    }
  ]
}
```
if i call directly api it works as expected.
here is defined action in console:
![image](https://user-images.githubusercontent.com/40892030/78835463-80e7ac80-79f0-11ea-9c3b-a4c7b51c600d.png)

here is my code on express js:
//@ts-check

```
import fetch from "node-fetch";
import express from "express";
import bodyParser from "body-parser";
import { HASURA_FIND_USER } from './queries/find_user.query'
import { HASURA_OPERATION } from "./queries/authenticate_log.mutation"

const app = express();

const PORT = process.env.PORT || 8000;

app.use(bodyParser.json());

app.post('/hello', async (req, res) => {
  return res.json({
    hello: "world"
  });
});

// Request Handler
app.post('/sign-in', async (req, res) => {

  // get request input
  const { email, password, customer_name } = req.body.input;

try{
    // run some business logic
    let result = await execute({email, password, customer_name},HASURA_FIND_USER)
    
    console.log("test")

    if(result.errors){
      return res.status(400).json(result.errors[0])
    }
    const { users } = result.data

    if(users.length !==1) return res.status(400).json({message:"wrong credentials please try again!"})
    console.log(users[0].customer_users.customer)
    const { 
      id:user_id, 
      customer_users
    } = users[0]
    if(customer_users.length!==1) return res.status(400).json({message:"wrong credentials pleas try again!"})
    
    const {
      brukerBrukerNavn,
      brukerRegion,
      customer:{
        accessible_services,
        id:customer_id
      }
    }= customer_users[0]

    console.log('console log result after firs request: ', user_id, brukerBrukerNavn,brukerRegion, accessible_services,customer_id );


    // execute the Hasura operation
    let { data, errors } = await execute({ user_id: user_id, customer_id: customer_id  },HASURA_OPERATION);

    // if Hasura operation errors, then throw error
    if (errors) {
      return res.status(400).json(errors[0])
    }

    // success
    return res.json({
      ...data.insert_authentication_logs
    })
}catch(e){

  return res.status(500).json(`${e}`)
}
});

app.listen(PORT);






// execute the parent operation in Hasura
const execute = async (variables:any, operation:string) => {

  
  const fetchResponse = await fetch(
    "http://localhost:7000/v1/graphql",
    {
      method: 'POST',
      headers:{
        "x-hasura-admin-secret":"customersservice"
      },
      body: JSON.stringify({
        query: operation,
        variables: variables
      })
    })
  const data = await fetchResponse.json();
  console.log('DEBUG: ', JSON.stringify(data));
  return data;
};
```

**Comment by tirumaraiselvan** [comment]
Since Hasura runs inside a container, it has a different network than the host network so `localhost` generally doesn't work (unless your container is configured to use the `host` network)

Anyway, you can reach the host using a fixed IP that is OS dependent:

With Docker for Mac/Windows: Use `http://host.docker.internal:8000/hello`

On Linux: Typically `172.17.0.1` i.e the IP address of docker0 interface. use `ip addr show docker0`

**Comment by Relaxe111** [comment]
Hello thnakyou for answer. 
I am on linux.
 I've checked ip address of docker0 interface and it is as you wrote here:
![image](https://user-images.githubusercontent.com/40892030/78881506-36e5e180-7a57-11ea-89be-888737ca2c33.png)
After I added this ip adress to url ive get following:
```
{
  "errors": [
    {
      "extensions": {
        "internal": "content type of response is \"text/html\"",
        "path": "$",
        "code": "unexpected"
      },
      "message": "not a valid json response from webhook"
    }
  ]
}
```

**Comment by Relaxe111** [comment]
Update: Its not hits action server when i call from graphiql

**Comment by Relaxe111** [comment]
I found the issue. It is because i used wrong adress in the handler input. For linux It should look like: 
![image](https://user-images.githubusercontent.com/40892030/79022904-4c562b00-7b7f-11ea-9d0d-3d2e55bc5cb7.png)

**Comment by s3dm** [comment]
I had the same problem, I am running on my Ubuntu machine hasura graphql engine from a docker container by mapping host port 8001 to docker container port 8080. Therefore GraphiQL is accessible at http://localhost:8002/console. In the same host I am running FastAPI, i.e. Uvicorn running on http://localhost:8882. 

In this scenario if you want to access the endpoint from hasura docker engine the IP:Port of the handler is:

## http://172.17.0.1:8882/signin

Guys it will help a lot users that are running hasura from docker if you make a warning or notice in the documentation about the IP:PORT address.

**Comment by AndrewPahomovOtto** [comment]
Thank you guys! You save my nerves and the time :)
Use Hasura / Docker / Ubuntu and **http://172.17.0.1:3000/way** work for me
