### ISSUE TITLE
add networking section to docs

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#4346]
Add a networking section to the docs.

Tables with the following dimensions:
- OS: Mac/windows/linux
- External API (in docker or outside docker)
- URL for Hasura to API connectivity
- URL for API to Hasura connectivity

**Comment by tirumaraiselvan** [comment]
Some content is available in the `Note` here: https://hasura.io/docs/1.0/graphql/manual/remote-schemas/index.html#step-2-merge-remote-schema
