### ISSUE TITLE
jwt claims should be case-insensitive

### ISSUE THREAD

**Issue by ecthiender** [hasura/graphql-engine#435]

**Comment by corysimmons** [comment]
Especially confusing since it seems like some headers aren't case sensitive. Example: https://github.com/hasura/sample-auth-webhook/blob/bb2c30afa7b5a87de8edd25959e3d28ec88bfb4d/firebase/firebaseHandler.js#L41-L42

**Comment by yairopro** [comment]
So should we (users of hasura engine) should set the `X-Hasura-*` claims in:

- lower case, ie `x-hasura-*` ?
- upper case, ie `X-HASURA-*` ?
- mixing case, ie `X-Hasura-*` ?
- it doesn't matter, it's insensitive ?

**Comment by corysimmons** [comment]
I think it's just insensitive. Test it out.
