### ISSUE TITLE
Docs for action body don't reflect actual action body

### ISSUE THREAD

**Issue by anisjonischkeit** [hasura/graphql-engine#4362]
I just added a hasura action and decoding into my type failed, turns out the docs are not consistent with the implementation.

docs type:
```
{
  "action": "<action-name>",
  "input": {
    "arg1": "<value>",
    "arg2": "<value>"
  },
  "session_variables": {
    "x-hasura-user-id": "<session user id>",
    "x-hasura-role": "<session user role>"
  }
}
```

raw body received by my handler:
```
{
    "session_variables": {
        "x-hasura-role": "admin"
    },
    "input": {
        "fbAccessToken": "akddsad"
    },
    "action": {
        "name": "loginWithFB"
    }
}
```

so action is not just the name, but actually an object containing a name.

**Comment by marionschleifer** [comment]
This is now fixed in the docs: https://hasura.io/docs/1.0/graphql/manual/actions/action-handlers.html#http-handler.

**Comment by anisjonischkeit** [comment]
The example on that page still seems to be the old format. Also, I would have thought that the intended behavior would be `action: string` (the way it was originally documented)... I can't see a use case for other things going into that actions object (when you do already have `input`), am I missing something here?

**Comment by marionschleifer** [comment]
Hi @anisjonischkeit 👋 not sure if this is a caching problem with docs. Does the HTTP handler show up like this?:

```
{
  "action": {
    "name": "<action-name>"
  },
  "input": {
    "arg1": "<value>",
    "arg2": "<value>"
  },
  "session_variables": {
    "x-hasura-user-id": "<session user id>",
    "x-hasura-role": "<session user role>"
  }
}
```

**Comment by anisjonischkeit** [comment]
HTTP Handler shows up fine, example doesn't 🤔

**Comment by marionschleifer** [comment]
@anisjonischkeit you're totally right. I'll fix this right away! Thank you for reporting!
