### ISSUE TITLE
Unable to do nested insert with object relationship

### ISSUE THREAD

**Issue by leoalves** [hasura/graphql-engine#4366]
When doing a nested insert with an object relationship the relationship_id is never sent to the child.

How to reproduce it:

Table **user**
  - id: gen_random_uuid()
  - name: text

Table **user_info**
  - id: gen_random_uuid()
  - email: text
  - user_id: uuid with unique constraint with a foreign key to the user table

Add relationship in Hasura.

Nested insert mutation
```graphql
mutation {
  insert_user (objects: {
    name: "test",
    user_info: {
      data: {
        email: "test@domain.com"
      }
    }
  }) {
    affected_rows
  }
}
```

Error returned
```graphql
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.insert_user.args.objects[0].user_info.data",
        "code": "constraint-violation"
      },
      "message": "Not-NULL violation. null value in column \"user_id\" violates not-null constraint"
    }
  ]
}
```

If I remove the object relationship and create an array relationship instead. The same mutation will work

Hasura v1.1.1

Thanks

**Comment by tirumaraiselvan** [comment]
@leoalves Are these one-to-one relationship? If yes, this might be the caveat mentioned here: https://hasura.io/docs/1.0/graphql/manual/schema/relationships/database-modelling/one-to-one.html#current-limitations-with-nested-mutations

**Comment by leoalves** [comment]
Yeah that's exactly it.
Thanks for the quick response.
I will close this.

**Comment by oliverpool** [comment]
You should be able to work around the caveat by performing the insert the other way around:
```graphql
mutation {
  insert_user_info (objects: {
    email: "test@domain.com",
    user: {
      data: {
        name: "test"
      }
    }
  }) {
    affected_rows
  }
}
```
