### ISSUE TITLE
[Bug report] cli migrate metadata v2, not support empty action argument

### ISSUE THREAD

**Issue by ghost-void** [hasura/graphql-engine#4367]
Action defined
```
type Mutation {
  hello: WorldOutput
}
```

Run `hasura metadata apply`

"failed to apply metadata: cannot apply metadata on the database: [parse-failed] key \"arguments\" not present ($[0].actions[1].definition)"

**Comment by tirumaraiselvan** [comment]
Fixed by https://github.com/hasura/graphql-engine/pull/4285

Will be released in `v1.2.0-beta.4`
