### ISSUE TITLE
BigInts not inserting properly

### ISSUE THREAD

**Issue by zcaudate** [hasura/graphql-engine#4368]
I've encountered a strange error on hasura v1.1.0. I'm storing time information as bigints and found that the initial insert does not create the right number in the database.

For example:
15866102209964 becomes 493018540
1586610220996 becomes 1767288772

When updating, the bigints update as normal.

I don't know where these numbers come from and am wondering if anyone has encountered this before and how it can be solved.

An example query:

```
mutation {
  insert_domain_category(objects: {description: "New Category", deleted: false, color: "#9B5456", name: "Ah", update_time: 15866102209964, update_op: "*vbnhaunefuxt", id: "ah", create_time: 1586610220996, create_op: "*vbnhaunefuxt"}) {
    returning {
      id
      name
      color
      description
      create_op
      update_op
      create_time
      update_time
      deleted
    }
  }
}

```

produces:

```
{
  "data": {
    "insert_domain_category": {
      "returning": [
        {
          "id": "ah",
          "name": "Ah",
          "color": "#9B5456",
          "description": "New Category",
          "create_op": "*vbnhaunefuxt",
          "update_op": "*vbnhaunefuxt",
          "create_time": 1767288772,
          "update_time": 493018540,
          "deleted": false
        }
      ]
    }
  }
}
```

**Comment by zcaudate** [comment]
The same problem exists when I updated to v1.2.0-beta.3

**Comment by zcaudate** [comment]
I did a bit more investigation and I think it has to do with the type being wrongly coerced as an integer.

Only the lower 32 bits are kept when inserting, the higher 32 bits are thrown out

```
  (Long/toBinaryString 15866102209964)
  => "11100110111000011101011000101101110110101100"

  (Long/toBinaryString 493018540)
  =>                "11101011000101101110110101100"

  (Long/toBinaryString (- 15866102209964
                          493018540))
  => "11100110111000000000000000000000000000000000"
```

**Comment by zcaudate** [comment]
When the bigints are entered as the string, the data is correct. I'll use this as a workaround.

`{create_time: "15866102209964"}`, as opposed to {create_time: 15866102209964}

**Comment by tirumaraiselvan** [comment]
@zcaudate Indeed it's a bug and will be solved by https://github.com/hasura/graphql-engine/issues/576

Your workaround for using "string" values is correct. Also, you should use `--stringify-numeric-types` flag in the server to get the response as string (there can issues with sending large numbers as Int as well): https://hasura.io/docs/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html#command-flags

**Comment by zcaudate** [comment]
Oh sweet! Thanks for the quick response.

**Comment by zcaudate** [comment]
Ah great. Thanks for confirming. I was tearing my code apart trying to figure out what was happening because updates work fine but not inserts.

Looking forward to the fix.
