### ISSUE TITLE
support Postgres functions as Action handlers

### ISSUE THREAD

**Issue by cpursley** [hasura/graphql-engine#4369]
The Actions announcement indicates that Postgres functions can be used as Action handlers. However, I haven't been able to find docs covering this nor usage examples.

https://hasura.io/blog/introducing-actions/

**Comment by rikinsk** [comment]
Actions in its initial release will not be supporting PG functions. This functionality should be added in the coming releases. 

Closing this issue for now.

**Comment by tirumaraiselvan** [comment]
Changing the title to track the feature.

**Comment by cpursley** [comment]
@tirumaraiselvan is there an estimate or timeline for this feature? Thank you.

**Comment by cpursley** [comment]
Is there an update on an expected release for Postgres Action handlers?
