### ISSUE TITLE
[QUESTION] How to enforce multiple mutations?

### ISSUE THREAD

**Issue by perrosnk** [hasura/graphql-engine#4370]
Our app enables users to send each other, some units.
So User A send User B, 1 unit.
We should check if User A balance is enough, decrement User A balance, increment User B balance, insert a "transaction" in the Transactions table.

Checking the User A balance >0 can be done through the rules.

But how can I enforce the client to send multiple mutations within a single mutation?

Would the best architecture be:
1. Disallow all changes for the client. The clients calls a serverless function, and the function sends to Hasura a properly formatted mutation with all the necessary mutations included.
2. Allow the client to make changes, but call an Action which will be a serverless function and from there send a properly formatted mutation with all the necessary mutations, and then send the result back to the client.
3. Is there a better way?

Taking the example give in the docs:
```javascript
mutation reset_author {
  delete_article (
    where: {author_id: {_eq: 6}}
  ) {
    affected_rows
  }
  update_author (
    where: {id: {_eq: 6}}
    _set: {name: "Cory"}
  ) {
    returning {
      id
      name
      articles {
        id
        title
      }
    }
  }
}

```

Is it possible to enforce the client to delete the article ONLY IF he ALSO updates the author?

**Comment by GavinRay97** [comment]
**From your requirements:**
- User A sends User B 1 **"unit"**
- We should check if User A balance is enough
- Decrement User A balance
- Increment User B balance
- Insert a "transaction" in the Transactions table.
- Checking the User A balance >0 can be done through the rules

As you may know, anything sent from the client inherently cannot be trusted. The suggested architecture for something like this, would be to allow the client to invoke an Action, which runs a custom handler/function that performs this logic in several steps.

A rough pseudocode example of this might be:

```js
const transactionHandler = async (req, res) => {
  const { sending_user_id, receiving_user_id } = req.body
  const sendingUser = await query(/** user where ID is sending user ID **/)
  if (!sendingUser.balance) res.status(401).send({ message: "Insufficient balance" })
  // You may not need this receiving user step, depending on your response shape
  // Perhaps it can be done in a single insert query
  const receivingUser = await query(/** user where ID is receiving user ID **/)
  const result = await query(/** update the users balances here **/)
  return res.send(result)
}
```

**Comment by perrosnk** [comment]
Thank you for your reply @tirumaraiselvan.
Unfortunately we can't trust the "sendingUser" query to query for the balance because there could be another mutation running at the same time which is simultaneously decrementing the balance.
So we need to rely on constraints.
I wanted to ask you if we call an action, and then within the action we send a SINGLE mutation with multiple mutations within:

```javascript
const transactionHandler = async (req, res) => {
  const { sending_user_id, receiving_user_id } = req.body

const mutation = `mutation send {
  update_user(
    where: {id: {_eq: sending_user_id}}
    _inc: {balance: -amount}
  ) {
    returning {
      id
    }
  }
  update_user(
    where: {id: {_eq: receiving_user_id}}
    _inc: {balance: amount}
  ) {
    returning {
      id
    }
  }
  insert_transaction_one(
    object: {
      amount: amount,
      sending_user_id: sending_user_id,
      receiving_user_id: receiving_user_id,
    }
  ) {
    id
    amount
  }
}`

  const result = await query(/** update the users balances here **/)
  return res.send(result)
}

```
I am coming from sequelize which when you run increment, it doesn't automatically validate the Model against the constraints, so you needed to run `.validate` afterwards.
1. Does hasura respects the constraint `amount > 0` if we run a mutation like this?
2. Would a mutation like this protect us from other mutations decrementing the balance at the same time?
3. If we get an error from the decrementing mutation, all other mutations will fail too, right?

**Comment by tirumaraiselvan** [comment]
@perrosnk 

There are two ways to solve the above problem:

1. Using the above multiple mutations (in a single operation) that you presented: This will be run in a transaction: https://hasura.io/docs/1.0/graphql/manual/mutations/multiple-mutations.html#execution. But you need to perform a check that `sending_user_id.balance > 0`. This can be done by setting an `update` [permission rule](https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/permission.html#updatepermission) to check the value or a postgres check constraint.

2. In your Action handler which performs the business logic, you can run the entire thing in a transaction via the upcoming [graphql-tx](https://github.com/hasura/graphql-engine/pull/3557) (tbr in v1.3). For now, you can also use sequelize in your Action handler to do a more programmatic transaction similar to what Gavin showed above.

**Comment by perrosnk** [comment]
Thank you both for your replies! (I mistakenly tagged @tirumaraiselvan instead of @GavinRay97)

I have already set a constraint like this:
<img width="718" alt="Screen Shot 2020-04-14 at 11 53 34 AM" src="https://user-images.githubusercontent.com/10828675/79205453-9e7ca200-7e46-11ea-8bb1-5eea7f20471d.png">


So I guess I don't need to do anything else. I wanted to confirm that if I run a multiple mutations in a single operation, the constraints will be respected, throw an error, and revert all other mutations in the operation.

P.S. So, for us the only thing that keeps us from using hasura is the [fact](https://github.com/hasura/graphql-engine/issues/3573) that we cannot increment numeric fields yet. It doesn't seem to be a way around it, apart from using sequelize, building models, instances etc, which was one of the reasons why we want to migrate from it and start using hasura.
