### ISSUE TITLE
Default value does not accept HTTP URL (Postgres error)

### ISSUE THREAD

**Issue by Tchoupinax** [hasura/graphql-engine#4371]
Hello,

I tried to add a default value in Hasura as an URL but Postgres threw an error:

![image](https://user-images.githubusercontent.com/9136206/79053238-175bde00-7c3c-11ea-81b5-9d4e5a78b912.png)

I guess that the URL should be between quote in this query because Postgres does not like the charactere `:`. :)

I do not have the knowledge of your project to know where to edit this and if it is the good way to fix that. 

Thank you for your awesome work ! :)

**Comment by rikinsk** [comment]
@Tchoupinax I attempted to do this for a column of type `text` and it seems to work. Can you confirm the type of the `imageUrl` column in your schema

**Comment by Tchoupinax** [comment]
@rikinsk Hello, my column is typed as `character varying`.
What is it the problem with that ? I can change but i would like to understand. ^^

Is `varchar` a bad practice to store URL or other string ?

**Comment by rikinsk** [comment]
@Tchoupinax No no. I was just querying to help debug the issue. This is definitely a bug.

**Comment by Tchoupinax** [comment]
Great. Tell me if you need other information. ;)

**Comment by rikinsk** [comment]
Till this is fixed, a workaround would be to surround the default values with single-quotes. eg. `'<value>'`

**Comment by Tchoupinax** [comment]
Yeah, to continue my work i performed manually the query with quote as you suggested and now it works.
For details, Hasura shows this:

![image](https://user-images.githubusercontent.com/9136206/79123291-1d67d100-7d9a-11ea-8799-51c05dd8d811.png)
