### ISSUE TITLE
Inconsistent migration SQL column type `integer` vs `int4` on table creation vs schema modification. Hasura console automatically generated migration file unnecessary ALTER COLUMN statements for aliased type integer->int4 on editing a column property up.yaml down.yaml.

### ISSUE THREAD

**Issue by slimlime** [hasura/graphql-engine#4380]
When altering an integer column in console, saving a change such as Nullable from true to false generates an unnecessary ALTER COLUMN statement in up.yaml (and corresponding rollback statement down.yaml) which updates the `integer` column type to `int4`, which is an alias of the same `integer` type. 

This unnecessarily adds noise to migrations and version control. 

There may be a broader base issue around superficially disparate types.
* Types on table **creation** such as `numeric`/`decimal` and `integer`/`int`/`int4` and other aliases should **maintain the same type** on **modification** for migration files.

Semantic decision on keeping customisability vs developer preference for naming things (one of the two hard challenges in computer science) (https://hasura.io/docs/1.0/graphql/manual/api-reference/postgresql-types.html).
Generates noise in migration files and version control.

Fix by checking reference list of aliased types to prefer keeping consistent (the initially set type) to reduce noise of functionally consistent statements (redundant). Would also be prudent to check consistent with the creation (although the aliased type checking should cover this case, would prefer solidly defined Hasura type alias preference)

https://github.com/hasura/graphql-engine/issues/4215.
https://github.com/hasura/graphql-engine/issues/4300 (varchar).
Noting with additional context as optimised migration should be consistent for all aliased types and an issue specifically for `int4` has not been linked.

 ### Example

 * Create table with `integer` someNumber attribute.
 * When altering a column, the update is set to change (by default) the `integer` to `int4`, even if nothing was actually edited.
 
 ### Steps to reproduce
 * Setup
   
   * Hasura
     * Setup per [Quickstart])https://hasura.io/docs/1.0/graphql/manual/getting-started/docker-simple.html_
     * Setup migrations per guide [Migrations for a new database and Hasura instance
](https://hasura.io/docs/1.0/graphql/manual/migrations/new-database.html#migrations-new-db)
     * Add a table with a column of type `integer`
     * Track the table you created
 * Reproduce
   
   * Click on the table - _Modify_ - click on the column's _Edit_
   * Click on _Save_ (without changing anything or changing an arbitrary property like null)
 
 The update will change the type from `integer` to `int4`.
 
 ### Expected behavior
Keep consistent type (especially with Hasura preferred type on **table creation**) when existing column type is an alias https://hasura.io/docs/1.0/graphql/manual/api-reference/postgresql-types.html 
https://www.postgresql.org/docs/12/datatype.html

**Comment by slimlime** [comment]
long-name
#namingthingsishard

**Comment by rikinsk** [comment]
Closing this and tracking it via #4215
