### ISSUE TITLE
Error: "no mutations exist" - Actions

### ISSUE THREAD

**Issue by costas90** [hasura/graphql-engine#4382]
**Version** v1.2.0-beta.3
**Deployed** on Heroku
**Front-end framework** Vue

**Expected result:**
Use action to send a base64 string to an action handler.

**The problem**
When I run the action mutation from the console GraphiQL, it works. But when I try to send a fetch post request from the front-end it fails with:

> extensions: {path: "$", code: "validation-failed"}
> message: "no mutations exist"

![image](https://user-images.githubusercontent.com/18027867/79080165-231ed180-7d1c-11ea-9f42-557ce4209f7f.png)
![image](https://user-images.githubusercontent.com/18027867/79080378-0505a100-7d1d-11ea-85f9-855a3654cbc7.png)
Note that the mutation in GraphiQL is tested with the `Authorization 'Bearer ${token}' header

**Code in the front-end:**
```
import fetch from 'isomorphic-fetch';

const SET_PROFILE_PICTURE = `
  mutation ($base64str: String!, $name: String!, $type: String!) {
    setProfilePicture(base64str: $base64str, name: $name, type: $type) {
      image_path
    }
  }
`;
const fileName = this.file.name;
      const fileType = this.file.type;
      const result = await this.toBase64(this.file).catch(e => Error(e));
      if (result instanceof Error) {
        console.log('Error: ', result.message);
        return;
      }
      const variables = { name: fileName, type: fileType, base64str: result };
      const url = 'https://kw-api-v2-staging.herokuapp.com/v1/graphql';
      const options = {
        method: 'POST',
        headers: {
          'content-type': 'application/json'
        },
        body: JSON.stringify({
          query: SET_PROFILE_PICTURE,
          variables: variables
        })
      };
      console.log("variables", variables);
      console.log("SET Profile PIC", SET_PROFILE_PICTURE);

      fetch(url, options)
        .then(res => res.json())
        .then(res => {
          console.log(res)
          this.file = null;
        })
        .catch(err => {
          console.log(err);
        });
```

**Comment by hgiasac** [comment]
@costas90 Did you debug returned role from auth webhook? I think it returns anonymous role that isn't allowed to run this action. Moreover, I don't see where you input `authorization` token header in your code

**Comment by costas90** [comment]
@hgiasac right! I normally use Apollo on the app and forgot that I have to set the Authorization headers manually also here.

What is the proper way for debugging this? Because I noticed the webhook didnt fire so I shouldnt be able to debug it. What exactly do you mean by auth webhook? I use Auth0. 

Should I be using apollo to send this request or fetch is much better for base64 uploads?  Not sure what the difference is, since I am sending a string in both cases.

**Comment by hgiasac** [comment]
@costas90 You can check in HGE log's `user_vars`, for example:

```json
{
  "type":"http-log",
  "timestamp":"2020-04-13T17:59:07.222+0000",
  "level":"error",
  "detail":{
     "operation":{
        "user_vars":{"x-hasura-role":"admin"},
        "error":{
            "path":"$",
            "error":"The email address is already in use by another account.",
            "code":"auth/email-already-exists"
        },
       "request_id":"418c3fb6-e7e3-4573-876a-f888673519c2",
       ...
     ,"http_info":{"status":200,"http_version":"HTTP/1.1","url":"  /v1/graphql", "ip":"172.21.0.1","method":"POST","content_encoding":null}
}}
```

If access token is verified successfully, user role can be show in http-log

**Comment by costas90** [comment]
Thanks, just added papertrail to my heroku app.

**Comment by Overdozed** [comment]
check you provide HASURA_GRAPHQL_UNAUTHORIZED_ROLE env var without any quotes from .env file. 
In my case hasura logs said {"x-hasura-role":"\"public\""} => double double quotes.

Hope this helps.
