### ISSUE TITLE
[Question] How to handle/init/persist migrations in Docker Image

### ISSUE THREAD

**Issue by mubaidr** [hasura/graphql-engine#4387]
If someone is using Hasura (cli-migrations) docker image, what is the recommended way to `init` migrations and share metadata and migrations with host?

_I could not find anything related to docker management in the documentation. All information is about when running docker locally._

**Comment by GavinRay97** [comment]
The workflow you can use with Docker/Kubernetes and the `.cli-migrations` image is to make a custom `Dockerfile` where you copy the migrations folder from the host to the container and let it apply them.

If you are using the V2 migrations format:

```dockerfile
FROM hasura/graphql-engine:v1.2.0-beta.3.cli-migrations-v2
COPY migrations /hasura-migrations
COPY metadata /hasura-metadata
```

If you are using the V1 format:

```dockerfile
FROM hasura/graphql-engine:v1.2.0-beta.3.cli-migrations
COPY migrations /hasura-migrations
```

Assuming that your migrations/metadata are stored in those directories. You can also customize the location from which Hasura reads migrations/metadata by setting environment variables:

```yaml
HASURA_GRAPHQL_MIGRATIONS_DIR=/custom-path-for-migrations
# V2 Only
HASURA_GRAPHQL_METADATA_DIR=/custom-path-for-metadata
```

The workflow looks like this:

* Dockerfile copies metadata/migrations automatically
* `.cli-migrations` image applies them on start
* Use the Hasura CLI to make changes to your schema/metadata
	- They will be applied now on your instance but will also have the migrations generated for them
	- So creating a fresh container instance will replicate the same state as your current one

Do you think the documentation would be improved by putting more information about the specifics of the entire workflow, outside of what pertains to CI/CD here?

https://hasura.io/docs/1.0/graphql/manual/migrations/auto-apply-migrations.html#

**Comment by mubaidr** [comment]
Thanks for the quick feedback. 

I am using `hasura/graphql-engine:v1.2.0-beta.3.cli-migrations-v2` and as you recommended, I have added volume mounts to the project location one confusion solved. 

Now: 
- start engine using `graphql-engine serve` (which runs at default port 8080) and I can type 
`http://127.0.0.1:5434/v1/version` in browser to get `{"version":"v1.2.0-beta.3"}`
- start console using 
```bash
hasura-cli console --project project --no-browser --skip-update-check --admin-secret ${HASURA_GRAPHQL_ADMIN_SECRET} --console-port 80
```
which starts successfully (i guess) because i get message: 
```bash
{"level":"info","msg":"console running at: http://localhost:80/","time":"2020-04-14T13:57:02Z"}
```

But I am unable to access console from the browser. There is no response at the specified port.

**Comment by GavinRay97** [comment]
Does it work without `--console-port`? on the default port `localhost:9695`?

**Comment by mubaidr** [comment]
I have tried different ports, but still nothing.

**Comment by mubaidr** [comment]
Console started using command: 
```bash
hasura-cli console --no-browser --project /hasura/project --skip-update-check --admin-secret ${HASURA_GRAPHQL_ADMIN_SECRET} --console-port 9090 --api-port 9091
```

I get following data using curl: 

```bash
curl http://localhost:9090
```

```js
window.__env = {
        apiHost: "http://localhost",
        apiPort: "9693",
        cliVersion: "v1.2.0-beta.3",
        dataApiUrl: "http://localhost:8080",
        dataApiVersion: "",
        adminSecret: "password",
        urlPrefix: "/",
        consoleMode: "cli",
        cliUUID: "24b31770-bd1c-46d4-9434-14a20e11c1d9",
        enableTelemetry:  false ,
        assetsPath: "https://graphql-engine-cdn.hasura.io/console/assets",
        serverVersion: "v1.2.0-beta.3",
      };
```

**Comment by mubaidr** [comment]
Got it running. I need to use `0.0.0.0` to make sure it is available outside the container. (localhost is not)

```bash
hasura-cli console --address 0.0.0.0
```
