### ISSUE TITLE
Error applying metadata if action with no input argument exists

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#4399]
While I can create such an action without issue, and export the resulting metadata, applying this metadata on a fresh database will raise an error:
```
FATA[0002] failed to apply metadata: cannot apply metadata on the database: [parse-failed] key "arguments" not present ($[1].actions[2].definition)
```

![image](https://user-images.githubusercontent.com/25712958/79182093-f3370300-7ddb-11ea-8c5d-bcc85c57b2ac.png)

adding a dummy argument solves the issue

![image](https://user-images.githubusercontent.com/25712958/79182263-6c365a80-7ddc-11ea-9d61-d1d31f46a896.png)

**Comment by GavinRay97** [comment]
Thank you for noting! This is a duplicate of https://github.com/hasura/graphql-engine/issues/4367 I believe.

**Comment by BenoitRanque** [comment]
> Thank you for noting! This is a duplicate of #4367 I believe.

That is correct. closing.
