### ISSUE TITLE
[BUG] [Beta Version] hasura-cli : directory vs directory-name

### ISSUE THREAD

**Issue by mubaidr** [hasura/graphql-engine#4400]
When using `directory` flag there is a deprecation message:
```bash
Flag --directory has been deprecated, use directory-name argument instead
```
 but I try to use `directory-name` there is an error message that this flag is unknown:
```bash
time="2020-04-14T06:19:12Z" level=fatal msg="unknown flag: --directory-name"
```
Version: v1.2.0-beta.3.cli-migrations-v2

**Comment by shahidhk** [comment]
@mubaidr The `--directory` flag has been deprecated and it is asking to use the argument instead.

i.e.

```
hasura init my-project
```
instead of 
```
hasura init --directory my-project
```
