### ISSUE TITLE
Console CodeGen not outputting full code for custom mutation names

### ISSUE THREAD

**Issue by srobrien** [hasura/graphql-engine#4401]
I'm not sure if this is an issue or my incompetence, however using v1.2.0beta3 console I have a mutation which I wish to derive an action from:

```
mutation ($username: String!, $password: String!){
  insert_app_users_one(object:{
       username: $username,
       password: $password,
  }){
    id
  }
}
```

When I derive the action and generate the code it works as intended:

```
type Mutation {
  InsertAppUsersOneDerived (
    username: String!
    password: String!
  ): InsertAppUsersOneDerivedOutput
}


type InsertAppUsersOneDerivedOutput {
  id : Int!
  password : String!
  username : String!
}
```

```
const fetch = require("node-fetch")

const HASURA_OPERATION = `
mutation ($username: String!, $password: String!){ insert_app_users_one(object:{ username: $username, password: $password, }){ id } }
`;

// execute the parent operation in Hasura
const execute = async (variables) => {
  const fetchResponse = await fetch(
    "http://localhost:8080/v1/graphql",
    {
      method: 'POST',
      body: JSON.stringify({
        query: HASURA_OPERATION,
        variables
      })
    }
  );
  const data = await fetchResponse.json();
  console.log('DEBUG: ', data);
  return data;
};
  

// Request Handler
app.post('/InsertAppUsersOneDerived', async (req, res) => {

  // get request input
  const { username, password } = req.body.input;

  // run some business logic

  // execute the Hasura operation
  const { data, errors } = await execute({ username, password });

  // if Hasura operation errors, then throw error
  if (errors) {
    return res.status(400).json(errors[0])
  }

  // success
  return res.json({
    ...data.insert_app_users_one
  })

});

```

 However, if I re-name the mutation and output type to a custom value, it does not generate the full code, as below:

```
type Mutation {
  createUser (
    username: String!
    password: String!
  ): createUserOutput
}

type createUserOutput {
  id : Int!
  password : String!
  username : String!
}

```

```// Request Handler
app.post('/createUser', async (req, res) => {

  // get request input
  const { username, password } = req.body.input;

  // run some business logic


  /*
  // In case of errors:
  return res.status(400).json({
    message: "error happened"
  })
  */

  // success
  return res.json({
    id: "<value>",
    password: "<value>",
    username: "<value>"
  })

});
```
I am under pretty confident i'm probably not using it correctly, however thought it was worth flagging.

Steve

**Comment by GavinRay97** [comment]
So the way that "Derived" Actions work on the Console is that, when you initially derive a method, the name of it is stored in `localStorage` in an dictionary object.

How the codegen component discriminates between standard and derived methods is by checking the name against the dict entries.

You can see some of this here:
https://github.com/hasura/graphql-engine/blob/21a4dff993e3e84f3311a1966e1be74361307a88/console/src/components/Services/Actions/lsUtils.js#L13-L35

If you open an inspector on the Console and type `window.localStorage`, you should see a stringified list of all derived methods in there. 

When you change the name of a derived action, the Console no longer "knows" that it's been derived.

There is some discussion around ways to improve the workflow for Derived Actions and how to persist them. I can see how this would be confusing.

**Comment by srobrien** [comment]
Hi Gavin, thanks for the quick and informative answer, I see the key/value in localstorage set with the pre-generated name. Its confusing as the guide video: https://www.youtube.com/watch?v=oqbxEp4FIjE&t=288s, shows this exact thing being carried out and it seems to works fine. It looks like he is working off a branch rather than v1.2 though so not sure if there is any differences.

**Comment by GavinRay97** [comment]
You're completely right, the branch there likely contains a patch for this. From the comments on the video:

![image](https://user-images.githubusercontent.com/26604994/79250030-2022fe80-7e4c-11ea-916c-04ba5cb93904.png)

**Comment by wawhal** [comment]
This was closed in https://github.com/hasura/graphql-engine/pull/4272.
