### ISSUE TITLE
Hasura console returns possibly ambiguous `postgres-error` message. Message popup adding invalid composite UNIQUE constraint erroneously returns only the first column listed in the composite constraint - postgres-error : <first-column-name> named in key "does not exist" 

### ISSUE THREAD

**Issue by slimlime** [hasura/graphql-engine#4402]
Wondering if this is specifically Hasura-related or if this error message is entirely passed through from Postgres.

(Trying to recall the exact conditions that allowed this error to be created in the first place; however, I believe it was during another suspicious automatically generated Hasura migration)

Error:
SQL Execution Failed
`postgres-error : column "productid" named in key does not exist`
or
`postgres-error : column "productrevisionid" named in key does not exist`
If you define `UNIQUE(productID, productRevisionID)`; or `UNIQUE(productRevisionID, productID)`;
Even though it could be the second column that was not in the table, it returns the first column as the errored one (productid) (productrevisionid)

(postgres-error pre-colon space)
(column name is returned in lowercase)

Reproduce:
* Create table with a column
* Attempt to create a composite UNIQUE constraint with that column and some unspecified column

**Hasura error notification message returns possibly ambiguous/erroneous postgres-error specifying only one column (the first one listed in the composite constraint).**

**Comment by GavinRay97** [comment]
Hey, unfortunately I'm unable to replicate this on `1.2.0-beta.3`:

![unique-err1](https://user-images.githubusercontent.com/26604994/79264637-e4dffa00-7e62-11ea-9c87-ef40238fe196.png)

![unique-err2](https://user-images.githubusercontent.com/26604994/79264639-e6112700-7e62-11ea-9984-ce6bac4bb9b2.png)

**Comment by slimlime** [comment]
> Hey, unfortunately I'm unable to replicate this on `1.2.0-beta.3`:
> 
> ![unique-err1](https://user-images.githubusercontent.com/26604994/79264637-e4dffa00-7e62-11ea-9c87-ef40238fe196.png)
> 


Hi @GavinRay97,

Thank you for checking this out and providing a screen clip.

Had not tried this on the beta version; however, did not see a related issue that got fixed!

Will see if I can provide more concrete steps with different versions

**Comment by rikinsk** [comment]
I suspect this could be a case of missed `"`s. I notice that the column name `productID` has capital letters in it. By default PG lowercases all identifiers unless they are wrapped in `"`s. Hence the expression would have to be `UNIQUE("productID", "productRevisionID")` to work.

@slimlime It isnt clear to me where you encountered this issue. Could you share some more details

**Comment by tirumaraiselvan** [comment]
Closing this as the question has been answered above. Pls comment/reopen if you have further questions.
