### ISSUE TITLE
Hasura console and migrations mishandles long file names; freezes hasura console UI feedback on long multi-column constraints submit

### ISSUE THREAD

**Issue by slimlime** [hasura/graphql-engine#4403]
May be more specifically related to the automatic migration generation functionality.

Long multi-name composite column constraints generate huge migration names based on concatenating the name of every column included without character limit.

Although some functionality does truncate the name to a usable string (the constraint name itself appears to be truncated after I refresh or check the code), the migrations generation of exceedingly and unlimited long file names freeze both the Hasura console feedback (Message: creating constraint... never resolves in the web console) and results in errors blocking the hasura migrate CLI from performing `migrate status` `migrate apply` functionality as well as causing issues with `git` version control and pre-commit/linting hooks mishandling long paths (not using `git` `longpaths` flag due to keep consistent tool interoperability compatibility).
* The default version control support not handling long file names can result in a hard to track down and troubleshoot error due to e.g. `git` not tracking the newly created migration files (hidden files causing errors in the background and not in version history!).

# Reproduce:
* Set up hasura migrations https://hasura.io/docs/1.0/graphql/manual/migrations/index.html
* Create a table with 20 (or any combination of columns + long column names to generate a long concatenated string for composite constraint migrations automatically)
* Create a composite constraint (include those 20+ columns in a `UNIQUE` constraint) that results in a concatenated constraint and subsequent even longer unlimited concatenated migration version folder
* Hasura console pops up the "creating..." message on submit that does not resolve and leaves the submission form open for editing (and provides UX case to edit submit more conflicting constraints multiple times without feedback).
* Check version control to see(!) your migrations were not tracked due to `longpaths` 😨 😃 

# Workaround: 
Deleting large appended strings from each fun migration version folder name works without issue, subsequently allowed the hasura CLI and `git` to continue working (hasura migrate either identifies based on the first prefix version epoch timestamp or has cached the data in some place).

May have been conducting a large amount of weird and wonderful denormalised data scraping 😅 

## Added possible draft breakdowns and representations:
> Do you happen to have any screenshots and logs (either from your browser, in the console errors/messages or from the Hasura container/CLI) to have some more tangible information on this?
> 
> Would be really helpful to visualize things and get a sense for exactly how "long" long is 😅

In having verbose naming conventions within obtuse denormalised data scraping for a database migration :P,
Example breakdown : 

- 33 characters default prefix: `1586847853419_alter_table_public_`
  - including 13 characters unix epoch: `1586847853419`
  - 10 to 20 characters action text: `add_unique_` `alter_table_`, `add_relationship_`,etc
* 15 to 30 characters table name depending on convention, standards: `ProductRevision` (or 63 characters)
* 400 characters... 20 to 30 characters column name multiplied by ... twenty columns (Postgres default maximum 63 characters identifier column, table name; Generally 10-30 characters) 
* ~20 characters all the underscores in between the columns, i.e. 1 per column: `_`

Example:
30 characters repo directory path + 33 + 30 + (... 20 * n) + (n)
Easily 100 to 150 characters by default (including base repo directory) even without long concatenated column names.

Minimal 60 to 100 characters for the generated migration version folder when not taking into account any parent directories or any column names in composite:
* `1586813845928_add_relationship_CustomerProductRevision_table_public_undefined`
* `1586412310362_add_relationship__table_public_ProductRevision`

^(not sure what inconsistencies are present here e.g. `__` vs `_`

>  By default, NAMEDATALEN is 64 so the maximum identifier length is 63 bytes.  The system uses no more than NAMEDATALEN-1 bytes of an identifier; longer names can be written in commands, but they will be truncated. If this limit is problematic, it can be raised by changing the NAMEDATALEN constant in src/include/pg_config_manual.h. 
https://www.postgresql.org/docs/12/sql-syntax-lexical.html 
`max_identifier_length` https://www.postgresql.org/docs/12/runtime-config-preset.html

Default 255 total file path (code repository may not be a flattened monorepo) 
😆 Wondering how to make both informative and super compatible auto migration names (whether the scaffolded folder generation is the preferred standard for developer-customisability)

Naming things https://martinfowler.com/bliki/TwoHardThings.html

**Comment by GavinRay97** [comment]
Do you happen to have any screenshots and logs (either from your browser, in the console errors/messages or from the Hasura container/CLI) to have some more tangible information on this?

Would be really helpful to visualize things and get a sense for exactly how "long" long is :sweat_smile:

**Comment by slimlime** [comment]
> Do you happen to have any screenshots and logs (either from your browser, in the console errors/messages or from the Hasura container/CLI) to have some more tangible information on this?
> 
> Would be really helpful to visualize things and get a sense for exactly how "long" long is 😅

In having verbose naming conventions within obtuse denormalised data scraping for a database migration :P,
Example breakdown : 

- 33 characters default prefix: `1586847853419_alter_table_public_`
  - including 13 characters unix epoch: `1586847853419`
  - 10 to 20 characters action text: `add_unique_` `alter_table_`, `add_relationship_`,etc
* 15 to 30 characters table name depending on convention, standards: `ProductRevision` (or 63 characters)
* 400 characters... 20 to 30 characters column name multiplied by ... twenty columns (Postgres default maximum 63 characters identifier column, table name; Generally 10-30 characters) 
* ~30 characters all the underscores in between the columns, etc 1 per column: `_`

Example:
30 characters repo directory path + 33 + 30 + (... 20 * n) + (n)
Easily 100 to 150 characters by default (including base repo directory) even without long concatenated column names.

Minimal 60 to 100 characters for the generated migration version folder when not taking into account any parent directories:
* `1586813845928_add_relationship_CustomerProductRevision_table_public_undefined`
* `1586412310362_add_relationship__table_public_ProductRevision`

^(not sure what inconsistencies are present here e.g. `__` vs `_`

>  By default, NAMEDATALEN is 64 so the maximum identifier length is 63 bytes.  The system uses no more than NAMEDATALEN-1 bytes of an identifier; longer names can be written in commands, but they will be truncated. If this limit is problematic, it can be raised by changing the NAMEDATALEN constant in src/include/pg_config_manual.h. 
https://www.postgresql.org/docs/12/sql-syntax-lexical.html 
`max_identifier_length` https://www.postgresql.org/docs/12/runtime-config-preset.html

Default 255 total file path (code repository may not be a flattened monorepo) 
😆 Wondering how to make both informative and super compatible auto migration names (whether the scaffolded folder generation is the preferred standard for developer-customisability)

Naming things https://martinfowler.com/bliki/TwoHardThings.html

**Comment by GavinRay97** [comment]
Thanks for the super comprehensive write-up!

To summarize:
- Creating tables with long table + column names, then composite constraints breaks the Console
- The migrations it generates are not properly tracked by git due to default file-name length constraints
- Measures are needed to ensure that generated migrations do not exceed 255 characters to prevent ghost-bugs from version control issues

**Comment by beerose** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/c1381d38e01090e87d4107321cb53c97a7303468
