### ISSUE TITLE
[Question] Select permissions as filters in SQL query

### ISSUE THREAD

**Issue by baskin** [hasura/graphql-engine#4404]
Hi team,

I was playing around with a multi-tenant schema (say) a movies table with fields 
`id | name | tenant_id`
I setup row select permissions `{"tenant_id":{"_eq":"X-Hasura-Tenant-Id"}}`

While running a query for (say) all movies, I observed that only the movies permitted by the above permissions setup i.e. only the movies for the requesting users `tenant_id` are returned instead of (say) failing fast and throwing an authZ error.

Does the underlying implementation automatically add a `tenant_id eq "<tenant_id>` filter to the SQL query? Or is the filtering a post DB retrieval step?

What is the best practice is for issuing queries from a performance standpoint in regards to the above?

I'd prefer to avoid such repetitive clauses (`tenant_id eq "<tenant_id>`) in the frontend client code, if performance is not an issue (e.g. if the underlying implementation automatically add a `tenant_id eq "<tenant_id>` to the SQL)

Many thanks,

**Comment by tirumaraiselvan** [comment]
> Does the underlying implementation automatically add a tenant_id eq "<tenant_id> filter to the SQL query?

Yes, the permissions checks are embedded in the generated SQL. You can click on `Analyze` in graphiql for any query operation and see the generated SQL too.

**Comment by baskin** [comment]
Thanks. Closing.

**Comment by ben-xx** [comment]
Just a follow-up note: Analyze is only available when using x-hasura-admin-secret header, at least in my current version (v1.3.2). If I try to use Analyze using a user-authorized JWT, I get redirected to login to console.  

So I believe it's not possible to use Analyze to see generated SQL for a user-level permission restriction, as the Analyze results show how the query would run as "root".  

Is there a way to Analyze non-root/admin generated SQL?
