### ISSUE TITLE
Allow Nullable action response

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#4405]
Actions can be defined to have a nullable return type like so:
```
type Mutation {
  authentication_refresh (
    dummy: String
  ): AuthRefresh
}
```
Yet returning an empty object or empty body will throw an error.
Nullable return types should either explicitly be disallowed, or not throw errors

**Comment by AndrewPahomovOtto** [comment]
Have similar problem. If webhook response null its trhrow error. If i returen empty object it's work, but its not that what i need

**Comment by rennehir** [comment]
I have also encountered this problem. Is it really so that currently it is not possible to return `null` from a custom action?

**Comment by BenoitRanque** [comment]
Seems there's been a regression on this as of 2.2.0.
Specifically given the following action schema:

```graphql
type Mutation {
  my_nullable_action: MyType
}

type MyType {
   my_non_nullable_field: String!
}
```

Returning null from the webhook will result in the following error:
```
[GraphQL] field "my_non_nullable_field" expected in webhook response, but not found
```
This is incorrect, `my_non_nullable_field` is not nullable but `my_nullable_action` is.

**Comment by BenoitRanque** [comment]
Fix has been merged into main, should be out in next release
