### ISSUE TITLE
docs: better wording on enum docs

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#4406]
And also in regards enum tables, I think it is better to update docs:

And enum tables, first time I went though the docs I misread.

> 3. The table may not contain any other columns.

As it also may contain others. It is better word it as must not contain imho
Probably better wording will be

3. The table must not contain any other columns.

[dmi3y in discord]

**Comment by marionschleifer** [comment]
Implemented in https://github.com/hasura/graphql-engine/pull/4827.
