### ISSUE TITLE
Feature Suggestion: @role directive

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#4417]
Currently, Hasura requires that a role be sent along with each request using the the `x-hasura-role` header.

This becomes an issue when using Hasura over websockets, as it is impossible to send additional cookies once the connection is established. 

With this proposal, auth would still be sent only when the connection is established, but crucially the specific role for a query/mutation/subscription would be sent with the query itself.

Usage of the propose api would look something like this

```
query MyQuery @role(name: "admin") {
  field
}
mutation MyMutation @role(name: "admin") {
  field
}
subscription MySubscription @role(name: "admin") {
  field
}
```

This may be invalidated by [this](https://github.com/hasura/graphql-engine/pull/3868) proposal, but I still wanted to put the idea out there.

**Comment by tirumaraiselvan** [comment]
@BenoitRanque This seems like a dupe of https://github.com/hasura/graphql-engine/issues/3566 ?

**Comment by BenoitRanque** [comment]
Closing as duplicate
