### ISSUE TITLE
Create event trigger from API with environment based webhook

### ISSUE THREAD

**Issue by marcopeg** [hasura/graphql-engine#4419]
Hello, I can't figure out how to setup a trigger toward a webhook defined by an environment variable using the API:

```
{
    type: 'create_event_trigger',
    args: {
      name: 'foobar',
      table: {
        schema: 'public',
        name: 'app_settings',
      },
      webhook: 'SHOULD_BE_ENV',
      update: {
        columns: '*',
        payload: '*',
      },
    },
  }
```

Can you help?

**Comment by tirumaraiselvan** [comment]
Sorry that the API has been missed in the documentation.

Can you try `webhook_from_env` key instead of `webhook`

**Comment by marcopeg** [comment]
@tirumaraiselvan it works, thanks. 

Do the docs have a repo? 
I may contribute and add this detail.

**Comment by tirumaraiselvan** [comment]
@marcopeg Appreciate the interest in contribution!

The docs is in the same repo, pls see the contributing guide here: https://github.com/hasura/graphql-engine/blob/master/docs/CONTRIBUTING.md

**Comment by marcopeg** [comment]
@tirumaraiselvan here it goes, it's minimal contribution but I hope it will help others. As always, keep it up with the incredible job!

**Comment by marcopeg** [comment]
Thank you guys :-)
