### ISSUE TITLE
clicking back button after expanding relations throws error

### ISSUE THREAD

**Issue by corysimmons** [hasura/graphql-engine#443]
1. Create FK link

![image](https://user-images.githubusercontent.com/224636/45499995-86fda480-b74b-11e8-9914-3ed7619840ce.png)

2. Click it

![image](https://user-images.githubusercontent.com/224636/45500005-8e24b280-b74b-11e8-99c3-2bf5827fb354.png)

3. Press browser back button

![image](https://user-images.githubusercontent.com/224636/45500032-a7c5fa00-b74b-11e8-80ec-34e3c49cc821.png)

**Comment by praveenweb** [comment]
@corysimmons - Hey, i'm not able to replicate this issue. More information would be helpful.

Which page were you supposed to be in after clicking the back button?

**Comment by corysimmons** [comment]
The table with the FK.

**Comment by corysimmons** [comment]
This happened a while ago. The bug still pops up from time-to-time in different circumstances, but I don't have time to make a reduced test case for it. It's not too inconvenient.
