### ISSUE TITLE
Use ENV variable to define or prefix actions handler

### ISSUE THREAD

**Issue by oxodesign** [hasura/graphql-engine#4457]
Hi

We started slowly developing a new project using Hasura and GraphQL 2 months ago and we are now trying to setup test and staging env for our application.

Since we are using Actions (still in beta) it should be very helpful for us if we can prefix or define action handlers using ENV variables.

Example prefixing (prefered)
```{ENV_MY_ACTION_HANDLER_HOST}/test```
Where ```ENV_MY_ACTION_HANDLER_HOST``` will be "https://hostname.com:5001" and the result of the handler will be "https://hostname.com:5001/test".

Exemple using an ENV variable per action handler:
```ENV_MY_ACTION_HANDLER_URL``` this will translate to "https://hostname.com:5001/test" and its the result of the action handler.

Thanks in advance and I appreciate your hard work :)

**Comment by rikinsk** [comment]
@oxodesign This is already possible. See the note regarding Url Templating under https://hasura.io/docs/1.0/graphql/manual/actions/create.html#step-2-create-the-action-handler.

I hope this was what you were looking for
