### ISSUE TITLE
propagate comments from sql to graphql schema

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#446]
(via ben on cherre)

@0x777 I remember you saying that there was a problem with this. What was it?
cc @rakeshkky

**Comment by shahidhk** [comment]
Propogate SQL comments as descriptions on GraphQL schema.

**Comment by OLDIN** [comment]
How to add a type description to the graphql?
I added a comment, but it is not displayed in the graphql schema.

**Comment by mastoj** [comment]
What is the status here? Is it a bug or a feature not implemented?

**Comment by shahidhk** [comment]
@mastoj This is a feature that is not implemented yet. There is a PR open to address it. Should be out in the next release: https://github.com/hasura/graphql-engine/pull/2397

**Comment by mastoj** [comment]
Awesome stuff @shahidhk ! Is there an ETA on the next release?

**Comment by shahidhk** [comment]
@mastoj Within two weeks, ideally.
