### ISSUE TITLE
allow array relationships based on array type columns

### ISSUE THREAD

**Issue by ravensnowbird** [hasura/graphql-engine#4464]
It is possible to have array relationships to directly map to an array field in postgres without any middle table connection. 

Conversations table
```
add_column :conversations, :user_ids, :uuid, array: true
```

![hasura-array-relationships](https://user-images.githubusercontent.com/854024/79641897-f9502980-81b7-11ea-8122-d7f8bedfcfc9.png)

**Comment by rikinsk** [comment]
@ravensnowbird Unfortunately I am not quite sure of the use case here. Can you maybe share some more details on what you are expecting and how it would be useful.

PS: Sorry for the delay in response. This seems to have been missed somehow.

**Comment by rikinsk** [comment]
Actaully I think I get it now. You would like to have an array relationship to the `users` table via the `user_ids` array type column of `conversation` table.

**Comment by ravensnowbird** [comment]
@rikinsk Yes. Postgres by default supports array field of strings/integers. These can be used to form a relationship directly avoiding a middle table users_conversations.

**Comment by ghyath5** [comment]
@ravensnowbird 

Did you find any work-around to do this array relationship ?

**Comment by ravensnowbird** [comment]
> users

Exactly. this is working with an array relationship. It didn't work in the old version. it works on the latest one. I guess it must have been some bug. Closing this now.

**Comment by pandoratoolbox** [comment]
Still isn't working

**Comment by efstathiosntonas** [comment]
any news in this? ^^ many customers have this issue. Yes, intermediate table is a solution but we want to avoid it.

**Comment by sounden** [comment]
Yepp looking for same functionallity.

**Comment by Gherciu** [comment]
@rikinsk ^^
