### ISSUE TITLE
How to turn off SELECT permissions but enable SELECT BY PK only ?

### ISSUE THREAD

**Issue by iamkhalidbashir** [hasura/graphql-engine#4465]
Hello folks, thank you all for providing such an awesome repo. 
Let me get into the issue

*How to turn off **SELECT** permissions but enable **SELECT BY PK** only ?*

![Screenshot from 2020-04-18 20-52-13](https://user-images.githubusercontent.com/27646811/79642395-a45fe380-81b6-11ea-8991-f95cef0c3c5c.png)

Why is this so important?

Because many times we need an anonymous user to UPDATE or SELECT the data if he has the PRIMARY KEY of the record, not anyone else?

There are solutions, for example, to create a VIEW function to achieve this in a dirty complex way, but if we are considering Hasura for prod then we might add this as an option in PERMISSIONS (in the console).

I don't know any Haskel, so I won't be able to contribute, Sorry.

Thank you all for your feedback.

**Comment by tirumaraiselvan** [comment]
Closing this in favour of https://github.com/hasura/graphql-engine/issues/3436
