### ISSUE TITLE
Graphql filter "or" is not working properly

### ISSUE THREAD

**Issue by DrHe1991** [hasura/graphql-engine#4472]
Hello there, 
I found that the filter "or" is not working properly in hasura at version 1.11 and lower verison.
Case1:
```
query MyQuery {
  recent_messages(where: {_or: {opp_id: {_eq: "ebd75875-3a18-429a-b681-25b404471886"}, user_id: {_eq: "ebd75875-3a18-429a-b681-25b404471886"}}}) {
    opp_id
    message_id
  }
}
```
returns
```
{
  "data": {
    "recent_messages": []
  }
}
```
But 
Case2:
```
query MyQuery {
  recent_messages(where: {user_id: {_eq: "ebd75875-3a18-429a-b681-25b404471886"}}) {
    opp_id
    message_id
  }
}

```
returns
```
{
  "data": {
    "recent_messages": [
      {
        "opp_id": "55a07435-14a0-41af-87ab-9365025fa688",
        "message_id": "a25b9716-d780-49bd-bbe0-3aab1b919b7f"
      }
    ]
  }
}
```
This is not right. The "or" clause should return at least one result in Case 1, right? Did I use the clause in the wrong way? Can someone double check this? Thank you! 

Chris

**Comment by GavinRay97** [comment]
On `1.2.0-beta.2`, I can confirm that using the sytax-sugar for `or` leads to `AND` being generated in the SQL query.

In the docs, we have:
```
  _or: {
   rating: { _gte: 4 },
   published_on: { _gte: "2018-01-01" }
  }
}

# will be coerced to:

{
  _or: [
    {
      rating: { _gte: 4 },
      published_on: { _gte: "2018-01-01" }
    }
  ]
}
```

Neither of those appear to function properly, the format that works is:
```graphql
_or: [
      { rating: { _gte: 4 } },  <-- notice curly braces for each statement
      { published_on: { _gte: "2018-01-01" } },
    ]
```

Running the following query in `1.2.0-beta.2`:
```graphql
query {
  user(where: {
    _or: {
      id: {_eq: 1},
      name: {_eq: "Test"},
  	}
  }) {
    id
    email
    name
  }
}
```

No data
![image](https://user-images.githubusercontent.com/26604994/79771115-57862500-82fc-11ea-85de-b6c877a24b85.png)

Analyze shows generated query using `AND`:
```sql
SELECT
  *
FROM
  "public"."user"
WHERE
  (
    (("public"."user"."id") = (('1') :: integer))
    AND (("public"."user"."name") = (('Test') :: text))
  )
```

Running this query:
```graphql
query {
  user(where: {
    _or: [
	  {
    	id: {_eq: 1},
        name: {_eq: "Test"},
  	  }
    ]
  }) {
    id
    email
    name
  }
}
```

Also gives no data:

![image](https://user-images.githubusercontent.com/26604994/79771348-ad5acd00-82fc-11ea-814e-600a06054f49.png)

The Analyze output is the same as above. Running this query gives data:
```graphql
query {
  user(where: {
    _or: [
      { id: {_eq: 1} },
      { name: {_eq: "Test"} },
    ]
  }) {
    id
    email
    name
  }
}
```

![image](https://user-images.githubusercontent.com/26604994/79771573-fb6fd080-82fc-11ea-8934-246be1c5350e.png)


```sql
SELECT
  *
FROM
  "public"."user"
WHERE
  (
    (("public"."user"."id") = (('1') :: integer))
    OR (("public"."user"."name") = (('Test') :: text))
  )
```

**Comment by GavinRay97** [comment]
Edited my previous comment

**Comment by DrHe1991** [comment]
Thanks for pointing that out. I was using the hasura "Explorer" to build the query and I thought it should give me the query I want for `or` logic. However, it will generate the logic like `and` clause
I still hope someone can make that easier to use.

**Comment by tirumaraiselvan** [comment]
GraphiQL-explorer has a bug where it[ doesn't open an array](https://github.com/OneGraph/graphiql-explorer/issues/32).

We are tracking improving the usability of this here: https://github.com/hasura/graphql-engine/issues/4488

**Comment by AliNaraghiA** [comment]
galleries(filter: {title: {eq: "rain"}})             me to o
