### ISSUE TITLE
docs: use example for `--directory` without deprecation warning

### ISSUE THREAD

**Issue by brandonFaf** [hasura/graphql-engine#4476]
In the example code for setting up a project directory the example command uses `--directory` and when running the command there is a deprecation warning. It would be nice if the example didn't use a deprecated argument 

https://hasura.io/docs/1.0/graphql/manual/migrations/new-database.html#step-2-set-up-a-project-directory

**Comment by GavinRay97** [comment]
Hey, thanks for bringing this to our attention!

There is a lot of work being done on the docs for `1.2`/`1.3` features, we will look at merging this information in there as well, thank you.

**Comment by marionschleifer** [comment]
This has been fixed.
