### ISSUE TITLE
Error: ensuring plugins index failed - cli migrations

### ISSUE THREAD

**Issue by trollr** [hasura/graphql-engine#4496]
We use a self hosted kubernetes cluster and our services are not allowed to connect to public services eg. github. 

It seems that the cli-migrations tool try to download several plugins for the execution. 

```
time="2020-04-21T12:21:10Z" level=fatal msg="ensuring plugins index failed: Get https://github.com/hasura/cli-plugins-index.git/info/refs?service=git-upload-pack: dial tcp 140.82.118.3:443: i/o timeout"
```

How can I prevent that hasura download things and is still able to execute the migrations? All necessary plugins should be bundled in the cli-migration docker image

**Comment by arvi3411301** [comment]
@trollr Could you tell me which docker image you are using?

**Comment by trollr** [comment]
@arvi3411301 I tried several images:

- v1.2.0-beta.4.cli-migrations-v2
- v1.2.0-beta.4.cli-migrations
- pull4459-d98cba5c (your cli_environment change)

None of them are working. **pull4459-d98cba5c** won't execute the migrations

**Comment by trollr** [comment]
Closes because v1.1.1.cli-migrations working

However you should customize v1.2.0 not to download any assets :)

**Comment by tirumaraiselvan** [comment]
@trollr We are fixing this in the PR linked to the issue. Reopening this to track.

**Comment by arvi3411301** [comment]
@trollr Can you try:

- `hasura/graphql-engine:pull4459-d98cba5c.cli-migrations` - v1 workflow
- `hasura/graphql-engine:pull4459-d98cba5c.cli-migrations-v2` - v2 workflow

**Comment by dostalradim** [comment]
Hi,

I have same issue with this binary https://github.com/hasura/graphql-engine/releases/download/v1.2.0/cli-hasura-linux-amd64 is it already solved?

Thank you!

**Comment by dostalradim** [comment]
Hi, I have K8S cluster on-premise which has no access to internet, I run hasura binary in my own docker image built from node12-alpine. Binary is downloaded from github releases with wget, version is 

```
/app/hasura # hasura --skip-update-check version
INFO hasura cli                                    version=v1.2.1
/app/hasura #
```

and when I run this command I get this error

```
/app/hasura # hasura --project /app/hasura --skip-update-check migrate apply --endpoint XXXXXXXXXXXX
FATA[0030] ensuring plugins index failed: Get https://github.com/hasura/cli-plugins-index.git/info/refs?service=git-upload-pack: dial tcp 140.82.118.3:443: i/o timeout 
/app/hasura #
```

am I doing something wrong? I think binary is still trying connect to internet.
Thank you!

**Comment by dostalradim** [comment]
I found solution in your Dockerfile. Append this variables helped. Can you document it somewhere? Or I just did not find it in doc? 
```
/app/hasura # export HASURA_GRAPHQL_CLI_ENVIRONMENT=server-on-docker
/app/hasura # export HASURA_GRAPHQL_SHOW_UPDATE_NOTIFICATION=false
```

**Comment by jflambert** [comment]
@tirumaraiselvan can I get some clarity on this `HASURA_GRAPHQL_SHOW_UPDATE_NOTIFICATION` environment variable? I asked for [something similar](https://github.com/hasura/graphql-engine/issues/4096) but my issue is still open. Googling for `HASURA_GRAPHQL_SHOW_UPDATE_NOTIFICATION` brings up [exactly two results](https://www.google.com/search?q=HASURA_GRAPHQL_SHOW_UPDATE_NOTIFICATION&nfpr=1), this issue and a broken dockerhub link, which suggests this did exist at some point. I can't find anything in your code about it though.
