### ISSUE TITLE
Connection refused Error, cannot connect to my postgres database with docker

### ISSUE THREAD

**Issue by ilahomesick** [hasura/graphql-engine#4498]
Hi Guys, 
I've been trying for hours to make hasura work with docker, i have a postgres db running locally and i can reach it and access it without any problem from 3 different postgres clients for mac (postgres, postico and pgadmin), but when i try to connect graphql with docker i keep getting the following error `{"internal":"could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n","path":"$","error":"connection error","code":"postgres-error"}`
the address seems to be correct, cause if i paste it in the browser it opens it with postico and connects correctly. I also tried playing with postgres configuration files like some stackoverflow users suggested but without any luck.

**Comment by GavinRay97** [comment]
If I understand this correctly, you have Hasura running in a Docker container and Postgres running on your host machine? And that Hasura says it cannot connect to Postgres?

Inside of the Hasura container, `localhost` points to it's own container network. You want to point it to the *host* (your machine's) `localhost`.

If you use `docker-compose`, a network is created that allows all services to communicate with each other directly. If you're using a single Docker image running, how to fix this depends on your OS.

On Windows/Mac:
- Use `host.docker.internal` to access the host's network

On Linux:
- Start the container process with `--network="host"` in your `docker run` command

**Comment by ilahomesick** [comment]
> If I understand this correctly, you have Hasura running in a Docker container and Postgres running on your host machine? And that Hasura says it cannot connect to Postgres?
> 
> Inside of the Hasura container, `localhost` points to it's own container network. You want to point it to the _host_ (your machine's) `localhost`.
> 
> If you use `docker-compose`, a network is created that allows all services to communicate with each other directly. If you're using a single Docker image running, how to fix this depends on your OS.
> 
> On Windows/Mac:
> 
> * Use `host.docker.internal` to access the host's network
> 
> On Linux:
> 
> * Start the container process with `--network="host"` in your `docker run` command

It worked, thank you !

**Comment by rikinsk** [comment]
Closing this issue. Please feel free to reopen if there is more to add.

**Comment by saikrishna-siddhard** [comment]
Its able to connect but How to add admin secret to it.
#! /bin/bash
docker run -d --net=host \
       hasura/graphql-engine:v1.0.0-alpha07 \
       graphql-engine \
       --database-url postgres://username:password@hostname:5432/dbname \
       serve --enable-console

**Comment by saikrishna-siddhard** [comment]
Please let me know how can we add admin secret here

**Comment by sahilrajput03** [comment]
I am using archlinux, and I was able to connect to my local db simply via doing these three things: 

1. https://stackoverflow.com/a/32844024/10012446
2. https://stackoverflow.com/a/34577754/10012446

I needed to set password for postgres user as well via:

```bash
psql -U postgres
\password
# set my password to `secret`
```

Then, I needed to use database url as Database URL as `postgresql://postgres:secret@192.168.18.3:5432/myDb1_test`.

where `192.168.18.3` is my local ip address on the wifi. 

It works now.

*FYI: I did not use `--network="host"` anywhere at all.*

Get complete guide how i did this @ https://github.com/sahilrajput03/learning_sql/blob/main/Notes_setup-postgres.md#hasura-connecting-db

**Comment by SeiwonPark** [comment]
> 

You saved my day :) thanks 👍

**Comment by SeiwonPark** [comment]
> If I understand this correctly, you have Hasura running in a Docker container and Postgres running on your host machine? And that Hasura says it cannot connect to Postgres?
> 
> Inside of the Hasura container, `localhost` points to it's own container network. You want to point it to the _host_ (your machine's) `localhost`.
> 
> If you use `docker-compose`, a network is created that allows all services to communicate with each other directly. If you're using a single Docker image running, how to fix this depends on your OS.
> 
> On Windows/Mac:
> 
> * Use `host.docker.internal` to access the host's network
> 
> On Linux:
> 
> * Start the container process with `--network="host"` in your `docker run` command

You saved my day :) thanks 👍

**Comment by HariharanUmapathi** [comment]
how to connect my local postgres database with hasura without docker 
i have tried to connect with hasura console add data source does not works

**Comment by rccc** [comment]
hasura/graphql-engine:v2.29.0

postgres://postgres:@host.docker.internal:5432/mydb

[
	{
		"definition": "mydb",
		"message": "could not translate host name \"host.docker.internal\" to address: Name or service not known\n",
		"name": "source mydb",
		"reason": "Inconsistent object: connection error",
		"type": "source"
	}
]


postgres://postgres:@localhost:5432/mydb

[
	{
		"definition": "mydb",
		"message": "connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at \"localhost\" (::1), port 5432 failed: Cannot assign requested address\n\tIs the server running on that host and accepting TCP/IP connections?\n",
		"name": "source mydb",
		"reason": "Inconsistent object: connection error",
		"type": "source"
	}
]

with graphql-engine:v1.3.3

postgres://postgres:@localhost:5432/mydb  -> works

Tanks a lot for what you have done, now i am spending hours to try to connect, thanks a lot for the waste of time.

**Comment by rccc** [comment]
@SamirTalwar 

I am very upset !

Do not closed this ticket as this is not resolved ! Do not do ot again or I will tell https://www.linkedin.com/in/tanmaig/ that this is not fair ! You are paid for a job, do it !


My configuration is the same than the default configuration that you can find here : https://hasura.io/docs/latest/getting-started/docker-simple/ 

Only PG_DATABASE_URL parameters is changes.

I can only make it works with  

`docker run  --net=host -e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:@localhost:5432/my_db        -e HASURA_GRAPHQL_ENABLE_CONSOLE=true        -e HASURA_GRAPHQL_DEV_MODE=true        hasura/graphql-engine:v1.3.3`
