### ISSUE TITLE
console DX improvement: single row mutation permissions

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#4500]
The permissions for `insert_one`, `update_by_pk` and `delete_by_pk` are inferred from `insert`, `update` and `delete` permissions **and** from the `select` permission. This is because the single row mutations share the returning type with `select`. This means, if no permissions are defined for `select`, the single row mutations will also be hidden from the schema.

This has to be made very clear in the UI.

**Comment by torw2n8** [comment]
Am intrigued, select then permissions show but they also show ie insert, update on there own. What's the issue then
