### ISSUE TITLE
update image graphql-engine to v1.2 in docker19 fail

### ISSUE THREAD

**Issue by fred8617** [hasura/graphql-engine#4507]
![image](https://user-images.githubusercontent.com/35049517/79931521-c5a62580-847d-11ea-9f0c-ef6311fb10a8.png)
[https://docs.docker.com/registry/spec/deprecated-schema-v1/](https://docs.docker.com/registry/spec/deprecated-schema-v1/)

**Comment by tirumaraiselvan** [comment]
Seems like a docker registry issue. Pls reopen if you continue to see this error for recent version as well.
