### ISSUE TITLE
file upload with Apollo iOS

### ISSUE THREAD

**Issue by ilahomesick** [hasura/graphql-engine#4512]
Hello, 
I'm trying to implement image Upload on an iOS app, with apollo and Hasura.
Reading from apollo documentation "https://www.apollographql.com/docs/ios/mutations/" in the "Uploading Directly With Apollo" paragraph, there's the example mutation 
`mutation UploadFile($file:Upload!) {
singleUpload(file:$file) {
id}
}` 
with "Upload" type, when i was using other frameworks it worked, while if i try to run the query on the hasura console it doesn't recognize that type, is there any way to include that type or any otherway to perform image upload from iOS ?

**Comment by perrosnk** [comment]
there is an interesting video [here](https://www.youtube.com/watch?v=mipb4N6ZzfM). Hope it helps

**Comment by praveenweb** [comment]
@ilahomesick - Multi-part file uploads are not defined as part of the GraphQL spec. The workaround is to either use base64 encoded file upload or just use a separate file service to manage files (typically cloud services like S3/Cloudinary).

The base64 approach works for smaller file size use cases. Here's an [example with React and Hasura Actions](https://github.com/hasura/hasura-actions-examples/tree/master/file-upload).
