### ISSUE TITLE
Getting an `Error in $: not enough input` error in my JWT auth token

### ISSUE THREAD

**Issue by andywong418** [hasura/graphql-engine#4525]
I'm getting an `invalid jwt - Error in $: not enough input` error when I try to curl my endpoint. Does anyone know what the issue might be? I'm using a HSA256 scheme.

**Comment by hgiasac** [comment]
@andywong418 what GraphQL Engine version do you use? This issue may be fixed on version 1.2 beta 4

**Comment by andywong418** [comment]
I think I'm on Hasura v1.1.1

**Comment by tirumaraiselvan** [comment]
@andywong418 Can you paste the token in https://jwt.io/ and see if it conforms to the spec Hasura expects: https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#the-spec

**Comment by andywong418** [comment]
@tirumaraiselvan  `{
  "sub": "USER_ID",
  "iat": 1587632091.513,
  "https://hasura.io/jwt/claims": {
    "x-hasura-allowed-roles": [
      "mine",
      "user"
    ],
    "x-hasura-user-id": "USER_ID",
    "x-hasura-default-role": "user",
    "x-hasura-role": "user"
  }
}`

My user id is a uuid

**Comment by tirumaraiselvan** [comment]
@andywong418 Can you please confirm the Hasura version?

**Comment by andywong418** [comment]
@tirumaraiselvan yeah it is on Hasura v1.1.1

**Comment by tirumaraiselvan** [comment]
@andywong418 I tried to repro this with the exact same payload values and `HS256` key configuration. It seemed to work fine.

Is it possible for you to launch a heroku instance where I can see the problem?

**Comment by andywong418** [comment]
@tirumaraiselvan could it be the UUID which is causing an issue?

**Comment by andywong418** [comment]
Do you mean creating a heroku instance with my existing schema?

**Comment by tirumaraiselvan** [comment]
Schema can be just minimal, but the `HASURA_GRAPHQL_JWT_SECRET` should be similar and a sample token which throws the error.

**Comment by andywong418** [comment]
I have a database from scratch so I can just share the token I have now (and change config later). How should I share the details?

**Comment by andywong418** [comment]
@tirumaraiselvan I have a feeling it's because the types aren't compatible between a uuid and a string in Hasura and so it's telling me there's not enough input since `x-hasura-user-id` is invalid

**Comment by tirumaraiselvan** [comment]
@andywong418 Can you just share the token here?

**Comment by andywong418** [comment]
This is my request - `curl -X POST https://wondrous-hasura.herokuapp.com/v1/graphql -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZGY5OWZkZC1jOGQ3LTQ5NTctODA1Ni1kZmZiMTc2YTg1NjciLCJuYW1lIjoiQW5kcm9zIFdvbmciLCJpYXQiOjE1ODc2NjE0OTMuMDc3LCJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWFsbG93ZWQtcm9sZXMiOlsibWluZSIsInVzZXIiXSwieC1oYXN1cmEtdXNlci1pZCI6IjJkZjk5ZmRkLWM4ZDctNDk1Ny04MDU2LWRmZmIxNzZhODU2NyIsIngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1yb2xlIjoidXNlciJ9fQ.PPY8qk40JIqoZKAmx6Wii2USYzKu1UyLfEIKTWWH_yo'`

**Comment by tirumaraiselvan** [comment]
Thanks @andywong418 

The error has nothing to do with the JWT token but it is complaining of the actual data that has been posted. There is basically no operation that is given to the endpoint.

Try giving something like this, notice the data after the `-d` argument :

`curl -X POST https://wondrous-hasura.herokuapp.com/v1/graphql -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJctODA1Ni1kZmZiMTc2YTg1NjciLCJuYW1lIjoiQW5kcm9zIFdvbmciLCJpYXQiOjE1ODc2NjE0OTMuMDc3LCJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWFsbG93ZWQtcm9sZXMiOlsibWluZSIsInVzZXIiXSwieC1oYXN1cmEtdXNlci1pZCI6IjJkZjk5ZmRkLWM4ZDctNDk1Ny04MDU2LWRmZmIxNzZhODU2NyIsIngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1yb2xlIjoidXNlciJ9fQ.PPY8qk40JIqoZKAmx6Wii2USYzKu1UyLfEIKTWWH_yo' -d'{"query": "query { __typename}"}`

**Comment by andywong418** [comment]
I get this error `{"errors":[{"extensions":{"path":"$","code":"invalid-jwt"},"message":"Could not verify JWT: JWSError (CompactDecodeError CompactDecodeError: Expected 3 parts; got 2)"}]}%`. Also in my Hasura logs I get this error when I try to fetch data of a logged in user - `"error":{"path":"$","error":"no such type exists in the schema: 'users'","code":"validation-failed"},"request_id":"8ee7bea9-0360-42ef-a719-9251cb9a4e0c","response_size":92,"query":{"variables":{},"operationName":"whoami","query":"query whoami {\n  users {\n    ...user\n    __typename\n  }\n}\n\nfragment user on users {\n  id\n  fullName\n  picture\n  __typename\n}\n"}`

**Comment by andywong418** [comment]
users definitely exist in the schema so it's still a validation failed error

**Comment by andywong418** [comment]
When I put the bearer token into my graphiql interface no schema turns up.

**Comment by andywong418** [comment]
Problem solved - @tirumaraiselvan  I'd suggest in the docs https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html that it should be explicitly mentioned that access control is necessary for roles like 'user' or 'editor' to work. The docs makes it seem like it's built in to Hasura and so no further setup is necessary. A link on the page to https://hasura.io/docs/1.0/graphql/manual/auth/authorization/roles-variables.html would have been helpful. Thanks!
