### ISSUE TITLE
Trailing spaces when adding a new column should be trimmed.

### ISSUE THREAD

**Issue by gnyani** [hasura/graphql-engine#4526]
When creating a new table if any one of the columns has an extra space in the column name table creating fails with the following error, but it's difficult for the user to understand  what's wrong as the space is  not available in the UI: 
 
![image](https://user-images.githubusercontent.com/13602716/80088671-7560bd80-857a-11ea-8440-d564b61c6008.png)

To be precise `column_name `  throws an exception since it has a trailing space but `column_name` doesn't. 

I suggest we should apply trim() on all column names before sending it to the Postgres and the user need not have to worry about anything.

If you agree that this should be fixed, I am willing to raise a PR for this. Please assign it on me.

**Comment by rikinsk** [comment]
@gnyani This makes sense. It would be great if you could add the fix as you suggested. Thanks

**Comment by mubaidr** [comment]
@rikinsk I would like to take on this. 

Also I think this should be handled on the input components, this will make sure maximum typed input is trimmed. What do you say?

**Comment by gnyani** [comment]
@mubaidr  I am working on it.

**Comment by gnyani** [comment]
@rikinsk can you please review #4545 and merge?
