### ISSUE TITLE
hide insert_one for nested inserts

### ISSUE THREAD

**Issue by anisjonischkeit** [hasura/graphql-engine#4543]
Seems pointless to have insert_one when insert does the same thing here (what is returned is dependent on the return query not the insert data).

I just came into a lot of confusion with this since I'd renamed insert_one_users to just insert_user and a nested insert_one seems to not prefill the foreign key to its parent.

**Comment by anisjonischkeit** [comment]
I guess this is a bug and an idea?

- bug: nested insert_one does not prefill the foreign key to its parent
- idea (would work as a solution): Just remove the insert_one method since it is (at least from what I can see) redundant on a nested insert.

**Comment by tirumaraiselvan** [comment]
@anisjonischkeit  `insert_users_one` is same as `insert_users` except that you can only insert one object and hence the type of `insert_users_one` is the table type. Can you explain what do you mean by "prefill" foreign key? You mean a nested insert which goes through with `insert_users` does not go through with `insert_users_one`?

**Comment by anisjonischkeit** [comment]
Ahh, I see the problem. Somehow I had an object and an array relationships for the same data. So while inserting I was seeing that I could insert one item or multiple... turns out the object relationship was actually not correct (it didn't actually make sense) and had no foreign key attached anyway. I did some programmatic changes to migrations so I think I may have messed it up there...
