### ISSUE TITLE
console: view relationship rows in data browser break for relationhips with bigint fkeys

### ISSUE THREAD

**Issue by Carleslc** [hasura/graphql-engine#4548]
I'm running v1.1.1 and having the following error when clicking on "View" for some table relationships in the console.

```
TypeError: Cannot read property 'user' of undefined
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/main.js.gz:1:3306984
    at Array.map (<anonymous>)
    at e (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/main.js.gz:1:3306937)
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/main.js.gz:1:3311060)
    at ho (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2735842)
    at Wo (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2742798)
    at Xo (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2749148)
    at fs (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2771675)
    at ds (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2772065)
    at Js (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:2779243)
```

I tried to reload metadata with no success.

**Comment by GavinRay97** [comment]
Hey Carlos, would you be able to attach your migrations, metadata, and Dockerfile/Docker Compose setup so that attempts to replicate this could be made?

**Comment by Carleslc** [comment]
After further investigation, it seems that this error is coming from tables with big integer columns. I have a custom id generator function that returns a bigint, and somehow Hasura is converting the assigned values to another close value (casting problem maybe?). Seems related to https://github.com/hasura/graphql-engine/issues/3667 and https://github.com/hasura/graphql-engine/issues/3697

This error is also raising foreign key violations when using GraphiQL to insert rows.

I have created a fresh new instance on Heroku with the one-click button at [https://hasura-issue-4548.herokuapp.com/](https://hasura-issue-4548.herokuapp.com/) to replicate this problem with a few tables: users, posts and comments. Migrations and metadata are available at https://github.com/Carleslc/hasura-issue-4548.

Some images for demonstration:

1. Create a post
![Create a post](https://i.imgur.com/RKZz1IM.png)
Pay attention to the returning id: `84154414708818940`

2. Try to insert a comment
![Try to insert a comment](https://i.imgur.com/WHDKrfQ.png)
Oops.

3. Ok, let's run a simple select on Raw SQL to see the post id
![SQL Select Post Id](https://i.imgur.com/q2E088D.png)
See? The post id is `84154414708818947`, not `84154414708818940`. The last digit shown by Hasura is wrong. Sometimes is a 0 or 5, sometimes even two last digits are wrong.

4. Let's try to insert the comment again, this time with the actual post_id
![Insert comment again with GraphiQL](https://i.imgur.com/tErAAbY.png)
Foreign key violation again. This simple task seems impossible.

5. So, what about using Raw SQL?
![Insert comment with Raw SQL](https://i.imgur.com/qaanAPz.png)
Now it works.

6. Switch to [comments](https://hasura-issue-4548.herokuapp.com/console/data/schema/public/tables/comments/browse) in Data tab
![Comment with wrong rendered id](https://i.imgur.com/fgiDU7y.png)
Wrong id for the comment too, and with two digits.

7. Let's try to click "View" in "users" relationship
![View users relationship](https://i.imgur.com/WpbBvg9.png)
This is the error posted in the first message of this issue.

This does not happen with the relationships of users table, as Hasura can find the user with its text id primary key.

Moreover, deleting rows with Hasura console in Data tab for posts and comments affects 0 rows, so deleting does not work in this case either. Delete from Raw SQL with the actual id and it works.

**Comment by rikinsk** [comment]
Should get fixed with #3667

**Comment by rikinsk** [comment]
This issue gets fixed once you set the `HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES` env var while running the GraphQL Engine. See [server config reference](https://hasura.io/docs/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html). This happens due to the max size of integers supported in JSON which is not sufficient to store PG bigint s

**Comment by rikinsk** [comment]
Closing this issue. Please feel free to reopen if there are further questions or some other thoughts to add
