### ISSUE TITLE
Feat: Define aggregate_fields on array_relationships so permissions can be centrally managed

### ISSUE THREAD

**Issue by jrhicks** [hasura/graphql-engine#455]
Imagine in the  the example poll app that an adminstrator detected some voting abuse and decided to institute a quality control process.  The developer added a field to the vote called `is_valid` and wants only the valid votes to be visible to users.  So he adds a user permission { is_valid: true }
 
Unfortunately, the developer forgot that there was a poll_results view that accessed votes directly without any knowledge of Hasura's centrally managed permissions.  

```sql
CREATE VIEW public.poll_results AS
 SELECT poll.id AS poll_id,
    o.option_id,
    count(*) AS votes
   FROM (( SELECT vote.option_id,
            option.poll_id,
            option.text
           FROM (public.vote
             LEFT JOIN public.option ON ((option.id = vote.option_id)))) o
     LEFT JOIN public.poll ON ((poll.id = o.poll_id)))
  GROUP BY poll.question, o.option_id, poll.id;
```

Since the developer implemented aggregate fields using hand written views, the users vote total count includes both valid and invalid votes.

**Comment by 0x777** [comment]
@jrhicks @vtrc Aggregations on tables and array relationships are now supported from `alpha26`. https://github.com/hasura/graphql-engine/releases/tag/v1.0.0-alpha26
