### ISSUE TITLE
error when inserting through data browser on Postgres 12 "Generated column" based table

### ISSUE THREAD

**Issue by iamkhalidbashir** [hasura/graphql-engine#4552]
Hey folks,

Today I decided to use Postgres 12 feature **Generated columns** (instead of hasura computed columns for efficiency), here is what went wrong:-

1. The Generated column name is "FLID"
2. It just concats 2 text columns in the same table. (No issue found while creating on Postgres)
3. When inserting through Hsaura console, this error was shown:-

![Screenshot from 2020-04-23 18-17-40](https://user-images.githubusercontent.com/27646811/80103961-47d23f00-858f-11ea-89c2-d2b4000b1961.png)

It seems hasura thinks "FLID" is a normal column and tries to insert into it, while Postgres doesn't allow you to insert it into a generated column.

Note: I have tried to pass NULL and a random value into "FLID" on INSERT, still the same error.

Regards,
Khalid Bashir

**UPDATE 1:-**

1. Hasura Metadata was not synced with postgres, because I created the column on postgres.
2. After Syncing a new error comes into action:-

```json
{
    "statement": "WITH \"fl_centers_info__mutation_result_alias\" AS (INSERT INTO \"fl_centers\".\"info\" ( \"flcn_role\", \"FLID_zone_code\", \"flcn_name\", \"FLID_region_code\", \"flcn_active_status\", \"FLID\", \"flcn_customer_fulfillment_status\", \"created_at\" ) VALUES ($1, $2, $3, $4, $5, $6, $7, DEFAULT)  RETURNING * , CASE WHEN 'true' THEN NULL ELSE \"hdb_catalog\".\"check_violation\"('insert check constraint failed')  END ) SELECT  json_build_object('returning', (SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_1_e\"  FROM  (SELECT         ) AS \"_1_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"fl_centers_info__mutation_result_alias\" WHERE ('true')     ) AS \"_0_root.base\"      ) AS \"_2_root\"      ), 'affected_rows', (SELECT  COUNT(*)  FROM \"fl_centers_info__mutation_result_alias\"      ) )        ",
    "prepared": true,
    "error": {
        "exec_status": "FatalError",
        "hint": null,
        "message": "cannot insert into column \"FLID\"",
        "status_code": "42601",
        "description": "Column \"FLID\" is a generated column."
    },
    "arguments": [
        "(Oid 25,Just (\"PRIMARY\",Binary))",
        "(Oid 25,Just (\"LH\",Binary))",
        "(Oid 25,Just (\"New Muslim Town\",Binary))",
        "(Oid 25,Just (\"NMT\",Binary))",
        "(Oid 25,Just (\"OFFLINE\",Binary))",
        "(Oid 25,Nothing)",
        "(Oid 25,Just (\"OFFLINE\",Binary))"
    ]
}
```
3. The reason is still same, i.e, Hasura console INSERT ROW tab is trying to insert a generated column.
4. It does not happened when inserting through graphql API though, so this can be treated as minor issue currently, but it might be a quick fix also.

**Comment by tirumaraiselvan** [comment]
@iamkhalidbashir Thanks for reporting.

Yes, you need to refresh the schema if you made any DDL changes from outside of Hasura.

Can you tell us the Hasura version you are using? Also, does this happen in the latest v1.2.0 release?

**Comment by iamkhalidbashir** [comment]
Hasura version: v1.1.1
Scheme reloaded
