### ISSUE TITLE
Deleting composite PK rows in batch

### ISSUE THREAD

**Issue by FredyC** [hasura/graphql-engine#4556]
## Current behavior

Looks like it's not possible right now (1.2.0-beta.4)?

What I mean is with a table of composite PK of two columns, when I would like to delete multiple rows, then the only query that comes to my mind is like following, but I doubt it comes with the intended outcome. It's not possible to verify that because Analyze in the API Explorer works for queries only.

```gql
mutation {
  delete_object(where: {firstId: {_in: [$firstIds]}, secondId: {_in: $secondIds}}) {}
}
```

## Expected behavior

I would like to be able to run a mutation like the following.

```gql
mutation {
  delete_objects_by_pk([{ firstId: '', secondId: ''}, { firstId: '', secondId: ''}]) {}
}
```

## Workarounds

I suppose it's either about deleting with `delete_object_by_pk` one by one (feels expensive) or adding non-composite PK only for that purpose.

**Comment by FredyC** [comment]
I take it back. Despite suspiciously looking query, after running a few tests it does seem to be deleting only what it's supposed to and nothing more. That was unexpected :)

**Comment by haaah** [comment]
@danielkcz may i know how does the query look like ? was trying out
`mutation {
  delete_objects_by_pk([{ firstId: '', secondId: ''}, { firstId: '', secondId: ''}]) {}
}`
in graphiQL but was unsuccessful.
