### ISSUE TITLE
Select - Row Limit picker hides 0 in Console

### ISSUE THREAD

**Issue by brenjay** [hasura/graphql-engine#4559]
First off - wonderful project! Ran into a maddening issue in the Console UI which caused me trouble for hours until I could figure out what it was; currently using v1.2.0-beta.5.

When editing permissions schema for 'select' and specifying a row limit, it is possible to iterate the number picker down to 0. However, the picker doesn't actually display '0'. Thus, you can save the schema and assume you actually have no row limit; when in fact its actually set at 0, but the number picker is blank so you assume everything is good and its set to null. All my queries for a particular role kept returning nothing; and I couldn't figure out why; as I kept pouring over the permissions schema and everything had "green checkmarks". 

The row limit picker's input for 'select' is hidden when set to 0 AND null in /tables/{name}/schema page, it just appears blank. However, in /schema/public/permissions, it actually does show the row limit integer, even when 0, and when null it displays a X, so that's how I figured out what the problem was. 

If the row limit gets set accidently to 0; you have to go back into the /tables/{name}/schema/ page, set the row limit picker to any positive integer, save the schema, then refresh the page, and remove the integer altogether so the field is blank; then save, and finally the row limit will be set to null instead of 0. Also I found that if you type '0' in the number picker, even though the picker shows nothing, if you save it, it will be saved as a 0 and you'll have to do the process described to remove it again. 

Finally, it would be helpful for the UI to display the 'filter' icon when the Row Limit is set to anything but null. The 'select' column displays a green check for the field regardless of row limit value; which can be deceptive when you're looking at permissions and think an action has no modifications when in fact it does.

**Comment by GavinRay97** [comment]
Good catch, thank you!
