### ISSUE TITLE
Create action fails silently if referencing an undefined environment variable

### ISSUE THREAD

**Issue by devuxer** [hasura/graphql-engine#4568]
This bug occurred while trying to create an Action in the console.

For the handler field, I referenced an environment variable that I hadn't yet added to my docker container. (I had added the environment variable to my docker-compose but hadn't yet restarted the container.)

When I clicked Create, I saw a "Creating Action" message, but then the message went away and nothing changed on the screen. This led me to open the Chrome dev tools, where I saw an "unexpected token i in JSON" error. This didn't really help, but I was eventually able to get to this much more useful error message by putting in a breakpoint and looking at the string it was trying to parse:

> "reason": "in action "proposeNewEmailAddress"; Value for environment variables not found: NETLIFY_FUNCTIONS_URL"

Here's a screen capture of the action I was trying to create:

![image](https://user-images.githubusercontent.com/1298521/80318948-7b48df80-87c2-11ea-97b8-de290be87556.png)

**Comment by devuxer** [comment]
Followup:

1. Cycling docker down and up with the environment variable configured did in fact allow me to create the action.
2. A migration was created for every attempt, so even though the error seemed to prevent the action from being created, it wrote the migration as if everything were fine.

**Comment by arvi3411301** [comment]
@devuxer Can you provide us the version of CLI you are using by running `hasura version`

**Comment by devuxer** [comment]
Hey @arvi3411301 

Good question:

hasura cli - version=v1.2.0-beta.2
hasura graphql engine - version=v1.2.0-beta.5

Perhaps the CLI being older than the engine was the cause? I did everything from the console, not the CLI, though.

**Comment by arvi3411301** [comment]
@devuxer We have fixed the mentioned issue in `v1.2.0-beta.4`. Can you try updating the cli to `v1.2.0-beta.5` by running `hasura update-cli --version v1.2.0-beta.5`

**Comment by devuxer** [comment]
@arvi3411301 ,

That fixed it, thanks! I now get a "Creating action failed", with a button to show the details.

Next time, I'll make sure I have the latest engine *and* CLI.
