### ISSUE TITLE
Allow multiline mode for input with type text

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#458]
Currently if we choose `text` type, hasura still allows only 1 line input.
We should allow multiline text area for multiline input also.

Even better suggestion: Allow WYSIWYG and Markdown mode as options for users to switch. And we could allow for even more formats in future (like LaText)

This is really cool feature to have, because it'll allow rich text inputing right from the Hasura console UI without any need for external system.

**Comment by praveenweb** [comment]
@coco98 @karthikvt26 - Should we bring back the rich text editor or just convert simple text box into text area for now?

**Comment by Anupam-dagar** [comment]
I would like to work on this issue.

**Comment by mnlbox** [comment]
@Anupam-dagar any plan for add mask textbox?
