### ISSUE TITLE
Define lookup_fields on Object Relationships to enable sorting / filtering on related fields

### ISSUE THREAD

**Issue by jrhicks** [hasura/graphql-engine#459]
Analogous to aggregate_fields that you plan to allow developers to define on "array_relationships" .... you might consider providing lookup_fields on "object_relationships".

Lookup fields add the ability to sort and filter on related fields.  For example, without lookup_fields the following order_by isn't valid:

```
{
  work_orders(order_by: contractor_name_asc)  {
    id
    work_order_no
    contractor {
      name
    }
  }
}
```

End users have a strong expectation when being displayed a data grid / table to be able to click any table header and sort. 

After allowing the developer to create a lookup columns "contractor_name" that points to the contractor's name ... the following would be valid:
```
{
  work_orders(order_by: contractor_name_asc)  {
    id
    work_order_no
    contractor_name
  }
}
```

**Comment by revskill10** [comment]
@jrhicks  Could custom view resolve this issue ?

**Comment by 0x777** [comment]
@jrhicks we support filtering on related fields already. For example, you can do this:
```graphql
{
  work_orders(where: {contractor: {name: {_eq: "somename"}}} )  {
    id
    work_order_no
  }
}
```

We don't yet support ordering using related fields. But we will definitely be adding this.

**Comment by jrhicks** [comment]
Cool.  I will close the Issue.
