### ISSUE TITLE
No null casting for non-nullable data type. 

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#460]
In Hasura, an object relationship is marked as non-null only if the underlying foreign key column is non null according to Postgres. For example, in article table if you have a column called author_id with foreign key constraint to author's id, the object relationship author is only marked as non-null if author_id has not null constraint in Postgres.

Currently Hasura won't raise any error in graphiql because it returns `null` for you.
But if you want to use schema stitching, it's impossible because it will raise runtime error.

Suggestion to fix: Mark object relationship data type as `nullable` or returning an `inner join` result instead.

**Comment by coco98** [comment]
Object relationships currently show up as:

```
article:
  id Int!
  title String!
  author author!
```

This should be:
```
article:
  id Int!
  title String!
  author author
```

**Comment by revskill10** [comment]
This also related to [this issue](https://github.com/hasura/graphql-engine/issues/456)

**Comment by revskill10** [comment]
@coco98 What if the result is
```
null: {
null: {
null
}
}
```
?

**Comment by 0x777** [comment]
closing in favor of https://github.com/hasura/graphql-engine/issues/462
