### ISSUE TITLE
"npm run start" doesn't work.

### ISSUE THREAD

**Issue by AfricanBones** [hasura/graphql-engine#4603]
I've installed all the packages that i need with npm install etc and I've created a script called "start" in packages.json.

When I do this command "npm run start" this comes up 

Error: Cannot find module 'D:\Project\react-scripts\bin\react-scripts.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

And I have no clue how to fix it.

**Comment by rikinsk** [comment]
Hey. Can you share some details on what project you're trying to run `npm run start` on?

**Comment by aleareco** [comment]
Hi. Any luck with this? I am trying to test a JS file and get the same error.

**Comment by rikinsk** [comment]
@aleareco what project are you facing the error in?

**Comment by aleareco** [comment]
Hi @rikinsk! I already fixed this problem, thanks for replying though :-)

**Comment by AfricanBones** [comment]
> Hey. Can you share some details on what project you're trying to run `npm run start` on?

I managed to solve it myself. Thanks anyway :)
