### ISSUE TITLE
v1.2.0 console not accessible in Safari 13.1 (desktop)?

### ISSUE THREAD

**Issue by r-moore** [hasura/graphql-engine#4605]
Having upgraded an instance from v1.0.0 to v1.2.0 today I can no longer access the web console in Safari browser.

Safari v13.1
MacOS 10.15.4

hasura-console CLI v1.2.0

In the browser's javascript console I see this error:
`SyntaxError: Invalid character '\ud801'`

It gets stuck at the Loading... screen:
<img width="218" alt="image" src="https://user-images.githubusercontent.com/366280/80609389-eb0fd200-8a2f-11ea-8edb-63376a164230.png">

I have tried clearing all caches and resetting browser to no avail. I see the same thing on another MacOS machine too.

I do not get stuck or see the console error in Chromium-based browsers.
I do not get stuck or see the console error in Safari Technical Preview (v13.2 release 105).

**Comment by r-moore** [comment]
I also get this issue regardless of whether I access the web console via the CLI proxy (`hasura console`) or directly (when `HASURA_GRAPHQL_ENABLE_CONSOLE=true`)

**Comment by KCErb** [comment]
I also just updated to v1.2.0 but I'm on the cli-migrations version. I'm not having any trouble in safari viewing the CLI UI that I launch to 9695 with `/bin/hasura-cli console` from the container.

**Comment by rikinsk** [comment]
Closed via #4612

**Comment by r-moore** [comment]
Just to say that this bug seems to have resurfaced when I tried out Hasura Cloud today (running ver. `v1.3.0-cloud.1`). 

Works in Chrome, but in Safari I can't launch the Hasura Console and see `SyntaxError: Invalid character '\ud801'` in browser console.
