### ISSUE TITLE
Cannot insert more than 1 row simultaneously into table with generated columns

### ISSUE THREAD

**Issue by medvesekg** [hasura/graphql-engine#4633]
# Using
- Hasura v1.2.0
- Postgres 12.2
# Steps to reproduce
1. Create a fresh Hasura app on Heroku
2. Create a table
![image](https://user-images.githubusercontent.com/25692818/80745107-12de6300-8b20-11ea-9ec6-5ed292c883b4.png)
3. Add generated column to table 
```
ALTER TABLE people 
ADD COLUMN full_name text 
GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED
```
4. Inserting a single row works fine 
![image](https://user-images.githubusercontent.com/25692818/80745692-f7278c80-8b20-11ea-81ba-c7e985385e0c.png)

5. Inserting more than one row gives an error
![image](https://user-images.githubusercontent.com/25692818/80745735-0ad2f300-8b21-11ea-9828-fd35cef18de0.png)

```
{
  "errors": [
    {
      "extensions": {
        "internal": {
          "statement": "WITH \"people__mutation_result_alias\" AS (INSERT INTO \"public\".\"people\" ( \"first_name\", \"full_name\", \"last_name\", \"id\" ) VALUES (($1)::text, DEFAULT, ($2)::text, DEFAULT), (($3)::text, DEFAULT, ($4)::text, DEFAULT)  RETURNING * , CASE WHEN 'true' THEN NULL ELSE \"hdb_catalog\".\"check_violation\"('insert check constraint failed')  END ), \"people__all_columns_alias\" AS (SELECT  \"id\" , \"first_name\" , \"last_name\" , \"full_name\"  FROM \"people__mutation_result_alias\"      ) SELECT  json_build_object('affected_rows', (SELECT  COUNT(*)  FROM \"people__all_columns_alias\"      ) )        ",
          "prepared": true,
          "error": {
            "exec_status": "FatalError",
            "hint": null,
            "message": "cannot insert into column \"full_name\"",
            "status_code": "42601",
            "description": "Column \"full_name\" is a generated column."
          },
          "arguments": [
            "(Oid 25,Just (\"John\",Binary))",
            "(Oid 25,Just (\"Doe\",Binary))",
            "(Oid 25,Just (\"Jane\",Binary))",
            "(Oid 25,Just (\"Doe\",Binary))"
          ]
        },
        "path": "$.selectionSet.insert_people.args.objects",
        "code": "unexpected"
      },
      "message": "database query error"
    }
  ]
}
```

**Comment by tirumaraiselvan** [comment]
Related: https://github.com/hasura/graphql-engine/issues/4506

**Comment by codingkarthik** [comment]
It seems that this issue is caused due to a bug in postgres while inserting mutliple rows having a default generated column. The postgres bug is tracked [here](https://www.postgresql.org/message-id/3a66b26f-0154-3216-1ed5-a63bf63ec61a%402ndquadrant.com)

**Comment by huss-jay** [comment]
Any updates on this? Not sure what the solution is to inserting multiple rows with a generated column.

**Comment by EdNutting** [comment]
This is a critical roadblock to our application. Inserting single rows one at a time is unrealistic given we may be inserting upwards of 2.000 rows in a single mutation, (and really they need to be inserted as a single transaction).

* Any word on whether Hasura will be patching around the Postgres bug? (Esp. given Postgres team don't seem to be making any progress)
* In addition, it would be good if Hasura added something to the docs or Console to highlight this known issue - it has been around, unfixed, for long enough now that this seems justified.
* In addition, it would be good if Hasura processed the error message from Postgres to substitute the error message for something more helpful. It took me several hours to find this GitHub issue, after getting lost in the various other (very similar) issues/PRs that claim this is fixed (but for the case of multi-insert, it isn't).

**Comment by yoshiwarab** [comment]
@tirumaraiselvan Checking in again to see if there are any plans to implement a workaround? Doesn't look like the Postgres team is planning on fixing this anytime soon. Thanks!

**Comment by tomjohn1028** [comment]
This issue is a bummer. Has anyone found a work around besides the single insert? I'm very new to Hasura. Is there a way to derive and create a custom action to bulk insert that way we can explicitly exclude the generated column?

**Comment by Gozala** [comment]
Just burned a day trying to figure out what the problem was here so it would really help if this known issue was surfaced better somehow. 

@0x777 Is there a chance to surface an option to disable certain columns in mutations ? That way all generated columns could be omitted by default and this issue would be solved. Even without automated disabling of generated columns manual disabling would provide a reasonable workaround.

**Comment by stefanquy** [comment]
Is there a solution or work around for this problem yet?

is it possible to create a custom input type, which leaves out the generated fields? 
if so how do we create a custom input type, or use a custom input type in a mutation?

**Comment by Bessonov** [comment]
Not sure if it helps and I didn't tried it, but I think with some tweaks and workarounds [this one](https://stackoverflow.com/questions/54232496/multi-row-conditional-insert-with-default-values/56207456#56207456) can at least help with batch inserts.

**Comment by rikinsk** [comment]
Fixed via https://github.com/hasura/graphql-engine/commit/e1918adb529344f790c0fe46f1153c065ce2ffbe
