### ISSUE TITLE
Anonymous  access with Firebase

### ISSUE THREAD

**Issue by Ahmad-Saleem** [hasura/graphql-engine#4642]
I can not access to Hasura query (anonymous role) when I used firebase auth (without token), 
I know I can access when signing in anonymously by Firebase, but I need to access Hasura before signing in.

**Comment by FredyC** [comment]
I highly recommend you to spend more time with Hasura docs. They have one of the best ones I have seen...

https://hasura.io/docs/1.0/graphql/manual/auth/authentication/unauthenticated-access.html

**Comment by Ahmad-Saleem** [comment]
@FredyC I did, but I think i had the issue after upgrading it to the latest version, I just re-create hasura with the new version and it is working well now.

**Comment by Ahmad-Saleem** [comment]
https://github.com/hasura/graphql-engine/issues/4648
