### ISSUE TITLE
Permission backend-only is only available for insert

### ISSUE THREAD

**Issue by EmrysMyrddin** [hasura/graphql-engine#4643]
The new permission option `bakcend-only` is only available in the console for insert's permissions.

Is it intended ?

If not, it could be great to have `backend-only` permissions also for other permission types.

My use case is for an authentication backend which is using Hasura's endpoint to verify user's password. Which I don't want to be available outside of my authentication backend.

**Comment by jlowin** [comment]
At least, it would be great to see it on updates as well

**Comment by webdeb** [comment]
we are using it to make a json-to-html conversion to make sure, we are storing safe markup.
backend-only is very important in this case. **update** is very important in this case.

**Comment by pablogomezlhp** [comment]
any update on this??
