### ISSUE TITLE
Upgrading to v1.2.0 from v1.1.0 breaks jwt auth permissions using roles

### ISSUE THREAD

**Issue by cetchells** [hasura/graphql-engine#4648]
I am using apollo-client with vue. I get my jwt which has the allowed roles
`'x-hasura-allowed-roles':['admin'],
 'x-hasura-default-role': 'admin'`
 This worked fine on v1.1.0.  
After upgrading to V1.2.0 I now get ` 'Customer not found in type: 'query_root'` errors' on every query.

**It works if I add the admin secret header.**
`["x-hasura-admin-secret"]=xxxxxx`
So I guess its a permissions issue.
Do I have to reapply the permissions for admin after upgrade?
If so, how do you do that?

**Comment by FredyC** [comment]
Um, the admin role has implicitly permissions to everything and for that, you need to use admin secret. On the contrary, you shouldn't need to specify a role at all. I don't know how it worked in 1.1.0, I started with Hasura recently.

**Comment by teflorg** [comment]
@FredyC I'm refering to  a client, in this case Vue authenticating using a JWT that contains the role, as per [the docs](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/index.html) the token contains the role and claims, I also includes the X-Hasura-User-Id. If you look at 'Authentication options' its option 2. JSON JWT

**Comment by cetchells** [comment]
It looks like I was storing  a value in `"x-hasura-role"` which was not admin, in the JWT, if I remove that it works again. So yeh don't store any app specific roles in there, not sure if that overriding, `'x-hasura-allowed-roles':['admin'], 'x-hasura-default-role': 'admin'` didn't seem to in v1.1.0
