### ISSUE TITLE
Permission: one to many relationship

### ISSUE THREAD

**Issue by amitava82** [hasura/graphql-engine#4658]
I have tables `users` and `user_parents`. A user have many parents and `user_parents` is linking table.
```
users
id   name
1    Parent 1
2    Child
```
```
user_parents
child_id   parent_id
2             1
```
A user should be able to update own parents.
```
mutation {
// update a parent 1 by user 2
 update_users(where: {id: {_eq: 1}}, _set: {name: 'foo'}) {
    returning {
      id
    } 
 }
}
```
I'm not sure how to model this permission. Seems like I need more than `X-Hasura-User-Id` session variable to check permission. I need to check X-Hasura-User-Id and updating id matches with user_parents table.

**Comment by rikinsk** [comment]
i assume you have parent and children relationships set up across the two tables. 

``user`` -> ``user_parents`` (``user_parents.child_id -> user.id``) -> ``parent`` (``user_parents.parent_id -> user.id``)
``user`` -> ``user_children`` (``user_parents.parent_id -> user_id``) -> ``child`` (``user_parents.child_id -> user.id``)

Then the permission rule for user table could be as follows:
```json
{
   "_or":[
      {
         "id":{
            "_eq":"X-Hasura-User-Id"
         }
      },
      {
         "user_children":{
            "child_id":{
               "_eq":"X-Hasura-User-Id"
            }
         }
      }
   ]
}```

This would mean that the `user` will be allowed to be updated if the user making the request is the user themself or is a child of the user

**Comment by amitava82** [comment]
Thanks! it worked. I was missing one of the relations
