### ISSUE TITLE
cli: cli-migrations image fails if actions files are not present

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#4670]
CLI migrations v2 image throws an error if the metadata directory does not contain actions.graphql, even though there are no actions in the project

I don't get the actions files when I export the metadata

```
metrics_1        | time="2020-05-05T06:39:18Z" level=fatal msg="failed to apply metadata: cannot apply metadata on the database: cannot build actions from metadata: error in reading actions.graphql file: open /tmp/hasura-project/metadata/actions.graphql: no such file or directory"

```

**Comment by MeixnerTobias** [comment]
Ran into that issue after upgrading a project from v1 to v2 configuration

Attempted to quick by adding an empty metadata/actions.graphql
which then lead to:

> failed to apply metadata: cannot apply metadata on the database: cannot build actions from metadata: error in reading actions.yaml: open /home/circleci/repo/hasura/metadata/actions.yaml: no such file or directory 

Then added an empty metadata/actions.yaml

So I guess these files need to handle non existence or have to be generated by: hasura scripts update-project-v2

**Comment by vitorbertulucci** [comment]
Same issue here! A month ago I was trying to update other project following the Updgrade Guide in Hasura Docs and I don't remember to get problems with that. Maybe it's some update from hasura-cli version. I'm now using v1.2.1.

For now, I'm going to use @MeixnerTobias steps to temporary fix this problem. Thanks!

**Comment by scriptonist** [comment]
Resolved in https://github.com/hasura/graphql-engine/pull/5170
