### ISSUE TITLE
Insert and update in one transaction

### ISSUE THREAD

**Issue by mrspartak** [hasura/graphql-engine#4672]
Need help, please. Maybe there is a way to make this.
In my case, I need a transaction, when I insert a new row and get auto-increment id and then update another table with this new ID.

Example tables:
Images:
-id
-type
-url

User:
-id
-profile_picture_id -> Images.id

So, I'm uploading a new image, inserting information into table Image and updating User.profile_picture_id 
I can make it in two requests, but this way this will not behave like a transaction

**Comment by leoalves** [comment]
@mrspartak,
You can do nested inserts.
https://hasura.io/docs/1.0/graphql/manual/mutations/insert.html#insert-an-object-along-with-its-related-objects-through-relationships

**Comment by mrspartak** [comment]
@leoalves 
I know about the nested insert. But I need an update and insert

**Comment by Motoxpro** [comment]
Nested updates are on their way https://github.com/hasura/graphql-engine/pull/3852

You can achieve what you are trying to do with https://hasura.io/docs/1.0/graphql/manual/mutations/upsert.html

Insert the image with the fields `type, url` leave `id` for the `image` blank and it will be generated automatically.
Then, nest your `user` with, `id` and leave the relationship blank. Hasura will handle it automatically
Add a constraint on the `user` to just update the `profile_picture_id` on an existing `id`

This is in React with graphql-code-generator codegen but you can do something like this
```
const imageToInsert = {
          type: image.type,
          url: image.url
          user: {
            data: { id: user.id },
            on_conflict: {
              constraint: UserContraint.UserPkey,
              update_columns: UseUpdateColumn.ProfilePictureId],
            },
          },
        };
```

The mutation

```
mutation insertImage(
    $imageToInsert: [image_insert_input!]!
  ) {
    insert_image(
      objects: $imageToInsert
      on_conflict: {
        constraint: image_id_pkey
        update_columns: [type, url]
      }
    ) {
      affected_rows
    }
```


However, a common way to solve this is to generate your IDs on the client. You will very likely run into problems dealing with those auto-generated ids when you need to keep the UI up to date. e.g. You only have a unique identifier for the image AFTER it is returned from the database which is not ideal. Most likely you are already using something to identify the image on the client so I would use that as your primary key in the database.

**Comment by mrspartak** [comment]
@Motoxpro thank you. This should work but looks really hacky. Cause I still have to present not the only ID of the user but have to meet all the constraints (for example present all not nullable keys here too).
Hope nested updates are on the way.

And the part of the primary key. We use placeholder images, so we don't really care if some data exists or not.

**Comment by Motoxpro** [comment]
@mrspartak No worries. Like I said, if you want to be able to do what you are talking about you need to generate the ids on the client, otherwise, nested updates or not, it will always look like that there is no way around that if you are auto-generating ids.

e.g. in a transaction

```
const profilePictureId = generateUuid()

const imageToInsert = {
          id: profilePictureId,
          type: image.type,
          url: image.url
        };
```
```
mutation insertImage(
    $userId: Int!
    $profilePictureId: Int!
    $imageToInsert: [image_insert_input!]!
  ) {
    insert_image(
      objects: $imageToInsert
    ) {
      affected_rows
    }
   update_user(
      where: { id: { _eq: $userId } }
      _set: { profile_picture_id: $profilePictureId }
    ) {
      affected_rows
    }
}
```
