### ISSUE TITLE
console: editing permissions manually seems to have stopped working properly

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#4683]
It's not possible to edit the JSON string in the permissions section.

**Current behaviour:**
![2020-05-18 at 19 43 30 - Peach Bat](https://user-images.githubusercontent.com/9019397/82243456-f0ca4a80-993f-11ea-8925-11c000d817fe.gif)

**Previous behavior:**
<img width="400" src="https://user-images.githubusercontent.com/9019397/82243912-a9908980-9940-11ea-9441-19ed32c87d0e.gif" />

**Comment by KATT** [comment]
+1
