### ISSUE TITLE
show tooltip / suggestion for using action handler templates in console

### ISSUE THREAD

**Issue by Toub** [hasura/graphql-engine#4689]
I would like to be able to define action trigger URL from environment variable, exactly as I am able to define trigger webhook URL from environment variable:

__TRIGGERS__

![image](https://user-images.githubusercontent.com/367762/81177059-c1febc80-8fae-11ea-8cb8-b56c4cad0cdd.png)

__ACTIONS__

![image](https://user-images.githubusercontent.com/367762/81177118-d5aa2300-8fae-11ea-9338-0c60d8bc884f.png)

Is it possible or planned? It is required to deploy hasura actions to different environments.

**Comment by rikinsk** [comment]
@Toub This is possible to do. Though the behaviour is a little different than the event trigger. You can see the note about URL templating in the [actions docs](https://hasura.io/docs/1.0/graphql/manual/actions/create.html#step-2-create-the-action-handler) for more info.

Do let us know if this doesnt solve your requirement

**Comment by rikinsk** [comment]
This behaviour can be made easier to discover via a simple note / tooltip in the console. WIll use this issue to track that

**Comment by Toub** [comment]
Thanks @rikinsk

That's great and much better, as we don't have to define an environment variable for each endpoint!

Is it also available for triggers?

BTW, your suggestion to add a simple note about this in the console is a good idea (I tried but it fails as I used this format: ${MY_SERVER}/api/endpoint

**Comment by rikinsk** [comment]
@Toub Unfortnately its not available for triggers yet. There is an open issue at #2483

**Comment by beerose** [comment]
Closed via https://github.com/hasura/graphql-engine/pull/5066
