### ISSUE TITLE
Hasura Con 2020 CFP

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#4694]
Hey there, we are so excited that you're interested in speaking at the first ever Hasura Con (our online Hasura conference)! The talks will be held from 9am - 12 pm PST on 8th, 9th & 10 of June.

This is a conference for our users & the community! We'd love to hear you speak if you are using Hasura in your applications, are part of the community, building tooling around Hasura or work at a company whose products work very well with Hasura!

Talk topic ideas:

- Use-cases & product showcases of applications built with Hasura.
- Insights around using Hasura for the industry that your product is in.
- Reference architecture of your Hasura apps.
- Tooling that you've created that works well with Hasura.
- Product integrations with Hasura (devrels, this one is for you :)).
- Community oriented talks around using Hasura or being a part of the Hasura - community.
- These are indicative topic themes! Please do submit talks even if they don't fit into these themes!

Submit your ideas [here](https://docs.google.com/forms/d/e/1FAIpQLScW8-f8XBStaODlg_FgieTmtuv2XyqrvKYRBT7hzdmjHpVerw/viewform).

**Comment by webdeb** [comment]
#HONCONF
