### ISSUE TITLE
export_metadata doesn't include field info?

### ISSUE THREAD

**Issue by ElixirMike** [hasura/graphql-engine#4695]
I am looking at trying to use replace_metadata API call to push fresh changes to Hasura, instead of having changes fetched from postgres.

To test this, I used the export_metadata api call to get the current version of metadata. However, when I look at it, it does not contain any field level info within the tables? 

To test this, I exported the metadata. I then did a run sql command and added a new column to a table. I ran export_metadata again, and the files are identical.

Am I missing something here? I'm hoping to find a way I can make changes on the DB using the runsql api query with the flag check_metadata_consistency to false, and then to post an updated schema in via replace_schema. api call. 

https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/run-sql.html

Is there something else I need to do in order to export/replace the metadata via API?

**Comment by rikinsk** [comment]
@ElixirMike When new columns are added to a table that is already tracked, the new columns will automatically be added to the GraphQL schema whenever it is refreshed. The GraphQL schema is refreshed everytime the server starts, metadata is imported or when the reload_matadata API is hit.

**Comment by ElixirMike** [comment]
so, in the case where I have a table tracked and for permissions I have specified the wildcard * for the columns...when I run a sql satement to add a new column/drop a column, the actual metadata will not have changed, yet I know it won't see those changes by default. Does that mean, I can add a column via api with flag for check_metadata_consistency = false and simply call reload_metadata in order for field to be seen in permission, etc?

Previously my work around for when I added a field via API was that I needed to include api calls to delete all permissions and then re-add all permissions which is very slow.  But again, at the end of that, the metadata hasn't changed, it still shows permission with columns having *.  It would be big performance improvement I believe if I could make sql change, and then just run reload_metadata ...or if I have the metadata stored someplace, just call replace_metadata with existing metdata for field to appear correctly?

**Comment by tirumaraiselvan** [comment]
>  Does that mean, I can add a column via api with flag for check_metadata_consistency = false and simply call reload_metadata in order for field to be seen in permission, etc?

Yes. Per our convos, I believe you have got this working up-till here. Closing this issue.
