### ISSUE TITLE
[graphql-engine] Unable to override port

### ISSUE THREAD

**Issue by mubaidr** [hasura/graphql-engine#4701]
`graphql-engine` always starts on default port `8080` even if the port is specified. 

```bash
graphql-engine --port 9090 serve
```

Version: hasura/graphql-engine:v1.2.1
Running in Docker on Windows

**Comment by scriptonist** [comment]
Hey @mubaidr 👋 , I think you are looking for `--server-port` 
https://hasura.io/docs/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html#command-flags

**Comment by mubaidr** [comment]
But the `graphql-engine` binary help points to `--port` usage. anyway thanks.

**Comment by mubaidr** [comment]
I think `graphql-engine` cli has more bugs. e.g. when passing `--enable-console false` to the `serve` command raises error: 

command:
```bash
graphql-engine serve --enable-console false
```
Error: 
```bash
api_1  | Invalid argument `false'
api_1  |
api_1  | Usage: graphql-engine [--host <HOST>] [-p|--port <PORT>] [-u|--user <USER>]
api_1  |                       [--password <PASSWORD>] [--database-url <DATABASE-URL>]
api_1  |                       [-d|--dbname <DBNAME>] [--retries NO OF RETRIES] COMMAND
```

**Comment by rikinsk** [comment]
@mubaidr I believe the `--enable-console` flag doesnt take any arguments. If the flag is present, it signifies `true` and if the falg isnt set it signifies `false`.

Our docs have an inconsistency which we will be fixing soon
