### ISSUE TITLE
console: missing suggested default functions for frequently used types

### ISSUE THREAD

**Issue by beerose** [hasura/graphql-engine#4704]
### Steps to reproduce
1. Go to either `New table` or to the `Modify` tab for the existing table.
0. Go to _Columns_.
0. Choose column type from `Frequently used types` list.
0. Go to `default_value` input. 

    **Actual result:** we don't show a list of suggested default functions. 
    <img width="300" alt="Screenshot 2020-05-07 at 20 13 22" src="https://user-images.githubusercontent.com/9019397/81329742-492b5d80-909f-11ea-94a8-9628386f6dc2.png">

    **Expected result:** we should show a list of suggested default functions as we do for other types that aren't from the `frequently used` list:
    <img width="300" alt="Screenshot 2020-05-07 at 20 13 37" src="https://user-images.githubusercontent.com/9019397/81329735-47fa3080-909f-11ea-9064-83445b011a62.png">

---

There is a list of [frequently used columns](https://github.com/hasura/graphql-engine/blob/master/console/src/components/Services/Data/utils.js#L606), and while looking for default functions we try to get them from the state by the `value` properties, that are not compliant with keys we have in the state:

<img width="200" alt="Screenshot 2020-05-07 at 20 28 53" src="https://user-images.githubusercontent.com/9019397/81331107-619c7780-90a1-11ea-9464-47e413934479.png">

**Comment by soorajshankar** [comment]
I see that `commonDataTypes` is used in multiple places. Shall I extend [commonDataTypes](https://github.com/hasura/graphql-engine/blob/6ffb29b9433b39622f6f3be66086ec19e1020943/console/src/components/Services/Data/utils.js#L606) with another property called `key` or something? 
like shown below

```jsx
export const commonDataTypes = [
  {
    name: 'Integer',
    value: 'integer',
    key: 'int4',
    description: 'signed four-byte integer',
    hasuraDatatype: 'integer',
  },
....
]
```

( another thought is to modify `value` prop but that would cause new bugs because that is used in other places as well)

**Comment by beerose** [comment]
`commonDataTypes` is imported in two places: `TableColumn` and `TableCreator` and in both places is passed to the `getDataOptions` function, which produces grouped by label list of types to display in the dropdown. Thus it should be okay to modify `value`.

**Comment by rohilrajkarki** [comment]
@beerose I saw the issue being completed in the current master branch. So is this issue has been implemented or not.?

**Comment by NoriSte** [comment]
> @beerose I saw the issue being completed in the current master branch. So is this issue has been implemented or not.?

I guess so, I close this PR, thanks for reporting 😊
