### ISSUE TITLE
Error modifying VIEW

### ISSUE THREAD

**Issue by mrspartak** [hasura/graphql-engine#4706]
So error happening, because there is no schema prefix on table name near FROM. Of course, I can write it by myself, but I guess it should be fixed.
![image](https://user-images.githubusercontent.com/993910/81347231-66265780-90c4-11ea-9172-b81e37f0dde9.png)

**Comment by tirumaraiselvan** [comment]
@mrspartak Could you paste the error that you are getting?

**Comment by mrspartak** [comment]
I'm sorry. Tried to reproduce this issue ones again and I'm not getting any errors. Everything works fine.
Closing this issue until I can reproduce it again.
