### ISSUE TITLE
[Bug][v1.2.1] Editing table permissions 

### ISSUE THREAD

**Issue by martavis** [hasura/graphql-engine#4708]
Since I updated to version 1.2.1 for the security fix, I am not able to edit the custom check for permissions on a table by typing. The goal is to add more than one check, for the user id and the organization's id. For reference, here is a screenshot:

![image](https://user-images.githubusercontent.com/47053705/81358350-17a89700-908b-11ea-873f-0847e4872c90.png)

In addition, this may be a feature request but is there a plan to allow adding multiple checks in the visual JSON representation?

**Comment by webdeb** [comment]
do you mean `_or` / `_and` ?

**Comment by martavis** [comment]
I don't believe so. Before, I was able to place my cursor at end of the JSON (just before the last curly brace), add a comma and type another object that looked like `{"org_id":{"_eq":"X-Hasura-Org-Id"}}`. Now I can't.

**Comment by webdeb** [comment]
```
{"creator_id":{"_eq":"X-Hasura-User-Id"}, "org_id":{"_eq":"X-Hasura-Org-Id"}}
```

Ok, I did't knew that this is a valid permission. IMHO it should be:

```
{_and: [{"creator_id":{"_eq":"X-Hasura-User-Id"}, {"org_id":{"_eq":"X-Hasura-Org-Id"}}]}
// or
, depending on your logic
{_or: [{"creator_id":{"_eq":"X-Hasura-User-Id"}, {"org_id":{"_eq":"X-Hasura-Org-Id"}}]}
```

But, I can confirm, that editing the json directly is not possible, since the `comma` gets sanitized out..  However, you can edit your rules with `_and` / `_or` through the UI widgets.

**Comment by martavis** [comment]
Oh, thank you for that! I'll give it a try. I don't recall see docs about it for permissions, but maybe I should have derived its use from the query docs.

**Comment by tirumaraiselvan** [comment]
Closing as dupe of https://github.com/hasura/graphql-engine/issues/4683
