### ISSUE TITLE
newly added columns are not given permissions without reload_metadata when "*" is set

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#4712]
Although the [permissions syntax](https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/permission.html#selectpermission) takes `*` as a value, the meaning of `*` expands to the list of columns available at the time of creating the permission. 

This means that adding new columns to such a table will not have the select permission on them, but the console shows that the permissions on the new columns are also set. 

Repro:

1. Create a table and give some select permission
2. Export metadata and edit the select permission to use `*` instead of list of columns
3. Import metadata
4. Add new columns

**Comment by tirumaraiselvan** [comment]
Although, if we `reload_metadata` then the new columns get included in the permission. This unpredictable behaviour also needs to be fixed.

**Comment by rikinsk** [comment]
console cannot figure out which columns currently have permissions from the metadata. The server should ideally respect '*' when a new column is added without need for metadata reload

**Comment by tirumaraiselvan** [comment]
Closing this as this is subsumed by https://github.com/hasura/graphql-engine/issues/2104
