### ISSUE TITLE
Dropping a column from table with "*" permission drops the entire permission

### ISSUE THREAD

**Issue by ElixirMike** [hasura/graphql-engine#4717]
I have a table that has defined permissions.
I use the /vq/query to run a SQL statement to drop/remove the column on a table.

Once done, I can run the "export_metadata" either via API or from console, and sure enough all the permissions except the Delete permission have been deleted/removed.

This is very problematic... is there a fix coming for this soon?

**Comment by tirumaraiselvan** [comment]
Hi @ElixirMike 

Could you describe the workflow again pls?

I tried:

1. `alter table <table> drop column <column>` using `run_sql` API with `check_metadata_consistency: false` 

2. Then I did a `reload_metadata` and all the permissions where intact.

**Comment by ElixirMike** [comment]
You're right. I didn't have the check_metadata_consistency=false, and I also had cascade: true. I guess the cascade wiped out the permissions. So, setting check_metadata_consistency=false seems to work and there doesn't seem to be a need to call reload_metadata either.
