### ISSUE TITLE
How do we handle changing auth credentials for subscriptions

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#472]
Problem is especially typical when JWT token needs to be refreshed, how do we refresh the subscriptions connection.

Things to find out:
1. Document the process of refreshing the auth header for subscriptions
2. For an existing subscription connection that has been established, if the auth credential changes, does it matter? Will the old susbcriptions continue?

Reference issues:
1. https://github.com/apollographql/subscriptions-transport-ws/issues/171#issuecomment-386824655 
2. Do we need to patch the apollo-subscriptions link? https://www.npmjs.com/package/patch-package

**Comment by wawhal** [comment]
The right way to solve this is to pass connectionParams as a function, from which you can fetch your headers and return them. It can also be an async function. 

Once that is done, you can close the connection whenever the a Websocket error occurs. (you'll need to store your Apollo WebsocketLink in some variable or state)

```js
wsLink.subscriptionClient.close(false, false);
```

On closing, the WebSocket connection will restart and the new connectionParams will be provided while restarting. ([Code Reference](https://github.com/wawhal/graphql-dynamic-headers-apollo-client/blob/master/src/App.js#L54))

If done in React, it should look like:

```js
const mkWsLink = () => {
    const wsClient = new SubscriptionClient(
      GRAPHQL_ENDPOINT,
      {
        // get headers asynchronously and set in connectionParams
        connectionParams: async () => {
          const headers = await this.getHeaders();
          return {
            headers
          };
        },
        // on subscription error, refresh subscription (close and reconnect)
        onError: refreshSubscription,
        // set reconnect to true for reconnecting whenever the connection is closed
        reconnect: true
      }
    );
    // store wsLink in state such that we can use and refresh connections whenever we want
    this.setState({
      ...this.state,
      wsLink: new WebSocketLink(wsClient),
    });
};

const refreshSubscription = () => {
    // refresh subscription whenever needed
    this.state.wsLink.subscriptionClient.close(false, false);
}
```
@coco98 does this make sense?

**Comment by revskill10** [comment]
How about using subscriptionClient on server-side to use with schema stitching ?

**Comment by rikinsk** [comment]
related: #994 #353

**Comment by rikinsk** [comment]
Tracked here #412

**Comment by dziamid** [comment]
What's the analog of ws link connectionParams function in http link? Can't seem to find the api for providing headers at request time..

**Comment by dziamid** [comment]
Solved with:
```
const httpLink = new HttpLink({
  uri: publicEnv('HASURA_ENDPOINT'),
  fetch: (input: RequestInfo, init?: RequestInit) => {
    return fetch(input, R.mergeDeepLeft({ headers: getHeaders() }, init));
  },
});
```
