### ISSUE TITLE
Error when the db.json file has more than 1927 items

### ISSUE THREAD

**Issue by famadori** [hasura/graphql-engine#4723]
When I run the file with 2000 json objects I get an error. I've done several tests and realized that the error only occurs when there are more than 1927 objects in the json. Any tips on how to solve?

Ex:
json2graphql http://localhost:8080 -s xxxxxxx -d C:\db.json -o

**Comment by tirumaraiselvan** [comment]
Could you pls raise an issue in `json2graphql` repo: https://github.com/hasura/json2graphql

**Comment by famadori** [comment]
Thanks
