### ISSUE TITLE
Add the ability to resolve an action webhook using an environment variable

### ISSUE THREAD

**Issue by knrz** [hasura/graphql-engine#4726]
First of all, let me say that I love Hasura. 

Actions fill a sweet spot that remote schemas do not — namely, the subscription support.

However, I do wish I could set up actions by using an ENV var, just like I can with Event Triggers.

This would let me deploy use IaaS tools to deploy containerized Hasura Engines behind a load balancer using an auto-scaling group.

As it stands, I'm not sure I can do that without having to manually configure the action URL for production separately from development.

**Comment by tirumaraiselvan** [comment]
This ability already exists. Although, it is bit different from Event Triggers. Pls see the note called URL templating [here](https://hasura.io/docs/1.0/graphql/manual/actions/create.html#step-2-create-the-action-handler) and also we are adding a tooltip to suggest this: https://github.com/hasura/graphql-engine/issues/4689

**Comment by knrz** [comment]
Thank you very much!
