### ISSUE TITLE
docs: add examples to API docs

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#4745]
We should add examples to the API docs: every API should have one or several examples.

**Comment by unfernandito** [comment]
Do you have any example to contribute?

Thanks You

**Comment by marionschleifer** [comment]
@unfernandito thank you so much for your interest in contributing.

So, most of your APIs have examples, like [here](https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/custom-functions.html). But some of then don't have examples yet, like [here](https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/permission.html#drop-insert-permission).

We should add examples to those APIs that don't have them yet. For those that have examples, we should check if we should add more in order to cover as many use cases as possible.

Let me know if you have any questions 🙂

**Comment by Ckbhatia** [comment]
Hi @marionschleifer,

I am interested to work on this issue. 

Can you elaborate a bit more on this issue?
There're examples available for both docs.

Maybe I'm not noticing well. So, Please help me to figure out this. 
So, I can work on this issue.

**Comment by marionschleifer** [comment]
@Ckbhatia of course. You can see that [here](https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/permission.html#create-insert-permission) there is an example for `create_insert_permission`. And you can see [here](https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/permission.html#drop-insert-permission) that there is no example for `drop_insert_permission`. We need to go through all these APIs and add examples where we don't have any yet. I hope this clarifies things 🙂 let me know if you have any more questions!

**Comment by Ckbhatia** [comment]
@marionschleifer I got it.
I am adding missing examples.

Questions:
1. Should I create another branch for these changes or master is okay?
2. Is there any resource where I can test the code or similar resource?

**Comment by marionschleifer** [comment]
@Ckbhatia 

1. You should create a fork of the `graphql-engine` repo and then you can make a PR from your forked repo to the `graphql-engine` repo. On your fork, it doesn't matter if you work on master or on a separate branch.

2. Please check out the [contributing guide for docs](https://github.com/hasura/graphql-engine/blob/master/docs/CONTRIBUTING.md). It explains how to set up docs for local development.

**Comment by Ckbhatia** [comment]
👍
