### ISSUE TITLE
Numbers in ENUMs

### ISSUE THREAD

**Issue by erichiller** [hasura/graphql-engine#4747]
When changing a table into an ENUM table, if there's a key that begins with a number, I receive an error when changing the table to an ENUM table:

_Setting table as enum failed
the table "enum.test_enum" cannot be used as an enum because the value "2Birds" is not a valid GraphQL enum value name_

```
[
    {
        "definition": {
            "schema": "enum",
            "name": "test_enum"
        },
        "reason": "the table \"enum.test_enum\" cannot be used as an enum because the value \"2Birds\" is not a valid GraphQL enum value name",
        "type": "table"
    }
]
```

So I checked the referenced [GraphQL spec on ENUMs](http://spec.graphql.org/June2018/#sec-Enum-Value) which says:

> Enum Value
> EnumValue
>      Name
>      but not true, false, or null
> Enum values are represented as unquoted names (ex. `MOBILE_WEB`). It is recommended that Enum values be “all caps”. Enum values are only used in contexts where the precise enumeration type is known. Therefore it’s not necessary to supply an enumeration type name in the literal.

Which doesn't mention anything about numbers not being supported.

Nor do I see any mentions of this on the [Hasura ENUM docs](https://hasura.io/docs/1.0/graphql/manual/schema/enums.html)

Is there a rule or specification I'm not seeing?

**Comment by leoalves** [comment]
@erichiller,
According to the GraphQL spec you linked the ENUM type `has to be a [Name](http://spec.graphql.org/June2018/#sec-Names) but not **true** **false** or **null**`.
The Name regex validator is `/[_A-Za-z][_0-9A-Za-z]*/`.  In that case it can't start with a number.
That's why I think it's failiing.

**Comment by erichiller** [comment]
@leoalves - thanks, looks like I missed that. I'll close this.
