### ISSUE TITLE
query object relation is null

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#476]
When object relationships are created manually, there is not is_null operator generated for them

**Comment by 0x777** [comment]
You can check if the relationship exists `{rel_name:{}}`.

**Comment by Youhan** [comment]
`where: { _not:{rel_name:{}}}`

**Comment by deathemperor** [comment]
How do I query this in combination with another condition: search profile with `name="You" or phone ="You"` and `friends (a relation) is not null`

**Comment by deathemperor** [comment]
I got the answer from Hasura Discord support:
```
query PublisherSearch($keyword: String!) {
  publisher(where: 
    {
      _or: 
      [
        {
          name: {_ilike: $keyword}
        },
      ],
      books: {id: {_is_null: false}}
    }) {
       id
      name
  }
}
```
