### ISSUE TITLE
Any way to get request IP address?

### ISSUE THREAD

**Issue by danielarbo** [hasura/graphql-engine#4770]
Hi! Anyone know if it is possible to get correct ip and user-agent directly from postgres or from action/event?

Thanks.

**Comment by tirumaraiselvan** [comment]
If "Forward client headers" is selected in your action metadata, then `X-Forward-Host` and `X-Forwarded-User-Agent` headers are added to the request to your webhook.

**Comment by tirumaraiselvan** [comment]
Changing the title for ip address.

**Comment by praveenweb** [comment]
Adding to @tirumaraiselvan's comment, you can use `X-Forwarded-For` to get the original IP.

`X-Forwarded-For: <client>, <proxy1>, <proxy2>`. [MDN Docs Reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For)

**Comment by vedovato** [comment]
@praveenweb what's the value needed for the `X-Forwarded-For` key on Hasura action headers?

**Comment by praveenweb** [comment]
@vedovato - We don't manually send in any value. When `Forward client headers` is enabled for the action, Hasura will automatically forward this value to the Action server and just parsing this `X-Forwarded-For` header in your action endpoint should be sufficient. 

In case you are using a proxy (like nginx) in between Hasura and your Action server, ensure that the headers are passed from the proxy to the Action server.

**Comment by leahciMic** [comment]
I only get the following headers:
```
[backend]   host: '172.17.0.1:3000',
[backend]   'accept-encoding': 'gzip',
[backend]   'content-length': '277',
[backend]   'x-b3-traceid': 'a26b52c772f0753866209c1db4906cd0',
[backend]   'x-b3-spanid': '7b932c3d8e29b32a',
[backend]   'x-b3-parentspanid': 'ffcfcd310043d747',
[backend]   'x-b3-sampled': '1',
[backend]   'content-type': 'application/json',
[backend]   'user-agent': 'hasura-graphql-engine/v2.23.0',
[backend]   'x-forwarded-user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36',
[backend]   'sec-fetch-site': 'same-site',
[backend]   'x-forwarded-host': 'localhost:8080',
[backend]   'sec-ch-ua-mobile': '?0',
[backend]   'sec-ch-ua': '"Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"',
[backend]   'sec-ch-ua-platform': '"Linux"',
[backend]   'x-hasura-role': 'anonymous',
[backend]   'x-request-id': 'ee229c49-5489-4e63-b640-38a9aafd200d',
[backend]   'sec-fetch-dest': 'empty',
[backend]   'x-forwarded-origin': 'http://localhost:5173',
[backend]   'sec-fetch-mode': 'cors',
```

I do not get `x-forwarded-for` and therefore cannot access the client's IP address.
