### ISSUE TITLE
cant access network PG DB via IP

### ISSUE THREAD

**Issue by JoeHogan** [hasura/graphql-engine#4774]
when i use

`postgres://user:pass@docker.for.win.localhost:5432/dbName`

everything works fine. I can also run:

`docker exec -it graph telnet [my localhost ip] 5432`
and i get:
"Connected to [my localhost ip]"

so i know my container can connect to my localhost PG instance via IP...

but when i try to use the localhost IP address in the db connection string:

`postgres://user:pass@[my localhost ip]:5432/dbName`

it doesnt work but also doesnt throw an error... just keeps restarting. Here is the log (which repeats over and over with restarts):

{"type":"startup","timestamp":"2020-05-15T02:52:27.309+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":"GET","use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":true,"enable_console":true,"auth_hook":"http://authhook:3004/api/hook","jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":true,"port":8080}}}
{"type":"startup","timestamp":"2020-05-15T02:52:27.309+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://user:...@[my localhost ip]:5432/dbName"}}}

**Comment by hgiasac** [comment]
Docker machine runs as a virtual OS. It creates another internal network with internal IP range. `docker.for.win.localhost` has different IP, not `127.0.0.1` or `localhost`. You should run docker info to know exact IP of docker machine are running

**Comment by JoeHogan** [comment]
I understand that, but my problem is that when I set my DB connection string to an IP that docker is able to hit via telnet, it doesn't work with Hasura... I don't get an error... it just keeps restarting...

**Comment by elcolie** [comment]
I also having this problem when I change from `postgres container` to `RDS`

**Comment by JoeHogan** [comment]
also, just for context, [my localhost ip] refers to my static address issued by the router, not 127.0.0.1. Point being, i want to configure hasura to always hit the instance of postgres running on my machine via my network address so other devs don't have to run a local instance of postgres. I can hit my static network address within the docker container, but using the address in the hasura db connection string doesnt work, and no error is thrown in the logs... just keeps restarting.

**Comment by JoeHogan** [comment]
OK - solved it. I reverted to Hasura 1.0.0 which then spit out the error that i want seeing with Hasura 1.2.0... the error was: no pg_hba.conf entry for host [my local ip]

just had to update the pg_hba.conf with my local ip and im good to go.

**Comment by elcolie** [comment]
I have to `create extensions pgcrypto` in RDS
