### ISSUE TITLE
Allow Action handler endpoint to be env var

### ISSUE THREAD

**Issue by rhlsthrm** [hasura/graphql-engine#4776]
I'd like to configure my Action handler endpoint from an env var for dev vs production. I can do this for Remote Schemas as well as Event Triggers, but not Actions.

**Comment by nason** [comment]
I was about to make this same feature request 🍔 

It would be super helpful to be able to define action endpoints and headers from env vars, like we can elsewhere.

**Comment by tirumaraiselvan** [comment]
This is already possible. See the note on Url templating here: https://hasura.io/docs/1.0/graphql/manual/actions/create.html#step-2-create-the-action-handler

An issue to add a tooltip to suggest this on the console is here: https://github.com/hasura/graphql-engine/issues/4689

**Comment by rhlsthrm** [comment]
Thank you @tirumaraiselvan! I somehow missed this in the docs! I'll close this issue.
