### ISSUE TITLE
Opt out in UI crashes with SQL error

### ISSUE THREAD

**Issue by haf** [hasura/graphql-engine#4785]
```
{
    "statement": "update hdb_catalog.hdb_version set console_state = '{\"disablePreReleaseUpdateNotifications\":true}' where hasura_uuid='null';",
    "prepared": false,
    "error": {
        "exec_status": "FatalError",
        "hint": null,
        "message": "invalid input syntax for type uuid: \"null\"",
        "status_code": "22P02",
        "description": null
    },
    "arguments": []
}
```

<img width="809" alt="image" src="https://user-images.githubusercontent.com/193115/82115202-a7240900-9761-11ea-8fab-812a419bb86c.png">

When you get the beta-notifications at the bottom of the console.

**Comment by rikinsk** [comment]
@haf This is unusual. As it turns out, `hasura_uuid` should never be `null` ideally. 

Could you share the response of the command: `select * from hdb_catalog.hdb_version;` in your DB. Ideally, this command should return 1 row. If it does not, we will need to investigate how this scenario has occurred.

**Comment by MarcelloTheArcane** [comment]
Replying from #5074 - Running that SQL query gives the following:

```
hasura_uuid	version	upgraded_on	cli_state	console_state
b71be1df-a2ee-44ff-b298-76f0a5fc4efa	34	2020-05-01 05:43:09.088171+00	{}	{"telemetryNotificationShown": true, "disablePreReleaseUpdateNotifications": true}
```

Or,

- hasura_uuid: 
 `b71be1df-a2ee-44ff-b298-76f0a5fc4efa`
- version: 
 `34`
- upgraded_on: 
 `2020-05-01 05:43:09.088171+00`
- cli_state: 
 `{}`
- console_state: 
 `{"telemetryNotificationShown": true, "disablePreReleaseUpdateNotifications": true}`

**Comment by isidentical** [comment]
I've just got a clean heroku instance (built from heroku elements), after setting up the admins secretkey, this was my first action and I got the same crash.

**Comment by haf** [comment]
Still a problem with 1.3.3
