### ISSUE TITLE
In role-based schemas, if graphql query fails, return null or errors in addition to the payload

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#479]
Let's say a graphql request is made:

```
query {
  profile { id name age }
}
```

and `age` is not in the schema (or the role-based schema). 

It is desirable in most situations to still receive the response for id & name along with an additional errors object adjacent to the data that is sent in the response. This is a behaviour desired only if these columns are used in the selection-set and not in the arguments. Currently the response is that graphql query validation failed entirely.

(via ben/cherre and matt/dsi)

@0x777 @dsandip this needs quick triaging. 
@0x777 comments?

Incidentally, @shahidhk, this is the behaviour with the github graphql api too right?

**Comment by revskill10** [comment]
@coco98 Why is this related to `role-base schemas` ?

**Comment by dsandip** [comment]
@coco98 What's the use-case for letting a user with limited scope run such a query in the first place?  This seems to be indicative of something being off with the permissions configured for this role.

**Comment by shahidhk** [comment]
I guess what the GitHub API does is that permissions are checked on the execution phase rather than in the validation phase like us.

**Comment by 0x777** [comment]
This cannot be done with our role based schemas.

**Comment by 0x777** [comment]
This can only be done if we abandon our current role based schemas (which I think is a bad idea) so I'm closing this.
