### ISSUE TITLE
As a read-only mode user, I am still able to do some CRUD operations in DATA module

### ISSUE THREAD

**Issue by soorajshankar** [hasura/graphql-engine#4791]
As a read-only mode user, I am still able to do CRUD operations in DATA.

**Current Behaviour**

1. Open Hasura console in read-only mode.
2. Go to the Data tab.
3. Some of the crud operations are enabled even in the read-only mode.
4. Relationships and Permissions tab works as expected.

**Expected Behaviour**

1. Add Table should not be enabled in both sidebar and landing page.
2. `Browse Rows` tab should not have a delete row button enabled.
3. `Modify Table` tab should not have 
      - a `save` button. 
      - inputs should be disabled. 
      - The editor should be on `readOnlyMode` 
4. `Modify Table` tab should not have 
      - a `save` button. 
      - inputs should be disabled. 
      - The editor should be on `readOnlyMode`

**Comment by kenptr** [comment]
How did you create read-only user for Hasura Console?

**Comment by jflambert** [comment]
What is this read-only mode you speak of?

According to #5349 there is no read-only mode yet.

Is this related to the two "readonly" images on dockerhub?

https://hub.docker.com/r/hasura/graphql-engine/tags?page=1&name=readonly

**Comment by tirumaraiselvan** [comment]
This original comment referred to an unsupported legacy feature. The docker image is also an experimental build and not supported. We can continue in #5349
