### ISSUE TITLE
Providing HASURA_GRAPHQL_ADMIN_SECRET makes role-based queries not work without admin secret

### ISSUE THREAD

**Issue by rhlsthrm** [hasura/graphql-engine#4793]
I'm having trouble getting the role-based auth to work. I have set `HASURA_GRAPHQL_ADMIN_SECRET` in my config and I added a "user" role who can query my `users` table with a custom check like:

```
{"id":{"_eq":"X-Hasura-User-Id"}}
```

However, when try a simple query with using the `X-Hasura-User-Id` header set in the console:

```graphql
query Users {
  users {
    created_at
    email
    id
    issuer
    last_login_at
  }
}
```

I get an error:

```
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "access-denied"
      },
      "message": "x-hasura-admin-secret/x-hasura-access-key required, but not found"
    }
  ]
}
```

I'm not sure I understand how this is supposed to work. if I add the admin secret I can make the query, but obviously I don't want to use the admin secret on my front end. How can I make the RBAC queries work without needing the admin header?

**Comment by joelmukuthu** [comment]
Hi @rhlsthrm, what was your solution to this issue? I've run into the same problem

**Comment by rhlsthrm** [comment]
@joelmukuthu, you have to enable authentication either through the webhook or JWT method to make this work.

**Comment by joelmukuthu** [comment]
I see, thanks a lot @rhlsthrm!
