### ISSUE TITLE
Feature: Progress indicator when applying migrations

### ISSUE THREAD

**Issue by nolandg** [hasura/graphql-engine#4795]
Couldn't find how to set this in the docs so I assume it's not implemented? When I apply a large series of migrations (like comissionsing a new instance of my app on a new database), it takes a while, like 5 minutes or more. It would be great to see progress, like which migration ID is currently being processed. Could we print that out to the console?

**Comment by scriptonist** [comment]
Addressed in https://github.com/hasura/graphql-engine/commit/b50df8a24b0b96b7b2016068cc55646672caee0f

**Comment by jflambert** [comment]
Can this be disabled? Looks atrocious in my docker logs with a large number of migrations. There's no new lines at the end of each output??

`====================================================================================================================================================>...........] 93.18%Applying migrations:  41 / 44 [===============================================================================================================================================================>...........] 93.18%Applying migrations:  41 / 44 [===============================================================================================================================================================>...........] 93.18%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [===================================================================================================================================================================>.......] 95.45%Applying migrations:  42 / 44 [========================================================================================`

**Comment by scriptonist** [comment]
@jflambert I concur, doesn't look right to me. Will address this ASAP

**Comment by jflambert** [comment]
And I do have `HASURA_GRAPHQL_LOG_LEVEL=warn` too

**Comment by jflambert** [comment]
Any update @scriptonist, or should I log a new issue?

**Comment by scriptonist** [comment]
@jflambert This is already being addressed and a PR fixing this will be merged in a day or two.

**Comment by jflambert** [comment]
@scriptonist I really appreciate all the work you guys do but I can't use Hasura 2.0.9 anymore because of this bug. It clutters our gitlab pipelines to the point where jobs fail because logs overflow limits.

**Comment by purush7** [comment]
@jflambert Can you use Hasura v2.0.10 which is the latest and has the fix for it
