### ISSUE TITLE
docs: guide on performance tuning

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#4805]
In the `deployment` section of the docs, we should add a page on performance tuning.

We can use [this](https://github.com/hgiasac/blog-builder/blob/master/pages/posts/2020-05-15-Tuning-Hasura-at-Scale.md) for content. Thank you @hgiasac 🙏

**Comment by Stefmore02** [comment]
If you want to pick up this task, reference the linked file in the first comment of this issue. 
You can use our [wiki](https://hasura.io/docs/wiki/) to determine how to add to our documentation.

**Comment by aniketh-varma** [comment]
Hi @rikinsk @Stefmore02, I would like to take this issue if it is still available.

**Comment by marionschleifer** [comment]
@aniketh-varma feel free to pick this up, so far, nobody has raised a PR on this.
