### ISSUE TITLE
Actions must return an object. How to return an array?

### ISSUE THREAD

**Issue by happyfloat** [hasura/graphql-engine#4806]
I did write an `hasura action` for a `query` and the action codegen return value did generate something like that:
```js
return res.json({
    ...data.content
})
```
This of course does not work, if my `content` is an array. 

Just returning an array is not possible, since hasura will throw an error, even though the result in the error body looks fine.

So currently the only way is to return a nested object like this:
```js
return res.json({
    result: data.content
})
```

And we need to adjust the action type definition accordingly, which will loose all of its descriptiveness, because object types is not possible here:
```
type ReturnValue {
  result : jsonb
}
```

Could this be improved in the future or is there a reason why an action can only return an object?

**Comment by wawhal** [comment]
@happyfloat action can return a list of object too. It is a bug in the codegen that we'll fix soon.You can return a list like you usually do:

```js
return res.json([
  {
    result: data1
  },
  {
    result: data2
  }
])
```

**Comment by wawhal** [comment]
Tracking it [here](https://github.com/hasura/codegen-assets/issues/28).

**Comment by happyfloat** [comment]
Thanks for the quick reply, but returning `res.json(data.content)`, did not work on version 1.2.1, thats my issue: `expecting object for action webhook response but got array`.

Wrapping it in `result` object was just a hacky workaround, the real type looks different, e.g.
```
type ReturnValue {
  id : uuid!
  title: String!
  ...
}
```

**Comment by wawhal** [comment]
@happyfloat I am unable to reproduce that issue. Say if I have the following action defintion:

```graphql
type Query {
  users(city: String): [User]
}

type User {
  username: String!
  city: String
  age: Int
}
```

For the above definition, if you send a list of objects, it is a valid response. For example check this:

```js
return res.json([
  {
    username: "ireneadler",
    city: "London",
    age: 45
  },
  {
    username: "sherlockholmes",
    city: "London",
    age: 60
  },
])
```
If possible, can you give some more information about your action definition and the response that you are returning?

**Comment by happyfloat** [comment]
Omg! Thank you so much,I just missed the array definition here:
```
type Query {
  users(city: String): [User]
}
```

Sorry for the inconvenience.
