### ISSUE TITLE
[BUG] Order_by with multiple arguments

### ISSUE THREAD

**Issue by perrosnk** [hasura/graphql-engine#4808]
The explorer doesn't produce correct results when selecting multiple arguments on the order_by.
The [documents](https://hasura.io/docs/1.0/graphql/manual/queries/sorting.html#sorting-by-multiple-fields) mention that order_by should be an array, whereas the explorer always produces an object

Edit: could be linked with [this](https://github.com/hasura/graphql-engine/issues/4488)

**Comment by tirumaraiselvan** [comment]
Explorer (different repo) has a bug where it doesn't handle list inputs properly: https://github.com/OneGraph/graphiql-explorer/issues/32

We are also tracking it here for any improvements that can be made: https://github.com/hasura/graphql-engine/issues/3322

**Comment by tirumaraiselvan** [comment]
Closing this in favour of #3322
