### ISSUE TITLE
[BUG] Nested object creation does not define nested object's foreign key

### ISSUE THREAD

**Issue by rhlsthrm** [hasura/graphql-engine#4812]
I have an object relationship defined by foreign keys and relationships, which I am inserting at the same time as the parent object using the nested object insert [syntax](https://hasura.io/docs/1.0/graphql/manual/mutations/insert.html#one-to-one-one-to-many-relationships). When I insert the object, the foreign key on the nested object is NULL.

**Comment by rikinsk** [comment]
@rhlsthrm I was not able to reproduce this. Can you share the schema of your tables and the query you are attempting.

**Comment by rhlsthrm** [comment]
Here's a simple example I've reproduced:

Parent table created with this schema:

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/11512787/82343286-f16fe900-99f2-11ea-9864-56710a98daba.png">

Child table created with this schema:

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/11512787/82343386-0fd5e480-99f3-11ea-92ea-b8fadfff7878.png">

I'm running this query:

```graphql
mutation MyMutation($identifier: String = "parent1") {
  insert_parent_one(
    object: {
      child: { data: { first_name: "Foo", last_name: "Bar" } }
      first_name: "Bob"
      identifier: $identifier
      last_name: "Hope"
    }
  ) {
    identifier
  }
}
```

The `child` that is created is showing the `parent_id` and object relationship as NULL:

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/11512787/82343727-7ce97a00-99f3-11ea-95b2-5b4286ce6a4a.png">

I need to be able to query children based on parent relationships, so I need this side of the relationship to be set. The parent -> child side is working fine.

**Comment by tirumaraiselvan** [comment]
It seems like you are creating object relationship both ways like a one-to-one relationship? In which case, there is a limitation that you can only insert nested objects from one direction: https://hasura.io/docs/1.0/graphql/manual/schema/relationships/database-modelling/one-to-one.html#current-limitations-with-nested-mutations

**Comment by rhlsthrm** [comment]
Ah, I see. That's too bad, I would have liked to have both sides of the relationship set, this means I need to use one more query to set that up.
