### ISSUE TITLE
console: wrap voyager in error boundary 

### ISSUE THREAD

**Issue by beerose** [hasura/graphql-engine#4818]
It will be a partial solution to https://github.com/hasura/graphql-engine/issues/3023. The idea is to wrap the voyager component in error boundary so that any voyager's errors won't crash the whole console, and users still will be able to use the application without page refresh. 

In the error message, we should display information that the error comes from Voyager. 

Voyager component: https://github.com/hasura/graphql-engine/blob/master/console/src/components/Services/VoyagerView/VoyagerView.js

**Comment by kolharsam** [comment]
@beerose I think I'd like to work on this. Is anyone else working on it?

I also had a couple of questions.

Also, what is the fallback for the ErrorBoundary? 
Are there other places where this ErrorBoundary can be used?

**Comment by beerose** [comment]
@kolharsam I'll assign you to this issue, you can work on it 😉

We have error boundary defined for the whole app here: https://github.com/hasura/graphql-engine/blob/master/console/src/components/Error/ErrorBoundary.js
And the fallback is either `PageNotFound` or `RuntimeError` component. The idea here is to wrap the Voyager component into an additional error boundary so that the top menu is still visible. 

> Also, what is the fallback for the ErrorBoundary?

Fallback will be a similar component to the [`PageNotFound`](https://github.com/hasura/graphql-engine/blob/master/console/src/components/Error/PageNotFound.js) or [`RuntimeError`](https://github.com/hasura/graphql-engine/blob/master/console/src/components/Error/RuntimeError.js) components (styling wise), but with the information that Voyager error occurred.

> Are there other places where this ErrorBoundary can be used?

No, we want to cover this specific case and wrap only the Voyager component. The whole application is already wrapped in the error boundary.

**Comment by kolharsam** [comment]
@beerose I guess the error boundary is ready, I've tested it & seems to be working as expected. 
For the styling, however, I've followed the style present on the `RuntimeError` component

<img width="1439" alt="Screenshot 2020-05-27 at 9 47 49 PM" src="https://user-images.githubusercontent.com/6604943/83047347-df7eed80-a065-11ea-8908-b16287a0d06f.png">

**Comment by NoriSte** [comment]
The Voyager is not linked anymore in the Console, I close this PR.
