### ISSUE TITLE
How do I make query/where for fetching groups that I don't belong to

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#482]
Schema:
```
group: id, name (group.users -> user_group)
user_group: user_id, group_id
user: id, name (user.groups -> user_group)
```

Let's say I'm user 8, and I want to see all the groups that I'm not a part of.

```
query groups(where: {users: {user_id: {_neq: 8}}}) {
  id
  name
}
```
This query ends up returning all the groups,  the ones I don't belong to as expected and the ones I belong to as well, which is unexpected.

I think the reason this doesn't work is because across an array, the where clause defaults to the `any` operator. So if a group I belong to contains any other user then I still get that group.

@0x777 Workarounds?

(via @cory/connectworxs discord)

**Comment by coco98** [comment]
I can confirm that this works:

```
query {
  group (where: {_not: {users: {user_id: {_eq: 1}}}}) {
    id
    name
    users {
      user_id
    }
  }
}```

This reads as: Fetch all groups where there is not (any user with user_id 1) which works.

**Comment by corysimmons** [comment]
🙇

**Comment by shahidhk** [comment]
@0x777 ^
