### ISSUE TITLE
Improve documentation of how operators work across array relationships

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#483]
Document common patterns around:
any, not exists

Refer #482 for an example of how I was confused.

**Comment by dsandip** [comment]
@0x777's comments on Discord: 

```
currently, we don't have operators on array relationships which let you do filter based on cardinality. However, you can still do what you intend to do with something like this:
```
`{ _not: {barByFooId: { id: {_gt: 0}}}}`

```
It is a bit convoluted but we'll add better support for this as soon as possible.
```

**Comment by coco98** [comment]
@rikinsk If we're putting together a section on how operators work across relationships, can you list an outline of topics/use-cases we should cover for array relationships and object relationships?
