### ISSUE TITLE
Support for application/graphql content-type payloads to endpoint

### ISSUE THREAD

**Issue by davingreen** [hasura/graphql-engine#4830]
I looked around, but don't see any documentation or other issues mentioning this, so this may be ignorance on my part.

Is it possible to send an application/graphql payload to the graphql engine? When I try sending a graphql query in the raw body of the request with the content-type set, I get an error. 

```
POST https://.../v1/graphql
Content-Type: application/graphql

{ 
  test {
    id
  }
}
```
```
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "invalid-json"
      },
      "message": "Error in $: Failed reading: satisfy"
    }
  ]
}
```

**Comment by ecthiender** [comment]
Hasura only supports `application/json` as per https://graphql.org/learn/serving-over-http/#post-request

`application/graphql` has a severe limitation that you cannot use variables.

See also: https://github.com/apollographql/apollo-server/issues/48

**Comment by davingreen** [comment]
Thank you! -- ignorance reduced
