### ISSUE TITLE
docs: update docs around auth0 jwk_url support

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#4847]
Auth0 has fixed a [bug](https://community.auth0.com/t/certificate-thumbprint-is-longer-than-20-bytes/7794/11) which prevented Hasura from using their rotating keys.

The docs around configuring `HASURA_GRAPHQL_JWT_SECRET` for Auth0 needs to be updated. 

Places where this content needs to be updated:
- https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#example-jwk-url
- https://hasura.io/docs/1.0/graphql/manual/guides/integrations/auth0-jwt.html#configure-hasura-to-use-auth0-keys
- https://hasura.io/jwt-config/

**Comment by marionschleifer** [comment]
We should also update the docs to use always use `accessToken` since this was recommended by Auth0.

**Comment by sanderhahn** [comment]
In the https://hasura.io/docs/1.0/graphql/manual/guides/integrations/auth0-jwt.html user sync snippet the `configuration` object can be used to store the url and admin secret outside of the sourcecode. https://auth0.com/docs/rules/guides/configuration

**Comment by rumsrami** [comment]
Hi everyone, I would like to use Hasura with Auth0. Auth0 rotates secrets and it would be alot of manual work to keep updating env variables with the new secret everytime, specially in k8s. Is there a link on where to configure hasura to get the key from auth0 link automatically?

**Comment by seanparkross** [comment]
We're closing this issue. The docs for auth have recently been updated. We'd really like to hear your thoughts on those new docs in our [Discord](https://discord.com/invite/hasura). If you feel that this issue has been closed in error please comment again and we will reopen.
