### ISSUE TITLE
Show line number of the error in custom types editor

### ISSUE THREAD

**Issue by karthikvt26** [hasura/graphql-engine#4849]
Currently the error message shows the syntax error. Line number would really be useful if the custom types are a lot

![Screen Capture_select-area_20200522195437](https://user-images.githubusercontent.com/25095884/82678747-c0e4b500-9c67-11ea-966a-2920fa864352.png)

**Comment by tanvibhakta** [comment]
Hello folks! I'd love to pick this one up. Have been talking to @shahidhk and will hopefully get a PR in soon!
