### ISSUE TITLE
docs: use <code> tag in documentation for better translations

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [hasura/graphql-engine#4851]
If I use the Google translator on the page, then the code examples are also translated:

![image](https://user-images.githubusercontent.com/60403187/82686206-25027b80-9c5e-11ea-9972-0e4b73c0c92b.png)

![image](https://user-images.githubusercontent.com/60403187/82686227-2d5ab680-9c5e-11ea-9943-6413647bd4a2.png)

![image](https://user-images.githubusercontent.com/60403187/82686278-42cfe080-9c5e-11ea-8c5e-8b469ded1d13.png)

Solution:
---
You need to use the `<code>` tag instead of the `<pre>` tag, then the translators will not translate the contents of this tag

**Comment by robertjdominguez** [comment]
Our migration to Docusaurus now includes code blocks wrapped with the `<code>` tag 👍
