### ISSUE TITLE
The documentation for the migrations upgrade command is wrong

### ISSUE THREAD

**Issue by nirvdrum** [hasura/graphql-engine#4853]
The documentation for the migration upgrade command says "In your project directory, run", but if you run the command in the project directory, the script is unable to open the migration files. I found the command really needs to be run where you store your migrations, which I believe is conventionally a directory named _migrations_ within the project.

**Comment by scriptonist** [comment]
Hey, @nirvdrum thanks for bringing this to notice. I wanted to make sure we are on the same page and tried reproducing the issue, but for some reason didn't succeed.

![hasura-upgrade](https://user-images.githubusercontent.com/8335904/82779370-a120dd00-9e71-11ea-925c-bf1b76bac770.gif)

Can you compare it and let me know if matches your setup? Also, let me know If I didn't understand the issue correctly.

**Comment by nirvdrum** [comment]
Thanks for investigating. You've understood the issue correctly and it's interesting that your results don't match my own. Here's what I'm seeing:

```
my_project/hasura
❯ hasura version
INFO hasura cli                                    version=v1.2.1
INFO hasura graphql engine                         endpoint="http://localhost:8080" version=v1.2.1

my_project/hasura
❯ ls
config.yaml  docker-compose.yaml  migrations/

my_project/hasura
❯ hasura scripts update-project-v2 --admin-secret myadminsecretkey
FATA[0007] error in reading up.sql: open 1578795661351_add_todo_completed_at/up.sql: no such file or directory 

my_project/hasura 
❯ cd migrations/

my_project/hasura/migrations
❯ ls
1576443956239_init/  1578543599221_add_todo_ranking/  1578795661351_add_todo_completed_at/  1578806597145_add_profile_rank/  1586062013338_add_note_to_todo/

my_project/hasura/migrations
❯ hasura scripts update-project-v2 --admin-secret myadminsecretkey
FATA[0012] error in copying migrations to migrations_backup: destination already exists 

my_project/hasura/migrations
❯ ls ../
config.yaml  docker-compose.yaml  metadata/  migrations/  migrations_backup/

my_project/hasura/migrations
❯ rm -rf ../migrations_backup/

my_project/hasura/migrations
❯ hasura scripts update-project-v2 --admin-secret myadminsecretkey
INFO Updated config to version 2                  
```

For good measure, I left in the code showing I had to clean up after the failed upgrade attempt (the "migrations_backup" directory is created) before I could run the upgrade in the proper directory.

**Comment by scriptonist** [comment]
@nirvdrum Thanks! totally makes sense. Actually it was a bug and a fix is on its way.
