### ISSUE TITLE
add a logout equivalent to console to remove access key stored locally

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#486]

**Comment by dsandip** [comment]
@shahidhk : can this be an option on the /console/metadata page to purge the locally stored access key? Logout doesn't sound right. Also, if this makes sense, can you also provide some description/help text that will accompany this button.

**Comment by dsandip** [comment]
@rikinsk Inputs needed here too

**Comment by rikinsk** [comment]
@dsandip Agree with your suggestion. Though technically it's not really metadata related but it seems like the best candidate.

**Comment by rikinsk** [comment]
Eventually the Settings icon will need to be dropdown with other such functionalities

**Comment by karthikvt26** [comment]
@dsandip Can you provide a screenshot of where we could place this button?

**Comment by dsandip** [comment]
@karthikvt26 Something like this the following text:

Text: `The console caches the access key (HASURA_GRAPHQL_ACCESS_KEY) in the browser. You can clear this cache to force a prompt for the access key when the console is accessed next using this browser.`

Button label: `Clear access key cache`

![access key purge](https://user-images.githubusercontent.com/24300818/46523092-4d2f4200-c8a2-11e8-98f6-5881c21007be.png)

**Comment by shahidhk** [comment]
Reset is a better word than reload for the button.

Regards,

Shahidh

**Comment by dsandip** [comment]
@shahidhk The text for the button is "Clear access key cache"

**Comment by coco98** [comment]
"Clear access key (logout)"
