### ISSUE TITLE
Hasura Action Allow Setting HTTP Method To Use For Request

### ISSUE THREAD

**Issue by zolamk** [hasura/graphql-engine#4862]
When setting handler for hasura actions i think it would be great if we could also select the http method to use for the request

**Comment by tirumaraiselvan** [comment]
For query actions, GET should probably be an option but that will change a lot of webhook spec.

**Comment by datakurre** [comment]
Run into this when I was trying out if I could replace remote schema (with self-maintained remote GraphQL implementation) with actions (calling upstream maintained REST API).

If I've understood actions properly, HTTP method setting would make it possible to map simple REST APIs as actions. In addition to GET for queries, also PUT and DELETE for mutations would be usable.

**Comment by tirumaraiselvan** [comment]
Hey folks, this is now possible through "Action Transforms": https://hasura.io/docs/latest/graphql/core/actions/transforms.html#method

This has been released in `2.1.0-beta.2`
