### ISSUE TITLE
Use root JWT claim (sub, aud, etc) with Hasura authorisation

### ISSUE THREAD

**Issue by james-ct** [hasura/graphql-engine#4869]
Hi there,

I was wondering if there's a reason why there isn't support (afaict) for using root claims in JWTs?

My use case in AWS Cognito, and for my relatively simple case, I feel like I should be able to get around needing a pre-token lambda by adding a static custom attribute per user for `X-Hasura-Default-Role` and `X-Hasura-Allowed-Roles`, and using the `sub` key instead of `X-Hasura-User-Id` in the permission definitions.

Hasura is a great product, and I'm honestly a little surprised this ability isn't already here, because there are so many configurable features in here already, good work.

**Comment by tirumaraiselvan** [comment]
@james-ct This is in the works: https://github.com/hasura/graphql-engine/pull/3575

The spec of configuration is here: https://github.com/hasura/graphql-engine/issues/3485#issuecomment-610943389

**Comment by james-ct** [comment]
@tirumaraiselvan, thanks, that looks perfect! A little embarrassed I didn't find this in my search, but it looks really good. Hopefully it will be out soon :)
