### ISSUE TITLE
docs: add click-to-copy button for examples

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#4874]
It would be nice to have a click-to-copy button for code examples, especially for the SQL code blocks.

**Comment by Ckbhatia** [comment]
It might need a script to implement this feature

**Comment by kzuri** [comment]
Can I give this issue a try?

**Comment by Ckbhatia** [comment]
@kzuri Sure

**Comment by PedroBern** [comment]
There is a package for this: [Sphinx-copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/)

**Comment by ashishra0** [comment]
I'll give this one a shot :)

**Comment by ashishra0** [comment]
I'll give this one a shot :)

**Comment by aloks98** [comment]
@marionschleifer Hey, I have been working on this, and I see in the whole docs we have $ before inputs and outputs too. If we do that the user might get confused what to copy and what not to copy. Can I remove $ from the output blocks and add OUTPUT above the code block? That way I can match the inputs with regex and provide copy buttons only to the code blocks which are input.
Example:
`
$ docker ps  #This is input
#The line below is output
CONTAINER ID IMAGE                 ... CREATED STATUS PORTS          ...
097f58433a2b hasura/graphql-engine ... 1m ago  Up 1m  8080->8080/tcp ...
b0b1aac0508d postgres              ... 1m ago  Up 1m  5432/tcp       ...
`

**Comment by sleep-404** [comment]
Hi all, 
may i know if there is a way to serve the sphinx documentation over `https` while testing locally ?

**Comment by sleep-404** [comment]
![Hasura](https://user-images.githubusercontent.com/31350263/95541666-85c60100-0a11-11eb-80c4-7a400e578efb.gif)
Guess that gets the required job done, will be creating a PR soon for the same

**Comment by maha885** [comment]
Is this issue is available to give a try or already resolved?

**Comment by BrunoGabrielGodoi** [comment]
I do think this has been solved already. @marionschleifer 
![image](https://user-images.githubusercontent.com/20050537/232932904-7b605211-95a1-49bf-ae8d-2732d550f82f.png)
