### ISSUE TITLE
migrate apply failed: failed parsing json: json: cannot unmarshal array into Go struct field HasuraError.internal of type hasuradb.SQLInternalError;

### ISSUE THREAD

**Issue by franciscolourenco** [hasura/graphql-engine#4879]
This issue is not about the failed migration, but about the error parsing json when the migration fails. 

```
FATA[0006] apply failed: failed parsing json: json: cannot unmarshal array into Go struct field HasuraError.internal of type hasuradb.SQLInternalError;
response from API: {"internal":[{"definition":{"definition":{"function":{"schema":"public","name":"plan"},"table_argument":null},"name":"plan","comment":"","table":{"schema":"public","name":"users"}},"reason":"in table \"users\": in computed field \"plan\": no such function exists in postgres : \"plan\"","type":"computed_field"}],"path":"$.args[36].args","error":"in table \"users\": in computed field \"plan\": no such function exists in postgres : \"plan\"","code":"constraint-violation"}
```

**Comment by scriptonist** [comment]
Hey @franciscolourenco, can you provide a bit more info on how to reproduce this ?

**Comment by franciscolourenco** [comment]
@scriptonist I assume that if you try to apply a migration which fails due to a computed field being based on a pgsql function which has not been defined yet, you might be able to reproduce.

1. Create and track table
2. Create function, **without** creating migration
3. Create computed field based on function
4. Apply migrations to a new hasura
