### ISSUE TITLE
PostGIS nearby places sort by distance

### ISSUE THREAD

**Issue by meseven** [hasura/graphql-engine#4880]
Hello there,
I am using Hasura with PostGIS.
I am following the article. However, I could not sort the nearby places by distance. Can you help?

https://hasura.io/blog/graphql-and-geo-location-on-postgres-using-hasura-562e7bd47a2f/

**Comment by tirumaraiselvan** [comment]
Hi @meseven  Could you try asking this in [our Discord](https://discordapp.com/invite/hasura) or Stackoverflow as there might be more POSTGIS users there?

**Comment by crewnew-git** [comment]
I sorted out if anybody else needs help. Calculating distance and sorting nearest first, too: https://crnw.uk/hasuradistance
