### ISSUE TITLE
Initialising migrations does not mark the generated migration as present in the database

### ISSUE THREAD

**Issue by RapidOwl** [hasura/graphql-engine#4887]
I followed the quick start docs and set up Hasura on Heroku. I added my tables via the console, but now I'm in a position where I want to set up local Hasura, staging, prod etc.

I Initialised migrations and exported migrations and metadata from my Heroku instance. I then applied the generated migration and metadata to Hasura running in Docker.

My local instance then worked identically to my Heroku instance.

I then used `hasura console` to open the console and created some indexes in my Docker instance. A new migration was created successfully, but when I tried to apply the new migration to the original Heroku instance it failed because it tried to re-apply the initial migration recreate tables that already existed.

This seems to be one of two issues:
1. Exporting an initial migration from a database created using the console does not mark that migration as run in Hasura.
2. The generated migrations are not idempotent e.g. Hasura uses `CREATE TABLE` instead of `CREATE TABLE IF NOT EXISTS`.

Is there a way to manually mark a migration as applied for a given Hasura instance?

Should I manually edit my initial migration so that it is idempotent?

Or should I just delete my Heroku instance, create a new one and apply the migrations to an empty database?

**Comment by scriptonist** [comment]
@RapidOwl you can mark the init migrations as applied using the following command

`hasura migrate apply --version "<init-version>" --skip-execution`

**Comment by RapidOwl** [comment]
@scriptonist Ah okay thanks!
