### ISSUE TITLE
Geometric Types Question (PostGIS)

### ISSUE THREAD

**Issue by costas90** [hasura/graphql-engine#4891]
When selecting the `box` type for a column (or any other geometric type), is this useable with PostGIS?

Are these considered to be of `geometry` type?

From the docs and reading online, it seems that you can choose between `geometry` or `geography` for such geo columns but these options are not available in the column types dropdown in the console.
https://hasura.io/docs/1.0/graphql/manual/api-reference/postgresql-types.html#geography

Should I create my tables from the data tab instead and select `geography` manually?

**My usecase below.** 

My app is a marketplace. I need to connect User A with User B.
I plan to get the viewport coordinates of city of each user from the `Google Maps Places Autocomplete API` and then I need to check if User A is in the city of user B's city.

![image](https://user-images.githubusercontent.com/18027867/82928571-0a484380-9f8b-11ea-90cc-afeb684c42d0.png)

Is this a good approach? 

The reason I dont plan to use `POINTS`. 

When using `POINTS` I dont have access to the bounds of the city. If a user is located near the bounds of the city and the point I get from Google is in the center of the city, then using `POINTS` is innacurate, correct?

I am new with geolocation so I would appreciate some advice!

Thanks for making Hasura, I re-launched V1 of our app last week!

**Comment by tirumaraiselvan** [comment]
Hi @costas90 Could you try asking this in [our Discord](https://discordapp.com/invite/hasura) or Stackoverflow as there might be more POSTGIS users there?

**Comment by costas90** [comment]
I ended up creating Geography with Point type for each location and works fine.
