### ISSUE TITLE
'12h', '1M'... are not valid GraphQL enum value names

### ISSUE THREAD

**Issue by waterdrop01** [hasura/graphql-engine#4896]
Hi, I tried to set a table as enum table, but I receive the following error:
```
Setting table as enum failed
the table "table.interval_enum" cannot be used as an enum because the values 12h, 1M, 1d, 1h, 1m, 1w, 2h, 30m, 3d, 3m, 4h, 5m, 6h, and "8h" are not valid GraphQL enum value names
```
and here is my table SQL description:
```sql
CREATE TABLE "table"."interval_enum" ("value" text PRIMARY KEY, "description" text);
```
I looked at http://spec.graphql.org/June2018/#EnumValue, but doesn't seem like "12h" as a text isn't a valid enum value....

Any idea?
Thanks for your help!

**Comment by leoalves** [comment]
As per GraphQL spec ENUM types have to be `Name but not true or false or null`. And the Name type can't start with a number.
http://spec.graphql.org/June2018/#Name

**Comment by ceefour** [comment]
@waterdrop01 In my case, I realized that the column shouldn't be enum at all.

But if you still have enum, prefix it with something, e.g. "P1h".
