### ISSUE TITLE
Cannot apply metadata on the database: Post http://localhost:9691/v1/query: EOF

### ISSUE THREAD

**Issue by jhaensli** [hasura/graphql-engine#4897]
We are using v1.0.0-rc.1.cli-migrations docker image deployed in Kubernetes.
We mount ./metadata.json to /hasura-migrations/
(config-v1)

To enjoy the latest improvements and fixes we would like to upgrade to v1.2.1.cli-migrations.
Thus we changed the image tag to v1.2.1.cli-migrations as defined in [Updating Hasura GraphQL engine running with Docker](https://hasura.io/docs/1.0/graphql/manual/deployment/docker/updating.html#docker-update). 
When pod/container starts we see this in the logs:
```
fatal: failed to apply metadata: cannot apply metadata on the database: Post http://localhost:9691/v1/query: EOF
```
Hasura  v1.2.1.cli-migrations stays unhealthy and gets restarted.

- Using the old still running v1.0.0-rc1 I tried to
```
drop schema hdb_catalog cascade;
drop schema hdb_views cascade;
```
without success. 

- I did "Reset metadata" in Hasura console, also no luck.

Next time Kubernetes starts v1.2.1.cli-migrations, it fails with the above mentioned fatal error message again.

How should we upgrade v1.0.0-rc.1.cli-migrations to v1.2.1.cli-migrations?

Thanks

**Comment by AlineFrancois** [comment]
Hello, was there ever any update on this?

**Comment by devthejo** [comment]
I have same error migrating to hasura v2.0.0.alpha-10

**Comment by devthejo** [comment]
and same with hasura v2.0.0.alpha-11

**Comment by devthejo** [comment]
same with v2.0.7.cli-migrations-v3

**Comment by scriptonist** [comment]
Hi, can you see if this comment helps? https://github.com/hasura/graphql-engine/issues/7463#issuecomment-906983240
