### ISSUE TITLE
update readme and add missing lanugages for serverless-triggers on zeit

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#490]
NodeJS is already added. Need more languages and an updated readme which clearly lists out all the steps required to get it running.

https://github.com/hasura/graphql-engine/tree/master/community/boilerplates/serverless-triggers/zeit-serverless-docker

**Comment by swatisingh45** [comment]
Hey, @shahidhk I'd like to take up the issue. Please assign this to me.

**Comment by swatisingh45** [comment]
Yes, we can do that too. If you could just provide a hint about the timeline or list out all the different sections to be added, that would be better. @coco98 @shahidhk

**Comment by shahidhk** [comment]
I am marking this issue for Zeit. Other platform are listed as

https://github.com/hasura/graphql-engine/issues/579
https://github.com/hasura/graphql-engine/issues/580
https://github.com/hasura/graphql-engine/issues/581

@swatisingh45 Feel free to comment on any of these and take it up. You can work on any language the platform supports.

**Comment by shahidhk** [comment]
@swatisingh45 Feel free to propose a timeline you're comfortable with.

**Comment by shahidhk** [comment]
@swatisingh45 Can you take up https://github.com/hasura/graphql-engine/issues/580? I am going to be working on Zeit as it is important for work in the next two days. Thanks.
