### ISSUE TITLE
Computed Field with `session_argument` requires args to be defined

### ISSUE THREAD

**Issue by lukepolo** [hasura/graphql-engine#4901]
I am unable to setup computed field with `session_argument` as it requires me to pass it in via arguments.

Here is a pretty basic implementation of just trying to get it to work properly.

### Query
```
query getDeviceHasuraSession {
  devices {
    hasura_session
  }
}
```

**Result**
```
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.devices.selectionSet.hasura_session.args",
        "code": "validation-failed"
      },
      "message": "the required argument \"args\" is missing"
    }
  ]
}
```

### Passing Hasura Session In

```
query getDeviceHasuraSession {
  devices {
    hasura_session(args: {hasura_session: "test"})
  }
}
```

**Result**
```
{
  "data": {
    "devices": [
      {
        "hasura_session": "\"test\""
      },
      {
        "hasura_session": "\"test\""
      },
   ]
}
```

## Setup 
For a simple test of getting a computed field to make sure the `hasura_session` would be returned I created a postgresql function and a computed field request. 

### Postgresql Function
```
CREATE OR REPLACE FUNCTION qx.get_device_computed_field (device qx. "Device", hasura_session json)
	RETURNS text STABLE
	LANGUAGE plpgsql
	AS $$
BEGIN
	RETURN hasura_session
END
$$;
```

### add_computed_field Request 

```
POST /v1/query HTTP/1.1
Content-Type: application/json
x-hasura-admin-secret: qxhasurasecret
Host: localhost:4400
Connection: close
User-Agent: Paw/3.1.10 (Macintosh; OS X/10.15.4) GCDHTTPRequest
Content-Length: 241

{"type":"add_computed_field","args":{"table":{"name":"Device","schema":"qx"},"name":"hasrua_session","definition":{"function":{"name":"get_device_computed_field","schema":"qx"},"table_argument":"device","session_argument":"hasura_session"}}}
```

### Metadata Export 

```
 {
          "name": "hasura_session",
          "definition": {
            "function": {
              "schema": "qx",
              "name": "get_device_computed_field"
            },
            "table_argument": "device"
          }
        }
```

It seems the `session_argument` is missing from metadata

### Related Issues 
https://github.com/hasura/graphql-engine/issues/4537
https://github.com/hasura/graphql-engine/issues/4499

**Comment by tirumaraiselvan** [comment]
Session arguments in computed fields is merged to master but not yet released unfortunately: https://github.com/hasura/graphql-engine/commit/ee7c7b16729c0eef01c2957e5532b4bfd3ee5e4f

The docs are little bit ahead as they were part of the same commit. Sorry for the confusion.

It will be out it in `v1.3`, beta coming up in few days.

**Comment by lukepolo** [comment]
Works in beta 1.3-2

**Comment by harryhcs** [comment]
I just upgraded to beta 1.3-2 and still getting the same results.

Dockerfile: FROM hasura/graphql-engine:v1.3.0-beta.2
Current server version: v1.3.0-beta.2

```
query {
    currentuser(args: {}) {
      id
      email
      userType
      employeeNumber
      fullname
    }
  }
```
`
message: "Non default arguments cannot be omitted"`
