### ISSUE TITLE
All placeholders should be surrounded by <> in the docs

### ISSUE THREAD

**Issue by GavinRay97** [hasura/graphql-engine#4906]
https://hasura.io/docs/1.0/graphql/manual/deployment/heroku/index.html#step-3-git-push-to-deploy

For example;
In the bash command example, `HEROKU_GIT_REMOTE` looks like an environment variable, so we should make it `<HEROKU_GIT_REMOTE>`:

![image](https://user-images.githubusercontent.com/26604994/83077801-31178000-a046-11ea-99d6-ae5074d6fbd0.png)

**Comment by marionschleifer** [comment]
Closing this in favour of https://github.com/hasura/graphql-engine-internal/issues/446.
