### ISSUE TITLE
Feature request: Define and save seed data via console

### ISSUE THREAD

**Issue by Manubi** [hasura/graphql-engine#4916]
Hey,
first of all thanks for the great work everyone! 👏 

Problem:
I am working for a startup where we have to deal with a lot of seed data that updates pretty often as people make mistakes or something else changes. The thing is, every time someone updates something in the hasura console I need to update the migrations as well, in order to not loose the changes when we redeploy the next time. 

Solution:
It would be awesome if we could have a checkbox where we could mark a row as seed data in the console. So everyone who updates the seed data can do it via the hasura console and the developer only needs to save the seed data from time to time as it is the case with the meta data. 

Don't get me wrong, hasura is a fantastic product, but the more powerful the console gets the less mundane work every developer has to do. 😄 

Thanks! 

EDIT: Sorry, just saw that the feature is in the pipeline. Is there a rough release date available? Thanks!

**Comment by rikinsk** [comment]
Yes. This is currently under development in https://github.com/hasura/graphql-engine/pull/3763. We would expect this to be out in the next couple of releases. cc: @scriptonist

**Comment by praveenweb** [comment]
Managing seed data files via CLI is available from [v1.3.0-beta.2](https://github.com/hasura/graphql-engine/releases/tag/v1.3.0-beta.2)
