### ISSUE TITLE
Remote Schemas refresh issue

### ISSUE THREAD

**Issue by samuelcastro** [hasura/graphql-engine#4921]
I'm facing an weird issue with remote schemas, I have a remote schema in a headless CMS (GraphCMS) and usually the schema changes quite often, the problem that I'm facing is that once I changed the schema on GraphCMS those changes are not reflected on Hasura, they old schemas are still preserved somehow, it looks like some sort of cache or something.

Thoughts?

Thanks.

**Comment by samuelcastro** [comment]
I just found a `reload` button in the remote schemas pages and now it's working, but that changes how I initially thought remote schemas worked, isn't it somehow live "connected" with the remote endpoint? If we need to constantly "reload" remote schemas, how can we automate this process?

Thanks!

**Comment by GeKorm** [comment]
Although I don't know the reasoning behind caching the schema (I imagine performance and reliability) I think this section in the documentation has some answers https://hasura.io/docs/1.0/graphql/manual/remote-schemas/index.html#schema-refreshing

**Comment by samuelcastro** [comment]
Ok thanks @GeKorm this is what I needed to know, more specifically, how to programatically reload remote schemas: https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/remote-schemas.html#reload-remote-schema

But it would be nice to know the reasons behind this strategy.

From documentation:

> From v1.0.0-beta.3 onwards, a remote server’s GraphQL schema is cached and refreshed only when user explicitly reloads remote schema by clicking the Reload button on the console or by making a reload_remote_schema metadata API request

**Comment by rikinsk** [comment]
@samuelcastro This was done to improve performance. Reloading remote schema everytime the metadata changes starts having performance impacts if you have lots of remote schemas or have very large remote schemas. As in most cases metadata change are due to updates to the database schema or other configuration such as relationships or permissions, it is wasteful to keep refreshing the data from remote schemas on every change. Hope this makes sense.

**Comment by samuelcastro** [comment]
Ok @rikinsk it make sense now. Thanks!

**Comment by samuelcastro** [comment]
Hi @rikinsk Is there a way to reload schemas from Hasura CLI?
