### ISSUE TITLE
Hasura console fails to launch when using --insecure-skip-tls-verify

### ISSUE THREAD

**Issue by pradyuman** [hasura/graphql-engine#4926]
I get the error "Invalid admin-secret passed from CLI" when trying to use the console UI with the `--insecure-skip-tls-verify` flag.

The other cli commands run just fine (e.g. migrate apply) but I cannot access the console UI.

**Comment by scriptonist** [comment]
@pradyuman this seems to be working on my end 🤔 can you provide a bit more info so that I can reproduce ?
![image](https://user-images.githubusercontent.com/8335904/83501946-820ff400-a4de-11ea-8c0b-74de30b6e445.png)

**Comment by ste824** [comment]
@scriptonist I get the same as you on the cmd, but then when I go to http://localhost:9695/ in a browser I get this, which sounds like the same thing as @pradyuman  
![image](https://user-images.githubusercontent.com/68113975/87159208-e3cf3500-c2b8-11ea-8b89-3691f70fe96f.png)

**Comment by pradyuman** [comment]
Yep, this is exactly what happens to me as well.

**Comment by galipmedia** [comment]
Same here all other CLI things work fine only console fails with invalid password no matter what I try.

**Comment by divramod** [comment]
same problem here. what could be the problem?

**Comment by pkong-ds** [comment]
Same problem here. All commands except `hasura console` work fine with the provided admin secret in `config.yaml` file.

**Comment by rlanyi** [comment]
for me it doesn't even work if I provide the admin secret with `--admin-secret`

my version is:
```
bash-5.0# hasura version
INFO hasura cli                                    version=v1.3.3
INFO hasura graphql engine                         endpoint="http://hasura:8080" version=v1.3.3
```

**Comment by andreikaralkou** [comment]
Same problem for me. Doesn't work `hasura console`

**Comment by sergiogcx** [comment]
Try removing (or adjusting) the HASURA_GRAPHQL_CORS_DOMAIN env var.  I ran into this problem a few moments ago, after playing a bit with the environment variables I found that I had a strict CORS policy. That's what worked for me anyways.

**Comment by brancusi** [comment]
Same problem here. This is only happening on v2. Have tried many variations. Any ideas?

**Comment by marbemac** [comment]
For us we had `HASURA_GRAPHQL_DISABLE_CORS: 'true'` which broke the cli console - removing that when we need to use the console fixed the issue for us.

**Comment by samuela** [comment]
Same here. I get this issue when trying to run `hasura console` on a remote NixOS machine and connect through SSH. When running locally on macOS I don't see this error. 

At least it'd be nice to get a correct error message. It's clearly not an invalid admin-secret issue...

**Comment by samuela** [comment]
Setting `HASURA_GRAPHQL_CORS_DOMAIN="*"` doesn't make any difference for me.

**Comment by samuela** [comment]
Just talked about this issue in office hours... Mysteriously my issue went away! Not 100% clear what changed. There were some package upgrades, though they should've been inconsequential.

I'll report back if I manage to reproduce the issue!

**Comment by samuela** [comment]
... and it's back! No idea what changed. Everything about my environment is the same, running all the same commands the same as I did during office hours...

**Comment by CKnoppas** [comment]
ran into the same issue after migrating from v1.x.x to v2.x.x... what worked for me was setting a different `--console-port` and `--no-browser`. Maybe you try playing around with that.

```
INFO hasura cli                                    version=v2.1.0
INFO hasura graphql engine                         endpoint="http://localhost:8080" version=v2.1.0

```
so i ran `hasura console --console-port 9090` and that fixed the issue for me

**Comment by purush7** [comment]
Can you guys follow the below steps and let me know whether the message `Invalid admin-secret passed from CLI` is still occurs or any other errors?

- Make sure to pass`HASURA_GRAPHQL_CORS_DOMAIN` env var with value `http://localhost:9695` in the case of graphql-engine endpoint having a different origin than `localhost`
- execute `hasura console`
- If there is a error message `x509: certificate signed by unknown authority`, make the certificate a trusted one
- If there isn't any error messages, go to `http://localhost:9695/console` in the preferred browser.


The response in https://github.com/hasura/graphql-engine/issues/4926#issuecomment-656674923 occurs for the endpoint
`http://localhost:9695/console/login` and I think `http://localhost:9695` is getting redirected to `http://localhost:9695/console/login` (ref:https://github.com/hasura/graphql-engine/issues/4926#issuecomment-965829817)

@samuela (regarding:https://github.com/hasura/graphql-engine/issues/4926#issuecomment-965829817) `http://localhost:9695/console` is the correct page for `cli-console` and `http://localhost:9695/console/login` displays the error message for `cli-console` 



The changes to be made are
- `http://localhost:9695/console/login` doesn't check the value of `admin-secret`
- the behavior of `--insecure-skip-tls-verify`

**Comment by purush7** [comment]
This can be a temporary workaround certification after making the self-signed certificates as trusted and addition of `http://localhost:9695` to `HASURA_GRAPHQL_CORS_DOMAIN`
and here the reason behind is browser blocking the API because of a self-signed certificate
Here `https://app.hasura.local` is server endpoint proxy

https://user-images.githubusercontent.com/72007599/148385011-97e0f1ac-74ca-4c8c-b712-c5d7adf2390d.mov
