### ISSUE TITLE
docker-compose.yml manifest points to non-existent image?

### ISSUE THREAD

**Issue by stlalpha** [hasura/graphql-engine#4937]
stlalpha@reverse:~/PROTOTYPING/hasura$ docker-compose up -d
Pulling graphql-engine (hasura/graphql-engine:v1.2.2)...
ERROR: manifest for hasura/graphql-engine:v1.2.2 not found: manifest unknown: manifest unknown

**Comment by shahidhk** [comment]
We were trying to push 1.2.2 but it didn't go through through the CI due to some resource restrictions. I have reverted the change from stable branch. Please use 1.2.1 till we make an official release.
