### ISSUE TITLE
How to define default action url handler for all handlers?

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [hasura/graphql-engine#4941]
How to define default action url handler for all handlers?

**Comment by rikinsk** [comment]
This is not possible currently. You can set an ENV variable and use that for all your actions. See the `URL templating` note in the [docs](https://hasura.io/docs/1.0/graphql/manual/actions/create.html#step-2-create-the-action-handler)

**Comment by FredyC** [comment]
Sorry for poking to the closed the issue, but is it really that problematic to add a server flag that allows configuring this value? Even with the ENV variable, it's kinda annoying to remember the name of the correct one after a while.

Can you at least reopen the issue? It should be worth investigating.
