### ISSUE TITLE
`sslmode` flag in `HASURA_GRAPHQL_DATABASE_URL`

### ISSUE THREAD

**Issue by michaelwooley** [hasura/graphql-engine#4944]
# Background

Hi, I was working through [this document](https://hasura.io/docs/1.0/graphql/manual/guides/deployment/digital-ocean-one-click.html) to set up an instance on digital ocean. Everything went smoothly until I got to the [last step of configuring my managed DB](https://hasura.io/docs/1.0/graphql/manual/guides/deployment/digital-ocean-one-click.html#using-digitalocean-managed-postgres-database).

In short, the instructions were to go into your `docker-compose.yaml` and change the `HASURA_GRAPHQL_DATABASE_URL` to the correct connection string (e.g. `postgresql://user:password@host:port/database`).

# Problem

The problem appears to come from the fact that the default connection string DO gave me had an added `sslmode` flag. That is, it had the form:

```
postgresql://user:password@host:port/database?sslmode=require
```

When I tried to restart the container with this environment, it was in a perpetual "restarting" mode. (That is, `docker-compose ps` showed that hasura was restarting but there was nothing obviously wrong in the logs.)

# Fixes

## Fast but maybe less secure?

So it turns out that just removing the `sslmode` flag got rid of the issue. That is, just set the variable to be `postgresql://user:password@host:port/database`.

_However,_ am I correct in thinking that this might be a bit less secure?

## Better?

Reading a bit into the pg docs it looks like adding the CA certificate...somewhere might do the trick.

I don't think I did anything special when setting up my managed PG on digital ocean so this might be some newer default behavior? If it is just a matter of adding the CA certificate it might be nice to add that final step to the docs.

**Comment by reinoldus** [comment]
What is the error message that hasura gave you?

I had the same issue with DO managed db's, for me hasura gave me this message: https://github.com/hasura/graphql-engine/issues/2764

My comment here fixed the issue: https://github.com/hasura/graphql-engine/issues/2764#issuecomment-619966754

Maybe hasura has some quirky bug where the extensions are not properly loaded if you init the first connection in ssl mode?

And re insecure: I don't think you can connect to the DO managed instances without ssl at least not via the public network. At least that is what suggested here in the last sentences: https://www.digitalocean.com/docs/databases/mysql/how-to/secure/

> By default, you must use SSL to transmit data because it prevents eavesdropping on administrative usernames and passwords as well as the data itself as it is transmitted. However, SSL doesn't protect against man-in-the-middle (MITM) attacks or impersonation.

**Comment by michaelwooley** [comment]
Apologies for the late/non-response.

Unfortunately, I could not find an actual error message, just that the container was in perpetual restart mode. At the time I was not trying to launch it with any extensions (unless, of course, the hasura graphql image tries to install extensions on its own).

I am going to go ahead and close this as it seems to be an isolated issue and I am no longer using hasura in my project.
