### ISSUE TITLE
Clicking on Modify View freeze browser

### ISSUE THREAD

**Issue by amitava82** [hasura/graphql-engine#4961]
When I try to modify a view the browser freezes, CPU usage goes up 100%. Only way to get out of this is to kill the browser process. Tried this Chrome and Safari. I can browse the rows fine. This only happens to few views which has more number of fields, eg - 10 to 20. Strangely this happens only on our QA instance; works file on the Prod instance with the same view. I'm not sure how else I can help to debug this issue.

**Comment by renato** [comment]
@amitava82 were you able to solve it? It started happening on my instance after a server migration.

**Comment by amitava82** [comment]
No, it is still an issue. @rikinsk anything on this?

**Comment by soorajshankar** [comment]
@amitava82 @renato,
I was trying to reproduce this from my end, but unfortunately I couldn't reproduce this, I tried with 1.3.1 and  v2.0.0-beta.2, both seem to be working fine with views that contain~20+ columns. 
Could you share which version of hasura are you on? and is there any particular steps that I could follow to reproduce this?

**Comment by amitava82** [comment]
Unfortunately I can't repo this anymore after we've made changes to the problematic view. So I guess this issue can be closed for now.

**Comment by renato** [comment]
Not reproducible here either 👍
