### ISSUE TITLE
Throw error on failing mutation

### ISSUE THREAD

**Issue by AdityaAnand1** [hasura/graphql-engine#4962]
Trying a simple insert with a unique column constraint (that should fail if it violates the unique constraint)

![image](https://user-images.githubusercontent.com/13274079/83479464-3cd7cc00-a4b6-11ea-8ac3-23b945a580e8.png)

and hasura happily returns 200 status

![image](https://user-images.githubusercontent.com/13274079/83479508-642e9900-a4b6-11ea-8bd7-429eef84d18e.png)

When infact the response.data.errors array gives the actual error: 
![image](https://user-images.githubusercontent.com/13274079/83479544-7e687700-a4b6-11ea-83d9-67804818eaf0.png)

Just trying understand the reasoning behind the 200 response code, is there a primer or a guide on the convention of status codes used in hasura? I need a way to reliably detect error responses. Given that the 200 status is not reliable, should I manually check length of response.data.errors to see if there are any errors?

**Comment by rikinsk** [comment]
This is by design. You can find more context about this at https://github.com/hasura/graphql-engine/issues/3571.
