### ISSUE TITLE
We are receiving this error messages "webhook authentication request failed"

### ISSUE THREAD

**Issue by mflps** [hasura/graphql-engine#4975]
We are receiving this error messages "webhook authentication request failed", on the webhook authentication: 

`{"type":"http-log","timestamp":"2020-06-02T20:57:18.657+0000","level":"error","detail":{"operation":{"error":{"path":"$","error":"webhook authentication request failed","code":"unexpected"},"request_id":"a050c080-e409-48a5-b69b-e201864c4585","response_size":80,"raw_query":"{\"operationName\":\"GetDataByHour\",\"variables\":{\"vehicleId\":9,\"timestamp\":\"2020/05/26T21:56\"},\"query\":\"query GetDataByHour($timestamp: timestamp, $vehicleId: Int) {\\n data: databyhour(where: {timestamp: {_gte: $timestamp}, vehicleId: {_eq: $vehicleId}, wh: {_is_null: false}​}) {\\n ...DataByHour\\n __typename\\n }\\n}\\n\\nfragment DataByHour on databyhour {\\n timestamp\\n batteryhealth\\n deltaEstimatedMiles\\n deltaIdealMiles\\n efficiency\\n wh\\n whPerMile\\n deltaWatts\\n watts\\n estimatedMiles\\n idealMiles\\n batteryLevel\\n maxMilesAvailable\\n outsideTemperature\\n insideTemperature\\n speed\\n __typename\\n}\\n\"}"},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"89.115.191.0","method":"POST","content_encoding":null}​}}`
--

3 questions:

 - How we control the webhook call timeout, because everything fine on the server side
 - why hasura is not respecting the 60s Cache?
 - hasura has a retry mechanism?

Thank you,
Miguel Santos

**Comment by tirumaraiselvan** [comment]
Do you have any logs from your webhook auth service? In particular, could you show the webhook response that is coming for this request?

**Comment by mflps** [comment]
Response is 200 OK, but sometimes is slower than 1s, and its when hasura gives error.

**Comment by mflps** [comment]
Here is the response from the server side:

2020-06-02T20:57:18.7310926Z,a0c8fda012280f41,,Authentication,"https://devm2daf01.azurewebsites.net/api/webhook/authentication",True,200,"6063.3433","3sec-7sec",request,"{""FunctionExecutionTimeMs"":""4539.8848"",""TriggerReason"":""This function was programmatically called via the host APIs."",""HostInstanceId"":""73c57aad-c5a3-4ec2-bdcb-fba48c3801ba"",""InvocationId"":""d833ebec-6eb2-4b8c-85b5-d9a3d8f9f2e4"",""LogLevel"":""Information"",""Category"":""Host.Results"",""FullName"":""Authentication"",""ProcessId"":""8836"",""HttpMethod"":""POST"",""HttpPath"":""/api/webhook/authentication""}",null,Authentication,5d1c2b25619ca34da77051b96e2e8b6b,5d1c2b25619ca34da77051b96e2e8b6b,,,,,,,PC,,,"0.0.0.0",Amsterdam,"North Holland",Netherlands,,devm2daf01,e8106a8061bfbf1e77923f2701724267ee8611f0100fbafddc292eb815692d1e,"e2124198-11f3-4845-b343-5f29345d1ecc",devm2daf01,"a03c458c-3ef4-40f8-b614-7cf09c081d36","azurefunctions: 3.0.13614.0","b4780eae-a513-11ea-81ad-dd6cadaf8d05",1

**Comment by mflps** [comment]
Any progress? I've checked all the logs and everything is good from the webhook server side...

**Comment by tirumaraiselvan** [comment]
@mflps It's not clear what is the response sent from the webhook auth service from the log you sent.

What we need when you hit the error:

1. Check that auth service recvd the request
2. Check the response sent by the auth service

**Comment by mflps** [comment]
@tirumaraiselvan  The response is working for 99,9% of the cases and giving 200 for this cases. What you want to see?
How can I trace this on Hasura? It's for sure problem in Hasura related with the timeout.
I'm checking the response and is good from the logic point of view, the only difference in this cases it's the time to response.

**Comment by tirumaraiselvan** [comment]
@mflps Gotcha, could you raise a new request for configuring timeouts and retries for webhook auth?

**Comment by mflps** [comment]
@tirumaraiselvan what you mean? where? How can I troubleshoot this? This is having impact on my platform...

**Comment by hgiasac** [comment]
@mflps Tiru means that you can create new Feature request issue for this. This is new feature, so you need to wait for it on newer versions. 

Regards

**Comment by mflps** [comment]
@hgiasac I understand, but what it's the current timeout? How can I troubleshoot this, to tune on my side? This is having impact on our customers.

And where I open that?

BTW Cache_Control is also not being reinforced...

regards

**Comment by tirumaraiselvan** [comment]
Well, I am just spilling ideas now: maybe add some intentional timeout in your webhook auth and see that it clears the 4s mark?

**Comment by mflps** [comment]
Yes, if I put 5s it doesn’t fail....

**Comment by mflps** [comment]
OK I have some progress in my analysis, the webhook is answering in less than 5s, but sometimes there is a cold start of some machine, and the end2end result is bigger than 30s... that's why we receive error. So the timeout would be good for us. I agree.

**Comment by tirumaraiselvan** [comment]
Closing this in favour of https://github.com/hasura/graphql-engine/issues/4990
