### ISSUE TITLE
Give enum tables a different icon on the sidebar

### ISSUE THREAD

**Issue by Xetera** [hasura/graphql-engine#4984]
It gets a little difficult to keep track of enum tables once you're past a certain amount. I feel like something like this could help
![](https://dreamcatcher.xetera.dev/😓👑💁🎓😊.png)

I would be happy to give this a shot if it's something the hasura team is interested in and if this data is available to the frontend

Possibly related #4981

**Comment by rikinsk** [comment]
@Xetera Would be awesome if you could raise a PR for this. The information should be available.cc: @beerose  

The only question remaining is what should the icon be? Maybe [this](https://fontawesome.com/v4.7.0/icon/list-ul)?

**Comment by beerose** [comment]
Yes, all the information is available. This is the corresponding part of the code: https://github.com/hasura/graphql-engine/blob/master/console/src/components/Services/Data/DataSubSidebar.js
You can check if a table is an enum table by accessing `is_enum` property from [`table` object](https://github.com/hasura/graphql-engine/blob/master/console/src/components/Services/Data/DataSubSidebar.js#L104).
