### ISSUE TITLE
event triggers: update listen columns should have "*" by default

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#4999]
![Screen Shot 2020-06-05 at 7 04 49 PM](https://user-images.githubusercontent.com/8663570/83882304-8ac32d00-a75f-11ea-8b6e-9ba29f692b1f.png)

By default, the list of columns are explicitly set. This means if a new column is added, then that is not part of LISTEN column. This would be surprising behaviour if the user has not explicitly chosen the columns.

**Comment by abhi40308** [comment]
This should be fixed here https://github.com/hasura/graphql-engine/commit/bc467a283aff4eea222fcd288681cf362bcd3a34
