### ISSUE TITLE
Document schema introspection

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#500]
mostly standard graphql concepts/community tooling

via:
https://medium.com/@joninsky/how-would-i-go-about-introspecting-my-new-graphql-server-powered-by-hasura-f9eb36ecf73

**Comment by shahidhk** [comment]
The corresponding docs page is present at https://docs.hasura.io/1.0/graphql/manual/schema/export-graphql-schema.html

But it doesn't have the word introspection.

**Comment by swatisingh45** [comment]
Hey! @shahidhk I would love to take up the issue, can you please explain in detail what is to be done?

**Comment by shahidhk** [comment]
@swatisingh45 It's just about adding the word `introspection` to the docs, particularly to the page mentioned above.

@rikinsk What do you think?

**Comment by swatisingh45** [comment]
Yeah, but what is the significance of adding this word? Where is this to be added or in what terms?

**Comment by ulshell** [comment]
Hey I would like to work on it
