### ISSUE TITLE
add relevant indexes to hdb_catalog schema

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#502]
event_invocation_logs should have an index on join column (event_id), to basically do efficient JOINs from event_log table.

Similarly there might be other JOINs. We need to add for them too.

**Comment by tirumaraiselvan** [comment]
https://github.com/hasura/graphql-engine/pull/419/commits/feb6f14c30617138a21d811cce33f04ff02b2aac

**Comment by ecthiender** [comment]
@tirumaraiselvan PR?

**Comment by shahidhk** [comment]
@tirumaraiselvan, are all the required indexes added? Performance has definitely increased.

**Comment by dsandip** [comment]
@tirumaraiselvan What's the status here?
