### ISSUE TITLE
Relay: Schema introspection isn't working

### ISSUE THREAD

**Issue by njaremko** [hasura/graphql-engine#5020]
After installing `v1.3.0-beta.1`, when I toggle the relay switch, the explorer doesn't show any schema. I've also tried a few other graphql tools, none can introspect the relay schema. I'd be happy to provide any info you need to debug, just let me know.

Having said that, I can run graphql queries against the relay endpoint perfectly fine, since I happen to know the shape of the query.

**Comment by Winwardo** [comment]
I don't have a full repro for this, but I believe it's to do with how views are exposed.
I have a view that's essentially a table with some extra metadata joined in, with an `id` field.

When I look at the network request for the introspection schema, I get the following error message:
`{"errors":[{"extensions":{"path":"$","code":"unexpected"},"message":"type info not found for: 'accounts_view'"}]}` where `accounts_view` is a view over `accounts`.

Note that on the regular view, `accounts_view` would be the second item to be exposed not the first, suggesting it's this particular view and not whatever table/view was found first.
![image](https://user-images.githubusercontent.com/840549/84122939-158e7b00-aa31-11ea-8a35-861d831c1b51.png)

**Comment by rakeshkky** [comment]
@njaremko Please give us minimal reproduction schema.

**Comment by rakeshkky** [comment]
@Winwardo I could confirm the issue. It'll be fixed in next beta release.

**Comment by njaremko** [comment]
Similarly, I'm getting
```
{"errors":[{"extensions":{"path":"$","code":"unexpected"},"message":"type info not found for: 'user_roles_select_column'"}]}
```

`user_roles` is a view
```
CREATE VIEW user_roles AS
SELECT role_id as id, model_id as user_id, name, created_at, updated_at
FROM model_has_roles
LEFT JOIN roles
ON model_has_roles.role_id = roles.id
WHERE model_type = 'users'
```

Here are the relevant schemas:
```
-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS roles_id_seq;

-- Table Definition
CREATE TABLE "public"."roles" (
    "id" int4 NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
    "name" varchar(255) NOT NULL,
    "guard_name" varchar(255) NOT NULL,
    "created_at" timestamp(0),
    "updated_at" timestamp(0),
    PRIMARY KEY ("id")
);
```

```
CREATE TABLE "public"."model_has_roles" (
    "role_id" int4 NOT NULL,
    "model_type" varchar(255) NOT NULL,
    "model_id" int8 NOT NULL,
    CONSTRAINT "model_has_roles_role_id_foreign" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE CASCADE,
    PRIMARY KEY ("role_id","model_id","model_type")
);
```

**Comment by rakeshkky** [comment]
@njaremko @Winwardo 

Please try the preview app in the [comment](https://github.com/hasura/graphql-engine/pull/5013#issuecomment-641724891) and let us know if the issue still persists.
Thank you.

**Comment by Winwardo** [comment]
I updated my Docker image to `hasura/graphql-engine:pull5013-f7fd3648`, without changing anything else, and now I can see the Relay schema.

![image](https://user-images.githubusercontent.com/840549/84247402-f874ad80-aaff-11ea-8a56-8ed54cd95e5e.png)

Thank you!
