### ISSUE TITLE
Cannot create row from console due to id schema definition conflict

### ISSUE THREAD

**Issue by tkim90** [hasura/graphql-engine#5024]
Hi Hasura team!

First of all, thanks for making such an amazing tool.

I ran into a problem trying to insert rows from the Hasura console and wanted to make sure whether this was a setup issue.

## The Problem
I can't create new rows because it asks me to provide a value for the primary key.

When I click "insert rows" from the Hasura console (under the "Data" tab), it asks me for a value in the primary `id` field. I shouldn't be able to do this because I defined my table schema to set it as `GENERATED ALWAYS AS IDENTITY` - aka postgres should always auto generate the primary `id` value. Clicking "insert row" with any value there returns an error.

[Imgur screenshot](https://imgur.com/a9WPquL)

## What I tried
- Both the "NULL" and "default" radio button is disabled, forcing me to put in a value.
- When I put in an arbitrary number + hit save, it returns an error:

## Error
```json
unexpected : cannot insert into column "id"

    "error": {
        "exec_status": "FatalError",
        "hint": "Use OVERRIDING SYSTEM VALUE to override.",
        "message": "cannot insert into column \"id\"",
        "status_code": "428C9",
        "description": "Column \"id\" is an identity column defined as GENERATED ALWAYS."
    },
```

Details: my primary key `id` is defined as follows in my schema:
`id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,`

## Steps to reproduce
1. Create a postgres table with a primary key, id, with type `INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY`
2. Connect it to Hasura
3. Go to Hasura console, go to DATA tab, select the table, and hit "Insert Row" tab
4. Enter any value into the `id` field and hit "Insert Row" at the bottom

Thanks in advance!

**Comment by beerose** [comment]
Thank you for reporting this and detailed description! 

We already track this problem in https://github.com/hasura/graphql-engine/issues/4863, so I'm closing this issue as a duplicate.

**Comment by tkim90** [comment]
@beerose Ah, I missed that, my bad. Thanks!
