### ISSUE TITLE
Getting apollo iOS Swift subscriptions to work with auth headers

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#503]
This is just an issue to document how to get [apollo iOS client](https://www.apollographql.com/docs/ios/) subscriptions to work.

That's how the headers go in:
```swift
let authPayloads = [
  "X-Hasura-Access-Key": "<key>"
]
let map: GraphQLMap = ["headers": authPayloads]
let websocket = WebSocketTransport(request: urlRequest, connectingPayload: map)
```

**Comment by havebeenfitz** [comment]
That's definitely a fix. Thank you, I spent hours on it
