### ISSUE TITLE
What i must input into X-Hasura-User-Id when role is anonymous?

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [hasura/graphql-engine#5031]
![image](https://user-images.githubusercontent.com/60403187/84190247-4b6a4880-aa9f-11ea-99e3-91751ee026c5.png)

**Comment by hgiasac** [comment]
No, maybe you don't need it. `X-Hasura-User-Id` is optional that is used for permission. For `anonymous` role, it won't be used whether you set it or not. The sample just set it as placeholder. You can remove it if you want

**Comment by MaxmaxmaximusGitHub** [comment]
@hgiasac  but i use this variable in permission to view "current_user", by rule `{id: {_eq: "X-Hasura-User-Id" }}`, and this must return null to anonymous user, but if i not get any permission anonymous to "current_user" view, graphql query from not loginnet user throw GraphQL error "current_user not exists in schema", so I have to give at least some permission, even to an anonymous user. so that he can get null without errors and understand what is anonymous.

**Comment by hgiasac** [comment]
@MaxmaxmaximusGitHub This is expected behavior. The user only can fetch permission GraphQL schema. So for anonymous role, you should add a select permission for `current_user`, but with dummy condition that is always false, e.g `{ "id": { "_eq": -1 } }`. Anonymous users always get empty result
