### ISSUE TITLE
Filtering records using data from another table

### ISSUE THREAD

**Issue by romcok** [hasura/graphql-engine#5034]
Hi,
we are using Hasura, which is excellent. All the things we needed have worked for us with it so far, but now we face a problem that I can't solve.

I need to achieve that when a user blocks someone, their content disappears for him. I wanted to solve it with a **custom check**, but I am not able to set data from another table to a value.

Here is what I am trying:
<img width="527" alt="Screenshot 2020-06-09 at 22 02 40" src="https://user-images.githubusercontent.com/179070/84194280-15c46000-aa9d-11ea-8818-41da3a4c7cf5.png">

Does anyone have an idea of how to implement this with Hasura? 🙏

**Comment by hgiasac** [comment]
First, you add `user_blocked_channels` relationship on `channels` table
![channel_relationship](https://user-images.githubusercontent.com/1615675/84224413-a5522900-ab06-11ea-8b3e-ad02b412b446.png)
Then define relationship permission. It is easier
![channel_permission](https://user-images.githubusercontent.com/1615675/84224417-a84d1980-ab06-11ea-93e5-e254c75e9298.png)

**Comment by romcok** [comment]
Oh, I didn't get this. Great, thank you.
