### ISSUE TITLE
Relay hash id size

### ISSUE THREAD

**Issue by ro-savage** [hasura/graphql-engine#5037]
The current relay hash id is a has of a json representation of the table structure.

`{"table" : {"schema" : "public", "name" : "test"}, "columns" : {"id" : 1}}`
This generated a very long hash
`eyJ0YWJsZSIgOiB7InNjaGVtYSIgOiAicHVibGljIiwgIm5hbWUiIDogInRlc3QifSwgImNvbHVtbnMiIDogeyJpZCIgOiAxfX0=`

Is there a good reason to hash a json like this? instead of a minimal version?
`public:test:1` which generates a hash of `cHVibGljOnRlc3Q6MQ==`

This id would be better for data transfer size and if people used the hash in the URL `/projects/cHVibGljOnRlc3Q6MQ==`

The advantage of a json would be that it's easier to decode and use if your app.

A side note, how does hasura relay handle multiple primary keys that are composite keys rather than an id field?

**Comment by jmsegrev** [comment]
> The advantage of a json would be that it's easier to decode and use if your app.

I think the drawbacks of the extra bytes outweigh this benefit, since the decoding of a custom format could easily be solved with proper documentation.

> A side note, how does hasura relay handle multiple primary keys that are composite keys rather than an id field?

A custom format will also work for this cases. `schema:table:columnA.1,columnB.2`

**Comment by jmsegrev** [comment]
> This id would be better for data transfer size and if people used the hash in the URL /projects/cHVibGljOnRlc3Q6MQ==

On a side note, base64 is not url freandly . I think there is a great benefit of having the encoded done to be url safe. Frontend developers would love it.

**Comment by rakeshkky** [comment]
@ro-savage @jmsegrev 

Implementing custom format for Node ids like `<schema>:<name>:<column-1>:<column-2>` needs a custom parser. Instead, I'm planning to use json array like `["schema", "name", "column-1", "column-2"]`

**Comment by rakeshkky** [comment]
@ro-savage Please read this [note](https://github.com/hasura/graphql-engine/pull/5013/files#diff-f3ab333f0443f416ce923cbd62d7df15R264) in the source code to know about relay id encoding. Thank you.
