### ISSUE TITLE
Hasura Console can not import/export v2 metadata

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#5048]
We have migrated to v2 metadata but are disappointed to see the Hasura Console still only imports/exports v1 metadata. It sends a confusing message to users that perhaps v2 is only for CI/CD as opposed to an eventual deprecation of v1? You tell me.

I understand importing/exporting a group of files is harder, so perhaps you could impose a tar or zip file as input/output.

Ideally there would be a v1/v2 selector next to these import/export buttons.

**Comment by rikinsk** [comment]
Currently the metadata exported via the console and the `export_metadata` API is a json file which can be imported via the console or the `import_metadata` API.

The CLI on the other hand has its own logic of dealing with metadata using yaml files that is optimised for CI/CD like you mentioned.

Note that there is no difference in the contents of metadata exported in in v1 or v2. It's just a different way of representation of the same data and there are no plans to deprecate the v1 format.

**Comment by rikinsk** [comment]
Also, forgot to add that your expectations here are quite valid and we will work towards unifying these for a more coherent experience across the console, API and CLI

**Comment by jflambert** [comment]
Well since v3 is out, I don't suppose there is much need for this issue anymore. I certainly won't need it.
