### ISSUE TITLE
[Documentation] [Console] improve scheduled events naming convention

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#5049]
After reading the 1.3.0-beta.1 changelog and using the feature in the Hasura console, I find the naming convention confusing for the new "scheduled triggers" feature. I see four names for more or less the same thing

- scheduled triggers (in the [changelog](https://github.com/hasura/graphql-engine/releases/tag/v1.3.0-beta.1))
- scheduled events (in the Console)
- cron triggers (one of the sub-features)
- (one-off) scheduled triggers (one of the sub-features)

Bonus:
- the Hasura Console browser tab (title) only says "Triggers" when the "Cron triggers" sub-feature is selected.
- the Hasura Console breadcrumbs only say "Scheduled" when the "Cron triggers" sub-feature is selected

I recommend only using "scheduled events" and "one-off scheduled events". Only refer to "cron" when describing the scheduling mechanism.

Please feel free to close this issue if I'm completely in the wrong.

**Comment by rikinsk** [comment]
@jflambert Valid feedback here. We'll work on making the terminology consistent across docs and the console

**Comment by jflambert** [comment]
@rikinsk I see some things are fixed in 1.3.0-beta.2, the names are much more consistent (cron triggers)

The only problem I see is that the breadcrumb still says "Scheduled" instead of "Cron Triggers"

![image](https://user-images.githubusercontent.com/11539524/85242751-dd624180-b40d-11ea-9391-94168d4d7c5e.png)

**Comment by tirumaraiselvan** [comment]
Most of the errors here are fixed in v1.3.0 stable. Pls reopen and let us know if you still find any confusion.
