### ISSUE TITLE
JSON payload in cron triggers should be pretty-printed

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#5052]
Would be nice if the cron trigger payload text box would pretty-print the JSON payload as opposed to printing a single line. Pretty sure it's the only place in the Hasura Console where JSON isn't pretty-printed too.

![image](https://user-images.githubusercontent.com/11539524/84286928-4c39c380-ab0d-11ea-9008-ac1e69a8eb3e.png)

**Comment by tirumaraiselvan** [comment]
@jflambert Little off-topic: With v1.3.0 stable, the body of a scheduled event is gonna change: https://github.com/hasura/graphql-engine/pull/5262 . In particular, see this comment: https://github.com/hasura/graphql-engine/pull/5262#issuecomment-652890466 .

**Comment by gnyani** [comment]
I can take a look at this, @beerose can you assign this on me please?

**Comment by jflambert** [comment]
> @jflambert Little off-topic: With v1.3.0 stable, the body of a scheduled event is gonna change: #5262 . In particular, see this comment: [#5262 (comment)](https://github.com/hasura/graphql-engine/pull/5262#issuecomment-652890466) .

hi @tirumaraiselvan I've started using 1.3.0 and indeed, I'm stuck on this new format change. I can't figure out how to execute a "run_sql" event with cron triggers anymore. Can you give me a quick example?
