### ISSUE TITLE
jsonb nullable input cannot be null

### ISSUE THREAD

**Issue by dminkovsky** [hasura/graphql-engine#5054]
I am using 1.2.2 and have an action that looks like:

```
type Mutation {
  createAccount (
    username: String!
    password: String!
    device: jsonb
  ): CreateAccountOutput
}
```

When I attempt this mutation:

```
mutation ($username: String!, $password: String!, $device: jsonb) {
  createAccount(username: $username, password: $password, device: $device) {
    userId
  }
}
```

with variables:

```
{
  "username": "username",
  "password": "password"
}
```

 I get the error: 

```
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "400"
      },
      "message": "\"device\" must be of type object"
    }
  ]
}
```

I get the same error for variables:

```
{
  "username": "username",
  "password": "password",
  "device": null
}
```

As the error suggests, I am required to input at least an empty object for the jsonb field. So this works:

```
{
  "username": "username",
  "password": "password",
  "device": {}
}
```

**Comment by tirumaraiselvan** [comment]
@dminkovsky I am not able to reproduce this. Could you confirm this is not something in your action handler?

![image](https://user-images.githubusercontent.com/8663570/84750072-73decf00-afd8-11ea-89dc-0d86e6ae3289.png)

**Comment by dminkovsky** [comment]
You are correct: it was a handler issue. Thank you for taking the time to try to replicating this, and sorry without correctly confirming on my end.
