### ISSUE TITLE
docs: document scheduled / cron triggers clean up 

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#5057]
@tirumaraiselvan 

I notice some documentation for the new scheduled and cron triggers is available, namely how to [manage them over API](https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/scheduled-triggers.html).

However I don't see anything about them under "[Event Triggers](https://hasura.io/docs/1.0/graphql/manual/event-triggers/index.html)"

Furthermore, the [cleanup event data](https://hasura.io/docs/1.0/graphql/manual/event-triggers/clean-up.html) page should be extended with instructions to properly purge the following tables:

- hdb_cron_events
- hdb_cron_event_invocation_logs
- hdb_scheduled_events
- hdb_scheduled_event_invocation_log

**Comment by tirumaraiselvan** [comment]
The main docs have been added in https://github.com/hasura/graphql-engine/commit/c4da0a70c52682ee77ad58f826f1d62d54b2afeb

I am changing the issue to add docs for cleanup.

**Comment by rikinsk** [comment]
Docs added at https://hasura.io/docs/latest/graphql/core/scheduled-triggers/clean-up.htmlhttps://hasura.io/docs/latest/graphql/core/scheduled-triggers/clean-up.html
