### ISSUE TITLE
support composite primary, and foreign keys and unique constraints through the console

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#506]
This issue comes from @lukebyrne and was originally opened [here](https://github.com/hasura/graphqurl/issues/27).

As of now:
1. You can set composite primary keys from the console while creating the table
2. You cannot set composite primary keys from the console once the table is already created (can be done via SQL)
3. You cannot set composite foreign keys from the console (can be done via SQL)
4. Relationships are not suggested based on composite primary keys (can be done by adding manual relationships) *([Related issue](https://github.com/hasura/graphql-engine/issues/284))*
5. Adding a manual relationship does not support multiple columns.

@praveenweb please point out if I have missed anything.

**Comment by Maxpain177** [comment]
Any updates?

**Comment by dsandip** [comment]
@praveenweb Once composite FKeys are available, are console changes needed for relationship recommendations over these constraints?

**Comment by dsandip** [comment]
@Maxpain177 There should be an update on this next week.

**Comment by dsandip** [comment]
@arvi3411301 
We can also address #285 here itself (the console part). Console suggestions for relationships based on Fkey should also pick up and show the Fkey name in the suggestions like this:

![relusingfkeynameinsuggestions](https://user-images.githubusercontent.com/24300818/49939178-16108900-ff02-11e8-9614-9d2c6df77b46.png)

@rikinsk FYI.

**Comment by dsandip** [comment]
@arvi3411301 Also adding wireframes for composite unique constraints:

**Create a composite unique constraint when creating a table**:
1) Option to create
![createtable5compunique1](https://user-images.githubusercontent.com/24300818/49943910-195e4180-ff0f-11e8-93c7-4e1258c8b7e8.png)

2) creating the constraint

![createtablecompunique2](https://user-images.githubusercontent.com/24300818/49943927-22e7a980-ff0f-11e8-8245-0cc9c3582e66.png)

**Options for composite unique constraint when editing a table**:

1) List comp-unique constraints with an option to create one:

![modtableschemacompuniq1](https://user-images.githubusercontent.com/24300818/49944219-f5e7c680-ff0f-11e8-933c-fec7f32e1115.png)

@arvi3411301 I forgot to add the option to add a composite FKey in the previous wireframes. Please take note of that option.

2) Editing a comp-unique-constraint:

![modtableschemaeditcompuniq](https://user-images.githubusercontent.com/24300818/49944247-04ce7900-ff10-11e8-8162-ec6456073ffe.png)

**Comment by dsandip** [comment]
From @rikinsk 
```
Show a column's config (all fields in the edit section) without having to click on the `edit` button in the modify tab. E.g. `unique`, `nullable`, `default value`, etc.
```

**Comment by dsandip** [comment]
@wawhal There are tiny modifications required in this, let's talk before you pick this up. cc: @rikinsk

**Comment by dsandip** [comment]
@rikinsk @wawhal 

## Latest wireframes

### Create table options

![1_createtable1](https://user-images.githubusercontent.com/24300818/53887334-0f4c6a80-4048-11e9-8393-687e0b4a42fe.png)

### Primary key (single-column/composite)
This is also the current behaviour, so no changes needed here

![2_createtableaddpkey](https://user-images.githubusercontent.com/24300818/53887474-5e929b00-4048-11e9-9be2-60948f0a37f9.png)

### Unique constraint - single column
For the most common use-case i.e. a unique constraint over a single column, you can define the constraint at the time of creating the column itself, and it will also show up in the section for unique constraints (which will show both single-column and composite constraints):

![2acreatetableaddpkey_1](https://user-images.githubusercontent.com/24300818/53887609-a4e7fa00-4048-11e9-89ea-1227a9cc80d9.png)

### Foreign key definition
with the option to define violation behaviour for update and delete:

![3createtablefkey](https://user-images.githubusercontent.com/24300818/53887661-bc26e780-4048-11e9-9354-0d78475f7cb2.png)

![4createtablefkeydef](https://user-images.githubusercontent.com/24300818/53887711-db257980-4048-11e9-863c-8c6dcf402ec9.png)

Show Fkeys creating during the table creation process:

![5createtablefkeysummary](https://user-images.githubusercontent.com/24300818/53887755-f42e2a80-4048-11e9-942a-7f13e1a9840a.png)

### Unique constraints

![6createtablecompuniquecreate](https://user-images.githubusercontent.com/24300818/53887800-0b6d1800-4049-11e9-83ad-5637319f6312.png)

Unique constraints' summary to be shown similar to Fkeys above while table is being created

### Modify table 

![7modtableschemaentry](https://user-images.githubusercontent.com/24300818/53887877-30fa2180-4049-11e9-9331-48fcd183ef05.png)

Modify Pkey:

![8modtableschemaeditpkey](https://user-images.githubusercontent.com/24300818/53887932-4707e200-4049-11e9-96ee-0c3948c60a57.png)

Modify Fkey:
*Existing issues with a dependent relationship will not be fixed here*

![9modtableschemaeditfkey](https://user-images.githubusercontent.com/24300818/53887951-50914a00-4049-11e9-8232-4e7ced591eee.png)

Modify unique constraint:

![Uploading 10modtableschemaeditcompuniq.png…]()

### Manual Relationship

![11modtableaddmanualrelationship](https://user-images.githubusercontent.com/24300818/53888106-ac5bd300-4049-11e9-9671-c68ed9197706.png)

![12modtableaddmanualrelationship_2](https://user-images.githubusercontent.com/24300818/53888114-b087f080-4049-11e9-9ef3-40197ee0e597.png)

**Comment by wawhal** [comment]
@0x777 @rakeshkky @ecthiender  Work is being done on console to support:
- PKs
  - You can drop and modify PK constraints
  - In case of modify, existing constraint is dropped and a new constraint is created  
- Composite unique constraints
  - You can create, drop and modify composite unique constraints
  - In case of modify, existing constraint is dropped and a new constraint is created
- Composing FK
  - You can create and drop composite FKs
  - In case of modify, existing constraint is dropped and a new constraint is created

cc: @dsandip @rikinsk

**Comment by mnlbox** [comment]
@dsandip your wire-frame is awesome. :heart:
I have one another suggestion. Maybe it's better to show dropdown as input type for **Insert Row** tab. For example in below image maybe it's better to show a dropdown that show `title` but pass `UUID id` for **parent_subject_id** field:

![Screenshot from 2019-03-11 16-00-27](https://user-images.githubusercontent.com/25859075/54124302-3b386900-4417-11e9-9f1e-3341c01cf5c4.png)

**Comment by mnlbox** [comment]
@dsandip Also I think some ordering for column also can useful and have a good UX to able to re order database table column. something like this:
![Screenshot from 2019-03-11 17-58-19](https://user-images.githubusercontent.com/25859075/54131428-91ada380-4427-11e9-8539-29bc5b5ba245.png)

**Comment by rakeshkky** [comment]
@wawhal Currently this is server behaviour

- Foreign keys
  - Dependencies (relationships) are being calculated on dropped constraints. An exception will be raised in case of any dependencies found for dropped constraints.
  - If `cascade` is `true` then those dependencies are dropped.

- Primary keys
  - There are no dependencies.
  - Primary key constraint names are updated in cache to generate `table_constraint` enum type in `on_conflict` clause in `insert` mutations.
  - A patch is needed to server to update primary columns in cache to generate input arguments for `<table-name>_by_pk` fields**. 

- Unique constraints
  - There are no dependencies.
  - Similar to primary keys, these constraint names are being updated in cache. 

** I'll push server patch to your branch. Update me with PR number.

**Comment by wawhal** [comment]
@rakeshkky the PR is not ready yet. Didn't open it to avoid unnecessary builds. You can push to issue-506 in my fork

**Comment by mnlbox** [comment]
Maybe related for table creation page: https://github.com/hasura/graphql-engine/issues/1462

**Comment by rikinsk** [comment]
Reopening to track unique constraints
