### ISSUE TITLE
Verbose logging

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#507]
via @praveenweb:

"we should enable verbose logging mode (via flag/env), where instead of just the query_hash, we get the actual query for better debugging".

**Comment by dsandip** [comment]
from Prashantha on Discord - additional info needed: the PG tables/columns being accessed

**Comment by dsandip** [comment]
Let's also add some numbers from #428 (*which I am closing in favor of this one*)

**Comment by martinzwirner** [comment]
I would like to point out that verbose logging is important for subscriptions as well. At the moment performance values are logged only for queries.

**Comment by mjonas87** [comment]
Any chance verbose logging could also spit out whether Hasura thinks you've configured it to use JWTs? Just had an issue where the `HASURA_GRAPHQL_JWT_SECRET` wasn't being set the right way because Windows.
