### ISSUE TITLE
Unable to track partitioned tables

### ISSUE THREAD

**Issue by qpre** [hasura/graphql-engine#5071]
Hi !

I'm currently trying to track a table that is partitioned over foreign tables.

**list of relations**

| Schema |     Name          |       Type                  |  
| -------- | --------------| -------------------| 
| public    | users               | partitioned table    |
| public    | users_eu         | foreign table           | 
| public    | users_us         | foreign table           | 

**Expectation**
Track `users` relation  in Hasura's schema.

**Actual behaviour**
When I open the Hasura console to see the list of trackable entities, 
I get `user_eu` and `users_us` but `users` won't show.

note: If I add a PostgreSQL view `all_users` that does a `SELECT * from users;` the `all_users` view shows up in the trackable relations and I'm capable of running `INSERT`, `SELECT` and `UPDATE` queries over it.

**Tested against**: 
 - Hasura (`v1.0`, `v1.2.2`, `v1.3.0-beta-1`)
 - PostgresQL 12

**Comment by rikinsk** [comment]
Partitioned tables have a `relkind` value of `p` in the `pg_class` table which the console currently does not fetch data for. A solution similar to the one added for foreign tables in #4742 should solve this.

cc: @nicuveo

**Comment by nicuveo** [comment]
We'll need to check if the backend currently supports them, there might be some required work there too. The easiest way to test would be to issue a 'track_table' and see what happens!

**Comment by tirumaraiselvan** [comment]
Some info here: https://github.com/hasura/graphql-engine/issues/655

**Comment by rikinsk** [comment]
Based on #655 it seems like for PG 11 onwards we pretty much everything works as expected (or did i miss something?). In that case we just need to start displaying them on the console.

**Comment by tirumaraiselvan** [comment]
I tracked using API and it works as expected (PG 11 onwards) so we can show it in console. Further tasks are mentioned here: https://github.com/hasura/graphql-engine/issues/655#issuecomment-652414335

I am not sure if we should show this only for PG >= 11 because of the limited capabilities of partitioned tables in PG 10.
