### ISSUE TITLE
Failed to opt out of pre-release notifications

### ISSUE THREAD

**Issue by MarcelloTheArcane** [hasura/graphql-engine#5074]
I just tried to opt out of pre-release notifications on my production Hasura deployment, and got this error:

> Failed to opt out
> postgres-error : invalid input syntax for type uuid: "null" 

```json
{
    "statement": "update hdb_catalog.hdb_version set console_state = '{\"disablePreReleaseUpdateNotifications\":true}' where hasura_uuid='null';",
    "prepared": false,
    "error": {
        "exec_status": "FatalError",
        "hint": null,
        "message": "invalid input syntax for type uuid: \"null\"",
        "status_code": "22P02",
        "description": null
    },
    "arguments": []
}
```

---

Current Hasura version: **v 1.2.1**

**Comment by jflambert** [comment]
I can confirm. Also would like to reiterate my request to completely [disable update notifications through an environment variable](https://github.com/hasura/graphql-engine/issues/4096).

**Comment by beerose** [comment]
Could you share the response of the following query:
```sql
select * from hdb_catalog.hdb_version;
```
?

**Comment by beerose** [comment]
Closing this issue as a duplicate https://github.com/hasura/graphql-engine/issues/4785.
