### ISSUE TITLE
Information about logs missing in docs

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#508]
There's no mention of logs in the docs currently. Some basic information on the fields in the structured logs should be added.

Suggestion: Add a section at the top-level , after GraphQL Engine internals (`Hasura GraphQL Engine` -> `Logging & Observability`).

**Comment by dsandip** [comment]
From Drew McArthur on email: 

> It might be mentioned, but it'd be great if the docs on setting up a docker instance included how to print out the hasura server's logs, while that info wasn't hard to find it'd be great to have it available right on that page.

**Comment by rikinsk** [comment]
Added under the ``Deploying`` main heading as it involves the deployment method
