### ISSUE TITLE
support insertion in both directions for one-to-one relationships

### ISSUE THREAD

**Issue by erichiller** [hasura/graphql-engine#5083]
With 1:1 ( Object ) relationships, it is impossible to insert nested (related) objects unless the root object being inserted contains the linking column (column with the foreign key).

This isn't a bug as I see this behavior is [documented](https://hasura.io/docs/1.0/graphql/manual/mutations/insert.html#insert-an-object-along-with-its-related-objects-through-relationships) - but it seems to be an unnecessary limitation.

For a concrete example:

Example Tables:

- `vendor`
   - `id`
   - `name`
   - `url`
   - `account_id`
- `manufacturer`
   - `id`
   - `name`
   - `url`
   - `vendor_id`  _# this links back to `vendor.id`_
   

```
mutation {
  insert_vendor_one ( object: {
    account_id: "my account",
    name: "test vendor",
    url: "http://myaccount.net",
    manufacturer: {
      data: {
        name: "test vendor-manufacturer"
        url: "my url"
      }
    }
  }) {
    returning {
      id
      account_id
      name
      url
      manufacturer {
        id
        name
        url
        vendor_id
      }
    }
  }
}
```

Will fail with the error:

    Not-NULL violation. null value in column \"id\" violates not-null constraint

If I change the relationship to be an array, it works fine. Here then I have to constantly do
_if length 1 ... [0]_ logic and then my GraphQL schema differs from the true logical schema.

```
mutation {
  insert_vendor ( objects: [{
    account_id: "my account",
    name: "test vendor",
    url: "http://myaccount.net",
    manufacturer: {
      data: [{
        name: "test vendor-manufacturer"
        url: "my url"
      }]
    }
  }]) {
    returning {
      id
      account_id
      name
      url
      manufacturer {
        id
        name
        url
        vendor_id
      }
    }
  }
}
```
returns:

```
{
  "data": {
    "insert_vendor": {
      "returning": [
        {
          "id": 118,
          "account_id": "my account",
          "name": "test vendor",
          "url": "http://myaccount.net",
          "manufacturer": [
            {
              "id": 119,
              "name": "test vendor-manufacturer",
              "url": "my url",
              "vendor_id": 118
            }
          ]
        }
      ]
    }
  }
}
```

It would be very helpful to me, and I presume others to allow the object relationship mapping column to be on either side of the one-to-one relationship.
So to use my example, I could `insert_vendor_one` and provide the `manufacturer` props and the vendor is inserted first, then its `vendor.id` inserted as `manufacturer.vendor_id`

**Comment by rikinsk** [comment]
Dup of #2576

**Comment by erichiller** [comment]
Yes, it appears that the author's issue is the same as mine, some of the later comments and potential fixes using different modifiers to the foreign key do not work however.

**Comment by vladciobanu** [comment]
It is indeed a duplicate, and the fix should land in master within a day or two.
