### ISSUE TITLE
Is there any way to use camel case in every generated type?

### ISSUE THREAD

**Issue by vinverdy** [hasura/graphql-engine#5085]
First of all, its a such a great project. Hope it will be greater in the future.

Although, there is [a way to custom query and field name](https://hasura.io/docs/1.0/graphql/manual/schema/custom-field-names.html). There still many underscore in the schema, such as on generated type (entity_insert_input, entity_set_input, entity_mutation_response, entity_select_column, etc). relay connection "table_connection", and query argument such as order_by, and distinct on.

Although, is it okay to use snake case for graphql naming, i just want to follow the [graphql unwritten convention](http://spec.graphql.org/June2018/#sec-Language.Variables) to use camel case in the schema.

Is there any way, to use camel case in every generated type? Thanks in advance

**Comment by rikinsk** [comment]
@vinverdy Not yet. The feature request is being tracked at #3320

**Comment by vinverdy** [comment]
oh okay, sorry I dont see that issue before
