### ISSUE TITLE
Better console UX in joining tables

### ISSUE THREAD

**Issue by Manubi** [hasura/graphql-engine#5086]
Hi, 
I have a lot of joining tables and it somehow annoys me that I can't click the field to get more information from that table like eg. postico does. 

Maybe something like that would be easier to implement. 
<img width="861" alt="Browse_-_vaccination_plan_user_-_Data___Hasura" src="https://user-images.githubusercontent.com/20935138/84596993-2429c780-ae61-11ea-9bee-d8ef15374fa4.png">

Or maybe if I hover over the ID I get the row of the foreign key...

**Comment by tirumaraiselvan** [comment]
Hmm, there is a way to get to the foreign row (the right side columns are all relationships):

![image](https://user-images.githubusercontent.com/8663570/84736603-cf529200-afc3-11ea-8056-00df13d862ba.png)

Did you mean something different?

**Comment by beerose** [comment]
@Manubi I'm closing this issue. Feel free to reopen if you meant something different than a functionality mentioned in the above comment.
