### ISSUE TITLE
PG pool can cause memory to never be freed on an active server

### ISSUE THREAD

**Issue by jberryman** [hasura/graphql-engine#5087]
libpq grows the buffers it uses for input and output, as needed,
exponentially, but it never shrinks them. This means that if we try to keep
connections open in a thread pool for as long as possible we should expect
RES to grow and grow as e.g. a new biggest result query comes in.

Keep in mind this is for _each connection_ in a pool of maybe hundreds, so a few megabytes here and there can add up. And it only takes one outlier huge result set to grow the buffer.

Here we can see libpq doubling the buffer as we expect:

![hasura-heaptrack](https://user-images.githubusercontent.com/210815/84600579-4b27cf80-ae48-11ea-87c7-807d4a9eacfe.png)

One proper solution is to simply shrink the buffers back down to some max
acceptable size after each transaction. User Ilya confirms they've been
using essentially this approach successfully in production since reporting
the first ticket below.

~Unfortunately it seems we can't simply create a binding and do this without vendoring postgres itself. So we'll first have a workaround and then see if we can do something more efficient.~
**EDIT**: actually it looks like we can, so long as we copy what `postgresql-libpq` does in their Setup.hs, and we depend on e.g. `postgresql-server-dev-9.6` (the version doesn't matter AFAICT)

See e.g. pqCheckInBufferSpace which is the source of the leak that we noticed:

  https://docs.huihoo.com/doxygen/postgresql/fe-misc_8c.html#ab9525b356ad08b90e9beb497203848f8 

References to others who have encountered this issue

  https://www.postgresql.org/message-id/15693-0df90da151425ff5@postgresql.org 
  https://groups.google.com/forum/#!topic/pgsql.general/DIA4g8mMzNM 

Linking: 
https://github.com/hasura/graphql-engine/issues/3388
https://github.com/hasura/graphql-engine/issues/4077

**Comment by jberryman** [comment]
A little graph showing libpq shrinking after big result sets. Here with only one connection, so we're clamping down to 1MB. In real life we'd probably expect to see something smoother since we'll have 50 or 100 connections and smaller result sets, maybe.

![new](https://user-images.githubusercontent.com/210815/86183881-fb602e00-bb00-11ea-8196-cb8e0cd3001e.png)

**Comment by jflambert** [comment]
@jberryman what kind of testing would you like me to do around `HASURA_GRAPHQL_PG_CONN_LIFETIME`? [I understand it's in seconds](https://github.com/jberryman/graphql-engine/commit/a97654271fab0a8ed24055b58340d9c9d1e7bd98), but is this an idle timeout or a full lifetime? Does a connection get killed even when busy?

Did you have time to check out my test environment for [Hasura memory leaks](https://github.com/jflambert/hasura-memory-consumption)? I will test with v1.3.0-beta.4 overnight.

**Comment by jberryman** [comment]
Hi @jflambert, dfa0701 arose from looking at your test environment and asking why it seemed memory was retained when we request huge results. The `HASURA_GRAPHQL_PG_CONN_LIFETIME` stuff was a workaround that happened to take long  enough to get merged that it went in with the libpq fix. 

We don't have a use-case for expiring active connections, but e.g. pgpool offers this knob, so presumably someone might be able to use it in the future.

The fact that you also report memory _growing_ over several hours may be another instance of an issue we're still tracking down.
