### ISSUE TITLE
[postgres] type float4 not correctly parsed for large numbers (rounded)

### ISSUE THREAD

**Issue by Toub** [hasura/graphql-engine#5092]
Hasura does not correctly retrieve value for Postgres `float4` large numbers (ex: 500000.5).

The value is rounded, instead of returning the real value.

However, if the postgres type is float8, no problem.

Is only `float8` type is supported?

The [documentation](https://hasura.io/docs/1.0/graphql/manual/api-reference/postgresql-types.html#float) mentions `float8`, but does not explicitly mention that `float4` is not supported.

**Comment by Toub** [comment]
https://github.com/hasura/graphql-engine/issues/5092

**Comment by abooij** [comment]
I can confirm that when a database column has type `float4` rather than `real`, a value of `500000.5` in the database is returned as `500000`, despite `500000.5` being representable exactly as an IEEE754 float.

**Comment by abooij** [comment]
As a workaround, it seems that upgrading to PostgreSQL 12 or later should fix this. The origin is that in PostgreSQL 11 and older, by default, floating point values are returned with a fixed decimal precision - in the case of `float4`, this is 6 digits. Using the option [`extra_float_digits`](https://www.postgresql.org/docs/11/runtime-config-client.html#GUC-EXTRA-FLOAT-DIGITS) (important: compare with the [v12 docs](https://www.postgresql.org/docs/12/runtime-config-client.html#GUC-EXTRA-FLOAT-DIGITS), which seems to claim some changed behavior alongside a change in the default value of `extra_float_digits`!), we can output the float with full precision. However, by default it is set to 0, which in this case means loss of precision. We should probably set `extra_float_digits` to 3 globally to avoid this problem. But this might introduce some platform dependent behavior, so we should make sure our CI test suite is resilient against this.

**Comment by Toub** [comment]
Thanks.
As a workaround, I used a `numeric` type (because `knex` used to create the schema on my project is not able to generate `float8`).

**Comment by abooij** [comment]
As a further workaround to this: by setting the `extra_float_digits` parameter to 3, one always gets the floats with sufficient precision. This parameter can be set through the database connection URL. For example, if the database is running on port 35432 on localhost, with username user, password pass, use the following URL:
```postgres://user:pass@127.0.0.1:35432/postgres?options=-c%20extra_float_digits%3D3```
Note that what we are passing for `options` is the URL encoding of `-c extra_float_digits=3`.
