### ISSUE TITLE
add a version command

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#51]
that just echos the server version

**Comment by praveenweb** [comment]
This is required for the console as well, to show update notifications for newer server versions.

**Comment by coco98** [comment]
@shahidhk @praveenweb chaps! Did this get done?

**Comment by shahidhk** [comment]
No, I can do this

**Comment by praveenweb** [comment]
console relies on the server's `/v1/version` endpoint to show update notifications. So just CLI changes to be done.

**Comment by shahidhk** [comment]
@0x777 This is not a CLI issue, but a server one. The proposed command is for the server binary:

```bash
# command
graphql-engine version
# output
v1.0.0-alpha14
```
