### ISSUE TITLE
cli-ext plugin not getting installed. Error: A required privilege is not held by the client."

### ISSUE THREAD

**Issue by ooxaam** [hasura/graphql-engine#5111]
I'm trying to install hasura plugin cli-ext, but getting following error:

```
C:\Users\umar.farooq>hasura plugins install cli-ext
time="2020-06-16T23:10:47+04:00" level=fatal msg="failed to install plugin \"cli
-ext\": install failed: failed to link installed plugin: failed to create a syml
ink from \"C:\\\\Users\\\\umar.farooq\\\\.hasura\\\\plugins\\\\store\\\\cli-ext\
\\\v1.3.0-beta.1\\\\cli-ext-hasura-win.exe\" to \"C:\\\\Users\\\\umar.farooq\\\\
.hasura\\\\plugins\\\\bin\\\\hasura-cli_ext.exe\": symlink C:\\Users\\umar.faroo
q\\.hasura\\plugins\\store\\cli-ext\\v1.3.0-beta.1\\cli-ext-hasura-win.exe C:\\U
sers\\umar.farooq\\.hasura\\plugins\\bin\\hasura-cli_ext.exe: A required privile
ge is not held by the client."
```
I have downloaded hasura cli exe from [here](https://github.com/hasura/graphql-engine/releases )

Now I'm simply running following command:
`hasura plugins install cli-ext`

**Comment by scriptonist** [comment]
Hey 👋 I think you found a solution here: https://stackoverflow.com/questions/62397595/hasura-migration-failed-required-privilege-is-not-held-by-client/
As you suggested, we are exploring how to document this better / tweak things for a better DX.
