### ISSUE TITLE
pg connection max lifetime?

### ISSUE THREAD

**Issue by domasx2** [hasura/graphql-engine#5123]
Hi,

There a way to specify max lifetime of a pooled connection, so it's closed after X seconds and a new one is opened?

Thanks

**Comment by tirumaraiselvan** [comment]
Please see `HASURA_GRAPHQL_PG_TIMEOUT` : https://hasura.io/docs/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html#id1

**Comment by domasx2** [comment]
Hi, thanks for reply. This is idle timeout, but I mean forcing recycle even if connection hasn't been idle for X seconds

**Comment by jberryman** [comment]
@domasx2 We've implemented this as essentially a bug fix, awaiting review. See https://github.com/hasura/graphql-engine/issues/5087 and attached PRs

At the moment it works like this: when a thread takes a connection from the pool, if it is older than 60sec it will be destroyed. This can (probably should) be made configurable. Note the idle timeout still comes into play. Setting it to 60s would ensure connections are always closed approximately every 60 sec

**Comment by 0x777** [comment]
@domasx2 Any reason why you would want to do this? As @jberryman pointed out, we might add this as a workaround for a leak that we discovered in libpq but not as a feature.

**Comment by domasx2** [comment]
Hey,
My mistake. I misunderstood our pgpool config, don't need it after all. Sorry, and thanks for the replies!
