### ISSUE TITLE
hasura migrate apply fails

### ISSUE THREAD

**Issue by MohiuddinM** [hasura/graphql-engine#5128]
I want to apply migrations to a new instance of hasura, running inside a docker container. But whenever I try to apply migrations it give the following error:
`function \"asbinary\" already exists with same argument types"`

```
 hasura migrate apply --admin-secret xyz
time="2020-06-17T18:55:42+02:00" level=fatal msg="apply failed: [postgres-error] query execution failed ($.args[0].args)\r\nFile: '1590428313337_init\\up.sql'\r\n{\n    \"check_metadata_consistency\": false,\n    

/* LOT OF OTHER STUFF HERE */

FatalError: function \"asbinary\" already exists with same argument types"
```

**Comment by scriptonist** [comment]
Hey @MohiuddinM, you are trying to apply migrations to a fresh instance of Hasura right? can you clarify the following two things for me, please
- Is the config file is updated with the new endpoint?
- Are we using fresh Postgres as well?

**Comment by MohiuddinM** [comment]
@scriptonist Actually I have identified the problem. The problem is that my postgres is also running postgis (which is preinstalled). And hasura migration also tracks postgis stuff, and hence tries to recreate them. I manually have to remove all the postgis stuff from "up.sql" of the migration file, and then everything works!

**Comment by MohiuddinM** [comment]
the `asbinary` function is part of postgis

**Comment by jeanpul** [comment]
Hi,
To avoid these erros, is it possible to use CREATE OR REPLACE instead of CREATE ?
