### ISSUE TITLE
cli: don't require config.yaml

### ISSUE THREAD

**Issue by silky** [hasura/graphql-engine#5142]
related to https://github.com/hasura/graphql-engine/issues/4561

there should be no reason to _require_ a config.yaml, given that all the arguments can be configured in other ways

for example, if i define everything via env-vars, then when i run `hasura ...` i get the following error:

```
FATA[0001] validating current directory failed: validate: cannot find [config.yaml] | search stopped: filesystem boundary hit 
```

```
> hasura version
INFO hasura cli                                    version=v1.2.2
```

**Comment by silky** [comment]
( also related - https://github.com/hasura/graphql-engine/pull/4765 & https://github.com/hasura/graphql-engine/pull/4668 )

**Comment by scriptonist** [comment]
Thanks for the feedback @silky, since we are tracking this in the above-mentioned issues and is a WIP I'm closing this issue in favour of those.
