### ISSUE TITLE
`hasura version` should print version instead of logging it

### ISSUE THREAD

**Issue by leos** [hasura/graphql-engine#5146]
Repro steps:
1. Run `hasura version`

Expected result:
`1.2.2` - Just the version string

Actual result:
`INFO hasura cli                                    version=v1.2.2`

This is problematic since it makes it hard to use the command from other scripts and tools to identify the CLI version. They're unable to easily (and shouldn't have to) parse the go logging format output string.

There's a secondary problem which is the auto-update notification can interfere with this output too but there's at least config ways around that.

**Comment by darkmtr** [comment]
can i take this up?

**Comment by scriptonist** [comment]
Sure @darkmtr go for it!

**Comment by scriptonist** [comment]
`hasura version | jq ".version" `  can satisfy this use case.
