### ISSUE TITLE
add a reset metadata button on console

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#515]
This would be under settings page, below import/export.

**Comment by praveenweb** [comment]
@shahidhk - Yeah reload metadata is to refresh the cache. Reset metadata is to remove all metadata and start from scratch.

**Comment by dsandip** [comment]
title (for the subsection): `Reset Metadata`
Tagline: Permanently clear GraphQL Engine's metadata and configure it from scratch (*tracking relevant tables and relationships*). This process is not reversible.
Button label: `Reset`
@paranoidsp @praveenweb: We should have a confirmation step ala Github (when deleting a  repo) when you click on the reset button.
Pop-up title: `Are you absolutely sure?`
Pop-up text: `This action cannot be undone. This will permanently reset GraphQL Engine's configuration and you will need to start from scratch. Please type "RESET" to confirm.`
Button label: `I understand the consequences, reset Metadata` (button gets enabled if the entered text matches "RESET")

**Comment by dsandip** [comment]
@paranoidsp : reference design:

![screen shot 2018-10-08 at 3 25 45 pm](https://user-images.githubusercontent.com/24300818/46602673-748a4700-cb0e-11e8-9be2-8e24f127c081.png)

**Comment by paranoidsp** [comment]
@dsandip Added a default confirmation dialog, everything except the button text is the same. Styling is browser default. @karthikvt26 Check if it looks okay?
