### ISSUE TITLE
console: filter incompatible postgres functions from computed fields drop down

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#5155]
Only functions which have an argument which is of row type of the selected table are valid.

![Menu_400](https://user-images.githubusercontent.com/8663570/85203488-d06d2180-b32b-11ea-8059-23d5e6615997.png)

**Comment by rikinsk** [comment]
Full requirements for supported functiona are mentioned [here](https://hasura.io/docs/1.0/graphql/manual/schema/computed-fields.html#supported-sql-functions)

**Comment by GrizliK1988** [comment]
Hi!

@beerose , can I take this one?

Proposed solution: adjust a payload in console to send a WHERE statement

```sql
WHERE "input_arg_types"::jsonb @> '[{"schema":"table_schema","name":"table_name"}]'::jsonb
```

**Comment by GrizliK1988** [comment]
Hi!

PR is ready :)
