### ISSUE TITLE
[v1.3.0-beta.2] Renaming Cron Trigger crashes Hasura console

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#5160]
1. create a cron trigger
2. attempt to rename it
3. type RENAME
4. Hasura console "crashes" -- it goes to a 404 really

The problem is that the redirect URL is still the old cron trigger name instead of the new one.

BONUS:
1. click "Home" on the 404 page
2. click "EVENTS" tab
3. another wonderful 404

**Comment by beerose** [comment]
Solved by https://github.com/hasura/graphql-engine/pull/5167

**Comment by jflambert** [comment]
@beerose is there already an issue for preserving Hasura's state when changing tabs in hasura? Are you the right person to talk to about this?

1. click "events"
2. click "new" type in some stuff..
3. click any other tab like "data" or "graphiql"
4. go back to "events" -> have to redo everything.

**Comment by beerose** [comment]
@jflambert 
No, we don't have any issue for that. Currently, changes that are done, for example, in `add event` tab are stored in local state and therefore cleared on component unmount.

**Comment by jflambert** [comment]
@beerose I tested your fix. works great. Thanks!
