### ISSUE TITLE
Invalid breadcrumb and tab title for "Data Triggers"

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#5162]
The tab and breadcrumb should read "Data Triggers" instead of "Events" and "Data Events" respectively.

![image](https://user-images.githubusercontent.com/11539524/85243197-2bc41000-b40f-11ea-8dc8-3d9ef4473c2d.png)

**Comment by beerose** [comment]
Solved in https://github.com/hasura/graphql-engine/pull/5427
