### ISSUE TITLE
[v1.3.0-beta.2] Cannot upgrade from v1.2.x.cli-migrations-v2

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#5163]
`1.3.0-beta.2` now expects `metadata/cron_triggers.yaml`, but this file didn't exist in 1.2.x

I recommend treating it as empty if it doesn't exist otherwise you'll have a bunch of folks who can't upgrade until they manually create the missing file with `[]` inside.

`time="2020-06-22T02:08:06Z" level=fatal msg="failed to apply metadata: cannot apply metadata on the database: cannot build cron_triggers from metadata: open /tmp/hasura-project/metadata/cron_triggers.yaml: no such file or directory"`

**Comment by scriptonist** [comment]
Hey @jflambert , that's concerning. Just wanted to gather a bit more info.
1. You upgraded your server to `v1.3.0-beta.2`
2. You tried applying metadata (`v1.2.2`) and it failed 

right?

If yes, can you after step 1, do a `metadata export` and then move to step 2 and see if you encounter the same error?

**Comment by jflambert** [comment]
1. Just spin up a docker-compose project with `v1.2.2.cli-migrations-v2`
2. hasura md export
3. bind metadata volume
4. `docker-compose up`, confirm metadata gets applied in logs, `docker-compose down -v`
5. Change hasura to `v1.3.0-beta.2.cli-migrations-v2`
6. docker-compose up, it'll crash because `cron_triggers.yaml` does not exist

**Comment by scriptonist** [comment]
Thanks @jflambert, got it. Will address this ASAP

**Comment by ItsWendell** [comment]
A quick fix that worked for me is creating an empty `cron_triggers.yaml` file with `[]` as content!

**Comment by jflambert** [comment]
Confirmed this works for me in 1.3.0-beta.3, thanks @scriptonist 

Only issue is I don't see your message "metadata file for %s was not found, assuming an empty file" appearing, that must be due to my log level being inadequate?

**Comment by scriptonist** [comment]
@jflambert cool, the `--log-level` should  be `debug` for that to appear.
