### ISSUE TITLE
console contributing guide is not clear about what env vars to set

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#517]
If I am trying to get console working locally, it is not clear which env vars I should be setting in `.env`

The current instructions assumes a lot of background knowledge and is confusing specifically around `DATA_API_URL` `DEV_DATA_API_URL` and some references to CLI. 

We need to make this crystal clear for someone who only knows GraphQL engine endpoint.

**Comment by karthikvt26** [comment]
I worked on a new draft for CONTRIBUTING.md. Will publish it by today.
