### ISSUE TITLE
Will Hasura ever work on Docker for the new upcoming ARM Macs?

### ISSUE THREAD

**Issue by joshuarobs** [hasura/graphql-engine#5179]
Given Apple's announcement of their new ARM Macs, will Hasura ever work on Docker on an arm architecture?

Also, would this experimental feature of Docker, `Buildx` make making an arm version of Hasura more feasable?

https://docs.docker.com/docker-for-mac/multi-arch/

**Comment by wwwdepot** [comment]
See #1266

**Comment by tirumaraiselvan** [comment]
I am closing this in favour of #1266
