### ISSUE TITLE
Automatically accept both camel and snake cased queries

### ISSUE THREAD

**Issue by karibertils** [hasura/graphql-engine#518]
It's common for databases to use snake_cased tables, while javascript has a strong convention for camelCase.

It would be nice if Hasura could accommodate both conventions.

For example queries for snake_cased_table could be queried with both styles:

```
snakeCasedTable {
  id
  myTitle
}

snake_cased_table {
  id
  my_title
}
```

Only one of those would be visible in the schema while the system would automatically accept both forms.

**Comment by dsandip** [comment]
@karibertils Closing this in favor of #981 (*will tag you there so you can subscribe to issue updates*)
