### ISSUE TITLE
Add New Action crashes console

### ISSUE THREAD

**Issue by tpoisson805** [hasura/graphql-engine#5188]
Go to the Actions tabs and click "Create".  Clearing all boilerplate code in "Action definition" box crashes console.
Back button does not resolve.

Deleting only one line instead triggers validation warning but doesn't crash.

Suggestions:
Increase debounce on user input.
Remove validation checking for NULL input until submit.

_Stack:
Hasura v1.3.0-beta.2
Postgres 12
PG Admin 4
Docker Container running localhost dev env on Windows 10_

**Comment by rikinsk** [comment]
@tpoisson805 I was not able to reproduce this. Can you share the error that is shown or a screenshot of the console when it crashes?

**Comment by tpoisson805** [comment]
Can't seem to reproduce it now myself.  Apologies, must have been an unidentified issue on my end.

**Comment by tpoisson805** [comment]
Misidentified bug.  Unable to reproduce

**Comment by rikinsk** [comment]
@tpoisson805 Thats too bad. The fact that it had crashed for you ever seems to indicate some missed edge case handling. Do let us know if this happens again.

**Comment by tpoisson805** [comment]
@rikinsk I was working on a new project with a new database.  May have been a provisioning issue/conflict while spinning up the db and I went straight in to writing Actions before Hasura could fully connect.  I suppose this could be an edge case because who would ever start writing functions before their db is instantiated?
