### ISSUE TITLE
migrations fail due to creating functions before tables 

### ISSUE THREAD

**Issue by Maxhodges** [hasura/graphql-engine#5194]
our migrations fail because the up.sql tries to create a function before the table references. here's the first couple dozens lines from our up.sql

`[42P01] FatalError: relation "order_items" does not exist`

clearly this function shouldn't be created before `order_items` exists. Is there anyway to manage this?

```
CREATE TABLE public.orders (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    customer_id uuid NOT NULL,
    shop text NOT NULL,
    created_at timestamp(6) with time zone DEFAULT now() NOT NULL,
    service_fees_id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    total_fees_usd integer NOT NULL,
    status text DEFAULT 'OPEN'::text,
    payment_method_id uuid NOT NULL,
    refunded boolean DEFAULT false,
    amount_approved_usd integer DEFAULT 0 NOT NULL
);
COMMENT ON COLUMN public.orders.shop IS 'Shop domain';
COMMENT ON COLUMN public.orders.refunded IS 'Fully refunded';
CREATE FUNCTION public.calculate_order_grand_total_usd(orders_row public.orders) RETURNS integer
    LANGUAGE sql STABLE
    AS $$
   SELECT
  (
    SUM(oi.total_price_usd) + SUM(e.amount_usd) + sum(d.amount_usd * -1) + o.total_fees_usd
  ) :: INTEGER
FROM
  orders o
  left outer join order_items oi on oi.order_id = o.id
  left outer join expenses e on o.id = e.order_id
  left outer join discounts d on d.order_id = o.id
WHERE
  o.id = orders_row.id AND oi.status != 'CANCELED'
GROUP BY
  o.id;
  $$;
```

**Comment by tirumaraiselvan** [comment]
@Maxhodges Could you give the error that is reported when you apply your migration?

**Comment by Maxhodges** [comment]
`[42P01] FatalError: relation "order_items" does not exist

`

**Comment by tirumaraiselvan** [comment]
@Maxhodges I don't see "order_items" table in the migration you posted. Could you paste the entire migration?

**Comment by Maxhodges** [comment]
to get it to run we have to manually comment out four functions. which prevents us from doing these things using automation

**Comment by tirumaraiselvan** [comment]
@Maxhodges What's the new error?

**Comment by tirumaraiselvan** [comment]
@Maxhodges Your new migration above references "order_items" table in the function but I can't see the table being created in the migration. Not sure how it is being created. Is it part of your migration file?

**Comment by Maxhodges** [comment]
right, the table gets created later. 

I guess hasura is calling Heroku's pg_restore and Heroku's restore is checking functions. 

Is there no way to use this flag to stop checking?

https://stackoverflow.com/questions/56729192/pg-restore-fails-when-trying-to-create-function-referencing-table-that-does-not

**Comment by tirumaraiselvan** [comment]
Hasura doesn't call Heroku's pg_restore. 

Ideally, "order_items" should be part of your migrations. Or if you have some other mechanism of creating the table, it should be created before calling your migration.

**Comment by seifip** [comment]
Hasura should add `SET check_function_bodies=false` at the top of the SQL migration file to stop Postgres from checking function bodies by default.

**Comment by Maxhodges** [comment]
Oh I see! yup that works! thank you @seifip 

https://media.giphy.com/media/yv3OeSujDzSDDM2Vxm/giphy.gif

**Comment by tirumaraiselvan** [comment]
Hey fellows

After trying to reproduce this locally, it appears that the migration was created using `--from-server` flag which creates an initial migration. Indeed it should have few `SET` statements to comply with proper pg_dump response (which is unordered and hence leads to such validation failures). I have created a more specific issue here: https://github.com/hasura/graphql-engine/issues/5198

Thanks for the report.

**Comment by tirumaraiselvan** [comment]
Closing as tracked in #5198
