### ISSUE TITLE
console: distinguish enum tables from non enum tables

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#5196]
In the table listing, just like functions, views and tables are shown differently, it would be nice if there's an indication about a table being enum.

**Comment by beerose** [comment]
This was done recently: https://github.com/hasura/graphql-engine/pull/4992
<img width="376" alt="Screenshot 2020-06-24 at 12 31 26" src="https://user-images.githubusercontent.com/9019397/85539891-a14dfd00-b616-11ea-95ea-145250c0b251.png">

**Comment by wawhal** [comment]
Dupe https://github.com/hasura/graphql-engine/issues/4984.
