### ISSUE TITLE
Introspection is failing for non-admin roles for enum types

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#5200]
By @wawhal 

Introspection is failing for me in graphiql when I set header `x-hasura-role: user` along with admin secret. `{"errors":[{"extensions":{"path":"$","code":"unexpected"},"message":"type info not found for: 'cloud_enum'"}]} `.

It's version `v1.2.1`

**Reproduction:** by @karthikvt26 
Basically what is happening is I have a table called `cloud` which is an `enum` and I am referencing that table from `region` and giving user to fetch only `name` from it and not the `enum` field in `region` table which is the FK to `cloud` table. If you give permission for user to fetch the `enum` column in `region` table it works.

**Comment by tirumaraiselvan** [comment]
Here is a sample metadata:

```
{
  "version": 2,
  "tables": [
    {
      "table": {
        "schema": "public",
        "name": "author"
      },
      "select_permissions": [
        {
          "role": "user",
          "permission": {
            "columns": [
              "id",
              "name"
            ],
            "filter": {
              "id": {
                "_eq": "X-Hasura-User-Id"
              }
            }
          }
        }
      ]
    },
    {
      "table": {
        "schema": "public",
        "name": "cloud"
      },
      "is_enum": true
    },
    {
      "table": {
        "schema": "public",
        "name": "region"
      },
      "select_permissions": [
        {
          "role": "user",
          "permission": {
            "columns": [
              "name"
            ],
            "filter": {}
          }
        }
      ]
    }
  ]
}
```

**Comment by jflambert** [comment]
@tirumaraiselvan is this possibly broken again in 2.4.0?

I'm having this issue where admin roles can fully access all enumValues of an enum through introspection

Adding new values to the enum? admin sees them right away.

but a non-admin role... seems to be limited to a cached subset. I'm going to try to restart hasura, postgres and a few other things.

**Comment by tirumaraiselvan** [comment]
@jflambert Is it possible to open a new issue with a small reproduction pls?
