### ISSUE TITLE
Consolidate handler/webbook urls and env variables use

### ISSUE THREAD

**Issue by FredyC** [hasura/graphql-engine#5203]
Currently, each part of the UI has a different way to define an URL. It would nice if all these could be consolidated and offer the same approach to work with env variables. I am sure there are some technical reasons, but can we discuss it here?

## Actions
In my opinion, actions are handled best with the ability to use env variable as part of the string which allows us to distinguish if necessary.

![image](https://user-images.githubusercontent.com/1096340/85588285-da03cb80-b642-11ea-8e00-8085edef5303.png)

## Remote schema & Data triggers
Both are the same and kinda limited to a specific env variable.

![image](https://user-images.githubusercontent.com/1096340/85588344-e556f700-b642-11ea-96ad-cadd000a6dca.png)
![image](https://user-images.githubusercontent.com/1096340/85588400-f1db4f80-b642-11ea-8d4d-8b4325470e93.png)

**Cron triggers & One-off events**
These are exactly the same (thus single image) and the most limited approach that doesn't even allow for env variables.

![image](https://user-images.githubusercontent.com/1096340/85588449-fc95e480-b642-11ea-8615-63b0ffaccd09.png)

**Comment by arpitjacob** [comment]
I agree the way `env variable` work in `Actions` give the most flexibility it would really simplify things

**Comment by FredyC** [comment]
Oh, that's interesting. Out of curiosity, I tried to specify URL for cron trigger & one-off event like `{{ENV}}` and it actually worked 🎉 I guess an explanation note should be there as well.

As for the Remote schemas & Data triggers when trying to do the same validation for "URL" fails, so these are only two that are inconsistent in the end.

**Comment by tirumaraiselvan** [comment]
Closing this as it is tracked here: https://github.com/hasura/graphql-engine/issues/2483

This is will happen very soon.
