### ISSUE TITLE
How to set glogal limit to rows for all tables and views?

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [hasura/graphql-engine#5216]
How to set glogal limit to rows for all tables and views?

Its must have feature. If it not exists, please mark this issue as [FEATURE_REQUEST]

**Comment by beerose** [comment]
@MaxmaxmaximusGitHub You can select a value from a dropdown on `Browse Rows` page. It will be persisted in local storage for **all** tables and views. Hence it is some kind of a _global limit_. 
<img width="334" alt="Screenshot 2020-07-13 at 11 25 35" src="https://user-images.githubusercontent.com/9019397/87288398-942c7b80-c4fb-11ea-956a-6a695cb07a5a.png">
<img width="118" alt="Screenshot 2020-07-13 at 11 25 45" src="https://user-images.githubusercontent.com/9019397/87288419-9b538980-c4fb-11ea-80b7-b1de947032ba.png">

I'm closing this issue. If you had something else in mind, feel free to reopen.
