### ISSUE TITLE
GraphQL error: the required argument {pk} is missing if there are two PKs in the table

### ISSUE THREAD

**Issue by ghyath5** [hasura/graphql-engine#5224]
If there are two or more primary keys in the table, can't delete row by primary key unless I specify the two primary keys at the same time

**Comment by rikinsk** [comment]
@ghyath5 You cannot have 2 independent primary keys for a table. I believe what you must be having is a composite primary key that consists of 2 columns. eg. for a table `article_review(article_id, user_id, review_text)`, the combination `(article_id, user_id)` will be the composite primary key that uniquely identifies each row and hence both need to be passed to delete a specific row.

**Comment by ghyath5** [comment]
@rikinsk 
Oh yes understand!!!!
Thank you for your answer.
