### ISSUE TITLE
set event trigger webhook headers from console

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#523]
refer https://github.com/hasura/graphql-engine/pull/419#issuecomment-423948293 for the API

**Comment by rikinsk** [comment]
Seems great @dsandip. A couple of additions from my end:
- Change ``Advanced - Operation/Columns`` to ``Payload columns``
- Remove checkbox for operations in the ``Payload columns`` section. If the operation is not selected in the ``Operations`` section above, just gray out the operation and columns. Currently two ways to modify the same data makes it confusing.
- Make the order of the Advanced features as ``Retry logic`` -> ``Headers`` -> ``Payload columns``. Just my preference based on what I feel I would use most.

**Comment by tirumaraiselvan** [comment]
Folks, the payload columns will actually become operation columns. We will
not have payload columns in UI anymore. Refer :
https://github.com/hasura/graphql-engine/issues/547

**Comment by dsandip** [comment]
@rikin @karthikvt26 : I've removed changes to the payload selection part of the UI based on Tiru's comment. We can just focus on the headers part in this issue.

**Comment by karthikvt26** [comment]
Fixed in #812
