### ISSUE TITLE
docs: document seed migrations as SQL files

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#5239]
We need to document the seed data facility with CLI as described here: https://github.com/hasura/graphql-engine/blob/master/CHANGELOG.md#manage-seed-migrations-as-sql-files.

**Comment by tirumaraiselvan** [comment]
https://hasura.io/docs/1.0/graphql/manual/migrations/advanced/seed-data-migration.html#seed-data-migration

**Comment by GavinRay97** [comment]
I have questions around this too -- the docs for using migrations as seed data work great, but when using the new CLI `hasura seeds create <name>`, it puts the seed in `/seeds/<timestamp>_<name>.sql`.

Looking through the release notes it doesn't mention the seeds get run automatically with the `.cli-migrations` images.

Is the best way to do this then to tweak the Dockerfile?
```dockerfile
FROM hasura/graphql-engine:v1.3.0-beta.4.cli-migrations-v2
COPY migrations /hasura-migrations
COPY metadata /hasura-metadata
RUN hasura seeds apply
```

Maybe we can have the functionality (or a flag maybe) to auto-run the seeds with the `.cli-migrations` image in the future.

**Comment by joshuarobs** [comment]
@GavinRay97 Any updates as to whether hasura seeds auto-runs with the `.cli-migrations` image version of Hasura as you suggested? This seeds functionality seems promising, but seems like it'll only work for playing around manually locally, and that it's entirely useless for CI/CD

**Comment by marionschleifer** [comment]
The work to document these commands has been done here: https://github.com/hasura/graphql-engine/pull/5565. @GavinRay97 please open a new issue if something on the Dockerfile needs to be done 🙂
