### ISSUE TITLE
set/show index of table columns

### ISSUE THREAD

**Issue by dohomi** [hasura/graphql-engine#5247]
Hey Guys,
I recently bumped into a performance issue while ordering a large dataset based on a date field without an index. After setting it through SQL everything was fine, but I think this very important and crucial part should be covered through the Hasura `console`. 
It would be great if CRUD of table columns would be part of the UI. As far as I see only combined index can be set (for `mn` relational tables) but not for example a date or email column.
Thanks for taking this idea into account.

**Comment by tirumaraiselvan** [comment]
I am closing this in favour of #2219
