### ISSUE TITLE
Cron trigger is sending only custom portion of payload

### ISSUE THREAD

**Issue by FredyC** [hasura/graphql-engine#5253]
## Actual behavior

This is what I see in the console for invocations.

![image](https://user-images.githubusercontent.com/1096340/86241119-a83eb780-bba2-11ea-949a-08f27e2ea72b.png)

And this is what I receive in my ngrok tunnel.

![image](https://user-images.githubusercontent.com/1096340/86241227-d623fc00-bba2-11ea-81cf-51bb2494b4ad.png)

## Expected behavior

Full `payload` should be sent including ID of invocation and the name.

**Comment by tirumaraiselvan** [comment]
This is weird. Is ngrok saying that the body of the webhook request is `{}` ? But can you log the body inside your webhook and see it's contents?

**Comment by FredyC** [comment]
I don't follow. There isn't anything between Hasura and ngrok that would change the payload. I can confirm that I can see the same in the webhook code.

My guess would be that due to `payload.payload` nesting, there might be some oversight in what is actually sent.

**Comment by FredyC** [comment]
Btw, I don't need ngrok to reproduce this, you can try with httpbin.org ... 

![image](https://user-images.githubusercontent.com/1096340/86272307-a5f25280-bbce-11ea-9073-ce4839e6013a.png)

![image](https://user-images.githubusercontent.com/1096340/86272418-d20dd380-bbce-11ea-8f43-765ebf63288a.png)

**Comment by tirumaraiselvan** [comment]
@FredyC Okay, now I understand. Thanks for reporting.
