### ISSUE TITLE
Enableto build  from source with Cabal

### ISSUE THREAD

**Issue by djalillounis** [hasura/graphql-engine#5259]
Hello,

I am having some  issue when I try to  build from  source using cabal.

I have this error Could not resolve dependencies:

cabal: Could not resolve dependencies:
[__0] trying: ci-info-0.1.0.0 (user goal)
[__1] next goal: base (dependency of ci-info)
[__1] rejecting: base-4.12.0.0/installed-4.12.0.0 (constraint from project
config TODO requires ==4.14.0.0)
[__1] rejecting: base-4.14.0.0 (constraint from non-upgradeable package
requires installed instance)
[__1] rejecting: base-4.13.0.0, base-4.12.0.0, base-4.11.1.0, base-4.11.0.0,
base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0,
base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0,
base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0,
base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1,
base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1
(constraint from project config TODO requires ==4.14.0.0)
[__1] fail (backjumping, conflict set: base, ci-info)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, ci-info

**Comment by tirumaraiselvan** [comment]
I think you have an older version of GHC (recently upgraded). You will need GHC 8.10.1.

**Comment by tirumaraiselvan** [comment]
Will be fixed in https://github.com/hasura/graphql-engine/pull/5377/files

**Comment by tirumaraiselvan** [comment]
Fixed in #5377
