### ISSUE TITLE
Allow relationships between tables in different schemas

### ISSUE THREAD

**Issue by ReneePhillips** [hasura/graphql-engine#526]
Currently there is a limitation when creating relationships such that only tables within the same schema may be selected in the relationship tool. 

We have several schemas and tables in various schemas are related by primary key/foreign key to tables outside their schema. Our dev team has been able to force this through our database, but we would prefer to also be able to do it through the UI.

**Comment by karthikvt26** [comment]
@ReneePhillips We will add this as soon as we can. For the time being, there is an API which can be used to achieve the same

The following query will create an array relationship or an object relationship from table `article` in schema `schema2` to `author` table in schema `public` using the column mapping (article_id -> id).

```bash
{
	"type": "create_array_relationship", // "type": "create_object_relationship"
	"args": {
		"name": "articlesAuthor",
		"table": { "name": "article", "schema": "schema2" },
		"using": {
			"manual_configuration": {
				"remote_table": {
					"name": "author",
					"schema": "public"
				},
				"column_mapping": {
					"author_id": "id"
				}
			}
		}
	}
}
```

Hope this solves the issue until we release this feature as part of the console itself.

**Comment by ReneePhillips** [comment]
Thanks! I’ll forward this to the team as well so we can all do this.

**Comment by pinale** [comment]
could i suggest to implement the crossschema relations creation even in the "track all" functionality? or at least don't stop the automatic generation in case of error on a specific relartion?
