### ISSUE TITLE
Add more code snippets to graphiql code exporter

### ISSUE THREAD

**Issue by beerose** [hasura/graphql-engine#5263]
We recently merged a [PR](https://github.com/hasura/graphql-engine/pull/4652/files) that adds `graphiql-code-exporter` to the console. Currently, we have default JavaScript snippets provided by the library and one custom [TypeScript snippet](https://github.com/hasura/graphql-engine/blob/master/console/src/components/Services/ApiExplorer/GraphiQLWrapper/snippets.ts). We can add more! Those snippets can be in different languages and using different solutions and libraries.

We'd love some help on this issue! 🙂 If you'd like to add language or framework, leave a comment below, so there's no overlapping work.

More information about adding custom snippets: https://github.com/OneGraph/graphiql-code-exporter#snippets

**Comment by Ishaan29** [comment]
can I work on this issue ?? @beerose

**Comment by beerose** [comment]
Go for it @Ishaan29!

**Comment by Ishaan29** [comment]
Thank you @beerose, working on it 👍 😄

**Comment by beerose** [comment]
Hi @Ishaan29! Any progress on this issue? Also, if you're still working on it can you let me know what languages or frameworks you want to add?

**Comment by fakhrip** [comment]
I would love to work on this issue @beerose , but can i know in which files do i have to add the code to ? (so its easier for me to look it up and not crawling through all the files), or should i look it up myself ?

**Comment by beerose** [comment]
Hi @fakhrip! You can take a look at this file: https://github.com/hasura/graphql-engine/blob/master/console/src/components/Services/ApiExplorer/GraphiQLWrapper/snippets.ts. We're creating there a TypeScript snippet. There are also a few utility functions to extract information from the query. You can add new snippets in this file, or you could declare a new snippet in a new file — as you wish. 
These snippets are then used in https://github.com/hasura/graphql-engine/blob/master/console/src/components/Services/ApiExplorer/GraphiQLWrapper/GraphiQLWrapper.js#L247.

**Comment by fakhrip** [comment]
Nice, its looking good, im gonna add javascript using vue framework snippet

**Comment by fakhrip** [comment]
Hello again, its really cool that i can learn so many new things just by adding snippet (cause i'll travel on the code deeper), and i think i want to add dart using flutter as i will also want to use it for my own project.

Should i create a new PR for that or just combine it with current PR ?

**Comment by fakhrip** [comment]
I'm sorry to bother you :pray: but, any update on this ? @beerose

**Comment by beerose** [comment]
Hi @fakhrip! I'm sorry for the late reply. Regarding your PR — I'll try to review as soon as I can. And regarding Dart snippet — you can do as you feel will be better for you 🙂 From my point of view, both options work just fine.

**Comment by fakhrip** [comment]
Sure, its okay, thanks for the reply :smile:

**Comment by NoriSte** [comment]
Update: the Code Exporter plugin is unmaintained, we're analyzing its usage to decide if revamping and maintaining it or digging rid of it. In both cases, I close this PR for now.
