### ISSUE TITLE
Error during passport-js boilerplate installation

### ISSUE THREAD

**Issue by codenm007** [hasura/graphql-engine#5270]
`used-function]
 char ToCharVersion(Local<String> str) {
      ^~~~~~~~~~~~~
bcrypt_lib.target.mk:113: recipe for target 'Release/obj.target/bcrypt_lib/src/bcrypt_node.o' failed
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory '/root/graphql-engine/community/boilerplates/auth-webhooks/passport-js/node_modules/bcrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/graphql-engine/community/boilerplates/auth-webhooks/passport-js/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/root/graphql-engine/community/boilerplates/auth-webhooks/passport-js/node_modules/bcrypt/lib/binding" "--napi_version=6" "--node_abi_napi=napi"
gyp ERR! cwd /root/graphql-engine/community/boilerplates/auth-webhooks/passport-js/node_modules/bcrypt
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/graphql-engine/community/boilerplates/auth-webhooks/passport-js/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/root/graphql-engine/community/boilerplates/auth-webhooks/passport-js/node_modules/bcrypt/lib/binding --napi_version=6 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/graphql-engine/community/boilerplates/auth-webhooks/passport-js/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 4.4.0-18362-Microsoft
node-pre-gyp ERR! command "/usr/bin/node" "/root/graphql-engine/community/boilerplates/auth-webhooks/passport-js/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/graphql-engine/community/boilerplates/auth-webhooks/passport-js/node_modules/bcrypt
node-pre-gyp ERR! node -v v14.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.2
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/graphql-engine/community/boilerplates/auth-webhooks/passport-js/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/root/graphql-engine/community/boilerplates/auth-webhooks/passport-js/node_modules/bcrypt/lib/binding --napi_version=6 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-02T05_34_14_382Z-debug.log`

**Comment by tirumaraiselvan** [comment]
I suppose you are trying to setup `community/boilerplates/auth-webhooks/passport-js/` ?

**Comment by praveenweb** [comment]
@codenm007 - I see that you are using node version 14.x The `bcrypt` module used in this example is v3 which supports till Node 11. For Node 12 and later, we need to upgrade the `bcrypt` version to >=3.0.6. Here's the [version compatibility](https://github.com/kelektiv/node.bcrypt.js#version-compatibility).

You can downgrade your Node version to test this example or manually upgrade the bcrypt version in package.json to try this out till we create a PR to fix this.

**Comment by codenm007** [comment]
thanks for the help ..... I have solved this earlier with a new bcrypt
version.......thanks a lot for replying!!

**Comment by praveenweb** [comment]
Awesome! Closing this issue then :)
