### ISSUE TITLE
fix downgrade tests for CI

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#5273]
Currently, we have a test here: https://github.com/hasura/graphql-engine/blob/97b1155bf83bbed223c763c681b88abfac5521e0/server/src-test/Hasura/Server/MigrateSpec.hs#L97 which fails frequently in the following scenarios:

1. For PRs that are in queue, right after a new release (new tag)
2. When we deploy stuff to beta, stable branches.

Sometimes, it doesn't show this failure in PR but only during a release. E.g. this PR (https://github.com/hasura/graphql-engine/pull/5269) has a trivial console fix and the tests passed in PR but failed after stable merge (https://app.circleci.com/pipelines/github/hasura/graphql-engine/11989/workflows/7f47963d-0351-4aea-a094-8a1118e6dd1f). We should atleast get this test failure feedback in PR itself?

Overall, we need to make this test more robust.

**Comment by jberryman** [comment]
https://github.com/hasura/graphql-engine/pull/4424 was my last attempt
