### ISSUE TITLE
Extend backend_only permissions to all operation types

### ISSUE THREAD

**Issue by amille14** [hasura/graphql-engine#5275]
Currently the `backend_only` permission setting is only available for insert operations. I would like to see this permission setting extended to all other operations (select, update, delete).

I have a system where I use actions to perform validations before creating or updating any tables. As such, I don't want clients to be able to directly insert OR update OR delete (sometimes) without going through the actions, as allowing direct access would mean that a user can update data in a way that doesn't conform to the validation schema. The existing `backend_only` setting does exactly what I'm looking for, but it seems that it's only made available for inserts for some reason.

Currently I need to create and manage an entire separate "actions" or "backend" role for this purpose. Would be nice if I could have a single "user" role that uses the backend_only setting for any of the operation types.

**Comment by MarcusBondezan** [comment]
@coco98 Do you have any updates on this? It's really important for us too.

**Comment by tirumaraiselvan** [comment]
In `pg_create_insert_permission` , the permission is given as https://hasura.io/docs/latest/graphql/core/api-reference/syntax-defs/#insertpermission, we need to extend this for [pg_create_update_permission](https://hasura.io/docs/latest/graphql/core/api-reference/syntax-defs/#updatepermission) and [pg_create_delete_permission](https://hasura.io/docs/latest/graphql/core/api-reference/syntax-defs/#deletepermission).

**Comment by tirumaraiselvan** [comment]
Will be released in `v2.8.0-beta.1`
