### ISSUE TITLE
Subscription Action

### ISSUE THREAD

**Issue by jascodes** [hasura/graphql-engine#5285]
I want use IMAP in idle mode which allows to listen to incoming email from external email server which is compatible with IMAP(with idle mode).

Now it can be possible feature for hasura to allow to write actions which allow such Subscription actions over websockets.

Thx

**Comment by tirumaraiselvan** [comment]
I am not 100% sure what you mean. Could you describe the APIs that you expect?

BTW, Hasura actions has an async mode which lets you subscribe to your action: https://hasura.io/docs/1.0/graphql/manual/actions/async-actions.html#id1 . Is this related to what you want?

**Comment by jascodes** [comment]
@tirumaraiselvan Thx for getting back.
Tell me if I am mistaken; but async action you return some to subscription at some later time. But I want to return websocket stream. In my usecase I am listening to new emails on server-side. I want my client to subscribe to the email list. Emails that I am going to be listening with IMAP(IDLE MODE) protocol can be external services. I want to write an action which exposes stream of data and on graphql client I can subscribe to. For now I can write my own resolver with graphql server. And then with remote API maybe merge it with hasura.

**Comment by coco98** [comment]
Merging this with #6912!
