### ISSUE TITLE
 I can not create a migration from the console

### ISSUE THREAD

**Issue by alexkharech** [hasura/graphql-engine#5296]
Hasura engine `hasura/graphql-engine:v1.3.0-beta.4`
Hasura console `v1.3.0-beta.4`
Postgres: `PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1)`
Docker: `19.03.8`

When creating any migration, I get the following error
```json
{"code":"migration_mode_enabled","message":"Migration mode is enabled"}
```

**Comment by alexkharech** [comment]
The creating from Raw SQL in console
![image](https://user-images.githubusercontent.com/41755348/86516599-a9821580-be2a-11ea-8d06-91311177dbd3.png)

**Comment by oliverpool** [comment]
As a workaround, you can manually set the migration_mode to `false`with curl (taken from https://github.com/hasura/graphql-engine/issues/2290#issue-449298096)
```
curl -H 'Content-Type: application/json' -X PUT -d '{"name": "migration_mode", "value": "false"}' http://0.0.0.0:9693/apis/migrate/settings
```

**Comment by aaronhayes** [comment]
Seeing the same issue with Raw SQL migrations.
- Hasura does generate migrations when I make changes within the Data tab.
- Can successfully run the raw SQL without the migration 
- Can manually create a migration using the cli with the same sql `hasura migrate create migration_name --up-sql "YOUR VALID SQL GOES HERE"`
