### ISSUE TITLE
Migration directory names documentation wrong

### ISSUE THREAD

**Issue by dan-lee** [hasura/graphql-engine#5297]
> Docker engine: 19.03.12
> Docker image: hasura/graphql-engine:v1.3.0-beta.4.cli-migrations-v2

The [documentation for migrations suggests to use](https://hasura.io/docs/1.0/graphql/manual/hasura-cli/config-reference.html#environment-variables):

```
HASURA_GRAPHQL_METADATA_DIRECTORY: /path/to/metadata
HASURA_GRAPHQL_MIGRATIONS_DIRECTORY: /path/to/migrations
```

But when executing it with these env vars I get:

> graphql-engine_1  | time="2020-07-04T20:26:24Z" level=fatal msg="failed to apply metadata: cannot apply metadata on the database: [parse-failed] key \"tables\" not found ($[1])"

After a few hours of digging, I found out that the reason is that the env var names are actually prefixed with `_DIR` instead of `_DIRECTORY`:

https://github.com/hasura/graphql-engine/blob/1e5e7d93dd29a5323918090bff567f3b0afc1417/scripts/cli-migrations/v2/docker-entrypoint.sh#L71-L73

https://github.com/hasura/graphql-engine/blob/1e5e7d93dd29a5323918090bff567f3b0afc1417/scripts/cli-migrations/v2/docker-entrypoint.sh#L90-L99

Now my docker container boots up without a problem.
Just wanted to report this issue, I don't know if the problem is just outdated documentation or something else.

**Comment by scriptonist** [comment]
@dan-lee The documentation for `cli-migrations-v2` image can be found here: https://hasura.io/docs/1.0/graphql/manual/migrations/advanced/auto-apply-migrations.html#applying-migrations, which mentions the Environment variables to use. 

But I understand this has created some confusion. Will be exploring how to improve it.

**Comment by dan-lee** [comment]
@scriptonist Aah I see, thanks for the link. Didn't see these docs right away.

My suggestion would be to maybe either sync these environment variables or have a more descriptive error message. The former, of course, could have some side effects I am not aware of.
