### ISSUE TITLE
When there is a "dot" in column name, table will not render within Console

### ISSUE THREAD

**Issue by kim8080** [hasura/graphql-engine#5302]
One of my column names contained "internal_2.5_" in its name. Noticed it would throw a React error #152. Replaced "2.5" with "2_5" and all worked OK. 

It appears it does not like a dot in the column name.

Using v.1.2.2 via Docker.

**Comment by hgiasac** [comment]
@kim8080 In best practice we shouldn't use special characters in column and table names except underscore `_` and `$`. Postgres official docs also mention about the rule:
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

> SQL identifiers and key words must begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) or an underscore (_). Subsequent characters in an identifier or key word can be letters, underscores, digits (0-9), or dollar signs ($). Note that dollar signs are not allowed in identifiers according to the letter of the SQL standard, so their use might render applications less portable. The SQL standard will not define a key word that contains digits or starts or ends with an underscore, so identifiers of this form are safe against possible conflict with future extensions of the standard.
>
> The system uses no more than NAMEDATALEN-1 bytes of an identifier; longer names can be written in commands, but they will be truncated. By default, NAMEDATALEN is 64 so the maximum identifier length is 63 bytes. If this limit is problematic, it can be raised by changing the NAMEDATALEN constant in src/include/pg_config_manual.h.

Dot `.` in table name or column name will mislead to schema prefix, and you should use bad words (SQL syntax) as name too

**Comment by praveenweb** [comment]
Adding to @hgiasac comment, [GraphQL spec](https://spec.graphql.org/June2018/#sec-Names) also only allows certain special characters and "dot" doesn't seem to be one of them.

Closing this issue.
