### ISSUE TITLE
[Feature Request] Multiple conflict constraints

### ISSUE THREAD

**Issue by kldzj** [hasura/graphql-engine#5309]
I really hope I am not just missing it, but I couldn't find anything regarding this in the docs or issues.

Currently I'm fighting with this issue, where sometimes multiple violations block me from running mutations (successfully). I'm thinking it would be very useful if Hasura's graphql-engine allowed to specify either multiple on_conflict conditions or constraints.

What'd be a nice to have:
```graphql
mutation {
    insert_test_one(object: { ... }, on_conflict: [
        { constraint: test_someId_key, update_columns: [a, b, c] },
        { constraint: test_user_key, update_columns: [c, d, e] }
    ]) {
        id
    }
}
```

Another way it could work for me, but would offer less flexibility in general is having the constraint as an array:
```graphql
mutation {
    insert_test_one(object: { ... }, on_conflict: { constraint: [test_someId_key, test_user_key], update_columns: [a, b, c, d, e] }) {
        id
    }
}
```

Is there a reason why having multiple conflict constraints would not work?

**Comment by kldzj** [comment]
Seems to be a duplicate of #4163

**Comment by tirumaraiselvan** [comment]
Yes @kldzj . Closing this in favour of #4163
