### ISSUE TITLE
[Feature request]: Conditional Event Trigger

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#5322]
Currently, you can't prevent event trigger to be run by using some conditionals (based on table data, or with environment variables).
As a result, the trigger endpoint must returns a dummy 2xx value based on the rule you want in your code.

Suggestion:

Add a rule option to prevent event trigger to be fired when true (the data for the rule is based on table data and session variables, environment variables)

**Comment by tirumaraiselvan** [comment]
We have a similar feature request here: https://github.com/hasura/graphql-engine/issues/1241

**Comment by revskill10** [comment]
@tirumaraiselvan mine is a bit different in that we set rule to `prevent` trigger to be called. The #1241 is about set rule for trigger to be called.

**Comment by tirumaraiselvan** [comment]
@revskill10 hmm... well `prevent` is just `not` on `allow` right? #1241 allows for general boolean conditions.

**Comment by revskill10** [comment]
@tirumaraiselvan Yes, it's almost. But in this case, you don't need to specify anything to run the trigger (just as now).
You only need to add rule to `prevent`.

**Comment by tirumaraiselvan** [comment]
I am still in favour of tracking these together. Maybe you could add a comment to say you would like a `prevent` rule.

**Comment by praveenweb** [comment]
Tracking this here https://github.com/hasura/graphql-engine/issues/1241#issuecomment-662914446

**Comment by carllippert** [comment]
Very interested in this. Essentially I am trying to find a way to prevent unwanted runaway lambdas when a large number of webhooks start getting configured to be triggered on one row. If I could tell Hasura to say not fire webhook when recieving new data from serverless functions vs a user/client it would be a nice buffer to prevent accidents like when I accidentally leave "update_at" column checked on a function that writes back to the row that fires it.
