### ISSUE TITLE
Bug: /v1/query Case Sensitive

### ISSUE THREAD

**Issue by PseudoSky** [hasura/graphql-engine#5328]
Version: v1.3.0-beta.4
URI: /console/data/sql

Steps

- I have a field that I named `createdAt`
- Went to raw sql editor in ui
- Entered `SELECT createdAt FROM tbl;`
- Pressed run

Request

```
curl 'https://localhost/v1/query' \
  --data-binary '{"type":"bulk","args":[{"type":"run_sql","args":{"sql":"SET LOCAL statement_timeout = 10000; SELECT tbl.createdAt from tbl;","cascade":false,"read_only":false}}]}'
```

Response
```
{
  "internal": {
    "statement": "SET LOCAL statement_timeout = 10000; SELECT tbl.createdAt from tbl;",
    "prepared": false,
    "error": {
      "exec_status": "FatalError",
      "hint": "Perhaps you meant to reference the column \"tbl.createdAt\".",
      "message": "column tbl.createdat does not exist",
      "status_code": "42703",
      "description": null
    },
    "arguments": []
  },
  "path": "$.args[0].args",
  "error": "query execution failed",
  "code": "postgres-error"
}
```

The part that made me think it has to do with case changing is the
> "column tbl.createdat does not exist"

Also when I renamed the column to created_at it started working.

**Comment by rikinsk** [comment]
@PseudoSky SQL statements are case-sensitive. You need to surround literals with `"`s. ie. `SELECT "createdAt" FROM tbl;`

**Comment by PseudoSky** [comment]
@rikinsk to reword my point - the quotes shouldn't be necessary if the goal is to match the actual query parser

IE: Testing the query from a shell works without the quotes, but not through the endpoint.

Do all columns need to be quote wrapped for the endpoint?
