### ISSUE TITLE
default option is selected while cloning row in data browser

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#5340]
If a column has a default value defined, then while cloning a row, the default radio-btn is selected instead of the input box radio-btn.

For example,

**Current behaviour**
![Screenshot from 2020-07-09 20-25-14](https://user-images.githubusercontent.com/54616969/87056009-a7e99080-c222-11ea-894d-ede6c110c60d.png)

**Expected behaviour**
![Screenshot from 2020-07-09 20-29-11](https://user-images.githubusercontent.com/54616969/87056208-ef701c80-c222-11ea-8764-23a8fef4e7de.png)

**Comment by sushil97** [comment]
I want to work on this but I want some more clarifications beforehand "why is the radio button of id is not selected in expected behaviour id also has the default value is'nt it?" .
