### ISSUE TITLE
graphQL field deprecation

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#535]
from Ben (cherre.com): 

Reading material: 
https://medium.com/@kevinsimper/how-to-deprecate-fields-in-graphql-52fbd03fb9d7
https://www.apollographql.com/docs/graphql-tools/schema-directives.html

**Comment by tirumaraiselvan** [comment]
Closing this in favour of this broader issue: https://github.com/hasura/graphql-engine/issues/2943
