### ISSUE TITLE
Large number of rows in hdb_instances_ref table

### ISSUE THREAD

**Issue by luke-j** [hasura/graphql-engine#5353]
The `hdb_instances_ref` is taking up thousands of rows in my database, even though the application itself only takes up a few dozen. 

What's the purpose of this table? Can the rows be purged at a certain point?

**Comment by njaremko** [comment]
^ This makes Heroku threaten to delete your DB on free tiers pretty quickly (10,000 row limit)

**Comment by tirumaraiselvan** [comment]
This will be fixed in an upcoming upgrade. Meanwhile, it is safe to truncate this table.

**Comment by tirumaraiselvan** [comment]
Should be fixed in latest cloud.
