### ISSUE TITLE
Setting EVENT DATA TRIGGER header automatically sets payload field

### ISSUE THREAD

**Issue by followbl** [hasura/graphql-engine#5358]
when you set any header in an EVENT DATA TRIGGER - Hasura automagically sets the payload fields to whatever columns you have selected based on the trigger.

Ex:

Step 1. 
Before:
Event is triggered after row updates as `confirmed_at` is set - entire row is passed to the event

Step 2.
Set any header in the EVENT DATA TRIGGER console.

Step 3.
After: 
Event is triggered after row updates as `confirmed_at` is set - only confirmed_at is passed to the event in new and old.

This feels like a bug to me - as there's nothing visual in the console after adding this header that would make me see that the payload is now being restricted to specific columns...it's only after having manually inspecting the metadata that I noticed the change.

**Comment by tobiastornros** [comment]
Which Hasura version are you testing on?

**Comment by followbl** [comment]
@tobiastornros `v1.3.0-beta.4`
