### ISSUE TITLE
Guide for setting up migrations with hasura console

### ISSUE THREAD

**Issue by khpatel4991** [hasura/graphql-engine#5359]
Hi,

I have a simple next js application. I want to use hasura pg instance as a data layer. 
I have deployed hasura instance on heroku.
Instead of manually creating tables and columns through hasura interface on heroku, I'd like to use hasura cli to generate migrations based on what I do on my local hasura like in this [video](https://www.youtube.com/watch?v=cGjH_HjkWiU)

I initialized hasura in my project with `hasura init --endpoint my_hasura_endpoint`. And now when I try to run `hasura console` I get the following error message.

```
FATA[0000] error creating migrate instance: cannot create migrate instance: Data Error: {"path":"$","error":"resource does not exist","code":"not-found"}
```

```
Versions:
INFO hasura cli                                    version=v1.3.0-beta.4
INFO hasura graphql engine                         endpoint="my_hasura_endpoint" version=
```

**Comment by khpatel4991** [comment]
It was my mistake

**Comment by SarathBaiju** [comment]
What was the mistake? Could u pls update?

**Comment by 24601** [comment]
The endpoint should NOT include /v1/graphql, it should be protocol://host *only*. This was my issue and doing this fixed it.
