### ISSUE TITLE
[Auth0/Nextjs] GraphQL query fails on missing 'hasura.io' claims

### ISSUE THREAD

**Issue by tonyjmartinez** [hasura/graphql-engine#5361]
I'm trying to add authentication with auth0 similar to how it's handled in this hasura [tutorial repo](https://github.com/hasura/learn-graphql/tree/master/tutorials/frontend/nextjs/app-final). I'm able to login/request user info successfully from auth0. The user info I receive includes `https://hasura.io/jwt/claims` as a key.

However, when I try to navigate to `/posts` which runs a gql query, I see this error:

```
Error: Network error: cannot start as connection_init failed with : claims key: 'https://hasura.io/jwt/claims' not found
    at new ApolloError (bundle.esm.js?74ca:63)
```

If I refresh the page when I'm at `/posts`, the query runs fine.

I'm not sure what I'm doing wrong when adding claims to the jwt. I have the rule setup on `auth0.com` to add the claims. I'm also not sure why it works when I refresh the page vs navigating within the app.

[Here's my repo](https://github.com/tonyjmartinez/from-way-downtown-next). Thanks!

**Comment by njaremko** [comment]
Maybe include a sample expired JWT? Have you confirmed that the claims key is present in your JWT?

**Comment by tonyjmartinez** [comment]
When I run `auth0.getSession` in `withApollo.js`, I get back and object with my `accessToken` and `idToken`. If I use the `idToken`, I'm able to get back data when I reload the page if I'm at `/posts`. If I use the `accessToken`, it doesn't work at all and I get the error about jwt claims every time.

I don't understand why yet. The tutorial I'm using uses `accessToken`. And I did confirm that I have the auth0 rule setup to add the claims.

I'm especially confused as to why it only works when I refresh the page once I'm at `/posts`. I can't tell if part of the issue is how I'm loading data in next, or if it's entirely a jwt issue.

### idToken
```
{
  "https://hasura.io/jwt/claims": {
    "x-hasura-default-role": "user",
    "x-hasura-allowed-roles": [
      "user"
    ],
    "x-hasura-user-id": "google-oauth2|XXXXXXXXXXXXX"
  },
  "given_name": "Lorem",
  "family_name": "Ipsum",
  "nickname": "Dolor",
  "name": "Lorem Ipsum",
  "picture": "https://lh3.googleusercontent.com/a-/XXXXXXXXXXX",
  "locale": "en",
  "updated_at": "2020-07-13T16:50:43.062Z",
  "iss": "https://mydomain.us.auth0.com/",
  "sub": "google-oauth2|XXXXXXXX",
  "aud": "XXXXXXXXXXX",
  "iat": 1594659044,
  "exp": 1594695044
}
```

### accessToken
```
{
  "iss": "https://mydomain.us.auth0.com/",
  "sub": "google-oauth2|123456789",
  "aud": [
    "https://mydomain.us.auth0.com/api/v2/",
    "https://mydomain.us.auth0.com/userinfo"
  ],
  "iat": 1594659044,
  "exp": 1594745444,
  "azp": "XXXXXXXXXXXXXX",
  "scope": "openid profile"
}
```

**Comment by tonyjmartinez** [comment]
Found out that this was due to differences between my auth0 rule and `withApollo`. I was changing the `idToken` in auth0, but reading the `accessToken` in next.
