### ISSUE TITLE
v1.3.0-beta.4 bug created_at

### ISSUE THREAD

**Issue by mkalayci35** [hasura/graphql-engine#5365]
```
mutation insertFeedRating($feed_id: uuid, $is_like: Boolean) {
	insert_feed_rating(objects: { feed_id: $feed_id, is_like: $is_like }, on_conflict: { constraint: feed_rating_feed_id_user_id_key, update_columns: is_like }) {
		affected_rows
		returning {
			is_like
		}
	}
}
``` 
i am update data and created at change. only update_at should have changed. 

<img width="475" alt="Screen Shot 2020-07-13 at 16 36 29" src="https://user-images.githubusercontent.com/38668796/87310715-023a6800-c527-11ea-9c51-78a03e3fb3c3.png">

<img width="358" alt="Screen Shot 2020-07-13 at 16 37 34" src="https://user-images.githubusercontent.com/38668796/87310821-28f89e80-c527-11ea-94cb-2e520ad45850.png">
<img width="478" alt="Screen Shot 2020-07-13 at 16 29 19" src="https://user-images.githubusercontent.com/38668796/87310550-c6070780-c526-11ea-89be-8ad4945244f0.png">

<img width="445" alt="Screen Shot 2020-07-13 at 16 32 44" src="https://user-images.githubusercontent.com/38668796/87310553-c8696180-c526-11ea-8c8c-d2320c447e2f.png">

**Comment by njaremko** [comment]
- Did you make this table in through the Hasura console? 
- Can you also provide the schema for the table? 
- Maybe also a list of triggers that are on this table?

**Comment by tirumaraiselvan** [comment]
@mkalayci35 Could you show the entire row (including primary key)? Since this is an upsert operation, maybe a new row was inserted?

**Comment by mkalayci35** [comment]
@njaremko I fixed it by hand myself. -> https://hasura.io/docs/1.0/graphql/manual/schema/default-values/created-updated-timestamps.html
