### ISSUE TITLE
cli: add command to reset migrations

### ISSUE THREAD

**Issue by scriptonist** [hasura/graphql-engine#5373]
`hasura migrate reset`

This command should clear the history of the migrations on the server and clear the local migrations. Basically, do steps 1 and 2 mentioned in this blog post: https://hasura.io/blog/resetting-hasura-migrations/

**Comment by timhere** [comment]
I agree that this would be a good addition as my feature development workflow has lots of writing `TRUNCATE hdb_catalog.schema_migrations;` and `rm -r migrations`.

**Comment by tharun208** [comment]
@scriptonist I like to work on this

**Comment by kolharsam** [comment]
@tharun208 you can go ahead, good luck! 😁

**Comment by ShraddhaAg** [comment]
Hi @tharun208! Wanted to check in if you need any help. Also, could you please open a draft PR with your progress?

**Comment by sushil97** [comment]
I would like to work on this

**Comment by Yashs911** [comment]
@scriptonist I would like to work on this issue.

**Comment by scriptonist** [comment]
Haven't heard from @tharun208 in while so I think it's okay for you pick it up @sushil97

**Comment by sushil97** [comment]
@scriptonist i would love to work on this but right now i am working on another PR. So there will be some delays on this.

**Comment by athanhat** [comment]
Hi, I have just upgraded my hasura engine and CLI to 

```bash
hasura version

INFO hasura cli                                    version=v2.0.0-alpha.9
INFO hasura graphql engine                         endpoint="http://localhost:8001/" version=v2.0.0-alpha.9
```
And I discovered that [resetting the migration history on the server][1] is still under construction. Moreover I noticed that you cannot do any more 
```sql
TRUNCATE hdb_catalog.schema_migrations;
```
And if you [pull the schema and metadata from the server][2], you will loose the granularity of having multiple migration steps, i.e.  
a single migration step will be marked as applied on the server by skipping execution. But I wanted to restore my PostgreSQL database (all schemas and populated table) and then apply all migrations steps from a backup folder.

So after restoring my PostgreSQL database, I initialised metadata operations and migrations folder and copied schema migrations from a backup folder. 

```bash
hasura migrate status --database-name default

VERSION        NAME                     SOURCE STATUS  DATABASE STATUS
1615111441648  Schema_auth              Present        Not Present
1615197558676  Account                  Present        Not Present
1615261416207  AccountConfirmation      Present        Not Present
etc...
```
Now the trick is to mark ALL migration steps as applied by skipping execution and make them present in the database. That can be done easily by running the following pipeline (check how many line you need to skip NR>?): 

``` bash
hasura migrate status --database-name default | awk 'NR>2 {print $1}' | xargs -I{} sh -c 'hasura migrate apply --version {} --skip-execution --database-name default'
```

Anyway hope that helps others that have the same problem until hasura team implements  __migrations reset__ with a more efficient and elegant solution.

[1]: https://hasura.io/docs/latest/graphql/core/migrations/advanced/resetting-migrations.html#step-2-reset-the-migration-history-on-the-server

[2]: https://hasura.io/docs/latest/graphql/core/migrations/advanced/resetting-migrations.html#step-3-pull-the-schema-and-metadata-from-the-server
