### ISSUE TITLE
console: ui issue on metadata actions page

### ISSUE THREAD

**Issue by kolharsam** [hasura/graphql-engine#5386]
The `Import Metadata` button changes state to `Importing...` while the user uploads the metadata file. In case, the user cancels the upload, the button state/text should revert to `Import Metadata`.

#### Depiction of the bug:

![ezgif-3-7ef21c2085b3](https://user-images.githubusercontent.com/6604943/87571514-ce5a7080-c6e7-11ea-92c0-69818fe32693.gif)

**Comment by kentaro84207** [comment]
I'd like to work on this issue.

**Comment by kolharsam** [comment]
@kentaro84207 go for it! 🎉

cc @beerose
