### ISSUE TITLE
curl install the cli fails (github action)

### ISSUE THREAD

**Issue by tibotiber** [hasura/graphql-engine#5389]
Hi,

I'm the maintainer of the [Hasura GitHub action](https://github.com/marketplace/actions/github-action-for-hasura). A user has reported a failed install of the CLI in his action workflow, see https://github.com/tibotiber/hasura-action/issues/5. We're unable to figure out why this may be happening on his end only, while other users have no issues. Would you mind having a look at that issue and assisting?

Thanks,
Thibaut

**Comment by ste824** [comment]
We get this too when running the `curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash` command described on https://hasura.io/docs/1.0/graphql/manual/hasura-cli/install-hasura-cli.html#install-a-binary-globally.

The problem appears to be when the script calls this - https://releases.hasura.io/graphql-engine?agent=cli-get.sh it receives an HTTP 500 with the response body `{"error":"contacting github api failed"}`

This is blocking our builds.  Can anyone help?  I guess we shouldn't have a dependency on the `curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash` command in our build process

**Comment by drj17** [comment]
This happens for us as well.  The https://releases.hasura.io/graphql-engine?agent=cli-get.sh endpoint goes down pretty frequently and blocks all of our builds.

**Comment by yash2code** [comment]
facing the same issue . any  Workarounds ?

**Comment by alexander-zheleznov** [comment]
still experiencing this issue from time to time

**Comment by drj17** [comment]
At this point I'm just going to copy the script and hardcode the version because the endpoint goes down multiple times a day causing all of our builds to fail.

**Comment by scriptonist** [comment]
Should be fixed in https://github.com/hasura/graphql-engine/pull/6215, feel free to reopen if it still persists.
