### ISSUE TITLE
Optional database schema prefix

### ISSUE THREAD

**Issue by ludovicc** [hasura/graphql-engine#5394]
Hello,

In my company, we use Postgres schemas to segregate data by customer. The table structure is the same for different schemas, but data in one schema is always linked to a customer and cannot be accessed from another customer.

This architecture makes compliance and multi-tenancy easier to manage, but with Hasura we have what looks like many different schemas but differ only by the schema prefix (cust1_tableA, cust2_tableA...). Ideally from GraphQL only tableA should be used when there are no ambiguities.

In Postgres, search_path is used to remove the need to specify the schema on each statement, can a similar functionality be added to Hasura, for example as a prefix in the url (/cust1/v1/graphql) or as x-hasura-search-path=cust1 header?

This issue is related to:

- Feature Request: Support graphql schema export by postgres schemas #2747
- rfc: renaming types and fields #4821

**Comment by tirumaraiselvan** [comment]
This is highly related to https://github.com/hasura/graphql-engine/issues/3606

**Comment by jflambert** [comment]
I would love being able to prefix hasura schema names... same situation as @ludovicc

**Comment by MarcusBondezan** [comment]
Same situation here! It would be great to have such way to work with different schemas.

**Comment by nezzard** [comment]
Have the same problem

**Comment by tirumaraiselvan** [comment]
One idea to solve this is being discussed in https://github.com/hasura/graphql-engine/issues/3606

Would love all you feedback there!

**Comment by tirumaraiselvan** [comment]
Closing this in favour of #3606
