### ISSUE TITLE
Getting "Nothing to apply" while auto-applying migrations using cli-migrations-v2

### ISSUE THREAD

**Issue by ghoshnirmalya** [hasura/graphql-engine#5396]
I'm unable to auto-apply migrations using **hasura/graphql-engine:v1.2.2.cli-migrations-v2**. I'm getting the following even though there are migrations which are created using Hasura:

```
{"level":"info","msg":"nothing to apply","time":"2020-07-16T18:32:17Z"}
```

## Screenshot
<img width="1674" alt="Screenshot 2020-07-17 at 12 06 51 AM" src="https://user-images.githubusercontent.com/6391763/87709159-78f29200-c7c1-11ea-99f4-6b9d323721ba.png">

## Demo application
[Link to a sample application](https://github.com/ghoshnirmalya/hasura-auto-apply-migration-issue). Just clone and run `docker-compose up`.

**Comment by scriptonist** [comment]
@ghoshnirmalya If I understand correctly, you are using the the `Dockerfile` mentioned in the repo right? 
If that's the case, you might wanna mount / set your migrations directory as mentioned here https://hasura.io/docs/1.0/graphql/manual/migrations/advanced/auto-apply-migrations.html#applying-migrations

**Comment by ghoshnirmalya** [comment]
@scriptonist I've added a custom env variable for the migrations directory: [HASURA_GRAPHQL_MIGRATIONS_DIR=./migrations](https://github.com/ghoshnirmalya/hasura-auto-apply-migration-issue/blob/master/.env#L8).

In the screenshot, it mentions that Hasura is "applying migrations from ./migrations".

**Comment by scriptonist** [comment]
@ghoshnirmalya got it, but the`migrations` directory from the repo is not mounted at `./migrations` right? So from the POV of container `./migrations` is empty.
IIUC if change the value of env var to `HASURA_GRAPHQL_MIGRATIONS_DIR=/usr/src/app/migrations` this should work as expected.

**Comment by ghoshnirmalya** [comment]
@scriptonist Thank you for solution. However, that's also not working. It still states "Nothing to apply". See the screenshot below:

![carbon](https://user-images.githubusercontent.com/6391763/87750410-fe556100-c818-11ea-9378-6859776cc60c.png)

**Comment by scriptonist** [comment]
Hey @ghoshnirmalya , I noticed that you are using config `v1` project, the corresponding `cli-migrations` image for that will be `hasura/graphql-engine:v1.2.2.cli-migrations`
https://hasura.io/docs/1.0/graphql/manual/migrations/config-v1/advanced/auto-apply-migrations.html#auto-apply-migrations-v1

**Comment by ghoshnirmalya** [comment]
@scriptonist Thank you. After I upgraded my Hasura project to v2 using `hasura scripts update-project-v2`, the migrations started applying automatically on starting the server.
