### ISSUE TITLE
Tracking a foreign key relationship request never finishes

### ISSUE THREAD

**Issue by tnrich** [hasura/graphql-engine#5398]
Hey there, 

I'm trying to get hasura up and running on a DB with multiple schemas. When I try to hit the "Track" button next to the relationships I get the following: 
![image](https://user-images.githubusercontent.com/2730609/87717724-b75a6380-c765-11ea-8225-4d29b9f0a3f4.png)

As you can see several of these requests just aren't finishing. There is no warning or error message in the console. Any help debugging what's happening would be appreciated. Please let me know if I can provide any more helpful info for you. 

Thanks!
Thomas

**Comment by tnrich** [comment]
I believe this might be related to https://github.com/hasura/graphql-engine/issues/3802

**Comment by beerose** [comment]
Hi @tnrich! Thanks for reporting. This issue is already tracked as a part of this one: https://github.com/hasura/graphql-engine/issues/5014. We have [a PR](https://github.com/hasura/graphql-engine/pull/5168) in place that will be merged soon.

**Comment by tnrich** [comment]
Thanks @beerose glad to hear it!
