### ISSUE TITLE
name field for migrations created via run_sql

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#541]
In the SQL tab, when a new migration is created, it currently creates it with the same name for all migrations.

An input box to accept a name per migration would be nice.

**Comment by karthikvt26** [comment]
Great @arshadkazmi42. Please put a PR anytime

**Comment by sdabhi23** [comment]
I would like to take this up!

**Comment by shahidhk** [comment]
@arshadkazmi42 Another person has showed interest. Have you done any work on this?

**Comment by shahidhk** [comment]
@sdabhi23 Let's wait for some time to see if @arshadkazmi42 has done anything. Otherwise, feel free to start work tomorrow.

**Comment by arshadkazmi42** [comment]
@shahidhk  I completely forgot about this, I have been working on alot of projects in parallel. @sdabhi23 you can work on this if you want. If you do not want to do it in any step then let me know, I will take it up.

**Comment by clarkdowding** [comment]
@shahidhk and @sdabhi23, are either of you going to do this one?

**Comment by sdabhi23** [comment]
@clarkdowding yes, I am working on it.
