### ISSUE TITLE
docs: info on setting hasura_graphql_jwt_secret for azure arm

### ISSUE THREAD

**Issue by fr8in** [hasura/graphql-engine#5413]
The ARM template and guidelines: https://github.com/hasura/graphql-engine/blob/865b150c82d731509605aba7ad3e843b6d52e24f/install-manifests/azure-container/README.md
is not clear about how to secure graphql endpoint and add authentication using JWT.

**1) Securing end point**
While securing endpoint is easy by adding to the commands array of ARM and pass the value through parameter or direct string
 "command": [
                                "graphql-engine",
								 "--host",
								"prodcore-pg-server.postgres.database.azure.com",
								"--port",
								"5432",
								"--user", 
								"xxxxx@xxxx-pg-server",
								"--password",
								"xxxxx",
								"--dbname",
								"xxxx",
								"serve",
								"--server-port",
								"80",
								"--enable-console",
								"--admin-secret",
								"[parameters('admin-secret')]"
                            ],

adding jwt is complex as jwt values for HASURA_GRAPHQL_JWT_SECRET is json and ARM commands acceps only string. The only workable option i figured out was use the environmentVariable and pass json as string with escape characters. All " and \n to be prefixed by \  _(ex. "type" = \"type\" and \n = \\n)_

**2) Adding JWT to Hasura**
"environmentVariables": [
                        
                                {
                                    "name": "HASURA_GRAPHQL_JWT_SECRET",
                                    "value": "{\"type\": \"RS512\",\"key\": \"-----BEGIN CERTIFICATE-----\\nMIIDBzCCAe+gAwIBAgIJTpEEoUJ/bOElMA0GCSqGSIb3DQEBCwUAMCExHzAdBgNV\\nBAMTFnRyYWNrLWZyOC51cy5hdXRoMC5jb20wHhcNMjAwNzE3MDYxMjE4WhcNMzQw\\nMzI2MDYxMjE4WjAhMR8wHQYDVQQDExZ0cmFjay1mcjgudXMuYXV0aDAuY29tMIIB\\nIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuK9N9FWK1hEPtwQ8ltYjlcjF\\nX03jhGgUKkLCLxe8q4x84eGJPmeHpyK+iZZ8TWaPpyD3fk+s8BC3Dqa/Sd9QeOBh\\nZH/YnzoB3yKqF/FruFNAY+F3LUt2P2t72tcnuFg4Vr8N9u8f4ESz7OHazn+XJ7u+\\ncuqKulaxMI4mVT/fGinCiT4uGVr0VVaF8KeWsF/EJYeZTiWZyubMwJsaZ2uW2U52\\n+VDE0RE0kz0fzYiCCMfuNNPg5V94lY3ImcmSI1qSjUpJsodqACqk4srmnwMZhICO\\n14F/WUknqmIBgFdHacluC6pqgHdKLMuPnp37bf7ACnQ/L2Pw77ZwrKRymUrzlQID\\nAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSOG3E+4lHiI+l0i91u\\nxG2Rca2NATAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEBAKgmxr6c\\nYmSNJOTPtjMFFDZHHX/7iwr+vqzC3nalr6ku8E3Zs0/IpwAtzqXp0eVVdPCWUY3A\\nQCUTt63GrqshBHYAxTbT0rlXFkqL8UkJvdZQ3XoQuNsqcp22zlQWGHxsk3YP97rn\\nltPI56smyHqPj+SBqyN/Vs7Vga9G8fHCfltJOdeisbmVHaC9WquZ9S5eyT7JzPAC\\n5dI5ZUunm0cgKFVbLfPr7ykClTPy36WdHS1VWhiCyS+rKeN7KYUvoaQN2U3hXesL\\nr2M+8qaPOSQdcNmg1eMNgxZ9Dh7SXtLQB2DAOuHe/BesJj8eRyENJCSdZsUOgeZl\\nMinkSy2d927Vts8=\\n-----END CERTIFICATE-----\"}"
                                }
                            ],

**Comment by tirumaraiselvan** [comment]
@fr8in We will be happy to have your contribution in the README if you are up for it :)

**Comment by adithyaakrishna** [comment]
@marionschleifer Can I work on this issue?
If so please do lmk some details about how to secure graphql endpoint and add authentication using JWT

**Comment by marionschleifer** [comment]
@adithyaakrishna you can work on it. You'll have to try it out yourself, I don't know by heart how it works with Azure, I'd have to try it out myself.

**Comment by adithyaakrishna** [comment]
Okay Thanks! I will learn and do this 🚀

**Comment by fr8in** [comment]
> Okay Thanks! I will learn and do this 🚀

@adithyaakrishna i have added a PR for the help file. But i don't know where is the ARM template. the ARM template has to be modified for JST and ADMIN Secret to work. The templates are here: https://drive.google.com/drive/folders/1G9DsIpNagCyXbnzWOKD4PLtaiwU6GPiI?usp=sharing
