### ISSUE TITLE
keyboard shortcut ctrl + enter to execute sql queries

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#542]
SQL tab under Data has a Run! button. This currently works with only button clicks and not via keyboard shortcuts. Need to listen for keyboard events.

**Comment by cTxplorer** [comment]
@praveenweb should I work on this issue?

**Comment by karthikvt26** [comment]
@cTxplorer Go for it and submit a PR once you are done.

**Comment by cTxplorer** [comment]
Thanks, @praveenweb

**Comment by cTxplorer** [comment]
@praveenweb Just to be sure, I can make new function for the current code triggered by `onclick()` event of the `Run!` button.
