### ISSUE TITLE
relay mode is showing uuids in base64 encoded

### ISSUE THREAD

**Issue by madeken** [hasura/graphql-engine#5431]
Normal mode presenting the id's (uuid in postgres) correctly:

<img width="1272" alt="Screen Shot 2020-07-20 at 8 15 24 PM" src="https://user-images.githubusercontent.com/36307021/88008725-c757a780-cac5-11ea-8481-0e685529112d.png">

But in relay mode:

<img width="1460" alt="Screen Shot 2020-07-20 at 8 16 37 PM" src="https://user-images.githubusercontent.com/36307021/88008819-f2da9200-cac5-11ea-9b21-2054e7cae9a1.png">

**Comment by hegelstad** [comment]
@madeken I am curious to hear why you closed the issue?
