### ISSUE TITLE
Removing relationships with dependent objects fails but the console reports success

### ISSUE THREAD

**Issue by timhere** [hasura/graphql-engine#5436]
## Environment

- docker-compose
- hasura engine v1.3.0
- Postgres 12.3

## Summary 

Attempting to delete a foreign key with dependent objects and permissions is reported as successful by the console, however the operation fails.

## Behaviour

If I try to remove a foreign key with dependent objects:

- go to the Data -> {table} -> Modify tab
- the console shows an error notification "Deleting foreign key failed", and that the operation can't be performed because of the dependent objects
- I am asked "Do you want to drop the dependent objects as well?"
- If I click "Continue" the error disappears and I see a success notification "Foreign key deleted"
- The foreign key appears to have been deleted and a new timestamp appears in the `migrations` directory
- If I navigate away from the "modify" page and then back, the foreign key relationship is still there!
- Testing using the API Explorer, the relationship still exists

A similar behaviour is observed when trying to delete relationships under the "Relationships" tab.

--

**Update:** 
I've now tried manually removing all reference to a relationship in permissions, and after doing so the specified FK is successfully deleted.

**Comment by beerose** [comment]
Fixed via https://github.com/hasura/graphql-engine/pull/6170
