### ISSUE TITLE
[Feature request] RBAC + Fastest way to add tenancy for 160 tables

### ISSUE THREAD

**Issue by ravensnowbird** [hasura/graphql-engine#5437]
Hi team, 

I would like to know if there can be a easy way to add default scope on tables from X-Hasura-Xxxxx-ID for tables that already has a foreign_key relationship to Xxxxx table. 

I believe it's a very common feature request for SaaS companies. Ruby on Rails has a gem for this as well - https://github.com/ErwinM/acts_as_tenant 

In my case I have a very large database - 160 tables. 

1. 3 tables have tenancy
  - Xxxxx 
  - Yyyyy
  - Zzzzz
2. Every other table on the db has a foreign-key
  - Xxxxx_id
  - Yyyyy_id
  - Zzzzz_id

I feel there could be an easy and  straight forward way to add default scope to all the tables except for 3.
  - Xxxxx_id eq X-Hasura-Xxxxx-ID
  - Yyyyy_id eq X-Hasura-Yyyyy-ID
  - Zzzzz_id eq X-Hasura-Zzzzz-ID

**Comment by rikinsk** [comment]
I can't think of a simple automated way to do this currently unfortunately. 

The way to approach this would be to auto-generate the permissions related Hasura metadata via some tooling and then applying that metadata to apply all the permissions in one go. 

A brief summary of the steps involved:

- [Export](https://hasura.io/docs/1.0/graphql/manual/migrations/manage-metadata.html#exporting-hasura-metadata) the current metadata via CLI/console
- Run a tool/script that reads the metadata, adds in the relevant permissions related metadata for all the tables and outputs the updated metadata file
- [Apply](https://hasura.io/docs/1.0/graphql/manual/migrations/manage-metadata.html#applying-importing-hasura-metadata) the updated metadata via CLI/console

The script/tool can have the following logic:
- Read the existing metadata (it will be in yaml format if exported via the CLI and in json format if exported via the console)
- Get all foreign-key constraints defined on the tables you are interested. 

  From some brief searching I found the following query to fetch all foreign key constraints defined on tables in the "public" schema. You can tweak it based on your requirements
  ```sql
  SELECT
    tc.table_schema, 
    tc.constraint_name, 
    tc.table_name, 
    kcu.column_name, 
    ccu.table_schema AS foreign_table_schema,
    ccu.table_name AS foreign_table_name,
    ccu.column_name AS foreign_column_name 
  FROM 
    information_schema.table_constraints AS tc 
    JOIN information_schema.key_column_usage AS kcu
      ON tc.constraint_name = kcu.constraint_name
      AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
      ON ccu.constraint_name = tc.constraint_name
      AND ccu.table_schema = tc.table_schema
  WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema='public';
  ```
  Sample output
  ![Screenshot from 2020-07-28 20-25-00](https://user-images.githubusercontent.com/54616969/88682586-745aa180-d110-11ea-96a6-81496959f1f1.png)
- Based on the above data generate your permissions based on your rules and set them appropriately in the metadata
  e.g.
  ```json 
  {
      "table": {
        "schema": "public",
        "name": "Customer"
      },
      "select_permissions": [
        {
          "role": "user",
          "permission": {
            "columns": "*",
            "filter": {
              "CustomerId": {
                "_eq": "X-Hasura-Customer-Id"
              }
            }
          }
        }
      ]
    }
   ```
- export the updated metadata file

Hope this made sense.

On the note of auto-generating metadata programatically, we are actively working on making the process of generating metadata programatically easier via tooling. Think SDKs in your favourite language. 
@GavinRay97 could you share some info and any resources regarding the same?

**Comment by GavinRay97** [comment]
Hey actually yeah, this would be pretty straightforward to do with the Metadata SDK from here:

https://github.com/hasura/graphql-engine/pull/5452
https://github.com/GavinRay97/graphql-engine/tree/feature/add-metadata-types-and-generator/metadata-types#programmatically-interacting-with-metadata

It would be roughly this:
```ts
import { Convert } from './customMetadataConverter'
import {
  TableEntry,
  Action,
  CustomTypes,
  HasuraMetadataV2,
} from '../generated/HasuraMetadataV2'

// Read "tables.yaml" file as text from filesystem
const tablesMetadataFile = fs.readFileSync('./metadata/tables.yaml', 'utf8')
// Convert it to JSON object with type annotation using loadYAML utility
const tablesMetadata: TableEntry[] = Convert.loadYAML(tablesMetadataFile)

const tenantTables = ["tenant_table_a", "tenant_table_b", "tenant_table_c"]
const nonTenantTables = tablesMetadata.filter(it => !tenantTables.some(table => table == it.table.name))

const request = await fetch('http://localhost:8080/v1/query', {
  method: 'POST',
  body: JSON.stringify({
    type: 'select',
    args: {
      table: { name: 'hdb_table', schema: 'hdb_catalog' },
      columns: [
        'table_schema',
        'table_name',
        { name: 'primary_key', columns: ['*'] },
        { name: 'relationships', columns: ['*'] },
      ],
      order_by: [{ column: 'table_name', type: 'asc' }]
    }
  })
})

const hdbTables: HDBTable[] = await request.json()

for (let table of nonTenantTables) {
  // Find table that matches this non-tenant table from API response 
  let hdbTable = hdbTables.find(it => it.table_name == table.name)

  // Look through it's relationships for a foreign key which matches <tenant_table>_id
  let tenantTable = hdbTable?.relationships.find(rel => {
    let fkey = rel.rel_def.foreign_key_constraint_on
    if (typeof fkey == 'string') return tenantTables.some(t => `${t}_id` == fkey)
    if (typeof fkey == 'object' && fkey != undefined) {
      // Just need this for TS types, it won't type right inside of .some() apparently
      let col = fkey.column
      return tenantTables.some(t => `${t}_id` == col)
    }
  })

  if (!tenantTable) continue

  if (table.select_permissions.length == 0) table.select_permissions = []
  // Add new permission for { <tenant_table>_id: { _eq: X-Hasura-<TenantTable>-ID } }
  table.select_permissions.push({
    role: 'user',
    permission: {
      limit: 100,
      allow_aggregations: false,
      columns: ['id', 'name', 'etc'],
      filter: {
        [tenantTable.table_name + '_id']: { _eq: `X-Hasura-${tenantTable.table_name}-ID` },
      },
    },
  })
}

// Ouput the updated "tables.yaml" to filesystem
fs.writeFileSync('./tables-updated.yaml', Convert.metadataToYAML(tablesMetadata))
```

Where the TS types for that `fetch` query and `HDBTable` are:
```ts
export interface HDBTable {
  table_schema:  string;
  table_name:    string;
  primary_key:   PrimaryKey | null;
  relationships: Relationship[];
}

export interface PrimaryKey {
  constraint_name: string;
  columns:         string[];
  table_schema:    string;
  table_name:      string;
}

export interface Relationship {
  rel_type:          RelType;
  rel_def:           RelDef;
  rel_name:          string;
  is_system_defined: boolean;
  table_schema:      string;
  comment:           null;
  table_name:        string;
}

export interface RelDef {
  foreign_key_constraint_on?: ForeignKeyConstraintOnUnion;
  manual_configuration?:      ManualConfiguration;
}

export type ForeignKeyConstraintOnUnion = ForeignKeyConstraintOnClass | string;

export interface ForeignKeyConstraintOnClass {
  table:  Table;
  column: string;
}

export interface Table {
  name:   string;
  schema: string;
}

export interface ManualConfiguration {
  remote_table:   Table;
  column_mapping: ColumnMapping;
}

export interface ColumnMapping {
  trigger_name?:       string;
  name?:               string;
  action_name?:        string;
  return_type_name?:   string;
  return_type_schema?: string;
  role_name?:          string;
  table_name?:         string;
  table_schema?:       string;
}

export enum RelType {
  Array = "array",
  Object = "object",
}
```
