### ISSUE TITLE
Remote schema is queried with null id

### ISSUE THREAD

**Issue by salceson** [hasura/graphql-engine#5448]
Hasura version: 1.3.0

We have a table `project` in our database that has following columns:
![image](https://user-images.githubusercontent.com/3855869/88177030-7ca27080-cc28-11ea-9426-cf0b2fe22324.png)
(relevant column is `updated_status_by` - please note that the column **CAN** be `null`)

On this column we have defined a remote relationship:
![image](https://user-images.githubusercontent.com/3855869/88177128-a196e380-cc28-11ea-9e40-c0323f1d4de4.png)

When we query for a row that has `null` in `updated_status_by`, the remote schema is also queried with `null`.

If relevant, the query we execute is as follows:
```graphql
query MyQuery($id: uuid!) {
  project: project_by_pk(id: $id) {
    id
    name
    status
    created_at
    updated_status_at
    updated_status_by_user {
      id
      name
  }
}
```

I believe that this should not be happening (if `updated_status_by` is `null`, then there will be no `updated_status_by_user`, would it?). Is this behavior correct?

**Comment by tirumaraiselvan** [comment]
Hmm, what is the response you get when this happens?

**Comment by salceson** [comment]
> Hmm, what is the response you get when this happens?

I get error on remote schema as the `id` is required in `user_by_pk`.

Full response:
```json
{
  "errors": [
    {
      "extensions": {
        "internal": {
          "errors": [
            {
              "extensions": {
                "exception": {
                  "stacktrace": [
                    "GraphQLError: Expected value of type \"String!\", found null.",
                    "    at Object.NullValue (/keycloak-hasura/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:80:29)",
                    "    at Object.enter (/keycloak-hasura/node_modules/graphql/language/visitor.js:323:29)",
                    "    at Object.enter (/keycloak-hasura/node_modules/graphql/utilities/TypeInfo.js:370:25)",
                    "    at visit (/keycloak-hasura/node_modules/graphql/language/visitor.js:243:26)",
                    "    at Object.validate (/keycloak-hasura/node_modules/graphql/validation/validate.js:69:24)",
                    "    at validate (/keycloak-hasura/node_modules/apollo-server-core/dist/requestPipeline.js:221:34)",
                    "    at Object.<anonymous> (/keycloak-hasura/node_modules/apollo-server-core/dist/requestPipeline.js:118:42)",
                    "    at Generator.next (<anonymous>)",
                    "    at fulfilled (/keycloak-hasura/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
                    "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
                  ]
                },
                "code": "GRAPHQL_VALIDATION_FAILED"
              },
              "message": "Expected value of type \"String!\", found null.",
              "locations": [
                {
                  "line": 1,
                  "column": 52
                }
              ]
            }
          ]
        },
        "path": "$",
        "code": "unexpected"
      },
      "message": "Errors from remote server"
    }
  ]
}
```

> Also, is the `id` input argument of `user_by_pk` field in your remote schema, a required input argument?

Yes, it is. Full remote schema:

```graphql
    type User {
        id: String!
        username: String!
        email: String!
        firstName: String!
        lastName: String!
        name: String!
    }

    type Query {
        user_by_pk(id: String!): User
        user: [User]!
    }
```

A workaround was to make it not required, however I think it is a bit strange that the remote server is queried at all.

**Comment by aaronhayes** [comment]
Having the same issue, and I agree the remote server should never be queried. Was quite surprised when it was queried.

**Comment by stephendeyoung** [comment]
This is also a big problem for me. Will you be planning to fix this @tirumaraiselvan? The remote schema shouldn't be queried if the field is null.

**Comment by codingkarthik** [comment]
I would like to understand what the ideal behaviour should be. In the case of a single argument remote relationship, it makes sense to avoid the remote call, when the joining argument is NULL. But, what should the behaviour be when there are multiple joining arguments in the remote relationship? 

Two possible things that can be done are:

1. Avoid querying the remote schema when any of the joining arguments is NULL
2. Avoid querying the remote schema when all of the joining arguments are NULL

I'm not sure which behaviour out of the above two will make more sense.

**Comment by salceson** [comment]
> I would like to understand what the ideal behaviour should be. In the case of a single argument remote relationship, it makes sense to avoid the remote call, when the joining argument is NULL. But, what should the behaviour be when there are multiple joining arguments in the remote relationship?
> 
> Two possible things that can be done are:
> 
> 1. Avoid querying the remote schema when any of the joining arguments is NULL
> 2. Avoid querying the remote schema when all of the joining arguments are NULL
> 
> I'm not sure which behaviour out of the above two will make more sense.

Hi, this is a very good point. I'd say that more 'correct' behavior from my point of view would be to not query remote schema if all arguments are null. If only some arg is null, but others are not, it could mean that some data may be available on remote side.

**Comment by codingkarthik** [comment]
Interestingly, in SQL joins (at-least in postgres) the remote table is not queried if any of the joining argument is NULL.

For example: 

If I have the following tables:

```
test_db=# select * from users;
 id | first_name | last_name
----+---------+-----------
  1 | foo  |
  2 | baz | bar
  3 |        | hello

test_db=# select * from address;
 id | first_name    | last_name |      address
----+-------------+-----------+-------------------
  1 | foo    |    | address1
  2 | baz | bar          | address2
  3 |          | hello         | address3
(3 rows)
```

Now performing the following query:

```sql
select u.first_name,u.last_name,a.address 
from users u 
left join address a on u.first_name = a.first_name and u.last_name = a.last_name;
```

gives the following result:

```
 first_name | last_name | address
------------+-----------+----------
 baz        | bar       | address2
 foo        |           |
 hello      |           |
```

**Comment by tirumaraiselvan** [comment]
The behaviour has been changed in v2.0, as explained in released notes:

> In a remote schema relationship query, the remote schema will be queried when all of the joining arguments are not null values. When there are null value(s), the remote schema won't be queried and the response of the remote relationship field will be null. Earlier, the remote schema was queried with the null value arguments and the response depended upon how the remote schema handled the null arguments but as per user feedback, this behaviour was clearly not expected.
