### ISSUE TITLE
Joining against custom function results gets rid of ordering

### ISSUE THREAD

**Issue by rccoe** [hasura/graphql-engine#5453]
Hi there,

I have a function that does fuzzy text searching and orders the results by similarity score. It seems to work fine when just querying the table, but as soon as I join anything up to it, the ordering is destroyed.

ex.

```
CREATE FUNCTION public.search_thing(query text) returns setof thing LANGUAGE sql STABLE AS $function$
.... search logic here
```

In this query, the ordering from the function gets preserved:
```
query SearchThings(
  $query: String!
) {
  search_thing(args: {query: $query}) {
    id
    ...
  }
}
```

And in this one it does not. 
```
query SearchThings(
  $query: String!
) {
  search_thing(args: {query: $query}) {
    id
    ...
   other_thing {
       id
   }
  }
}
```

Unfortunately because custom functions have to return `setof <table>`, there is no way to get similarity score other than custom functions. This really limits the functionality because joining to a custom function results is useless in any case where we're relying on custom functions for ordering.

**Comment by tirumaraiselvan** [comment]
The order of results returned by a function is not preserved if it is used in a join (this happens at the Postgres layer itself).

Is it possible to include a similarity-score column in the returned row type, maybe via a view : `create view thing_with_score as (select *, NULL::double as score from thing)` and then you can order_by this column.

**Comment by rccoe** [comment]
That makes sense. Thanks Tiru.
