### ISSUE TITLE
Data and schema managment failed to load and throw of an error.

### ISSUE THREAD

**Issue by SenchoDev** [hasura/graphql-engine#5454]
I am new with Hasura and my app broke in production for some reason.
My GraphQl mutations arent fetching data from database and when i go to Data and schema managment in app console i get an error that says "something went wrong".
In my hasura console it says fix env vars but i havent changed anything since 15 days.

**Comment by tirumaraiselvan** [comment]
Are you using Heroku db? 

Sometimes heroku rotates the database credentials. Can you check if the `HASURA_GRAPHQL_DATABASE_URL` which is set in your project is same as the one in Heroku (by logging to Heroku dashboard)

**Comment by SenchoDev** [comment]
Yes im using Heroku DB. I just saw this email from heroku.

Your database DATABASE_URL on instagram-senco requires maintenance. During this period, your database credentials will become read-only. Once it has completed, your database URL will have changed, but we will update your app's config variables accordingly.

This automated maintenance is a necessary part of our Hobby tier plans, Dev and Basic. Should you need more control over maintenance windows, a production database (Standard tier or higher) offers more control over database maintenance, as we are able to schedule them in advance and provide better tools for self-served maintenance.

We expect maintenance to last just a few moments depending on the size of the database. We will notify you when maintenance begins, and again once it's complete.

Maintenance (DATABASE_URL on instagram-senco) has completed successfully.

Can you explain what does this mean? Im new with hasura and heroku
