### ISSUE TITLE
1.3.0 hasura startup fails with "table not found" even thought the table does exist

### ISSUE THREAD

**Issue by seltsamonkel** [hasura/graphql-engine#5457]
Dear all,

I was trying to upgrade Hasura running in Heroku from v1.2.2 to v1.3.0, but the startup fails with the following error:
`
{"type":"startup","timestamp":"2020-07-24T00:12:55.480+0000","level":"error","detail":{"kind":"db_migrate","info":{"path":"$","error":"table not found: \"expected_loads\"","code":"unexpected"}}}
`

I logged into postgresql directly and confirmed that the table "expected_loads" did exist in the public schema.
The v1.2.2 image had no problem finding that table, so I am wondering what has been changed in v1.3.0.

I deleted the table and its dependencies from the metadata tables (e.g. hdb_function, hdb_permissions, hdb_table, etc.)  to see what happens, then the same error message with another table I have was thrown.
I am not sure if it is relevant, but those 2 tables have one thing in common: they are dummy tables created to support custom exposed SQL functions.

Could someone help?

Thank you!

**Comment by Noobshit112** [comment]
Try setting primary key to the dummy tables, it works for me.

**Comment by tirumaraiselvan** [comment]
Based on @Noobshit112 's hint, this may be related to: https://github.com/hasura/graphql-engine/issues/5153

**Comment by seltsamonkel** [comment]
@Noobshit112 Your solution fixed the issue! Thanks a lot :)

I wanted to write a migration for that, but since the migration won't startup, I had to manually login to postgres and add a primary key to that table.

**Comment by tirumaraiselvan** [comment]
@seltsamonkel Could you confirm if this was a computed field or a top-level function?

**Comment by seltsamonkel** [comment]
@tirumaraiselvan Actually I had both a computed field and a top-level function.

**Comment by tirumaraiselvan** [comment]
Thanks @seltsamonkel 

Closing this in favour of #5153
