### ISSUE TITLE
invalid x-hasura-admin-secret/x-hasura-access-key when downloading schema

### ISSUE THREAD

**Issue by Albert-Gao** [hasura/graphql-engine#5458]
Hasura v1.3.0:

I am trying to download Relay schema.

follow: https://hasura.io/docs/1.0/graphql/manual/schema/export-graphql-schema.html

tried:

```bash
gq https://my-url.herokuapp.com/v1beta1/relay -H "x-hasura-admin-secret:my-key" --introspect > schema.graphql

apollo schema:download --endpoint https://my-url.herokuapp.com/v1beta1/relay --header "x-hasura-admin-secret:my-key"
```

However, always ends up with error: `GraphQL error: invalid x-hasura-admin-secret/x-hasura-access-key`

But, I can use the same key to login the Hasura console.

I tried to add the space between the `:` and `key`, does not work as well.

What am I missing here?

**Comment by tirumaraiselvan** [comment]
@Albert-Gao Not sure. Seems to work for me. Are you sure the admin secret is correct?

**Comment by Albert-Gao** [comment]
This is the example key: `sifr&xib?Ipu$ru`

maybe because some char needs to be escaped?

I solved the problem by using the Apollo CLI and a config file, if we can confirm it is the escape-char problem in bash, will be happy to send a PR

**Comment by qqgg231** [comment]
I have the same issue. I resolved it by adding "Select" permission.
I was getting this error with only "Update" permission. So it is probably not about escaping, but I am not sure.

So it may be because "Query Explorer" was empty. But not sure.

**Comment by tirumaraiselvan** [comment]
> This is the example key: `sifr&xib?Ipu$ru`
> 
> maybe because some char needs to be escaped?
> 
> I solved the problem by using the Apollo CLI and a config file, if we can confirm it is the escape-char problem in bash, will be happy to send a PR

Yeah, possible! Can you try wrapping the headers in single quotes to prevent bash substitution and check?

**Comment by nunopato** [comment]
Just wanna add that those special characters are also problematic on the web console as well.

**Comment by williscool** [comment]
For me making sure there was no special chars fixed this for me.

**Comment by samuelchanx** [comment]
Same issue with me when using hasura cli. Tested the following 3 cases:

- Hasura console with no admin secret
- Hasura console with admin secret without special chars
- Hasura console with admin secret containing special chars

The first two cases work fine but the one with special chars simply doesn't work. Would not generate special chars for admin secret keys for now.

**Comment by tirumaraiselvan** [comment]
Turns out docker-compose does variable substitution from shell when it encounters `$`. You need to escape a `$` by adding another `$`: https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution 

So if your password is `sifr&xib?Ipu$ru`, you need to give the following environment variable in docker-compose:

```
HASURA_GRAPHQL_ADMIN_SECRET: "sifr&xib?Ipu$$ru"
```

After that, use single quote for hasura cli ( to prevent bash substitution):

```
hasura console --admin-secret 'sifr&xib?Ipu$ru'
```

**Comment by joaotux** [comment]
I solved this problem as follows:

1 - Access: https://cloud.hasura.io/
2 - Go in "Env Vars"
3 - Click on "New Env Var"
4 - Add the HASURA_GRAPHQL_JWT_SECRET the same way it is in hiroku

**Comment by shivekkhurana** [comment]
I had this problem. My issue was due to my mistake. 

The hasura engine was exposed on port 9099 to the host, but the config.yml file had port 8080. Changing that fixed the issue.

**Comment by PhiFry** [comment]
> > This is the example key: `sifr&xib?Ipu$ru`
> > maybe because some char needs to be escaped?
> > I solved the problem by using the Apollo CLI and a config file, if we can confirm it is the escape-char problem in bash, will be happy to send a PR
> 
> Yeah, possible! Can you try wrapping the headers in single quotes to prevent bash substitution and check?

This was the solution for me! And the problem is Hasura on their webpage https://hasura.io/docs/latest/schema/common-patterns/export-graphql-schema/ has double quotes `"` in their examples.

**Comment by robertjdominguez** [comment]
Thanks for pointing it out @PhiFry 👍 

hasura/graphql-engine-mono#10661 closes this and should be live shortly 🎉
