### ISSUE TITLE
Is there a way to set permissions across multiple tables at once 

### ISSUE THREAD

**Issue by tnrich** [hasura/graphql-engine#5459]
Hey there, 

I see that there is a way to "clone" the permissions for a given role from one table to another. However, this UI can be very tedious when going through all 300+ tables in my schema. I'm wondering if there is another way to set up roles/permissions for multiple tables at once? 

Thanks!
Thomas

**Comment by paf31** [comment]
One option is to programmatically generate the Hasura metadata, which is a different workflow from the usual one, with its own set of trade offs. I've written a little bit about how you could do that with a configuration like Jsonnet [here](https://hasura.io/blog/using-jsonnet-for-programmable-hasura-metadata/).

**Comment by tnrich** [comment]
@paf31 thanks for the input. We were thinking we would probably do something of the sort because creating the roles by hand would take a very long time and would be difficult to change once set up.

**Comment by GavinRay97** [comment]
@tnrich 

Using Metadata SDK (see below)
#5452
https://github.com/GavinRay97/graphql-engine/tree/feature/add-metadata-types-and-generator/metadata-types#programmatically-interacting-with-metadata

It would look roughly like this:

```ts
import { Convert } from './customMetadataConverter'
import { TableEntry } from '../generated/HasuraMetadataV2'

// Read "tables.yaml" file as text from filesystem
const tablesMetadataFile = fs.readFileSync('./metadata/tables.yaml', 'utf8')
// Convert it to JSON object with type annotation using loadYAML utility
const tablesMetadata: TableEntry[] = Convert.loadYAML(tablesMetadataFile)

// Define which role and table the base permissions should be copied from
const baseRoleName = "user"
const baseTableName = "some_table"
const baseTable = tablesMetadata.find(it => it.table.name == baseTableName)

// Sets up the object which contains all the permissions from the base table, to copy over later
const permissionKeys = ['insert_permissions', 'select_permissions', 'update_permissions', 'delete_permissions']
const basePermissions = {}
for (let key of permissionKeys) {
  // Copy over all permissions where the role belongs to the base role
  basePermissions[key] = baseTable[key].filter(perm => perm.role == baseRoleName)
}

// Helper function which merges base permissions in with existing permissions for a table
const assignBasePermissions = (tableElement: TableElement, basePermissions) => {
  for (let key of basePermissions) {
    if (tableElement[key].length == 0) tableElement[key] = []
    tableElement[key].push(...basePermissions[key])
  }
}

// Assuming for the sake of this example that we want to copy permissions to every table (except base table)
const allOtherTables = tablesMetadata.find(it => it.table.name != baseTable)
allOtherTables.forEach(it => assignBasePermissions(it, basePermissions))

// Ouput the updated "tables.yaml" to filesystem
fs.writeFileSync('./tables-updated.yaml', Convert.metadataToYAML(tablesMetadata))
```

**Comment by tnrich** [comment]
@GavinRay97 thanks for pointing me towards this resource! I'll definitely check it out. I think for the time being I'll probably write a couple of manual conversion scripts to get out data model converted over to hasura's metadata format and then try using the hasura console UI from that point forward to manage updates to the DM.
