### ISSUE TITLE
Option to disable persistent connections

### ISSUE THREAD

**Issue by eads** [hasura/graphql-engine#5465]
I have a Hasura instance connected to an Amazon RDS Aurora serverless cluster. After 5 minutes of inactivity, those can go completely idle. This is absolutely perfect for my use-case, which is an infrequently used DB but that needs lots of horsepower when it is in use.

Also, this is for a project with very minimal resources. We can live with 30 second cold starts if we only have to pay for the CPU cycles we use. It's a pretty classic data analysis use case, where there's intense activity but only in short bursts when people are working.

However, I've found that Hasura maintains persistent connections and a low level DB activity at all times. But could there be a way to disable this background chatter between the Hasura task and the DB cluster so that the DB can go to sleep when it's not in use?

**Comment by eads** [comment]
Just wanted to see if there's a way to help push this along. This would be a godsend for the budget of projects that have sporadic bursts of resource-intensive activity like the analyze-and-publish model that's common in data journalism and data science.

**Comment by sdkitono** [comment]
+1 I have just realized from my daily cost that Hasura kept a persistent connection when there is no SQL operation being sent.

**Comment by abbyblachman** [comment]
+1!

**Comment by TheHyphen** [comment]
+1

**Comment by svenkat683** [comment]
+1

**Comment by tirumaraiselvan** [comment]
Hey all,

With v2.0, you can separate the metadata DB to a different Postgres database which will avoid Hasura from performing any "persistent activity" on the user db. There is one exception which is event triggers, which you can also disable by setting: `HASURA_GRAPHQL_EVENTS_FETCH_INTERVAL: 0`

I am going to close this issue for now, but feel free to reopen/comment if the above solution doesn't work for you.
