### ISSUE TITLE
Details field for tables in console

### ISSUE THREAD

**Issue by Manubi** [hasura/graphql-engine#5467]
Hey,
It would be awesome if you could add a details field to the table in the web console so we could add some information for people who are not that familiar with the project.

<img width="729" alt="Browse_-_family_-_Data___Hasura" src="https://user-images.githubusercontent.com/20935138/88581566-a656ff80-d04d-11ea-9192-dbd03f8cdc1e.png">

Thanks!

**Comment by beerose** [comment]
Hi @Manubi! 

In `Modify` section you can add a comment for your table that will be visible in other tabs as well. Or did you mean something else than that?

<img width="371" alt="Screenshot 2020-07-30 at 18 43 03" src="https://user-images.githubusercontent.com/9019397/88950146-82392f80-d294-11ea-9921-1a975d7d3a3b.png">
<img width="247" alt="Screenshot 2020-07-30 at 18 42 56" src="https://user-images.githubusercontent.com/9019397/88950162-882f1080-d294-11ea-98a9-6de1fc10572c.png">

**Comment by beerose** [comment]
@Manubi I'm closing this issue. Please reopen if you were thinking about something other than table comments.
