### ISSUE TITLE
console: improve expand row UX in events tables

### ISSUE THREAD

**Issue by beerose** [hasura/graphql-engine#5477]
Right now we have an arrow icon to expand a row that is confused with a play button (to run a particular event). 

<img width="544" alt="Screenshot 2020-07-29 at 10 09 44" src="https://user-images.githubusercontent.com/9019397/88774397-ae18c000-d183-11ea-8796-928c1bca42dd.png">

Todo:

1. Replace the icon with `expand` icon as we have in Data Browse Rows: <img width="32" src="https://user-images.githubusercontent.com/9019397/88774612-f3d58880-d183-11ea-8ca3-9f951fe3cf81.png">

2. Make those tables consistent with table in `Data Browse Rows` — all action buttons in the first column. Meaning we should also move `redeliver` icon there.

**Comment by gnyani** [comment]
I can take a look at this, @beerose can you assign this on me, please?
