### ISSUE TITLE
cli metadata diff should not print common parts

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#5487]
`hasura metadata diff` will print the entire metadata if the local metadata and server metadata are the same. This is because it apparently prints common parts after the diff.

This is confusing from a DX pov. I don't think common parts should be part of the output unless requested via `--include-common` flag or similar?

**Comment by oliverpool** [comment]
Or maybe a flag to `--hide-common`.

Another possibility would be to use another diff library.

For instance https://github.com/pmezard/go-difflib can output a `unified diff` (on which you can add a `context` flag to specifiy the number of common lines that should be printed).

```diff
--- Original
+++ Current
@@ -1,3 +1,3 @@
 foo
-bar
+baz
```

I would be willing to take a stab at this, if the maintainers are willing to review it (and once the CLA issue has been cleared/discussed https://github.com/hasura/graphql-engine/pull/5323#issuecomment-655690734)

**Comment by purush7** [comment]
Thanks @oliverpool  for suggesting to use different library https://github.com/pmezard/go-difflib

**Comment by scriptonist** [comment]
addressed in https://github.com/hasura/graphql-engine/commit/a70e6089c89ae9a066ac47238944c01272589caf
