### ISSUE TITLE
"Edit on GitHub" links for Hasura Cloud docs are broken

### ISSUE THREAD

**Issue by leerob** [hasura/graphql-engine#5505]
👋   It appears the "edit this page on GitHub" link in the footer of the docs is broken for Cloud docs. 

![Screen Shot 2020-08-01 at 9 58 41 AM](https://user-images.githubusercontent.com/9113740/89104275-b79d6480-d3dd-11ea-8ee1-fdec3e061301.png)

The current link is `https://github.com/hasura/graphql-engine/blob/master/docs/manual/metrics/index.rst`, which throws a 404. Happy to open a PR if someone can clarify where the docs should be pointing to. It looks like the Hasura Core docs link works fine, but all of the Cloud ones are broken. Are the cloud docs not open-source, maybe?

Thanks!

**Comment by leerob** [comment]
Looks like this will be addressed with https://github.com/hasura/graphql-engine/pull/5411.

**Comment by rikinsk** [comment]
closed via #5411
