### ISSUE TITLE
Schema not loading in Explorer and Editor

### ISSUE THREAD

**Issue by nksaraf** [hasura/graphql-engine#5514]
Hi, just had a small issue with the console today. Out of the blue, the schema is not being available on the explorer when either the x-hasura-admin-secret or the authorization header is checked. It works neither is checked, I get the schema for anonymous role. The requests are working in both cases so just an issue with the console.

![](https://cdn.discordapp.com/attachments/428469959530643466/739735989441921075/Screen_Shot_2020-08-03_at_12.15.03_PM.png)

Looking into it further, the network introspection query seems to be getting all the stuff, but the schema is not available for autocomplete and explorer

![](https://cdn.discordapp.com/attachments/428469959530643466/739737119836209184/Screen_Shot_2020-08-03_at_12.20.32_PM.png)

**Comment by beerose** [comment]
The issue was partially solved with https://github.com/hasura/graphql-engine/pull/5640.

Otherwise, it will be tracked in https://github.com/hasura/graphql-engine/issues/3757.
