### ISSUE TITLE
Can't expand events invocation info in redeliver modal 

### ISSUE THREAD

**Issue by beerose** [hasura/graphql-engine#5515]
The invocation info becomes collapsed right after expanding it.

![modal-bug](https://user-images.githubusercontent.com/9019397/89175047-3681d100-d587-11ea-9f67-8c8fbd95c38b.gif)

**Comment by kentaro84207** [comment]
@beerose May I tackle this issue?

**Comment by beerose** [comment]
Sure @kentaro84207! Go ahead 🙂
