### ISSUE TITLE
Multiple subscriptions in one request

### ISSUE THREAD

**Issue by SenchoDev** [hasura/graphql-engine#5521]
I've seen that im able to use multiple mutations and queries in one request. I want to know if i am able  to use multiple subscriptions in one request?

**Comment by wwwdepot** [comment]
> Hasura follows the GraphQL spec which allows for only one root field in a subscription.

See [docs](https://hasura.io/docs/1.0/graphql/manual/subscriptions/index.html#convert-a-query-to-a-subscription)

**Comment by tirumaraiselvan** [comment]
Unfortunately, the GraphQL spec mandates only one subscription field: http://spec.graphql.org/June2018/#sec-Single-root-field

**Comment by Bessonov** [comment]
@tirumaraiselvan I would suggest revisiting it from a business perspective even if it is not supported by spec:
- It would be a competitive advantage if no one or a few vendors support it.
- It might push GraphQL maintainers to finally specify it if the feature is widely used.
- It would be harder to migrate from Hasura to other vendors (positive vendor lock-in).

Of course, it would be quite fine to put it behind a "highly experimental" flag in the documentation.

Why do I need it?
I have an offline application and want to synchronize all data while the user is offline. Currently I do it through a central update stream of changes, but I would like to change the architecture and observe entities (>30) directly and move the load from the write side (triggers) to the replica.
