### ISSUE TITLE
how to obtains incremental change data by subscription？

### ISSUE THREAD

**Issue by huashaoxu** [hasura/graphql-engine#5528]
The subscription method obtains all data rather than incremental change data, how to do？

**Comment by praveenweb** [comment]
@huashaoxu - This can be achieved by using a subscribe and refetch pattern. 

If you are looking to fetch only the new data that has changed, you can make use of Subscription query with limit 1, sorted by a unique identifier (like an id or timestamp) to listen to any new data changes. Once you get a response from this subscription you can make a normal query to refetch all the new data using the same unique identifier.

We have covered this pattern in our [React GraphQL tutorials](https://hasura.io/learn/graphql/react/realtime-feed/). Hope this helps.

There's also different [use case patterns for Subscriptions](https://hasura.io/docs/1.0/graphql/manual/subscriptions/use-cases.html#subscriptions-sample-use-cases) covered in our docs.
