### ISSUE TITLE
FATA[0000] exporting seed data: [unexpected] error while executing pg_dump: pg_dump: error: no matching tables were found  ($) 

### ISSUE THREAD

**Issue by gorress** [hasura/graphql-engine#5532]
I get this error with tables, that contains capital letters(table name). I don't have any problem with tables, that contains only lowercase letters.

**Comment by DomVinyard** [comment]
I'm getting this same error with just one of my tables, no capital, nothing unusual about the name at all

```
$ hasura seed create test_data --from-table users
// outputs > INFO created seed file successfully
```
```
$ hasura seed create test_data --from-table orgs
/* outputs:
FATA[0001] exporting seed data: pg_dump request: 500 
{
  "path": "$",
  "error": "internal exception while executing pg_dump",
  "code": "unexpected"
} 
*/
```

Any other possible causes?

**Comment by corysimmons** [comment]
@scriptonist This needs reopened. It's not just a capital letter thing, it's the pg_dump trying to consume an illegal character thing.
