### ISSUE TITLE
update geojson docs

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#554]
accompanying documentation for https://github.com/hasura/graphql-engine/pull/513

**Comment by rikinsk** [comment]
related to #554

**Comment by Soundug** [comment]
@shahidhk Should I add postgis in readme or docs folder?

**Comment by shahidhk** [comment]
@Soundug Are you familiar with PostGIS? If yes, you can contribute to the documentation, not the readme.

**Comment by dsandip** [comment]
closing this one in favor of #505 (added the description as a comment there)
