### ISSUE TITLE
Support for "connect" and "disconnect" websocket events with subscriptions

### ISSUE THREAD

**Issue by amille14** [hasura/graphql-engine#5540]
Currently it seems that there's no way to respond when a client connects via websocket to Hasura and when they subsequently disconnect. It would be great if we could get an event that's triggered whenever one of these things happens. This way it becomes much easier to track which users are "online", and we can write event handlers to respond to things like users abruptly closing a browser or losing internet connection.

Currently [this article](https://hasura.io/blog/building-a-realtime-chat-app-with-graphql-subscriptions-d68cd33e73f/) recommends implementing "online" user status by having each client ping the server every 2 seconds. This doesn't scale very well when you have thousands or millions of users. Using Hasura's existing event system to emit a simple `CONNECTED` or `DISCONNECTED` event along with some additional info identifying the client/user (some kind of client id or the headers used when creating the websocket connection maybe?) would be really great.

**Comment by tirumaraiselvan** [comment]
Related: https://github.com/hasura/graphql-engine/issues/3168

**Comment by tirumaraiselvan** [comment]
@amille14 Can you post your thoughts in the issue #3168 and we can close this?

**Comment by amille14** [comment]
@tirumaraiselvan done, thanks!

**Comment by tirumaraiselvan** [comment]
Thanks!
