### ISSUE TITLE
Could not verify JWT: JWTExpired

### ISSUE THREAD

**Issue by ewelinam10** [hasura/graphql-engine#5545]
**Header 'Authorization' is not valid.** 
I've parsed my token and it looks good. But when i click on hasura api decode JWT it shows message
Could not verify JWT: JWTExpired. 
But I don't have idea why, i coudnt find my problem solved anywhere.

What should i post here more?
Greetings!

**Comment by praveenweb** [comment]
@ewelinam10 - The JWT token issued has an expiry time attached to it. It can be checked under the key `exp` and it will be a timestamp. Check the value of that. It seems it has expired. 

You can regenerate a new token using the Authentication server that you used to generate the initial token.

**Comment by ewelinam10** [comment]
Okay so the value of exp is 1596596949 and when i parse it looks like its to 05.08.2020 but why? I'm running hasura by docker. This  is the command which i am using to run docker with hasura 
docker run -d -p 8080:8080 \
-e HASURA_GRAPHQL_ADMIN_SECRET="#################################" \
    -e HASURA_GRAPHQL_JWT_SECRET='{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\########################################################################################################################################################################################################################################################################################==\n-----END CERTIFICATE-----"}' \
  -e HASURA_GRAPHQL_DATABASE_URL=url_to_my_database \
  -e HASURA_GRAPHQL_ENABLE_CONSOLE=true \
  hasura/graphql-engine:latest

**Comment by praveenweb** [comment]
@ewelinam10 - What is the Authentication provider? Who is issuing this JWT token? (For example Auth0 or Firebase Auth or some custom Auth server)

Hasura doesn't generate this JWT token. So you will need to regenerate this token using the Auth provider used.

**Comment by ewelinam10** [comment]
in my case is Auth0 - i generate that token using your website https://hasura.io/jwt-config/ ... do you have any ideas why my exp date is science 5 days.. ?

**Comment by ewelinam10** [comment]
[](url)
![image](https://user-images.githubusercontent.com/17653335/89761015-cc6cad00-daed-11ea-94c3-f7c67c836460.png)

this is token's settings by default. But even if generate token once again using that website which i posted above its expired.

**Comment by praveenweb** [comment]
@ewelinam10 - The page https://hasura.io/jwt-config/ is used for generating the configuration that can be configured as ENV. Generating the Auth0 token should happen via Auth0 UI/API.

You can probably refer to this doc for generating a sample JWT token, but I would recommend you using the Auth0 sample react app as recommended by Auth0 themselves to generate and test the token - https://github.com/auth0-samples/auth0-react-samples

**Comment by ewelinam10** [comment]
Yep i know that this page is used for that but why it generates not valid token? Isnt it a problem ?
So your approach you propse in yours doc https://hasura.io/learn/graphql/hasura/authentication/3-setup-env-vars-hasura/ is not working properly?

**Comment by ewelinam10** [comment]
And as i assume you recommend to use hooks Auth0 which generates me token but this is the case in my application. This is another case. I would like to use your hasura console which i am running by docker, and i understand that this is the only way that i could run docker with that jwt i generate on that pagehttps://hasura.io/jwt-config/
