### ISSUE TITLE
Role names without white spaces

### ISSUE THREAD

**Issue by KirillSBarsukov** [hasura/graphql-engine#5553]
Hey folks!

Whenever I create a new Role under the Permissions tab, a new role. I cannot create a role name with white spaces. For example, `Sales Manager`
Interestingly, I made that type of role name before. To fix that I usually copy `Sales Manager` to an input field and then change words separately. For example, `Sales Manager` becomes `Sales Moderator`.

Thank you

**Comment by wwwdepot** [comment]
It's just [trimming whitespace](https://github.com/hasura/graphql-engine/blob/master/console/src/components/Services/Data/TablePermissions/Permissions.js#L485) when you're typing. I'd use `snake_case` or `kebab-case` over spaces between words.

**Comment by KirillSBarsukov** [comment]
Is it something new?  I have a bunch of roles with spaces
