### ISSUE TITLE
Unable to secure instance with admin secret

### ISSUE THREAD

**Issue by the-jackalope** [hasura/graphql-engine#5563]
Hello,

I'm using Kubernetes to run Hasura and configured my `deployment.yaml` with the `HASURA_GRAPHQL_ADMIN_SECRET` environment variable in order to secure my instance. I am able to verify that the Kubernetes pod running my instance has `HASURA_GRAPHQL_ADMIN_SECRET` set and that the secret it has matches mine.

However I am completely unable to use the admin secret to log into the instance, meaning I cannot secure it. When I visit the console in my browser and attempt to log in with the secret I am denied. When I set the `admin_secret` in `config.yaml` and attempt to use `hasura console` to log in I am denied with the message: 

```
FATA[0001] error creating migrate instance: cannot create migrate instance: Data Error: {"path":"$","error":"invalid x-hasura-admin-secret/x-hasura-access-key","code":"access-denied"}
```

The instance appears to work normally when I do not attempt to set `HASURA_GRAPHQL_ADMIN_SECRET`. Am I doing something wrong here? The docs appear to indicate that this should "just work".

**Comment by the-jackalope** [comment]
The error I get in the web UI is:
```
Failed to load console options: {"path":"$","error":"x-hasura-admin-secret/x-hasura-access-key required, but not found","code":"access-denied"}
```
In my network inspector I can see that when I click the button to submit my password a `x-hasura-admin-secret` header with the password I input - is that different from a `x-hasura-admin-secret/x-hasura-access-key` header?

**Comment by hgiasac** [comment]
@the-jackalope can you double check admin secret to see if there is any extra special character such as spaces? Many Hasura users use Kubernetes, and they don't have any problem with it. 
You also can test admin secret locally with Docker

**Comment by the-jackalope** [comment]
Double checked - it's alphanumeric with no special characters. That's why this is particularly baffling. I will try deleting and recreating the K8s deployment tomorrow and see if that does anything. Will also give testing on local Docker a go too.

**Comment by the-jackalope** [comment]
I completely deleted and redeployed and it seems to work fine now 🤷‍♂️ 

Thanks for the assistance - it's completely possible I messed something up and just didn't catch it.
