### ISSUE TITLE
Security alert on Hasura windows

### ISSUE THREAD

**Issue by baptistemanson** [hasura/graphql-engine#5571]
When downloading and booting hasura.exe on windows, I get this alert by Avast:
![image](https://user-images.githubusercontent.com/5444992/89929195-c219e400-dbbd-11ea-81ed-fd541440006b.png)
IDP.Generic seems to be a fairly common threat type.
My Avast is up to date. My machine is not infected by anything rn according to Avast.

**Comment by Conorrr** [comment]
Presumably this relates to v1.3 of the hasura-cli.

Related to https://github.com/hasura/graphql-engine/issues/3922

**Comment by baptistemanson** [comment]
v1.3.1-beta which is the latest available to my knowledge.

**Comment by scriptonist** [comment]
Closing in favour of https://github.com/hasura/graphql-engine/issues/7147, which aims to add a solution for this issue
