### ISSUE TITLE
Fix stringified JSON in some logs sub-keys

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#5582]
* prepared arguments in `query-log` are printed as strings (stringified JSON).

**Comment by tirumaraiselvan** [comment]
Note that prepared arguments are not always key-value pairs. For example,

Query:

```
query($id: Int!) {
  test(where: {id: {_eq: $id}}) {
    id
    name
  }
}
```

Variables:

```
{
  "id": 1
}
```

The `query-log` prints: 

```
"prepared_arguments":["{\"x-hasura-role\":\"admin\"}","1"]
```

**Comment by BenHizak** [comment]
Hi,
Has this issue been addressed?

**Comment by Naveenaidu** [comment]
Hey @BenHizak, Yes the issue has been addressed and fixed by this  https://github.com/hasura/graphql-engine/pull/5615
