### ISSUE TITLE
Wrong migration column name (Camelcase name)

### ISSUE THREAD

**Issue by TheoWolf** [hasura/graphql-engine#5587]
Hello, 
I'm using Hasura  1.3.0 and the hasura-cli (v2 cli) docker is not migrating the correct column name. uploadedDatetime column is always changed to uplaodeddatetime I have issues only with this column. I didn't have this issue with the v1 cli or the non docker cli. please let me know if you have any workaround for this. 
Thanks

**Comment by scriptonist** [comment]
Hi @TheoWolf thanks for reporting this, will you provide a bit more details on how I can reproduce this?

**Comment by TheoWolf** [comment]
Hi @scriptonist 
We were using Hasura 1.1.0 and our database fields were in snake case style (e.g. created_by_id, uploaded_datetime, ...) and once Hasura 1.3.0 got released we decided to migrate to the latter to get the faster migration and other gems. After moving to 1.3.0 version and upgrade to CLI v2, we decided to use camel case style for our fields, however, uploadedDatetime is always created as uploadeddatetime even though the SQL files were correct (in camel case). I fixed this issue by renaming the uploadedDatetime field to uploadedDatetime.
Now, I have a much bigger problem, I get FatalError when running mutations on fields renamed to camelCase, especially on foreign keys.
let me know if this makes sense for you.
Thanks

**Comment by tirumaraiselvan** [comment]
@TheoWolf How did you change from snake case to camel case? Did you manually change the migration files?

**Comment by TheoWolf** [comment]
@tirumaraiselvan No, we use the Hasura console to change our database schema

**Comment by tirumaraiselvan** [comment]
@TheoWolf We weren't able to reproduce this at our end.

Could you pls share 1) the table definition, 2) the migration to change the column and 3) the sample query that fails.
