### ISSUE TITLE
Feature Request: Remote Schema complex header redirects

### ISSUE THREAD

**Issue by jascodes** [hasura/graphql-engine#5589]
I following Hasura since inception and its getting better and better. One quick note about remote schemas though. If you try to add github api without Authorization header, it gives me error; as it can't fetch schema without it. What I was looking to do was to redirect Authorization header from client; so the end user can use his/her account. 

Additionally it makes sense to add option of custom header mapping. e.g  Github_Authorization -> Authorization . In this way I can use multiple remote with Authorization header. Similar idea of mapping node for let's say user node from github can to renamed to github_user . Aside from mapping, use of namespace is another option where all node and headers are prefixed with remote schema name. I am cool with any approach.

**Comment by tirumaraiselvan** [comment]
Thanks for your feedback. You raise valid points and there are issues already existing for some of these:

1. Auth header: https://github.com/hasura/graphql-engine/issues/4890
2. Prefixing remote schema: https://github.com/hasura/graphql-engine/issues/3518

**Comment by jascodes** [comment]
@tirumaraiselvan Thanks for getting back. Thats great, I will subscribe and follow them. Thanks.

**Comment by liuxiaodong008008** [comment]
Hi @jascodes, do you get the header mapping feature or alternative solution? I ran into the same problem.
