### ISSUE TITLE
Setting HASURA_GRAPHQL_TX_ISOLATION not working properly in Hasura Cloud 

### ISSUE THREAD

**Issue by dknaus-safenow** [hasura/graphql-engine#5596]
The setting HASURA_GRAPHQL_TX_ISOLATION to control the transaction isolation works as documented in https://hasura.io/docs/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html when using the docker image (tested successfully with hasura/graphql-engine:v1.3.0.cli-migrations-v2 and with hasura/graphql-engine:v1.3.1-beta.1.cli-migrations-v2): The default ist "read-commited" and I am able to explicitly set it to "repeatable-read" and "serializable" and the value is actually used for all transactions. 

So far so good. However, things are very different in Hasura Cloud. It does not work as expected:
- the default value is "serializable" instead of "read-commited"
- the value cannot be changed (at least not to the point where the transactions use the explicitly configured value). Neither via the Tenant API nor via the Hasura Cloud Console

Steps to reproduce:
A. Wrong Default value: 
1. Create a new Project in Hasura Cloud
2. Lauch Console
3. Go to "Tab Data" -> "SQL"
4. Execute `select current_setting('transaction_isolation');`
5. The result is "serializable"  instead of "read-commited"

B. Change to "read-committed" not working
1. In Hasura Cloud  UI: "Env Vars" -> "New Env Var "
2. Choose "HASURA_GRAPHQL_TX_ISOLATION"
3. Choose value "read-commit"
4. Config error "Error for tenant. Details: Vault error for tenant. Error: Only expecting read-committed / repeatable-read / serializable" appears
5. `select current_setting('transaction_isolation');` still returns "serializable"
(Please note the difference in spelling in the error message vs the value from the dropdown: "read-committed" vs "read-commited ")

C. Change to "repeatable-read" not working
1. In Hasura Cloud  UI: "Env Vars" -> "New Env Var "
2. Choose "HASURA_GRAPHQL_TX_ISOLATION"
3. Choose value "repeatable-read"
4. Other than in above in B , no error appers
5. But  `select current_setting('transaction_isolation');` still returns "serializable"

**Comment by dknaus-safenow** [comment]
Update: things seem to have changed a bit: I can not select the other transaction isolation types in the hasura cloud UI without errors. But still: whatever I chose there, `select current_setting('transaction_isolation');` returns `serializable`

**Comment by shahidhk** [comment]
Hello! This has been fixed and will be rolled out with the next update.

**Comment by shahidhk** [comment]
The fix is now live on Hasura Cloud.

**Comment by dknaus-safenow** [comment]
Cool. confirmed. Thank you! :+1:
