### ISSUE TITLE
Setting the HASURA_GRAPHQL_JWT_SECRET for hasura cloud from API does not work.

### ISSUE THREAD

**Issue by gurukulkarni** [hasura/graphql-engine#5601]
Hello,
As per the [documentation](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#configuring-jwt-mode), we can use the `HASURA_GRAPHQL_JWT_SECRET` to see the JWT secret (this is the only way for hasura cloud!) 
However since the value of the key is JSON and is included in json it causes some troubles and requires ugly escaping.

Further ~despite~ because of the fact that [hasura cloud](https://cloud.hasura.io/) itself uses the graphql mutation to update the JWT token, it is ~not~ possible to do that from a curl request e.g.
from the network of the cloud console when we update the JWT we see : 
```
{
	"operationName": "updateTenant", 
	"variables": {
		"tenantId": "valid-tenant-uuid-here", 
		"currentHash": "01somevalidhashhere", 
		"envs": [
			{
				"key": "HASURA_GRAPHQL_JWT_SECRET", 
				"value": "{\n    \"key\": \"some very secret stuf that is reasonably long and hopefully secure with some digits 0123456789 for good measure\",\n    \"type\": \"HS256\"\n}"
			}
		]
	},
	"query": "mutation updateTenant($tenantId: uuid!, $currentHash: String!, $envs: [UpdateEnvObject!]!) {\n  updateTenantEnv(currentHash: $currentHash, tenantId: $tenantId, envs: $envs) {\n    hash\n    envVars\n    __typename\n  }\n}\n"}
```

This is somehow working ~however it is NOT working~ when the same is called from a curl request (generated by chrome dev tools) and we get : 
This was because of not updating the hash after once updating the env.
~{"errors":[{"extensions":{"path":"$","code":"unexpected"},"message":"{\"location\":\"config\",\"message\":\"configuration has moved on\"}"}]}~

The request was : 
```
curl 'https://data.pro.hasura.io/v1/graphql' \
  -H 'authority: data.pro.hasura.io' \
  -H 'accept: */*' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'origin: https://cloud.hasura.io' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://cloud.hasura.io/project/e4799ffd-46c5-4afc-a81e-657e60ef19c1/env-vars' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: _lfa=ey0%3D; intercom-id-rucirpb3=11550475-a0d3-4266-b8f8-cb991ba0b3dc; _gcl_au=1.1.1434532956.15323232321; hasura-lux=MTU5SEZPd9--c6' \
  --data-binary $'{"operationName":"updateTenant","variables":{"tenantId":"e0913a86-ab37-4564-aa26-a180ea0916d8","currentHash":"82ee2af43ecdd5fe4e3bbef10fe939a958583808","envs":[{"key":"HASURA_GRAPHQL_JWT_SECRET","value":"{\\n    \\"key\\": \\"some very secret stuf that is reasonably long and hopefully secure with some digits 0123456789 for good measure\\",\\n    \\"type\\": \\"HS256\\"\\n}"}]},"query":"mutation updateTenant($tenantId: uuid\u0021, $currentHash: String\u0021, $envs: [UpdateEnvObject\u0021]\u0021) {\\n  updateTenantEnv(currentHash: $currentHash, tenantId: $tenantId, envs: $envs) {\\n    hash\\n    envVars\\n    __typename\\n  }\\n}\\n"}' \
  --compressed
```

**So the questions / suggestions still valid are :** 

* Could you please include a working example of how should the secret be uploaded on the [hasura cloud API docs](https://hasura.io/docs/cloud/1.0/manual/api-reference.html#update-env-vars)?
* Would it be possible to maybe NOT use a JSON inside of a JSON and maybe use individual keys that are then internally maybe converted to json?
* If this is not possible, then maybe the value to the env keys `"key":"HASURA_GRAPHQL_JWT_SECRET"` should accept not a string but maybe a json object itself?
* Otherwise maybe could be better to possibly find a way to convert this json to a string somehow that you can get back later? maybe base64? (just a hint -- not very nice TBH)

**Comment by shahidhk** [comment]
We've noted down your feedback on the API.

To update any env var, you need to first know the hash of the current config. To get that, use the following query:
```gql
query getTenantENV {
  getTenantEnv(
    tenantId: "7a79cf94-0e53-4520-a560-1b02bf522f08"
  ) {
    currentHash: hash
  }
}
```

Then make a mutation to update the required env var:

```gql
mutation updateTenantEnv {
  updateTenantEnv(
    tenantId: "7a79cf94-0e53-4520-a560-1b02bf522f08"
    currentHash: "6902a395d70072fbf8d36288f0eacc36c9d82e68"
    envs: [
      {key: "HASURA_GRAPHQL_JWT_SECRET", value: "<escaped-json-string>"},
    ]
  ) {
    hash
    envVars
  }
}
```

If the `currentHash` does not match, API will throw an error. This is to make sure simultaneous updates to the env vars doesn't result in an inconsistent state.

Feel free to re-open the issue if you have more questions.

**Comment by Mouvedia** [comment]
The only header you actually need is cookie.
i.e `hasura-lux` is required
