### ISSUE TITLE
remote schemas v1.3.0

### ISSUE THREAD

**Issue by sasog23** [hasura/graphql-engine#5611]
when i query (remote schema/table) from graphiql hasura doesn't Forward headers to the remote schema.
it's treated as anonymous user ( when creating remote schema i've checked Forward all headers from client )

in the console i have set x-hasura-admin-secret, x-hasura-user-id and x-hasura-role
if i remove select permission for anonymous role in the remote table/schema, i get an error 
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.organizations.selectionSet.bank_accounts",
        "code": "validation-failed"
      },
      "message": "field \"bank_accounts\" not found in type: 'organizations'"
    }
  ]
}

**Comment by tirumaraiselvan** [comment]
It seems your remote schema is another Hasura instances? What does the remote schema configuration look like? Does it also use `x-hasura-admin-secret` to authenticate?

**Comment by sasog23** [comment]
not relevant any more
