### ISSUE TITLE
Support for EXPLAIN ANALYZE-ing generated SQL to help tweak perf with indices, etc.

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#562]

**Comment by dsandip** [comment]
requested by:
Madhu from uncommon
@benoitscherrer (Discord)

**Comment by dsandip** [comment]
@karthikvt26 Let's add a button next to `History` labelled `Analyze`:

![console-analyze-button](https://user-images.githubusercontent.com/24300818/46952197-cf401780-d0a7-11e8-8fbf-d1a16d4e5a81.png)

This button will:
a) If there are multiple graphql queries in GraphiQL, prompt user to choose one of them (just like the `Run` button):

![console-select-one-query](https://user-images.githubusercontent.com/24300818/46952581-e0d5ef00-d0a8-11e8-9d3c-11802053b108.png)

b) If there is a single GraphQL query or one of the multiple ones has been selected, pop open a modal. The modal will show a list of the top level nodes in the query, with the first one preselected. For each top level node in this list, we'll show the generated SQL along with corresponding execution plan:

![console-query-analysis-modal](https://user-images.githubusercontent.com/24300818/46952438-7624b380-d0a8-11e8-9187-7e50b0b167c1.png)

@rikinsk @0x777 FYI

**Comment by dsandip** [comment]
@0x777 Can we also log the generated SQL when a debug/verbose flag is enabled? Reference: https://app.intercom.io/a/apps/rucirpb3/inbox/inbox/mentions/conversations/18242089570

**Comment by shahidhk** [comment]
Re-opening to track console improvements.
