### ISSUE TITLE
console: don't show complete list of non-trackable functions

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#5627]
![image](https://user-images.githubusercontent.com/8663570/90715670-9aff9880-e2c8-11ea-8a08-f789d5319f48.png)

PG has lots of functions and when you launch console for the first time it is quite overwhelming. We can either hide non-trackable functions or just show 5 of them and have a `Show All` button to show the full list.

**Comment by rikinsk** [comment]
Closed via #5657
