### ISSUE TITLE
Query int as string?

### ISSUE THREAD

**Issue by m0ngr31** [hasura/graphql-engine#5628]
Is there a way that I can search for a partial match on a `bigint` field? Something similar to `_like` would be great, but I can't figure out how to cast during a query...

**Comment by wwwdepot** [comment]
You might want to use that in a [custom function](https://hasura.io/docs/1.0/graphql/manual/schema/custom-functions.html).

**Comment by m0ngr31** [comment]
Yeah, that's what I figured. The problem is that it's part of a big query in Apollo, so I need to figure out how to turn the entire query into a custom function.
