### ISSUE TITLE
Hasura - Events ENV url

### ISSUE THREAD

**Issue by leomotta121** [hasura/graphql-engine#5635]
The 1.3 version it does not allow to compose event url with ENV vars, would be nice to have something like ACTION_BASE_ENDPOINT.

it happens that many times, the event will trigger our own api not only third part services or micro services, and having to create many env vars for each route in this case not really cool

the current console 1.3.0 validates the following as invalid url

```
{{EVENT_BASE_ENDPOINT}}/eventRoute
```

**Comment by tirumaraiselvan** [comment]
Tracking this here: https://github.com/hasura/graphql-engine/issues/2483

This will be released very soon.
