### ISSUE TITLE
Allow using computed fields in row-level permissions

### ISSUE THREAD

**Issue by amille14** [hasura/graphql-engine#5646]
It would be really helpful to be able to use computed fields where the only argument is the current table row in row level permissions. Currently, computed fields don't appear in the list.

This would allow you to set up something like select permissions on a `user` where `full_name` equals "Bob" or whatever, assuming `full_name` is a computed field that uses only the current user row as input and just combines the row's `first_name` and `last_name` fields.

In a more real example, this is particularly useful because it allows you to encapsulate complex permission logic into a single, reusable function, rather than being forced to manually add it through the console's permission ui which can get very tedious and difficult to test, especially in cases where you're repeating the same chunk of permissions across multiple roles and actions with only slight variations.

**Comment by altschuler** [comment]
My use-case for this: I have an `expiry` field (a `date`) in a table called `things`, and I need to only allow selecting rows where `expiry` is in the future. I would then create a computed field called `is_expired` which returns a boolean indicating whether `expiry` is in the future, and would like to use that field in a permission config.

Sidenote: I haven't actually found a workaround for this yet, I have tried using a view (say the original is called `things`, then I created a `things_computed` which adds an `is_expired` column), however I cannot seem to use the view-relation in a permission check either, so I'm currently at a loss. The only other option I see is to create an entire new view that `selects * from things where [expiry is in the future]` but that require changing a lot of queries and makes it way more cumbersome (sometimes I _do_ want to include the expired rows).
