### ISSUE TITLE
Custom X-Hasura headers ignored when authorization passed

### ISSUE THREAD

**Issue by martinpengellyphillips** [hasura/graphql-engine#5647]
Consider an app that allows anonymous viewing of shared data through a 'code'. The code is passed via an `X-Hasura-Share` header. An Hasura permission role `viewer` is created and set as default for the unauthenticated. This viewer role enables read only permission for the row whose `id` matches the `X-Hasura-Share` value. This all works great.

However, when an authenticated user (passing `authorization` header with correct token) tries to use that same share code, Hasura returns no data. This happens even though the `X-Hasura-Role` is set to `viewer` in the request headers (and the authenticated user is allowed that role). Note that Hasura does not error at all, it just returns an empty data set. It seems that as soon as the auth header is set the `X-Hasura-Share` header is ignored.

Is this behaviour expected or a bug?

**Comment by tirumaraiselvan** [comment]
Are you also setting `x-hasura-default-role` in the token ?

**Comment by martinpengellyphillips** [comment]
Yes, I have `x-hasura-default-role` set to `user` in the jwt (via Auth0 rules).

**Comment by tirumaraiselvan** [comment]
@martinpengellyphillips Does the `user` role also refer to `x-hasura-share` variable in it's permissions. Or is it just the `viewer` role? 

Note that Hasura can only run an operation as one role at a time.

**Comment by tirumaraiselvan** [comment]
@martinpengellyphillips Could you share the custom claims of your JWT token? Ideally, you should be able to become `viewer` role if you have set it from the client and the claim allows it via `x-hasura-allowed-roles`.

**Comment by martinpengellyphillips** [comment]
Thanks @tirumaraiselvan - that's what I suspected so thank you for confirming and linking me to the relevant issue. 

Is it documented somewhere that client headers (except 'role' ) are ignored when authenticated? I did do an initial search, but might have missed it.

**Comment by tirumaraiselvan** [comment]
I think it may not be documented: https://github.com/hasura/graphql-engine/issues/4101

**Comment by martinpengellyphillips** [comment]
My original question is answered (is it expected behaviour or a bug) so I will close this issue and follow the other one's linked to. Thanks again!
