### ISSUE TITLE
_is_null, _eq: null, _neq: null do not work

### ISSUE THREAD

**Issue by bconnorwhite** [hasura/graphql-engine#5670]
I've never been able to get `_is_null`, `_eq: null`, or `_neq: null` to work, has anyone else seen this?

(This has been the case across multiple versions, 1.0.0 through 1.3.0)

**Comment by wwwdepot** [comment]
I have no problem with query like this:

```
query MyQuery {
  orders(where: {order_date: {_is_null: true}}) {
    id
  }
}
```

**Comment by tirumaraiselvan** [comment]
Can you try the syntax suggested by @wwwdepot above ?

**Comment by bconnorwhite** [comment]
`_is_null` was failing for another reason, and I didn't realize null was invalid for `_eq` and `_neq`.

Working now, thanks!
