### ISSUE TITLE
Hasura return 404 when using Google Cloud SQL via sql-proxy container

### ISSUE THREAD

**Issue by izznatsir** [hasura/graphql-engine#5674]
Hello!

 So, today I tried to deploy Hasura using docker-compose containing gce-proxy and hasura/graphql-engine container. The logs say that the connection to Cloud SQL is successful, but strangely, when I try to open the console on the browser Hasura returns 404 code and a JSON saying resource does not exist. Repo containing dokcer-compose.yml, docker-compose logs, and returned json are specified below.

I found deploymnet guide for GKE and Cloud SQL, but I don't understand Kubernetes. How to do the same with docker-compose? I choose docker-compose to save cost instead of Kubernetes.

I also tried to connect from psql through exposed gke-container, and it works as expected.

**Repo:**
https://github.com/izznatsir/hasura-with-cloud-sql.git

**Docker Logs**

> cloud_sql_proxy_1  | 2020/08/26 14:56:40 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
> 
> cloud_sql_proxy_1  | 2020/08/26 14:56:40 using credential file for authentication; email=sql-hasura-admin@api-izznatsir-com.iam.gserviceaccount.com
> 
> cloud_sql_proxy_1  | 2020/08/26 14:56:41 Listening on 0.0.0.0:5432 for api-izznatsir-com:asia-southeast2:hasura
> 
> cloud_sql_proxy_1  | 2020/08/26 14:56:41 Ready for new connections
> 
> cloud_sql_proxy_1  | 2020/08/26 14:56:42 New connection for "api-izznatsir-com:asia-southeast2:hasura"
> 
> cloud_sql_proxy_1  | 2020/08/26 14:56:42 New connection for "api-izznatsir-com:asia-southeast2:hasura"
> 
> cloud_sql_proxy_1  | 2020/08/26 14:56:42 New connection for "api-izznatsir-com:asia-southeast2:hasura"
> 
> cloud_sql_proxy_1  | 2020/08/26 14:56:42 New connection for "api-izznatsir-com:asia-southeast2:hasura"
> 
> cloud_sql_proxy_1  | 2020/08/26 14:56:42 New connection for "api-izznatsir-com:asia-southeast2:hasura"
> 
> cloud_sql_proxy_1  | 2020/08/26 14:56:42 New connection for "api-izznatsir-com:asia-southeast2:hasura"
> 
> cloud_sql_proxy_1  | 2020/08/26 14:59:43 Client closed local connection on 172.18.0.2:5432
> 
> cloud_sql_proxy_1  | 2020/08/26 14:59:43 Client closed local connection on 172.18.0.2:5432
> 
> cloud_sql_proxy_1  | 2020/08/26 14:59:43 Client closed local connection on 172.18.0.2:5432
> 
> hasura_1           | {"type":"startup","timestamp":"2020-08-26T14:56:42.000+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":4000},"enabled_log_types":["http-log","websocket-log","startup","webhook-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":true,"enable_console":false,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":true,"port":8080}}}
> 
> hasura_1           | {"type":"startup","timestamp":"2020-08-26T14:56:42.000+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@cloud_sql_proxy:5432/hasura"}}}
> 
> hasura_1           | {"type":"startup","timestamp":"2020-08-26T14:56:42.000+0000","level":"info","detail":{"kind":"catalog_migrate","info":"Already at the latest catalog version (37); nothing to do."}}
> 
> hasura_1           | {"type":"startup","timestamp":"2020-08-26T14:56:42.000+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 17","instance_id":"ef521e9e-620d-4cfa-a920-5b0a36884714","message":"listener thread started"}}}
> 
> hasura_1           | {"type":"startup","timestamp":"2020-08-26T14:56:42.000+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 18","instance_id":"ef521e9e-620d-4cfa-a920-5b0a36884714","message":"processor thread started"}}}
> 
> hasura_1           | {"type":"startup","timestamp":"2020-08-26T14:56:42.000+0000","level":"info","detail":{"kind":"event_triggers","info":"preparing data"}}
> 
> hasura_1           | {"type":"startup","timestamp":"2020-08-26T14:56:42.000+0000","level":"info","detail":{"kind":"event_triggers","info":"starting workers"}}
> 
> hasura_1           | {"type":"startup","timestamp":"2020-08-26T14:56:42.000+0000","level":"info","detail":{"kind":"scheduled_triggers","info":"preparing data"}}
> 
> hasura_1           | {"type":"startup","timestamp":"2020-08-26T14:56:42.000+0000","level":"info","detail":{"kind":"telemetry","info":"Help us improve Hasura! The graphql-engine server collects anonymized usage stats which allows us to keep improving Hasura at warp speed. To read more or opt-out, visit https://hasura.io/docs/1.0/graphql/manual/guides/telemetry.html"}}
> 
> hasura_1           | {"type":"startup","timestamp":"2020-08-26T14:56:42.000+0000","level":"info","detail":{"kind":"server","info":{"time_taken":0.464193044,"message":"starting API server"}}}
> 
> hasura_1           | {"type":"http-log","timestamp":"2020-08-26T15:18:28.107+0000","level":"error","detail":{"operation":{"error":{"path":"$","error":"resource does not exist","code":"not-found"},"request_id":"11ea8ee4-658e-4796-89bc-a68cf48503dd","response_size":65,"raw_query":""},"http_info":{"status":404,"http_version":"HTTP/1.1","url":"/","ip":"36.71.232.27","method":"GET","content_encoding":null}}}
> 
> hasura_1           | {"type":"http-log","timestamp":"2020-08-26T15:18:28.107+0000","level":"error","detail":{"operation":{"error":{"path":"$","error":"resource does not exist","code":"not-found"},"request_id":"5a6796d9-42c3-4c96-be28-7bf51df9f300","response_size":65,"raw_query":""},"http_info":{"status":404,"http_version":"HTTP/1.1","url":"/favicon.ico","ip":"36.71.232.27","method":"GET","content_encoding":null}}}

**Response JSON**
`{
    "path": "$",
    "error": "resource does not exist",
    "code": "not-found"
}`

**Comment by tirumaraiselvan** [comment]
If you look at the following snippet in the first log line:

```
"enable_console":false
```

It seems you do not have console enabled. Please enable it via `HASURA_GRAPHQL_ENABLE_CONSOLE` env var and it should work.

**Comment by izznatsir** [comment]
Yeah, you're right! Instead of CONSOLE, I wrote COSNOLE as my env variable. My bad. Thanks for your help!
