### ISSUE TITLE
Document Postgres max connections requirement

### ISSUE THREAD

**Issue by G-Goldstein** [hasura/graphql-engine#5681]
A few months back, we had an issue running multiple Hasura instances against a single database, in our dev environment, where it seems that the database couldn't support the connections and that Hasura may require multiple active connections at any time. We think we resolved it by increasing the `max_connections` flag on our database.

Does the Hasura graphql engine require multiple connections to a postgres instance, and either way could this be documented on the [Postgres requirements](https://hasura.io/docs/1.0/graphql/core/deployment/postgres-requirements.html) page of the documentation?

**Comment by RodolfoSilva** [comment]
@G-Goldstein take a look: https://hasura.io/docs/1.0/graphql/core/deployment/graphql-engine-flags/reference.html

You can use the `HASURA_GRAPHQL_PG_CONNECTIONS` to define a limit.

**Comment by G-Goldstein** [comment]
Thanks, that's ideal!
