### ISSUE TITLE
Reference from a Hasura table to Hasura Action | feature proposal

### ISSUE THREAD

**Issue by mezhik91** [hasura/graphql-engine#5682]
Hi,

Now in Hasura 1.3 there is a great feature called Actions. Great thing also about Actions is that we can create references from Actions to Hasura database table, but unfortunately it turned out that we can not do opposite. We can create a reference only to some remote schema which is great but the thing is that usually it is overkill to serve GraphQL server somewhere on a cloud function in order to fetch some simple data.

Or let's consider a use case.
I manage my users and their's profiles in Firebase.
In Hasura I have a table **posts** which has a field **user_id** which stores user's Firebase ID. 
Now I want to fetch posts with user profile info which is a trivial operation and I do not want to bring so much complexity like setup Apollo server and serve it as micro-graphql-server which has only one query on my cloud function.

I know that we can come across performance issue because if I query 10 posts then 10 requests to the REST endpoint (action) will be done. But maybe it could be possible to implement something like DataLoader which collects ids and then does only one call where all profiles will be resolved and properly mapped. 

It would be great to get your feedback,
Thank you

**Comment by tirumaraiselvan** [comment]
Could you add your use-case in this issue: https://github.com/hasura/graphql-engine/issues/4900 and close this?

**Comment by mezhik91** [comment]
@tirumaraiselvan yes, sure! I have added.
Thanks for the feedback
