### ISSUE TITLE
Action relationships are not working

### ISSUE THREAD

**Issue by VladimirCourse** [hasura/graphql-engine#5686]
Hello! I'm trying to create action handler with custom types and relationship (as in documentation):

![image](https://user-images.githubusercontent.com/6079349/91601719-cc383280-e972-11ea-8af0-0394679b37b3.png)

```
type Mutation {
  auth_confirm (
    phone: String!
    code: String!
  ): AuthConfirmOutput
}
```
```
type AuthConfirmOutput {
  token : String!
  userId : uuid
  loggedUser: user
}
```

After action save it gives error:

> validation for the given custom types failed because the type "user" for field "loggedUser" in object type "AuthConfirmOutput" does not exist

What I am doing wrong? (I am new for Hasura and sorry if my question is silly).

**Comment by goodmase** [comment]
I think if you remove loggedUser:user it should work. You don't have to define the object relationship in the Output.

**Comment by VladimirCourse** [comment]
Finally, found that problem was in permissions: it was needed to make anonymous role  able to select users from table
