### ISSUE TITLE
Large-ish JWT Creates Connection Error: Artificially Low Limits Prevent Otherwise Valid JWT/Header Lengths

### ISSUE THREAD

**Issue by 24601** [hasura/graphql-engine#5688]
**Environment**
Server: Hasura 1.3.1 official docker image, PG 10 (AWS Aurora for Postgres on RDS 10.11), JWT Authentication mode against AWS Cognito Pool, Kubernetes 1.17.9, nginx-ingress (Issue replicated locally against bare docker image as well - no k8s, no nginx)

Been stable for months, upgrade to 1.3.1 went just fine a few days ago. No issues from 1.3.1 we believe. Issue manifested itself on restore from back in separate test environment on 1.3.0 - confirmed after fix NOT related to 1.3.1 upgrade recently.

Client application: Angular 9 Application using Apollo Angular 

Misc Diagnostic Tools Involved (all exhibit the issue the same): Hasura Client/Console v1.3.1, curl, Postman

**Issue Summary**
JWTs of a certain size cause a very stark, sudden, and cryptic error. Unsure if this is related to contributing to an overall HTTP header size exceed or specific to JWT sizing. However, we verified BOTH overall HTTP header size in the request as well as JWT specifically, and they were *well* under standards (HTTP and JWT standards), and, the requests were successfully made via HTTP clients and servers, only during request processing did an exception occur. 

JWT was around 3.6k (decoded and encoded were about the same size) and headers were about 3.8k total. Removing some claims or replacing full-url claim names with shortened names and appropriately modifying the application/hasura permissions to expect much shorter strings reduced the JWT size to 1.5k and the problem disappeared with no other interventions.

**Action Taken**
Run any known-good GraphQL Query, Mutation, or Subscription against Hasura.

**Expected Result**
Proper response for Query, Mutation, or Subscription or at least a valid error message indicating what went wrong. 

**Actual Result**
Sudden (after months of successful production use of application), cryptic error in POST request for query against /v1/graphql with "net::ERR_CONNECTION_CLOSED", indeed, the HTTP/TCP connection was just suddenly being dropped without explanation either to the end user or even in the Hasura logs (everything configurable set to DEBUG). 

**Current Workaround**
We put our JWTs on Weight Watchers

**Desired Change/Remedy**

Just dropping the connection is *never* an acceptable failure mode, IMO (not sure if this is an intentional design or accidental result of an internal library like Warp crashing or taking an unhandled error path: although no output at all on the Hasura log/stdout was noted, so this is really a very odd and elusive error), but I believe at the very least a proper HTTP Status Code and error message pursuant to the GraphQL error handling patterns should be done. Ideally, user-configurable HTTP Headers/JWT size limits should be allowed.

1. Allow larger JWTs/HTTP Header section total size (ideally configurable by the end user as an ENV var consistent with all other Hasura configuration items)
2. Provide a sane, reasonable, helpful error message if the above is not possible or if the configured value is exceeded by the client payload, HTTP header size, or JWT size (e.g. a 431 Request Header Fields Too Large as in RFC 6585 or if this is indeed JWT, specific an 431 YOUR JWT NEEDS A WEIGHT LOSS PROGRAM).

**Issue Details**

Connections to the /v1/graphql endpoint suddenly failed with error "net::ERR_CONNECTION_CLOSED". No application code change nor ops environment change had been made.

Examination of the HTTP traffic indicated client was making a well-formed request with properly signed, cryptographically valid, non-expired JWT with all appropriate claims. 

Further examination down the line at the nginx level showed no problems with forwarding, headers as sent to Hasura were unchanged from previous, known-good traffic, test traffic, etc. 

Hasura logs (on debug mode) show *NOTHING*, literally no request. Examination of RDS logs show *no* activity at all (we know roughly what SQL the queries we were diagnosing translate to, although no query would work, period, this was not a query/mutation/subscription specific issue). 

Exact HTTP requests headers (via copy-as-curl) and requests were replicated (in time for JWTs to be valid/non-expired. this was validated) and error was replicated using CURL cli and Postman. 

Headers were loaded into Hasura Console running locally connected to production system and development system in question/exhibit errors, Hasura Console complained "Hasura console is not able to reach your Hasura GraphQL engine instance. Please ensure that your instance is running and the endpoint is configured correctly." in a red bar at the top. 

Again, through no method (Hasura Console, curl, postman) was any different activity observed in nginx, Hasura logs, or RDS query monitoring/connection monitoring (except user-agent differences, of course). 

Permissions rules, etc were analyzed for issues or spurious changes. None were found. 

Authentication was changed from "Authorization: Bearer <JWT HERE>" style to x-hasura-admin-secret in GraphiQL, curl, and Postman, and the request succeeded as normal/expected. 

No issues with Cognito JWKS, authentication, JWT signing, etc were noted. 

JWT and HTTP header sizes were examined and did not seem out-of-specification for all relevant standards. Nevertheless, after reading #5441 we hypothesized that mechanisms internal to Hasura were artificially limiting this to a number that is not publicly available, configurable, or understood, so we attempted to reduce JWT claim name length from standard-practice of using URLs to very short property names with very terse values, adjusted permissions and other application code expecting the non x-hasura claims and managed to get the JWT to 1.5k - problem did not occur.

**Comment by tirumaraiselvan** [comment]
When you say JWT size to 1.5k, do you mean 1.5 kilobytes of header? 

As mentioned in #5441, the sum total of all headers should not exceed 50KB but there is a bug in the warp (the web server package) which limits it to something lower like ~30KB. The upstream issue is here: https://github.com/yesodweb/wai/issues/807

We are waiting on some triage on the upstream issue before merging #5441.

**Comment by 24601** [comment]
@tirumaraiselvan it was a 1.5k JWT, all the headers were WELL under 50Kb, and likely 30Kb, but I can't be sure, but there weren't a massive amount of other headers as far as I could tell.

**Comment by Vlix** [comment]
yesodweb/wai#807 has been fixed with yesodweb/wai#838

The calculation of header length was wrong in such a way that it could trigger at different sizes (it might let 30kb pass, or it might throw an exception) depending on how large the header chunks are and how many of them there are.
It should now be fixed and actually accept headers with the size up to the maximum setting (default 50kb)

**Comment by 24601** [comment]
> When you say JWT size to 1.5k, do you mean 1.5 kilobytes of header?
> 
> As mentioned in #5441, the sum total of all headers should not exceed 50KB but there is a bug in the warp (the web server package) which limits it to something lower like ~30KB. The upstream issue is here: [yesodweb/wai#807](https://github.com/yesodweb/wai/issues/807)
> 
> We are waiting on some triage on the upstream issue before merging #5441.

It seems like warp merged in the fix for this in https://github.com/yesodweb/wai/pull/838 and they did a release afterwards, too (Feb 2ish), are there plans to bump the version of warp included/depended on to address this issue?

**Comment by manasag** [comment]
This has been made configurable in v2.29. Here is the [commit](https://github.com/hasura/graphql-engine/commit/3124c93673f42f461ddf7c09b165fb765077a446) that adds the support.
