### ISSUE TITLE
[1.3.1] Computed fields select permissions not working

### ISSUE THREAD

**Issue by fvieira** [hasura/graphql-engine#5696]
Hi, I have a two computed fields and for the sake of testing, I've disabled them for a given role (just like I'm used to doing with normal columns), but to my surprise, I can still query them using that role (I tried the same process with a normal column and it's gone from the GraphQL schema as expected).

I'm running version 1.3.1 on Heroku and my Postgres version is 12.4.

Let me know if you need more information.

**Comment by tirumaraiselvan** [comment]
Thanks for the report.

Fixed in https://github.com/hasura/graphql-engine/commit/b057eb8f3c242c85afa3de7f52242be5ab3b6be3
