### ISSUE TITLE
Dependent items do not get deleted from console on "Continue" + metadata not updated

### ISSUE THREAD

**Issue by avimoondra** [hasura/graphql-engine#5699]
![image](https://user-images.githubusercontent.com/2534903/91767684-6675c180-eb91-11ea-9744-03b350f88669.png)

On clicking "Continue," the migration files will be generated but the column will not be removed nor metadata updated.

In addition, the console will say it did complete the migration:

![image](https://user-images.githubusercontent.com/2534903/91767841-a5a41280-eb91-11ea-9ae9-3ff2e58a7ca7.png)

(multiple attempts seen here)
![image](https://user-images.githubusercontent.com/2534903/91767768-8c9b6180-eb91-11ea-8070-dba9b74cae52.png)

------------------------

Workaround: remove the columns from the permissions metadata, and then remove the column (no dependent items)

**Comment by soorajshankar** [comment]
@avimoondra Thanks for reporting the bug!
Closing this and will track this using the existing issue https://github.com/hasura/graphql-engine/issues/5436
