### ISSUE TITLE
hasura cli console command opens empty page

### ISSUE THREAD

**Issue by whollacsek** [hasura/graphql-engine#5707]
I followed the documentation and have a setup where I run the provided docker-compose.yaml in WSL2, however when I run `npx hasura console` the page that is automatically opened is unreachable. No errors are logged in the terminal. Other commands such as `npx hasura migrate status` work as expected.

**Comment by tirumaraiselvan** [comment]
The `npm` hasura-cli package is maintained by community here: https://github.com/jjangga0214/hasura-cli

Maybe you can create an issue there?

**Comment by whollacsek** [comment]
I think the issue is not related to the npm package. The opened page is localhost:9695 but the browser can not reach it.

**Comment by whollacsek** [comment]
Just now I tried to run the command and it segfault immediately. So I reinstalled everything and now it's working so I'm closing this issue but you can see the console output below, not sure it's helpful.

```
npx hasura console
Checking for update... ◓ panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x758106]

goroutine 1 [running]:
github.com/Masterminds/semver.(*Version).Major(...)
        /go/pkg/mod/github.com/!masterminds/semver@v1.5.0/version.go:131
github.com/Masterminds/semver.(*Version).Compare(0x0, 0xc0005400f0, 0x0)
        /go/pkg/mod/github.com/!masterminds/semver@v1.5.0/version.go:268 +0x26
github.com/Masterminds/semver.(*Version).GreaterThan(...)
        /go/pkg/mod/github.com/!masterminds/semver@v1.5.0/version.go:250
github.com/hasura/graphql-engine/cli/update.HasUpdate(0xc0005400f0, 0xc0002883f0, 0x2a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/graphql-engine/cli/update/update.go:98 +0x12d
github.com/hasura/graphql-engine/cli/commands.(*updateOptions).run(0xc000325cb0, 0x1, 0x1, 0x108542e)
        /root/graphql-engine/cli/commands/update-cli.go:75 +0x5fc
github.com/hasura/graphql-engine/cli/commands.glob..func1(0xc0001ca280, 0x1b89e78, 0x0, 0x0)
        /root/graphql-engine/cli/commands/root.go:42 +0xc3
github.com/spf13/cobra.(*Command).execute(0xc0001ca280, 0x1b89e78, 0x0, 0x0, 0xc0001ca280, 0x1b89e78)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:810 +0x21d
github.com/spf13/cobra.(*Command).ExecuteC(0x19da780, 0xc0000ba300, 0xc0000ba020, 0x2)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/hasura/graphql-engine/cli/commands.Execute(0xc0000a2058, 0x0)
        /root/graphql-engine/cli/commands/root.go:119 +0x13a
main.main()
        /root/graphql-engine/cli/cmd/hasura/hasura.go:11 +0x22
```

**Comment by tirumaraiselvan** [comment]
Thanks, have forwarded this error. Seems like something to do with "update check".

**Comment by scriptonist** [comment]
@whollacsek Thanks a lot, but there is a good chance this was fixed in https://github.com/hasura/graphql-engine/pull/5403, can you please make sure you are using the latest version. If the issue still persists please feel free to reopen this issue.
