### ISSUE TITLE
[CLI] `hasura seeds create` doesn't allow for specifying a table schema

### ISSUE THREAD

**Issue by nunopato** [hasura/graphql-engine#5711]
The following release [v1.3.1-beta.1](https://github.com/hasura/graphql-engine/releases/tag/v1.3.1-beta.1) fixed an issue with creating seed migrations for tables with capital letters, but introduced another one by removing the possibility for specifying tables from schemas other than `public`.

So, `v1.3.1` doesn't allow for something like:

`hasura seeds create seeds_from_auth --from-table auth.providers --endpoint endpoint --admin-secret secret`

https://github.com/hasura/graphql-engine/pull/5710 fixes the issue for both capitalized tables and schemas other than `public`.

**Comment by scriptonist** [comment]
although not ideal I think something like  `\"auth\"\".\"\"providers\"` can work.
