### ISSUE TITLE
Can't create table.

### ISSUE THREAD

**Issue by Manubi** [hasura/graphql-engine#5714]

**Comment by Manubi** [comment]
Hi,
Can't make the following two tables:

Table I want to create:
![Add_Table_-_Data___Hasura](https://user-images.githubusercontent.com/20935138/91993292-7af2bf00-ed35-11ea-9087-d8644768b83d.png)


Error:
![Add_Table_-_Data___Hasura](https://user-images.githubusercontent.com/20935138/91993077-4121b880-ed35-11ea-8f03-a183e5394101.png)

Table with the error:
![Modify_-_user_-_Data___Hasura](https://user-images.githubusercontent.com/20935138/91993161-54348880-ed35-11ea-840c-530db4403ce7.png)

Thanks for your help!

**Comment by wwwdepot** [comment]
> A foreign key must reference columns that either are a primary key or form a unique constraint

From psql 11 docs [Foreign Keys](https://www.postgresql.org/docs/11/ddl-constraints.html#DDL-CONSTRAINTS-FK)
