### ISSUE TITLE
Cloud console on small screen

### ISSUE THREAD

**Issue by PedroBern** [hasura/graphql-engine#5716]
I'm using a 13 in. Macbook pro and the cloud console looks like the picture below. 

The `pro` tab going under other tabs is not an issue. But the header taking up space from the screen is annoying. In the picture below my scrollY is at position 0.

The problem is [here at this padding](https://github.com/hasura/graphql-engine/blob/master/console/src/components/Main/Main.scss#L634), it should match the actual header hight.

![hasura](https://user-images.githubusercontent.com/39778068/92037128-b4342a80-ed47-11ea-89f2-b7221378adc2.jpg)

**Comment by beerose** [comment]
Solved in https://github.com/hasura/graphql-engine-mono/pull/652
