### ISSUE TITLE
Upsert mutation overwrites unchanged columns

### ISSUE THREAD

**Issue by esseswann** [hasura/graphql-engine#5720]
I'm not sure if this is an intended behavior but this mutation

```graphql
mutation {
  insert_entity(
    object: {
     id: 1
     field1:"test"
    }
    on_conflict: {
      constraint: entity_pkey
      update_columns: [field1, field2]
    }
  ) {
    id
    field1
    field2 
  }
}
```
whilst having only `field1` provided also updates the `field2` to NULL which is very inconvenient, because it makes me either create 2 separate upsert mutations or choosing between update and insert

**Comment by tirumaraiselvan** [comment]
This is intended behaviour: the above API says to update `field1` and `field2` with values from the new row (on conflict).

**Comment by tirumaraiselvan** [comment]
You could set the the update_columns with a variable itself?

**Comment by esseswann** [comment]
Oh, nice
For anybody wondering here is a complete example:

Mutation
```graphql
mutation upsertEntity(
  $object: entity_insert_input!
  $update_columns: [entity_update_column!]!
) {
  upsertEntity: insert_entity_one(
    object: $object
    on_conflict: {
      constraint: entity_pkey
      update_columns: $update_columns
    }
  ) {
    id
    field1
    field2
  }
}
```
And here is the way to call it
```javascript
const upsert = (data) => mutate({
  variables: {
    object: {
        id: data.id,
        ...data
    },
    update_columns: keys(data)
})
```
