### ISSUE TITLE
Hasura Cloud & AWS Cognito: Could not verify JWT: JWSError (CompactDecodeError Invalid number of parts: Expected 3 parts; got 5)

### ISSUE THREAD

**Issue by stayingcool** [hasura/graphql-engine#5724]
**Issue:**
Could not verify JWT: JWSError (CompactDecodeError Invalid number of parts: Expected 3 parts; got 5).

The above error comes up when I use the bearer token generated from AWS Cognito in the Authorization Header.

**Env:**
- Hasura Cloud v1.3.1-cloud.2
- AWS Cognito

**Steps completed successfully**

- [x] Set up user pools and hosted web UI
- [x] Create a lambda function to add claims to the JWT
- [x] Configure Cognito to trigger the lambda function
- [x] Test the Cognito login and generate sample JWTs for testing
- [x] Configure Hasura to use Cognito keys

**Errors while using the sample JWT under the Authorization header:**
<img width="959" alt="Screen Shot 2020-09-04 at 7 09 14 pm" src="https://user-images.githubusercontent.com/31205483/92225246-4b36e900-eee6-11ea-82b9-3aaeeb2ad602.png">

**Comment by tirumaraiselvan** [comment]
Could you verify if `HASURA_GRAPHQL_JWT_SECRET` has `claims_format: stringified_json` set? See: https://hasura.io/docs/1.0/graphql/core/guides/integrations/aws-cognito.html#configure-hasura-to-use-cognito-keys

**Comment by stayingcool** [comment]
Yes, it is set. 

Here is the screenshot of the env var:
<img width="457" alt="Screen Shot 2020-09-09 at 6 48 04 pm" src="https://user-images.githubusercontent.com/31205483/92576975-7bf39580-f2cd-11ea-90e8-938c70bfb054.png">

**Comment by stayingcool** [comment]
**Figured out the issue:**
The bearer token (value of id_token) that I copied from the browser had the access_token as well 😳. I figured out that when I pasted the entire value of id_token in my VS Code editor. So silly! 

Thanks for your time @tirumaraiselvan 

Closing the issue.

**Comment by ButeForce** [comment]
Dear stayingcool,

I have the same issue when i use jwt with react client , what do you mean by whole JWT and what part of the token is considered id_token, how i get this part only

**Comment by stayingcool** [comment]
We just need the value of id_token as shown below:
https:
//localhost:3000/cognito-callback#id_token=eyJr...&access_token=eyJra...&expires_in=3600&token_type=Bearer

I was copying the access_token as well and hence that was the problem.

Regards,
Nisar
