### ISSUE TITLE
Data browser not returning actual DB values

### ISSUE THREAD

**Issue by corepay** [hasura/graphql-engine#5727]
I am using the following function to generate a `bigint` id for my Postgres tables.

create sequence public.global_id_sequence;

```
CREATE OR REPLACE FUNCTION public.id_generator(OUT result bigint) AS $$
DECLARE
    our_epoch bigint := 1314220021721;
    seq_id bigint;
    now_millis bigint;

BEGIN
    SELECT nextval('public.global_id_sequence') % 1024 INTO seq_id;
    SELECT FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000) INTO now_millis;
    result := (now_millis - our_epoch) << 23;
    result := result | (seq_id);
END;
$$ LANGUAGE PLPGSQL;
```

Execute from PSQL with `select public.id_generator();`

![image](https://user-images.githubusercontent.com/48992923/92295209-53e5ea00-eefb-11ea-9345-56a268f6461f.png)

I enter this function as DEFAULT when I build a new table:

![image](https://user-images.githubusercontent.com/48992923/92295476-9a3b4900-eefb-11ea-84c2-677b8d4c131a.png)

When I Insert Row without providing anything in the id field:
![image](https://user-images.githubusercontent.com/48992923/92295675-d66ea980-eefb-11ea-97cd-73c2fab088b6.png)

It returns the following row:
![image](https://user-images.githubusercontent.com/48992923/92295764-f1d9b480-eefb-11ea-93e1-881db6a8c502.png)

However when I go to my database and look at the table I get a different id:

![image](https://user-images.githubusercontent.com/48992923/92295859-a7a50300-eefc-11ea-9d6f-48899a5e661f.png)

* DB Value -> `2391189448013381651` 
* Hasura Data Browser -> `2391189448013381600`

Hasura replaces last 2 numbers with `00` every time I try - all other numbers map out correctly.

**Comment by soorajshankar** [comment]
@corepay Can you try enabling the flag `--stringify-numeric-types` while running Hasura GraphQL Engine?
More info https://hasura.io/docs/1.0/graphql/core/deployment/graphql-engine-flags/reference.html

**Comment by beerose** [comment]
Closing as https://github.com/hasura/graphql-engine/issues/5727#issuecomment-688761099 should fix the issue. Please reopen if it didn't.
