### ISSUE TITLE
I'm getting error "variable object of type User_insert_input is used in position expecting User_insert_input!"

### ISSUE THREAD

**Issue by tychop** [hasura/graphql-engine#5728]
Not sure if this is Apollo-ios client related or Hasura... But since I an error from Hasura, I thought I would try here first.
The error I'm getting when trying to create my users with Apollo-ios is:

    variable object of type User_insert_input is used in position expecting User_insert_input!

I have no idea what I am doing wrong..... It's not like I create an optional User_insert_input variable. What is the error trying to tell me?

This is the code that gives me the error from the Hasura GraphQL server:

    func createUsers() {
      let usersDTO: [UserDTO] = self.data.users
    
      for userDTO in usersDTO {
        let user: User_insert_input = User_insert_input(
          department: userDTO.department,
          email: userDTO.email,
          firstName: userDTO.firstName,
          id: UUID().uuidString.lowercased(),
          isAdmin: userDTO.isAdmin,
          lastName: userDTO.lastName,
          psn: userDTO.psn,
          teamId: userDTO.teamIdentifier,
          uid: userDTO.uid,
          usedBuild: userDTO.lastUsedApplicationBuild,
          usedVersion: userDTO.lastUsedApplicationVersion
        )
    
        let insertUserOneMutation = InsertUserOneMutation(object: user)
    
        self.apollo.perform(mutation: insertUserOneMutation) { (result) in
          switch result {
            case .success(let graphQLResult):
              if let errors = graphQLResult.errors {
                for error in errors {
                  guard let message = error.message else { continue }
                  print("Error in createUsers: \(message)")
                }
              }
            case .failure(let error):
              print("InsertUserOneMutation failed with error: \(error)")
          }
        }
      }
    }

And this is how my Hasura graphql mutation is defined:

[![enter image description here][1]][1]

P.s. This following function works just fine, but I need the 'User_insert_input' type elsewhere so that's why I want to use that.

    func createUsers() {
      let usersDTO: [UserDTO] = self.data.users
   
      for userDTO in usersDTO {
        let insertUserMutation = InsertUserMutation(
          used_version: userDTO.lastUsedApplicationVersion,
          used_build: userDTO.lastUsedApplicationBuild,
          psn: userDTO.psn,
          last_name: userDTO.lastName,
          is_admin: userDTO.isAdmin,
          id: UUID().uuidString.lowercased(),
          uid: userDTO.uid,
          first_name: userDTO.firstName,
          email: userDTO.email,
          department: userDTO.department,
          team_id: userDTO.teamIdentifier
        )
   
        self.apollo.perform(mutation: insertUserMutation) { (result) in
          switch result {
            case .success(let graphQLResult):
              if let errors = graphQLResult.errors {
                for error in errors {
                  guard let message = error.message else { continue }
                  print("Error createUsers: \(message)")
                }
              }
            case .failure(let error):
              print("InsertUserOneMutation failed with error: \(error)")
          }
        }
      }
    }

P.s. This question is also asked on SO: https://stackoverflow.com/questions/63743523/how-do-i-create-insert-input-objects-which-i-can-use-in-the-apollo-ios-clien

  [1]: https://i.stack.imgur.com/9HNBh.png

**Comment by aaronhayes** [comment]
so in your mutation you are defining `$object` as an **optional** input, instead of a required input. To make it a required input simple append `!` to the type, i.e: 

**Optional**: `$object: User_insert_input`

vs. 

**Required**: `$object: User_insert_input!`


All together:

```graphql
mutation InsertUserOne($object: User_insert_input!) {
  insert_User_one(object: $object) {
    id
  }
}

```

**Comment by tychop** [comment]
Thanks, worked like a charm !!!
