### ISSUE TITLE
Select first operator by default on the browse rows screen

### ISSUE THREAD

**Issue by bertyhell** [hasura/graphql-engine#5729]
Most of the time people filter by searching for an exact value, so setting the default operator to the first operator might save people a little bit of time

![image](https://user-images.githubusercontent.com/1710840/92306610-b1784600-ef90-11ea-8cfb-999b45b8fc7d.png)

**Comment by GrizliK1988** [comment]
Hi!

Would it make more sense to store the latest selected value and then show it when Browse Rows content is shown? By default on the first opening user will see "equals" operator.

What do you think?

**Comment by bertyhell** [comment]
> What do you think?

Yes, that sounds great. It is quite a bit more complex since you need to store the last selected value somewhere. But someone could do it in a separate PR.

For now since most people search for an exact value, I think merging this PR as is is already an improvement.

**Comment by GrizliK1988** [comment]
@kolharsam , I'd like to take this one.

**Comment by beerose** [comment]
Hi @GrizliK1988!

Thanks for your PR and willingness to work on this issue! However, @bertyhell already submitted a PR that solves the issue. 
Though, I'd like to leave your PR open in case you want to work on the functionality you mentioned in your comment.

**Comment by bertyhell** [comment]
@beerose according to this remark my PR is actually no good,since it only manipulates the html, but it should instead set the value in the store.

So if @GrizliK1988 wants to do that, I'm more than happy to close this PR and let him open a better implementation PR

**Comment by GrizliK1988** [comment]
Thank you for your feedback @bertyhell  and @beerose !

a PR is already in progress: https://github.com/hasura/graphql-engine/pull/6032 (tests have to be fixed) and the approach is to change value in store. It's fine for me either to move changes to the PR of @bertyhell or to keep my PR opened - whatever better fits the process.

**Comment by beerose** [comment]
From my point of view, both options work just fine. You can do whatever feels better for you 🙂

**Comment by GrizliK1988** [comment]
Ok, then I'd also like to propose to keep PR https://github.com/hasura/graphql-engine/pull/6032, simply because it's a replacement of https://github.com/hasura/graphql-engine/pull/5730 :)

**Comment by bertyhell** [comment]
Closed in favor of https://github.com/hasura/graphql-engine/pull/6032

**Comment by beerose** [comment]
I'm reopening the issue to keep track of this feature and for further discussion.
I closed the #5730 PR instead.
