### ISSUE TITLE
Option to allow (ignore) unexpected fields in action webhook response

### ISSUE THREAD

**Issue by datakurre** [hasura/graphql-engine#5731]
I was amazed to find out that Hasura Actions could be used to integrate existing REST APIs into Hasura schema. Thank you!

Yet, I did run into two issues:

* Because actions create only POST requests, calling REST endpoints for other methods don't work out of the box: https://github.com/hasura/graphql-engine/issues/4862 (in my use case I was able add support for configuring required method as action request header)

* **Unless all fields in response are defined in response type, queries fail with unexpected fields in webhook response error.**

Adding all response fields into custom type even if they are not really required could be a lot of extra work. It might also be impossible until actions response may contain nested types: https://github.com/hasura/graphql-engine/issues/4796

Simply having an option to ignore all action response field not expected in action type would make actions a lot more practical for integrating existing REST APIs with Hasura (unless you have even better ideas for similar use cases).

**Comment by esseswann** [comment]
Hasura being exposed as GraphQL endpoint is a core feature. Removing schema-bound constraints would break a lot of things both on your frontend and in Hasura, for example Action relationships

**Comment by datakurre** [comment]
I'm sorry if I was ambiguous. I don't think I am asking to remove schema-bound constraints, but if it would be possible for Hasura to just ignore any data outside schema when parsing a webhook / action response.

My context here is that I was playing with on idea to use Hasura actions to merge existing REST API with the schema. Not the full responses, but only the parts defined in action schemas. This already works for POST endpoints when all fields in the response are defined. But REST APIs may be very verbose and defining all the fields even when only a few of them are really required is a lot of work. In this use case it would be ok for Hasura to just ignore and drop parts of the response in schema.

I know that actions were not designed for this use case, but as I said, I was surprised how well they already worked for this.

**Comment by renato** [comment]
I'm also using actions for querying a REST endpoint and currently I need to extract those specific fields in use on the query from the returning objects, repeating the format of the the Action definition output.

Would be nice to avoid repeating these fields on the request handler.

**Comment by sordina** [comment]
@tirumaraiselvan Do you think this should always ignore unexpected fields, or be configurable? I don't see much of a downside in always ignoring unexpected fields right?

**Comment by sordina** [comment]
If all we want to do is ignore the extra fields it should be trivial to make this change:

Current validation:

```
      -- Webhook response object should conform to action output fields
      validateResponseObject obj = do
        -- Fields not specified in the output type shouldn't be present in the response
        let extraFields = filter (not . flip Map.member outputFields) $ Map.keys obj
        unless (null extraFields) $
          throwUnexpected $
            "unexpected fields in webhook response: " <> commaSeparated extraFields
```

in `server/src-lib/Hasura/GraphQL/Execute/Action.hs`

**Comment by tarwich** [comment]
Currently my frontend code has 

```ts
if (userType === 'Author') {
  mutate({
    id: article.id,
    title: article.title,
    tags: article.tags,
    body: article.body,
  });
}
else {
  mutate({
    id: article.id,
    tags: article.tags,
  });
}
```

It would be convenient if I could send the same fields, but the schema could strip out extras so that I have only one query. I came here hoping to find a solution, but there seems to be confusion, so I wrote this example hoping (hoping) to clarify.

**Comment by sordina** [comment]
@tarwich Ah interesting, this is a seperate issue I think with respect to ignoring unexpected request fields rather than action response fields. We should probably create a seperate issue to track this. What do you think @tirumaraiselvan ?

**Comment by tarwich** [comment]
Oh, wow. I see how I misread this. I'm happy to move the issue. Do you think I should use Discussions first to see if there's any interest, or just open an issue?

**Comment by sordina** [comment]
Sure, couldn't hurt to try a discussion! It would be interesting to see if other people have run into the same friction point as you.

**Comment by tirumaraiselvan** [comment]
> @tirumaraiselvan Do you think this should always ignore unexpected fields, or be configurable? I don't see much of a downside in always ignoring unexpected fields right?

@sordina Yeah, I think we can ignore unexpected fields always

**Comment by sordina** [comment]
@tirumaraiselvan @datakurre This is merged in main branch. The changes should be available in the next release.
