### ISSUE TITLE
console reusing old websocket connection on headers change

### ISSUE THREAD

**Issue by crubier** [hasura/graphql-engine#5744]
When using a subscription on a count aggregate query, the value returned does not seem to take permissions into account.

Doing a normal graphql query returns a different count depending if I use the `x-hasura-admin-secret` header or a jwt `Authorization` header.

On the other hand, using a subscription always returns the total count that the admin sees.

**Comment by sebastiangraef** [comment]
I've got a subscription like

```
      subscription {
        reports_aggregate {
          aggregate {
            count
          }
        }
      }
```

and it returns the correct count for the user

**Comment by tirumaraiselvan** [comment]
A bug was introduced in Hasura's GraphiQL when it tries to reuse old connection for websocket: https://github.com/hasura/graphql-engine/pull/5064

We will fix this ASAP. This is ONLY a bug in Hasura's console and you can verify this either by hard refreshing the console with roles set or use some other client like [gq](https://github.com/hasura/graphqurl).

**Comment by crubier** [comment]
@tirumaraiselvan indeed I think it is this bug.
