### ISSUE TITLE
fix parser to accept integer values of any length and throw error for relevant types

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#576]
The GraphQL API does not throw an error if a number  > 32 bit is inserted into a Int32 field, instead, it inserts the overflown value.

But JSON API throws error saying this is not possible.

**Comment by rakeshkky** [comment]
Should handle this in [graphql-parser](https://github.com/hasura/graphql-parser-hs) ([line](https://github.com/hasura/graphql-parser-hs/blob/076d3894cd3977aea8119c9131ccc44b0b19f63e/src/Language/GraphQL/Draft/Parser.hs#L182))

**Comment by tirumaraiselvan** [comment]
From @rakeshkky 

This will also fix #4368 :

1. Fix parser to accept integer values of any length without causing overflow
2. Raise error if the number > 32 bit and it's input scalar type is Int
