### ISSUE TITLE
Custom functions/code for permissions: limiting number of rows inserted

### ISSUE THREAD

**Issue by s-kris** [hasura/graphql-engine#5772]
It'll be helpful to execute custom code or functions in place of permissions when a user is inserting a new row. 
For example:
To restrict number of rows per user.id to 100 in a table.  

Reference:
https://github.com/hasura/graphql-engine/issues/2575#issuecomment-545238593

**Comment by Bessonov** [comment]
Can't you do this with a custom postgres check?

**Comment by s-kris** [comment]
You mean by creating a custom SQL function to extend the schema?

**Comment by Bessonov** [comment]
I was mistaken, that it can be done with check constraints, but it's [dangerous](https://www.postgresql.org/docs/13/ddl-constraints.html#id-1.5.4.6.5.12). Instead look at [this SO answer](https://stackoverflow.com/questions/1743439/how-to-write-a-constraint-concerning-a-max-number-of-rows-in-postgresql/1743742#1743742) with a trigger.

**Comment by s-kris** [comment]
I'm not an expert in SQL but It's helpful, thank you.
