### ISSUE TITLE
Support for sharded tables on Azure Hyperscale (Citus)

### ISSUE THREAD

**Issue by dave-philp** [hasura/graphql-engine#5775]
Hi team,

We've run into a roadblock when testing Azure Database for PostgreSQL Hyperscale (i.e. Citus) with Hasura. Is this a known issue / limitation, or something that we've missed?

Originally we were looking into Yugabyte, which is probably great for some use cases, but it wasn't coping well with our large and rather complex schema. Citus offers a Microsoft-backed PaaS solution that would be ideal for us.

Example error:
```
{
  "errors": [
    {
      "extensions": {
        "internal": {
          "statement": "SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_1_e\"  FROM  (SELECT  \"_0_root.base\".\"connector_uuid\" AS \"connector_uuid\", \"_0_root.base\".\"batch_uuid\" AS \"batch_uuid\", \"_0_root.base\".\"ext_id\" AS \"ext_id\", \"_0_root.base\".\"landed_file\" AS \"landed_file\", \"_0_root.base\".\"last_updated\" AS \"last_updated\", \"_0_root.base\".\"last_updated_src\" AS \"last_updated_src\", \"_0_root.base\".\"lkey\" AS \"lkey\"       ) AS \"_1_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"etl\".\"keystore\"  WHERE ('true')     ) AS \"_0_root.base\"      ) AS \"_2_root\"      ",
          "prepared": true,
          "error": {
            "exec_status": "FatalError",
            "hint": "Consider using an equality filter on the distributed table's partition column.",
            "message": "could not run distributed query with subquery outside the FROM, WHERE and HAVING clauses",
            "status_code": "0A000",
            "description": null
          },
          "arguments": [
            "(Oid 114,Just (\"{\\\"x-hasura-role\\\":\\\"admin\\\"}\",Binary))"
          ]
        },
        "path": "$",
        "code": "unexpected"
      },
      "message": "database query error"
    }
  ]
}
```

**Comment by tirumaraiselvan** [comment]
Hi @intellischool-dave 

Although, we do not yet have Citus support officially (coming very soon), Hasura may still start and work for basic queries on Citus (it may also not work for other basic queries). 

Could you describe what graphql query were you trying to run and what is the schema of the table?

**Comment by intellischool-dave** [comment]
Hi @tirumaraiselvan 

Unfortunately we've shut down our test Citus instance, but from memory everything was running fine on Citus until we actually sharded the tables.

All of our tables have a primary key which consists of two fields: a `tenant_id` and another unique key for the table.

When we sharded the table on the `tenant_id` we started seeing the above errors on almost everything we did in the console. I don't recall testing any GraphQL; once we saw the volume of errors popping up in the console we wrote it off for the time being. 

Citus is a bit too expensive to have running just for dev purposes so we don't have another instance I can test on. Once you have your official Citus support (even if it's in Beta) we'd be happy to do some testing 👍🏻 🚀

**Comment by cesdias** [comment]
I've started on Citus recently hoping we can migrate our current dataset to a distributed postgres infrastructure, but due to the lack of official support for Citus on Hasura kinda frustated our team. Really looking forward to the official Citus support from Hasura. It would be great if there's a beta version I can try.

**Comment by intellischool-dave** [comment]
Hi @tirumaraiselvan - checking in to see if there's been any movement on this one. We're hoping to move to a horizontally-scalable Postgres variant in the next couple of months.

**Comment by Ciboulette** [comment]
I'm also interested to know when this feature would be available 😇

**Comment by intellischool-dave** [comment]
Hi @tirumaraiselvan. Checking in again to see if there's been any updates on this one.

> Although, we do not yet have Citus support officially (coming very soon), Hasura may still start and work for basic queries on Citus (it may also not work for other basic queries).

Is there an ETA for Citus support, even if its alpha or beta? 🙂

**Comment by jmarbutt** [comment]
What is the eta of full support for Citus?

**Comment by 0x777** [comment]
Hey folks, Citus/Hyperscale is now officially supported by graphql-engine in v2. The known limitations are mentioned [here](https://hasura.io/docs/latest/graphql/core/databases/citus-hyperscale-postgres/hasura-citus-compatibility.html).

**Comment by ammirator-administrator** [comment]
with a big table you are going to hit this limitation
https://postgrespro.com/list/thread-id/2486891
Because they use json_build_object instead of row_to_json
I already asked for a fix, but don;t see any action
@0x777 @jmarbutt @tirumaraiselvan @cesdias
