### ISSUE TITLE
Small syntax error in Glitch remote schema example

### ISSUE THREAD

**Issue by mellson** [hasura/graphql-engine#5779]
Your remote schema [example on Glitch](https://glitch.com/edit/#!/hasura-sample-remote-schema?path=index.js%3A7%3A3) has a small error on line 8, that line contains a } too much. It's not there in the sample code on GitHub so I can't submit a PR to fix it.

**Comment by tirumaraiselvan** [comment]
Thank you for pointing this. This must have been me fiddling around the project and accidentally editing it. Fixed now. I must look for a way to make this read only :)

**Comment by mellson** [comment]
@tirumaraiselvan thanks for the quick fix 👍
