### ISSUE TITLE
server: JWK refresh happens continuously when max age is 0

### ISSUE THREAD

**Issue by ecthiender** [hasura/graphql-engine#5781]
`Cache-Control` header parsing for JWKs response doesn't take into account `no-cache` directive or `max-age=0`. As a result, JWK refresh happens continuously.

**Comment by tirumaraiselvan** [comment]
From https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

> Requiring revalidation
Specifying no-cache or max-age=0 indicates that clients can cache a resource and must revalidate each time before using it. This means HTTP request occurs each time, but it can skip downloading HTTP body if the content is valid.

Seems like we should simply refetch the JWK on each request when `no-cache` or `max-age=0` is found in the response headers. So this could be the behaviour:

1. Fetch JWK on startup and mark it as "requires revalidation" if `no-cache` or `max-age=0` are present in `Cache-Control` header.
2. When a request comes in, see if the JWK "requires revalidation" and if yes, then refetch the JWK and update "requires revalidation" based on the new `Cache-Control` header.

**Comment by daniel-chambers** [comment]
@tirumaraiselvan I've done a little digging on this issue. It seems like there could be two potential solutions to the problem:

### "Requires revalidation"
The approach you detailed out above has the advantage of performing the minimum number of JWK fetches, in the case where incoming requests are less than once a second, as we'll only grab a JWK when we need one.
However, this approach also couples the success of getting a new JWK into the incoming request, which potentially reduces reliability. One could argue that this behaviour would be expected, though, given the setting of `no-cache` (etc). 
It's also a more complicated solution as it requires switching between two different modes of refresh: "throttled on-request" for when `no-cache`, or an "upon expiry" loop that refreshes the token after `max-age` expires.

### Refresh a maximum once per second
In this approach, if we saw `no-cache` or `max-age=0` (etc), we could simply poll and refresh our JWK every second. This is the simplest solution and should be fairly trivial to implement, however it does result in a bunch of unnecessary JWK fetches in the case where incoming requests happen less frequently than once per second. It also has the advantage of decoupling the success of getting a JWK from incoming requests to the server.


It would be good to understand the use case of where a JWK server would use the `no-cache` (etc) settings. My intuition makes me think maybe in a dev prototyping scenario where they're fiddling with the JWKs? In which case, maybe the simpler poll once per second solution is sufficient?

**Comment by daniel-chambers** [comment]
We chose to go with the simpler "refresh once per second" solution from above. If we receive more user input as to what better to do when `max-age=0` etc, or if the industry establishes some sort of standard behaviour that should be followed for this case, then we can revisit it.

The fix was applied in this commit: https://github.com/hasura/graphql-engine/commit/4d9417fac47c208bb30fa7b369428c2e59d86410. We've updated the documentation and that fully describes the new behaviour, which for now you can see [here](https://github.com/hasura/graphql-engine/blob/4d9417fac47c208bb30fa7b369428c2e59d86410/docs/graphql/core/auth/authentication/jwt.rst#rotating-jwks).

**Comment by Twister42** [comment]
Hello,
  I think the implementation here does not respect the must-revalidate spec.

  The must-revalidate specifications are [(link)](https://datatracker.ietf.org/doc/html/rfc7234#section-5.2.2.1) :
   ```
   The "must-revalidate" response directive indicates that once it has
   become stale, a cache MUST NOT use the response to satisfy subsequent
   requests without successful validation on the origin server.

   The must-revalidate directive is necessary to support reliable
   operation for certain protocol features.  In all circumstances a
   cache MUST obey the must-revalidate directive; in particular, if a
   cache cannot reach the origin server for any reason, it MUST generate
   a 504 (Gateway Timeout) response.

   The must-revalidate directive ought to be used by servers if and only
   if failure to validate a request on the representation could result
   in incorrect operation, such as a silently unexecuted financial
   transaction.
```

What it means is :
* you can cache the request
* if the data is stale you HAVE to make a new request, you can't send your cache. So if the server is not responding the browser/proxy is supposed to return a 504 error.

Therefore I strongly believe that the polling every second is not justified when must-revalidate is present.
This information is only there for proxy that could be present between Hasura and the server hosting the JWK data.

Regards.

**Comment by Twister42** [comment]
Hello,
  I think the implementation here does not respect the must-revalidate spec.

  The must-revalidate specifications are [(link)](https://datatracker.ietf.org/doc/html/rfc7234#section-5.2.2.1) :
   ```
   The "must-revalidate" response directive indicates that once it has
   become stale, a cache MUST NOT use the response to satisfy subsequent
   requests without successful validation on the origin server.

   The must-revalidate directive is necessary to support reliable
   operation for certain protocol features.  In all circumstances a
   cache MUST obey the must-revalidate directive; in particular, if a
   cache cannot reach the origin server for any reason, it MUST generate
   a 504 (Gateway Timeout) response.

   The must-revalidate directive ought to be used by servers if and only
   if failure to validate a request on the representation could result
   in incorrect operation, such as a silently unexecuted financial
   transaction.
```

What it means is :
* you can cache the request
* if the data is stale you HAVE to make a new request, you can't send your cache. So if the server is not responding the browser/proxy is supposed to return a 504 error.

Therefore I strongly believe that the polling every second is not justified when must-revalidate is present.
This information is only there for proxy that could be present between Hasura and the server hosting the JWK data.

Regards.
