### ISSUE TITLE
update readme and add missing languages for serverless-triggers on aws lambda

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#579]
NodeJS 6 and Python are already added. Need more languages and an updated readme which clearly lists out all the steps required to get it running.

https://github.com/hasura/graphql-engine/tree/master/community/boilerplates/serverless-triggers/aws-lambda

**Comment by OrthoDex** [comment]
Hi @shahidhk, Do you mind if I take a shot at adding the Go boilerplate(s)?

**Comment by shahidhk** [comment]
Go for it @orthodex

**Comment by vyaspranjal33** [comment]
@shahidhk  can i add blog links

**Comment by shahidhk** [comment]
@vyaspranjal33 This issue is about adding sample code.

**Comment by tirumaraiselvan** [comment]
Closing in favour of https://github.com/hasura/graphql-engine/issues/431
