### ISSUE TITLE
Support Returning SETOF View from Computed Column

### ISSUE THREAD

**Issue by jpulec** [hasura/graphql-engine#5791]
From what I can tell, Hasura doesn't support computed fields where the function returns `SETOF <View>` where the view is a sql view. This really limits the ability to use existing tables with custom views, which are often used to provide filtering and ordering to a table, since Hasura does not support filtering or ordering based on computed fields.

**Comment by tirumaraiselvan** [comment]
Is it a materialized view? This is a know issue: https://github.com/hasura/graphql-engine/issues/5294

**Comment by tirumaraiselvan** [comment]
Closing as dupe.
