### ISSUE TITLE
environment specific remote schema

### ISSUE THREAD

**Issue by John0x** [hasura/graphql-engine#5796]
Hey, I have some remote schemas that are only supposed to exist in specific environments. I saw that we can use env vars to define different urls for different environments, but can we disable/enable remote schemas for specific environments?
It's causing problems because some remote schemas only exist in dev or prod environment but not locally, therefore I'd like to disable them locally.

**Comment by esseswann** [comment]
You can apply different metadata definitions based on your environment in your docker\k8s
