### ISSUE TITLE
update readme and add missing languages for serverless-triggers on google cloud functions

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#580]
NodeJS 8 is already added. Need more languages and an updated readme which clearly lists out all the steps required to get it running.

https://github.com/hasura/graphql-engine/tree/master/community/boilerplates/serverless-triggers/google-cloud-functions

**Comment by shahidhk** [comment]
@swatisingh45 Let me know if you'd like to take this up.

**Comment by rosariopfernandes** [comment]
I'm not a NodeJS developer, but I don't see how NodeJS 8 is different from Node 6. I know there are performance improvements, but I fail to see any syntax differences. Could you maybe point me to an article/page/book/notes demonstrating the differences?

**Comment by shahidhk** [comment]
@rosariopfernandes NodeJS 8 can make use of the latest [async/await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) syntax. Other than that, everything should be similar in this context.

**Comment by rosariopfernandes** [comment]
Thanks, then I'll be taking this one (at least the Node 6 part). Should be done in 6 hours give or take.

After that I'll see if I can add Python. But for now, anyone can do it.

**Comment by rosariopfernandes** [comment]
The echo function seemed simple enough, so I went ahead and wrote the python code for it.

**Comment by ulshell** [comment]
I would like to work for python3

**Comment by tirumaraiselvan** [comment]
Closing in favour of #431
