### ISSUE TITLE
update readme and add missing lanugages for serverless-trggers on azure functions

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#581]
NodeJS is already added. Need more languages and an updated readme which clearly lists out all the steps required to get it running.

https://github.com/hasura/graphql-engine/tree/master/community/boilerplates/serverless-triggers/azure-functions

**Comment by IpshitaC** [comment]
Hi @shahidhk 
Can I take this up as a part of hacktoberfest?

**Comment by shahidhk** [comment]
Sure @IpshitaC. Go for it!

**Comment by IpshitaC** [comment]
Hey!
Is [this](https://github.com/hasura/graphql-engine/blob/master/README.md) the readme in question?
Also, can you guide me regarding what needs to be updated?
Thanks!

**Comment by shahidhk** [comment]
Hi @IpshitaC, [this](https://github.com/hasura/graphql-engine/blob/master/community/boilerplates/serverless-triggers/azure-functions/README.md) is the readme. We need to update the boilerplate by adding more languages that are supported by Azure Functions.

**Comment by swetax** [comment]
@shahidhk I tried to solve this #743 but was not able to pass the tests . Please guide me to make this work.

**Comment by shahidhk** [comment]
@swetax The issue is to create more examples for the laguages suppoted by Azure. Not to update the readme. :smile: 

Feel free open another PR with examples in these languages.

**Comment by tirumaraiselvan** [comment]
Closing in favour of #431
