### ISSUE TITLE
websocket connection closed after 60 seconds

### ISSUE THREAD

**Issue by sproctor** [hasura/graphql-engine#5813]
I'm having trouble debugging why the connection is closed. I'm running the 1.3.2 hasura docker image on ECS. I've set a ping interval of 10s, so the load balancer shouldn't be closing the connection. The hasura logs just tell me the connection was closed, not why or by whom. Hasura never sends back an ACK for my ping.

**Comment by sproctor** [comment]
The ACK thing I'm still not sure why there's no response. Turns out my id tokens were expiring. The log message doesn't explain why, but that was the reason. The expiry time is in the log message, but I missed it.

**Comment by tirumaraiselvan** [comment]
What message are you sending as part of your ping? Hasura websocket follows the websocket protocol as described here: https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md

**Comment by sproctor** [comment]
I'm sorry, it was a bit of a confusing morning for me. I didn't get to inspect this as deeply as I should have. I was sending the pings using OkHttp pingInterval. When I'm looking at the packets, I see extra ones now that I'm assuming are related. I was missing them in the typical keep alive messages. Sorry for not looking into this better initially. Not my finest hour. Thanks for sending the link. If I have further issues, I'll read into it more before bothering you. Things are working correctly now that I realize that hasura was closing the connection because of the expired id token. Thank you for your time.
