### ISSUE TITLE
server: Support custom URI schemes in CORS config

### ISSUE THREAD

**Issue by pkvince** [hasura/graphql-engine#5818]
It would be great if we could specify custom URI schemes in the `HASURA_GRAPHQL_CORS_DOMAIN` list. Right now it only supports `http://` and `https://`.

We have recently started using Ionic's [CapacitorJS](https://capacitorjs.com/) to build our webapp into mobile apps (inside a webview). The following scheme is used for iOS: `capacitor://localhost`,  but I am unable to add it to Hasura's CORS config.

See following error:
```
Fatal Error:- Environment variable HASURA_GRAPHQL_CORS_DOMAIN: invalid domain: 'capacitor://localhost'. All domains should have scheme + (optional wildcard) host + (optional port)
```

I also tried to use a wildcard as the scheme:
```
Fatal Error:- Environment variable HASURA_GRAPHQL_CORS_DOMAIN: invalid domain: '*://localhost'. All domains should have scheme + (optional wildcard) host + (optional port)
```

Right now my solution is to allow any domain for CORS... I know I could probably setup a reverse proxy to handle CORS, but I feel like this could be easily supported using custom schemes, or wildcard as the scheme in Hasura directly.

Let me know if I can be of any help to support this! Thank you!

**Comment by GavinRay97** [comment]
Thank you for pointing this out.

Note:
https://github.com/hasura/graphql-engine/blob/7e970177c19169ffff4e06fe37fe9d0aafe04ff8/server/src-lib/Hasura/Server/Cors.hs#L149-L159

**Comment by dminkovsky** [comment]
More schemas are mentioned on #6345 (for example, chrome-extension://) and it makes me wonder: why restrict to any particular schema at all?
