### ISSUE TITLE
Split variable HASURA_GRAPHQL_DATABASE_URL

### ISSUE THREAD

**Issue by dostalradim** [hasura/graphql-engine#5819]
To consider. What do you think about splitting variable HASURA_GRAPHQL_DATABASE_URL?

Because I want to share k8s Secret over more Deployments and when I create variable for database password, user, name etc. I have no chance to concatenate these variables into this complicated one.

Thank you!

**Comment by dostalradim** [comment]
Ok, sorry
https://stackoverflow.com/questions/54173581/combining-multiple-k8s-secrets-into-an-env-variable

**Comment by fbuetler** [comment]
I still think this should be done as we are leaking the password in plaintext in the `HASURA_GRAPHQL_DATABASE_URL` environment variable.
Please \reopen

**Comment by offlinehacker** [comment]
Variable expansion only works if you use `kubectl` or tool that supports variable expansion. I think having database url with password as a text is a bad practice and environment variables for username and password should be supported, this issue should be reopened.
