### ISSUE TITLE
add deploying guide on digital ocean

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#582]
Docs already lists deployment on [Kubernetes](https://github.com/hasura/graphql-engine/tree/master/docs/graphql/manual/deployment/kubernetes). Similarly, we need deployment guide on a Digital Ocean Droplet, using Docker Compose.

The guide should include instructions to update to latest version, as well as setting an access key. 

HTTPS setup can be found at https://github.com/hasura/graphql-engine/tree/master/install-manifests/docker-compose-https

**Comment by aaqaishtyaq** [comment]
hi @shahidhk, I would like to take up the task if not assigned to someone else.

**Comment by shahidhk** [comment]
That sounds good. Please be thorough in each steps. This is going to be
part of docs. Follow the Kubernetes example for style/ formatting
guidelines.

**Comment by aaqaishtyaq** [comment]
Yes, I will write in reStructuredText and follow doc contribution guidelines.

**Comment by aaqaishtyaq** [comment]
HI, 
I've installed docker, docker-compose and follow this [instruction](https://github.com/hasura/graphql-engine/tree/master/install-manifests/docker-compose-https) but was unable to setup hasura.

Can you help

**Comment by shahidhk** [comment]
@aaqaishtyaq Where are you stuck? Have you setup a domain?

**Comment by iUtsavB** [comment]
hello @shahidhk , I need help in testing the .rst file locally.
please help!
