### ISSUE TITLE
cloud: google cloud sql and non-superadmin user

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#5820]
Database URL with a new user on Google Cloud SQL Postgres does not work on Hasura Cloud, super user credentials works though. Followed the steps as mentioned on https://hasura.io/docs/1.0/graphql/cloud/projects/create.html#postgres-permissions

Dashboard says an unknown error has occurred.

**Comment by quantumlicht** [comment]
Ideally, at the very least, there should be a more descriptive user message.

**Comment by shahidhk** [comment]
@quantumlicht This should be fixed now. Will you try again and re-open the issue if the problem persists?
