### ISSUE TITLE
Creating one-off scheduled events with hasura web-console causes payload to be set to string instead of json literal

### ISSUE THREAD

**Issue by andoks** [hasura/graphql-engine#5821]
Version: 1.3.0

![Screenshot_2020-09-22 Schedule an event - One-off Scheduled Events - Events Hasura](https://user-images.githubusercontent.com/5228/93917624-840af680-fd0b-11ea-8806-13844fdaa4a3.png)
![Screenshot from 2020-09-22 19-38-56](https://user-images.githubusercontent.com/5228/93917666-9422d600-fd0b-11ea-9bde-76a896d1f78d.png)

**Comment by RomansBermans** [comment]
I have exactly the same problem in v2.0.0-alpha.4

**Comment by happyfloat** [comment]
Same issue on 2.0.7

**Comment by rodrik** [comment]
Still exists in v2.2.0
![image](https://user-images.githubusercontent.com/993347/155619931-fef879e3-b3f0-41a8-bdc4-a6e8d60048ae.png)

**Comment by kmtym1998** [comment]
It seems to be fixed in v2.17.0

![image](https://user-images.githubusercontent.com/54347899/217032807-ea1011da-8786-409d-ad71-31aaac7864d7.png)

**Comment by andoks** [comment]
Closing as confirmed fixed by https://github.com/hasura/graphql-engine/issues/5821#issuecomment-1419398619 between v2.2.0 and v2.17.0
