### ISSUE TITLE
Hasura docker images for cli-migrations (v1 & v2) not properly loading hasura-metadata.json

### ISSUE THREAD

**Issue by crosseyedalien** [hasura/graphql-engine#5822]
Greetings,

We've been using Hasura in our development for a year or more and in earlier versions we had successfully used Hasura cli-migration containers with Docker and had them loading metadata on first run by placing hasura-metadata.json in the default metadata directory. Somewhere along the way it seemed like the cli-migration container images fell behind and we stopped using this feature. We're now trying to use v1.3.2 of cli-migrations and/or cli-migrations-v2, but the metadata doesn't seem to load properly. With hasura/graphql-engine:v1.3.2.cli-migrations, only 8 of 21 tables/views/functions are loaded from the metadata. With hasura/graphql-engine:v1.3.2.cli-migrations-v2, the container cannot even start, the logs show this error:

```
limsproto2-graphql     | {"level":"info","msg":"Applying metadata...","time":"2020-09-22T20:16:56Z"}
limsproto2-graphql     | time="2020-09-22T20:16:57Z" level=fatal msg="failed to apply metadata: cannot apply metadata on the database: [parse-failed] key \"tables\" not found ($[1])"
limsproto2-graphql exited with code 1
```

Loading the same metadata manually through the web interface works in both versions, but ideally we really need the metadata to automatically load when the container first starts up.

Our Dockerfile:
```
FROM hasura/graphql-engine:latest.cli-migrations-v2

ENV HASURA_GRAPHQL_DATABASE_URL postgres://<removed>
ENV HASURA_GRAPHQL_ENABLE_CONSOLE true
ENV HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
ENV HASURA_GRAPHQL_ENABLE_ALLOWLIST "true" 
ENV HASURA_GRAPHQL_NO_OF_RETRIES 10 
ENV HASURA_GRAPHQL_MIGRATIONS_DIR "/config/migrations"
ENV HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT 60

COPY ./config /config
COPY hasura_metadata.json /hasura-metadata/hasura_metadata.json
```

Thanks for your help and please let me know if I should provide any additional details.

Here is the metadata, suffix renamed from json (In case it helps, the 8 tables/views/functions that do load when we use v1.3.2.cli-migrations are: bill_sponsors, bills, billsearch_results, cosponsors, getAllMembers, members, billDetail, and billSearch.):
[hasura_metadata.txt](https://github.com/hasura/graphql-engine/files/5263863/hasura_metadata.txt)

**Comment by GavinRay97** [comment]
Hi, can you tell me what the result of doing this is:

1. Use `hasura metadata export` with V2 metadata configuration to generate the YAML files in `/metadata` from the current state of running instance
2. Create a Dockerfile like this:
```dockerfile
FROM hasura/graphql-engine:v1.3.2.cli-migrations-v2
COPY ./migrations /hasura-migrations
COPY ./metadata /hasura-metadata
```
3. Run it, and check whether the metadata has been properly loaded

If there are still issues, can continue to troubleshoot this but this _should_ resolve it :+1:

**Comment by crosseyedalien** [comment]
The output is the same, but I'm not really sure what step 1 is instructing me to do. It looks like something to do on the command line, but the version of Hasura we're trying to move away from is v1.2.1 (not a cli-migrations version - sorry I may not have described that well enough). I just tried logging into the running v1.2.1 container and it does not contain a `hasura` command. Alternatively, if that is an instruction for exporting from the web GUI, I'm not sure how to specify an exact metadata version to generate (and the metadata I posted appears to me to be V2 already).

Just to correct my earlier lack of detail, we're trying to upgrade from this Hasura docker image version:
FROM hasura/graphql-engine:v1.2.1

Thanks.

**Comment by GavinRay97** [comment]
Hey, apologies for ambiguity.

The `hasura metadata export` is a command for the Hasura CLI. You should run it on your own machine (no container/SSH), from your Hasura project root (the one that contains `config.yaml`, the `/metadata` folder and the `/migrations` folder).

The Migrations V2 image expects a metadata folder present in the Docker Image (defaults to `/hasura-metadata`) that have the V2 metadata YAML files:

```
❯ tree
├── config.yaml
├── metadata
│   ├── actions.graphql
│   ├── actions.yaml
│   ├── allow_list.yaml
│   ├── cron_triggers.yaml
│   ├── functions.yaml
│   ├── query_collections.yaml
│   ├── remote_schemas.yaml
│   ├── tables.yaml
│   └── version.yaml
├── migrations
    └── <TIMESTAMP + MIGRATION NAME>
        ├── up.sql
        └── down.sql
```

Your Dockerfile for the `.cli-migrations-v2` image must just `COPY` these two folders into the container (at the specified default paths, or a custom path if you set one). Then it will look for these folders and try to run `hasura migrate apply` and `hasura metadata apply` automatically.

---

I believe the piece that should have you up and running is to run `hasura metadata export` so that the YAML files are generated. Once you have the Metadata in the YAML files format, you can use the above Dockerfile and all should be good :+1: 

Let me know if this still doesn't work or there are any hangups

**Comment by crosseyedalien** [comment]
Thanks! Looks like it is working now and I just have a general lack of awareness of: [Migrations and Metadata](https://hasura.io/docs/1.0/graphql/core/migrations/index.html). In addition to what you posted, we had created a config with v1, but never upgraded so I also followed the instructions for upgrading to v2.
