### ISSUE TITLE
How to enforce NULL as a valid unique value in multiple columns for a table?

### ISSUE THREAD

**Issue by joshuarobs** [hasura/graphql-engine#5823]
In a table, I have these columns:

````
**id** - integer, primary key, unique, default: nextval('body_segment_masks_id_seq'::regclass)
**a_id** - integer, nullable
**b_id** - integer, nullable
**c_id** - integer, nullable
**d_id** - integer, nullable
````

a, b, c, and d all are ids that are foreign keys to all the same table (e.g. table B).

I want it so that I can enter these values (ignoring id), no more than once:

````
(1, 1, 1, 1)
(1, 1, 1, NULL)
(2, 1, 1, NULL)
(NULL, NULL, NULL, NULL)
(1, NULL, NULL, NULL)
````

The problem is, if I try to add all the keys as unique:

`( a_id, b_id, c_id, d_id ) - name_of_unique_constraint`

I can insert something like this:

````
(1, 1, 1, NULL)
(1, 1, 1, NULL)
(1, 1, 1, NULL)
````

I shouldn't be able to insert 3 rows that are the "same". There should only be one.

I can obviously do this as normal if I use non-null values, meaning I can't insert something like `(1, 1, 1, 1)` more than once, but I need null values to be a valid value. I'd use `0` or `-1` as a "null" foreign key if I could, but then I can't have those columns as a foreign key. 

I know this is how postgres handles NULL values with unique constraints, but is there a way we can enforce them to be treated as a valid unique value in Hasura?

Also how would I do it, if I have 4 or more of these fields as unique values?

**Comment by GavinRay97** [comment]
I'm not fantastic at SQL, but I think there are two ways you can do this.

1. Use partial unique indices:
```sql
-- Allows for id_C to be null, you can expand this to cover multiple cases/columns for all of them
CREATE UNIQUE INDEX some_index ON my_table (id_A, id_B) WHERE id_C IS NULL;
```
2. Use `coalesce` on unique index. This is only useful for preventing duplicates though, queries won't utilize the index:
```sql
CREATE UNIQUE INDEX some_index (COALESCE(id_a, -1), COALESCE(id_b,-1),COALESCE(id_c, -1))
```

https://www.postgresql.org/docs/current/indexes-partial.html
