### ISSUE TITLE
docs: add deploying guide on aws fargate

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#583]
[AWS Fargate](https://aws.amazon.com/fargate/) is a service to run containers without managing servers or clusters. Since Hasura is just a docker image, it can be deployed to Fargate easily.

The guide can be added at https://hasura.io/docs/1.0/graphql/core/deployment/deployment-guides/index.html.

It'll be great if the Postgres setup can be on Amazon RDS. Should have updating and setting access key instructions.

**Comment by moulikcipherX** [comment]
Hy I want to work on this issue but can you please guide me how to get docker image of graphql-engine

**Comment by shahidhk** [comment]
Hi @moulikcipherX. Thanks for your interest. You can find the docker image here: https://hub.docker.com/r/hasura/graphql-engine

The latest release is `hasura/graphql-engine:v1.0.0-alpha22`.

Let me know if you have any other questions.

**Comment by moulikcipherX** [comment]
Do I have to write a script for it or just the steps to do that?

**Comment by shahidhk** [comment]
@moulikcipherX Detailed steps would be enough. 

But, if you can provide a script, that'll be great too. We can add it to [install-manifests](https://github.com/hasura/graphql-engine/tree/master/install-manifests)

You can work on the detailed steps first. Then if time permits you can add the script too.

**Comment by moulikcipherX** [comment]
Hello Sir,
I am a bit confused as I deployed on AWS Fargate but I want to know that Fargate should show UI thing like making graphql-queries

**Comment by shahidhk** [comment]
@moulikcipherX Can you elaborate?

**Comment by moulikcipherX** [comment]
I am having a problem in deploying to Fargate as it takes many things in consideration which makes me less understandable.

**Comment by shahidhk** [comment]
@moulikcipherX Sure. Take your time.

**Comment by moulikcipherX** [comment]
I can not find the Environment Variables for connecting database.

**Comment by shahidhk** [comment]
@moulikcipherX Have you provisioned an Amazon RDS instance?

**Comment by shahidhk** [comment]
@moulikcipherX Did you manage to figure this out?

Any other takers?

**Comment by theharshitgarg** [comment]
@shahidhk I would like to take some.

**Comment by coco98** [comment]
@shahidhk Not sure what the latest on this is. 
@emerballen on discord has been doing a tonne of work with fargate, rolling out hasura version updates, and rolling out schema updates; maybe they can help us put this together.

**Comment by shahidhk** [comment]
Hi @emerballen, it'll be awesome if you can contribute the cloudformation templates, we can keep them under https://github.com/hasura/graphql-engine/tree/master/install-manifests

**Comment by shahidhk** [comment]
Some resources until we have a dedicated walk-through guide:

- https://dev.to/lineup-ninja/deploying-hasura-on-aws-with-fargate-rds-and-terraform-4gk7
- https://github.com/Rayraegah/terraform-aws-hasura
- https://github.com/hasura/hasura-aws-stack

**Comment by kabirbaidhya** [comment]
Hey @shahidhk @marionschleifer is this still available? If yes - I'm willing to help. Thanks!

**Comment by marionschleifer** [comment]
@kabirbaidhya sure, go ahead. Please read through the comments above and here: https://github.com/hasura/graphql-engine/pull/762#issuecomment-506188397 🙂

**Comment by kabirbaidhya** [comment]
Sure. Will do. I'll take the reference from the above shared links before writing the new guideline. 

Also, please do let me know if there are any specifics that are to be included besides what are already covered in the links above. Thanks!

**Comment by marionschleifer** [comment]
@shahidhk do you have anything to add? 🙂

**Comment by henkesde** [comment]
Hey guys,

I need something similar right now as well since I'm working on IaC with CloudFormation for all resources in AWS like VPC's, LoadBalancer, Fargate, RDS, ..
Some things are not clear to me yet since I'm new to ECS and Fargate as well. Would be nice if you could share something already @kabirbaidhya . 🙂

**Comment by kabirbaidhya** [comment]
@henkesde Mine isn't complete yet and I need to fully test the steps before I can post it. Also, I haven't used cloud formation yet - just trying to run it on fargate. 

For now you can refer to the above shared links - they use terraform but apart from it things are similar for fargate. 

- https://dev.to/lineup-ninja/deploying-hasura-on-aws-with-fargate-rds-and-terraform-4gk7
- https://github.com/Rayraegah/terraform-aws-hasura
- https://github.com/hasura/hasura-aws-stack

**Comment by MartijnHarmenzon** [comment]
@kabirbaidhya Did you achieve to create a guideline? Or are the above links still the best out there?

**Comment by kabirbaidhya** [comment]
@MartijnHarmenzon I tried it out on my own with fargate and tested it. But I haven't worked on the guidelines yet as I got occupied after a while. Yes - the links above can still serve you if you want to try.

**Comment by amit-git-account** [comment]
We are working on this request. The documentation will be available on Hasura Docs under Deployment Guides section.

**Comment by manasag** [comment]
Steps for Fargate deployment are described [here](https://hasura.io/docs/latest/enterprise/getting-started/quickstart-aws-ecs/). Note: this section is for Enterprise Hasura edition, but works for Community edition too.
