### ISSUE TITLE
cli: fix lint errors

### ISSUE THREAD

**Issue by scriptonist** [hasura/graphql-engine#5831]
If we use tools like https://github.com/golangci/golangci-lint we can see that hasura CLI has a bunch of lint errors. Let's take the opportunity of hacktoberfest and fix them.

## How can I contribute ?
- Make sure you follow the CLI [contribution](https://github.com/hasura/graphql-engine/blob/master/cli/CONTRIBUTING.md) guide to setup your local development environment.
- Install `golangci-lint` on your machine by following instructions at https://golangci-lint.run/usage/install/#local-installation
- On your `graphql-engine` local clone navigate to `cli` directory
- run the following command
```
$ golangci-lint run
```
- You'll see a bunch of lint errors.
![](https://i.imgur.com/2QEJWwm.png)

- Now choose a file and fix lint errors in that file.
- Once you are ready with the changes to your chosen file, feel free to open a PR

## Things to note
- We expect one community member to contribute and fix lint errors of one file. This will make changes easy to review.
- Once you choose which particular file you are going to work on, please comment on this issue to let others know. So that we don't duplicate work.

**Comment by shreyagupta30** [comment]
HI @scriptonist! Can I work on this?

**Comment by scriptonist** [comment]
@shreyagupta30 sure 💯, can you also let us know which file you will be working on?

**Comment by sam09** [comment]
@scriptonist I made a PR for `cli/migrate/source/testing/testing.go`

**Comment by arunvm123** [comment]
@scriptonist fixed lint errors in metadata/actions/actions.go

**Comment by 97amarnathk** [comment]
@scriptonist picking up migrate/migrate.go

**Comment by 97amarnathk** [comment]
@scriptonist Added the PR for migrate/util.go

**Comment by Yashs911** [comment]
@scriptonist picking up commands\docs.go

**Comment by avats-dev** [comment]
@scriptonist picking up `cli/util/git.go` :rocket:

**Comment by bpedersen** [comment]
@scriptonist fixed lint errors in `migrate/cmd/commands.go

**Comment by ayan-b** [comment]
I would like to work on this file: https://github.com/hasura/graphql-engine/blob/master/cli/integration_test/v2/seeds.go

**Comment by mjnagel** [comment]
@scriptonist I'll pick up `commands/help.go`

**Comment by mjnagel** [comment]
@scriptonist see above PR! Fixed linting issues in `commands/help.go`.

**Comment by ukitta555** [comment]
I take up cli/migrate/migrate.go

**Comment by ukitta555** [comment]
@scriptonist see above PR! Fixed linting in `source/stub/stub_test.go`

**Comment by csaranbalaji** [comment]
I would like to take up [`commands/scripts_update_config_v2.go`](https://github.com/hasura/graphql-engine/blob/master/cli/commands/scripts_update_config_v2.go)

**Comment by daniel-shuy** [comment]
@scriptonist I've created a PR for `cli/commands/init.go` at #5943

**Comment by daniel-shuy** [comment]
This Issue has been mistakenly closed
