### ISSUE TITLE
Hasura changing data in database (with similar row and column data)

### ISSUE THREAD

**Issue by adventurini** [hasura/graphql-engine#5835]
I am not even sure how I can replicate this bug, but I will do my best to explain.

I have a table called campaign. In this table, there is a column called campaign IDs, which are not null (but can have duplicates -- there are up to two total rows with the same campaign ID). 

The table also has a column called campaign NAMES and other various columns that create similar data across certain rows. 
Hasura seems to be taking these rows and deciding that they are similar enough, to change the campaign ID when I run a query for all of them. I attached a photo below showing the replication of Campaign with the ID of 144281332495870500. It is replicating the ID twice into 144281332495870506. However, there should only be a single row of this ID.

The images below show the timestamps - showing that these are different rows (not a duplication). And the raw query from the DB shows that Hasura is somehow changing the campaign ID. 

<hr>

<img width="447" alt="Screen Shot 2020-09-24 at 5 08 35 PM" src="https://user-images.githubusercontent.com/12114942/94203747-cc91f380-fe74-11ea-88d2-64ba9fb12016.png">

<hr>

Two rows ending in 506 on the DB above, single row ending in 500 below.

<hr>

<img width="446" alt="Screen Shot 2020-09-24 at 5 08 26 PM" src="https://user-images.githubusercontent.com/12114942/94203752-d3206b00-fe74-11ea-97e6-c3b2cd6b7a56.png">

<hr>

Three rows returning from Hasura -- with Campaign ID changed on the two previously shown campaigns to ending in 506.

<hr>
<img width="522" alt="Screen Shot 2020-09-24 at 5 12 24 PM" src="https://user-images.githubusercontent.com/12114942/94203759-d87db580-fe74-11ea-873d-ca5f1d576b6c.png">

<hr>

When I query Hasura directly for the campaign, it returns the correct result.

<hr>

<img width="453" alt="Screen Shot 2020-09-24 at 5 06 51 PM" src="https://user-images.githubusercontent.com/12114942/94203754-d582c500-fe74-11ea-8cf2-c7f0da145fbe.png">

<hr>

Here is a replication of the rows.

<table>
	<tr>
		<th>id</th>
		<th>profile_id</th>
		<th>portfolio_id</th>
		<th>name</th>
		<th>campaign_type</th>
		<th>budget_type</th>
		<th>budget</th>
		<th>state</th>
		<th>serving_status</th>
		<th>start_date</th>
		<th>end_date</th>
		<th>spending_policy</th>
		<th>bid_optimization</th>
		<th>targeting_type</th>
		<th>premium_bid_adjustment</th>
		<th>creation_date</th>
		<th>last_updated_date</th>
		<th>created_at</th>
		<th>updated_at</th>
		<th>bidding_strategy</th>
		<th>is_legacy</th>
		<th>cost_life</th>
		<th>budget_life</th>
		<th>first_report_date</th>
		<th>creative_brand_name</th>
		<th>creative_brand_logo_asset_id</th>
		<th>creative_brand_logo_url</th>
		<th>creative_brand_headline</th>
		<th>creative_asins</th>
		<th>creative_should_optimize_asins</th>
		<th>creative_video_asset_id</th>
		<th>landing_page_type</th>
		<th>landing_page_url</th>
		<th>landing_page_asin</th>
		<th>brand_entity_id</th>
		<th>tactic</th>
		<th>profile_name</th>
		<th>portfolio_name</th>
		<th>optimization_group_id</th>
	</tr>
	<tr>
		<td>144281332495870506</td>
		<td>706073535518186</td>
		<td><i>NULL</i></td>
		<td>Random House Children's Books 01/09/2018</td>
		<td>sp  </td>
		<td>daily</td>
		<td>50</td>
		<td>archived</td>
		<td>terminated</td>
		<td>2018-01-09</td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td>0</td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td>2020-07-01 20:57:05.668715</td>
		<td>2020-07-06 12:25:58.794549</td>
		<td><i>NULL</i></td>
		<td>0</td>
		<td>0</td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td>Random House Children's Books</td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
	</tr>	
	<tr>
		<td>144281332495870506</td>
		<td>706073535518186</td>
		<td><i>NULL</i></td>
		<td>Random House Children's Books 01/09/2018</td>
		<td>hsa </td>
		<td>daily</td>
		<td>50</td>
		<td>archived</td>
		<td>terminated</td>
		<td>2018-01-09</td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td>0</td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td>2020-04-12 22:53:25.722507</td>
		<td>2020-08-28 20:12:11.307744</td>
		<td><i>NULL</i></td>
		<td>0</td>
		<td>0</td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td>Random House Children's Books</td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
	</tr>
	<tr>
		<td>144281332495870500</td>
		<td>706073535518186</td>
		<td><i>NULL</i></td>
		<td>Random House Children's Books 01/09/2018</td>
		<td>hsa </td>
		<td>daily</td>
		<td>50</td>
		<td>archived</td>
		<td>terminated</td>
		<td>2018-01-09</td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td>0</td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td>2020-04-16 18:20:05.838499</td>
		<td>2020-04-20 00:52:23.754016</td>
		<td><i>NULL</i></td>
		<td>0</td>
		<td>0</td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
		<td>Random House Children's Books</td>
		<td><i>NULL</i></td>
		<td><i>NULL</i></td>
	</tr>
</table>

<hr>

I removed all relationships from the table on Hasura and replicated the table and received the same outcome.

**Comment by adventurini** [comment]
Here is my Hasura SQL analysis:

```
SELECT
  coalesce(
    json_agg(
      "root"
      ORDER BY
        "root.pg.name" ASC NULLS LAST
    ),
    '[]'
  ) AS "root"
FROM
  (
    SELECT
      "_0_root.base"."name" AS "root.pg.name",
      row_to_json(
        (
          SELECT
            "_1_e"
          FROM
            (
              SELECT
                "_0_root.base"."name" AS "name",
                "_0_root.base"."id" AS "id",
                "_0_root.base"."created_at" AS "created_at"
            ) AS "_1_e"
        )
      ) AS "root"
    FROM
      (
        SELECT
          *
        FROM
          "public"."campaign_copy"
        WHERE
          (
            ("public"."campaign_copy"."profile_id") = (('706073535518186') :: bigint)
          )
      ) AS "_0_root.base"
    ORDER BY
      "root.pg.name" ASC NULLS LAST
  ) AS "_2_root"
```

**Comment by tirumaraiselvan** [comment]
Hi @adventurini 

Since it appears the issue is with a `bigint` column, have you set `HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES`

Otherwise the JSON representation of a numeric type may not be the actual value. From https://hasura.io/docs/1.0/graphql/core/deployment/graphql-engine-flags/reference.html

```
Stringify certain Postgres numeric types, specifically bigint, numeric, decimal and double precision as they don’t fit into the IEEE-754 spec for JSON encoding-decoding.
```

**Comment by adventurini** [comment]
It appears that this has solved my issue. Thank you!!
