### ISSUE TITLE
add deploying guide on azure container instances

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#584]
[Azure Container Instances](https://azure.microsoft.com/en-us/services/container-instances/) is a service to easily run containers on Azure without managing servers. Since Hasura is just a docker image, it can be deployed to Fargate easily.

The guide can be added at https://github.com/hasura/graphql-engine/tree/master/docs/graphql/manual/deployment

It'll be great if the Postgres setup can also be on Azure. Should have updating and setting access key instructions.

(All content can be on the same page)

**Comment by vnyk** [comment]
Can u provide me a link to your docker image

**Comment by shahidhk** [comment]
Hi @vnyk. Thanks for your interest. You can find the docker image here: https://hub.docker.com/r/hasura/graphql-engine

The latest release is `hasura/graphql-engine:v1.0.0-alpha22`.

Let me know if you have any other questions.

**Comment by vnyk** [comment]
Yes one more thing, the github repo link on your comment is broken

**Comment by shahidhk** [comment]
Thanks, updated

**Comment by vnyk** [comment]
check PR

**Comment by flowkraD** [comment]
If this is still an open issue, I would love to contribute (^_^)

**Comment by shahidhk** [comment]
Go for it @flowkraD
