### ISSUE TITLE
Automatic generation of the Graphql API

### ISSUE THREAD

**Issue by mrkkrp** [hasura/graphql-engine#5843]
What is the best way to generate a human-readable description of the resulting GraphQL API? AFAIU this is not an existing feature of Hasura, so perhaps quering the schema could be used for that?

Related question: is there a way to get GraphQL scheme out of Hasura? I tried to find instructions for that but it is not immediately obvious.

**Comment by GavinRay97** [comment]
You can press the "Voyager" button on the GraphiQL screen to open an interactive visual diagram of your schema:

![image](https://user-images.githubusercontent.com/26604994/94297894-3f61a400-ff33-11ea-94be-b977702f8d97.png)

If you want to export a static documentation website, you can use graphdoc:

https://github.com/2fd/graphdoc

```
npx @2fd/graphdoc -e http://localhost:8080/v1/graphql -o ./doc/schema
```

If you just want the entire `schema.graphql`, you can use an introspection query and save the result:

https://github.com/hasura/graphqurl

```
npx graphqurl http://localhost:8080/v1/graphql --introspect > schema.graphql
```
