### ISSUE TITLE
Columns of data results (table, views, etc.) are collapsed 

### ISSUE THREAD

**Issue by elMatadito** [hasura/graphql-engine#5844]
Hello!
I'm testing the Brave browser and the styles for the results on data section isn't working correctly, the columns are collapsed. In Chrome looks good, but for Brave is not.

![image](https://user-images.githubusercontent.com/6616760/94318741-cf611700-ff4e-11ea-88e5-6e16ccb82352.png)

What could be? Thanks

_PD: I'm in the v1.0.0-beta.2_

**Comment by Ckbhatia** [comment]
Hi @elMatadito,

Can you please share a bit more info?

What is your browser's build version?
What is your machine OS?

These info would help to reproduce and fix this issue.

**Comment by elMatadito** [comment]
I found the problem/solution. Turning off the shield of Brave works again. This happens because hasura loads an external script 

Example: 
![image](https://user-images.githubusercontent.com/6616760/97041506-47623300-1535-11eb-9ba1-247a54d8e629.png)
