### ISSUE TITLE
migrate create command fails with error

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#585]
```bash
$ hasura migrate create new
Error: error creating migration files: mkdir : no such file or directory
```

**Comment by joninsky** [comment]
I still get this error. I checked my CLI version.

```shell
hasura CLI version: v0.4.12
GraphQL Engine CLI version:  v1.0.0-alpha22
```
I'm trying to follow [this documentation](https://docs.hasura.io/1.0/graphql/manual/migrations/existing-project.html).

**Comment by shahidhk** [comment]
@joninsky Sorry about that. This is not released yet.

You can manually create the two required files:

```
001_init.up.sql
001_init.up.yaml
```
