### ISSUE TITLE
cli: make YAML parsing errors user friendly and actionable

### ISSUE THREAD

**Issue by hasparus** [hasura/graphql-engine#5850]
## The Problem

I got this error today.

> graphql-engine_1  | time="2020-09-28T05:22:11Z" level=fatal msg="failed to apply metadata: cannot apply metadata on the database: [parse-failed] using should be an object ($[1].tables[15].array_relationships[2].using)"

 `$[1].tables[15].array_relationships[2].using` describes the location of the error accurately, but not for a human.

I had to write a script to discover I was missing a tab in tables.yaml.

![image](https://user-images.githubusercontent.com/15332326/94394433-a06cc000-015d-11eb-9039-1bd08564f540.png)

### Showing file path, line and character numbers

A location where the error occurred would be super **actionable**.

```
hasura/metadata/tables.yaml:316:7: [parse-failed] using should be an object
```

Written in a standard way, paths like this can be used to jump straight to the point in text editors either by clicking in an integrated or by pasting to <kbd>go to file</kbd> input.

![image](https://user-images.githubusercontent.com/15332326/94396325-f93e5780-0161-11eb-9f11-2a13ce476b72.png)

### Domain-specific context

The parsing error occured while parsing an array relationship named `my_array_relationship_name` in table `my_table`.
Names would make it easier to find the problem.

### Great error messages suggest fixes

This probably requires too much work, but I wanted to mention it.

> Errors should suggest fixes and hints where possible. These should be inferred and filtered from usage to reduce surfacing irrelevant and unhelpful messages.
>
> _from Rome toolchain philosophy — https://romefrontend.dev/#technical_

chrisdone's ["Good parser messages with Parsec"](https://gist.github.com/chrisdone/fd6c6f6a8c5b5d4d3c3f91289343629f) is also a read I enjoyed.

How could it look like?

> hasura/metadata/tables.yaml:316:7: [parse-failed] using should be an object
>
> The `using` property is empty, and there is an extra `foreign_key_constraint_on` in the relationship object.
> Is your YAML indented properly?

This would be soo _nice_, but I suppose that it requires a lot of additional work.

**Comment by tirumaraiselvan** [comment]
Hi

Could you tell us which version of `graphql-engine` are you running?

**Comment by hasparus** [comment]
Sure thing, I'm using `hasura/graphql-engine:v1.3.2.cli-migrations-v2` image.

**Comment by James-Firth** [comment]
I believe this is the same request so adding my vote and details:

I had this issue come up when `git` merge between 2 devs caused some mangled `yaml`, but it slipped through the PR review until I ran

```
➜ hasura metadata apply
FATA[0000] error applying metadata 
cannot build sources from project: yaml: line 185: did not find expected key 
```

Which is _so close_ to being actionable, but it doesn't tell me what file! I happened to be able to check git diffs to sort it out.

I would love if it could tell me the file that was being parsed when this happened.
(a bonus would be have a flag to output the combined file as I presume all the yaml files are combined into either a yaml or JSON object before getting pushed to hasura engine)


And since you asked about version here's mine:
```
➜ hasura version
INFO hasura cli                                    version=v2.0.0-beta.1
INFO hasura graphql engine                         endpoint="http://localhost:8080/" version=v2.0.0-alpha.10
```

**Comment by scriptonist** [comment]
This has partially been addressed as part of https://github.com/hasura/graphql-engine/issues/7020 (which should be available in latest releases)

Also closing issue this in favour of https://github.com/hasura/graphql-engine/issues/7350 to address this generally across CLI
