### ISSUE TITLE
community: translations 

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#5851]
We want to embrace a multi-cultural community, and we'd love to have some of our content available in several languages. If you're a native speaker of a language other than English, we'd love to see your contribution 🙂 

We welcome translations for the following files:

- https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md
- https://github.com/hasura/graphql-engine/blob/master/README.md
- https://github.com/hasura/graphql-engine/blob/master/SECURITY.md
- https://github.com/hasura/graphql-engine/blob/master/code-of-conduct.md

This is how you should proceed:

1. Scroll down to the very bottom where you find existing translation. Make sure that the language you want to translate into is not yet available
2. Add a file with the translation of your language
3. Make sure all links are working
4. Make sure links in the table of contents are working
5. Add the translation link to the English file at the bottom under "Translations"

Contributing guide: follow our [contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md).

Note: we'll have each translation checked by a native speaker. We will *not* accept translations that have been copy-pasted in Google Translate.

We're looking forward to your contribution 🙌

**Comment by daniloff200** [comment]
Coool!

I can help with Ukrainian translations, and, with Russian, when it wasn't created

**Comment by akash1997** [comment]
I would like to contribute the translation for the above docs in Hindi.

**Comment by rafaeelaudibert** [comment]
Hi! I'd be glad to translate them to Portuguese!

**Comment by GuyKh** [comment]
I'll do Hebrew

**Comment by estim** [comment]
I'll do Russian translation for [CONTRIBUTING.MD](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)

**Comment by ErickJoestar** [comment]
I'll do Spanish

**Comment by adithyaakrishna** [comment]
@uravgkarthik Noduuu

**Comment by AshishMhrzn10** [comment]
I would like to contribute in Nepali language..

**Comment by nikita812** [comment]
i will do hindi

**Comment by Naveenaidu** [comment]
> i will do hindi

@nikita812 As a heads-up(_and also to avoid duplicating efforts_), if you are attempting to translate the docs, please do note that - There's already an Open PR for `CONTRIBUTING.md` docs. But please feel free to translate any of the remaining documentation as mentioned in the issue :)

**Comment by vieee** [comment]
I'll do that it Marathi..!

**Comment by Yashs911** [comment]
Hi, @marionschleifer I would like to do Hindi translation for https://github.com/hasura/graphql-engine/blob/master/code-of-conduct.md .

**Comment by upedd** [comment]
Could i do it in Polish?

**Comment by chicken-biryani** [comment]
hi, I would line to make a bengali translation for  https://github.com/hasura/graphql-engine/blob/master/code-of-conduct.md

**Comment by Naveenaidu** [comment]
Apologies, I accidentally clicked the `Close Issue` button. Sorry for the notification :/

**Comment by Naveenaidu** [comment]
@upedd Please go ahead with the translation, But before you start your work - It would be really nice if you could comment here, what docs would you like to translate. Just

**Comment by upedd** [comment]
@Naveenaidu all of them im 3/4 done

**Comment by adarsh-qclw** [comment]
Can I do a Malayalam translation?

**Comment by SeriousCorgi** [comment]
I'd like to contribute in Vietnamese

**Comment by rjn01** [comment]
Hi, I would like to do Hindi translation for README.md

**Comment by asyraf-labs** [comment]
Hi, I would love to do the Malay translation

**Comment by mee-kell** [comment]
Hello! I'm happy to translate all of these documents into Chinese!

**Comment by hillarysousa** [comment]
Hello, I'd like to translate the `CONTRIBUTING.md` file to Brazilian Portuguese :)

**Comment by pedrowoy** [comment]
Hello! It would be great to translate the `SECURITY.md` and `CODE-OF-CONDUCT.md` documents to PT-BR

**Comment by sushil97** [comment]
Hello, I'd like to translate the `code-of-conduct.md` and 'README.md' file to Hindi :)

**Comment by Yashs911** [comment]
> Hello, I'd like to translate the `code-of-conduct.md` and `README.md` file to Hindi :)

@sushil97 I already translated (Hindi) and created a PR for the code-of-conduct.md file

**Comment by Naveenaidu** [comment]
Hey @sushil97 , `code-of-conduct.md` already has a Open PR for it :see_no_evil: , and I see that someone else also said that they will be working on Hindi translation of `README.md`. In order to avoid duplication of work, It would really help us if you would translate `Security.md`.

cc @rjn01 Do you have plans to work on the the translation of `README.md`? If not, please do comment here - so that others can take up the task :)

**Comment by sushil97** [comment]
@Naveenaidu `Security.md` is already translated in hindi. Is'nt it?

**Comment by sushil97** [comment]
> > Hello, I'd like to translate the `code-of-conduct.md` and `README.md` file to Hindi :)
> 
> @sushil97 I have already translated and created a PR for the code-of-conduct.md file

ok

**Comment by Naveenaidu** [comment]
> @Naveenaidu `Security.md` is already translated in hindi. Is'nt it?

Ahh Sorry! My bad :/  

I would suggest you to wait until @rjn01 replies back, in order to avoid duplication of work. In the mean time, please do have a look at the other available issues that interests you :)

**Comment by sushil97** [comment]
> > @Naveenaidu `Security.md` is already translated in hindi. Is'nt it?
> 
> Ahh Sorry! My bad :/
> 
> I would suggest you to wait until @rjn01 replies back, in order to avoid duplication of work. In the mean time, please do have a look at the other available issues that interests you :)

Sure

**Comment by raihan71** [comment]
I can hack it Indonesia

**Comment by jerryjaimon** [comment]
Hello, I'd like to translate the code-of-conduct.md and CONTRIBUTING.md file to Malayalam :)

**Comment by rjn01** [comment]
@Naveenaidu @sushil97 I am working on the issue.  Sorry for the delay.

**Comment by AshishMhrzn10** [comment]
@marionschleifer can you check my PR #5891 . I have added Nepali language translation.

**Comment by fakhrip** [comment]
Im working on the indonesian part for contributing and security as i didnt see any PR regarding these translations...

**Comment by Wrth1** [comment]
I'll translate code-of-conduct.md to indonesian

**Comment by archit041198** [comment]
I can hack this in Punjabi

**Comment by shraddhavp** [comment]
@marionschleifer can i do it in Kannada?

**Comment by kentaro84207** [comment]
Hi! I'll translate `CONTRIBUTING.md`, `SECURITY.md` and `code-of-conduct.md` to Japanese.

**Comment by Wittty-Panda** [comment]
@marionschleifer hi 
I would like to translate in marathi language

**Comment by vieee** [comment]
Hi @Wittty-Panda, As a heads-up(and also to avoid duplicating efforts), if you are attempting to translate the docs, please do note that - There's already an Open PR for translation in the Marathi language. But please feel free to translate any of the remaining documentation as mentioned in the issue :)

**Comment by josselineperdomo** [comment]
Hello! I'd like to translate the code of conduct in Spanish :)

**Comment by y-martinez** [comment]
Hello! the `README` in Spanish is outdated I would like to work with that file

**Comment by DebugAgrawal** [comment]
**Hey I would love to translate the code of conduct in Marathi (मराठी)**

**Comment by DebugAgrawal** [comment]
**Please review if any change required**

**Comment by y-martinez** [comment]
Hi! @marionschleifer sorry for the inconvenience, but it would be possible that meanwhile we awaiting for a PR review, you could add the label hacktoberfest-accepted to our PRs so that the verification time of the Hacktoberfest begins because now we need await for two weeks for mature.

**Comment by shaonkabir8** [comment]
Hi [Marion Schleifer](https://github.com/marionschleifer) :wave: 
:pray: Wishing :house_with_garden:   a good day from :bangladesh: Bangladesh 
I'm highly interested :raised_hand_with_fingers_splayed:  to translate all the available docs you've mentioned above in **Bengali** :bangladesh:  
-  [CONTRIBUTING](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)
-  [README](https://github.com/hasura/graphql-engine/blob/master/README.md)
-  [SECURITY](https://github.com/hasura/graphql-engine/blob/master/SECURITY.md)
-  [Code of conduct](https://github.com/hasura/graphql-engine/blob/master/code-of-conduct.md)

I love :heart: graphql-engine and obviously I'll be :100:  honoured to contribute here. 
Hopefully this journey will be exciting enough to be motivated till the last moment. :rocket: 

Thanks.

**Comment by jrcamelo** [comment]
Added #6038 that fixes some typos and adds remote-schemas.md to the PT-BR translations.

**Comment by tylerhannan** [comment]
All.

Thank you for your participation in this issue.

Sadly, we are in a situation where a number of the translation requests we have received are machine generated. So, for now, I am going to be closing this issue.

I will leave the related PRs that are referenced herein, or directly submitted, open and reach out through the community or network for native speakers to review. 

For those who participated authentically, thank you for helping us bring Hasura to you in your language. It is appreciated.

**Comment by tacoelho** [comment]
> All.
> 
> Thank you for your participation in this issue.
> 
> Sadly, we are in a situation where a number of the translation requests we have received are machine generated. So, for now, I am going to be closing this issue.
> 
> I will leave the related PRs that are referenced herein, or directly submitted, open and reach out through the community or network for native speakers to review.
> 
> For those who participated authentically, thank you for helping us bring Hasura to you in your language. It is appreciated.

hey there, mine was not machine generated and I can help fixing the PT-BR translations. Some have bad mistakes.

**Comment by tylerhannan** [comment]
@tacoelho - That would be immensely helpful.

Please feel free to tag me directly if you've reviewed a thing and I can work to get it merged. I'll also re-review your contribution so that we can get it merged.

**Comment by daniloff200** [comment]
well, can say the same about my Russian / Ukrainian translations, that's not google translate copypaste
I also see one more contribution from @estim in Russian, which also needs review. I can do that, I think

**Comment by tylerhannan** [comment]
Awesome @daniloff200 - The same request applies...and the same appreciation for the time and effort that an actual translation takes.

Please tag me when/if you have been able to review and I can get merged. I'll also add your translation to the list.

**Comment by GuyKh** [comment]
@tylerhannan Mine (https://github.com/hasura/graphql-engine/pull/5911) was done manually - so I'd really be glad if it won't go to waste.

**Comment by estim** [comment]
@tylerhannan my translation (#5880) was done manually. I hope it won't be wasted and could be used in future updates. 
If anyone (@daniloff200 or any other member) could review it and use for future needs I'd be glad.
