### ISSUE TITLE
infra: add check for images in docs

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#5853]
### Motivation

As explained in [this guide](https://github.com/hasura/graphql-engine/wiki/How-to-write-docs-pages#images), we should compress images that are added as part of a docs pull request. This sometimes gets forgotten and then a PR gets merged with too large images.

### Instructions

We should make this part of the PR process. I've added a label called `docs-compress-images`. 

We should write a GitHub action that checks the following:

- Is it a docs PR?
- Has one or more images been added?

If the answer to both is yes, the build should only succeed if the label `docs-compress-images` is added. Otherwise it should fail.

### Reference

We have a similar (yet not exactly the same) [use case for the changelog label](https://github.com/hasura/graphql-engine/blob/master/.github/workflows/changelog.yml). You can check it out for inspiration.

**Comment by Hard-Coder05** [comment]
@marionschleifer 
Is it like the default PR form must contain two checkboxes asking 1.) is it a docs PR and 2.) has one or more images been added, then if both are yes then add "docs-compress-image" tag on the PR

**Comment by marionschleifer** [comment]
@Hard-Coder05 no, no check boxes. It's supposed to be a Github action that is doing these checks.

**Comment by Hard-Coder05** [comment]
@marionschleifer I am working on it! Please assign it to me!

**Comment by wicked-smart** [comment]
hey, @Hard-Coder05 , i'm sure you would be aware of cases where your **checks** are failing (missing update in CHANGELOG.md  regarding changes made  and in your [ action script ](https://github.com/hasura/graphql-engine/pull/5871/commits/6507510efd07bad5226b3bd4ff9ecdf5601f953e),line **33**  change `changeLogPresent = true;` to `imageAdded = true `) 

  Since , i'm farely new to this circleCI thing , i have no idea how to get my all **ci/circleCI** tests getting passed, but  i think your action script will work smoothly after doing above changes.

**Comment by wicked-smart** [comment]
Hi, @marionschleifer , my all checks have passed. Can you take a look into it?

P.S:- Major Noob here regarding opensource contributions, please excuse if i do something silly :-)

**Comment by Hard-Coder05** [comment]
@wicked-smart 
I have made a PR on the same issue! How can you make a PR for a issue which is taken?

**Comment by wicked-smart** [comment]
@Hard-Coder05 ok boss , my bad ...relax !!! , as i said i'm quite new to this.  I guess one needs to get assigned to make PR . I saw your check didn't passed , so then fixed it and pushed. 

Alright, buddy, please enlighten me on what should i do now....is there a thing called deleting PR or something ?

**Comment by marionschleifer** [comment]
@Hard-Coder05 @wicked-smart thank you both for your PR. Please be nice to each other, it's all good. We don't assign issues as explained in our [Hacktoberfest blogpost](https://hasura.io/blog/hasura-joins-hacktoberfest-3rd-year-in-a-row/).

@Hard-Coder05 I made a comment on your PR. 

@wicked-smart it's great that you've started contributing to open source. Let's leave your PR open for now, until the other one is merged. We explain in the blogpost how to look for issues. If you need help, it's also explained in the blogpost where to get it 🙂

**Comment by Hard-Coder05** [comment]
@marionschleifer yes sure! am working on it!

**Comment by wicked-smart** [comment]
@marionschleifer Thanks for your considerate response, since I was to learn and implement a GitHub action , which I think is pretty cool tool for an effectively automating CI/CD pipeline, I chose this issue ...anyway, will be going through other `Hacktoberfest` labelled issues for a potential PR
