### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by sasog23** [hasura/graphql-engine#5860]
would it be possible to set a permission for the nested objects (relationships), 
to be visible if an user has the permission for the parent object

**Comment by GavinRay97** [comment]
Relationships inherit the permissions for each table in the chain. So select `user -> posts` would check the individual permissions for both a person's access to the `user` table + row, and then the `posts` table + row.

You can create this behavior by just checking the same condition in both tables. IE:
```
Role "user", table "user": { id: { _eq: "X-Hasura-User-Id" } }
Role "user", table "post": { user: { id: { _eq: "X-Hasura-User-Id" } } }
```

For more info, there is some documentation around this here:
https://hasura.io/docs/1.0/graphql/core/auth/authorization/permission-rules.html#using-relationships-or-nested-objects

:+1:
