### ISSUE TITLE
[Schema/Metadata] Memory leak

### ISSUE THREAD

**Issue by Difrex** [hasura/graphql-engine#5868]
Hi!

This issue is related to #5536. Same environment but with increased memory limits on the Hasura pod.

The Hasura doesn't release memory after permissions creations. And memory usage over time grows linearly.

![hasura_memory](https://user-images.githubusercontent.com/3982213/94655698-ad2d1780-0307-11eb-973d-a4080dc5577a.png)

**Comment by jberryman** [comment]
I'm going to close this and treat this as additional info for #5536 . Thanks for reporting!

Referencing canonical memory issue #3388
