### ISSUE TITLE
Event-Trigger error logs of type "could not serialize access due to concurrent update"

### ISSUE THREAD

**Issue by aklinkert** [hasura/graphql-engine#5933]
Hi hasura team,

at the current customers project we're having some issues with scaling hasura. We run hasura in a kubernetes deployment with HPA (min 3, max 10 pods) and face a lot of the attached `event-trigger` error logs during high write load (1200-4000 transactions per second). This is technically not a problem, but the logs are of a significant amount and it seems to be something that is improvable. :)

(_I already tried to move the event trigger handling to one specific worker node by setting `HASURA_GRAPHQL_EVENTS_HTTP_POOL_SIZE=0` on all pods that serve HTTP traffic and spin up a dedicated worker node that is not serving HTTP, but unfortunately this does not get rid of the logs, neither on the worker instance nor on the GQL instances._) **EDIT:** This actually makes things worse. I understood this env var as if I could disable the event dispatching with it, but that is not the case. Too bad!

### Additional information: 

- Hasura 1.3.2
- Custom docker image FROM `hasura/graphql-engine:v1.3.2.cli-migrations-v2`
- Google Cloud SQL Postgres 12
- Schema migrations managed with https://github.com/golang-migrate/migrate, only metadata handled by hasura

### Log message:

```json
{
  "type": "event-trigger",
  "timestamp": "2020-10-06T09:37:34.719+0000",
  "level": "error",
  "detail": {
    "internal": {
      "statement": "\n      UPDATE hdb_catalog.event_log\n      SET locked = 't'\n      WHERE id IN ( SELECT l.id\n                    FROM hdb_catalog.event_log l\n                    WHERE l.delivered = 'f' and l.error = 'f' and l.locked = 'f'\n                          and (l.next_retry_at is NULL or l.next_retry_at <= now())\n                          and l.archived = 'f'\n                    ORDER BY created_at\n                    LIMIT $1\n                    FOR UPDATE SKIP LOCKED )\n      RETURNING id, schema_name, table_name, trigger_name, payload::json, tries, created_at\n      ",
      "prepared": true,
      "error": {
        "exec_status": "FatalError",
        "hint": null,
        "message": "could not serialize access due to concurrent update",
        "status_code": "40001",
        "description": null
      },
      "arguments": [
        "(Oid 20,Just (\"\\NUL\\NUL\\NUL\\NUL\\NUL\\NUL\\NULd\",Binary))"
      ]
    },
    "path": "$",
    "error": "database query error",
    "code": "unexpected"
  }
}

```

**Comment by tirumaraiselvan** [comment]
We are working on a potential fix by refactoring the writes on the table to be in "Read Committed". It appears we can safely do it but we need to do some analysis, run tests and confirm.

**Comment by tirumaraiselvan** [comment]
Closed in https://github.com/hasura/graphql-engine/pull/6120 . Will be out in v1.3.3
