### ISSUE TITLE
Bug when creating cron with '/' in name

### ISSUE THREAD

**Issue by rolivegab** [hasura/graphql-engine#5935]
Cron is created succesfully:
![image](https://user-images.githubusercontent.com/7359906/95191980-e81bc900-07a7-11eb-8e55-ba785de16f19.png)

But when i click on it, this happens:
![image](https://user-images.githubusercontent.com/7359906/95191920-d0444500-07a7-11eb-9396-1980146bfd62.png)

[EDIT]

Just to being more informative, accessing url at: `http://localhost:9695/console/events/cron/cron%2Fclear-confirmation-codes/modify` manually works.

**Comment by kentaro84207** [comment]
Could I work on this issue?

**Comment by beerose** [comment]
Sure @kentaro84207!

I guess we need to use `encodeURIComponent` function for cron trigger name in the path, as we do for example here: https://github.com/hasura/graphql-engine/blob/master/console/src/components/Common/utils/routesUtils.js#L7.
