### ISSUE TITLE
disable event triggers

### ISSUE THREAD

**Issue by aklinkert** [hasura/graphql-engine#5937]
For a HA deployment in kubernetes I would like to disable the event trigger handling in all instances that serve GQL traffic (which are managed by the HPA) and handle all of the event trigger processing on a single worker instance. Is there already an ENV var or cli flag to do so?

The main reason is that we see a significant amount of error logs due to concurrent tries to lock the event_log Table and fetch new events from all of the (up to) 10 pods serving GQL traffic described in #5933 , also the event trigger handler themselves speak to the GQL API of hasura and thus the whole event trigger load amplifies up to a point where the DB is under very high load.

**Comment by maxpain** [comment]
Any updates on this?

**Comment by Svarto** [comment]
+1

**Comment by tirumaraiselvan** [comment]
You can set environment 
variable `HASURA_GRAPHQL_EVENTS_FETCH_INTERVAL: 0` to prevent event processing.

**Comment by tuanalumi** [comment]
When I set `HASURA_GRAPHQL_EVENTS_FETCH_INTERVAL` to 0 in Hasura Cloud, it says the value has to be non-negative. I believe that is a bug?

**Comment by hgiasac** [comment]
@tuanalumi yes, that is a bug. Thanks for letting us know.
We already fixed that bug. You can try again.
