### ISSUE TITLE
Include the CLA (Contributor License Agreement) in Contributing Guidelines

### ISSUE THREAD

**Issue by Bharat123rox** [hasura/graphql-engine#594]
Currently, all of Hasura's Contributing or Readme instructions do not mention that the contributor has to sign a CLA (Contributor License Agreement). It may be trivial to some, but not all.

I have tried to fix this in PRs #590, #591, #592, #593 to cover all Contributing docs I am aware of

**Comment by karthikvt26** [comment]
Good find and great work @Bharat123rox.

**Comment by shahidhk** [comment]
Thanks for the contribution @Bharat123rox. Can you merge #590, #591, #592 and #593 in one PR and close others?
