### ISSUE TITLE
Possible Bug: Computed Field Permission is not being inferred

### ISSUE THREAD

**Issue by LydiaF** [hasura/graphql-engine#5974]
Hi there,

I have a computed field, `order`, for which I believe the inferred permission is incorrect. If my understanding is correct, the permission box is meant to be checked *and disabled* if the computed field permissions are inferred from the table from which it is derived. However, it is unchecked and  *not* disabled.

![image](https://user-images.githubusercontent.com/10000865/95596295-1c5fe580-0a45-11eb-831b-a83563db317e.png)
 

![image](https://user-images.githubusercontent.com/10000865/95595973-b5dac780-0a44-11eb-8069-f301244fd0cc.png)

As can be seen below, the permission for the value returned by the sql function is enabled on the table that the computed field is derived from:

![image](https://user-images.githubusercontent.com/10000865/95596055-cf7c0f00-0a44-11eb-80b7-a5981f5e49c9.png)

I am doing metadata programatically so I have to come to the console afterwards and check this box in order for things to work at all!

I have seen this pull request, https://github.com/hasura/graphql-engine/pull/5741, maybe this issue I am having relates to this?

We are using 1.3.2. 

Thanks!

**Comment by LydiaF** [comment]
Hey, we just updated to 1.3.2 and the permission *is* being inferred correctly. Great that this looks like it is fixed!

However, the checkbox is still not disabled. Shouldn't the checkbox be completely disabled for permission columns on computed fields?

Thanks!

**Comment by tirumaraiselvan** [comment]
Computed field needs to be checked explicitly in the column list for it to be visible for the role. This is because you may want some computed field to be visible for role1 but not for role2.

**Comment by LydiaF** [comment]
Hi @tirumaraiselvan, thanks for getting back to me so quickly.

That's all cool, it just really doesn't seem to be working like that for me – I can't achieve setting the permission  through applying metadata programatically. I am getting an error that aligns with what is written in the docs ("For table computed fields, the permissions set on the return table are respected.") about automatic inference.

```
INFO hasura cli is up to date                      version=1.3.2
FATA[0009] failed to apply metadata: cannot apply metadata on the database: [unexpected] cannot continue due to inconsistent metadata ($.args[1].args)

reason: in table "level_rounds": in permission for role "user": expecting a postgres column; but, "order" is a computed field; permissions for relationships are automatically inferred
type: select_permission
definition: 
{
  "comment": null,
  "permission": {
    "allow_aggregations": false,
    "columns": [
      "id",
      "order",
      "level_platonic_id",
      "round_platonic_id",
      "recorded_by_id",
      "valid_period",
      "sys_period"
    ],
    "computed_fields": [],
    "filter": {}
  },
  "role": "user",
  "table": {
    "name": "level_rounds",
    "schema": "public"
  }
}```

**Comment by tirumaraiselvan** [comment]
Got it. One thing that seems off in the API above is that `computed_fields` is `[]`. Shouldn't `order` be defined in `computed_fields` section too?

**Comment by LydiaF** [comment]
Hi @tirumaraiselvan,

Thanks again for getting back so quickly. Thanks for explaining that, I didn't realise the difference between visibility and permission, and yes, you are right that there is something off with with the empty array for computed fields. (The computed field is definitely being applied though...)

Sadly however, I believe the problem is still there. I am going to use a different example as it is simpler and I can copy and paste it more easily. I am using the sdk that I learned about in a community call from @GavinRay97 :)

```ts
import { TableEntry } from '../sdk'

const plevel_players: TableEntry = {
  table: { schema: 'public', name: 'plevel_players' },
  array_relationships: [
    {
      name: 'plevel',
      using: {
        manual_configuration: {
          remote_table: 'plevels',
          column_mapping: {
            user_platonic_id: 'user_platonic_id',
          }
        }
      }
    },
  ],
  computed_fields: [
    {
      name: 'card_order',
      definition: {
        function: {
          name: 'card_order_function_for_plevel_players',
          schema: 'public'
        },
        table_argument: 'pp_row'
      }
    },
  ],
  object_relationships: [
    {
      name: 'card',
      using: {
        manual_configuration: {
          remote_table: 'cards',
          column_mapping: {
            card_platonic_id: 'platonic_id'
          }
        }
      }
    }
  ],
  update_permissions: [
    {
      role: 'user',
      permission: {
        check: {
          user_platonic_id: 'X-HASURA-USER-ID'
        },
        set: {
          user_platonic_id: 'X-HASURA-USER-ID'
        },
        columns: [
          'user_platonic_id',
          'card_platonic_id',
          'name',
          'submitted',
          'ready_for_next'
        ],
        filter: {}
      }
    }
  ],
  insert_permissions: [
    {
      role: 'user',
      permission: {
        check: {},
        set: {
          user_platonic_id: 'X-HASURA-USER-ID',
          submitted: 'false',
          ready_for_next: 'false'
        },
        columns: [
          'user_platonic_id',
          'card_platonic_id',
          'name',
        ],
      },
    },
  ],
  select_permissions: [
    {
      role: 'user',
      permission: {
        columns: [
          'user_platonic_id',
          'card_platonic_id',
          'name',
          'ready_for_next',
          'submitted',
          'card_order'
        ],
        filter: {
          "user_platonic_id": "X-HASURA-USER-ID"
        }
      },
    },
  ],
  delete_permissions: [
    {
      role: 'user',
      permission: {
        filter: {
          "user_platonic_id": "X-HASURA-USER-ID"
        }
      }
    }
  ]
}

export default plevel_players

```

This is the error message:

```bash
FATA[0016] failed to apply metadata: cannot apply metadata on the database: [unexpected] cannot continue due to inconsistent metadata ($.args[1].args)

reason: in table "plevel_players": in permission for role "user": expecting a postgres column; but, "card_order" is a computed field; permissions for relationships are automatically inferred
type: select_permission
definition: 
{
  "comment": null,
  "permission": {
    "allow_aggregations": false,
    "columns": [
      "user_platonic_id",
      "card_platonic_id",
      "name",
      "ready_for_next",
      "submitted",
      "card_order"
    ],
    "computed_fields": [],
    "filter": {
      "user_platonic_id": "X-HASURA-USER-ID"
    }
  },
  "role": "user",
  "table": {
    "name": "plevel_players",
    "schema": "public"
  }
} 
```

However, if `card_order` select permission is commented out, the metadata *does* work and it looks like this on the console after:

![image](https://user-images.githubusercontent.com/10000865/95783577-0d3d9980-0cca-11eb-81b7-fe0b68601078.png)

Thank you so much for looking into this! It is pretty tedious as I need to go into multiple tables on the console and tick the boxes every time I reapply md!!

**Comment by tirumaraiselvan** [comment]
@GavinRay97 Can you take a look at the SDK side?

**Comment by LydiaF** [comment]
Dear Hasura,

This is still a major issue for us.

I do not think the issue is just to do with the sdk, as when I skip the sdk part and just add it directly to the yaml, I get: ""Inconsistent object: in table \"my_table\": in permission for role \"my_role\": expecting a postgres column; but, \"my_c_filed\" is a computed field; permissions for relationships are automatically inferred""

It would be great if you could fix this as having to go through and do this by hand each time the md gets updated....

Thank you

**Comment by GavinRay97** [comment]
Hey Lydia, sorry for not replying sooner - I think this got lost in my inbox.

Would you be willing to double-check something really quick?
1. Export `metadata.json` from the web console
2. Manually add the metadata using the web console, so that the computed field is set up properly
3. Export the `metadata.json` again
4. Do a diff between the original and the updated `metadata.json` -- which should give you back just the (proper) metadata object to add the computed field
5. Look at the shape of this JSON and see if it matches up to the Metadata SDK types

For two reasons this could be useful:
- A) The types in the Metadata SDK were all written entirely by hand so it's super possible (probable?) that I have made a mistake somewhere
- B) If the Metadata SDK types are correct but it's just not working -- then maybe worst case you now know exactly what JSON format the server wants for these computed fields to be acceptable and you can try to forcibly send them, like in the `replace_metadata` operation or similar.

**Comment by LydiaF** [comment]
Dear Gavin,

Thank you so much for replying so quickly and indeed for helping me fix the issue!!

It was all my fault.

Instead of doing this : 

```
  permission:  {
    computed_fields: [
      'card_order'
    ],
    columns: [...],
    ...
  }
```

```
  permission:  {
    columns: ['card_order', ...],
  }
```

Basically I didn't know `permission.computed_fields` was thing. Had a quick check of the docs there and can only see "For scalar computed fields, permissions are managed similar to the columns permissions of the table." but maybe I'm missing it... I was at the time certainly.

In any case I am glad as now I understand how to find bugs a bit better!

A BIG THANK YOU!

Lydia

**Comment by GavinRay97** [comment]
That's awesome to hear! Glad it was something able to be figured out =D
