### ISSUE TITLE
cli: hasura seeds --file adds `seeds` to path subverting expectations

### ISSUE THREAD

**Issue by kreempuff** [hasura/graphql-engine#5980]
Whenever I try to issue a command using `hasura seeds apply -f <FILEPATH>`, the command adds the `seeds` prefix to the path and errors 

I would expect it to use the relative file path as given so I can tab complete specific seed files.

Ex: 
```shell
hasura seeds apply --file seeds/1602160517233_resource.sql
FATA[0000] error opening file: open <REDACTED>/seeds/seeds/1602160517233_resource.sql: no such file or directory
```

Version info:

```
hasura version
INFO hasura cli                                    version=v1.3.2
INFO hasura graphql engine                         endpoint="http://localhost:8080" version=v1.3.2
```

**Comment by scriptonist** [comment]
currently, seed files are taken relative to the seed directory, https://github.com/hasura/graphql-engine/blob/1f2037947d9a9810849911092ffffa0dc55d37dc/cli/seed/apply.go#L27 this can be changed to take files relative to the project directory. Which should be fairly straight forward, Interchanging `ec.SeedsDirectory` with `ec.ExecutionDirectory` should do the trick.

**Comment by kreempuff** [comment]
Sweet, I can take this on then

**Comment by Yashs911** [comment]
@kreempuff I would like to work on this issue.

**Comment by kreempuff** [comment]
@Yashs911 sure, looks like someone took it up already though

**Comment by Yashs911** [comment]
@kreempuff at least one should first claim the issue. No problem I will take some other issue.

**Comment by kreempuff** [comment]
@Yashs911 Yeah, I'm not really familiar with the process, sorry!

**Comment by fumblehool** [comment]
@Yashs911 @kreempuff Apologies for the confusion.
The issue was unassigned and I missed the last 3 comments.
I'm more than happy to delete the PR if you want to work on this issue.

**Comment by Yashs911** [comment]
@fumblehool it's okay, no need to delete the PR.

**Comment by James-Firth** [comment]
I would also like this. This would allow us to separate out some test data from real data or conditionally add data more easily.

**Comment by ShubhamPalriwala** [comment]
Hey, Can I open a quick PR for this fix?
