### ISSUE TITLE
server: cryptic permission error for select filter violation

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#5984]
I faced a strang issue recently which was quite hard to debug:

```json
{
	"errors": [{
		"extensions": {
			"path": "$",
			"code": "data-exception"
		},
		"message": "time zone \"c5e28365-55c1-4368-ac9b-4ac87e85727b\" not recognized"
	}]
}
```

This was because I had made a mistake while creating a select permission rule:

```json
{
       "created_at": { "_eq": "x-hasura-user-id" }
}
```

It was a mistake because I intended to set the filter on `creator_id` rather than `created_at`. A more intstructive error would have helped with debugging.

**Comment by tirumaraiselvan** [comment]
Because of Hasura's "push down of permission clause" architecture, not sure if system could have given a better error message. Anyway, let's tackle this in https://github.com/hasura/graphql-engine/issues/3658
