### ISSUE TITLE
ask for confirmation before deleting an event trigger

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#599]
The `Delete Trigger` button on `Events > Manage > Triggers > <trigger-name> > Settings` page should ask for confirmation before deleting the trigger.

This can be a browser-level ask for confirmation prompt.

**Comment by shahidhk** [comment]
Go for it @akash1997. Also, reply with a time estimate if you can.

**Comment by akash1997** [comment]
I am going through the code. I will try to complete by today or tomorrow. Will ask for help if I get caught up somewhere.
