### ISSUE TITLE
enable analytics and allow opt-out for analytics

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#60]

**Comment by praveenweb** [comment]
@rakeshkky @shahidhk - console requires a env named isAnalyticsEnabled to be templated in window.__env part of index.html. The values can be boolean true/false.

**Comment by praveenweb** [comment]
@rakeshkky - server needs to add a new environment variable called DISABLE_CONSOLE_ANALYTICS and accept values true/false. Depending on this value, template console as specified above.

**Comment by shahidhk** [comment]
Server and CLI needs to take configuration to disable analytics.

**Comment by shahidhk** [comment]
@0x777 @rakeshkky We need to add an env var / config file variable called `HASURA_GRAPHQL_DISABLE_USAGE_REPORTING` which can be set to `true` to disable sending usage statistics to hasura.io

**Comment by shahidhk** [comment]
We are not implementing analytics on console.
