### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by TheColorRed** [hasura/graphql-engine#6006]
I am playing around with the new MySQL support, and I am not sure if this issue is a Hasura issue, MySQL issue, or an AWS RDS issue. So, I thought I would ask here. 

When running the docker container, over time I eventually cannot connect to the MySQL database, and I am getting this error:

> MySQL server has gone away

As of now I just restart the Container and I am back in business, but is there a way for me to avoid getting this? When using a MySQL editor such as MySQL Workbench or HeidiSQL, this doesn't happen.

**Comment by ddukepear** [comment]
Just ran into this issue as well

**Comment by toomanyjoes** [comment]
I also am getting this with the same setup. Help!

**Comment by tylerhannan** [comment]
Thanks for the report. 

There are some issue in the preview...and this is one. We are working through them.

For now, the workaround is as you describe...restart the container or the instance. As we progress towards final release we'll address it fully.

**Comment by raajnadar** [comment]
@tylerhannan when can we expect a stable release?

**Comment by linuxexp** [comment]
@tylerhannan Any progress on this, I am trying `hasura/graphql-engine:pull5655-633f084f` but issue still exists.

**Comment by ebrake** [comment]
Sounds like Hasura is trying to use a mysql connection that has gone stale, needs a HASURA_GRAPHQL_PG_CONN_LIFETIME equivalent for expiring old connections after some amount of time

**Comment by kincjf** [comment]
HASURA_GRAPHQL_PG_CONN_LIFETIME Does this setting value work in the current hasura mysql version as well? I keep getting "MySQL server has gone away" issue.

**Comment by rsd1122** [comment]
We recently launched our new MySQL alpha integration:
https://hasura.io/docs/latest/databases/mysql/index/

It has support for queries, table relationships and permissions. Support for mutations is coming soon.

Please reach out to me if you would like to be a part of the early-access slack channel where we post the latest builds and updates.
