### ISSUE TITLE
subscriptions

### ISSUE THREAD

**Issue by sasog23** [hasura/graphql-engine#6012]
i'm subscribed to a table with more than 400.000 records

works fine
subscription MySubscription {
  test_events(limit: 100) {
    id
    updated_at
  }
}

while setting the limit to 1000, i'm getting response every second, without changing data
subscription MySubscription {
  test_events(limit: 1000) {
    id
    updated_at
  }
}

![image](https://user-images.githubusercontent.com/43674468/95955997-f26c4180-0dfd-11eb-89ef-68fa4507597c.png)

**Comment by tirumaraiselvan** [comment]
Without having an `order_by`, the result of a `limit: 1000` query could be arbitrarily different. This is because PG doesn't guarantee any order of tuples without an explicit order_by.

Try adding an `order_by` to your `where` clause.
