### ISSUE TITLE
Hasura translates unspecified mutation variables in SQL query as `null` yielding unwanted/unexpected behavior

### ISSUE THREAD

**Issue by larsblumberg** [hasura/graphql-engine#6016]
**Request payload** (replaced `\n` with real lin feed to increase readability):

```
{
  "operationName": "upsertOrganization",
  "variables": {"name": "someName"},
  "query": "mutation upsertOrganization($city: String, $id: uuid, $name: String, $street: String, $zipCode: String) {
    insertOrganization(
      object: {city: $city, id: $id, name: $name, street: $street, zipCode: $zipCode},
      on_conflict: {
        constraint: organizations_pkey,
        update_columns: [city, name, street, zipCode]
      }
    ) {city id name street zipCode}
  }"
}
```

Hasura replies with `Not-NULL violation. null value in column "id" violates not-null constraint"`.

As `id` column has `default: gen_random_uuid()` set, this response message from Hasura implies that Hasura run an insert query with the new row having `id = null` instead of _not specifying `id` at all_ so that Postgres can use the default value instead.

**(Supposed) actual behavior**: Hasura auto-fills `id` column with `null` (leading to the constraint violation)

**Wanted behavior**: Not specifying a column leaves auto-filling to Postgres
 
Related: https://github.com/hasura/graphql-engine/issues/1456

**Comment by tirumaraiselvan** [comment]
Hi @larsblumberg 

Indeed this is exactly the situation in #1456 . Closing as dupe. Let's continue the discussion there.
