### ISSUE TITLE
[hasura cloud] custom cert

### ISSUE THREAD

**Issue by jeveleth** [hasura/graphql-engine#6045]
I am using Hasura Cloud with GCP's Cloud SQL. Currently, if I require SSL connections in GCP, then I cannot connect directly to Hasura Cloud, as there is no option to pass in a client certificate. Is it possible for Hasura to enable a configuration improvement that supports passing in client certificates?

**Comment by devthejo** [comment]
Same problem here, I can't connect on https kubernetes ingress using hasura cli on my dev server that use local CA generated by mkcert, I get:
`FATA[0000] version check: failed to get version from server: failed making version api call: Get "https://hasura.my.localdomain/v1/version": x509: certificate is valid for ingress.local, not hasura.my.localdomain`

**Comment by dohomi** [comment]
Further more I am interested if the connection between Hasura Cloud and GCPs Cloud SQL is actually encrypted? Is it enough to attach `?sslmode=require` to the connection string?

**Comment by pablocastellanos** [comment]
Hey Hasura team! Any updates on this issue? I was told by the customer service team that it had an ETA for the end of last month. Thanks!

**Comment by tirumaraiselvan** [comment]
Work is in progress, we hope to have it in about 2 weeks.

**Comment by pablocastellanos** [comment]
Hello Hasura Team, any update on this request? Sorry for the hassle but this is a big blocker since we want to move away from IP based security into SSL. Thanks!

**Comment by dsandip** [comment]
Related issue: https://github.com/hasura/graphql-engine/issues/7249

**Comment by shahidhk** [comment]
This feature is now available on Console.
![image](https://user-images.githubusercontent.com/4124733/128850771-3cca0824-060d-47ca-9978-c4b4fe2a3d62.png)
