### ISSUE TITLE
deadlock with metadata apply and running subscriptions

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#6052]
This was seen by a user (Howard Wang#8417 Discord) in v1.3.2 when applying metadata:

2020-10-20 18:31:42 UTC:172.17.5.63(54744):t5br6hpuBHCetN33jJczdXRvTwfFXjBpANW5@hasura:[4585]:
DETAIL: Process 4585 waits for AccessExclusiveLock on relation 17646 of database 16396; blocked by process 458.

Process 458 waits for AccessShareLock on relation 17824 of database 16396; blocked by process 4585.

Process 4585: DROP FUNCTION IF EXISTS hdb_views."notify_hasura_channel_post_created_INSERT"() CASCADE

Process 458: SELECT "_subs"."result_id" , "_fld_resp"."root" AS "result" FROM UNNEST(($1)::uuid[], ($2)::json[]) AS...

This is causing `hasura metadata apply` command to fail and hence rollback of the desired upgrade.

**Comment by markerdmann** [comment]
@tirumaraiselvan We're also using subscriptions and we're seeing a similar issue with metadata apply, which I've detailed in this thread: https://github.com/hasura/graphql-engine/discussions/6066

This is causing about 20m of downtime on one out of every five to ten deploys. Is there anything we can do as an emergency fix to prevent the DROP FUNCTION from running during metadata apply?

**Comment by tirumaraiselvan** [comment]
@markerdmann How big would you say your hasura metadata is? How long does it take to get applied on a dev instance (i.e. no connected clients).

**Comment by markerdmann** [comment]
@tirumaraiselvan, answering your question above and the two questions from https://github.com/hasura/graphql-engine/discussions/6066:

1. We use 30+ triggers and dozens of subscription queries on our core tables. Unfortunately disabling the triggers would break the app.
2. We have about 50 tables. Our tables.yaml is the largest metadata file, and that's currently 190K. It typically takes just a few seconds to apply the metadata.
3. I'll run the the query today to see which locks are acquired and post an update.

**Comment by markerdmann** [comment]
@tirumaraiselvan This is what blocked state looks like for us. Let me know if you need additional detail.

![image](https://user-images.githubusercontent.com/187540/97645612-08d7e700-1a13-11eb-8bde-1b4f8051be44.png)

**Comment by ian-hayashi-jones** [comment]
Any update on this? I’m seeing the same issue

**Comment by tirumaraiselvan** [comment]
@markerdmann When you are facing this issue:

1) Are you creating any new event triggers or modifying existing event triggers in any way, i.e. any changes to `companyAdded` event trigger? 
2) Are you doing anything to the underlying table for the event trigger?

**Comment by markerdmann** [comment]
@tirumaraiselvan 

1. No, this happens even when nothing has changed in our Hasura migrations or metadata. The `companyAdded` event trigger was added more than six months ago and hasn't changed since.
2. We're not doing anything ourselves to the underlying table, but this is a production instance, so I would guess that the blocking queries might be from active Subscriptions? We do use Subscriptions extensively in our client app.

**Comment by tirumaraiselvan** [comment]
@markerdmann 

> No, this happens even when nothing has changed in our Hasura migrations or metadata.

Hmm, as per the design `DROP FUNCTION` is executed only if the event trigger is modified or the underlying table changes. There might be a bug but it's not easy to reproduce. Is it possible to share your migrations and metadata privately? If yes, then could you email to `tiru@hasura.io` ?

I also added a [question 3 above](https://github.com/hasura/graphql-engine/issues/6052#issuecomment-719887148) just before you replied.

**Comment by tirumaraiselvan** [comment]
@markerdmann You also mentioned in #6066 that this started happening recently. Any clues as to what changed in your application (assuming Hasura version, migration/metadata did not change)?

**Comment by markerdmann** [comment]
@tirumaraiselvan For #3, I initially assumed it was related to Subscriptions because of this Issue title, but I tested it locally and those long-running queries still appear when I cut off Subscriptions. I'll do some further investigation tomorrow to see if I can find the exact GQL that's connected to those long-running queries.

It does seem very strange that Hasura is running DROP FUNCTION for a very old event trigger which hasn't been modified. I've sent our migrations and metadata to your email. Also, looking at the company table, I think the most recent migration which modified that table was added on August 7, about 5 weeks before this bug appeared. Would a change to the permissions in metadata.yaml trigger the DROP FUNCTION?

In terms of recent changes that might have been a trigger, I haven't found a smoking gun. There was no recent Hasura upgrade (the last upgrade was to 1.3.1 on Sep 4) and no recent Hasura migration or metadata change (the last change happened 6 days before the bug appeared).

**Comment by tirumaraiselvan** [comment]
>  I initially assumed it was related to Subscriptions because of this Issue title, but I tested it locally and those long-running queries still appear when I cut off Subscriptions. I'll do some further investigation tomorrow to see if I can find the exact GQL that's connected to those long-running queries.

Subscription queries look like `SELECT "_subs"."result_id" ...` whereas `SELECT coalesce(json_agg("root"), '[]) ...` are regular queries. If you have the spreadsheet saved from [before](https://github.com/hasura/graphql-engine/issues/6052#issuecomment-719096114), then just directly copying that query and running against your prod DB would be safe.

Thanks for sending the migrations/metadata, we will continue investigating what might be causing `DROP FUNCTION` to be executed in the first place.

**Comment by markerdmann** [comment]
@tirumaraiselvan Thanks for the suggestion. I discovered that the blocking SELECT query is taking 50s or longer in production. After some digging I was able to unearth the source of that query, and it was coming from a backfill operation in our backend that runs on every deploy. That explains why it's interfering with the metadata apply so reliably. Luckily this backfill operation was written for a ledger table that is no longer used. After removing the backfill, I was able to deploy smoothly without a deadlock.

Now I expect that we'll be able to deploy without downtime going forward, so this resolves the urgency of the metadata apply bug for us.

Is it expected that a long-running query will deadlock metadata apply, or would you still consider this a bug in metadata apply? If it's the latter, let me know if there's any additional information I can provide that would help with the debugging effort.

**Comment by tirumaraiselvan** [comment]
That's good to know.

> Is it expected that a long-running query will deadlock metadata apply, or would you still consider this a bug in metadata apply?

Metadata apply might perform a DDL like DROP FUNCTION which will try to acquire exclusive lock on the table, this means if some other query is doing something on the table (even a SELECT) then DROP FUNCTION will wait to get the lock. If the query turns out to be long running then DROP FUNCTION and hence metadata apply will take that much time atleast. This is just postgres's concurrency mechanism and nothing much we can do here.

Although, the remaining question is why is DROP FUNCTION getting executed in the first place if there were no changes to the table or event trigger. Could you perhaps share the "diff" of the metadata that changed the last time you your metadata apply was "hung"?

**Comment by tirumaraiselvan** [comment]
@markerdmann First thanks for working with us on this issue. We have found why `DROP FUNCTION` was being called needlessly and it turned out to be a CLI issue: https://github.com/hasura/graphql-engine/issues/6115 

We will fix this ASAP in v1.3.3

**Comment by markerdmann** [comment]
@tirumaraiselvan Thanks for your help with this bug! We'll keep an eye out for the next release.

**Comment by tirumaraiselvan** [comment]
This is fixed in v1.3.3. Please reopen if you face any further issues.
