### ISSUE TITLE
cli: can't add migration - running into admin error

### ISSUE THREAD

**Issue by adityas129** [hasura/graphql-engine#6104]
I'm stumped by what I'm doing wrong. 

I'm trying to do 
```hasura migrate create "init" --from-server```

and get the error 
```FATA[0000] cannot create migrate instance: cannot create migrate instance: [access-denied] restricted access : admin only ($.args)```

This is on EC2 instance with hasura install through curl with the right ip address. I tried sudo but same error - any thoughts?

**Comment by scriptonist** [comment]
@adityas129 Is HGE setup with an `admin-secret` ?

**Comment by adityas129** [comment]
it wasn't properly configured - thank you for your help!
