### ISSUE TITLE
cli-migrations: can't pass in metadata config from docker

### ISSUE THREAD

**Issue by TimMurnaghan** [hasura/graphql-engine#6105]
(v2 metadata/migrations)
The docker-entrypoint.sh builds a temporary directory setup with a metadata directory pointed to by a metadata_directory entry in the config.yaml file

but the command always fails with:
hasura-cli metadata apply
FATA[0000] failed to apply metadata: cannot apply metadata on the database: [parse-failed] key "tables" not found ($[1]) 

You can make it work  manually by truncating the config.yaml file and putting the metadata in the migrations directory where it wants to default to.
The whole cli config file arrangement is very fragile.

Also the error message is very unhelpful. It would be much better it gave the name of the file that it's incorrectly attempting rather than $[1]

Maybe there's a magic file name that it's looking for - but it's stumped me.

**Comment by scriptonist** [comment]
@TimMurnaghan did you use`hasura/graphql-engine:<version>.cli-migrations-v2` or `hasura/graphql-engine:<version>.cli-migrations-v1`

Also, can you share the `Dockerfile` or `docker-compose` file you were using

**Comment by TimMurnaghan** [comment]
It's V2 (as mentioned). I've tried dozens of config variations,  here's one:

#! /bin/bash
docker run -it \
       --entrypoint /bin/sh \
       -p 8080:8080 \
       -e HASURA_GRAPHQL_DATABASE_URL=postgres://$LOGNAME:@docker.for.mac.host.internal:5432/integrum \
       -e HASURA_GRAPHQL_AUTH_HOOK=http://docker.for.mac.host.internal:4000/api/hasura-webhook \
       -e HASURA_GRAPHQL_ENABLE_CONSOLE=true \
       -e HASURA_GRAPHQL_DEV_MODE=true \
       -e HASURA_GRAPHQL_ADMIN_SECRET=1234 \
       --mount type=bind,source=`pwd`/hasura/metadata/,target=/hasura-metadata/ \
       hasura/graphql-engine:v1.3.2.cli-migrations-v2

As more information V1 does work if you put the metadata file in the migrations directory
As I'm coming to the conclusion that V2 just doesn't work - could you give a working example as a conterexample?

**Comment by scriptonist** [comment]
The given bash script seems to work for me.

```
╭─atom@drogon /tmp/hasura
╰─$ tree .
.
├── config.yaml
├── metadata
│   ├── actions.graphql
│   ├── actions.yaml
│   ├── allow_list.yaml
│   ├── cron_triggers.yaml
│   ├── functions.yaml
│   ├── query_collections.yaml
│   ├── remote_schemas.yaml
│   ├── tables.yaml
│   └── version.yaml
├── migrations
├── run.sh
└── seeds

3 directories, 11 files
╭─atom@drogon /tmp/hasura
╰─$ cat run.sh
#! /bin/bash
docker run -it \
-p 8081:8080 \
-e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgrespassword@172.17.0.1:15432/postgres \
-e HASURA_GRAPHQL_ENABLE_CONSOLE=true \
-e HASURA_GRAPHQL_DEV_MODE=true \
--mount type=bind,source=/tmp/hasura/metadata/,target=/hasura-metadata/ \
hasura/graphql-engine:v1.3.2.cli-migrations-v2
```
```
╭─atom@drogon /tmp/hasura
╰─$ ./run.sh
:<trimmed>
Applying metadata...◑ {"type":"schema-sync-thread","timestamp":"2020-10-31T18:20:59.018+0000","level":"info","detail":{"thread_type":"listener","info":{"received_event":{"instance_id":"59bfcab8-521c-4c47-9aa2-2189e55b75a2","invalidations":{"remote_schemas":[],"metadata":false},"occurred_at":"2020-10-31T18:20:59.014091Z"}}}}
INFO Metadata applied
{"timestamp":"2020-10-31T18:20:59.000+0000","level":"info","type":"startup","detail":
<trimmed>
```
https://asciinema.org/a/3x3bXBB7EPSWlxnAF4YLAgPA1
[hasura-project.zip](https://github.com/hasura/graphql-engine/files/5469594/hasura-project.zip)

**Comment by TimMurnaghan** [comment]
Ahh - maybe it's magic (undocumented) names for the files. I was trying to use metadata.yaml

**Comment by scriptonist** [comment]
Got it, understood. I agree that this has caused some confusion. we should probably improve the docs and the error messages to fix that. 

For the time being please refer
- https://hasura.io/docs/1.0/graphql/core/migrations/manage-metadata.html
- https://hasura.io/docs/1.0/graphql/core/migrations/reference/metadata-format.html

The use case we had in mind when designing this was as follows.
- Setting up a project directory as mentioned here https://hasura.io/docs/1.0/graphql/core/migrations/migrations-setup.html
- tracking Metadata and migrations changes in VCS
- During deployment the CI/CD pipeline will mount metadata and migrations directory on to the `cli-migrations` container.

**Comment by TimMurnaghan** [comment]
For my use case (generating the metadata in the console rather than writing it by hand) I'm probably better sticking with the V1 API, which is where I ended up.

Thanks for all your help.

**Comment by scriptonist** [comment]
I think you got misunderstood a bit, you don't have to write metadata by hand if you don't want to. you can you use `hasura metadata export` command to export metadata which will populate all the required files.

**Comment by ihsaram** [comment]
In case someone else ends up here because of the mistake I made, make sure to export metadata using `hasura-cli` and not the web console, Plus make sure the `config.yaml` file you're using mentions `version: 2` and `metadata_directory`, here's what worked for me:

```yaml
version: 2
endpoint: http://[host]:[port]
metadata_directory: metadata
```

**Comment by tirumaraiselvan** [comment]
Seems like the issue is resolved. Please reopen in case there are any further issues.
