### ISSUE TITLE
Can role permissions of hasura be inherited?

### ISSUE THREAD

**Issue by s97712** [hasura/graphql-engine#611]
Like a database role, role can inherit another role's permissions, hasura role can do that?

**Comment by shahidhk** [comment]
@s97712 Not at the moment, but we are working on something very close to this: https://github.com/hasura/graphql-engine/issues/280

Are you looking for a case where a role can inherit another role's permissions and on top of that over-riding/extra rules can be added?

**Comment by s97712** [comment]
Thank you very much, can use it now in a production environment?

**Comment by coco98** [comment]
Yes, you can! Hasura is fairly stable. If you need any help or run into any
issues please hit us up on discord:
https://discord.gg/vBPpJkS

**Comment by dsandip** [comment]
Comment from Intercom back in the day in #351:

> It'll be much more awesome if permissions could be grouped or inherited somehow. Right now I have to add the same rules for every table `X-hasura-org-id _eq org_id`

> I would say an another tab "Permissions".
There I add a permission "Tenant-only" f.e. with `X-hasura-org-id _eq org_id`
After that when I create/edit a table I see a list of available permissions and select "Tenant-only" with a checkbox

**Comment by carlosbaraza** [comment]
> Comment from Intercom back in the day in #351:
> 
> > It'll be much more awesome if permissions could be grouped or inherited somehow. Right now I have to add the same rules for every table `X-hasura-org-id _eq org_id`
> 
> > I would say an another tab "Permissions".
> > There I add a permission "Tenant-only" f.e. with `X-hasura-org-id _eq org_id`
> > After that when I create/edit a table I see a list of available permissions and select "Tenant-only" with a checkbox

I find this to be quite frustrating. We have to duplicate the permissions for every new role, and if something changes in the permissions business logic, that would require changing all the roles that are affected, which is very error prone.

**Comment by tirumaraiselvan** [comment]
A small update: this is something we are working on at the moment.
