### ISSUE TITLE
"created_at" Field Is Incorrect For Scheduled One-Off Trigger Event

### ISSUE THREAD

**Issue by rahulmadduluri** [hasura/graphql-engine#6117]
The UI for a scheduled one-off trigger event shows an incorrect "created_at." The scheduled time is correct, but the created_at time is in the future. Maybe it's not applying the -8 hour offset?

![Screen Shot 2020-11-02 at 4 02 46 PM](https://user-images.githubusercontent.com/5498644/97932437-dc7ade00-1d24-11eb-9350-c6f521556170.png)
![Screen Shot 2020-11-02 at 4 03 16 PM](https://user-images.githubusercontent.com/5498644/97932465-ed2b5400-1d24-11eb-9bf8-be099f796fe8.png)

**Comment by tirumaraiselvan** [comment]
This was fixed in https://github.com/hasura/graphql-engine/pull/5736 but we haven't release it yet. We will try to do so in v1.3.3

**Comment by tirumaraiselvan** [comment]
Meanwhile, you can run this SQL to fix this:

```

ALTER TABLE hdb_catalog.hdb_cron_events
ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE hdb_catalog.hdb_cron_event_invocation_logs
ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE hdb_catalog.hdb_scheduled_events
ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE hdb_catalog.hdb_scheduled_event_invocation_logs
ALTER COLUMN created_at TYPE TIMESTAMPTZ;
```

**Comment by rahulmadduluri** [comment]
thanks @tirumaraiselvan !
