### ISSUE TITLE
cli - migration error when I migrate staging to production 

### ISSUE THREAD

**Issue by MinJunKimKR** [hasura/graphql-engine#6118]
Hi there! I'm having some problems when I try migration staging into production.

I already delete all of directory in migrations directory before type these commands
I typed` hasura migrate create staging --from-server --admin-secret <password> --endpoint <staging-address> `and `hasura migrate apply staging --admin-secret <password> --endpoint <production-address>`

But I got a this 
`FATA[0002] apply failed: [postgres-error] query execution failed ($.args[0].args)
File: '1604310088861_test_migration/up.sql'
{
    "check_metadata_consistency": false,
    "sql": "CREATE FUNCTION public.set_current_timestamp_updated_at() RETURNS trigger\n `
.
.
.
`error FatalError: function "set_current_timestamp_updated_at" already exists with same argument types`

Anyone help my problems

**Comment by MinJunKimKR** [comment]
I did this
1. I made production DB
2. create migration and metadata of production DB
3. applied migration and metadata to fresh new DB for using stagingDB
4. something do in stagingDB.
5. create migration and metadata stagingDB
6. try to apply migration and metadata to productionDB <- here is the error point

**Comment by scriptonist** [comment]
@MinJunKimKR I see this error `function "set_current_timestamp_updated_at" already exists with same argument types`, which means that a function that you are trying to create is already present in the database. So when `migrate apply` is trying to create the same function it encounters this error.

**Comment by rikinsk** [comment]
Closing this for now. Please feel free to reopen this if this wasnt resolved
