### ISSUE TITLE
Its impossible to use Hasura in JWT auth mode with Oracle IDCS auth provider tokens

### ISSUE THREAD

**Issue by miqu** [hasura/graphql-engine#6136]
Oracle IDCS cannot handle special characters in claim names with custom claims. It also has a problem with the default namespace.

Hasura could alleviate the problem by allowing configuration of claim names looked for in Tokens.

The "use the webhook" as a workaround is as stated in many other issues has its problems with the round trip time etc.

**Comment by coco98** [comment]
@miqu Will this solve the problem? 
https://github.com/hasura/graphql-engine/pull/3575

**Comment by miqu** [comment]
Yeah I suppose it will. Great thanks for the fast reply. Going to setup the Hasura new version for testing tomorrow as if I saw correctly in my night eyes that it has been merged to 1.3.3.

**Comment by tirumaraiselvan** [comment]
Released in v1.3.3
