### ISSUE TITLE
Failed while attempting to install hasura graphql-engine cli. Please manually install

### ISSUE THREAD

**Issue by hugomn** [hasura/graphql-engine#6141]
Hello,

I'm deploying hasura metadata and migrations using Circleci. Before applying the data, I need to install the cli, and it's failing randomly with the following message:

```
#!/bin/bash -eo pipefail
sudo curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   139    0   139    0     0   1494      0 --:--:-- --:--:-- --:--:--  1494
100  3577  100  3577    0     0  17364      0 --:--:-- --:--:-- --:--:-- 17364
--> Getting latest version...
--> 
--> Failed while attempting to install hasura graphql-engine cli. Please manually install:
--> 
--> 2. Open your web browser and go to https://github.com/hasura/graphql-engine/releases
--> 2. Download the cli from latest release for your platform. Name it 'hasura'.
--> 3. chmod +x ./hasura
--> 4. mv ./hasura /usr/local/bin
```

Any ideas on how to solve that? I didn't find another reliable way of having hasura-cli installed in my CI. This is making the deployment flows unstable. Thanks!

**Comment by scriptonist** [comment]
Thanks @hugomn for bringing this to notice. This happens because our update servers are being rate limited by Github. We'll fix this ASAP. 

While we get that fixed, what I can suggest is directly using artifacts from Github releases in your installation scripts. Which will look something like the following.
```
#!/bin/bash 
set -eo pipefail
curl -LO https://github.com/hasura/graphql-engine/releases/download/v1.3.2/cli-hasura-linux-amd64
chmod +x cli-hasura-linux-amd64
sudo mv ./cli-hasura-linux-amd64 /usr/local/bin/hasura
```

**Comment by hugomn** [comment]
@scriptonist that worked perfectly, thanks. Should we maybe add this option to the docs?
