### ISSUE TITLE
always allow horizontal scroll on Browse Rows page

### ISSUE THREAD

**Issue by erikhSSI** [hasura/graphql-engine#6158]
When browsing wide data tables in the dashboard (which I do a lot) it is very inconvenient because the browser's horizontal scrollbar is hidden unless you scroll to the very bottom of the page.  
If I am at a page like /console/data/schema/public/tables/[tablename]/browse

I won't be able to scroll the table right (to see other columns) unless I first scroll vertically to the bottom of the page.

![image](https://user-images.githubusercontent.com/39960163/98564631-94a30c00-227a-11eb-8f8b-13532607e4da.png)

A small CSS change seems to fix that:

![image](https://user-images.githubusercontent.com/39960163/98564654-9d93dd80-227a-11eb-9d5f-eb48ad99b8af.png)

And now the horizontal scroll bar always appears

![image](https://user-images.githubusercontent.com/39960163/98564733-b603f800-227a-11eb-8311-dd7da79805c3.png)

**Comment by TheTalesman** [comment]
I'm working on this

**Comment by aniketh-varma** [comment]
Hi, @Stefmore02, I would like to work on this issue if it is still available.

**Comment by Stefmore02** [comment]
Hey @aniketh-varma thank you for your interest! Feel free to open a PR. The first PR that is submitted will be reviewed first.

**Comment by BrunoGabrielGodoi** [comment]
Hello, @Stefmore02. I think this issue has been solved already.
![image](https://user-images.githubusercontent.com/20050537/203442521-03d6c2a2-7802-4ed5-b43a-c01ec28333aa.png)
This print is from version 2.12

**Comment by Stefmore02** [comment]
This issue is solved.
