### ISSUE TITLE
jsonb mutation variable fails with "no such type exists in the schema: 'jsonb'"

### ISSUE THREAD

**Issue by trymbill** [hasura/graphql-engine#6159]
Connected to Hasura through a WebSocket, I'm trying to use a `jsonb` column, inserting an array. But even without any data being sent for that variable (which should then result in it becoming `NULL` since it's nullable), I still get an error stating `no such type exists in the schema: 'jsonb'`. I've seen `jsonb` being used in the Hasura docs (as an example: https://hasura.io/docs/1.0/graphql/core/mutations/insert.html#insert-an-object-with-a-jsonb-field) so I'm not sure what I'm doing wrong.

Here's the mutation (note that I'm not sending the `$files` variable through for testing purposes):
```graphql
mutation submitPost($body: String!, $files: jsonb) {
  insert_newsfeed_one(object: { body: $body }) {
    id
  }
}
```

Here's the full WS message being sent:
```json
{
  "id": "5",
  "type": "start",
  "payload": {
    "variables": { "body": "Testing", "files": [] },
    "extensions": {},
    "operationName": "submitPost",
    "query":"mutation submitPost($body: String!, $files: jsonb) {
      insert_newsfeed_one(object: {body: $body}) {
        id
        __typename
      }
    }
    "
  }
}
```

And the error response:
```json
{
  "type": "error",
  "id": "5",
  "payload": {
    "errors": [
      {
        "extensions": {
          "path": "$.variableValues",
          "code": "validation-failed"
        },
        "message": "no such type exists in the schema: 'jsonb'"
      }
    ]
  }
}

```

**Comment by trymbill** [comment]
Submitting that same mutation in GraphIQL works fine, although it doesn't seem to know what `jsonb` is supposed to look like (which I think is related to https://github.com/hasura/graphql-engine/issues/4787):

<img width="1243" alt="Screen Shot 2020-11-09 at 10 37 39 AM" src="https://user-images.githubusercontent.com/658727/98582285-9e774000-2277-11eb-9616-07cca08614b4.png">

Still doesn't work in my code.

**Comment by trymbill** [comment]
Just tried it with XHR instead of WebSocket, same error.

**Comment by tirumaraiselvan** [comment]
Hi @trymbill 

Are you using any `role` (x-hasura-role)? If you are using a role, then does the table with a `jsonb` column have permission on that column to insert or select? I guess it does not by looking at the error message: `no such type exists in the schema: 'jsonb'` 

This is just a GraphQL spec thing where if a type is not used in any field, it is simply omitted from schema. You do not see this with GraphiQL as it is running as `admin` role.

**Comment by trymbill** [comment]
Ahh! Good catch! Yeah, it's definitely a new column so the permissions weren't updated yet. Thank you for your help!

Just as a sidenote; might be worth updating that error message. Checking the permissions will from now on be something I check, but for new users, it's definitely not 100% obvious. Thanks again for a killer product!

**Comment by JavaJamie** [comment]
I'm getting a similar error when fetching data but it ONLY happens after a page refresh?? It works the first time, hit F5, then no such type exists in the schema: 'uuid'. I have no clue why this would happen after a reload.

All permissions are configured. I'm uskmg Nhost (Hasura, Postgres)

**Comment by nisharmultani** [comment]
i have facing same problem its work proper but i add new coloum and the  i get this kind of error .
GraphQL error: no such type exists in the schema: 'registration_group_tickets_insert_input'
  mutation: gql`
            mutation InsertRegistrationGroupTicketsOne(
              $data: registration_group_tickets_insert_input!
            ) {
              insert_registration_group_tickets_one(
                object: $data
                on_conflict: {
                  constraint: registration_group_tickets_pkey
                  update_columns: path
                }
              ) {
                id
              }
            }
          `,
          variables: {
            data: {
              group_id: this.groupId,
              path: uploadPath.key,
            },
          },
this is a code  i check all permision is as well as i dont change it its work properly but after some chnages in table its give this kind of ... any solution ?
