### ISSUE TITLE
reload metadata button should be shown if version check fails

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#618]
Reload metadata button (in Settings) should be shown if the version check fails. Right now, for pull-request builds, the button is not shown.

Version is checked to see if the server supports the function or not. I guess the feature is available from `v1.0.0-alpha18`. But, if this semver check fails, assume it's a pull request build and show the button.

**Comment by pmc-a** [comment]
Hi @shahidhk, I'd like to have a look at this one!

Can you provide some more info on how to reproduce the version check failure?

**Comment by shahidhk** [comment]
Thanks for pitching in @pmc-a.

@praveenweb Can you help out @pmc-a?

**Comment by shahidhk** [comment]
@pmc-a Sorry about the delay. I have set-up a test server for you at https://hasura-issue-618-test.herokuapp.com which has a non-semver version.

You can clone the repo, follow the readme for instructions to run console in `server` mode.

In the `.env` file, set the following:

```env
PORT=3000
NODE_ENV=development
DATA_API_URL=https://hasura-issue-618-test.herokuapp.com
CONSOLE_MODE=server
URL_PREFIX=/
```

Start the console dev server:

```bash
npm run dev
```

Goto http://0.0.0.0:3000 check the JavaScript console. You can see that there is an error saying `TypeError: "Invalid Version: pull635-6bf21b2"`

What we need to do is to handle this error and show the Reload metadata button in the settings page.

**Comment by pmc-a** [comment]
Hi @shahidhk - thanks very much! Will have a look at this issue over the next day or so.

I'll let you know if I have any other issues or queries.
