### ISSUE TITLE
Nav bar tooltips are not aligned

### ISSUE THREAD

**Issue by beerose** [hasura/graphql-engine#6180]
**Current:**

<img width="293" alt="Screenshot 2020-11-12 at 14 42 10" src="https://user-images.githubusercontent.com/9019397/98947252-40579080-24f5-11eb-9235-8d756124c867.png">
<img width="273" alt="Screenshot 2020-11-12 at 14 42 19" src="https://user-images.githubusercontent.com/9019397/98947270-45b4db00-24f5-11eb-9e04-3a440171136d.png">

**Expected:**

Tooltips should be vertically aligned with text.

**Comment by kawamataryo** [comment]
I fix it.

https://github.com/hasura/graphql-engine/pull/6409
