### ISSUE TITLE
When editing default column value cursor jumps to end of line

### ISSUE THREAD

**Issue by beerose** [hasura/graphql-engine#6182]
![default](https://user-images.githubusercontent.com/9019397/98956780-bd3c3780-2500-11eb-8656-4ad4914aacf9.gif)

**Comment by harishm72** [comment]
Hi, @beerose can I take this issue?

**Comment by beerose** [comment]
Sure @harishm72!

**Comment by anantramverma777** [comment]
hi i am anant
may i fix this issue

**Comment by prajzwol7** [comment]
@beerose this issue seems to be fixed .

**Comment by Varun-Choudhary** [comment]
Thanks, @prajzwol7! I just check the issue, you are right this issue is fixed now.
