### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by rahulkumaran** [hasura/graphql-engine#619]
Currently requirements.txt has a few python libraries that are not up to date. We have more recent and stable versions for the same. I think it's better to update them.

@shahidhk I'd like to work on this and will be sending a PR for the same in a few minutes.

**Comment by rahulkumaran** [comment]
@shahidhk this issue would also come under hacktoberfest right?

**Comment by shahidhk** [comment]
Thanks for your efforts @rahulkumaran :pray: :sparkles:

Sadly, as @rikinsk mentioned in https://github.com/hasura/graphql-engine/pull/620#issuecomment-427001652, we cannot update the requirements.txt file.

Feel free to pick up any issue from https://github.com/hasura/graphql-engine/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Ahacktoberfest and give it a go.
