### ISSUE TITLE
'This is a migration' option unavailable in Data -> SQL section

### ISSUE THREAD

**Issue by manuFL** [hasura/graphql-engine#6195]
Hi,

as per screenshot below there should be a 'This is a migration' option available in Data -> SQL section

<img width="1080" alt="hasura-sql-citext" src="https://user-images.githubusercontent.com/64466925/99089260-59337500-25cd-11eb-8ace-c1f646ab7377.png">

but there is none in my installation:

![missing option](https://user-images.githubusercontent.com/64466925/99089490-aca5c300-25cd-11eb-81fd-3705d83487bc.jpg)

There is something to be done to enable it?

Here there is my current setup:

Current server version: v1.3.2
Latest stable server version: v1.3.2
Console asset version: 1605156101803
Postgres version: PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

Thank you advance!

**Comment by denisyilmaz** [comment]
Are you using `hasura console` command to access the console? As afar as I understood it only via this command the migrations are tracked automatically in migration files for you. See instructions here https://hasura.io/docs/1.0/graphql/core/migrations/migrations-setup.html#migrations-setup

**Comment by manuFL** [comment]
Hi, the checkbox is missing both using `hasura console` and the integrated hasura instance web console

**Comment by manuFL** [comment]
Ok never mind it seems to work now via hasura console, thank you

**Comment by gabrieljoelc** [comment]
I've had this happen so many times. I finally figured out that if I ctrl+c `hasura console` and start it again, the checkbox appears. 🤷
