### ISSUE TITLE
Updating Enum row doesn't generate new migrations

### ISSUE THREAD

**Issue by jvukoja** [hasura/graphql-engine#6200]
Hi,

We noticed that in Hasura console, when we update a row in the table which is marked as Enum, we are not getting migrations automatically generated by Hasura.

We don't know if this is a bug, but if it is not, it would be a nice feature to have. Would like to hear what do you from Hasura think about it?

**Comment by beerose** [comment]
Hi @jvukoja,

We recently merged https://github.com/hasura/graphql-engine/pull/4993 that provides this feature. It will be out in the next release — 1.4. 

I'm therefore closing this issue. 🙂
