### ISSUE TITLE
"subscriptions-transport-ws library is not being actively maintained"

### ISSUE THREAD

**Issue by LydiaF** [hasura/graphql-engine#6204]
Dear Hasura team,

There is a notice on the [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) that the library will no longer be maintained.

(Without doing enough reading of the hasura docs :) ) we just tried to move to [graphql-ws](https://github.com/enisdenjo/graphql-ws) but it failed, which was probably to be expected!

Will Hasura move to the new graphql-ws library?

Thanks for any info!

Lydia

**Comment by tirumaraiselvan** [comment]
Closing this in favour of https://github.com/hasura/graphql-engine/issues/6264

Pls do drop a thumbs up there!
