### ISSUE TITLE
Track All tables/views for existing database throws error

### ISSUE THREAD

**Issue by oxcid** [hasura/graphql-engine#6205]
Hi,

Total noob here. I'm currently testing Hasura to connect to an existing database from Odoo 13 Community Edition. But when I tried to "Track All" tables/views, after waiting for quite a long time, I got this error (attached screenshot).

<img width="960" alt="Screenshot 2020-11-17 12 54 06" src="https://user-images.githubusercontent.com/45662692/99352470-4b376a00-28d5-11eb-9e14-e629e35ea58d.png">

I checked at the docker logs, and nothing peculiar, all is getting status 200.

I've tried also to create new tables from Hasura console, just to test the connection, and it worked. So not sure what went wrong here.

I followed the tutorial here ( https://hasura.io/docs/1.0/graphql/core/deployment/deployment-guides/docker.html ) for localhost setup. Running on Ubuntu 20.04

Please let me know if you need other info.

Thanks in advance!

**Comment by v3ss0n** [comment]
I am also going to test hasura with odoo , and i will let you know.
Its better to test one by one and do tutorials first.
Have you tried Hasura alone ?

**Comment by oxcid** [comment]
@v3ss0n thanks. Turned out, it's actually working, it just took d*mn long to finish, probably 1 whole day using DigitalOcean $10 droplet. I noticed today, the "untracked tables or views" list is empty. And then I continue to "track all" foreign-key relationships, and I got the same exact response. When I checked at htop, the CPU is running at 100% constantly.

I'm ok with the processing time, considering Odoo by default has tons of tables, but I'm hoping for a "clearer" response when the task is still processing, instead of error message like currently I got.

I've tried setting up Hasura using a new DB, and it's working fine. This is the next step, as my main goal is to use Hasura to read Odoo's DB. Let me know how it goes on your end.

**Comment by v3ss0n** [comment]
For me  what i do is work on my laptop/desktop firs then deploy on DO. DO 10$ can only handle like 2 odoo users at the same time , very bad performance if using concurrently - need specific tuning and setup to work well on 10$ servers.
Back to topic , its best to 
- deploy your own locally and test first
- docker-compose your setup locally
- depoly on server

**Comment by oxcid** [comment]
Going back to the initial problem, after tracking all tables/views, next step was to track all "foreign-key relationships". I encountered the same issue, after a while, the process seems to stop running. This time, it's not running in the background anymore, it's actually stuck.

I've bumped up the server to using 4vCPUs and 8GB, still the same.

The process is only stuck when I tried to "Track All", while if I click 1 by 1 the relationship, it's tracked properly, and the relationship is removed from the "Untracked foreign-key relationships" list.

If I see at htop, the CPUs are being used. But what for, I don't know. All I know is if I leave "Track All" supposedly running overnight, next morning the "Untracked foreign-key relationships" list is still exactly the same.

Any help here please? I've probably missed something very basic..

**Comment by tirumaraiselvan** [comment]
@oxcid This is a known issue for track all: https://github.com/hasura/graphql-engine/issues/5014

For databases with large number of tables, this operation can be quite slow. The workaround is to use the `replace_metadata` [API](https://hasura.io/docs/1.0/graphql/core/api-reference/schema-metadata-api/manage-metadata.html#replace-metadata) or the [metadata SDK](https://github.com/hasura/graphql-engine/tree/master/contrib/metadata-types) to make this API call.

I am closing this issue as dupe but we can continue discussing the workaround here.
