### ISSUE TITLE
Nested insert mutations fails to associate user_id with user.id

### ISSUE THREAD

**Issue by qpre** [hasura/graphql-engine#6206]
Hi,

# With the following schema:

**user:**
- id: _uuid, primary key, unique, default: gen_random_uuid()_

**assoc_user_adress:**
- address_id: _integer, primary key_
- user_id: _uuid, primary key_

note: I also tested, with the same results, using a separate **id** field as primary key on the assoc table.

# Having the following mutation:

```
mutation MyMutation {
   insert_users(objects: {
      assoc_user_adresses: {
         data: [
            {address_id: 1}
         ]
      }
   }) {
    affected_rows
  }
}
```

# Experience

- When I try running this mutation from the console I get a NOT-NULL constraint violation on _assoc_user_adress_'s user_id field.
- When I try running this mutation from my app I get the following error: `invalid input syntax for type integer: \"<redacted>""`, where `<redacted>` is my user_id (taken, I guess from the `X-hasura-user-id` header).

I don't get why the `user_id` on the assoc table is not collected from the `insert_user` mutation, and I _really_ don't get why I get a type error in the second case as `address_id` is expected as an integer and user_id is expected as a uuid.

Could it be that  ColumnPresetsExp takes precedence on query-provided and resolved values ?

Thanks in advance for any help !

**Comment by qpre** [comment]
Edit: destroying `assoc_user_adresses ` then recreating it fixed the issue for me, I can't figure what was wrong but I guess it had something to do with my setup.

Leaving it open in case someone has an enlightment about it.

**Comment by tirumaraiselvan** [comment]
@qpre I am going to close this. One thing you should be aware of is the caveat in doing nested mutations on one-to-one relationships (which is what I think your model is): https://hasura.io/docs/1.0/graphql/core/guides/data-modelling/one-to-one.html#current-limitations-with-nested-mutations 

In case you face this issue again, pls reopen.
