### ISSUE TITLE
UI for adding custom timeouts to actions

### ISSUE THREAD

**Issue by beerose** [hasura/graphql-engine#6207]
Related server PR: https://github.com/hasura/graphql-engine/pull/5762

console : https://github.com/hasura/graphql-engine-mono/pull/97

**Comment by jsalva** [comment]
This would be really helpful to have -- it's really easy to accidentally blow away manual migrations that set this to non-default values by changing anything else about an async action in the UI without knowing/realizing it (apparently this sets the value back to 30s).

**Comment by CristianAlba75** [comment]
Hi, is there any update about the interface to add the custom times for the actions?

**Comment by Varun-Choudhary** [comment]
@CristianAlba75 
We were working on this. Custom timeout field will be added soon on the actions page.

**Comment by soorajshankar** [comment]
Hey @jsalva @CristianAlba75 👋🏼 ,

We have released this feature with [v2.0.7](https://github.com/hasura/graphql-engine/releases/tag/v2.0.7).
