### ISSUE TITLE
docs: note on export metadata in json format

### ISSUE THREAD

**Issue by beepsoft** [hasura/graphql-engine#6209]
While the Schema / Metadata API is documented, the result of the [export_metadta](https://hasura.io/docs/1.0/graphql/core/api-reference/schema-metadata-api/manage-metadata.html#export-metadata) operation doesn't seem to be described.

Is this a data format that we can rely on to be stable for at least the major versions of Hasura? 

I ask this because I was thinking about adding generation of this kind of metadata JSON to https://github.com/dsd-sztaki-hu/hasuraconf instead os/next to the current solution, which generates a `bulk` metadata API JSON with many `track_table`, `create_object_relationship` etc. operations inside.

Would this be feasible?

**Comment by beepsoft** [comment]
A reason why I'm thinking of using export_metadata format JSON instead of the metadata API is that the API is still not idempotent as already raised in this issue: https://github.com/hasura/graphql-engine/issues/3959

This makes the current API quite convenient. For example, when I say `untrack_table` for a table that is already untracked the API fails with an error, but it would be more convenient if it just did nothing. Or at least if error reporting was optional.

**Comment by rikinsk** [comment]
We have a reference for the metadata yaml files generated via the CLI at https://hasura.io/docs/1.0/graphql/core/migrations/reference/metadata-format.html. The output of the `export_metadata` api should just be a "json" version of the same. We shall add a note regarding this in the docs as well

**Comment by rikinsk** [comment]
Regarding the stability of the format, we would recommend using the CLI to manage the metadata instead of the API as the metadata format is versioned and will guarantee backwards compatibility. If we do need to change the format in the future it will come with a version bump of the metadata format and there will be tooling to convert the current format into the new format to keep transitions smooth.

**Comment by beepsoft** [comment]
@rikinsk Thanks for the clarifications!
