### ISSUE TITLE
Cli installation script fails too often

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#6210]
we use the [CLI installation script](https://raw.githubusercontent.com/hasura/graphql-engine/stable/cli/get.sh) in our CI/CD environment to install the cli. This scripts relies on https://releases.hasura.io/graphql-engine?agent=cli-get.sh which occasionally seems to fail by returning `{"error":"contacting github api failed"}` hence failing all our pipelines because we can't install the cli.

![image](https://user-images.githubusercontent.com/5978905/99407186-a175ce80-2910-11eb-9871-29db130f874f.png)

**Comment by scriptonist** [comment]
@abdullah2993 can you use this workaround https://github.com/hasura/graphql-engine/issues/6141#issuecomment-722904745, while we get this fixed.

closing, since we are tracking this in #6141
