### ISSUE TITLE
Hasura cli command not found when running npm script

### ISSUE THREAD

**Issue by Luifr** [hasura/graphql-engine#6218]
I'm on windows 10
cli version=v1.3.2

I can run `hasura`

![image](https://user-images.githubusercontent.com/29644302/99542625-0d981700-2991-11eb-9063-1b6522e920e7.png)

It works in a `.sh` script

![image](https://user-images.githubusercontent.com/29644302/99543157-9f078900-2991-11eb-95b0-7067ef84210c.png)

But it does not work when running from a npm command

Running it directly:

![image](https://user-images.githubusercontent.com/29644302/99542958-623b9200-2991-11eb-9c2b-65c56503c85c.png)

Running it though a `.sh` script

![image](https://user-images.githubusercontent.com/29644302/99543095-87c89b80-2991-11eb-9d76-b0005f505306.png)

**Comment by tirumaraiselvan** [comment]
Looking at the error seems like the path that npm is looking for is screwed up:

If you look at the path: `C:\Users\Lui\Desktop\ ...... \node_modules\.bin/../hasura-cli/hasura` , seems like you have the slashes reversed on windows.
