### ISSUE TITLE
cli: v1.3.3 `cannot fetch plugin manfiest cli-ext error` happens intermittently

### ISSUE THREAD

**Issue by scriptonist** [hasura/graphql-engine#6219]
The following error has been happening intermittently for a bunch of users.

```
FATA[0003] failed to apply metadata: cannot apply metadata on the database: cannot build actions from metadata: cannot fetch plugin manfiest cli-ext
```
The current workaround is to `rm -rf ~/.hasura` and retry.

**Comment by thomie** [comment]
Happened to me, for the first time, after upgrading to CLI version 1.3.3:

```
% hasura metadata export
INFO A new version (v1.3.3) is available for CLI, update? (y/N) 
y
INFO Updated to latest version                     version=v1.3.3
FATA[0035] failed to export metadata: cannot export metadata from server: cannot export actions from metadata: error in converting metadata to sdl: signal: killed:  
% hasura metadata export
FATA[0001] failed to export metadata: cannot export metadata from server: cannot export actions from metadata: cannot fetch plugin manfiest cli-ext: plugin version is not available 
% rm -rf ~/.hasura 
% hasura metadata export
INFO Help us improve Hasura! The cli collects anonymized usage stats which
allow us to keep improving Hasura at warp speed. To opt-out or read more,
visit https://hasura.io/docs/1.0/graphql/manual/guides/telemetry.html 
INFO hasura cli is up to date                      version=1.3.3
INFO plugin installed                              name=cli-ext
INFO Metadata exported                            
```

**Comment by xiaoyu-tamu** [comment]
> rm -rf ~/.hasura

thanks

**Comment by coloradocolby** [comment]
this one bit me last night. I realized this morning none of the metadata updates I made yesterday were applied, and I'm guessing this is why, since this is the first thing I saw this morning :/

**Comment by jflambert** [comment]
@scriptonist I'm still having this issue. I use hasura 1.3.3 and 1.3.4-beta.2

I want to use the hasura-cli on gitlab with brand new kubernetes runners. These are "clean slate" environments and there is no concept such as `rm -rf ~/.hasura`

1.3.2 works just fine so we can't upgrade until this is resolved.

**Comment by jflambert** [comment]
Heard that. I'll put it on my TODO list.
________________________________

Jean-François Lambert
Lead Data Engineer
T  +1 (514) 922-3214

**Comment by followbl** [comment]
@scriptonist this is a nasty bug - I've spent the better part of the morning trying to figure out what the issue is and unfortunately have very little...

getting

```
FATA[0001] failed to apply metadata: cannot apply metadata on the database: cannot build actions from metadata: error in converting sdl to metadata: exit status 4:
```

I have confirmed that it is not a data issue - as a colleague was able to easily run export and apply metadata. Any ideas?

**Comment by followbl** [comment]
@scriptonist this is happening for both the v2 and the v3 versions.

**Comment by scriptonist** [comment]
@followbl do you have `NODE_OPTIONS` env setup ? like https://github.com/hasura/graphql-engine/issues/4953

**Comment by followbl** [comment]
@scriptonist that was it, thanks for the response and support.

rough error message. not sure if there's a way to make that better.
