### ISSUE TITLE
Console UI for SQL volatile functions

### ISSUE THREAD

**Issue by beerose** [hasura/graphql-engine#6228]
* https://github.com/0x777/graphql-engine/blob/pg-function-improvements/rfcs/pg-function-improvements.md
* https://github.com/hasura/graphql-engine-internal/issues/502

Server PR: https://github.com/hasura/graphql-engine/pull/6160

Console PR: https://github.com/hasura/graphql-engine/pull/6096

**Comment by tirumaraiselvan** [comment]
When tracking a function which is VOLATILE, a pop up should say "This will be added in mutation as the function is VOLATILE." Then there are 2 buttons: 1) "Continue" or 2) "Add as query". If "add as query" is chosen then a warning is shown saying "queries are supposed to be read only and hence recommended to be STABLE or IMMUTABLE. Are you sure?"

**Comment by beerose** [comment]
if "add as query" is chosen then the console needs to add a new key `"expose_as": "query"` in the payload

**Comment by its-a-feature** [comment]
Any idea when this will be pulled into a beta? This is _exactly_ what I need. I was following along with https://www.youtube.com/watch?v=WDBiPbP1iJY, but it doesn't appear to be in the 1.3.4-beta.2.

**Comment by beerose** [comment]
Hi @its-a-feature! It will be released in 1.4, which should be out in just a few days.
