### ISSUE TITLE
optional custom set permission for insert

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#623]
Add custom `set` permission for `insert` and it is optional. 

Example:- If `admin` don't want to `publish` an article created by `student` and value of `author_id` column is `X-Hasura-Student-Id` header

```http
POST /v1/query

{
  "type": "create_insert_permission",
  "args": {
    "table": "article",
    "role": "student",
    "permission": {
      "check": {},
      "set": { "author_id": "X-Hasura-Student-Id", "is_published": false },
      "allow_upsert": true
    }
  }
}
```
For server changes look at this [PR](https://github.com/hasura/graphql-engine/pull/622)

**Comment by dsandip** [comment]
@karthikvt26 @paranoidsp 

1) Let's have a checkbox after role-based checks like this:
![1](https://user-images.githubusercontent.com/24300818/46670723-9b20ae80-cbf0-11e8-8e72-a8ccddddcbcd.png)

2) While the API doesn't care about the preset types, we should have a dropdown to give more context about the fact that values beginning with `X-Hasura-` will be looked for in session variables (more on this later):
![2](https://user-images.githubusercontent.com/24300818/46670734-a2e05300-cbf0-11e8-8132-2b1fa2f243d9.png)


3) Tooltip and general interaction for adding more k-v pairs:
![3](https://user-images.githubusercontent.com/24300818/46670765-b55a8c80-cbf0-11e8-9de9-5227cc9aa7f8.png)

4) Show the `X-Hasura-` prefix with the help text as shown here to drive home the above point about picking preset values from a session variable:
![4](https://user-images.githubusercontent.com/24300818/46670783-bd1a3100-cbf0-11e8-948a-f57e0abbbceb.png)


Signed off by @rikinsk

**Comment by dsandip** [comment]
@karthikvt26 Adding the mockups for the edit flow we discussed yesterday:

* Option to delete a preset when adding multiple ones:
   ![multiple_presets_cross_button](https://user-images.githubusercontent.com/24300818/46788115-261bb900-cd57-11e8-9767-f483557e502e.png)

* Editing presets - removing all presets:
   ![edit_presets](https://user-images.githubusercontent.com/24300818/46788263-654a0a00-cd57-11e8-80c2-b6cd585886e7.png)

* Editing presets - remove 1 of multiple presets:
   ![edit_1_preset](https://user-images.githubusercontent.com/24300818/46788302-7bf06100-cd57-11e8-9ac5-3bab65cb233e.png)
