### ISSUE TITLE
not able to apply metadata on hasura 1.3.3 (plugin manfiest cli-ext: plugin version is not available)

### ISSUE THREAD

**Issue by tanmaypatil** [hasura/graphql-engine#6234]
Using hasura version 1.3.3

- INFO hasura cli                                    version=v1.3.3

- INFO hasura graphql engine                         endpoint="http://localhost:8080" version=v1.3.3

Getting error when applying metadata 
`hasura metadata apply --endpoint http://localhost:8080
FATA[0001] failed to apply metadata: cannot apply metadata on the database: cannot build actions from metadata: cannot fetch plugin manfiest cli-ext: plugin version is not available`

Hasura plugin info
(base) N10991:vam-migs tanmay.patil$ hasura plugin list
WARN unable to update plugin index "some refs were not updated" 
NAME     DESCRIPTION                VERSION       INSTALLED
cli-ext   Hasura CLI extension       v1.3.2        yes
pro       CLI plugin for Hasura Pro  v1.3.0-pro.2  no

**Comment by hgiasac** [comment]
duplicated https://github.com/hasura/graphql-engine/issues/6219

| The current workaround is to rm -rf ~/.hasura and retry.

**Comment by tanmaypatil** [comment]
`(base) N10991:vam-migs tanmay.patil$ ls -l .hasura
ls: .hasura: No such file or directory`

**Comment by tanmaypatil** [comment]
worked thank you @hgiasac
