### ISSUE TITLE
Error when modifying an event trigger URL in the console to include a templated environment variable

### ISSUE THREAD

**Issue by bubba** [hasura/graphql-engine#6239]
After creating an event trigger, modifying the URL to include an environment variable template such as `{{MY_ENV_VAR}}/foo/endpoint` (from 1.3.3) gives a "Saving failed Invalid URL" error. There are no errors logged to the javascript console nor on the server from what I can see

**Comment by altitudems** [comment]
I can confirm this:
<img width="828" alt="Screen Shot 2020-11-23 at 12 35 39 PM" src="https://user-images.githubusercontent.com/73688/100006918-795ef300-2d88-11eb-917c-aa72a8d60ebe.png">
