### ISSUE TITLE
add operators for ltree columns

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#625]
https://www.postgresql.org/docs/current/static/ltree.html

**Comment by DaleBeckles** [comment]
Thank you for your ongoing enhancements to Hasura. Do you have an ETA for this?

**Comment by lxblvs** [comment]
That would be amazing! The current tree implementation is totally lacking https://blog.hasura.io/graphql-and-tree-data-structures-with-postgres-on-hasura-dfa13c0d9b5f/

**Comment by fogelfish** [comment]
This feature I would be a huge benefit for me.  What does it mean for the triage/2-rfc-candidate label to be removed and dsandip to be unassigned?

**Comment by DanieltheYogi** [comment]
Any ETA on this? This would be an incredibly powerful enhancement in the permission rule builder to be able to check hierarchical data.

**Comment by perrosnk** [comment]
Congratulations to all for the nice progress that Hasura is making lately! 

If this is an easy fix could be implemented soon? We are also very interested in this feature, because we need to support a marketplace with a lot of categories and subcategories organized in ltree columns.

**Comment by russelgal** [comment]
> Congratulations to all for the nice progress that Hasura is making lately!
> 
> If this is an easy fix could be implemented soon? We are also very interested in this feature, because we need to support a marketplace with a lot of categories and subcategories organized in ltree columns.

I think we need to wait a couple more years for this feature to be implemented )))
@0x777 or I'm wrong?

**Comment by deepu** [comment]
Eagerly waiting for ltree support. Any ETA guidance would be nice so that we can plan accordingly. thanks.

**Comment by tirumaraiselvan** [comment]
Folks, we have few high priority features already in the queue for the next 2 releases. You can expect this in 3/4 releases from now. Hard to give ETA currently, unfortunately.

**Comment by maxcan** [comment]
Planning yet-another-hasura-project, but kind of need this.  will watch this issue.

**Comment by maxcan** [comment]
@tirumaraiselvan any updates on how this is being sequenced? 

if not, are there any good examples of another data type being added that a contributor could follow?

**Comment by bcordo** [comment]
This would be an incredibly useful feature.

**Comment by russelgal** [comment]
> Thank you for your ongoing enhancements to Hasura. Do you have an ETA for this?

It took only 878 days! (2 years 4 months and 24 days) 😅

**Comment by WonderPanda** [comment]
Loving the LTREE functionality! Is there any ETA or issue tracking the ability to use LTREE operators inside of the permissions system? This would be incredible for some hierarchical permission implementation

**Comment by nicuveo** [comment]
@WonderPanda ltree operators already work in the permissions system, but are not handled by the editor yet. It just means you have to write the permission JSON object manually, like so:

![ltree_permissions](https://user-images.githubusercontent.com/1618949/117335616-41112400-ae93-11eb-86fd-1cb9ac3bd1b8.png)
