### ISSUE TITLE
Tracking foreign data wrappers from MySQL, can not mutation it by hasura mutation operation

### ISSUE THREAD

**Issue by huashaoxu** [hasura/graphql-engine#6258]
Tracking foreign data wrappers from MySQL, can not mutation it by hasura mutation operation

**Comment by tirumaraiselvan** [comment]
Any chance you could share the SQL commands to add mysql as fdw?

**Comment by rsd1122** [comment]
We recently launched our new MySQL alpha integration:
https://hasura.io/docs/latest/databases/mysql/index/

It has support for queries, table relationships and permissions. Support for mutations is coming soon.

Please reach out to me if you would like to be a part of the early-access slack channel where we post the latest builds and updates.

**Comment by rsd1122** [comment]
The Hasura MySQL data connector is now generally available (GA). 

Please our docs for more information:
https://hasura.io/docs/latest/databases/mysql/index/
