### ISSUE TITLE
Hasura CLI 1.3.3: cannot fetch plugin manfiest cli-ext

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#6262]
I can no longer run `hasura md export` because it complains with this message:

`FATA[0001] failed to export metadata: cannot export metadata from server: cannot export actions from metadata: cannot fetch plugin manfiest cli-ext: plugin version is not available `

I also tried upgrading to 1.3.4-beta.1 -- same problem
`hasura update-cli --version 1.3.4-beta.1`

downgrade to 1.3.2 -- everything works
`hasura update-cli --version 1.3.2`

**Comment by webdeb** [comment]
Try to remove `.hasura` from your home path

```
rm -rf ~/.hasura
```

**Comment by scriptonist** [comment]
https://github.com/hasura/graphql-engine/issues/6219

**Comment by jflambert** [comment]
that works. Since you closed the other issue (#6219) I'm gonna assume 1.3.4 or whatever won't have that issue.

You might want to fix that typo!!! `manfiest`
