### ISSUE TITLE
Support for dynamic datetimes in events

### ISSUE THREAD

**Issue by coloradocolby** [hasura/graphql-engine#6267]
I apologize if there is a better space to be asking this question, but I'm curious to know if there is anyway to implement an operation like so:

```
mutation {
  delete_posts(where: {created_at: {_gte: "<two-days-ago>"}})
}
```

The specific use case here being a cron event that checks every 5 minutes for a post older than 2 days and deletes it. I'm guessing at the minute this is not supported, but if it were I could see it opening the door to many powerful cron events!

**Comment by tirumaraiselvan** [comment]
Closing this in favour of https://github.com/hasura/graphql-engine/issues/2178
