### ISSUE TITLE
Role, permission and error "validation-failed" on a simple "select query"

### ISSUE THREAD

**Issue by tdetugny** [hasura/graphql-engine#6279]
I have a user role with a right restriction on only one field of a "select" request. Is it possible to have something else than a global error with "validation-failed" ?
It's a pity to have all the request in error because it forces us to check the role and to make two requests - according to the role of the current user - with in addition, specific code for the display.

It would be so much easier for front end developers to get an error for the restricted field but with the rest of the data.

I also tried the operator `@skip(if: ...)` but I still have the global error "validation-failed"

**Comment by followbl** [comment]
this exact scenario on `1.3.3` is failing for us on `v1.3.4-beta.1` related to the skip functionality.

**Comment by tirumaraiselvan** [comment]
@followbl Could you give a sample query that was working in `v1.3.3` but not in `v1.3.4-beta.1` ? We tried to reproduce this but simple cases have the same behaviour in `v1.3.3` as in `v1.3.4-beta.1` .

Also if this is a regression report, do you mind opening a new issue as the original comment is a feature request.

**Comment by tirumaraiselvan** [comment]
> I also tried the operator @skip(if: ...) but I still have the global error "validation-failed"

Are you using `v1.3.4-beta.1`?

> this exact scenario on 1.3.3 is failing for us on v1.3.4-beta.1 related to the skip functionality.

@followbl Do you mean what is throwing an error in `v1.3.3` is passing for you in `v1.3.4-beta.1` ? Isn't this an expected improvement?

In `v1.3.4-beta.1`, the following query will NOT throw a `validation-failed` even if `email` doesn't have select permission:

```
# x-hasura-role: user (does not have select permission on `email`)
query {
  test {
    id
    name
    email @skip(if: true) 
  }
}
```
This would have thrown the `validation-failed` error on v1.3.3 and prior.

**Comment by tdetugny** [comment]
I have just checked with v1.3.4-beta.2. I works ! Thanks for your help @tirumaraiselvan
