### ISSUE TITLE
invalid column type when using "frequently used columns" in console

### ISSUE THREAD

**Issue by beerose** [hasura/graphql-engine#6287]
![Screenshot 2020-12-02 at 14 31 11](https://user-images.githubusercontent.com/9019397/100878869-07cf2500-34ab-11eb-8f4d-c9b0f11b6222.png)

When selecting a value from "frequently used columns" dropdown, console _sometimes_ populates a label instead of an actual data type.

**Comment by prajzwol7** [comment]
@beerose this issue has been solved

**Comment by vijayprasanna13** [comment]
Thanks @prajzwol7, closing this issue.
