### ISSUE TITLE
Console - "Analyze" gives bad error when admin-secret is not set

### ISSUE THREAD

**Issue by rccoe** [hasura/graphql-engine#6288]
I have a pretty complex query that involves permissions, and when I try to hit "Analyze" on the GraphiQL tab in the console, I get an alert error back:

> Unable to fetch: undefined.

The 400 error I get back is that I have to be an admin to use it. 

Pretty sure its because I'm passing the token in (to simulate a user) and excluding the admin secret header.

**Comment by tirumaraiselvan** [comment]
Could you share the postgres schema, hasura metadata and the query that you are trying?

**Comment by rccoe** [comment]
I'm pretty sure you can reproduce without me having to dump all that here / create a minimal example.

1. Open Hasura Console
2. Write any graphql query
3. Remove the x-hasura-admin-secret header from the request
4. Add an authorization token that will work (and any other appropriate headers, e.g. x-hasura-user-id)
5. Hit "Analyze"

Result: 
1. Alert: Unable to fetch: undefined.
2. Frontend console app crashes

**Comment by tirumaraiselvan** [comment]
You are right. The `explain` API only works with admin secret (since this is kind of a privileged operation). If you only have `Authorization` header and try explain then it gives the following error in the browser dev tools and also immediately logs you off the console:

```
{"path":"$","error":"You have to be an admin to access this endpoint","code":"access-denied"}
```
We should fix the error message there to show that it requires admin secret.

**Comment by Notalifeform** [comment]
If you provide the admin-secret (next to the  it does not x-hasura-user-id, x-hasura-default-role, x-hasura-allowed-roles) that I would expect that 'analyze' would do the analyze for that users - that does not seem the case. correct?
