### ISSUE TITLE
Postgres function can not be tracked because the function does not return a SETOF table

### ISSUE THREAD

**Issue by tanmaypatil** [hasura/graphql-engine#6292]
Following function can not be tracked by hasura . because of following error 
```
CREATE FUNCTION vam.hierarchy_parent_accounts (acct_id  text)
RETURNS SETOF  public.virt_acct AS $$
  with recursive parents as (
  select account_id , account_name , parent_id ,  1 as level 
   from vam.virtual_account va where account_id::text = acct_id
 union all 
    select va.account_id , va.account_name , va.parent_id  ,level+1  as level
    from  vam.virtual_account va
    join parents on va.account_id  = parents.parent_id
    )
   select * from parents;
$$ LANGUAGE sql stable 
```;

Error is as below 
```
{
    "internal": [
        {
            "definition": {
                "schema": "vam",
                "name": "hierarchy_parent_accounts"
            },
            "reason": "in function \"vam.hierarchy_parent_accounts\": the function \"vam.hierarchy_parent_accounts\" cannot be tracked because the function does not return a SETOF table",
            "type": "function"
        }
    ],
    "path": "$.args[1].args",
    "error": "in function \"vam.hierarchy_parent_accounts\": the function \"vam.hierarchy_parent_accounts\" cannot be tracked because the function does not return a SETOF table",
    "code": "constraint-violation"
}

```
virt_acct is defined as type

`CREATE  TYPE vam.virt_acct AS (account_id  text , account_name text,parent_id text , level  integer );`

**Comment by tanmaypatil** [comment]
Create a table with name virt_acct and same columns namely account_id , account_name , parent_id , level . Was able to track function,

**Comment by maxpain** [comment]
> Create a table with name virt_acct and same columns namely account_id , account_name , parent_id , level . Was able to track function,

I can't use this workaround on v2.5.1.
