### ISSUE TITLE
Protecting individual rows from modification (Postgres Rules vs Triggers)

### ISSUE THREAD

**Issue by zewa666** [hasura/graphql-engine#6298]
Hey there,

I've got a table that contains user roles (not related to Hasura but my apps ones). Now one of them has the name `authenticated` and another one `guest`. The user is allowed to modify/delete roles except those two.

As far as I understand I could go along with an onDelete/Update trigger and check whether any of the mentioned rows is targeted.

But I also read about [Postgres Rules](https://www.postgresql.org/docs/8.3/rules-triggers.html) and felt like they would be better suited for my usecase. Are they supported by Hasura? or lets put it different. are they going to cause issues if I add them?

**Comment by tirumaraiselvan** [comment]
Postgres rules won't cause any issues for Hasura. From Hasura's standpoint, it is just a db trigger which Hasura does not interfere with.
