### ISSUE TITLE
Unable to use env var to template URL when updating URL for event trigger

### ISSUE THREAD

**Issue by elitan** [hasura/graphql-engine#6301]
![2020-12-04 14 56 28](https://user-images.githubusercontent.com/331818/101172313-4dbdf180-3641-11eb-836a-4079dec012f3.gif)

**Comment by beerose** [comment]
Thanks for the report and detailed reproduction steps!

It was previously reported here: https://github.com/hasura/graphql-engine/issues/6239.
We just merged a fix, it will be deployed in a bit. 

Closing this issue as a duplicate.
