### ISSUE TITLE
metadata updates cause locks

### ISSUE THREAD

**Issue by maxpain** [hasura/graphql-engine#6302]
Sometimes when I change something in hasura metadata (for example create SQL function or update event trigger) our website crashes. I noticed that at this moment there are a lot of locks:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/5875582/101183442-95a04100-3660-11eb-9613-c9ce9ba52e4b.png">

**Comment by tirumaraiselvan** [comment]
Are you using the CLI? If yes, this was fixed in v1.3.3: https://github.com/hasura/graphql-engine/issues/6115

**Comment by maxpain** [comment]
@tirumaraiselvan no, I do metadata updated via console. And also we use patched version (hasura/graphql-engine:pull5495-b2500d26)

**Comment by tirumaraiselvan** [comment]
Would you be able to give the result of the following the next time this happens:

1. Who is waiting for locks on whom

```
SELECT
    activity.pid,
    activity.usename,
    activity.query,
    blocking.pid AS blocking_id,
    blocking.query AS blocking_query
FROM pg_stat_activity AS activity
JOIN pg_stat_activity AS blocking ON blocking.pid = ANY(pg_blocking_pids(activity.pid));
```

And 2. What locks are not granted

```
  select relation::regclass, * from pg_locks where not granted;

```

**Comment by tirumaraiselvan** [comment]
BTW, RowExclusive and RowShare lock are DML locks and this could be happening because the DDL that your migration is performing is blocking the running DMLs. What is the database activity looking like at the time of these changes?
