### ISSUE TITLE
Metadata problem

### ISSUE THREAD

**Issue by Manubi** [hasura/graphql-engine#6312]
Hi,
how can this happen and how can I avoid it?

![Settings___Hasura](https://user-images.githubusercontent.com/20935138/101292429-ac38ca80-380f-11eb-93d4-44ebfc535b9f.jpg)

**Comment by ayuryshev** [comment]
I suppose that DB objects were changed and hasura fairly displays those changes in DB.

There is no need to prevent or avoid this: there is a need to update hasura metadata after changing DB objects.

**Comment by Manubi** [comment]
It deleted my metadata so I needed to add it again. So it looks like a problem to me.

**Comment by ayuryshev** [comment]
From what I see there were changes in DB:
- 2 foreign key constraints were dropped
- 3 columns we dropped

It's not a hasura problem.
Find someone who do that
