### ISSUE TITLE
Use env variable to define whether to show console or not

### ISSUE THREAD

**Issue by valstu** [hasura/graphql-engine#632]
I discussed about this topic earlier today on Discord. It would be nice if there would be additional env variable for whether console is visible or not. 

You can currently use following env variables with graphql-engine:
- `HASURA_GRAPHQL_DATABASE_URL`
- `HASURA_GRAPHQL_ACCESS_KEY`
- `HASURA_GRAPHQL_AUTH_HOOK`
- `HASURA_GRAPHQL_CORS_DOMAIN`
- `HASURA_GRAPHQL_JWT_SECRET` <-- this could be added to these [docs](https://docs.hasura.io/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html)

These env variables are logical and are pretty much the same as the cli flags mentioned on the docs. But it would be nice if there would be extra env variable for `--enable-console` flag as well. It could be `HASURA_GRAPHQL_ENABLE_CONSOLE` so it follows the logic of other env variables.

There are also few other flags which doesn't have matching env variables.

**Comment by manu-chroma** [comment]
hey, this seems like a good beginner task. Can I take up this one?

**Comment by 0x777** [comment]
@manu-chroma Hi ! This is being worked on and scheduled to be released today. Another issue maybe?

**Comment by dsandip** [comment]
@manu-chroma Created another issue for the docs part here #641. You can take that up.
