### ISSUE TITLE
Migrations & Metadata in AWS fargate

### ISSUE THREAD

**Issue by carlfedak** [hasura/graphql-engine#6332]
Question:

I have the cli-migrations image deployed in AWS fargate, with mu ci/CD pipeline up and running from a git repo all the way to the image. 

Question is:  with migrations specifically, doesn’t this mean each time the container boots/scales up and starts new one, the migrations will try and apply each time?

If so... is this... ok?  Am I doing this right??

**Comment by tirumaraiselvan** [comment]
The migration history is stored in the hasura catalog schema: `select * from hdb_catalog.schema_migrations ;` so it is not reapplied everytime.

**Comment by carlfedak** [comment]
Thanks, I guess my question was not specific enough, so same question about metadata.  If I'm running 2 (or 20?) containers of hasura, do I need to apply the metadata across all of them, like with the auto-apply image or is running it from a CI/CD deployment script against the shared endpoint enough to trigger the other containers to sync?
