### ISSUE TITLE
Allow VOLATILE functions for queries and subscriptions

### ISSUE THREAD

**Issue by ayuryshev** [hasura/graphql-engine#6333]
This issue is written in response for https://github.com/hasura/graphql-engine/issues/1514#issuecomment-716677761

Please don't reject this proposal  outright from theorethical standpoint that queries must be without side effects.

There are 2 cross-cutting concerns that could be solved with impure functions:
- server-side memoization 
- logging

# Server-side memoization 

Consider the following scenario:
- there is a big historical table with millions of records
- there is a need to provide aggregate data from this table 
- this aggregate data is rarely needed and  it's not needed for everyday functionality of system
- it costs a lot to prepare such aggregated data for all records

With impure function it could be implemented as:
- look for prepared aggregate data
- if not exists - prepare it
- return prepared data

This way only first query will execute long time, next queries will be fast and aggregated data will be shared between users.

Such functions would work extremely well in case of subscriptions.

# Logging

Sometimes arises a need to have log of queries.

E.g. right now I have a need to check that frontend application pass correct hasura session parameter into functions.

With impure functions it could be dumb simple: create log table, write function parameters into it.

Right now I don't have such option. I need to check it by other means.

Logging in query functions would be extremely well in development environments.

# Overall

From theorethical standpoint both cases  violates principle that graphlq queries must be "side-effect free".

From practical POV - I think that even Seymour Peyton-Jones will not object such "violations".

Please consider such functionality.

**Comment by karibertils** [comment]
These are definitely useful and practical things I would like having when working with Hasura.

**Comment by tirumaraiselvan** [comment]
Thank you for the detailed description of the use-case. VOLATILE functions will be supported as queries as well (ref: https://github.com/hasura/graphql-engine/issues/1514#issuecomment-744498072).
