### ISSUE TITLE
Console: permissions unusable with keyboard

### ISSUE THREAD

**Issue by mantagen** [hasura/graphql-engine#6343]
![image](https://user-images.githubusercontent.com/12934669/102104831-89697000-3e26-11eb-9b98-ed8dc2db1b26.png)

- `ctrl` expands and collapses the list items (which it shouldn't) 
- `tab` exapnds and collapses the list items (rather than tabbing onto the next visible item)
- if you expand an item (eg using `right arrow` or `space`) then attempt to `tab` onto it's child content, what actually happens is that the list item closes, and you a tabbed onto the next list item

**Comment by troglotit** [comment]
Closed by #6416
