### ISSUE TITLE
Remote schema relationships tab not present in console

### ISSUE THREAD

**Issue by IceHoppr** [hasura/graphql-engine#6353]
I am using docker-compose based deployment of Hasura engine v 1.3.3 to connect to remote GraphQL API.

I can add remote schema and I can make queries, however, the only 'Details' and 'Modify' tabs are visible on the 'Remote Schemas' section.  Is there any special config I need to enable in docker-compose to make the 'Relationships' tab visible?

I will like to add local DB based schema and remote schema relationships as described in the following link. https://hasura.io/docs/1.0/graphql/core/schema/remote-relationships/remote-schema-relationships.html

hasura/graphql-engine:v1.3.3
Console asset version: 1607958177782

**Comment by tirumaraiselvan** [comment]
The "Remote schema relationships" section is actually present in the `Relationships` tab of your **table**. The relationship is from a table to your remote schema. The docs here: https://hasura.io/docs/1.0/graphql/core/schema/remote-relationships/remote-schema-relationships.html#step-1-open-the-remote-relationship-section definitely can be improved to emphasize that the relationship has to be made from the `Table` page.

**Comment by IceHoppr** [comment]
@tirumaraiselvan OK I had an initial setup using MySQL but it stopped working as soon as I moved to 1.3.3 for the 'remote schema'.  I will use Postgres instead and test.  So in order to have a remote schema relationship we have to have a 'local' database-based GraphQL schema table? We cannot have two remote schemas that are GraphQL APIs?

**Comment by tirumaraiselvan** [comment]
Yes, currently remote schema relationships are between a Postgres table and a remote schema. 

Remote schema to remote schema relationships is also part of the roadmap but not released yet.

**Comment by IceHoppr** [comment]
@tirumaraiselvan thanks for the help! Remote schema linking is working fine.  
If you have any specific PR deals with remote to a remote schema in the works please share the details.

**Comment by tirumaraiselvan** [comment]
It is still early for remote to remote schema. We will make plenty of announcements when we get closer to releasing that - late Q1 or early Q2.
