### ISSUE TITLE
Actions permissions : permission for role not defined  

### ISSUE THREAD

**Issue by Julien-Sytadelle** [hasura/graphql-engine#6355]
Hi,

Using Hasura cloud, when I try to allow a role to use an action, it sends "drop_action_permission" as type instead of create.
So api replies that the permissions does not exists.
I modified the query to pass "create_action_permission" as type and it works fine.
Removing the permissions works well.

**Comment by karthikvt26** [comment]
@Julien-Sytadelle there is a regression on the `cloud`. We are working on the fix at the moment.
