### ISSUE TITLE
metadata/actions.yaml and actions.graphql are not auto-updated after upgrading to v1.3.3

### ISSUE THREAD

**Issue by denis-ryzhkov** [hasura/graphql-engine#6356]
With Hasura v1.3.2 when I created a new action in Hasura Console, both `metadata/actions.yaml` and `metadata/actions.graphql` were updated automatically.

Now in v1.3.3 I create a new action in Hasura Console, it is created successfully, listed and available via Hasura Console, but `metadata/actions.*` files are not updated any more - why?

**Comment by scriptonist** [comment]
@denis-ryzhkov AFAIK there were no changes to that part of code in `v1.3.3` . can you confirm you did open console using the `hasura console` command and observed this behavior?

**Comment by denis-ryzhkov** [comment]
@scriptonist yes, I double-checked, it is the same `hasura console --skip-update-check` I always used.

Also, from Chrome Inspect Network tab I see that when action is saved, `http://localhost:8080/v1/query` with `{"type":"bulk","args":[{"type":"select","args":{"table":{"name":"hdb_action","schema":"hdb_catalog"},...` responds with my new action name included in the list of actions. So `hdb_action` table was updated successfully, but `metadata/actions.*` files - were not. Both `git diff` and manual check prove this.

Should I try to downgrade to v1.3.2?

**Comment by scriptonist** [comment]
@denis-ryzhkov Thank you. I was trying to reproduce this but it seems to works ok for me.  

We might need some help to understand if this is a bug by

1. make sure we using console opened by CLI (http://localhost:9695/console if you are using the default settings)
2. Downgrade to verify the issue is specific to the new version.

**Comment by denis-ryzhkov** [comment]
@scriptonist

1. yes
2. yes, downgrade to v1.3.2 resolved the issue

**Comment by CoenNengerman** [comment]
I have the same issue. Will try downgrading.

**Comment by scriptonist** [comment]
@denis-ryzhkov Thanks for the prompt reply, I'm trying to reproduce this but still hasn't succeeded. 

Would be a great help, if you can 
1. Add a screenshot of dev tools network tab specifically for requests going to http://localhost:9693
2. Paste in output for `hasura console --skip-update-check --log-level debug`

**Comment by denis-ryzhkov** [comment]
@scriptonist alas, I'm AFK until tomorrow.
maybe @CoenNengerman could help to debug this?

**Comment by scriptonist** [comment]
I'm guessing this can happen because of https://github.com/hasura/graphql-engine/issues/6219. 
would appreciate if someone can try the workaround mentioned there.

> The current workaround is to `rm -rf ~/.hasura` and retry.

**Comment by CoenNengerman** [comment]
debug gives me this message: "DEBU cannot export actions from metadata: cannot fetch plugin manfiest cli-ext: plugin version is not available"

**Comment by scriptonist** [comment]
Thanks for the quick turnaround @CoenNengerman , that sort of confirms my doubt here https://github.com/hasura/graphql-engine/issues/6356#issuecomment-746424526, do you mind trying the workaround?

**Comment by CoenNengerman** [comment]
I will try the workaround.

**Comment by CoenNengerman** [comment]
The workaround works like a charm (for me). Thank you very much!

**Comment by tirumaraiselvan** [comment]
Seems like this was caused by #6356

**Comment by denis-ryzhkov** [comment]
> Seems like this was caused by #6356

Do you mean #6356 is caused by #6356 ? :)

Maybe you have meant some other issue?

If that related issue is fixed, please link it here,
else please reopen current issue #6356 until it gets fixed

**Comment by scriptonist** [comment]
I think that was a typo, the right issue is https://github.com/hasura/graphql-engine/issues/6219
