### ISSUE TITLE
after row insertion - add redirection to the row in the popped up notification

### ISSUE THREAD

**Issue by yairv13** [hasura/graphql-engine#6362]
Hi guys, we appreciate your hard work and your awesome product!
I have some improvement to the UI/UX for inserting data from within Hasura.

Steps to reproduce:
1. choose a table
2. go to Insert Row tab
3. insert data and press Save

Now a notification saying "Inserted! affected rows: x" is being popped up, but there's no option to see the inserted data (e.g. in order to see what the row's id is, etc.), you have to go manually to the table and search for it.

Add a Link in the notification that redirects to the rows' display.

Alternative: A collapse bar in the notification itself, that upon pressed will reveal the inserted data.

**Comment by beerose** [comment]
Solution (for now):

[Update `returning`](https://github.com/hasura/graphql-engine-mono/blob/main/console/src/components/Services/Data/TableInsertItem/InsertActions.js#L148) to contain a list of all the columns:
```ls
const returning = columns.map(col => col.column_name);
```
and use returned values to fill the insert item form.
