### ISSUE TITLE
MySQL preview cannot order_by?

### ISSUE THREAD

**Issue by toomanyjoes** [hasura/graphql-engine#6367]
The docs:
https://hasura.io/docs/1.0/graphql/core/queries/sorting.html

do not seem to apply to mysql. When I query with this argument I get the following:

```json
"errors": [
    {
      "extensions": {
        "path": "$.selectionSet.table",
        "code": "validation-failed"
      },
      "message": "\"table\" has no argument named \"order_by\""
    }
  ]
```

**Comment by 0x777** [comment]
@toomanyjoes So far the strategy for query execution with graphql-engine has been to convert the graphql query into a SQL query that the underlying database understands. This requires the database to support aggregating rows into json arrays - on MySQL the function is `json_arrayagg`, but it does not preserve the ordering of rows specified through 'order by' and does not support an additional 'order by' clause for aggregation. This means that we can't support `order_by` in the GraphQL API with the similar execution logic as Postgres. 

To work around these limitations, we've been working an a new execution engine for databases such as MySQL (where the SQL features are not as powerful as Postgres). We'll post an update as soon as this is ready!

**Comment by rsd1122** [comment]
We recently launched our new MySQL alpha integration:
https://hasura.io/docs/latest/databases/mysql/index/

It has support for queries, table relationships and permissions. Support for mutations is coming soon.

Please reach out to me if you would like to be a part of the early-access slack channel where we post the latest builds and updates.

(Note: The previous version has been deprecated)
