### ISSUE TITLE
Hasura Action to Self-Signed Cert

### ISSUE THREAD

**Issue by its-a-feature** [hasura/graphql-engine#6369]
I need to be able to use Hasura Actions to post to a server with a self-signed cert which I do not control. Or more generically, using Actions to a certificate that isn't trusted and which I do not have the ability ahead of time to get the certs for. Many programming languages or tools have an option for `--insecure` or some way to say either generically (or for a specific site) to ignore the cert chain. Is that possible in Hasura?

**Comment by tirumaraiselvan** [comment]
This is now possible in v2.0.8. Go to console -> Settings page (top right gear icon) -> Insecure TLS Allowlist
