### ISSUE TITLE
Nullable fields when permissions are restricted

### ISSUE THREAD

**Issue by webdeb** [hasura/graphql-engine#6373]
There are a lot of obvious use-cases where you have different field sets for different roles.

Imagine you are building a "job-advertisement page". You want to show everybody the basic job information even anons,
but you also want to show applicants information to the owner of the ad.

```
job_by_pk(id: 1) {
  title
  description
  applicants {
    message
    applicant {
      name
      skills
    }
  }
}
```

Now when your anonymous role does not have any permissions to the many-to-many relationship `applicants`, your graphql Server will throw an error, that the applicants field does not exists.

Not only, that this is awkward to first load the user and then decide which query to perform. It also requires additional requests.

As an idea, maybe instead of an error, hasura could just return `null` for any field which does not exists and try to load the other fields? Or why would this be a bad idea?

```
query {
  foo {
    bar
  }
  user {
    id
    baz
  }
}
--- result
data: {
  foo: null,
  user: [
    { id: 1, baz: null}
  ]
}
```

If not the default behaviour, but as an option?

![](https://user-images.githubusercontent.com/14992140/102697172-20be3100-4234-11eb-851a-8f4aca8f9cd0.png)

**Comment by webdeb** [comment]
Or why would this be a bad idea?

**Comment by webdeb** [comment]
Maybe its kinda a bad idea to make it the default behaviour, but it seems to be a totally valid option

![Bildschirmfoto 2020-12-19 um 19 52 14](https://user-images.githubusercontent.com/14992140/102697172-20be3100-4234-11eb-851a-8f4aca8f9cd0.png)

**Comment by tirumaraiselvan** [comment]
This is now possible via "Inherited Roles" as described in this issue: https://github.com/hasura/graphql-engine/issues/6541

**Comment by xiaoyu-tamu** [comment]
Hi, @tirumaraiselvan. Could you please explain a little more how to make it return null via "Inherited Roles"?
