### ISSUE TITLE
send query fields as part of action payload

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#6383]
Currently, when writing the Action handler, the payload that is received contains the input arguments and session variables/headers. But it doesn't contain the fields that were part of the query or mutation.

This is the current payload.
```
{
  "action": {
    "name": "<action-name>"
  },
  "input": {
    "arg1": "<value>",
    "arg2": "<value>"
  },
  "session_variables": {
    "x-hasura-user-id": "<session-user-id>",
    "x-hasura-role": "<session-user-role>"
  }
}
```
In addition, I would like to get the actual GraphQL query made / just the fields of the query in another object.

This information will be useful to optimize data fetching inside the Action handler.

After feedback from product, it may be easier to simply include the query instead of the field listing, in which case the payload would include the query under the `request_query` field.

**Comment by pranshi06** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/e77b79ae02c121406278bcaf06e5cfe09a122fb6
