### ISSUE TITLE
(1.3.4-beta.2) action relationship with permissions

### ISSUE THREAD

**Issue by jacdx** [hasura/graphql-engine#6385]
Trying out 1.3.4 beta 2 today (from 1.3.3) and I have run into multiple issues. Haven't had issues upgrading before. PostgreSQL 11.5 

1. Hasura wouldn't start due to hyphens in primary keys. This worked previously.
`{"type":"startup","timestamp":"2020-12-22T16:14:35.348+0000","level":"error","detail":{"kind":"catalog_migrate","info":{"path":"$","error":"cannot` include \"article-article_category_pk\" in the GraphQL schema because it is not a valid GraphQL identifier","code":"validation-failed"}}} .` I refactored those to remove the error.

2. Then, I got an error on a previously working Action query. I'm not using `hasura.user` anywhere in code. I finally restarted the server and it went away.
`"error": {
          "path": "$",
          "error": "unrecognized configuration parameter \"hasura.user\"",
          "code": "constraint-error"
},`

3. Now, I'm getting "invalid input syntax for type json" from the same action. 
`"error": {
    "path": "$",
    "error": "invalid input syntax for type json",
    "code": "data-exception"
},`

It's a simple action--not sure where to go from here: 
`type GetHomeContentOutput {
  postId : Int
}`

**Comment by codingkarthik** [comment]
Hello @jacdx,

Thank your for reporting this issue. I was not able to reproduce #1 of your description. I created a table with the name "article-article_category" and tracked it in v1.3.3 and then upgraded the graphql-engine to v1.3.4-beta.2 and everything seems to work fine. Did you try to track the table with a custom name? Because that's the only way the above mentioned issue can arise

**Comment by tirumaraiselvan** [comment]
Regarding the action, can you also please provide the query/mutation definition as well? I couldn't reproduce this with just `type GetHomeContentOutput { postId : Int }` as my output type.

**Comment by jacdx** [comment]
Hi guys,

#1 
My table is `article_article_category`, and the pkey was `article-article_category`. I removed the hyphen from the pkey to resolve that error.

#2/3
Action definition:
`type Query {
  GetHomeContent (
    offset: Int
  ): [GetHomeContentOutput]
}
`
This action also has a relationship `post  / GetHomeContentOutput . postId → public.post . id`

Example Action handler response:
`{
  statusCode: 200,
  body: '[{"postId":46},{"postId":45},{"postId":44},{"postId":43},{"postId":42}]'
}`

BTW, I went back to 1.3.3 and it's working again

**Comment by tirumaraiselvan** [comment]
@jacdx Thanks for the more details. I am still unable to reproduce this in v1.3.4-beta.2

This is my action handler code (in nodejs with express):

```
app.post('/', (req, res) => {
    console.log(req.body);
    res.json([{"postId":1},{"postId":2}]);
});
```

and this query:

```
query {
  GetHomeContent {
    postId
    post {
      content
    }
  }
}
```

works as expected:

```
{
  "data": {
    "GetHomeContent": [
      {
        "postId": 1,
        "post": {
          "content": "abc"
        }
      },
      {
        "postId": 2,
        "post": {
          "content": "xyz"
        }
      }
    ]
  }
}
```

**Comment by tirumaraiselvan** [comment]
If you could share your metadata and your action handler code, then maybe I can reproduce it. If it's private then you can mail me at `tiru@hasura.io`

**Comment by jacdx** [comment]
@tirumaraiselvan sent you an invite to the source code that day (google drive). Did you receive it?

**Comment by tirumaraiselvan** [comment]
Thanks @jacdx . I was on holidays last few days. I will check your repro today.

**Comment by tirumaraiselvan** [comment]
I have been able to reproduce this and forwarded to our engineering team. Thanks for the report!

The issue seems to arise when using a role and action relationships (with permissions on the relationship table).
