### ISSUE TITLE
document decrement operation (using _inc)

### ISSUE THREAD

**Issue by rossng** [hasura/graphql-engine#6390]
Hasura [already supports an atomic 'increment' operator](https://hasura.io/blog/updating-data-using-mutations-on-hasura-graphql-87c7e22503bc/), `_inc`. It would be useful to have a similar decrement operator (perhaps `_dec`).

Example use case: counter of remaining attempts. A number can be set by an adminstrator and then decremented each time a user performs an action. When the counter reaches 0 the user can no longer perform the action. This is possible with `_inc`, but only by using a) negative numbers or b) two columns (counter + maximum).

**Comment by tirumaraiselvan** [comment]
As you rightly pointed out, you can use the `_inc` operator with negative values to perform a decrement. You can also set up permission rule so that the column values remains `gte: 0` (greater than or equal to 0). 

So if I understand correctly, you want this essentially as a syntactic sugar?

**Comment by rossng** [comment]
Oh, interesting. For some reason supplying a negative number hadn't even crossed my mind - but that's an ideal solution. I don't think the syntactic sugar is necessary in that case.

(For context, I had been thinking about setting the number to e.g. `-3` initially and then incrementing it until it reached `0`)

However, it would definitely be helpful to explicitly call out the negative number support in the documentation/blog post.

**Comment by rikinsk** [comment]
closed via https://github.com/hasura/graphql-engine/commit/8246bcc9d329ac9231af73799499ff37be5f4ec6

**Comment by Monte9** [comment]
> Oh, interesting. For some reason supplying a negative number hadn't even crossed my mind 

Lol same. I spent a good 5 mins wondering why there wasn't a `_dec` function before I read this thread. Syntactical sugar no needed, but clearly people think pretty linearly. So if there's a `_inc` and no `_dec` it's a head scratcher.
