### ISSUE TITLE
List of tables is unsorted in 'Create a new event trigger' form

### ISSUE THREAD

**Issue by rossng** [hasura/graphql-engine#6391]
It would be nice if the list of tables in the dropdown at `/console/events/data/add` was alphabetised. Here's what the current experience looks like:

![image](https://user-images.githubusercontent.com/565371/103107547-49309b80-4637-11eb-95ad-d9733071d5d6.png)

**Comment by safwan-1998** [comment]
i am taking this.

**Comment by keremgocen** [comment]
@safwan-1998 any progress on this one? I'd like to have a go if you're not currently working on it.

**Comment by Varun-Choudhary** [comment]
Hi @rossng, thanks for reporting the issue. The issue is fixed and will be released in the next version.
