### ISSUE TITLE
Actions generate array relation types for object relations

### ISSUE THREAD

**Issue by altschuler** [hasura/graphql-engine#6402]
In v1.3.4-beta2 the action result types are being generated as array types even though they are configured as object relations.

Configuration:
![image](https://user-images.githubusercontent.com/956928/103369916-aa3ef000-4acb-11eb-9ba0-1926d56b51a2.png)

Generated schema:
![image](https://user-images.githubusercontent.com/956928/103371680-61d60100-4ad0-11eb-918b-6d01df67b8e0.png)

The `group` field of `CreateGroupResult` should be of type `groups`, which it also used to be :)

*The actual data sent is correct*, ie I'm receiving a single `groups` object, not an array.

**Comment by JanC** [comment]
hey, the issue is closed but was there a PR that addressed it? I'm runing into the same issue in `1.3.4 beta 2`
