### ISSUE TITLE
Can't use transaction mode in PGBouncer

### ISSUE THREAD

**Issue by maxpain** [hasura/graphql-engine#6405]
We have a lot of connections in Postgres from Hasura instances and have to use connection pooler in front of Postgres.
As I see Hasura uses LISTEN/NOTIFY to sync metadata between Hasura replicas, so we can't use Transaction or Statement pooling, only Session mode in PGBouncer.

Is it possible to make separate env variable (Besides `HASURA_GRAPHQL_DATABASE_URL`) for metadata sync?

**Comment by tirumaraiselvan** [comment]
Configuring a separate database for metadata will be available in v1.4. It's almost ready to be released (in beta).

**Comment by tirumaraiselvan** [comment]
v1.4.0-alpha.1 is now released which takes a parameter `HASURA_GRAPHQL_METADATA_DATABASE_URL` for just Hasura metadata. Now you wouldn't need a external connection pooler infront of the metadata db. You can one for your data source db though.

**Comment by tirumaraiselvan** [comment]
Closing this as resolved. We can continue the discussion/reopen in case this doesn't work.

**Comment by maxpain** [comment]
@tirumaraiselvan Thank you!
