### ISSUE TITLE
Mutate multiple rows using the same alias

### ISSUE THREAD

**Issue by realph** [hasura/graphql-engine#6407]
I'm trying to mutate multiple rows on the same table using the same alias like this:

    mutation {
        update_games(
          where: {gameId: {_eq: "3030-49998"}}
          _set: {boxart: "https://giantbomb1.cbsistatic.com/uploads/original/0/3699/2920687-the%20legend%20of%20zelda%20-%20breath%20of%20the%20wild%20v7.jpg"}
        ) {
          affected_rows
        }

      update_games(
          where: {gameId: {_eq: "2010-42298"}}
          _set: {boxart: "https://giantbomb1.cbsistatic.com/uploads/scale_small/11/118833/2996375-91somf876vl._sl1500_.jpg"}
        ) {
          affected_rows
        }
    }

However this mutation is throwing the following errors:

    cannot merge fields with different arguments under the same alias: \"update_games\"

Is there a way to do this? I'm new to the backend so I'm not sure if this is even good practice. Is there a better way to update multiple rows in a database in one single request?

Any help is appreciated. Thanks in advance!

**Comment by xiaoyu-tamu** [comment]
```
mutation {
   u1: update_games(
      where: {gameId: {_eq: "3030-49998"}}
      _set: {boxart: "https://giantbomb1.cbsistatic.com/uploads/original/0/3699/2920687-the%20legend%20of%20zelda%20-%20breath%20of%20the%20wild%20v7.jpg"}
    ) {
      affected_rows
    }

  u2: update_games(
      where: {gameId: {_eq: "2010-42298"}}
      _set: {boxart: "https://giantbomb1.cbsistatic.com/uploads/scale_small/11/118833/2996375-91somf876vl._sl1500_.jpg"}
    ) {
      affected_rows
    }
}
```

**Comment by tirumaraiselvan** [comment]
The above solution will make your operation work. Thanks @xiaoyu-tamu 

We also have this related feature request: https://github.com/hasura/graphql-engine/issues/2768

**Comment by franciscolourenco** [comment]
How can this solution work with the [allow-list](https://hasura.io/docs/latest/graphql/core/deployment/allow-list.html#:~:text=The%20Allow%2Dlist%20is%20a,0.0%2Dbeta.) functionality?
