### ISSUE TITLE
Unable to pass order_by variable in javascript

### ISSUE THREAD

**Issue by baronyoung** [hasura/graphql-engine#6408]
On GraphiQL this works fine:
```
query MyQuery($order_by: [audits_order_by!] = {}) {
  audits(order_by: $order_by) {
    treatment_date
  }
}

query variables:
{
  "order_by": {"treatment_date": "desc"}
}
```

However, when trying to pass this variable in javascript I can't get it to work by setting an object to the same value using:

```
const order_by = {
 {treatment_date: "desc"}
}

const QUERY_DATA = gql`
query MyQuery($order_by: [audits_order_by!] = {}) {
  audits(order_by: $order_by) {
    treatment_date
  }
}`
```

The query works but it's behaving as if it didn't get any order_by statement at all.  What is the proper way to pass a javascript variable to this query variable and have it work?

**Comment by tirumaraiselvan** [comment]
A `variables` key needs to passed in the POST body. For e.g. see this: https://graphql.org/graphql-js/graphql-clients/

**Comment by tirumaraiselvan** [comment]
Closing this for now. Please feel free to ask more in our Discord support: https://discord.com/invite/hasura
