### ISSUE TITLE
parsing error response issue on synchronous actions

### ISSUE THREAD

**Issue by Endriyas** [hasura/graphql-engine#6411]
Hello,
I am using Hasura 1.3.3 and loopback 3.

I have been developing graphql API using Hasura and action handler on loopback 3.

I use both the sync and async types of Hasura actions.
When I use the async type action and my action handler remote method in loopback 3 throws an error, I can see the error.
But when I use the sync action, it only says,
```
"errors": [
    {
      "extensions": {
        "path": "$",
        "code": "parse-failed"
      },
      "message": "the key 'message' was not present"
    }
  ]
```

I use the same loopback error object for sync and async actions. For Example, 
```
    let error = new Error();
    error.name = "Failed";
    error.message = "Method not allowed!";
    error.statusCode = 422;
    throw error;

```

**Comment by tirumaraiselvan** [comment]
hi @Endriyas 

I am not able to reproduce this. This is my action handler code:

```
app.post('/', (req, res) => {
    console.log(req.body);
    res.status(422).json({"message": "error", "code": "default-error"});
});
```

The same response gives proper error objects for both sync and async actions.

**Comment by Endriyas** [comment]
Thanks @tirumaraiselvan

I have used your suggestion and rather than throwing errors, I have responded using the default express res value. and it works.

Thanks again.
