### ISSUE TITLE
Getting the raw sql from meta queries

### ISSUE THREAD

**Issue by zcaudate** [hasura/graphql-engine#6414]
I've got a list of meta queries and would like to generate an sql script (so that it can be loaded by postgres without connecting hasura) 

ie... the commands look something like this:

```
[ {
  "type" : "track_table",
  "args" : {
    "schema" : "public",
    "name" : "status_contract"
  }
}, {
  "type" : "set_table_is_enum",
  "args" : {
    "table" : {
      "schema" : "public",
      "name" : "status_contract"
    },
    "is_enum" : false
  }
}, {
  "type" : "track_table",
  "args" : {
    "schema" : "public",
    "name" : "op"
  }
}, {
  "type" : "track_table",
  "args" : {
    "schema" : "public",
    "name" : "entry"
  }
}, {
  "type" : "track_table",
  "args" : {
    "schema" : "public",
    "name" : "currency"
  }
}, {
  "type" : "track_table",
  "args" : {
    "schema" : "public",
    "name" : "region_country"
  }
}, {
  "type" : "create_object_relationship",
  "args" : {
    "table" : "currency",
    "name" : "currency_type",
    "using" : {
      "foreign_key_constraint_on" : "type"
    }
  }
}, {
  "type" : "create_array_relationship",
  "args" : {
    "table" : "currency_type",
    "name" : "currencies",
    "using" : {
      "foreign_key_constraint_on" : {
        "table" : "currency",
        "column" : "type"
      }
    }
  }
}, 
```

Is there a way to be able to do this with hasura?

**Comment by tirumaraiselvan** [comment]
Do you want the SQL script for adding the metadata objects to the hasura catalog (i.e. to avoid using the metadata queries) or do you want SQL script for creating the tables/objects that are specified in the metadata queries?

**Comment by zcaudate** [comment]
I'd like to avoid starting up hasura to create both the pg and hasura schemas. 

If there were a way to precompile the schemas through hasura as an sql file, then I wouldn't need to make the metadata queries.

**Comment by tirumaraiselvan** [comment]
The simplest way is probably to take [pg_dump](https://www.postgresql.org/docs/12/app-pgdump.html) of your schemas alongwith `hdb_catalog` and `hdb_views` schemas from a Hasura intialized database.

**Comment by zcaudate** [comment]
@tirumaraiselvan: I know that's it possible but it'd be great to be able to see how hasura is writing to postgres on each query as opposed to a bulk one.

I mean, technically, it is possible to do a meta query, check the database for the diff and continue but it'll be great if there were some sort of tap for the postgres call for debugging/analysis purposes.

**Comment by tirumaraiselvan** [comment]
@zcaudate You can also turn on logging in Postgres and capture all SQLs that are performed on running a metadata query.

Overall, this is an internal detail (of the metadata query) and something that cannot be figured out without looking into the source code.

**Comment by zcaudate** [comment]
okay that makes sense. thanks for the insight!
