### ISSUE TITLE
Hasura CLI: Error using seeds command

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#6422]
While using `hasura seeds create initial`
I'm getting the following error:
```
time="2021-01-05T19:42:52+05:00" level=fatal msg="cannot find default editor from env: open C:\\Users\\user\\AppData\\Local\\Temp\\*.796371283.sql: The filename, directory name, or volume label syntax is incorrect."
```
I have tried setting the `EDITOR` environment manually as well but still getting the same error. 

For reference cli version is `v1.3.1`

Also there is a typo in the [docs for seed command](https://hasura.io/docs/1.0/graphql/core/hasura-cli/hasura_seeds_create.html#examples) in example it should be `seeds` not `seed`

**Comment by purush7** [comment]
Sorry for the late response @abdullah2993 . The problem isn't due to editor . It's due to a small bug while creating the temporary file. We will fix this soon and thanks for mentioning the typo in docs seeds example and bringing this to our notice .

**Comment by Fabianstelmach** [comment]
For others encountering this issue, this only occurs when the (required?) flag `--from-table` is not used.
