### ISSUE TITLE
cli-ext: inaccurate instructions to build binaries

### ISSUE THREAD

**Issue by jesselve** [hasura/graphql-engine#6426]
The ["Building the binaries"](https://github.com/hasura/graphql-engine/blob/master/cli-ext/README.md#building-the-binaries) section of the README.md states:

> `npm install`
> `npm run package`

This fails, however, with:

 `npm ERR! missing script: package`

since there is no "package" entry in the "scripts" block of the package.json file in this folder.

**Comment by tirumaraiselvan** [comment]
Hi @jesselve 

Judging by this recent issue: https://github.com/hasura/graphql-engine/issues/6433 , it appears you have made some progress in building the binaries (current issue)?

If yes, any kind of PR to update the Readme would be much appreciated!
