### ISSUE TITLE
ARM architecture support

### ISSUE THREAD

**Issue by jesselve** [hasura/graphql-engine#6433]
I have hit only 1 blocking issue with running Hasura on linux/ARM, which is the installation of the "cli-ext" plugin.

- Postgres has an officially-supported ARM version as both binary and as a docker file.

- An ARM64 version of the Hasura GraphQL docker file has already been made available at: <https://hub.docker.com/r/fedormelexin/graphql-engine-arm64>

- The Hasura CLI can be installed on linux/ARM using "go get" per the instructions at <https://github.com/hasura/graphql-engine/tree/master/cli>.  This CLI has then been confirmed to be functional in a linux/ARM environment with the exception of the `hasura metadata` commands as these depend on the "cli-ext" plugin which is not currently available for the linux/ARM platform.

I have been able to build a version of the "cli-ext" plugin for linux/ARM from the source in this repo.   However, I am not then able to "install" this locally-built plugin via `hasura plugin install` since this command seems to be hard-coded to connect to the plugin-index repository at <https://github.com/hasura/cli-plugins-index/tree/master/plugins/cli-ext>.

I have cross-posted [this issue](https://github.com/hasura/cli-plugins-index/issues/55) to the [cli-plugins-index repository](https://github.com/hasura/cli-plugins-index).

In case there is a separate team monitoring issues here, the questions are the same:
1. Am I missing an alternative, supported method to install a plugin which could be used in this case?
2. Would Hasura be open to a pull request to add "official" ARM support - especially since the effort to do this would be so small?

(It occurs to me that I could likely "hi-jack" calls from the Hasura CLI to the plugin-index repo via HOSTS file mapping to a locally-hosted copy of this repo, etc. and possibly thereby install the linux/ARM plugin.  However, given the recent up-surge in ARM devices, I believe that official ARM support would be appreciated by an increasing number of other users.  I'm therefore raising this issue as a first course of action, instead.)

**Comment by pat154** [comment]
Any update or progress on this? I'm on an Macbook with Apple M1 ARM processor. I can get Hasura running with `graphql-engine-arm` but can't run the CLI to develop things locally.

If it's a long way off, can anyone recommend a way I might be able to develop for Hasura on an ARM processor?

**Comment by MrLesk** [comment]
Up. I would also like to be able to download an official arm version with the CLI. Doesn't have to be production proof but would be good on my raspberry pi

**Comment by stigmat4j** [comment]
Any updates?

**Comment by MarcStdt** [comment]
Are there any plans to make this happen?
I would love to use hasura and the cli on my raspberry pi.

**Comment by scriptonist** [comment]
CLI Arm 64 builds were added in https://github.com/hasura/graphql-engine/commit/8a6f3f7e9dbf6f029d7fc8df5e305d8aab918c7a and should be available from the latest releases (>=v2.0.2)

**Comment by yangm97** [comment]
Good, now do it again 😅

**Comment by lumleon** [comment]
wow...starting to use Apple M1 mac mini

**Comment by lumleon** [comment]
@pat154 are you all good to run Hasura in the M1 Mackbook?

**Comment by deathemperor** [comment]
I believe this is for the CLI only.

**Comment by yann-embie** [comment]
Any updates about an official hasura image which supports arm64 and can be used in docker?

**Comment by glenno3891** [comment]
It would be good if this was officially supported. It has been discussed for some time now.

**Comment by morandalex** [comment]
there is a plan to include arm image in near future?

**Comment by MarkNBroadhead** [comment]
Finally! v2.1.0 is being compiled for the ARM64 architecture. Thank you Hasura team!

**Comment by creeefs** [comment]
Yay!!!!

**Comment by glenno3891** [comment]
Thank you so much!!!

**Comment by thenonameguy** [comment]
Please provide the engine binaries as well for releases, for all supported platforms, not just the CLI.

**Comment by kmein** [comment]
Recent tags of [`graphql-engine`](https://hub.docker.com/r/hasura/graphql-engine/tags) on dockerhub feature ARM support.
