### ISSUE TITLE
cli: squashing should clean migration state from state store as well

### ISSUE THREAD

**Issue by Clee681** [hasura/graphql-engine#6434]
Hello 👋 ,

It looks like the "squash" feature did not delete the "squashed migration files" from the `schema_migrations` table.

#### Squash Attempt

```
hasura migrate squash --name "add_store_id_to_orders_items_pk" --from 1609534185173
```

#### `hasura migrate status` Output
```
1609534185173  -                                        Not Present    Present
1609534198662  -                                        Not Present    Present
1609534563940  -                                        Not Present    Present
1609534756643  add_store_id_to_orders_items_pk          Present        Not Present
```

#### Result

You'll notice that the squashed migration was successfully created but the "old" files are still in the `schema_migrations` table.

#### Question

If I wanted to clean this up manually, do I only need to update the `schema_migrations` table? Not sure if there's other state that I need to clean up as well.

Hasura CLI Version: `v1.3.3`

Thanks!

**Comment by scriptonist** [comment]
Yes @Clee681 you are right, after cleaning up the `schema_migrations` table you should be good.
