### ISSUE TITLE
Cannot get Array Relationships in Derived Mutation Actions

### ISSUE THREAD

**Issue by nickwang0808** [hasura/graphql-engine#6435]
First of all, I would like to thank the Hasura team for making something this amazing, and I appreciate any help from you.

So,

I have a One to Many Relationship between **recipe** and **recipe_ingredients**,

This is the working mutation query, a simple add recipe title and add the corresponding ingredients.
![image](https://user-images.githubusercontent.com/63834422/104161134-47374c80-542d-11eb-9695-9afd656eca20.png)

After I derived from it :
![image](https://user-images.githubusercontent.com/63834422/104161209-6afa9280-542d-11eb-858e-91519fc0e0b4.png)

With action relationship from id -> recipe_id
![image](https://user-images.githubusercontent.com/63834422/104161291-97aeaa00-542d-11eb-9d42-71dd9d7d9609.png)

And I simply forward the result from the res my server makes to Hasura back to the derived mutation
![image](https://user-images.githubusercontent.com/63834422/104161568-0c81e400-542e-11eb-84d9-cfb2a01e5cef.png)

as per the doc https://hasura.io/docs/1.0/graphql/core/actions/types/index.html
I can retrieve the scalar types from the mutation(id, title, etc.), however, I cannot retrieve the recipe_ingredients_list array of objects from the action relationship, here is the error code,
![image](https://user-images.githubusercontent.com/63834422/104161758-57036080-542e-11eb-963a-d4458a7cbdb7.png)

I'm using **hasura/graphql-engine:v1.3.3** and **postgres:12** and **TS@4.1.2** with **expressjs@4.17.9**

also, I'm noticing that the codegen for typescript-express has the return statement wrong
![image](https://user-images.githubusercontent.com/63834422/104162192-1bb56180-542f-11eb-8686-538127f339f6.png)

which should actually be `return res.json({...data.insert_recipe_one})`

**Comment by tirumaraiselvan** [comment]
Seems like the error you are getting is because of this: https://github.com/hasura/graphql-engine/issues/5731

For your example though, there is a simpler solution! Since you are creating an action relationship called `recipe_ingredient_list`, you need not "derive" that field at all. This field you get automatically.

**Comment by nickwang0808** [comment]
> Seems like the error you are getting is because of this: #5731
> 
> For your example though, there is a simpler solution! Since you are creating an action relationship called `recipe_ingredient_list`, you need not "derive" that field at all. This field you get automatically.

thank you for your quick response, 

after some further investigation, I have found the issue.

so in the parent mutation, you cannot return the nested result even if you specify the relationship in the derived action. to actually query for the relationship you specified, you just ask for it in the derived mutation and it's handled outside of your REST endpoint. 

I think the doc needs some update on this particular subject because intuitively, you'd think you can just return the nested object inside the REST API **after you set up the relationship**.

to further explain what I meant
first you setup your parent mutation like so, but remove the 2nd level object or array
![image](https://user-images.githubusercontent.com/63834422/104282017-5d0a4780-54e9-11eb-841c-e6798f67093c.png)


then you setup your derived mutation following the doc, now at this stage you only going to receive the 1st level data, because you only queried for that inside your REST API,  to fix that, we declare a relationship for the derived mutation,
![image](https://user-images.githubusercontent.com/63834422/104281991-55e33980-54e9-11eb-8365-e886fcc8a8dc.png)


now next all you have to do is to specify the returned 2nd level object or array in the derived mutation and Hasura will handle the rest for you, **DO NOT** return 2nd level object or array in your REST API.
![image](https://user-images.githubusercontent.com/63834422/104282381-ede12300-54e9-11eb-8128-a0f6ec9fce37.png)


good luck!
