### ISSUE TITLE
[Feature-request] Enable cross-table column comparisons in permission rules

### ISSUE THREAD

**Issue by tillspeicher** [hasura/graphql-engine#6436]
I really like Hasura so far, however, I have a lot of trouble defining permission rules for the following use-case:

I am building a chat app with messages which are sent to channels and users who are members of those channels. Users can join and leave channels and I only want messages to be visible to channel members who were in a channel when a message was sent.
I.e. suppose message A is sent to a channel, user U joins the channel, message B is sent to the channel, user U leaves the channel, message C is sent to the channel. In this case I want only message B to be visible to U, not A and C.

The table setup in this case is the following:
```
user(id integer,...)
channel(id integer,...)
message(id integer, channel_id integer, sent_at timestamp,...)
user_channel_membership(user_id integer, channel_id integer, start_time timestamp, end_time timestamp,...)
```

Now I would like to define select permission rules on the `message` table that limit visibility as described above. But there I run into problems because doing this requires me to compare the `sent_at` value of the `message` with the `start_time` and `end_time` values of the `user_channel_membership` table, which doesn't seem to be possible.
I.e. I would like to be able to write the following permission rules on the `message` table:

```
{"channel": {
    "memberships": {"_and": [
        "user_id": {"_eq": "X-Hasura-User-Id"},
        "start_time": {"_lte": $message.sent_at},  # <- not possible
        "end_time": {"_gt": $message.sent_at},    # <- not possible
    ]}
}}
```
where `channel` is an object-relationship from `message` to `channel` and `memberships` is an array-relationship from `channel` to `user_channel_membership`.

A solution I tried is to extend the schema with a `visible_message` SQL-function that computes this check and disable select permissions on the `message` table, but that doesn't work either because SQL-functions inherit permissions from the underlying table. So the function either cannot access the `message` table or I have to make the rules for the `message` table too permissive which negates the point of using the SQL-function to restrict visibility.
Even if this would work it would come with a lot of overhead because all relationships referencing `visible_message` would have to be defined as computed fields which seem to be restricted, e.g. I was not able to use a computed field in an `order_by` argument.
I also want to define similar visibility rules for `user_channel_membership`.

The only workaround I can see at this point is to make the authentication backend issue separate per-channel permissions (as JWTs in my case) that somehow include the membership interval(s), e.g. as `x-hasura-memberhip-interval`, which I could use in comparisons directly. But being able to define permissions using table values directly would be much preferred.

It would be really useful to be able to either make cross-table column comparisons or to use SQL-functions/computed fields in permission rules to compute these checks. This problem seriously impacts the usability of Hasura for me right now which I otherwise really like for making backend development very efficient.

This request is related to #5293, #6076 and  #5646.

**Comment by tirumaraiselvan** [comment]
Thanks for detailing the use-case!

We are discussing this feature here: https://github.com/hasura/graphql-engine/issues/3459

The current workaround is probably to create a view which is a join of `user_channel_membership` with `message`, let's call it `user_channel_membership_with_messages` and define `memberships_msgs` as an array-relationship from `channel` to user_channel_membership_with_messages. Then the permission can be defined like:

```
{"channel": {
    "memberships_msgs": {"_and": [
        "user_id": {"_eq": "X-Hasura-User-Id"},
        "start_time": {"_clte": sent_at}, # uses _clte
        "end_time": {"_cgt": sent_at},    # uses _cgt
    ]}
}}
```

**Comment by tillspeicher** [comment]
Thanks a lot! Your workaround solved the problem for me now.

It's good to see that this feature is on the roadmap. Being able to make cross-table comparisons directly would be very useful.

**Comment by tirumaraiselvan** [comment]
@tillspeicher Absolutely! I am going to close this issue now. Pls do feel free to comment on #3459 if you have more thoughts.
