### ISSUE TITLE
Missing custom response headers, how to paginate response from action?

### ISSUE THREAD

**Issue by dbarrionuevo** [hasura/graphql-engine#6440]
Hi everyone,

I'm using Hasura actions against a handler in my Rails API. The API is providing pagination metadata in the **response headers**, but Hasura is ignoring those and always returns the same headers (Date, Content-Type, Transfer-Encoding, Connection, Server, x-request-id, Content-Encoding).

If I hit this same endpoint directly with a POST, I can clearly see my custom response headers with the metadata I need.

I there any workaround for this or any other way to send pagination metadata in the response from the handler?

Thanks so much.

**Comment by tirumaraiselvan** [comment]
Just to be clear, you want to send response headers in your action handler and expect it to forward to the client (as response header of the graphql request) ?

**Comment by dbarrionuevo** [comment]
That's correct! I think header forwarding would be a useful feature. Could you think of another way to add pagination metadata otherwise?

**Comment by tirumaraiselvan** [comment]
I am closing this in favour of https://github.com/hasura/graphql-engine/issues/6476 

Pls do add a comment about your use-case there if possible. I am not sure what is pagination metadata header, but is it possible for it to come as the response body of the action handler?
