### ISSUE TITLE
Suggestion: use of aggregates in permissions

### ISSUE THREAD

**Issue by AnsonT** [hasura/graphql-engine#6443]
I would like to give any authenticated user permission to insert the first item in a related collection. If the collection is already populated then the permission to insert will be based on user role. There isn't a way within the permissions tree to determine whether the related collection is empty.

Perhaps something like this:

```
{
   "collection_aggregate": {
     "aggregate": {
       "count": {
         "_eq": 0
       }
     }
   }
}
```

**Comment by ayuryshev** [comment]
You can achieve it with check constraint function on Postgresql level.

**Comment by tirumaraiselvan** [comment]
Closing in favour of https://github.com/hasura/graphql-engine/issues/3949
