### ISSUE TITLE
[Feature Request] Ability to specify different refetch interval by subscription.

### ISSUE THREAD

**Issue by mathieutu** [hasura/graphql-engine#6452]
Hi folks.

Thanks for this amazing product.

As specified on [the subscription documentation](https://hasura.io/docs/1.0/graphql/core/subscriptions/index.html), hasura subscription are in fact live queries, refetched automatically following an interval (1s by default) that we can set globally with `HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_REFETCH_INTERVAL` env var.

It could be really cool to be able to specify that interval for each subscription. 

For example, for a messaging app, we can have a interval of 0.5s for a messages subscription, because I want it all to come quickly, but we would prefer an interval of 3s for statuses, as it's far less important, and even an interval of 10s for new users or groups because it's a cool thing to have them automatically via ws without the need to refetch them, but no need to see them in real time.

The main goal is to be able to rely more on subscription, but without increasing the performance need. Executing Xk queries each 0.5s will have a certain impact on database usage, without the real need of that.

What are you thoughts about that?

Thanks.
Mathieu.

**Comment by tirumaraiselvan** [comment]
Closing in favour of https://github.com/hasura/graphql-engine/issues/5766
