### ISSUE TITLE
computed fields - hasura views

### ISSUE THREAD

**Issue by tanmaypatil** [hasura/graphql-engine#6457]
Currently computed fields are only available for hasura table objects .

- Need support of computed fields in views also 
- computed field can hook to a sql function which can have access to hasura session variables and can used to have a custom logic from application security point of view.

@tirumaraiselvan

**Comment by rikinsk** [comment]
@tanmaypatil this is actually supported by the server but not available on the console yet. A [PR](https://github.com/hasura/graphql-engine/pull/6174) for this has been merged but hasnt made it to a release yet. we will make a console hotfix release in a day or 2 with this change. 

In the meanwhile you can use the [metadata API](https://hasura.io/docs/1.0/graphql/core/api-reference/schema-metadata-api/computed-field.html#add-computed-field) directly to add a computed field to a view

**Comment by devakrishna33** [comment]
I have a similar requirement, is this change released?
