### ISSUE TITLE
Found a bug in version v1.3.4-beta.2 - error when updating fields with type Integer set to null by default

### ISSUE THREAD

**Issue by dodanex** [hasura/graphql-engine#6459]
If you have a field set as Integer and nullable set to true by default, 
On inserting a new row it works fine but when you update the field with "null" an error ocures:

`expected a 32 bit integer for type "Int", but fund a string`

This is happening because the "null" is interpreted as a string.

Example: lets say I create a table called users, with 3 fileds: 
1. id - integer, primary key, unique, default: nextval('products_id_seq'::regclass)
2. name - text, nullable
3. image_id - integer, nullable

When you insert a new row filling only the "name", ("id" is auto incremented), and "image_id" is left blank or set to a number, the insertion is working fine and the row is saved.

But if you now want to update this row and set the "image_id" to "null", you get that error.

**Comment by tirumaraiselvan** [comment]
@dodanex What's the operation that you are running? Are you inserting from the `Data` page or Graphql API?

I am not able to reproduce this using the following operation (i.e. updates the `image_id` value to null):

```
mutation {
  update_users_by_pk(pk_columns: {id: 3}, _set: {image_id: null}) {
    id
    image_id
    name
  }
}
```

**Comment by dodanex** [comment]
Hello, thanks for the reply.
I am inserting using Graphql API, in version v1.3.3 there was no error, just worked fine, but after updating to 1.3.4-beta.2 this error occurred.
I will make more tests to see what's the problem.

**Comment by tirumaraiselvan** [comment]
Posting the exact graphql API would help!

**Comment by tirumaraiselvan** [comment]
Any updates here @dodanex  ?

**Comment by dodanex** [comment]
Sorry for the delay, I cannot reproduce and test it anymore because I rolled back to the stable version v.1.3.3 and the error is gone. Will close this issue.
