### ISSUE TITLE
Migrations aren't applied on Kubernetes when mounted using ConfigMaps

### ISSUE THREAD

**Issue by iosifnicolae2** [hasura/graphql-engine#6463]
### Expected behaviour
When the `/hasura-migrations` directory is mounted from a ConfigMap, the Docker `cli-migrations-v2` image applies the migrations automatically.

### Problem
 If you're mounting `/migrations` directory from a ConfigMap, the migrations are not discovered by `hasura-cli` because Kubernetes mount files into the migrations directory using symlinks.

### Solution
1. Mount your migrations/metadata in a separate directory (`/my-migrations`, `/my-metadata`).
2. Create `docker-compose.yml` file with the following content:
```bash
#!/bin/sh
set -e

cp -Lr /my-migrations/ /hasura-migrations
cp -Lr /my-metadata/ /hasura-metadata

. /bin/docker-entrypoint.sh
exec "$@"
```
3. Create a `Dockerfile` with the following content:
```dockerfile
FROM hasura/graphql-engine:latest.cli-migrations-v2

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["graphql-engine", "serve"]
```

**Comment by tirumaraiselvan** [comment]
Could you also paste any errors that you see in the logs when you mount it via ConfigMaps? (I am trying to understand what exactly is the issue with symlinks)

**Comment by iosifnicolae2** [comment]
I don't have the logs anymore, but Hasura did not recognized any migration while they have been mounted directly to `/hasura-migrations`
