### ISSUE TITLE
When the name of the field that holds the foreign key is edited using the console, the name of the foreign key is not updated automatically

### ISSUE THREAD

**Issue by gloredo** [hasura/graphql-engine#6464]
Consider two tables: `user` and `user_details` with a 1:1 relationship where the `user` table has the `user_details_id` field that holds the reference to the `user_details` table.

When the foreign key is created in the user table the automatically generated name is `user_user_details_id_fkey`, but if the `user_details_id` field name is changed to `user_info_id` the foreign key name is not updated to `user_user_info_id_fkey`.

You can fix this manually by editing and saving the foreign key, in this case the name is updated to `user_user_info_id_fkey`.

**Comment by gloredo** [comment]
I noticed that the same behavior occurs with unique keys.

**Comment by tirumaraiselvan** [comment]
The SQL that is executed when you change a column name is `alter table "public"."anothertable" rename column "id1" to "id2"`, this doesn't change the name of the foreign key constraint. This happens at the Postgres layer itself.

**Comment by tirumaraiselvan** [comment]
I am going to close this as the result is as expected.
