### ISSUE TITLE
Apollo Client in VSCode / schema introspection fails

### ISSUE THREAD

**Issue by haf** [hasura/graphql-engine#6466]
When using apollo.config.js in VSCode, the ApolloClient tries to introspect the graphql endpoint.

This causes some issues:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/193115/105155987-8f303080-5b0b-11eb-8d08-992bdd7b7399.png">

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/193115/105155962-88092280-5b0b-11eb-88d1-3e86e2e93713.png">

...to list a few. It's a couple of pages of warnings and errors.

Is it possible to have the server declare all its types and directives?

**Comment by GavinRay97** [comment]
Hey @haf 

It's a little bit unintuitive to completely configure the `apollo.config.js` right.
Let me post my boilerplate example which I've used successfully across my Hasura projects, maybe that could help:

```js
// apollo.config.js
module.exports = {
  client: {
    service: {
      name: 'Hasura',
      url: 'http://localhost:8080/v1/graphql',
      headers: {
        'X-Hasura-Admin-Secret': 'my-secret',
      },
    },
    // Files processed by the extension. Change this to suit your preferences for JS/TS and framework.
    includes: ['src/**/*.vue', 'src/**/*.ts', 'src/**/*.tsx', 'src/**/*.graphql'],
    // Files excluded -- here contains an example Typescript SDK generated from Hasura types and some queries
    excludes: ['src/generatedHasuraSDK.ts'],
  },
}
```

Can you try something like this and report back on whether you have any luck?

**Comment by haf** [comment]
Hi, yes this is what I have, except the includes. This is the issue.

**Comment by tirumaraiselvan** [comment]
@haf Is it working now?

**Comment by haf** [comment]
@tirumaraiselvan No? Nothing has changed?

**Comment by haf** [comment]
Any update? :)

**Comment by haf** [comment]
This is an error in how the VSCode plugin works; see https://github.com/apollographql/apollo-tooling/issues/801#issuecomment-914111560 for my resolution
