### ISSUE TITLE
invalid input syntax for type money: "£120.00"

### ISSUE THREAD

**Issue by subodh022** [hasura/graphql-engine#6482]
I am trying to insert a value (£120.00) to a field of type "money", but it throws this errors - 
**invalid input syntax for type money: "£120.00"**

Though it works with $ symbol.

**Comment by wwwdepot** [comment]
You need to set `LC_MONETARY` to your locale. https://stackoverflow.com/a/54065313

**Comment by subodh022** [comment]
@wwwdepot Thanks, that solved it.
