### ISSUE TITLE
Hasura returns content encoded in gzip instead of brotli

### ISSUE THREAD

**Issue by jtanneh** [hasura/graphql-engine#6484]
We're passing "Accept-Encoding: gzip, deflate, br" in our request headers, but hasura is returning gzip instead of brotli in the response. According to this post, hasura should default to brotli if both are passed: [https://github.com/hasura/graphql-engine/pull/2751](https://github.com/hasura/graphql-engine/pull/2751).

Hasura server version 1.3.1

<img width="335" alt="Screen Shot 2021-01-22 at 12 58 28 PM" src="https://user-images.githubusercontent.com/73910284/105753287-0d2a7800-5f0e-11eb-9967-45daf6946740.png">

**Comment by praveenweb** [comment]
@jtanneh - Brotli was removed in a subsequent PR https://github.com/hasura/graphql-engine/pull/2967 due to licensing issue.

**Comment by jtanneh** [comment]
@praveenweb - Thanks!
