### ISSUE TITLE
Remote schema migrations are not applied when using v1.3.4-beta.2.cli-migrations-v2 image

### ISSUE THREAD

**Issue by pimsomeday** [hasura/graphql-engine#6487]
I'm trying to auto apply my remote schema migrations, however they are not applied. I'm using this image: hasura/graphql-engine:v1.3.4-beta.2.cli-migrations-v2.

I see this in the log file:

```
graphql-engine_1  | {"level":"info","msg":"Applying migrations...","time":"2021-01-26T12:40:46Z"}
graphql-engine_1  | {"level":"info","msg":"nothing to apply","time":"2021-01-26T12:40:46Z"}
```

Checking the migration status `hasura migrate status` shows under DATABASE STATUS: not present.

Steps to reproduce:

1. Start Hasura container
2. Open console: `hasura console`
3. Add remote schemas to write the migration files
4. Stop Hasura container
5. Drop database
6. Start Hasura
7. Remote Schemas are still empty

 - I also tried to add the remote schemas and reset the migrations like mentioned [here](https://hasura.io/blog/resetting-hasura-migrations/), but without any luck.
 - Adding a table (so `tables: []` in the up.yaml migration file wasn't empty) resulted in a new table, however the remote schema(s) were still not added.

Any thoughts?

**Comment by scriptonist** [comment]
Hey, @pimsomeday information regarding the remote schemas are stored in Hasura metadata (https://hasura.io/docs/1.0/graphql/core/migrations/manage-metadata.html). Can you confirm that you mounted the project metadata directory to the container as mentioned here: https://hasura.io/docs/1.0/graphql/core/migrations/advanced/auto-apply-migrations.html#applying-only-metadata. If not can you try mounting that? 

If yes, can check your log file for lines giving information about applying metadata?

**Comment by pimsomeday** [comment]
Hi @scriptonist, it says metadata is applied
```
graphql-engine_1  | {"level":"info","msg":"Applying metadata...","time":"2021-01-27T09:59:39Z"}
graphql-engine_1  | {"level":"info","msg":"Metadata applied","time":"2021-01-27T09:59:40Z"}
```

I also verified if the migrations/metadata exist in the running container using these commands: 
```
docker exec -it [container id] ls -la tmp/hasura-project/migrations
docker exec -it [container id] ls -la hasura-metadata
docker exec -it [container id] ls -la hasura-migrations

so they are mounted..

**Comment by tirumaraiselvan** [comment]
Could you share the `remote_schemas.yaml` file that you have in `hasura-metadata` folder?

**Comment by pimsomeday** [comment]
it's only containing an empty array
```
[]

**Comment by tirumaraiselvan** [comment]
@pimsomeday This means the remote schema was not even added to the `remote_schemas.yaml` file. Did you start the Hasura console via the CLI to add the remote schema?

(I just added a remote schema through the console CLI in v1.3.4-beta.2 and it successfully adds the remote schema to `remote_schemas.yaml`)

**Comment by pimsomeday** [comment]
@tirumaraiselvan yes, I did start the console using the CLI. 

- When I add the remote schema (using the console started via cli) this file: ./metadata/remote_schemas.yaml remains an empty array.
- When I add the remote schema (using the console started via cli) and run: `hasura metadata export`, the metadata file(s) are not updated

- However, when I open the console and go to metadata-actions and hit the export metadata button, the .json file contains the remote schemas. When i add them manually to ./metadata/remote_schemas.yaml everything works as expected..

**Comment by tirumaraiselvan** [comment]
@pimsomeday I am not able to reproduce the first scenario. Could you check the config of your hasura project i.e. `config.yaml` ?

**Comment by pimsomeday** [comment]
the config.yaml my project root only contains: 
```
admin_secret: ${SOME_VALUE}
```
running `hasura version` returns:
```
INFO hasura cli                                    version=v1.3.4-beta.2
INFO hasura graphql engine                         endpoint="http://localhost:8080" version=v1.3.4-beta.2

**Comment by scriptonist** [comment]
@pimsomeday appologies for the delayed response. I think your config file is not setup to use config v2. Can you edit your `config.yaml` to have the following and retry.

```
version: 2
endpoint: http://localhost:8080
admin_secret: <your admin secret>
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000

```

**Comment by pimsomeday** [comment]
Hi @scriptonist, this fixes the problem. Thanks 👍 !
