### ISSUE TITLE
Postgres trigger produces "database query error"

### ISSUE THREAD

**Issue by giulianok** [hasura/graphql-engine#6489]
I followed this documentation https://hasura.io/docs/1.0/graphql/core/guides/postgres/triggers.html and getting

```
{errors: [{,…}]}
errors: [{,…}]
0: {,…}
extensions: {path: "$.selectionSet.insert_class_one.args.object[0].dates_times.data", code: "unexpected"}
code: "unexpected"
path: "$.selectionSet.insert_class_one.args.object[0].dates_times.data"
message: "database query error"
```

**Comment by tirumaraiselvan** [comment]
Can you check Postgres logs for the actual error (mostly likely generated by the trigger function)?

**Comment by giulianok** [comment]
I can see the error in the postgres logs

```
2021-01-27 01:38:49.120 UTC [3253] ERROR: There is a conflict with one of the selected dates and times.
2021-01-27 01:38:49.120 UTC [3253] CONTEXT: PL/pgSQL function check_class_date_and_time() line 14 at RAISE
```

The problem is that the user sees "database query error", how can I tell the user what the error was about?

**Comment by tirumaraiselvan** [comment]
This is not possible at the moment. See the original feature request here: https://github.com/hasura/graphql-engine/issues/2599

We don't forward all exceptions to client because it might leak internal details.

**Comment by tirumaraiselvan** [comment]
I am closing this in favour of #2599

**Comment by JavaJamie** [comment]
Getting this error too after creating a trigger. Literally no information other than "database query error"
