### ISSUE TITLE
Can I clean unneeded definitions from the auto-generated schema?

### ISSUE THREAD

**Issue by zynyz** [hasura/graphql-engine#6490]
Is it possible to go through and remove unused types and methods from the auto-generated GQL schema? We're never going to use more than 10% (if that) of them, and they make it really hard to navigate to find the thing you're looking for. For instance, we have a bunch of enum tables, which all get the full complement of inserts, mutations, mutation responses, aggregates, and comparison/sorting expressions, none of which will ever get used.

I'm getting a huge amount of pushback from the frontend devs about the "noise level" (their term) making their lives miserable when building queries in Graphiql. There are also concerns with exposing all this complexity to outside users. I would also like people to yell at me less.

Is there some way to edit the generated schema down to the essentials and pass that back into Hasura? I know that I can use the GUI to untrack tables or columns, but that's not a practical solution for us.

**Comment by tirumaraiselvan** [comment]
Does adding a role and permissions on tables not  help in reducing the schema that is exposed? Or is that not sufficient for your case?

**Comment by zynyz** [comment]
Kinda sorta? It's a tedious process to go through in the UI and there are a lot of tables. I can do it through the API, but it seems that it's a separate REST call for each action on each table. I'd like to do it by editing metadata.yaml, but again, that's tedious and error-prone.

We're going to try and see if roles and perms will work for us, but I would really love to have a cleaner way to do this.

**Comment by zynyz** [comment]
Roles and permissions work great, thanks! Now that I know a little more about the metadata format I'm comfortable scripting it.

Thanks for all the help. This is my first Hasura project and it's a bit overwhelming.

**Comment by tirumaraiselvan** [comment]
@zynyz You can also use the Metadata SDK to help you in scripting: https://github.com/hasura/graphql-engine/tree/master/contrib/metadata-types

**Comment by zynyz** [comment]
@tirumaraiselvan : The metadata SDK looks really useful, thank you. Is there a way to use it without Typescript and all? 

For now, I just need to write a script to add/remove permissions on various tables for specific users, just to simplify their views in Graphiql. Eventually this will be more sophisticated and extend to managing all permissions and setting up different user levels, but that's further down the road.
