### ISSUE TITLE
GraphQL server from master build fails to start on fresh RDS instance after catalog migration

### ISSUE THREAD

**Issue by thenonameguy** [hasura/graphql-engine#6493]
# Scenario

1. Download and `docker load -i ` [the container image from the latest master build](https://app.circleci.com/pipelines/github/hasura/graphql-engine/16593/workflows/d2ab3ab0-82db-4028-87b8-337de003bb21/jobs/213283/artifacts)
2. Create RDS t2.micro 12.4 Postgres instance
3. Run `docker-compose up` setup pointed at RDS with image from step 1, using the default postgres (superuser) on the default database, similar to this section: https://github.com/hasura/graphql-engine/blob/master/install-manifests/docker-compose-https/docker-compose.yaml#L10-L23

# Expectation
The Hasura server starts, with hdb_catalog schema migrated and empty metadata. Similar to the `latest` tagged Docker Hub graphql-engine image.

# Result
- `hdb_catalog` schema gets created and `hdb_version` and `hdb_metadata` tables get populated with correct looking records, as expected.
- based on the `debug` log level enabled logs, the process within the container hangs after:
```
{"type":"startup","timestamp":"2021-01-27T17:05:52.166+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@the.rds.host.:5432/defaultdb"}}}
{"type":"startup","timestamp":"2021-01-27T17:05:52.166+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 25","instance_id":"fac0c780-8abf-431b-a9b6-161f33cde442","message":"listener thread started"}}}
```
- Eventually the process exits with either exit code 1 or 137.

# Reason for needing to use a non-official build
We are using the un-released volatile mutation stored procedure functionality which is not yet available in any official release in our application to enable a completely backend-free deployment.

**Comment by tirumaraiselvan** [comment]
Hi @thenonameguy We just release `v1.4.0-alpha.1` which includes volatile functions support. Do try it out!

**Comment by tirumaraiselvan** [comment]
Can we close this since `v1.4.0-alpha.1` is released?

**Comment by thenonameguy** [comment]
@tirumaraiselvan yes it works with that version! Although until #6503 is fixed it is not fully usable for us. Eagerly waiting for `alpha.2` :)

Closing as it seems this will be fixed the next versions.
