### ISSUE TITLE
Feature Request: Computed Field functions accept `anyelement`

### ISSUE THREAD

**Issue by LydiaF** [hasura/graphql-engine#6494]
Dear Hasura,

I am using Postgres' inheritance feature and I would like to write one function that could be used as a computed field for all of the child tables. At the moment this is not possible as the table argument must be the same as the table which the computed field is attached to.

I was looking at https://www.postgresql.org/docs/9.3/datatype-pseudo.html and was wondering: if hasura allowed computed field functions to accept `anyelement`, would that solve this issue?

Thanks!

Lydia

**Comment by tirumaraiselvan** [comment]
Closing this in favour of https://github.com/hasura/graphql-engine/issues/6175
