### ISSUE TITLE
Header value templating from env i.e. {{HEADER_VALUE_FROM_ENV}}

### ISSUE THREAD

**Issue by tanmaypatil** [hasura/graphql-engine#6497]
When remote schema is installed on hasura . A introspection query is fired onto the remote graphql server . Introspection api is normally protected by a secret . In our case , it is x-shared-secret  . 

Issue is , hasura does not allow a environment variable inside header value . which means it can be hardcoded only 
variable | value 
--| --
GraphQL Server URL | {{QUEST_SERVER_URL}}
Headers |  
x-shared-secret | 6c3d57fe-cb79-46d0-945d-c2f8e30120c8

@tirumaraiselvan

**Comment by tirumaraiselvan** [comment]
You can change the type of header to `From ENV` and give an environment directly like `QUEST_SERVER_URL`.

I am changing this to feature request  to support header value templating in Header configuration.

**Comment by manasag** [comment]
This is now supported in v2.29. One can add add env vars in headers via templating. e.g. `header-{{HEADER_FROM_ENV}}`. See this [commit](https://github.com/hasura/graphql-engine/commit/f2fe9cfe3bc8ff1817d4fedf802a61dfd53a2e8e).

**Comment by marionschleifer** [comment]
Hey folks, we'll give a quick update on this in our community call this Thursday, 27th July at 9am PT, along with many other exciting community updates 🎉  Sign up [here](https://hasura.io/community/community-call/) if you're interested.
