### ISSUE TITLE
v1.3.0 "serve" command for migration fails on AWS RDS Postgres 12.4 with Segmentation Fault

### ISSUE THREAD

**Issue by alextraul** [hasura/graphql-engine#6507]
The environment is Kubernetes/Docker, but the container is running as root to try to avoid non-root issues which seem possible with 1.3.0.

Connection/networking seems fine, as when presented with a database inside the RDS instance which does not yet exist, the `serve` command correctly shows a descriptive error.  When I use either the `postgres` database inside the AWS RDS instance, or a brand new DB inside the instance created and left empty, the graphql-engine serve command fails with a segfault and no other logging (log level set to debug):

```
{"type":"startup","timestamp":"","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@myrds:5432/newdb"}}}
Segmentation fault (core dumped)
```

The exact same environment/container, when pointed at a non RDS postgres works as normal. I have yet to try different PG versions, however.

**Comment by tirumaraiselvan** [comment]
Hey there

Could you try using v1.3.3? We had a seg fault issue (with our pg client) which was fixed in this.

**Comment by tirumaraiselvan** [comment]
I am going to close this, pls reopen if you have this problem with v1.3.3 or later versions.
