### ISSUE TITLE
MacBook M1: crash in QEMU

### ISSUE THREAD

**Issue by rendervis** [hasura/graphql-engine#6511]
When running Hasura in a Docker container and POST:ing to it, you get a crash in QEMU.

`QEMU  uncaught target signal 4 (Illegal instruction)`

There are no further outputs.

## Versions

- hardware: Apple M1, 2020
- macOS: Big Sur Version 11.1
- hasura container version: v1.3.3

**Comment by rossng** [comment]
I have a similar issue. When running the `hasura/graphql-engine:v1.3.4-beta.3.cli-migrations-v2` image (I also tried with `latest`) under Docker Compose, I get the following messages while the container continuously crashes.

```
{"timestamp":"2021-02-16T01:47:23.000+0000","level":"info","type":"startup","detail":{"kind":"installing cli-ext plugin","info":""}}

qemu: uncaught target signal 11 (Segmentation fault) - core dumped

Segmentation fault
```

**Comment by sajidnaseem** [comment]
I have a similar issue 
Segmentation fault
hardware: Apple M1, 2020
macOS: Big Sur Version 11.1
hasura container version: v1.3.4-beta

**Comment by prawee** [comment]
still same issue guy

**Comment by punkratz312** [comment]
please fix this, its a real show stopper....

**Comment by rossng** [comment]
I'm using the [fedormelexin/graphql-engine-arm64](https://hub.docker.com/r/fedormelexin/graphql-engine-arm64) image now. It seems to work fine - but an official solution would be very nice!

**Comment by punkratz312** [comment]
@rossng thanks for the support. i have updated the image, it seems to work on CI but still not on the apple m1 machine.

**Comment by revelaustris** [comment]
Facing the same issue still here.

**Comment by tirumaraiselvan** [comment]
Tackling this here: https://github.com/hasura/graphql-engine/issues/6337

**Comment by matiasmir** [comment]
@SamirTalwar Thanks Samir!
For anyone following the getting started guide you have to specify the platform in the docker-compose
```
graphql-engine:
    image: hasura/graphql-engine:v2.36.0
    platform: linux/arm64
    ...
```
