### ISSUE TITLE
Break up tables.yml in individual files by table

### ISSUE THREAD

**Issue by adamrneary** [hasura/graphql-engine#6512]
We are having continual issues with merge conflicts on large refactors to our schema as a result of a single tables.yml file. We also have large diffs on a single file that are collapsed, and the diff is hard to review because it's not always clear which table is being edited.

All of this would be made easier if rather than 1 file called `/metadata/tables.yml`, we instead had a folder with files called `/metadata/tables/[tablename].yml`. Then it would be easy to see which tables are being created/updated/removed, and permissions would be a lot simpler!

**Comment by scriptonist** [comment]
@adamrneary with the new changes which has landed in the latest `alphas` in the form for config v3  should address this.

https://hasura.io/docs/latest/graphql/core/migrations/upgrade-v3.html
