### ISSUE TITLE
Raw SQL functions for computed fields returns error if table fields are writen in camelcase, in v1.3.3.cloud3

### ISSUE THREAD

**Issue by dodanex** [hasura/graphql-engine#6520]
Hello, 
I found a bug in v1.3.3.cloud3, I dont know if this will be fixed in v1.3.4 so I just wanted to report it.

There is an error when you create a function in Raw SQL to be used in a computed field.

Steps to reproduce: 
You have 2 or more tables (the name of tables and fields does not matter): 
`articles ` with fields: `id, title, userId`; 
`users ` with fields: `id, firstName, lastName`;

Create a Raw SQL function `get_user_full_name ` to use it in computed field named "user_full_name" inside "articles" to get the user full name from table users by "userId" field.

`
CREATE OR REPLACE FUNCTION public.get_user_full_name(article_row article)
 RETURNS text
 LANGUAGE sql
 STABLE
AS $function$
  SELECT firstName || ' ' || lastName
  FROM users
  WHERE id = article_row.userId
$function$
`
So when you run the SQL function you get an error saying `firstname, lastname, userid ` does not exist. This is because it has transformed them form camel case to lower case.

You can resolve this problem if you write all your table fields with lowercase or/and underscore, But if you have multiple fields writen in camel case in multiple tables, and you also use those fields inside your react/vue application, or multiple applications, then you have a problem because you have to rename them everywhere.

Happy to help.

**Comment by tirumaraiselvan** [comment]
> CREATE OR REPLACE FUNCTION public.get_user_full_name(article_row article) RETURNS text LANGUAGE sql STABLE AS $function$ SELECT firstName || ' ' || lastName FROM users WHERE id = article_row.userId $function$

Postgres automatically lowercases identifiers if they are not explicitly quoted. So try changing to :

```
CREATE OR REPLACE FUNCTION public.get_user_full_name(article_row article) RETURNS text LANGUAGE sql STABLE AS $function$ SELECT "firstName" || ' ' || "lastName" FROM users WHERE id = article_row."userId" $function$
```

**Comment by dodanex** [comment]
Thank you. 
I think this must be explained in the error itself so the user can quick fix it and also in the hasura docs because they are lacking multiple scenarios and examples.
Will close the issue.
