### ISSUE TITLE
1.4.0-alpha.1 - GraphiQL clears request after page refresh

### ISSUE THREAD

**Issue by mm-io** [hasura/graphql-engine#6521]
**Steps to Reproduce**
- Track table
- Create request using GraphiQL
- Browser reqfresh
- Request has been cleared from GraphiQL working area

![2021-02-04 15 38 27](https://user-images.githubusercontent.com/1396255/106952858-aa9c5d80-66ff-11eb-93d9-38044dba357f.gif)

**Comment by beerose** [comment]
Fixed in https://github.com/hasura/graphql-engine-mono/pull/493
