### ISSUE TITLE
1.4.0-alpha.1 - 'Table does not exist' message from data explorer on creating new view - requires metadata reload

### ISSUE THREAD

**Issue by mm-io** [hasura/graphql-engine#6523]
**Steps to Reproduce**
- Created a table with 1 row of data
- Created sample view and tracked from SQL runner:
```sql
create view new_view as
select * 
from public.user
```
- Went to new_view in data explorer, received error

_Went to settings and reloaded metadata to resolve_

**Metadata**
https://drive.google.com/file/d/1XQ54iCye7Q57W0wz6pGRkLXxzqu8bb_o/view?usp=sharing

![2021-02-04 15 14 28](https://user-images.githubusercontent.com/1396255/106953702-b0df0980-6700-11eb-8e2c-b5a5af766aa9.gif)

**Comment by beerose** [comment]
Fixed via https://github.com/hasura/graphql-engine-mono/pull/605
