### ISSUE TITLE
CLI Install Script Guesses wrong architecture leading to 404 on ARM (Apple Silicone/M1)

### ISSUE THREAD

**Issue by motleydev** [hasura/graphql-engine#6526]
Trying to install the CLI script leads to a 404. The install script tries to guess which architecture to use and ends up looking for an `amd_386` release which does not exist.

Two possible paths forward:
1. Handle the ARM architecture (maybe it's already compliant?) and patch the logic handler in the install script.
2. Return users to the x_86 architecture since Rosetta should be able to handle the runtime.

**Comment by tirumaraiselvan** [comment]
Tackling this here: https://github.com/hasura/graphql-engine/issues/6337
