### ISSUE TITLE
Hasura using massive amounts of memory when [schema changed] or [run introspection]

### ISSUE THREAD

**Issue by xiaoyu-tamu** [hasura/graphql-engine#6530]
![image](https://user-images.githubusercontent.com/33362998/107137449-5b5a5680-68d2-11eb-9ad0-57cac08bc2ac.png)

Whenever I changed the graphql schema via console (add relationship, add permission) or introspect the hasura to generate types for frontend code, I get memory alert from Heroku. (it also happened in self host via docker in VPS)

Look at the peak in the above charts, the server won't release the memory unless i hard restart the server. This is not an ideal solution for production app. I saw some issues mentioned set HASURA_GRAPHQL_QUERY_PLAN_CACHE_SIZE to 100, but I couldn't find any documentation for this environment variables.

Is there a solution for this?

Hasura Version: tried all from v1.3.3 to v1.3.4-beta.3

**Comment by tirumaraiselvan** [comment]
Any chance you tried this in any of the v2.0s yet?

**Comment by xiaoyu-tamu** [comment]
Yes, v2 fixed the issues. I forgot to closed this
