### ISSUE TITLE
http exception when calling webhook

### ISSUE THREAD

**Issue by friend0** [hasura/graphql-engine#6537]
We have an application running instances of GQL engine on Kubernetes.

Hasura Version: hasura/graphql-engine:v1.3.3.cli-migrations-v2
OS: Linux/MacOS

We do local dev on both DockerDesktop and Minikube. 
We have actions configured for the graph.
We have noticed on both local K8s clusters, we will get errors like the following:
Please note that we can verify no traffic is directed to the action handlers, and we can otherwise reach the handlers with curl.

```
{
  "errors": [
    {
      "extensions": {
        "internal": {
          "error": {
            "type": "http_exception",
            "message": "ConnectionFailure Network.Socket.connect: <socket: 111>: does not exist (Connection refused)"
          },
          "response": null,
          "request": {
            "body": {
              "session_variables": {
                REDACTED
              },
              "input": {
                "args": {
                  REDACTED
                }
              },
              "action": {
                "name": "myAction"
              }
            },
            "url": "http://preflight-backend:8001/actions/myAction",
            "headers": [
              {
                "value": "localhost:8080",
                "name": "X-Forwarded-Host"
              },
              {
                "value": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0",
                "name": "X-Forwarded-User-Agent"
              },
            ]
          }
        },
        "path": "$",
        "code": "unexpected"
      },
      "message": "http exception when calling webhook"
    }
  ]
}
```

If we spam the send button on a query for an action in the Hasura console 5-20 times, we will finally get a response and things seem to work reliably until we redeploy. 
One of our engineers noticed that using the `docker.internal...` host names fixed the issue, unfortunately this doesn't address the issue for minikube or remote deployments. 

Is there some kind of DNS caching that's causing Hasura to fail out before sending traffic to our handlers?

**Comment by tirumaraiselvan** [comment]
> Please note that we can verify no traffic is directed to the action handlers, and we can otherwise reach the handlers with curl.

Where are you running the curl from? Ideally, you should check from inside the Hasura container.

> One of our engineers noticed that using the docker.internal... host names fixed the issue, unfortunately this doesn't address the issue for minikube or remote deployments.

Right...this is the most likely the cause. You need to give an endpoint which is reachable from inside the Hasura container. The docker networking could be different depending on how/where you are running Hasura and your webhook. This is a small guide that may help: https://hasura.io/docs/1.0/graphql/core/guides/docker-networking.html#id1 but you should check the minikube docs to see the actual IP/hostname that should be accessed.

**Comment by friend0** [comment]
@tirumaraiselvan I investigated this a bit further, and it looks like this was a result of a bad Service selector definition. I'm closing this for now

**Comment by ash0080** [comment]
For development,
You can use 'host.docker.internal' to access host from a docker container internal
