### ISSUE TITLE
Hasura console error - Apple M1

### ISSUE THREAD

**Issue by tapeo** [hasura/graphql-engine#6549]
I'm trying to start a new project on the new Apple M1. The console doesn't starts, these are the errors after run `hasura init` and `hasura console --log-level DEBUG`:

> DEBU global config file exisits, verifying contents 
DEBU global config is pre-set to &cli.GlobalConfig{UUID:"e871ba60-7561-44f3-9dc9-9770073ec101", EnableTelemetry:true, ShowUpdateNotification:true, CLIEnvironment:"default"} 
DEBU global config: uuid: e871ba60-7561-44f3-9dc9-9770073ec101 
DEBU global config: enableTelemetry: true         
DEBU global config: showUpdateNotification: true  
DEBU global config: cliEnvironment: default       
DEBU cannot get config information from server, this might be because config API is not enabled: invalid character '<' looking for beginning of value 
DEBU graphql engine endpoint: http://localhost:8080 
DEBU graphql engine admin_secret:                 
DEBU telemetry: beamed                             fields.time=347.190459ms isError=true
FATA[0000] version check: failed to get version from server: failed to parse version api response: error converting YAML to JSON: yaml: line 7: mapping values are not allowed in this context

**Comment by tirumaraiselvan** [comment]
Tackling this here: https://github.com/hasura/graphql-engine/issues/6337
