### ISSUE TITLE
Inserting into Enum table

### ISSUE THREAD

**Issue by Yagger** [hasura/graphql-engine#6552]
After inserting a new row into an Enum table, that new value will not work right away.
If I try to insert into another table with that Enum table in relation and using the new value, I will get an error

`unexpected value "<new_value>" for enum: '<table>_enum'`

I have to manually uncheck and re-check the Enum switch for that table. Then all works.

Can it be done so that new values are added to Graphql schema automatically?

**Comment by wwwdepot** [comment]
Hasura doesn't detect changes automatically, see current limitations:

https://hasura.io/docs/1.0/graphql/core/schema/enums.html#current-limitations

**Comment by tirumaraiselvan** [comment]
One solution is to  create an event trigger and manually reload metadata using API in the event trigger handler.

**Comment by Yagger** [comment]
Question is answered. Thanks!
