### ISSUE TITLE
Remote schema is not registered.

### ISSUE THREAD

**Issue by imdhanush** [hasura/graphql-engine#6554]
Am using docker to run hasura-graphql-engine with Postgres and am using version 1.3.3.

I wanna add remote schema through env variables. But I cannot find any remote schema in the UI.
Let me know if am doing anything wrong.

Here's the docker-compose env am using.
```
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ADMIN_SECRET: '123'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      REMOTE_SCHEMA_ENDPOINT: http://172.17.0.1:3000/ghl
```
![hasura](https://user-images.githubusercontent.com/37190602/107990621-d15d6c80-6ffa-11eb-9791-e59dcb00e148.png)

**Comment by tirumaraiselvan** [comment]
Click the `Add` button to add a new remote schema. You will have to provide the URL (or env variable having the URL) there.
