### ISSUE TITLE
Inconsistent graphql schema on object relationship

### ISSUE THREAD

**Issue by kapolos** [hasura/graphql-engine#6555]
This is easier for me to explain with an example, so please bear with me.

Consider the following tables:

 `foo`:

![image](https://user-images.githubusercontent.com/10794126/107992748-01e4dc80-6fe2-11eb-9e0c-548bc37a01e1.png)

`bar`:

![image](https://user-images.githubusercontent.com/10794126/107992725-f4c7ed80-6fe1-11eb-8bac-fef0c4ccd253.png)

Introspecting `bar`, we notice that `fooId` is nullable as expected but `foo` is `NOT` nullable.

![image](https://user-images.githubusercontent.com/10794126/107992646-cd712080-6fe1-11eb-88c0-9c38a3ab58d5.png)

Querying though, will return a `null` if a relationship is not defined for a record:

![image](https://user-images.githubusercontent.com/10794126/107992912-62741980-6fe2-11eb-8b14-143db4eb2102.png)

The problem is that because `foo` is not nullable in the definition, when using auto-code generators (like `graphql-mesh`), queries on `bar` will fail when the results do not have `foo` objects (i.e. with a null `fooId`).

![image](https://user-images.githubusercontent.com/10794126/107993068-c39bed00-6fe2-11eb-8694-98a3616afa89.png)

Solution: Don't define `foo` in `bar` as `NON_NULL` when the foreign relationship can be `null`.

**Comment by tirumaraiselvan** [comment]
Closing this in favour of https://github.com/hasura/graphql-engine/issues/6633 since more activity there. Thanks for the report!
