### ISSUE TITLE
cli: migrations are generally slow.

### ISSUE THREAD

**Issue by haf** [hasura/graphql-engine#6568]
Running 30-50 migrations using `hasura migrate apply` takes up to three minutes.

Exactly the same as https://github.com/hasura/graphql-engine/issues/3654 — the actual SQL is nothing fancy; create a bunch of tables. No calculations or computations; nothing that should take time.

**Comment by scriptonist** [comment]
@haf This should have improved in the latest `alpha`, can you give it a try?

**Comment by haf** [comment]
Yes, fixed in the alpha. Now it takes 0.5 seconds instead of 3 minutes.

**Comment by murph-acuitymd** [comment]
Hi, I'm running into this issue both locally on my ARM macbook and on Ubuntu via GitHub Actions. I'm running the `hasura/graphql-engine:v2.37.1.cli-migrations-v3` image

**Comment by murph-acuitymd** [comment]
I'm also seeing it on `v2.45.1-ce.cli-migrations-v3`
