### ISSUE TITLE
Hasura migrations from existing server which using extensions

### ISSUE THREAD

**Issue by JigneshPatel23** [hasura/graphql-engine#6569]
I have taken complete migration from existing server but when tried to use those in another server there are failures due to in migrations there is no extensions but after adding extensions manually on migration file it started working.  

```
CREATE EXTENSION pg_trgm;
```

**Comment by JigneshPatel23** [comment]
@scriptonist  don't you think this can have bug label as well - as it is not expected behaviour.

**Comment by tirumaraiselvan** [comment]
Only public schema (default) or schemas given via `--schema` flags are dumped, extensions on the other hand are global objects (although their "sub objects" can be in particular schema).

**Comment by rikinsk** [comment]
Closing this issue. Please feel to reopen
