### ISSUE TITLE
cli: migrations from existing server: order of SQL statements

### ISSUE THREAD

**Issue by JigneshPatel23** [hasura/graphql-engine#6570]
I have taken complete migration from existing server but when tried to use those in another server there are failures due to in migrations there is function which is dependent on table but function creation statement runs first before table creation statement.

After reorganising sql file, this started working for me..

Any way can we improve this migration generation utility?

**Comment by JigneshPatel23** [comment]
@scriptonist don't you think this can have bug label as well - as it is not expected behaviour.

**Comment by dsandip** [comment]
Notes from @tirumaraiselvan:

1) we are using pg_dump for this command, and this seems to be an issue with it.

2) Need to investigate if this is limited to just functions referencing other tables/functions which can be circumvented by prefacing the migrations file with `SET check_function_bodies = false;`

**Comment by dsandip** [comment]
From: https://www.postgresql.org/docs/10/app-pgdump.html

When -n is specified, pg_dump makes no attempt to dump any other database objects that the selected schema(s) might depend upon. Therefore, there is no guarantee that the results of a specific-schema dump can be successfully restored by themselves into a clean database.

**Comment by scriptonist** [comment]
This is fixed in [v2.0.0-alpha.7](https://github.com/hasura/graphql-engine/releases/tag/v2.0.0-alpha.7) by https://github.com/hasura/graphql-engine/commit/e3d8a721ee44fb2e3ba059f5074761bc8c009a49
