### ISSUE TITLE
Convert metadata.yaml to CLI-migrations 

### ISSUE THREAD

**Issue by chsi13** [hasura/graphql-engine#6572]
Hi.

I want to export metadata from existing hasura instance (v1.3.0) and use them to start hasura instance from cli-migration-v2 docker image (auto-apply migration at startup).

This last image is waiting for a specific set of files : a directory migrations with a set of *.sql and a metadata directory with a set of yaml files: "tables.yaml, triggers.yaml and so on....(https://hasura.io/docs/1.0/graphql/core/migrations/reference/metadata-format.html#metadata-format-v2)

Is there any tool to do this migration ? Or I have to convert this manually ?

**Comment by scriptonist** [comment]
@chsi13 the command `hasura scripts update-project-v2` should help do that for you. https://hasura.io/docs/1.0/graphql/core/hasura-cli/hasura_scripts_update-project-v2.html

**Comment by chsi13** [comment]
So this will convert a single metadata.yaml into config v2 (multiple files approach -> tables, cron_trigger...) so I can export them, put in a version control system and finally mount them into the cli-migration image ?

**Comment by scriptonist** [comment]
@chsi13 yes, that's right.

**Comment by chsi13** [comment]
@scriptonist I'm connecting to the hasura container (v1.3.0) via classic docker exec ....

But hasura-cli is not available in the container...

How should I proceed to make this conversion if I can't execute this procedure (hasura script.....) directly on the running container instance ? Does install hasura-cli aside of it if the only way ?

**Comment by scriptonist** [comment]
`hasura-cli` is not avialable inside a `graphql-engine` container. what is your use case?

**Comment by chsi13** [comment]
Developers worked on a single hasura instance (based on graphql-engine 1.3.0 image). They built lot of things in a manual way...

We want to stop this so it's time to extract all their work, versionned it and deploy hasura instances in a ci/cd fashion.

So do that the idea is the use the cli version of the image.

The use-case is : how easily export what they did manually until now and migrate metadata in a structure requires by the cli-image.

So how could we transform an exported metadata.yaml into multiple yamls files expected by the V2 cli-image (tables.yaml, triggers.yaml....)

Hope I'm clear :-)

**Comment by tirumaraiselvan** [comment]
You can download the hasura-cli separately. I am closing this issue as the original question seems resolved via https://github.com/hasura/graphql-engine/issues/6572#issuecomment-782062398
