### ISSUE TITLE
Console menu break in low resolutions

### ISSUE THREAD

**Issue by gloredo** [hasura/graphql-engine#6575]
The print are a 1366 x 768 screen resolution.

![hasura-print](https://user-images.githubusercontent.com/20311005/108604162-d455b580-738a-11eb-9e87-09a3338c1950.PNG)

**Comment by beerose** [comment]
Fixed in https://github.com/hasura/graphql-engine-mono/pull/652

**Comment by gloredo** [comment]
> 
> 
> Fixed in [hasura/graphql-engine-mono#652](https://github.com/hasura/graphql-engine-mono/pull/652)

Broken link
