### ISSUE TITLE
Proposal to extend Row-Level permissions. Allow comparing hasura session variable to a constant

### ISSUE THREAD

**Issue by ayuryshev** [hasura/graphql-engine#6576]
# Problem

Let's say we want to extend example from documentation https://hasura.io/docs/1.0/graphql/core/auth/authorization/permission-rules.html#using-session-variables

> For example, to allow an author to access only their articles, you can use the X-Hasura-User-ID session variable to construct a rule to restrict access for select to rows in the articles table where the value in the id column is equal to the value in the session variable (assuming this variable is being used to indicate the author’s ID):

```json
{"id":{"_eq":"X-Hasura-User-Id"}}
```

We have a superuser with id = '00000006-0006-0006-0006-000000000006'.

And we want to allow them  access all rows.

So Row-Level Permission would be like:

```json
{
  "_or": [
    { "id": { "_eq": "X-Hasura-User-Id" } },
    { "X-Hasura-User-Id": { "_eq": "00000006-0006-0006-0006-000000000006" } }
  ]
}
```

But such definition could not be accepted by hasura  because left argument must be a field.

# Proposal

Extend functionality of row-level permissions: 
- allow hasura session variable be left argument
- allow comparing hasura session variable to a constant value

**Comment by tirumaraiselvan** [comment]
Thanks! This is being tracked here: https://github.com/hasura/graphql-engine/issues/3685
