### ISSUE TITLE
[Feature Request] Text Search in JSONB field that consists of arrays

### ISSUE THREAD

**Issue by yasinarik** [hasura/graphql-engine#6577]
For normal text fields, we have the `_ilike` operator which is fairly good for text searching. We can combine multiple of them with the `_or` operator. Also, there are other full-text searching methods. 

For the JSONB fields specifically, as far as I know, we do not have a text searching option. 

We have the `_contains` operator which checks if a key-value pair exists in that particular jsonb data. 

However, we can’t make a text search against the value of a key. Also, if the value of a top-level key is an `array` field, again we can’t search. 

For example, This is a sample table structure:

```gql
id,
keyname,
locales_map: {
  “en”: [“Cars”, “Vehicles”, “Automobiles”],
  “tr”: [“Arabalar”, “Otomobiller”]
}
```

Regardless of what language a user prefers, I want to build search fields on the client app. 

A user could start typing “Cars”, “Vehicles”, or “Automobiles” and my GQLapi should find the rows that have any data similar to that the user typed. 

How can I do that? Until now, I thought I can do it but apparently I just can not.

@tirumaraiselvan @marionschleifer 

### Query
This is a sample query. Obviously, I will have more than 10 language keys like `en, tr, fr, it, ge, ar, cn, sp, az, ru, in` .etc
So it is not. practical to create a field in the `variables JSON` for each country.

Apart from that, even if I do that and use the `_or` operator to check each of the languages, **I still need to** have the full text in order `_contains` operator to match. I show it on the variables example below.

```gql
query GetMatchingCategories($name1: jsonb, $name2: jsonb) {
  items: categories(where: {_or: [{locales_map: {_contains: $name1}}, {locales_map: {_contains: $name2}}]}, order_by: {keyname: asc}) {
    id
    keyname
    locales_map
    created_at
    updated_at
  }
}
```

### Variables
The below variable will match. At first, I thought that I need to provide all items in the array of the key respectively. Thankfully, it will still match for a single item. 

```json
{
  "name1": {
    "en": ["Otomobiller"]
  },
  "name2": {
    "tr": ["Otomobiller"]
  }
}
```

**However,** the user must type the exact search term in full length as `"Otomobiller"`. So for example `"otom"` (for Turkish) or `"veh"`  (for English) will not match. 

There must be a way to overcome that. Something like `regex` or `%` operators but I've tried, they don't work here.

Please offer this feature or offer a workaround.

**Comment by tirumaraiselvan** [comment]
A workaround could be a custom function? https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/custom-functions.html

**Comment by yasinarik** [comment]
> A workaround could be a custom function? https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/custom-functions.html

Hi @tirumaraiselvan how are you? I hope all is well. Thanks for your reply. 

Alongside your suggestion, I was thinking the same. I have checked the docs especially the ones **Text-search functions** and **Fuzzy match search functions**. 

However, probably because the lack of my SQL skills, I couldn't manage to produce such a function. 

I honestly know that you are generally busy with other things but would you mind posting an example search function that I can match the similar texts inside a **JSON field**?

The code example that you kindly provide may be added to the docs as an extended example. 

Thanks a lot,
Yasin
