### ISSUE TITLE
CLI plugin system does not work on NixOS

### ISSUE THREAD

**Issue by samuela** [hasura/graphql-engine#6579]
Much of the functionality of the CLI relies on a plugin system, esp. the `hasura metadata ...` commands. The plugin system AFAICT is built around downloading binaries for each plugin which are maintained in `~/.hasura`. Unfortunately these binaries are dynamically linked and do not work across all Linux distros, in particular they don't work on NixOS where `/lib64/ld-linux-x86-64.so.2` is not generally present. 

Here's an example of what I mean:
```
[skainswo@ip-172-31-5-175:~]$ nix-shell -p hasura-cli file

[nix-shell:~]$ hasura plugins install cli-ext
INFO "can't install, plugin is already installed"  name=cli-ext

[nix-shell:~]$ cd .hasura/plugins/store/cli-ext/v1.4.0-alpha.2/

[nix-shell:~/.hasura/plugins/store/cli-ext/v1.4.0-alpha.2]$ ./cli-ext-hasura-linux
bash: ./cli-ext-hasura-linux: No such file or directory

[nix-shell:~/.hasura/plugins/store/cli-ext/v1.4.0-alpha.2]$ file cli-ext-hasura-linux
cli-ext-hasura-linux: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=2106a959eb86690fe4628f369dd4b325b515ed02, with debug_info, not stripped

[nix-shell:~/.hasura/plugins/store/cli-ext/v1.4.0-alpha.2]$ ldd cli-ext-hasura-linux
	linux-vdso.so.1 (0x00007ffe722c2000)
	libdl.so.2 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libdl.so.2 (0x00007f88b1e05000)
	librt.so.1 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/librt.so.1 (0x00007f88b1dfb000)
	libstdc++.so.6 => not found
	libm.so.6 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libm.so.6 (0x00007f88b1cba000)
	libgcc_s.so.1 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libgcc_s.so.1 (0x00007f88b1ca0000)
	libpthread.so.0 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libpthread.so.0 (0x00007f88b1c7f000)
	libc.so.6 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libc.so.6 (0x00007f88b1abe000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib64/ld-linux-x86-64.so.2 (0x00007f88b1e0c000)
```
Note that libstdc++.so.6 is not resolved. However, I've tested that even with libstdc++.so.6 in LD_LIBRARY_PATH, the binary does not run, likely because of the `/lib64/ld-linux-x86-64.so.2` interpreter issue.

This is especially problematic when trying to run eg
```
[nix-shell:~/dev/cuddlefish/hasura]$ hasura metadata apply
FATA[0001] failed to apply metadata: cannot apply metadata on the database: cannot build actions from metadata: cannot fetch plugin manfiest cli-ext: plugin version is not available
```
which makes the CLI mostly useless for me.

I'm guessing the simplest solution would be to simply ship statically linked executables for plugins. This should reduce the complexity of running on different systems, and (I think) get the plugin system working on NixOS. Alternatively, the metadata functionality could be moved into the main CLI binary itself, which AFAIU would seem to make more sense.

Related:
* https://github.com/hasura/graphql-engine/issues/5449
* https://github.com/hasura/graphql-engine/discussions/6573
* https://github.com/NixOS/nixpkgs/issues/113756

**Comment by samuela** [comment]
So I did a bit of [nix-ld](https://github.com/Mic92/nix-ld) hackery, and I've now gotten to the point where I can run the extension binary:
```
[nix-shell:~/dev/cuddlefish/hasura]$ ~/.hasura/plugins/store/cli-ext/v1.4.0-alpha.2/cli-ext-hasura-linux
Cannot read property 'error' of undefined
```
but even after deleting `~/.hasura`, and reinstalling cli-ext I'm still seeing the same error:
```
[nix-shell:~/dev/cuddlefish/hasura]$ hasura metadata apply
FATA[0001] failed to apply metadata: cannot apply metadata on the database: cannot build actions from metadata: cannot fetch plugin manfiest cli-ext: plugin version is not available
```

So now I'm out of guesses... What does this error mean? What could be triggering it?

**Comment by scriptonist** [comment]
@samuela will try to reproduce this and get back to you

**Comment by samuela** [comment]
@scriptonist any update?

**Comment by scriptonist** [comment]
@samuela can you try the latest alpha? We have some changes which should address this.

**Comment by samuela** [comment]
Okay cool, I'll check it out!

**Comment by vrinek** [comment]
@samuela have you tried the latest alpha as mentioned? Did it work for you?

**Comment by samuela** [comment]
I haven't gotten a chance to test yet. Trying the alpha builds is a little tricky on NixOS since it's not yet in nixpkgs... Is there a quick trick to install the alpha?

**Comment by scriptonist** [comment]
The latest releases should have this fixed, feel free to reopen if that's not the case.

**Comment by silky** [comment]
this issue should definitely not be closed; it's still an issue 🥲 🥲 🥲 🥲

**Comment by Deluxo** [comment]
bump.

It keeps changing the path for cli-ext for every run. 
The tries below are just seconds apart.

```
❯ hasura metadata apply
FATA[0000] error applying metadata
cannot build actions from project: error parsing metadata
object: actions
file: actions.yaml
error: error in converting sdl to metadata: fork/exec /home/user/.hasura/cli-ext/v2.35.0/cli-ext-904470691/cli-ext: no such file or directory:

❯ hasura metadata apply
FATA[0000] error applying metadata
cannot build actions from project: error parsing metadata
object: actions
file: actions.yaml
error: error in converting sdl to metadata: fork/exec /home/user/.hasura/cli-ext/v2.35.0/cli-ext-609912433/cli-ext: no such file or directory:

❯ hasura metadata apply
FATA[0000] error applying metadata
cannot build actions from project: error parsing metadata
object: actions
file: actions.yaml
error: error in converting sdl to metadata: fork/exec /home/user/.hasura/cli-ext/v2.35.0/cli-ext-621884603/cli-ext: no such file or directory:

❯ hasura metadata apply
FATA[0000] error applying metadata
cannot build actions from project: error parsing metadata
object: actions
file: actions.yaml
error: error in converting sdl to metadata: fork/exec /home/user/.hasura/cli-ext/v2.35.0/cli-ext-864906436/cli-ext: no such file or directory:
```
