### ISSUE TITLE
Expected an object instead of a list on Hasura v2.0.0-alpha.1

### ISSUE THREAD

**Issue by whiterabbit1983** [hasura/graphql-engine#6584]
Hello everyone. Could anybody help me to resolve the issue please? In brief, here's my remote schema:
```
scalar JSON

input InputPipe {
  op: String
  transform: String!
  context: JSON
}

type ComposeResult {
  result: JSON
}

type Query {
  compose(pipeline: [InputPipe]!, init: JSON): ComposeResult
}
```

When I try to execute the following query:
```
{
  compose(init:{q: 1}, pipeline:[{transform:"*"}, {transform:"*"}]) {
    result
  }
}
```
I get this:
```
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.compose.args.pipeline",
        "code": "validation-failed"
      },
      "message": "expected an object for type \"InputPipe\", but found a list"
    }
  ]
}
```

This worked correctly on Hasura < 1.4.0. Apologies if it's a duplicate. Thanks in advance.

**Comment by whiterabbit1983** [comment]
Hi, any progress on this? Mybe I did something wrong? If no, then maybe there's some workaround?

**Comment by codingkarthik** [comment]
Hello @whiterabbit1983,

Thanks for reporting this issue, it's indeed a bug. The fix will be released in the next release.

**Comment by whiterabbit1983** [comment]
Thank you @codingkarthik , let me ask you, is this bug already fixed now? If yes, could you please point me to the source code?

**Comment by codingkarthik** [comment]
@whiterabbit1983  Here is the relevant commit: https://github.com/hasura/graphql-engine/commit/6093010a6ebdfd322e70bc1b4a17bc36b7764c46
