### ISSUE TITLE
Hasura CLI: Cannot migrate --from-server due to pg_dump server version mismatch

### ISSUE THREAD

**Issue by neiled** [hasura/graphql-engine#6587]
Hi,

Already have a project on hasura cloud, downloaded the hasura cli v.1.3.3.
I init the project and confirmed connection to my cloud endpoint (can retrieve the metadata from the sever fine).
Tried running:
`hasura migrate create "init" --from-server`
Error received:
```
FATA[0003] cannot fetch schema dump: [unexpected] error while executing pg_dump: pg_dump: error: server version: 13.2 (Ubuntu 13.2-1.pgdg20.04+1); pg_dump version: 12.5 (Ubuntu 12.5-1.pgdg18.04+1)
pg_dump: error: aborting because of server version mismatch
 ($)
```

I don't have postgres installed on my machine, pg_dump must be being used from delivered with the cli?

Any ideas? Tried the latest cli beta too but same issue.

**Comment by scriptonist** [comment]
@neiled CLI uses the [pg_dump API](https://hasura.io/docs/latest/graphql/core/api-reference/pgdump.html) provided by the server. But I believe this has since been fixed on cloud, can you give it one more try?

**Comment by neiled** [comment]
Yes thanks, works now with no changes from my side.

**Comment by GreenRobot777** [comment]
Same error, but with self-hosted hasura #5836

**Comment by antholeole** [comment]
@scriptonist any way to use the pg-dump api on the Hasura docker container? doesn't seem to be possible, even the latest container only errors out with `error: server version: 13.2 (Ubuntu 13.2-1.pgdg20.04+1); pg_dump version: 12.2 (Debian 12.2-2.pgdg90+1)`

**Comment by ReniDelonzek** [comment]
I have the same error

**Comment by CoenNengerman** [comment]
Same problem here. Don't know how to fix this.....

**Comment by AlexKenbo** [comment]
❯ hasura migrate create "init" --from-server
FATA[0006] cannot fetch schema dump: [unexpected] error while executing pg_dump: pg_dump: error: server version: 13.2; pg_dump version: 12.2 (Debian 12.2-2.pgdg90+1)
pg_dump: error: aborting because of server version mismatch
 ($)

**Comment by chwzr** [comment]
same error - please at least add this to your cloud docs: 

DO NOT USE postgressql v14 as your database. you will not able to migrate properly from hasura cloud to local dev.

or give some working postgresql versions as hint..

```
FATA[0008] cannot fetch schema dump: [unexpected] error while executing pg_dump: pg_dump: error: server version: 14.1 (Debian 14.1-1.pgdg110+1); pg_dump version: 13.4 (Ubuntu 13.4-4.pgdg18.04+1)
pg_dump: error: aborting because of server version mismatch
 ($) 
```

**Comment by cindyloo** [comment]
why is this closed?? this is still a MAJOR issue. @tirumaraiselvan  #7676 and a number of related issues

**Comment by Rossi-9999** [comment]
just install the less version in your OS

**Comment by prince-bansal** [comment]
Any update on this issue? I'm still facing a version mismatch error. 

```
FATA[0007] cannot fetch schema dump: pg_dump request: 500 
{
  "path": "$",
  "error": "error while executing pg_dump: pg_dump: error: server version: 14.10; pg_dump version: 13.5 (Debian 13.5-1.pgdg100+1)\npg_dump: error: aborting because of server version mismatch\n",
  "code": "unexpected"
} 

```

Running ```postgres --vesion``` returns  ```postgres (PostgreSQL) 14.12 (Homebrew)```

**Comment by SamirTalwar** [comment]
Are you having this problem with Hasura Cloud or with a local deployment?

If it's local, which version are you running?

**Comment by prince-bansal** [comment]
I'm trying to set up local env for Hasura. 

Postgres image version: 14.10
GraphQL Engine: v2.38.0

**Comment by SamirTalwar** [comment]
I checked the Docker image for Hasura GraphQL Engine (HGE) v2.38.0 and it seems to have the latest `pg_dump`:

```
$ docker run --rm -it hasura/graphql-engine:v2.38.0 pg_dump --version
pg_dump (PostgreSQL) 16.2 (Ubuntu 16.2-1.pgdg22.04+1)
```

I think we're going to need more information.

1. How are you running HGE?
2. How are you running PostgreSQL?
3. What command are you running that triggers the error?

**Comment by prince-bansal** [comment]
Hi, thanks for responding. 

1. I'm running using the docker
2. PostgreSQL is also a docker container spinning up with Hasura setup
3. ```hasura migrate create init --sql-from-server --endpoint my-endpoint --admin-secret my-admin-secret```

Following these articles: 

1. https://hasura.io/docs/latest/hasura-cli/quickstart/
2. https://hasura.io/blog/moving-from-local-development-staging-production-with-hasura
