### ISSUE TITLE
CLI DNS resolution is incorrect on macOS

### ISSUE THREAD

**Issue by samuela** [hasura/graphql-engine#6589]
I have a macOS and a Linux machine connected via Tailscale. Tailscale DNS routes `doodoo` to the linux machine, where I'm running postgres and hasura. Now, this works great for querying hasura:
```
❯ curl http://doodoo:8080/v1/version
{"version":"v1.3.3"}%
```
And I can access `doodoo:8080` from web browsers, etc. However the hasura CLI fails to correctly DNS resolve `doodoo`:
```
❯ HASURA_GRAPHQL_ENDPOINT=http://doodoo:8080 HASURA_GRAPHQL_ADMIN_SECRET=XXX hasura migrate apply
FATA[0001] version check: failed to get version from server: failed making version api call: Get "http://doodoo:8080/v1/version": dial tcp: lookup doodoo on 192.168.1.1:53: no such host
```
It appears that the hasura CLI is querying the first DNS provider and neglecting the rest.

**Comment by scriptonist** [comment]
might be a duplicate of https://github.com/hasura/graphql-engine/issues/5138

**Comment by scriptonist** [comment]
Tracking in https://github.com/hasura/graphql-engine/issues/5138

**Comment by samuela** [comment]
Just tested this with `cli: v2.0.0-beta.2` and I'm still getting the same error.
