### ISSUE TITLE
Hacktoberfest reward contact

### ISSUE THREAD

**Issue by gahag** [hasura/graphql-engine#6601]
I've qualified for Hasura's 2020 hacktoberfest reward by contributing to this repository, but I'm yet to receive such reward. Since I've filled the form with the shipping details, I have not heard from Hasura again. I have tried to reach to the person that sent me the form via email, and also to other of Hasura's public channels, to no avail, so I'm starting to feel like I've been fooled. Is there any contact where I can get to know why my rewards have not yet arrived? I would be glad if someone could help me to sort this out. Thank you.

**Comment by mehtavishwa30** [comment]
Hello @gahag! Apologies for the inconvenience. I've checked and can confirm that we've shipped you your swag. Please check your email for the tracking details I've sent you. Thanks for your patience. :)

Cheers!
