### ISSUE TITLE
CLI is confused about version ordering

### ISSUE THREAD

**Issue by samuela** [hasura/graphql-engine#6602]
I just got the following error using the hasura CLI:
```
WARN [cli: v2.0.0-alpha.1] [server: v1.3.3] version mismatch: older cli version might not be compatible with latest server apis, please update cli
```
which seems backwards to me.

**Comment by rossng** [comment]
Looks like the issue is that the CLI returns exactly the same message no matter which way the ordering is!

https://github.com/hasura/graphql-engine/blob/master/cli/version/compatibility.go#L46

**Comment by scriptonist** [comment]
fixed in https://github.com/hasura/graphql-engine/commit/5884b8d17c015e63fa6253a324443c03a642d3ce

**Comment by purush7** [comment]
@FatmaMahmoud698 can you share the error/warnings log and the output of `hasura version` too.
