### ISSUE TITLE
request_parse_error when trying to create a remote schema relations ship

### ISSUE THREAD

**Issue by zolamk** [hasura/graphql-engine#6603]
i am running `hasura 2.0.0-alpha.2` and when i try to create a relationship between one of my tables and a remote schema it says `creating remote relationships` but nothing happens the response of the network request is as follows

```
{"code":"request_parse_error","message":"json: cannot unmarshal object into Go struct field Request.down of type []api.requestType"}
```

**Comment by beerose** [comment]
Closed in https://github.com/hasura/graphql-engine-mono/pull/693
