### ISSUE TITLE
Announcing Hasura 2.0! 🎉

### ISSUE THREAD

**Issue by mehtavishwa30** [hasura/graphql-engine#6604]
On behalf of the entire team at Hasura, I'm delighted to announce the release of Hasura GraphQL Engine 2.0 (also just called Hasura 2.0). 🎉

Hasura 2.0 is our most significant release over the last few years, but is also entirely backwards compatible with Hasura 1.x. Over the last 85 releases of Hasura over 2 years, we've endeavoured to never break user facing APIs and this major release is another checkpoint in ensuring that users get new features without having to refactor their work. In fact, Hasura 2.0 == Hasura 1.4, but it was such a big release that we decided to call our next 1.4 release, 2.0.

Please do try this out and give us your feedback here or on our Discord.

@coco98 hosted a launch webinar on March 4 to demo what’s new and answer questions from our users. Check out the [recording](https://hasura.io/hasura2webinar/)!

So, what’s in 2.0?

- Connect Multiple Databases Simultaneously - A single instance of Hasura GraphQL engine, multiple databases for multi-tenancy or workload flexibility.
- Database Generalization - Say hello to SQL Server and BigQuery support and the framework for more.
- REST endpoints - Idiomatic REST endpoints based on GraphQL templates. Both options depending on your needs and tooling.
- Authorization engine - Authz policies extended across data sources.
- High Availability & Distributed Ops - ‘Maintenance mode’ for upgrades (of engine our sources) without downtime to the API
- Metadata APIs - Much more work on metadata tooling coming very soon.

To learn more about what's in store, check out @coco98's announcement blog post [here](https://hasura.info/3aKDPtn). 

Our launches are always exciting. This one is no different. Thank you -- our community -- for your support, your feedback, and joining us on this journey. ❤️

**Comment by psrcek** [comment]
Is it just me or does the `v2.0.0-alpha.2` console load WAY slower. In my case it's 10-15 seconds vs 4-5 seconds on `v1.3.3`.

**Comment by raphaelmerx** [comment]
The blog post and this issue mention BigQuery support, however can't find it in the data source driver list, on Hasura Cloud v2:
<img width="1440" alt="Screenshot 2021-03-05 at 18 41 01" src="https://user-images.githubusercontent.com/5139869/110104622-578ef680-7de2-11eb-9fe3-e45644daac22.png">

**Comment by ccalvarez** [comment]
Are mutations provided for MS SQL Server?

**Comment by yu-tou** [comment]
Are there any plans to support MySQL？

**Comment by acatzk** [comment]
so means that if we have local database so we can remove it in the cloud and just inject it right away

**Comment by miguelocarvajal** [comment]
I don't see the "Custom GraphQL Root Fields", section in a table for this version.

Is this something that has not been implemented yet or is it done differently now?

**Comment by Sami26912** [comment]
> On behalf of the entire team at Hasura, I'm delighted to announce the release of Hasura GraphQL Engine 2.0 (also just called Hasura 2.0). 🎉
> 
> Hasura 2.0 is our most significant release over the last few years, but is also entirely backwards compatible with Hasura 1.x. Over the last 85 releases of Hasura over 2 years, we've endeavoured to never break user facing APIs and this major release is another checkpoint in ensuring that users get new features without having to refactor their work. In fact, Hasura 2.0 == Hasura 1.4, but it was such a big release that we decided to call our next 1.4 release, 2.0.
> 
> Please do try this out and give us your feedback here or on our Discord.
> 
> @coco98 hosted a launch webinar on March 4 to demo what’s new and answer questions from our users. Check out the [recording](https://hasura.io/hasura2webinar/)!
> 
> So, what’s in 2.0?
> 
> * Connect Multiple Databases Simultaneously - A single instance of Hasura GraphQL engine, multiple databases for multi-tenancy or workload flexibility.
> * Database Generalization - Say hello to SQL Server and BigQuery support and the framework for more.
> * REST endpoints - Idiomatic REST endpoints based on GraphQL templates. Both options depending on your needs and tooling.
> * Authorization engine - Authz policies extended across data sources.
> * High Availability & Distributed Ops - ‘Maintenance mode’ for upgrades (of engine our sources) without downtime to the API
> * Metadata APIs - Much more work on metadata tooling coming very soon.
> 
> To learn more about what's in store, check out @coco98's announcement blog post [here](https://hasura.info/3aKDPtn).
> 
> Our launches are always exciting. This one is no different. Thank you -- our community -- for your support, your feedback, and joining us on this journey. ❤️

#
