### ISSUE TITLE
v2.0.0-alpha.2 Hasura console not accessible

### ISSUE THREAD

**Issue by mirzap** [hasura/graphql-engine#6605]
There's an issue with using a console protected with admin key. All other `hasura` cli commands work with the admin key (migrate up/reset, update configs with `scripts update-project-v3` etc) but when i run hasura console, I get this:

![image](https://user-images.githubusercontent.com/991967/109151055-f9bb3880-7769-11eb-9821-a5701bb59198.png)

Here's what I have in logs:

```
{
  "type": "http-log",
  "timestamp": "2021-02-25T11:59:33.153+0000",
  "level": "error",
  "detail": {
    "operation": {
      "error": {
        "path": "$",
        "error": "resource does not exist",
        "code": "not-found"
      },
      "request_id": "a0afaf87-9e0c-4ac1-bd1c-0779d06936ff",
      "response_size": 65,
      "raw_query": ""
    },
    "request_id": "a0afaf87-9e0c-4ac1-bd1c-0779d06936ff",
    "http_info": {
      "status": 404,
      "http_version": "HTTP/1.1",
      "url": "/v1alpha1/config",
      "ip": "172.21.0.1",
      "method": "GET",
      "content_encoding": null
    }
  }
}
```

Rolling back project to the `v1.4.0-alpha.2` version and console works without problem.

**Comment by beerose** [comment]
Hey @mirzap! We'll look into it. In the meantime I have one question — do you have Config APIs disabled (https://hasura.io/docs/latest/graphql/core/api-reference/config.html#disabling-config-api)?

**Comment by mirzap** [comment]
It would seem so. I have this in docker compose
```
HASURA_GRAPHQL_ENABLED_APIS: metadata,graphql,pgdump
```

**Comment by soorajshankar** [comment]
Hey @mirzap! 
Console uses config api to communicate with Hasura graphql engine.
It can be resolved by adding `config` to the enabled APIs.
```
HASURA_GRAPHQL_ENABLED_APIS: metadata,graphql,pgdump,config
```

Also, we will investigate to see if we can load the console features that are not using the config APIs.

**Comment by mirzap** [comment]
Hey @soorajshankar, yes it works now. But it worked without config api before. All I did (same as always) just update image tag for the graphql server, so I guess there's some new change?

Another thing, setting `HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets` doesn't work, it returns 404 for the assets. I had to disable it for the moment.

**Comment by beerose** [comment]
Console assets are in `srv/` insetad of `srv/console-assets` (issue on our side, we'll fix it) so `HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv` should work. 

As for the console, we did change the way of how we do post-login validation, and we're using Config API for that purpose now. Previously we were using Metadata API. However, it's not ideal, and we'll work on reverting back to Metadata API.

**Comment by mirzap** [comment]
Just tried, still doesn't work (Should I open separate issue for this?)
![image](https://user-images.githubusercontent.com/991967/109174195-e9648700-7784-11eb-9827-c86e4278ba57.png)

**Comment by beerose** [comment]
@mirzap yes, please do. 
By the way — the fix for the original issue should be live in a few hours.

**Comment by beerose** [comment]
Fixed in https://github.com/hasura/graphql-engine/commits/alpha
