### ISSUE TITLE
cli: known issues/caveats in v2.0.0-alpha.4

### ISSUE THREAD

**Issue by scriptonist** [hasura/graphql-engine#6607]
The following is the list of known issues/caveats for `2.0.0-alpha.4` release of CLI
1. ~~No support for REST endpoints in metadata (will be available in alpha.4)~~
2. ~~No MS-SQL migrations support (will be available in alpha.4)~~
3. ~~No `cli-migrations` image for config v3 yet~~

**Comment by haf** [comment]
It deletes all metadata too

**Comment by jgoux** [comment]
Is the point 3 addressed in alpha.3? I just tested and I still hit this error on `hasura/graphql-engine:v2.0.0-alpha.3.cli-migrations-v2` startup : 

```
{"timestamp":"2021-03-05T09:41:05.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-apply","info":"applying metadata from /hasura-metadata"}}
{"level":"info","msg":"Applying metadata...","time":"2021-03-05T09:41:05Z"}
time="2021-03-05T09:41:06Z" level=fatal msg="failed to apply metadata: cannot apply metadata on the database: {\"path\":\"$\",\"error\":\"key \\\"tables\\\" not found\",\"code\":\"parse-failed\"}"
```

This is blocking me to test the v2 in fargate as the auto-migration feature makes it so simple to deploy.

**Comment by haf** [comment]
@jgoux Just remove the first line "tables:" and paste its contents in `tables.yaml` instead.

**Comment by jgoux** [comment]
Not sure I follow.

This is what I have currently : 
![image](https://user-images.githubusercontent.com/1443499/110117530-44b3fc00-7db9-11eb-8d26-6baf54d9e260.png)

Where am I supposed to put tables.yaml and where is the `tables:` line that I need to copy?

**Comment by scriptonist** [comment]
@jgoux `cli-migrations` image for config v3 is not yet out. `hasura/graphql-engine:v2.0.0-alpha.3.cli-migrations-v2` is supposed to be used with a `config V2` project.

**Comment by jgoux** [comment]
Ok my bad, as you still publish these images I thought it was compatible. 😄

**Comment by scriptonist** [comment]
@jgoux It's fully compatible but with a config v2 project

**Comment by haf** [comment]
In the alpha I'm not getting automatic suggestions of relationships by foreign keys:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/193115/110236567-c2e9dd00-7f36-11eb-8f73-37387fe503c2.png">

**Comment by haf** [comment]
When navigating backwards in the `hasura console`, you get:

<img width="1865" alt="image" src="https://user-images.githubusercontent.com/193115/110238035-81a9fb00-7f3f-11eb-9af2-3107bad6addb.png">

A full page refresh solves this.

**Comment by its-a-feature** [comment]
For reference as an interim solution - I ran into this today and got a workaround to keep using the v2 config and have it update/ingest.

1. Start docker migrations container like normal
2. make modifications as needed to your metadata (i do this in the UI)
3. docker exec into your container. 
4. run hasura-cli init and give some arbitrary name (let's say "bob")
5. cd to "bob" and remove everything in the `metadata` folder.
6. in the `config.yml` file at the root of "bob", change the version from 3 to 2
7. run `hasura-cli metadata export` like normal, and now you have the v2 data that can still be imported like normal

not a long term solution, but at least is pretty quick and doesn't require editing any of your actual metadata files

**Comment by gunar** [comment]
Nice, thanks Hasura team!

The [README on Docker Hub](https://hub.docker.com/r/hasura/graphql-engine) hasn't been updated yet to include the `cli-migrations-v3` variant but the image has been pushed: `hasura/graphql-engine/v2.0.0-alpha.7.cli-migrations-v3`.
