### ISSUE TITLE
Hasura 2.0 incompatible with Hasura 1.3 Remote Schema

### ISSUE THREAD

**Issue by flobaader** [hasura/graphql-engine#6608]
Hello everyone,

thank you for the hard work of the next great release. I found the following problem when starting a hasura/graphql-engine:v2.0.0 that has a remote schema on a hasura hasura/graphql-engine:v1.3.2:

```json
{
  "type": "startup",
  "timestamp": "2021-02-25T15:02:53.873+0000",
  "level": "info",
  "detail": {
    "kind": "schema-sync",
    "info": {
      "thread_id": "ThreadId 17",
      "message": "listener thread started"
    }
  }
}
{
  "type": "unstructured",
  "timestamp": "2021-02-25T15:02:53.873+0000",
  "level": "info",
  "detail": "Thread SchemeUpdate.listener (re)started"
}
{
  "type": "startup",
  "timestamp": "2021-02-25T15:02:53.873+0000",
  "level": "error",
  "detail": {
    "kind": "catalog_migrate",
    "info": {
      "path": "$",
      "error": "Found conflicting definitions for \"String_comparison_exp\".  The definition at \"query_root.REMOTE SCHEMA URL\" differs from the the definition at \"query_root.LOCAL DEFINTIONS.....,
      "code": "unexpected"
    }
  }
}
```

It seems like an issue with different String definitions between those instances.

**Comment by codingkarthik** [comment]
Hello @flobaader 

Thanks for reporting this issue. It seems like this issue depends on the remote schema that has been added because I was not able to reproduce this issue with a remote schema I have in my local dev. It will be great if you can share the schemas of your hasura instance and the remote schema.

**Comment by flobaader** [comment]
Thanks for the quick reply @codingkarthik

The following user schema is defined in the remote hasura 1.3.2

![image](https://user-images.githubusercontent.com/16624361/109471655-5a4fbb80-7a71-11eb-9616-a2da560dcbcb.png)

This schema is then referenced in the current 2.0.0-alpha.2 version with:
![image](https://user-images.githubusercontent.com/16624361/109471744-79e6e400-7a71-11eb-8330-e64a5492142e.png)

This results in the described error.

**Comment by codingkarthik** [comment]
Oh, I see what maybe happening. 
I think this is caused due to the version mismatch between your local hasura instance and the remote schema hasura instance. Can you try upgrading your hasura remote schema instance first before upgrading your local hasura instance?

**Comment by flobaader** [comment]
Okay so this is exactly what I wanted to report. Maybe the incompatibility should be pointed out in the release notes.

The problem that we face is that we are using a hasura micro service architecture. 
That means that we would need to upgrade all hasuras at once in order to have compatible remote schemas.

**Comment by tirumaraiselvan** [comment]
@flobaader We will definitely try to see what we can do to avoid this issue or atleast mention it clearly in the release notes. Thanks for notifying us!

**Comment by tirumaraiselvan** [comment]
This has now been mentioned in the Release notes: https://github.com/hasura/graphql-engine/releases/tag/v2.0.0-alpha.1
