### ISSUE TITLE
v2.0.0-alpha.2 Console assets not found

### ISSUE THREAD

**Issue by mirzap** [hasura/graphql-engine#6610]
I have specified `HASURA_GRAPHQL_CONSOLE_ASSETS_DIR`  in my docker file to `/srv/console-assets` but after the upgrade to the v2.0.0-alpha.2 those are not to be found.

I've tried setting to `/srv` as suggested [here](https://github.com/hasura/graphql-engine/issues/6605#issuecomment-785954514) but it's the same:

![image](https://user-images.githubusercontent.com/991967/109184147-f8e8cd80-778e-11eb-871c-71093566edd1.png)

**Comment by jflambert** [comment]
Yes I mentioned this to @scriptonist  in  #6600, which I will no close in favor of this new issue.

**Comment by 0x777** [comment]
@mirzap @jflambert This will be fixed in 2.0.0-alpha.3, till then setting `HASURA_GRAPHQL_CONSOLE_ASSETS_DIR` to `/srv` should work. 

> I've tried setting to /srv as suggested here but it's the same:

@mirzap Maybe the docker image was not re-built after the environment variable is changed?

**Comment by mirzap** [comment]
@0x777 Great! When can we expect 3rd alpha?

I do `down -v` everytime, which removes docker containers and volumes and it still happens... For now I'm using cloud assets.

**Comment by mirzap** [comment]
I'm testing on alpha.3. Still neither `/srv` nor `/srv/console-assets` work. When I enter the container files exist in `/srv/console-assets`

![image](https://user-images.githubusercontent.com/991967/110000533-b20d5180-7d13-11eb-9815-7b989bf3b57e.png)


```
{
  "type": "http-log",
  "timestamp": "2021-03-04T16:59:04.248+0000",
  "level": "error",
  "detail": {
    "operation": {
      "error": {
        "path": "$",
        "error": "resource does not exist",
        "code": "not-found"
      },
      "request_id": "eedbaef6-09f8-4858-9594-b01b90b78f37",
      "response_size": 65,
      "raw_query": ""
    },
    "request_id": "eedbaef6-09f8-4858-9594-b01b90b78f37",
    "http_info": {
      "status": 404,
      "http_version": "HTTP/1.1",
      "url": "/console/assets/versioned/vendor.js.gz",
      "ip": "172.21.0.1",
      "method": "GET",
      "content_encoding": null
    }
  }
}
```

**Comment by kolharsam** [comment]
@mirzap I can confirm that this issue has been fixed in 2.0.0-alpha.3. Setting `HASURA_GRAPHQL_CONSOLE_ASSETS_DIR` to `/srv/console-assets` works now. Please make sure that you're setting `HASURA_GRAPHQL_ENABLE_CONSOLE` to `true` as well. Let me know if this helps.

**Comment by mirzap** [comment]
Yes, setting `HASURA_GRAPHQL_ENABLE_CONSOLE` did the trick.

**Comment by jflambert** [comment]
Seems to work now. Maybe close this issue?
