### ISSUE TITLE
[v2.0.0-alpha.3] Adding query to allow-list not possible

### ISSUE THREAD

**Issue by mirzap** [hasura/graphql-engine#6617]
I've posted question asking for help [here](https://github.com/hasura/graphql-engine/discussions/6615) Since then I've made tests on stable release v1.3.3 and adding queries works without problem. This looks like a regression to me. 

Here's error message I get on v2.0:
![image](https://user-images.githubusercontent.com/991967/109414544-adfbcf80-79b3-11eb-8404-94eb4e8a0de3.png)

**Comment by kolharsam** [comment]
Hey @mirzap!
Could you let us if you had created any REST endpoint(s) prior to adding a query to the allow-list?

**Comment by tirumaraiselvan** [comment]
@kolharsam Let's also implement part of this issue while triaging this: https://github.com/hasura/graphql-engine/issues/4138 (atleast show the name of the collection being created)

**Comment by mirzap** [comment]
Hey @kolharsam! No I did not. I've just migrated project from 1.3.4-beta3 using `update-project-v3`. I've replicated this issue every time (droping db, running migrations and seeds) on multiple machines.

This is hdb_catalog. There's no `hdb_allowlist` and `hdb_query_collection`:
![image](https://user-images.githubusercontent.com/991967/109468231-9896ac00-7a6c-11eb-9eb6-2cf4fb3092f8.png)

**Comment by mirzap** [comment]
Is this fixed or?

**Comment by beerose** [comment]
@mirzap the fix was merged and it will be live in a few hours. The issue was closed automatically when the corresponding PR was merged.

**Comment by mirzap** [comment]
@beerose I have this issue on alpha.3. Anything else I need to do beside setting `HASURA_GRAPHQL_ENABLE_ALLOWLIST=true` ?

**Comment by mirzap** [comment]
OK I've narrowed it down. For the new project with `alpha.3` image everything is fine, I can add queries to the allow list. But when I update project v2 -> v3 I get this error.

**Comment by mirzap** [comment]
@beerose  @kolharsam @0x777 Here is repo where I've described every step how to replicate this issue. I get the same result every time. I think this issue should be re-opened.

https://github.com/mirzap/hasura-allow-query

**Comment by scriptonist** [comment]
@mirzap we have identified this as a bug on the CLI, thanks for the detailed repro steps.

**Comment by scriptonist** [comment]
Should be fixed in the latest alpha release
