### ISSUE TITLE
unable to filter jsonb columns using  hasura session variables 

### ISSUE THREAD

**Issue by tanmaypatil** [hasura/graphql-engine#6620]
I have jsonb column in my table called as criteria . 
Data for criteria column is as follows 
`"criteria": [
          {
            "type": "ACC",
            "values": [
              "198cd920-92d0-55e3-222e-53aam"
            ]
          }
        ]`

Permission rule for criteria column is as follows 
`{"criteria":{"_contained_in":[{"type":"ACC","values":"x-hasura-account-id"}]}}`

- x-hasura-account-id passed as {"198cd920-92d0-55e3-222e-53aam"}
- x-hasura-account-id passed as ["198cd920-92d0-55e3-222e-53aam"]

in both cases graphql query returns empty response 
`SELECT  *  FROM "vam"."transaction_master"  WHERE (("vam"."transaction_master"."criteria") <@ 
  (('[{"values": ["198cd920-92d0-55e3-222e-53aam"],"type":"ACC"}]')::jsonb))   
 `
returns correct response . Any pointers on this behavior of hasura session variables

@tirumaraiselvan

**Comment by 0x777** [comment]
@tanmaypatil Can you share the output when you hit the `explain` button in graphiql?

**Comment by tanmaypatil** [comment]
@0x777  i was running query from postman as i need to use non admin role.
hasura console is protected through admin secret and session variables are not used for admin role

**Comment by tirumaraiselvan** [comment]
Seems like this is what you are hitting: https://github.com/hasura/graphql-engine/issues/4817

**Comment by tanmaypatil** [comment]
yes exactly same problem.  Session variables are not getting replaced.

**Comment by tirumaraiselvan** [comment]
Thanks! Going to close this as dupe. Let's continue in #4817
