### ISSUE TITLE
Unable to connect to SQL Server

### ISSUE THREAD

**Issue by instantgis** [hasura/graphql-engine#6634]
I am running Hasura 2 alpha 2 in a Docker container on Windows 10 PRO 64 bit and trying to connect to a local SQL Server 2017 via

Driver={ODBC Driver 17 for SQL Server};Server=localhost;Database=DryMix-Dev;UID=DryMix;PWD=<removed>;

I tried my machine name instead of localhost too.
I checked my SQL Server allows remote connections.

I get this:

unexpected exception while connecting to database: UnsuccessfulReturnCode "odbc_SQLDriverConnect" (-1) "[Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired[Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2AF9[Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.[Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online."

**Comment by instantgis** [comment]
I was able to connect to an Azure SQL Server via

Driver={ODBC Driver 17 for SQL Server};Server=tcp:drymix.database.windows.net,1433;Database=DryMix;UID=...;PWD=...;

However I get this when looking at tables in the database

unexpected exception while executing query: UnsuccessfulReturnCode "odbc_SQLExecDirectW" (-1) "[Microsoft][ODBC Driver 17 for SQL Server]The connection is broken and recovery is not possible. The connection is marked by the client driver as unrecoverable. No attempt was made to restore the connection.[Microsoft][ODBC Driver 17 for SQL Server]The connection is broken and recovery is not possible. The connection is marked by the client driver as unrecoverable. No attempt was made to restore the connection. "

**Comment by ccalvarez** [comment]
I was able to connect to an on-premises SQL Server 2016 (version 13.0.5865.1) using the  `hasura/graphql-engine:v2.0.0-alpha.3` image.

My connection string:  

`Driver={ODBC Driver 17 for SQL Server};Server=myServer;Database=myDatabase;UID=myUser;PWD=myPassword;`

I had to install the ODBC Driver 17 for SQL Server on the Windows box where I start the Hasura docker container, I have downloaded the driver from https://www.microsoft.com/en-us/download/details.aspx?id=56567 (choose the 4.5 MB file).

That worked for me.


What I could't get to work is connecting to SQL Server using Windows Integrated Authentication, aka "Integrated Security=SSPI"

I'm trying this connection string, but it fails to connect:

`Driver={ODBC Driver 17 for SQL Server};Server=myServerAddress;Database=myDataBase;Trusted_Connection=yes;`

**Comment by 0x777** [comment]
@instantgis 

> Driver={ODBC Driver 17 for SQL Server};Server=localhost;Database=DryMix-Dev;UID=DryMix;PWD=;

This connection string will not work because `localhost` would mean the localhost of the container and not your windows machine. How are you running docker?

> I was able to connect to an Azure SQL Server via
Driver={ODBC Driver 17 for SQL Server};Server=tcp:drymix.database.windows.net,1433;Database=DryMix;UID=...;PWD=...;
However I get this when looking at tables in the database

We will look into this ASAP.
