### ISSUE TITLE
Passing Conditions as JSONB

### ISSUE THREAD

**Issue by mayank** [hasura/graphql-engine#6645]
I want to pass the conditions as JSON in the query. Something like this,

Queries
```graphql
query get_cases($condition: jsonb) {
      cases(where: $condition) {
            id
            name
      }
}
```

Variables
```graphql
{
   "name": {
    "_nlike": "%2843%"
   }
}
```
Wanted to ask

- [ ]  Is this possible in the current scenario?
- [ ] Is this the correct approach to do this, as the frontend has different filters.
- [ ] If not we can create a future PR, I would be happy to help on this.

**Comment by amnaveenriaz** [comment]
Is this what you are looking for ?

**Query:**
`query cases($where: cases_bool_exp) {
  cases(where: $where) {
    id
    name
  }
}`

**Variables:**
`{
  "where": {
    "name": { "_nlike": "%test%"}
  }
}`

**Comment by mayank** [comment]
@amnaveenriaz yes, is `case_bool_exp` a defined type in  hasura?

**Comment by coots0001** [comment]
0x2294aBf506fF4414ca3184d8CED9555840Ac77E0
That’s the E 20 token here’s that address
At coots0001
That’s my Coinbase wallet
JASON A CARPENTER 
COOTS ......

**Comment by amnaveenriaz** [comment]
> @amnaveenriaz yes, is `case_bool_exp` a defined type in hasura?

Yes.. U can search in docs (Console Right Side )for all the ways you can query a table.
![Screenshot 2021-03-11 at 9 13 38 PM](https://user-images.githubusercontent.com/78220824/110792820-d38bb180-82ae-11eb-9d4f-4e7b9148435e.png)

**Comment by amnaveenriaz** [comment]
Join the discord community to get answers directly - https://discord.com/invite/hasura

**Comment by mayank** [comment]
@amnaveenriaz thanks dude!

**Comment by coots0001** [comment]
Yep 👍🏻
