### ISSUE TITLE
SQL Server - GraphQL table name customization

### ISSUE THREAD

**Issue by sve-odoo** [hasura/graphql-engine#6647]
Hello.

I just tried out Hasura ( v2.0.0-alpha.3 ) on my legacy Ms SQL Server database.
Because of internal conventions, all my table names start with numbers. ( example : "10_Users" , "20_Products" , etc. )

Because of that I get the following error message for all my tables:
![image](https://user-images.githubusercontent.com/7520862/110637538-c89d2800-81ad-11eb-8a1a-977a9a1e0153.png)

And it seems that I cannot do anything because of that.

Is there any way to set an alias for my tables? Or do you suggest something else?

Best regards,
Sébastien

**Comment by iykekings** [comment]
closing as fixed [here](console: fix browse rows sections failing on a table with custom name)
