### ISSUE TITLE
Upgrade from v2.0.0-alpha.2 => v2.0.0-alpha.4 error

### ISSUE THREAD

**Issue by followbl** [hasura/graphql-engine#6650]
```
$ hasura metadata apply && hasura migrate apply --database-name default && hasura metadata reload
FATA[0001] failed to apply metadata: cannot apply metadata on the database: {
  "path": "$.metadata",
  "error": "key \"sources\" not found",
  "code": "parse-failed"
}
```

no clue what this error message is referring to.

**Comment by scriptonist** [comment]
@followbl there has been some changes to how CLI parses local metadata files in the latest alpha. So, once you update the server please do a `hasura metadata export` and a subsequent `hasura metadata apply` commands should work correctly.

**Comment by followbl** [comment]
@scriptonist works, thx 🔑
