### ISSUE TITLE
Type Issue: Expected an Object for Type but found List

### ISSUE THREAD

**Issue by SandeepSamba** [hasura/graphql-engine#6651]
When Hasura autogenerates the query schema for a table, the `_and` and `_or` fields of `where` clause is of type list of `bool_exp`. When this graphql schema is added as a remote schema to another Hasura, the type for `_and` and `_or` of the same `where` field becomes just `bool_exp`, making it impossible to create long boolean expressions. 

In the below screenshot (Actors table in Chinook Dataset), the schema generated from the table has list of bool_exp type for `_and` .
![Direct-db](https://user-images.githubusercontent.com/17796073/110806766-62490000-82a8-11eb-8abd-aef6fbb20c04.png)

When the above is exposed as remote schema, the type for and operator is as below:
![Remote-schema](https://user-images.githubusercontent.com/17796073/110806944-8e648100-82a8-11eb-8d23-ee1f8ff84e8f.png)

**Comment by codingkarthik** [comment]
@SandeepSamba Which version of graphql-engine did you encounter this issue?

**Comment by tirumaraiselvan** [comment]
@SandeepSamba said:

> I reproduced this with remote schema hasura version V1.3.3 and main hasura V2.0.0.alpha.2

**Comment by codingkarthik** [comment]
fixed in https://github.com/hasura/graphql-engine-mono/pull/638
