### ISSUE TITLE
Not able to perform Hasura migrate apply

### ISSUE THREAD

**Issue by radha-igtb** [hasura/graphql-engine#6652]
Team need help.
We recently enabled Auth hook in our project.
Now when I with to apply this migration it fails. I get the following error:
FATA[0000] apply failed: cannot create migrate instance: [access-denied] Authentication hook unauthorized this request ($) 

My Hasura and CLI versions are as below:
INFO hasura cli                                    version=v1.3.2
INFO hasura graphql engine                         endpoint="http://localhost:8080" version=v1.3.3

Some more information, chronology of actions taken: 
1. With 1.3.3 webhook was getting invoked even for metadata and migrate apply. Is this expected behaviour? because of this the migration and metadata apply failed for me. And I get the error: FATA[0020] apply failed: cannot create migrate instance: [access-denied] Authentication hook unauthorized this request ($) 

2. On upgrade to GQL Engine as v2.0.0-alpha.4, it was not able to connect to postgres. It keeps giving the following in the logs '<>_graphql-engine_1 exited with code 137'. And I am not able to access the console.

3. So I downgraded GQL Engine back to 1.3.3 and now my GQL Engine wont come up. I get the error: "Cannot use database previously used with a newer version of graphql-engine (expected a catalog version <=40, but the current version is 44)."

4. For this I followed the steps given here to downgrade the catalogue version -> https://hasura.io/docs/latest/graphql/core/deployment/downgrading.html#step-2-downgrade-hasura-catalogue-version
On doing so I get the following error: 
**Command**: docker run -e HASURA_GRAPHQL_DATABASE_URL=$DATABASE_URL hasura/graphql-engine:v2.0.0-alpha.4 graphql-engine downgrade --to-v1.3.3
**Error output**
{"type":"pg-client","timestamp":"2021-03-12T16:40:40.586+0000","level":"warn","detail":{"message":"postgres connection failed, retrying(0)."}}
{"type":"pg-client","timestamp":"2021-03-12T16:40:40.586+0000","level":"warn","detail":{"message":"postgres connection failed, retrying(1)."}}
{"internal":"could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?\n","path":"$","error":"connection error","code":"postgres-error"}

**Comment by radha-igtb** [comment]
@tirumaraiselvan have updated the request with the attempts I have made. What m I missing?

**Comment by tirumaraiselvan** [comment]
Closing this as resolved in discord
