### ISSUE TITLE
[2.0.0-alpha.3] Remote Schema Argument Type Issue: Expecting Array but is Object

### ISSUE THREAD

**Issue by LydiaF** [hasura/graphql-engine#6655]
Hi there,

We have a remote schema that looks like this:
```graphql
input File {
  id: ID!
  name: String!
  type: String!
  base64_contents: String!
}

type Mutation {
  upload(files: [File!]!, asPlatonic: Boolean): [Media!]!
}
```

The problem is that Hasura is saying the `files` type is `File!` when it should be `[File!]!`.

I have tried refreshing the remote schema, and dropping and reapplying md. 

I know Hasura is picking up changes as I tried changing the name of the second argument and that did work.

Thanks!

**Comment by tirumaraiselvan** [comment]
Seems identical to https://github.com/hasura/graphql-engine/issues/6651

**Comment by khan297** [comment]
ذ

**Comment by codingkarthik** [comment]
closing as dupe of #6651

**Comment by LydiaF** [comment]
Thanks a mill :)
