### ISSUE TITLE
Why can't custom functions receive session arguments with GraphQL subscription in console?

### ISSUE THREAD

**Issue by hadajun** [hasura/graphql-engine#6657]
Hasura v2.0.0-alpha.1

I have "me" custom function which returns a current user data using x-hasura-user-id session variable.
GraphQL query returns the data normally, but GraphQL subscription in hasura's console does not.

The function is
`CREATE
OR REPLACE FUNCTION public.me(hasura_session json) RETURNS SETOF users LANGUAGE sql STABLE AS $ function $
SELECT
  *
FROM
  users
WHERE
  id = hasura_session ->> 'x-hasura-user-id' $ function $`

A picture below is a result of GraphQL query.
<img width="1214" alt="screenshot 2021-03-14 16 50 46" src="https://user-images.githubusercontent.com/39161486/111061509-13d57480-84e7-11eb-8f29-3ccd43e4f235.png">

A picture below is a result of GraphQL subscription.
<img width="1214" alt="screenshot 2021-03-14 17 04 56" src="https://user-images.githubusercontent.com/39161486/111061591-7fb7dd00-84e7-11eb-969c-af9154cb9673.png">

For query using Apollo client from React, the function receives session variables.
<img width="1214" alt="screenshot 2021-03-14 17 14 28" src="https://user-images.githubusercontent.com/39161486/111061889-eb4e7a00-84e8-11eb-82fb-c876f4d3f791.png">

Is this normal? Is there a way to fix it? Thanks.

**Comment by 0x777** [comment]
Sorry about the delay in responding to this. This bug was introduced because of an optimization going wrong in 2.0. This is fixed in 63594e18281afc40c84a6f102ee68ff82c8dda41. It'll be part of the next release.
