### ISSUE TITLE
How  can i  create a  field  like  of  GEMETRY(Polygon, 4326)  from UI?

### ISSUE THREAD

**Issue by Barolina** [hasura/graphql-engine#6662]
How  can i  create a  field  like  of  GEOMETRY(Polygon, 4326)  from UI   with  type  of geometry?

**Comment by wwwdepot** [comment]
To create a geometry column in UI: enter `geometry` for column_type.

Enter geojson value when inserting a row:

```json
{
  "type": "Polygon",
  "coordinates": [
    [
      [0, 0],
      [0, 0],
      [0, 0],
      [0, 0]
    ]
  ]
}
```

**Comment by Barolina** [comment]
thanks , sorry,  how i can set SRID  from  UI?

**Comment by wwwdepot** [comment]
GeoJSON defaults for all epsg:4326 (WGS84). If you want to set it to something like 3857, just set the `crs` field

```jsonc
{
  "type": "Polygon",
  "coordinates": [
    [
      [0, 0],
      [0, 0],
      [0, 0]
    ]
  ],
  //   add this
  "crs": {
    "type": "name",
    "properties": {
      "name": "EPSG:3857"
    }
  }
}
```

**Comment by Barolina** [comment]
thanks
