### ISSUE TITLE
How can  i  delete a same  table from UI ?

### ISSUE THREAD

**Issue by Barolina** [hasura/graphql-engine#6663]

**Comment by amnaveenriaz** [comment]
please elaborate the issue with what you are trying to do, what you are expecting.

**Comment by Barolina** [comment]
If  i create  a some table   from UI  hasura and  then  i want to delete  this out UI hasura

**Comment by tirumaraiselvan** [comment]
Go to `Modify` tab of the table and scroll to the bottom.

![Screen Shot 2021-04-28 at 11 23 12 AM](https://user-images.githubusercontent.com/8663570/116353318-2c3dec00-a814-11eb-9210-88392a967db1.png)

**Comment by Barolina** [comment]
thanks  you
