### ISSUE TITLE
v2.0.0-alpha.4 - error connecting to mssql using env variable

### ISSUE THREAD

**Issue by istvan-fstg** [hasura/graphql-engine#6665]
Hi,
I set up the ms sql connection env variable in the kubernetes deployment file ex:
- name: MSSQL_MYDBNAME_DATABASE_URL
                value: "Driver=ODBC Driver 17 for SQL Server;Server=sqlserver;Database=mydbname;Uid=sa;Pwd=mypassword;"
When i try to connect from the ui to existing database with environment variable i get the following error:  
Add data source failed
parsing Text failed, expected String, but encountered Object.

With the above mentioned connection string i can connect using the Database url option. When i export the metadata, and try to set the connection for ms sql from env variable and reapply the metadata to the server i am again getting an error: 
time="2021-03-16T11:37:55+01:00" level=fatal msg="failed to apply metadata: cannot apply metadata on the database: {\n  \"path\": \"$.metadata.sources[1].configuration.connection_info\",\n  \"error\": \"key \\\"connection_string\\\" not found\",\n  \"code\": \"parse-failed\"\n}"

Is connecting to ms sql using env variables not implemented yet in v2.0.0-alpha.4 or am i making a mistake setting the env variable for mssql connection?

![Hasura ms sql env variable](https://user-images.githubusercontent.com/78965472/111300228-210e7280-8651-11eb-8bfe-3f4ca6bab692.png)

**Comment by 0x777** [comment]
@istvan-fstg, can you try running the latest alpha (`v2.0.0-alpha.7`)? I tried adding an MSSQL source through an environment variable and it works as expected. The exported metadata in my case looks as follows:
```json
{
  "version": 3,
  "sources": [
    {
      "name": "chinook",
      "kind": "mssql",
      "tables": [],
      "configuration": {
        "connection_info": {
          "connection_string": {
            "from_env": "CHINOOK_CONNECTION_STRING"
          },
          "pool_settings": {
            "idle_timeout": 5,
            "max_connections": 50
          }
        }
      }
    }
  ]
}
```
