### ISSUE TITLE
v2.0.0-alpha.4 - function hdb_catalog.check_violation(unknown) does not exist

### ISSUE THREAD

**Issue by alex-vladut** [hasura/graphql-engine#6669]
Since recently updating from `v1.3.3` to `v2.0.0-alpha.4` we noticed such errors happening randomly while performing an insert mutation:

```
GraphQL error
[
  {
    "extensions": {
      "internal": {
        "statement": "WITH \"users_tokens__mutation_result_alias\" AS (INSERT INTO \"users\".\"tokens\" ( \"updated_at\", \"expires_at\", \"created_at\", \"id\", \"user_id\" ) VALUES (DEFAULT, ($1)::timestamptz, DEFAULT, DEFAULT, ($2)::uuid)  RETURNING * , CASE WHEN 'true' THEN NULL ELSE \"hdb_catalog\".\"check_violation\"('insert check constraint failed')  END ), \"users_tokens__all_columns_alias\" AS (SELECT  \"id\" , \"expires_at\" , \"user_id\" , \"created_at\" , \"updated_at\"  FROM \"users_tokens__mutation_result_alias\"      ) SELECT  (SELECT  coalesce((json_agg(\"root\" )->0), 'null' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_1_e\"  FROM  (SELECT  \"_0_root.base\".\"id\" AS \"id\"       ) AS \"_1_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"users_tokens__all_columns_alias\" WHERE ('true')     ) AS \"_0_root.base\"      ) AS \"_2_root\"      )        ",
        "prepared": false,
        "error": {
          "exec_status": "FatalError",
          "hint": "No function matches the given name and argument types. You might need to add explicit type casts.",
          "message": "function hdb_catalog.check_violation(unknown) does not exist",
          "status_code": "42883",
          "description": null
        },
        "arguments": []
      },
      "path": "$.selectionSet.insert_users_tokens_one.args.object",
      "code": "unexpected"
    },
    "message": "database query error"
  }
]
{
  "query": "\n  mutation create_token($object: users_tokens_insert_input!) {\n    insert_users_tokens_one(object: $object) {\n      id\n    }\n  }\n",
  "variables": {
    "object": {
      "user_id": "e0b8e41a-03e1-4264-94a3-fdf5c5a496b8",
      "expires_at": "2021-04-13T08:07:05.974Z"
    }
  }
}
}
```

To give you a bit more context, there is a Hasura action (i.e. Lambda function) which invokes the Hasura generated insert mutation `insert_users_tokens_one` for which the error occurs (so this error happens on the backend in a Hasura action).
We figured out the function `hdb_catalog.check_violation` was removed with this migration script so it shouldn't be referenced anymore: https://github.com/hasura/graphql-engine/blob/29f2ddc28907c3d562ec15cf31579625047a9900/server/src-rsr/migrations/42_to_43.sql

Any insights into what might cause this issue would be great as it's currently impossible for use to reproduce it taking into account it is not clear what are the circumstances triggering it. Thanks in advance for your help 🙏

**Comment by dariocravero** [comment]
Related PR that brought the change in https://github.com/hasura/graphql-engine/pull/6123

**Comment by tirumaraiselvan** [comment]
@alex-vladut Is this still an issue? Our guess is that you may have had `v1.3.3` still running (along side v2.0). This is because the v2.0 implementation gets rid of hdb_catalog.check_violation entirely.

**Comment by alex-vladut** [comment]
@tirumaraiselvan Thanks for your reply. We checked at the time and it didn't seem more than one instance was running (with v2), but there may have been a glitch at the infra layer somewhere. We didn't encounter this issue after that anymore so we can close the issue
