### ISSUE TITLE
Postgresql SCRAM Authentication

### ISSUE THREAD

**Issue by mmillerbkg** [hasura/graphql-engine#6670]
Versions Tested: v2.0.0-alpha.4 (Problem version), v2.0.0-alpha.1 (Working version)
Postgresql Version: 13.2

I recently tried upgrading from v2.0.0-alpha.1 to v2.0.0-alpha.4, but I am unable to connect to my Postgresql instance. Here is the associated log entry. 

```json
{"type":"schema-sync-thread","timestamp":"2021-03-17T16:02:14.776+0000","level":"error","detail":{"thread_type":"listener","info":{"error":{"type":"query_error","info":{"internal":"SCRAM authentication requires libpq version 10 or above\n","path":"$","error":"connection error","code":"postgres-error"}}}}}
```
Using MD5 is an option, but SCRAM-SHA-256 is looking to be the preferred method for authentication.
[EDB "How to secure PostgreSQL"](https://www.enterprisedb.com/blog/how-to-secure-postgresql-security-hardening-best-practices-checklist-tips-encryption-authentication-vulnerabilities):
> md5 vs. SCRAM
>For many years md5 was the preferred hashing mechanism for use with Postgres, and though still widely used it's strongly recommended that users move to the scram-sha-256, where password authentication is required.
> ...
>If you need to support password authentication with a standalone Postgres server, you should be using scram-sha-256 as the authentication method. Do not use md5 in new deployments!

Thank you!

**Comment by codingkarthik** [comment]
Hey Folks, 

Thank you for reporting this issue. I've opened a PR which fixes this issue. Here's a docker image of the PR - `hasurabuild/graphql-engine:mono-pr-1380-9d068ac7f` , it will be great if you can test this out on your local setup where you have scram authentication and let me know.

**Comment by codingkarthik** [comment]
closed via https://github.com/hasura/graphql-engine/commit/7d630e8147eb116d4a6aa7b6afdc7313e3ca968f
