### ISSUE TITLE
Inherited roles doesn't work with null role

### ISSUE THREAD

**Issue by sfcgeorge** [hasura/graphql-engine#6672]
### Background

Our app has both public content and logged in (instructor) content. Our permissions webhook always returns "instructor" when logged in, or "public" when logged out. With the old Hasura permissions if a logged in instructor visited a public page they'd see nothing because the role wouldn't match. With inherited roles I've made the real roles "public" and "instructor_private" then added an inherited role "instructor" which inherits both of those. This seems ideal! (Thank you for the feature 😄) 

### What works

Query endpoints with both "public" and "instructor_private" roles set up work when accessed by the "instructor" inherited role. 

### Issue

Not all endpoints have a public permission, AKA "notifications" only make sense when logged in. So for those endpoints I only had the "instructor_private" role, but the "instructor" inherited role couldn't see them - they weren't in the schema.

It seems for an inherited role to be able to see an endpoint, ALL roles within it need some kind of permissions to be set. This is unintuitive to me and took hours to figure out what the problem was.

### Workarounds

For endpoints that we don't actually want to be public but need a public role we have to add one that:

* Has no column select permissions.
* For the row select permissions either:
  * "Without any checks" (every row will be accessible to public but all values will be `null`).
    * Probably also want to add a limit.
  * "With custom check" `{"id":{"_eq":0}}` (IDs start at 1 so no rows will be returned).

This feels a bit hacky and cumbersome. It's harder to write the fake custom check for UUIDs because they need to be valid.

I also tried just setting the public row limit to `0` but that doesn't work because inherited roles take the _minimum_ row limit (so instructors couldn't access any rows either). I think I'd prefer inherited roles to use the _maximim_ row limit so I've [opened another issue](https://github.com/hasura/graphql-engine/issues/6671).

### Suggestion

Remove the requirement that all roles within an inherited role must have permissions. The docs say an inherited role unions all rows of its sub-roles so I think it should be `instructor ∪ null = instructor` not `instructor ∪ null = null`.

**Comment by codingkarthik** [comment]
This is fixed in `v2.0.0-alpha.6`

**Comment by sfcgeorge** [comment]
@codingkarthik been working great, thank you so much 💖
