### ISSUE TITLE
hasura-cli: metadata apply ends with no change to the schema

### ISSUE THREAD

**Issue by benams** [hasura/graphql-engine#6675]
I try to apply metadata with hasura-cli (after I exported the metadata, and made changes to metadata/tables.yaml),  using the command `hasura metadata apply --admin-secret "<my_secret>" --endpoint "http://<myserver>:<hasura_port>"`, but I can notice no changes on the console(http://<myserver>:<hasura_port>/console).
Am I missing something?
(although I get a "INFO Metadata applied" message in the terminal, with no errors)

**Comment by scriptonist** [comment]
@benams that's not expected behavior. For a sanity check, can we make sure you are applying metadata to the correct Hasura instance?

**Comment by benams** [comment]
@scriptonist Unfortunately it is a private instance, which means I can't grant any kind of access. I can tell you that I checked many times, and I'm using the correct server address with the "endpoint" option (the same address I use in the "export" command).

**Comment by scriptonist** [comment]
@benams can you try following `metadata apply` with a `metadata reload` and report back if you see your changes on the console?

**Comment by tirumaraiselvan** [comment]
What is the expected schema change? Can you report the output of `hasura metadata apply --dry-run` ?

**Comment by rikinsk** [comment]
@benams I am closing this issue for now. Feel free to reopen this with some extra details
