### ISSUE TITLE
viewing related rows breaks for tables with json column and no pkey

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#6677]
![Screenshot from 2021-03-18 19-06-26](https://user-images.githubusercontent.com/54616969/111635023-156fa700-881d-11eb-9d46-2f1af8ff7560.png)

**Comment by rikinsk** [comment]
Cause:
While fetching unique identifying clauses for a row, if a primary key is not defined, all columns and their values are used to identify the row
Suggested solution:
If primary key is not defined, fallback to a unique if defined, else fallback to using all columns except json/jsonb columns

**Comment by beerose** [comment]
Fixed in https://github.com/hasura/graphql-engine-mono/pull/910
