### ISSUE TITLE
Microsoft SQL Event Triggers 

### ISSUE THREAD

**Issue by jmillerv** [hasura/graphql-engine#6679]
I tried hooking up events to the Microsoft SQL instance I have connected but it's only giving me Postgres options. My guess is that it's not supported yet, but wanted to check if I was missing something. 

Currently using alpha.5

If I'm not missing anything, are there plans to support this in the 2.0 stable release?

**Comment by jmillerv** [comment]
Commenting here to see if there's any updates. We would prefer to use Hasura but due to timelines we may need to roll our own solution. Anyone know timelines for this feature or if support for Event Triggers is confirmed in the roadmap?

**Comment by 0x777** [comment]
@jmillerv  
> Anyone know timelines for this feature or if support for Event Triggers is confirmed in the roadmap?

Event triggers is definitely on our roadmap but not for 2.0 stable release. It is scheduled for the first minor release after 2.0 stable, so it should be part of 2.1. Unfortunately, we can't yet promise the release date for 2.1 but it should be within 2 weeks of 2.0 stable release.

**Comment by jmillerv** [comment]
> @jmillerv
> 
> > Anyone know timelines for this feature or if support for Event Triggers is confirmed in the roadmap?
> 
> Event triggers is definitely on our roadmap but not for 2.0 stable release. It is scheduled for the first minor release after 2.0 stable, so it should be part of 2.1. Unfortunately, we can't yet promise the release date for 2.1 but it should be within 2 weeks of 2.0 stable release.

Thanks! That's very good to know. Looking forward to it!
