### ISSUE TITLE
cli: installation script fails in M1 Macs

### ISSUE THREAD

**Issue by go4cas** [hasura/graphql-engine#6680]
When trying to install the `hasura-cli` using the command, open an MacBook with M1 chip:
```bash
curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
```
I get the following error:
```bash
curl: (22) The requested URL returned error: 404
FAILED> failed executing: curl -L# -f -o /tmp/cli-hasura-darwin-386 https://github.com/hasura/graphql-engine/releases/download/v1.3.3/cli-hasura-darwin-386
```

Using the nom package works fine.

**Comment by go4cas** [comment]
@scriptonist ... any idea when this fix will make it into a production release?

**Comment by scriptonist** [comment]
@go4cas does `brew install hasura` work for you?

**Comment by scriptonist** [comment]
Also, while this get's fixed you can download the binary from [github releases](https://github.com/hasura/graphql-engine/releases). Also, a script like the following might also help.
```
curl -LO https://github.com/hasura/graphql-engine/releases/download/v2.0.0-alpha.7/cli-hasura-darwin-amd64 && chmod +x cli-hasura-darwin-amd64
sudo mv cli-hasura-darwin-amd64 /usr/local/bin/hasura
```

**Comment by go4cas** [comment]
@scriptonist ... `brew install worked` for the cli, but only after I had to reinstall brew for ARM64.

In case anyone else runs into Apple MacBook M1 (ARM64) issues with cli migration images, the community contributed image (fedormelexin/graphql-engine-arm64:v2.0.0-alpha.7.cli-migrations-v2) works 100%. Thanks to @melehin.

**Comment by cpv123** [comment]
Had the same issue and made it working by running the install script locally with a small change...

<img width="887" alt="Screenshot 2564-04-14 at 15 18 39" src="https://user-images.githubusercontent.com/35846795/114678544-87acac00-9d35-11eb-8a73-156298f4355a.png">

I haven't raised a PR because I have no idea if what I've done is safe for all installs - I just noticed that it would work on my M1 Mac where `uname -m` --> `arm64 `

FYI the script is here: `https://github.com/hasura/graphql-engine/blob/master/cli/get.sh`

**Comment by oz-vynyl** [comment]
As a temporary workaround you can set Terminal to **open using Rosetta** and the original command should work.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/48929270/115076613-a932a280-9eb1-11eb-87aa-cc5bdd7e22ea.png">

**Comment by scriptonist** [comment]
@go4cas we have a short term fix in the installation script here https://github.com/hasura/graphql-engine/blob/master/cli/get.sh, can you verify if it works as expected?

**Comment by rsaphala** [comment]
I got this error with the above link @scriptonist 

```
curl -L https://github.com/hasura/graphql-engine/blob/master/cli/get.sh | bash

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0bash: line 7: syntax error near unexpected token `newline'
bash: line 7: `<!DOCTYPE html>'
100 34129    0 34129    0     0  47533      0 --:--:-- --:--:-- --:--:-- 47467
curl: (23) Failed writing body (0 != 1361)
```

**Comment by melehin** [comment]
@rsaphala
Use https://raw.githubusercontent.com/hasura/graphql-engine/master/cli/get.sh

![image](https://user-images.githubusercontent.com/3829167/118470839-839ef000-b720-11eb-9d31-db2d65cc931b.png)

**Comment by scriptonist** [comment]
fixed in https://github.com/hasura/graphql-engine/commit/8a6f3f7e9dbf6f029d7fc8df5e305d8aab918c7a
