### ISSUE TITLE
v2.0.0-alpha.4 - "cannot read config: invalid config version" with Github actions

### ISSUE THREAD

**Issue by Hubiwan** [hasura/graphql-engine#6681]
I upgraded Hasura CLI on my machine to v2.0.0-alpha.4 and hence config.yml to v3.

While the sync between Hasura console and local metadata & migration files work locally (e.g. dev mode), the process fails when trying to do the same with Github actions for a deployed cloud instance (e.g. prod mode).

For example, if I run this:
```
//...
steps:
      - uses: actions/checkout@v2

      - name: Install hasura cli
        run: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      - name: Update hasura cli for reading config v3
        run: hasura update-cli --version v2.0.0-alpha.4

      - name: Apply metadata
        working-directory: server/cli
        run: hasura metadata apply --endpoint ${{ secrets.HASURA_GRAPHQL_ENDPOINT }} --admin- 
        secret ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
//...
```

the update fails with the following permission error message:
```
Run hasura update-cli --version v2.0.0-alpha.4
{"level":"info","msg":"Updating cli to v2.0.0-alpha.4... ","time":"2021-03-19T07:57:11Z"}
time="2021-03-19T07:57:11Z" level=fatal msg="apply update: download asset: creating new binary file: open /usr/local/bin/.hasura.new: permission denied"
Error: Process completed with exit code 1.
```

Also tried to not update the CLI in actions sequence i.e. directly applying metadata, still I got an error but this time saying CLI cannot read the config version:
```
{"level":"info","msg":"a new pre-release version is available:\n- v2.0.0-alpha.5 (changelog: https://github.com/hasura/graphql-engine/releases/tag/v2.0.0-alpha.5)\nto update cli to this version, execute:\n\n  hasura update-cli --version v2.0.0-alpha.5\n\n","time":"2021-03-19T07:55:51Z"}
time="2021-03-19T07:55:51Z" level=fatal msg="cannot read config: invalid config version"
Error: Process completed with exit code 1.
```

How are we supposed to make v3 config work with GitHub actions given the CLI update permission is denied? Has anyone had the same issue? Thank you v much.

**Comment by scriptnull** [comment]
@Hubiwan could you try adding `sudo` before the `hasura update-cli` command? (that should probably fix the permission denied error)

```yaml
//...
steps:
      - uses: actions/checkout@v2

      - name: Install hasura cli
        run: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      - name: Update hasura cli for reading config v3
        run: sudo hasura update-cli --version v2.0.0-alpha.4

      - name: Apply metadata
        working-directory: server/cli
        run: hasura metadata apply --endpoint ${{ secrets.HASURA_GRAPHQL_ENDPOINT }} --admin- 
        secret ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
//...
```

**Comment by Hubiwan** [comment]
@scriptnull Hey Vishnu - It works now, thanks a lot.
I had not thought about forcing it with `sudo` indeed, sorry about that.

**Comment by SrihariharaanS** [comment]
@scriptnull msg="cannot read config: unable to parse server endpoint: parse \"--admin-secret\": invalid URI for request" 
I'm getting this error

**Comment by scriptnull** [comment]
@SrihariharaanS This might be due to the value of ` --endpoint` being empty.  Are you sure if you had set the `HASURA_GRAPHQL_ENDPOINT` secret in GitHub actions settings?

**Comment by SrihariharaanS** [comment]
@scriptnull Hey it works, Thanks.
