### ISSUE TITLE
cli: fix changelog hyperlink in the log message

### ISSUE THREAD

**Issue by scriptnull** [hasura/graphql-engine#6682]
Whenever a new version of Hasura is available, the cli logs a message about it. Here is an image from a CI log showing such a message.

![image](https://user-images.githubusercontent.com/4211715/111762876-8370a880-88c7-11eb-91e9-1c893daa130e.png)

Most CI providers automatically make the changelog hyperlink clickable. When the user clicks the link, it is directing them to

```
https://github.com/hasura/graphql-engine/releases/tag/v2.0.0-alpha.5)\nto
```

instead of 

```
https://github.com/hasura/graphql-engine/releases/tag/v2.0.0-alpha.5
```

The fix is to remove the unnecessary characters appended at the end of the hyperlink.

**Comment by Soundug** [comment]
@scriptnull I would like to contribute to this project and I'm new to open source. Can I work on this?

**Comment by scriptnull** [comment]
Yeah, sure :+1: Go for it! :100:

**Comment by that-coder** [comment]
@scriptnull Is the issue fixed? Or Can I take this one?
