### ISSUE TITLE
v2.0.0-alpha.5: issue applying metadata  to hasura cloud instance ("source with name \"default\" [does not exist/is inconsistent]")

### ISSUE THREAD

**Issue by Hubiwan** [hasura/graphql-engine#6685]
Hi team - I am currently using Hasura CLI v2.0.0-alpha.5 and having issue to apply local metadata / migration files to the remote Hasura cloud instance as it keeps saying that `"source with name \"default\" does not exist"`.

I tried the following according to the config v3 documentation as well as other raised issues:

- create local metadata and migration files with `hasura init`command
- launch the local console with `hasura console` (at this stage, the local postgres DB is called `default` by default with a `public` schema inside it, not sure if we can change it or if we should not change it, for now I keep it unchanged but just asking out of curiosity)
- create a random test table, so far so good

Now I want to apply this change to the Hasura cloud instance
- when creating a new DB via Heroku, it shows a fancy name so I removed it and re-added it by renaming it `default` so that the `database-name` matches with my local metadata/migration files, here is a screenshot of the cloud instance:
<img width="530" alt="screenshot_1" src="https://user-images.githubusercontent.com/50402245/111869172-53381100-897e-11eb-91a6-703870531e5b.png">
<img width="658" alt="screenshot_2" src="https://user-images.githubusercontent.com/50402245/111869191-6a76fe80-897e-11eb-80cd-e2ca671e693d.png">

- it matches with local files names:
<img width="329" alt="screenshot_3" src="https://user-images.githubusercontent.com/50402245/111869232-985c4300-897e-11eb-817f-65a49b96877c.png">

- but still, when applying the local changes to the cloud instance I get the following error message:
<img width="788" alt="screenshot_4" src="https://user-images.githubusercontent.com/50402245/111869402-921a9680-897f-11eb-92c8-01f308073e98.png">

Highly appreciate if someone can help, thank you very much.

**Comment by Hubiwan** [comment]
Also realised that while applying metadata does not work, applying migrations to cloud instance still work and end up as usual with the untracked table (e.g. in case of a new table creation) showing up in the cloud instance. It does not solve the point raised above by definitely confuses me, especially given what documentation says re. applying metadata before migrations:

- ["Changes needed in existing workflows"](https://hasura.io/docs/latest/graphql/core/migrations/upgrade-v3.html)

Not sure how all of this ties together to get proper local/prod workflow.

**Comment by rikinsk** [comment]
Hey. This seems odd. your set up seems fine.
Would it be possible to share the contents of your `metadata/databases/database.yaml file` _(post hiding anything sensitive of course)_. Also could you share the current metadata of the hasura instance. You can just export it as a json from the `Console -> Settings -> Metadata -> Export metadata`. Just trying to confirm the config we have here.

**Comment by Hubiwan** [comment]
Hey sure, no problem, nothing confidential on my end (only running some pre-tests).

- Please see below the content of `metadata/databases/database.yaml`:

```bash
- name: default
  kind: postgres
  configuration:
    connection_info:
      database_url:
        from_env: HASURA_GRAPHQL_DATABASE_URL
      pool_settings:
        idle_timeout: 180
        max_connections: 50
        retries: 1
  tables: "!include default/tables/tables.yaml"
  functions: "!include default/functions/functions.yaml"
```

- Please see below the content of database.yaml from cloud instance:

```bash
{
  "version": 3,
  "sources": [
    {
      "name": "default",
      "kind": "postgres",
      "tables": [],
      "configuration": {
        "connection_info": {
          "database_url": {
            "from_env": "HEROKU_DATABASE_URL"
          },
          "pool_settings": {}
        }
      }
    }
  ]
}
```

I also just tried again to apply metadata (w. config v3, alpha.5) and I get a slightly different error message i.e. with `source with name "default" is inconsistent` instead of `source with name "default" does not exist` previously:
```bash
FATA[0004] failed to apply metadata: cannot apply metadata on the database: {
  "path": "$.args",
  "error": "source with name \"default\" is inconsistent",
  "code": "unexpected"
} 
```

Thanks a lot

**Comment by rikinsk** [comment]
@Hubiwan Sorry for the delay. Your configurration seems quite correct to me except for one detail. Can you confirm which env var you have the database url stored in? As you created the Heroku db on the cloud, the env var must be `HEROKU_DATABASE_URL`. But in the metadata file we seem to have `HASURA_GRAPHQL_DATABASE_URL` which I presume comes from the earlier configuration you had. Could you update the metadata file with the `HEROKU_DATABASE_URL` env var you have in cloud and attempt to apply.

**Comment by Hubiwan** [comment]
@rikinsk Hey no worries. Thank you for your reply. I just tried and it works indeed when I replace the value of `HASURA_GRAPHQL_DATABASE_URL` in .env file with the value of my cloud instance URL.
But then, is there a way to avoid having to change it manually whenever I choose to apply it on cloud instance or local dockerized postgres instance? Thanks again

**Comment by Hubiwan** [comment]
Ok just got it work actually. I think in case of several databases or easy ci/cd with say different .env file we only have to remove the `HASURA_GRAPHQL_DATABASE_URL` from the docker-compose file and add our own custom var + making sure names are identical between local and remote instances. Tks again and closing the issue.
