### ISSUE TITLE
Do not generate mutation fields for materialized views 

### ISSUE THREAD

**Issue by mirzap** [hasura/graphql-engine#6688]
Setting a custom GraphQL root `Select by PK` for a materialized view doesn't work. For `Select` and `Select Aggregate` everything is OK. This issue exists on 1.x and 2.x

Also, shouldn't mutations be disabled for materialized view?

**Comment by paritosh-08** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/8c05efb6d97eb06ecc1fb7dcf66a7b692e817a61
