### ISSUE TITLE
add support for relationships in update mutations

### ISSUE THREAD

**Issue by patcito** [hasura/graphql-engine#669]
It would be nice to have support for relationships in update mutations like there is in insert so that it automatically delete/add new relationships.

My use case is if a Post table has tags ["x","y","z"] as a relationship in a tag_posts table, if I do an update mutation on post with just tags: ["x","y"] it would be nice if "z" could be deleted automatically from tag_posts table, if you see what I mean. Or maybe add an _unset operator so that we could do _set: {tags: ["x","y"]}, _unset: {tags: ["z"]} to delete "z". That would be more explicit and avoid having people deleting things without knowing. Maybe have an option to _unset all tags that are not set such as {_unsetAllNonSet: {tags: true}}, so in this case that would delete "z".

**Comment by nolandg** [comment]
I've described how Prisma handles this in https://github.com/hasura/graphql-engine/issues/1573#issuecomment-495963136

**Comment by bkstorm** [comment]
We can learn how Prisma handles this problem (described by @nolandg), they do very well, I think.

**Comment by THPubs** [comment]
Any ETA for this feature?

**Comment by LeoMartinDev** [comment]
So, is this still on track ? This feature is clearly lacking

**Comment by brianjd** [comment]
@coco98 Is there a timeline for this? I'm currently working on a problem created by the lack of this feature.

**Comment by rccc** [comment]
@marionschleifer @coco98 

3 years after this issue is still open, it is a shame that such a features is still not implemented. 

Can we ask a Hasura boss for this ?

**Comment by marionschleifer** [comment]
@rccc this is definitely on our roadmap, and we will try to pick it up soon.

An [RFC](https://github.com/hasura/graphql-engine/pull/3852) has already been created for it.

**Comment by erikkjell** [comment]
@marionschleifer is there an update on this?

**Comment by rccc** [comment]
@marionschleifer it seems this issue is the same as https://github.com/hasura/graphql-engine/issues/1573

**Comment by sassela** [comment]
Thanks for this feature request! Closing this issue to deduplicate things, in favour of https://github.com/hasura/graphql-engine/issues/1573
