### ISSUE TITLE
Remote schema permission error: expected default value of input value to be null but received ""

### ISSUE THREAD

**Issue by creatorrr** [hasura/graphql-engine#6692]
Version: _2.0.0-alpha.5_
Mode: _console_
Steps to reproduce:
- Enable remote schema permissions
- Add permissions to a remote schema query with an input object with default values using the console

Schema:
```graphql
type Query {
    callMatchIntent(
        possible_intents: [String!]
        input: String
        similarity_threshold: Float=0.8
    )  {...}
}
```

Error:
```md
validation for the given role-based schema failed for the following reasons:
 • expected default value of input value: "possible_intents"of input object "callMatchIntent" to be null but received
 • expected default value of input value: "input"of input object "callMatchIntent" to be null but received
 • expected default value of input value: "similarity_threshold"of input object "callMatchIntent" to be 0.8 but recieved
```

![Screenshot from 2021-03-22 15-33-16](https://user-images.githubusercontent.com/931887/111974573-8963c500-8b25-11eb-92f7-1ff17d5d746d.png)

**Comment by beerose** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/0f7c273873d4c5c4913399868a339c8af7192556
