### ISSUE TITLE
Memory usage get very high for updating the meta-data

### ISSUE THREAD

**Issue by zhao-shan** [hasura/graphql-engine#6701]
We are using multiple-schema in one Postgres instance to manage the multi-tenant. 
New tenant meta-data has been updated by calling /v1/metadata/  replace_metadata.
We found one tenant metadata will cost almost 450-500M memory.  So when we added 3rd tenant, the on-peak of memory will be around 1.6G, after that, the memory will be down to 1.1G.  If the POD of Hasura only have 1.8G memory,  then the 4th tenant should be supported, but when 4th tenant has been created and tried to update the meta-data, then the memory usage will be grown up to 1.8 immediately. Then the Hasura will be restarted automatically and continue failing for restarting. 

So what's exactly the memory cost for holding the metadata in Hasura cache.  Does Hasura have strategy to persist the catch to disk in order to prevent the Hasura crash because of huge metadata?

**Comment by AndresPrez** [comment]
Any updates. Is there a way to control how hasura caches its metadata?

**Comment by 24601** [comment]
Having this issue, too. See #7077 and #4077

**Comment by manasag** [comment]
Hi, Please try the latest 2.15 release, which has a bunch of improvements. Feel free to reopen this issue, if similar behaviour persists in this release too.

We are working to continually make improvements around memory usage. As a long term strategy, persisting metadata cache on disk make sense, but its not trivial to achieve without significant work on how internally metadata cache is represented in Haskell code.

**Comment by 24601** [comment]
@manasag - funny you mention that, we tried just that yesterday and the problem is as bad as ever. In fact, to do some MD update calls, we had to increase the memory limit of the Hasura container to 32GB to keep it from dying nearly every MD call. 

There's definitely a bad memory management bug somewhere in the stack when MD calls around tracking tables are made against multiple databases in succession.

**Comment by vst** [comment]
> @manasag - funny you mention that, we tried just that yesterday and the problem is as bad as ever. In fact, to do some MD update calls, we had to increase the memory limit of the Hasura container to 32GB to keep it from dying nearly every MD call.

Confirming that v2.15.2 did not solve large memory peaks during metadata updates.

In our case, typical runtime memory usage is slightly less than 1GB (which is itself too much for us given our usecase), but metadata updates peak to 3GB. 

As a feedback, all in all, this causes concerns in our team to add further functionalities to Hasura which may result in bigger metadata, therefore need for larger memory provisions. We are now relying on auxiliary solutions for new functionalities to sideline Hasura.

**Comment by 24601** [comment]
> > @manasag - funny you mention that, we tried just that yesterday and the problem is as bad as ever. In fact, to do some MD update calls, we had to increase the memory limit of the Hasura container to 32GB to keep it from dying nearly every MD call.
> 
> Confirming that v2.15.2 did not solve large memory peaks during metadata updates.
> 
> In our case, typical runtime memory usage is slightly less than 1GB (which is itself too much for us given our usecase), but metadata updates peak to 3GB.
> 
> As a feedback, all in all, this causes concerns in our team to add further functionalities to Hasura which may result in bigger metadata, therefore need for larger memory provisions. We are now relying on auxiliary solutions for new functionalities to sideline Hasura.

Yup, we are totally removing any use of Hasura events and moving all event handling in Hasura to a PG->Kafka Connect + Debezium->Kafka->FaaS solution b/c the Hasura eventing is another disaster of an implementation at scale. 

The MD updates and RAM usage also continue to be scary. Our goal is to get Hasura down to only the "unification" and Access Control layer if at all possible, at which point we will undoubtedly have to start asking ourselves the question of "Beyond legacy code/arch, where does Hasura fit in our stack when frameworks like GraphQL Mesh and/or Apollo exist?". 

We love Hasura, don't get us wrong, but we had a really, really disastrous adventure with Hasura Cloud and brought it back in house (so not like we aren't willing to pay and pay good money for services, but the support and core product has to be there to justify it, and waking up every week to an upgrade gone bad on Hasura Cloud we didn't even ask for was just a no-go and we had to bring production back in house). 

And support doesn't matter when the containers get OOM killed: we could talk to support all we want, it isn't going to make our production environment more reliable until the memory management in the core code is truly fixed. 

Even our containers with 8GB RAM are getting OOM'ed. It's out of control (on v2.17.0).

**Comment by mbrevda** [comment]
Been seeing this, too, on metadata deployment with multiple databases on version 2.19.0. This is happening when calling replace_metadata and often forces our product instance offline - to the extent that we are considering adding an additional instance just for updating metadata.

Is there a better way of going about replacing metadata? Are there unadvertised limits in place? We are planning on adding hundreds more databases to a single instance - but wondering if Hasura is built for real scale...


Can we get this issue reopened until the issue is fixed @manasag?
