### ISSUE TITLE
Remote schema relationship query fails if all argument in remote query is mapped with tables columns

### ISSUE THREAD

**Issue by lohiaad** [hasura/graphql-engine#6703]
**Current Behaviour** 
In my remote schema relationship, i have mapped all arguments of remote query with the columns from postgres table.

<img width="591" alt="Screen Shot 2021-03-23 at 7 57 18 PM" src="https://user-images.githubusercontent.com/6629241/112162423-0b311c80-8c12-11eb-85ac-d8694ac1b2af.png">

GQL query - 
`{
  vam_approval_center {
    initiated_by {
      name
    }
  }
}
`

Response
`
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.vam_approval_center.selectionSet.initiated_by.args",
        "code": "validation-failed"
      },
      "message": "the required argument \"userParams\" is missing"
    }
  ]
}
`

Because we have mapped all arguments of remote query hasura creates empty input object called 
`userParams: UserInput_remote_rel_vam_approval_centerinitiated_by!` and empty objects are not allowed in schema language

**Expected Behaviour**
hasura engine shouldn't create empty input object

**Comment by codingkarthik** [comment]
related https://github.com/hasura/graphql-engine/issues/6029

**Comment by tirumaraiselvan** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/84ed74aba1253ef938244700bf633d7715f5de8a
