### ISSUE TITLE
Error: Invalid or incomplete schema, unknown type: query_root when using Hasura

### ISSUE THREAD

**Issue by austinrivas** [hasura/graphql-engine#6705]
The issue is described in more detail here:

https://github.com/anvilco/spectaql/issues/5

In summary we are attempting to use spectaql to generate api documentation from our hasura api using the introspection query.

It seems like the `graphql` library is having a hard time parsing the `Query` and `Mutation` root types.

Has anyone else experienced this error or used hasura in combination with documentation generators like spectaql?

**Comment by tirumaraiselvan** [comment]
The name of the query root and mutation root types in Hasura are `query_root` and `mutation_root` respectively. This can be defined using the `schema` definition  as defined in Graphql spec: https://spec.graphql.org/June2018/#example-e2969

I think the underlying library should get the types from inferring this.
