### ISSUE TITLE
Dollar sign is not valid in a column name

### ISSUE THREAD

**Issue by MikeyTheFluker** [hasura/graphql-engine#6712]
Some of our tables in SQL server have columns that start with $
Hasura doesn't want to add these tables
"cannot include $site in the GraphQL Schema because it is not a valid GRAPHQL identifier"

Not sure if this is a bug, we can rename those columns, but thought I'd mention it

**Comment by rikinsk** [comment]
Yes. This is in accordance with the graphql spec.

Closing this as its known behaviour
