### ISSUE TITLE
SQL Function (to aggregate nested table) for "Hasura computed field" can not be tracking: Tracking items failed ... reasons: the function does not return a "COMPOSITE" type AND the function does not return a table

### ISSUE THREAD

**Issue by GreenRobot777** [hasura/graphql-engine#6715]
```
TABLE A
agency.task

id           name        
-----------  ----------  
1            "Task 1"    
2            "Task 2"    
3            "Task 3"    


TABLE B
agency.time_entry

id           task__id    duration   
-----------  ----------  ----------  
1            "1"         2            
2            "1"         8            

3            "2"         20            
4            "2"         2             

5            "3"         1            


New TABLE A with Hasura computed field 'duration_sum':
agency.task

id           name        duration_sum   
-----------  ----------  -------------  
1            "Task 1"    10             
2            "Task 2"    22             
3            "Task 3"    1              

```

```sql
CREATE OR REPLACE FUNCTION agency.task_duration_sum(task_row agency.task)
RETURNS NUMERIC AS $$
    SELECT SUM( duration )
    FROM agency.time_entry
    WHERE task__id = task_row.id
$$ LANGUAGE sql STABLE;
```

☑️ Track this (See supported functions requirements)
☑️ Cascade metadata

Returns

```
Tracking items failed
in function "agency.task_duration_function": the function "agency.task_duration_function"
cannot be tracked for the following reasons:
• the function does not return a "COMPOSITE" type
• the function does not return a table
```

Of course, without _tracking_ i can not access this new field from GraphQL.

**Questions:**
- How to fix SQL function?
- Does it exist other solution to aggregate "nested" table data and put it as a value of "parent" table field?

I found only this alternative solution, but whis is query, not field:
[Postgres: Extend schema with SQL functions / Aggregations on custom functions](https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/custom-functions.html#aggregations-on-custom-functions)

**Comment by antonblockchain** [comment]
Добрый день Александр.
https://freelance.habr.com/tasks/356205
Готов сделать, ошибку вижу в postgresql

Оплата по факту выполненной работы на карту сбера.
(если 500 рублей жалко, оставьте просто отзыв не надо пропадать без отзыва)
Звоните сразу там дел на 5-10 минут )

telegram @antonchain

**Comment by rikinsk** [comment]
@GreenRobot777 Hi. If you are trying to add the function as a computed field to a table you do not need to track the function. Just create the function with the `Track this` unchecked and then you can add it as a computed field from the table modify page

 [Tracking a function](https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/custom-functions.html) exposes it as a root field and has different requirements than those needed to add a function as a computed field.

**Comment by susannahameyer** [comment]
Is this still possible? When I run a query to create a function and leave those boxes unchecked, it won't appear in the dropdown when going to add a computed field.
