### ISSUE TITLE
Can permissions check use non-column / hard coded value?

### ISSUE THREAD

**Issue by gabrieljoelc** [hasura/graphql-engine#6720]
I am building a feature that would force frontend users to update their mobile app to the latest version.

1. Add new "version" claim requirement on all `user` role database permissions
1. Add ability to set and send "version" in claim in all graphql requests

All old versions of the app without these updates will be usable until this update.

I would like to do something like this:

```json
{
  "user": {
    "_and": [
      {
        "auth_id": {
          "_eq": "X-Hasura-User-Id"
        }
      },
      {
        "v1.0": {
          "_eq": "X-Hasura-Version"
        }
      }
    ]
  }
}
```

I can't find anything in the documentation that shows me how to do this. Can I only do this by creating a `versions` table that `users` joins to?

**Comment by tirumaraiselvan** [comment]
Currently, not possible. Tracking this here: https://github.com/hasura/graphql-engine/issues/3685
