### ISSUE TITLE
Documentation does not state anything about dependency behaviour when using Remote Schemas

### ISSUE THREAD

**Issue by Mousaka** [hasura/graphql-engine#6727]
### Scenario
We have Hasura v.1.3.3 running in production and we also have a new graphql service up that we want to use.
I can easily add the graphql service as a "Remote Schema" and combine them somewhat seamlessly which is great.

But I noticed that this other Remote Schema is now a dependency for me to be able to start/restart my Hasura service since it just seems to crash if the Remote Schema is down. 

In my case, I don't have any relations between local schemas and the remote one and I wish my service could still provide some functionality while the Remote Schema is down.

### Problem
I have so far not found anything about Hasura dependency behaviour when using Remote Schemas in the documentation so something about this should probably be added.

Things I would like to get an answer to in the documentation (and answer already now in the comments if you know):
* What is the behaviour of Hasura if the Remote suddenly goes down?
* What is the behaviour when starting Hasura and the Remote is down? (seems to be that it crashes)
* Is there any way to use Remote Schema without being 100% dependent on the Remote being up?

### Solution
Add information in Hasura Documentation about Hasuras behaviour when a Remote is down and different possible strategies.

**Comment by happyfloat** [comment]
I noticed the same recently... hasura said my metadata is inconsistent and needs to be resolved. It was looking for the /graphql endpoint of my remote schema, so I had to expose the playground to that URL in order to return something non 404... very strange.

**Comment by khan297** [comment]
.

**Comment by tirumaraiselvan** [comment]
With v2.0, remote schema is not a hard-dependency for starting up. If your remote schema is unreachable, then it will continue to start and mark the remote schema as inconsistent.

**Comment by namoscato** [comment]
> With v2.0, remote schema is not a hard-dependency for starting up.

@tirumaraiselvan, is this actually true? We're seeing the same behavior on v2.2.0.

For example, restarting Hasura while the remote schema is down results in a fatal error:

<details>
<summary>error applying metadata</summary>

```json
{
    "internal": [
        {
            "definition": {
                "definition": {
                    "timeout_seconds": 60,
                    "url_from_env": "HASURA_ACTIONS_API_SERVER_ENDPOINT",
                    "forward_client_headers": true
                },
                "remote_relationships": [],
                "name": "actions_api",
                "permissions": [],
                "comment": null
            },
            "reason": "Inconsistent object: HTTP exception occurred while sending the request to http://host.docker.internal:3001/graphql",
            "name": "remote_schema actions_api",
            "type": "remote_schema",
            "message": {
                "message": "ConnectionFailure Network.Socket.connect: <socket: 46>: does not exist (Connection refused)",
                "request": {
                    "proxy": null,
                    "secure": false,
                    "path": "/graphql",
                    "responseTimeout": "ResponseTimeoutMicro 60000000",
                    "method": "POST",
                    "host": "host.docker.internal",
                    "requestVersion": "HTTP/1.1",
                    "redirectCount": "10",
                    "port": "3001"
                }
            }
        }
    ],
    "path": "$.args",
    "error": "cannot continue due to inconsistent metadata",
    "code": "unexpected"
}
```

</details>

**Comment by namoscato** [comment]
_Following up here for posterity..._

This behavior specifically changed with [config v3](https://hasura.io/docs/latest/graphql/core/migrations/upgrade-v3.html#changes-needed-in-existing-workflows), which explains the confusion in my previous comment. Graceful remote schema degradation works as expected, and I imagine this issue can be closed.

/cc @BenoitRanque

**Comment by BenoitRanque** [comment]
@namoscato thanks for cross posting here. Closing this issue
