### ISSUE TITLE
[v2.0.0-alpha.6] SQL Server dbo schema not loaded

### ISSUE THREAD

**Issue by ccalvarez** [hasura/graphql-engine#6730]
Hi, 

I'm connecting Hasura v2.0.0-alpha.6 to an on-premises SQL Server 2016 (version 13.0.5865.1) using  authentication mode (user/password).

The connection string is:  `Driver={ODBC Driver 17 for SQL Server};Server=myServerIPAddress;Database=UtiCaro;UID=hasurauser;PWD=thepassword;
`

The SQL Server user "hasurauser" has  default schema:  `dbo`

![image](https://user-images.githubusercontent.com/2665104/113039708-35746400-9155-11eb-9226-77a3ea8aa3a9.png)

Under the `dbo` schema I have created a table named `Cargos`:

![image](https://user-images.githubusercontent.com/2665104/113040043-913eed00-9155-11eb-8a18-f0380559fe23.png)

What happens is, when the connection to SQL Server is added in the Hasura Console, the `dbo` schema and tables under it are not loaded.  A "public" schema is loaded instead, and it does not contain my table:

![image](https://user-images.githubusercontent.com/2665104/113040430-001c4600-9156-11eb-8e52-c661b05e8ab0.png)

![image](https://user-images.githubusercontent.com/2665104/113063755-0f5dbc80-9173-11eb-8b6a-a1efd4efe235.png)

I'm confused because in the Hasura 2.0 launch demo, Tanmai Gopal adds a connection to a SQL Server instance, and the `dbo` schema is loaded inmediately, with all the tables under the schema available to be tracked:

![image](https://user-images.githubusercontent.com/2665104/113040767-6c974500-9156-11eb-8377-443344e3639b.png)

Could someone help me identify what might be missing?

Thank you.

**Comment by ccalvarez** [comment]
Update:

I've just tried the same on an Azure SQL Database instance, and it did load the `dbo` schema as expected:

![image](https://user-images.githubusercontent.com/2665104/113063018-df61e980-9171-11eb-9144-9a28d1050b3b.png)


![image](https://user-images.githubusercontent.com/2665104/113063203-251eb200-9172-11eb-9e8c-deb120563141.png)

![image](https://user-images.githubusercontent.com/2665104/113063415-8181d180-9172-11eb-8485-9858af609580.png)

**Comment by 0x777** [comment]
@ccalvarez I deployed SQL Server 2016 on Azure and added it as a source on `v2.0.0-alpha.7`. The console shows me the `dbo` schema and lets me track all tables and relationships. Running `SELECT @@VERSION;` from 'SQL' section has the following output:
```
Microsoft SQL Server 2016 (SP2-CU16) (KB5000645) - 13.0.5882.1 (X64) 
	Jan 25 2021 21:40:32 
	Copyright (c) Microsoft Corporation
	Express Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)
```

Can you head to `SQL` section and share the output of the following query when connected to sql server 2016?
```sql
select s.name, s.schema_id from sys.schemas s;
```

**Comment by cdkisa** [comment]
Hi,

Having exact same issue (mostly). Noticed in most examples, for connection string, the user is SA. Does the SQL user need to be a database admin? Is it possible to have a read-only user with schema access?

Sql User with dbo schema access
![image](https://user-images.githubusercontent.com/3293036/115814320-0cd93600-a3b2-11eb-8113-eb588b28924d.png)

Plenty of tables under the dbo schema
![image](https://user-images.githubusercontent.com/3293036/115814337-14004400-a3b2-11eb-8280-08063f8ef672.png)

Hasura about
![image](https://user-images.githubusercontent.com/3293036/115814400-32fed600-a3b2-11eb-9ef4-4d01a02ce438.png)

Difference from @ccalvarez is that I don't see anything and it remains in "Loading..." state forever
![image](https://user-images.githubusercontent.com/3293036/115814448-490c9680-a3b2-11eb-9eb1-0494681fcabd.png)

Using Sql Mgmt connected as user....
![image](https://user-images.githubusercontent.com/3293036/115815039-77d73c80-a3b3-11eb-93e4-d012544007a4.png)

**Comment by ccalvarez** [comment]
> @ccalvarez I deployed SQL Server 2016 on Azure and added it as a source on `v2.0.0-alpha.7`. The console shows me the `dbo` schema and lets me track all tables and relationships. Running `SELECT @@VERSION;` from 'SQL' section has the following output:
> 
> ```
> Microsoft SQL Server 2016 (SP2-CU16) (KB5000645) - 13.0.5882.1 (X64) 
> 	Jan 25 2021 21:40:32 
> 	Copyright (c) Microsoft Corporation
> 	Express Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)
> ```
> 
> Can you head to `SQL` section and share the output of the following query when connected to sql server 2016?
> 
> ```sql
> select s.name, s.schema_id from sys.schemas s;
> ```

@0x777 hi, sorry for the delay, I've been very busy at work, here is the result of running that query when connected to the on premises SQL Server 2016, thanks:

![image](https://user-images.githubusercontent.com/2665104/116572891-9369a800-a8c9-11eb-99aa-dbd31f2e97ae.png)

**Comment by stevebelskie** [comment]
Also ran into this issue.

@0x777 Any chance this is related to this code for fetching the schemas?
https://github.com/hasura/graphql-engine/blob/d22d26b39c782890324491bc7c7f8b25e5d26a8a/console/src/dataSources/services/mssql/index.tsx#L206-L217

An on premise database likely has a schema owner that is a windows users (e.g. `p.type_desc` would be `WINDOWS_USER`). 

Looks like this query was recently changed in https://github.com/hasura/graphql-engine/commit/3dfc50e3acab1387c02204cb2fcd4b7fafa66baf, but the old query checking for `issqluser=1` would have the same issue.

**Comment by celvin** [comment]
does the on-premises user has full admin rights?

**Comment by stevebelskie** [comment]
@celvin I’m not sure which on-prem user you mean. There are (at least) 2 in this case: the schema owner (windows user) and the Hasura user (sql user). The Hasura user has all the permissions needed to do anything that Hasura needs to do as far as I can tell. But no matter how many permissions you give it, it will never be the principal associated the dbo schema. If the owner of the schema is a Windows user that query will never bring back the schema name (even if the Hasura user has full permissions).

**Comment by 0x777** [comment]
@stevebelskie The intention with the query is to not show system created schemas and we got the query wrong twice. Looks like a schema is automatically created for all the  [`db_*` schemas](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles?view=sql-server-ver15#fixed-database-roles) and this behaviour is a [relic from the past](https://www.sqlservercentral.com/forums/topic/db_owner-is-a-schema#post-1854611). 

Can you check if this query returns the relevant schemas that you want to expose through GraphQL? 
```sql
 SELECT
   s.name AS schema_name,
   p.type_desc
 FROM
   sys.schemas s
   INNER JOIN sys.database_principals p ON (s.principal_id = p.principal_id)
 WHERE
   p.type_desc <> 'DATABASE_ROLE' AND 
   s.name NOT IN ('guest', 'INFORMATION_SCHEMA', 'sys')
 ORDER BY
   s.name
```
@ccalvarez Would you mind running the above query too and check if it returns `dbo` schema?

**Comment by ccalvarez** [comment]
@

> On second thought, I think we should just simplify the above query to this:
> 
> ```sql
>  SELECT
>    s.name AS schema_name...
> ```

Hi, yes it returns `dbo`:

![image](https://user-images.githubusercontent.com/2665104/117454668-9e44be00-af03-11eb-831f-4a3ca0078604.png)


Also if it helps, these are the properties of my `hasurauser` :

Login properties:

![image](https://user-images.githubusercontent.com/2665104/117456060-07790100-af05-11eb-8638-888ce73b0aa2.png)



User in database properties:

![image](https://user-images.githubusercontent.com/2665104/117455680-a94c1e00-af04-11eb-816d-51f3c43bf450.png)

![image](https://user-images.githubusercontent.com/2665104/117455770-bc5eee00-af04-11eb-84d2-5bf58c3f280c.png)

![image](https://user-images.githubusercontent.com/2665104/117455862-d3054500-af04-11eb-908f-ba48f700fbd5.png)


Thank you.

**Comment by 0x777** [comment]
@ccalvarez Are those two the relevant schemas for you? Or is the query missing any other schemas that you may want to expose through graphql-engine?

**Comment by ccalvarez** [comment]
@0x777 the relevant schema is dbo.  This because when we create tables, they are created by default under the dbo schema, but Hasura console doesn't expose them to track them.

**Comment by ccalvarez** [comment]
@0x777 I have updated to Hasura v2.0.0-alpha.10, and started with a fresh new metadata database, to test again, and I'm still not being able to see the `dbo` schema when I connect to the on-premises SQL Server.  I can see in Hasura console the other schemas, but not the `dbo` schema, despite it shows in the query you provided:

**Query results:**

![image](https://user-images.githubusercontent.com/2665104/117692059-db19ea80-b179-11eb-9752-4328e77d503f.png)


**Hasura console:**

![image](https://user-images.githubusercontent.com/2665104/117692701-8460e080-b17a-11eb-8487-0316a86578a8.png)

**Comment by beerose** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/a5ce316a96c071c629d30d12ae16029a452cb6e5
