### ISSUE TITLE
error track table with unique field from Prisma migrations

### ISSUE THREAD

**Issue by fbonhomm** [hasura/graphql-engine#6732]
Hello, I did a database migration with prisma  and after, I will try to track this table in Hasura console but my table `Users` don't want to be tacked because a `email` field is unique.
Do you have a hint ?

Thank you.

<img width="391" alt="Screenshot 2021-03-30 at 23 15 32" src="https://user-images.githubusercontent.com/8777400/113057859-d858cc80-91ad-11eb-950d-6a01df3efc28.png">

<img width="507" alt="Screenshot 2021-03-30 at 23 16 09" src="https://user-images.githubusercontent.com/8777400/113057917-ee668d00-91ad-11eb-8854-b54c33c8d9e0.png">

**Comment by rikinsk** [comment]
Hey. I am not quite familiar with the migration Prisma generates for its models. Can you share the sql statement in your migration that created this table?

**Comment by tirumaraiselvan** [comment]
Can you show the name of the constraints on your table `\d+ <table_name>`? I think it may be related to unique constraint name. Hasura generates `on_conflict` fields which can take the name of the unique constraint and perhaps that name is not graphql spec compliant.
