### ISSUE TITLE
Invalid SQL statement generated when setting existing column to be unique

### ISSUE THREAD

**Issue by rossng** [hasura/graphql-engine#6734]
I just tried to set an existing table column to have a uniqueness constraint, and got this error message:

```json
{
    "internal": {
        "statement": "alter table \"job_queues\".\"ChannelStackCreateJob\" add constraint \"ChannelStackCreateJob_stackLogicalResourceId_key\" unique (stackLogicalResourceId);",
        "prepared": false,
        "error": {
            "exec_status": "FatalError",
            "hint": null,
            "message": "column \"stacklogicalresourceid\" named in key does not exist",
            "status_code": "42703",
            "description": null
        },
        "arguments": []
    },
    "path": "$[0]",
    "error": "query execution failed",
    "code": "postgres-error"
}
```

It looks like this is simply a case of Hasura failing to quote the `stackLogicalResourceId` identifier correctly (since Postgres is weird about capital letters).

I tried running the migration myself, quotes included, and it worked.

Working:
```sql
alter table "job_queues"."ChannelStackCreateJob" add constraint "ChannelStackCreateJob_stackLogicalResourceId_key" unique ("stackLogicalResourceId")
```

Broken:
```sql
alter table "job_queues"."ChannelStackCreateJob" add constraint "ChannelStackCreateJob_stackLogicalResourceId_key" unique (stackLogicalResourceId)
```

I would guess [this line](https://github.com/hasura/graphql-engine/blob/b829520f49abafa2dad5027863bfcefda6ffc15e/console/src/dataSources/services/postgresql/sqlUtils.ts#L631) is the source of the bug.

I am running Hasura v2.0.0-alpha.6.

**Comment by 0x777** [comment]
This has been fixed in `master`. It'll be part of the next release! Thanks for reporting this :)
