### ISSUE TITLE
Hasura CLI cannot find config.yaml

### ISSUE THREAD

**Issue by mwarger** [hasura/graphql-engine#6740]
I'm trying to run `hasura console` with a valid config.yaml file (created by running `hasura init`) and I get the following error:
```
level=fatal msg="validating current directory failed: validate: cannot find [config.yaml] | search stopped: filesystem boundary hit"
```

I'm not sure how to debug this as the error message doesn't print the `current directory` it's referring to.  I'm using the NPM version of the cli, `    "hasura-cli": "2.0.0-alpha.5",`

**Comment by scriptonist** [comment]
@mwarger `hasura init` creates a project directory for you, are you sure you are executing the command from that particular directory? 

For example, by default `hasura init` creates a directory called `hasura`, so the steps that we should follow are,

```
cd hasura
hasura console
```

**Comment by mwarger** [comment]
@scriptonist I'm pretty sure I am, I have changed into the directory and tried running the command a few ways...

```
mat@macbook-air hasura % yarn hasura version
yarn run v1.22.5
$ /Users/mat/dev/khs/now-playing-nx/node_modules/.bin/hasura version
INFO hasura cli                                    version=v2.0.0-alpha.5
✨  Done in 0.84s.

mat@macbook-air hasura % yarn hasura console
yarn run v1.22.5
$ /Users/mat/dev/khs/now-playing-nx/node_modules/.bin/hasura console
FATA[0000] validating current directory failed: validate: cannot find [config.yaml] | search stopped: filesystem boundary hit 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

mat@macbook-air hasura % npx hasura version           
INFO hasura cli                                    version=v2.0.0-alpha.5

mat@macbook-air hasura % npx hasura console
FATA[0000] version check: failed to get version from server: failed making version api call: Get "http://localhost:8080/v1/version": dial tcp [::1]:8080: connect: connection refused 
mat@macbook-air hasura % 
```

As far as I can tell, this was working previously with the 1.3.3 version of hasura CLI.  I've only had this issue after upgrading to the 2.0.0-alpha.5 version.

The `yarn` call seems to fail to find the config.yaml.  The `npx` call seems to find it, but isn't reflecting the values in the config.yaml file (where I have overridden the endpoint).

**Comment by scriptonist** [comment]
@mwarger can you try installing the CLI globally using any of the methods mentioned [here ](https://hasura.io/docs/latest/graphql/core/hasura-cli/install-hasura-cli.html#install-hasura-cli)(not using npm) and retry?

```
FATA[0000] version check: failed to get version from server: failed making version api call: Get "http://localhost:8080/v1/version": dial tcp [::1]:8080: connect: connection refused 
```
This error tells us that the CLI is trying to communicate with a graphql-engine instance running on `http://localhost:8080`. Can you make sure a graphql-engine instance is running on `localhost:8080`

**Comment by mwarger** [comment]
> ```
> FATA[0000] version check: failed to get version from server: failed making version api call: Get "http://localhost:8080/v1/version": dial tcp [::1]:8080: connect: connection refused 
> ```
> 
> This error tells us that the CLI is trying to communicate with a graphql-engine instance running on `http://localhost:8080`. Can you make sure a graphql-engine instance is running on `localhost:8080`

Right, but in my config I have the endpoint set to `:8010`.  It's not picking up that value for some reason.  

```
version: 3
endpoint: http://localhost:8010
admin_secret: asdf
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000

```


I will try the global CLI.

**Comment by mwarger** [comment]
The global CLI worked.  I updated it to the specific `alpha.5` version.  The `version` command even prints out the values it picks up, so that's great to see.  Thank you for your help!

```
mat@macbook-air now-playing-nx % cd libs/hasura-backend/hasura
mat@macbook-air hasura % hasura version
INFO hasura cli                                    version=v2.0.0-alpha.5
INFO hasura graphql engine                         endpoint="http://localhost:8010/" version=v2.0.0-alpha.5
mat@macbook-air hasura % hasura console 
INFO console running at: http://localhost:9695/  
```
