### ISSUE TITLE
Occasional slow GraphQL Query execution

### ISSUE THREAD

**Issue by shoNagai** [hasura/graphql-engine#6743]
The problem I'm having is that when I access the site after a period of time, the query response from Hasura sometimes takes a very long time. 

My environment is as follows.
- hasura on Google Cloud Run
- postgreSQL on Cloud SQL
- JWT method with Firebase Auth

The following logs were being output by the server at that time.

```
{
  "jsonPayload": {
    "level": "info",
    "timestamp": "2021-04-01T15:44:18.392+0000",
    "detail": {
      "message": "refreshing JWK from endpoint: https://XXXX,
      "error": null
    },
    "type": "jwk-refresh-log"
  }
}
```

The current solution is to cause a timeout error using RetryLink and retry again, since we are using apollo client.

However, this is not a good solution as it still takes some time to retry and so on.

Do you know of any other good ways to deal with this problem?
Also, do you have any plans to address this issue?

**Comment by arjunyel** [comment]
Hasura shouldnt be run on Google Cloud Run, it should be on App Engine Flexible

**Comment by shoNagai** [comment]
@arjunyel Thanks for the advice.

Does this mean that the cold start is affecting it?

If I continue to use Cloud Run, I will check if I can handle it by setting the minimum number of instances to 1.

**Comment by arjunyel** [comment]
Cloud Run was designed for stateless HTTP servers but Hasura is stateful, for example the cron job service needs to be constantly running in Hasura but with Cloud Run the CPU only works during external requests, so you need a stateful host for Hasura like App Engine Flexible, or Compute engine, or Kubernetes... Having gone down that route I highly highly recommend you just use Hasura Cloud

**Comment by shoNagai** [comment]
I see, thank you!
I will check out hasura cloud and consider the environment for hasura adoption.
