### ISSUE TITLE
Updating Session argument variable failed

### ISSUE THREAD

**Issue by happyfloat** [hasura/graphql-engine#6748]
I'm working with the `2.0.0-cloud.2` version and I can not set my session argument in the console. It says it can't find the function in the cache, whatever this means? I did upgrade my postgres RDS instance, reloaded metadata, re-created the function... nothing did help.

<img width="330" alt="Screenshot 2021-04-04 at 18 09 04" src="https://user-images.githubusercontent.com/64045340/113514877-4f58e100-9571-11eb-8f21-bbeb3756fb64.png">
<img width="438" alt="Screenshot 2021-04-04 at 18 08 44" src="https://user-images.githubusercontent.com/64045340/113514874-4d8f1d80-9571-11eb-8a33-805dbe90bbaa.png">

The function itself is working as expected (here still with the user_id as argument instead of the hasura_session variable because of the issue above)

<img width="867" alt="Screenshot 2021-04-04 at 18 09 38" src="https://user-images.githubusercontent.com/64045340/113514875-4ec04a80-9571-11eb-8fd8-7bfe1144c959.png">

**Comment by tirumaraiselvan** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/53beef47ea1de3cefb0f6aa6ae155482cc637d8f . Will be out in next release.
