### ISSUE TITLE
[v2.0.0-alpha.6] Hasura CLI's console won't load (incorrect CDN asset URL)

### ISSUE THREAD

**Issue by peteygao** [hasura/graphql-engine#6757]
Hasura CLI version: `v2.0.0-alpha.6`
Hasura server version: `v2.0.0-cloud.2`

Two things are broken:

1. `--static-dir` flag. Using this flag with the CLI console does *nothing*.
1. The CDN URL that the CLI console is pulling from is wrong. It's pointing to `channel/stable`, but it should be `channel/alpha`.

## Missing CDN assets

The console is just stuck on "Loading..."

With these errors in the console:
![image](https://user-images.githubusercontent.com/2184561/113652079-fd36bf00-9647-11eb-8ed0-5278f5a5d738.png)

The specific URLs are (top to bottom, corresponding to the error in the screenshot):
```
https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/main.css.gz
https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz
https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/main.js.gz
https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/main.css.gz
```

## `--static-dir` option does nothing

I cloned this repo, `cd console` and then `make server-build` to compile my own dist of the assets and specified `--static-dir`. But using `--static-dir` to specify a local directory does nothing on hasura CLI:
```bash
hasura console --static-dir /some/local/dir
```

The assets are still being fetched from the CDN.

## Solution?

It looks like all the assets are under the `channel/alpha` directory, NOT `channel/stable`. The following URLs work:
```
https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/main.css.gz
https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz
https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/main.js.gz
https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/main.css.gz
```

## Temporary Hack Solution

If you're running into this problem, then the following hack will solve your problem:

You have to override the `window.__env.assetsVersion` environment variable in the console.

Paste the following function into the browser console. This is to bootstrap the asset loading process with the correct asset URLs.
```javascript
function l() {
    window.__env.assetsVersion = "channel/alpha/v2.0";

    const loadIcon = url => {
        linkElem = document.createElement("link");
        linkElem.rel = "icon";
        linkElem.type = "image/png";
        linkElem.href = url;
        document.head.append(linkElem);
    };
    const loadCSS = url => {
        linkElem = document.createElement("link");
        linkElem.rel = "stylesheet";
        linkElem.charset = "UTF-8";
        linkElem.href = url;
        document.body.append(linkElem);
    };
    const loadScript = url => {
        scriptElem = document.createElement("script");
        scriptElem.charset = "UTF-8";
        scriptElem.src = url;
        document.body.append(scriptElem);
    };
    const prependSlash = str => (str === "" ? "" : "/" + str);
    const loadAssets = () => {
        loadCSS(
            window.__env.assetsPath + "/common/css/font-awesome.min.css.gz"
        );
        loadIcon(window.__env.assetsPath + "/common/img/favicon_green.png");
        loadCSS(window.__env.versionedAssetsPath + "/main.css.gz");
        loadScript(window.__env.versionedAssetsPath + "/main.js.gz");
        loadScript(window.__env.versionedAssetsPath + "/vendor.js.gz");
    };

    window.__env.versionedAssetsPath = window.__env.assetsPath + prependSlash(window.__env.assetsVersion);

    loadAssets();
}
```

Then execute it: `l()`. This will load the console. If you are getting invalid admin secret token error, the solution is to add `http://localhost:9695` as one of the allowed domains on Hasura Cloud under `HASURA_GRAPHQL_CORS_DOMAIN ENV` var (for multiple domains, add a comma separator).

**Comment by scriptonist** [comment]
@peteygao I was trying to reproduce this but couldn't, can you share the output of `hasura version` here?

**Comment by peteygao** [comment]
@scriptonist Updated the original description. Server version is `v2.0.0.0-cloud.2`

**Comment by scriptonist** [comment]
@peteygao this should be fixed now, can you verify?

**Comment by peteygao** [comment]
@scriptonist Fixed. Thanks!
