### ISSUE TITLE
[v2.0.0-alpha.6] Can't use read-only database with separate metadata database

### ISSUE THREAD

**Issue by akashkrishnan** [hasura/graphql-engine#6759]
I've set up graphql-engine v2.0.0-alpha.6 to use a dedicated, separate metadata database. Specifying a second, read/write database works fine, but when replacing this database with a read-only version, graphql-engine is able to check the metadata on the dedicated metadata database but fails to check metadata consistency on the second, read-only database. It fails with the following error:

```
info: catalog_migrate ... Already at the latest catalog version (44); nothing to do.
warn: Inconsistent Metadata! ... postgres tx error ... custom types are inconsistent
```

Are read-only databases supported yet? We've been using the read-only variant of v1.3.3 and it works well.

**Comment by tirumaraiselvan** [comment]
This will be possible in the next release. Currently, Hasura tries to also initialize event trigger tables during startup in the user-db which makes then throws this error. In the next release, event trigger tables will be initialized "dynamically" i.e. only if an event trigger is created on the user db (and not during startup).

**Comment by tirumaraiselvan** [comment]
Can you pls try with `v2.0.0-alpha.11` ?

**Comment by tirumaraiselvan** [comment]
This is now possible in v2.0.0-alpha.11. Please let us know if you face any problems.
