### ISSUE TITLE
Documentation Update:  DNS for Docker Desktop for Windows 3.2.0 is no longer docker.for.win.localhost

### ISSUE THREAD

**Issue by corepay** [hasura/graphql-engine#6766]
Looks like the Docker localhost network name for  Docker Desktop for Windows 3.2.0 has been changed to `host.docker.internal` 

![image](https://user-images.githubusercontent.com/48992923/114039217-90dadc00-9850-11eb-9cdc-6c391065694e.png)

See here:  https://github.com/docker/for-win/issues/1764

**Comment by keremgocen** [comment]
anyone doing a PR for this?

**Comment by rikinsk** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/21215dad1b047b59d203178b07ecc76224ff9961
