### ISSUE TITLE
add clear access key button should be shown even if reload metadata state is set to false

### ISSUE THREAD

**Issue by arvi3411301** [hasura/graphql-engine#677]

**Comment by shahidhk** [comment]
@arvi3411301 @paranoidsp Can you explain what this bug is?

**Comment by arvi3411301** [comment]
@shahidhk Clear access key button should be shown for any server version. But currently, it is shown only when the reloadMetadata state is set to true.

**Comment by arvi3411301** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/882719f7e7073e3ca3ff9440698b52a665b7340b
