### ISSUE TITLE
Can the http handler ingest XML?

### ISSUE THREAD

**Issue by RedCloudDC** [hasura/graphql-engine#6773]
Our production SQL Server 2014 and outputs XML response (not JSON). Can I create a Hasura Action with handler to convert XML response to JSON?

**Comment by 0x777** [comment]
@RedCloudDC I'm not sure what you mean. Are you asking about support for SQL Server 2014? graphql-engine uses certain json aggregation features that are only available on SQL Server 2016 and above. If there is enough interest though, we will consider supporting SQL Server 2014 in the future.
