### ISSUE TITLE
Squashing fails on graphql-engine:v2.0.0-alpha.7.cli-migrations-v3

### ISSUE THREAD

**Issue by cies** [hasura/graphql-engine#6774]
I'm trying to run the following from the docker container:

```root@9d086bd0ab6b:/hasura# hasura-cli migrate squash --name "initial schema" --from 1618168947666 --database-name=postgres
FATA[0000] error determining database kind for postgres, check if database exists on hasura
```

The folder with `config.yml`, `migrations/` and `metadata/` is mounted at `/hasura`. I'm in that folder when executing the command.

I know it's marked as experimental and I dont really need it to be squashed, but I want to mention it to help improving your great product! (that's what alphas are for is it not?)

**Comment by cies** [comment]
I tried to run the command with the console (development `hasura-cli` console) running, and with it not running. No difference.

**Comment by scriptonist** [comment]
@cies what did you name your database when you were connecting it to hasura? you can find that in the "data" tab in console.

![image](https://user-images.githubusercontent.com/8335904/114860128-3a9a0a00-9e09-11eb-8723-7e81923e90e1.png)

**Comment by cies** [comment]
![image](https://user-images.githubusercontent.com/8694/116078407-d8f25f00-a696-11eb-8ffe-53b240a75ed3.png)

I think it's `default`

**Comment by rikinsk** [comment]
Hey. Can you confirm the exact command you were attempting to run? Cant seem to see it in the above comments. In any case, passing the flag `--database-name default` to the command should ideally fix this issue.

**Comment by rikinsk** [comment]
Hey. I am closing this issue for now. Please feel free to reopen it if you are still facing this.
