### ISSUE TITLE
Sometimes applying metadata fails silently

### ISSUE THREAD

**Issue by mfcochauxlaberge** [hasura/graphql-engine#6784]
Sometimes applying metadata fails silently. I usually have to go back in my Git history and redo all changes one by one until it works.

I have an example here:

![image](https://user-images.githubusercontent.com/534861/114781201-62746980-9d46-11eb-8233-8234d87d40f3.png)

The `_or` is clearly a mistake, but the hasura cli would still say the metadata was applied (see screenshot below) successfully. When I log into the UI, there is no metadata. I only see a list of untracked tables.

<img width="175" alt="image" src="https://user-images.githubusercontent.com/534861/114781443-ab2c2280-9d46-11eb-8b29-f2c7c7a3d3a3.png">

**Comment by chartpath** [comment]
Can confirm this has been a pain when upgrading to v3 config!

**Comment by scriptonist** [comment]
@mfcochauxlaberge @chartpath Thanks for pointing this out. This turned out to be a bug and should be fixed in the next release.

**Comment by mfcochauxlaberge** [comment]
I can confirm that with `v2.0.0-alpha.8`, the config mistake mentioned above now fails with a clear error message.
