### ISSUE TITLE
Auto-apply in cli-migrations (Hasura 2) tries to apply metadata before applying migrations

### ISSUE THREAD

**Issue by mfcochauxlaberge** [hasura/graphql-engine#6785]
In v3 of cli-migrations, the metadata is applied before the migrations. So when applying metadata, the tool outputs some errors, but then it applies migrations and that fixes the metadata. For longer migrations, the tool can attempt to apply metadata multiple times before it works.

This is confusing behaviour. Why is the metadata applied before migrations in v3?

See: https://github.com/hasura/graphql-engine/tree/master/scripts/cli-migrations

We used to rely on the metadata applied message to do some kind of health check. But now we can't trust the logs anymore.

**Comment by scriptonist** [comment]
Hey @mfcochauxlaberge, The latest `cli-migrations` v3 image works with a config V3 based project. There has been some workflow changes w.r.t config V3. see https://hasura.io/docs/latest/graphql/core/migrations/upgrade-v3.html#changes-needed-in-existing-workflows

**Comment by mfcochauxlaberge** [comment]
Thanks, this explains the situation.

But one of my complaints remain, which is that the logs are filled with errors before everything gets resolved. I don't think this is good behaviour.

**Comment by scriptonist** [comment]
@mfcochauxlaberge those logs are in "warn" log level right? I understand it is a concern and will see what can be done here. Regarding migrations and metadata, can you help me with a rough count of number of migrations that you have?

**Comment by chartpath** [comment]
@scriptonist can confirm that they are warnings. Seems they appear in between every SQL migration (as if the engine attempts to apply metadata than many times).

<img width="1516" alt="Screen Shot 2021-04-19 at 9 59 12 AM" src="https://user-images.githubusercontent.com/461274/115248829-074fc780-a0f6-11eb-94d3-5ccf339c010b.png">

**Comment by mfcochauxlaberge** [comment]
@scriptonist Also, we used to have 140 migrations. We recently squashed most of them and we are down to 20. The problem still exists, although it might take a little bit less time before the engine reaches a working state.

**Comment by rikinsk** [comment]
Closing this issue. Please feel free to raise another issue with details on the migration performace bit
