### ISSUE TITLE
Can  you please  explain  how can  i set-cookies from remote api-service on  client

### ISSUE THREAD

**Issue by Barolina** [hasura/graphql-engine#6787]
In the  guide i  found   this: 

```
Passing cookie headers from your remote schema to the client

Set-Cookie headers from your remote schema servers are sent back to the client over HTTP transport. Over websocket transport there exists no means of sending headers after a query/mutation and hence the “Set-Cookie” headers are not sent to the client. Use HTTP transport if your remote servers set cookies.

```

There is    i can't  set-Cookie  on  client from  remote api service  through action ?

**Comment by rikinsk** [comment]
hi. can you share some more information here. Are you using hasura actions or remote schemas here? in any case, any cookies returned by the action handler should be passed on to the client. are you not observing the same?

**Comment by Barolina** [comment]
yes,  i use to  the sheme like   this  

   1. clint (http request) -> 2. hasura (action)  ->   3. same service (set cokies)  -> 4. hasura  -X - 5.client

And the step from 4 to 5  don't  get  cookies for  client.

**Comment by tirumaraiselvan** [comment]
We tried to look into this but Cookies to get set from an Action: https://github.com/hasura/graphql-engine/issues/6637#issuecomment-831158379

**Comment by Barolina** [comment]
Thank you
