### ISSUE TITLE
Can't apply metadata with cli

### ISSUE THREAD

**Issue by devrsi0n** [hasura/graphql-engine#6792]
Hi folks, thanks for making such an amazing project. Currently, I'm migrating hasura to a new database, I found that I can't apply metadata with cli, here is the error details:
![image](https://user-images.githubusercontent.com/7880675/115038402-166e2400-9f02-11eb-8fcf-8485bf447528.png)

Any thoughts how to mitigate this issue?

**Comment by scriptonist** [comment]
@devrsi0n Thanks for reporting this. can you help me with the following details
- CLI version
- Operation System that you are on

**Comment by devrsi0n** [comment]
@scriptonist Thanks for the reply, I'm using hasura cli `v1.3.3`, macOS `11.2.3`.

**Comment by devrsi0n** [comment]
@scriptonist Finally, the issue is gone when I run the command in the `iTerm2` instead of VSCode internal terminal, thanks for the attention.
