### ISSUE TITLE
Urql mutation fails with "[GraphQL] field "__typename" not found in type: 'books_set_input'"

### ISSUE THREAD

**Issue by aswinmohanme** [hasura/graphql-engine#6793]
I have a books table that I am updating with the mutation 
```
      mutation updateBook($book: books_set_input!, $id: uuid!) {
        update_books_by_pk(pk_columns: { id: $id }, _set: $book) {
          id
        }
      }
```

The query successfully executes on the hasura console, but fails with urql as it expects a __typename from the `books_set_input` type. 

The error message
```
Error: field "__typename" not found in type: 'books_set_input' 
extensions:
code: "validation-failed"
path: "$.selectionSet.update_books_by_pk.args._set.__typename"
__proto__: Object
message: "field "__typename" not found in type: 'books_set_input'"
```

**Comment by aswinmohanme** [comment]
Related: #6547

**Comment by 0x777** [comment]
@aswinmohanme Can you share the request the exact request that urql is making?

**Comment by JavaJamie** [comment]
Also getting this issue with Apollo client. Granted I'm very new to GQL but this is a stumbling block. Is there a solution to this? I have an update mutation and it seems like it's trying to insert __typename which obviously it shouldn't be...

`Error: field "__typename" not found in type: 'user_profile_set_input'`

**Comment by HT-Moh** [comment]
@aswinmohanme I think you should  remove  `delete set.__typename`  from the object then pass it the variables

**Comment by ianschmitz** [comment]
@0x777 I just ran into the same issue as OP. Urql uses the `__typename` to determine what to update in the cache that it provides.

Here's the exact request being made by urql in our case (formatted for readability):

```
operationName: "UpdateUser"
query: "mutation UpdateUser(
  $id: bigint!
  $user: users_set_input!
) {
  updateUser(pk_columns: { id: $id }, _set: $user) {
    __typename
  }
}"
variables: {
    "user": {
        "name": "Foo",
        "__typename": "users"
    },
    "id": 1
}"
```

And the response:

```
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.updateUser.args._set.__typename",
        "code": "validation-failed"
      },
      "message": "field \"__typename\" not found in type: 'users_set_input'"
    }
  ]
}

```

**Comment by ianschmitz** [comment]
Ahh i just found the solution in my case. It was due to `__typename` being present within the `variables` sent for the mutation. I enabled `maskTypename` on the Urql client and that fixed it! See https://formidable.com/open-source/urql/docs/api/core/#masktypename
