### ISSUE TITLE
"malformed array literal" when querying without "x-hasura-admin-secret"

### ISSUE THREAD

**Issue by tconroy** [hasura/graphql-engine#6795]
I'm running into an issue where a query works as I expect if I am using the `x-hasura-admin-secret` request header, but as soon as I replicate a user (ie `Authorization` token and `x-hasura-user-id` header), the request fails:

error:
```
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "data-exception"
      },
      "message": "malformed array literal: \"6808a0d5-858f-4aa4-a727-0b000e370a34\""
    }
  ]
}
```

this is what the query looks like:
```
query myQuery($id: uuid!) {
  team(where: {team_members: {user_id: {_eq: $id}}}) {
    name
    id
    team_members {
      user {
        name
        image
      }
    }
  }
}
```

and this are the query variables:
```
{
  "id": "6808a0d5-858f-4aa4-a727-0b000e370a34"
}
```

honestly a little stumped. Not sure why it works as admin but not as a user. Permissions are configured correctly.

**Comment by 0x777** [comment]
@tconroy What role are you making the query as (when it fails with the above error)? Can you share the permissions on both the tables in the above query for this role?
