### ISSUE TITLE
Volative Function permissions are incorrectly displayed in the UI

### ISSUE THREAD

**Issue by TheMrZZ** [hasura/graphql-engine#6800]
When creating a volatile function, exposed as a mutation, with `HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS` set to `false`, the function permissions are displayed like if they were similar to the related table's permissions:

![image](https://user-images.githubusercontent.com/30944236/115399031-1020c600-a1e8-11eb-81c3-b68db89d428b.png)

As you can see here, it looks like absolutely everyone but anonymous users can access this mutation, which should not be the case since HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS is false.

However, when trying to call this mutation from any role other than admin, the function is not available:
![image](https://user-images.githubusercontent.com/30944236/115399195-3cd4dd80-a1e8-11eb-96df-58445a2e9491.png)
(this happens with a user, a guest & an anonymous role).

With an administrator role, it runs just fine:
![image](https://user-images.githubusercontent.com/30944236/115399263-4cecbd00-a1e8-11eb-8096-7db0c913c4bf.png)

We would therefore have expected permissions to be ❌ for all roles except admin, like this:
![image](https://user-images.githubusercontent.com/30944236/115399546-9e954780-a1e8-11eb-8776-9d635b1fd49d.png)

We really pulled our hair for 2 days on this one, persuaded that we did something wrong before we realized that the permissions were *in fact* correct, but incorrectly displayed. It led us to try a lot of things, which gave us inconsistent metadata, problems with migrations etc...

In the end, this bug might not *look* important, but it's been a huge waste of time for my team. Hopefully it will be solved in the next alpha release.

**Comment by 0x777** [comment]
@TheMrZZ Our sincere apologies about the trouble this has caused. We'll fix this asap.

**Comment by TheMrZZ** [comment]
Well this is an alpha version, so it's normal to have problems. Thanks for the quick answer!

**Comment by kolharsam** [comment]
@TheMrZZ Thanks for reporting the issue! A fix is in the pipeline and should be out soon!  👍

**Comment by beerose** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/2b0b4ec3a48d2986e6d5db5e3852f1b6c4e4d989
