### ISSUE TITLE
[v2.0.0-alpha.8] Breaking change to `on_conflict` permissions

### ISSUE THREAD

**Issue by rossng** [hasura/graphql-engine#6804]
Hasura 2.0 appears to have introduced a breaking change with the way `on_conflict` interacts with permissions.

Specifically, if a role has `update` permissions, but no columns ticked, `on_conflict` will not be available in the GraphQL schema. This is different behaviour to Hasura 1.3.3 and I would consider it a breaking change (well, it broke [my app](https://github.com/clowdr-app/clowdr)!)

I have put together a [minimal reproduction of the issue](https://github.com/rossng/hasura2-on_conflict-reproduction).

**Comment by tirumaraiselvan** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/5283eebf756160f92b814807ee9d69c5f3eb77fd . Will be released in next alpha/beta.
