### ISSUE TITLE
Remote schema permissions: Input types should also allow to be preset

### ISSUE THREAD

**Issue by andremetzen** [hasura/graphql-engine#6806]
## Problem
When I set a preset an input object field on Remote Schema Permission, Hasura makes the whole object unavailable. 

Versions:
I've tested several v2 alpha versions, inclusing the alpha.9
Postgres: 12

## Steps to reproduce

- Setup a remote schema with a mutation and an input object as argument like so:

```graphql
input test_input {
    id: Int!
    name: String
}

type User {
    id: Int
    name: String
}

type Mutation {
    test (object: test_input!)
}
```

- Go to the Remote Schema Permissions and allow the `test` and define a preset to `id` with `X-Hasura-User-Id` for a specific role

- For that role, run the following mutation:

```graphql
mutation {
    test(object: {name: "John Doe"}) {
        id
        name
    }
}
```

## Outcome

Hasura returns an error saying that `object` doesn't exists for mutation `test`

Looking at the `remote_schemas.yaml`, I see something like:

```graphql
type Mutation {
    test(object: test_input @preset(value: {id: \"X-Hasura-Customer-Id\"})): [User]
}

input test_input {
    id: Int!
    name: String
}

type User {
    id: Int
    name: String
}
```

## Expected outcome

The query should be valid for that role. I believe that the expected `remote_schemas.yaml` would be:

```graphql
type Mutation {
    test(object: test_input): [User]
}

input test_input {
    id: Int! @preset(value: \"X-Hasura-Customer-Id\")
    name: String
}

type User {
    id: Int
    name: String
}
```

**Comment by codingkarthik** [comment]
Hello @andremetzen ,

From this 

```graphql
type Mutation {
    test(object: test_input @preset(value: {id: \"X-Hasura-Customer-Id\"})): [User]
}

input test_input {
    id: Int!
    name: String
}

type User {
    id: Int
    name: String
}
```

It seems that you have preset the `object` argument of the `test` field and the output you get is expected. From your other comments, it seems that you only want to preset the `id` field, to do that you'll have to specify the preset in the  `id` field of the `test_input`  input object instead of the `test` field, then you'll be able to query the remote schema with the `object` argument with only the `name` argument exposed to the role. 

Please do let me know if this works or you have any other queries regarding remote schema permissions :)

**Comment by andremetzen** [comment]
Yeah, but I don't see how can I preset the input object using the console UI. 

In addition to that, the current UI is misleading, since it seems you're presetting just one field, not the entire object.

**Comment by tirumaraiselvan** [comment]
> Yeah, but I don't see how can I preset the input object using the console UI.

![Screen Shot 2021-04-23 at 5 31 09 PM](https://user-images.githubusercontent.com/8663570/115868449-18803780-a45a-11eb-82df-ab285d9169a6.png)

You can preset `input` types for this. If you preset an argument, it means that the whole argument is preset.

> In addition to that, the current UI is misleading, since it seems you're presetting just one field, not the entire object.

We will improve the UI here to make it clear that the whole argument is preset.

**Comment by andremetzen** [comment]
@tirumaraiselvan in the screenshot you just sent, you can toggle which fields are visible, but the UI doesn't allow you to define a preset. Am I missing something?

**Comment by tirumaraiselvan** [comment]
@andremetzen Yikes, the UI should show a preset option next to them. Our bad, will fix in next release.

**Comment by abhi40308** [comment]
This should be fixed now https://github.com/hasura/graphql-engine/commit/75f37f69d3fdc85e7fc2b479bbc29a3890abcb73

**Comment by abhi40308** [comment]
We are now able to add `input` types preset using the UI like as shown


<img width="513" alt="Screenshot 2021-06-17 at 6 41 50 PM" src="https://user-images.githubusercontent.com/26903230/122403153-c2cc9500-cf9b-11eb-9e55-b729c1be59e3.png">
