### ISSUE TITLE
running locally example does not work on M1 mac

### ISSUE THREAD

**Issue by formvoltron** [hasura/graphql-engine#6815]
On Mac 11.2.3.  mb air m1.  plenty of disk space and memory

Following these instructions
https://hasura.io/docs/latest/graphql/core/getting-started/docker-simple.html

Results in a docker install with Hasura restarting over & over again.

**Comment by tirumaraiselvan** [comment]
Tackling this here: https://github.com/hasura/graphql-engine/issues/6337
