### ISSUE TITLE
1.3.3-Denial-Of-Service

### ISSUE THREAD

**Issue by doroniz** [hasura/graphql-engine#6819]
Hi, I came across those and have not seen any mention of them here. Has anyone seen this? Has it been fixed?

https://packetstormsecurity.com/files/162277/Hasura-GraphQL-1.3.3-Denial-Of-Service.html
https://packetstormsecurity.com/files/162265/Hasura-GraphQL-1.3.3-Arbitrary-File-Read.html
https://packetstormsecurity.com/files/162267/Hasura-GraphQL-1.3.3-Server-Side-Request-Forgery.html

Thanks

**Comment by 0x777** [comment]
@doroniz The above reports expect access to the admin APIs, which is only possible through the admin secret. These cannot be classified as expolits or vulnerabilities.
