### ISSUE TITLE
[v2.0.0 - alpha] Null variables throwing `validation-failed` for non-required variables

### ISSUE THREAD

**Issue by martin-hasura** [hasura/graphql-engine#6822]
Non-present null variables are currently failing type checking.
1.3.3 functionality would allow the query to run without the variable being present.

If we run a query like the following without the variable:
```
query query($content: String) {
  post(where: {content: {_eq: $content}}) {
    title
    content
  }
}
```

We're currently returning the following error:
```
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.post.args.where.content._eq",
        "code": "validation-failed"
      },
      "message": "expected a string for type \"String\", but found null"
    }
  ]
}
```

**Comment by tirumaraiselvan** [comment]
This is the breaking change introduced in v2. You can set `HASURA_GRAPHQL_V1_BOOLEAN_NULL_COLLAPSE: true` to get the old behaviour back.
