### ISSUE TITLE
Console Permission Builder JSON parse error crash

### ISSUE THREAD

**Issue by holloway** [hasura/graphql-engine#6823]
Using `2.0.0-alpha.9` the permission builder in the console crashes

![Screenshot from 2021-04-27 09-36-56](https://user-images.githubusercontent.com/620580/116154165-6e93fa00-a73c-11eb-8308-97923108dab9.png)

I can't add additional fields, rules, etc.

A second later there's a full crash,

![Screenshot from 2021-04-27 09-41-57](https://user-images.githubusercontent.com/620580/116154566-ec580580-a73c-11eb-82d2-8ce1673baead.png)

The text of the error is,

```
Error

Something went wrong. Head back Home.

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/cloud/v2.0/main.js.gz:1:641846)
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/cloud/v2.0/main.js.gz:1:4586850)
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/cloud/v2.0/main.js.gz:1:140939)
    at e (https://graphql-engine-cdn.hasura.io/console/assets/channel/cloud/v2.0/vendor.js.gz:1:1838338)
    at v (https://graphql-engine-cdn.hasura.io/console/assets/channel/cloud/v2.0/vendor.js.gz:1:1835151)
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/cloud/v2.0/main.js.gz:1:6408291
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/cloud/v2.0/vendor.js.gz:1:4928031
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/cloud/v2.0/vendor.js.gz:1:4322764
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/cloud/v2.0/main.js.gz:1:4112119)

You can report this issue on our GitHub or chat with us on Discord
Something went wrong!
```

**Comment by holloway** [comment]
Bug doesn't seem browser dependent. It occurs in Firefox or Chrome.

I seem to be able to easily reproduce. E.g. in a table with no no foreign keys, with a single auto-incrementing integer column. Eg.

```
CREATE TABLE "default"."thingid" ("thing_id" serial NOT NULL, PRIMARY KEY ("thing_id") );
```

I'm using a locale console with Hasura Cloud if that matters.

**Comment by abhi40308** [comment]
Hello @holloway, I tried replicating this with `v2.0.0-alpha.9` console cli but couldn't. It was an earlier known issue with console which was fixed in a recent release. 
Could you tell me the exact steps to repro, and confirm you are using the latest version using `hasura version` command from cli.
For me its:
```
➜ hasura version
INFO hasura cli                                    version=v2.0.0-alpha.9
INFO hasura graphql engine                         endpoint="http://localhost:8080/" version=v2.0.0-alpha.9
```

**Comment by holloway** [comment]
@abhi40308

```
$ hasura version
INFO hasura cli                                    version=v2.0.0-alpha.9
```

It doesn't print out the `INFO hasura graphql engine` line. Maybe that's because I'm using Hasura Cloud and the endpoint is specified in my `config.yml`.

The console errors are originating from https://graphql-engine-cdn.hasura.io/console/assets/channel/cloud/v2.0/vendor.js.gz . That path doesn't have a cache busting `-cloud.9` in it, so if this was a recently fixed error, is is possible that `https://graphql-engine-cdn.hasura.io/` is serving old buggy code? I have my browser network cache disabled so I don't have a cached copy.

New screenshots showing I can easily reproduce the issue,

![Screenshot from 2021-04-29 21-14-46](https://user-images.githubusercontent.com/620580/116528894-71efd700-a930-11eb-851f-8543e7e46526.png)

![Screenshot from 2021-04-29 21-20-07](https://user-images.githubusercontent.com/620580/116529209-cbf09c80-a930-11eb-9819-f6df8703aea6.png)

This can occur from a new install that only has this migration,

```
CREATE TABLE "default"."formadmin" ("formadmin_id" uuid NOT NULL DEFAULT gen_random_uuid(), "formadmin_authprovider_id" text NOT NULL, "formadmin_name" text, "formadmin_primary_email" text, "formadmin_primary_mobilephone" text, "formadmin_details" jsonb, "formadmin_created_at" timestamptz NOT NULL DEFAULT now(), "formadmin_is_active" boolean, PRIMARY KEY ("formadmin_id") , UNIQUE ("formadmin_authprovider_id"), UNIQUE ("formadmin_primary_email"), UNIQUE ("formadmin_primary_mobilephone"));
CREATE EXTENSION IF NOT EXISTS pgcrypto;
```

Here's all my config [formally.tar.gz](https://github.com/hasura/graphql-engine/files/6397516/formally.tar.gz)

**Comment by abhi40308** [comment]
@holloway  Looks like CDN url is wrong, which is causing the issue. I've opened an issue for the same.

**Comment by holloway** [comment]
@abhi40308 Thanks for looking into this. Is there a temporary work around or should I wait on the new release? And any ETA on that?

This was affecting all Hasura Cloud customers, right? Feel free to give my account some free stuff :grin:

**Comment by abhi40308** [comment]
Hi @holloway, we will do a temporary workaround by updating the CDN URL with the latest assets pretty soon, our apologies that it happened. We have a super generous free-tier btw 😁, check it out [here](https://hasura.io/pricing/) if you missed it :)

**Comment by holloway** [comment]
Ok thank, and when might this be released? I just updated to `v2.0.0-alpha.10` and the assets it downloads still have this bug.

**Comment by holloway** [comment]
*sigh* ... I'm not meaning to be unreasonable, but your SaaS cloud product is still severely broken, because anyone can't add any security at all

**Comment by abhi40308** [comment]
@holloway really sorry to keep you waiting. I'll update this thread as soon as the assets issue is fixed.

**Comment by holloway** [comment]
Hi, the issue is the inability to add permissions

**Comment by abhi40308** [comment]
Hi @holloway, sorry to keep you waiting, seems like it is taking some time for this fix to be released. For the workaround, you can add the permissions in your Hasura cloud console, and those permissions should be reflected in your cli instance.

**Comment by holloway** [comment]
Hi @ccabhi40308 ...sad to say but I'm moving to self-hosting to avoid the bugs of the cloud product.

**Comment by abhi40308** [comment]
Hi @holloway, this should be fixed now. This was happening as some wrong assets were being served by the CLI due to an issue in the CI. Do let us know if you are still facing this or other issues. Closing this :)
