### ISSUE TITLE
Unclear metadata error in Hasura CLI

### ISSUE THREAD

**Issue by JacobGalati** [hasura/graphql-engine#6824]
If you are missing a ENV variable when trying to apply metadata  using `$ hasura metadata apply`.  You get a generic error. `source with name {database-name} is inconsistent`. Trying to debug using `$ hasura metadata inconsistency list` it returns no issues.

However if you go into the console settings interface and try to import the metadata json you get a much clearer error telling you the name of the ENV variable that is missing. This would be great if the CLI could also give you that kind of information.

**Comment by rikinsk** [comment]
This is caused due to https://github.com/hasura/graphql-engine/issues/6913

**Comment by scriptonist** [comment]
closed via https://github.com/hasura/graphql-engine/issues/6913
