### ISSUE TITLE
Hasura Events : Not able to view more than 10 invocation logs

### ISSUE THREAD

**Issue by n2ctech** [hasura/graphql-engine#6846]
We have a project in production on hasura cloud v2.0.0-cloud.9
We have thousands of DAU and as many events, however we are not able to see more than the past 10 invocation logs, processed events or pending evens. There is no option to change page or display more. 

It doesn't work for any team member, on any navigator. 

We really need this feature!

Screenshot attached for reference.
![image](https://user-images.githubusercontent.com/21331958/116556619-ed846080-a8fd-11eb-9cb1-f418b5444cae.png)

**Comment by rikinsk** [comment]
Clsoed via e6b5b66edf00237044428aa1574e1d99e1469c57
