### ISSUE TITLE
console/mssql: browse rows sections fails on a table with custom name

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#6849]
Create a table with a name that is not a valid graphql identifier, track it and head to the browse rows section. The graphql query issued seems to have the original table name and not the mapped 'custom_name' of the table.

**Comment by 0x777** [comment]
Let's close https://github.com/hasura/graphql-engine/issues/6647 when this is fixed.

**Comment by iykekings** [comment]
closing as fixed [here](https://github.com/hasura/graphql-engine/commit/726c3e07b3741e282ae751bfba3276cad2dffe29)
