### ISSUE TITLE
Arrays do not work in Action output types 

### ISSUE THREAD

**Issue by giulianok** [hasura/graphql-engine#6856]
I just migrated to `2.0.0-alpha9` from `1.3.3`, and the Arrays from Action types stopped working.

I'm trying to output an array of string, but instead, it outputs just a String

`terms` should be an array of strings
![Screen Shot 2021-05-01 at 10 04 32 PM](https://user-images.githubusercontent.com/8062245/116800133-4144a480-aacc-11eb-88b9-fb97dce4c3d3.png)

but instead, I get a string
![Screen Shot 2021-05-01 at 10 03 23 PM](https://user-images.githubusercontent.com/8062245/116800138-4e619380-aacc-11eb-9cfa-b7ae3788e9d1.png)

This causes a problem with codegen because I get now a type string instead of an array of strings

Things I've tried:
* `[String]`
* `[String!]`
* `[String!]!`
* Upgraded to `2.0.0-alpha10`

**Comment by arjunyel** [comment]
I believe this is a duplicate https://github.com/hasura/graphql-engine/issues/6631

**Comment by tirumaraiselvan** [comment]
Closing this in favour of #6631 . Thanks for the report.
