### ISSUE TITLE
Migrations timeout issue

### ISSUE THREAD

**Issue by sdahlbac** [hasura/graphql-engine#6857]
Background: I'm using hasura with an existing database

and having a migration that is slow (adding a generated always column to an existing table in this case, but could also be e.g. adding an index)

```hasura migrate apply --endpoint https://val-fieldops.arjo.com/hasura
WARN [cli: v2.0.0-alpha.10] [server: v1.3.3] version mismatch: older cli version might not be compatible with latest server apis, please update cli
FATA[0061] apply failed
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
 /html>
```

```hasura migrate apply --endpoint https://val-fieldops.arjo.com/hasura --dry-run
WARN [cli: v2.0.0-alpha.10] [server: v1.3.3] version mismatch: older cli version might not be compatible with latest server apis, please update cli
VERSION        TYPE  NAME
1620025979743  up    task_instances_division
```

but when I look in the database the migration has been applied

I guess I can workaround it by applying with skip execution

**Comment by martin-hasura** [comment]
How are you currently hosting your graphql-engine container? Is it currently running through something like nginx or another gateway?

That 504 may be that the gateway is waiting for a response and is timing out on that side of things, waiting for a response from the migration to finish applying.

**Comment by sdahlbac** [comment]
It is deployed in kubernetes so I suppose that it is possible that this issue is outside hasura

**Comment by sdahlbac** [comment]
This was very likely an issue with AWS lb
