### ISSUE TITLE
hasura scripts update-project-v3 fails with "FATA[0001] invalid character '<'"

### ISSUE THREAD

**Issue by vileanco** [hasura/graphql-engine#6872]
I was running v1.3.4-beta.2 in AWS Fargate and then I did the following:

1. Changed image to version v2.0.0-alpha.10
2. Waited for new container with version to start up
3. Updated hasura-cli from v1.3.4-beta.2 to v2.0.0-alpha.10
4. Run `hasura scripts update-project-v3 --log-level debug` locally against the Hasura container in AWS

Output:

```
DEBU global config file exisits, verifying contents 
DEBU global config is pre-set to &cli.GlobalConfig{UUID:"8e4fbf38-0972-43e9-9315-1ec5c6950ad5", EnableTelemetry:true, ShowUpdateNotification:true, CLIEnvironment:"default"} 
DEBU global config: uuid: 8e4fbf38-0972-43e9-9315-1ec5c6950ad5 
DEBU global config: enableTelemetry: true         
DEBU global config: showUpdateNotification: true  
DEBU global config: cliEnvironment: default       
DEBU cannot get config information from server, this might be because config API is not enabled: json: cannot unmarshal object into Go struct field HasuraServerInternalConfig.jwt of type string 
DEBU graphql engine endpoint: **********
DEBU graphql engine admin_secret: *********
DEBU versions: cli: [v2.0.0-alpha.10] server: [v2.0.0-alpha.10] 
DEBU compatibility check: [true] older cli version might not be compatible with latest server apis, please update cli
DEBU telemetry: beamed                             fields.time=148.61863ms isError=true
FATA[0001] invalid character '<' looking for beginning of value
```

It looks like there is some problem with getting the config information from server, however if I execute curl to /v1alpha1/config on the same hasura instance I get back the following:

```
{
    "version": "v2.0.0-alpha.10",
    "is_function_permissions_inferred": true,
    "is_remote_schema_permissions_enabled": false,
    "is_admin_secret_set": true,
    "is_auth_hook_set": false,
    "is_jwt_set": true,
    "jwt": {
        "claims_namespace": "https://hasura.io/jwt/claims",
        "claims_format": "stringified_json",
        "claims_map": null
    },
    "is_allow_list_enabled": false,
    "live_queries": {
        "batch_size": 100,
        "refetch_delay": 1
    },
    "console_assets_dir": null,
    "experimental_features": []
}
```

So it looks like config is working normally. Also the web console UI is working 100% correctly as well as the graphql API itself. The problem is with running any cli commands, also `migrate` and `metadata` commands fail with the same error. I spent all day trying to resolve this but could not figure out what is wrong. Also weirdly enough before doing this migration in the AWS, I did the same steps on a locally hosted docker instance on my computer and everything worked fine. Any idea how could I further investigate what's wrong with this?

**Comment by scriptonist** [comment]
@vileanco I was not able to reproduce this on my side. Can you provide a bit more information about this? Also, which operating system are you on?

**Comment by vileanco** [comment]
I have resolved this issue just today but I still couldn't exactly pinpoint the reason.

I have several services under one domain, and I was forwarding traffic in the load balancer from paths "/console", "/v1*", and "/v2*" to Hasura instance. After creating a subdomain and forwarding all traffic of the subdomain to Hasura, the error went away. So what I am guessing is that while forwarding paths ( /console /v1* and /v2*) were enough for cli v1.3.x to work, something has changed in v2 that made it not work anymore. Anyway, I guess host-based forwarding in the load balancer is more robust for the future so will stick with that for now! Thanks for looking into the issue.

**Comment by vileanco** [comment]
Yes, I guess we can close this.
