### ISSUE TITLE
console: show customization options when tracking table

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#6875]
Tables with non-compliant graphql names can't be tracked from the console otherwise. 

`<source>_track_table` API have a configuration option e.g. https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/table-view.html#id1 

We need to expose this in the UI during the track step.

Related: https://github.com/hasura/graphql-engine/issues/6647

**Comment by vijayprasanna13** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/b2cbd343bd05189f3dcf868978f05d52260f6adc
