### ISSUE TITLE
deep queries fail after alpha23

### ISSUE THREAD

**Issue by Verikon** [hasura/graphql-engine#688]
alpha23 seems to have introduced some issue with queries of reasonable depth.

I've set up a heroku instance here - https://hasura-piel.herokuapp.com/console

the following query no longer works (as of introducing alpha23)
```
{
  users {
    firstname
    roles {
      role{
        name
        locations {
          location {
            name
            amusements{
              amusement{
                name
                tickets{
                  ticket{
                    ticketnum
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

If i remove some of the inner items (amusements->tickets) it will work again:
```
{
  users {
    firstname
    roles {
      role{
        name
        locations {
          location {
            name
          }
        }
      }
    }
  }
}

```

if i remove some of the outer items (users->roles) it too will work again:
```
{
  locations {
    name
    amusements {
      amusement {
        name
        tickets {
          ticket {
            ticketnum
          }
        }
      }
    }
  }
}
```

**Comment by Verikon** [comment]
I should make mention, this worked in the release prior to alpha23.

**Comment by coco98** [comment]
For reference, I’ve linked to this on the discord h-general channel with an
example too.
