### ISSUE TITLE
Insert row as migration

### ISSUE THREAD

**Issue by amal-chandran** [hasura/graphql-engine#6884]
### Current
The **enum tables** and other constant tables need to **save values as migrations** is a better way
currently, we need to insert it using SQL window and we can create a migration.

### Expected 
Each table has an insert row section. where we can add a check box like track this as migration and on checking that we can provide the name for the migration its a small requirement but good to have.

**Comment by rikinsk** [comment]
@adevofficial this is already possible. Are you looking for something else here?
![Screenshot from 2021-08-25 13-36-27](https://user-images.githubusercontent.com/54616969/130752521-920a8c67-0553-4cd2-b91e-7eb46e8a99d3.png)

**Comment by rikinsk** [comment]
Closing this. Feel free to reopen.
