### ISSUE TITLE
[v2.0.0-alpha.10] No tables when creating event trigger

### ISSUE THREAD

**Issue by Tyler-RCSD** [hasura/graphql-engine#6896]
When trying to create an event trigger the database/schema dropdowns work but the table drop down is empty.  PostgreSQL 12.6.  I have ~20 tables tracked in Hasura.  Is something configured wrongly or is this a bug?

![image](https://user-images.githubusercontent.com/42674425/117712791-014b8480-b192-11eb-9241-cb3385021946.png)

**Comment by Tyler-RCSD** [comment]
I'll add that there is a request that runs when the page load that is returning all my tracked tables, but none of them end up in the dropdown.  Seems like a console bug?

![image](https://user-images.githubusercontent.com/42674425/118012355-31b82d80-b30e-11eb-957d-d06506e31e46.png)

**Comment by martin-hasura** [comment]
Hey @Tyler-RCSD - going to close this issue - the other ticket you linked is from the team, we actively have this in the backlog and should have a fix up for 2.0 soon
