### ISSUE TITLE
console: cannot give whitespace in comment while modifying action

### ISSUE THREAD

**Issue by abhi40308** [hasura/graphql-engine#6897]
Steps to reproduce: 

1. Visit the Actions tab.
2. Create an action with some comment
3. Try modifying the action comment

**Comment by k-herm** [comment]
Anyone mind if I take a crack at this?

**Comment by abhi40308** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/e6c62e6793aee61402a4cf577ec3ae81dcf8534d
