### ISSUE TITLE
Empty subscription_root when no reading permissions apply

### ISSUE THREAD

**Issue by emdagon** [hasura/graphql-engine#6898]
I have a project that publicly exposes a few actions using `HASURA_GRAPHQL_UNAUTHORIZED_ROLE`. Those work fine, but some tools (ie: graphql-codegen) fail with an error complaining about `subscription_root` being empty.

I was able to generate the schema and in fact it has the subcription_root declared, empty:

```
schema {
  query: query_root
  mutation: mutation_root
  subscription: subscription_root
}

type query_root {
    ...
}

type mutation_root {
    ...
}

type subscription_root    <-------

scalar timestamptz
scalar uuid
...
```

The workaround I found for this is to publicly expose a table.

Happy to provide more details if necessary.

**Comment by nicuveo** [comment]
This was auto-closed when the PR fixing it was merged; it'll be part of the next release. :)
