### ISSUE TITLE
docs: document websocket keep alive interval

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#6915]
Support added in https://github.com/hasura/graphql-engine/pull/6092

add `HASURA_GRAPHQL_WEBSOCKET_KEEPALIVE` env var to server configuration table page. use case and usage can be added as an example in the config example page

**Comment by tobiasbudig** [comment]
@rikinsk did you found out if the value for the `HASURA_GRAPHQL_WEBSOCKET_KEEPALIVE` env var is in milli seconds? Or is it in another format?

**Comment by rikinsk** [comment]
@tobiasbudig the value is in seconds. default value: 5

**Comment by rikinsk** [comment]
closed via https://github.com/hasura/graphql-engine/commit/8246bcc9d329ac9231af73799499ff37be5f4ec6
