### ISSUE TITLE
docs: update one-to-one relationships guide

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#6918]
Update [one-to-one relationships guide](https://hasura.io/docs/latest/graphql/core/guides/data-modelling/one-to-one.html#one-to-one-modelling) with new changes added in https://github.com/hasura/graphql-engine-mono/pull/1236 and remove limitations section 

_addendum_: Change this to show the usage of `before_parent` and `after_parent` configurations.

**Comment by Spark3000** [comment]
Link to the PR is dead now. I can't find definitive info about what this was about. I've looked in the release changelogs with no luck.

**Hopefully** one-to-one relationships with nested inserts with foreign key in the "child" table now work? Is that right?

**Comment by rikinsk** [comment]
@Spark3000 yes. nested inserts now work from either directions bye virtue of [this](https://hasura.io/docs/latest/graphql/core/api-reference/syntax-defs.html#insertorder)

**Comment by edmbn** [comment]
> @Spark3000 yes. nested inserts now work from either directions bye virtue of [this](https://hasura.io/docs/latest/graphql/core/api-reference/syntax-defs.html#insertorder)

Nested updates/upserts aren't working yet, right?

**Comment by rikinsk** [comment]
closed via https://github.com/hasura/graphql-engine/commit/8246bcc9d329ac9231af73799499ff37be5f4ec6

**Comment by maaft** [comment]
Where can "after_parent" be set? It's not stated anywhere in the docs

**Comment by FlxEd** [comment]
> Where can "after_parent" be set? It's not stated anywhere in the docs

I am desesperately searching for that too ... :/

**Comment by spookyuser** [comment]
me 3 :(
