### ISSUE TITLE
Console crashes when trying to access an inherited table

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#6926]
Trying to access a [PG inherited table](https://www.postgresql.org/docs/10/tutorial-inheritance.html) from the left nav bar (Data manager) makes the console crash:

Version tested: `v2.0.0-cloud.10`
Other information: queries and mutations work as expected; also, inheritance in PG is quite cool!

### Steps to reproduce

1) Create a set of two tables, one of which is inherited from the other:
   ```
   CREATE TABLE cities (
   id SERIAL PRIMARY KEY,
   name       text,
   population real,
   elevation  int     -- (in ft)
   );

   CREATE TABLE capitals (
   state      char(2) UNIQUE NOT NULL
   ) INHERITS (cities);
   ```
2) Head to the nav bar in the Data section and click on the inherited table (`capitals`) -  this will result in the following error:

<img width="1377" alt="Screenshot 2021-05-14 at 6 25 54 PM" src="https://user-images.githubusercontent.com/24300818/118273673-dc347a00-b4e1-11eb-8caf-91fe9f04e1a0.png">

**Comment by PedroBern** [comment]
Same here.
