### ISSUE TITLE
uuid! URL parameter in REST endpoint not supproted

### ISSUE THREAD

**Issue by fi0** [hasura/graphql-engine#6938]
`{"path":"$","error":"Type of URL parameter not supported - Consider putting it in the request body: \"a\"","code":"bad-request"}`

in the docs, UUID is interpreted as string
https://hasura.io/docs/latest/graphql/core/api-reference/restified.html

**Comment by rikinsk** [comment]
Hi, thanks for reporting this. This issue is fixed in 3fad5f6678a107b50856922ce293cea383e94e72 and should be available in the next release
