### ISSUE TITLE
hasura migrate fails on initial migration setup with Hasura Cloud

### ISSUE THREAD

**Issue by osdiab** [hasura/graphql-engine#6943]
Hi all, I sent this to Hasura Cloud support but haven't gotten any useful response yet, so trying here.

I created a new Hasura Cloud instance with nothing in it and try to run `hasura migrate` with the v2 alpha CLI tool like so:

```
hasura migrate create "init" --from-server --database-name default --log-level DEBUG
```

My `config.yaml` looks like this:

```
version: 3
endpoint: https://spinach.hasura.app
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
```

That produces this output:

<details>
<summary>Output</summary>

```
DEBU global config file exisits, verifying contents
DEBU global config is pre-set to &cli.GlobalConfig{UUID:"f21a688f-60ea-454e-87aa-1a22242b9d16", EnableTelemetry:true, ShowUpdateNotification:true, CLIEnvironment:"default"}
DEBU global config: uuid: f21a688f-60ea-454e-87aa-1a22242b9d16
DEBU global config: enableTelemetry: true
DEBU global config: showUpdateNotification: true
DEBU global config: cliEnvironment: default
DEBU cannot get config information from server, this might be because config API is not enabled: json: cannot unmarshal object into Go struct field HasuraServerInternalConfig.jwt of type string
DEBU graphql engine endpoint: https://spinach.hasura.app
DEBU graphql engine admin_secret: <REDACTED>
DEBU versions: cli: [v2.0.0-alpha.10] server: [v2.0.0-cloud.10]
DEBU compatibility check: [true] older cli version might not be compatible with latest server apis, please update cli
DEBU server: uuid: a2007ce5-13b5-4ef1-a66d-cf68dd9d92d7
DEBU response: {"path":"$","error":"resource does not exist","code":"not-found"}
DEBU telemetry: beamed                             fields.time=1.244104166s isError=true
FATA[0004] cannot fetch schema dump: [not-found] resource does not exist ($)
```

</details>

As a result I can't follow the [setup instructions on Hasura's website](https://hasura.io/docs/latest/graphql/core/migrations/migrations-setup.html#migrations-setup) to set up migrations on my project.

Salient part seems to be the `json: cannot unmarshal object into Go struct field HasuraServerInternalConfig.jwt of type string` - not sure how to debug that. Any thoughts?

**Comment by scriptonist** [comment]
@osdiab the error `json: cannot unmarshal object into Go struct field HasuraServerInternalConfig.jwt of type string` can be ignored. The actual error seems to be `FATA[0004] cannot fetch schema dump: [not-found] resource does not exist ($)`

CLI uses [pg_dump API](https://hasura.io/docs/latest/graphql/core/api-reference/pgdump.html) behind the scenes for the command you mentioned. It looks like it's not reachable.
I quickly tried to reproduce this on my app on hasura cloud, but it seems to work as expected. 

Can you try to verify if the following request to `/v1alpha1/pg_dump` succeeds from your side?
```
curl --location --request POST 'http://<hasura-cloud-endpoint>/v1alpha1/pg_dump' \
--header 'x-hasura-admin-secret: <admin-secret>' \
--header 'Content-Type: application/json' \
--data-raw '{
  "opts": ["-O", "-x", "--schema-only", "--schema", "public"],
  "clean_output": true
}'
```

**Comment by osdiab** [comment]
I tried running that and it also just returns `{"path":"$","error":"resource does not exist","code":"not-found"}`. IS there something I need to configure on Hasura Cloud to make that API available?

**Comment by scriptonist** [comment]
@osdiab any chance this API is disabled using [HASURA_GRAPHQL_ENABLED_APIS](https://hasura.io/docs/latest/graphql/core/deployment/graphql-engine-flags/reference.html#command-config)?

**Comment by osdiab** [comment]
@scriptonist That was it! Just saw it in the Hasura Cloud config.

that seems like a good candidate to be included in the docs (alongside the fact that the linked document above doesn't specify that its commands don't actually work unless you use the v2.0 alpha CLI tool).
