### ISSUE TITLE
Where query no longer works the same since upgraded to latest version

### ISSUE THREAD

**Issue by shaunnez** [hasura/graphql-engine#6946]
I was able to  run the query below and if no id was provided, the where clause would effectively ignore the null field giving me all the foos. Now, in the latest version of hasura, it's saying "Get me the foo where id is null", and therefore no foos.

`query Foos($optionalId) {
  Foos(where : { id: { _eq: $optionalId } } ) {
    id
    name
  } 
}`

Now if this is intentional... fine, i'll have to duplicate a bunch of queries.. ALternatively, is there a way to make the where claude more "dynamic"

**Comment by arjunyel** [comment]
Changed here: https://github.com/hasura/graphql-engine/releases/tag/v2.0.0-alpha.8

**Comment by rikinsk** [comment]
@shaunnez This was an intentional change introduced in v2.0. You can set the env var `HASURA_GRAPHQL_V1_BOOLEAN_NULL_COLLAPSE` to `true` in versions > `v2.0.0-alpha.8`  to continue using the above query
