### ISSUE TITLE
server/bigquery: global limit setting that applies to all tables

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#6947]
Currently with graphql-engine, one can limit the number of rows a user can fetch by `limit` field in select permissions. However no limit applies for the admin role. With databases such as bigquery, where a table typically holds millions of rows, we need a way to limit rows for admin role. 

A bigquery source should take an extra option in `configuration` section - `global_select_limit`. The semantics of `global_select_limit` are as follows:
1. It is mandatory
1. For admin role, it is equivalent to having a `limit` defined with `global_select_limit` in the select permission on all tables.
1. For non-admin roles, `r`, if the `limit` on a table `t` is not defined in the select permission, it defaults to `global_select_limit`.

**Comment by chrisdone** [comment]
I'll check out how easy it is to handle this in `FromIr` and if it's fine I'll report here before I start.

**Comment by chrisdone** [comment]
Given the changes in [Bigquery/cleanups](https://github.com/hasura/graphql-engine-mono/pull/1317) removes the Haskell-level joining and performs a single SQL query now, perhaps this feature can be cancelled.

**Comment by chrisdone** [comment]
I think it'd be helpful if a log was written somewhere to say "a limit was hit" - because if you hit a limit and you don't know you did, that can be confusing.

**Comment by chrisdone** [comment]
Admittedly, that's pretty tricky to implement (always selecting N+1 and then doing checks). So let's not do that.
