### ISSUE TITLE
expose graphiql as a documentation page

### ISSUE THREAD

**Issue by ecthiender** [hasura/graphql-engine#695]
- Perhaps add `graphiql_access_key` as an env var
- Integrate with graphqldoc https://github.com/2fd/graphdoc

**Comment by sdabhi23** [comment]
@ecthiender I would like to help out with this one

**Comment by sdabhi23** [comment]
Should this be implemented like #314? Also what will be the  role of the env var?

**Comment by ecthiender** [comment]
@praveenweb @coco98 can you give @sdabhi23 more context? Also we have already done https://graphiql-online.com/ ; so not sure if this necessary.

**Comment by iamzjk** [comment]
@ecthiender I didn't know https://graphiql-online.com/. I really like it. Is it possible that I can host my own version of it for my graphql?

**Comment by praveenweb** [comment]
@iamzjk - You can view the source code [here](https://github.com/hasura/graphql-engine/tree/master/community/tools/graphiql-online). Dockerfile is available. Can be deployed anywhere.

@sdabhi23 @ecthiender - Closing this issue as https://graphiql-online.com should be good enough to share for documentation purposes.

**Comment by adamrneary** [comment]
It looks like this requires Hasura login to use?
