### ISSUE TITLE
RFC: server integration test suite improvements

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#6951]
## Proposed problems and solutions

🙏🏽 _But first, a grateful acknowledgement of past & ongoing contributions to an extensive integration test suite and significant CI build & test run time improvements._

### 🚀 test run time: https://github.com/hasura/graphql-engine/issues/7136

it currently takes 15+ mins on a beefy desktop to run the postgres integration test suite; we can expect significant slowdown as we add backends. Coupled with [hour-long CI build times (in P95)](https://app.circleci.com/insights/github/hasura/graphql-engine-mono/workflows/build_and_test_workflow/overview) this is prohibitive to testing and integrating changes quickly.

_suggested goal:_
reduce local integration test run time from ~15mins to [insert suggestions here. A quick Google indicates that a reasonable run time is 3-5 minutes].

_suggested improvements_

- confirm that running the entire suite locally is a common workflow. I only have a few data points including my own experience to suggest this is even an issue.
- document running tests in parallel as part of the local development process.
- optimise metadata operations, as suggested in [recent work](https://github.com/hasura/graphql-engine/commit/a935746e174f60463ea7436fc86207d9659cd8e6) improving integration tests.
- figure out, or document, how to easily identify relevant tests for a particular feature, such that devs don't have to run the entire suite.
  - combine a haskell code coverage report with the local git diff

### 🎉 testing new backends: https://github.com/hasura/graphql-engine/issues/7137

adding test support for a new backend (e.g. SQL Server, BigQuery) is currently a [4 or 5-step process](https://github.com/hasura/graphql-engine/blob/master/server/CONTRIBUTING.md#adding-test-support-for-a-new-backend) involving a lot of code and yaml-file duplication, with many minor, manual and error-prone tweaks (see linked examples). This is likely to discourage extensive testing and community contribution.

_suggested goal:_ eliminate/minimise duplication of code and test files for backend-agnostic feature tests and optimise workflow for backend-specific feature testing.

_suggested improvements_

- restructure tests into backend-specific and -agnostic tests so the former is clearer to identify and contribute to.
- introduce some generator or intermediate representation for test setup/teardown.
  - explore [synth](https://github.com/openquery-io/synth) for alt-backend test data generation given a Postgres data set 

### ❤️ debugging/fixing tests: https://github.com/hasura/graphql-engine/issues/7138

our pytest output has a pretty low signal:noise ratio, and it's often difficult to understand the cause of a test failure, if there is one. [Example: a 8600-line log for what turned out to be a flaky test that passed on a second run](https://app.circleci.com/pipelines/github/hasura/graphql-engine-mono/10008/workflows/5e17c77f-4b96-43aa-8a5b-bb722a80ddd0/jobs/192672/parallel-runs/23/steps/23-106).

_suggested improvements_

- there's almost certainly some pytest configuration that would help with this. Adjust circleci config and local testing scripts to reduce verbosity.
- better isolate (or reduce) stateful tests.

### 👀 reasoning about test state and coverage: https://github.com/hasura/graphql-engine/issues/7139

identifying which tests are actually run and which setup/teardown files support them seems to be a manual lookup of test files to string filepaths. [Example](https://github.com/hasura/graphql-engine/blob/master/server/tests-py/test_graphql_queries.py#L158-L170). This contributes to cargo-culting redundant files and makes refactoring/unused file cleanup difficult.

_goal:_ unsure, to be honest. Is it enough to find and remove dead code regularly, so that we have more confidence that the existing files are relevant? In which case...

_suggested improvements_

- explore test coverage / dead code elimination tools such as [vulture](https://pypi.org/project/vulture/) and [pytest-cov](https://pypi.org/project/pytest-cov/)
- introduce a set of setup/teardown files per test class, following an obvious naming convention

## Request for comments
- Hasura team: I think you should be able to edit this description directly, please do so with additions or corrections.
- Otherwise, please comment below with anything else you'd like to see improved with the server integration test workflow. 
- I've just added emojis to each title as an experiment. If you've experienced some pain in that part of the workflow, but don't want to write anything, just react with that emoji. We may or may not use this to prioritise what to work on 😅

## What happens next
I'll leave this open for at least a few weeks to gather feedback and suggestions. However, the team's quite keen to address these kinds of ongoing improvements, so will likely prioritise some of them in our upcoming sprints and update this issue accordingly.

**Comment by jberryman** [comment]
Thanks for putting this together Abby!

> - figure out, or document, how to easily identify relevant tests for a particular feature, such that devs don't have to run the entire suite.

We could in theory hack something together with haskell code coverage, for each integration test class/module store a code coverage report, then (waves hands) combat that with the local git diff...

> adding test support for a new backend (e.g. SQL Server, BigQuery) is currently a 4 or 5-step process involving a lot of code and yaml-file duplication, with many minor, manual and error-prone tweaks (see linked examples). This is likely to discourage extensive testing and community contribution.

The process linked for adding a new backend doesn't sound too bad to me, but I probably have low expectations... but I definitely agree with the goal of encouraging thorough testing against new backends.

> our pytest output has a pretty low signal:noise ratio, and it's often difficult to understand the cause of a test failure, if there is one. Example: a 8600-line log for what turned out to be a flaky test that passed on a second run.

One thing I've noticed is some sets of tests within a class are stateful, so if an earlier test fails the later ones will too. The appropriate thing is I think to just make them one big test (commenting the different phases).

> identifying which tests are actually run and which setup/teardown files support them seems to be a manual lookup of test files to string filepaths. Example. This contributes to cargo-culting redundant files and makes refactoring/unused file cleanup difficult.

Ya it's annoying to match setup/teardown specs to tests... I think an improvement would be to have every test class have its own set of setup/teardown files, following some obvious naming convention, even if that meant duplicating some of these files

**Comment by sassela** [comment]
Thanks so much for these suggestions @jberryman, I've included them in the description above.

> The process linked for adding a new backend doesn't sound too bad to me

I hope @vladciobanu doesn't mind me linking to their [PR as an example](https://github.com/hasura/graphql-engine-mono/pull/1329/files) to illustrate that the process in practice turns out to be much more clunky. 

The request format for `v1/query` (existing Postgres tests) and `v2/query` (new backend tests) differs ever so slightly, and new backend tests require split setup files for `v1/metadata` and `v2/query` requests, which introduces a lot of _almost_ entirely duplicated files, with minor manual alterations. 

Combined with unclear test logs, testing new backends in bulk can be difficult due to errors or test failures that might be caused by SQL syntax, `.yaml` file format, missing setup, stateful tests or any combination thereof.

**Comment by vladciobanu** [comment]
For "reasoning about test state and coverage":

> goal: unsure, to be honest. Is it enough to find and remove dead code regularly, so that we have more confidence that the existing files are relevant? In which case...

How about unifying the way we do setup/teardown such that there is a single way to do so? The syntax might become slightly more complex, but the advantage is that it'll always be clear how to do it, and there's no more redundancies.

Additionally, I think adding new tests should only rely on creating new files. It's really easy to forget to update the Python classes to add the appropriate method and get PRs accepted.

**Comment by sassela** [comment]
I've created separate issues for each of the proposed goals listed above; we'll aim to prioritise these in the server team sprints in the next few weeks, but please consider these individual issues open to feedback, discussion and contribution.

Otherwise closing this RFC with the plan to keep the individual issues updated.
