### ISSUE TITLE
[v2.0.0-alpha.5] Hasura not reading from the session variable with AzureAD JWT token

### ISSUE THREAD

**Issue by jbek7** [hasura/graphql-engine#6952]
I'm trying a simple permission config for update. Consider this custom check permission for update with role "contributor":
```json
{
  "_exists": {
    "_where": {
      "resource_id": {
        "_eq": "X-Hasura-Allowed-Resource-Id"
      }
    },
    "_table": {
      "schema": "public",
      "name": "user_roles"
    }
  }
}
```

I see the variables are sent in the header:

```
X-Hasura-Allowed-Resource-Id: 369
x-hasura-role: contributor
```

But I'm getting this error:

```json
{
  "errors": [  { "extensions": {  "path": "$",  "code": "not-found"  },
      "message": "missing session variables: \"x-hasura-allowed-resource-id\"" 
    }]
}
```

I've an authorization bearer token from AzureAD and it's configuration is as follows:

```
HASURA_GRAPHQL_JWT_SECRET: '{ "type":"RS256", "jwk_url": "https://my-azure.domain.com/as/discovery/v2.0/keys", "claims_namespace_path": "$$", "claims_map": { "x-hasura-allowed-roles": ["reader","admin","contributor"], "x-hasura-default-role": "reader", "x-hasura-user-id": {"path":"$$.oid"} } }'
```
And it might be related to this issue: #5068 

I'm using Hasura `v2.0.0-alpha.5`.

Update: The same problem in `v2.0.0-alpha.10`

Update II: Downgraded to 1.3.3 still the same.

**Comment by tirumaraiselvan** [comment]
Just as a sanity check, can you check if the variable name is correct? I see `"_eq": "X-Hasura-Allowed-Resource_Id"` in your JSON which has an underscore but the header is `x-hasura-allowed-resource-id`

**Comment by jbek7** [comment]
downgraded to 1.3.3 but still the same

**Comment by jbek7** [comment]
@tirumaraiselvan I think the problem is you can't send custom hasura header (x-hasura-***) along with JWT header (Authorization: Bearer jwt-token)? 🤔

**Comment by tirumaraiselvan** [comment]
@jbek7 Yes, you can only send raw session variables with the admin token (`x-hasura-admin-secret`). With normal JWT tokens, you need to send the session variables inside the JWT token.
