### ISSUE TITLE
Hide postgres system objects (pg_toast_temp, pg_temp) by default or by configuration

### ISSUE THREAD

**Issue by shaunnez** [hasura/graphql-engine#6954]
Hello

I have ALOT of temporary tables, and it's annoying me that they show in the database table list. Is there a way to hide these? (In pgAdmin tool, they are hidden unless you toggle on show system objects)

![image](https://user-images.githubusercontent.com/1751766/118892685-61da7e80-b955-11eb-84c2-6e0f6a1d51ea.png)

![image](https://user-images.githubusercontent.com/1751766/118892727-70c13100-b955-11eb-93c6-00d2212bb5cc.png)

Cheers
Shaun

**Comment by 0x777** [comment]
@beerose Looks like this is the query that we are using to fetch the list of schemas in Postgres:
```sql
SELECT
  schema_name
FROM
  information_schema.schemata
WHERE
  schema_name NOT IN (
    'information_schema',
    'pg_catalog',
    'hdb_catalog',
    'hdb_views',
    'pg_temp_1',
    'pg_toast_temp_1',
    'pg_toast'
  )
```

It should instead be as follows:
```sql
SELECT
  schema_name
FROM
  information_schema.schemata
WHERE
  schema_name NOT IN ('information_schema', 'hdb_catalog', 'hdb_views')
  AND schema_name NOT LIKE 'pg_%'
```

**Comment by abhi40308** [comment]
This should be fixed now, ref https://github.com/hasura/graphql-engine/commit/c0fde4d1d5571465a428d97f6e1e52ad47509850
