### ISSUE TITLE
Customise Health endpoint

### ISSUE THREAD

**Issue by jarleriksen** [hasura/graphql-engine#6958]
Hi,

We are currently self-hosting our Hasura instance on Google Cloud App Engine.
We are trying to use the `healthz` endpoint exposed by the GraphQL engine to monitor for inconsistent metadata.

However, `healthz` is a reserved path for App Engine and as far as I can tell it's not possible to customise the path in Hasura.

If it's not something that's going to be implemented or you have alternative solutions, I think it would be awesome to have it added to the docs. I spent some time figuring this one out :)

I would be more than happy to provide a PR for the docs.

Thanks!

**Comment by sordina** [comment]
Hi @jarleriksen,

Quick question, which of these would work for you?

* An additional health endpoint, such as `/healthz2` or `/healthz-hasura`?
* The health endpoint to be customizable via command-line-options, with `/healthz` returning a 404.

**Comment by jarleriksen** [comment]
Hi @sordina,
Honestly, any of those would work fine. A common solution is to prefix it with something to avoid the clashing e.g. `/hasura/healthz` etc.

Google uses `/_ah` for their prefix.

**Comment by kolharsam** [comment]
Hi @jarleriksen,
We've added `/hasura/healthz` which mirrors `/healthz`. 
This should be out in one of the upcoming releases.

**Comment by bkniffler** [comment]
Its cool to have an alternative endpoint, but I can't do migrations now because the cli will attempt to check the endpoint health via /healthz, but since it is reserved in app engine / cloud run, it may just return 404. Could the CLI default to /hasura/healthz?

**Comment by romainbriand** [comment]
> Its cool to have an alternative endpoint, but I can't do migrations now because the cli will attempt to check the endpoint health via /healthz, but since it is reserved in app engine / cloud run, it may just return 404. Could the CLI default to /hasura/healthz?

I'm having the same issue with the CLI to apply metadata, migrations, etc. to our Google Cloud Run hosted endpoint. Is there any possible workaround?

**Comment by romainbriand** [comment]
I've submitted a PR here: https://github.com/hasura/graphql-engine/pull/7994
