### ISSUE TITLE
cli: new metadata file structure changes

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#6959]
These changes are introduced by d5ff1acf2df68b3b40195bcb903801b5e5457f98 and the upcoming citus support. 

1. In the definition of *object relationships*, `foreign_key_constraint_on` previously accepted a single column name, a String. Now it can be one of these things

   - `String`
   - `[String]`
   - ```
     {
       "table": TableName
       /* only one of column/columns should be present */
       "column": String,
       "columns": [String]
     }
     ```

1. In the definition of *array relationships*, `foreign_key_constraint_on` changes as follows:

   ```
   {
     "table": TableName
     /* only one of column/columns should be present */
     "column": String,
     "columns": [String]
   }
   ```

   i.e, `columns` is a the new key that is introduced

**Comment by scriptonist** [comment]
closing since this change in metadata should get addressed without additional changes on CLI.
