### ISSUE TITLE
FATA[0000] unknown flag: --database-name

### ISSUE THREAD

**Issue by bennettl** [hasura/graphql-engine#6965]
I tried running hasura migrate apply with database name flag, but it said flag not found.

I see this as available in documentation over @ https://hasura.io/docs/latest/graphql/core/hasura-cli/hasura_migrate_apply.html 

However, it is not available when i execute hasura migrate apply help.

I am on hasura v1.3.3 of the cli

**Comment by scriptonist** [comment]
@bennettl this flag is applicable for the latest v2.0.0 releases only

**Comment by bennettl** [comment]
@scriptonist the latest CLI tool is v1.3.3 correct?

https://www.npmjs.com/package/hasura-cli

**Comment by bennettl** [comment]
bash-3.2$ hasura migrate help
Manage migrations on the database

Usage:
  hasura migrate [command]

Available Commands:
  apply       Apply migrations on the database
  create      Create files required for a migration
  squash      (PREVIEW) Squash multiple migrations into a single one
  status      Display current status of migrations on a database

Flags:
      --admin-secret string            admin secret for Hasura GraphQL Engine (env "HASURA_GRAPHQL_ADMIN_SECRET")
      --certificate-authority string   path to a cert file for the certificate authority (env "HASURA_GRAPHQL_CERTIFICATE_AUTHORITY")
      --endpoint string                http(s) endpoint for Hasura GraphQL Engine (env "HASURA_GRAPHQL_ENDPOINT")
  -h, --help                           help for migrate
      --insecure-skip-tls-verify       skip TLS verification and disable cert checking (default: false) (env "HASURA_GRAPHQL_INSECURE_SKIP_TLS_VERIFY")

Global Flags:
      --envfile string      .env filename to load ENV vars from (default ".env")
      --log-level string    log level (DEBUG, INFO, WARN, ERROR, FATAL) (default "INFO")
      --no-color            do not colorize output (default: false)
      --project string      directory where commands are executed (default: current dir)
      --skip-update-check   Skip automatic update check on command execution
