### ISSUE TITLE
Hasura CLI --database-name Issue

### ISSUE THREAD

**Issue by bennettl** [hasura/graphql-engine#6968]
Following up on this issue, which is not resolved and I cannot reopen https://github.com/hasura/graphql-engine/issues/6965 

There's a discrepancy between whats in the docs and what the CLI tool supports.

I started using Hasura this week, so everything I have is latest. The latest CLI version v1.3.3 and I'm connected to a newly created Hasura cloud

The CLI tool does not support the --database-name flag which means we cannot apply migrations to our database with a name other than default, but the tutorials and documentation uses this flag.

Here's the command I typed with the CLI tool and note that database-name is not here, also the flag is not recognized.

`bash-3.2$ hasura migrate help
Manage migrations on the database

Usage:
hasura migrate [command]

Available Commands:
apply Apply migrations on the database
create Create files required for a migration
squash (PREVIEW) Squash multiple migrations into a single one
status Display current status of migrations on a database

Flags:
--admin-secret string admin secret for Hasura GraphQL Engine (env "HASURA_GRAPHQL_ADMIN_SECRET")
--certificate-authority string path to a cert file for the certificate authority (env "HASURA_GRAPHQL_CERTIFICATE_AUTHORITY")
--endpoint string http(s) endpoint for Hasura GraphQL Engine (env "HASURA_GRAPHQL_ENDPOINT")
-h, --help help for migrate
--insecure-skip-tls-verify skip TLS verification and disable cert checking (default: false) (env "HASURA_GRAPHQL_INSECURE_SKIP_TLS_VERIFY")

Global Flags:
--envfile string .env filename to load ENV vars from (default ".env")
--log-level string log level (DEBUG, INFO, WARN, ERROR, FATAL) (default "INFO")
--no-color do not colorize output (default: false)
--project string directory where commands are executed (default: current dir)
--skip-update-check Skip automatic update check on command execution`

**Comment by scriptonist** [comment]
@bennettl The docs currently point to steps with respect to the latest per-release which is https://github.com/hasura/graphql-engine/releases/tag/v2.0.0-alpha.10

**Comment by bennettl** [comment]
To my understanding the graphql-engine and cli tool are different binaries correct? I'm using the latest of each.

```
DGB-D88RSML85:hasura-project leebennett$ hasura version
INFO hasura cli                                    version=v1.3.3
WARN [cli: v1.3.3] [server: v2.0.0-alpha.10] version mismatch: older cli version might not be compatible with latest server apis, please update cli 
INFO hasura graphql engine                         endpoint="http://localhost:8080" version=v2.0.0-alpha.10

```

This is currently a showstopper for us because AWS RDS does not allow `default` for database name

**Comment by rikinsk** [comment]
@bennettl This seems to be a confusion caused due to Hasura v2.0.0 not being released as stable yet. The latest stable release currently is v1.3.3 but the docs have been updated based on v2.0.0-alpha.10. This is understandingly confusing and we will attempt to clarify this in the docs. 

In the meanwhile you can follow the steps in https://hasura.io/docs/latest/graphql/core/migrations/config-v2/migrations-setup.html to set up your migrations with Hasura v1.3.3.

Hope this helps clear the confusion.

**Comment by rikinsk** [comment]
I just noticed that you mentioned connecting to a Hasura cloud project. New projects in Hasura cloud already use Hasura v2.0 and hence you can use the latest alpha release of the CLI to interact with it. You can update to a prelease CLI version by specifying the version, i.e. `hasura update-cli --version v2.0.0-alpha.10` _(PS: a stable release for 2.0 is around the corner)_. All the steps in the [migration guide](https://hasura.io/docs/latest/graphql/core/migrations/migrations-setup.html) you were following should now work.

**Comment by scriptonist** [comment]
@bennettl yes, you have to update to config v3.
