### ISSUE TITLE
Hasura UI not showing Data tables with "Cannot read property 'unique_constraints' of undefined"

### ISSUE THREAD

**Issue by istarkov** [hasura/graphql-engine#6975]
Hasura affected v2.0.0-alpha.10 - v2.0.0-alpha.11 (havent used previous alphas)

Every time Im opening hasura UI data tab
![image](https://user-images.githubusercontent.com/5077042/119538949-4a0b5c00-bd94-11eb-8071-34925940fc18.png)

I see `Loading...` forever. In browser console I see error `Cannot read property 'unique_constraints' of undefined`

![image](https://user-images.githubusercontent.com/5077042/119539006-5f808600-bd94-11eb-9645-96093b3d3ef5.png)

**Comment by abhi40308** [comment]
Hi @istarkov, Is it possible to send the hasura metadata and/or the hasura migrations? You can also send it to me privately on abhijeet@hasura.io

**Comment by istarkov** [comment]
Thank you! Sent.

**Comment by abhi40308** [comment]
This should be fixed now https://github.com/hasura/graphql-engine/commit/83e1f51d2cad95ade5a7533860baae377e17241e.
