### ISSUE TITLE
new field in http-log to indicate batched requests

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#6978]
We need to introduce a key called `request_type` in `http-log` and `ws-log` to indicate if the request is a batch of operations: https://hasura.io/docs/latest/graphql/core/api-reference/graphql-api/index.html#batching-requests and https://hasura.io/docs/latest/graphql/core/api-reference/relay-graphql-api/index.html#batching-requests

This is because the query-log semantics are different for a batched request and a normal request.

The location of this field should be `$.detail.request_type`, possible values are `single` or `batched`

**Comment by ecthiender** [comment]
Fixed via f6e49500d5ebabe5896e94afd0809c5fcc939b04
