### ISSUE TITLE
gen_random_uuid() is not suggested when creating table in schema different than 'public'

### ISSUE THREAD

**Issue by deathemperor** [hasura/graphql-engine#6980]
https://user-images.githubusercontent.com/4255482/119642497-fc9af780-be44-11eb-9009-851a2444caae.mov

**Comment by texfu** [comment]
Thx

**Comment by soorajshankar** [comment]
Hey @deathemperor 👋🏼 ,

Thanks for reporting this issue, this issue has been fixed on v2.0.6.
