### ISSUE TITLE
log output for query_response_time and other timing metrics is not an easily parsable format

### ISSUE THREAD

**Issue by khumps** [hasura/graphql-engine#6983]
Having numeric outputs as exponents such as `query_execution_time":1.0240461e-2"` Does not bode well for frameworks like cloudwatch and ELK when it comes to queries such as "longest running queries" and other metrics. Can these measurements be output as a floating point number without exponentiation?

**Comment by tirumaraiselvan** [comment]
I think we should fix the precision to 4 decimal points.

**Comment by khumps** [comment]
> I think we should fix the precision to 4 decimal points.

I agree with that. Anything past that is overkill. I haven't written haskell before but my guess is [these lines](https://github.com/hasura/graphql-engine/blob/dd1192ca2cb7ad1c4efd45468ed410ba5a9fa5fb/server/src-lib/Data/Time/Clock/Units.hs#L108-L114) are what cause the scientific formatting

**Comment by ecthiender** [comment]
We might loose resolution if we fix to only 4 decimal places. If the amount (say execution time) is really small, it may be erroneously rounded to 0. Is that sensible or reasonable?

On the other hand, [JSON spec](https://datatracker.ietf.org/doc/html/rfc7159#section-6) does support exponential notation for numbers. I am not sure why that doesn't work with tools that parse JSON. @khumps would you mind elaborating what breaks with systems like ELK and Cloudwatch?

--- 
References
- https://datatracker.ietf.org/doc/html/rfc7159#section-6)
- https://json-schema.org/understanding-json-schema/reference/numeric.html#id5

**Comment by khumps** [comment]
I realize I didn't close this, it was due to a configuration issue on my end. It is working as intended
