### ISSUE TITLE
GraphQL Error: invalid input syntax for type uuid: "019f68a5-3f34-4ced-97a9-42f7026ff744d" ?!

### ISSUE THREAD

**Issue by archywillhe** [hasura/graphql-engine#6985]
**Intended outcome:**

It should just work.

**Actual outcome:**

This string is deemed invalid for the type uuid. This makes no sense

**How to reproduce the issue:**

Just use this string as uuid; also this string was generated by 

```
import {v4 as uuid} from 'uuid'
```

so it should be valid; ran into no problem with other uuid string generated the same way

-->

**Versions**

  System:
    OS: macOS 11.1
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/debuild-nextjs-website/node_modules/.bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.0.2
  npmPackages:
    @apollo/client: ^3.2.5 => 3.3.19

**Comment by archywillhe** [comment]
though apollo was the one who threw it; but doesn't look like the problem is in apollo; 

<img width="761" alt="Screenshot 2021-05-27 at 6 17 08 AM" src="https://user-images.githubusercontent.com/10269911/119738417-43bfd180-beb3-11eb-9db9-640a9e08615a.png">

**Comment by wwwdepot** [comment]
Your uuid string is 33 hexadecimal long, which is invalid.

**Comment by 0x777** [comment]
Yup, looks like your uuid is invalid:
```bash
$ python -c 'import uuid;import sys;print(uuid.UUID(sys.argv[1]))' '019f68a5-3f34-4ced-97a9-42f7026ff744d' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/uuid.py", line 177, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
```
Looks like an extra character gets appended? Removing the last character 'd':
```bash
$ python -c 'import uuid;import sys;print(uuid.UUID(sys.argv[1]))' '019f68a5-3f34-4ced-97a9-42f7026ff744' 
019f68a5-3f34-4ced-97a9-42f7026ff744
```

**Comment by archywillhe** [comment]
ohh interesting! thanks! maybe it was a bug in uuid or somewhere else? closing this then :/
