### ISSUE TITLE
Hasura-cli don't follow symlinks

### ISSUE THREAD

**Issue by albttx** [hasura/graphql-engine#6989]
Hello,

I'm managing differents seeds for development purpose and i'd like to use different seeds directories.

For that i have 

```
seeds_A/
seeds_B/
seeds_C/
seeds -> seeds_A
```

But when i want to seed i have this error
```
level=fatal msg="no SQL files found in /home/albttx/go/src/github.com/albttx/myproject/hasura/seeds"
```

**Comment by scriptonist** [comment]
@albttx Does configuring the "seed_directory" using `config.yaml` solve your use case? https://hasura.io/docs/latest/graphql/core/hasura-cli/config-reference.html

**Comment by albttx** [comment]
Thanks @scriptonist for your answers, but it's not working either...

**Comment by purush7** [comment]
@albttx  It is `seeds_directory` not `seed_directory`. The final `config.yaml` file should have `seeds_directory: seeds_A`

**Comment by rikinsk** [comment]
Closing this issue as a workaround is available. please feel free to reopen if there is a strong requirement for this.
