### ISSUE TITLE
Allow table comments to describe the schema type

### ISSUE THREAD

**Issue by rocketraman** [hasura/graphql-engine#6997]
This was supposed to have been fixed in PR https://github.com/hasura/graphql-engine/pull/2397 (issues https://github.com/hasura/graphql-engine/issues/446 and https://github.com/hasura/graphql-engine/issues/2615), however I see that table-level PostgresQL comments are *not* shown as schema documentation in 2.0-alpha11. I don't know which version it regressed in though. Comments on fields do work as expected.

**Comment by rikinsk** [comment]
@rocketraman this seems to be working as expected for me. could you share some more details on which graphql type you are not seeing the documentation for

**Comment by rocketraman** [comment]
Hmm, looks like it is working for me now as well. I thought I had check but, perhaps the console just hadn't refreshed the schema docs information yet. In any case, seems ok. Closing.
