### ISSUE TITLE
SCRAM authentication requires libpq version 10 or above

### ISSUE THREAD

**Issue by jaschaschmidt** [hasura/graphql-engine#6999]
Postgres version: PostgreSQL 11.10
Hasura version: 2.0.0-alpha-11
K8s version: v1.20

error message:
{"type":"startup","timestamp":"2021-05-31T08:12:46.974+0000","level":"error","detail":{"kind":"catalog_migrate","info":{"internal":"SCRAM authentication requires libpq version 10 or above\n","path":"$","error":"connection error","code":"postgres-error"}}}

Please note that the latest stable build v1.3.3 works perfectly fine with Postgres version 11.10.
Changing from scram to md5 on the postgres server is not feasible workaround and does not solve the connection error.

suggestion:
Could you please update the libpq version in the next image release so that the connection works again with Postgres 11 and scram authentication?

**Comment by tirumaraiselvan** [comment]
This was earlier reported here: https://github.com/hasura/graphql-engine/issues/6670 and been fixed in master. Will be released in next released.

Thanks!
