### ISSUE TITLE
console: during row insertions single line text inputs lose their formatting

### ISSUE THREAD

**Issue by iykekings** [hasura/graphql-engine#7000]
From @wawhal:
> I was storing some XML in the database through browse-insert rows on console and the line breaks were getting stripped which caused some information to be lost. I later discovered that one has to expand the editor to enter the text if they wish to preserve line-breaks.
Not thought of the experience, but I think we should make sure that the data going in the database should be exactly what users entered.

Possible Solution:
1. using textarea for all string inputs at insert rows
2. When values are being inserted, if user hits ctrl+enter or shift+enter, we toggle the expanded text editor that autoscales with content
3. When values are being edited, if we detect a \n in the existing value, we expand it when the box goes into focus.

**Comment by beerose** [comment]
Closing in favor of https://github.com/hasura/graphql-engine/issues/7207
