### ISSUE TITLE
Hasura Events are configured on the read replica instead of the main DB

### ISSUE THREAD

**Issue by n2ctech** [hasura/graphql-engine#7006]
Hasura Cloud v2.0.0-cloud.11
Configured with postgres + 1 read replica

The events are reacting to changes in the read replica instead of the write DB, as a result they are executed after the delay it takes for the replica to sync, which makes our stack much less reactive. This is a weird implementation. Do you have an explanation for this or is this a bug ?

Thanks!

**Comment by tirumaraiselvan** [comment]
Hasura creates and picks events from the primary db (as it is only writeable). You can check this by looking for `UPDATE hdb_catalog.event_log` query in your Postgres logs. 

Can you describe your issue from scratch?

**Comment by shahidhk** [comment]
@n2ctech feel free to reopen when you have more information
