### ISSUE TITLE
hasura graphql endpoint : resource does not exist error

### ISSUE THREAD

**Issue by instantwpuserwin** [hasura/graphql-engine#7008]
Hello

SQL server database serving graphql from hasura cloud:

I am able to connect and  run graphql quries from within Hasura console(graphql tab),

But when I try to access my graphql endpoint from browser, I am getting 
error: 

{"path":"$","error":"resource does not exist","code":"not-found"}

hasura graphql endpoint:
https://fancy-jaybird-51.hasura.app/v1/graphql

Pls help.

Thanks

**Comment by AlexMeuer** [comment]
Are you providing a valid query/mutation/subscription in your `/v1/graphql` request?

**Comment by rikinsk** [comment]
As @AlexMeuer mentioned, the `v1/graphql` is a POST endpoint and hence attempting to access it via the browser with a GET erquest will result in a 404.

Closing this
