### ISSUE TITLE
console: changing primary key removes the existing PK when fails to create PK

### ISSUE THREAD

**Issue by soorajshankar** [hasura/graphql-engine#7018]
Current Behaviour
1. Create a PG table with PK 
2. try to change the PK to some invalid column
3. currently when we change PK, there are 2 SQL executions 
    a. getDropConstraintSql to remove the existing one 
    b. getCreatePkSql to add PK again 
4. this removes the PK and fail to add new PK (if there is an error)
5. PK will be still there in UI
6. but upon page refresh, UI will show that the PK is actually removed.    
    

https://user-images.githubusercontent.com/8408875/120965462-8ec6c800-c782-11eb-9fa9-9021b6bb6f5a.mp4

Expected Behaviour 
When we alter PK, removing and adding new PK should be like a transaction and if one fails the removal should be reverted back.

**Comment by beerose** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/12045a827c3ed2b5e49979992d32c77df0ae1a08
