### ISSUE TITLE
Could not verify JWT: JWTClaimsSetDecodeError "Error in $.sub: failed to parse StringOrURI"

### ISSUE THREAD

**Issue by cryptic-ai** [hasura/graphql-engine#7019]
I am attempting to use a Social login with Auth0 with Hasura. I followed the NextJS tutorial that you guys have up, however it's still failing. 

I get the error listed in the title, yet my sub is a string that is coming in from the token:

```"sub": "oauth2|Combine|1:1467702",```

Not really sure what else to do. Any help would be amazing! :)

**Comment by ecthiender** [comment]
Hi @cryptic-ai 

According to the [spec](https://datatracker.ietf.org/doc/html/rfc7519#section-2) (search for `StringOrURI` under "Terminology" heading), if the string contains a `:` it must be a spec-compliant URI.

Quoting the spec:
>    StringOrURI
      A JSON string value, with the additional requirement that while
      arbitrary string values MAY be used, any value containing a ":"
      character MUST be a URI [RFC3986].  StringOrURI values are
      compared as case-sensitive strings with no transformations or
      canonicalizations applied.

**Comment by ecthiender** [comment]
I am not sure what the Auth0, NextJS tutorial have. Would you mind linking it here? And are you sure that Auth0 generates that `sub`? I'll try to follow up and see what we can do here.

**Comment by cryptic-ai** [comment]
Thank you for your reply! It led me to the exact reason for the error. Turns out, when I create the user profile, I pass in the `uid` that they give me from the external api. It has the `:` in it. I updated the `fetchUserProfile` script I am running to generate a UUID for the `user_id`, which fixed this issue.
