### ISSUE TITLE
relation "hdb_catalog.schema_migrations" does not exist. null

### ISSUE THREAD

**Issue by ya5has** [hasura/graphql-engine#7021]
I am trying to reset migrations and following the steps at [https://hasura.io/blog/resetting-hasura-migrations/](url)

I deleted the local files, but I when I try to truncate schema_migrations, I get an error hdb_catalog.schema_migrations does not exist.

Running
```
hasura migrate status --database-name default
```
```
VERSION        NAME  SOURCE STATUS  DATABASE STATUS
1622577356824  -     Not Present    Present
1622780106278  -     Not Present    Present
1622780265876  -     Not Present    Present
1622780294960  -     Not Present    Present
1622780329854  -     Not Present    Present
1622780389735  -     Not Present    Present
1622780556253  -     Not Present    Present
1622780825178  -     Not Present    Present
```

Obviously table is not present
```
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'hdb_catalog'
ORDER BY table_name;
```

<h4 class="_3hn72cDofRyTeHUKGf7YZa" style="box-sizing: border-box; font-family: Gudea; font-weight: 700; line-height: 1.1; color: rgb(77, 77, 77); margin-top: 0px; margin-bottom: 0px; font-size: 15px; margin-block: 0px; padding-bottom: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(248, 250, 251); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">SQL Result:</h4><div class="_3WoF_OCxPdO6jxmtcyR4XM" style="box-sizing: border-box; overflow: auto; width: 1517.84px; padding-right: 5px; color: rgb(77, 77, 77); font-family: Gudea; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(248, 250, 251); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
table_name
--
event_invocation_logs
event_log
hdb_action_log
hdb_cron_event_invocation_logs
hdb_cron_events
hdb_metadata
hdb_scheduled_event_invocation_logs
hdb_scheduled_events
hdb_schema_notifications
hdb_source_catalog_version
hdb_version

</div>

I am using Hasura v2.0.0-beta.1 

Where is the information about migrations stored on database? How to clean it up?

**Comment by scriptonist** [comment]
@ya5has you can clean it up with a new command `hasura migrate delete --all --database-name <database-name>`. I understand this is not added to docs, will update the docs to reflect this change.

**Comment by ya5has** [comment]
That worked. Thanks!
