### ISSUE TITLE
document source name option in PG_dump API

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#7023]
The source name option is missing from the API reference documentation here: https://hasura.io/docs/latest/graphql/core/api-reference/pgdump.html#pg-dump-api-reference.

**Comment by dsandip** [comment]
Update for others: the source can specified by passing a `source` key in the payload. So, https://hasura.io/docs/latest/graphql/core/api-reference/pgdump.html#request needs to be updated to include this in the sample request and explain this field too:

```
{
  "opts": ["-O", "-x", "--schema-only", "--schema", "public"],
  "clean_output": true,
  "source": <database-source-name>
}
```

**Comment by rikinsk** [comment]
closed via https://github.com/hasura/graphql-engine/commit/8246bcc9d329ac9231af73799499ff37be5f4ec6
