### ISSUE TITLE
[v2.0.0-beta.1] Wrong route when clicking `Create Table` button

### ISSUE THREAD

**Issue by italodeandra** [hasura/graphql-engine#7025]
![26xwmqQPqd](https://user-images.githubusercontent.com/19225266/121302805-86919880-c8fa-11eb-8ab7-fbf29d1b90a6.gif)

**Comment by italodeandra** [comment]
Is this already fixed on latest alpha version? If yes, I can close this issue. My main goal is so people that have the same question can see this.

**Comment by abhi40308** [comment]
This should be fixed now, ref https://github.com/hasura/graphql-engine/commit/240738cf60d7b2bf4bff834f2dc7df3239bd12b8
