### ISSUE TITLE
metadata V2 - custom_name ignored

### ISSUE THREAD

**Issue by chsi13** [hasura/graphql-engine#7027]
I want to rename tracked tables. 

But renaming is not working.

sample of tables.yaml : 
```
 configuration:
      custom_name: PBooking
      custom_column_names:
        pkmr : id
        reference_p  : prReference
``` 

But hasura still generates a graphql node with the tracked table name and so ignores the renaming.

What did I forget ?

docker image : graphql-engine:v1.3.3.cli-migrations-v2

**Comment by rikinsk** [comment]
@chsi13 the `custom_name` field has been introduced in `v2.0.0-alpha.1` and hence it isnt working on the v1.3.3.cli-migrations-v2 image. we shall update the docs to mention the same
