### ISSUE TITLE
Modifying a remote schema through the console UI is deleting all its remote permissions

### ISSUE THREAD

**Issue by jgoux** [hasura/graphql-engine#7035]
Hello,

When going to the "Modify" tab in the remote schema section of the console UI and hitting the "modify" button then "save" (so even without doing any modification to the existing infos), all the remote permissions are deleted. 😅

**Comment by tirumaraiselvan** [comment]
Will be solved by https://github.com/hasura/graphql-engine/issues/7032

**Comment by kolharsam** [comment]
This has been resolved with: 608e4fb
