### ISSUE TITLE
Segmentation Fault w/Hasura CLI v2.0.0-beta1 on Mac OS 12 Monterey

### ISSUE THREAD

**Issue by 24601** [hasura/graphql-engine#7036]
A similar thing occurred in Big Sur beta + early release and it had to do with binary signing, I wonder if the same is going on here? 
```
❯ hasura
[1]    28098 segmentation fault  hasura
```
Interestingly, the 1.X series of Hasura CLIs function just fine. 

I have attempted to build the CLI to see if building from source is a remedy, but the build process does not seem to be cooperative either (it fails quite early in make by not finding the cli-ext binaries, which I did build but the output does not appear to be there), will continue to debug and find a workaround, but opening this in case there is official wisdom to help me.

**Comment by scriptonist** [comment]
@24601 this should be fixed by https://github.com/hasura/graphql-engine/pull/7096 can you verify with the latest release please?

**Comment by scriptonist** [comment]
@24601 Also, sorry for the delayed response, you can get the local build to work by following these steps:

1. clone HGE repo `git clone github.com/hasura/graphql-engine`
2. `cd cli`
3. Assuming you have go 1.16+, node and npm installed, execute `make build-cli-ext copy-cli-ext build`

**Comment by 24601** [comment]
@scriptonist - Thank you, sir, this problem seems to be "fixed", although when running ```hasura console``` it freezes and does nothing now on Monterey, should I open a separate issue?

debug output: 

```
❯ NODE_OPTIONS=""  hasura console --admin-secret $HASURA_ADMIN_KEY --endpoint https://hasura.dev.XXXXXXXXXXXX.com --log-level DEBUG
DEBU global config file exists, verifying contents
DEBU global config is pre-set to &cli.GlobalConfig{UUID:"fd79354e-b3de-44dc-854e-8f887c08538c", EnableTelemetry:true, ShowUpdateNotification:true, CLIEnvironment:""}
DEBU global config: uuid: fd79354e-b3de-44dc-854e-8f887c08538c
DEBU global config: enableTelemetry: true
DEBU global config: showUpdateNotification: true
DEBU global config: cliEnvironment:
DEBU cannot get config information from server, this might be because config API is not enabled: json: cannot unmarshal object into Go struct field HasuraServerInternalConfig.jwt of type string
DEBU graphql engine endpoint: https://hasura.dev.XXXXXXXXXXXXXX.com
DEBU graphql engine admin_secret: XXXXXXXXXXXXXXXXXXXXXXX
DEBU versions: cli: [v2.0.1] server: [v2.0.0-alpha.10]
DEBU compatibility check: [true] compatible CLI and Server
DEBU server: uuid: 1787cbe3-4882-4678-b25a-d8155c4a532d
DEBU copying cli state from hdb_catalog.schema_migrations to catalog state
```

**Comment by 24601** [comment]
@scriptonist - it eventually completed the operation, it took some time, but it worked, think all is good in Monterey land with Hasura & the CLI now, including locally running console.
