### ISSUE TITLE
Query: Does Hasura graphql work with Data API of Amazon Aurora Postgres and MySQL?

### ISSUE THREAD

**Issue by patelatharva** [hasura/graphql-engine#7039]
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html

**Comment by rsd1122** [comment]
We recently launched our new MySQL alpha integration:
https://hasura.io/docs/latest/databases/mysql/index/

It has support for queries, table relationships and permissions. Support for mutations is coming soon. Yes it does work with Aurora MySQL. 

Please reach out to me if you would like to be a part of the early-access slack channel where we post the latest builds and updates.

(Note: The previous version has been deprecated).

**Comment by rsd1122** [comment]
The Hasura MySQL data connector is now generally available (GA).

Please see our docs for more information:
https://hasura.io/docs/latest/databases/mysql/index/

We support Amazon RDS and Aurora databases (Postgres and MySQL), so closing this issue.
