### ISSUE TITLE
Question: how to export and import relationships between tables added via Hasura web UI?

### ISSUE THREAD

**Issue by patelatharva** [hasura/graphql-engine#7047]

**Comment by soorajshankar** [comment]
@patelatharva, You could use metadata export feature.

>All the actions performed on the console, like tracking tables/views/functions, creating relationships, configuring permissions, creating event triggers and remote schemas, etc. can be exported as a JSON/yaml metadata file which can be version controlled. The metadata file can be later imported to another Hasura instance to get the same configuration. You can also manually edit the metadata file to add more objects to it and then use it to update the instance.

For more details : https://hasura.io/docs/latest/graphql/core/migrations/manage-metadata.html#exporting-hasura-metadata

If you want to know how to set up a version control system, please refer the following
https://hasura.io/docs/latest/graphql/core/migrations/index.html
