### ISSUE TITLE
CLI: Error when applying metadata through CLI

### ISSUE THREAD

**Issue by kaiz16** [hasura/graphql-engine#7049]
Hi, we're hosting hasura on heroku. CLI always give this error whenever I apply metadata to production hasura. It works fine with migrations
```
$ hasura mgirations apply
migrations applied

$ hasura metadata apply
FATA[0054] failed to apply metadata: cannot apply metadata on the database: failed parsing json: invalid character '<' looking for beginning of value; response from API: <!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html> 
```

**Comment by kaiz16** [comment]
Also my cli version is 1.3.3

**Comment by scriptonist** [comment]
@kaiz16 CLI makes use of [`v1/query`](https://hasura.io/docs/latest/graphql/core/api-reference/schema-metadata-api/index.html#endpoint) it seems CLI is not able to reach that particular API.

Also, are you sure the commands you are running are right? because `hasura mgirations apply` is not a valid command, it should be `hasura migrate apply`.

**Comment by kaiz16** [comment]
Hello thanks for the reply, yes it's actually `hasura migrate apply`. I mistakenly put `hasura migrations apply`.  `hasura migrate apply` always runs fine but for some reason `hasura metadata apply` gives this error. However, I have another hasura instance hosted on hasura cloud. It seems to run both commands (`hasura migrate apply` and `hasura metadata apply`) just fine. It's using the same cloud version as well as the CLI version. I am not sure if this is with Heroku or Hasura CLI.

**Comment by scriptonist** [comment]
@kaiz16 CLI uses [v1/metadata](https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/index.html#metadata-apis) API under the hood, are there some firewall rules blocking access to this API endpoint?

**Comment by scriptonist** [comment]
@kaiz16 got it, thanks. The problem here is CLI is not able to reach hasura API endpoint `v1/query`. I would suggest you to look at the HGE logs from your Heroku deployment while running `hasura metadata apply`. This might uncover why the API is not reachable.

**Comment by kaiz16** [comment]
@scriptonist Actually, the metadata is applied even tho I received an error. So I think it has to do with Heroku. Thanks again.
