### ISSUE TITLE
[bug] hasura console deletes hasura.exe

### ISSUE THREAD

**Issue by Szanik** [hasura/graphql-engine#7053]
Using Graphql endinge v.1.3.3. with the hasura cli for windows.
Using it with docker.

I wanted to use hasura console for migration purposes.
But when I start `.\hasura.exe  console` in the hasura-server folder the .exe gets deleted.
After that I can't copy the hasura.exe to the folder again

This happens also when I used hasura via a npm global installation

**Comment by scriptonist** [comment]
@Szanik this is very unlikely to be something which is related to the CLI, this maybe because of interference from some other software running on the system.

**Comment by Szanik** [comment]
Hm i cant think of another reason, only docker is running.
It doesnt happen immediately after running `hasura console` but like 10 seconds after the hasura.exe is gone.
Interesting is that i cant recopy the hasura.exe to the folder.
Is there a way how I can see which process blocks the folder or deletes hasura.exe?

**Comment by scriptonist** [comment]
@Szanik something like an antivirus or something is falsely identifying the executable as a threat and removing it?

**Comment by Szanik** [comment]
Yes indeed that was it. Oh man sorry for not thinking about that. Thanks for your help
