### ISSUE TITLE
hasura console loads indefinitely

### ISSUE THREAD

**Issue by ethanabrooks** [hasura/graphql-engine#7054]
When I run `hasura console`, the Loading... screen hangs. In the devtools, I see the error `Uncaught TypeError: Cannot read property 'call' of undefined`:
![image](https://user-images.githubusercontent.com/10344742/121817048-0d24dd80-cc4d-11eb-92c2-6c1700bca74e.png)

Please let me know if there are config files that I can share that would help diagnose the problem.

```
❯ hasura version
INFO hasura cli is up to date                      version=2.0.0-beta.1
INFO hasura cli                                    version=v2.0.0-beta.1
INFO hasura graphql engine                         endpoint="http://141.213.3.130:8080/" version=v2.0.0-alpha.10
```

**Comment by soorajshankar** [comment]
Hey @ethanabrooks, Thanks for reporting this issue!
I tried to reproduce this issue with the same versions of hasura and CLI, unfortunately I couldn't reproduce this. 
Could you share some steps to reproduce this? also are you getting any network errors?

**Comment by ethanabrooks** [comment]
So I was strangely unable to reproduce it on a different machine. But on this particular machine, I was able to reproduce it by exactly following the steps here: https://hasura.io/docs/latest/graphql/core/migrations/migrations-setup.html#migrations-setup. Maybe there is no way we can reproduce on your end.. but I am happy to share information about the machine that was causing problems, if it helps.

**Comment by barbalex** [comment]
I have the same problem. How can I help you find the issue?

**Comment by barbalex** [comment]
Update: The issue appears in my case when using chrome (up to date). The console starts normally on Firefox.

**Comment by barbalex** [comment]
Just to reiterate this weird behavior:
- it happens in Chrome for a local docker instance
- it does not happen in Chrome for a remote docker instance

**Comment by baggsie** [comment]
Reproduced here http://207.154.200.8/console

Docker image running on Digital Ocean (v2.0.0-beta.2 and v2.0.0-beta.1)

**Comment by barbalex** [comment]
http://207.154.200.8/console works for me on Chrome and Firefox.

**Comment by soorajshankar** [comment]
@baggsie, I am able to load the login screen from  http://207.154.200.8/console.
Is this issue happening after login or before login? also could you share your browser details too?

**Comment by soorajshankar** [comment]
@ethanabrooks @barbalex @baggsie Folks,

This could be because some of the static resources could be cached and are in out-of-sync. 
Could you try the following steps and confirm?

* [Run console offline](https://hasura.io/docs/latest/graphql/core/deployment/graphql-engine-flags/config-examples.html#run-console-offline-i-e-load-console-assets-from-server-instead-of-cdn) : serve assets from the server instead of the CDN by setting the env `HASURA_GRAPHQL_ADMIN_INTERNAL_ERRORS=true`
* restart the container and try loading console on your browser. 
* once the console is loading correclty, you could try removing this env back and then try loading console again.

**Comment by barbalex** [comment]
@soorajshankar 
I tried running offline, then restarting the container. It did not work for me.

Then I tried to update to v2.0.1 and first got:
```
PS C:\Users\alexa\capturing> docker run -d --name capturing -p 8080:8080 -e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:secret@host.docker.internal:5432/record-data -e HASURA_GRAPHQL_ENABLE_CONSOLE=true hasura/graphql-engine:v2.0.1docker run -d --name capturing -p 8080:8080 -e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:secret@host.docker.internal:5432/record-data -e HASURA_GRAPHQL_ENABLE_CONSOLE=true hasura/graphql-engine:v2.0.1
Unable to find image 'hasura/graphql-engine:v2.0.1docker' locally
docker: Error response from daemon: manifest for hasura/graphql-engine:v2.0.1docker not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

But after trying twice it worked:
```
PS C:\Users\alexa\capturing> docker run -d --name capturing -p 8080:8080 -e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:secret@host.docker.internal:5432/record-data -e HASURA_GRAPHQL_ENABLE_CONSOLE=true hasura/graphql-engine:v2.0.1
Unable to find image 'hasura/graphql-engine:v2.0.1' locally
v2.0.1: Pulling from hasura/graphql-engine
69692152171a: Already exists
943e98b4e2e8: Already exists
0915c2c6cedd: Pull complete
1f1f11739e95: Pull complete
84012d2fe280: Pull complete
Digest: sha256:ca9943715e92454588a5f715693eccd9cfbfba28d0abdd8becfe414ee2d8d3c4
Status: Downloaded newer image for hasura/graphql-engine:v2.0.1
7d9904b17468d896fb19f683021378939179f84ef269b750f3677a18c43c196d
```

And now the console works on Chrome too.

**Comment by soorajshankar** [comment]
Hello @barbalex, 

Thanks for confirming so quickly, and happy that it is resolved for you!

```
PS C:\Users\alexa\capturing> docker run -d --name capturing -p 8080:8080 -e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:secret@host.docker.internal:5432/record-data -e HASURA_GRAPHQL_ENABLE_CONSOLE=true hasura/graphql-engine:v2.0.1docker run -d --name capturing -p 8080:8080 -e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:secret@host.docker.internal:5432/record-data -e HASURA_GRAPHQL_ENABLE_CONSOLE=true hasura/graphql-engine:v2.0.1
Unable to find image 'hasura/graphql-engine:v2.0.1docker' locally
docker: Error response from daemon: manifest for hasura/graphql-engine:v2.0.1docker not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

I think, the first attempt (^) seems to have 2 `docker run` commands, and docker got confused with the image name as `hasura/graphql-engine:v2.0.1docker` (instead of `hasura/graphql-engine:v2.0.1`). might be the clipboard pasted it twice.

**Comment by barbalex** [comment]
> I think, the first attempt (^) seems to have 2 docker run commands

omg 😭

**Comment by soorajshankar** [comment]
> This could be because some of the static resources (vendor & main.js) could be cached and are in out-of-sync.

fix : https://github.com/hasura/graphql-engine/issues/7054#issuecomment-868293261
