### ISSUE TITLE
column "resource_version" of relation "hdb_metadata" already exists

### ISSUE THREAD

**Issue by maxpain** [hasura/graphql-engine#7058]
Trying to update from `hasura/graphql-engine:pull5495-b2500d26` to `hasura/graphql-engine:v2.0.0-beta.1` and first start was successful:

`Successfully migrated from catalog version 36 to version 46.`

But next start of `graphql-engine` failed with error:
`column "resource_version" of relation "hdb_metadata" already exists`

**Comment by warezio-welico** [comment]
Same here, I'm not sure why it happened exactly, but I just drop the related catalog every time as below;
```sql
ALTER TABLE "hdb_catalog"."hdb_metadata" DROP COLUMN "resource_version";
DROP INDEX "hdb_catalog"."hdb_metadata_resource_version_key";
DROP TABLE "hdb_catalog"."hdb_schema_notifications";
DROP INDEX "hdb_catalog"."hdb_cron_events_unique_scheduled";
```

**Comment by ssbothwell** [comment]
I'm trying to reproduce this error but haven't been able to thus far. Can you describe a little more explicitly the steps you took to upgrade?

**Comment by alexandrim0** [comment]
I face the same problem while upgraded from beta.1 to beta.2
First start was normal but after docker-compose down & docker-compose up it crashes with same error.

**Comment by devinellis** [comment]
Same here. Going from 1.3.3 to 2.0.0-beta.2 (docker image) and got this error, causing the container to restart. I ran @warezio-welico's changes above and it worked.
