### ISSUE TITLE
Allow using computed fields for remote joins

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#7068]
Currently remote joins can only use the column values in a table in the remote join condition. Allow using computed fields.

Some examples of use-cases:
- Country column. Remote join needs country code, which is derived from the raw country column.
- JSON/JSONB column. Remote join needs a value inside a JSONB column.

**Comment by rikinsk** [comment]
closing as dup of https://github.com/hasura/graphql-engine/issues/7101
