### ISSUE TITLE
graphiql-code-exporter - Cannot change any of the export options

### ISSUE THREAD

**Issue by Noblepal** [hasura/graphql-engine#7072]
Hi Hasura team, I have been having this issue where I can't change any of the export options. The dropdown menus are unclickable as you can see, there is some overlay error on the UI (Screenshot Below).

Hasura Cloud Version: v2.0.0-cloud.11

Browser: Chrome Version 91.0.4472.101 (Official Build) (64-bit) ... and ... FireFox 89.0 (64-bit)
OS: Fedora 33 (Workstation Edition) GNOME 3.38.5 X11

Steps to reproduce:

1. Go to https://cloud.hasura.io/projects
2. Select a project and Launch Console
3. Enable Code Exporter 
4. Run any query

![image](https://user-images.githubusercontent.com/20543843/122366304-1ae7a500-cf64-11eb-8986-ee96f273e5cb.png)

**Comment by soorajshankar** [comment]
Hey @Noblepal 👋🏼 

Thanks for taking time to report this issue!
This issue is fixed and it fix will be available with the next cloud release.

(Related Issue : https://github.com/hasura/graphql-engine/issues/7573)
