### ISSUE TITLE
[sql-server] Support stored procedures and functions on SQL Server

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#7073]
Add support for "tracking" (exposing) stored procedures on SQL over a GraphQL API:

1. Authorization & permissions on stored procedure input and output
2. Relationships to other models from the procedures output
3. Relationships to the stored procedures from other models in the GraphQL schema

**Comment by AvronNet** [comment]
Hi,
do you have any timeline on when this feature will be available?

**Comment by sntg-p** [comment]
It seems like it is in progress, check issue https://github.com/hasura/graphql-engine/issues/7621.

**Comment by AvronNet** [comment]
@sntg-p The issue you mentinos deals only with mutations, not DB procedures and functions.
Looks like this is not started yet.
That is why I am interested in the target timeline for this feature.

**Comment by Ganesh1991** [comment]
Hi, any timeline on when this feature (DB procedures and functions) will be available?

**Comment by rishi-div** [comment]
Hey everyone, given our current priorities and commitments, we don't expect to begin work on this issue this year but will update this issue as and when we have more information.

**Comment by ryangugcloudca** [comment]
Thank you for working on this new feature. It is critical to complicated processes and performance demanding use cases.

**Comment by waqas-syed** [comment]
Has any decision been made on making progress on this issue? The [Hasura MSSQL](https://hasura.io/docs/latest/databases/ms-sql-server/index/) mentions that this is next on the SQL Server roadmap. 

I really hope it is because it is imperative for our use case.

**Comment by manasag** [comment]
Yes, this is in works and we plan to launch an early version of this feature soon.

**Comment by dameleney** [comment]
Support for SQL Server Stored Procedures is now available. Check out the docs to learn more.
https://hasura.io/docs/latest/schema/ms-sql-server/logical-models/stored-procedures/

**Comment by jtomaszewski** [comment]
What about "writeable" stored procedures ( https://hasura.io/docs/latest/schema/ms-sql-server/stored-procedures/#mutations )? Any idea if there's plans to release it soon, and where can I track it?
