### ISSUE TITLE
[sql-server] Support event triggers on SQL Server

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#7075]
Add support for [event triggers](https://hasura.io/docs/latest/graphql/core/event-triggers/index.html) on SQL Server.

**Comment by jmarbutt** [comment]
What is the time frame for this?

**Comment by ampsarfraz** [comment]
Hello any update on this features for SQL Server?

**Comment by jmarbutt** [comment]
@tirumaraiselvan What is the latest on this, we are about a month past the 3-4 week estimate.

**Comment by ericwilhite** [comment]
Would love to see some movement on this. We need to build out some notification infrastructure soon and event triggers would make that really easy to manage.

**Comment by m4ttheweric** [comment]
@tirumaraiselvan You mentioned last August that this would be available in 3-4 weeks. What's the status?

**Comment by arjunyel** [comment]
Hi friends, 7 days ago a PR for this feature opened up in our internal repo and is now under going testing, I am not sure when it will release but it is actively being worked on

**Comment by jmarbutt** [comment]
Thanks @arjunyel for the update, can't wait for this feature!

**Comment by tirumaraiselvan** [comment]
Dupe of https://github.com/hasura/graphql-engine/issues/7228
