### ISSUE TITLE
Increasing memory usage over time

### ISSUE THREAD

**Issue by cep21** [hasura/graphql-engine#7077]
Hi, 

Is there a way to get a memory dump of hasura to see where memory is being used?  We're currently on `v1.3.3-pro.1`  and here is a datadog graph of our container's memory usage over time. It shows the memory continuously growing during the morning as users come online each day.  This happens until the memory hits our container's limit and the container is killed.

We are currently serving around 200 req/sec via these hasura containers.

![image (2)](https://user-images.githubusercontent.com/20358/122452038-ac074d80-cf5d-11eb-8592-29f6fec46914.png)

**Comment by tirumaraiselvan** [comment]
Would you be able to try this out on Hasura v2.0 ? We have put in a patch which fixes this kind of build up.

**Comment by 24601** [comment]
We are having this issue, too, discussion over in #4077 appears relevant (and I've added our data in there). 

@tirumaraiselvan - having this on v2.12.0

**Comment by manasag** [comment]
Hi, Please try the latest 2.15 release, which has a bunch of improvements. Feel free to reopen if similar behaviour persists in this release too.
