### ISSUE TITLE
Running `hasura console` within docker container for programmatic migrations (and bugs/issues encountered along the way)

### ISSUE THREAD

**Issue by Californian** [hasura/graphql-engine#7080]
Apologies for the long-winded post, I'm trying to give perspective both so I can find a solution for my problem and so this can potentially help anyone developing hasura.

Our goal is to use `docker-compose` for local development, without installing any local packages separately (including CLIs).

We are using hasura cloud for our production instances, but need to generate migrations and test schema changes locally.

The obvious solution here is to use `hasura core`/`graphql engine` (I'll call it the latter from now on) via `docker` in `docker-compose`. The main issue is that this process isn't working; in particular, we can't run `hasura console` in a docker container and access it from the host.

Getting the schema (and some data for pseudo-enums) from our staging instance was quite a headache -- there isn't a good way to get enums programmatically that I could find, and getting the `v2.0.0-beta.2` CLI was unintuitive as well (the `v2.0.0-beta.2` branch's `get.sh` script should, in my opinion, get the latest `2.x` version). Eventually, we worked around these issues, and since v2 is in beta, some growing pains are understandable. Unfortunately, since this project was started apparently right when v2 was released for Hasura cloud, we have to stick with that and can't go back to a more stable version (though it's confusing that `graphql-engine` v2 is still in beta, but `hasura cloud` v2 is supposedly production-ready).

Anyway, after manually writing the SQL to insert the pseudo-enums during the initial migration, everything seemed to be going well. That is, until we had to turn the console off from the image and instead run the cli version of `hasura console`.

I'll put this in its own paragraph because I think it deserves calling out on its own: I'm sure there are underlying technical reasons for making a separate command that runs the console instead of having the image-internal console write migrations, but it's a really unintuitive user experience and seems unnecessary from an outsider's perspective.

That being said, the reasons behind that confusing decision aren't particular important to me, other than how they can inform our investigation of the core issue here: **how does one run the `hasura console` command within a docker container and access it from the host**?

Here is our current best-guess setup: one container for the main hasura image, and another which just installs the CLI and runs the `hasura console` command with the appropriate flags (e.g. `hasura console --address 0.0.0.0 --no-browser`). However, in order to get the cli command to connect to the container, the `config.yaml` needs to use the docker-internal url of `graphql-engine` i.e. `http://graphql-engine:8080`. This variable seems to be used both in the initial connection and for the code the browser runs, because when navigating to the console in my browser, it attempts to send a network request to `http://graphql-engine:8080`, which of course fails because my host is not on the docker-internal network.

Are there any suggested ways to resolve this?

Thank you in advance!

As a side-note, a couple other issues we've run into along the way are related to waiting for services to start; `graphql-engine` fails if the database isn't started yet (e.g. on initial db creation), so I think it should probably retry until it does (with some falloff). Similarly, this separate `hasura console` container fails waiting for the `graphql-engine` container to start up, so we have to manually restart that after it's up. We'll be writing a health check (or retry) wrapper for it, but if that's the recommended workflow it would be nice to have that built-in.

**Comment by martin-hasura** [comment]
So to hopefully help with a couple of those issues:
- The CLI's Console UI is usually meant to be run from a local machine -- there are a few sample workarounds for running it through a Docker container though: (this is the one I've used personally: https://github.com/hasura/graphql-engine/issues/2824#issuecomment-803269543). Using that implementation you'll set the `svc_hasura_console` service's env var of `HASURA_GRAPHQL_ENDPOINT` to the Hasura Cloud endpoint vs the local Docker container endpoint.
- That example also nicely mentions `healthcheck` and `depends_on` -- the grapghql-engine has a `healthz` endpoint which you can use to check for health and 'is-it-up?' which may help with your last issue for order-of-operations.

In that `svc_hasura_console` service your migrations and metadata will be available here for checking into version control:
```
    volumes:
      - ./metadata:/usr/src/hasura/metadata
      - ./migrations:/usr/src/hasura/migrations
```

The way CLI is currently set the way it is to allow for writing migration files to your local machine as you work in Hasura. We understand the ergonomics of the multi-console / setup can be a bit awkward to work with at times - we currently have a couple of RFCs to help improve the process, and especially for first-time use.

**Comment by Californian** [comment]
> So to hopefully help with a couple of those issues:
> 
> * The CLI's Console UI is usually meant to be run from a local machine -- there are a few sample workarounds for running it through a Docker container though: (this is the one I've used personally: [Running hasura console via CLI in docker container #2824 (comment)](https://github.com/hasura/graphql-engine/issues/2824#issuecomment-803269543)). Using that implementation you'll set the `svc_hasura_console` service's env var of `HASURA_GRAPHQL_ENDPOINT` to the Hasura Cloud endpoint vs the local Docker container endpoint.
> * That example also nicely mentions `healthcheck` and `depends_on` -- the grapghql-engine has a `healthz` endpoint which you can use to check for health and 'is-it-up?' which may help with your last issue for order-of-operations.
> 
> In that `svc_hasura_console` service your migrations and metadata will be available here for checking into version control:
> 
> ```
>     volumes:
>       - ./metadata:/usr/src/hasura/metadata
>       - ./migrations:/usr/src/hasura/migrations
> ```
> 
> The way CLI is currently set the way it is to allow for writing migration files to your local machine as you work in Hasura. We understand the ergonomics of the multi-console / setup can be a bit awkward to work with at times - we currently have a couple of RFCs to help improve the process, and especially for first-time use.

Awesome, that post fully resolved my issues! It wasn't easy to get working, but it's functional so that's great.

Just for context, we're not trying to run it on a remote machine, this is for the purposes of local-only, offline development. Running in docker is just preferable to remove inconsistencies between the environments of different developers, as well as those between development and production.
