### ISSUE TITLE
Migration from 1.3.3 to 2.0 does not occur automatically

### ISSUE THREAD

**Issue by au1985** [hasura/graphql-engine#7082]
Hi,

I am migrating my project from Hasura 1.3 to 2.0. During CI/CD pipeline, Hasura container is created from image, /metadata and /migrations are copied into, and the container is deployed in Kubernetes.

All worked fine until I changed image from 1.3.3.cli-migrations-v2 to v2.0.0-beta.2.cli-migrations-v2. The database used was the same. So, the version was the only change. It turned out that my schema cannot migrate smoothly.

I get logs of the Hasura pod:

`"type":"startup","timestamp":"2021-06-18T10:07:18.311+0000","level":"error","detail":{"kind":"catalog_migrate","info":{"internal":{"statement":"-- This migration adds versioning to metadata, used for optimistic locking in UIs.\n-- TODO: Are there changes required in catalog_versions.txt\n\nALTER TABLE hdb_catalog.hdb_metadata ADD COLUMN \"resource_version\" INTEGER NOT NULL DEFAULT 1 UNIQUE;\n","prepared":false,"error":{"exec_status":"FatalError","hint":null,"message":"column \"resource_version\" of relation \"hdb_metadata\" already exists","status_code":"42701","description":null},"arguments":[]},"path":"$","error":"database query error","code":"unexpected"}}}
`

I tried to drop column, but seems there are many further errors. So I did not succeed in automatic migration yet. I believe this is an issue in migration. Or am I doing something wrong?..

**Comment by tirumaraiselvan** [comment]
Seems like dupe of https://github.com/hasura/graphql-engine/issues/7058

**Comment by au1985** [comment]
> Seems like dupe of #7058

yes, pretty sure my issue is the same. Seems it yet to be fixed, but I am closing the duplicate here, thanks!
