### ISSUE TITLE
Issue setting the default database URL with Hasura v2.0.0, migrations v3 & migrations docker image

### ISSUE THREAD

**Issue by themasalamill** [hasura/graphql-engine#7088]
While deploying Hasura to Staging/Production with migrations with the migrations Docker image (currently using hasura/graphql-engine:v2.0.0-beta.2.cli-migrations-v3) we've hit an issue with setting the correct database URL (default database). The value that gets set as the default database URL comes from the file metadata > databases > default > databases.yaml :: name.configuration.connection_info.database_url. AFAIK the only way I can set the value of the database URL during deployment  is to set the value in databases.yaml, but that value is for our dev environment DB and can't be predetermined/hard coded in our dev environment (the production/staging string is currently loaded from AWS Secret Manager during deployment, once the values have been set in RDS)

With v1.4.x (v2 migrations) the value of the DB URL was always set by the Docker container env var HASURA_GRAPHQL_DATABASE_URL. Is it possible to keep that behaviour with v2.0.0 (v3 migrations) at least for the default database?

**Comment by deathemperor** [comment]
you can still do that with docker container env var. I'm running all configs with .env as image

![image](https://user-images.githubusercontent.com/4255482/122666250-630dfe00-d1d6-11eb-9c18-3796133ac845.png)

**Comment by themasalamill** [comment]
Hey @deathemperor, thanks for sharing that. Glad you have got it working. But I'm wondering if you are using the hasura/graphql-engine:v2.0.0-beta.x.cli-migrations-v3 image for your container (runs migrations when the container starts)? I've also got the HASURA_GRAPHQL_DATABASE_URL value configured in my docker-compose file. If I run the container using the hasura/graphql-engine:v2.0.0-beta.x image (basic image, no migrations) it uses the docker-compose value. In fact, if I check the value in Hasura Console, the `environment variable` radio button is checked and HASURA_GRAPHQL_DATABASE_URL is the value in the Database URL field.

But, when I deploy using the _hasura/graphql-engine:v2.0.0-beta.x.cli-migrations-v3_ image, it definitely ignores the environment variable set in docker-compose. Whatever value is in the migration databases.yml file is the value it tries to connect with. Can verify by opening the Hasura Console; Data > Data Manager > Edit Data Source. The `database URL` radio button is checked and the Database URL is set to whatever value was in database.yml; definitely not using the environment variable from docker-compose in my deployment. If it is working for you, then maybe I have something set up wrong.

**Comment by deathemperor** [comment]
Yes I'm developing and early stage production of Hasura so I'm using migration image. Are you able to share your docker-compose file?.

You can also "jump" into the hasura container and check if the environment variables are there.

I'm also using docker-compose. Mine: 

![image](https://user-images.githubusercontent.com/4255482/122673484-d9245c00-d1fa-11eb-8d61-d1cc09fd37a9.png)

Would be helpful if you share your databases.yml file. Mine is:

![image](https://user-images.githubusercontent.com/4255482/122673547-21dc1500-d1fb-11eb-9a9e-aaaf89b671f1.png)

**Comment by themasalamill** [comment]
Hey @deathemperor, thank you so much that solved the problem. I had no idea you could set the value of database_url using from_env with an environment variable.

For future reference, when Hasura initialises v3 migrations it sets the value of name.configuration.database_url in databases.yaml to a string by default, but this prevents migrations from being deployed properly. @deathemperor's config showed me that you can set the database_url from your containers environment variables. It's documented here (https://hasura.io/docs/latest/graphql/core/migrations/upgrade-v3.html), but I missed it before. Thanks again @deathemperor!!
