### ISSUE TITLE
Adding a table with capital letter and a comment causes SQL error

### ISSUE THREAD

**Issue by EdNutting** [hasura/graphql-engine#7090]
Hi,

I tried to insert a new table into Postgres using Hasura v2.0.0-beta.1 (server and console). The table name included a capital letter and I tried to add it with a comment. Hasura Console failed the operation with an SQL error due to the lack of quoting around the table name.

```json
{
    "internal": {
        "statement": "CREATE TABLE \"schedule\".\"XYZ\" (\"id\" serial NOT NULL, PRIMARY KEY (\"id\") );COMMENT ON TABLE \"schedule\".XYZ IS E'asfdsdf';",
        "prepared": false,
        "error": {
            "exec_status": "FatalError",
            "hint": null,
            "message": "relation \"schedule.xyz\" does not exist",
            "status_code": "42P01",
            "description": null
        },
        "arguments": []
    },
    "path": "$[0]",
    "error": "query execution failed",
    "code": "postgres-error"
}
```

This statement `COMMENT ON TABLE "schedule".XYZ IS E'asfdsdf';` should be `..."schedule"."XYZ"...`

Cheers,
Ed

**Comment by rikinsk** [comment]
same as #6935

**Comment by abhi40308** [comment]
This should be fixed now, ref https://github.com/hasura/graphql-engine/commit/9255fcf173ea09784bc34aa7aef0d77dff9a5c8f

**Comment by EdNutting** [comment]
Thank you!
