### ISSUE TITLE
server/postgres: use computed fields to filter rows

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#7100]
Reference: https://github.com/hasura/graphql-engine/issues/3772
Enable using computed fields in `where` clause of a HGE generated graphql query. For example, we have a table `student_marks` which contains integer columns for various courses to store marks obtained. We defined a computed field `total_marks` which is basically a total sum of marks. We need to fetch list of passed students by filtering on `total_marks` column.
```graphql
query {
  passed_students: student_marks(where: {total_marks: {_gte: 200}}){
    student { # object relation
      id
      name
      roll_number
    }
    total_marks
  }
}
```

**Comment by rakeshkky** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/e567a096e656db3a1fa94278646be615227f7351

**Comment by ethanabrooks** [comment]
Is there a way to access this feature now? It doesn't seem to be included on the latest dockerhub image.
