### ISSUE TITLE
server/postgres: use computed fields in order_by expression

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#7103]
Enable using computed fields in order_by clause. For example, we have a table `student_marks` which contains integer columns for various courses to store marks obtained. We defined a computed field `total_marks` which is basically a total sum of marks. We need to query student details sorted by `total_marks`

```graphql
query {
  student_marks(order_by: {total_marks: desc}){
       student_id
       total_marks
  }
}
```

**Comment by mikejackowski** [comment]
Looking forward to this. Any ETA?

**Comment by dariocravero** [comment]
@mikejackowski it looks like it will be out in some one of the next releases https://github.com/hasura/graphql-engine/issues/3772#issuecomment-883458306

**Comment by 0x777** [comment]
sever support has been added in v2.0.4. This issue tracks the console support: https://github.com/hasura/graphql-engine/issues/7336.
