### ISSUE TITLE
[Bug] gql schema of root query function that returns a single row shows a list as return type.

### ISSUE THREAD

**Issue by ghry5** [hasura/graphql-engine#7109]
I followed #4299 to create a sql function which returns only a single row. It works great but since the schema still lists the return type as `[user!]!`, graphql codegen is generating incorrect types.

I created a `me` query via a sql function of the form:

```
CREATE OR REPLACE FUNCTION public.me(hasura_session json) 
RETURNS "user" LANGUAGE sql STABLE AS 
$function$
SELECT
  *
FROM
  "public"."user" u
where
  u.id =(hasura_session ->> 'x-hasura-user-id') :: uuid
$function$
```

![image](https://user-images.githubusercontent.com/32223782/123217834-49690100-d4cb-11eb-8e58-2b4e83f12c8e.png)

**Comment by xiaoyu-tamu** [comment]
i'm facing the same issue :-(

**Comment by eviefp** [comment]
This issue has been fixed and should be merged soon. It should be available with the next release.
