### ISSUE TITLE
Issue with password containing @ in it.

### ISSUE THREAD

**Issue by AzadKshitij** [hasura/graphql-engine#7121]
I was having the issue just because my password contains '@' and the engine is not able to understand that. And it is giving me error like this...
```bash
 {
        "definition": "PostgreSQL 13",
        "reason": "Inconsistent object: connection error",
        "name": "source PostgreSQL 13",
        "type": "source",
        "message": "could not translate host name \"247@localhost\" to address: Name or service not known\n"
 }
```

**Comment by martin-hasura** [comment]
Try using `%40` to represent `@`

This should work as in:`HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:pass%40word@postgres:5432/postgres` for `postgres:pass@word ` - this is something we'll investigate taking up in our parsing logic though.

**Comment by AzadKshitij** [comment]
Thanks that worked.😀🧡❤
