### ISSUE TITLE
Skip a mutation variable

### ISSUE THREAD

**Issue by tamal-appsbee** [hasura/graphql-engine#7123]
Hi,

Is there any way to skip the mutation variable ?
 Example:
mutation EditUser($first_name: String!, $last_name: String) {
  update_users_by_pk(pk_columns: {id: 7}, _set: {first_name: $first_name, last_name: $last_name}) {
    id
    first_name
    last_name
  }
}

variables:
{
  "first_name": "Tom"
}

Output:
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "constraint-violation"
      },
      "message": "Not-NULL violation. null value in column \"last_name\" violates not-null constraint"
    }
  ]
}

Is there any way to skip the last_name from query on the fly which will alow me to partial update ?

Thanks

**Comment by martin-hasura** [comment]
Could you go to your data tab and make sure that your column is marked as nullable - as per:
![image](https://user-images.githubusercontent.com/74692114/123484600-9e456e00-d5d6-11eb-97b2-e9bd08457cb5.png)

**Comment by tamal-appsbee** [comment]
Hi,
Thanks for the reply. 
But is it possible to update the "first-name" only and skip the "last-name" on the fly ?
Let say we just need to update only " first-name " and as user not sending the "last-name" from frontend so we do not want to write the existing data with null


Thanks

**Comment by m-rgba** [comment]
Gotcha! Yep, that's possible, just slightly different syntax vs. the above.
You can look at something like:
```
mutation EditUser($changes: users_set_input) {
  update_users_by_pk(pk_columns: {id: 1}, _set: $changes) {
    id
    first_name
    last_name
  }
}
```

And then you'd pass a variable like:
```
{
  "changes": {
    "first_name": "Jane"
  }
}
```

**Comment by tamal-appsbee** [comment]
Got it
Thank you
