### ISSUE TITLE
Authorization not working as documented

### ISSUE THREAD

**Issue by themasalamill** [hasura/graphql-engine#7128]
Version: V2.0.0-beta.2

Following the directions at https://hasura.io/docs/latest/graphql/core/auth/authorization/basics.html#auth-basics, but it doesn't seem to be behaving as documented.

I have defined three roles; 'admin' (administrator role), 'anonymous' (anonymous role set by HASURA_GRAPHQL_UNAUTHORIZED_ROLE), 'public'. For a table (cart) I have defined permissions for the 'public' role, which should allow public role to access to all columns in the table (as shown).

![image](https://user-images.githubusercontent.com/69784614/123577267-d804b780-d816-11eb-93a7-e18a4fcddb26.png)

I've provided a header with key **X-Hasura-Role** and value of **public**, but field but when I run the query 'cart' not found.

![image](https://user-images.githubusercontent.com/69784614/123577585-77c24580-d817-11eb-9537-3cb224479504.png)

If I provide **X-Hasura-Admin-Secret** header, I can query that field, so I know the field is in the schema.

![image](https://user-images.githubusercontent.com/69784614/123577866-f3bc8d80-d817-11eb-82af-5342173e634a.png)

If I set permissions for the 'anonymous' role (select all columns), as follows:

![image](https://user-images.githubusercontent.com/69784614/123577999-3b431980-d818-11eb-8a9c-136b536a17f8.png)

then I can query the field, even if **X-Hasura-Role** **public** is set (or also if it is not set at all).

![image](https://user-images.githubusercontent.com/69784614/123578181-9c6aed00-d818-11eb-8d71-9240d307d993.png)

This doesn't seem to work how it's documented in link above, so I'm wondering if I'm doing something wrong, or if there's a bug in role based authorization in this v2.0.0-beta.2?

**Comment by martin-hasura** [comment]
That seems like it's a docs issue - those screenshots don't look quite right in terms of the headers present.

So when you're setting up your API using the API tab, you can keep your `x-hasura-admin-secret` on (this'll put you in admin mode). When you layer on `x-hasura-role` / `x-hasura-user-id` or any others, you're basically emulating those claims in the system (without having to gen a JWT token to test with).

In the gif below I'm activating my Hasura role and you can see my schema update based on the limited `select` permissions that the `users` group has:
![2021-06-28 01 04 02](https://user-images.githubusercontent.com/74692114/123583107-0cdc2480-d7ad-11eb-8ae4-da2d53d98071.gif)

When you go to develop you won't be passing the `x-hasura-admin-secret` anymore, and you won't be passing the `x-hasura-role` as part of your headers. Your `x-hasura-role` claim will get pulled from your JWT token you pass in (or via webhook) as per https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt.html#the-spec

**Comment by themasalamill** [comment]
Thanks @martin-hasura! That worked. I had thought the reason why my field was available with **X-Hasura-Admin-Secret** active was because it was overriding **X-Hasura-Role**, but I see now that it is actually required in the API tab to allow the **X-Hasura-Role** header to work at all. With the admin both the admin header and the role header active, it is indeed limited to just the permissions the role should have. I also confirmed when I turn off the admin header and the role header and use a Bearer token with the public role instead, the schema is correct for the public role.

The docs at https://hasura.io/docs/latest/graphql/core/auth/authorization/basics.html#auth-basics are perhaps a touch confusing, since they don't mention that the **x-hasura-admin-secret** header is also required.
