### ISSUE TITLE
Event trigger making the insert query fail

### ISSUE THREAD

**Issue by brundozer** [hasura/graphql-engine#713]
I have a _task_ table. When I call the insert_task mutation, it works. But as soon as I add an event trigger listening on inserts in that table, I get the following error:

`
{
  "errors": [
    {
      "internal": {
        "statement": "WITH \"public_task__rel_insert_result\" AS (INSERT INTO \"public\".\"task\" ( \"createdAt\", \"detectField\", \"displayField\", \"endedAt\", \"processedEntries\", \"userId\", \"id\", \"title\" ) VALUES ( DEFAULT, $1, $2, DEFAULT, DEFAULT, $3, $4, $5 )  RETURNING * ) SELECT  coalesce((json_agg(\"root\" )->0), 'null' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"e\"  FROM  (SELECT  \"root.base\".\"id\" AS \"id\"       ) AS \"e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"public_task__rel_insert_result\" WHERE ('true')     ) AS \"root.base\"      ) AS \"root\"      ",
        "prepared": true,
        "error": {
          "exec_status": "FatalError",
          "hint": null,
          "message": "record \"new\" has no field \"createdat\"",
          "status_code": "42703",
          "description": null
        },
        "arguments": [
          "(Oid 25,Just (\"Full Name\",Binary))",
          "(Oid 25,Just (\"Type\",Binary))",
          "(Oid 0,Just (\"82b10a97-ce9b-4530-844d-fb8065076e58\",Text))",
          "(Oid 0,Just (\"88c49254-49c1-48eb-8b67-3ca7c04c348b\",Text))",
          "(Oid 25,Just (\"file.csv\",Binary))"
        ]
      },
      "path": "$.selectionSet.insert_task.args.objects[0]",
      "error": "postgres query error",
      "code": "postgres-error"
    }
  ]
}
`

Here is the configuration of my trigger.
<img width="695" alt="screen shot 2018-10-12 at 11 54 30" src="https://user-images.githubusercontent.com/1772174/46862906-46f71380-ce16-11e8-8e05-8231ca09ec10.png">

Am I doing anything wrong here?

**Comment by 0x777** [comment]
Hi ! This is because of a bug in the trigger code generation logic. For now you can drop the trigger so that inserts don't fail (or only have lower cased column names in your table). The fix for this bug is part of the upcoming release (`alpha24`) which will be out in the next 3-4 hours.

**Comment by shahidhk** [comment]
Fixed in https://github.com/hasura/graphql-engine/pull/644, https://github.com/hasura/graphql-engine/commit/d57be587b3959dabd8146becd0d4ec7106fa9ff7

Release in a couple of hours

**Comment by tirumaraiselvan** [comment]
@0x777 @coco98 Maybe we should also look into making event-triggers take a non-critical path so it does not affect graphql query.

**Comment by 0x777** [comment]
I don't see how that can be done. Any insert will fail if the trigger fails.

**Comment by brundozer** [comment]
It works now. Thank you for the amazing responsiveness and for the good work! :)

**Comment by shahidhk** [comment]
@brundozer The fix was released in `v1.0.0-alpah24`. Hope you have upgraded already.
