### ISSUE TITLE
[v2.0.0-beta.2][mssql] Sql query fails on building json with aggregate and __typename on every level

### ISSUE THREAD

**Issue by kkumor** [hasura/graphql-engine#7130]
There is an issue why we want to build an query with __typename and aggregation. __typename is added by default by Appollo client for caching purposes. 
There is workaround that you can use with Appollo by changing clients settings, but probably this may affect performance.
` inMemoryCacheOptions: { addTypename: false }`
Same query works fine with PostreSQL.

![image](https://user-images.githubusercontent.com/6154875/123601044-8436a600-d7f7-11eb-8f5b-e7e82ad1c5fd.png)

And here is a bit of my investigation with SQL profiler and potential way to fix this.
First is a query that Hasura is sending right now and second one is maybe a query that you want to send.
![image](https://user-images.githubusercontent.com/6154875/123601120-94e71c00-d7f7-11eb-9f1a-d4784c5cadbd.png)

**Comment by 0x777** [comment]
The fix has landed on [master](https://github.com/hasura/graphql-engine/commit/61663ec901dba0c5ee0b66b6f83503dfacfeb8af). It'll be part of the next release.
