### ISSUE TITLE
Clarify allowed types for RESTified queries.

### ISSUE THREAD

**Issue by nagautier** [hasura/graphql-engine#7135]
Regarding support for list/arrays in RESTified endpoints, looking at the documentation we have: 
- "JSON Body Object values are passed directly to the associated query with no additional validation or type-coersion." (https://hasura.io/docs/latest/graphql/core/api-reference/restified.html) 
- "POST is permitted in order to support non-primitive variable types" (https://github.com/hasura/graphql-engine/blob/master/rfcs/rest-endpoints.md). 
This leads me to believe I can use input type lists to REST queries as long as I make it a POST request. However I also read this:
- Parsing for nullable types and list types is not supported, but may be added in a future version of this document.

Trying it myself I could not get non-primitive types to work. I'm pretty sure they don't. Would it be posible to get some clarification on this?
This is related to https://github.com/hasura/graphql-engine/issues/6911.

Many thanks!

**Comment by travisroyal** [comment]
I can confirm that a list of complex types does not work. It is not clear via the docs that complex types, whether in a list or not, are not supported. The RFCS partially clarifies.

**Comment by BenoitRanque** [comment]
Per the RFC, List types and Nullable types are not yet implemented

**Comment by arno-cma** [comment]
@BenoitRanque thanks for clarifying

**Comment by BenoitRanque** [comment]
@arno-cma My apologies. Further investigation revealed this is a bug.
A fix is already ready to be merged and should be out in the next release.
