### ISSUE TITLE
server/backends: improve testing workflow for alternative data sources

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#7137]
_Issue split from https://github.com/hasura/graphql-engine/issues/6951_

adding test support for a new backend (e.g. SQL Server, BigQuery) is currently a [4 or 5-step process](https://github.com/hasura/graphql-engine/blob/master/server/CONTRIBUTING.md#adding-test-support-for-a-new-backend) involving a lot of code and yaml-file duplication, with many minor, manual and error-prone tweaks (see linked examples). This is likely to discourage extensive testing and community contribution.

_suggested goal:_ eliminate/minimise duplication of code and test files for backend-agnostic feature tests and optimise workflow for backend-specific feature testing.

_suggested improvements_

- restructure tests into backend-specific and -agnostic tests so the former is clearer to identify and contribute to.
- introduce some generator or intermediate representation for test setup/teardown.
  - explore [synth](https://github.com/openquery-io/synth) for alt-backend test data generation given a Postgres data set

**Comment by jkachmar** [comment]
This (appears) to block us from merging generalized joins.

**Comment by sassela** [comment]
closing in favour of https://github.com/hasura/graphql-engine/issues/7760
