### ISSUE TITLE
server: improve `pytest` integration test signal:noise ratio

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#7138]
_Issue split from https://github.com/hasura/graphql-engine/issues/6951_

our pytest output has a pretty low signal:noise ratio, and it's often difficult to understand the cause of a test failure, if there is one. [Example: a 8600-line log for what turned out to be a flaky test that passed on a second run](https://app.circleci.com/pipelines/github/hasura/graphql-engine-mono/10008/workflows/5e17c77f-4b96-43aa-8a5b-bb722a80ddd0/jobs/192672/parallel-runs/23/steps/23-106).

_suggested improvements_

- there's almost certainly some pytest configuration that would help with this. Adjust circleci config and local testing scripts to reduce verbosity.
- better isolate (or reduce) stateful tests.

**Comment by V1shvesh** [comment]
@sassela Hey!
Is this issue still open/relevant?

**Comment by sassela** [comment]
hey @V1shvesh! Have you experienced this while running the pytests, or do you have any feedback? 

I'd say this is less relevant now as:
1) I reduced the verbosity a little simply by [removing the `-vv` flag](https://github.com/hasura/graphql-engine-mono/commit/30528d9720f529b8782778d7bc0810362e853d7a)
2) we've recently started an effort to port many of the [pytests over to a Haskell test suite](https://github.com/hasura/graphql-engine/issues/8432), so I wouldn't want to invest much more effort in improving the pytests at the moment

Thank you for asking the question. I'm gonna close this for now and reopen if it becomes

**Comment by V1shvesh** [comment]
Hey @sassela 
Just asked out of curiosity. Thought this issue would be a good opportunity to contribute to Hasura!
