### ISSUE TITLE
cli: sign windows binaries

### ISSUE THREAD

**Issue by scriptonist** [hasura/graphql-engine#7147]
Windows SmartScreen/Defender identifies CLI binary as some kind of Trojan/Virus. Even though this is a false positive and users can safely add the binary to the exclusion list, users might be not comfortable doing that. A solution for this could be to release signed binaries.

**Comment by purush7** [comment]
Reference : https://hasurahq.slack.com/archives/C01M20G1YRW/p1624524548011300

**Comment by purush7** [comment]
Tracking in https://gist.github.com/purush7/f7b7d64da81007d81f9d6690653bde70

**Comment by purush7** [comment]
For OV code signing certs https://gist.github.com/purush7/e89c44e1a1f4852a21ad8a88d2c5de67
