### ISSUE TITLE
server: support connection params for Postgres databases in `add_source` API

### ISSUE THREAD

**Issue by kolharsam** [hasura/graphql-engine#7149]
Upon encountering this issue #7121, I thought the best solution for certain cases like the user had pointed out here, would be to use connection parameters directly instead of having to deal with the connection string itself. We could easily provide an option to connect via `connection_parameters` too. Our pg driver also supports connections when provided with the parameters too (See https://github.com/hasura/pg-client-hs/blob/master/src/Database/PG/Query/Connection.hs#L64)

**Comment by paf31** [comment]
@tirumaraiselvan wanted to make sure you saw this too

**Comment by kolharsam** [comment]
This was addressed in the commit https://github.com/hasura/graphql-engine/commit/f6af5796191c5f7411d8c505b1682728cd23a317
