### ISSUE TITLE
[Feature Request] Embedded runtime

### ISSUE THREAD

**Issue by Bessonov** [hasura/graphql-engine#7159]
I'm using hasura for some time and I'm very impressed about it. While hasura is great, one of the hard parts of it that it must be used with some external service to achieve advanced functionality, which isn't easy to implement with PL/pgSQL or like. I like to propose an embedded runtime, which can execute arbitrary code, like send email, handle oauth2, use redis for caching and so on. I would love to see a JavaScript runtime (because of TypeScript and huge ecosystem).

I can image similar style like aws lambda or azure functions. Or even better, if it's compatible to one of them. Of course there are more questions like mapping, routing, security... but I'm sure that this would be a game changer not only for hasura engine, but especially for hasura cloud.

What do you think about it?

Probably related:
- https://github.com/hasura/graphql-engine/issues/4783
- https://github.com/nhost/hasura-backend-plus
- https://nginx.org/en/docs/njs/

**Comment by jberryman** [comment]
Hi, thanks for the feedback! Have you looked into actions? https://hasura.io/docs/latest/graphql/core/actions/index.html

Rather than being something _like_ aws lambda it lets you expose an AWS lambda as a graphql query or mutation

**Comment by Bessonov** [comment]
@jberryman yes, saw it and remote schemas too. But both aren't the answer. In meanwhile, I'm thinking about just include runtime within image. It's not how I imagine it, but at least the communication can happen through localhost.

**Comment by Bessonov** [comment]
I'm embedding own runtime in hasura's image now.
