### ISSUE TITLE
document mssql explain api

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#7162]

**Comment by eviefp** [comment]
Specifically, this is about updating this document https://github.com/hasura/graphql-engine-mono/blob/main/docs/graphql/core/api-reference/explain.rst to reflect it refers to postgres and either updating or creating a new document to specify the Explain API for MSSQL.

Is there any preference between having a document for both or having two documents, @rikinsk ?

**Comment by sassela** [comment]
Belatedly sharing my understanding of what needs to be done for this issue and unprompted advice to limit the scope to something reasonable for a new contributor, as opposed to digging into the query plan generation code solo just yet:

This issue involves updating [this Explain API reference](https://github.com/hasura/graphql-engine-mono/blob/main/docs/graphql/core/api-reference/explain.rst), highlighting where the endpoint, request, or response for SQL Server differs from Postgres.

The motivation for this change is to improve discoverability of the Explain feature for MSSQL. If it’s not documented, users don’t know it exists.

AFAICT, and having paired briefly with Alex last week, neither the endpoint nor request differ between MSSQL / Postgres. Stating this explicitly as it was a useful prompt for code exploration and there is no harm in documenting it.

However, the [sample responses](https://github.com/hasura/graphql-engine-mono/blob/main/docs/graphql/core/api-reference/explain.rst#sample-response-for-a-query) will differ between MSSQL / Postgres. So, the task is to update the API reference with the response to the example `explain` request on an MSSQL DB. We could do this in a couple of ways:
1. Set up a dummy Hasura Cloud project ([prod](https://hasura.io/docs/latest/graphql/core/getting-started/index.html) or [local](https://github.com/hasura/graphql-engine/blob/master/server/CONTRIBUTING.md#run-and-test-via-devsh)) with an MSSQL data source. Add an `Author` table with a `name` field, and [analyse the query plan](https://hasura.io/learn/graphql/hasura-advanced/performance/3-analyze-query-plans/) for the example request
2. Temporarily tweak one of the existing [`explain` integration tests](https://github.com/hasura/graphql-engine/blob/4887f70caa1b348db033b0d187b788a9e15b53d0/server/tests-py/test_graphql_queries.py#L1132) to match the example request from the API reference, [run it against an MSSQL backend](https://github.com/hasura/graphql-engine/blob/master/server/CONTRIBUTING.md#run-and-test-via-devsh), and copy the response
3. (errr…we could obvs call `EXPLAIN` directly on an MSSQL DB, but that would kinda circumvent the spirit of documenting the call via API)

@awjchen sorry again that this task was unclear in the first place and you didn’t get clear answers to your Qs in Slack. I’m happy to pair as much or little as you need to (until Thursday, when I’m OOO)

**Comment by sassela** [comment]
Completed last week https://github.com/hasura/graphql-engine/commit/f1daabab0457cee75108f895b25a91b0f2808e40
