### ISSUE TITLE
Scheduled events UI is broken on Hasura 2.0

### ISSUE THREAD

**Issue by kgpingle** [hasura/graphql-engine#7168]
Steps to reproduce:
1. Go to Events -> one-off-scheduled-events -> Pending
2. Click to expand any one of the event in the Pending list.
You get below error.

```
Error: An error occurred. See https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/errors.md#12 for more information. Additional arguments: fQdAWJ
at I (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.1-cloud.1/vendor.js.gz:1:5539942)
at e.toString (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.1-cloud.1/vendor.js.gz:1:5547985)
```

**Comment by Varun-Choudhary** [comment]
Thanks for reporting the issue @kgpingle 

@beerose @tirumaraiselvan this issue can only be seen on the pro & cloud console. Will have more updates soon.

**Comment by soorajshankar** [comment]
@kgpingle, Thanks for reporting this issue!

We have a fix for this, and it will be available for you in the next release.
