### ISSUE TITLE
BUG: JSON field key breaks GraphQL validation if remote schema relationship is included in request

### ISSUE THREAD

**Issue by yoshiwarab** [hasura/graphql-engine#7172]
Version: v2.0.1-cloud.1

I'm receiving this error when querying a table that has both a JSON field and a remote schema relationship: 
"variable value contains an object with key \"Start Color\", which is not a legal GraphQL name". "Start Color" in this instance is a key of a JSON field.

This error does not occur if I do not include data from the remote schema in the query. The issue also does not occur if all of the keys from the JSON field are valid GraphQL names.  So for example if I ran the query:

```
query GetTokens($id: String!) {
  tokens_by_pk(id: $id){
    # features is a JSON field and should return { "Start Color": 44 }
    features
    # project is a remote relationship
    project {
      id
    }
  }
}
```

I would receive the error above.  However, if I ran the query:

```
query GetTokens($id: String!) {
  tokens_by_pk(id: $id){
    # features is a JSON field and should return { "Start Color": 44 }
    features
  }
}
```

it would run normally.  JSON fields should not get validated as though they were GraphQL fields regardless of whether or not data from a remote relationship is included in the query.

I believe the error might be coming from around [here](https://github.com/hasura/graphql-engine/blob/master/server/src-lib/Hasura/GraphQL/Execute/RemoteJoin/Join.hs#L216) but am not very familiar with Haskell, so haven't been able to dig too deep. Any help much appreciated!

Also thank you so much for the awesome service and library!

**Comment by yoshiwarab** [comment]
Adding screenshots of the issue in case it helps
<img width="1414" alt="Screen Shot 2021-07-07 at 10 59 05 AM" src="https://user-images.githubusercontent.com/1716299/124807306-7a592500-df12-11eb-922e-3e0c32b65479.png">
<img width="1404" alt="Screen Shot 2021-07-07 at 10 58 50 AM" src="https://user-images.githubusercontent.com/1716299/124807319-7cbb7f00-df12-11eb-842c-caf4c0dcfdb1.png">

**Comment by yoshiwarab** [comment]
@0x777 Just wanted to see if this is scheduled or if there has been any progress on this bug, thanks!

**Comment by abooij** [comment]
@yoshiwarab We have started looking at this issue. It seems to us that this issue may no longer be present in v2.0.6, since the execution of remote joins was reworked in 4a83bb1. It would be great if you could verify this.

Even if a simple upgrade fixes it for you, we'll have to make sure add regression tests to prevent this from reoccurring, of course.

**Comment by yoshiwarab** [comment]
@abooij awesome, yes v2.0.6 seems to fix the issue, thank you! When do you expect that will land in Hasura Cloud

**Comment by abooij** [comment]
@yoshiwarab Sorry, I don't know that. I don't think there's anything special about the release schedule for v2.0.6. So it shouldn't be too long.

**Comment by abooij** [comment]
A regression test for this issue has been added in 88aa42a98686a182d239a527d3675ddff43ea347.
