### ISSUE TITLE
Untracked foreign-key relationships suggestion across schemas not working in v2.x.x

### ISSUE THREAD

**Issue by elitan** [hasura/graphql-engine#7177]
If I created a foreign key between two tables in two different schemas with Hasura v1.3.3 Hasura showed the suggestion in the console. But with v2.0.1 it does not.

**Comment by soundswarm** [comment]
I see this problem, too, which makes v2.0.1 hasura unusable. I'm using postgres 12.5

**Comment by iykekings** [comment]
closed as resolved
