### ISSUE TITLE
Why does Hasura map `text[]` to `_text` type instead of `[String!]`?

### ISSUE THREAD

**Issue by ethanabrooks** [hasura/graphql-engine#7187]
I have the following SQL function:
```sql
CREATE OR REPLACE FUNCTION public.my_function(texts text []) 
RETURNS SETOF table 
LANGUAGE sql STABLE
AS $ function $
SELECT  * FROM table 
$ function $
```
I have added this to my database and the function that Hasura exposes over the GraphQL API looks like:
```graphql
query MyQuery($texts: _text = "") {
  my_function(args: {texts: $texts}) {
    id
  }
}
```
where `$texts` ends up needing to be an argument that looks like `"{a,b,c}"`. In my opinion this is a bit awkward. Furthermore, the `_text` type is not documented by Hasura:
![image](https://user-images.githubusercontent.com/10344742/124487453-bc506280-dd7c-11eb-8c24-e4fdb33c273f.png)

It would seem that an argument of type `text[]` would more naturally map to `[String!]`. Is there a reason not to do that? Also, is there a work around on my end that can force Hasura to choose this mapping?

**Comment by wwwdepot** [comment]
duplicate #348

**Comment by danieljharvey** [comment]
Hello! As of version `2.29` we have built-in support for Postgres arrays, meaning `text[]` will now be mapped to `[String!]`

You can now use native arrays to insert array items, like this:

```graphql
mutation insert_author {
  insert_author (
    objects: [
      {
        name: "Ash",
        emails: ["ash@ash.com", "ash123@ash.com"]
      }
    ]
  ) {
    affected_rows
    returning {
      id
      name
      emails
    }
  }
}
```

You can also use `_contains` and `_contained_in` to filter array fields.

More information can be found [in the docs](https://hasura.io/docs/latest/mutations/postgres/insert/#insert-an-object-with-an-array-field).

**Comment by SamirTalwar** [comment]
Looks like your variable `xxxxxx`'s type definition needs to change from `_text` to `[String!]`. If you need help with that, could you share the part of your query where you declare your variables?

**Comment by emrahc** [comment]
We use apollo-graphql-codegen for producing custom hooks.  We already switched variable definitions from _text to [String!].

**Comment by emrahc** [comment]
We solved. Sorry for confusion it was due to type definition of action.

**Comment by marionschleifer** [comment]
Hey folks, we will give a quick update on supporting Postgres arrays in the community call this Thursday, 27th July at 9am PT, along with many other community updates 🙌  if you're interested, you can sign up [here](https://hasura.io/community/community-call/).

**Comment by ryparker** [comment]
so what was the solution?
