### ISSUE TITLE
Question: Is it possible to use Hasura with Clikhouse

### ISSUE THREAD

**Issue by sergii4** [hasura/graphql-engine#7189]
Clickhouse emulate MySql protocol but not MySql database, so when I tried to point Hasura to  Clickhouse I get a DB Exception such as `missing  INFORMATION_SCHEMA`.

Are there any workarounds from Hasura side for it?

**Comment by xiaoyu-tamu** [comment]
I'm getting the same error.

**Comment by maxpain** [comment]
Any updates?

**Comment by iosifnicolae2** [comment]
I'm also interested.

**Comment by L-U-C-K-Y** [comment]
Would also be interested!

**Comment by iosifnicolae2** [comment]
We've managed to implement a solution using [clickhouse_fdw](https://github.com/adjust/clickhouse_fdw) (also, we've fixed some bugs with json support here: https://github.com/iosifnicolae2/clickhouse_fdw)

**Comment by sina68** [comment]
ClickHouse and PostgreSQL - a Match Made in Data Heaven
https://clickhouse.com/blog/migrating-data-between-clickhouse-postgres

**Comment by marionschleifer** [comment]
Hey folks, we're launching our new Clickhouse connector in our monthly community call on 31st of August at 9am PT. Would love to see you there! 🎉 you can sign up [here](https://hasura.io/community/community-call/). If you can't make it, no problem. You can sign up anyway and we'll send you the recording.

**Comment by maxpain** [comment]
@marionschleifer wow! Will it be available in the free version of Hasura?

**Comment by marionschleifer** [comment]
@maxpain yes it will be 🙂

**Comment by manasag** [comment]
Hi, I want to update that we are launching Hasura V3 (DDN) this month. in V3, Clickhouse will be available for Free tier and Community version.

I would highly suggest to join us to see the full power of Hasura DDN at the Hasura Dev Day on April 16 🎉. Sign up here: https://hasura.io/dev-day. Can't make it? Sign up anyway and we'll send you the recording.
