### ISSUE TITLE
Relationship with data type instead of root resource.

### ISSUE THREAD

**Issue by chsi13** [hasura/graphql-engine#7194]
Let's say we have a simple model : a customer has one and only one address.

I want to expose Customer as API ressource and Address as simple data type. So only Customer entity has a unique identifier.

Now If I want to map this model to hasura I have to create 2 tables (fine) , track both and create an object relationship (a customer has a single address) with Address entity.

In the end the schema will expose 2 queries (one to list all customers and one to list all addresses but I don't want the second one). 
I only want Address to be a simple graphql type without giving the possibility to fetch addresses idependently of customers. 

But we can only create relationships based on tracked tables and a tracked table = API Resource.

How can I put Address as a simple data type (Graphql Type) without do the change manually ???

**Comment by rikinsk** [comment]
related https://github.com/hasura/graphql-engine/issues/696

**Comment by rikinsk** [comment]
@chsi13 i am closing this as a dup of #696. please feel free to reopen this with some more details if you were looking for something different

**Comment by chsi13** [comment]
@rikinsk  question related : is it possible to map 2 ressources from a single table ? Sometimes having a ressource matching a table/view is overkill .
