### ISSUE TITLE
hasura cli - 2.0.1 hasura console error when using istio

### ISSUE THREAD

**Issue by eaf-josephportello** [hasura/graphql-engine#7196]
Hasura version 2.0.1
Istio version 1.10.2
Kubernetes 1.20.x

When launching the console with:

hasura console --endpoint "https://api.x.x.com" --admin-secret "XXXXXXXXXXXXXXXXXX" 

We received the error RBAC denied. Using Istio we route Hasura traffic through our API endpoint via the following virtual services rules:

  http:
    - match:
        - uri:
            prefix: /v1/
        - uri:
            prefix: /v1alpha1/
        - uri:
            prefix: /v2/
        - uri:
            prefix: /healthz
        - uri:
            prefix: /console
      route:
        - destination:
            host: hasura
            port:
              number: 80

This worked fine for 1.3.3, but we noticed in 2.0, we started getting the error. Looking at the istio envoy logs of another service that just routes "/", we see: 

POST //v1/query HTTP/1.1" 403 - rbac_access_denied_matched_policy[none]

Adding //v1 to our virtual services fixes the issue. 

Any thoughts?

Regards

**Comment by anhpngt** [comment]
Try adding
```sh
    - uri:
        prefix: //v1
```
hasura calls `//v1/query` for some reason

**Comment by purush7** [comment]
Hey @eaf-josephportello , just want to confirm is the endpoint mentioned in `hasura console` is "https://api.x.x.com"  or "https://api.x.x.com/"?
We addressed the slash thing in the above PR.

**Comment by eaf-josephportello** [comment]
@purush7, it would be api.x.x/console or api.x.x/healthz, api.x.x/v1/, etc.. route to Hasura. Anything else / routes elsewhere. Upgrading to 2.0 we noticed that the cli tool was calling an additional / with /v1 so it was putting in //v1 which matched no pattern. As I mentioned above putting //v1 resolved the cli issue. This only affected the cli as far as we could tell in our tests. 

Does that help?

**Comment by purush7** [comment]
yeah thanks for the quick response @eaf-josephportello
