### ISSUE TITLE
relay support

### ISSUE THREAD

**Issue by srghma** [hasura/graphql-engine#721]
From this message https://github.com/hasura/graphql-engine/pull/686#issuecomment-428469217

```
@srghma Thanks for the feedback but Hasura GraphQL engine does not support relay at the moment. we'll revisit when we add relay support.
```

What's missing in graphql-engine to support relay?

**Comment by toxsick** [comment]
I think it is mainly that relay's connection spec with cursors and first/after ist not available. Is there a timeline on this?

**Comment by 0x777** [comment]
Hi @srghma @toxsick relay makes assumptions about the GraphQL server as outlined [here](https://facebook.github.io/relay/docs/en/graphql-server-specification.html). We haven't made any attempt to implement this spec yet. At a quick glance, we don't have cursors for pagination. Apart from that it shouldn't be hard to map rest of the spec to what we already have right now. 

> Is there a timeline to this?

We haven't received a lot of community interest in this feature. We'll revisit this once more people ask for this. You can add a `+1` reaction to show interest.

**Comment by srghma** [comment]
@0x777 
> We haven't received a lot of community interest in this feature

I personally have to use to postgraphile on work because of no support for relay (I don't like apollo, apollo forces me to manage state of application myself)

**Comment by toxsick** [comment]
@0x777 ,

thanks for your answer. I see 2 challenges here to make hasura relay compatible:

1. relay connection spec with structure edges --> node (and cursor, pageInfo, first/last, after/before etc.)
2. Nodes have to be unique in whole system. Currently Hasura uses just the database id as id field for items. That means items from 2 tables have the same ids. This is not allowed in relay. Migrating to unique id's could be a problem for existing Hasura users since all id's would change.

I would love to see relay support in Hasura since we did not use Apollo yet.

regards
Hannes

**Comment by toxsick** [comment]
@0x777 so this is not something that will land anytime soon right? Just for our planning...

**Comment by coco98** [comment]
@toxsick We'll take a look at this early next week to see what timelines we can put around this! @0x777 will probably have some questions for you. 

We haven't played around with relay very well yet. Are you on our discord? Will be easier for us to chat and for us to ask you questions around relay. I know @srghma is on discord already!

https://discord.gg/vBPpJkS

**Comment by toxsick** [comment]
Jeah sure i joined as @Hanso0o to your discord, I'm not so much online though. If not contact me here and I will show up

**Comment by Maxpain177** [comment]
+1. I have an existing application with ApolloClient and GraphQL server with join-monster, that supports relay pagination. It's too hard to remove relay pagination from our current infrastructure.

**Comment by Fxlr8** [comment]
+1, this is a must have feature

**Comment by 0x777** [comment]
Thanks for all the input ! We've moved this into our roadmap. So it'll be implemented soon, my current estimate is 4 weeks from now, end of November.

**Comment by Maxpain177** [comment]
> Thanks for all the input ! We've moved this into our roadmap. So it'll be implemented soon, my current estimate is 4 weeks from now, end of November.

Thank my friend very much, it is a handy feature!

**Comment by toxsick** [comment]
nice, llokobg foreward to it

**Comment by Maxpain177** [comment]
@0x777, @coco98, how is progress with the Relay pagination?
Maybe it will be helpful for you:
https://join-monster.readthedocs.io/en/latest/relay/

**Comment by 0x777** [comment]
We are actively working on this but it looks like it will be delayed by a couple of weeks.

**Comment by bardak-dev** [comment]
Papa bless you for this upcoming feature 🙏🏻

**Comment by gabrielschmith** [comment]
Any update on this?

**Comment by idetoile** [comment]
Too much suspense on this feature !
Can you please tell us if it's still planned, even if it's in a long time ;)

**Comment by 0x777** [comment]
Hi, we've tried earlier to add relay support. Unfortunately we couldn't finish it. We will take it up again post `1.0` release.

**Comment by longfellowone** [comment]
Only thing holding us back from switching over!

**Comment by mohankonyala** [comment]
Same here. Would really like to move over but relay support is what is holding me. Any ideas on when this will be available?

Thanks

**Comment by 0x777** [comment]
No change in status. We'll post an update when we pick this up.

**Comment by hammadj** [comment]
> No change in status. We'll post an update when we pick this up.

@0x777 Could you publish the work that has been done so far so the community could possibly pick it up and move it across the line?

Laying the foundations for a big new venture right now, we love Hasura and all its amazing out of the box functionality. However, Relay Modern and especially [Relay Experimental](https://babangsund.com/relay_experimental/) are looking a lot more polished and fully featured with a simpler/cleaner API and I think it is a much better fit for Hasura now, both pushing the latest and greatest in a well opinionated way. Would be absolutely incredible for us to use them together.

**Comment by ryanflorence** [comment]
We're hoping to tightly integrate React Router and Relay soon, we were hoping to recommend hasura (and use it ourselves!)

Would love to see this get pushed over the finish line!

**Comment by zth** [comment]
Adding to @ryanflorence , there's been quite some interest in using Relay with Hasura throughout the Relay community lately, especially now that FB released the experimental hooks/suspense APIs for Relay. Even adding Relay support step-wise (starting with just the `Node` interface) would be very valuable, if that's an alternative.

**Comment by 0x777** [comment]
Thank you all for taking the time to time to respond how important this feature is for you :) This has always been on our radar; we made an exploratory attempt last year too.

Just to give a bit of background, the interface that you see currently with Hasura existed before the first release of GraphQL specification in 2015 (before GraphQL, queries were written in a JSON based DSL called RQL which the console still uses this!). Because of this there are some assumptions about the query interface through the codebase. However once we refactor some parts of the codebase as outlined in https://github.com/hasura/graphql-engine/issues/2801, adding an interface like Relay should be fairly straightforward. Our priority currently is to get the 1.0 release out (couple of releases away), and then work on #2801 to implement the Relay interface.

**Comment by tsaiDavid** [comment]
@dquesada @dmi3y - FYI

**Comment by cooldesigns** [comment]
Waiting for it

**Comment by coco98** [comment]
Some notes on supporting relay subscriptions by @zth 🙏 
https://gist.github.com/zth/e1d4bcdace2b5498d247991ead8f74ba

**Comment by WJChai** [comment]
+1.. would be awesome if we can use relay + hasura

**Comment by ivawzh** [comment]
The later Hasura implements this feature, the harder it will be for the migration. 
Because when you change database row ID to node UID, it will introduce breaking changes to URLs and harm SEO 😞

**Comment by ro-savage** [comment]
Found this [Repo](https://github.com/renanmav/hasura-relay-example) from @renanmav that uses the unstable and undocumented `UNSTABLE_DO_NOT_USE_getDataID` in relay to generate the dataID client side instead of server side.

Here's the commit: https://github.com/renanmav/hasura-relay-example/commit/c0dcf82a22dddf6069d4e0ca5e200c0b8fbc4bf7

I haven't tried it yet but looks like it may be a good way to get Hasura working with relay while waiting on Hasura to implement GUIDs.

**Comment by renanmav** [comment]
Relay team has plans to remove the `UNSTABLE_DO_NOT_USE` and document the `getDataID` but works fine. Haven’t tried pagination with connections yet.

**Comment by ivawzh** [comment]
Interesting @ro-savage @renanmav 
How would that work with cursors? It'd be great if there is an example.

**Comment by arjunyel** [comment]
Relay is part of the Community Call on April 29th https://hasura.io/community/

**Comment by renanmav** [comment]
> How would that work with cursors? 
As I said @ivawzh, haven’t tried cursoring yet. I can manage some time this weekend to see it.

**Comment by 0x777** [comment]
Folks, we now have a working implementation for Relay modern (WIP as part of [this PR](https://github.com/hasura/graphql-engine/pull/4458))! The docker image to try this out as of this writing is `hasura/graphql-engine:pull4458-e3f5b95e` (**Important**: Do **not** use this image on any of your existing databases that you use with stable graphql-engine versions, please make a copy of your database). Please do try it out and let us know! You can leave the feedback on the [above](https://github.com/hasura/graphql-engine/pull/4458) PR.

**Comment by soneymathew** [comment]
Works beautifully so far 👏 

I was unable to use the mentioned docker image so testing with `hasura/graphql-engine:pull4458-2c0725d1` .
Pull the latest version related to this PR if you face any problem with this https://hub.docker.com/r/hasura/graphql-engine/tags?page=1&name=4458

**Comment by tirumaraiselvan** [comment]
This has now been released  in `v1.3.0-beta.1`. Closing this, pls open new issues if you face any difficulties.

**Comment by TheMrZZ** [comment]
Is adding Custom Actions to the Relay endpoint planned on the roadmap? It would really make Relay support awsome!

**Comment by zuohuadong** [comment]
+1

**Comment by coco98** [comment]
Have some good news regarding relay coming up in a few weeks. 🔥

Do join us! :)

https://hasura.io/events/hasura-con-2023

**Comment by nullxone** [comment]
Here's some thoughts on what the hasura relay client will look like. Please drop by and share your thoughts!
https://github.com/hasura/hasura-relay-client
