### ISSUE TITLE
HASURA_GRAPHQL_JWT_SECRET stop working after update to 2.0.1

### ISSUE THREAD

**Issue by perelman** [hasura/graphql-engine#7220]
the value is in the format 
-----BEGIN CERTIFICATE-----\\nABCVCDFDSDFSF....-----END CERTIFICATE-----
I took it from https://hasura.io/jwt-config -> Auth0
It works in v1.3.3 after I replaced all the \n with \\n

Now I am getting 
Fatal Error:- Environment variable HASURA_GRAPHQL_JWT_SECRET: Error in $: object value: Failed reading: unescaped control character

**Comment by arjunyel** [comment]
Check this out https://github.com/hasura/graphql-engine/issues/4847

**Comment by perelman** [comment]
@arjunyel  thanks!
