### ISSUE TITLE
Metadata out-of-date error when modifying column name and custom graphQL field at the same time

### ISSUE THREAD

**Issue by iykekings** [hasura/graphql-engine#7221]
Reproduce by: Going to modify table route and editing any column of a table. Then change column name and custom graphql field. There will be an error about inconsistent metadata, if the custom graphql field isn't empty but if it is, there will be an error notification 'Metadata out-of-date...'

**Comment by 0x777** [comment]
@iykekings Is this something that needs to be fixed on the server?

**Comment by iykekings** [comment]
I'm just guessing, most metadata-out-date error I have encountered needed a fix from the server. I and Sam have scheduled to discuss it tomorrow

**Comment by altschuler** [comment]
This happens for me on v2.0.3 when I add a new table.

**Comment by KloudJack** [comment]
Related #7324

**Comment by iykekings** [comment]
closing as resolved
