### ISSUE TITLE
mssql: support event triggers

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#7228]
Similar to what we have for Postgres

**Comment by 0x777** [comment]
Notes from @nicuveo : 

<hr> 

(Documentation for event triggers: https://hasura.io/docs/latest/graphql/core/event-triggers/index.html.)

This is likely to be a long task. First, the code for event triggers need to be generalized (it is Vanilla Postgres only for now);
  - API types are declared in `Hasura/RQL/Types/EventTrigger`
  - the API itself is in `Hasura/RQL/DDL/EventTrigger`
  - the invocation code is in `Hasura/Eventing`
 
There already are a few functions related to them in BackendMetadata, but I don't know to which extent we've moved the process to the class.

**Comment by sassela** [comment]
Related issues:
[OSS issue](https://github.com/hasura/graphql-engine/issues/7075)
[user request](https://github.com/hasura/graphql-engine/issues/6679)

**Comment by m4ttheweric** [comment]
+1 for this! we love to see sql server support.

**Comment by MiteshDhiranAllscripts** [comment]
+ 1 for this!

**Comment by jmarbutt** [comment]
Also can't wait to see this.

**Comment by chrisknu** [comment]
+1 for this!

**Comment by ecthiender** [comment]
This is now implemented and merged to main via abb57e58c84d493202d36d654a009b46e306b297. It will be available in the upcoming release. 

cc @tirumaraiselvan @Naveenaidu

**Comment by chrisknu** [comment]
Most excellent, thanks!

**Comment by jmarbutt** [comment]
@ecthiender so can we start using it without the console work in the next release?

**Comment by tirumaraiselvan** [comment]
@jmarbutt Yeah, it will work without console. Pls do try it out in the next major beta (2.7) !

**Comment by Deluxo** [comment]
In release notes of 2.7 I see that MSSQL Event Trigger support is mentioned, but I cannot select MSSQL while creating an Event Trigger (my primary database is PG, MSSQL is a +1).

Is this by design or a bug?

**Comment by tirumaraiselvan** [comment]
Console support is still pending and hence we haven't officially released
it. It is slated for 2.9 release.

**Comment by Deluxo** [comment]
Does this mean it's still possible to use it in mssql? Like via API or other ways? @tirumaraiselvan

**Comment by tirumaraiselvan** [comment]
@Deluxo Yes, you can use the APIs: https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/event-triggers/#metadata-mssql-create-event-trigger
