### ISSUE TITLE
mssql: support mutations

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#7229]
The update and delete APIs should be similar to what exists for Postgres. We'll have to check if sql server's `output` is as powerful as postgres's `returning` (which is essential for enforcing `check` in update permissions). For inserts, we can start of with the most basic inserts without relational inserts and upsert API (which will probably be different for mssql).

**Comment by seanparkross** [comment]
Closing this issue since this is implemented. [Docs](https://hasura.io/docs/latest/mutations/ms-sql-server/index/).
