### ISSUE TITLE
Upgrade from v1/Config V2 to v2/ Config v3 keeps applying migrations that were already applied.

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#7230]
We upgraded form v1 with config v2 to v2 with config v3.
when doing
```
hasura migrate apply --all-databases
```
it tries to reapply the migrations that were already applied earlier resulting in an error because tables already exists.

**Comment by scriptonist** [comment]
@abdullah2993 config v3 uses a different state store for storing migration state. the `scripts update-project-v3` command should move this automatically during the update process, but it looks like that is not the case for you.

What we can do here is, we can use `hasura migrate apply --skip-execution` to mark your migrations as applied.

**Comment by abdullah2993** [comment]
Running `hasura update-project-v3  --move-state-only ` on the deployed version fixed it for us.
