### ISSUE TITLE
Metadata is Out-of-Date if creating a table with updated_at column

### ISSUE THREAD

**Issue by bkniffler** [hasura/graphql-engine#7233]
Tried on v2.0.1 and v2.0.0-beta2. PostgreSQL 12.4.

When creating a table with predefined uuid id and created_at, everything is OK. As soon as I try to add one with the predefined updated_at, this error is appearing:

```
The operation failed as the metadata on the server is newer than what is currently loaded on the console. The metadata has to be re-fetched to continue editing it.

Do you want fetch the latest metadata?
```

**Comment by bkniffler** [comment]
Maybe related to:
https://github.com/hasura/graphql-engine/issues/6805

**Comment by 0x777** [comment]
This is easily reproducible, when creating a new table add 'created_at' column from 'frequently used columns' list. I'm not sure if this is an issue on the server or on the console.

**Comment by crates** [comment]
I'm having this problem with a brand new instance of Hasura v2.0.3 today.

**Comment by KloudJack** [comment]
Caused by #7324

**Comment by happyfloat** [comment]
My current workaround is to create the Table via the UI, then after getting the metadata error I just go to the data tab again and track the table with the click of the button manually. Works well.
