### ISSUE TITLE
Config v3 issues on windows when using env variable to set database_url

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#7238]
On windows using env variables to set the `database_url` in `databases.yaml` throws error. On linux it works prefectly.
This fails
```
database_url: 
    from_env: HASURA_GRAPHQL_DATABASE_URL
```
with error
```
graphql-engine_1  | time="2021-07-14T13:10:12Z" level=fatal msg="error applying me
tadata \n{\n  \"path\": \"$.metadata.sources[0].tables\",\n  \"error\": \"parsing 
[] failed, expected Array, but encountered Null\",\n  \"code\": \"parse-failed\"\n
}"
```
setting it directly works
```
database_url: postgres://postgres:postgres@postgres:5432/postgres
```

Using docker compose image `hasura/graphql-engine:v2.0.1.cli-migrations-v3`

**Comment by scriptonist** [comment]
@abdullah2993 Just tried reproducing this issue, but it seems to work as expected.

Can you share the contents of your `database.yaml` file?

**Comment by abdullah2993** [comment]
@scriptonist we managed to fix this 
![image](https://user-images.githubusercontent.com/5978905/125631436-f0e94ca7-a7e8-4c22-b9db-440b55994c02.png)

not sure if has to do with the space or the line endings

**Comment by scriptonist** [comment]
@abdullah2993 that seems very unlikely. I just tried to run a project on windows that was "generated" on a Linux machine, which seems to work as expected. 

One question though, by any chance did the `databases.yaml` was missing a `tables` key?

**Comment by abdullah2993** [comment]
@scriptonist this fixed it for us and is reproducible.

the `database.yaml` has the `tables` key.
```
  tables: "!include default/tables/tables.yaml"
``` 

we followed [this technique](https://github.com/hasura/graphql-engine/issues/7153#issuecomment-871467196) to regenerate the metadata on the windows machine with changed line endings for migration/metadata file and did the change shown above.

**Comment by scriptonist** [comment]
@abdullah2993 Got it, thanks. can you share the steps to reproduce this?
