### ISSUE TITLE
Generated custom_column_names are not always compliant

### ISSUE THREAD

**Issue by vst** [hasura/graphql-engine#7239]
I am receiving errors while trying to track MSSQL tables (from a legacy database) with fields of which some have multiple space characters (via builtin Web console).

Hasura attempts to *fix* such fields via `custom_column_names` but not all custom names are GraphQL-compliant. Here is a synthetic example:

```json
...
    {
      "type": "mssql_track_table",
      "args": {
        "table": {
          "name": "mytable",
          "schema": "dbo"
        },
        "configuration": {
          "custom_column_names": {
            "My field": "My_field",
            "My funny field": "My_funny field"
          }
        },
        "source": "db"
      }
    },
...
```

`My field` is well customized as `My_field`, but `My funny field` is not customized correctly: Only the first space character is replaced with an underscore.

I wanted to fix it and issue a PR, but I couldn't find the responsible piece of code in the codebase. If this is a concern of low-priority, I would appreciate if someone can guide me to fix it.

**Comment by iykekings** [comment]
@vst Thanks for spotting this. It is coming from src/dataSources/common/index.ts#L90. The regex needs the global flag. I will link a PR with the applied fix in a moment.

**Comment by vijayprasanna13** [comment]
Resolved in [commit](https://github.com/hasura/graphql-engine/commit/760406b85131d9826f87af069ac41698f75869cb)
