### ISSUE TITLE
cloud: internal server error when adding db with ssl connection settings

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#7249]
When adding a database with SSL certificates, 500 internal server error happens:
![image](https://user-images.githubusercontent.com/4124733/125924899-0ff7806d-411b-48e7-9de1-170ba2dc9ada.png)

**Comment by shahidhk** [comment]
We've tracked this to a bug in the infrastructure and will update here after rolling out a fix.

**Comment by pablocastellanos** [comment]
never mind, just tested on v2.0.3 and it now works!

**Comment by shahidhk** [comment]
This is fixed on Cloud.
