### ISSUE TITLE
Insert mutation with multiple objects throwing error "cannot insert into column from_amount_str" on a generated column

### ISSUE THREAD

**Issue by albinth** [hasura/graphql-engine#7250]
While insert into a table having generated column with multiple objects thorwing error can't insert into generated column.

mutation query {
  insert_vam_interest_rate_work(objects:[{channel_seqid:"686874hgdsjfsgh" calc_type: CREDIT, rate_type: FIXED, interest_cat: CREDIT_ALL, fixed_rate: 5.0, from_amount: 0, to_amount: 1000, spread: 0.0}, {calc_type: CREDIT, rate_type: FIXED, interest_cat: CREDIT_ALL, fixed_rate: 5.0, from_amount: 1000.01, to_amount: -1, spread: 0.0}]){
    affected_rows
  } 
}

response :

{
  "errors": [
    {
      "extensions": {
        "internal": {
          "statement": "WITH \"vam_interest_rate_work__mutation_result_alias\" AS (INSERT INTO \"vam\".\"interest_rate_work\" ( \"calc_type\", \"from_amount\", \"to_amount\", \"fixed_rate\", \"reference_rate\", \"spread\", \"from_amount_str\", \"updated_at\", \"currency\", \"interest_cat\", \"bank_entityid\", \"to_amount_str\", \"created_at\", \"rate_type\", \"id\", \"corporate_guid\", \"effective_date\", \"channel_seqid\", \"profile_code\", \"profile_id\" ) VALUES (('CREDIT')::text, ('0.0')::numeric, ('1000.0')::numeric, ('5.0')::numeric, DEFAULT, ('0.0')::numeric, DEFAULT, DEFAULT, DEFAULT, ('CREDIT_ALL')::text, DEFAULT, DEFAULT, DEFAULT, ('FIXED')::text, DEFAULT, DEFAULT, DEFAULT, ('686874hgdsjfsgh')::text, DEFAULT, DEFAULT), (('CREDIT')::text, ('1000.01')::numeric, ('-1.0')::numeric, ('5.0')::numeric, DEFAULT, ('0.0')::numeric, DEFAULT, DEFAULT, DEFAULT, ('CREDIT_ALL')::text, DEFAULT, DEFAULT, DEFAULT, ('FIXED')::text, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT)  RETURNING * , ('true')::boolean AS \"check__constraint\"), \"vam_interest_rate_work__all_columns_alias\" AS (SELECT  \"id\" , \"profile_code\" , \"calc_type\" , \"interest_cat\" , \"from_amount\" , \"to_amount\" , \"rate_type\" , \"fixed_rate\" , \"reference_rate\" , \"spread\" , \"created_at\" , \"updated_at\" , \"corporate_guid\" , \"currency\" , \"effective_date\" , \"profile_id\" , \"bank_entityid\" , \"channel_seqid\" , \"from_amount_str\" , \"to_amount_str\"  FROM \"vam_interest_rate_work__mutation_result_alias\"      ) SELECT  json_build_object('affected_rows', (SELECT  COUNT(*)  FROM \"vam_interest_rate_work__all_columns_alias\"      ) ) , (SELECT  coalesce(bool_and(\"check__constraint\" ), 'true' )  FROM \"vam_interest_rate_work__mutation_result_alias\"      )        ",
          "prepared": false,
          "error": {
            "exec_status": "FatalError",
            "hint": null,
            "message": "cannot insert into column \"from_amount_str\"",
            "status_code": "42601",
            "description": "Column \"from_amount_str\" is a generated column."
          },
          "arguments": []
        },
        "path": "$.selectionSet.insert_vam_interest_rate_work.args.objects",
        "code": "unexpected"
      },
      "message": "database query error"
    }
  ]
}

NB: Mutation query working with single object

**Comment by dsandip** [comment]
Closing this one in favour of https://github.com/hasura/graphql-engine/issues/4633
