### ISSUE TITLE
metadata diff: Add filenames or more context to make updates actionable

### ISSUE THREAD

**Issue by James-Firth** [hasura/graphql-engine#7263]
When you run `hasura metadata diff --endpoint "myendpoint"` to compare your local system to the server you see a file diff which references line numbers.

However, it's comparing an entire directory to presumably the JSON export of the server.

There is little to no information on where to make changes if you need to manually update your local metadata.

Example diff output: 
```diff
--- /Users/jamesfirth/projects/repo/hasura/metadata
+++ server
@@ -1340,7 +1325,7 @@
-      type: String
+      type: String!
```

I would like to see something like:
A) The server metadata compared against each metadata file individually instead of against the aggregate so file names could be shown

or 

B) The name of the relationship shown

Thoughts?

**Comment by scriptonist** [comment]
@James-Firth Yes, this makes sense. We will work on a solution for this.
In the interim, `hasura metadata diff --type "unified-common"` might help to add the missing context?

**Comment by scriptonist** [comment]
Addressed in https://github.com/hasura/graphql-engine/commit/8c41ff539a3a193267fcab68cbc9e6b858358bee
