### ISSUE TITLE
Console: Inherited Roles Update for Launch

### ISSUE THREAD

**Issue by martin-hasura** [hasura/graphql-engine#7289]
Looking to update the Console to support the new inherited roles API -

RFC detailed here: https://github.com/hasura/graphql-engine-mono/blob/rfc/inherited-roles-improvements/rfcs/inherited-roles-improvements.md

PR here: https://github.com/hasura/graphql-engine-mono/pull/1715

From the Console side it seems like there are 2 breaking changes we'd need to account for:

1. When there is a conflict in inheritance (ex. 2 roles with insert permissions) the server will be passing an inconsistent metadata object with the roles, tables, and permissions which are conflicted. For the time being, the only resolution for this issue is to add a 'Custom Permission' which will overwrite the conflicted permission of the roles. 

Attached is a design to illustrate how we could do that using our current inconsistent metadata page + permission components: 
- https://hasura.github.io/product-design/63-inherited-roles-update/v1.1-mvp/2-inherited-roles-conflict.html
- https://hasura.github.io/product-design/63-inherited-roles-update/v1.1-mvp/2-inherited-roles-resolve.html
 
2. The other change is that inherited roles now have the possibility of inheriting from other roles which have inheritance.

Attached is also a design with how we can update the current inherited role page to update for this:
- https://hasura.github.io/product-design/63-inherited-roles-update/v1.1-mvp/1-inherited-roles-list.html

**Comment by clausMeko** [comment]
@martin-hasura will it be possible in the future to created inherited roles via cli?

**Comment by iosifnicolae2** [comment]
@martin-hasura would it be possible to resolve the conflicts by letting hasura merge the permissions using an OR operation? (basically, Hasura will dynamically create a permission which combine the conflicted permissions using an OR operation)

Thank you!
