### ISSUE TITLE
console: loss of transactionality in bulk v1 queries (raw SQL timeout)

### ISSUE THREAD

**Issue by sounden** [hasura/graphql-engine#7306]
I was testing some join statements that was pretty long running and I thought it was safe since there was a timeout you can set for each statement. But the reality was that the queries was running for a very very long time and consuming a lot of CPU on the database.

It works fine in my 1.3.3 environment but not in v2.0.3-cloud.1.

**Re-produce**
Execute a SQL statement in the console that takes longer time to run than the timeout.

**Expected behaviour**
"error": {
        "exec_status": "FatalError",
        "hint": null,
        "message": "canceling statement due to statement timeout",
        "status_code": "57014",
        "description": null
    },

**Actual behaviour**
No timeout error messages appears and the query runs as long as it needs.

**Comment by tirumaraiselvan** [comment]
Just to confirm, you are running the SQL from the `SQL` tab in Console?

![image](https://user-images.githubusercontent.com/8663570/127285730-f31f486b-d481-4760-be27-98709f6456a4.png)

**Comment by sounden** [comment]
Yes, correct @tirumaraiselvan

**Comment by vijayprasanna13** [comment]
commit https://github.com/hasura/graphql-engine/commit/2abd5a464af943eb3596a218f4303e2124753925 removes timeout input from the SQL page since server doesn't support transactions in v1 bulk queries
