### ISSUE TITLE
hasura seeds and migrations dont work connecting with server "pg_dump request: 404" "cannot fetch schema dump"

### ISSUE THREAD

**Issue by juandak16** [hasura/graphql-engine#7314]
i need get the data sql seed of hasura cloud server

run this command (with real data) in my local console, for launch hasura and connect with server

`hasura init my-project --endpoint http://my-graphql.hasura.app --admin-secret '<your-admin-secret>'`

`cd my-project`

`hasura console`

with this, the new hasura console is running connected with server y the project is good created!

now, i need run `hasura migrate create "init" --from-server` for get the server migrations 

but i get this error `level=fatal msg="cannot fetch schema dump: [not-found] resource does not exist ($)`

and when try get the server seeds with `hasura seed create table1_seed --from-table table1`

i get this error `level=fatal msg="exporting seed data: pg_dump request: 404 \n{\n  \"path\": \"$\",\n  \"error\": \"resource does not exist\",\n  \"code\": \"not-found\"\n}`

i dont know if need configure some more, already tried add the schema or db name but it didn't work either

my hasura version is updated and is the same as the server
![image](https://user-images.githubusercontent.com/20199487/127360068-bcb6c9f7-c6e8-4f7a-8346-1c9a3423ec71.png)

thanks

**Comment by scriptonist** [comment]
@juandak16 this probably will be because the pg dump API is not enabled on your instance. 

You can enable it by adding it to your list of enabled API's using `HASURA_GRAPHQL_ENABLED_APIS` environment variable.

Ref: https://hasura.io/docs/latest/graphql/core/deployment/graphql-engine-flags/reference.html

**Comment by juandak16** [comment]
yes!, pgdump was off in the HASURA_GRAPHQL_ENABLED_APIS. 

now, is activated and works correctly
