### ISSUE TITLE
console: support for computed fields

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#7336]
- [x] #7418
- [x] #7419

Note: Only the computed fields that do not require extra arguments other than the table row and those which return scalars are currently supported by the server.

**Comment by neil-buckley** [comment]
Thanks for this! Shouldn't compute fields that use the hasura_session be supported as it's a default there already really? 
![Screenshot 2021-08-18 at 16 55 29](https://user-images.githubusercontent.com/3385748/129931375-ad449f3c-4641-432d-a9fd-4418b42e5207.jpg)

**Comment by iykekings** [comment]
closed as resolved
