### ISSUE TITLE
 database query error on manually invoking an event trigger (first time for each row)

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#7339]
How to reproduce:

1) Create a simple insert trigger on, let's say an authors table. Allow this trigger to be manually invoked via the console.
2) Head to the authors table. Click on ⏯️ button to invoke the trigger. This will results in a database query error.
<img width="1420" alt="Screenshot 2021-08-03 at 12 24 07 PM" src="https://user-images.githubusercontent.com/24300818/127971136-8dfc9b38-1bfe-4812-b72f-0cd943ad5133.png">

3) Hit the ⏯️ button again, and the invocation works.
4) Hard refresh the page and try the button again on the same row. results in a database query error again. Another try succeeds.

Version: `v2.0.3-cloud.1`

**Comment by rikinsk** [comment]
Fixed via https://github.com/hasura/graphql-engine/commit/454e6afd1dcd0be39249353cd426426bb07dd498. Fix should be available in v2.0.4
