### ISSUE TITLE
bigquery: fix scalar type mapping

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#7344]
All BigQuery scalar types are currently published an built-in GraphQL Scalar types: `Int`, `Float`, `String` and `Boolean`. We'll need to only map those db scalar types which actually fit into the built-in GraphQL types and expose the rest of the them as custom scalar types, like we do with Postgres and SQL Server.

**Comment by soupi** [comment]
Sorry I don't really understand what this means, could you elaborate?

**Comment by sassela** [comment]
Closing, addressed at https://github.com/hasura/graphql-engine/commit/47b9321ba45ab673cee0d27bb08e01e97902d250
