### ISSUE TITLE
cli: add `hasura deploy` command

### ISSUE THREAD

**Issue by scriptonist** [hasura/graphql-engine#7349]
Add a CLI command which can do the following operations in one go. 

Config v3 
```
$ hasura metadata apply
$ hasura migrate apply --all-databases
$ hasura metadata reload
```

Config v2
```
$ hasura migrate apply
$ hasura metadata apply
```

**Comment by atb00ker** [comment]
I was wondering why this doesn't exist already.
I'll be happy to help you add this! :smile:

**Comment by atb00ker** [comment]
Hi @scriptonist 

https://github.com/hasura/graphql-engine/pull/7426 solves the issues and I think it's ready for review! :smile:

**Comment by scriptonist** [comment]
Thanks @atb00ker, will get it reviewed.

**Comment by purush7** [comment]
@scriptonist I think it is better for deploy to execute `migrate apply` and then `metadata apply`. In this way we don't need to execute `metadata reload` cmd.

**Comment by scriptonist** [comment]
@purush7 excerpt from [docs](https://hasura.io/docs/latest/graphql/core/migrations/upgrade-v3.html#changes-needed-in-existing-workflows)

> The reason why we have to do `metadata apply` first instead of `migrate apply` (that we are used to doing in config v2) is that if we do a migrate apply first then Hasura might not yet be aware about the databases it has to connect to as that information is present in metadata. Earlier we could not start Hasura without a connected database, but now we can.

This is for config v3, config v2 can use `migrate apply` -> `metadata apply` sequence.
