### ISSUE TITLE
Computed field not showing in relationships

### ISSUE THREAD

**Issue by flocosnier** [hasura/graphql-engine#7352]
On a table, I have a computed field which concatenates other fields and return a TEXT type :

`CREATE OR REPLACE FUNCTION public.get_codes_communes_intercommunalite(intercommunalite_row intercommunalite)
 RETURNS TEXT
 LANGUAGE sql
 STABLE
AS $function$
  SELECT string_agg(commune.code_commune, ',') AS codes_communes
  FROM commune
  WHERE
    code_epci = intercommunalite_row.code_epci
$function$`

I can query the computed field and it works perfectly. However, it doesn't show in the relationship dropdown menu.

Am I missing something ?

**Comment by 0x777** [comment]
@flocosnier 
> However, it doesn't show in the relationship dropdown menu.

I'm not sure what you mean by this. Are you trying to define a manual relationship using a computed field?

**Comment by flocosnier** [comment]
Yes, exactly ! Sorry if it wasn't clear.

**Comment by flocosnier** [comment]
I managed to create the remote relationship with a computed field via the metadata API :)

However, it can't be done via the console but I think it's being taken care of here https://github.com/hasura/graphql-engine/issues/7336 :)

Closing this issue !

**Comment by maxcan** [comment]
Is it possible to do this for local relationships?
