### ISSUE TITLE
stable/cli/get.sh fails because v2.0.5 release doesn't exist for amd64 (and others)

### ISSUE THREAD

**Issue by vegarsti** [hasura/graphql-engine#7354]
Hi, thanks for a great service!

We're using the [tibotiber/hasura-action](https://github.com/tibotiber/hasura-action) in our CD pipeline, which calls out to https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh. This script tries to get the newest release for the architecture it's called on, in our case it calls

```
curl -L# -f -o /tmp/cli-hasura-linux-amd64 https://github.com/hasura/graphql-engine/releases/download/v2.0.5/cli-hasura-linux-amd64 
```

but this release doesn't exist yet.

**Comment by scriptnull** [comment]
Hi, thanks for reporting :pray:

We have applied a quick fix for this in our stable branch - https://github.com/hasura/graphql-engine/commit/75a22967cf345fae5e208bb8b9ab39b2a3d510c4 and this problem should have been mitigated already. Please try rerunning your CI/CD pipeline.

**Comment by vegarsti** [comment]
Amazing, thanks for fixing so quickly! It worked as a charm now!

**Comment by scriptnull** [comment]
More update on this: We also landed a commit ( https://github.com/hasura/graphql-engine/commit/28c7a1d0d0283413d304ebae4aa476d39fbdab75 ) which will help in avoiding this situation for future releases :slightly_smiling_face:

Additionally, I would suggest the usage of `VERSION` env for pinning the CLI version that gets installed in CI/CD pipelines (if you would like to have more control over what version of the CLI gets installed)
```
curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | VERSION=v2.0.4 bash
```

**Comment by vegarsti** [comment]
Very nice! And thanks for the suggestion, we should probably do that!
