### ISSUE TITLE
console: add support for `track_table` version 2 API

### ISSUE THREAD

**Issue by kolharsam** [hasura/graphql-engine#7360]
### Problem

**Click on "Track"**

![image](https://user-images.githubusercontent.com/6604943/128456461-60b85185-171b-4c0b-9b1d-1e0e998ba11d.png)

**Boom! Error...**

![image](https://user-images.githubusercontent.com/6604943/128457117-14bfde6f-5c74-4db1-b23c-7664955cafc7.png)

### Possible Solution

Currently, it may not be possible to track tables with duplicate names since the types generated by the server might overlap, resulting in errors. So it'll be useful to be able to customise before tracking. The server currently already supports customisation before tracking tables via the `track_table (V2)` API [Docs](https://hasura.io/docs/latest/graphql/core/api-reference/schema-metadata-api/table-view.html#track-table-v2). It would be nice to extend the same on the console too.

If we observe untracked tables with the same names as one's that have already been tracked, we could show an additional button next to the `Track` button, which would open a small dialog box to insert any customisation info on click.

![image](https://user-images.githubusercontent.com/6604943/128458059-2d9914ab-b37c-492a-b08e-930b7119d8e3.png)

### Open Question(s)

- Is this API supported on other data sources on the server?
- How would "Track All" function in that case? (We could warn the users that they might bump into errors before making the API call(s) for "Track All")

**Comment by martin-hasura** [comment]
Hey @kolharsam 👌

Put together some designs to go with this, as well as conflict resolution:
https://hasura.github.io/product-design/77-console-customize-table/1-track.html
https://hasura.github.io/product-design/77-console-customize-table/2-track-customize.html
https://hasura.github.io/product-design/77-console-customize-table/3-track-resolve-conflict.html

Lemme know if you want to chat through it

**Comment by kolharsam** [comment]
@martin-hasura, I think these are great! I'll get started on the initial work soon, and I will get to you if I have any questions! 
Thanks again! 🙏

**Comment by vijayprasanna13** [comment]
@kolharsam We're working on a new UX for postgres that makes the landing page for viewing/tracking your tables that should ideally solve all of these issues that you've mentioned. Updates in the related [issue](https://github.com/hasura/graphql-engine/issues/9509)

**Comment by manasag** [comment]
Closing this issue in favor of #9509 . This is possibly solved with the new UI released in v2.29
