### ISSUE TITLE
Hasura Console fails to add migrations if there are tabs in function body

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#7362]
The title pretty much says it all but if the function body is indented with `tabs` rather then `spaces` it fails to create a migration.
See the GIF for reproducing it.
using version `2.0.3` of console/cli

![Peek 2021-08-06 18-27](https://user-images.githubusercontent.com/5978905/128517611-1e1ffbe3-e881-4c51-bb0d-9d5d52378021.gif)

**Comment by abdullah2993** [comment]
any update on this?

**Comment by scriptonist** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/7d26e86fa1d0df3744f540fa986d4ce52120ae50
