### ISSUE TITLE
hasura cli cannot access hasura cloud

### ISSUE THREAD

**Issue by stephensamra** [hasura/graphql-engine#7370]
I have a project in Hasura cloud (v2.0.4-cloud.2). When I try to run `hasura console`, I get the following error:

```
FATA[0002] {
  "path": "$",
  "error": "resource does not exist",
  "code": "not-found"
}
```

I am using a `.env` file with the endpoint and admin secret:

```
HASURA_GRAPHQL_ENDPOINT=https://xxxx.hasura.app/v1/graphql/
HASURA_GRAPHQL_ADMIN_SECRET=xxxx
```

Debug output:

```
❯ hasura console --log-level DEBUG
DEBU global config file exists, verifying contents
DEBU global config is pre-set to &cli.GlobalConfig{UUID:"cb351c7d-88e8-4a99-be62-390e904d0a8e", EnableTelemetry:true, ShowUpdateNotification:true, CLIEnvironment:"default"}
DEBU global config: uuid: cb351c7d-88e8-4a99-be62-390e904d0a8e
DEBU global config: enableTelemetry: true
DEBU global config: showUpdateNotification: true
DEBU global config: cliEnvironment: default
DEBU ENV vars read from: /xxxx/xxxx/xxxx/xxxx/.env
DEBU cannot get config information from server, this might be because config API is not enabled: error fetching server config: [not-found] resource does not exist ($)
DEBU graphql engine endpoint: https://xxxx.hasura.app/v1/graphql/
DEBU graphql engine admin_secret: xxxx
DEBU versions: cli: [v2.0.0-beta.1] server: []
DEBU compatibility check: [true] server with no version treated as pre-release build
DEBU telemetry: beamed                             fields.time=185.725285ms isError=true
```

I have enabled the config API via `HASURA_GRAPHQL_ENABLED_APIS`:

![Screen Shot 2021-08-09 at 11 08 57](https://user-images.githubusercontent.com/8583469/128690836-da26897f-2110-4e11-bbff-e0e321cb886d.png)

Am I missing something?

Thanks in advance.

**Comment by scriptonist** [comment]
@stephensamra `HASURA_GRAPHQL_ENDPOINT` has to be set to `https://xxxx.hasura.app` rather than `https://xxxx.hasura.app/v1/graphql/`. Can you try that? I'm guessing that might be it.

**Comment by stephensamra** [comment]
Hi @scriptonist, thanks for the quick reply. That solved it. I'm not sure if it's related but the version has suddenly changed from v2.0.4-cloud.2 to v2.0.5-cloud.1.
