### ISSUE TITLE
Downgrade Hasura 2.0.X to 1.3.3 error "Key (trigger_name)=(...) is not present in table"

### ISSUE THREAD

**Issue by christopherjwang** [hasura/graphql-engine#7374]
I'm running some local docker based runs in preparation for a Hasura 2.0 upgrade. While we are going to be doing this live in production on Hasura Cloud, we're trying this out locally to get some playbooks running just in case anything unexpected occurs.

After adding a simple cron trigger (named foo in this example), on v1.3.3, I've taken down the docker stack and brought it back up with a v2.0.X of Hasura. However, after upgrading to Hasura 2.0.1 (or 2.0.5) from 1.3.3, I am unable to run the command from the docs[0] due to an error that ends with

```
"description":"Key (trigger_name)=(foo) is not present in table \"hdb_cron_triggers\"."},"arguments":[]},"path":"$","error":"database query error","code":"unexpected"}
``` 

Without downgrading the catalogue, switching the docker image back to v1.3.3 refuses to start with:
```
{"path":"$","error":"Cannot use database previously used with a newer version of graphql-engine (expected a catalog version <=40, but the current version is 46).","code":"not-supported"}
```

I've created a quick github repository [1] that shows the steps necessary to reproduce this issue. The full error message is in the root of the repository [2].

Main followup questions from me are:
1) Is it possible to downgrade from Hasura 2.0.X to 1.3.3 cleanly?
2) How would one go about downgrading Hasura from 2.0.X to 1.3.3-cloud.9 in Hasura Cloud?

Thanks!

[0] https://hasura.io/docs/latest/graphql/core/deployment/downgrading.html#step-2-downgrade-hasura-catalogue-version
[1] https://github.com/christopherjwang/hasura_downgrade_cron_issue
[2] https://github.com/christopherjwang/hasura_downgrade_cron_issue/blob/main/error_message.txt

**Comment by rikinsk** [comment]
FIxed via https://github.com/hasura/graphql-engine/commit/1294ae59f2524d5ebec38de52e30f14a38282199
