### ISSUE TITLE
Confusing HASURA_GRAPHQL_ENABLED_APIS options (Documentation issue?)

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#7379]
Both [1.x](https://hasura.io/docs/1.0/graphql/core/deployment/graphql-engine-flags/reference.html#server-flag-reference) and [2.x](https://hasura.io/docs/2.0/graphql/core/deployment/graphql-engine-flags/reference.html#server-flag-reference) server flag pages state that `HASURA_GRAPHQL_ENABLED_APIS` options are as follow:

`Comma separated list of APIs (options: metadata, graphql, pgdump) to be enabled. (default: metadata,graphql,pgdump)`

Then the "[Config API](https://hasura.io/docs/latest/graphql/core/api-reference/config.html#config-api-reference)" page states it is enabled by default. To disable, omit the `config` option from the `HASURA_GRAPHQL_ENABLED_APIS` value.

So which documentation page is right? Is `config` an option or not?

I see a single reference to `config` being an option in [#6605](https://github.com/hasura/graphql-engine/issues/6605#issuecomment-785922477)

**Comment by kolharsam** [comment]
Hey @jflambert! Thanks for pointing this out. 

To answer your question, `config` is a valid option.
To clear things up, `metadata, graphql, pgdump, config` are all enabled by default.

We'll improve the documentation around this in the coming days.

**Comment by rikinsk** [comment]
closed via https://github.com/hasura/graphql-engine/commit/8246bcc9d329ac9231af73799499ff37be5f4ec6

**Comment by ash0080** [comment]
> Hey @jflambert! Thanks for pointing this out.
> 
> To answer your question, `config` is a valid option. To clear things up, `metadata, graphql, pgdump, config` are all enabled by default.
> 
> We'll improve the documentation around this in the coming days.

So what about he schema API, what's keyword to enable disable it?
