### ISSUE TITLE
Templated Envs in Hasura Events 

### ISSUE THREAD

**Issue by adevofficial** [hasura/graphql-engine#7383]
**Current**
Hasura actions have an ability to use templated environment variables but Hasura events we need to create new environment variables for every new event

**Solution**
Add the same behavior to Hasura Events so that we can reduce no environment variables while using with lambdas/resources like endpoints

![image](https://user-images.githubusercontent.com/29562232/128977232-a1bcbf4d-0791-40cf-8626-4b9255c14901.png)

![image](https://user-images.githubusercontent.com/29562232/128977298-79ab5d2c-44fa-40c7-9951-fe6d9241cb06.png)

**Comment by tirumaraiselvan** [comment]
Actually, you can use the templated env in Hasura Event Triggers as well. Just use the static option and put in the templated env.

**Comment by adevofficial** [comment]
@tirumaraiselvan I tried adding but not working for me. Hasura is 2.0.9
![image](https://user-images.githubusercontent.com/29562232/139800590-49b8596c-b8ed-491c-ac57-13db6bf19a85.png)

**Comment by tirumaraiselvan** [comment]
@adevofficial Do not use `From env var` option in Webhook URL, use the `Static` option and provide the template.

**Comment by jmarbutt** [comment]
This seems super counter intuitive, specially since the drop down calls it `URL` not `Static`
