### ISSUE TITLE
Support for Bulk Insert/Updates in REST endpoints

### ISSUE THREAD

**Issue by sytabaresa** [hasura/graphql-engine#7393]
Hi hasura team!!

when you configure a REST endpoint whis this kind of mutation:

```graphql
mutation insert_multiple_articles($objects: [article_insert_input!]!) {
  insert_article(objects: $objects) {
    returning {
      id
      title
    }
  }
}
```
like you can find in [Insert multiple objects of the same type in the same mutation](https://hasura.io/docs/latest/graphql/core/databases/postgres/mutations/insert.html#insert-multiple-objects-of-the-same-type-in-the-same-mutation)

and send POST request with this body:
```json
{
    "objects": [
        {
            "title": "Article 2",
            "content": "Sample article content",
            "author_id": 4
        },
        {
            "title": "Article 3",
            "content": "Sample article content",
            "author_id": 5
        }
    ]
}
```
the endpoint will returns:
```json
{
    "path": "$",
    "error": "The variable type for the expected variable data was not supported.",
    "code": "bad-request"
}
````
so the `article_insert_input` type is the problem here, but in this case, is used for bulk insert multiple values. Hasura has a form to make a bulk insert or update in a REST endpoint? I guess this can achieve by supporting this kind of custom types but it appears that isn't supported yet.

**Comment by sytabaresa** [comment]
Duplicated and/or related to #6911, there use `[Float!]!` and here custom input types, like `insert_multiple_articles` if the problem is the array type and not the input type, this will be resolved

**Comment by GrozescuRares** [comment]
Any updates about when it will be solved? Thank you.
