### ISSUE TITLE
Updating Session argument variable failed. 2.0.5.cloud-1

### ISSUE THREAD

**Issue by happyfloat** [hasura/graphql-engine#7395]
I can not add the hasura_session argument in the UI. It will error with `function already tracked : "..."`

**Comment by happyfloat** [comment]
Also untracking a function in the UI doesn't work too

**Comment by happyfloat** [comment]
After deleting the function and tracking it via a POST request, it is working.
Documentation is also linking to the outdated version. Here the new one:
https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/custom-functions.html
```
// POST /v1/metadata HTTP/1.1
{
    "type": "pg_track_function",
    "args": {
        "function": {
            "schema": "public",
            "name": "YOUR_FUNCTION_NAME"
        },
        "source": "YOUR_DB_NAME",
        "configuration": {
            "session_argument": "hasura_session"
        }
    }
}```

**Comment by lorenzo** [comment]
I'm affected by this bug too

**Comment by lucarestagno** [comment]
This issue refers to an old version of the Console, therefore this should have been addressed in recent versions.
If the issue is still present, @happyfloat please reopen it — thanks.
