### ISSUE TITLE
Error in error return message (just grammar - no biggie)

### ISSUE THREAD

**Issue by corepay** [hasura/graphql-engine#7396]
Hi, hate to sound nitpicky but I am returning the Hasura error codes and messages to user when I create event webhooks.  My OCD is paralyzing at times so wanted to point out a small adjustment that should be made in your error code response... 

```
"data": {
      "error": "event trigger with name \"webhook-h8q0nc2hm96ym7hv6wlc4\" not exists",  <-- here
      "code": "not-exists"
    }
```

The error message should read:

```
"data": {
      "error": "event trigger with name \"webhook-h8q0nc2hm96ym7hv6wlc4\" does not exist",  <-- here
      "code": "not-exists"
    }
```

Real pleased with everything I am finding in Hasura.  Really appreciate it.

**Comment by rikinsk** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/47f8bc9b42f93d0a9ad1e3995600ef42ec2260fd

**Comment by rikinsk** [comment]
@corepay I feel you :). Thanks for poinitng this out.
