### ISSUE TITLE
Bug: Hasura using ANY when it should be using IN clause.

### ISSUE THREAD

**Issue by dougg0k** [hasura/graphql-engine#7404]
Hi, what the title says.

I have been trying to query using IN which give me results only regarding those parameters, but Hasura was giving me other results all together, when I analysed the request, the SQL showed me that it was using `ANY` even though I specified `_in` in the filters.

**Comment by 0x777** [comment]
@dougg0k Can you provide us more information on how to reproduce this? What the query is? What is expected? What is instead returned?

**Comment by dougg0k** [comment]
Only by using the `_in` filter, the SQL generated was with the `ANY` clause. 

There are owners in every item that is returned, the query was being filtered by owner using the `_in` filter, and it was returning me results from other owners also when it should have been only owners that I passed through the parameters, then I tried to check why and analysed the query, the query showed the `ANY` clause where it should have been the `IN`. At least it seems like it since the filters seems to follow the SQL pattern. Unless I am wrong about it.
