### ISSUE TITLE
Index Creation Errors with Camel Case Column Names

### ISSUE THREAD

**Issue by browniefed** [hasura/graphql-engine#7409]
If a postgres column name is camel cased like `firstName`. The generated SQL query does not add quotes, and fails to create the index with the error `postgres-error: column "firstname" does not exist`

```
"statement": "CREATE  INDEX \"patient_name_index\" on\n  \"public\".\"patients\" using btree (firstName, lastName, goesByName);",
```

<img width="1547" alt="Screen Shot 2021-08-17 at 3 24 41 PM" src="https://user-images.githubusercontent.com/1714673/129808655-53117953-f7ab-4b58-b6af-fcfdb3354c72.png">

**Comment by vijayprasanna13** [comment]
Fixed in [commit](https://github.com/hasura/graphql-engine/commit/479c0b3980a6683947a6cb651f14bb35e444e3ab)
