### ISSUE TITLE
Console Bug v2.0.4 - Renaming table not updating side navigation

### ISSUE THREAD

**Issue by leoalves** [hasura/graphql-engine#7412]
When renaming a table in the console, the side navigation does not update with the new name

https://user-images.githubusercontent.com/3867140/129909599-e107f04e-e03e-435e-9d0b-96a1ad87697d.mp4

**Comment by vijayprasanna13** [comment]
resolved in [commit](https://github.com/hasura/graphql-engine/commit/8ca110b5bb2af799eda9649b7ed093c0b3bd2362)
