### ISSUE TITLE
event_trigger: show better errors during http_error

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#7425]
Currently, when we don't receive a proper response from event trigger (say, connection timeout, response timeout, etc), then the invocation log has something like this:

```
{
"type":"client_error",
"version": 2,
"data": {}
}
```

We should change `client_error` to something like `http_error` and have another key, inside `data`, called `error_type` which can be the `Show` of the HTTPExceptionContent: https://hackage.haskell.org/package/http-client-0.7.8/docs/Network-HTTP-Client.html#t:HttpExceptionContent

Also, if we receive a HTTP status code from the webhook (during such exceptions), then we must use that code instead of 1000.

**Comment by ecthiender** [comment]
Fixed via ccf97ab6b02c1cd73eef547daf8075f519cb23d2
