### ISSUE TITLE
Console: Changes to Actions spin forever and do not complete

### ISSUE THREAD

**Issue by 24601** [hasura/graphql-engine#7427]
v2.0.7 server & client, we make a change to a type definition (e.g. add a string property), attempt to save, and the red status bar just sits there for quite some time, no error, just sits for ever, the change is never reflected in metadata. 

Also, changes in other areas (such as column presets) do not appear to be working either, but sometimes other changes do work, but Actions consistently never work. 

This is occurring across 3 different developers' workstations.

**Comment by scriptonist** [comment]
@24601 is this on a console opened via `hasura console` ?
