### ISSUE TITLE
server/mssql: error "[Mic...t][ODBC Driver 17 for SQL Server]...Invalid column name 'xxx'  "

### ISSUE THREAD

**Issue by cocomm1995** [hasura/graphql-engine#7429]
Hello,

we are seeing the below error when we use the **_exists** operator to set a permission rule

![image](https://user-images.githubusercontent.com/17053618/130270736-fe9f2d14-7f04-4480-b300-cf0386ee26b2.png)

Add custom check in permission table:

`{"_exists":{"_where":{"_and":[{"fldCrewID":{"_eq":"X-Hasura-User-Id"}},{"fldNoRights":{"_eq":0}}]},"_table":{"schema":"dbo","name":"tblSettingsPersonal"}}}`

Run this query:

`query MyQuery {
  Equipment {
    Amount
  }
}
`

It fails with this error when we use the **_exists** operator to set a permission rule:

`{
  "errors": [
    {
      "extensions": {
        "internal": {
          "tag": "unsuccessful_return_code",
          "contents": [
            "odbc_SQLExecDirectW",
            -1,
            "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'fldCrewID'.[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'fldCrewID'.[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'fldNoRights'.[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'fldNoRights'.[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'fldNoRights'."
          ]
        },
        "path": "$",
        "code": "unexpected"
      },
      "message": "sql server exception"
    }
  ]
}`

The generated SQL is:

`SELECT ISNULL((SELECT [t_Equipment1].[Amount] AS [Amount],
[t_Equipment1].[ArrangementNum] AS [ArrangementNum],
FROM [dbo].[Equipment] AS [t_Equipment1]
WHERE ((EXISTS (SELECT 1 AS [exists_placeholder]
FROM [dbo].[tblSettingsPersonal] AS [t_tblSettingsPersona1]
WHERE ((((([t_Equipment1].[fldCrewID]) = (('123')))
OR ((([t_Equipment1].[fldCrewID]) IS NULL)
AND ((('123')) IS NULL))))))))
FOR JSON PATH), '[]')
`

Below are the steps we did:

1. check permission table, noticed that the no schema shows in the schema list, but the schema name 'dto' shows in the expression area

![Screen Shot 2021-08-23 at 12 47 47 PM](https://user-images.githubusercontent.com/17053618/130510134-cf075db5-70f5-4200-b815-6f7a5a39a170.png)

2. check raw query which causes the error from hasura console, noticed that the table name is wrong from WHERE keyword, should be **[t_tblSettingsPersona1].[fldCrewID]** instead of **[t_Equipment1].[fldCrewID]**

`FROM [dbo].[tblSettingsPersonal] AS [t_tblSettingsPersona1]
WHERE ((((([t_Equipment1].[fldCrewID]) = (('123')))
OR ((([t_Equipment1].[fldCrewID]) IS NULL)
AND ((('123')) IS NULL))))))))
FOR JSON PATH), '[]')`

![Screen Shot 2021-08-20 at 9 33 12 AM](https://user-images.githubusercontent.com/17053618/130266080-abc33da3-f3e6-4166-b0ce-6a1a4d612cf0.png)

Does anyone have any idea how to fix this issue? 

Appreciate it!

**Comment by GildedHonour** [comment]
Will it require Windows to reproduce it?

**Comment by cocomm1995** [comment]
> Will it require Windows to reproduce it?

Hi, I don't think so, mine is macOS Catalina. I can reproduce the issue in my machine, do you have any suggestions regarding this issue? Thanks

**Comment by sassela** [comment]
Hey @cocomm1995 , thank you for the detailed bug report! [A fix for this was merged yesterday](https://github.com/hasura/graphql-engine/commit/d358d06e68aa33d4badba1aa1cb15406745a0308) and will be available in the next release. Please comment/reopen this if you notice any other issues.
