### ISSUE TITLE
cli: cannot add database from `hasura console`

### ISSUE THREAD

**Issue by scriptonist** [hasura/graphql-engine#7448]
![image](https://user-images.githubusercontent.com/8335904/130546618-edeba267-2f99-4c28-85ad-6790ac5abc83.png)

**Comment by purush7** [comment]
Hey @scriptonist , I think there is a problem in console code in the body of post `/apis/migrate`
<img width="1118" alt="Screenshot 2021-08-24 at 4 40 47 PM" src="https://user-images.githubusercontent.com/72007599/130607225-428149c0-712d-4718-bd25-68434324a9af.png">
The datasource should be the `Database Display Name` and it shouldn't be empty

**Comment by vijayprasanna13** [comment]
Like @purush7 mentioned, it's due the `datasource` field being empty, but I'm not able to replicate the situation where this would happen. On a successful DB addition via CLI mode, this is the payload I see from the browser

```
{
    "name": "add_data_source",
    "up": [
        {
            "type": "pg_add_source",
            "args": {
                "name": "test",
                "configuration": {
                    "connection_info": {
                        "database_url": {
                            "from_env": "HASURA_GRAPHQL_DATABASE_URL"
                        },
                        "use_prepared_statements": false,
                        "isolation_level": "read-committed"
                    },
                    "read_replicas": null
                },
                "replace_configuration": false
            }
        }
    ],
    "down": [],
    "datasource": "default",
    "skip_execution": false
}
```
And if the `Database Display Name` is not filled, then the console will throw an UI validation error message. Could you share the steps that you used?

**Comment by scriptonist** [comment]
@vijayprasanna13 the steps to reproduce this is as follows.
1. start a Hasura instance with `HASURA_GRAPHQL_METADATA_DATABASE_URL` , ie no databases connected.
2. create a new CLI project by using the following commands 
```
hasura init test-project
cd test-project
``` 
3. open the console with `hasura console`
4. Try adding a new source from console, we will encounter the aforementioned issue.

**Comment by vijayprasanna13** [comment]
@scriptnull Yes, I'm able to replicate it now.

**Comment by vijayprasanna13** [comment]
@scriptonist If I set a valid string to the `datasource` field in the payload, the migrate API is failing with a error -
```
POST http://localhost:9693/apis/migrate
Error: socket hang up
```
I discussed this with @purush7 and he said that the `datasource` field is used to generate the migrations folder name, so in that case any valid string should work. 

Also, another behaviour I noted is that if use server with the `HASURA_GRAPHQL_METADATA_DATABASE_URL` not set, the `datasource` is sent as `default` (which works fine).

**Comment by purush7** [comment]
@scriptonist  and @vijayprasanna13 I have noticed that if the server is started with `HASURA_GRAPHQL_DATABASE_URL`, there isn't any api call to `/apis/migrate` while creating a new database

**Comment by purush7** [comment]
Hey @scriptonist and @vijayprasanna13 , there are 2 problems 

1) the `datasource` key is empty
2) cli exports the metadata from server to get the `kind`(Postgresql or Mssql) of datasource added as the server metadata isn't updated. It's getting hanged up. This is the old code for it
<img width="880" alt="old" src="https://user-images.githubusercontent.com/72007599/130625639-b8a2d445-f512-4f49-92ea-d8a91e2ca7c1.png">
and When I have changed it to 
<img width="880" alt="new" src="https://user-images.githubusercontent.com/72007599/130625801-3f7932a4-9bd6-4b8e-9abe-40aeff063dd6.png">
and with datasources key value as `dd`. The dd has been created inside the migrations folder.


I think we can solve this by having a datasource key and updating the server metadata before calling the `/apis/metadata`

**Comment by vijayprasanna13** [comment]
> I have noticed that if the server is started with HASURA_GRAPHQL_DATABASE_URL, there isn't any api call to /apis/migrate while creating a new database

When console is run from CLI mode and `HASURA_GRAPHQL_DATABASE_URL` is set, afaik, there will be no option to create a database from the console (the `default` database will be present and the console will not redirect to the `Add Datasource Page`) 
It has to created via the migrate API I believe, even if the `metadata` api is called for adding a source, the server will respond back with
```
code:  "migration_mode_enabled"
message:  "Migration mode is enabled"
```
I'm not if I'm missing something here.

> I think we can solve this by having a datasource key and updating the server metadata before calling the /apis/metadata

So this will be done from the CLI side?

**Comment by purush7** [comment]
Changes needed to make on cli side:

- cli shouldn't hangup if the databaseKind is missing (need to fix the GetSourceKind func)
- While handling the `/apis/migrate` Post query the cli should get the database kind from the configuration present in the query body

I think these are changes needed to make at present @vijayprasanna13 right? cc: @scriptonist 

and will think about datasources-name and display-names afterwards

**Comment by vijayprasanna13** [comment]
Yes, in addition I'll investigate why the `datasource` goes as empty on adding a new datasource from the console side.

**Comment by mmack** [comment]
Why is this issue closed? Still having this issue...

**Comment by purush7** [comment]
Thanks @mmack for pointing out. The `datasources` key is still empty with the latest binary in the request for `/apis/migrate`

Steps to produce:  https://github.com/hasura/graphql-engine/issues/7448#issuecomment-904570994

**Comment by mjazwinski** [comment]
I'm having this issue also, please fix it. I tried it on Windows 10 and Ubuntu 20.04. Also removing HASURA_GRAPHQL_METADATA_DATABASE_URL as @vijayprasanna13 described does not work for me.

**Comment by purush7** [comment]
@mjazwinski Have you tried with `HASURA_GRAPHQL_DATABASE_URL` instead of `HASURA_GRAPHQL_METADATA_DATABASE_URL`?

**Comment by mjazwinski** [comment]
Yes, with same results. On my env with config for graphql-engine like below the error is still present:
`graphql-engine:
    image: hasura/graphql-engine:v2.0.9
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      # PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey`

**Comment by vijayprasanna13** [comment]
@purush7 I'm running  server (v2.0.9) and cli (v2.0.9), when I try the following request on `http://localhost:9693/apis/migrate` I do not get a response back from the CLI and I get the `err: socket hang up` message. I also see that the payload from the console is generated correctly during adding a DB - 
```
{
    "name": "add_data_source",
    "up": [
        {
            "type": "pg_add_source",
            "args": {
                "name": "chinook_test",
                "configuration": {
                    "connection_info": {
                        "database_url": "postgres://postgres:test@172.17.0.1:6001/chinook",
                        "use_prepared_statements": false,
                        "isolation_level": "read-committed"
                    },
                    "read_replicas": null
                },
                "replace_configuration": false
            }
        }
    ],
    "down": [],
    "datasource": "chinook_test",
    "skip_execution": false
}
```

**Comment by purush7** [comment]
Hey @vijayprasanna13 , I have just seen the PR isn't merged before`v2.0.9`.

**Comment by purush7** [comment]
@mmack  and @mjazwinski you will see the changes in new release `v2.0.10`

**Comment by denisrudov** [comment]
@purush7  v2.1.0-beta.1 still has this issue

**Comment by vijayprasanna13** [comment]
@denisrudov can you confirm which version of Hasura you're using?

**Comment by Soviut** [comment]
I had the same issue, I was running the following (from `hasura version`)

```
INFO hasura cli                          version=v2.0.9
INFO hasura graphql engine               endpoint="http://localhost:8080/" version=v2.0.10
```

I tried upgrading the CLI to the latest beta but left the server version at `2.0.10` and still had the same issue.

```
INFO hasura cli                          version=v2.1.0-beta.1
INFO hasura graphql engine               endpoint="http://localhost:8080" version=v2.0.10
```

Finally, I updated to the latest `2.1.0-beta.2` in my docker compose file

```yaml
  graphql-engine:
    image: hasura/graphql-engine:v2.1.0-beta.2
```

And now it works; I can connect to the database with the following.

```
INFO hasura cli                          version=v2.1.0-beta.1
INFO hasura graphql engine               endpoint="http://localhost:8080" version=v2.1.0-beta.2
```
