### ISSUE TITLE
docs: GraphQL indentation broken on hasura.io

### ISSUE THREAD

**Issue by aedm** [hasura/graphql-engine#7449]
GraphQL code samples are currently not indented on `hasura.io`:

Example: https://hasura.io/docs/latest/graphql/core/databases/postgres/mutations/insert.html

![image](https://user-images.githubusercontent.com/7765984/130588441-8dbce041-33b2-466c-a70e-aa7250911beb.png)

**Comment by rikinsk** [comment]
Hey. Thanks for reporting this. We are tracking this issue [here](https://github.com/hasura/graphql-engine/issues/6767). Its quite odd actually as it seems to be only affecting our prod env. We'll try to fix this soon
