### ISSUE TITLE
server: determine the identity columns in BigQuery and MySQL

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#7450]
[Identity columns](https://en.wikipedia.org/wiki/Identity_column) are table fields whose values are generated by the database. We need to determine whether a column is identity or not from its metadata available from the database. If we can't determine then we should consider the column as not identity.

**Comment by plcplc** [comment]
Related: https://github.com/hasura/graphql-engine/issues/7557#issuecomment-920360031

**Comment by sassela** [comment]
@plcplc @rakeshkky has this been addressed now, by Philip's work on https://github.com/hasura/graphql-engine-mono/issues/2770 and/or https://github.com/hasura/graphql-engine-mono/issues/3500? Can we close it?

**Comment by rsd1122** [comment]
Closing this for now
