### ISSUE TITLE
[UI] broken input form on Firefox

### ISSUE THREAD

**Issue by atb00ker** [hasura/graphql-engine#7454]
I am not sure if Firefox is officially supported or not, but while everything is fine in chromium, I am seeing the following in FF:

![bug01](https://user-images.githubusercontent.com/24985760/130638843-1e382ae6-bb01-4e60-9665-9581a379264b.png)

Everything is working fine on `Hasura Cloud v2.0.7-cloud.2` but I can reproduce it on current master: https://github.com/hasura/graphql-engine/tree/8246bcc9d329ac9231af73799499ff37be5f4ec6

So, I assume this is a newly introduced change! :smile:

**Comment by vijayprasanna13** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/efc86d85244038019eadb2d816a30bd09fc8848e.
