### ISSUE TITLE
Better feedback in CLI when endpoint is malformed

### ISSUE THREAD

**Issue by eads** [hasura/graphql-engine#7456]
We used the full endpoint (including `v1/graphql` at the end) and got this message trying to run CLI commands:

```
FATA[0001] {
  "path": "$",
  "error": "resource does not exist",
  "code": "not-found"
}
```

It would be great if there were a more descriptive message about where the config is failing, and potentially simple fixes (like not including the end of the URL) in the error message.

**Comment by coco98** [comment]
Noted!

@rikinsk @scriptonist this is a pretty common/simple error to run into and having a default message that says the endpoint should not have the `v1/graphql` endpoint would be useful for the user.

**Comment by scriptonist** [comment]
In addition to this we should also make sure the error is more actionable/friendly when HGE itself is not reachable. The following is the current behaviour
```
$ hasura migrate apply
FATA[0001] version check: failed to get version from server: failed making version api call: Get "http://localhost:8080/v1/version": dial tcp 127.0.0.1:8080: connect: connection refused
```
This should ideally be “GraphQL engine not reachable” or something along the similar lines.

**Comment by purush7** [comment]
Closed this issue as the corresponding PR has been merged and the changes will be visible in the next release
