### ISSUE TITLE
Does dropping an index from cli has a bug?

### ISSUE THREAD

**Issue by motleydev** [hasura/graphql-engine#7465]
### Discussed in https://github.com/hasura/graphql-engine/discussions/7422

<div type='discussions-op-text'>

<sup>Originally posted by **nizamani** August 19, 2021</sup>
I created an index but when creating index I made a mistake and named that index wrong. When I try to delete that index from CLI I run into an issue. Issue is this:
-- I delete index Hasura CLI shows me a success message that index is deleted
-- after that I see index is still there, when I reload Hasura console index is still there
-- in migrations folder dropping index migration is created
I want to know if this is a bug if so how can I delete this index maybe through sql and later deleting that redundant migration?

Edit: Dropping index from SQL tab doesn't work either seems to be an issue with Hasura CLI when dropping an index</div>

**Comment by purush7** [comment]
BTW @EdNutting, Is this in  `MSSQl`?

**Comment by vijayprasanna13** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/9015b354ac556c18e4a3af03cdbd562e126ec797
