### ISSUE TITLE
server: failed to parse complicated queries with directive in query_collections

### ISSUE THREAD

**Issue by hgiasac** [hasura/graphql-engine#7467]
Hasura Version: 2.0.7

The server can't parse complicated GraphQL queries, although it's save successfully from the console. After reboot, HGE can't startup due to following error:

```
error applying metadata \n{\n  \"path\": \"$.args.metadata.query_collections[0].definition.queries[2].query\",\n  \"error\": \"parsing the graphql query failed\",\n  \"code\": \"parse-failed\"\n}
```

After troubleshot, I find several use cases that the HGE can't parse:
- Inline order by: 
```graphql
query GetNotifications($limit: Int, $offset: Int) {
  notification_desc(limit: $limit, offset: $offset, order_by: { created_at: desc}) {
    id
    headings(path: "en")
    contents(path: "en")
    send_after
    subject_id
    subject_type
  }
  
  notification_aggregate {
    aggregate {
      count
    }
  }
}
```

**Reproduce**

- Start Hasura CLI console to create metadata
- Create a REST endpoint using above queries
- Re-apply metadata after saved `query_collections.yaml`

**Comment by hgiasac** [comment]
After reproduced, the issue is on JSON directive. In the `query_collections.yaml` file, the query string can't be prettified too.

![Screenshot_20210828_121117](https://user-images.githubusercontent.com/1615675/131207082-c3f2d27b-33ed-4d00-ac5c-6d810b07fd89.jpg)

**Comment by 0x777** [comment]
@hgiasac Do you mean the directive `path` on `headings`/`contents` field?

**Comment by hgiasac** [comment]
@0x777 after reproduced again, The issue was gone after I deleted the blank line between 2 queries. 

So I think maybe the CLI send incorrect query format from the YAML file. 
Sorry for the confusion. This isn't graphql-engine issue. We can close this
