### ISSUE TITLE
v2  console doesn't show cross schema foreign key relationships

### ISSUE THREAD

**Issue by soundswarm** [hasura/graphql-engine#7477]
In v2.0.7
If I have a table books_schema.books and another one 
authors_schema.authors
  id, book_id
  
In the hasura console, in the books_schema.books table the relationship to authors_schema.authors does not show up.  
In v1.3.3 this relationship shows up.

I have tested this against the same database schema using v1.3.3 and v2.0.7.  I made up these table names as an example.  This is a big bug that makes v2.0.7 unusable.  

Thanks for fixing it.

**Comment by rikinsk** [comment]
@soundswarm while we fix this, as a workaround you could use the CLI/API to add these relationships as shown in the docs [here](https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/table-relationships/create.html#step-2-create-an-object-relationship)

**Comment by soundswarm** [comment]
@rikinsk Thanks.  Do you have an estimate of when it will be fixed?

**Comment by iykekings** [comment]
@soundswarm 
I tried reproducing this but it worked for me(see screenshot below)
<img width="628" alt="Screenshot 2021-09-01 at 23 11 26" src="https://user-images.githubusercontent.com/22247592/131752156-de19b517-a41a-4d73-a41d-2bc658f1a7b4.png">

- Do you have a foreign key constraint between the tables?
    -  If yes: 
            - Is the relationship suggestion missing in pages of both schemas or just one?
            - Can you share the SQL for creating the foreign key constraint?
    -  If no: We only show relationship suggestions if there's a foreign key constraint between both tables
- It will be very helpful to know the type of database you are using(Postgres/ SQL Server/ Citus/Big Query).
- Also I'd like to know the definition for both tables. sth like this: books_schema.books(id serial primary key, name text, author_id integer) and authros_schema.authors(id serial primary key, name text)

**Comment by soundswarm** [comment]
@iykekings 
Thanks for reaching out!!
I'm using Postgres 12 and made the tables in PGadmin and hasura. 

I made two databases which are identical.  I then created a hasura 2 server and a hasura 1.3.3 server that connects to their respective DB.  I then tracked all the tables in each schema.  You can see that hasura v2 doesn't recognize the FK relationship in the books table:

![image](https://user-images.githubusercontent.com/3759173/131756629-3cf0e134-3382-4c9c-afce-ae40317dc28c.png)


Here's a diagram of the tables
![image](https://user-images.githubusercontent.com/3759173/131760466-6203a0f1-5ea1-450b-b9ca-0b8305d45ffa.png)

Here's a backup of the DB made from pgadmin.  You can restore from this backup.  If that doesn't work, you see the diagram.
```--
-- PostgreSQL database dump
--

-- Dumped from database version 12.3
-- Dumped by pg_dump version 13.2

-- Started on 2021-09-01 18:55:28 EDT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 9 (class 2615 OID 159030)
-- Name: authors_schema; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA authors_schema;


ALTER SCHEMA authors_schema OWNER TO postgres;

--
-- TOC entry 7 (class 2615 OID 159031)
-- Name: books_schema; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA books_schema;


ALTER SCHEMA books_schema OWNER TO postgres;

--
-- TOC entry 2 (class 3079 OID 159033)
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- TOC entry 3246 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 205 (class 1259 OID 159071)
-- Name: authors; Type: TABLE; Schema: authors_schema; Owner: a
--

CREATE TABLE authors_schema.authors (
    id integer NOT NULL,
    book_id integer NOT NULL
);


ALTER TABLE authors_schema.authors OWNER TO a;

--
-- TOC entry 206 (class 1259 OID 159074)
-- Name: authors_id_seq; Type: SEQUENCE; Schema: authors_schema; Owner: a
--

CREATE SEQUENCE authors_schema.authors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE authors_schema.authors_id_seq OWNER TO a;

--
-- TOC entry 3247 (class 0 OID 0)
-- Dependencies: 206
-- Name: authors_id_seq; Type: SEQUENCE OWNED BY; Schema: authors_schema; Owner: a
--

ALTER SEQUENCE authors_schema.authors_id_seq OWNED BY authors_schema.authors.id;


--
-- TOC entry 207 (class 1259 OID 159076)
-- Name: books; Type: TABLE; Schema: books_schema; Owner: a
--

CREATE TABLE books_schema.books (
    id integer NOT NULL
);


ALTER TABLE books_schema.books OWNER TO a;

--
-- TOC entry 208 (class 1259 OID 159079)
-- Name: books_id_seq; Type: SEQUENCE; Schema: books_schema; Owner: a
--

CREATE SEQUENCE books_schema.books_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE books_schema.books_id_seq OWNER TO a;

--
-- TOC entry 3248 (class 0 OID 0)
-- Dependencies: 208
-- Name: books_id_seq; Type: SEQUENCE OWNED BY; Schema: books_schema; Owner: a
--

ALTER SEQUENCE books_schema.books_id_seq OWNED BY books_schema.books.id;


--
-- TOC entry 3104 (class 2604 OID 159153)
-- Name: authors id; Type: DEFAULT; Schema: authors_schema; Owner: a
--

ALTER TABLE ONLY authors_schema.authors ALTER COLUMN id SET DEFAULT nextval('authors_schema.authors_id_seq'::regclass);


--
-- TOC entry 3105 (class 2604 OID 159154)
-- Name: books id; Type: DEFAULT; Schema: books_schema; Owner: a
--

ALTER TABLE ONLY books_schema.books ALTER COLUMN id SET DEFAULT nextval('books_schema.books_id_seq'::regclass);


--
-- TOC entry 3237 (class 0 OID 159071)
-- Dependencies: 205
-- Data for Name: authors; Type: TABLE DATA; Schema: authors_schema; Owner: a
--

COPY authors_schema.authors (id, book_id) FROM stdin;
\.


--
-- TOC entry 3239 (class 0 OID 159076)
-- Dependencies: 207
-- Data for Name: books; Type: TABLE DATA; Schema: books_schema; Owner: a
--

COPY books_schema.books (id) FROM stdin;
\.


--
-- TOC entry 3249 (class 0 OID 0)
-- Dependencies: 206
-- Name: authors_id_seq; Type: SEQUENCE SET; Schema: authors_schema; Owner: a
--

SELECT pg_catalog.setval('authors_schema.authors_id_seq', 1, false);


--
-- TOC entry 3250 (class 0 OID 0)
-- Dependencies: 208
-- Name: books_id_seq; Type: SEQUENCE SET; Schema: books_schema; Owner: a
--

SELECT pg_catalog.setval('books_schema.books_id_seq', 1, false);


--
-- TOC entry 3107 (class 2606 OID 159156)
-- Name: authors authors_pkey; Type: CONSTRAINT; Schema: authors_schema; Owner: a
--

ALTER TABLE ONLY authors_schema.authors
    ADD CONSTRAINT authors_pkey PRIMARY KEY (id);


--
-- TOC entry 3109 (class 2606 OID 159158)
-- Name: books books_pkey; Type: CONSTRAINT; Schema: books_schema; Owner: a
--

ALTER TABLE ONLY books_schema.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- TOC entry 3110 (class 2606 OID 159182)
-- Name: authors authors_book_id_fkey; Type: FK CONSTRAINT; Schema: authors_schema; Owner: a
--

ALTER TABLE ONLY authors_schema.authors
    ADD CONSTRAINT authors_book_id_fkey FOREIGN KEY (book_id) REFERENCES books_schema.books(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


-- Completed on 2021-09-01 18:55:28 EDT

--
-- PostgreSQL database dump complete
--

```

**Comment by soundswarm** [comment]
Here are the relationships after I tracked all foreign key relationships:
![image](https://user-images.githubusercontent.com/3759173/131760754-7b8b13ac-064f-4d9e-8dde-de419a1f62fe.png)

**Comment by soundswarm** [comment]
The relationships show up correctly in the authors table:
![image](https://user-images.githubusercontent.com/3759173/131760866-b27c36f5-8965-4c52-abe8-f0322966800f.png)

**Comment by iykekings** [comment]
@soundswarm thank you so much...I'm looking into this right now

**Comment by iykekings** [comment]
@soundswarm thanks a lot for your help with this issue. I'm happy to tell you that it has been fixed here https://github.com/hasura/graphql-engine/commit/be6cd1131921c76312606d879dbd5a4d6fcfe0f1.
Should be available with next release.

**Comment by soundswarm** [comment]
thanks @iykekings !

**Comment by ns-ajalbani** [comment]
I get this error in 2.7.0
