### ISSUE TITLE
Hasura complains about stored proc being not trackable because it doesn't return table but it does return table.

### ISSUE THREAD

**Issue by timuckun** [hasura/graphql-engine#7480]
I am getting the following error when I attempt to track a function in postgres

 Inconsistent object: in function "api.cas": the function "api.cas" cannot be tracked for the following reasons: • the function does not return a "COMPOSITE" type • the function does not return a table

Here is the function signature.

CREATE FUNCTION api.cas(IN start_date timestamp without time zone, IN end_date timestamp without time zone, IN sec_code text)
    RETURNS TABLE (
        "timestamp" timestamp without time zone,
        security_code text,
        announcement_number integer,
        source text,
        announcement text
                  )
    LANGUAGE 'sql' STABLE

**Comment by leoalves** [comment]
Return table does not work with HASURA.  You need to create a dummy table and return a `SETOF tablename`.
**https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/custom-functions.html#track-sql-functions**
Check the notes in that link from the documentation

There is an open issue somewhere to allow return table but that is not available yet.

**Comment by clausMeko** [comment]
@leoalves 
> You need to create a dummy table and return a `SETOF tablename`.
Is that official? :rofl:
