### ISSUE TITLE
I don't see the "Custom GraphQL Root Fields", section in a table for this version.

### ISSUE THREAD

**Issue by Sami26912** [hasura/graphql-engine#7483]
I don't see the "Custom GraphQL Root Fields", section in a table for this version.

Is this something that has not been implemented yet or is it done differently now?

_Originally posted by @miguelocarvajal in https://github.com/hasura/graphql-engine/issues/6604#issuecomment-866153849_

**Comment by rikinsk** [comment]
@Sami26912 Can you confirm which database type and which exact version you are noticing this with?
