### ISSUE TITLE
Pod restarts after applying metadata on v2.0.7

### ISSUE THREAD

**Issue by vshelke** [hasura/graphql-engine#7487]
Hi,

We have v1.3.3 instance and recently planned to migrate to v2.0.7. according to docs no changes were required only we had large event log data which was dumped. after migration to v2.0.7 everything is normal and all the clients are also stable. The problem comes when i try to apply new metadata to the instance it always restarts the pod and gives a 502. In the hasura logs also no error is recorded only http-log which consists of the metadata request.

![Screenshot 2021-08-26 at 9 17 36 AM](https://user-images.githubusercontent.com/15365654/130897826-fd72a172-f7e9-4e27-8d65-45ae3c2054d3.png)

We have `HASURA_GRAPHQL_ENABLED_APIS=metadata,graphql,config` and `HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup,http-log,query-log,websocket-log,webhook-log`

Even after i change anything from hasura console the Pod restarts.

**Comment by scriptonist** [comment]
@vshelke can you look at your logs of graphql-engine by changing [`HASURA_GRAPHQL_LOG_LEVEL`](https://hasura.io/docs/latest/graphql/core/deployment/graphql-engine-flags/reference.html#server-flag-reference)  to "debug"

What probably is happening is, graphql-engine is restarting because of some reason. Therefore the API request that CLI sends to "apply" metadata is not succeeding and hence the "502 Bad Gateway". So additional logs from graphql-engine can help us figure out the root cause. Also, the nginx logs might uncover more details about these HTTP requests from CLI. Look for requests to `v1/metadata` /  `v1/query`.

**Comment by vshelke** [comment]
Hey @scriptonist thanks for the reply. I did turn on the above flag. So following are some of the steps i tried.
I downgraded back to 1.3.3 and then again updated to 2.0.7. Now the `hasura metadata apply` command works but i see a weird behaviour while updating metadata of some specific tables only, done from console. Like if i update any permissions in 'user' table the server restarts without any logs even in debug mode. But if its some other table like 'device' i change the permission then it gets updated. After doing a fresh install now the server restarts for some specific tables if metadata is changed.

I am attaching the logs generated while updating of a 'device' table because no logs are generated if i do changes for 'user' table.

![Screenshot 2021-09-03 at 7 14 20 PM](https://user-images.githubusercontent.com/15365654/132015378-2878caf2-7ca0-404d-a58f-af0eb83126d8.png)

After this the server restarts without creating any logs.

**Comment by vshelke** [comment]
@scriptonist any updates ?

**Comment by scriptonist** [comment]
@vshelke The console that you are using is started from the CLI ie using `hasura console` command? or the one the server serves?

**Comment by vshelke** [comment]
> @vshelke The console that you are using is started from the CLI ie using `hasura console` command? or the one the server serves?

@scriptonist the one server serves.

**Comment by vshelke** [comment]
@scriptonist do you have any updates ?

**Comment by scriptonist** [comment]
I'm out of ideas, @tirumaraiselvan can you help us here?

**Comment by vshelke** [comment]
Hey @scriptonist I reverted the instance to v1.3.3 and again updated to v2.0.9 and now everything is working as expected. No restarts are experienced now.
