### ISSUE TITLE
Trackable custom function shows as non-trackable in the console

### ISSUE THREAD

**Issue by lorenzo** [hasura/graphql-engine#7492]
I've created several functions of this style, which I have only managed to track via the metadata API, but that show as non-trackable in the hasura console.

Here's an example:

```
create table foos (id bigint primary key);
create or replace function search_foo(keyword text) returns public.foos as $$
    select * from foos;
$$ language sql stable;
```

Reload the database in Hasura, and visit the data tab. The function is now listed as "non-trackable".

The function can be tracked, though, using this metadata yaml:

```
function:
  name: search_foo
  schema: public
```

**Comment by tirumaraiselvan** [comment]
You are right. The console doesn't show non-SET OF as trackable. We will fix this.

**Comment by vijayprasanna13** [comment]
This should be fixed in https://github.com/hasura/graphql-engine/commit/bbed956137fee6eb7df0daef36ed8c33f47fae5b
