### ISSUE TITLE
Have a way to disable the auto-generated comments on tables and views

### ISSUE THREAD

**Issue by lorenzo** [hasura/graphql-engine#7496]
Hasura tries to be helpful when documenting the API it generates from the database. Unfortunately, it adds too much information sometimes, which leaks aspects of the database design that are often not relevant to the end consumer of the API.

Here's an example:

```sql
create schema foo;
create view foo.my_crazy_named_view_v2 as
   select 1::bigint as id, 'foo' as name;
comment on view foo.my_crazy_named_view_v2 is 'A nice comment about this';
```

Track the `foo.my_crazy_named_view_v2` and give it a root name like `MyFoos`
When inspecting the generated schema you will find the following comment on the `MyFoos` type:

```
A nice comment about this
columns and relationships of "foo.my_crazy_named_view_v2"
```

The second line was generated by hasura. I would like to have the following:

* A way to entirely disable generated comments, regardless of whether or not the relation has a comment already
* Refrain from appending the auto-generated comment if the relation already has a comment of its own.
* Have a way to add a comment in the metadata that is entirely independent of the comment in the database.

**Comment by daniel-chambers** [comment]
@tirumaraiselvan I'd like to clarify the specs for this new feature. I've had a look at it and formulated my own impression of what we'd want, but I'd like to hear your thoughts on it too.

I think we could add a new property to the `pg_track_table` and `pg_set_table_customization` APIs in the Table Config to capture the user's documentation preference as to table/view commenting. There would be two modes:
* Automatic - The documentation is generated by using the comment off the table in the database, OR if that does not exist, it uses `columns and relationships of <table>` (never both, which is the current behaviour). This would be the default.
* Explicit - This mode would take an additional property where the user sets the documentation text they'd like to appear. If they don't want any documentation, they could set an empty value here.

I think these two modes capture the requirements described in the OP.

### Open questions
1. The OP mentions "a way to _entirely_ disable generated comments...". Does this mean we also want some sort of data source-level setting that, if enabled, would cause Automatic mode tables to have no description?
2. I noticed in the code that fields that are satisfied by database functions have a similar documentation behaviour (ie drawing from the database comment + a hardcoded description HGE adds). Do we also want to provide same the documentation setting for these as well?
3. Would this change need to support all the different databases (eg. MSSQL, BigQuery, etc)?

**Comment by tirumaraiselvan** [comment]
I think we can just add this capability to `pg_set_table_customization`.

The automatic/default and explicit behaviours sounds good!

> 1. The OP mentions "a way to entirely disable generated comments...". Does this mean we also want some sort of data source-level setting that, if enabled, would cause Automatic mode tables to have no description?

We can do this later. Let's tackle the finer-grained customization for now.

> 2. I noticed in the code that fields that are satisfied by database functions have a similar documentation behaviour (ie drawing from the database comment + a hardcoded description HGE adds). Do we also want to provide same the documentation setting for these as well?

Yes, we should!

> 3. Would this change need to support all the different databases (eg. MSSQL, BigQuery, etc)?

Yes, it should!

**Comment by daniel-chambers** [comment]
> I think we can just add this capability to pg_set_table_customization.

Looks like `pg_track_table` and `pg_set_table_customization` share the `TableConfig` type where the new property would live. So if I add it to one we get it implicitly on the other. I think this makes sense, given you may wish to set the doco setting when initially tracking the table.

**Comment by lorenzo** [comment]
@daniel-chambers Will this include adding comments to the root field as well? I just noticed that I left that out in the original issue description

**Comment by daniel-chambers** [comment]
No, not currently. This only affects the description on the type, not the root field. For example:

The root fields (descriptions are generated):
<img src="https://user-images.githubusercontent.com/1214352/153596833-daba14c7-e47e-462a-9fc5-c33fb401ce0a.png" width="300" />
<img src="https://user-images.githubusercontent.com/1214352/153597059-fcf57fcd-d70a-46d9-b01a-158c91bee343.png" width="300" />

The type (description is from the new comment property in the table metadata):
<img src="https://user-images.githubusercontent.com/1214352/153597144-95c7c1df-7615-4979-abc0-d9ae0b010319.png" width="300" />

Changing the description on those root fields might need a bit more thought. There are three fields per table, we probably wouldn't want the same description applied to all three?

**Comment by lorenzo** [comment]
@daniel-chambers At this point I would prefer the same comment repeated than having the automatically generated comment, as it reveals implementation details of the database and look confusing to an API consumer.

But I agree that the right call is to think it through.

**Comment by daniel-chambers** [comment]
What if we extended the `custom_root_fields` configuration in `track_table` with the ability to set a comment for each root field?

For example:
```json
{
   "type": "pg_track_table",
   "args": {
     "source": "default",
     "table": "author",
     "configuration": {
        "custom_root_fields": {
            "select": {
               "name": "Authors",
               "comment": "Authors comment"
            },
            "select_by_pk": {
                "name": "Author",
                "comment": "Author comment"
            },
            "select_aggregate": {
                "name": "AuthorAggregate",
                "comment": "AuthorAggregate comment"
            },
            "insert": {
                "name": "AddAuthors",
                "comment": "AddAuthors comment"
            },
            "insert_one": {
                "name": "AddAuthor",
                "comment": "AddAuthor comment"
            },
            "update": {
                "name": "UpdateAuthors",
                "comment": "UpdateAuthors comment"
            },
            "update_by_pk": {
                "name": "UpdateAuthor",
                "comment": "UpdateAuthor comment"
            },
            "delete": {
                "name": "DeleteAuthors",
                "comment": "DeleteAuthors comment"
            },
            "delete_by_pk": {
                "name": "DeleteAuthor",
                "comment": "DeleteAuthor comment"
            }
        },
        "comment": "A comment for the type"
     }
   }
}
```

@tirumaraiselvan thoughts?

**Comment by lorenzo** [comment]
I like this idea @daniel-chambers

**Comment by sordina** [comment]
👍

**Comment by tirumaraiselvan** [comment]
@daniel-chambers That API makes sense to me but we need to make sure console can handle the same.

**Comment by lorenzo** [comment]
@daniel-chambers will comments for computed fields also be taken in consideration with your recent changes?

Take a look at this ticket to see how the auto-generated description remains for computed fields https://github.com/hasura/graphql-engine/issues/6256

**Comment by daniel-chambers** [comment]
@lorenzo Yes, we now use the comment set in the console as the GraphQL schema description! In fact, we have already shipped [these changes](https://github.com/hasura/graphql-engine/commit/2c7a4e3a1645fe38959c4ab83aad80ab17dacb9a) in `v2.3.0-beta.1`. 🙂

The [ability to set custom comments](https://github.com/hasura/graphql-engine/commit/0f9f2192a0b1d35ee513172bafbc60386d02329e) for table root fields (as discussed above) will ship in our next version. 🎉

The console support for this new stuff is a bit spotty at the moment, we've initially just focused on getting the functionality out as APIs, and we're currently looking into improvements in the console so you can edit these settings directly there as you'd expect.

**Comment by lorenzo** [comment]
Thanks so much @daniel-chambers !

**Comment by lorenzo** [comment]
Sorry to bother you again, @daniel-chambers. I wanted to consult with you if I should make another ticket for a similar problem, or just continue the conversation here.

The motivation behind this ticket is to avoid leaking implementation details about the internal database organization via auto-generated comments. I just realized that after your changes there are still a few places where this happens:

## `[RootField]_select_column`

it auto-generates the comment

```
select columns of table "my_foo_schema.my_table_with_aliased_graphql_name"
```

I suggest that it generates automatically

```
select internal fields for [RootField]
```

I think maintaining the `field` terminology in GraphQL is important, and not to mention that it is a database column, as it can get confusing for an external consumer of the API.

## `[RootField]_order_by`

```
Ordering options when selecting data from "my_foo_schema.my_table_with_aliased_graphql_name"
```

I suggest it generates

```
Ordering options when querying data from [RootField]
```

## `[RootField]_bool_exp`

It generates the automatic comment

```
Boolean expression to filter rows from the table "my_foo_schema.my_table_with_aliased_graphql_name". All fields are combined with a logical 'AND'.
```

My suggestion

```
Boolean expression to filter entries from [RootField]. All fields are combined with a logical 'AND'.
```

## `[RootField]_aggreagate`

Automatically generated:

```
aggregated selection of "marketplace.purchase"
```

my suggestion

```
aggregated selection of [RootField]
```

## Can I help?

Let me know if there is a way I can help with this. It's likely that I can help contribute part of the changes given some minor guidance.

**Comment by daniel-chambers** [comment]
Thanks @lorenzo, I like that idea personally, it will help keep things consistent. Talking about it in this issue is fine; this issue is currently capturing all aspects of this overall idea. :)

@tirumaraiselvan, what do you think?

**Comment by tirumaraiselvan** [comment]
@lorenzo What we consider "implementation details" is gonna vary a bit among different users. For example, someone might actually find more value with "select columns of table "my_foo_schema.my_table_with_aliased_graphql_name" instead of "select internal fields for [RootField]" 

For the time-being, we will suggest explicitly adding comments to remove extraneous information but we will keep the issue open for more user demand and feedback on what the default comment should be :)

**Comment by tirumaraiselvan** [comment]
Since this issue has become quite overloaded I would also suggest breaking out 2 new issues:

1. Disable auto-generated comments when tracking tables/views/functions
2. Change the default auto-generated comment

The current issue can probably be re-titled to the comment customization capabilities added by @daniel-chambers and closed out after its release.

**Comment by lorenzo** [comment]
@tirumaraiselvan so you are suggesting adding the ability to customize the comment for those types?

That would also work for me. Specially if it lets you change the name of the type itself.

My suggestion comes from the principle I suggested in the original ticket: use the auto generated text only if not explicitly changed. This principle is already followed in many other places. For example, if you change the root field name, the types I mentioned above also change correspondingly!

If you change the name of a root field to something else, how is it useful to have the old name appear somewhere else? If you wanted the default, you could just not change the default.

Do you have a suggestion on how the metadata could look like when customizing those automatically generated types?

**Comment by tirumaraiselvan** [comment]
> @tirumaraiselvan so you are suggesting adding the ability to customize the comment for those types?

@lorenzo Yes! I agree with your reasoning. If table names or root fields are changed then the comments should change accordingly by default. Secondly, other parts of the schema like input arguments should also have customizable comments. It will be nice to explicitly create issues for these. Another issue (which was one of the original intent for the issue) is the ability to not generate any comment per source/ per table, etc

**Comment by tirumaraiselvan** [comment]
I am going to close this issue as we have addressed large parts of it. I will create a separate issues for the remaining issues based off @lorenzo 's comments.

To summarize:

1. You can disable table/view type comments by giving empty value
2. You can disable root field comments like below:

![image](https://user-images.githubusercontent.com/8663570/161723505-521f4433-8144-4691-8474-e331e65b1006.png)

3. You can also customize comments for computed fields.
