### ISSUE TITLE
Add a flag to fail with error in hasura migrate apply with --all-databases

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#7499]
Instead of skipping and just displaying an error add a flag like `--fail-on-error` or `--do-not-skip` so the the command `hasura migrate apply --all-databases` exit with an error code this is specially helpful in CI/CD like in github actions where right now it shows all green even though a migration failed. The workaround could be to grep for error fail that way but would be nice to have it supported directly in the CLI.
Behavior should be exit 1 if migration fails for any of the databases
```
{"level":"error","msg":"skipping applying migrations for database default...
```

**Comment by scriptonist** [comment]
I'm of the opinion that this was overlooked in the original command. `hasura migrate apply --all-databases` should probably exit with a non zero exit code if the operation didn't succeed at least for one database.

**Comment by badrequest400** [comment]
We have also noticed this and is causing issues for us in that we need to check CI job output to check all is well after each release.
Also using Github Actions and we have noticed it when DB errors are thrown. Specifically a migration was adding a constraint that was already violated in the upstream DB.
A non-zero exit code emitted from the CLI would fix the issue for us!
