### ISSUE TITLE
Returning the event ID when creating scheduled event

### ISSUE THREAD

**Issue by ManUtopiK** [hasura/graphql-engine#7506]
It could be useful to return the ID of a scheduled event created via `v1/query`. So we can store this ID in a separate database and fetch all related event of this ID.

**Use case:**
Users of my app can create webhooks for particulars events. My app creates a scheduled event to trigger the webhook at these events. I would like to display all hdb_scheduled_event_invocation_logs of each user.

Currently, it's not possible to do that because I can't know which scheduled events is specific to one user. The `create_scheduled_event` only return `{"message": "success"}`.

With the ID of the event, I could store this ID in a separate table (user_id, event_id), and fetch all events for one user via a custom view and a relationship...

**Comment by BenoitRanque** [comment]
Posted then closed #7513 which is the same issue, and has mostly the same details. Thank you @ManUtopiK for pointing that out

**Comment by aaronhayes** [comment]
This has been discussed [previously](https://github.com/hasura/graphql-engine/issues/5025#issuecomment-647336495) 👍

**Comment by kolharsam** [comment]
This was resolved in bafefac. It should be out in the upcoming release(s).
