### ISSUE TITLE
endpoint with trailing slash causes issues with cli

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#751]
In `config.yaml` created by the cli, if `endpoint` url contains a trailing slash, the url that is built turns out to be `https://localhost:8080//v1/version`

We should be using the `net/url` package in building the urls everywhere.

@arvi3411301 Can you point to the places where endpoint is parsed and new urls are built?

**Comment by arshadkazmi42** [comment]
@shahidhk
I would like to work on  this.
 So we just need to change the `url` for this?

**Comment by ms10398** [comment]
I would like to work on it if it is possible @arvi3411301 can you guide me what needs to be changed as this would be my first PR for Hasura

**Comment by shahidhk** [comment]
@ms10398 False alarm, we were unable to reproduce this. Will re-open if it happens again.
