### ISSUE TITLE
delete_scheduled_event metadata api is not documented.

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#7512]
The `v1/metadata` endpoint supports a type `delete_scheduled_event`, yet this isn't documented in the [metadata docs](https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/scheduled-triggers.html)

**Comment by ManUtopiK** [comment]
Same issue here #7439

**Comment by BenoitRanque** [comment]
Closing in favor of #7439
