### ISSUE TITLE
metadata api: calls to create_scheduled_event should return event id.

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#7513]
Calls to `v1/metadata` which create events should return the created event's id, to facilitate possible deletion of those events.

## Example use case

Creating a scheduled event for later, and possibly deleting that event before it triggers.
This can easily be achieved by making a post request to `v1/metadata` to create a scheduled event, as is documented [here](https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/scheduled-triggers.html):
```http
POST /v1/metadata HTTP/1.1
Content-Type: application/json
X-Hasura-Role: admin

{
    "type" : "create_scheduled_event",
    "args" : {
        "webhook": "https://httpbin.org/post",
        "schedule_at": "2019-09-09T22:00:00Z",
        "payload": {
            "key1": "value1",
            "key2": "value2"
        },
        "headers" : [{
            "name":"header-key",
            "value":"header-value"
        }],
        "comment":"order-event-unique-id:0123456789"
    }
}
```
This will return a response that looks like this:
```json
{ "message": "success"}
```
If this response also included the ID of the created event, it would facilitate potential deletion of the event in the future.
(There is an undocumented type `delete_scheduled_event`, see #7512 )

Pre 2.0, it was possible to work around this by setting a unique ID as comment when creating the event, and using the metadata api to run raw SQL to delete that event. This is no longer possible on hasura cloud due to event metadata no longer living in the user's database.
```js
   {
      type: 'run_sql',
      args: {
        source: 'default',
        sql: `DELETE FROM hdb_catalog.hdb_scheduled_events WHERE COMMENT = '${comment}'`,
      },
    };
```

This is related to the internal ticket 565

**Comment by ManUtopiK** [comment]
I posted the same issue yesterday here #7506

**Comment by BenoitRanque** [comment]
Closing in favor of #7506
