### ISSUE TITLE
One to one relationships not suggested when using custom names for unique indexes

### ISSUE THREAD

**Issue by pnoyens** [hasura/graphql-engine#7525]
It has come to my attention that, while this was working in earlier versions of Hasura (at least until 1.3.3), one-to-one relations are not tracked in the expected way in current version(s) of Hasura. I'm running Hasura 2.0.8 for the moment.

At the owning side of the relation, it gets taken up in the right way, i.e. suggesting an object relationship from the owning side to the other.

From the perspective of the other side however, an array relationship is suggested. Clearly, this doesn't make a lot of sense and causes the automated GraphQL queries and mutations to have a rather weird syntax.

A concrete example in my case:

One-to-one relationship between table "users" and table "app_settings".
Users table has a foreign key constraint to app_settings, named "app_settings_id". This is made unique.

After applying all suggested trackings, a new relationship with name "users" will show up in table "app_settings". This used to be "user" in earlier versions, as expected.

Did I miss anything or is this genuine unexpected behavior?

**Comment by svenpeeters** [comment]
+1

**Comment by BenoitRanque** [comment]
I was unable to confirm what you are saying, in fact in 2.0.9 this schema produces what you describe as the behavior of previous versions
```sql
create table app_settings (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  setting_name TEXT,
  setting_value TEXT
);
create table app_users (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name TEXT,
  app_settings_id INT NOT NULL,
  FOREIGN KEY (app_settings_id) REFERENCES app_settings (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  UNIQUE(app_settings_id)
);
```

**Comment by BenoitRanque** [comment]
After some research, we were able to determine that the issue seemed to be caused by the ORM @pnoyens is using to manage his schema.

Specifically, this ORM will create unique indexes, and give them pseudorandom names. It seems that hasura has a naming scheme for unique indexes, if a unique index exists but does not follow the naming scheme the one to one relationship will not be suggested.

**Comment by BenoitRanque** [comment]
Created pull request #7529 to fix this issue. As it stands, the issue arises when the name of the unique key does not contain the string `_key`. This is most likely an oversight.
