### ISSUE TITLE
Metadata export fails with "error parsing metadata object: actions

### ISSUE THREAD

**Issue by raphaeltm** [hasura/graphql-engine#7554]
### Version Information

INFO hasura cli                                    version=v2.0.6
INFO hasura graphql engine                         endpoint="http://localhost:5000/" version=v2.0.6

### Environment

Ubuntu

### What is the expected behaviour?

The metadata should be written to yaml files.

### Keywords

failed to export metadata: cannot export actions from metadata: error parsing metadata object: actions
export failure metadata problem

### What is the current behaviour?

Hasura fails to export metadata completely using the CLI. If I make changes in the console, I expect those changes to be reflected in the metadata directory, but they aren't. When running `hasura metadata export --admin-secret=<password>` I keep getting:

> failed to export metadata: cannot export actions from metadata: error parsing metadata object: actions

I have tried adding actions (there were none), and deleting them to no avail. 

### How to reproduce the issue?

1. Not clear. It's only happening with one project.

### Screenshots or Screencast

<img width="1065" alt="Screen Shot 2021-09-15 at 00 55 56" src="https://user-images.githubusercontent.com/910895/133393680-17c21fd2-4a85-470f-bfa2-d32133a2cbd8.png">

**Comment by scriptonist** [comment]
@raphaeltm can you see if this is related to the following issues: 

- https://github.com/hasura/graphql-engine/issues/4953?
- https://github.com/vercel/pkg/issues/921

Basically, setting `NODE_OPTIONS` interferes with [vercel/pkg](https://github.com/vercel/pkg), which we use for packaging some parts of the CLI.

**Comment by raphaeltm** [comment]
@scriptonist Thanks for that! Now I just need to figure out why my `NODE_OPTIONS` are set... Everything works when I `unset` that env variable.
