### ISSUE TITLE
Document Hasura behind Traefik Reverse Proxy

### ISSUE THREAD

**Issue by theelderbeever** [hasura/graphql-engine#7571]
### Is your proposal related to a problem?

The docs located [here](https://hasura.io/docs/latest/graphql/core/deployment/enable-https.html) outline how to set up hasura behind `nginx` and `caddy` however, it would be really helpful if there was a `traefik` example as well. 

### Describe the solution you'd like

Clear documented example of utilizing an https terminating Traefik proxy config in front of hasura.

### Describe alternatives you've considered

Not using `hasura` because I am limited to exposing hasura through a traefik proxy in our environment.

### If the feature is approved, would you be willing to submit a PR?

I don't know the solution so I won't be able to.

**Comment by Azanul** [comment]
I want to give this a shot, please assign this to me.

**Comment by Azanul** [comment]
@theelderbeever I'm assuming you're looking for SSL/TLS as well using Traefik.

**Comment by Stefmore02** [comment]
@Azanul thank you for your interest! So far, nobody has raised a PR on this. Feel free to pick this up 👍
