### ISSUE TITLE
Code Exporter - Language Drop Menu Unaccessible in Chrome

### ISSUE THREAD

**Issue by frangucc** [hasura/graphql-engine#7573]
### Version Information
Occurs only on cloud console, not present in OSS / Cli. Could be replicated in `v2.1.1-cloud.1`

### Environment

Browser

### What is the expected behaviour?

Cannot use the drop menu on the Code Exporter window - it's covered by the actual code div.

### Keywords

Code, Code Exporter

### What is the current behaviour?

Cannot change language from Javascript to anything else because it cannot be access in the dom. 

### How to reproduce the issue?

Run a grapiql query
Select Code Exporter
Try to change the code language example

### Screenshots or Screencast

<img width="929" alt="Screenshot 2022-02-08 at 6 39 42 PM" src="https://user-images.githubusercontent.com/26903230/152993493-0ecfda03-9c79-4845-b736-39d3054801dc.png">

### Any possible solutions?

Seems like a front-end issue.

**Comment by abhi40308** [comment]
Hey @frangucc, I tried replicating this issue but couldn't. I'm using the latest image (v2.2.0) but tried on a few older ones too (2.0.8 & 2.0.9). [Screencast](https://www.loom.com/share/42ffdcc970e143f6a0741f1e0551ae2d) showing the language selector. I was able to select language dropdown in chrome, firefox, and safari. Please note that currently, we only support `JavaScript` and `TypeScript` in [language dropdown](https://github.com/hasura/graphql-engine/blob/master/console/src/components/Services/ApiExplorer/GraphiQLWrapper/snippets.ts#L109).

Please let us know if this issue still exists, and provide more details if possible.

**Comment by rikinsk** [comment]
I could reproduce this on `v2.1.1-cloud.1`

**Comment by abhi40308** [comment]
Thanks @rikinsk, was able to repro this, update the issue description accordingly.

**Comment by abhi40308** [comment]
This should be fixed now, should be available with the next cloud release.
