### ISSUE TITLE
Provide ARM based containers

### ISSUE THREAD

**Issue by XAMPPRocky** [hasura/graphql-engine#7577]
Hello, I was trying to run the Quickstart, but running it on an ARM M1 Mac it causes a QEMU segfault, meaning it can't be used at all. This is due to a bug in QEMU emulating `amd64` on ARM with docker-compose. This bug would addressed by providing ARM host containers in the Docker registry removing the need to emulate `amd64`.

```
$ docker pull hasura/graphql-engine
$ docker run hasura/graphql-engine
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

**Comment by glenno3891** [comment]
Would be great to see this sorted out. There are workarounds but really, these chips have been out for some time now.

**Comment by XAMPPRocky** [comment]
@glenno3891 What workarounds have you been using? My "workaround" is to just run it from an x86 machine and connect remotely from the ARM machine.

**Comment by glenno3891** [comment]
@XAMPPRocky I am using this image `fedormelexin/graphql-engine-arm64` which works well

**Comment by rikinsk** [comment]
Closing this in favour of #6337
