### ISSUE TITLE
CRON Trigger - Certificate Issue

### ISSUE THREAD

**Issue by jagijan** [hasura/graphql-engine#7586]
### Version Information
v2.0.8-cloud.3

Server Version:
CLI Version (for CLI related issue):

### Environment
Cloud

### What is the expected behaviour?
Expecting an option to specify self-signed certificate in Hasura so that CRON Trigger to Remote API with self-signed certificate work

Currently, when CRON trigger to Remote API with self-signed certificate in Hasura, I'm getting following error:
InternalException (HandshakeFailed (Error_Protocol (\\\"certificate rejected: [NameMismatch \\\\\\\"13.233.86.227\\\\\\\"]\\\",True,CertificateUnknown
Expecting an option to specify self-signed certificate via env var or any other means in Hasura so that certificate issue won't occur.
### Keywords

CRONTrigger, Certificate, SelfSigned,HandshakeFailed

### What is the current behaviour?
Getting HandshakeFailed error

Currently, when CRON trigger to Remote API with self-signed certificate in Hasura, I'm getting following error:
InternalException (HandshakeFailed (Error_Protocol (\\\"certificate rejected: [NameMismatch \\\\\\\"13.233.86.227\\\\\\\"]\\\",True,CertificateUnknown

### How to reproduce the issue?

1. Configure CRON Trigger to remote API (which is hosted as https using self-signed certificate) at any frequency

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/20244466/134321251-d013e2a0-541c-465f-9f1a-6275cbaa046d.png)

### Please provide any traces or logs that could help here.1

{
    "data": {
        "message": "\"HttpExceptionRequest Request {\\n  host                 = \\\"13.233.86.227\\\"\\n  port                 = 443\\n  secure               = True\\n  requestHeaders       = [(\\\"X-B3-TraceId\\\",\\\"123be4b9af9f1b64\\\"),(\\\"X-B3-SpanId\\\",\\\"db24708834d085af\\\"),(\\\"X-B3-ParentSpanId\\\",\\\"68d46f2d5c1b85d1\\\"),(\\\"Content-Type\\\",\\\"application/json\\\"),(\\\"User-Agent\\\",\\\"hasura-graphql-engine/v2.0.8-cloud.3\\\")]\\n  path                 = \\\"/api/requests/process\\\"\\n  queryString          = \\\"\\\"\\n  method               = \\\"POST\\\"\\n  proxy                = Nothing\\n  rawBody              = False\\n  redirectCount        = 10\\n  responseTimeout      = ResponseTimeoutMicro 60000000\\n  requestVersion       = HTTP/1.1\\n  proxySecureMode      = ProxySecureWithConnect\\n}\\n (InternalException (HandshakeFailed (Error_Protocol (\\\"certificate rejected: [NameMismatch \\\\\\\"13.233.86.227\\\\\\\"]\\\",True,CertificateUnknown))))\""
    },
    "version": "1",
    "type": "client_error"
}

### Can you identify the location in the source code where the problem exists?
No

**Comment by tirumaraiselvan** [comment]
Hi, you can add the URL that uses self-signed certificate in the TLS Allowlist (available in the console on the `Settings` page -> top-right gear icon)

![image](https://user-images.githubusercontent.com/8663570/134321615-2a910b6c-4e15-4287-86a6-0808e124186a.png)

**Comment by jagijan** [comment]
Thank you, just noticed the same. After adding the host to Insecure TLS Allow List configuration, the issue no longer exists.
