### ISSUE TITLE
Should auth0 JWT be RS256 instead of RS512?

### ISSUE THREAD

**Issue by chriship** [hasura/graphql-engine#7587]
I am receiving the JWSInvalidSignature error after I log in using auth0 and try to retrieve some elements from the db. I've been through all the settings and the only thing I can see which seems incorrect is the HASURA_GRAPHQL_JWT_SECRET which has been generated by https://hasura.io/jwt-config

The generated config has a signing algorithm of RS512 but in my auth0 dashboard, the signing algoithm is set to RS256 and I am unable to change. Could this be why I cam getting the error?

**Comment by srichakradhar** [comment]
@chriship Were you able to make it work? I see a similar issue with my app as well. Any inputs would be appreciative!
