### ISSUE TITLE
1.x site doc redirecting to 2.x

### ISSUE THREAD

**Issue by carlpaten** [hasura/graphql-engine#7589]
Visit https://hasura.io/docs/1.0/graphql/core/schema/index.html

Be redirected to https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/index.html

### Keywords

1.x 1.0 2.x 2.0 site doc docs documentation

**Comment by lilred** [comment]
Bug is still happening

**Comment by rikinsk** [comment]
This was closed by mistake earlier I believe, apologies. This is now fixed

**Comment by carlpaten** [comment]
Thank you for the return!
