### ISSUE TITLE
No scroll option while creating table

### ISSUE THREAD

**Issue by sarwan920** [hasura/graphql-engine#7599]
Hello, i am not sure if this is the right way to open an issue or bug report, but page of creating table doesn't have scroll, can't scroll down as you can see in the phot
![page](https://user-images.githubusercontent.com/47607107/135104820-c4b17a42-affd-439f-a85d-194540ca6f97.PNG)
o

**Comment by martin-hasura** [comment]
There was a client deployment problem earlier this morning on Cloud Console.
This should be fixed now, feel free to re-open if you're still running into any problems at all.
