### ISSUE TITLE
Unable to scroll to bottom to create rest endpoints.

### ISSUE THREAD

**Issue by niveditavijayvargiya** [hasura/graphql-engine#7615]
I want to create rest endpoint for my graph ql queries but when i move to rest end point screen, its not allowing to scroll down and i am unable to create rest end point.
If i see in developer tools it showing lots of errors.
![image](https://user-images.githubusercontent.com/89009416/135396548-a98a5b43-8f80-4c51-a60d-ad053581ecf2.png)

**Comment by rikinsk** [comment]
@niveditavijayvargiya Are you still noticing this?  We are not able to observe this ourselves so would like some more details if its still an issue for you cc: @wawhal

**Comment by niveditavijayvargiya** [comment]
Its working fine now.

**Comment by niveditavijayvargiya** [comment]
Its working fine now
