### ISSUE TITLE
restructure migrations documentation

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#766]
1. Use Hasura's migration tooling: Include one step for initializing from existing database. Add a small video.
2. Use your own database migration tooling: Add a small video.

**Comment by shahidhk** [comment]
Let's add detailed guides on environment promotion, dev->straging->prod kind of scenarios.

**Comment by shahidhk** [comment]
Rough structure:
- Using existing tool for Postgres migrations
  1. export
  2. import or curl
- Using Hasura for Posgres migrations
  1. Existing project
  2. New project

**Comment by shahidhk** [comment]
Use `pg_dump` with `docker exec` followed by `docker cp` for exporting current schema.

**Comment by shahidhk** [comment]
Comments from @coco98:

- Migrations & Metadata
- Add: Recovering from inconsistent migrations or metadata
- Migrations advanced use-cases
  - Auto-apply migrations/metadata when server starts
  - Writing migrations manually
  - Rolling back migrations
- Migrations reference
  - How do hasura migrations work
  - Migration files
  - Metadata file
