### ISSUE TITLE
update sample app: nextjs-postgres-graphql

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#7672]
### Is your proposal related to a problem?

The current [Next.js app](https://github.com/hasura/graphql-engine/tree/master/community/sample-apps) is built on older Next version (v9) and uses the now deprecated Apollo Boost module.

### Describe the solution you'd like

- Update to latest Next.js version (v11+)
- Switch to Apollo Client v3.

**Comment by amit-ksh** [comment]
Hey, I like to work on this issue.
