### ISSUE TITLE
support pg_dump for postgres 14

### ISSUE THREAD

**Issue by mdenson-dayspring** [hasura/graphql-engine#7676]
### Version Information

Server Version: 2.0.9
CLI Version (for CLI related issue):2.0.9

Running `hasura seed create ...` returns

```
FATA[0001] exporting seed data: pg_dump request: 500
{
  “path”: “$”,
  “error”: “error while executing pg_dump: pg_dump: error: server version: 14.0 (Debian 14.0-1.pgdg110+1); pg_dump version: 13.4 (Debian 13.4-1.pgdg100+1)\npg_dump: error: aborting because of server version mismatch\n”,
  “code”: “unexpected”
}
```

Downgrading the Postgres container to 13.4 fixes the problem.

**Comment by cindyloo** [comment]
is there an update on this? Still getting error `while executing pg_dump: pg_dump: error: server version: 14.1; pg_dump version: 13.4 (Debian 13.4-4.pgdg100+1)`

**Comment by dennislaviolette** [comment]
Hi Folks - This bug came across my desk. My team and I will take a closer look and get back to you soon.

**Comment by dventimihasura** [comment]
Hey, folks.  Maybe you already know this, but Heroku [announced](https://devcenter.heroku.com/changelog-items/2372) on March 23, 2022 generally availability of PostreSQL 14 and adds that _"For Hobby plans, all newly provisioned databases will default to PostgreSQL 14."_  

From the CLI you can create a PostgreSQL 13 database even in a Hobby plan with:

`heroku addons:create heroku-postgresql --version 13`

However, beginners won't know to do this.  Moreover, the Hasura Console won't do this if you use it to create a database.  The consequence is that newcomers trying out Hasura may run into a problem.  Just giving you a "heads up."

**Comment by ChrisCrosley** [comment]
the situation @dventimihasura describes seems to have happened to me. I have a Hasura project started in March working with no issues on Heroku using PG 13.6, started a new project 2 days ago and the Heroku database is using PG 14.2 and `hasura migrate create init` fails with `npg_dump: error: aborting because of server version mismatch`

**Comment by rikinsk** [comment]
Support for this is added in `v2.6.0-beta.2`

**Comment by jubalm** [comment]
Am I missing something?

```sh
INFO hasura cli                                    version=v2.6.0-beta.2
```

```json
{
  "path": "$",
  "error": "error while executing pg_dump: pg_dump: error: server version: 14.2; pg_dump version: 13.6 (Ubuntu 13.6-1.pgdg18.04+1)\npg_dump: error: aborting because of server version mismatch\n",
  "code": "unexpected"
}
```

**Comment by scriptnull** [comment]
Hi @jubalm, I notice that you have upgraded the CLI version to `v2.6.0-beta.2`. We will need the graphql-engine server to be upgraded to `v2.6.0-beta.2` in order to make use of the released fix. Could you try doing that?

**Comment by jubalm** [comment]
> Support for this is added in `v2.6.0-beta.2`



> Hi @jubalm, I notice that you have upgraded the CLI version to `v2.6.0-beta.2`. We will need the graphql-engine server to be upgraded to `v2.6.0-beta.2` in order to make use of the released fix. Could you try doing that?

indeed needed to upgrade graphql-engine for this to work. thanks for the quick response!

**Comment by matlin** [comment]
We're running v2.6.1-cloud.1 and it seems our pg_dump is still set to 13.6. Is this expected?

```
{
	"path": "$",
	"error": "error while executing pg_dump: pg_dump: error: server version: 14.1; pg_dump version: 13.6 (Ubuntu 13.6-1.pgdg18.04+1)\npg_dump: error: aborting because of server version mismatch\n",
	"code": "unexpected"
}
```

**Comment by Edwin824** [comment]
Hi I am also facing the issue when trying to create a migration file.  FATA[0005] cannot fetch schema dump: pg_dump request: 500
{
  "path": "$",
  "error": "error while executing pg_dump: pg_dump: error: server version: 14.2 (Ubuntu 14.2-1.pgdg20.04+1+b1); pg_dump version: 13.7 (Ubuntu 13.7-1.pgdg18.04+1)\npg_dump: error: aborting because of server version mismatch\n",
  "code": "unexpected"
}

**Comment by lti-equipamiento** [comment]
Please fix this

**Comment by prince-bansal** [comment]
Any updates on this? I'm still getting this issue after running the graphql engine at v2.6.0-beta.2.

**Comment by prince-bansal** [comment]
I'm still getting the same issue. 
I'm running this command. ```hasura migrate create init --from-server --endpoint hasura-end-point --admin-secret hasura-secret```


<img width="1351" alt="image" src="https://github.com/user-attachments/assets/05f14cb6-2319-4a17-b03f-37a7a6cc55b1">

Docker containers:

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/8640ba08-c960-4749-b5de-14c2e9d84814">
