### ISSUE TITLE
opentelemetry support

### ISSUE THREAD

**Issue by bbigras** [hasura/graphql-engine#7683]
I'm using opentelemetry everywhere, and maybe it could be nice if hasura would send performance traces to opentelemetry

### Is your proposal related to a problem?

No, unless maybe to spot slow queries. It would be more to have a big picture of the time it takes for an operation in my systems.

### Describe the solution you'd like

- get trace id from headers
- create spans
- send spans to opentelemetry

### Describe alternatives you've considered

Maybe it doesn't really matter to have it supported in Hasura. Maybe tracing the http request to Hasura on my side is enough.

### If the feature is approved, would you be willing to submit a PR?

I don't know Haskell.

**Comment by 24601** [comment]
Well, I do think it does matter for situations like Hasura Actions, Events, and remote schemas because a major component of OpenTelemetry is Context Propogation/Span Correlation, and if the HTTP header coming *into* a Hasura Action/Event is not forwarded to the handler (or an Event, or to a Remote Schema), the whole point of breaking into the black box is lost....

**Comment by luizjunior05** [comment]
> Thank you for submitting this issue. Support for OpenTelemetry traces is on our roadmap but not scheduled yet. Will update when we have more information.

Where can i see the roadmap?

**Comment by xsoheilalizadeh** [comment]
It would be very useful to have OpenTelemetry support in Hasura, please prioritize it if possible.

**Comment by xsoheilalizadeh** [comment]
Hi @rishi-div, could you please give us an update on this?

**Comment by prashant-shahi** [comment]
OpenTelemetry support would be very useful to get more visibility on the internal operations and its performance.

@rishi-div Any information on the same would be very much appreciated.

**Comment by rishi-div** [comment]
Hi everyone, 

Thank you for your comments. 

We have released support for OpenTelemetry traces in Hasura Cloud:
https://hasura.io/docs/latest/observability/integrations/opentelemetry/

Support for traces is also coming soon to Hasura Enterprise. There will be an easy way to try the feature in Hasura Enterprise trials soon after that.

We are also looking to publish a public facing roadmap in the near-future.

**Comment by raweber42** [comment]
Hey @rsd1122 are there any news on the public facing roadmap? :)
