### ISSUE TITLE
graphql-ws WebSocket connection closed with `1000: Normal Closure` on errors

### ISSUE THREAD

**Issue by enisdenjo** [hasura/graphql-engine#7696]
### Version Information

Server Version: Hasura Cloud

### Environment

Cloud

### Keywords

graphql-ws,normal clousure,errors,subscriptions,websocket

### What is the expected behaviour?

Failing connections close with an error close code (>1000).

### What is the current behaviour?

Failing connections close with a `1000: Normal Closure`. [The close code 1000 is used for when the connection successfully completed the purpose for which it was created.](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent/code)

### How to reproduce the issue?

1. Create a project on [Hasura Cloud](https://cloud.hasura.io/projects) or use mine https://engaging-filly-31.hasura.app/v1/graphql
2. Copy GraphQL API URL
3. Connect using `graphql-ws` without setting the authorization header (you can use the [GraphiQL ❤️ graphql-ws gist](https://gist.github.com/enisdenjo/a68312878fdc4df299cb0433c60c1dea))
4. `Connection Closed: 1000 {"server_error_msg":"4400: Connection initialization failed: x-hasura-admin-secret/x-hasura-access-key required, but not fo...`

### Screenshots or Screencast

<img width="1138" alt="Screenshot 2021-10-18 at 13 46 07" src="https://user-images.githubusercontent.com/11807600/137724643-88c08742-fcee-4ce7-95ff-8c9637006b67.png">

### Any possible solutions?

Use **literally** any other code instead of the `1000: Normal Closure`. [I suggest using `4401: Unauthorized` to be in par with the GraphQL over WebSocket protocol.](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#subscribe)

### Additional info

Causes: https://github.com/enisdenjo/graphql-ws/issues/244.

### Can you identify the location in the source code where the problem exists?

No.

### If the bug is confirmed, would you be willing to submit a PR?

No, I am not familiar with Haskell.

**Comment by paritosh-08** [comment]
Closed  via https://github.com/hasura/graphql-engine/commit/a886da2f217e0e77501a35a08ae54a3d3f91345e
