### ISSUE TITLE
Wrong implementation of GraphQL over WebSocket `Error` message

### ISSUE THREAD

**Issue by enisdenjo** [hasura/graphql-engine#7706]
### Version Information

Server Version: Hasura Cloud

### Environment

Cloud

### Keywords

graphql-ws,messages,error,websocket

### What is the current behaviour?

The error message provides an object with the `errors` field set to an array of `GraphQLError`s.
```json
{
  "type": "error",
  "id": "1",
  "payload": {
    "errors": [
      {
        "extensions": {
          "path": "$.selectionSet.somefield",
          "code": "validation-failed"
        },
        "message": "field \"somefield\" not found in type: 'query_root'"
      }
    ]
  }
}
```

### What is the expected behaviour?

The error message implements the [GraphQL over WebSocket `Error` message](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#error).
```diff
{
  "type": "error",
  "id": "1",
- "payload": {
-   "errors": [
-     {
-       "extensions": {
-         "path": "$.selectionSet.somefield",
-         "code": "validation-failed"
-       },
-       "message": "field \"somefield\" not found in type: 'query_root'"
-     }
-   ]
- }
+ "payload": [
+   {
+     "extensions": {
+       "path": "$.selectionSet.somefield",
+       "code": "validation-failed"
+     },
+     "message": "field \"somefield\" not found in type: 'query_root'"
+   }
+ ]
}
```

### How to reproduce the issue?

1. Create a project on [Hasura Cloud](https://cloud.hasura.io/projects) or use mine https://engaging-filly-31.hasura.app/v1/graphql
2. Copy GraphQL API URL
3. Connect using `graphql-ws` without setting the authorization header (you can use the [GraphiQL ❤️ graphql-ws gist](https://gist.github.com/enisdenjo/a68312878fdc4df299cb0433c60c1dea))
4. Execute a query with invalid/missing fields
5. `Connection Closed: 4400` because the `Error` message is malformed

### Screenshots or Screencast

<img width="1434" alt="Screenshot 2021-10-20 at 15 02 54" src="https://user-images.githubusercontent.com/11807600/138098207-a27911b1-5413-4b9b-a0a7-0f426b208595.png">

### Any possible solutions?

1. **(recommended)** Implement the [GraphQL over WebSocket `Error` message](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#error) when sending `GraphQLError`s as presented above.
2. Use the [`Next` message](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#next) to transmit an error as a part of the [`GraphQL's ExecutionResult`](https://github.com/graphql/graphql-js/blob/4c9bf037ed32b8a9bd2215b264c8b89e1f6c86c2/src/execution/execute.ts#L120-L134) like this:

```diff
{
- "type": "error",
+ "type": "next",
  "id": "1",
  "payload": {
    "errors": [
      {
        "extensions": {
          "path": "$.selectionSet.somefield",
          "code": "validation-failed"
        },
        "message": "field \"somefield\" not found in type: 'query_root'"
      }
    ]
  }
}
```

### Additional info

This issue is quite critical for clients using [`graphql-ws`](https://github.com/enisdenjo/graphql-ws) because malformed messages result in immediate connection termination, [as per the GraphQL over WebSocket Protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#invalid-message).

### Can you identify the location in the source code where the problem exists?

No.

### If the bug is confirmed, would you be willing to submit a PR?

No, I am not familiar with Haskell.

**Comment by paritosh-08** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/a886da2f217e0e77501a35a08ae54a3d3f91345e
