### ISSUE TITLE
CLI does not return non-zero on failure

### ISSUE THREAD

**Issue by jsmusgrave** [hasura/graphql-engine#7707]
### Version Information

Server Version: v2.0.8-cloud.3
CLI Version (for CLI related issue): v2.0.9

### Environment

Cloud

### What is the expected behaviour?

On a failure, the shell should return a non-zero status code so automation can tell it failed.  This prevents CI pipelines from being able to notice failuress.  Ex. below.

```shell
 hasura migrate apply             
✔ default
ERRO skipping applying migrations on database default, encountered:                                                                                                                                                                                    
{
...
echo $?
127
```

### Keywords

CLI, CI

### What is the current behaviour?

Failures return a zero status code.

```shell
 hasura migrate apply             
✔ default
ERRO skipping applying migrations on database default, encountered:                                                                                                                                                                                    
{
...
echo $?
0
```

### How to reproduce the issue?

1. Apply a migration that fails
2. Look at the status code

### Screenshots or Screencast

N/A

### Please provide any traces or logs that could help here.

N/A

### Any possible solutions?

Use the standard expected of status codes.  See examples: 
https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html#:~:text=A%20non%2Dzero%20exit%20status,N%20as%20the%20exit%20status.

### Can you identify the location in the source code where the problem exists?

No.

### If the bug is confirmed, would you be willing to submit a PR?

Perhaps, someday.

**Comment by scriptonist** [comment]
@jsmusgrave Thanks for reporting this issue. We had this reported in https://github.com/hasura/graphql-engine/issues/7629 and was fixed in https://github.com/hasura/graphql-engine/commit/ffce0d266bc23a5142066f6b7fafc3105569bd32
