### ISSUE TITLE
Broken images in README.md

### ISSUE THREAD

**Issue by Utkarsh299-tech** [hasura/graphql-engine#7748]
### Version Information

Server Version:
CLI Version (for CLI related issue):

### What is the current behaviour?

Two images are broken in [README.md](https://github.com/hasura/graphql-engine/edit/master/README.md) file

### Screenshots or Screencast

![Screenshot (384)](https://user-images.githubusercontent.com/60184229/139596303-5f39409a-b6e5-4f01-8e9a-dbb1c2a854f3.png)

### Any possible solutions?

Images can be fixed by providing the correct file path of them in lines no 190 and 191.

### Can you identify the location in the source code where the problem exists?

Lines no 190 and 191 in [README.md](https://github.com/hasura/graphql-engine/edit/master/README.md) file

### If the bug is confirmed, would you be willing to submit a PR?

Yes, I would be happy to do so.

**Comment by rikinsk** [comment]
This is fixed now. Thanks for reporting!
