### ISSUE TITLE
server/tests: `RemoteResourceSpec` equivalent

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#7756]
Implement the equivalent of RemoteResourceSpec in the Haskell integration test suite, executable locally and run in CI.

https://github.com/hasura/graphql-engine/blob/master/server/tests/integration/Tests/RemoteSourceSpec.hs

**Comment by sassela** [comment]
Whoops, I meant to link to them in this issue: https://github.com/hasura/graphql-engine/blob/master/server/tests/integration/Tests/RemoteSourceSpec.hs

**Comment by chrisdone** [comment]
OK, this will be an interesting one to explore. Thinking aloud...

We could spin up two hasura servers that just look at the same database, or separate ones. So perhaps the `SpecWith` may contain e.g. two `Server`s, e.g.

```haskell
-- | A state that's passed to all tests.
data State = State
  { server1 :: Server
  , server2 :: Server
  }
```

Current tests look like this:

```haskell
spec :: SpecWith State
spec =
  Feature.feature
    Feature.Feature
      { Feature.backends =
          [ Feature.Backend
              { name = "MySQL",
                setup = mysqlSetup,
                teardown = mysqlTeardown
              },
            Feature.Backend
              { name = "PostgreSQL",
                setup = postgresSetup,
                teardown = postgresTeardown
              }
          ],
        Feature.tests = tests
      }
```

And the tests are setup like this:

```haskell
main :: IO ()
main =
  hspec $
    aroundAllWith (const . bracket setupState teardownState) $ do
      describe "ServiceLiveness" ServiceLivenessSpec.spec
      describe "BasicFields" BasicFieldsSpec.spec
      describe "Ordering" OrderingSpec.spec
```

* I can imagine haing another aroundAllWith, that would spin up two servers.
* We could possibly re-use the "Feature" thing. Or not. 
* But I think the `SpecWith State` can be re-usable and the general layout of the existing tests. 
* Just that one backend's metadata will have a remote specified in it referring to the other server. So there is an order dependency, but not one that's hard to setup.

I believe we can setup remotes just with the yaml metadata we're already using. The [one linked](https://github.com/hasura/graphql-engine/blob/master/server/tests/integration/Tests/RemoteSourceSpec.hs) does seem unnecessarily low level. I can see why Vamshi might be concerned about that one.

Going forward, I think I can put together a simple test of remotes between postgres and postgres and go from there.

**Comment by sassela** [comment]
@jkachmar 's team has much more experience with remote joins testing that I do. Tagging FYI and in case they have any feedback

**Comment by chrisdone** [comment]
Should I take the approach I described and see how it looks?

**Comment by chrisdone** [comment]
Vamshi wrote up some notes here: https://gist.github.com/0x777/4aa23535591a099b63c50e3f66b7ddb2

Copying here:

> Hey folks, regarding remote relationships related testing, after the
> discussions we've had so far, I [refactored the tests](https://github.com/hasura/graphql-engine-mono/tree/vamshi/generalized-joins-from-remote-schema/server/tests-hspec/RemoteRelationship) to more or less confirm to
> the principles of existing hspec tests.
> 
> Setup and tests for x-to-db-object-relationship and x-to-db-array-relationship
> are defined in their respective modules. This differs from existing tests as follows:
> 
> 1. When 'x' is a remote schema, the setup of the remote schema unfortunately
>    does not fully happen in the Haskell module. We need not have introduced
>    this limitation if we used graphql-engine as a remote schema but I don't
>    think it is a good idea. We want to test the interaction of these features
>    with interfaces types, object types and union types and it is hard to get to
>    such desired schema if graphql-engine is used as a remote schema - for
>    example, no configuration of graphql-engine currently generates union types
>    in the GraphQL schema that it exposes.
> 
>    That being said, the tests aren't written assuming a global remote schema
>    server which would have made the tests very sensitive to changes. They are
>    instead neatly [isolated by endpoints](https://github.com/hasura/graphql-engine-mono/blob/vamshi/generalized-joins-from-remote-schema/server/tests-hspec-services/remote-schema/server.py):
> 
>    1. '/remote_relationship_rs_to_db_object' exposes a GraphQL API against
>       which x-to-db-object-relationships are tested.
> 
>    1. '/remote_relationship_rs_to_db_array' exposes a GraphQL API against
>       which x-to-db-array-relationships are tested.
> 
> 1. The setup of the [tests are parameterized](https://github.com/hasura/graphql-engine-mono/blob/vamshi/generalized-joins-from-remote-schema/server/tests-hspec/RemoteRelationship/XToDBObjectRelationship.hs#L155) to make it easy to define several
>    x-to-x setups. This is done to reduce boilerplate. I'm not sure what the
>    right approach here is.
> 
> Some open questions:
> 
> 1. The choice of using Python for writing the remote schema is purely
>    arbitrary. I don't have a strong opinion about this. I think a typed
>    language would make more sense.
> 
> 1. Whether to merge 'XToDBObjectRelationship' and 'ObjectRelationshipsSpec'
>    module. In a way db-to-db remote relationships are a more restricted
>    variant of local db relationships. They differ in the following ways:
> 
>    1. remote db-to-db cannot be configured using foreign key constraints.
>       'manual_configuration' is the only option.
> 
>    1. remote db-to-db relationships cannot be used in 'where' and
>       'order_by' APIs. For example,
>       ```graphql
>       author (where: {article: {name: {_eq: "something"}}}) {
>         id
>       }
>       ```
>       and
>       ```graphql
>       author (order_by: {article: {name: asc}}) {
>         id
>       }
>       ```
>       are not valid when 'article' is a remote db-to-db relationship
> 
>    I'll leave this to your judgment
> 
> My overall experience with the hspec tests has been great so far. We'll
> need to improve on these fronts:
> 
> 1. Show a diff output when the expected response does not match the actual
>    response.
> 
> 1. If there are errors in the setup of a test (happens when writing new tests),
>    the test output wouldn't show this error but the error that would happen
>    during the teardown (which is guaranteed to happen as the setup did not
>    finish successfully). This can be debugged currently by enabling debug logs
>    but can easily be improved, maybe Python exception messages style - "when
>    handling exception 'x', another exception 'y' was raised"

**Comment by nicuveo** [comment]
FWIW: I started a quick experiment to use our graphql parsers to define a remote schema in the hspec-tests. It's a very rough draft, but could be a starting point: https://github.com/hasura/graphql-engine-mono/pull/3426

**Comment by sassela** [comment]
Update: I can see Antoine you're [more actively working on this now](https://github.com/hasura/graphql-engine-mono/pull/3567) so FTR it seems to make sense to take this off of FPCo's plate, but keep them involved as code reviewers for changes to the test harness.

let me know what you think @nicuveo @qrilka

**Comment by nicuveo** [comment]
Sounds good, yeah! I've extracted the core changes to #3573.

**Comment by qrilka** [comment]
@nicuveo I guess you wanted to post https://github.com/hasura/graphql-engine-mono/pull/3573 instead?

**Comment by sassela** [comment]
addressed at https://github.com/hasura/graphql-engine-mono/pull/3573
