### ISSUE TITLE
server/tests: `TestGraphQLQueryBasicMySQL` equivalent

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#7757]
Implement the equivalent of `TestGraphQLQueryBasicMySQL` in the Haskell integration test suite

**Comment by chrisdone** [comment]
I think this one is done or needs validating as done. I copied all the python yaml tests into the hspec suite. Should I do a write-up or something for double accounting purposes?

**Comment by sassela** [comment]
@chrisdone if you have the list pytest -> hspec tests written somewhere already, please share it, otherwise I'll do a check this morning and confirm my understanding here.

**Comment by sassela** [comment]
@chrisdone Grouped by the hspec suite, checklist items are the corresponding pytest AFAICT

## BasicFieldsSpec
- [x] '/basic.yaml' # Author fields
- [x] '/select_query_author.yaml' # Use operationName
- [ ] '/nested_select_query_deep.yaml'
- [ ] '/select_query_author_quoted_col.yaml'
- [x] '/select_query_non_tracked_table.yaml' # Missing table
- [x] '/select_query_author_col_not_present_err.yaml' # Missing field
## LimitOffsetSpec
- [ ] '/offset_1_limit_2.yaml'
- [x] '/offset_2_limit_1.yaml' # order descending, offset 2, limit 1
- [x] '/select_query_author_limit.yaml' # limit 1
- [ ] '/select_query_author_offset.yaml'
- [ ] '/select_query_author_limit_offset.yaml'

## WhereSpec
- [x] '/select_query_author_where.yaml' # Where id=1

## ArrayRelationShipSpec
- [x] '/nested_select_where_query_author_article.yaml' # Select an author and one of their articles

## OrderingSpec
- [x] '/select_query_author_order_by.yaml' (order by int)
- [x] '/select_query_author_order_by.yaml' (order by text)

## DirectivesSpec
- [ ] '/select_query_author_with_skip_directive.yaml'
- [x] '/select_query_author_with_skip_include_directive.yaml' # DirectivesSpec
- [ ] '/select_query_author_with_wrong_directive_err.yaml'

## ViewSpec
- [x] '/query_search_author_view.yaml' # Query that a view works properly

**Comment by chrisdone** [comment]
PR  ready for review https://github.com/hasura/graphql-engine-mono/pull/3271
