### ISSUE TITLE
server/tests: `TestGraphQLQueryBasicCommon` equivalent

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#7758]
Implement the equivalent of `TestGraphQLQueryBasicCommon` ([pytests are here](https://github.com/hasura/graphql-engine/blob/369d1ab2f119634b0e27e9ed353fa3d08c22d3fb/server/tests-py/test_graphql_queries.py#L251)) in the Haskell integration test suite.

**Comment by sassela** [comment]
Writing up following a chat with @psibi.


This issue involves more of an audit of existing specs than I made clear in the original description, so I'm sorry about any duplicated effort that followed as a result.

Before porting over any more specs from pytest -> hspec, let's please clarify the state of work so far on [BasicCommon tests](#basiccommon-pytests):

1. which pytests tests have been ported to hspec for all backends*?
1. which pytests have been ported to hspec as part of https://github.com/hasura/graphql-engine/issues/7757?
1. which pytests have been ported to hspec for a single backend, but which we can't test in the same way across all backends for any reason?
1. which pytests from BasicCommon have not yet been ported to hspec at all?


*all backends = Postgres, Citus, BigQuery, SQL Server

### `BasicCommon` pytests
```
test_select_query_author
test_select_query_author_v1
test_select_query_author_quoted_col
test_select_query_author_with_skip_directive
test_select_query_author_with_include_directive
test_select_query_author_with_skip_include_directive
test_select_query_author_with_wrong_directive_err
test_select_query_where
test_nested_select_query_article_author
test_nested_select_query_deep
test_nested_select_query_where
test_nested_select_query_where_on_relationship
test_select_query_non_tracked_table
test_select_query_col_not_present_err
test_select_query_multiple_columns_arr_fkey
test_select_query_multiple_columns_obj_fkey
test_select_query_author_pk
test_select_query_author_pk_null
test_select_placeholder_err
```

**Comment by psibi** [comment]
I have done an initial analysis of the existing hspec test suite: https://gist.github.com/psibi/e3c266c62170cd13aa4724794cc66102

**Comment by psibi** [comment]
Based on the above gist, I'm summarizing things here. These are the haskell spec that has been implemented which are part of TestGraphQLQueryBasicCommon (from python):

- BasicFieldsSpec: 3
- DirectiveSpec: 8
- NestedRelationshipsspec: 1

The above haskell suite contains the implementation of the following yamls:

- graphql_query/basic/select_query_author.yaml
- graphql_query/basic/select_query_author_col_not_present_err.yaml
- graphql_query/basic/select_query_non_tracked_table_err.yaml
- graphql_query/basic/select_query_author_skip_include_directives.yaml
- graphql_query/basic/select_query_author_skip_directive.yaml
- graphql_query/basic/select_query_author_wrong_directive_err.yaml
- graphql_query/basic/nested_select_query_deep.yaml

These are the additional tests that are not yet implemented from the TestGraphQLQueryBasicCommon:

- select_query_author_where.yaml
- select_query_author_v1alpha1.yaml
- select_query_author_include_directive.yaml
- select_query_author_col_quoted.yaml
- select_query_author_by_pkey.yaml
- select_query_author_by_pkey_null.yaml
- select_placeholder_err.yaml
- nested_select_where_query_author_article.yaml
- nested_select_query_article_author.yaml
- nested_select_query_article_author_where_on_relationship.yaml

We also need to ensure that the above test suite which has been already been implemented - is done for all the three backends of TestGraphQLQueryBasicCommon (right now that's not the case).

**Comment by sassela** [comment]
@psibi this list LGTM, thanks again for putting it together. For easier accounting next time, would you consider something like adding a code comment for each hspec referencing the pytest it's replacing? Or something more elegant if you can think of it. I think that'd make it easier to remove the corresponding pytests wholesale after this work is done.

**Comment by psibi** [comment]
@sassela I have a PR ready locally which does these things:

- Expands the testing backends of the already implemented tests from `TestGraphQLBasicCommon`
- Implement all the missing haskell equivalent for `TestGraphQLBasicCommon`
- Add a comment on each `it` blocks referencing the equivalent pytest. (Note that this has been only done for the one in `TestGraphQLBasicCommon now). We should do it for the other ones too, probably in a separate PR.

This PR is also implemented on top of the primitive MR which I have already created. I'm delaying opening it until that one is merged, so that the PR review is much easier. (But let me know if you want me to open it anyway).

**Comment by sassela** [comment]
@psibi thanks for the update! Please go ahead and open the tests PR and consider using https://github.com/hasura/graphql-engine-mono/pull/4263 as the base branch (rather than `master`) for a clearer diff. The base branch should update automatically to master once the PR's merged.

In any case, I've approved the PR with the hspec primitives so that should be auto-merged soon.

**Comment by sassela** [comment]
Addressed at https://github.com/hasura/graphql-engine/commit/c9a5d51c70ed6b90ebde4021d77911dbcd95d17b, although there are some remaining BigQuery tests outstanding. @psibi mind creating a tracking issue for the BigQuery tests you're looking into?
