### ISSUE TITLE
server/tests: `RemoteResourceSpec` equivalent

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#7759]
Implement the equivalent of `RemoteResourceSpec` in the Haskell integration test suite.

https://github.com/hasura/graphql-engine/blob/master/server/tests/integration/Tests/RemoteSourceSpec.hs

**Comment by chrisdone** [comment]
Should I start on this one?

**Comment by sassela** [comment]
sure, but please keep @jkachmar in the loop on this one in particular; I don't have a very good idea how much change is needed from what's there already.

**Comment by chrisdone** [comment]
Maybe we can close this in favor of https://github.com/hasura/graphql-engine/issues/7756 which seems to have the same content but more engagement.
