### ISSUE TITLE
server: Haskell integration test suite

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#7760]
Produce a Haskell-based test suite which can initially complement, and eventually replace, the testing power of the current pytest test suite for alternative backend and cross-backend features.

[server/rfc: Haskell integration test suite](https://github.com/hasura/graphql-engine/blob/master/rfcs/hspec-test-suite.md)

[Checkpoints](https://github.com/hasura/graphql-engine/blob/master/rfcs/hspec-test-suite.md#checkpoints)
-----------
_checkpoints are mainly for visibility, please organise PRs as you see fit_
- [x] https://github.com/hasura/graphql-engine/issues/7752
- [x] #7801
- [x] https://github.com/hasura/graphql-engine/issues/7753
- [x] https://github.com/hasura/graphql-engine/issues/7827
- [x] https://github.com/hasura/graphql-engine-mono/issues/2866
- [x] https://github.com/hasura/graphql-engine/issues/7755
- [x] https://github.com/hasura/graphql-engine/issues/7756
- [x] https://github.com/hasura/graphql-engine/issues/7757
- [x] https://github.com/hasura/graphql-engine/issues/7877
- [x] https://github.com/hasura/graphql-engine/issues/7758

**Comment by chrisdone** [comment]
Suggestion to add a todo item: "make it so that teardown actions all run sequentially whether or not the previous teardown succeeded."

**Comment by chrisdone** [comment]
Another item suggestion: We should have something in the SanityCheckSpec which checks that the postgres and mysql have the correct schemas available, perhaps also a quick check that there are no tables in the schema could also be handy. 

Maybe even a post sanity check that no things are left over.

**Comment by chrisdone** [comment]
Suggest to add: make a docker-compose file?

**Comment by sassela** [comment]
thanks @chrisdone, I've added https://github.com/hasura/graphql-engine/issues/7827 and prioritised it quite high up as it would make verifying the PRs that follow (and the local testing experience in general) much smoother

**Comment by sassela** [comment]
> Suggestion to add a todo item: "make it so that teardown actions all run sequentially whether or not the previous teardown succeeded."

I wonder if this suggestion could be done under https://github.com/hasura/graphql-engine-mono/issues/2926. I'll mush them together for now, but let me know if you think they should be addressed separately.

I've created issues and referenced them to here (rather than create a separate board, which seems like overkill atm), along with some PR feedback that came in recently

**Comment by soupi** [comment]
Another feature proposal: It would be nice to be able to run a console with a specific test environment easily so we can experiment while writing or debugging tests.
This could be in a few steps like running a console manually and running the setup functions manually from ghci, but preferably not much more complicated than that.

**Comment by sassela** [comment]
I did some cleanup of the now-replaced `Basic*` pytests last week, now that hspecs are reliable and required in CI, and wanted to share my anecdotal local comparison of test execution time in closing. Our [goal](https://github.com/hasura/graphql-engine/blob/master/rfcs/hspec-test-suite.md#requirements) was only that tests _were no slower_ in hspec, so I think this is a pretty good result. **Thanks again to everyone who contributed to this new test suite!**

### MySQL pytests vs hspec equivalent: **5x faster in hspecs**

`scripts/dev.sh test --integration -k MySQL`
11 passed, 43 skipped in 16.13s

`cabal run tests-hspec -- -m MySQL`
* Finished in 3.0519 seconds
* 33 examples, 0 failures, 1 pending

### other `Basic*` pytests vs hspec: **10x faster in hspecs**

_disclaimers_
1. I belatedly noticed we missed testing [`LimitOffset`](https://github.com/hasura/graphql-engine-mono/issues/5012) and [`Ordering`](https://github.com/hasura/graphql-engine-mono/issues/5013) for all backends, I'll address those separately
2. BQ pytests are a notable outlier due to so many API roundtrips and the request overhead (AFAICT)

`cabal run tests-hspec -- -m Test.BasicFieldsSpec -m Test.Directives -m Test.LimitOffset -m Test.NestedRelationships -m Test.Ordering -m Test.PrimaryKey -m Test.SelectSpec -m Test.Where`
* Finished in 38.3313 seconds
* 98 examples, 0 failures

`scripts/dev.sh test --integration -k TestGraphQLQueryBasicCommon`
* `--backend postgres` 38 passed, 93 skipped in 17.18s
* `--backend citus` 38 passed, 93 skipped in 14.48
* `--backend mssql` 38 passed, 93 skipped in 16.48s

`scripts/dev.sh test --integration -k TestGraphQLQueryBasicBigquery`
 * 64 passed, 17 skipped in 350.99s

**Comment by soupi** [comment]
Awesome results! 🎉
