### ISSUE TITLE
Cannot use database previously used with a newer version of graphql-engine (expected a catalog version <=40, but the current version is 47

### ISSUE THREAD

**Issue by Johann-L-Pickard** [hasura/graphql-engine#7768]
graphql-engine version: v1.3.0
Postgress DB version: v13

I tried updating to the latest version, during which I think something was edited in my database, when I tried accessing the console again, I saw ...

![image](https://user-images.githubusercontent.com/75929513/139943167-06b58c0a-f87b-4d40-b16f-9b5d6b1018b9.png)

**Comment by Shalashtein** [comment]
Same issue here, upgraded from 1.3.3 v2 to 2.0.10 v3, the deploy failed because hasura was trying to edit hbd_catalog.events_log but failed. So I downgraded again and now I've got the same error

**Comment by sunapi386** [comment]
I just had to pull the latest image using
`docker pull hasura/graphql-engine`

**Comment by SamirTalwar** [comment]
Hasura doesn't support downgrading the `hdb_catalog`, unfortunately.
