### ISSUE TITLE
CLI not using Proxy environment settings

### ISSUE THREAD

**Issue by robhayesmba** [hasura/graphql-engine#7781]
### Version Information

Server Version:
CLI Version (for CLI related issue): 2.0.1

### Environment

OSS

### What is the expected behaviour?

When environment variables related to a proxy server are set the CLI should utilize the proxy when attempting to communicate with the Hasura endpoint.  The proxy environment variables are HTTP_PROXY, http_proxy, HTTPS_PROXY, https_proxy.

### Keywords

cli, proxy

### What is the current behaviour?

When attempting to export the metadata via cli when proxy is set, getting an error indicating no such host is present.  Here is an example of the output.  NOTE: I scrubbed the domain and the IP address.

```shell
$ hasura metadata export
FATA[0000] Post "https://capi-hasura-mt-eng.dev.cglcloud.in//v1/query": dial tcp: lookup hasura-mt-eng.dev.example.in on 10.XX.XX.XX:53: no such host
```

### How to reproduce the issue?

1.  Set proxy environment variables to point to an existing proxy server.
2.  Execute metadata export against a tls endpoint.
3.  CLI will not be able to find the host.

### Any possible solutions?

Yes, see the question below re: source code.

### Can you identify the location in the source code where the problem exists?

Yes.  In the cli.go file, (around line 332 and 763) when setting the transport for the TLS a quick check to see if the proxy environment variables are set, and then adding in the proxy to the transport should do it.

### If the bug is confirmed, would you be willing to submit a PR?

Yes.  I have one ready to go.  Pretty small change.

**Comment by scriptonist** [comment]
@robhayesmba Feel free to submit a PR with the change
