### ISSUE TITLE
server/mssql: query by pk returning empty array when no column values are matched

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#7784]
### Version Information

Server Version: v2.1.0-beta.2

### Environment
OSS

### What is the expected behaviour?
While running a `table_by_pk` query, if no rows found with given primary key column values then the response should be `null`.

The query: No rows exist with `id = 6`
```graphql
query {
  article_by_pk(id: 6){
    id
    author_id
  }
}
```
Expected response:
```json
{
  "data": {
    "article_by_pk": null
  }
}
```

### Keywords
mssql query by pk

### What is the current behaviour?
While running a `table_by_pk` query, if no rows found with given primary key column values then the response is empty array expression `[]`.

The query: No rows exist with `id = 6`
```graphql
query {
  article_by_pk(id: 6){
    id
    author_id
  }
}
```
Current response:
```json
{
  "data": {
    "article_by_pk": []
  }
}
```

**Comment by sassela** [comment]
closed by https://github.com/hasura/graphql-engine/commit/95be515a60e5933463904424ec88d2cd8c3730e7
