### ISSUE TITLE
Malformed errors in GraphQL over WebSocket Protocol support (`graphql-ws` clients)

### ISSUE THREAD

**Issue by bitjson** [hasura/graphql-engine#7786]
### Version Information

Server Version: 

### Environment

OSS

### What is the expected behavior?

Based on the [`graphql-ws` protocol specification](https://github.com/enisdenjo/graphql-ws/blob/216075510ad7ecbe2fdd4ba6fe578a668ae38fe3/PROTOCOL.md#error), error messages should have the format:

```ts
import { GraphQLError } from 'graphql';

interface ErrorMessage {
  id: '<unique-operation-id>';
  type: 'error';
  payload: GraphQLError[];
}
```

But Hasura returns subscription errors with an extraneous, nested `errors` field, e.g.:
```json
{
  "type": "error",
  "id": "1a6ab524-257f-47af-a8b3-cf0dfd406c88",
  "payload": {
    "errors": [
      {
        "extensions": {
          "path": "$.selectionSet.node.selectionSet.bad_field",
          "code": "validation-failed"
       },
        "message": "field \"bad_field\" not found in type: 'users'"
      }
    ]
  }
}
```

Corrected, the above response should be:
```json
{
  "type": "error",
  "id": "1a6ab524-257f-47af-a8b3-cf0dfd406c88",
  "payload": [
    {
      "extensions": {
        "path": "$.selectionSet.node.selectionSet.bad_field",
        "code": "validation-failed"
      },
      "message": "field \"bad_field\" not found in type: 'users'"
    }
  ]
}
```

This currently prevents client libraries from correctly displaying errors emitted by Hasura subscriptions.

**Comment by kolharsam** [comment]
@bitjson I think a similar issue was raised and fixed in this PR: https://github.com/hasura/graphql-engine/pull/7730

cc @paritosh-08 @sordina

**Comment by bitjson** [comment]
Ah, perfect! Thanks for the heads up @kolharsam, looking forward to the release. 👍
