### ISSUE TITLE
Add the ability to run SQL functions from Cron Triggers.

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#7800]
### Is your proposal related to a problem?
No

### Describe the solution you'd like
Right now [cron triggers](https://hasura.io/docs/latest/graphql/core/scheduled-triggers/create-cron-trigger.html#creating-cron-trigger) support calling a webhook but it would be nice to be able to run a SQL against the DB. If that is not viable have to ability to run `GQL` query instead so basically we track a SQL function and call it from the cron trigger 

### Describe alternatives you've considered
The alternative right now is to expose webhook endpoint that runs the sql once the webhook is received, or `pg_cron/pgAgent`(would like it be managed by hasura)

### If the feature is approved, would you be willing to submit a PR?
I could try but haskell :man_shrugging:

**Comment by Bessonov** [comment]
@abdullah2993 may be relevant: https://github.com/hasura/graphql-engine/issues/7012

**Comment by tirumaraiselvan** [comment]
Closing this in favour of #7012
