### ISSUE TITLE
Field for setting Tolerance in cron triggers not visible in console

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#7811]
### Version Information

Server Version: v2.0.6
CLI Version (for CLI related issue): 2.0.9

### Environment

OSS

### What is the expected behaviour?

There is suppose to be an option visible in console to set `Tolerance in seconds` in `console` as shown [here](https://hasura.io/docs/latest/graphql/core/scheduled-triggers/create-cron-trigger.html#step-3-define-advanced-options-optional) but it is not visible
![image](https://user-images.githubusercontent.com/5978905/141762836-2bf4f4b0-c0a4-4f7d-9d49-da43675372ea.png)

### Keywords
Tolerance

### What is the current behaviour?
The field for setting tolerance is not visible in console

### How to reproduce the issue?
Navigate to a cron trigger

### Screenshots or Screencast

https://user-images.githubusercontent.com/5978905/141763103-628893f1-f890-43f1-a890-8a77ce33f8bf.mp4

### Please provide any traces or logs that could help here.
I don't think they are needed. Please let me know if required otherwise

### Any possible solutions?
Manually edit the `yaml` config

### Can you identify the location in the source code where the problem exists?
Haven't looked

### If the bug is confirmed, would you be willing to submit a PR?
Of course, why not

**Comment by soorajshankar** [comment]
Quick update: we have a fix for this merged - https://github.com/hasura/graphql-engine/commit/eb401b5925a80194c6ca6cbbc1c42a47f610cd84 and will be available from the next beta release.
