### ISSUE TITLE
fkeys become UNIQUE in Hasura / console differs from DDL

### ISSUE THREAD

**Issue by strazan** [hasura/graphql-engine#7812]
### Version Information
Server Version: v2.0.9

### Environment
macos

### What is the current behaviour?

The columns in hasura console differs from DDL.

- Primary key is wrong
- UNIQUE keys are being created for all columns with fk.

### Reproduce
- Create the tables `public.apps` and `models.models`

```SQL
CREATE SCHEMA public;

CREATE TABLE "public"."apps" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  PRIMARY KEY ("id")
);
```
```SQL
CREATE SCHEMA models;

CREATE TABLE "models"."models" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  PRIMARY KEY ("id")
);
```
- Create the table
```SQL
CREATE TABLE "public"."model_settings" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "model_id" uuid NOT NULL,
  "app_id" uuid NOT NULL,
   -- (more columns)
  PRIMARY KEY ("id"),
  UNIQUE ("app_id", "model_id"),

  constraint "model_settings_app_id_fkey"
  foreign key ("app_id")
  references "public"."apps"
  ("id") on update restrict on delete cascade,
  
  constraint "model_settings_model_id_fkey"
  foreign key ("model_id")
  references "models"."models"
  ("id") on update restrict on delete cascade
);
```

#### DDL from pgadmin
```SQL
-- Table: public.model_settings

-- DROP TABLE public.model_settings;

CREATE TABLE IF NOT EXISTS public.model_settings
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    model_id uuid NOT NULL,
    app_id uuid NOT NULL,
    CONSTRAINT model_settings_pkey PRIMARY KEY (id),
    CONSTRAINT model_settings_app_id_fkey FOREIGN KEY (app_id)
        REFERENCES public.apps (id) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT model_settings_model_id_fkey FOREIGN KEY (model_id)
        REFERENCES models.models (id) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE CASCADE
)

```
- Notice how the console differs
#### Hasura console
![image](https://user-images.githubusercontent.com/43888637/141816941-9e6cdd4d-44e7-4bbf-a754-015985dcd940.png)

#### Note
This seems to only happen when the fk constraints are part of creating the tables.

**Comment by BenoitRanque** [comment]
Most likely a bug in how the console identifies unique constraints vs foreign keys.
As a guess, do you get the same error when you _don't_ use a custom name for the foreign key constraint?

```sql
CREATE TABLE "public"."model_settings" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "model_id" uuid NOT NULL REFERENCES "public"."apps" ("id") on update restrict on delete cascade,
  "app_id" uuid NOT NULL REFERENCES "models"."models" ("id") on update restrict on delete cascade,
   -- (more columns)
  PRIMARY KEY ("id"),
  UNIQUE ("app_id", "model_id"),
);
```

We've had issues with constraints using custom names before.
That said, this is definitely a bug.

**Comment by Varun-Choudhary** [comment]
Hey @strazan, this issue has been resolved in later versions. So, I'd recommend switching to the latest stable version of Hasura [v2.1.1](https://github.com/hasura/graphql-engine/releases/tag/v2.1.1)

**Comment by haf** [comment]
@Varun-Choudhary 2.1.1 has an major bug that deletes multiple rows from the UI if one row is selected to be deleted

**Comment by Varun-Choudhary** [comment]
> @Varun-Choudhary 2.1.1 has an major bug that deletes multiple rows from the UI if one row is selected to be deleted

Hey @haf, I tried deleting a single row from the browse row data viewer and I'm unable to replicate this issue on v2.1.1
[Here](https://www.loom.com/share/7ad20b3330124b4eade0e45b5bb3b511) is the recording.

**Comment by strazan** [comment]
@Varun-Choudhary 
https://github.com/hasura/graphql-engine/issues/8064

**Comment by strazan** [comment]
@Varun-Choudhary 
updated with video
https://www.loom.com/share/3437c95ca30148a19a4e82a19dedff42
