### ISSUE TITLE
server/tests: create `docker-compose` file for integration test DBs

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#7827]
Suitable for running [Haskell integration tests](https://github.com/hasura/graphql-engine/issues/7760) locally. For postgres and mysql containers initially

**Comment by chrisdone** [comment]
Note. I must check/ensure that will be applied on the PG database when spinning it up.
```
hasura=# create extension pgcrypto;
CREATE EXTENSION
```

**Comment by sassela** [comment]
addressed in https://github.com/hasura/graphql-engine/commit/926da74819337a7c5f9c3539b7c1cc705560f0f3
