### ISSUE TITLE
create hasura adapter for react-admin

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#783]
[react-admin](https://github.com/marmelab/react-admin) is an open source admin dashboard built on React which can provide an interface to view/edit/manage data from various backends.

It supports GraphQL, but the grammar is a bit different from what Hasura has.

We can implement a [DataProvider](https://marmelab.com/react-admin/DataProviders.html) to support managing data through Hasura GraphQL APIs.

**Comment by supriyanta** [comment]
I want to work on this, I'm beginner here. Could you please guide me?
What to learn?

**Comment by EmaSuriano** [comment]
I'm taking this issue thank you @coco98 for the help to understand what was exactly to do 👏 

@supriyanta you could ask for help in the discord channel of hasura.

**Comment by jasonmorganson** [comment]
For reference, from the [docs](https://marmelab.com/react-admin/DataProviders.html#available-providers):
> Graphcool: marmelab/ra-data-graphcool. A provider for GraphQL servers following the Graphcool convention. Incidentally, this package builds up on marmelab/ra-data-graphql, which lets you develop providers for other GraphQL conventions.

The react-admin [ra-data-graphql](https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql) package is maintained by the react-admin team as a basis for building other adapters off of. 

They have a couple implementations which might be useful to look at:
- [ra-data-graphql-simple](https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql-simple) - 
A GraphQL data provider for react-admin built with Apollo and tailored to target a simple GraphQL implementation.
- [ra-data-graphcool](https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphcool) - 
A GraphQL data provider for react-admin built with Apollo and tailored to target the GraphCool service.

**Comment by edv1297** [comment]
Is this issue closed?

**Comment by EmaSuriano** [comment]
Hi @praveenweb, I'm having lots of problems to find some time to continue it. So if @edv1297 want to take it, please be my guest. I really wanted to contribute to this project but unfortunately, I can't for now.

**Comment by mnlbox** [comment]
Guys any update on this feature request?

**Comment by EmaSuriano** [comment]
I couldn't continue working on it. Also, I think I'll drop it because I don't think I will be able to work on this for about 1 month or maybe more.

**Comment by eaverdeja** [comment]
Hey @EmaSuriano ! I've been using react-admin for the past few months and just found out about Hasura yesterday. Seems like a perfect match :)
I would love to work on this, but I have never contributed with a PR. Any tips?

**Comment by shahidhk** [comment]
Hi @eaverdeja, the easiest way to checkout the grammar would be to create a Heroku app, create some tables and try out some graphql queries. We have not written the grammar anywhere down, I guess, maybe this is the time do so.

Let us know if you're taking this up :smile:

**Comment by ptrobert** [comment]
Hi Guys,

Any progress on this?

**Comment by Pomazan-Bogdan** [comment]
Hello
I just consider the react-admin as admin interface to hasura.

I have a need for an application prototype in which the users associated with the organization, which should be many, add entries to the first entity.

Overall, I have such a database schema I can lay out:
![emisto](https://user-images.githubusercontent.com/696713/51197411-1bdefd00-18fa-11e9-9bc9-f71af35f473e.png)

And there is somebody who wants to help, then we will try to "write" the interface to the react-admin for testing the functional and put it as a sample of the ties of hasaur and react-admin.

**Comment by Pomazan-Bogdan** [comment]
![emisto](https://user-images.githubusercontent.com/696713/51198715-b856ce80-18fd-11e9-8ad7-5985a39ab1f9.png)

**Comment by lumannnn** [comment]
@shahidhk @praveenweb Thanks for the awesome work! I've been waiting and watching for this as well! 😃

I'm currently testing your new ``ra-data-hasura`` release and it works pretty well so far! Congrats! 🎉 

However, I think I've encountered a bug in the ``GET_MANY_REFERNECE`` case.

# Issue
I'm trying to use the ``<ReferenceManyField>`` and get the following error:

```
index.js:1452 Warning: Missing translation for key: "Cannot read property 'args' of undefined"
```

## Debugging
Looking through the source code, I think there is an issue in [this line (index.js#L106)](https://github.com/hasura/graphql-engine/blob/master/community/tools/ra-data-hasura/src/index.js#L106).

The variable ``finalSelectQuery`` seems to be ``undefined`` in this particular case. It is only initialised in [index.js#L22](https://github.com/hasura/graphql-engine/blob/master/community/tools/ra-data-hasura/src/index.js#L22).

Can anyone verify this as well?

Thanks in advance and keep up the awesome work! 👍 🚀

**Comment by praveenweb** [comment]
@lumannnn - Hey, thanks for reporting the issue. Will fix it asap and release an updated version.

**Comment by praveenweb** [comment]
@lumannnn - Fixed the issue. Released version `0.0.2` on npm. Please update and let us know.

**Comment by lumannnn** [comment]
@praveenweb Thanks for the quick response! Seems to be working now 👍

**Comment by AdamNowaczyk** [comment]
Hi @praveenweb,

This is an awesome job, but as I understand it's using /v1/query and SQL based approach, right?

Do you think it would be possible to create GraphQL based version of the provider? Otherwise react-admin basically cannot handle many to many relations without using custom code. Just wondering :D. It's quite interesting as I've found out both react-admin and hasura adapter just today. Quite a coincidence :D.

**Comment by praveenweb** [comment]
@AdamNowaczyk - Hi, we are using /v1/query, instead of GraphQL for convenience as it solves the full use case of react-admin. 

> Otherwise react-admin basically cannot handle many to many relations without using custom code. 

/v1/query supports many to many relations. Can you give an example model which cannot be implemented using the current hasura provider? And by custom code you mean the react code?

**Comment by a613** [comment]
@praveenweb 

> Can you give an example model which cannot be implemented using the current hasura provider?

Any query that uses GraphQL relationships, for example

```graphql
{
  user(id: 1) {
    name
    address {
      street
    }
  }
}
```

When this query is run in ra-data-hasura, the user data is loaded, but not the address data, as it's stored in a different postgres table and ra-data hasura always passes `columns: ['*']`, and it ignores any nested fields like this.
