### ISSUE TITLE
server/mssql:  implement UPDATE mutation execution

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#7834]
This issue is product of work done as part of [technical spike](https://github.com/hasura/graphql-engine/issues/7815) involves figuring out SQL statement(s) to implement MSSQL UPDATE mutations. It is found that the approach we took for [DELETE mutations](https://github.com/hasura/graphql-engine-mono/pull/2691) involving temporary tables works for UPDATE mutations as well. 

A GraphQL update mutation does two things:

1. Updates rows in a table according to some predicate
2. (Potentially) returns the updated rows (including relationships) as JSON

In order to complete these 2 things we need 3 SQL statements:

1. SELECT INTO <temp_table> WHERE <false> - creates a temporary table
   with the same schema as the original table in which we'll store the updated rows
   from the table we are updating
2. UPDATE SET FROM with OUTPUT - updated the rows from the table and inserts the
  updated rows to the temporary table from (1)
3. SELECT - constructs the `returning` query from the temporary table, including
  relationships with other tables.

Example:- Consider a simple table `author` with following schema,
```sql
      CREATE TABLE author(
          id int identity NOT NULL PRIMARY KEY,
          [name] varchar(450) UNIQUE,
          [is_registered] bit NOT NULL DEFAULT 0
      );
```
Consider the following update mutation query,
```graphql
mutation {
  update_author(_set: {name: "update_name"}, where: {id: {_eq: 1}}){
    affected_rows
    returning{
      id
      name
    }
  }
}
```
Generated SQL statements to implement above query will look like:

1.
```sql
SELECT [name], [is_registered], [id] INTO #updated FROM [dbo].[author] WHERE (1<>1) UNION ALL SELECT [name], [is_registered], [id] FROM [dbo].[author] WHERE (1<>1);
```
2.
```sql
UPDATE [t_author1] SET [t_author1].name = 'updated_name' OUTPUT INSERTED.[name], INSERTED.[is_registered], INSERTED.[id] INTO #updated([name], [is_registered], [id]) FROM [dbo].[author] AS [t_author1] WHERE (((([t_author1].[id]) = (1))));
```
3.
```sql
WITH [with_alias] AS ( SELECT * FROM #updated AS [updated_alias] ) SELECT ISNULL((SELECT (SELECT COUNT(*) AS [count] FROM [with_alias]) AS [affected_rows], (SELECT ISNULL((SELECT [with_alias].[id] AS [id], [with_alias].[name] AS [name] FROM [with_alias] FOR JSON PATH, INCLUDE_NULL_VALUES), '[]')) AS [returning] FOR JSON PATH, INCLUDE_NULL_VALUES, WITHOUT_ARRAY_WRAPPER), 'null');
```

Implementation details:

```
+--------------+     +-----+     +-----------------+
| Mutation AST | --> | SQL | --> | Execution on DB |
+--------------+     +-----+     +-----------------+
```

This broadly involves:
1. creating an intermediate mutation AST: for example, `data Update` in `Hasura.Backends.MSSQL.Types`.
2. writing `fromUpdate` function in `module Hasura.Backends.MSSQL.FromIr` which constructs the intermediate AST from IR data type `AnnotatedUpdateG`
2. writing `fromUpdate` function in `module Hasura.Backends.MSSQL.ToQuery` which translates the data type to update SQL statement.

To verify: simple update tests such as `test_set_author_name` for sql server

**Comment by sassela** [comment]
hey @rakeshkky, Evie and I didn't have enough info to estimate this, but I know you said you wanted to work on it anyway, so I'm going to assign it to you. Please add your own estimate as a label when you start work on it.

Please could you also add a brief implementation outline to the description, including pointers to the modules and types to start looking at?  [Here's an example for upserts](https://github.com/hasura/graphql-engine/issues/7862). This would be helpful for documentation and review, regardless of who works on it.

**Comment by soupi** [comment]
Closing this as the related PR has been merged. CC @rakeshkky
