### ISSUE TITLE
server/mssql: upsert SQL generation & execution

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#7862]
Relates to #7864

```
+--------------+     +-----+     +-----------------+
| Mutation AST | --> | SQL | --> | Execution on DB |
+--------------+     +-----+     +-----------------+
```

This broadly involves:
1. creating an intermediate mutation AST: for example, `data Merge` in `Hasura.Backends.MSSQL.Types`.
     - [These notes on MSSQL upsert](https://github.com/hasura/graphql-engine-mono/issues/2427) give an example `MERGE` statement in context of HGE upserts.
     - Postgres' `SQLConflict` datatype can be used as a reference implementation.
1. using AST: including this new type as a field in MSSQL's `Insert` record
1. translating AST to a [SQL Server `MERGE` statement](https://docs.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql): update the `fromInsert` query printer to generate the correct `MERGE` statement when the upsert condition is met.

*To verify:* simple insert tests such as `test_on_conflict_update`, at a minimum, should now pass.

- [x] https://github.com/hasura/graphql-engine-mono/issues/3000

**Comment by rakeshkky** [comment]
Following SQL statements work for achieving the upsert mutation
```sql
-- the table
create table test (
  id int identity primary key,
  name text
);
-- create temporary table
select id, name into #merged from test where (1 <> 1) union all select id, name from test where (1 <> 1);

-- the "id" column is identity column
set identity_insert test on;

-- the MERGE statement
merge test target using (values (1008, 'updated_name_again')) source(id, name) ON target.id = source.id when matched then update set name = source.name when not matched then insert (id, name) values (source.id, source.name);

-- statement that generate mutation response
WITH [with_alias] AS ( SELECT * FROM #merged AS [merged_alias] ) SELECT ISNULL((SELECT (SELECT COUNT(*) AS [count] FROM [with_alias]) AS [affected_rows], (SELECT ISNULL((SELECT [with_alias].[id] AS [id], [with_alias].[name] AS [name] FROM [with_alias] FOR JSON PATH, INCLUDE_NULL_VALUES), '[]')) AS [returning] FOR JSON PATH, INCLUDE_NULL_VALUES, WITHOUT_ARRAY_WRAPPER), 'null');
```

**Comment by plcplc** [comment]
Note that the IR for upserts introduced in https://github.com/hasura/graphql-engine-mono/pull/3056 uses the same `ConflictClauseP1` data type that is used in the PG IR. This, however, has cases pertaining to both specifying constraints _as well as_ individual columns. (The alternative for individual columns appears to be a leftover from the DML API - it's not used anywhere in the GraphQL API)

Since we're only going to be supporting either of the two cases, we might want to refactor and use a slightly different IR type.

**Comment by plcplc** [comment]
> Since we're only going to be supporting either of the two cases, we might want to refactor and use a slightly different IR type that reflects this. (Should be a straightforward change because different backend's upsert IR is now completely decoupled from each other as per [hasura/graphql-engine-mono#3056](https://github.com/hasura/graphql-engine-mono/pull/3056) )

This was implemented.

**Comment by plcplc** [comment]
As per PR https://github.com/hasura/graphql-engine-mono/pull/3056/ the new schema is not yet enabled, ensuring we don't actually expose new schema to users before we have a corresponding execution implementation.

In order to enable the new schema, simply make changes to `Hasura.Backends.MSSQL.Instances.Schema.backendInsertParser` as per the inline instructions:

```haskell
backendInsertParser ::
  forall m r n.
  MonadBuildSchema 'MSSQL r m n =>
  SourceName ->
  TableInfo 'MSSQL ->
  Maybe (SelPermInfo 'MSSQL) ->
  Maybe (UpdPermInfo 'MSSQL) ->
  m (InputFieldsParser n (BackendInsert (UnpreparedValue 'MSSQL)))
backendInsertParser _sourceName tableInfo _selectPerms _updatePerms = do
  -- Uncomment when we implement execution of upserts.
  -- import Hasura.Backends.MSSQL.Schema.IfMatched
  -- ifMatched <- ifMatchedFieldParser sourceName tableInfo selectPerms updatePerms
  pure $ do
    -- _biIfMatched <- ifMatched
    let _biIfMatched = Nothing
    pure $ BackendInsert {..}
  where
    _biExtraColumnInfo :: ExtraColumnInfo
    _biExtraColumnInfo =
      let pkeyColumns = fmap (map pgiColumn . toList . _pkColumns) . _tciPrimaryKey . _tiCoreInfo $ tableInfo
          identityColumns = _tciExtraTableMetadata $ _tiCoreInfo tableInfo
       in ExtraColumnInfo (fromMaybe [] pkeyColumns) identityColumns
```
