### ISSUE TITLE
unexpected null value for type ***

### ISSUE THREAD

**Issue by 1018715564** [hasura/graphql-engine#7865]
### Version Information
release latest (arm64) 

![image](https://user-images.githubusercontent.com/35763284/143888449-06c2daf7-73d4-43f1-a993-d0f377de06fd.png)

An optional parameter, it does not work

**Comment by BenoitRanque** [comment]
See [this discussion](https://github.com/hasura/graphql-engine/discussions/7640#discussioncomment-1445035)

The variable itself is nullable. However if a key is present (in your case `_like`) it cannot be provided a null value.
This is due to the changes introduced in #704

**Comment by 1018715564** [comment]
Thank you, I have found a solution that suits me
