### ISSUE TITLE
inherited_roles.yaml not being applied in metadata

### ISSUE THREAD

**Issue by LydiaF** [hasura/graphql-engine#7868]
### Version Information

Server Version: v2.1.0-beta.2
CLI Version (for CLI related issue): v2.1.0-beta.2

### What is the expected behaviour?

I have enabled inherited_roles and can make an inherited role in the console. However, I am not having any luck doing so via metadata/inherited_roles.yaml.

Expected: What is described in the docs works: https://hasura.io/docs/latest/graphql/core/auth/authorization/inherited-roles.html#creating-inherited-roles

![image](https://user-images.githubusercontent.com/10000865/144054574-27140961-069a-41c2-9dbd-9b410670495e.png)

### Keywords

inherited_roles, cli

### What is the current behaviour?

metadata/inherited_roles.yaml is not having any effect despite successful `hasura md apply`

After `hasura md apply`, inherited_roles are still empty:
![image](https://user-images.githubusercontent.com/10000865/144054437-674dedff-4218-4711-83fc-e1ecaf0016b1.png)

**Comment by BenoitRanque** [comment]
I've not been able to replicate you issue.
However, the console will not automatically refresh the list of inherited roles after a successful `hasura metadata apply`
Did you refresh the console after applying metadata?

We did encounter an issue when replicating this, but it was not the issue you mentioned. See #7872
Can you confirm that the `HASURA_GRAPHQL_EXPERIMENTAL_FEATURES` is set to `inherited_roles` in all your environments?

**Comment by LydiaF** [comment]
Hi @BenoitRanque,

Thanks so much for replying so quickly.

I actually did run into #7872 as well! I was originally going to include it but then thought this was more important. Thanks for writing it up!

What do you mean by "refresh"? Like refresh the browser with command + R? Yes, certainly I did.

I am pretty confident that HASURA_GRAPHQL_EXPERIMENTAL_FEATURES is set to inherited_roles... how else would it come up in the console if I had done it wrong?

Is there anything wrong with this yaml file?

```yaml
- role_name: sample_inherited_role
  role_set:
    - parent
```

Thanks for looking into this,

Lydia

**Comment by BenoitRanque** [comment]
The file above is valid, assuming the role `parent` exists. If not, you would get an error, metadata would not apply successfully.
I am just now noticing that you are using the latest beta. Let me see if I can replicate the issue there

**Comment by BenoitRanque** [comment]
Cannot replicate this in version v2.1.0-beta.2, everything behaves as expected. Perhaps your issue lies elsewhere?

**Comment by LydiaF** [comment]
Hi @BenoitRanque,

Thanks for looking into this.

I tried an `inherited_roles.yaml` file with a role that did I knew did *not* exist. I expected `hasura md apply` to fail because you said I would get an error if the role did not exist. However, *it still applied successfully*.

It is like hasura is not "picking up" that `inherited_roles.yaml` even exists. It is like it is ignoring it.

What else can I try?

**Comment by BenoitRanque** [comment]
This is quite perplexing. I would encourage you to try to replicate this on a fresh project, perhaps the cli is not pointing at the directory you think it is? Have you configured a custom location for the metadata directory in `config.yaml`?

**Comment by LydiaF** [comment]
Hi @BenoitRanque,

Thank you so much for your help with this but we have not progressed at all with this. The cli is working as it always has done for months – when we make a change it is reflect in the cli. It really, really seems like the `inherited_roles.yaml` file is just not being picked up by hasura.

This is our `config.yaml`

![image](https://user-images.githubusercontent.com/10000865/144666628-7e65e3aa-8c9c-4908-9ec0-91a20dfd2e6d.png)

Here is our metadata folder:

![image](https://user-images.githubusercontent.com/10000865/144666998-464c923e-1b06-468f-a5ca-6f26478b5f47.png)

**Comment by BenoitRanque** [comment]
Oh. You seem to be using config v2. Please update to config v3.
https://hasura.io/docs/latest/graphql/core/migrations/upgrade-v3.html#upgrade-steps

**Comment by LydiaF** [comment]
Okay... I am v glad we have gotten to the bottom of this but this is going to be a huge pain for us. Thank you so much for your help. 

However... Our workflow greatly depends on

https://www.npmjs.com/package@hasura/metadata

... Which is only works for v2 :S

@GavinRay97 hey Gavin, sorry if I am mis-tagging you but if I remember correctly you made the metadata npm package... will there be a v3 of the package out anytime soon? :) :) :)

**Comment by BenoitRanque** [comment]
I have good news for you: the V3 version of the package exists, and recently got merged into main, but has not been published to npm yet. You can find the source for this at https://github.com/hasura/graphql-engine/tree/master/contrib/metadata-types/src/types

This is assuming you are not referencing the yaml json schema validation, which is the only thing missing if I am not mistaken

**Comment by LydiaF** [comment]
This is absolutely fantastic news! Thank you team hasura! 

I will probably try tomorrow if not early next week.

Thank you so so much for helping us @BenoitRanque :)

**Comment by BenoitRanque** [comment]
Closing this issue for now, if updating to config v3 does not solve your problem please mention it here and I will re-open.

**Comment by LydiaF** [comment]
@BenoitRanque 

Hello again :)

Our workflow depends on `HasuraMetadataV2.ts` here: https://github.com/hasura/graphql-engine/tree/master/contrib/metadata-types/generated

... but unlike the rest of the V2 files, there is no V3 file for typescript! Is this an oversight? We think that without this file we will be stuck.

Thanks!
