### ISSUE TITLE
CLI Console does not update inherited_roles.yaml when removing last role.

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#7872]
### Version Information

Server Version: 2.0.10
CLI Version (for CLI related issue): 2.0.10

### Environment

OSS

### What is the expected behaviour?

When deleting all inherited roles from the cli console, the `inherited_roles.yaml` file should either be deleted, or it's value should be an empty list (the string `[]`).

### Keywords

inherited roles deleted console metadata

### What is the current behaviour?

Currently, the `inherited_roles.yaml` file does not update when the last role is deleted.
This could cause the following scenario: 

1. User deletes all inherited roles from the console in their dev environment
2. User commits the metadata to their repo, and pushed it to production
3. Ci applies the metadata to the production instance
4. The production instance will still contain the last role that was deleted, instead of no roles as was intended.

### How to reproduce the issue?

1. Run `hasura console` against a hasura instance that has inherited roles enabled
2. Add at least one inherited role. The `inherited_roles.yaml` file on local disk will be updated with the relevant metadata.
3. Delete that role, and any other roles.
4. The `inherited_roles.yaml` file will _not_ be updated.

### Any possible solutions?

Currently this can be worked around by either deleting the file, or replacing it's content with the string `[]` (empty list)

**Comment by LydiaF** [comment]
The issue for me was that `inherited_roles.yaml` was not updating for any change I made.

**Comment by BenoitRanque** [comment]
Is it possible you were mistakenly using the server console instead of the cli console?
Also, can you make sure your cli is up to date and on the same version are the image, preferably latest?
Frankly puzzled by this

**Comment by LydiaF** [comment]
We do not understand the distinction you are making between "server" console and "cli" console.

The cli is definitely up to date: 

![image](https://user-images.githubusercontent.com/10000865/144288956-a5318661-58d9-4c00-b0dc-7f1dbf2acf7e.png)

**Comment by BenoitRanque** [comment]
Cli Console refers to the console you can access by running the command `hasura console`.
This console will update metadata files in a local directory whenever a change is made, and create sql migrations when necessary.

Server Console refers to the console accessible at the root of the server enpoint, when `HASURA_GRAPHQL_ENABLE_CONSOLE` is set to `true`. This console does not update the local metadata files. This would also include the console you can launch from the hasura cloud dashboard. In both cases you can still make changes to your instance, but they won't update your local files.

**Comment by LydiaF** [comment]
Okay, thanks a million for the clarification. However in our docker-compose.yml file we have: `HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'` so I don't see how that could be the issue.

**Comment by BenoitRanque** [comment]
Hiding above conversation to avoid polluting the issue.
User's issue was using config v2 instead of v3.
This was resolved in #7868 but is not relevant to this issue

**Comment by scriptonist** [comment]
Fixed in https://github.com/hasura/graphql-engine-mono/commit/4cc8f67dd8b6ba0e78f1c35d415f89bd1b901705
