### ISSUE TITLE
server/mssql: fix count aggregate query with multiple columns

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#7873]
### Version Information

Server Version: v2.0.10

### Environment

OSS

### What is the expected behaviour?

The following query should be successful.
```graphql
query {
  author_aggregate{
    aggregate{
      count(columns: [id, name])
    }
  }
}
```

### Keywords

mssql sql server aggregate count multiple columns

### What is the current behaviour?

The query results in following error
```json
{
  "errors": [
    {
      "extensions": {
        "internal": {
          "tag": "unsuccessful_return_code",
          "contents": [
            "odbc_SQLExecDirectW",
            -1,
            "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The COUNT function requires 1 argument(s).[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'AS'.[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'AS'."
          ]
        },
        "path": "$",
        "code": "unexpected"
      },
      "message": "sql server exception"
    }
  ]
}
```

### How to reproduce the issue?

1. Create author table with following schema
```sql
      create table author(
          id int identity not null primary key,
          name varchar(20)
      );
```
2. Track table and perform the query mentioned above

### Screenshots or Screencast

N/A

### Please provide any traces or logs that could help here.

N/A

### Any possible solutions?

As I can see now, we can solve the issue in 2 ways
1. Modify the schema to accept only one column for `count` aggregate field (breaking change as schema is changing?)
2. Generate SQL using sub-queries to achieve the count for multiple columns. For example,
```sql
select count(*) from (select id, name from author where id is not null and name is not null) as t
```

**Comment by sassela** [comment]
@0x777 @dennislaviolette considering the 2 solutions that @rakeshkky proposed above, do you have a preference between:
1. Preserving the semantics of SQL Server `count`, which is likely a breaking schema change
2. Following what we currently do on graphql-engine for Postgres

**Comment by sassela** [comment]
Confirmed with @dennislaviolette during earlier that we'll go with option 1:

> Preserving the semantics of SQL Server count, which is likely a breaking schema change

@rakeshkky please could you update the description to point to the relevant part of the schema generation code, and any guidance for testing / verifying this works as expected? We'll need this in order to estimate. 

Also, do you have any advice about how we should handle potentially breaking schema changes? Does it warrant a metadata version bump, highlight in the changelog, or anything else?

**Comment by rakeshkky** [comment]
@sassela 
> do you have any advice about how we should handle potentially breaking schema changes? Does it warrant a metadata version bump, highlight in the changelog, or anything else?

- GraphQL schema changes don't involve metadata change whatsoever. So, version bump in this case is not required.
- Highlight in changelog; definitely yes
 
I cannot thing off anything else right now.

**Comment by rakeshkky** [comment]
**Implementation**

Modify the schema field `count` to accept only one column. The schema changes as follows
```diff
count (
---  columns: [table_select_column!]
+++  column: table_select_column
  distinct: Boolean
): Int!
```
We need to update the [count field parser](https://github.com/hasura/graphql-engine-mono/blob/90a5c9e2346c8dc2da6ec5b8c970d6c863d2afb8/server/src-lib/Hasura/GraphQL/Schema/Select.hs#L1016) to reflect the above change. This requires changing the `Backend` instance of  [CountType](https://github.com/hasura/graphql-engine-mono/blob/582a2e77c8120ad2dc818d5f0b51cf56afc79bc5/server/src-lib/Hasura/Backends/MSSQL/Instances/Types.hs#L29) for MSSQL backend.
cc @sassela

**Comment by rakeshkky** [comment]
closed with https://github.com/hasura/graphql-engine-mono/pull/3354
