### ISSUE TITLE
server/tests: unified setup/teardown interface

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#7877]
[refers to work on the Haskell integration test suite](https://github.com/hasura/graphql-engine/issues/7760)

_How might we share the same schema for different backends, so we can test the same features across multiple backends with minimal code duplication?_

(As per suggestion by @chrisdone) It might just be that a simple thing such as the below would be enough to serve our purposes:

```haskell
-- Small model of SQL relations. The only intention is to capture the bare
-- minimum that translates easily across different backends.

data CreateTable = CreateTable
  { tableName :: Text,
    tableColumns :: [Column],
    tablePrimaryKey :: [Text],
    tableReferences :: [Reference]
  }

-- Reference "targetTable" [("localCol1", "targetCol1"), ("localCol2", "targetCol2")]
data Reference = Reference
  { referenceTargetTable :: Text,
    referenceColumns :: [(Text, Text)]
  }

data Column = Column
  { columnName :: Text,
    columnType :: Type,
    columnNullable :: Bool,
    columnDefault :: Maybe Value
  }

column :: Text -> Type -> Column
column name ty = Column name ty False Nothing

data Type = TInteger | TText

data Value = VInt Int | VText Text

instance Integral Value -- inject int literals via VInt

instance IsString Value -- Inject string literals via VText

data InsertInto = InsertInto
  { insertTable :: Text,
    insertColumns :: [Text],
    insertValues :: [[Value]]
  }

cr = CreateTable "author" [column "author_id" TInteger, column "author_name" TText] ["author_id"] []

v =
  InsertInto
    "author"
    ["author_id", "author_name"]
    [ [1, "hey"],
      [2, "wow"]
    ]

```

... And then you'd have functions such as `mssqlCreate :: CreateTable -> Text` etc. in order to execute these on different backends.

Note that we don't need to model any remotely advanced security or coherency guarantees in the types. This is only used for tests, so we'll know straight away if we're specifying something inconsistent. But it still enables us to share data model definitions and test data between backends.

_Originally posted by @plcplc in https://github.com/hasura/graphql-engine/issues/7755#issuecomment-982792659_

**Comment by soupi** [comment]
I think a good place to learn from about the api this should have is the console gui from creating tables.

1. Is the console gui uniform between databases?
2. How do we define tables/columns there?
3. Can it be always be used, or do we need an escape hatch in the form of raw SQL? In which cases?

One thing I'm a bit worried about is feature parity between databases. How do we handle default schemas, identity columns, timestamp/datetime, etc. Sometimes we explicitly want to test these differences as well, how should we approach this?

**Comment by soupi** [comment]
@sassela we had a brief discussion about this in https://github.com/hasura/graphql-engine-mono/pull/3901#discussion_r821411290

I wondering what would be a good way to keep this discussion and proposed solutions in mind.
