### ISSUE TITLE
Unable to access OpenAPI spec(Swagger documentation) through /api/swagger/json

### ISSUE THREAD

**Issue by pravin-d** [hasura/graphql-engine#7881]
### Version Information

Server Version: v2.0.9

### Environment
Docker image: hasura/graphql-engine:v2.0.9
Connected DB: postgres13

- Admin console enabled
- Admin secret enabled
- Rest APIs enabled

### What is the expected behaviour?
GET /api/swagger/json HTTP/1.1
X-Hasura-Role: admin
X-Hasura-Admin-Secret: xxxxx

should return OpenAPI spec documentation

### What is the current behaviour?
HTTP/1.1 404 Not Found
Content-Type: application/json
{
    "path": "$",
    "error": "resource does not exist",
    "code": "not-found"
}

### How to reproduce the issue?

1. Start hasura graphql server along with the above env settings
2. Access the following
GET /api/swagger/json HTTP/1.1
X-Hasura-Role: admin
X-Hasura-Admin-Secret: xxxxx

### Screenshots or Screencast
![Screenshot from 2021-12-04 02-16-33](https://user-images.githubusercontent.com/6554155/144673540-cfcbadaa-f169-49f7-8b95-54e9737ebaee.png)
![Screenshot from 2021-12-04 02-15-21](https://user-images.githubusercontent.com/6554155/144673545-fc51a4da-0364-482e-9bf0-6c14670bdb7f.png)

### If the bug is confirmed, would you be willing to submit a PR?
Very new to haskell and no idea on how hasura is implemented under the hoods. So I don't I can help

**Comment by alherd-by** [comment]
Swagger endpoint available since [v2.2.0](https://github.com/hasura/graphql-engine/releases/tag/v2.2.0)
Your version is 2.0.9

**Comment by jwarwick-delfi** [comment]
I have the same issue on hasura cloud version v2.3.1-cloud.1. 404 Client Error: Not Found for url: https://***.hasura.app/api/rest/json

**Comment by tirumaraiselvan** [comment]
@jwarwick-delfi Sorry about that. We are working on making this available on Cloud within a week.

**Comment by jwarwick-delfi** [comment]
thanks, it's working now!

**Comment by soorajshankar** [comment]
> thanks, it's working now!

Closing this issue as it is resolved now.
