### ISSUE TITLE
hdb_catalog.hdb_version doesn't have a primary key?

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#789]
Should we have a primary key on this table? I was trying this out with yugabyte which is a postgres flavour hence ran into this. 
In any case, we should add a primary key to the table anyway right? Why does it not already have one?
@arvi3411301 @rakeshkky @shahidhk

**Comment by shahidhk** [comment]
@0x777 ^

**Comment by shahidhk** [comment]
@coco98 This is not created by the cli. This table is managed by the server to keep track of it's internal schema version.

**Comment by 0x777** [comment]
It doesn't have a primary key because it can only ever have one row. The constraint guarantees it. Sure, we can add a primary key constraint too.

**Comment by 0x777** [comment]
Added with 11e7c3f9d694cee48749f0d0d2881b884aa057cd
