### ISSUE TITLE
Cannot have duplicate tables in different databases

### ISSUE THREAD

**Issue by 2bithacker** [hasura/graphql-engine#7895]
### Version Information

Server Version: v2.0.10
CLI Version (for CLI related issue):

### Environment

Docker image hasura/graphql-engine:v2.0.10.cli-migrations-v3

### What is the expected behaviour?

Being able to have tables with the same name/fields in separate databases.

### Keywords

duplicate tables multiple databases

### What is the current behavior?

When attempting to track the duplicated table in the second database, an error pops up saying:

```
Adding existing table/view failed
found duplicate fields in selection set for mutation root
```

### How to reproduce the issue?

1. Connect two separate PostgreSQL databases to Hasura
2. Track a table in one of the databases
3. Track a table of the same name/schema in the second database

In my particular case I'm attempting to connect a single Hasura instance to two databases used by Django web apps. In both apps, I'd like to be able to access the django_content_type table.

I'd expect different databases to be treated as separate namespaces to deal with these kinds of collisions.

### Please provide any traces or logs that could help here.

```json
{"type":"http-log","timestamp":"2021-12-07T22:15:20.991+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"path":"$.args[0].args","error":"found duplicate fields in selection set for mutation root: insert_django_content_type, update_django_content_type, delete_django_content_type, update_django_content_type_by_pk, delete_django_content_type_by_pk, insert_django_content_type_one","code":"unexpected"},"request_id":"bdb8d489-745d-4dcd-b253-82bf7fa4acb0","response_size":297,"query":{"resource_version":3,"args":[{"args":{"source":"Peering Manager","table":{"schema":"public","name":"django_content_type"}},"type":"pg_track_table"}],"source":"Peering Manager","type":"bulk"},"request_mode":"error"},"request_id":"bdb8d489-745d-4dcd-b253-82bf7fa4acb0","http_info":{"status":500,"http_version":"HTTP/1.1","url":"/v1/metadata","ip":"100.64.6.1","method":"POST","content_encoding":null}}}
```

### Can you identify the location in the source code where the problem exists?

No, I'm not familiar enough with the graphql-engine source.

### If the bug is confirmed, would you be willing to submit a PR?

Willing to, but it may take me some time to learn the source before doing so.

**Comment by dmoverton** [comment]
Version 2.1 beta supports putting different databases in separate namespaces. In 2.0 as a work-around you can give the conflicting table a `custom_name`.

**Comment by cj** [comment]
@dmoverton I can't find an example of how to do this, would you be able to provide one please?

**Comment by jordan-lumley** [comment]
Any updates on this? Also running into issues without multiple databases with the same table schemas.

**Comment by pcrosemurgy** [comment]
@dmoverton 
>Version 2.1 beta supports putting different databases in separate namespaces.

I am seeing this issue on v2.2.0. Can you elaborate on how this has supported? For example, is it supported by default or is there extra configuration needed in order to avoid duplicate table name collisions? Thanks!

**Comment by demonmind** [comment]
Any updates on this one. It is a pretty big pain when dealing with many DBs and one Hasura instance.

**Comment by jflambert** [comment]
I've hit a similar problem with Hasura 2.8.1

My metadata worked just fine with Hasura 2.7.0 but fails in 2.8.1 with this error

`found duplicate fields in selection set: mine_device_types, system_dtc_parameters, mine_contractors, mine_areas, mine_manufacturers, mine_machine_variables, mine_operation_hauling_routes, mine_shift_plans, mine_crew_shifts, mine_machine_hourmeter_type_definitions, mine_location_materials, mine_telemetry_variables, mine_device_associations, mine_machine_known_activities, mine_materials, system_measure_units, mine_telemetry_sensor_sets, mine_worker_machine_types, system_languages, mine_telemetry_event_conditions, mine_crew_rotations, mine_telemetry_event_sensor_sets, mine_work_shift_logs, mine_machine_models, mine_worker_departments, mine_machine_activities, mine_location_activities, mine_location_type_cycle_activities, mine_location_types, system_dtc_failure_messages, mine_machine_types, system_dtc_subsystems, system_can_protocols, mine_mining_companies, system_legacy_migration_logs, mine_telemetry_events, mine_location_levels, mine_telemetry_machine_model_variables, mine_machine_model_hourmeter_type_definitions, system_dtc_modules, mine_machine_engine_models, mine_machine_fleets, system_dtc_module_groups, mine_worker_titles, mine_workers, mine_worker_associated_devices, mine_telemetry_constants, mine_engine_models, mine_fleets, mine_telemetry_time_usage_event_definitions, mine_telemetry_sensors, mine_machine_hourmeter_types, mine_crews, mine_operation_hauling_route_materials, mine_shifts, mine_device_associated_devices, mine_operators, mine_devices, mine_machine_states, mine_locations, mine_machine_associated_devices, mine_location_states, mine_device_type_definitions, mine_operation_hauling_cycles, mine_location_type_cycles, mine_area_locations, mine_location_associated_devices, mine_machines, mine_telemetry_known_sensors, mine_location_activity_location_types, mine_device_associations_latest, mine_machine_activity_machine_types, mine_telemetry_sensor_set_sensors`

**Comment by geoffraymond** [comment]
I submitted a ticket with Hasura support to figure this one out. 

> Go to data -> manage -> edit data source. You'll need to both set a type prefix/suffix, and a root field namespace, prefix, or suffix.

![unnamed](https://user-images.githubusercontent.com/117678664/220738603-d60dd59f-e18e-4f9e-b9f2-f7f5b1336772.png)
