### ISSUE TITLE
support renaming tables, columns and relationships

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#79]

**Comment by dsandip** [comment]
@nukinuki FYI

**Comment by dsandip** [comment]
*Console wireframes*
1. Option to rename table name and column name in the `Modify` tab of a table:

![edit-table-column-name-1](https://user-images.githubusercontent.com/24300818/51961345-6f1c8800-2482-11e9-8f94-eebb198f4c50.png)

2. In-place edit for table name:

![edit-table-column-name-2](https://user-images.githubusercontent.com/24300818/51961372-83608500-2482-11e9-8198-5536a8dabdb9.png)

3. Option to edit relationship name:
![edit-relationship-name-1](https://user-images.githubusercontent.com/24300818/51961514-008bfa00-2483-11e9-9b12-08333b194f4e.png)

4. In-place edit for relationship name:

![edit-relationship-name-2](https://user-images.githubusercontent.com/24300818/51961401-97a48200-2482-11e9-9977-1e60eb860234.png)

@shahidhk @rikinsk please take a look at this. I am unsure about whether the option to edit the table name in `1` above is to be shown in the `modify` tab alone or in all tabs. I would prefer to limit it to the first option.

**Comment by shahidhk** [comment]
Editing the table name can go inside the Modify tab.

**Comment by tirumaraiselvan** [comment]
Also needs to update event trigger metadata. @rakeshkky

**Comment by nolandg** [comment]
Can anyone explain how this helps in deleting columns? The "can't delete column because of permissions" links here but...?  Is the only way to delete a column to through all the permissions for all rows removing that column first? I have 32 boxes to click then... :-(

**Comment by rikinsk** [comment]
@nolandg We are working on improving the console experience for this. It being tracked in #1593.As a worardounf till then you can drop the column via SQL in the RawSQL tab using `ALTER TABLE <table> DROP <column>` statement and checking the `Cascade metadata` checkbox. This will drop all permissions depending on the given column. Note that for row level permissions the entire permission will be dropped and not just clause containing the column

**Comment by Rigel772** [comment]
After I use : ```ALTER TABLE <table> DROP <column> ``` statement and checking the Cascade metadata checkbox.'
The table still shows in console...
