### ISSUE TITLE
Environment variables not expanded in Actions Transforms

### ISSUE THREAD

**Issue by motleydev** [hasura/graphql-engine#7905]
### Version Information

Version: graphql-engine:v2.1.0-beta.3

### Environment

OSS

### What is the expected behaviour?

I should be able to use an environment variable for the base_url path of an action.

### Keywords

base_url_path, environment variable, actions

### What is the current behaviour?

Referencing any environment variable renders "error [object, object]" in the preview path of an action transform.

### How to reproduce the issue?

1. Add a custom environment variable to one of the docker-compose manifests.
2. Provide specified docker image: graphql-engine:v2.1.0-beta.3
3. Attempt to reference the environment variable with `{{env_name}}` in the action handler field.

### Screenshots or Screencast

<img width="457" alt="CleanShot 2021-12-10 at 16 23 48@2x" src="https://user-images.githubusercontent.com/1203804/145598225-2a8017da-3e67-4759-bd76-d3e7d5d92a25.png">

![CleanShot 2021-12-10 at 16 24 10@2x](https://user-images.githubusercontent.com/1203804/145598300-29b722b4-9fc7-4645-a49e-e60820be4ac8.png)

**Comment by motleydev** [comment]
Update: IT does in fact "work" to use the URL, but the preview is broken

**Comment by abhi40308** [comment]
Hey @motleydev,

Considering the env vars could contain sensitive information, the env vars are not expanded in preview. You could provide mock env-vars in the context area which could be used for showing the preview as shown below

<img width="857" alt="Screenshot 2021-12-22 at 1 06 11 PM" src="https://user-images.githubusercontent.com/26903230/147053752-93e3e9be-b565-4bd9-b3ba-9da8fddee033.png">

**Comment by motleydev** [comment]
It should still not show "error/error" so perhaps another default value, maybe the env var name itself?
