### ISSUE TITLE
Hover on Relationships tab highlights unrelated cell

### ISSUE THREAD

**Issue by seanonthenet** [hasura/graphql-engine#7908]
This is a small but relevant UI tweak for the **Data** => **{{table}}** => **Relationships** tab where hover state on over a relationship highlights the adjacent Object / Array relationship when they aren't related at all. The highlight should only be over the current cell. 
Video:
https://user-images.githubusercontent.com/4939629/145628202-94088550-1851-44c5-9422-fe1b0dc051c8.mp4

**Comment by sauzzon** [comment]
I started working on this issue

**Comment by vijayprasanna13** [comment]
Closing this issue as the UI has undergone substantial changes and a new version of the relationship UI is available by default. Please feel free to open a new issue if you encounter any further problems
