### ISSUE TITLE
Action transforms params should support array transforms

### ISSUE THREAD

**Issue by motleydev** [hasura/graphql-engine#7911]
### Is your proposal related to a problem?

Many rest endpoints transform the value:

```js
{
 key: [value1, value2, value2]
}
```

Into the following syntax:

```
?key=value1&key=value2&key=value3
```
Being able to identify a query param as an array or having an ability to iterate over an array input with a Kriti template would help account for these use cases. Notably, an array of objects is often handled:

```
?name[0]=jack&name[1]=jill&last[0]=king&last[1]=queen
```
Having the ability to handle these cases would help integrate with a wider set of usecases.

### Describe alternatives you've considered

A boolean to indicate if a query param is an array which would render handle an index and value as params to a provided kitri template.

[ key ] [ value ] [isArray?]

**Comment by solomon-b** [comment]
I think the general solution we want here is a `fold`, or `reduce` in JS parlance, builtin for Kriti. We would need to sort out the syntax but it is totally doable.

> ?name[0]=jack&name[1]=jill&last[0]=king&last[1]=queen

You can do this with our current string templating syntax:

```
"?{{name[0]}}=jack&{{name[1]}}=jill&{{last[0]}}=king&{{last[1]}}=queen"
```

Where `name` and `last` are variables referencing arrays of strings..

**Comment by purugupta99** [comment]
We now have support for converting arrays to query params, following Kriti templates can be used to achieve the same:

| Query Template | Output |
|---|---|
| `{{ concat ([concat({{ range _, x := [\"apple\", \"banana\"] }} \"tags={{x}}&\" {{ end }}), \"flag=smthng\"]) }}`| `tags=apple&tags=banana&flag=smthng`  |
| `{{ concat ([\"tags=\", concat({{ range _, x := $body.input }} \"{{x}},\" {{ end }})]) }}` | `tags=apple%2Cbanana%2C` |
