### ISSUE TITLE
console: support new API for create remote relationships

### ISSUE THREAD

**Issue by abhi40308** [hasura/graphql-engine#7916]
### Version Information

Version: v2.1.0-beta.3

### Environment
OSS

### How to reproduce the issue?

1. Add a remote schema through `Remote Schema` tab
2. Go to `Data` tab, add a table, then go to `Relationships`
3. Define a [remote relationship](https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/remote-relationships/remote-schema-relationships.html) and save
4. Console breaks now on accessing the Relationships tab

### Related issues
#7906

**Comment by soorajshankar** [comment]
![image](https://user-images.githubusercontent.com/8408875/145764294-94c055bd-3382-4818-bd45-bef47c21fd74.png)

Keyword `definition` seem to be missing in `v2.1.0-beta.3` with remote relationships

**Comment by tirumaraiselvan** [comment]
Not required after https://github.com/hasura/graphql-engine/commit/bacadc30dad59619fb268820f12911d6c580c7f1
