### ISSUE TITLE
Hasura v2.1.0-beta.3 : If Cookie header is present, Hasura doesn't read the Authorization header and returns a "Missing authorization header in JWT authentication mode" error

### ISSUE THREAD

**Issue by jgoux** [hasura/graphql-engine#7924]
### Version Information

Server Version: v2.1.0-beta.3
CLI Version (for CLI related issue): v2.1.0-beta.3

### Environment

OSS

### What is the expected behaviour?

If the `header` key is present in the HASURA_GRAPHQL_JWT_SECRET variable, it should be used so Hasura knows where to read the token.

If the `header` key is not present in the HASURA_GRAPHQL_JWT_SECRET variable, Hasura should : 
1. read the Authorization header by default
2. if the Authorization isn't present, read the Cookie header and look for the default cookie name key I guess

### Keywords

jwt
cookie
authorization

### What is the current behaviour?

I think a bug was introduced [here](https://github.com/hasura/graphql-engine/blob/5726852c5414d9a0bcb1b50b439a964438ce0ae4/server/src-lib/Hasura/Server/Auth/JWT.hs#L427) by this [commit](https://github.com/hasura/graphql-engine/commit/f2437603989b5fb6cbe88d5a963f4d245b2cddc5).

I'm not a Haskell developer, but it seems like it gets the values for both the Cookie and the Authorization header and takes the first one that exists. In this case, it seems to be Cookie.

So if there is a Cookie header in a request, no matter its content, the Authorization header is ignored and we get this error : 

`Missing authorization header in JWT authentication mode`

### How to reproduce the issue?

1. Execute a query with only a working Authorization header with the Bearer token (it works)
2. Add a Cookie header with "test=test;" value
3. You now get the "Missing authorization header in JWT authentication mode" error

### If the bug is confirmed, would you be willing to submit a PR?

I did my best but I'm not familiar enough with the Haskell language.

**Comment by tirumaraiselvan** [comment]
@jgoux Could you send the value of `HASURA_GRAPHQL_JWT_SECRET` that is configured? (You can mask any sensitive info)

**Comment by jgoux** [comment]
@tirumaraiselvan 

This is the one we always used :
```
{"allowed_skew": 180, "type": "RS512", "key": "<redacted>"}
```

After noticing this bug I tried this variant without effect : 
```
This is the one we always used :
```
{"header": { "type": "Authorization"}, "allowed_skew": 180, "type": "RS512", "key": "<redacted>"}
```
```

**Comment by ecthiender** [comment]
> If the `header` key is not present in the HASURA_GRAPHQL_JWT_SECRET variable, Hasura should : 
>  1. read the Authorization header by default
>  2. if the Authorization isn't present, read the Cookie header and look for the default cookie name key I guess

You are right about 1. But for `Cookie` the config has to be set explicit. See docs here: https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt.html#header

**Comment by jgoux** [comment]
> > If the `header` key is not present in the HASURA_GRAPHQL_JWT_SECRET variable, Hasura should :
> > 
> > 1. read the Authorization header by default
> > 2. if the Authorization isn't present, read the Cookie header and look for the default cookie name key I guess
> 
> You are right about 1. But for `Cookie` the config has to be set explicit. See docs here: https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt.html#header

I think you're talking about the "default cookie name" part, yes I wasn't sure if you had a fallback or if you required an explicit key name for the cookie. 👍 

Maybe it's not clear enough but we don't use `Cookie` as a means for authorization in our case, we use the `Authorization` header (we always have been) but the changes introduced in beta.3 totally ignore this header if `Cookie` is present.

In our case `Cookie` is present but its content isn't authz related.

**Comment by ecthiender** [comment]
@jgoux ah I see. Got it. Thanks for the clarification. We are looking into the issue.

**Comment by tirumaraiselvan** [comment]
Should be fixed in v2.1.0, can you verify pls?

**Comment by jgoux** [comment]
Yep it's working now. 👍 

I saw that you reverted the changes, I think it would be great when you work on it again that we can explicitly opt-in to Authorization or Cookie headers following the `header` config in the HASURA_GRAPHQL_JWT_SECRET secret. I don't think it was taken into account when checking the headers, it was only used to pick the cookie's name.

**Comment by mgwedd** [comment]
I'm seeing this error after setting up `HASURA_GRAPHQL_JWT_SECRET` with an Auth0 API JWT secret config, generated using https://hasura.io/jwt-config/

<img width="1728" alt="Screen Shot 2022-10-24 at 1 19 00 PM" src="https://user-images.githubusercontent.com/34141289/197620931-5b7fe6c9-3337-46e0-9340-1b034ceb4940.png">

Is this related to the thread?

**Comment by Prabhdeep-Singh24** [comment]
I am seeing this error as well
`{"detail":{"connection_info":{"msg":null,"token_expiry":null,"websocket_id":"89fae8f3-a428-4a48-802d-581cdb84792c"},"event":{"detail":"Missing` 'Authorization' or 'Cookie' header in JWT authentication mode","type":"conn_err"},"user_vars":null},"level":"error","timestamp":"2023-08-08T01:02:35.071+0000","type":"websocket-log"}`

We use a jwk_url fro AWS cognito:

{       "claims_format": "stringified_json",       "jwk_url": "https://cognito-idp.us-west-2.amazonaws.com/POOL_ID/.well-known/jwks.json",       "type": "RS256",     "header": {"type": "Authorization"}}

I have also tried providing the public key from Cognito instead of the jwk_url, still get the same error
