### ISSUE TITLE
hasura v1.3.3 not supported apt-get command 

### ISSUE THREAD

**Issue by sweety-jhamb** [hasura/graphql-engine#7928]
### Version Information

Server Version:
CLI Version (for CLI related issue):v1.3.3

### How to reproduce the issue?

1.
2.
3.

### If the bug is confirmed, would you be willing to submit a PR?

while the latest image of hasura allows it. I need to use the earlier version only.
can anyone let me know the fix for ths

**Comment by rikinsk** [comment]
Hey.The issue you are facing is not clear with the details shared. Could you elaborate on what exactly is not working?

**Comment by rikinsk** [comment]
Closing this.Please feel free to reopen with some more details
