### ISSUE TITLE
Hasura v2.0.10: setup claims map `x-hasura-allowed-roles`, convert path variable from String to String Array

### ISSUE THREAD

**Issue by vctqs1** [hasura/graphql-engine#7935]
https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt.html#claims-map

Hi teams, I'm struggling at this step

Here is example JSON for my JWT token
```
{
   "org": "x-org"
}
```

when setup `claims-map` I want to assign path `$.org` to `x-hasura-allowed-roles`

EX: 

```
"x-hasura-allowed-roles":{"path":"[\"$.org\"]","default":[]}
```
and
```
"x-hasura-allowed-roles":{"path":"['$.org']","default":[]}
```

But It does not work and get message error like
```
Schema introspection query failed
Your requested role is not in allowed roles
```

![image](https://user-images.githubusercontent.com/30227910/146119519-7b4b5c74-cf6a-4862-b286-e58eaca24c88.png)

_Originally posted by @vctqs1 in https://github.com/hasura/graphql-engine/discussions/7934_

**Comment by vctqs1** [comment]
If I don't set default value, the message will be `

```
Schema introspection query failed
JWT claim does not contain x-hasura-allowed-roles

```

**Comment by SamirTalwar** [comment]
The path should be a string which references an array in the claims JSON. Removing the square brackets and the `"default"` should fix it.

I am going to close this issue due to its age. Please feel free to re-open it if it is still a concern.
