### ISSUE TITLE
Action Transforms: GET sends POST body and Content-Type header

### ISSUE THREAD

**Issue by Winwardo** [hasura/graphql-engine#7937]
Hi all, love the 2.1.0 release, congratulations.

### Version Information

Server Version: 2.1.0
CLI Version (for CLI related issue):

### Environment

Running on Heroku.

### What is the expected behaviour?

When I use the new Action Transforms, I wish to be able to send a regular GET request, without extra headers or body.

### Keywords

action transforms, get, post, headers

### What is the current behaviour?

When I use a GET Action, Hasura overrides any `Content-Type` header with `application/json` and sends a body. This breaks certain APIs (such as Stripe) who are expecting a GET request to not have a body, nor a `Content-Type` header.

In Stripe's case, because of either the header or body (I don't know which), the GET request is instead treated as a malformed POST request, and the request fails.

### How to reproduce the issue?

1. Create a new Action.
2. Set the webhook handler to one such as on webhook.site to test the request.
3. Set a custom `Content-Type` header 
![image](https://user-images.githubusercontent.com/840549/146188340-55d5b7ef-f7dd-47e2-ae98-88279c6c8ce4.png)
4. Add a request option transformation, and select GET. 
![image](https://user-images.githubusercontent.com/840549/146188373-adc27eeb-3ffa-45e1-98ae-3c01e6d15ed0.png)
5. OPTIONAL: Add a Payload Transformation, with a configured request body of `null`, or `[]` or `""`. If you leave it blank, or don't complete this step, Hasura will assume that, instead of sending no body at all, you intended to remove the Payload Transform and send through the current payload as the body.

## Without a Payload transform
![image](https://user-images.githubusercontent.com/840549/146188582-524b5253-cdc6-4d65-8b96-a8ac94e7ef0e.png)

You can see how this GET request has overridden the `content-type` header to be `application/json`, despite me setting it to `text/plain` in my custom headers.
It also has a raw content of the original request.

## With a Payload transform of `null`
![image](https://user-images.githubusercontent.com/840549/146188837-95bd9cb6-8931-4da6-97b2-a2d006a4b8dd.png)

Again, the `content-type` has been overridden with `application/json` and the body is set to the JSON value `null`. A body of `null` is different from not sending the body at all.

### Any possible solutions?

When action transform method type is set to GET, do not provide a `content-type` header or send any body whatsoever. Note that this is different from setting `content-type` or body to null or empty string - the mere presence of the keys may confuse the receiver.

Alternatively, do not make this a GET only difference, and always allow the transformation definition to clearly say "Do not send a body / particular headers."

### Can you identify the location in the source code where the problem exists?

I am not familiar with the source code, but my best guess would be line 496 in the Action executor:

https://github.com/hasura/graphql-engine/blob/master/server/src-lib/Hasura/GraphQL/Execute/Action.hs#L496

It looks like the code first stamps on the headers and body as if it were a POST, and then applies further transformations. The code should avoid adding the headers and body until we know for sure this is a POST request, or the transformation should be able to strip them later.

### If the bug is confirmed, would you be willing to submit a PR?

My Haskell is unfortunately not good enough to write the code myself.

**Comment by knenkne** [comment]
+1, getting the `404` error due to body field

**Comment by knenkne** [comment]
Would be great to get some ETA on it

**Comment by kkgosu** [comment]
> 

+1

**Comment by jesse-savary** [comment]
[Flagsmith](https://flagsmith.com) has the same issue with GET requests that contain a body. Looking forward to a fix!

**Comment by solomon-b** [comment]
> Would be great to get some ETA on it

We now have a PR in review to implement the backend changes and we are getting started on the frontend changes now. More info will be available when the frontend updates are further along.

**Comment by knenkne** [comment]
> > Would be great to get some ETA on it
> 
> 
> 
> We now have a PR in review to implement the backend changes and we are getting started on the frontend changes now. More info will be available when the frontend updates are further along.

Lovely!

**Comment by dvdthecoder** [comment]
Would be great to get an ETA , did this make to 2.2 release ?

**Comment by tirumaraiselvan** [comment]
@dvdthecoder This couldn't make it to the 2.2.0 release but it will definitely make it in a new release in about 2 weeks.

**Comment by dvdthecoder** [comment]
Thanks

**Comment by dvdthecoder** [comment]
Wha tis the current status on this

**Comment by dvdthecoder** [comment]
> @dvdthecoder This couldn't make it to the 2.2.0 release but it will definitely make it in a new release in about 2 weeks.

any progress on this one @tirumaraiselvan

**Comment by tirumaraiselvan** [comment]
This has been fixed and released in https://github.com/hasura/graphql-engine/releases/tag/v2.4.0-beta.1

You can now disable the body of a payload (in most GET scenarios), this will remove the `Content-Type` header as well:

![image](https://user-images.githubusercontent.com/8663570/156562921-dac0fb42-d56d-49bc-8a2e-9546bf96aac6.png)

**Comment by Winwardo** [comment]
I've just tested this, and can confirm I able to make a GET to Stripe to access a payment 👍 

Thank you for fixing this!

**Comment by dvdthecoder** [comment]
I also confirm that my get end points are now returning the right set of
values

**Comment by tirumaraiselvan** [comment]
Released in v2.4.0
