### ISSUE TITLE
insert or delete data from Hasura console produce errors

### ISSUE THREAD

**Issue by Edmartt** [hasura/graphql-engine#7949]
I'm still having this issue in version 2.0.10 in any moment.  When I deleted something from hasura console in the database like some rows I get the same error

{
    "statement": "SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_1_e\"  FROM  (SELECT  \"_0_root.base\".\"cash_balance\" AS \"cash_balance\", \"_0_root.base\".\"defined_benefit\" AS \"defined_benefit\", \"_0_root.base\".\"defined_contribution\" AS \"defined_contribution\", \"_0_root.base\".\"healthcare\" AS \"healthcare\", \"_0_root.base\".\"non_qualified\" AS \"non_qualified\", \"_0_root.base\".\"plan_401a\" AS \"plan_401a\", \"_0_root.base\".\"plan_401k\" AS \"plan_401k\", \"_0_root.base\".\"plan_409a\" AS \"plan_409a\", \"_0_root.base\".\"aprox_assets\" AS \"aprox_assets\", \"_0_root.base\".\"client_type\" AS \"client_type\", \"_0_root.base\".\"employees_number\" AS \"employees_number\", \"_0_root.base\".\"industry\" AS \"industry\", \"_0_root.base\".\"investment_broker\" AS \"investment_broker\", \"_0_root.base\".\"org_name\" AS \"org_name\", \"_0_root.base\".\"plan_sponsor\" AS \"plan_sponsor\", \"_0_root.base\".\"plan_type\" AS \"plan_type\", \"_0_root.base\".\"sponsor_email\" AS \"sponsor_email\", \"_0_root.base\".\"actuary_id\" AS \"actuary_id\", \"_0_root.base\".\"auditor_link_id\" AS \"auditor_link_id\", \"_0_root.base\".\"auditor_referral_id\" AS \"auditor_referral_id\", \"_0_root.base\".\"auditor_status_id\" AS \"auditor_status_id\", \"_0_root.base\".\"id\" AS \"id\", \"_0_root.base\".\"pgi_score\" AS \"pgi_score\", \"_0_root.base\".\"plan_auditor_id\" AS \"plan_auditor_id\", \"_0_root.base\".\"three_provider_id\" AS \"three_provider_id\", \"_0_root.base\".\"user_id\" AS \"user_id\"       ) AS \"_1_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"public\".\"organization\"  WHERE ('true')     ) AS \"_0_root.base\"     LIMIT 100 ) AS \"_2_root\"      ",
    "prepared": true,
    "error": {
        "exec_status": "FatalError",
        "hint": null,
        "message": "relation \"public.organization\" does not exist",
        "status_code": "42P01",
        "description": null
    },
    "arguments": []
}

This is happening every time and I need to be active all the day reloading the database from hasura and sometimes the database and metadata together

All I do is delete or insert from the console some rows and that's the result. Sometimes just refreshing the web is enough but sometimes I need to reload database and metadata as I mentioned before

_Originally posted by @Edmartt in https://github.com/hasura/graphql-engine/issues/7087#issuecomment-996209723_

**Comment by rikinsk** [comment]
Hey, the fact that reloading the webpage fixes this seems to indicate this might not be a trivial error and we'll need more details to investigate. Could you start with sharing how you are running hasura i.e. using Hasura cloud, docker on local system, etc. Do yo happen to to have any event triggers defined for the table?

**Comment by Edmartt** [comment]
> 

Thanks for your answer

- Well, right now everything is running on kubernetes self hosted, including db
- Just one table has some trigger for scrap some pdf data, but it was happening before this change was applied
- I have seen this happens always when I change something (anything) direcly on the graphical console, but if I apply metada from hasura console (cli) this not happening. Sometimes its printing inconsistent metadata, but sometimes just says nothing and the fix until now has been just reload metadata from graphic console including the reload all metadata and database check
- At this point the hasura console(cli) doesn't work for the hasura metadata apply --endpoint option, so I have to do it manually as I mentioned

**Comment by Edmartt** [comment]
I'm still waiting answer about this. This is affecting our project. Even today this happened again. We get query results like 1 row and checking in the database this record exists, but sometimes we make the same query and gets 4 records previously added that dont appear to come from anywhere. We were today debugging for hours and we don't have solutions

**Comment by lucarestagno** [comment]
@Edmartt has this issue been solved?
