### ISSUE TITLE
Adding comment issue in v2.1.1

### ISSUE THREAD

**Issue by marcosfons** [hasura/graphql-engine#7951]
### Version Information

I've upgraded graphql-engine to `v2.1.1`.

### What is the expected behaviour?

I should be able to add a comment on a given column table.

### Keywords

Comment, relation does not exist

### What is the current behaviour?

I receive an error each time I try to modify a column to add a new comment.

### How to reproduce the issue?

1. Create a basic table with a column
2. Try to modify the column with a new comment

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/22989734/146556644-494f4167-8321-4926-9cee-202c2affbed3.png)
![image](https://user-images.githubusercontent.com/22989734/146556712-590f0033-fce4-46d2-bf5c-2b79eadf8ad4.png)

### Please provide any traces or logs that could help here.

<details>
<summary>Error message</summary>

```json
{
    "internal": {
        "statement": "comment on column \"public\".\"bool\" is E'Indicates whether it is a recurrent plan or not';",
        "prepared": false,
        "error": {
            "exec_status": "FatalError",
            "hint": null,
            "message": "relation \"public\" does not exist",
            "status_code": "42P01",
            "description": null
        },
        "arguments": []
    },
    "path": "$[0]",
    "error": "query execution failed",
    "code": "postgres-error"
}
```

</details>

### Any possible solutions?

In my tests the errors returned indicate that the code is trying to add a comment on `<schema>.<column type>`. And I think that it should be `<schema>.<table name>.<column name>`.

**Comment by marcosfons** [comment]
### Possible solution

I searched on the codebase and I think that I figured out where the problem is.

In the function `getSetCommentSql` definition the 6th parameter it's the `functionName`. If it's defined then the code enters in the first `if` and try to comment with a function comment template.

https://github.com/hasura/graphql-engine/blob/175391bb8841baf4fbd31f47722ef0670f89b7d2/console/src/dataSources/services/postgresql/sqlUtils.ts#L665-L687

In the next block of code it's called the `getSetCommentSql` function passing the `colType` as the 6th parameter (`functionName`).

https://github.com/hasura/graphql-engine/blob/175391bb8841baf4fbd31f47722ef0670f89b7d2/console/src/utils/migration/utils.ts#L254-L272

So the `colType` evaluates to true inside `getSetCommentSql` and the function tries to comment using a function comment template.

A possible solution would be remove the `colType` in the `getSetCommentSql` function call. But I don't know if this will impact another area of the code.

**Comment by Smirow** [comment]
Can confirm the behavior: comments works fine on tables not on columns.

**Comment by afmotta** [comment]
Thanks folks for reporting this and in particular to @marcosfons for analyzing the issue and writing a PR.

You can see the fix [here](https://github.com/hasura/graphql-engine/commit/19c7002a7b37a71df2f9d074d46757cbd24461cf).

We'll improve the signature of the getSetCommentSql asap, to make it more robust.
