### ISSUE TITLE
Accessing Context variables in event trigger transforms

### ISSUE THREAD

**Issue by creatorrr** [hasura/graphql-engine#7953]
_Server Version: 2.1.1_

In the configuration section for the new event trigger transformations, how can we access Context variables (defined under the Sample Context)? According to the documentation for action transforms, one has to use `$session_variables` but inside the event trigger transforms body, that throws an error:

```
InvalidPathCode: Path Lookup Error: "$session_variables.A" 
```

![2021-12-18 (4)](https://user-images.githubusercontent.com/931887/146636013-855acc23-5a99-4bb9-827b-d4bda97dcd7b.png)
![2021-12-18 (3)](https://user-images.githubusercontent.com/931887/146636022-872ccf67-a6d8-433d-a241-b16d997ac21c.png)

**Comment by abhi40308** [comment]
Hey @creatorrr, you can access the session variables using `session_variables['A']` format, in this case it should be:
```
{
  "a": {{$session_variables['A']}}
}
```
Please let us know if it fixes your issue, we'll try improving the documentation around this feature.

**Comment by creatorrr** [comment]
Same problem with that syntax. :(
![2021-12-21](https://user-images.githubusercontent.com/931887/146920355-96aa87e5-ea23-49a8-8802-7495e8e6e1d5.png)

**Comment by abhi40308** [comment]
@creatorrr thanks for reporting! I can replicate it now. The issue seems to be with capital letters in the `session_varialbes`, so this is working for me:
```
{
  "a": {{$session_variables['a']}}
}
```
<img width="757" alt="Screenshot 2021-12-22 at 11 30 31 AM" src="https://user-images.githubusercontent.com/26903230/147043315-9efc7d66-473e-4d10-84e2-8a795cdd680a.png">

<img width="726" alt="Screenshot 2021-12-22 at 11 30 54 AM" src="https://user-images.githubusercontent.com/26903230/147043338-5f467ff6-f9e6-437b-8b27-8f6a280dd3b4.png">

We'll look into this issue, till then hopefully you could use the above-mentioned alternate way.

**Comment by creatorrr** [comment]
Gotcha, thanks @abhi40308 !

**Comment by creatorrr** [comment]
@abhi40308 - what about environment variables? I can't seem to access those using `session_variables` :(

**Comment by abhi40308** [comment]
@creatorrr  Yes, for env vars they are currently only supported in the `{{$base_url}}`, and cannot be referenced in other places, but we have an open [issue](https://github.com/hasura/graphql-engine/issues/7910) which we are tracking, and looking into supporting this in future :)

**Comment by creatorrr** [comment]
ah gotcha! Should I close this issue for now then?

**Comment by solomon-b** [comment]
@creatorrr session variables are actually converted to lowercase internally. You should be able to reference the `A` session variable like this:
```
{
  "a": {{$session_variables.a]}}
}
```

This should unblock you for the moment and we are looking into more long term solutions to make this less confusing.

**Comment by paritosh-08** [comment]
With the commit https://github.com/hasura/graphql-engine/commit/bc74046ab26350ebf606b2b83296e2632a5ff10a, we can now use the function `getSessionVariable` to reference the session variables. This function takes a string (can be a literal string or a path, see example) and looks up in a case insensitive manner. For example, we can do the following:
```
{
  "a": {{getSessionVariable "A"}},
  "b": {{getSessionVariable $body.secretVarName}}
}
```
And this should return:
``` JSON
{
  "a": "newvalue",
  "b": "someSecretValue"
}
```

Please note that `$body.secretVarName` is a string in the above example. If it is not, then it will throw an error.
