### ISSUE TITLE
Hasura v2.1.1: parse-failed for remote source relationships

### ISSUE THREAD

**Issue by vshelke** [hasura/graphql-engine#7954]
### Version Information

Server Version: v2.1.1
CLI Version (for CLI related issue): v2.1.1

### Environment

OSS

### What is the expected behaviour?

A remote source relationship should have been created across tables between separate databases.
Referring to the [docs](https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/remote-relationships/remote-source-relationships.html) here to achieve the required result.

### Keywords

Remote source relationships
create_remote_relationship
parse-failed

### What is the current behaviour?

Get a `parse-failed` error with below response
```json
{
    "path": "$",
    "error": "create_remote_relationship expects exactly one of: remote_schema, definition",
    "code": "parse-failed"
}
```

### How to reproduce the issue?

1. Added two PostgreSQL databases
2. `default` database has `user` table
3. `ecommerce` database has `order` table
4. Sent below request
`POST`:` http://localhost:8080/v1/query`
```json
{
  "type": "create_remote_relationship",
  "args": {
    "name": "ordered_by_user",
    "source": "ecommerce",
    "table": "order",
    "remote_source": {
      "relationship_type": "object",
      "field_mapping": {
        "ordered_by_user_id": "id"
      },
      "source": "default",
      "table": "user"
    }
  }
}
```

### Screenshots or Screencast

![Screenshot 2021-12-18 at 4 30 25 PM](https://user-images.githubusercontent.com/15365654/146638646-c6f0d840-0112-4c54-92c6-cc69a6ae65d6.png)

**Comment by vshelke** [comment]
Can anyone please help with resolving this issue ?

**Comment by jjlpinto** [comment]
I can reproduce this error in v2.1.1.

I am able to create the relationship in a v2.1.0 server using the /v1/metadata endpoint, but it seems to have been removed in v2.1.1.

Sent below request
POST: http://localhost:8080/v1/metadata
```json
{
  "type": "create_remote_relationship",
  "args": {
    "name": "ordered_by_user",
    "source": "ecommerce",
    "table": "order",
    "to_source": {
      "relationship_type": "object",
      "field_mapping": {
        "ordered_by_user_id": "id"
      },
      "source": "default",
      "table": "user"
    }
  }
}
```

**Comment by rikinsk** [comment]
Docs updated

**Comment by jonesty** [comment]
@rikinsk @jjlpinto I'm following the latest documentation using v2.2.0 and getting the following response when posting to `/v1/metadata`. **The same request works fine on v2.1.0.** Any ideas?
```
{
    "path": "$",
    "error": "unknown metadata command \"create_remote_relationship\"; \"create\" was not recognized as a valid backend name",
    "code": "parse-failed"
}
```

**Comment by jjlpinto** [comment]
@jonesty That's what I tried to communicate in my previous post.  They removed the API endpoint to create remote source relationships in 2.2.0 and you cannot create it in the newer versions using the API.  It is an active bug and I am unsure why they closed this issue.

My workaround has been to create the source relationship using a 2.1.0 container and then using the metadata it creates in 2.2.0 container.

**Comment by jonesty** [comment]
@jjlpinto Thanks, it's definitely still an issue. Not being able to create remote source relationships effectively blocks us from using multiple database. I tried your workaround but I then get an error page when viewing the Relationships tab on the source table. It appears to have put the meta in a weird state.

@rikinsk Can we please reopen this one? Any chance it can be fixed in the next release?

**Comment by jonesty** [comment]
@jjlpinto FYI, I've just upgraded to v2.2.1, which includes the ability to add these relationships via the console and it seems to work.
