### ISSUE TITLE
"Error during validation:" when defining action request transform using env var for "Webhook (HTTP/S) Handler"

### ISSUE THREAD

**Issue by beepsoft** [hasura/graphql-engine#7959]
### Version Information

Server Version:  v2.1.1

### Environment

macOS, docker

### What is the expected behaviour?

I would like to be able to define an action with a request transform without errors, when using environment variables for "Webhook (HTTP/S) Handler"

### Keywords

actions, request transform, environment variable

### What is the current behaviour?

When creating an action with a request transform, the Hasura console executes a `test_webhook_transform` call, which fails resolving the environment variable for "Webhook (HTTP/S) Handler" and a red error is displayed on the page. The `{{NHOST_AUTH_ENDPOINT}}` is correctly set and the action and the request transformation actually work when called, but I have this error in the action definition page:

![image](https://user-images.githubusercontent.com/1926265/146673475-9d269b42-344d-466e-a77e-3a1bc61db84f.png)
![image](https://user-images.githubusercontent.com/1926265/146673480-81239565-c197-4c2c-8866-af65c79c94df.png)
![image](https://user-images.githubusercontent.com/1926265/146673487-cbf9ee7d-e1cf-4529-bfe2-f1efd06b4adb.png)

In the Chrome Network console I can see this request:

```json
{"type":"test_webhook_transform","args":{"webhook_url":"{{NHOST_AUTH_ENDPOINT}}","body":{"action":{"name":"signUpEmailPassword"},"input":{"args":{"email":"email","password":"password"}}},"env":{},"session_variables":{"x-hasura-admin-secret":"xxx"},"request_transform":{"url":"{{$base_url}}/signup/email-password","query_params":{},"template_engine":"Kriti"}}}
```

and response:

```json
{"error_code":"InvalidPathCode","source_position":{"end_column":20,"start_line":1,"end_line":1,"start_column":1},"message":"Path Lookup Error: \"NHOST_AUTH_ENDPOINT\""}
```

**Comment by soorajshankar** [comment]
Hey @beepsoft, 
Thanks for reporting the issue!

Hasura GraphQL Engine will use the sample context for real time validation. (considering the server env could contain sensitive information, actual server env values are not resolved during real time validation)
Could you check if you have a sample ENV variable specified in the sample context section? (as shown below)

![image](https://user-images.githubusercontent.com/8408875/146675679-b48b1af9-a01c-4043-9e77-717ee96a30d8.png)

**Comment by beepsoft** [comment]
@soorajshankar yes, if I specify the env var in the Sample Context, then it is OK, thanks for the tip! It would be great if somehow the error would suggest setting this value. The `[object Object]` thing is hard to understand. 😃

**Comment by soorajshankar** [comment]
Thanks @beepsoft for confirming!

We will fix the error message soon 😃
