### ISSUE TITLE
Error while connecting to remote SQL server from hasura inside docker

### ISSUE THREAD

**Issue by Dhanya1995** [hasura/graphql-engine#7966]
Hi,

I am trying to connect to an SQL server from Hasura. The SQL Server is installed in a remote machine, which allows remote connection. Also, the firewall allows connections.  

Connection string:
**Driver={ODBC Driver 17 for SQL Server};Server=tcp:ipaddress of remote server,1433;Database=dbname;Uid=uname;Pwd=pwd**   

  I am getting the following error. 

[Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired[Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x102[Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections.

How can I resolve this issue? Thank you .

**Comment by thiagodamas** [comment]
The SQL its accessible from the docker host? The DB IP address its in the CIDR range?

**Comment by rikinsk** [comment]
@Dhanya1995  Is this still an issue?
