### ISSUE TITLE
cli: hasura migrate create <my_migration> fails if no content is passed.

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#7971]
### Version Information

Server Version: 2.1.0
CLI Version (for CLI related issue): 2.1.0

### Environment

OSS

### What is the expected behaviour?

running the following command should create a new, empty up and down migration:
```bash
hasura migrate create my_migration
```

### Keywords

hasura migrate create

### What is the current behaviour?

Instead we face the following error message:
```bash
level=fatal msg="error creating migration files: none of the files has been set with data"
```
### How to reproduce the issue?

1.run the command above

### Any possible solutions?

This can be worked arround by passing the `--up-sql` flag like so:
```bash
hasura migrate create my_migration --up-sql """"
```
note the 4 double quotes

**Comment by sourcec0de** [comment]
@BenoitRanque Thank you for this :)
