### ISSUE TITLE
Why in your actions example (codegen and blog post) your endpoints aren't protected?

### ISSUE THREAD

**Issue by Edmartt** [hasura/graphql-engine#7972]
### Discussed in https://github.com/hasura/graphql-engine/discussions/7965

<div type='discussions-op-text'>

<sup>Originally posted by **Edmartt** December 22, 2021</sup>
I'm talking about this https://hasura.io/docs/latest/graphql/core/actions/codegen/python-flask.html#actions-codegen-python-flask

Well, I've been working with Hasura for tha last months and I like it a lot but I'm curious about this, cause I implemented that example for a project and the update password allows to anybody to update users password and this is because the endpoint is unprotected, but if I protect it with JWT authorization, from Hasura I can't update the password cause it asks for Authorization header, so, I hope you can help on this. Thanks in advance</div>

**Comment by arjunyel** [comment]
Hi friend, I replied to your discussion post but basically with the examples we try to make them as simple as possible. To secure your action endpoint you can use something like a secret password via headers https://hasura.io/docs/latest/graphql/core/actions/action-handlers.html#restrict-access-to-your-action-handler
