### ISSUE TITLE
GraphQL Field Names not handled correctly in the data grid 

### ISSUE THREAD

**Issue by Smirow** [hasura/graphql-engine#7974]
### Version Information

Server Version: 2.1.1
### Environment

Docker

### What is the expected behaviour?

Should be able to sort by columns in the data grid with the specified field name.

### Keywords

Field Name, column name, does not exist

### What is the current behaviour?

The field name is correctly displayed in the data grid, however pressing on the sort arrows will provoke an error "<field_name> does not exit" as it seems to be looking for the column named after the field name and not the actual column name.

![image](https://user-images.githubusercontent.com/16503412/147512504-573d6fb8-4c2c-4cfb-a324-8a5f7fa2547c.png)
![image](https://user-images.githubusercontent.com/16503412/147512523-aac3bd10-5de8-46ee-b746-e68c9439b351.png)

### How to reproduce the issue?

1. Create a field name for a column
2. Try to sort by this column in the data tab

### Screenshots or Screencast

See above

### Please provide any traces or logs that could help here.

NA

### Any possible solutions?

NO

### Can you identify the location in the source code where the problem exists?

NO

### If the bug is confirmed, would you be willing to submit a PR?

NO

**Comment by xomaczar** [comment]
Besides broken sorting, the edit/create duplicate views for a particular data row fails to load data for fields with custom graphql field name.
