### ISSUE TITLE
Boolean expression error in the WHERE clause.

### ISSUE THREAD

**Issue by Svancara** [hasura/graphql-engine#7976]
Boolean expression error in the WHERE clause.

'A **OR** B' is translated to 'A **AND** B'

Example:

query MyQuery {
  c2ex_equity_daily(where: {systemid: {_eq: "13202557"}, _or: {systemid: {_eq: "21522544"}}}) {
    datetime
  }
}

is converted to the AND expression:

SELECT
  coalesce(json_agg("root"), '[]') AS "root"
FROM
  (
    SELECT
      row_to_json(
        (
          SELECT
            "_1_e"
          FROM
            (
              SELECT
                "_0_root.base"."datetime" AS "datetime"
            ) AS "_1_e"
        )
      ) AS "root"
    FROM
      (
        SELECT
          *
        FROM
          "public"."c2ex_equity_daily"
        WHERE
          (
            (
              ("public"."c2ex_equity_daily"."systemid") = (('13202557') :: bigint)
            )
            AND (
              ("public"."c2ex_equity_daily"."systemid") = (('21522544') :: bigint)
            )
          )
      ) AS "_0_root.base"
  ) AS "_2_root"

**Comment by rikinsk** [comment]
the _or operator expects an array of expressions  as explained in the note [here](https://hasura.io/docs/latest/graphql/core/api-reference/graphql-api/query.html#orexp). 

The following is the query you are looking for:

```
query MyQuery {
  c2ex_equity_daily(
    where: {
      _or: [
        {systemid: {_eq: "13202557"}},
     	{systemid: {_eq: "21522544"}}   
      ] 
    }
  ) {
    datetime
  }
}
```
