### ISSUE TITLE
Hasura v2.1.1 remote schema customize type prefix error when use it as an argument

### ISSUE THREAD

**Issue by vuongxuongminh** [hasura/graphql-engine#7977]
### Version Information

Server Version: v2.1.1

### Environment

OSS

### What is the expected behaviour?

I have remote schema with customized type prefix: `api_`, when I execute this query:

```graphql
query CallApi($arg: api_client_args) {
    api_client(args: $args) {
          id
    }
}
```

The server will cause an error with the message: 

```
"message": "variable "args" is declared as api_client_args, but used where client_args is expected"
```

In beta version `v2.1.0-beta.1` it work fine.

### How to reproduce the issue?

1. Add remote schema in console UI 
2. Modify remote schema had added before with type prefix 
3. Create graphql query have input args have type prefixed and execute.

**Comment by dmoverton** [comment]
Fixed by https://github.com/hasura/graphql-engine/commit/8eca322b941dee9c505b1cdcf605ae0392d1922d

**Comment by commandodev** [comment]
@dmoverton - I've just come across an instance of this behaviour on v2.36.3.

I can see the prefix variable name being sent to the remote schema.

Should I raise another bug?
