### ISSUE TITLE
Cannot add new role in permissions table

### ISSUE THREAD

**Issue by yuta-ike** [hasura/graphql-engine#7983]
### Version Information

Server Version: 2.1.1
CLI Version (for CLI related issue):

### Environment
OSS

### What is the expected behaviour?
We want to add new role.
We can add new role in `/schema/:schema/tables/:table/permissions` by editing `Enter new role` textbox.
![image](https://user-images.githubusercontent.com/38308823/147853560-6c417e43-5fc1-4704-bce4-f6895760fee4.png)

### Keywords
console, permission, role

### What is the current behaviour?
When I edit `Enter new role` textbox, nothing happens. We have no way to add new role.

### How to reproduce the issue?

1.
2.
3.

### Can you identify the location in the source code where the problem exists?
- https://github.com/hasura/graphql-engine/commit/412194ad13bd9046bf9d5efb70c49ba0e5c1350c

### If the bug is confirmed, would you be willing to submit a PR?
Yes.

**Comment by soorajshankar** [comment]
Hey @yuta-ike 👋🏼 ,
Thanks for reporting this issue! 

I was trying to replicate this issue but it seem to be working with v2.1.1 (attaching the screencast)

https://user-images.githubusercontent.com/8408875/147904405-5d160e3b-eed2-453b-9340-968eb55dbe1a.mov

Am I missing something here?

**Comment by yuta-ike** [comment]
Ah! I see.
I didn't notice at all that I should click red "X" in a table after input new role name...!
Thank you for your kind explanation.
