### ISSUE TITLE
add contributing guides

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#80]
Add `CONTRIBUTING.md` to `cli/`, `server/` and `console/`

**Comment by shahidhk** [comment]
console is pending @praveenweb @wawhal 

server added in https://github.com/hasura/graphql-engine/commit/79d7b497c993bf6bb3a81a4cd4b3e3eae3435211

**Comment by praveenweb** [comment]
console added in 32750d65fb0f6409ec4927cd79665338aa11517f
