### ISSUE TITLE
Database drop down does not show database while creating trigger

### ISSUE THREAD

**Issue by MiteshDhiranAllscripts** [hasura/graphql-engine#8007]
### Version Information

Server Version:
CLI Version (for CLI related issue):

### Environment

 
Hasura in Docker connecting t0 SQL server database
### What is the expected behaviour?
While creating trigger - Database drop down does not show database, it should show the database.

**Comment by rikinsk** [comment]
Hi. This is because event triggers are currently not supported for SQL Server databases. You can track the progress on that at https://github.com/hasura/graphql-engine/issues/7228
