### ISSUE TITLE
Setting column's GraphQL Field Name to the same as the column name will render `NULL` values in data browser.

### ISSUE THREAD

**Issue by elitan** [hasura/graphql-engine#8020]
### Version Information

Server Version: 2.1.0

### Environment

https://www.nhost.io/ (OSS)

### What is the expected behavior?

Hasura Console should render data even if the column's GraphQL Field Name is set to the same name as the column name.

### Keywords

GraphQL Field Name null

### What is the current behavior?

If a column's GraphQL Field Name is set to the same name as the column the data browser will render `NULL`.

### How to reproduce the issue?

1. Create a table with ID UUID (from frequently used columns)
2. Set the GraphQL Field Name of the `id` column to `id`
3. Insert a data row
4. Look at the data browser and see that IDs are rendered as `NULL`.

### Screenshots or Screencast

https://www.loom.com/share/28151b9d883b4df89124928fb7e76824

### If the bug is confirmed, would you be willing to submit a PR?

Sure.

**Comment by BenoitRanque** [comment]
Able to reproduce this in a simple hasura cloud project.
Interestingly this only happens when the id column is a `UUID`

**Comment by elitan** [comment]
Same issue for text field `role`:

![image](https://user-images.githubusercontent.com/331818/150949662-bb950c74-bcdc-4f2c-8578-4f1d1cf032af.png)

**Comment by elitan** [comment]
This was fixed in v2.2.0
