### ISSUE TITLE
Console data editor does not populate fields with existing data when a custom field name is set

### ISSUE THREAD

**Issue by afefer** [hasura/graphql-engine#8021]
### Version Information

Server Version: 2.1.1
CLI Version (for CLI related issue): 2.1.1

### Environment

Linux x64

### What is the expected behaviour?

When editing a row, the Hasura data browser should automatically pre-populate the fields with the data that's already in the database:

![image](https://user-images.githubusercontent.com/3399494/149239100-626decae-257e-4c58-ab4a-3e276a5e0c7c.png)

![image](https://user-images.githubusercontent.com/3399494/149239128-499ae089-5690-4220-bcb9-becb6d47669f.png)
 
### Keywords

console custom field names missing data edit row

### What is the current behaviour?

If you set a custom field name for a particular column:

![image](https://user-images.githubusercontent.com/3399494/149239288-b93d81f0-8b8e-4b78-b3ab-1f13cfd1c2a1.png)

And with the table pre-populated with some data:

![image](https://user-images.githubusercontent.com/3399494/149239326-7e812e2f-bd45-4a1c-99d6-8e8e45e34738.png)

When you click "edit", all fields with custom names don't have their existing data correctly pre-populated (set to NULL).

![image](https://user-images.githubusercontent.com/3399494/149239380-b0de6149-6d5d-45d5-92e0-79676feab9f9.png)

### How to reproduce the issue?

1. Create a table
2. Add some data to it
3. Assign a custom GraphQL field name to one of the columns
4. Open the row for editing. None of the fields with custom names will have their data populated.

**Comment by afefer** [comment]
Note this issue occurs both in a local console launched by the CLI, and also a console running directly on the server.

**Comment by Varun-Choudhary** [comment]
Thanks @afefer for reporting the issue. It is resolved now.

**Comment by afefer** [comment]
Awesome! Thanks for the really quick turnaround on this @Varun-Choudhary.
