### ISSUE TITLE
CLI 2.1.1 does not read remote schemas metadata from separate files

### ISSUE THREAD

**Issue by davydkov** [hasura/graphql-engine#8022]
### Version Information

Server Version: 2.1.1
CLI Version (for CLI related issue): 2.1.1

### What is the expected behaviour?

CLI `v2.1.0-beta.3` allows to split monstreous (in our case) `remote_schemas.yaml` to separate folders:

```
metadata
 remote_schemas
  graph1
   permissions
    role1.graphql
    role2.graphql
    permissions.yaml
  graph2
   permissions
    role1.graphql
    role2.graphql
    permissions.yaml
  remote_schemas.yaml
```

This was SUPER-cool.
With some combination of commit hooks, prettier and [format-graphql](https://github.com/gajus/format-graphql) we finally get reviewable git diffs.
We drop our in-house "merge-all-files-to-remote_schemas.yaml", opened a bottle of champagne and celebrated.

We expected next version of CLI does support this format further, or at least fails with some meaningful message.

### What is the current behaviour?

We got strange local dev issues, and found out that [commit 0c7e23312](https://github.com/hasura/graphql-engine/commit/0c7e233125de0575f28672fcc5058a2b5e61c2da) reverted our beloved feature in [2.1.1](https://github.com/hasura/graphql-engine/releases/tag/v2.1.1).

We restore from the ashes our tool and merge schemas manually, but was this revert intentional? Do we get it back?

**Comment by miradnan** [comment]
+1

**Comment by scriptonist** [comment]
@davydkov this was a beta feature that was rolled back in stable w.r.t to some critical feedback. 
ref: https://github.com/hasura/graphql-engine/blob/master/CHANGELOG.md#v210

**Comment by davydkov** [comment]
@scriptonist thank you!

Are there any plans to give it another shot?
I think we can close this issue, right?

**Comment by scriptonist** [comment]
@davydkov Yes, will revisit this taking into account all the feedback.
