### ISSUE TITLE
mysql database: expected a catalog version <=37, but the current version is 47

### ISSUE THREAD

**Issue by cyan-T** [hasura/graphql-engine#8023]
I use MySQL as database, so I followed the tutorial and got the image to run at local container: 

`image: hasura/graphql-engine:pull5655-633f084f`

The container started failed, with the log as following:

```
{"type":"startup","timestamp":"2022-01-13T06:19:33.957+0000","level":"error","detail":{"kind":"catalog_migrate","info":{"path":"$","error":"Cannot use database previously used with a newer version of graphql-engine (expected a catalog version <=37, but the current version is 47).","code":"not-supported"}}}
Connected to MySQL!
```

I refered previous similar issues and changed graphql-engine image version to v1.3.3. Then failed again, because it didn't known the option "--mysql-host " .

What can I do ?

**Comment by cyan-T** [comment]
Change to hasura/graphql-engine:v2.1.0-beta.2, still the error `Invalid option `--mysql-host'`

**Comment by rikinsk** [comment]
MySQL is not supported in `hasura/graphql-engine:v2.1.0-beta.2` and hence you are seeing the invalid option error. 

Regarding the original error you mentioned, it seems like you are trying to run the MySQL preview build i.e. `hasura/graphql-engine:pull5655-633f084f` connected to PG DB that was connected to a more recent Hasura version. Thats the reason for a catalog version error. i.e. the preview is aware of metadata catalog version uptill 37 but your db has version 47.

To try out MySQL I would recommend you set up a dedicated Hasura instance by following the steps described [here](https://hasura.io/docs/latest/graphql/core/guides/mysql-preview.html#mysql-preview). Do note that the MySQL preview build does not support all the latest features of Hasura.

**Comment by cyan-T** [comment]
I followed this `MySQL priview` tutorial when I tried to deploy it at first time and just again. Both  time I deleted old graphql-engine and postgres containers as first, then deleted their images.  It didn't worked. Should I change any arguments in docker-compose.yaml?

**Comment by cyan-T** [comment]
I changed the two lines in docker-compose.yaml and it worked, but can't use HASURA_GRAPHQL_ADMIN_SECRET. 
```
image: postgres:11
- db_data:/var/lib/postgresql11/data
```

**Comment by rsd1122** [comment]
We recently launched our new MySQL alpha integration 
https://hasura.io/docs/latest/databases/mysql/index/

It has support for queries, table relationships and permissions. Support for mutations is coming soon.

Please reach out to me if you would like to be a part of the early-access slack channel where we post the latest builds and updates.

(Note: The previous version has been deprecated)
