### ISSUE TITLE
Console does not report an error if Hasura CLI migrations fail

### ISSUE THREAD

**Issue by vijayprasanna13** [hasura/graphql-engine#8041]
### Version Information

Server Version: 2.1.0
CLI Version (for CLI related issue): 

### Environment
OSS

### What is the expected behaviour?

If there are any permission issue in the filesystem while writing migrations via the Hasura CLI console, the user is to be notified with an error message indicating the error.

### Keywords

console, error handling, cli, permissions

### What is the current behaviour?

Currently, the console side tab is stuck in an infinite loading state and there is no error message on screen.

### How to reproduce the issue?

1. Run Hasura cli locally.
2. Navigate to the folder where you have initialised the CLI directory and set the migrations folder to read only.
3. Go to the console (`http://localhost:9695/console`) and click on the Data tab.
3. Create a table under the default database.
4. In the network tab, you can see that the network request fails with a 500 error but the console doesn't report the error.

### Screenshots or Screencast
![Screenshot 2022-01-18 at 1 37 36 PM](https://user-images.githubusercontent.com/11921040/149896147-3fccf0a4-ed54-42d4-a3dd-125ea8e6c039.png)

### Please provide any traces or logs that could help here.

```
Uncaught (in promise) SyntaxError: Unexpected token c in JSON at position 0
    at JSON.parse (<anonymous>)
    at DataActions.js:700:35
    at index.js:8:1
    at dispatch (redux.js:659:1)
    at onError (DataActions.js:869:7)
```

### Any possible solutions?

Check `typeof error.message` before attempting to parse the error or switch to a more generalised error catching logic.
 
### Can you identify the location in the source code where the problem exists?
This line [here](https://github.com/hasura/graphql-engine/blob/a7dbe95666a41f17d03f6695355cbb2a16fe5446/console/src/components/Services/Data/DataActions.js#L700)

**Comment by iykekings** [comment]
@vijayprasanna13 a good solution will be to wrap the error with `getErrorMessage` from [here](https://github.com/hasura/graphql-engine-mono/blob/88257687a2c989369b62115c238aa318ea9780ca/console/src/components/Services/Common/Notification.tsx#L80-L129)

**Comment by rikinsk** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/9ca658a4f6aaf510335c77082386b1cb7548d6fa
