### ISSUE TITLE
health check url configuration (cloud run gcp incompatibility)

### ISSUE THREAD

**Issue by gucaldeira** [hasura/graphql-engine#8042]
### Is your proposal related to a problem?
Yes! Today we can't use CLI when running graphql-engine on [Cloud Run](https://cloud.google.com/run) because that service reserves the health check url (/healthz).

We could have the health configuration as an external configuration both in server and CLI

#### On **Server**
It would be included a environment variable ex: `HEALTH_CHECK_ENDPOINT=my-healthcheck`

Expected behavior: When request the URL https://my-app.a.run.app/my-healthcheck returns HTTP status 200 and plain contexto `OK`

#### On **CLI**
It would be included a parameter ex: `--health-check-entpoint my-healthcheck`

Expected behavior: When the CLI will do the health check, It will use the URL: https://my-app.a.run.app/my-healthcheck 

### Describe alternatives you've considered

Change only CLI including a `--skip-health-check`

### If the feature is approved, would you be willing to submit a PR?

Sure

**Comment by scriptonist** [comment]
@gucaldeira Thanks for bringing this up! This has been addressed recently in https://github.com/hasura/graphql-engine/commit/d5e2d613f0539e9ff845d23f2a6775e7f0b1ee63 and should be available from the next release.

**Comment by gucaldeira** [comment]
Thank you for the quick answer. By the way I will try build a local version that skips health check steps until the new next release.
