### ISSUE TITLE
server/mssql: document updates on SQL Server

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#8053]
Add a documentation page 'SQL Server: Update mutation' similar to the existing [Postgres page](https://hasura.io/docs/latest/graphql/core/databases/postgres/mutations/update.html) with examples.

Relates to #7624.

**Comment by marionschleifer** [comment]
This has been completed. [Link to page](https://hasura.io/docs/latest/mutations/ms-sql-server/update/).
