### ISSUE TITLE
hasura-cli 2.1.1 installs cli-ext version v2.0.0-alpha.4

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#8060]
### Version Information

CLI Version (for CLI related issue): 2.1.1

### Environment

Linux

### What is the expected behaviour?

I expect the plugin version to not be alpha

### What is the current behaviour?

I have the 2.1.1 hasura-cli but I noticed I can't install the cli-ext plugin any higher than v2.0.0-alpha.4. Is this normal?

### How to reproduce the issue?

```
$ hasura plugins list
NAME     DESCRIPTION                VERSION         INSTALLED
cli-ext  Hasura CLI extension       v2.0.0-alpha.4  yes
pro      CLI plugin for Hasura Pro  v2.0.1-pro.1    no

$ hasura plugins upgrade cli-ext --version v2.1.1
FATA[0000] failed to upgrade plugin "cli-ext": plugin version is not available 
```

**Comment by scriptonist** [comment]
@jflambert Staring `v2.0.0`, `cli-ext` is not a plugin anymore and is part of the main binary. So, you can basically ignore a recent version being not available.
