### ISSUE TITLE
Use hasura-cli to manage migrations without a Hasura server

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#8061]
### Is your proposal related to a problem?

I'd like to be able to manage migrations using hasura-cli, without actually needing a hasura instance.

### Describe the solution you'd like

using `hasura-cli` in a "migration-only" functionality.

### Describe alternatives you've considered

Run hasura while hasura-cli manages migrations, then shutdown hasura.

Or use other migration tools.

**Comment by rikinsk** [comment]
@jflambert Could you elaborate a bit more on the "without actually needing a hasura instance" bit. Would like to get some more clarity on how/where you would use it and the workflow you are thinking of.

**Comment by jflambert** [comment]
Am I doing something wrong and this is already possible?

I maintain lots of databases. Many have hasura instances running alongside them, so we can provide them as remote schemas.

Others are smaller, standalone databases that don't need a Hasura API on top of them.

But I'm very familiar with Hasura's SQL migrations, and I'd still like to use hasura-cli to apply migrations (NOT metadata), without needing to connect to an 8080 server. Does that make sense?

I guess hasura-cli would have to create the hasura schema, and create the necessary tables to track migrations, if instructed as such with a special flag.

**Comment by jflambert** [comment]
I'm going to close this issue as it's probably not possible. The hasura-cli tool would have to contain the business logic of the API it calls.

In those cases I'll use Hasura as an init container only.

**Comment by rikinsk** [comment]
Hey sorry for missing your earlier response. But you did come to the right conclusion. The CLI specifically uses the Hasura server APIs to execute the migrations so it would be a little out of its scope to run migrations directly on a db

**Comment by villasv** [comment]
But what kind of API call is necessary just to create the migration file with `hasura migrate create`?
