### ISSUE TITLE
Passing JSONB as variables in console shows error but works

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#8067]
### Version Information

Server Version:
CLI Version (for CLI related issue): `v2.1.1`

### Environment
OSS

### What is the expected behaviour?
Should not show error on passing jsonb conditional variables 

### Keywords

CLI JSONB Varaiables

### What is the current behaviour?
Right now even though it works it shows error

### How to reproduce the issue?
Check the screenshot

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/5978905/150557879-e6bd2b0e-f39c-4cae-8df7-c38fab54fa2d.png)

### Please provide any traces or logs that could help here.
Please ask if needed

### Any possible solutions?
It works but shows error

### Can you identify the location in the source code where the problem exists?
Haven't checked

### If the bug is confirmed, would you be willing to submit a PR?
Of course.

**Comment by rikinsk** [comment]
This is being tracked in #4787
