### ISSUE TITLE
Row checkbox selects the entire page

### ISSUE THREAD

**Issue by strazan** [hasura/graphql-engine#8075]
### Version Information
2.1.1

### Environment

MacOS

### What is the current behaviour?

- Ticking the checkbox on a row selects the entire page.
This doesn't happen on all tables. The only common denominator I found is that tables where the entire page gets selected contains more rows than the page displays.

![image](https://user-images.githubusercontent.com/43888637/150542211-06a48ff7-0c94-404e-a39f-73d9ad821fd0.png)

**Comment by vijayprasanna13** [comment]
Hey @strazan , could you confirm if it's a `postgres` db  you're using here?

**Comment by strazan** [comment]
Hey, @vijayprasanna13, yes `postgres`!

**Comment by vijayprasanna13** [comment]
> The only common denominator I found is that tables where the entire page gets selected contains more rows than the page displays.

@strazan We are trying to investigate this issue from our side. I'd like to close this issue and continue the conversation on the other [issue](https://github.com/hasura/graphql-engine/issues/8064), It seems that they are related.
