### ISSUE TITLE
[BigQuery]  Incorrect error code is shown when rate limit is reached

### ISSUE THREAD

**Issue by dennislaviolette** [hasura/graphql-engine#8081]
### Version Information

Server Version:
CLI Version (for CLI related issue):

### Environment

BigQuery Server side

Using the **v1alpha1/graphql** endpoint

### What is the expected behaviour?

Assumed behavior should be Error 429

### What is the current behaviour?

When the query rate limit is reach the user receives an error 400

### How to reproduce the issue?

1.
2.
3.

https://hasurahelp.zendesk.com/agent/tickets/1240

**Comment by tirumaraiselvan** [comment]
Just for historical context, the `v1alpha1/graphql` endpoint is supposed to return proper HTTP status code for errors whereas the `v1/graphql` endpoint returns 200 always (the latter is graphql spec compliant).

**Comment by dmoverton** [comment]
Fixed by https://github.com/hasura/graphql-engine/commit/8d0eb6b812c5f956ca25116f72a79915b9444c88
