### ISSUE TITLE
[BigQuery] Limit Failure due to Inconsistent Metadata

### ISSUE THREAD

**Issue by dennislaviolette** [hasura/graphql-engine#8082]
### Version Information

Server Version:
CLI Version (for CLI related issue):

### Environment

Server side

### What is the expected behaviour?

No errors.

### What is the current behaviour?
The new BigQuery API is being piloted by a single client. Twice today (within a 5-hour window), they experienced a failure due to inconsistent metadata (see screenshot).

Reloading metadata with the “reload all databases” box checked resolved the issue in both cases.

![image](https://user-images.githubusercontent.com/93953444/151000559-d1d0c5db-c011-48e7-a8c5-bc0bbd035552.png)

### How to reproduce the issue?

1.
2.
3.

https://hasurahelp.zendesk.com/agent/tickets/843

**Comment by tirumaraiselvan** [comment]
Main issue resolved in https://github.com/hasura/graphql-engine-mono/pull/3569
