### ISSUE TITLE
/healthz fails on Google App Engine

### ISSUE THREAD

**Issue by rccoe** [hasura/graphql-engine#8093]
### Version Information

Server Version: 2.*
CLI Version (for CLI related issue):2.1.*

### Environment

GCP

### What is the expected behaviour?

CLI should be able to connect

### Keywords

healthz, app engine

### What is the current behaviour?

/healthz is a reserved endpoint in Google App engine, so any attempt to connect to that endpoint fails. We are stuck on hasura cli 2.0.* permanently until this is resolved

### How to reproduce the issue?

Deploy Hasura 2.* to Google App engine
Install CLI 2.1.*
Run `hasura console`
Will fail.

### Any possible solutions?

Add a secondary backup endpoint ("healthx") for GCP App engine

### Can you identify the location in the source code where the problem exists?

Not yet

### If the bug is confirmed, would you be willing to submit a PR?

If a solution is agreed upon yes

**Comment by rikinsk** [comment]
Hi, this issue has been fixed and should be available in the next release. Previousy tracker at https://github.com/hasura/graphql-engine/issues/8042
