### ISSUE TITLE
Add readonly mode to hasura core

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#8109]
### Is your proposal related to a problem?
No

### Describe the solution you'd like
It would be nice to have the ability to run a read-only hasura instance so we can run multiple instance to hasura against a single database.

**Comment by jflambert** [comment]
Do you mean the Console itself?

Because then this is a duplicate of !5349

**Comment by tirumaraiselvan** [comment]
Closing as dupe of #5349
