### ISSUE TITLE
Some data are not visible in the edit row form and saving remove the non visible data

### ISSUE THREAD

**Issue by lionelB** [hasura/graphql-engine#8110]
### Version Information
Server Version: v2.1.1

### Environment
firefox / chromium

### What is the expected behaviour?
When editing a row, input fields should contains the existing value of the field
 

### What is the current behaviour?
When editing a row, input that they contain value of type uuid, timestampz are empty.
 

### How to reproduce the issue?

1. edit a row with at least a uuid foreign key and a created_at field
2. see the empty field

**Comment by prajzwol7** [comment]
@lionelB i think this issue has been solved in upgraded hasura version.
