### ISSUE TITLE
Invalid mutations (delete_by_pk and update_by_pk) placeholder text in Custom Graphql Root Fields

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#8113]
### Version Information

Server Version: 2.1.1

### Environment

OSS

### What is the expected behaviour?

When customizing Graphql Root Fields, the placeholder text should be accurate.

### What is the current behaviour?

The placeholder text for update_xxx_by_pk and delete_xxx_by_pk WRONGLY suggests that the mutations will be update_by_pk_xxx and delete_by_pk_xxx

At least, when these mutations aren't customized, they will use the normal format.

### How to reproduce the issue?

1. Either track an existing table or create a new one
2. Open Custom Graphql Root Fields
3. Notice the incorrect placeholder text

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/11539524/151830034-39c1ca4d-8dd5-442d-b26a-08cc2bf667aa.png)

![image](https://user-images.githubusercontent.com/11539524/151830470-4d77a221-b7c7-4f74-ac9a-2e7433d706b3.png)

**Comment by jflambert** [comment]
If I may add, perhaps the order in which they are listed in custom graphql root fields should match the display order in the API tab.

- delete_xxx
- delete_xxx_by_pk
- insert_xxx
- insert_xxx_one
- update_xxx
- update_xxx_by_pk

**Comment by jflambert** [comment]
> If I may add, perhaps the order in which they are listed in custom graphql root fields should match the display order in the API tab.

I ended up creating an entirely new issue for this #8253

**Comment by julian-mayorga** [comment]
Thanks for the issue @jflambert.

Hasura v2.28 fixes these default mutations placeholders.

<img width="761" alt="248004356-981a5cad-cdc3-4fef-ad7b-3dfa9335aff1" src="https://github.com/hasura/graphql-engine/assets/118911427/3c226d83-9a1f-4fd0-bfaa-2b7310467710">

**Comment by jflambert** [comment]
Confirmed fixed, thanks
