### ISSUE TITLE
Recursive Custom Type does not work as said in the documentation

### ISSUE THREAD

**Issue by jmsilvas-xep** [hasura/graphql-engine#8126]
### Environment

Cloud

### What is the expected behaviour?

In the custom types documentation is said that is possible to define recursive custom types providing the following example:
![image](https://user-images.githubusercontent.com/94845117/152173704-c5306d2d-bdd4-4092-869c-49b28d233f56.png)

I expected this to work and tried this example in my custom types tab hoping that i could save this type normally

### Keywords

Documentation error
recursive type
custom types
action
object 

### What is the current behaviour?

Im receiving the following error when i try to save the type
![image](https://user-images.githubusercontent.com/94845117/152174110-faf3fc69-91db-4c61-a3f2-53552a5ffbe2.png)

(Inconsistent object: validation for the given custom types failed because the type "UserObj" of the field "friends" in the object type "UserObj" is object type which isn't allowed)

So the example in the documentation you provide does not really work indeed. Hope you can make the fix!

### How to reproduce the issue?

1. go to custom types
2. paste the example: 
```
type UserObj {
  name: String!
  favFood: String!
  isAdmin: Boolean!
  friends: [UserObj]!
}
```
3. try to save it

### Screenshots or Screencast

<![image](https://user-images.githubusercontent.com/94845117/152173704-c5306d2d-bdd4-4092-869c-49b28d233f56.png)

![image](https://user-images.githubusercontent.com/94845117/152174110-faf3fc69-91db-4c61-a3f2-53552a5ffbe2.png)

![image](https://user-images.githubusercontent.com/94845117/152175321-49b3b508-0fd0-4d46-97be-47764b67fd6b.png)

**Comment by rikinsk** [comment]
Hey thanks for reporting this. This seems to be actually a case of the docs erroneously getting deployed before a feature release. Recursive custom types will be supported from `v2.2.0` onwards which is about to be released very soon.

**Comment by marionschleifer** [comment]
Documented [here](https://hasura.io/docs/latest/actions/types/index/#object-types).
