### ISSUE TITLE
reload_metadata reports "success" even if inconsistencies are present

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#8129]
### Version Information

Server Version: 2.1.1

### Environment

OSS

### What is the expected behaviour?

`reload_metadata` API calls should probably report that, although the operation was successful, inconsistencies are present.

### What is the current behaviour?

I'm a little surprised to notice that `reload_metadata` just reports success even though the schema isn't consistent.

As it stands, I have to call `reload_metadata` and `get_inconsistent_metadata` sequentially to confirm whether or not the schema is consistent. Is this expected?

### How to reproduce the issue?

1. Using `replace_metadata` with `"allow_inconsistent_metadata": true`, create inconsistencies (for example track a wrong table)
2.  call `reload_metadata`: get a success
3. call `get_inconsistent_metadata`: get `inconsistent_objects`

**Comment by tirumaraiselvan** [comment]
It does make sense for reload_metadata to report inconsistencies. We will fix this.

**Comment by paritosh-08** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/a0c83b8e99d4c37a9c3473b6f9344ec054f18694

**Comment by jflambert** [comment]
Just want to thank you @tirumaraiselvan  and @paritosh-08  for adding this feature

Needed it today!
