### ISSUE TITLE
[Documentation] Invalid response for get_inconsistent_metadata

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#8136]
### Version Information

Server Version: 2.1.1

### Environment

OSS

### What is the expected behaviour?

Documentation examples should be accurate

### What is the current behaviour?

Documentation for `get_inconsistent_metadata` gives an incomplete response sample.

### How to reproduce the issue?

1. Go to https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/manage-metadata.html#get-inconsistent-metadata
2. Observe an invalid response
3. it should have `is_consistent` and `inconsistent_objects` keys

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/11539524/152459121-ab709da1-0b51-491b-a2d3-fe2f45655ca0.png)

![image](https://user-images.githubusercontent.com/11539524/152459221-7a4cbea7-9e29-4090-9a45-4eb46a0796ae.png)

**Comment by rikinsk** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/8cfdd1ee3b99389b8df65f1e873edba427ebc5a2
