### ISSUE TITLE
Console URL display does not support `--api-host`

### ISSUE THREAD

**Issue by sho-hata** [hasura/graphql-engine#8144]
### Version Information

Server Version: v2.2.0
CLI Version (for CLI related issue):v2.2.0

### Environment
OSS

### What is the expected behaviour?
When `--api-host` is specified, the value of `--api-host` is displayed instead of the default value `"http://localhost"` of the `--address` option.

### Keywords
hasura console

### What is the current behaviour?

```bash
hasura console --api-host https://XXX
```

The URL that is displayed is `"http://localhost"`.
```bash
INFO console running at: http://localhost:9695/
```

### How to reproduce the issue?
- Run hasura console command with the --api-host option set to a value other than default value.

### Screenshots or Screencast
<img width="614" alt="Screenshot 2022-02-05 16 19 52" src="https://user-images.githubusercontent.com/37888628/152633023-06539a00-0e9a-4a46-aa4f-7cba8c781453.png">

### Can you identify the location in the source code where the problem exists?
[/cli/pkg/console/consoleserver.go#L100](https://github.com/hasura/graphql-engine/blob/master/cli/pkg/console/consoleserver.go#L100)
In this section, the value specified by `--address` is used.

Instead, it should be modified to display the value of `--address` if it is specified, and the value of `--api-host` otherwise.

### If the bug is confirmed, would you be willing to submit a PR?
yes.

**Comment by scriptonist** [comment]
@sho-hata IIUC this is working as expected? 
```
$ hasura console --api-host http://hasura                                                                        
INFO console running at: http://localhost:9695/
```
"Console" is served at `http://localhost:9695/` and API server will be served at `http://hasura:9693/` with this configuration. Which seems right to me.

**Comment by sho-hata** [comment]
@scriptonist Ooops! :scream:

My understanding of the console's URL and the server's URL was incorrect. I'm closing this issue.
Thank you.
