### ISSUE TITLE
[2.2.0] Can't update due to request transform error

### ISSUE THREAD

**Issue by flocosnier** [hasura/graphql-engine#8151]
I was trying to update to the latest version (2.2.0) but I'm getting an error :

graphql-engine_1  | {"type":"startup","timestamp":"2022-02-07T16:31:16.555+0000","level":"error","detail":{"kind":"catalog_migrate","info":{"internal":{"statement":"\n       SELECT metadata from hdb_catalog.hdb_metadata\n    ","prepared":true,"error":"Error in $.sources[0].tables[3]['event_triggers'][1]['request_transform'].body: ParseError: Unexpected token '}'.","arguments":[]},"path":"$","error":"database query error","code":"unexpected"}}}

Everything works fine in 2.1.1

**Comment by flocosnier** [comment]
Solved it, there were extra brackets in some events but it had never raised an error before and it was working fine.. Strange ! Thanks :-)

**Comment by tirumaraiselvan** [comment]
Let us know if you can reproduce this again!
