### ISSUE TITLE
Sql Server - cast issue - nvarchar(max)) AS varchar

### ISSUE THREAD

**Issue by amish-patel** [hasura/graphql-engine#8158]
### Version Information

Server Version: 2.2.0

### Environment

Core

### What is the expected behaviour?

Nvarchar(max) should be casted as proper varchar length

### Keywords

Hello, we are seeing an issue when a query is being made. nvarchar(max)) AS varchar - SQL server varchar default is to convert to 30 characters and our GUID fails to match - seems like this was fixed in v2.0.0-alpha.3 but we still see it. We are on 2.2.0 version. 
Please see the below link/query.  Any help would be appreciated

### What is the current behaviour?

https://github.com/hasura/graphql-engine/search?q=%22as+varchar%22&type=code

```SELECT ISNULL((SELECT [t_tblSettingsPersona1].[PKey] AS [PKey],\n       [t_tblSettingsPersona1].[fldAcctAdmin] AS [fldAcctAdmin]\nFROM [dbo].[tblSettingsPersonal] AS [t_tblSettingsPersona1]\nWHERE ((((([t_tblSettingsPersona1].[fldCrewID]) = (CAST(CAST((N'36a6257b-08bb-45ef-a5cf-c1b7a7997087') AS nvarchar(max)) AS varchar)))\n      OR ((([t_tblSettingsPersona1].[fldCrewID]) IS NULL)\n      AND ((CAST(CAST((N'36a6257b-08bb-45ef-a5cf-c1b7a7997087') AS nvarchar(max)) AS varchar)) IS NULL)))))\nFOR JSON PATH, INCLUDE_NULL_VALUES), '[]')"```

``` SELECT (CAST(CAST((N'36a6257b-08bb-45ef-a5cf-c1b7a7997087') AS nvarchar(max)) AS varchar))``` will give you ```36a6257b-08bb-45ef-a5cf-c1b7a7``` as result and hence won't match the GUID.

### How to reproduce the issue?

1. Create a varchar column
2. Issue a query via API console 
3. Watch console and you will see ```nvarchar(max)) AS varchar``` in generated query

### Please provide any traces or logs that could help here.

```{"type":"query-log","timestamp":"2022-02-08T20:47:21.449+0000","level":"info","detail":{"kind":"database","request_id":"17f78a13-d0f6-48ca-99f6-dbc155912425","generated_sql":{"tblSettingsPersonal":{"prepared_arguments":null,"query":"SELECT ISNULL((SELECT [t_tblSettingsPersona1].[PKey] AS [PKey],\n       [t_tblSettingsPersona1].[fldAcctAdmin] AS [fldAcctAdmin]\nFROM [dbo].[tblSettingsPersonal] AS [t_tblSettingsPersona1]\nWHERE ((((([t_tblSettingsPersona1].[fldCrewID]) = (CAST(CAST((N'36a6257b-08bb-45ef-a5cf-c1b7a7997087') AS nvarchar(max)) AS varchar)))\n      OR ((([t_tblSettingsPersona1].[fldCrewID]) IS NULL)\n      AND ((CAST(CAST((N'36a6257b-08bb-45ef-a5cf-c1b7a7997087') AS nvarchar(max)) AS varchar)) IS NULL)))))\nFOR JSON PATH, INCLUDE_NULL_VALUES), '[]')"}},"query":{"operationName":"MyQuery","query":"query MyQuery {\n  tblSettingsPersonal {\n    PKey\n    fldAcctAdmin\n  }\n}\n"}}}```

### Any possible solutions?

Below query will work and give appropriate results back - change from ```varchar``` to ```varchar(max)``` - column is actually ```varchar(255)```

```
SELECT
	ISNULL((
	SELECT
		[t_tblSettingsPersona1].[PKey] AS [PKey],
		[t_tblSettingsPersona1].[fldAcctAdmin] AS [fldAcctAdmin]
		FROM [dbo].[tblSettingsPersonal] AS [t_tblSettingsPersona1]
		WHERE ((((([t_tblSettingsPersona1].[fldCrewID]) = (CAST(CAST((N'36a6257b-08bb-45ef-a5cf-c1b7a7997087') AS nvarchar(max)) AS varchar(max))))
			OR ((([t_tblSettingsPersona1].[fldCrewID]) IS NULL)
				AND ((CAST(CAST((N'36a6257b-08bb-45ef-a5cf-c1b7a7997087') AS nvarchar(max)) AS varchar(max))) IS NULL)))))FOR JSON PATH,
		INCLUDE_NULL_VALUES),
	'[]')

```

**Comment by amish-patel** [comment]
@sassela - thank you - looking forward to it - we are currently blocked shipping a release - we found this last minute - a long story as to why that happened.

**Comment by sassela** [comment]
@amish-patel we [merged the fix](https://github.com/hasura/graphql-engine/commit/69fd7449be51ce7919743e70a2eee6b40632ac64) earlier today, so it'll be available in the next release within a couple of weeks

**Comment by amish-patel** [comment]
Fantastic - thanks for fixing it promptly @sassela and team! 

Is there a way to get a patched docker image/version or build it ourselves? As I mentioned earlier, we are blocked and need to ship the release.Any pointers from team/community would be appreciated.

**Comment by sassela** [comment]
@amish-patel please try Docker image `hasurabuild/graphql-engine:mono-branch-main-04de036ee`, and let me know if you have any issues?

**Comment by amish-patel** [comment]
@sassela thank you for that link - yes, we tried it - sorry it took a bit to get back - we were trying to see if some behavior was due to this new image. Happy to report that, we see the fix is working. Will do a bit more testing but its looking good. Thanks to everyone involved!

**Comment by sassela** [comment]
wonderful, thanks for confirming! I'll close this issue now, in case I forget to come back to it after next week's release.
