### ISSUE TITLE
Array relationship nested object where condition ignored. Returns wrong results

### ISSUE THREAD

**Issue by nadendlaprasad** [hasura/graphql-engine#8164]
```
query MyQuery {
  customer(where: {active: {_eq: false},addresses:{ active: {_eq: false}}}) {
    addresses{
      street
      city
      active
    }
    name
    dob
    active
  }
}
```

Above query returns the data where addresses active status is  'true'.

**Comment by abdullah2993** [comment]
I could be wrong but I think what you need is something like this
```gql
query MyQuery {
  customer(where: {active: {_eq: false}}) {
    addresses(where: {active: {_eq: false}){
      street
      city
      active
    }
    name
    dob
    active
  }
}
```

**Comment by rikinsk** [comment]
@nadendlaprasad 

```
customer(where: {active: {_eq: false},addresses:{ active: {_eq: false}}})
```

This is a filter on the `customer`. i.e. it will return all `customers` that have atleast one `address` which has `active` false. I believe you are looking for what @abdullah2993 has suggested.

Closing this for now. Please feel free to reopen if you need more help with this.
