### ISSUE TITLE
Allow Cli-Migrations image to run cli console from inside container

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#8175]
### Is your proposal related to a problem?

The cli-migrations image includes the hasura cli inside the container, and uses it during startup.
Allowing this image to serve the cli console would allow simplification of some dev environments and lower the barrier of entry.

### Describe the solution you'd like

Ideally the image should by default maintain the current behavior, but given the right configuration start with the cli console already available on a separate port.
For this to work, the hasura metadata, migrations, and seeds directory should be mounted onto the volume, as well as the config.yaml file.

### Describe alternatives you've considered

This is almost currently possible with a custom command on container startup.
We first need to wait for the graphql engine to be available, then we start the cli console and point it at the right files and directories.

For the docker container to bind the ports onto the host properly, we must explicitly start the cli console with an address of `0.0.0.0`. This allows us to bind the port and make the console available on  the host machine.

Unfortunately this is where we hit a roadblock. Because we changed the address, the hasura console will attempt to connect to the cli console api at `0.0.0.0`, not localhost. Because we can't set the listening address separately from the address the console should use to reach the api, this is currently impossible to work around.

### If the feature is approved, would you be willing to submit a PR?

If the cli folks added the right flags, I could give customizing the image a shot.
Would definitely still need help.

**Comment by rikinsk** [comment]
Also seems related to https://github.com/hasura/graphql-engine/issues/6048

**Comment by m-Bilal** [comment]
Completed in https://github.com/hasura/graphql-engine/issues/2824
