### ISSUE TITLE
Code Exporter Overflow Error

### ISSUE THREAD

**Issue by Akshat4799** [hasura/graphql-engine#8178]
### Version Information

Server Version: v2.1.1-cloud.1

### Environment

Cloud

### What is the expected behaviour?

Code Exported has options to choose the Language and the Method which seem to be overflowed by the code block. The Options checkboxes and the Copy code buttons are not working either. 

### Keywords

Code Exporter, Hasura Cloud, Overflow

### What is the current behaviour?

Currently due to the overflow none of the buttons are interactable. 

### How to reproduce the issue?

1. Open project on Hasura Cloud
2. Click on the API tab
3. On the GraphiQL tab choose the Code Exporter option
4. New tab should open up to the right of the GraphiQL console

### Screenshots or Screencast
![overflow_error_hasura_cloud](https://user-images.githubusercontent.com/88447609/154114370-29c45055-42d8-455c-9dc2-ca7d7ee04b21.PNG)

### Any possible solutions?

Revisit the styling for the parent component where the Code Exporter Options and Code Exporter Code Block are child elements.

### If the bug is confirmed, would you be willing to submit a PR?

Yes

**Comment by Akshat4799** [comment]
Related to [this previously mentioned issue](https://github.com/hasura/graphql-engine/issues/5263)

**Comment by rikinsk** [comment]
As you can see this from the issue a fix has been merged. This should be fixed in the next release

**Comment by wizztjh** [comment]
still replicable on v2.13.0-beta.1 and v2.12.0

![image](https://user-images.githubusercontent.com/462417/192483593-868ab426-1205-4497-b2b4-0b0d8f9e8404.png)

**Comment by jskrzypek** [comment]
Digging into the chrome inspector, I noticed the top-level `.graphiql-code-exporter .CodeMirror` element's CSS has 
```css
position: absolute;
top: 0;
```

If I change this to:
```css
position: relative;
top: 0;
```
it fixes the issue.

**Comment by jskrzypek** [comment]
@rikinsk can we re-open this? or should we file a new issue?
