### ISSUE TITLE
X-Forwarded-For not being sent properly 

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#8183]
### Version Information

Server Version: v2.2.0

### Environment
OSS on heroku

### What is the expected behaviour?
Get proper `X-Forwarded-For` headers. Instead of getting multiple  `X-Forwarded-For` headers we should get only one header with multiple values.

**getting**
```
X-Forwarded-For: 175.107.2.62
X-Forwarded-For: 44.197.241.184
```
**expected:**
```
X-Forwarded-For: 175.107.2.62, 44.197.241.184
```

### What is the current behaviour?
Hasura seems to be sending multiple `X-Forwarded-For` headers. Instead it should be sending single header with multiple values `X-Forwarded-For:  175.107.2.62, 44.197.241.184`
Sample response coming from hasura
```
POST / HTTP/1.1
Host: d00d-175-107-2-62.eu.ngrok.io
User-Agent: hasura-graphql-engine/v2.2.0
Content-Length: 172
Accept-Encoding: gzip
Connect-Time: 0
Content-Type: application/json
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Sec-Gpc: 1
Total-Route-Time: 0
Via: 1.1 vegur
X-B3-Parentspanid: 9113fc650b216afc
X-B3-Spanid: e83eb00e72de8691
X-B3-Traceid: f477d1a5ae07b645
X-Forwarded-For: 175.107.2.62
X-Forwarded-For: 44.197.241.184
X-Forwarded-Host: test-hasura-app-x.herokuapp.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Proto: https
X-Forwarded-User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0
X-Request-Id: 83f0d743-3bb5-42ae-bc78-7cbca3fd1617
X-Request-Start: 1645009659256

{"request_query":"mutation MyMutation {\n  actionName {\n    accessToken\n  }\n}\n","session_variables":{"x-hasura-role":"admin"},"input":{},"action":{"name":"actionName"}}
```

### How to reproduce the issue?

1. Deploy fresh instance on heroku
2. Create an action with forwarding client headers
3. Check response

**Comment by rakeshkky** [comment]
Hi @abdullah2993, 

[HTTP semantics](https://www.rfc-editor.org/rfc/rfc9110.html#name-field-lines-and-combined-fi) for header fields says
```
X-Forwarded-For: 175.107.2.62
X-Forwarded-For: 44.197.241.184
```
and 
```
X-Forwarded-For: 175.107.2.62, 44.197.241.184
```
are logically same.
