### ISSUE TITLE
Hasrua CLI init failing with error exporting metadata failed

### ISSUE THREAD

**Issue by lakshyasharma14** [hasura/graphql-engine#8190]
### Version Information

CLI Version (for CLI related issue): version=v2.3.0-beta.1 and v2.2.0

### Environment

Hasura Cloud 
OS: Windows
DB: Postgres on Heroku 

### What is the expected & current behavior?

I create a few tables and added permissions using hasura cloud UI and added a few permissions to it.
I wanted to export all the schema to my git repo so I used hasura CLI and executed the query 
`hasura init hasura --endpoint <endpoint>`
I
But I was getting this error:
```
INFO Creating migrations for source: fyt
INFO Created Migrations
INFO migrations applied
ERRO creating migrations failed:
failed to export metadata: cannot export actions from metadata: error parsing metadata
object: actions
file: actions.yaml
error: error in converting metadata to sdl: exit status 1: internal/modules/package_json_reader.js:4
const internalModuleReadJSON = function (f) { return require('fs').internalModuleReadJSON(f); };
                                                                   ^

TypeError: require(...).internalModuleReadJSON is not a function
    at internalModuleReadJSON (internal/modules/package_json_reader.js:4:68)
    at Object.read (internal/modules/package_json_reader.js:19:34)
    at readPackage (internal/modules/cjs/loader.js:237:36)
    at readPackageScope (internal/modules/cjs/loader.js:270:19)
    at trySelf (internal/modules/cjs/loader.js:386:40)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:24)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1147:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:451:5)
run `hasura migrate create --from-server` from your project directory to retry
INFO directory created. execute the following commands to continue:
```

### How to reproduce the issue?

I am working on it, but it started after adding relationship and permission on the tables.
### If the bug is confirmed, would you be willing to submit a PR?

Yes

**Comment by scriptnull** [comment]
Hi @lakshyasharma14, thanks for reporting! We have been trying to reproduce this bug on our end and we are still unable to reproduce it.

Will you be interested in sharing your metadata with us? That might help us to get a repro on this. You could download the metadata from the graphql-engine console like shown [here](https://hasura.io/docs/latest/graphql/core/migrations/manage-metadata.html#exporting-hasura-metadata) and share it with us here. If you would like to share it with us privately, feel free to drop it to me at vishnu@hasura.io

Could you also check if you have defined `NODE_OPTIONS` env in your environment variables? (apparently having it set might be causing trouble like mentioned [here](https://github.com/vercel/pkg#error-requireinternalmodulestat-is-not-a-function))

**Comment by lakshyasharma14** [comment]
> Will you be interested in sharing your metadata with us? That might help us to get a repro on this. You could download the metadata from the graphql-engine console like shown [here](https://hasura.io/docs/latest/graphql/core/migrations/manage-metadata.html#exporting-hasura-metadata) and share it with us here. If you would like to share it with us privately, feel free to drop it to me at [vishnu@hasura.io](mailto:vishnu@hasura.io)

I would have sent it, if I was able to export it. But metadata-export itself is failing 
```
 PS L:\Study\findyourtrip\hasura>  hasura metadata export
time="2022-02-17T22:37:17+05:30" level=fatal msg="failed to export metadata: cannot export actions from metadata: error parsing metadata \nobject: actions\nfile: actions.yaml\nerror: error in converting metadata to sdl: exit status 1: internal/modules/package_json_reader.js:4\r\nconst internalModuleReadJSON = function (f) { return require('fs').internalModuleReadJSON(f); };\r\n                                                                   ^\r\n\r\nTypeError: require(...).internalModuleReadJSON is not a function\r\n    at internalModuleReadJSON (internal/modules/package_json_reader.js:4:68)\r\n    at Object.read (internal/modules/package_json_reader.js:19:34)\r\n    at readPackage (internal/modules/cjs/loader.js:237:36)\r\n    at readPackageScope (internal/modules/cjs/loader.js:270:19)\r\n    at trySelf (internal/modules/cjs/loader.js:386:40)\r\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:24)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:667:27)\r\n    at Module.require (internal/modules/cjs/loader.js:887:19)\r\n    at Module._preloadModules (internal/modules/cjs/loader.js:1147:12)\r\n    at loadPreloadModules (internal/bootstrap/pre_execution.js:451:5)\r"
PS L:\Study\findyourtrip\hasura> hasura metadata reload
INFO Metadata reloaded
INFO Metadata is consistent
PS L:\Study\findyourtrip\hasura>  hasura metadata export
time="2022-02-17T22:42:54+05:30" level=fatal msg="failed to export metadata: cannot export actions from metadata: error parsing metadata \nobject: actions\nfile: actions.yaml\nerror: error in converting metadata to sdl: exit status 1: internal/modules/package_json_reader.js:4\r\nconst internalModuleReadJSON = function (f) { return require('fs').internalModuleReadJSON(f); };\r\n                                                                   ^\r\n\r\nTypeError: require(...).internalModuleReadJSON is not a function\r\n    at internalModuleReadJSON (internal/modules/package_json_reader.js:4:68)\r\n    at Object.read (internal/modules/package_json_reader.js:19:34)\r\n    at readPackage (internal/modules/cjs/loader.js:237:36)\r\n    at readPackageScope (internal/modules/cjs/loader.js:270:19)\r\n    at trySelf (internal/modules/cjs/loader.js:386:40)\r\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:24)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:667:27)\r\n    at Module.require (internal/modules/cjs/loader.js:887:19)\r\n    at Module._preloadModules (internal/modules/cjs/loader.js:1147:12)\r\n    at loadPreloadModules (internal/bootstrap/pre_execution.js:451:5)\r"
```
> Could you also check if you have defined `NODE_OPTIONS` env in your environment variables? (apparently having it set might be causing trouble like mentioned [here](https://github.com/vercel/pkg#error-requireinternalmodulestat-is-not-a-function))

I checked those issues reported earlier and had confirmed already that NODE_OPTIONS is not set.

I have everything setup in my hasura cloud account and I don't want to reset metadata, I can try making a new account and try reproducing it, and then will try to pinpoint exactly because of what thing this issue might be happening.

If you want you can take access to my hasura account and check it. There is no confidential data present as such.

**Comment by lakshyasharma14** [comment]
@scriptnull  Hey, I just created a new empty Hasura account and ran this from my console and I am getting the same error, I think it's just an issue with my machine setup.
 hasura init hasura2 --endpoint https://upright-polliwog-28.hasura.app --admin-secret <secret>

**Comment by scriptnull** [comment]
ah, sorry! I should have been a bit more clear in my comment which requests for metadata. I meant to ask for downloading the metadata from the Web UI of the graphql-engine like this :point_down: 

![image](https://user-images.githubusercontent.com/4211715/154624826-cd674d58-5940-412e-a84d-0f10bf3b23d2.png)

Another option in cli is to use the json output mode like this `hasura metadata export -o json` which would give us the raw metadata that we are looking for. So it might be worth trying out.

But if you would like me to directly take a look at the hasura cloud project that you have created, could you add `vishnu@hasura.io` as a collaborator to that project?

**Comment by lakshyasharma14** [comment]
@scriptnull I have added you as a collaborator.
One more thing I was able to export the metadata of this project on a different computer. It is something to do with my computer only that is not working, I don't think it is the metadata issue. As on my system, I can't even export metadata for an empty project too.

**Comment by lakshyasharma14** [comment]
Hey, it has started working for me now, I don't know if you have fixed something or it was a temporary issue.
