### ISSUE TITLE
Allow Multiple Databases With the Same Schema on a Single Server

### ISSUE THREAD

**Issue by ericwilhite** [hasura/graphql-engine#8204]
### Problem

We have a mix of identical multitenant databases and single tenant isolated databases (MSSQL). We cannot currently add them to a single Hasura instance as the table names cause conflicts.

### Possible solution

Add the option to rename tables (for the schema only, not an actual db migration) when tracking tables to avoid conflict. Or allow namespacing with prefixes on the table names.

### Existing workaround

We currently have to spin up a new server each time a new database is added. This adds a non-trivial amount of management and ops overhead even with some of the process automated via the Hasura CLI / APIs.

**Comment by raarts** [comment]
I have the same use case: each tenant is required to have its own database due to legal requirements.
It would be great to be able to just provide an X-Hasura-Database-Id in either a header, a JWT-claim and (in our case) the auth web hook, to have Hasura select a specific database to use for the query.

**Comment by tirumaraiselvan** [comment]
Adding prefix, suffix and namespace is possible using the metadata API. Check out `mssql_add_source` API's `customization` key: https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/source/#mssql-add-source

**Comment by ericwilhite** [comment]
This works well but there is an issue with namespace visibility.

Currently if a role only has access within one namespace they can still see all available namespaces. This is a showstopping issue for us. The namespaces reveal db names that correspond to our tenant information and even if we anonymized the namespace names it would cause confusion during introspection.
