### ISSUE TITLE
Error applying metadata - parsing the graphql query failed

### ISSUE THREAD

**Issue by frisket** [hasura/graphql-engine#8205]
### Version Information

Server Version: 2.3.0 beta 1(happens with 2.2.0 as well)
CLI Version (for CLI related issue): 2.3.0 beta1 (and 2.2.0)

### Environment

OSS

### What is the expected behaviour?

Importing metadata should complete without errors

### Keywords

cli metadata export apply invalid yaml

### What is the current behaviour?

It seems the yaml in the metadata export is somehow tripping up hasura when it tries to import it again.

I can export the metadata using "hasura metadata export", then immediately try to import it again and it fails with the following error:

```
FATA[0000] error applying metadata 
{
  "path": "$.args.metadata.query_collections[0].definition.queries[5].query",
  "error": "parsing the graphql query failed",
  "code": "parse-failed"
}
```

### How to reproduce the issue?

1. hasura metadata export
2. hasura metadata apply

### Any possible solutions?

It seems to be related to the REST api definitions we've added to our instance.

Looking at the yaml in question (query_collections.yml), I see this on element [5]:

`- name: allowed-queries
  definition:
    queries:
    - name: script_update
      query: "mutation update_templates($scrp_id: Int!, $changes:
        templates_set_input) {\n    update_templates(\n
        \     pk_columns: {scrp_id: $scrp_id}, \n      _set: $changes\n    ) {\n\t\tscrp_code\n\t\tscrp_id\n
        \   }\n  }"
`

Note the dangling "\\" in the middle of the block as well as the "`\t`" characters.

Given that the REST definition is basically a textarea form, this block can contain all sorts of random control characters entered by the user.

Once I remove the dangling "\\" and "\t"s, the metadata import succeeds.

Note also that in other places, it tripped over "\r\n" (removed "\r" to make it work).

### Can you identify the location in the source code where the problem exists?

No

### If the bug is confirmed, would you be willing to submit a PR?

Not a haskel guy, so not really.

**Comment by Grubba27** [comment]
Hello! I've never contribuited to a Haskell project but I would love to start. This is a Hard issue to be done ?
If is not could I get some directions to where to start ? I would start removing "\" something ? or I got this wrong ?
