### ISSUE TITLE
Filter (search) tables by name on console

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#8218]
### Is your proposal related to a problem?

For data sources with a long list of tables, finding the right table to navigate to is not an easy task with Hasura v2. Hasura v2 had a search input which I could use to filter the list down by table name. But with v2, this functionality is lot. It would be add to the user experience so much if this functionality is bought back.

### Describe the solution you'd like

A search input which I can use to filter the names of tables within a datasource.

### Describe alternatives you've considered

I have scrolled up and down the list many times trying find the right table name using my eyes and clicking on it, typing the name and narrowing down the list must be much faster.

### If the feature is approved, would you be willing to submit a PR?

I won't be able to commit as of now :)

**Comment by rikinsk** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/bd05e242d5a8744cf3f7881168af953fba6674f4
