### ISSUE TITLE
Column Presets not working in Sql Server

### ISSUE THREAD

**Issue by m4ttheweric** [hasura/graphql-engine#8221]
### Version Information

Server Version: 2.3.0-beta.2 and beta.1

### Environment

Core / sql server

### What is the expected behaviour?

When configuring a column preset, that it would use that preset...

### Keywords

column presets, sql server

### What is the current behaviour?

When you set a preset either using a server variable like `x-hasura-user-id` or even a hard coded value, it does not work and produces an error.

The error in my case is a rejected insert because of a constraint violation b/c the column in question cannot insert a NULL value. This error occurs because the preset is not part of the insert script generated by the insert mutation.

I am not sure if perhaps the preset is supposed to be invoked after the insert? But whatever the case, my mutations are failing. Since the column preset disallows inserting into that column, it of course doesn't show up as a column I can provide a value for. And without an value for the insert either manually provided or via the preset then the query fails.

Error is : ```Integrity constraint violation. [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the value NULL into column 'UserId', table 'answr.Messaging.ConversationMessage'; column does not allow nulls. INSERT fails.```

### Screen Shots:
Here's the column preset setup screen:
![Screen_Shot_2022-02-17_at_12-1 59 08_PM](https://user-images.githubusercontent.com/49927862/155211568-d4da798e-e41f-419e-b90e-e09ae4973bde.png)

Here's what happens when trying to run an insert:
![Screen_Shot_2022-02-17_at_12-1 59 30_PM](https://user-images.githubusercontent.com/49927862/155211763-58914b87-f0c7-4cf5-b9a0-d1216766214e.png)

**Comment by sassela** [comment]
@m4ttheweric thanks so much for the detailed bug report! This has been addressed at https://github.com/hasura/graphql-engine/commit/92ab93775f5d79aa9407999acb0f85c948d3155d. The fix will be available in the next release within the next two weeks.

 In the meantime, you can try it out using the Docker image `hasurabuild/graphql-engine:mono-branch-main-8527749c3`.
