### ISSUE TITLE
JWK Refresh polling and CacheControl

### ISSUE THREAD

**Issue by Twister42** [hasura/graphql-engine#8236]
Hello,
  I'd like to speak about the JWK refresh mechanism discussed in issue [#5781](https://github.com/hasura/graphql-engine/issues/5781)

  I think the implementation here does not respect the must-revalidate spec.

  The must-revalidate specifications are [(link)](https://datatracker.ietf.org/doc/html/rfc7234#section-5.2.2.1) :
   ```
   The "must-revalidate" response directive indicates that once it has
   become stale, a cache MUST NOT use the response to satisfy subsequent
   requests without successful validation on the origin server.

   The must-revalidate directive is necessary to support reliable
   operation for certain protocol features.  In all circumstances a
   cache MUST obey the must-revalidate directive; in particular, if a
   cache cannot reach the origin server for any reason, it MUST generate
   a 504 (Gateway Timeout) response.

   The must-revalidate directive ought to be used by servers if and only
   if failure to validate a request on the representation could result
   in incorrect operation, such as a silently unexecuted financial
   transaction.
```

What it means is :
* you can cache the request
* if the data is stale you HAVE to make a new request, you can't send your cache. So if the server is not responding the browser/proxy is supposed to return a 504 error.

Therefore I strongly believe that the polling every second is not justified when must-revalidate is present.
This information is only there for proxy that could be present between Hasura and the server hosting the JWK data.

Regards.

_Originally posted by @Twister42 in https://github.com/hasura/graphql-engine/issues/5781#issuecomment-1048799643_

**Comment by tirumaraiselvan** [comment]
Thanks for the issue. You are right, we will fix this ASAP.

**Comment by tirumaraiselvan** [comment]
Closing as per comment in another issue: https://github.com/hasura/graphql-engine/issues/8299#issuecomment-1067696243
