### ISSUE TITLE
No trigger created with Updated At Frequently Used Column creation

### ISSUE THREAD

**Issue by zanebclark** [hasura/graphql-engine#8239]
### Version Information

Docker Image: hasura/graphql-engine:v2.2.0.cli-migrations-v2
Server Version: v2.2.0
CLI Version (for CLI related issue): cli-migrations-v2

### Environment

Apple Silicon, BigSur 11.4
Docker Compose w/ Hasura Console + Postgres DB

### What is the expected behaviour?

Per the description of the "updated_at" "Frequently used column", updating a field on a record _should_ result in a different `updated_at` value than was assigned upon the record's creation. 

### Keywords

updated_at
trigger

### What is the current behaviour?

An up migration is created:
```sql
alter table "<SchemaName>"."<TableName>" add column "updated_at" timestamptz
 null default now();
```

There's no SQL trigger associated with this migration. `updated_at` could be refreshed via other mechanisms. If I insert a record and update a field on said record, the `updated_at` column still reflects the insertion timestamp

### How to reproduce the issue?

1. Navigate to `Data` tab
2. Select a table
3. Navigate to `Modify` sub-tab
4. Select `Add a new column`
5. Select `Frequently used columns`
6. Select `updated_at` and `created_at` (for comparison)
![image](https://user-images.githubusercontent.com/5956939/155568108-e57d69df-a4b7-4ee9-ad4e-8a7edb75184f.png)
7. Select `Save`
8. Insert a record into the table w/ the `updated_at` column
9. Perform a SQL update statement on the underlying DB changing some field on the record
10. Compare the `created_at` timestamp with the `updated_at` timestamp.

**Comment by ctrlemo** [comment]
Wanted to let you know I also experienced the same issue on v2.2.0 today while developing.

**Comment by vijayprasanna13** [comment]
@ctrlemo was this while running both the Hasura v.2.2.0 server and cli? It'd be helpful to debug if you could get the request body that is generated by the console while creating the table (refer to this https://github.com/hasura/graphql-engine/issues/8239#issuecomment-1063795759 for the steps on how do that).

**Comment by Salman9000** [comment]
Hello.
The trigger is only created if you are creating a new table. If for example you did not add a column of updated_at while creating a new table, and you decided to add it afterwards once the table is created, then it will not work.
I am facing the same issue when creating new column of "updated_at" in modify tab. The trigger is not adding. Had to delete the entire table and create a new.
Please fix

**Comment by vijayprasanna13** [comment]
@Salman9000 Thanks for the input! I've been able to replicate the trigger not being created while adding new columns via the modify tab. I can also confirmed that this issue exists on `v2.2.2` as well. We'll take a look into it

**Comment by Varun-Choudhary** [comment]
Hey folks! After some poking around I've found that the `dependentSQLGenerator` is not called while adding columns from the modify tab. Will open a PR to fix this.

**Comment by Salman9000** [comment]
Glad to hear! I am surprised how this issue was not raised previously.
While you are looking into that, i would also like to add that if the column is renamed, the trigger does not work.

**Comment by vijayprasanna13** [comment]
@Salman9000 right now, there is no option to automatically modify the trigger function related to a column when the column name is updated but we can add this to our list of requested features. I'll track this in a separate issue. 
In the meantime, you can workaround this by modifying the trigger function definition via the RawSQL tab. 
![Kapture 2022-03-16 at 16 07 24](https://user-images.githubusercontent.com/11921040/158571919-ec3ec0cf-71b7-4071-a4b1-eefbfb848a6c.gif)

**Comment by rikinsk** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/7eb59330b1c7a3b9a237f91a08df9571467e7036
