### ISSUE TITLE
webhook authentication + subscriptions

### ISSUE THREAD

**Issue by rafaelugolini** [hasura/graphql-engine#824]
Anyone had issues using subscription and webhook authentication?

The examples pointed [here](https://github.com/hasura/graphql-engine/tree/master/community/boilerplates/auth-webhooks/nodejs-express) doesn't seem to work with apollo-client 

The headers are not being sent.

ps: only the websocket connection is not working, normal queries are working well.

**Comment by coco98** [comment]
@shahidhk @praveenweb @ecthiender @rikinsk Folks it's been a while on this issue, please look at this!

@rafaelugolini Is this still a problem you're facing?

**Comment by jasine** [comment]
@rafaelugolini It's a problem out team facing, is there any solution or guide we can follow?

**Comment by wawhal** [comment]
Hey @jasine how are you sending the headers from apollo-client?

**Comment by rafaelugolini** [comment]
@coco98 just updated to the newer docker version and looks like it's working.

@jasine I just updated the alpha 27th and it looks fine

**Comment by jasine** [comment]
@tirumaraiselvan thanks, alpha 27th works.
@wawhal the following headers is working with apollo-client when i use alpha 27th
![image](https://user-images.githubusercontent.com/1934966/47805590-ab045c00-dd72-11e8-83b4-3ce6305d8808.png)
