### ISSUE TITLE
Syntax error in CLI install script when specifying version

### ISSUE THREAD

**Issue by mccare** [hasura/graphql-engine#8247]
### Version Information

CLI Version (for CLI related issue): 2.2.0

### Environment

Linux

### What is the expected behaviour?

The install script will install the specified CLI.

### Keywords

install, CLI

### What is the current behaviour?

when running with `VERSION=v2.2.0` the correct version is installed but the update check is run. This causes the
install script to fail.
### How to reproduce the issue?

1. curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | VERSION=v2.2.0 INSTALL_PATH=/Users/chris/bin bash
 
### Please provide any traces or logs that could help here.

```shell
curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | VERSION=v2.2.0 INSTALL_PATH=/Users/chris/bin bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   139  100   139    0     0   1110      0 --:--:-- --:--:-- --:--:--  1177
100  4252  100  4252    0     0  17570      0 --:--:-- --:--:-- --:--:-- 17570
--> Selecting version...
--> Selected version: v2.2.0
-->
--> NOTE: Install a specific version of the CLI by using VERSION variable
--> curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | VERSION=v2.2.1 bash
-->
-->
--> You already have the hasura cli at '/opt/homebrew/bin/hasura'
--> Downloading again in 3 seconds... Press Ctrl+C to cancel.
-->
--> Downloading hasura for darwin-arm64 to /tmp/cli-hasura-darwin-arm64
######################################################################## 100.0%##O#-#
--> Download complete!
--> Moving cli from /tmp/cli-hasura-darwin-arm64 to /Users/chris/bin
-->
--> hasura cli installed to /Users/chris/bin
-->
INFO A new version (v2.2.1) is available for CLI, update? (y/N)
INFO skipping update, run 'hasura update-cli' to update manually
INFO hasura cli                                    version=v2.2.0
bash: line 154: syntax error near unexpected token `then'
bash: line 154: `! $(echo "$PATH" | grep -q "$INSTALL_PATH"); then'
```

### Any possible solutions?

* do not specify the VERSION
* in `hasura version` in the install script, specify `--skip-update-check`
* 
### Can you identify the location in the source code where the problem exists?

PR is forthcoming.

**Comment by scriptonist** [comment]
Fixed in https://github.com/hasura/graphql-engine/pull/8248
