### ISSUE TITLE
inherited roles created via metadata api not applies  

### ISSUE THREAD

**Issue by zlil** [hasura/graphql-engine#8265]
### Version Information

Server Version: 2.1.1

### Environment

Docker container

### What is the expected behaviour?

after creating inherited roles via metadata API  reflect the new roles inside the 'permissions' tab for the related tables.

### Keywords

API metadata roles inherited

### What is the current behaviour?
 
I'm trying to create roles using inherited roles in the metadata api - https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/inherited-roles.html

I'm receiving successful response and I see newly created file inside /hasura/metadata/inherited_roles.yaml which looks like this:
<img width="274" alt="image" src="https://user-images.githubusercontent.com/14261475/156211971-b2eb288a-39c7-4a57-9211-d1a432b670ef.png">

In this example, I tried twice to create support roles that inherit from the editor role.

The thing is, I don't see the role in the console:
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/14261475/156212182-a811f6f9-b3c1-45be-bdac-c0ddf8bd7801.png">

I already tried to refresh the console, rebuild the docker container, but still, it's not reflecting.

### How to reproduce the issue?

call add_inherited_role endpoint, check if you see a new role.

maybe I'm missing something - do I need to create the role somehow before calling add_inherited_role endpoint?
If so, is there any related endpoint to create a new role with no permissions at all or default permissions on creation?

**Comment by tirumaraiselvan** [comment]
Inherited roles are shown here (go to gear icon on top right -> Inherited roles) :

![image](https://user-images.githubusercontent.com/8663570/161559943-eb837ff4-6739-454a-87eb-607f4f0b9c05.png)
