### ISSUE TITLE
Action relationship for nullable field is non-nullable 

### ISSUE THREAD

**Issue by jdurcik** [hasura/graphql-engine#8274]
### Version Information

Server Version: v2.3.0

### Environment

OSS

### What is the expected behaviour?

Relationship based on nullable field should be nullable.

### Keywords

action relationship nullable

### What is the current behaviour?

Relationship based on nullable field is non-nullable

### How to reproduce the issue?

1. create action with output type containing nullable field
2. add relationship based on this field

### Screenshots or Screencast

<img width="302" alt="Snímek obrazovky 2022-03-03 v 14 36 35" src="https://user-images.githubusercontent.com/98015044/156575421-cc50ebc1-2610-4f64-9168-0c257b447cf4.png">
<img width="399" alt="Snímek obrazovky 2022-03-03 v 14 36 48" src="https://user-images.githubusercontent.com/98015044/156575454-3315b421-99e9-4605-860d-ae7411e10c26.png">
<img width="351" alt="Snímek obrazovky 2022-03-03 v 14 37 17" src="https://user-images.githubusercontent.com/98015044/156575545-c92cf399-dd09-4cbc-ae55-bcdd578cbe49.png">

**Comment by pranshi06** [comment]
@jdurcik can you send the webhook response you are sending and the expected action output?

**Comment by pranshi06** [comment]
@jdurcik The bug has been fixed in v2.5.0-beta.1

**Comment by tirumaraiselvan** [comment]
Just FYI, all action object relationships are nullable since even if the action field is non-nullable, there is no guarantee that the relationship object will be present in the DB. Action relationships have the same type semantics as manual relationships for tables.
