### ISSUE TITLE
Database customization not exported to metadata files

### ISSUE THREAD

**Issue by stefan1968** [hasura/graphql-engine#8292]
### Version Information

Server Version: v2.4.0-beta.1
CLI Version (for CLI related issue):

### Environment

Docker - Self Hosted
### What is the expected behaviour?

customization is not exported to the database.yml 

### What is the current behaviour?

When you add a database source via the api with a “customization” node, with namespace, if you export the metadata, the customization is not exported to the database.yml and when you next apply metadata it overwrites and clears the namespacing and then all hell breaks loose!  Essentially the metadata export does not export the customization node, at least as far as I can see.

**Comment by tirumaraiselvan** [comment]
I can see that export_metadata does give `customization`:

```
{
  "resource_version": 7,
  "metadata": {
    "version": 3,
    "sources": [
      {
        "name": "default",
        "kind": "postgres",
        "tables": [
          {
            "table": {
              "schema": "public",
              "name": "test"
            }
          }
        ],
        "configuration": {
          "connection_info": {
            "use_prepared_statements": true,
            "database_url": {
              "from_env": "HASURA_GRAPHQL_DATABASE_URL"
            },
            "isolation_level": "read-committed",
            "pool_settings": {
              "connection_lifetime": 600,
              "retries": 1,
              "idle_timeout": 180,
              "max_connections": 50
            }
          }
        },
        "customization": {
          "type_names": null,
          "root_fields": {
            "suffix": null,
            "prefix": null,
            "namespace": "mynamespace"
          }
        }
      }
    ]
  }
}
```

So this seems like a CLI parsing bug.
