### ISSUE TITLE
Hasura 2.1.1 exploded this morning, across multiple independent installs and environments simultaneously

### ISSUE THREAD

**Issue by carlpaten** [hasura/graphql-engine#8298]
### Version Information

Server Version: 2.1.1

### Environment

`hasura/graphql-engine:v2.1.1` docker image on AWS Fargate, Ubuntu, Linux and Windows

### What is the expected behaviour?

Low CPU usage, opening a table in Hasura web console works

### Keywords

"arg mismatch between arg and selection"

### What is the current behaviour?

- Very high `graphql-engine` CPU usage leading to request timeouts
- Can't open tables in Hasura web console

### How to reproduce the issue?

1. Be on Hasura 2.1.1
2. ???
3. Pain

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/1834919/157487101-46fc77a6-a34e-40e7-abbe-09cd167b752b.png)

### Please provide any traces or logs that could help here.

Seen in the browser console on Hasura web console:

```
arg mismatch between arg and selection 
Object { name: "transaction_order_by", description: "Ordering options when selecting data from \"transaction\".", extensions: undefined, astNode: undefined, extensionASTNodes: undefined, _fields: {…} }
 
Object { kind: "ListValue", values: (1) […], loc: undefined }
vendor.js.gz:1:7184335
```

### Any possible solutions?

Update version to 2.0.10, 2.2.1, or 2.3.0

### Can you identify the location in the source code where the problem exists?

Nope

### If the bug is confirmed, would you be willing to submit a PR?

Nope, I have no idea what's going on

**Comment by aaka3207** [comment]
This also happened to me this morning.

**Comment by dopecoder** [comment]
Im experiencing the same thing from this morning for a specific table. Looks like FE issue.

On Chrome : 
`
rror: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at oc (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5486981)
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5432151
    at Zo (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5442287)
    at Ql (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5482766)
    at zl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5473739)
    at jl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5473664)
    at kl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5470514)
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5421486
    at t.unstable_runWithPriority (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5497297)
    at oa (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5421195)
`

On Safari : 
`
oc@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5486986
@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5432153
Zo@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5442289
Ql@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5482768
zl@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5473741
jl@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5473666
kl@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5470516
kl@[native code]
@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5421487
@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5497298
ua@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5421433
ca@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5421368
Ll@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5470913
n@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:109533
e@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:110231
e@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:110311
e@[native code]
g@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:1865379
@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/main.js.gz:1:3541643
@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/main.js.gz:1:2225312
promiseReactionJob@[native code]
`

**Comment by rikinsk** [comment]
To add some context, we recently updated the console CDN assets with a hotfix for [this bug ](https://github.com/hasura/graphql-engine/issues/8064) which is likely to have now introduced the error that you are facing. As @BenoitRanque mentioned a temporary workaround would be to use the local assets bundled with the server but do be aware of the above issue as the local assets will have that bug.

**Comment by carlpaten** [comment]
@rikinsk thank you for your reply. Could the console CDN asset issue have caused the increased CPU load on the GraphQL engine instance? We suffered a ~35 minute slowdown/partial downtime, I'm trying to figure out what the story is so I can tell it to the rest of the org.

**Comment by rikinsk** [comment]
@carlpaten I cant say for sure. It might be possible that the console JS might have gotten into a situation where it would consume a lot of CPU by getting stuck in some infinite loop making requests for example. But its quite hard to say without actually observing in the browser dev tools what the console was doing at time. If you can still reproduce this then you should be able to test that out by checking the browser activity on the console tab when the crash happens.If you can still reproduce this then you should be able to test that out by checking the browser activity on the console tab when the crash happens.

**Comment by rikinsk** [comment]
@carlpaten @aaka3207 @dopecoder Folks can you confirm if you are still facing this issue. It is possible that this might have been an issue caused by the CDN serving older assets even after we had released the update due to some cache / replication lag. If you are not observing the crash any more, it might help confirm that theory and we can look towards fixing it.

**Comment by aaka3207** [comment]
@rikinsk yes it's still happening to me in all environments. For me it specifically happens on a table with a **text** primary key column and a **citext** index column

**Comment by carlpaten** [comment]
The frontend bug was still happening this morning on 2.1.1. I haven't tried to reproduce the CPU load issue.

**Comment by rikinsk** [comment]
@carlpaten Thanks for the info

**Comment by mnlbox** [comment]
@rikinsk I faced the same issue right now but only for one of my tables. So console is working without any issue for all tables except one specific table when I open that table it's returns same error message:
```
Error: Minified React error #8130 
```

**Comment by vijayprasanna13** [comment]
@mnlbox I think this might be a separate console bug, could you share the schema for the table that crashes the console?

**Comment by mnlbox** [comment]
@vijayprasanna13 But I think it's related to this CDN issue because I didn't change my table schema for this table for a while. (maybe more than 2 or 3 weeks)
I just re-opened my console this morning to continue my unfinished work and it's not working for this specific table.
At first, I thought maybe it is because of my changes then I revert all of my changes and checkout to a stable version in the past of my git history but it's again not working for that specific table :thinking:

**Comment by mnlbox** [comment]
@vijayprasanna13 Like what @aaka3207 said I also have one text index column in this specific table. I don't know if this can help you to detect the issue or not.

**Comment by mnlbox** [comment]
I was using Hasura v2.1.1 after upgrading to Hasura v2.3.0 the problem solved. :+1:

**Comment by morishjs** [comment]
Hmm... For me, I'm still facing the issue even though I upgraded the version from v2.1.1 to v2.3.0 :(

**Comment by jayouimet** [comment]
I am also having this issue, I tried v2.0.10, v2.1.1, v2.2.0 and v2.3.0-beta.1, all of which were not working. I also tried adding HASURA_GRAPHQL_CONSOLE_ASSETS_DIR=/srv/console-assets to the .env file with no results. If that can help, I can only run into the error when browsing into 2 specific tables with no data in them. As soon as there is data I run into the error.

**Comment by vijayprasanna13** [comment]
@jayouimet could share the table schema for those specific tables? @mnlbox @aaka3207 reported that they had issues with text index columns, so this might be a issue with the browse tab which might be related to the CDN issue

**Comment by jayouimet** [comment]
@vijayprasanna13 After some testing it appears it happens on tables to which I have set an event trigger to. These 2 tables are the only ones in my database where I have event triggers for. One of them was a user table where the password_hash field would be modified upon modification to its hash (calls a webhook on insert and update of the password_hash field). I deleted the event trigger and got normal access to the browse section of the users table (used to get the Minified React error #130), then I added the event trigger back and got the error when browsing the users table back again. Hopefully this helps, let me know if my schema is needed regardless.

**Comment by vijayprasanna13** [comment]
@morishjs I tried the first one and these are the list of columns as per the schema. The browse and the modify tabs of the console load without any issues. Perhaps I'm missing some detail here. Is it possible to share a minimal metadata for the the `product_update_requests` table along with `product_update_request_state` & `products`? A Hasura instance on [heroku app](https://hasura.io/docs/latest/graphql/core/deployment/deployment-guides/heroku.html#deploying-hasura-on-heroku) with a minimal reproducible error state would be huge help here!

![Screenshot 2022-03-16 at 4 39 42 PM](https://user-images.githubusercontent.com/11921040/158576941-e1ea4728-3e37-4a63-bfaa-68d7b71679c9.png)

**Comment by morishjs** [comment]
@vijayprasanna13 
Okay I will do. I think that reproducible one would way better than writing down codes.

**Comment by rikinsk** [comment]
Folks we seem to have multiple different issues here that seem to be throwing very similar error messages and leading to a bit of confusion. I'll attempt to summarize my understanding below _(please do correct me if I have misunderstood or missed something)_ :

- The original issue raised by @carlpaten seems to be occurring on the API explorer page if I understand correctly. (exact error line: `vendor.js.gz:1:7184335`. (We havent been able to reproduce this yet.)
- The issue faced by @dopecoder @aaka3207 @jayouimet @mnlbox seems to be happening on the browse rows page of certain tables. (exact error line: `vendor.js.gz:1:5486981`). (We might have a lead on this one. Could you folks confirm if you folks have any [manual event triggers](https://hasura.io/docs/latest/graphql/core/event-triggers/invoke-trigger-manually.html) defined on your affected tables?)
- @morishjs is also facing an issue but it seems to be happening in `v2.3.0` so isn't specific to the `v2.1.1` .

As this thread is specific to regressions in `v2.1.1` post updating the CDN assets, if the error you are facing is not just limited to `v2.1.1` and you are still facing them in the latest Hasura version I would suggest opening them as separate issues with some details added to help us investigate them separately and avoid confusion.

**Comment by carlpaten** [comment]
I apologize, my issue was happening on the browse rows page. So I believe it's the same issue as the others (except @morishjs).

**Comment by morishjs** [comment]
My workaround was that

1. upgrade v2.1.1 to v2.3.0
2. Save the metadata to restore after deleting some triggers.
3. delete all event triggers related to a table occuring the issue.
4. import the metadata 
5.

I hope this could help to someone
