### ISSUE TITLE
Server refuses queries when more than 900 queries/s

### ISSUE THREAD

**Issue by gauthierrodaro** [hasura/graphql-engine#830]
I did a simple script to test if `graphql-engine` could handle big loads (e.g. IOT projects) but it looks like it can't...

Am I doing something wrong? 

It is running in a docker container
# Versions
- **postgres**: timescale/timescaledb-postgis:1.0.0-rc2-pg10
- **graphql-engine**: hasura/graphql-engine:v1.0.0-alpha25

# Error
`FetchError: request to http://localhost:8080/v1alpha1/graphql failed, reason: connect ECONNRESET 127.0.0.1:808`

# Script:
```
import dayjs from "dayjs"
import { range } from "lodash"
import { GraphQLClient } from "graphql-request"

async function main() {
  const endpoint = "http://localhost:8080/v1alpha1/graphql"

  const graphQLClient = new GraphQLClient(endpoint, {
    headers: {
      "X-Hasura-Access-Key": "************"
    }
  })

  const mutation = `
    mutation {
      insert_observations(objects: {
        timestamp: "${dayjs().toISOString()}",
        value: 42
      }) {
        returning {
          timestamp
        }
      }
    }
  `

  const requests = range(1000).map(() => graphQLClient.request(mutation))
  await Promise.all(requests)
  console.log("🎉 done!")
}

setInterval(() => main().catch(error => console.error(error)), 1000)
```

**Comment by 0x777** [comment]
We'll try to reproduce this and get back to you as soon as possible.

**Comment by tpiros** [comment]
I run into something similar as well although with a different engine. I hope to see an update on this soon which will hopefully shed some light into my issue as well.

**Comment by 0x777** [comment]
We can't reproduce this on our end
