### ISSUE TITLE
server: json scalar response is empty in action

### ISSUE THREAD

**Issue by hgiasac** [hasura/graphql-engine#8301]
### Version Information

Server Version: v2.3.0
CLI Version (for CLI related issue):

### Environment
OSS

### What is the expected behaviour?

For example, an action that returns a `json` scalar 

```graphql
type Query {
  responseJsonItem: json
}
```

The expected response is a dynamic object

```json
{
    "responseJsonItem": {
      "hello": "world"
    }
}
```

### Keywords
action scalar json

### What is the current behaviour?

An empty object is returned

```json
{
    "responseJsonItem": { }
}
```

### How to reproduce the issue?

1. Reproducing repository https://github.com/hgiasac/graphql-engine-action-scalar-json-empty
2. Create an action that returns json 
3. Write an action webhook that returns mock json data
4. Run the query on Graphiql 

### Screenshots or Screencast

![Screenshot_20220311_020636](https://user-images.githubusercontent.com/1615675/157736922-d633cccd-03fe-4675-9369-db1e124b336c.jpg)

### Please provide any traces or logs that could help here.
None 

### Any possible solutions?
None

### Can you identify the location in the source code where the problem exists?
No

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by pranshi06** [comment]
Closed via 056765578fa6b23c5d757b7a3e2bf6829cb0d9a0
