### ISSUE TITLE
[Question] Is graphql-ws support still considered BETA?

### ISSUE THREAD

**Issue by efstathiosntonas** [hasura/graphql-engine#8303]
Sorry for not using bug template, it's more of a question than a bug.

[Apollo client encourages devs](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws) for Apollo Client v3.5.10 or later to use `graphql-ws` instead of `subscriptions-transport-ws`. 

As per [Hasura docs](https://hasura.io/docs/latest/graphql/core/databases/postgres/subscriptions/index.html#communication-protocol) `graphql-ws` is considered beta, is it still in beta or it's considered safe to use?

Thanks

**Comment by tirumaraiselvan** [comment]
Hi, graphql-ws has been out since v2.1 so it's reasonably well tested. We will remove the beta tag and promote it to stable in the next release or so.

**Comment by efstathiosntonas** [comment]
@tirumaraiselvan thanks for the clarification.

**Comment by tirumaraiselvan** [comment]
Closing this. The GA status should be reflected in future releases as of this commit: https://github.com/hasura/graphql-engine/commit/8ef270404a09ec52a946537aa839ab05e376636f
