### ISSUE TITLE
Allow using computed fields with hasura session in permission builder

### ISSUE THREAD

**Issue by noverby** [hasura/graphql-engine#8321]
### Is your proposal related to a problem?

I'm currently trying to setup a permission system, that uses computed fields with a hasura session argument.
Unfortunately, computed fields with a hasura session argument does not show up in the permission builder. 

### Describe the solution you'd like

I would expect computed fields with a hasura session argument to show up in the permission builder.

### Describe alternatives you've considered

Create an even more complex permission system (with performance overhead), that combine computed fields without a hasura session and additional checks in the permission builder, that actually checks relevant values in the hasura session.

### If the feature is approved, would you be willing to submit a PR?

No, I'm not familiar with the graphql-engine codebase

**Comment by radha-igtb** [comment]
We are in need of this feature and it does not seem to be working. I am trying with v2.5.0. My computed field function returns a boolean value. So ideally it should work. 
We understand that there is an issue with computed fields which use the Hasura session variable. these do not come up when setting say select permissions for the user role.

**Comment by m-revetria** [comment]
Hello, is there an ETA to get this released? I'm needing this feature to check whether a user has access to some resources stored in a postgres db. In my use case, the permission filter are becoming really complex and they are getting duplicated in several tables, this feature would help a lot.

Thanks

**Comment by rikinsk** [comment]
Apologies for the delay on this. This should be available in `v2.9.0`. As this is a console only issue, In the meanwhile you could directly update the metadata / use the create permission API to to use computed fields in your permission rules
