### ISSUE TITLE
accept query params for filter/sort in browse table page

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#833]
Accept URL query params for filter/sort in console's browse table page so that it can be like the default query when the page is opened.

(via comfortablydumb on Discord)

**Comment by bendtherules** [comment]
Hi,
I would like to take this up.

**Comment by feloy** [comment]
I would like to work on this issue

**Comment by feloy** [comment]
Just to be sure. is it about this page?

http://localhost:8080/console/data/schema/public/tables/mytabe/browse?params...
