### ISSUE TITLE
More-permissive updates of inherited children should take precedence and be used instead of throwing "inherited role permission inconsistency"

### ISSUE THREAD

**Issue by corsali-albert** [hasura/graphql-engine#8343]
### Version Information

Server Version: 2.3.1
CLI Version (for CLI related issue): 2.3.1

### Environment

OSS

### What is the expected behaviour?

More-permissive updates of inherited children should take precedence and be used.

`inherited role permission inconsistency` should be displayed in the console upon save if they are actually inconsistent.

### Keywords

inherited roles

This issue is similar but different: https://github.com/hasura/graphql-engine/issues/8063

### What is the current behaviour?

**This fails silently**. Saving the permission is successful, and the console behaves normally, but **the role is not updated and refreshing the console gets redirected to the metadata status page which comes up as a 404**.

### How to reproduce the issue?

1. Create role A. Give it update permissions on table X with a limited row select and a limited column select.
2. Create role B. Give it update permissions on table X with unlimited row and column select permissions.
3. Create inherited role C, have it inherit from roles A and B.
4. Refresh the console.

### Screenshots or Screencast

Sensitive data, sorry.

### Please provide any traces or logs that could help here.

```xxxx-hasura-engine-1  | {"type":"metadata","timestamp":"2022-03-18T22:34:40.763+0000","level":"warn","detail":{"message":"Inconsistent Metadata!","info":{"objects":[{"reason":"Could not inherit permission for the role 'xxaaxx' for the entity: 'update permission, table: xxbbxx, source: 'default''","name":"xxaaxx","type":"inherited role permission inconsistency","entity":{"permission_type":"update","source":"default","table":"xxbbxx"}}]}}}```

### Any possible solutions?

Don't use inherited roles and instead replicate the functionality manually by computing the equivalent and manually keeping it in sync with what would have been its children.

### Can you identify the location in the source code where the problem exists?

Sorry I cannot.

### If the bug is confirmed, would you be willing to submit a PR?

Sorry, I don't know haskell.

**Comment by BenoitRanque** [comment]
I've been able to reproduce this in 2.3.0.

Currently this can be worked around by clicking the resolve button besides the error message. This will allow you to set the permissions for that operation and role explicitly.

**Comment by corsali-albert** [comment]
> I've been able to reproduce this in 2.3.0.
> 
> Currently this can be worked around by clicking the resolve button besides the error message. This will allow you to set the permissions for that operation and role explicitly.

There is no "resolve" button in the error message for me, as there is no error message: it fails silently, and I'm simply redirected to the 404 page on refresh.

**Comment by BenoitRanque** [comment]
@corsali-albert I should have mentioned in my previous message: I needed to perform a metadata reload for the error to show up. Can you try that?

**Comment by tirumaraiselvan** [comment]
This has been fixed in https://github.com/hasura/graphql-engine/commit/df23bdb5f01c5678d15712ce229a5882dfd13564 and should be out in the next beta release.

**Comment by tirumaraiselvan** [comment]
As for the behaviour of composing roles:

> More-permissive updates of inherited children should take precedence and be used.

This makes sense and is part of our roadmap for inherited roles.

**Comment by pe224** [comment]
Thanks for the hint @BenoitRanque 
Maybe a quick note for those on older versions who can't use the console fix in production (yet):
I opened the metadata settings `/console/settings/metadata-actions` in one browser tab and then updated the permissions in another tab. As "expected", the permissions tab will 404, but the settings tab is still working and you can reload metadata and click the mentioned `resolve` button.

**Comment by tirumaraiselvan** [comment]
Keeping the issue open to address OP's ask:

> More-permissive updates of inherited children should take precedence and be used.

Changed the title to reflect the same.
