### ISSUE TITLE
remote schema relationship is null even though relationship exists when i have multiple relationships to the same schema

### ISSUE THREAD

**Issue by zolamk** [hasura/graphql-engine#8345]
### Version Information

Server Version: v2.3.1
CLI Version (for CLI related issue): v2.3.1

### Environment

OSS

### What is the expected behaviour?

all remote relationships to the same schema should not be null because one is null, hasura should return data for the available relationships and null for the unavailable ones

### Keywords

remote-schema

### What is the current behaviour?

I have a hasura server in which tables have `created_by` and `updated_by` columns, where `updated_by` is nullable like below

![image](https://user-images.githubusercontent.com/14203663/159419310-82e2c3d9-6fe3-4e9d-b721-c5c1b4b36621.png)

i have a remote schema relationship setup like this

![image](https://user-images.githubusercontent.com/14203663/159419370-f68ae0dd-287f-488c-8c54-585e74cf6538.png)

`created_by` is set on insert operations and `updated_by` on update operations

![image](https://user-images.githubusercontent.com/14203663/159424962-c4c94631-70b6-401a-9d36-455136ac4754.png)

when i query the data like this

```
query {
  users_roles {
    name
    creator {
      id
      name
    }
    updater {
      id
      name
    }
  }
}
```
for rows where `updated_by` is null both `creator` and `updater` remote schema relationships are null

![image](https://user-images.githubusercontent.com/14203663/159425136-8dc15652-a426-4d28-a08d-0a9262f6dcd9.png)

### How to reproduce the issue?

1. created a table with `created_by` and `updated_by` columns related to a remote schema as `creator` and `updater`
2. set `created_by` only for one of the rows
3. query your data
4. for the row where `updated_by` is not set, both `creator` and `updater` will be null

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/14203663/159419310-82e2c3d9-6fe3-4e9d-b721-c5c1b4b36621.png)

![image](https://user-images.githubusercontent.com/14203663/159419370-f68ae0dd-287f-488c-8c54-585e74cf6538.png)

![image](https://user-images.githubusercontent.com/14203663/159424962-c4c94631-70b6-401a-9d36-455136ac4754.png)

![image](https://user-images.githubusercontent.com/14203663/159425136-8dc15652-a426-4d28-a08d-0a9262f6dcd9.png)

### Any possible solutions?

as a work around currently i am setting `updated_by` too on insert, but there are situations that solution is wrong

### Can you identify the location in the source code where the problem exists?

No, i wish i could.

### If the bug is confirmed, would you be willing to submit a PR?

I don't know Haskell 😟

**Comment by sheldonbaker** [comment]
This is biting me too.

Can confirm that if _one_ of the column values is null, then _both_ remote relationships return null.

**Comment by zolamk** [comment]
Another possible work around might be providing a default value from your remote schema that returns a default for your relationship, maybe even `null`

**Comment by vshelke** [comment]
Any updates on this issue ? I am also facing similar issues

**Comment by harshalgalgale** [comment]
Any update on this issue...? We too are facing similar issue, since we have updated Hasura from v2.0.9 to 2.8.1.

**Comment by cyber1998** [comment]
Facing the same issue here.. it would be great if we can fix this as soon as possible. 99% of our frontend (both web and mobile) are reliant on Hasura and we would love to use the new features of the latest releases but due to this bug we had to revert back to an older version. :(

**Comment by nicuveo** [comment]
Sorry for the delay! We have a PR with a fix, I'll let you know as soon as it is merged to main.
