### ISSUE TITLE
Support backup/restore Postgres database right from Console UI

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#836]

**Comment by revskill10** [comment]
Streaming download is nessessary in this caes for large database.

**Comment by mnlbox** [comment]
@revskill10 Maybe related: #1967, #2121

**Comment by mnlbox** [comment]
@shahidhk Maybe some option also useful for example:
* Select schema for import/export
* Export mode
   * Schema only
   * Data only
   * Schema + Data (full mode)

**Comment by manasag** [comment]
Thanks everyone for your comments and patience on this issue. We plan to provide a more mature database management experience in Hasura V3, by integrating a full feature database manager within Console. Closing this issue, in favor of this new V3 [issue](https://github.com/hasura/graphql-engine/issues/10076)
