### ISSUE TITLE
Event triggers optimization with `run_sql`

### ISSUE THREAD

**Issue by codingkarthik** [hasura/graphql-engine#8374]
### Is your proposal related to a problem?

Currently, while the [run_sql](https://hasura.io/docs/latest/graphql/core/api-reference/schema-api/run-sql/) API is run, all the SQL triggers defined in the source are dropped before running the user-provided SQL, this is done to so that the user-provided SQL have no conflicts with the Hasura defined triggers. After the SQL is run, the event trigger is recreated by Hasura. The recreation of the event trigger is a necessary step because if the SQL alters the structure of the table which have event triggers defined, then the SQL trigger needs to be updated according to the new structure of the table.

### Describe the solution you'd like

We need not drop all the SQL triggers defined in the source, instead, we should parse the user-provided SQL statements and get all the tables that are being altered and drop only the triggers of those tables and then we recreate the event triggers only for those tables. This way, the graphql-engine will only be recreating the triggers which are affected by the `run_sql` call.

### If the feature is approved, would you be willing to submit a PR?

sure, why not :smile:

**Comment by tirumaraiselvan** [comment]
> Currently, while the [run_sql](https://hasura.io/docs/latest/graphql/core/api-reference/schema-api/run-sql/) API is run, all the SQL triggers defined in the source are dropped before running the user-provided SQL, this is done to so that the user-provided SQL have no conflicts with the Hasura defined triggers

Does this dropping also happen when run_sql is run with `check_metadata_consistency: false` (https://hasura.io/docs/latest/graphql/core/api-reference/schema-api/run-sql/#schema-run-sql-syntax)

**Comment by tirumaraiselvan** [comment]
Closed via https://github.com/hasura/graphql-engine-mono/pull/4397
