### ISSUE TITLE
Hasura should check if triggers created by Hasura exist at startup, `reload_metadata` and `import_metadata`

### ISSUE THREAD

**Issue by codingkarthik** [hasura/graphql-engine#8376]
### Version Information

Server Version:
CLI Version (for CLI related issue):

### Environment

OSS

### Problem

Currently, when an event trigger is created in the graphql-engine it creates SQL triggers in the source as well. When the graphql-engine instance is restarted, we don't check if the event triggers present in the metadata have corresponding SQL triggers present in the source DB. This can happen when a table is dropped and then created again (done outside the graphql-engine) and the graphql-engine is restarted. In this case, the event trigger will exist in the metadata but there will be no corresponding SQL trigger present in the source, so events will never be generated in this case.

### What is the expected behaviour?

During startup, `reload_metadata` and `replace_metadata` the graphql-engine should check if the SQL triggers is present in the source or not. Additionally, while checking if the trigger exists or not, we can also check if the SQL definition is what the graphql-engine expects it to be. This can be done by comparing the hash of the definition of the trigger function definition that exists in the DB and the hash of the definition of the trigger function that we expect to be.

### How to reproduce the issue?

1. Create an event trigger `ET_A` on a table `A`
2. Drop table `A` along with its event triggers (to be done outside hasura)
3. Create table `A` again (to be done outside hasura)
4. Restart the hasura instance.

You should see that the `ET_A` will have no corresponding SQL triggers present.

#### Repro 2 (by @Naveenaidu )

 Say you have the following:

A table `author` and you have some event triggers associated to this table. 

1. Export this metadata and save it somewhere.
2. Drop the `author` table from the psql console or (mssql console) - All SQL triggers will be dropped since we drop the table
3. Create the author table via psql console
4. Import the metadata from the first step.

**Expected:**
The author table should have SQL event triggers created for it.
**What happens:**
The author table has no associated SQL triggers.

### Any possible solutions?

Check if the Hasura created triggers exist during `startup`, `reload_metadata` and `replace_metadata`.

**Comment by mcsimps2** [comment]
I came onto this repo looking exactly for this issue.  I had upgraded Hasura from 2.0.9 to 2.4.0 and realized that, when I reload the metadata, the triggers are no longer re-created. In 2.0.9, they would at least get recreated.  I was taking advantage of that so I could easily re-seed my local development database and then get the triggers back up and runnings by reloading the metadata.

**Comment by tirumaraiselvan** [comment]
We should also check if there are unnecessary triggers and remove them as well.

**Comment by codingkarthik** [comment]
closed via https://github.com/hasura/graphql-engine/commit/edef724879da7bbbd96dec4ab7c9c0c5fff29892

**Comment by webjunkie** [comment]
Is there a way to `recreate_event_triggers` via Hasura CLI?
