### ISSUE TITLE
stringify-numeric-types option is not respected in remote database relationships

### ISSUE THREAD

**Issue by Seeker14491** [hasura/graphql-engine#8387]
### What is the expected behaviour?

The `stringify-numeric-types` flag / `HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES` env variable makes the server stringify certain Postgres numeric types such as `bigint` that might be too big to represent as a JSON number.

### What is the current behaviour?

Despite enabling the `stringify-numeric-types` flag, when I perform a query that traverses a remote database relationship, a `bigint` field is being returned as a JSON number instead of a string.

### Screenshots

If I query the `users` table directly, then the `steam_id` field (which is a `bigint`) is returned as a string, as expected:
![chrome_0331](https://user-images.githubusercontent.com/6490497/162553628-fb74b88a-3853-4a0e-8e31-04805672194d.png)

However, if I traverse a remote database relationship, then the `steam_id` field is returned as a number:
![chrome_0329](https://user-images.githubusercontent.com/6490497/162553692-291efe69-f19c-4102-9bb5-ea072c428121.png)
Here, `lf_inspections` is a table in another postgres database, and `player` is a remote database relationship I've defined that connects it to the same `users` table from the previous query.

### Version Information

Hasura server: v2.4.0
Main Hasura db with `users` table: Postgres v14.2
Other db with `lf_inspections` table: Postgres v12.9

**Comment by beepsoft** [comment]
I think the same thing happens with actions returning a related entity. I have this action:

```graphql
type Mutation {
  registerUser(args: RegisterUserInput!): RegisterUserOutput
}

input RegisterUserInput {
  username: String
  email: String
  password: String!
  firstName: String
}

scalar bigint

type RegisterUserOutput {
  userId: uuid!
  profileId: bigint!
}

scalar uuid

```

And I have this realtionship:

```
RegisterUserOutput . profileId → default . public.profile . id
```

Now I receive a result like this, where Profile's `id` should be "24" but I get 24 (numeric):
```json
{
  "data": {
    "registerUser": {
      "profile": {
        "__typename": "profile",
        "id": 24,
        "email": "test@test.com",
        "firstName": "Test",
        "lastName": "User",
        "userId": "00de1cbf-9fb6-4005-950f-91f6b79c78a6",
        "user": {
          "__typename": "users",
          "id": "00de1cbf-9fb6-4005-950f-91f6b79c78a6"
        }
      }
    }
  }
}
```

All my typings expect string and this just breaks everything for me.

**Comment by beepsoft** [comment]
I just checked that in v2.1.1 I got back string values for data.registerUser.profile.id. In v2.13 I get it as number.

**Comment by thenonameguy** [comment]
+1 on this issue, this broke our Action mutation response follow-up reads as well by migrating to v2.13.0.

**Comment by sassela** [comment]
hey @Seeker14491 thank you for the bug report! I'll look into this today, try to repro on `v2.13.0` onwards and share any updates or questions I have with you here.

**Comment by sassela** [comment]
thanks again for your patience! I have a PR with a fix under review and will update this issue once it's merged.

**Comment by debagger** [comment]
Yesterday I unexpectedly encountered this problem. Now this is blocking the development of my project.

**Comment by sassela** [comment]
This fix has been reviewed, merged and will be available in the next stable [release](https://github.com/hasura/graphql-engine/releases) `v2.17.0`.

In the meantime, you can try it out using the Docker image: `hasurabuild/graphql-engine:mono-pr-7302-numeric.ubuntu`

Please reopen this issue (ideally with a repro case) if you have any other issues or questions post-release.
