### ISSUE TITLE
console: support remote db relationships for views

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#8409]
### Version Information

Server Version: v2.3.0 and above

### What is the expected behaviour?

Allow setting remote db relationships for views in the console. Also currently on adding a remote db relationship via the metadata directly causes the console to crash

### Keywords

remote db relationships, views

**Comment by abhi40308** [comment]
This should be resolved in https://github.com/hasura/graphql-engine/commit/d2f50e2a7e6798f15207f12473233eb8e7fa4f23
