### ISSUE TITLE
Add auth header to hasura CLI

### ISSUE THREAD

**Issue by kevin-meyers** [hasura/graphql-engine#8412]
### Is your proposal related to a problem?
I want to use the hasura CLI to apply metadata to a hasura instance hosted on GCP.

### Describe the solution you'd like
To specify the auth header as an env variable or argument which would pass through to the actual request

### Describe alternatives you've considered

Using the curl approach, but I would need to work with a single JSON file instead of the much nicer multiple yamls (for code review purposes)

### If the feature is approved, would you be willing to submit a PR?

Absolutely! I have never written any go, but I have an idea of how this might slot in fairly simply

**Comment by kevin-meyers** [comment]
We found a nicer alternative, using a proxy to set up a local connection to the hosted hasura, didnt need to pass any auth through at all. That may not be possible for everyone, let me know if I should close this issue

**Comment by rikinsk** [comment]
Hi. You can pass the admin-secret for you hasura instance as an env var to the CLI as described [here](https://hasura.io/docs/latest/graphql/core/hasura-cli/config-reference/). Do share a little more details on your use case if this is not what you were looking for.
