### ISSUE TITLE
not-found: Missing Env Var: on action Change Request Options

### ISSUE THREAD

**Issue by jasonmccallister** [hasura/graphql-engine#8428]
### Version Information

Server Version: v2.5.0
CLI Version (for CLI related issue): v2.5.0

### Environment

OSS

### What is the expected behaviour?

When modifying the Change Request Options for an action that uses an environment variable (e.g. `{{MY_FUNCTION_URL_ENV}}` the following error is displayed:

> not-found: Missing Env Var: MY_FUNCTION_URL_ENV

### Keywords

- action not-found 
- not-found: Missing Env Var:

### What is the current behaviour?

It shows an error even though the environment variable is there.

### How to reproduce the issue?

1. Use the `docker-compose` example
2. Add a new environment variable to the docker-compose.yaml
3. Create an action that uses the environment variable
4. Modify the  Change Request Options and set it to a POST 

### Can you identify the location in the source code where the problem exists?

Looked but can't find it.

### If the bug is confirmed, would you be willing to submit a PR?

Yes, if I knew where it was :)

**Comment by snaptsoft** [comment]
We appear to be facing the same issue after having tried several different conventions for the environment variable. We are using the same versions listed above, however, it is hosted on Heroku for our dev instance using the One Click Deploy.

**Comment by hallettj** [comment]
Hi! I'm investigating this issue. I want to double-check that you have included a placeholder value for the relevant environment variable in the "Sample Env Variables" list? That is in the "Sample Context" section. For security reasons when request options transforms are previewed the system does not use real environment variable values, it uses values from the "Sample Env Variables" list. If the environment variable is not in that list then at preview time you will get the error you reported, "not-found: Missing Env Var: MY_FUNCTION_URL_ENV". See https://hasura.io/docs/latest/graphql/core/actions/rest-connectors/#action-transforms-sample-context

**Comment by jasonmccallister** [comment]
@hallettj sorry for missing this...

I was not sure what this sample env vars were referring too... However, I have that environment variable defined in the docker compose, are you saying I need to add it to the samples list?

**Comment by hallettj** [comment]
Yes; I believe the error message you are seeing comes from a function that provides a preview of your custom action. For security reasons the preview does not have access to real environment variable values (such as the values defined in your docker compose config). The Sample Env Variables configuration it the action configuration UI allows you to provide an example value to use in the preview.

From the description of your report it sounds like you are using the console web UI to configure your action, and this is where are seeing the error message. The Sample Env Variables are configured on the same screen. You can find that option by expanding the Sample Context section. Sample env variables are configured per-action.
