### ISSUE TITLE
Namespace visibility during introspection

### ISSUE THREAD

**Issue by ericwilhite** [hasura/graphql-engine#8434]
Namespacing was introduced as discussed in #8204 to allow for multiple data sources with the same schema

This works well but there is an issue with namespace visibility.

Currently if a role only has access within one namespace they can still see all available namespaces. This is a showstopping issue for us. The namespaces reveal db names that correspond to our tenant information and even if we anonymized the namespace names it would cause confusion during introspection.

A role with no access within a given namespace should not be able to see it.

**Comment by paritosh-08** [comment]
Thanks for raising the issue. We have fixed this via https://github.com/hasura/graphql-engine/commit/2498176052d65e8cf5093a0e2947a10b10fd4526. This will be released soon.
