### ISSUE TITLE
Hasura 2.6.0 doesn't properly handle metadata involving tables with uppercase needing double quoting

### ISSUE THREAD

**Issue by 24601** [hasura/graphql-engine#8454]
### Version Information

Server Version:
CLI Version (for CLI related issue):
2.6.0
### Environment

OSS (although we are cloud customers for our production & dev envs, this is in our testing/validation for 2.6.0 before it becomes available on Hasura Cloud in our validation environment)
### What is the expected behaviour?
metadata apply works as expected

### Keywords
metadata

### What is the current behaviour?
Since 2.6.0 (no problem on 2.5.1 and below), metadata apply fails with a relation not found because somewhere in the processing, quoting is not being properly applied, causing the db engine to treat the relation name as case-insens, when it should double quote it to retain case sensitivity as a relation name reference.

We *DO* have the "Jobs" table, but we do not have "jobs". 

### How to reproduce the issue?
metadata apply any metadata with relations with uppercase characters in it

### Screenshots or Screencast

```
{
    "statement": "\n      SELECT EXISTS (\n        SELECT 1\n        FROM pg_trigger\n        WHERE NOT tgisinternal\n        AND tgname = $1 AND tgrelid = $2::regclass\n        )\n     ",
    "prepared": true,
    "error": {
        "exec_status": "FatalError",
        "hint": null,
        "message": "relation \"jobs\" does not exist",
        "status_code": "42P01",
        "description": null
    },
    "arguments": [
        "(Oid 25,Just (\"notify_hasura_jobs_geocode_handler_INSERT\",Binary))",
        "(Oid 25,Just (\"Jobs\",Binary))"
    ]
}
```

### Any possible solutions?

Check all code paths that handle relation names (esp changes since 2.5.1, since this issue is new in 2.6.0) for proper quoting.

Write better tests. This should not be something that occurs. Very easy to test for, and incredible that this made it into a release.

**Comment by jfacoustic** [comment]
I'm having the same exact issue.

**Comment by DavidKvas** [comment]
Same here.

**Comment by tirumaraiselvan** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/955db8ab114b85538f051ea9e5e4b130be7660d7
