### ISSUE TITLE
[Doc] Explain in the documentation what X-Hasura-Is-Owner does/means/is used for.

### ISSUE THREAD

**Issue by raarts** [hasura/graphql-engine#8460]
### Version Information

Server Version: any
CLI Version (for CLI related issue):

### Environment

Any, I guess

### What is the expected behaviour?

It should be explained

### Keywords

X-Hasura-Is-Owner

### What is the current behaviour?

It's unclear what it does/means/used for.

### How to reproduce the issue?

n/a

### Screenshots or Screencast

n/a

### Please provide any traces or logs that could help here.

n/a

### Any possible solutions?

n/a

### Can you identify the location in the source code where the problem exists?

It's a doc issue

**Comment by ecthiender** [comment]
@raarts where are you seeing `X-Hasura-Is-Owner` in the docs? Can you link and/or elaborate a bit?

**Comment by raarts** [comment]
It's in the authentication pages, for example the webhook.
See here: https://www.google.com/search?q=%22x-hasura-is-owner%22+site%3Ahasura.io

**Comment by rikinsk** [comment]
@raarts The `X-Hasura-Is-Owner` and `X-Hasura-User-Id` variables in the docs you pointed to are just examples of custom variables that you can pass via your auth system and not special Hasura variables. You can set any session variables of your choice that you can then use in permission rules.  We will clarify this in the documentation.

**Comment by seanparkross** [comment]
Closing this issue as a PR has been made for this which clarifies custom session variables. It will be deployed to live docs soon.
