### ISSUE TITLE
cli: 2-spaces for query formatting in metadata would be nice rather than tabs

### ISSUE THREAD

**Issue by shinnoki** [hasura/graphql-engine#8469]
### Is your proposal related to a problem?

GraphQL queries in metadata came to be validated and formatted from cli version >= 2.6.0.
These queries are formatted by tabs while the whole YAML files use 2-spaces indent, so the output files oddly combine spaces and tabs.

We can see this situation in test data updated in https://github.com/hasura/graphql-engine/commit/e46777b7ea7f014609f12209e5b4183a00229809

### Describe the solution you'd like

[vektah/gqlparser](https://github.com/vektah/gqlparser) supports format options as implemented [here](https://github.com/vektah/gqlparser/pull/208/files).
Passing options when calling `formatter.NewFormatter(buf)` would solve this problem.

### If the feature is approved, would you be willing to submit a PR?

I'd like to try contributing if it's ok.

**Comment by jflambert** [comment]
OMG yes please
