### ISSUE TITLE
MSSQL: query wrapped in double transaction.

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#8483]
### Version Information

Server Version: 2.6.1

### Environment

OSS

### What is the expected behaviour?

Select operations should be wrapped in a single operation, not  two.

### What is the current behaviour?

Performing basic select operations from hasura will result in the operation being wrapped in two transaction blocks, which can cause issues related to locking.

### How to reproduce the issue?

1. Create and track table on a mssql database.
2. Open SQL Server Profiler (Included with SQL Server Management Studio) and begin a trace.
3. Execute a simple select operations.
4. The traces show the operation is wrapped in two transaction blocks.

**Comment by sassela** [comment]
thanks for raising this Benoit! It's been brought to the team's attention and we'll triage it soon

**Comment by sassela** [comment]
So @BenoitRanque I can produce something that _looks_ like a repro (using Azure Data Studio on MacOS):

<img width="697" alt="Screenshot 2022-05-12 at 10 44 45" src="https://user-images.githubusercontent.com/3883855/168042549-3de48b47-d1c7-4523-8526-d0f2670276d6.png">

But AFAICT the duplicate statements are in fact `BatchStarting`/`BatchCompleted` events for the same transaction statement. I'm wondering if this in fact a duplicate transaction, or just the way the data's presented in the profiler itself?

**Comment by sassela** [comment]
Another thing that leads me to believe this is that @soupi mentioned not being able to reproduce nested transactions with server-side traces

**Comment by soupi** [comment]
indeed @sassela, I put a `trace` on the boundry (afaict) in [`rawQueryE`](https://hasura.github.io/graphql-engine/server/haddock/main/Database-MSSQL-Transaction.html#v:rawQueryE) and got the following result:

```hs
query: Query
    ( fromList
        [ TextPart "BEGIN TRANSACTION" ]
    )
query: Query
    ( fromList
        [ TextPart "SELECT "
        , TextPart "ISNULL"
        , TextPart "("
        , TextPart "("
        , TextPart "SELECT "
        , TextPart "[t_somedefaults1]"
        , TextPart "."
        , TextPart "[name]"
        , TextPart " AS "
        , TextPart "[name]"
        , TextPart ","
        , TextPart " "
        , TextPart "[t_somedefaults1]"
        , TextPart "."
        , TextPart "[id]"
        , TextPart " AS "
        , TextPart "[id]"
        , TextPart ","
        , TextPart " "
        , TextPart "[t_somedefaults1]"
        , TextPart "."
        , TextPart "[dt]"
        , TextPart " AS "
        , TextPart "[dt]"
        , TextPart " "
        , TextPart "FROM "
        , TextPart "[dbo]"
        , TextPart "."
        , TextPart "[somedefaults]"
        , TextPart " AS "
        , TextPart "[t_somedefaults1]"
        , TextPart " "
        , TextPart "FOR JSON PATH, INCLUDE_NULL_VALUES"
        , TextPart ")"
        , TextPart ", "
        , ValuePart
            ( TextValue "[]" )
        , TextPart ")"
        , TextPart " AS "
        , TextPart "[root]"
        ]
    )
query: Query
    ( fromList
        [ TextPart "SELECT XACT_STATE()" ]
    )
query: Query
    ( fromList
        [ TextPart "COMMIT TRANSACTION" ]
    )
```

**Comment by sassela** [comment]
Thanks Gil! I also checked with a transaction directly on the DB and got a similar result

<img width="270" alt="Screenshot 2022-05-12 at 11 27 06" src="https://user-images.githubusercontent.com/3883855/168050938-03bc6661-aa27-44e6-ba23-7312aa041141.png">

@BenoitRanque @dsandip I'm going to close this for now as this doesn't seem to be a graphql-engine bug, but please reopen/share more detail if there's anything else we should look into.
