### ISSUE TITLE
add support for CockroachDB

### ISSUE THREAD

**Issue by otan** [hasura/graphql-engine#8491]
### Is your proposal related to a problem?

This is a re-opened version of #678, in hope of having an open issue for more visibility.

CockroachDB currently cannot run on Hasura, due to small things CockroachDB cannot support or some driver upgrades required (see https://github.com/cockroachdb/cockroach/issues/72407 for more information on this).

### Describe the solution you'd like

We're hoping to get CockroachDB support with Hasura!

### Describe alternatives you've considered

N/A

### If the feature is approved, would you be willing to submit a PR?

Folks working on CockroachDB are happy to collaborate when we get the all clear!

**Comment by adamfeldman** [comment]
It's a positive sign to see some co-marketing work by Cockroach and Hasura! https://hasura.io/events/webinar/hasura-hosts-cockroach

**Comment by ElGrecode** [comment]
According to @coco98 in this morning's webinar with Cockroach Labs, this integration is in progress. They are working out some of the kinks with eventing and might have a multi step integration approach

**Comment by dameleney** [comment]
We are pleased to announce the beta release for CocroachDB datasource on the Hasura GraphQL Engine for Hasura CE, Cloud, and EE in v2.15.  🚀 🚀 🚀 Beta release for v2.15 is expected to take place Monday 10/31.

In this beta release Hasura supports Queries and Mutations with plans to add support for subscription before the GA release, which will coincide with the release of CockroachDB v22.2 (tentatively scheduled for early December).

CockroachDB is a distributed SQL database built on a transactional and strongly-consistent key-value store. It scales horizontally; survives disk, machine, rack, and even datacenter failures with minimal latency disruption and no manual intervention; supports strongly-consistent ACID transactions; and provides a familiar SQL API for structuring, manipulating, and querying data.

Together with Hasura, CockroachDB now supports: Instant GraphQL & REST APIs, Declarative Role Based Authorization, Advanced Security and Performance with rate limiting, allow lists, and caching.

**Comment by dameleney** [comment]
🎉💥 Excited to officially announce the beta release of CockroachDB on Hasura v2.15.0 currently available on cloud and oss versions of Hasura. Support for CockroachDB will be considered GA when the minimum required CockroachDB version, v22.2, which is currently in beta is released as GA and pushed to CockroachDB's managed solutions.

[Find out more in this blog post](https://hasura.io/blog/announcing-native-cockroachdb-integration/) or follow the instructions in the [CockroachDB docs](https://hasura.io/docs/latest/databases/postgres/cockroachdb/getting-started/docker/) to get started building with Hasura and CockroachDB today.

Coming soon!!! We are hoping to release support for subscriptions for CockroachDB in the coming weeks.

**Comment by dvasdekis** [comment]
Now that CockroachDB functions are released into [GA as well](https://hasura.io/docs/latest/databases/postgres/cockroachdb/hasura-cockroachdb-compatibility/), support for these could be added to Hasura? If Hasura does already support them, then [the docs](https://hasura.io/docs/latest/databases/postgres/cockroachdb/hasura-cockroachdb-compatibility/) need to be updated.

**Comment by SamirTalwar** [comment]
Currently, Hasura only supports table-based UDFs, and I believe CockroachDB only supports scalar UDFs, so unfortunately these features don't really line up.

If we add support to Hasura for scalar UDFs, we'll definitely be supporting them in CockroachDB too. Unfortunately, I cannot make promises about whether this'll happen.

I'm going to close this issue as, broadly speaking, CockroachDB is now well-supported by the Hasura GraphQL Engine. Please feel free to open new issues for specific feature requests!
