### ISSUE TITLE
Changing the query name in the UI for the console stopped working

### ISSUE THREAD

**Issue by haf** [hasura/graphql-engine#8505]
2.6.2 console

<img width="545" alt="image" src="https://user-images.githubusercontent.com/193115/169561642-144d0be3-bae2-4461-bc39-932dca72911e.png">

**Comment by rikinsk** [comment]
Hi, I Was not able to reproduce this. Could you confirm if you are still facing this. If yes, could you maybe try in another browser to check if its an issue specific to certain browsers.

**Comment by haf** [comment]
yes I can confirm
