### ISSUE TITLE
Fix: Fix docs for PG Dump API 

### ISSUE THREAD

**Issue by meetzaveri** [hasura/graphql-engine#8507]
### Version Information

Server Version: v2.6.2-cloud.1
CLI Version (for CLI related issue):

### Environment
Cloud

### What is the expected behaviour?
As per docs, we need to apply an extra header alongside those existing two headers for `POST` request to `v1alpha1/pg_dump` endpoint. That header would be `X-Hasura-Admin-Secret`.

### Keywords
pg_dump,migrations

### What is the current behaviour?
Currently, without adding `X-Hasura-Admin-Secret` into header , API gives error `Invalid response from authorization hook`.

### How to reproduce the issue?

1. Follow instructions as per docs. Perform `POST` request to `v1alpha1/pg_dump` endpoint (you can do with POSTMAN or any other API request tool)
2. Check response. Check if it contains `Invalid response from authorization hook`.
3.

### Screenshots or Screencast
Here's the video recording I have recorded

https://user-images.githubusercontent.com/21293048/169664873-54189645-e934-414e-bba5-5bb1cb91689d.mov

### Please provide any traces or logs that could help here.
Irrelevant to this bug report

### Any possible solutions?

We can update docs by suggesting an extra header (of x-hasura-admin-secret) alongside those two headers. That means three headers in total

### Can you identify the location in the source code where the problem exists?

Yes

### If the bug is confirmed, would you be willing to submit a PR?

Yes, I'd happy to submit a PR.

**Comment by sudeshna-22** [comment]
can you please describe which part of the docs needs correction? Provide link or something that'd help.

**Comment by sudeshna-22** [comment]
Working on this issue.

**Comment by meetzaveri** [comment]
Closing this issue as updates are now visible on v2 docs, thanks @robertjdominguez
