### ISSUE TITLE
Remote Relationships for MS SQL Databases

### ISSUE THREAD

**Issue by Smibser** [hasura/graphql-engine#8512]
### Is your proposal related to a problem?

I noticed that Relationships to a Remote Schema (Remote Relationships) is only possible if the connected Database is a PostgreSQL. For an MS SQL DB, I can't see the option to create a Remote Relationship. Am I doing something wrong or do just Remote Relationships not work für MS SQL for now.

### Describe the solution you'd like

I would love to create Remote Relationships for MS SQL Databases.

### Describe alternatives you've considered

I started to migrate our Database to PostgreSQL and that temporarily fixes the problem but we would like to continue with the MS SQL DB.

### If the feature is approved, would you be willing to submit a PR?

Probably it's a lot of work to add this feature so I won't be able to do this on my own. I want to know if this feature is planned in the future or if we have to ultimately migrate to PostgreSQL when we want to use Hasura.

**Comment by rishi-div** [comment]
@Smibser - this is available in Hasura CE 2.6.0 and later versions.

**Comment by Smibser** [comment]
Sorry for the late response. Yeah, actually I tested it before 2.6.0 was released. It's working now. Thank you and sorry for the trouble
