### ISSUE TITLE
[DOCUMENTATION] Incorrect streaming subscription example

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#8552]
### Version Information

Server Version: 2.7.0

### Environment

OSS

### What is the expected behaviour?

Documentation should be correct.

### What is the current behaviour?

Documentation example has a typo AND doesn't work.

### How to reproduce the issue?

1. https://hasura.io/docs/latest/graphql/core/databases/postgres/subscriptions/streaming/use-cases/
2. run the subscription as-is
3. it will complain that ""field \"created_at\" not found in type: 'messages_stream_cursor_input'"
4. Also it says `batches of 100 rows` but the example uses 2

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/11539524/171914766-b5cab434-cb96-49fc-9d34-571a22dbbb2b.png)

### Any possible solutions?

Change third line to:
` messages_stream(cursor: {initial_value: {created_at: "2022-01-01"}, ordering: ASC}, batch_size: 100) {`

**Comment by seanparkross** [comment]
Thanks @jflambert will check this out. 🙏
