### ISSUE TITLE
console: suggestions for relationships based on naming convention

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#8573]
### Is your proposal related to a problem?

Currently, relationship names are suggested based on foreign key constraints. The names are snake cased because that was the only naming convention Hasura had so far (pre 2.8.0).

In 2.8.0, we introduced a new naming convention called `graphql-default`: https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/naming-convention/

With this naming convention, we should show "camelCased" relationship name suggestions. 

![image](https://user-images.githubusercontent.com/8663570/172850775-e5c8a482-846c-4734-9647-a20eba9b034f.png)

### Describe the solution you'd like

The console should detect the global naming convention or the per-source naming convention and display relationship name suggestions accordingly.

**Comment by tirumaraiselvan** [comment]
There may be some server support required e.g. adding `global_naming_convention` to the config API. We can discuss server requirements here.

**Comment by lucarestagno** [comment]
@tirumaraiselvan I think that the UI currently shows the table and column names involved in the relationship.

Once the relationship is tracked, it is added to the GraphQL API with the right naming convention.

So, I don't think there's anything to be done in this specific view.

**Comment by lucarestagno** [comment]
@tirumaraiselvan you're right, the relationship is not created respecting the selected naming convention.

But the users can rename it, so they still have a workaround.

Considering we are working on the UI (currently under feature flag — disabled by default), we will fix it there, and not in the legacy code.

**Comment by vijayprasanna13** [comment]
Fixed in https://github.com/hasura/graphql-engine/commit/a5e4141eefd1caeefdaa649ecb911295940dde6e
