### ISSUE TITLE
Hasura cannot handle response "Content-Type header [] is not supported"

### ISSUE THREAD

**Issue by japrogramer** [hasura/graphql-engine#8598]
### Version Information

Server Version:
CLI Version (for CLI related issue):
latest

### Environment
docker local

### What is the expected behaviour?

I expect my action to run and return the hits from an
opensearch instance

### Keywords
header content-type

### What is the current behaviour?

406 error when running action

### How to reproduce the issue?

1. make a request via an action to an api that returns  
    something like this, opensearch does,

    < HTTP/1.1 200 OK
    < content-type: application/json; charset=UTF-8

2. run query
3. behold the error

### Screenshots or Screencast
```
{
  "errors": [
    {
      "extensions": {
        "internal": {
          "error": "unexpected response",
          "response": {
            "status": 406,
            "body": {
              "status": 406,
              "error": "Content-Type header [] is not supported"
            },
            "headers": [
              {
                "value": "application/json; charset=UTF-8",
                "name": "content-type"
              },
              {
                "value": "gzip",
                "name": "content-encoding"
              },
              {
                "value": "90",
                "name": "content-length"
              }
            ]
          },
          "request": {
            "body": {
              "request_query": "{\n  searchPractitioner(query: {query: \"health\"}) {\n    hits\n  }\n}\n",
              "session_variables": {
                "x-hasura-role": "admin"
              },
              "input": {
                "query": {
                  "query": "health"
                }
              },
              "action": {
                "name": "searchPractitioner"
              }
            },
            "transformed_request": {
              "query_string": "?format=json",
              "body": "{"query" :  {"boo": {"must" : {"match_all": {}}}}}",
              "url": "http://opensearch-node1:9200/practitioner_placeholder/_search?format=json",
              "headers": [
                [
                  "User-Agent",
                  "hasura-graphql-engine/v2.8.0"
                ]
              ],
              "method": "GET",
              "response_timeout": "5000000"
            },
            "url": "http://opensearch-node1:9200/practitioner_placeholder/_search",
            "headers": [
              {
                "value": "application/json",
                "name": "Content-Type"
              }
            ]
          }
        },
        "path": "$",
        "code": "parse-failed"
      },
      "message": "the key 'message' was not present"
    }
  ]
}
```
### Any possible solutions?
allow array values for said header.

### Can you identify the location in the source code where the problem exists?
not yet

### If the bug is confirmed, would you be willing to submit a PR?
if I can find the location of the bug and language the bug is written in is one I already know, yes

**Comment by tirumaraiselvan** [comment]
@japrogramer Can you please share the transform metadata in your action?

**Comment by tirumaraiselvan** [comment]
Were you also sending a Content-type header with the GET request in curl?

I think the Hasura console takes a shortcut and assumes that GET requests do not need a Content-type (which is true in almost all cases), this is possible to change using the API though.

I am closing the issue for now but happy to continue discussing this.
