### ISSUE TITLE
add tests for /api/1/table endpoint

### ISSUE THREAD

**Issue by ecthiender** [hasura/graphql-engine#86]
This endpoint is no longer required.

https://github.com/ecthiender/graphql-engine/blob/issue-13-server-tests/server/src-lib/Hasura/Server/App.hs#L440

**Comment by shahidhk** [comment]
@0x777 @ecthiender @coco98  I suggest we do not remove this as HGE is used in platform too.

Let's take a call and close this issue off?

**Comment by dsandip** [comment]
@coco98 @nizar-m is this part of the tests coverage plan?

**Comment by ecthiender** [comment]
I think we can close this issue, if we want to continue running `/api/1/table`.

**Comment by shahidhk** [comment]
@nizar-m Since this query is translated to whatever `v1/query` does, let's just add one test to ensure that it's working and close this issue.
