### ISSUE TITLE
Cmd/Ctrl+Enter in the SQL Runner UI should run the SQL statements

### ISSUE THREAD

**Issue by jaril** [hasura/graphql-engine#8600]
### Is your proposal related to a problem?

I often find myself using the SQL runner (Run SQL?) UI as a scratchboard. Problem is, it's a bit clunky. Usually, I have to edit the code, click Run, wait for the result, then focus back on the editor to modify the query if needed.

### Describe the solution you'd like

It _would_ be nice if, after editing, I could hit Cmd+Enter (Windows: Ctrl+Enter) and it would run my recent changes. 

### Describe alternatives you've considered

🤷‍♂️

### If the feature is approved, would you be willing to submit a PR?

Sure!

**Comment by sauzzon** [comment]
i started working on this issue
