### ISSUE TITLE
Columns with trim() unique constraints aren't trackable anymore in 2.8

### ISSUE THREAD

**Issue by Zerebokep** [hasura/graphql-engine#8601]
### Version Information

Server Version: Hasura 2.8
CLI Version (for CLI related issue): Hasura 2.8

### Environment

Official Docker image

### What is the expected behaviour?

Tracking a table

### What is the current behaviour?

Tables which contain a unique index with TRIM() results in an error when trying to track that table.

`"error": "Error in $['unique_constraints'][0].columns: parsing [] failed, expected Array, but encountered Null",`

### How to reproduce the issue?

1. Create a table with an unique index:

`CREATE UNIQUE INDEX test_key ON "users" (trim(first_name))`

2. track that table in hasura

**Comment by tirumaraiselvan** [comment]
Thanks, this has been fixed in https://github.com/hasura/graphql-engine/commit/6a15d3ea5fdefc4c4507bcead481ed68c15c2fae and will be out in 2.8.1 soon.
