### ISSUE TITLE
Header values sent to webhook are all of type string (null and number types are lost)

### ISSUE THREAD

**Issue by AndresPrez** [hasura/graphql-engine#8608]
When using POST webhook authentication, header values originally of type null or number, get converted to strings when put into the webhook's req.body.headers.

**Comment by rahulagarwal13** [comment]
Hey Andres, as per HTTP spec, all header values should be string. We have mentioned this as a note here in the user documentation as well - https://hasura.io/docs/latest/auth/authentication/webhook/#success. As a result, closing this issue.
