### ISSUE TITLE
When editing row I can not see the field that I am editing

### ISSUE THREAD

**Issue by AdamSchinzel** [hasura/graphql-engine#8609]
### Version Information

Server Version: 2.8.0

### Environment

OSS

### What is the expected behaviour?

When I want to edit row, I want to see the name of the field I am editing.

### Keywords

#editing

### What is the current behaviour?

Can not see the name of the field that I want to edit (or any field in general)

### How to reproduce the issue?

1. Go to any table
2. Click on the edit icon on any row

### Screenshots or Screencast

<img width="685" alt="Screen Shot 2022-06-21 at 11 03 04 AM" src="https://user-images.githubusercontent.com/66002635/174763205-2d320398-d939-4d4f-8ce6-270f9603177b.png">

### Any possible solutions?

Just show the name. And also the UI of top menu is a little broken, see the screen shot
<img width="575" alt="Screen Shot 2022-06-21 at 11 03 00 AM" src="https://user-images.githubusercontent.com/66002635/174763584-abc339a0-b748-437f-aaa8-84829e1c439c.png">

**Comment by rikinsk** [comment]
Fixed via https://github.com/hasura/graphql-engine/commit/6d2c8f1ec3c85d0508af687e65e8f0ae6c1cb215
