### ISSUE TITLE
ability to disable jwk-refresh-log via enabled log types

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#8611]
### Is your proposal related to a problem?

Currently, we cannot disable `jwk-refresh-log` through enabled log types: https://hasura.io/docs/latest/graphql/core/deployment/logging/#log-types

Many JWK providers have a Cache-Control policy which makes Hasura refresh them every second and pollute the logs.

### Describe the solution you'd like

Add `jwk-refresh-log` as a configurable log type

**Comment by CameronNemo** [comment]
Seeing the same with keycloak. https://github.com/keycloak/keycloak/issues/11320

**Comment by pranshi06** [comment]
Closed via fd6aa0a2662632c867fcf16c1fca4e1636cd5cf2 and 7b7845f697d1b0014b75533e03a0958e5c41530b
