### ISSUE TITLE
Hasura 2.8.x w/ Streaming Subscriptions doesn't support "Select" custom root fields

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#8618]
### Version Information

Server Version: 2.8.3

### Environment

OSS

### What is the expected behaviour?

Hasura w/ Streaming Subscriptions supports Select custom root fields

### What is the current behaviour?

Hasura 2.7.0 (with streaming subscriptions enabled) supports Select custom root field
Hasura 2.8.x (with streaming subscriptions enabled) doesn't support Select custom root field

### How to reproduce the issue?

1. use hasura 2.8.x with streaming subscriptions
2. Create/track a simple table
3. Modify the table, open Custom GraphQL Root Fields panel
4. provide an override for "Select"
5. hasura refuses to save the new root field and complains about "duplicate fields"

### Can you identify the location in the source code where the problem exists?
No

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by jflambert** [comment]
I will try to provide better replication steps, perhaps even with a DB + metadata.

Suffice to say I can't provide my own metadata here because it's enormous and confidential.

I'm hoping one of the hasura devs gets a bright idea reading this bug report.

**Comment by codingkarthik** [comment]
Hello,

Thanks for opening this issue. Can you tell if your metadata remained unchanged while you upgraded from v2.7.0 to v2.8.1? Also, did the error message include the entities that contain the duplicate fields? Do you mind sharing them here?

Best, 

Karthikeyan

**Comment by jflambert** [comment]
completely unchanged, it's a huge remote schema with hundreds of endpoints so I'm trying to narrow it down for you.

**Comment by jflambert** [comment]
one last thing @codingkarthik do I still need to enable SS through expérimental features or is it now built-in?

**Comment by jflambert** [comment]
@codingkarthik I found the issue

2.7.0 supported overriding "select" root field w/ streaming subscription

2.8.x doesn't

**Comment by codingkarthik** [comment]
@jflambert Thanks for identifying this issue and I can confirm this is indeed a bug. We'll open a fix for this soon!

**Comment by codingkarthik** [comment]
The issue should be fixed by providing a way to customize the streaming subscriptions root field.

**Comment by codingkarthik** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/584aa666bda386d7842d00d2ff16d1465128b9cf

**Comment by codingkarthik** [comment]
@jflambert You don't need to do anything different and it will just work :)
