### ISSUE TITLE
docs: refactor hasura internals section

### ISSUE THREAD

**Issue by rikinsk-zz** [hasura/graphql-engine#862]
Create one section with:
- [x] Hasura graphql internals (i.e. db table structures)
- [x] How schema generation works
- [ ] Hasura metadata (what parts are Postgres and what parts are Hasura specific)
- [ ] How console works 
- [ ] How CLI works

**Comment by robertjdominguez** [comment]
@rikinsk-zz and @rikinsk, if you'd like to re-open this, yell at us 👍
