### ISSUE TITLE
Shouldn't delete/update mutation throw an error when a condition is not met ?

### ISSUE THREAD

**Issue by MussieT** [hasura/graphql-engine#8626]
**Version information**
Server Version: v2.8.1
PostgreSQL Version: v13.7

**Environment**
Local linux Kubuntu: V20.04

**Problem**
When a particular condition(s) is not met on row update/delete, Hasura returns an empty array. This leaves us not knowing which state is not satisfied.

**Suggestions**
- Instead of returning an empty array, throwing an error (I just thought returning an empty array seems the row is removed in delete mutation)
- Specify which condition is not met (If possible).

**Comment by jflambert** [comment]
that sounds like an awful lot of work for something sql itself doesn't even do.
