### ISSUE TITLE
Streaming subscriptions do not work when the field used as cursor has a custom field name

### ISSUE THREAD

**Issue by harishnair96** [hasura/graphql-engine#8630]
### Version Information

Server Version: 2.8.1

### Environment

OSS

### What is the expected behaviour?

Streaming subscription should work properly even if the field used as cursor is exposed with a custom name in the API.

### Keywords

streaming subscription

### What is the current behaviour?

Streaming subscriptions do not work when using a field with a custom name in the cursor parameter.

### How to reproduce the issue?

1. Start an instance of Hasura with `HASURA_GRAPHQL_EXPERIMENTAL_FEATURES` containing the value `streaming_subscriptions`
2. Create a table like `CREATE TABLE EXAMPLE(ID SERIAL PRIMARY KEY, TIME TIMESTAMP WITH TIME ZONE DEFAULT NOW());` and track the table.
3.  Run the following subscription and confirm that it works:
```
subscription {
  example_stream(batch_size: 10, cursor: {initial_value: {time: "2022-06-27T11:51:52.619516+00:00"}}) {
    id
    time
  }
}
```
4. Go to Data -> Modify. In the Columns section, click edit on the 'time' field. Enter a new name in the 'GraphQL Field Name' section like 'entered_at'.
5. Now run the following subscription:
```
subscription {
  example_stream(batch_size: 10, cursor: {initial_value: {entered_at: "2022-06-27T11:51:52.619516+00:00"}}) {
    id
    entered_at
  }
}
```
This does not work. Even if new data is added to the table, it is never sent to the subscribed clients.

**Comment by jflambert** [comment]
quick question, can you try with 2.7.0?

something broke for me between the two releases.

**Comment by harishnair96** [comment]
Same issue as #8985
