### ISSUE TITLE
Many bugs with the new `graphql-default` naming convention

### ISSUE THREAD

**Issue by lorenzo** [hasura/graphql-engine#8640]
### Version Information

Server Version: 2.8.1

### Environment

OSS

### Keywords

naming convention, graphql-default

### What is the current behaviour?

I tried the the new `graphql-default` naming convention with an existing database and I found several inconsistencies, as listed below.

#### 1. Types ending with the suffix `_cast_exp`  are not transformed to `PascalCase`

For example I have the following types in the generated schema:

* `Boolean_cast_exp`
* `timestamtz_cast_exp`
* `Int_cast_exp`

#### 2. `OrderBy` fields contain `_aggregate` suffixes

For example, I Hasura generated this field for the `CustomerOrderBy` type:

* `emails_aggregate`, it should have generated `emailsAggregate`

#### 3. `ComparisonExp` for enums is cased incorrectly

For example, I have this enum table definition

```yaml
table:
  schema: public
  name: payment_status
is_enum: true
configuration:
  custom_root_fields: {}
  column_config: {}
  custom_column_names: {}
```

Hasura generated the type

```PaymentstatusenumComparisonExp```

it should be `PaymentStatusEnumComparisonExp ` instead

#### 4. `orderBy` is not properly cased, it should start with an uppercase letter

The automatic enum type `orderBy should be generated as `OrderBy`. Additionally, its values should be `UPPER_CASED`:

* `ASC`
* `DESC`
* `ASC_NULLS_FIRST`
* ...

#### 5. Types for function arguments are not cased correctly

If I have a function `my_function` hasura generates the type `Myfunctionargs` for the arguments. It should be `MyFunctionArgs`

#### 6. Automatic Upper case enum values are broken

If an enum table has rows containing `lower_cased` values, the schema is correctly generated with `UPPER_CASED` members.

BUT

When performing a query, those values are still retuned in `lower_cased` form. This breaks clients.

#### 7. Custom table names in the metadata are not respected

If I have a table with this setting

```
custom_name: CustomerAddress
```

Hasura will generate a field `Customeraddress`. The workaround is to write the custom name in `snake_case` form. For example `customer_address` will generated the desired `CustomerAddress` type.

### If the bug is confirmed, would you be willing to submit a PR?

Sure

**Comment by tirumaraiselvan** [comment]
Thanks for the detailed report @lorenzo ! 

This feature is marked experimental because we did expect few missing cases. Your feedback helps a lot.

**Comment by paritosh-08** [comment]
Thank you so much for raising the issue. All the issue mentioned above has been resolved and will be released in our next release.
- 3,5 and 7 via https://github.com/hasura/graphql-engine/commit/0c6ddc36663c3802bd2e03458d70c7a346499ad9
- 1,2 and 4 via https://github.com/hasura/graphql-engine/commit/680cf5b3c00658828d2dfe37e07e16a2d79c2589
- 6 via https://github.com/hasura/graphql-engine/commit/d66abcefabc98102a3600da62ee8f48ddda2827a

**Comment by lorenzo** [comment]
Thank you so much for all your work!

**Comment by raszi** [comment]
6. was only partially fixed because, with remote schema relationships, the enum values are not converted to the right casing.

We are using the `graphql-default` naming convention, the enum values are correctly uppercased for queries that are not related to remote schemas, but where we use remote schema relationships the values are left in their lower-cased form.
