### ISSUE TITLE
docs: add Cloud DB guides for new databases

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#8654]
We currently only cover Postgres in the [Cloud DB guides](https://hasura.io/docs/latest/graphql/cloud/getting-started/cloud-databases/index/). We should add guides on other DBs as well.

Wish by community: SQL server on Azure.

**Comment by aloks98** [comment]
I can take this up. Please assign this issue to me :)

**Comment by marionschleifer** [comment]
@aloks98 feel free to pick up this issues, so far, nobody has raised a PR on this. We don't assign issues, so whatever PR gets submitted first will be reviewed first 🙂

**Comment by praveenweb** [comment]
SQL Server on Azure is available here - https://hasura.io/docs/latest/databases/connect-db/cloud-databases/mssql/

**Comment by robertjdominguez** [comment]
Closing this as we added this at the end of 2022. There are more DB guides to come which are being planned and mapped out within Hasura 👍
