### ISSUE TITLE
Cannot remove datasource with dependencies

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#8663]
### Version Information

Server Version: 2.8.3

### Environment

OSS

### What is the current behaviour?

Hasura is unable to remove datasources if dependencies to it exist, despite being offered as an option.

### What is the expected behaviour?

The "Continue" button should work and cascade to remote relationships.

### How to reproduce the issue?

1. Track two databases (A and B)
2. Create a remote relationship from B to A
3. Try to remove database A
4. Hasura will fail, and offer to "Drop the dependent objects"
5. Clicking "Continue" fails again

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/11539524/177069004-d3279efb-df1a-405e-bcee-233501834848.png)

![image](https://user-images.githubusercontent.com/11539524/177069045-fe81b22a-8199-4d39-96a2-37f0883c6ec7.png)

**Comment by jflambert** [comment]
This is still a problem in 2.11.2

This time trying to remove a database which has permissions granted to inherited roles

![image](https://user-images.githubusercontent.com/11539524/196466221-00f7d413-0057-41a6-8b08-6e4fcc934fb4.png)

**Comment by jflambert** [comment]
Still a problem in 2.15.1

**Comment by vijayprasanna13** [comment]
@jflambert Thanks. I was able to reproduce this on my end as well. We'll look into this asap

**Comment by vijayprasanna13** [comment]
@jflambert this should be fixed now in https://github.com/hasura/graphql-engine/commit/3af0d49dd7cc8eaf2bc2337e32d4fcce449de699 and will be available in the next release.
