### ISSUE TITLE
Remote Schema - Adding new schema failing with conflict error timestamptz_comparison_exp

### ISSUE THREAD

**Issue by amal-chandran** [hasura/graphql-engine#8672]
### Version Information

Server Version:
CLI Version (for CLI related issue): 2.8.4

### Environment

Cloud - v2.8.1-cloud.1

### What is the current behaviour?

When I'm trying to add a remote schema of objkt graphql API (https://data.objkt.com/v2/graphql)
The connection is failing with the error message given below
On the cloud console

```
Found conflicting definitions for "timestamptz_comparison_exp". The definition at "query_root.attribute.where.attribute_counts.fa.asks.currency.token.creators.holder.bidder_english.auction.end_time" differs from the the definition at "query_root.account_providers.where.updated_at, query_root.account_providers.where.created_at, query_root.account_providers.where.account.updated_at, query_root.account_providers.where.account.storefronts.updated_at, query_root.account_providers.where.account.storefronts.created_at, query_root.account_providers.where.account.created_at".
```

On the local docker 

```
{
    "path": "$.args[0].args",
    "error": "Found conflicting definitions for \"timestamptz_comparison_exp\".  The definition at \"query_root.attribute.where.attribute_counts.fa.asks.currency.token.creators.holder.bidder_english.auction.end_time\" differs from the the definition at \"query_root.account_providers.where.updated_at, query_root.account_providers.where.created_at, query_root.account_providers.where.account.updated_at, query_root.account_providers.where.account.storefronts.updated_at, query_root.account_providers.where.account.storefronts.created_at, query_root.account_providers.where.account.created_at\".",
    "code": "unexpected"
}
```

The same issue is only happening in v2.8.0 to v2.8.1.
Its works fine in v2.7.0 and v2.8.2 above.

Since the Hasura cloud version is 2.8.1 I'm not able to 

### What is the expected behaviour?

The connection will happen without any error 

### How to reproduce the issue?

1. Create a Hasura cloud environment and check the version is  v2.8.1 or create a local instance with the same config
2. Create an accounts table with schema containing timestamp fields like created_at, updated_at
3. Try to create remote schema with https://data.objkt.com/v2/graphql 

Accounts table schema
```
id- uuid, primary key, unique, default: gen_random_uuid()
created_at- timestamp with time zone, default: now()
updated_at- timestamp with time zone, default: now()
display_name- text, nullable
```

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/29562232/177773521-52ad3b61-1343-41f5-b101-a89bf301d324.png)

### Any possible solutions?

Could you please update the Hasura version in the Hasura cloud to the latest v2.8.4

### If the bug is confirmed, would you be willing to submit a PR?

The issue is already sorted out in v2.8.4

### Keywords

Remote Schema
Timestamp

**Comment by marionschleifer** [comment]
@amal-chandran the current version of Cloud is `v2.10.1`, so I'm assuming this issue is resolved.
