### ISSUE TITLE
Unable to use cross DB relationships in permissions

### ISSUE THREAD

**Issue by manterfield** [hasura/graphql-engine#8679]
### Version Information

Server Version: 2.8.0

### Environment
OSS

### What is the current behaviour?

If I create two databases with tables and create a cross DB relationship on one of these tables, it is not available as an option when building custom permissions in the console UI

### What is the expected behaviour?

I should be able to use this relationship in custom permissions as I would any other relationship

### How to reproduce the issue?

1. Create an Hasura instance with 2 DBs and a table in each
2. Create a relationship across these tables
3. Observe your inability to use that relationship in a permission

### Keywords

permissions, relationships, cross database, multi database

---

I was unsure whether this is a bug or a feature request as it's not clear to me if this is expected behaviour or not. I've seen comments by the Hasura team saying things such as separate DBs just look like any other table, in addition to a release note posted on Discourse describing this feature being added to the console (though the matching release note in the repo didn't say that).

Those swayed me into thinking it's supposed to work already, but I'm not confident.

**Comment by manterfield** [comment]
We've just bumped into this again for another permission check. Is this supported or planned to be supported in the near future?

**Comment by Rudedog9d** [comment]
+1, Ran into this on our project

**Comment by sghoweri** [comment]
BUMP. Any updates on this? We just ran into this same issue ourselves!

**Comment by aaka3207** [comment]
+1 ran into this just now, really need this.

**Comment by Dein1** [comment]
Is there a workaround for this?

**Comment by manterfield** [comment]
@Dein1 

Our workaround was to switch to webhook based auth, Hasura passes the same JWT back to us it would normally use, then we validate, figure out what projects the user has access to and return those as a list in that can be used in permissions. In our API project IDs exist across all DBs so they can be used to establish perms.

It works reliably, but it's not as seamless as just having Hasura handle this. There's effectively two levels to permissions which I don't like, in addition to needing code changes if we ever need more info than the project ID.

Initial setup effort was quite low, but we already had a service that made sense as an owner of this auth webhook.

**Comment by aaka3207** [comment]
my workaround was to duplicate my table that checks for the permissions into the database, and then set up event triggers to keep the two tables in sync. now the second database can use the duplicated table to lookup relationship permissions.

It works, but I don't love that I have to maintain two tables.

**Comment by manterfield** [comment]
@aaka3207 That's an interesting idea. I take it the event triggers need to call some custom function that then performs the write over to the other DB? Or is there a built in way to support this synch?

**Comment by manasag** [comment]
Hi all, thanks for your request and feedback. We have started scoping the design for this feature. We will share more details soon.

**Comment by aaka3207** [comment]
> @aaka3207 That's an interesting idea. I take it the event triggers need to call some custom function that then performs the write over to the other DB? Or is there a built in way to support this synch?

@manterfield yeah our system uses lambda for actions/event triggers and is connected to our DB as well. so we duplicated table A into the other database as table B, created hasura event triggers on table A where, on insert/update/delete, do that same action (programmatically) on table B.

**Comment by Mihai-P** [comment]
We would love to be able to use this, I had an amazing solution to an issue we have :) but unfortunately, this is not available so I have to figure out some work arounds.

**Comment by TimUnderhay** [comment]
+1 for this request.  This limitation is quite painful

**Comment by manasag** [comment]
Hi everyone. This feature is now support since v2.33 onwards and documented [here](https://hasura.io/docs/latest/auth/authorization/permissions/row-level-permissions/#remote-relationships-in-permission).
