### ISSUE TITLE
Can't track tables with columns or constraints with dashes "-" in them

### ISSUE THREAD

**Issue by Keyruu** [hasura/graphql-engine#8687]
### Version

2.8.3

### What is the current behaviour?

There is an error when trying to add or delete stuff with a table that has a constraint with a dash in it:
```
Deleting relationship failed
{ "path": "$.args[0].args", "error": "cannot include \"UK_J3RWUVD56ONTGSUHOGM184WW2-2\" in the GraphQL schema because it is not a valid GraphQL identifier", "code": "validation-failed" }
```
If I rename the constraint to not have the dash in the name it works fine.
I have this error trying to track the keycloak_role table.

### What is the expected behaviour?

A successful track of the table.

### How to reproduce the issue?

1. Have a table with a constraint with a dash in the name, for example: "UK_J3RWUVD56ONTGSUHOGM184WW2-2"
2. Try to track the table in the Hasura Console

### Any possible solutions?

Hasura should be able to either convert or ignore names that have dashes in them. Or even include an alias function for those entries.

### Can you identify the location in the source code where the problem exists?

I think its this line right here: https://github.com/hasura/graphql-engine/blob/9d93baa96f7539230b8df63aca82a9192189da00/server/src-lib/Hasura/Backends/Postgres/SQL/Types.hs#L277
But I'm not sure. I never coded in Haskell before.

### If the bug is confirmed, would you be willing to submit a PR?

Unfortunately no, because I don't know Haskell that well...

### Keywords

keycloak, graphql identifier, dash in constraint, constraint, keycloak in hasura

**Comment by seanparkross** [comment]
`-` is not allowed in column names.

**Comment by seanparkross** [comment]
This is a PostgreSQL convention also, which is why it's not supported in Hasura at all. Hope this clears things up. Feel free to reply if you need to reopen.

**Comment by pscanlon1** [comment]
bump. I have an index from dbt which I cant change the name of 69a08b342139b3824c2cfe6c8162e52d, and our instance was crashed all day until i figured it out. Why can't we add an underscore or in @jflambert issue, replace invalid graphql characters with a valid one?

**Comment by jflambert** [comment]
really upsetting this was closed @seanparkross

**Comment by pscanlon1** [comment]
Very similar to this:

https://github.com/hasura/graphql-engine/issues/7850

**Comment by dzhus** [comment]
> @seanparkross It may be a postgres convention not to use `-` but it is absolutely an allowed character once double-quoted, otherwise postgres itself wouldn't allow creating this column/constraint name.
> 
> Please consider fixing this issue.
> 
> @Keyruu I'm in the same boat as you, trying to track Keycloak in Hasura. Until they support quoted constraint names, we'll have to rename this unique constraint in `keycloak_roles` to something without a `-`.

I think the source of this restriction is not really PostgreSQL– it's the GraphQL standard, see https://github.com/graphql/graphql-spec/issues/479. I guess GraphQL field names are meant to be "friendly" with mainstream languages without additional quoting., and `-` is not a valid character for identifiers in TS, for example (`{ kebab-case: "blah" }` is not allowed).
