### ISSUE TITLE
Some of the Hasura console page's style is broken.

### ISSUE THREAD

**Issue by PJijin** [hasura/graphql-engine#8690]
### Version Information

Hasura version: v2.8.4

### How to reproduce the issue?

1.  Go to data -> select any table -> click on edit (the label is not shown there. check the screenshot below.)
2.  Click on events -> click on any event -> click on the edit option at Trigger operations
3.  Click on events -> any event -> click on invocation logs -> click on retry 

### Screenshots or Screencast
 
![image](https://i.imgur.com/O3nQVaN.png "image")
![image](https://i.imgur.com/HIHi3Hg.png "image")
![image](https://i.imgur.com/ASbYipD.png "image")

**Comment by soorajshankar** [comment]
Hey Folks, 

Thanks for reporting the issue @PJijin!

Thanks for volunteering to contribute @sudeshna-22! I'm assigning this issue to you.
Here are some suggestions from our end, 
- We started using more TailwindCSS and less CSS/SCSS to simplify the UI development, would appreciate if you can follow the pattern.
- [Here](https://main--614d7904644d03004addd43b.chromatic.com/?path=/story/dev-tooling--page) is a storybook document that explains our latest tooling.

Please reach out to us if you have any doubts, Happy to help :)

**Comment by sudeshna-22** [comment]
A recent commit to the main repo appears to have resolved the problems raised in this issue. However, there are some section that could be improved. 

1. There is some change in the edit section of the data which does not match other view of the application. 
2. There is no space between the button and other elements. 

I believe I can improve this section. 

![image](https://user-images.githubusercontent.com/99816019/179955493-ac932d1b-1f9e-40d1-b0de-58aca4ea06aa.png)

**Comment by sudeshna-22** [comment]
Will be solving this in this issue: The styling of the data table view and edit row sections needs an improvement. #8704

**Comment by seanparkross** [comment]
Closing in favour of #8704
