### ISSUE TITLE
Metadata resource version referenced (N) did not match current version during deployments

### ISSUE THREAD

**Issue by collin** [hasura/graphql-engine#8696]
### Version Information

Server Version: from Dockerfile: `v2.6.2.cli-migrations-v3`

### Environment

Google Cloud Platform
Cloud Run

### What is the current behaviour?

We are intermittently seeing errors when starting up new containers in Cloud Run.

### What is the expected behaviour?

We would expect containers to successfully boot.

### How to reproduce the issue?

We're not entirely sure what might be going wrong. We see this intermittently.

### Screenshots or Screencast

N/A

### Please provide any traces or logs that could help here.

This is the error we see in logs:

Raw
```
"time="2022-07-12T16:58:52Z" level=fatal msg="error applying metadata \n{\n  \"path\": \"$\",\n  \"error\": \"metadata resource version referenced (770) did not match current version\",\n  \"code\": \"conflict\"\n}""
````

Formatted
```
error applying metadata 
"{
  "path": "$",
  "error": "metadata resource version referenced (770) did not match current version",
  "code": "conflict"
}"
```

### Any possible solutions?

As a wild guess we lowered the concurrency setting of our Cloud Run service to 1 JIC there was some concurrency issue with startup of `v2.6.2.cli-migrations-v3`. We still see the issue, though we may not have ruled out all kinds of concurrency, during deployments there would be 1 instance from the old revision while 1 instance from the new revision is coming online.

We could consider upgrading our version to > 2.6.

We could also consider using a Docker container that doesn't auto-migrate and come up with a different approach to running migrations.

### Can you identify the location in the source code where the problem exists?

No, haven't been able to understand what conditions would load to this value getting out of sync.

### Keywords

Metadata resource version referenced  did not match current version during deployments

Found #7324, #6805, and #7351, all of which have been closed and don't obviously yield any answers for us.

**Comment by collin** [comment]
We have observed that this correlates with multiple `graphql-engine` instances attempting to run a migration at the same time.

We are adjusting our deployment practices so we will not attempt to run concurrent migrations.

**Comment by paymog** [comment]
I'm seeing this happen when attempting to run `pg_track_table` against the hasura admin metadata api.

**Comment by collin** [comment]
For us it was a case of doing very close tracing of our postgres logs and the graphql-engine logs.

We were using the migrations-cli images and a serverless environment. With that configuration we were unable to guarantee only one container would attempt the migration.

So we ended up running the non-migration containers, and running 1-off jobs to migrate as part of our deployments.

**Comment by gunar** [comment]
Seeing the same problem here.

In case this is useful, a quick hack is to deploy the non `.cli-migrations` version, then deploy the `.cli-migrations` version again. This will prevent two `.cli-migration` versions from conflicting with each other.

The better solution is to do what @collin mentioned:

> So we ended up running the non-migration containers, and running 1-off jobs to migrate as part of our deployments.

Of course, it'd be great if Hasura itself could provide some sort of sophisticated locking mechanism instead of just failing to boot up.

**Comment by RodriguezLucha** [comment]
Why did this get closed? Is the expected fix to run 1 off jobs for migrations?
