### ISSUE TITLE
There are no Non trackable functions and hdb_catalog in Hasura Cloud.

### ISSUE THREAD

**Issue by kim-mini6** [hasura/graphql-engine#8697]
When i create Docker Hasura local with Amazon Aurora database, functions are included in Non trackable functions, but when created with Hasura Cloud, Non trackable functions are empty.

Also, there is no hdb_catalog in Hasura Cloud.

What should I do?

thank you.

**Comment by rikinsk** [comment]
> Also, there is no hdb_catalog in Hasura Cloud.

As mentioned [here](https://hasura.io/docs/latest/graphql/core/how-it-works/metadata-schema/#hdb_catalog-schema) the metadata in Hasura Cloud is stored in dedicated DBs managed by Hasura Cloud itself. 

> functions are included in Non trackable functions, but when created with Hasura Cloud, Non trackable functions are empty.

Are there any specific functions you are looking for that were missing?

If you could explain in a bit more detail what you are looking to achieve and we'll try to guide you towards it.
