### ISSUE TITLE
Synapse support

### ISSUE THREAD

**Issue by garyamorris** [hasura/graphql-engine#8722]
### Discussed in https://github.com/hasura/graphql-engine/discussions/8681

<div type='discussions-op-text'>

<sup>Originally posted by **garyamorris** July 11, 2022</sup>
Do you have any plans to support synapse? 

We're making a move to synapse and due to json support we're having to look at alternatives to Hasura and just wanted to see if there was any plans on extending the MS SQL Server support to include Synapse data warehouse. </div>

**Comment by ajohnson1200** [comment]
hi Gary! No immediate plans for Synapse support but we've got a lot in the works around support for various data warehouse / analytics DB's (Athena, Snowflake, BigQuery).  Would be great to hear about what your use cases are for Synapse + Hasura as we plan out the second half of the year and look to next year.

**Comment by seanparkross** [comment]
Closing in favour of the discussion
