### ISSUE TITLE
Event trigger on sql database with a Danish_Norvegian_CI_AI collation and with a special norwegian characters (æ, ø, å, Æ, Ø, Å)

### ISSUE THREAD

**Issue by Hsoratsa** [hasura/graphql-engine#8747]
### Version Information

Server Version:2.9.0
CLI Version (for CLI related issue):2.9.0

### Environment

 OSS

### What is the current behaviour?

We have a sql database connected to hasura with a Danish_Norvegian_CI_AI collation.
In this database there are some columns with norwegian characters(ø, ...), column name for ex. is Fødeland
When we create an event trigger on that table with columns with this characters, it fires but does not deliver anything. The error in hasura logs is:
{"detail":{"code":"unexpected","error":"payload decode failed while fetching MSSQL events","path":"$"},"level":"error","timestamp":"2022-08-05T07:07:15.391+0000","type":"event-trigger"}

### What is the expected behaviour?

It should deliver data without a restriction on collation of a databse.

### How to reproduce the issue?

1. Create a database in sql server with a Danish_Norvegian_CI_AI collation
2. Add table, add column with a norvegial special characters in its name(like Fødeland)
3. Add trigger on update to that column
4. Fire a trigger by updating this column value

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/78162650/183041933-b25ac467-e317-4f51-a7c7-7c9f930e0ff7.png)

![image](https://user-images.githubusercontent.com/78162650/183041866-1f5bbf91-663e-46d9-b1a7-84081eaad611.png)

![image](https://user-images.githubusercontent.com/78162650/183042028-f6aa5909-fa7f-458d-84ec-999203235939.png)

![image](https://user-images.githubusercontent.com/78162650/183042124-556ea769-c04a-4758-9400-427e5744951e.png)

![image](https://user-images.githubusercontent.com/78162650/183042186-85860c52-590d-463f-a019-43d58c094ec1.png)

### Any possible solutions?

The nearly exact bug was resolved for a columns in 2.5.0 version (before it we cannot do a mutations on a columns with some special characters(norwegian letters))

### Can you identify the location in the source code where the problem exists?

no

### If the bug is confirmed, would you be willing to submit a PR?

no

### Keywords

event, trigger, collation, mssql, payload

**Comment by caiogranero** [comment]
Hi, i have the same problem with portugues characters like 'ç, ã, è'

**Comment by ccalvarez** [comment]
Hi, I'm having the same problem with Spanish characters.  In our case they are: á, é, í...

Our collation:  Modern_Spanish_CI_AS

Any news on this issue?  Thanks.

**Comment by tirumaraiselvan** [comment]
Thanks for reporting this. We are looking into this.

**Comment by mateusgoncalonascimento** [comment]
Hi, 

I`m facing the same issue over here.

**Comment by Naveenaidu** [comment]
Thanks folks for reporting the issue and for your patience. This is closed via 99fb6ac22f861a860d9ab66616614c17a76b8b6f. This should be available in our next release `v2.18.0`
