### ISSUE TITLE
Using suggested relationships via console on foreign keys on tables across postgres schemas causes bug

### ISSUE THREAD

**Issue by david-studyblue** [hasura/graphql-engine#876]
If I track tables in the `PUBLIC` schema, and then track the suggested relationships, all via the console, then Hasura seems to work properly.  If I track tables in another schema, and then track the suggested relationships for those tables, Hasura gets into a weird state.  Specifically, the suggested relationship isn't removed from the UI component displaying the suggested relationships, though it seems like the relationship nevertheless is tracked.  Or something.  I'll try to illustrate it with SQL and with screenshots.

I'll paste in the SQL that I used to set up the test, and then I'll attach some screenshots that illustrate the problem.

```sql
-- -*- sql-product: postgres; -*-

-- Create related tables in the public schema

create table parent (
id serial primary key);

create table child (
id serial primary key,
creator_id int not null references parent (id));

-- Create related tables in the test schema

create schema test;

create table test.parent (
id serial primary key);

create table test.child (
id serial primary key,
creator_id int not null references test.parent (id));
```
![screenshot from 2018-10-26 16-25-12](https://user-images.githubusercontent.com/1790654/47596840-25ca1300-d93e-11e8-9195-e2742ea364b8.png)
![screenshot from 2018-10-26 16-25-21](https://user-images.githubusercontent.com/1790654/47596845-2cf12100-d93e-11e8-8bf9-adcc8aad8f30.png)
![screenshot from 2018-10-26 16-25-29](https://user-images.githubusercontent.com/1790654/47596847-3084a800-d93e-11e8-8862-ad2eb24265c1.png)

**Comment by david-studyblue** [comment]
Follow-up:  again, when tracking suggested relationships in the `test` schema, it leaves the suggestion offered as an untracked relation.  Except, if you try to add it again, it says it's already added.  This doesn't happen when the related tables are in the default `public` schema.  I hope I'm explaining this clearly enough.

**Comment by praveenweb** [comment]
@david-studyblue - Thanks for pointing this out. There was an issue in handling the schema name while creating relationships and it has been fixed now.
