### ISSUE TITLE
Console: New Relationships UI array relationships do not show up on dropdown inputs related tables on edit

### ISSUE THREAD

**Issue by efstathiosntonas** [hasura/graphql-engine#8774]
### Version Information

Server Version: 2.11.0-beta.1
CLI Version (for CLI related issue): 

### Environment
OSS

### What is the current behaviour?
Using the new relationships UI, try to edit one array relationship, the tables won't populate in the dropdown inputs. See screenshots for more info. 

If I revert back to the old ui, everything shows up.

**NOTE: these relationships shown on screenshots were created with the old ui, not the new.**

### What is the expected behaviour?
Display selected tables on dropdown boxes

### How to reproduce the issue?

1. Create array relationship. 
2. Try to edit it
3. No tables are being selected on dropdown inputs

### Screenshots or Screencast
![Screenshot at Aug 11 10-48-30](https://user-images.githubusercontent.com/717975/184087881-377ff30a-a9c6-47c3-b800-067ed4c1df70.png)
![Screenshot at Aug 11 10-47-11](https://user-images.githubusercontent.com/717975/184087887-4eb24a74-e92b-49c6-8198-339ba39aa427.png)
![Screenshot at Aug 11 10-46-24](https://user-images.githubusercontent.com/717975/184087889-bdf4922d-6619-463a-a027-4c34d8c3f578.png)

### Keywords
missing array relationships, dropdown empty, new relationship ui

**Comment by vijayprasanna13** [comment]
@efstathiosntonas I believe this should been fixed in the latest version of Hasura (`v2.28`). Let me know if this issue still occurs on your side, or I can mark this thread as closed.

https://github.com/hasura/graphql-engine/assets/11921040/72e49791-e5b9-4444-b9d5-0b50233a7904

**Comment by efstathiosntonas** [comment]
@vijayprasanna13 thanks for the heads up, I’ve tried it yesterday and just fyi, I’ve noticed a long delay until the permissions are shown, a loading skeleton is being shown for around 10-15 seconds.

**Comment by vijayprasanna13** [comment]
Thanks for confirming @efstathiosntonas! I'll mark as closed then. 

> I’ve noticed a long delay until the permissions are shown, a loading skeleton is being shown for around 10-15 seconds.

This _might_ be the network call. We fire some SQL to your databases fetch the column names from the dropdown list (to allow editing). The loading state is just a placeholder until we get that data. Feel free to open a separate issue and we'll look into it!
