### ISSUE TITLE
CLI: Hasura CLI health check

### ISSUE THREAD

**Issue by kevcube** [hasura/graphql-engine#8777]
### Is your proposal related to a problem?

There's no great way to run an in-container health check without modifying the containers that Hasura ships. I'd like to be able to run `hasura-cli health` or something inside a container to get the same information at `/healthz` so that I can add it to a docker-compose healthcheck.

### Describe the solution you'd like

`hasura-cli health` which exits with code `1` if the healthcheck doesn't return `200` AND `OK`, maybe the command can be configurable to fail how you like, because `/healthz` will still return `200` even if there are inconsistencies, and maybe for some people that is considered healthy. (For us, it is not! One more vote for #7907)

### Describe alternatives you've considered

We can package curl/wget in our container, then curl the health endpoint, then `jq` to extract status information, and `test` or `[` to determine if it's a passing result.

### If the feature is approved, would you be willing to submit a PR?

No

**Comment by manasag** [comment]
Hi @kevcube,  `curl` will be available in images from version 2.12.0-beta.1 onwards.

**Comment by silky** [comment]
@manasag lies, you just removed it in 2.14 😀 

can you please bring it back?

**Comment by ryparker** [comment]
As a workaround I installed curl in my custom Dockerfile.

```dockerfile
FROM --platform=linux/arm64 hasura/graphql-engine:v2.14.0

EXPOSE 8080

RUN apt-get update &&\
  apt-get install -y curl

HEALTHCHECK --start-period=120s CMD curl -f http://localhost:8080/healthz || exit 1
```

**Comment by manasag** [comment]
Hi folks, we realised that the support was inadvertently removed. We are working on adding the support back for `curl`

**Comment by manasag** [comment]
Hi, `curl` and a `HEALTHCHECK` directive has been added to Hasura v2.18.0-beta docker images published today.
