### ISSUE TITLE
"distinct_on" columns must match initial "order_by" columns

### ISSUE THREAD

**Issue by evanwang0** [hasura/graphql-engine#8778]
### Version Information

Server Version: v2.10.0
CLI Version (for CLI related issue): 

### Environment
Cloud + OSS

### What is the current behaviour?
Query errors when using "distinct_on" with "order_by" when conditions for error are met.

`"distinct_on" columns must match initial "order_by" columns`

### What is the expected behaviour?
Query completes successfully.

### How to reproduce the issue?
Query was made with the following form
```
merchants(where: { merchant_id: { _eq: $merchant_id } }) {
  activity_records(order_by: { updated_at: desc, activity_id: asc }, distinct_on: activity_id) {
    created_at
  }
}
```
### Screenshots or Screencast
N/A

### Please provide any traces or logs that could help here.
N/A

### Any possible solutions?
Rollback relevant code changes to v2.9.0. This issue seems to be a regression bug as I have verified v2.9.0 works with the exact same code/data store. Untested on v2.11.0.

### Can you identify the location in the source code where the problem exists?
Probably, given the time

### If the bug is confirmed, would you be willing to submit a PR?
Bold question - probably not unless v2.10.0 gets released to Hasura Cloud standard projects.

### Keywords
I searched the title of this issue.

**Comment by HTHoussam** [comment]
i had the same error you should add `updated_at` to the `distinct_on` this should fix the error
 `order_by: { updated_at: desc, activity_id: asc }, distinct_on: [activity_id,updated_at])`
this worked for me but

**Comment by HTHoussam** [comment]
if you change the code to what i have suggested, can you test if the query orders by both fields `updated_at` and `activity_id`,because on my code it doesn't order by both fields
my code: 
``` 
      distinct_on: [ReportSelectColumn.Address,ReportSelectColumn.CreatedAt,],
      order_by: [
        {
          Address: OrderBy.Desc,
        },
        {
          createdAt: OrderBy.Desc,
        },],``` 
        
i would appreciate your opinion on this

**Comment by HTHoussam** [comment]
after further testing, i figured that it orders based on both fields, just the order of the fields inside `Order_by` array crucial
this code:
``` 
distinct_on: [ReportSelectColumn.Address,ReportSelectColumn.CreatedAt,],
order_by: [
        {
          createdAt: OrderBy.Desc,
        },
        {
          Address: OrderBy.Asc,
        },
      ],
``` 
returned different results than the code mentioned here.
just sharing in case some one needs this 
> if you change the code to what i have suggested, can you test if the query orders by both fields `updated_at` and `activity_id`,because on my code it doesn't order by both fields my code:
> 
> ```
>       distinct_on: [ReportSelectColumn.Address,ReportSelectColumn.CreatedAt,],
>       order_by: [
>         {
>           Address: OrderBy.Desc,
>         },
>         {
>           createdAt: OrderBy.Desc,
>         },],
> ```
> 
> i would appreciate your opinion on this

**Comment by evanwang0** [comment]
Thanks! This solved my problem. I guess the question to the maintainers is then - which is the correct behavior? Regardless, it is somewhat of a breaking change.

**Comment by evanwang0** [comment]
Coming back to this, while this resolved the error, I believe the underlying behavior is not the same.

**Comment by rikinsk** [comment]
Hey folks. The issue here might be due to using an object for the multiple order_by statements as opposed to an array. As mentioned in the docs [here](https://hasura.io/docs/latest/queries/postgres/sorting/#sorting-by-multiple-fields) the sorting of keys in an object is not guaranteed and can cause unpredictable results. 
Also as mentioned [here](https://hasura.io/docs/latest/queries/postgres/distinct-queries/#the-distinct_on-argument) the distinct_on column has to be the first column of your order_by 

I believe updating the query to the following should result in the behaviour you were looking for:

```
merchants(where: { merchant_id: { _eq: $merchant_id } }) {
  activity_records(
    order_by: [{activity_id: asc }, { updated_at: desc}], 
    distinct_on: activity_id
  ) {
    created_at
  }
}
```

Do let us know if Is there anything else that you observe in the behaviour which seems to have changed from v2.9.0 to v2.10.0 or if you expect a different behaviour than one  described above? (Apologies if I may have missed something already mentioned.)

**Comment by HTHoussam** [comment]
thank you for the information you shared, i didn't know that the disctinct_on column has to be the first column of order_by, however after testing your code the behaviour it resulted is: ordering by `address` then ordering by `createdAt` while having `distinct_on:address`
meaning it shows for examples: three addresses who starts by letter `A` (ordered by date),then 2 addresses start by `B`(ordered again by date)
eventhough some addresses starting with `A` has a `createdAt` date < the ones starting by `B` 
here is the code below
``` 
order_by: [{ address: OrderBy.Desc }, { createdAt: OrderBy.Desc }],
distinct_on: [ReportSelectColumn.address],
```
the behaviour i'm looking for which i couldn't achieve yet is: having all addresses (not duplicated),ordered by column `createdAt`,then ordered by `address` (optional)

i hope i explained my problem as clear as possible

**Comment by evanwang0** [comment]
Ah, I read through your @HTHoussam posts quickly and did not see that you had put `order_by` into an array.  Yes, @rikinsk, this fixes my issue and produces the intended behavior. I will close this issue as there is no bug. However, it might be helpful to disallow multi-key objects as an argument to `order_by` as I cannot think of a case where this behavior would be useful. Cheers!

@HTHoussam For your question, I think you're looking for a solution like this:
https://stackoverflow.com/questions/9795660/postgresql-distinct-on-with-different-order-by. Looks like it is more of a underlying postgres/sql restriction than in hasura.
