### ISSUE TITLE
update digitalocean one-click app manifests on deploy

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#878]
DO one-click manifests are located at `https://storage.googleapis.com/graphql-engine-cdn.hasura.io/install-manifests/do-one-click/{docker-compose.yaml,Caddyfile}`

Manifests in `docker-compose-https` should be copied here on deploy step.

**Comment by Skchoudhary** [comment]
Hi @shahidhk 
```docker-compose-https``` is already added in [install-manifests](https://github.com/hasura/graphql-engine/blob/master/install-manifests/) folder.

**Comment by shahidhk** [comment]
@Skchoudhary This is something different. It's about copying manifests to our cloud storage bucket.
