### ISSUE TITLE
Server/Tests: Integrate CockroachDB in test harness and CI

### ISSUE THREAD

**Issue by plcplc** [hasura/graphql-engine#8789]
This issue involves implementing a CockroachDB test harness in the [Haskell integration test suite](https://github.com/hasura/graphql-engine/tree/master/server/tests-hspec/Test), running the tests, and seeing what falls out.
* [x] adding a `v22.1` CockroachDB docker container to the `server/docker-compose.yml` file
* [x] introducing a `CockroachDB` testing fixture in `Tests/Harness/Backend.hs`

**Comment by i-am-tom** [comment]
NB: if someone picks this up while #8790 is being done, we can change the `Fixture.run` function to ignore the CockroachDB `BackendType` entirely. This way, we can add the boilerplate in the fixture lists before the other work is done, and then we can remove the guard in `run` as soon as we're ready to try running the tests against the implementation.

**Comment by soupi** [comment]
I'm not very familiar with docker but I will give this a try

**Comment by soupi** [comment]
Are we able to connect cockroach to graphql-engine at the moment?

**Comment by soupi** [comment]
Depends on https://github.com/hasura/graphql-engine/issues/8799 I believe?

**Comment by soupi** [comment]
This item was split to https://github.com/hasura/graphql-engine/issues/8839
