### ISSUE TITLE
server/cockroachdb: Define a new Postgres variant boilerplate

### ISSUE THREAD

**Issue by plcplc** [hasura/graphql-engine#8790]
This issue involves introducing a new `PGKind cockroachDB` and `AnyBackend` constructor. 

As a first pass, consider grepping the codebase for `PGKind citus` for the parts of the `graphql-engine` codebase that need to be adapted to support CockroachDB queries.

_To verify_
This work may well be done in parallel with [test work](https://github.com/hasura/graphql-engine/issues/8789), so perhaps making the corresponding PGKind changes and checking the code compiles?

**Comment by sassela** [comment]
closing as done
