### ISSUE TITLE
Console: Integrate CockroachDB and disable Raw SQL

### ISSUE THREAD

**Issue by plcplc** [hasura/graphql-engine#8794]
As some of the SQL functions will not be available for CockroachDB, we need to disable the possibility for the users to run raw SQL statements.

**Comment by soupi** [comment]
@lucarestagno Nice work! I was able to build and connect to cockroachdb locally. I tried to create a table using the console  "Add a new table" interface, which didn't work because we don't seem to support `run_sql` for cockroach.
Is the plan to add support for `run_sql`, or disable this section?
