### ISSUE TITLE
Server: Deal with lack of support for custom `SET LOCAL` options

### ISSUE THREAD

**Issue by plcplc** [hasura/graphql-engine#8797]
HGE uses the transaction-local options feature of Postgres, accessed via the [`SET LOCAL`](https://www.postgresql.org/docs/14/sql-set.html) to set custom variables `hasura.user` and `hasura.tracing_context`.

The CockroachDB implementation of [`SET LOCAL`](https://www.cockroachlabs.com/docs/v22.1/set-vars.html#set-local) do not support custom variables.

In order to close this gap, either CockroachDB needs to support custom variables or HGE needs to be able work around their absence.

**Comment by plcplc** [comment]
Likely a no-op, as CockroachDB has verified customized options work in v22

**Comment by sassela** [comment]
Confirmed this works https://github.com/cockroachdb/cockroach/issues/86438#issuecomment-1222541100, closing
