### ISSUE TITLE
Server/CockroachDB: Verify Metadata API for CockroachDB

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#8799]
This issue involves:
- at a minimum verifying manually that adding a cockroachDB via the `cockroach_add_source` operation works (with the same inputs as [the `pg_add_source` operation](https://hasura.io/docs/latest/api-reference/metadata-api/source/#metadata-pg-add-source))
- verify that `cockroach_track_tables` works 
- optionally, adding a hspec test for `replace_metadata` with a cockroachDB
- optionally, adding a hspec test for `cockroach_add_source`

**Comment by danieljharvey** [comment]
This _may_ work already due to the boilerplate changes, needs testing though.

**Comment by plcplc** [comment]
To relate this issue with our initial scope as defined in #8788, we could test:

* adding/dropping a source
* un-/tracking a table
* un-/tracking a relationship
* setting permissions on a table.

... as these are the commands we're going to rely on for that scope.

For some technical context, the implementation of the metadata API commands is backend-generic and simply a matter of enabling/disabling, c.f.:

https://github.com/hasura/graphql-engine-mono/blob/5d45c8ac85aa3721697f32cd7910a7e648d130f6/server/src-lib/Hasura/Backends/Postgres/Instances/API.hs

As such it might not be of much interest to test these thoroughly for each backend.

**Comment by plcplc** [comment]
> I'm currently getting the error:

Either `fetchTableMetadata` needs to be made `pgKind`-aware such that it won't pass the list of known tables as a parameter as the current `cockroach_table_metadata.sql` doesn't use them, or `cockroach_table_metadata.sql` needs to be amended to use them - preferably by re-introducing the optimization disabled by a lack of `jsonb_to_recordset` function. Alternatively we can just use it in a dead WITH-bound definition or something.

https://github.com/hasura/graphql-engine-mono/blob/5d45c8ac85aa3721697f32cd7910a7e648d130f6/server/src-lib/Hasura/Backends/Postgres/DDL/Source.hs#L325-L341

**Comment by sassela** [comment]
this is blocked by https://github.com/hasura/graphql-engine-mono/pull/5593

**Comment by plcplc** [comment]
This is also blocked by #8840

**Comment by danieljharvey** [comment]
Have tested `cockroach_add_source` ,`replace_metadata`, `cockroach_track_tables` and `cockroach_untrack_tables`, all are working.
