### ISSUE TITLE
2.10.1: error applying metadata when event triggers exist

### ISSUE THREAD

**Issue by maaft** [hasura/graphql-engine#8806]
### Version Information

Server Version: 2.10.1
CLI Version (for CLI related issue): 2.10.1

### Environment

oss

### What is the current behaviour?

I use event triggers in my metadata. After upgrade from 2.10.0 to 2.10.1 I get following error:

FATA[0000] error applying metadata 
{
  "code": "not-exists",
  "error": "event trigger \"delete_user_data\" does not exist",
  "path": "$.args"
}

**Comment by manasag** [comment]
Hi @maaft , thank you for bringing this issue to our attention. We are currently investigating this and would update soon with our findings.

**Comment by robertjdominguez** [comment]
Closing this as a duplicate of #8819 👍
