### ISSUE TITLE
Events aren't being triggered when using Logical Replication

### ISSUE THREAD

**Issue by gunar** [hasura/graphql-engine#8814]
### Version Information

Server Version: 2.8.4
CLI Version (for CLI related issue):

### Environment

Hosting on Google Cloud

### What is the current behaviour?

Inserting a row in the database A, makes the row show up in database B, but the Hasura Event isn't triggered.

### What is the expected behaviour?

Hasura should've triggered an INSERT event.

### How to reproduce the issue?

1. Set up postgres databases A and B
2. Set up Logical Replication between them
3. Set up Hasura Events on a table on B
4. Insert row into A

The row will appear on B but no event will be triggered.

**Comment by ajohnson1200** [comment]
@rahulagarwal13 ☝️ great issue to dig into.  @marionschleifer it'd great to have to have documentation that talks about how we actually implement triggers and / or in the meantime to document that at least from what gunar wrote above, that they don't work today with Postgres database replication.

**Comment by gunar** [comment]
Thank you. I'm very happy to see movement on this issue. Let me know how I can help.

**Comment by gunar** [comment]
This is the quick solution:

```sql
ALTER TABLE mytable ENABLE ALWAYS TRIGGER "notify_hasura_prices_UPDATE";
ALTER TABLE mytable ENABLE ALWAYS TRIGGER "notify_hasura_prices_DELETE";
ALTER TABLE mytable ENABLE ALWAYS TRIGGER "notify_hasura_prices_INSERT";
```

@ajohnson1200 @rahulagarwal13  Can we make it so that Hasura runs the above query by default whenever a new Event is set up?

**Comment by gunar** [comment]
Can't run the SQL above inside a migration because apparently by the time migrations are run Hasura hasn't yet created the triggers. This needs to be resolved at the graphql-engine level.

```
{"level":"error","msg":"skipping applying migrations on database default, encountered: \n{\n  \"internal\": {\n    \"statement\": \"ALTER TABLE prices ENABLE ALWAYS TRIGGER \\\"notify_hasura_mytable_INSERT\\\";\\n\",\n    \"prepared\": false,\n    \"error\": {\n      \"exec_status\": \"FatalError\",\n      \"hint\": null,\n      \"message\": \"trigger \\\"notify_hasura_prices_INSERT\\\" for table \\\"mytable\\\" does not exist\",\n      \"status_code\": \"42704\",\n      \"description\": null\n    },\n    \"arguments\": []\n  },\n  \"path\": \"$\",\n  \"error\": \"query execution failed\",\n  \"code\": \"postgres-error\"\n}","time":"2022-10-20T15:43:12Z"}
```

**Comment by gunar** [comment]
My temporary workaround:

1. Copy and paste Hasura's Trigger function (with `CREATE OR REPLACE FUNCTION`)
2. Create the trigger manually
3. `ENABLE ALWAYS TRIGGER`

Something like this:

```sql
-- up.sql
-- XXX: This trigger should actually be created automatically by Hasura as it applies the metadata but we're having to copy and pase it here because of this issue: https://github.com/hasura/graphql-engine/issues/8814#issuecomment-1285781869
CREATE OR REPLACE function hdb_catalog."notify_hasura_price_INSERT"() RETURNS trigger
   LANGUAGE plpgsql
   AS $$
   DECLARE
     _old record;
     _new record;
     _data json;
   BEGIN
     IF TG_OP = 'UPDATE' THEN
       _old := row((SELECT  "e"  FROM  (SELECT  OLD."column_a" , OLD."column_b" , OLD."column_c" , OLD."column_d" , OLD."column_e" , OLD."column_f"        ) AS "e"      ) );
       _new := row((SELECT  "e"  FROM  (SELECT  NEW."column_a" , NEW."column_b" , NEW."column_c" , NEW."column_d" , NEW."column_e" , NEW."column_f"        ) AS "e"      ) );
     ELSE
     /* initialize _old and _new with dummy values for INSERT and UPDATE events*/
       _old := row((select 1));
       _new := row((select 1));
     END IF;
     _data := json_build_object(
       'old', NULL,
       'new', row_to_json((SELECT  "e"  FROM  (SELECT  NEW."column_a" , NEW."column_b" , NEW."column_c" , NEW."column_d" , NEW."column_e" , NEW."column_f"        ) AS "e"      ) )
     );
     BEGIN
     /* NOTE: formerly we used TG_TABLE_NAME in place of tableName here. However in the case of
     partitioned tables this will give the name of the partitioned table and since we use the table name to
     get the event trigger configuration from the schema, this fails because the event trigger is only created
     on the original table.  */
       IF (TG_OP <> 'UPDATE') OR (_old <> _new) THEN
         PERFORM hdb_catalog.insert_event_log(CAST('public' AS text), CAST('mytable' AS text), CAST('price' AS text), TG_OP, _data);
       END IF;
       EXCEPTION WHEN undefined_function THEN
         IF (TG_OP <> 'UPDATE') OR (_old *<> _new) THEN
           PERFORM hdb_catalog.insert_event_log(CAST('public' AS text), CAST('mytable' AS text), CAST('price' AS text), TG_OP, _data);
         END IF;
     END;

     RETURN NULL;
   END;
 $$;

CREATE OR REPLACE TRIGGER "notify_hasura_price_INSERT" AFTER INSERT ON mytable FOR EACH ROW EXECUTE PROCEDURE hdb_catalog."notify_hasura_price_INSERT"();
ALTER TABLE mytable ENABLE ALWAYS TRIGGER "notify_hasura_price_INSERT";
```

**Comment by gunar** [comment]
The solution above is brittle and doesn't always work. My assumption is that Hasura might delete and recreate the TRIGGER in some circumstances, which would cause the `ALWAYS TRIGGER` option to not be set.

I've run out of options in user-land. I really need the solution to come from Hasura.

**Comment by codingkarthik** [comment]
@gunar Thanks for reporting this issue. 

You're right in saying that the solution needs to come from Hasura. So, to solve this I'm thinking of adding an `always_enable_trigger` option in Hasura's event trigger configuration and when it is enabled, it will enable the SQL trigger for logical replication as well. Does this seem like a reasonable solution to you?

**Comment by codingkarthik** [comment]
@gunar Thanks for reporting this issue. 

You're right in saying that the solution needs to come from Hasura. So, to solve this I'm thinking of adding an `always_enable_trigger` option in Hasura's event trigger configuration and when it is enabled, it will enable the SQL trigger for logical replication as well. Does this seem like a reasonable solution to you?

**Comment by gunar** [comment]
@codingkarthik Yes, that would work for me. It's an elegant solution too. Thank you for looking into this!

**Comment by codingkarthik** [comment]
There's a small issue with the proposed solution, the default behaviours in postgres and SQL server are different. 
In postgres, by default, triggers are not fired for logically replicated tables and in SQL server, triggers are fired for logically replicated tables. 

One approach to this would be to keep the default database feature i.e. `always_enable_trigger` default value for postgres will be `false` and for SQL server will be `true`. 

cc: @ecthiender @tirumaraiselvan @rahulagarwal13

**Comment by gunar** [comment]
Here's my dumb suggestion:

- `always_trigger` omitted: default database behavior
- `always_trigger == true`: always trigger enabled regardless of database
- `always_trigger == false`: always trigger disabled regardless of database

**Comment by gunar** [comment]
Hi there, as I'm planning my next weeks of work, I'm wondering when can I expect this to land on a docker `cli-migrations-v3` image? Thank you :pray:

**Comment by purugupta99** [comment]
Hi @gunar, the implementation is ready and under review. We should be able to provide you with a docker image by next week.

**Comment by purugupta99** [comment]
@gunar You can use this docker build: `docker pull hasurabuild/graphql-engine:mono-branch-dev-dbc07b0-main.ubuntu`.
We now support event triggers on logical replication.

How to use?
- While creating event trigger using the metadata API(`pg_create_event_trigger/mssql_create_event_trigger`), you can send a new field `trigger_on_replication`: `true` in the payload.
- This will setup event triggers to fire in case any logical replication happens on the corresponding table.

Let us know if you have any queries! Closing this issue now.

**Comment by gunar** [comment]
Awesome stuff, guys! Thank you so much. I can see it's already included in this release https://github.com/hasura/graphql-engine/releases/tag/v2.16.0-beta.1 :+1:
