### ISSUE TITLE
Server: Tracking items failed - the function does not return a "COMPOSITE" type • the function does not return a table

### ISSUE THREAD

**Issue by patrice-blp** [hasura/graphql-engine#8818]
### Version Information

Server Version:
v2.6.1

I have the following SQL to create a custom function.

![image](https://user-images.githubusercontent.com/4908933/185580659-a66f1d8b-eb67-4306-8581-718ee0005019.png)

When I check Track this and run the query, I get the following error.

`Inconsistent object: in function "faq_most_helpful": the function "faq_most_helpful" cannot be tracked for the following reasons: • the function does not return a "COMPOSITE" type • the function does not return a table`

But when I run it unchecking Track this, the function is created correctly

I have read the documentation about computed fields, [Postgres: Computed fields](https://hasura.io/docs/latest/schema/postgres/computed-fields/#pg-adding-computed-field) but I don't see any untracked function in selector options.

![image](https://user-images.githubusercontent.com/4908933/185584775-db35ad5b-16db-4331-b3bd-24a9148b2121.png)

- How can I track the function returning a table instead of Composite type.
- In the case of using the computed fields, how can I add them from the web interface if they do not appear in the selector?

**Comment by harishnair96** [comment]
The [documentation](https://hasura.io/docs/latest/schema/postgres/computed-fields/#supported-sql-functions) lists the conditions necessary to add a function as computed field.
> * Function behaviour: ONLY STABLE or IMMUTABLE
> * Argument modes: ONLY IN
> * Table Argument: One input argument with a table row type
> * Return type: Either SETOF <table-name> or BASE type

The function shared breaks 2 of these conditions-
1. It doesn't have the mandatory argument with the table row type
2. The return type is not SETOF \<table-name> or BASE type

This is why it isn't possible to track it and why it doesn't show up in the dropdown.
