### ISSUE TITLE
Console: Explorer height is really small in lower res screens

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#8826]
### Version Information

Server Version: 2.10

### Environment

All

### What is the current behaviour?

Graphiql onnly fills half the screen in lower res screens. e.g. 1366x768

### What is the expected behaviour?

GraphiQL should have a min-height comfortable to use

### How to reproduce the issue?

1. Open explorer in lower resolution screen / reduce your browser window size and observe graphiql window 

### Screenshots or Screencast

![Screenshot from 2022-08-22 14-01-00](https://user-images.githubusercontent.com/54616969/185876401-060badcd-ece6-42c8-8f80-78063b239e5f.png)

### Keywords

graphiql, explorer, size, height

**Comment by pkreipke** [comment]
Have this problem all the time. And it persists. Is there a workaround? Delete cookies? Localstorage?

**Comment by haaah** [comment]
[Original Discussion](https://github.com/hasura/graphql-engine/discussions/8811)
My original discussion was transferred to here. My situation happened when it's in higher resolution. 

`Environment`
Hardware: Macbook Pro 15
OS: BigSur
Resolution: 2880 x 1880

**Comment by rikinsk** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/c0b7d14adc442ce100847e7583be24287d742584. This will be fixed in v2.12.

@haaah Am tracking your request at #8880 instead

**Comment by WGTW** [comment]
The #c0b7d14 fix pushed in v2.12.0-beta.1 does not actually resolve the issue. See [this](https://i.imgur.com/aCtCWBQ.png) explanation.

**Comment by deathemperor** [comment]
the issue still exists in v2.12.0

**Comment by rikinsk** [comment]
Graphiql will be resizeable in v2.13 onwards
