### ISSUE TITLE
Using existing types in actions

### ISSUE THREAD

**Issue by adas98012** [hasura/graphql-engine#8881]
### Discussed in https://github.com/hasura/graphql-engine/discussions/8686

<div type='discussions-op-text'>

<sup>Originally posted by **tombrouwer** July 12, 2022</sup>
Hi all, and thanks for the hard work.

I did setup a Hasura instance with Docker. I created some database tabels. One of them is called `list`. I want to create a action similar to insert_list, zo I can create a validation layer between the database and the action. When I want to create a action, it tells me some types not existing. Is it possible to use existing types which already exists form de database resources. Right now it throws an error that it is not existing. 

Action like:

```
type Mutation {
 insert_list(
    """the rows to be inserted"""
    objects: [list_insert_input!]!

    """upsert condition"""
    on_conflict: list_on_conflict
  ): list_mutation_response
}
```

Error:
```
\"list_insert_input\" is not defined in custom types or it is not a scalar/enum/input_object
```</div>

**Comment by soorajshankar** [comment]
Hey @adas98012, 

Thanks for creating the issue! 
At the moment if you want to use a type on actions, you need to define this as custom types, and you cannot use generated types (from Database schema) while creating an action. 

There is already an open issue here #5001 on re-using generated types on actions.
(closing this to keep a single open thread)
