### ISSUE TITLE
docs: update screenshots

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#8883]
### Problem description

Screenshots have mostly been updated for Cloud related docs (identified by the ☁️ icon on docs) and for the Enterprise docs (identified by the 🏢 icon on docs). 

A lot of the screenshots of the feature docs are outdated.

### Describe the solution you'd like

Update the updated screenshots.

### Instructions

Please read carefully through the [Wiki on writing documentation](https://hasura.io/docs/wiki/), especially the [images section](https://hasura.io/docs/wiki/style/images/).

**Comment by Ln11211** [comment]
@marionschleifer I'm interested but can you tell me where do I get the screenshots from? and also which document/s you want me to update?

**Comment by marionschleifer** [comment]
@marionschleifer You get the screenshots by actually going through all the tutorials and then check if the UI has been changed. If so, you can create a new screenshot and add it to the docs. All pages except the Cloud and Enterprise docs need to be checked and updated (as explained in the description above). Hope that helps 🙂

**Comment by Sujithkumardola** [comment]
@marionschleifer I've read the documents and noticed that there are more than 50 screenshots that need to be updated; I'd like to be assigned to this Issue.

**Comment by marionschleifer** [comment]
@Sujithkumardola feel free to take this up, nobody has raised a PR on this so far 🙂

**Comment by Ln11211** [comment]
> @Ln11211 You get the screenshots by actually going through all the tutorials and then check if the UI has been changed. If so, you can create a new screenshot and add it to the docs. All pages except the Cloud and Enterprise docs need to be checked and updated (as explained in the description above). Hope that helps 🙂

Seems like a lot of reading to do :)  I am interested and I'll do the task.  Since @Sujithkumardola is also interested, how about we divide the work? is that ok with you @marionschleifer ? what say you @Sujithkumardola ?

**Comment by Stefmore02** [comment]
Hey folks, thank you for your interest! Feel free to divide amongst yourselves, seems like a good idea.

**Comment by Sujithkumardola** [comment]
@Ln11211 That sounds good.

**Comment by Ln11211** [comment]
Hello @Stefmore02,
I have read the wiki for adding the images in which it is specified that a 1200px viewport for images and also a naming convention for the images and I followed them. 

I raised a PR now, so that you can review the changes I did for a file `docker-simple.mdx` and let me know if I am doing them correctly.

I also wanted to know about the recommended editor for editing the `.mdx` extensions, I use intelliJ and it has got no plugin or support for .mdx, so I don't get the preview for the changes I make, any help please ? :)

**Comment by Ln11211** [comment]
Once you pick your docs, create a comment and paste your list and strike them off from the above, that way we can stay organized.

**Comment by Ln11211** [comment]
> @Sujithkumardola Looks like all the docs except the cloud and enterprise need a review and update, I'll list them out here and strike out the one's that are already done(so that we don't repeat), feel free to add to the list and pick some from the list...
> 
> ****Feel free to strike off if the ss are already up to date**
> 
> * [x]  getting-started/docker-simple
> * [ ]  databases/connect-db/index
> * [ ]  databases/connect-db/read-replicas

Btw @marionschleifer and @Sujithkumardola , I apologize if you keep getting pinged as I update this list, I just want to have everything at one place, hope you understand :)

**Comment by Sujithkumardola** [comment]
* [x]  databases/connect-db/index
 * [ ]  databases/connect-db/read-replicas > available only on cloud
 * [x]  databases/postgres/citus-hyperscale-postgres/getting-started/cloud
 * [x]  databases/postgres/citus-hyperscale-postgres/getting-started/docker
 * [x]  databases/ms-sql-server/getting-started/cloud 
 * [x]  databases/ms-sql-server/getting-started/docker
 * [x]  databases/bigquery/getting-started/cloud
 * [x]  databases/bigquery/getting-started/docker
 
Completed Updating the Databases Section.
I'll make a PR shortly

**Comment by Sujithkumardola** [comment]
> Hello @Stefmore02, I have read the wiki for adding the images in which it is specified that a 1200px viewport for images and also a naming convention for the images and I followed them.
> 
> I raised a PR now, so that you can review the changes I did for a file `docker-simple.mdx` and let me know if I am doing them correctly.
> 
> I also wanted to know about the recommended editor for editing the `.mdx` extensions, I use intelliJ and it has got no plugin or support for .mdx, so I don't get the preview for the changes I make, any help please ? :)

hey @Ln11211 

Have a look at [this](https://plugins.jetbrains.com/plugin/14944-mdx) Extension.

**Comment by seanparkross** [comment]
@Ln11211 Just checked out the PR and it looks good thanks!

One comment... please crop out your browser UI scroll bars. 

Thanks
Sean
