### ISSUE TITLE
docs: correct capitalization for hasura features

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#8884]
### Is your proposal related to a problem?

The capitalization in docs is quite random at the moment. Sometimes, Hasura features are sometimes in capital letters, and sometimes not. 

### Describe the solution you'd like

Capitalize all Hasura features, e.g. "Actions", "Event Triggers" etc.

### Instructions

Please read carefully through the [Wiki on writing documentation](https://hasura.io/docs/wiki/), especially the [style guide](https://hasura.io/docs/wiki/style/index/).

**Comment by zesterquinn** [comment]
Hello, can I work on this one?

**Comment by aniketh-varma** [comment]
Hi @marionschleifer, I want to contribute to this issue, can you please help me with the file where these changes must be made?

**Comment by marionschleifer** [comment]
@zesterquinn feel free to open a PR. The first PR that is submitted will be reviewed first.

@aniketh-varma all files in docs need to be searched and checked for feature names.

**Comment by aniketh-varma** [comment]
Hi @marionschleifer, can you please help list all the Hasura features, like Actions, Event Triggers, etc, so that I can start working on this issue

**Comment by Stefmore02** [comment]
@aniketh-varma if it appears in our marketing material as capitalized, or if it's not an industry-standard term and appears on our side navigation, then it's a Hasura feature.

**Comment by 3t8** [comment]
I fixed the capitalization

**Comment by Stefmore02** [comment]
@3t8 thank you for your PR, it will be reviewed within 2 weeks 🤓

**Comment by marionschleifer** [comment]
This is completed.
