### ISSUE TITLE
docs: capitalization of headings

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#8885]
### Is your proposal related to a problem?

The capitalization of the main headings are very random. 

### Describe the solution you'd like

Update the headings according to [this guide](https://hasura.io/docs/wiki/style/headings/).

**Comment by najeebkp** [comment]
Hi @marionschleifer ,

I would like to work on this. Can you please guide me what should i do ?

Thanks

**Comment by marionschleifer** [comment]
@najeebkp it's all described in the guide linked above.

**Comment by aniketh-varma** [comment]
Hi @marionschleifer, I would like to take up this issue, please help me with the file where the changes must be made. Thanks! :)

**Comment by devstardude** [comment]
Hello @marionschleifer, I would like to work on this issue, Can you please provide guidelines about how to start with this?

**Comment by marionschleifer** [comment]
These changes need to be made in all files of our docs. The guidelines are in the description of this issue.

**Comment by NiranjanMeghwal** [comment]
Hello! I have started working on this one, could you please assign this to me.

**Comment by catcecilia** [comment]
Lets divide this up since it is quite a bit of work. I'll be submitting what I have done for right now. My goal is to update graphql-engine/docs/docs/hasura-cli to graphql-engine/docs/docs/scheduled-triggers throughout the week
