### ISSUE TITLE
docs: improve docker compose spelling

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#8886]
### Is your proposal related to a problem?

Docker compose has changed its spelling from `docker-compose` to `docker compose` in all commands. This is currently still wrong in many placed in our docs.

### Describe the solution you'd like

Update to the new spelling in docs.

**Comment by amit-ksh** [comment]
I want to work on this issue. Can you assign it to me, please?

**Comment by Stefmore02** [comment]
@amit-ksh Thank you for your interest! Nobody has picked this up so far, feel free to raise a PR.
