### ISSUE TITLE
Server: GraphQL API error with CockroachDB

### ISSUE THREAD

**Issue by lucarestagno** [hasura/graphql-engine#8890]
Steps to reproduce:

* Connect a CockroachDB
* Select the CrDB in the navigation tree
* Click on a CDB table in the Nav Tree

You get an error response:
```json
{
  "errors": [
    {
      "extensions": {
        "code": "unexpected",
        "internal": {
          "arguments": [],
          "error": {
            "description": "source SQL:\nSELECT  json_build_object('aggregate', json_build_object('count', COUNT(*) ) ) AS \"root\" FROM  (SELECT   FROM  (SELECT  *  FROM \"public\".\"cdb_posts\"  WHERE ('true')     ) AS \"_root.base\"      ) AS \"_root\"      \n                                                                                                         ^",
            "exec_status": "FatalError",
            "hint": "try \\h SELECT",
            "message": "at or near \"from\": syntax error",
            "status_code": "42601"
          },
          "prepared": true,
          "statement": "SELECT  json_build_object('aggregate', json_build_object('count', COUNT(*) ) ) AS \"root\" FROM  (SELECT   FROM  (SELECT  *  FROM \"public\".\"cdb_posts\"  WHERE ('true')     ) AS \"_root.base\"      ) AS \"_root\"      "
        },
        "path": "$"
      },
      "message": "database query error"
    }
  ]
}
```

Request URL: `/v1/graphql`
Request Body:
```json
{
  "query": "query TableRows {\n      cdb_posts (limit: 10,offset: 0) {\n          title\nid\n    }\n    cdb_posts_aggregate {\n      aggregate {\n        count\n      }\n    }\n  }",
  "variables": null,
  "operationName": "TableRows"
}
```

There's an error in the SQL statement executed on the server
```sql
SELECT  json_build_object('aggregate', json_build_object('count', COUNT(*) ) ) AS "root" FROM  (SELECT   FROM  (SELECT  *  FROM "public"."cdb_posts"  WHERE ('true')     ) AS "_root.base"      ) AS "_root"      
```

-> `SELECT   FROM`

**Comment by codedmart** [comment]
More information:

If you create a table in cockroachdb and don't specify a primary key cockroachdb generates a primary key for you.

**Comment by lucarestagno** [comment]
> More information:
> 
> If you create a table in cockroachdb and don't specify a primary key cockroachdb generates a primary key for you.

The issue seems related to the fact that CockroacHDB doesn't support this syntax `SELECT FROM`, while Postgres does.

We opened an issue to the CockroachDB repository to get a more consistent behaviour https://github.com/cockroachdb/cockroach/issues/87428

**Comment by sassela** [comment]
This is blocked by https://github.com/hasura/graphql-engine-mono/pull/5787, which we're currently implementing a workaround for

**Comment by sassela** [comment]
Luca verified this works as expected yesterday, closing
