### ISSUE TITLE
error highlighting in GraphiQL has stopped working

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#8900]
### Version Information

Server Version: v2.11.0

### Environment

Cloud and OSS

### What is the current behaviour?

GraphiQL normally highlights errors in GraphQL queries based on the on the introspection info. This used to work uptill `v2.10` but has stopped working in `v2.11` and above 

### What is the expected behaviour?

The error syntax highlighting should work

### How to reproduce the issue?

1. Open Api explorer
2. Type in a query not conformant to the generated API

### Screenshots or Screencast

in v2.10:
![Screenshot from 2022-09-01 18-13-20](https://user-images.githubusercontent.com/54616969/187917630-1eee3711-a869-45ad-ac33-163d56a015a9.png)

in v2.11:
![Screenshot from 2022-09-01 18-10-33](https://user-images.githubusercontent.com/54616969/187917668-c3af028a-f566-4d76-af62-e7d36ffcb366.png)

### Keywords

graphiql, explorer, error, syntax, highlighting

**Comment by manasag** [comment]
The fix is being patched in 2.11 release.
