### ISSUE TITLE
server: metadata API very slow when tracking CockroachDB tables

### ISSUE THREAD

**Issue by lucarestagno** [hasura/graphql-engine#8902]
Steps:

- Connect a CockroachDB that runs locally in a docker image (like the graphql-engine) using the Console
- Click on the CockroachDB schema in the Nav Tree
- Click on "Track" to track a table

Current: the metadata API request takes ~30 seconds to complete
Expected: it should be very fast, like for Postgres databases (a few milliseconds)

Note: the `reload_metadata` request is affected by the same issue.

**Details**

<details>
<summary>Request</summary>
URL: `http://localhost:8080/v1/metadata`

Request payload: 
```json
{
  "type": "bulk",
  "source": "cdb",
  "resource_version": 192,
  "args": [
    {
      "type": "cockroach_track_table",
      "args": {
        "table": {
          "name": "cdb_users",
          "schema": "public"
        },
        "source": "cdb"
      }
    }
  ]
}
```
</details>

**Comment by soupi** [comment]
I think I traced this issue to:

- `src-lib/Hasura/RQL/DDL/Schema/Cache/Dependencies.hs:(51,1)-(56,43)`: the `resolveDependencies` function.

**Comment by soupi** [comment]
With Auke's help, we traced the issue to querying cockroachdb, in the [cockroachFetchTableMetadata](https://github.com/hasura/graphql-engine-mono/blob/main/server/src-lib/Hasura/Backends/Postgres/DDL/Source.hs#L376). So we need to take a look at https://github.com/hasura/graphql-engine-mono/blob/main/server/src-rsr/cockroach_table_metadata.sql

**Comment by sassela** [comment]
fixed by https://github.com/hasura/graphql-engine-mono/pull/5910
