### ISSUE TITLE
BIGQUERY: computed fields arg object is required.

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#8904]
### Version Information

Server Version: 2.6.0

### Environment

EE

### What is the current behaviour?

When using [table computed fields](https://hasura.io/docs/latest/schema/bigquery/computed-fields/) in bigquery, the generated schema will mark the `args` argument as required, even if there are no required arguments.

### What is the expected behaviour?

In postgres, [table computed fields](https://hasura.io/docs/latest/schema/postgres/computed-fields/#2-table-computed-fields) can be queried without arguments if the function does not have required arguments.

We expect this behavior to be consistent across data sources.

**Comment by dsandip** [comment]
[Ref conversation](https://hasurahelp.zendesk.com/agent/tickets/5660)
