### ISSUE TITLE
Console event not scoped on multiple database

### ISSUE THREAD

**Issue by albttx** [hasura/graphql-engine#8926]
Hasura version: `v2.7.0`

I have 2 databases with some console events

Both databases have an `inventories` table.

In this database, only `pcminventory_generate_ppi` should be present, `event_notify_questionnaire_finalized` and `generate_ppi` belongs to the table `inventories` from the other database.

![image](https://user-images.githubusercontent.com/8089712/188485081-f7b286bc-2408-4491-9abf-2d7cb0e602e0.png)

**Comment by albttx** [comment]
up ? @sassela :pray:

**Comment by sassela** [comment]
hey @albttx ! Thanks for the bug report. I've not been working on this change, but it looks like my colleague resolved it back in Sept with [this commit](https://github.com/hasura/graphql-engine/commit/95e2fe270b404bd88656403df5f6aae2d8c0a659) which was released in `graphql-engine v2.14.0`.

Would you kindly try from that version onwards and reopen the issue if you still see the same problem?

**Comment by Varun-Choudhary** [comment]
Hey @albttx, this bug is fixed and released in `graphql-engine v2.13.0`. Update your `hasura-engine` version.
Thank you!
