### ISSUE TITLE
Make admin interface usable without internet.

### ISSUE THREAD

**Issue by lucasdellabella** [hasura/graphql-engine#8933]
### Is your proposal related to a problem?

I'm frustrated because the locally running admin interface on localhost:8080 needs to make web requests to run. I was trying to develop with no internet while on a flight and I couldn't.

### Describe the solution you'd like

Bundle all the js and css that you use for the local admin client with the local admin client so I can work without internet.

### If the feature is approved, would you be willing to submit a PR?

No, just wanted to report.

**Comment by tirumaraiselvan** [comment]
Console can run offline: https://hasura.io/docs/latest/deployment/graphql-engine-flags/config-examples/#console-assets-on-server

But I think there is a scope for much better experience here so a user can figure this out themselves when they have no internet.

**Comment by rikinsk** [comment]
Closing in favour of https://github.com/hasura/graphql-engine/issues/2816. Please feel free to reopen this if you have different suggestions
