### ISSUE TITLE
Hasura deploy will not create event triggers on db

### ISSUE THREAD

**Issue by sayjeyhi** [hasura/graphql-engine#8934]
### Version Information

Server Version: 2.8.4
CLI Version (for CLI related issue): v2.9.0

### Environment
GCE - OSS

### What is the current behavior?
After changing metadata when I run `hasura deploy` the changes did not apply on DB and it only displayed the event triggers there. So changing data is not triggering these events. (I created another one on server and worked)

### What is the expected behavior?
When I deploy it should create event triggers and call them.

### How to reproduce the issue?

1. Create events on local
2. Deploy them
3. Try to trigger the events

### If the bug is confirmed, would you be willing to submit a PR?
No

### Keywords
events

**Comment by adas98012** [comment]
We attempted to reproduce the issue in test environment, but could not. There may be some issues specific to your environment preventing a smooth creation of event triggers. Please send an email to support@hasura.io with details about the issue, we'll be able to follow up from there, through a non-public channel.

**Comment by sayjeyhi** [comment]
Hmm, I don't know, I've created them on live servers manually, and it worked, closing for now. Will reopen this if it happens again.
