### ISSUE TITLE
(console): `NullsOrder failed` when attempting to sort table

### ISSUE THREAD

**Issue by ryparker** [hasura/graphql-engine#8955]
### Version Information

Server Version: v2.11.1

### Environment

OSS

### What is the current behaviour?

Sorting a table by a field in the Console UI throws:

```sh
Browse query failed!
parsing Hasura.Backends.Postgres.SQL.DML.NullsOrder failed, 
expected one of the tags ["ulls_first","ulls_last"], but found tag "last"
```

### What is the expected behaviour?

To sort the table.

### How to reproduce the issue?

1. Click on a header in any populated table in an attempt to sort the table.

### Screenshots or Screencast

<img width="547" alt="CleanShot 2022-09-10 at 22 46 46@2x" src="https://user-images.githubusercontent.com/17558268/189514323-15a8855b-951e-4e26-9cf1-47847f5d4d22.png">

### Related issues

This was reported once before in https://github.com/hasura/graphql-engine/issues/8780

**Comment by manasag** [comment]
Hi @ryparker , thanks for reporting the issue. Yes, this is a known regression as you mentioned. We should be able to patch and release a new 2.11 version in next 24 hours.

**Comment by shahidhk** [comment]
The fix is released with https://github.com/hasura/graphql-engine/releases/tag/v2.11.2
