### ISSUE TITLE
[2.11.1] in operator 

### ISSUE THREAD

**Issue by vitaliytv** [hasura/graphql-engine#8961]
### Version Information

Server Version: 2.11.1 only, 2.11.0 work as expected

### Environment 

OSS

### What is the current behaviour?

query with non latin symbol in operator return empty result
for example:
```
query issue_title {
  issue_title(where: {group_id: {_in: ["Україна"]}}) {
    id
    name
  }
}
```

return empty array

### What is the expected behaviour?

with 2.11.0
query with non latin symbol in operator return empty result
for example:
```
query issue_title {
  issue_title(where: {group_id: {_in: ["Україна"]}}) {
    id
    name
  }
}
```

return correct result

**Comment by adas98012** [comment]
Steps to reproduce:
1. Create a postgres table:

```
CREATE TABLE IF NOT EXISTS public.test_non_latin
(
    id integer NOT NULL DEFAULT nextval('test_non_latin_id_seq'::regclass),
    name text COLLATE pg_catalog."default" NOT NULL,
    group_id text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT test_non_latin_pkey PRIMARY KEY (id)
)
```
2. INSERT some non-latin values (in group_id field):

```
INSERT INTO public.test_non_latin(
	name, group_id)
	VALUES ('Test Name', 'Україна');
```
3. Start Graphql server locally (with different versions of the graphql-server, using docker) and connect to the above database.

4. Run queries and compare the results (screenshots added) 

<img width="1136" alt="Screen Shot 2022-09-12 at 11 45 06 AM" src="https://user-images.githubusercontent.com/101733366/190001869-bb8e6292-bdbb-4971-b419-1599e85d5f12.png">

![Screen Shot 2022-09-12 at 11 54 11 AM](https://user-images.githubusercontent.com/101733366/190001969-f9a29df3-1b16-4bde-aa1e-29f8cd83cb0f.png)

5. Compare the generated query between the two:

**2.11.1:**

```
SELECT
  coalesce(json_agg("root"), '[]') AS "root"
FROM
  (
    SELECT
      row_to_json(
        (
          SELECT
            "_e"
          FROM
            (
              SELECT
                "_root.base"."group_id" AS "group_id",
                "_root.base"."id" AS "id",
                "_root.base"."name" AS "name"
            ) AS "_e"
        )
      ) AS "root"
    FROM
      (
        SELECT
          *
        FROM
          "public"."test_non_latin"
        WHERE
          (
            ("public"."test_non_latin"."group_id") = ANY(('{""}') :: text [])
          )
      ) AS "_root.base"
  ) AS "_root"
```

**2.10.1:**


```
SELECT
  coalesce(json_agg("root"), '[]') AS "root"
FROM
  (
    SELECT
      row_to_json(
        (
          SELECT
            "_e"
          FROM
            (
              SELECT
                "_root.base"."group_id" AS "group_id",
                "_root.base"."id" AS "id",
                "_root.base"."name" AS "name"
            ) AS "_e"
        )
      ) AS "root"
    FROM
      (
        SELECT
          *
        FROM
          "public"."test_non_latin"
        WHERE
          (
            ("public"."test_non_latin"."group_id") = ANY(
              (
                E '{"\\"\\1059\\1082\\1088\\1072\\1111\\1085\\1072\\""}'
              ) :: text []
            )
          )
      ) AS "_root.base"
  ) AS "_root"
```

**Comment by adas98012** [comment]
**2.11.0:**

![Screen Shot 2022-09-13 at 1 33 31 PM](https://user-images.githubusercontent.com/101733366/190004170-67359a21-98fb-4c79-a9d3-441ddc3d6b53.png)

**Comment by soupi** [comment]
Thanks @vitaliytv for the report and @adas98012 for the additional reproduction steps! We have identified the issue and are working on a fix.

**Comment by soupi** [comment]
We've merged [the fix](https://github.com/hasura/graphql-engine/commit/71597778c9260d1949e96a97847e7d7dd4073dea) and it should be available in the next version. In the meantime you can try it out via the Docker image: `hasurabuild/graphql-engine:mono-branch-dev-9063f7f-main.ubuntu`

**Comment by vitaliytv** [comment]
> We've merged [the fix](https://github.com/hasura/graphql-engine/commit/71597778c9260d1949e96a97847e7d7dd4073dea) and it should be available in the next version. In the meantime you can try it out via the Docker image: `hasurabuild/graphql-engine:mono-branch-dev-9063f7f-main.ubuntu`.

2.12.0 without this patch ?

**Comment by soupi** [comment]
v2.12.0 does not contain this patch, but it will be part of `v2.13.0-beta.1` which is scheduled to be released today/tomorrow.
