### ISSUE TITLE
Inconsistent metadata (request timeout) with self signed cert on remote schema

### ISSUE THREAD

**Issue by zachequi** [hasura/graphql-engine#8976]
### Version Information

Server Version: 2.11.2 (tried v2.12.0-beta as well, same result)
CLI Version (for CLI related issue): N/A

### Environment

OSS

### What is the current behaviour?

* Have a remote schema configured in metadata using https with a self signed certificate
* Have the domain for the remote schema in the TLS allowlist in the console
* Have consistent metadata
* Reboot hasura

### What is the expected behaviour?

* Hasura reboots and still has consistent metadata

### Actual Behavior

* Hasura reboots with inconsistent metadata complaining the request to the remote schema timed out.

I've tried changing our backend url to use our public remote schema URL (which has a valid signed cert instead of the internal url which is self-signed) and the issue goes away, so the issue is isolated to when our remote schema uses an https url with a self-signed certificate.

**Comment by paritosh-08** [comment]
Hey @zachequi thanks a lot for reporting this bug. We have fixed it via https://github.com/hasura/graphql-engine/commit/a88e6cfa9dbe047cb9aadedc52fbfa8fdc400e46.

Can you please try out the docker image `hasurabuild/graphql-engine:mono-pr-6045-129.ubuntu` and let us know if this issue is fixed for sure?

**Comment by paritosh-08** [comment]
Thanks @zachequi, we will patch our next release with this bugfix. I am closing this issue for now. Thanks again for reporting this bug and for trying out the patched image :100:.

**Comment by paritosh-08** [comment]
Fixed via https://github.com/hasura/graphql-engine/commit/a88e6cfa9dbe047cb9aadedc52fbfa8fdc400e46.
