### ISSUE TITLE
Streaming subscriptions take forever to load when passing custom GraphQL field name in cursor

### ISSUE THREAD

**Issue by meetzaveri** [hasura/graphql-engine#8985]
### Version Information

Server Version: `v2.11.2-cloud.1`
CLI Version (for CLI related issue):

### Environment

Cloud

### What is the current behaviour?

Let's say I've some table with custom graphql field name(`created_at` -> `createdAt`). If I am using that custom graphql field name in `initial_value` in cursor, then streaming subscription takes forever to load and it keeps loading.

### What is the expected behaviour?

It should work as expected as it works in original way (by passing original field name and not custom graphql field name)

### How to reproduce the issue?

1. Create table, and add some fields in it (lets say one of them is `created_at`)
2. Modify one of the column by adding custom GraphQL field name to it (in this case, I changed it from `created_at`  to `createdAt`)
3. Run streaming subscriptions in API explorer ( streaming subscription would have suffixed as `_stream` )
4. Wait for some time to experience the loading issue ( as it keeps loading forever)

**Note**: It doesn't show any error but it only keeps loading

### Screenshots or Screencast

Here, I've attached loom recording for visual aid. Loom recording - https://www.loom.com/share/3b7240cfcff04620ab5e45f589488ddc

### Please provide any traces or logs that could help here.

N/A

### Any possible solutions?

N/A

### Can you identify the location in the source code where the problem exists?

Not familiar with the codebase.

### Keywords
streaming subscriptions custom graphql field name

**Comment by dsandip** [comment]
@rahulagarwal13 FYI

**Comment by tirumaraiselvan** [comment]
@furkanilgenci This will be out in v2.13.0-beta.1 which will be out tomo.

**Comment by tirumaraiselvan** [comment]
Fixed via https://github.com/hasura/graphql-engine/commit/3b167b7df132ea0c82baa076d967f2c4742d12e8
