### ISSUE TITLE
Edit row label left hiden

### ISSUE THREAD

**Issue by chanthavong** [hasura/graphql-engine#8994]
### Version Information

Server Version:  v2.8.1
CLI Version (for CLI related issue):

MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)
Display: Built-in Retina Display - 13,3-inch (2560 × 1600)

### How to reproduce the issue?

label left hiden when edit row

### Screenshots or Screencast

<img width="683" alt="image" src="https://user-images.githubusercontent.com/18229355/191660982-9ff02ecd-96bd-49f0-a84a-afa5586402fc.png">

**Comment by rikinsk** [comment]
Fixed via https://github.com/hasura/graphql-engine/commit/6d2c8f1ec3c85d0508af687e65e8f0ae6c1cb215
