### ISSUE TITLE
docs: update clouds screenshots throughout docs 

### ISSUE THREAD

**Issue by Stefmore02** [hasura/graphql-engine#8998]
### Is your proposal related to a problem?
Currently, on our documentation, we have a series of outdated Hasura Cloud screenshots. While these are mostly present in our cloud database guides there maybe others throughout documentation. 

### Describe the solution you'd like
To solve this a PR would need to be raised that updates all existing screenshots of Cloud that are not consistent with `v2.12.0-cloud.1`.

In order to update these screenshots, please consider these guidelines:
* Consult our wiki for guidance on [file-naming conventions](https://hasura.io/docs/wiki/style/images/#file-name).
* Consult our wiki for guidance on [callouts and arrows](https://hasura.io/docs/wiki/style/images/#callouts-arrows-and-other-screenshot-markup).
* Consult our wiki for guidance on where to [add files](https://hasura.io/docs/wiki/page-structure/#images).

**Comment by Ln11211** [comment]
hey there @Stefmore02 ,
I'm interested in trying to update the screenshots but I want to know more before I commit myself to this issue.
Firstly, I want to know how to get the screenshots and where is this doc with outdated screenshots, can you help me with this info? :)

**Comment by droid31** [comment]
Hi, I would like to work on this issue as part of Hacktoberfest. I have taken a look at the docs, kindly assign the issue to me.

**Comment by Stefmore02** [comment]
@Ln11211 thank you for your interest! For this one, you'll have to audit our docs and see which screenshots are out-of-date. An example would be any of the Cloud screenshots on [this page](https://hasura.io/docs/latest/getting-started/getting-started-cloud/) that reference versions earlier than `2.12.0`.

**Comment by Stefmore02** [comment]
@droid31 Feel free to pick this up. The PR that is submitted first will also be the one to be reviewed first 🙂
