### ISSUE TITLE
Can't create foreign keys on Big Int for cockroachdb

### ISSUE THREAD

**Issue by ejkkan** [hasura/graphql-engine#9016]
### What is the current behaviour?

When trying to create a foreign key relation between two tables via a Big Int rows this error is thrown:
```
{
    "arguments": [],
    "error": {
        "description": null,
        "exec_status": "FatalError",
        "hint": "Some of the non-DDL statements may have committed successfully, but some of the DDL statement(s) failed.\nManual inspection may be required to determine the actual state of the database.\n--\nSee: https://github.com/cockroachdb/cockroach/issues/42061",
        "message": "transaction committed but schema change aborted with error: (23503): foreign key violation: \"users\" row shareables=800183840795852800, id='3e7393b4-cdbe-41fa-8abd-1816dd0ec101' has no match in \"shareables\"",
        "status_code": "XXA00"
    },
    "prepared": true,
    "statement": "COMMIT"
```
### What is the expected behaviour?

To be able to create a foreign key relation between two tables with Big Int rows

**Comment by soupi** [comment]
@ejkkan could you provide reproduction steps for this? That would be very helpful.

**Comment by lucarestagno** [comment]
I think this is related to the issue with BIGINTs, the last 2 digits are truncated (800183840795852800 -> ...00).

A mitigation to this is to enable `HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES` on the server.

Here's a small thread https://hasurahq.slack.com/archives/C01RZPEPF0W/p1664274235484159

@ejkkan could you please confirm that `HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES` mitigates the issue?

**Comment by ejkkan** [comment]
I can confirm that it does not work @lucarestagno 

> I think this is related to the issue with BIGINTs, the last 2 digits are truncated (800183840795852800 -> ...00).
> 
> A mitigation to this is to enable `HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES` on the server.
> 
> Here's a small thread https://hasurahq.slack.com/archives/C01RZPEPF0W/p1664274235484159
> 
> @ejkkan could you please confirm that `HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES` mitigates the issue?

I can confirm that it does not work @lucarestagno

**Comment by ejkkan** [comment]
> @ejkkan could you provide reproduction steps for this? That would be very helpful.

Create two table 
```
Users:
id: UUID
shareables: BigInt
---
Shareables:
id: BigInt
```

To the Modify tab in the Users table.
Scroll down to the "Foreign key" section and try to create the connection between "Users.shareables" -> "Shareables.id"

**Comment by lucarestagno** [comment]
I tried the same and it worked for me.

In order to run the server with `"stringify_numeric_types":true` (double check the container logs to be sure) you need to do `docker compose down` and `up` back.

At least that's the way I found to make the server read the new ENV variable `HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES`.

At that point, the FK worked! ✅

**Comment by soupi** [comment]
I'm unable to reproduce this. Using commit 9960f580b955f973834df6644667f0ffc5bd60ce without any additional flags, I created the `Users` and `Shareables` tables via the console, then added a foreign key from the Users table and it worked without further changes required.

<img width="406" alt="Screen Shot 2022-09-28 at 14 32 08" src="https://user-images.githubusercontent.com/8547573/192768861-9d7c3251-28fb-43df-a32f-2f229d0a8087.png">

**Comment by ejkkan** [comment]
After `docker compose down` and spawning a new cockroachdb, it works for me aswell!:
Thanks for the help
