### ISSUE TITLE
Inserting JSON field with JSON.stringify() inserts data but querying properties do not work

### ISSUE THREAD

**Issue by leoalves** [hasura/graphql-engine#902]
Hello,

When inserting JSON fields using the generated graphql mutation, using JSON.stringify does not work to query properties with Postgresql.

Steps on how to reproduce it:

Create a table named test_json.  Create 2 fields: id (int auto increment) and json (JSONB type).

Run the following code:

```javascript
const { GraphQLClient } = require('graphql-request')
const graphql_host = 'url_to_graphql_endpoint'
const hasuraAccessKey = 'accesskey'
const client = new GraphQLClient(graphql_host, {
    headers: { 'X-Hasura-Access-Key': hasuraAccessKey }
})

const mutation = `
mutation insert_test_json ($objects: [test_json_insert_input!]! ) {
  insert_test_json(objects: $objects) {
    returning {
      json
    }
  }
}`

const json = {
    property1: "test string property 1",
    property2: 1234,
    property3: true
}

const insert = async() => {
    // this will work
    await client
        .request(mutation, {
            objects: [{
                json
            }]
        })

    // this will insert the data into the database 
    // but the select into a property name won't work
    await client
        .request(mutation, {
            objects: [{
                json: JSON.stringify(json)
            }]
        })
}
insert()
```

When selecting a property of the inserted JSON data, in Postgresql,  the first record will work. But the second will return null.

Here is the select command I am using

`SELECT json->'property1' FROM test_json`

Not sure why this is happening. I am new with Postgresql.  Looking at both records the data looks the same to me.

Thanks

**Comment by leoalves** [comment]
Ok. Thanks.  I am new to Postgresql.

**Comment by shahidhk** [comment]
No worries @leoalves. Feel free to re-open if you have any issues. You can also find us at https://discord.gg/vBPpJkS
