### ISSUE TITLE
console: error thrown while deleting relationship should be more descriptive (experimental feature)

### ISSUE THREAD

**Issue by meetzaveri** [hasura/graphql-engine#9024]
### Version Information

Server Version: `v2.12.0-cloud.1`
CLI Version (for CLI related issue):

### Environment

Hasura Cloud

### What is the current behaviour?
This issue is about a new relationship UI (experimental feature). When we try to delete a relationship, it throws a generic error `Error while deleting the relationship`. This message is shown as plain text without any specific details or reason (where we can expand the error message).

### What is the expected behaviour?

Error should be more descriptive. 

Regardless of user's fault or system's fault, this error message should convey a more specific message about what caused it. Having more clear error message, i.e. **why it occurred** or **what caused it**, will help the user to resolve the error by themselves. Error messages should be represented in technical jargon indicating underlying technical problem to the user

### How to reproduce the issue?

1. Create Relationship via new relationship UI (you can test this by toggling experimental feature in console -> Settings -> Feature flags )
2. Try deleting relationship, and it will throw a generic error message `Error while deleting the relationship`

### Screenshots or Screencast

<img width="1436" alt="Screenshot 2022-09-27 at 1 02 21 PM" src="https://user-images.githubusercontent.com/21293048/192547498-b003c4b8-7bcb-44d0-bd58-2f419a0d23ec.png">

### Keywords

relationship delete experimental feature

**Comment by meetzaveri** [comment]
We have a difference in request payload made for old and new UI

New UI
```
{"type":"pg_drop_relationship","args":{"relationship":"from_user","table":{"name":"users","schema":"public"},"source":"default"}} 
```

Old UI
```
{"type":"bulk","source":"default","resource_version":37,"args":[{"type":"pg_drop_relationship","args":{"table":{"name":"messages","schema":"public"},"relationship":"to_user","source":"default"}}]}

```

**Comment by Varun-Choudhary** [comment]
Closing this issue as part of this [PR](https://github.com/hasura/graphql-engine-mono/pull/6147#pullrequestreview-1127836486)
