### ISSUE TITLE
API explorer editor stays shrunk - not expanding vertically in responsive manner to use available height

### ISSUE THREAD

**Issue by SachinB-Droisys** [hasura/graphql-engine#9031]
### Version Information

Server Version: Hasura v2.12.0
CLI Version (for CLI related issue): 

### Environment

Console asset version: 8a1dfb4c701d2

### What is the current behaviour?

When there is empty blank space vertically created either on a large display device or as a result of collapse of GraphQL Endpoint or Request Headers panels, the API Explorer editor should use that space to expand vertically in a responsive manner (increase height) to allow editing evaluating APIs flexibly.

### What is the expected behaviour?

When there is empty blank space vertically available below the API explorer editor, it should use that space in a responsive manner and expand its height.

### How to reproduce the issue?

1. Open API explorer
2. Collapse either or both the GraphQL Endpoint and Request Headers nodes
3. Observe that the API explorer is not using up the empty space created at its bottom as a result of step 2 and stays with the same height

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/48682626/192944325-10ef18e0-9c7d-42ac-ae02-4c38ddc91694.png)

### Please provide any traces or logs that could help here.

​POST https://data.undefined/v1/graphql net::ERR_NAME_NOT_RESOLVED
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
u @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
h @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
o @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
v @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
r @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
c @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
t @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
​          POST https://data.undefined/v1/graphql net::ERR_NAME_NOT_RESOLVED
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
u @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
h @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
o @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
v @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
r @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
c @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
Promise.then (async)
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
Promise.catch (async)
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
t @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
​          POST https://data.undefined/v1/graphql net::ERR_NAME_NOT_RESOLVED
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
u @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
h @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
o @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
v @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
r @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
c @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
Promise.then (async)
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
Promise.catch (async)
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
Promise.then (async)
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
Promise.catch (async)
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
t @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
​          POST https://data.undefined/v1/graphql net::ERR_NAME_NOT_RESOLVED
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
u @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
h @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
o @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
v @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
r @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
c @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
Promise.then (async)
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
Promise.catch (async)
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
Promise.then (async)
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
Promise.catch (async)
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
Promise.then (async)
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
Promise.catch (async)
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
e @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
(anonymous) @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
t @ graphql-engine-cdn.h…2.12/vendor.js.gz:1
react_devtools_backend.js:4026 APIError: Failed to fetch
    at Function.e (graphql-engine-cdn.h…dor.js.gz:1:1464234)
    at e (graphql-engine-cdn.h…ndor.js.gz:1:376702)
    at u (graphql-engine-cdn.h…ndor.js.gz:1:369953)
    at Generator._invoke (graphql-engine-cdn.h…ndor.js.gz:1:369706)
    at Generator.throw (graphql-engine-cdn.h…ndor.js.gz:1:370316)
    at h (graphql-engine-cdn.h…ndor.js.gz:1:375241)
    at c (graphql-engine-cdn.h…ndor.js.gz:1:375489)

![image](https://user-images.githubusercontent.com/48682626/192945396-44e49025-bb8e-447d-949d-7f686e4e6ccf.png)
![image](https://user-images.githubusercontent.com/48682626/192945434-1a5adad7-66df-4975-b85b-7487fae10641.png)
![image](https://user-images.githubusercontent.com/48682626/192945453-ad4e77a8-49c8-4137-ba04-24cadf2539ab.png)

### Any possible solutions?

Have to look at the source code - not aware how to do this.

### Can you identify the location in the source code where the problem exists?

Not aware

### If the bug is confirmed, would you be willing to submit a PR?

Yes

### Keywords

API explorer window height, API explorer query box height issue

**Comment by SachinB-Droisys** [comment]
I just found out that this is due to the Quirk mode (already added as one of the log messages) which causes page layout issues. The possible solution is to include <!DOCTYPE html> at the top of the page as mentioned on [https://web.dev/doctype/?utm_source=devtools](url).

**Comment by rikinsk** [comment]
Ability to resize graphiql has been released with `v2.13.0-beta.1`. See https://github.com/hasura/graphql-engine/issues/8880

**Comment by SachinB-Droisys** [comment]
Thanks @rikinsk for responding back quickly. Hope we are sooner able to see this solution in next update!
