### ISSUE TITLE
console: clarify unused functions in dataSources/services

### ISSUE THREAD

**Issue by lucarestagno** [hasura/graphql-engine#9036]
The functions named `getGraphQLQueryForBrowseRows` in
`console/src/dataSources/services/bigquery/utils.ts` and `console/src/dataSources/services/mssql/utils.ts` seem not to be used.

If this is intentional we need to remove them, or otherwise use them.

**Comment by lucarestagno** [comment]
@vijayprasanna13 any hints on this?

**Comment by vijayprasanna13** [comment]
@lucarestagno This can be removed from the utils file for both the dbs.

**Comment by lucarestagno** [comment]
thanks, I'll do that in my current working branch!
