### ISSUE TITLE
Docs: Broken link in Hasura Docs Wiki

### ISSUE THREAD

**Issue by roshni-salpekar** [hasura/graphql-engine#9047]
### Version Information

Server Version:
CLI Version (for CLI related issue):

### What is the expected behaviour?
"Contributing to Docs" link should point to a page with relevant documentation.

### How to reproduce the issue?

1.
2.
3.

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/73110064/193396383-b009142a-8b3f-493b-9451-09481fc6b46e.png)

**Comment by 201B153** [comment]
But the link is working!

**Comment by roshni-salpekar** [comment]
Path to "Hasura Docs Wiki" where the link is broken.
![Screenshot_20221001_211325~2](https://user-images.githubusercontent.com/73110064/193417406-c3f9210e-15d0-4178-a323-c5697a00f599.jpg)

**Comment by 201B153** [comment]
ok can I change it!?

**Comment by kunalranjan19** [comment]
hey, I would like to work on this.

**Comment by MoskalykA** [comment]
The link works properly
[https://hasura.io/docs/wiki/contributions/](https://hasura.io/docs/wiki/contributions/)

**Comment by robertjdominguez** [comment]
Hey, everyone 👋 

Thanks for this PR @roshni-salpekar, but the several comments that mention this is working are correct. The `docs` directory uses Docusaurus as its framework, and these root-relative paths are used at build time to generate the right links. As you can see from the [live site](https://hasura.io/docs/wiki/), everything functions as expected.
