### ISSUE TITLE
Document how to resolve SSL certificate errors with EPROTO codes 

### ISSUE THREAD

**Issue by adas98012** [hasura/graphql-engine#9058]
We have several instances of client-side issues reported for SSL cerificate errrors
(Refer: tickets 
[5284](https://hasurahelp.zendesk.com/agent/tickets/5284)
[5993](https://hasurahelp.zendesk.com/agent/tickets/5993)

The error message would be similar to this:

```
ERROR:
{
code: EPROTO,
errno: EPROTO,
message:
request to <graphql-api> failed, reason: write EPROTO <....> alert handshake failure:..<...>: SSL alert number 40
```

The recommended resolution is to :
**whitelist the EPROTO error code (in client side code), allow the retry logic to be activated, and monitor the system for improvements or changes in the reconciliation process**

We should update our Troubleshooting guide with this information :
https://hasura.io/docs/latest/troubleshooting/index/

**Comment by Smartmind12** [comment]
Hey, Could you assign this issue to me as i would like to work on it...Thanks!

**Comment by Smartmind12** [comment]
@Stefmore02 @marionschleifer Kindly review my submission and propose recommendations if any!
Also, requesting you to assign the "Hacktoberfest" label if possible. Thanks!

**Comment by Stefmore02** [comment]
Issue closed thanks to #[9077](https://github.com/hasura/graphql-engine/pull/9077)
