### ISSUE TITLE
link to docs on console help button

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#908]
the help button on console currently links to GitHub, Discord and email. It should also link to docs.

![image](https://user-images.githubusercontent.com/4124733/47638883-e3931280-db85-11e8-9d28-6916089cd4b0.png)

**Comment by rifrayugo** [comment]
@shahidhk I'll help you to add the link to docs

**Comment by rifrayugo** [comment]
@shahidhk did pull request on #909

**Comment by shahidhk** [comment]
Thanks, @praveenweb and @karthikvt26 will review.

**Comment by dushyantRathore** [comment]
@shahidhk did pull request on #931
