### ISSUE TITLE
console: text getting trimmed in select dropdown box in "column presets" (permission builder)

### ISSUE THREAD

**Issue by meetzaveri** [hasura/graphql-engine#9086]
### Version Information

Server Version: `v2.12.0-cloud.1`
CLI Version (for CLI related issue):

### Environment

Cloud

### What is the current behaviour?

The text in select dropdown is trimmed given the height of the select dropdown container. the css property of `line-height` has 30 px with respect to `height:30px`

### What is the expected behaviour?

It should be fitting into select dropdown container with sufficient amount of height. When debugging it with chrome inspector, if I remove `line-height:30px` css property for that specific element, then it displays as expected without trimming.

### How to reproduce the issue?

1. Go to permissions tab in table view (console)
2. create role(if not any) or modify existing role
3. try to apply permissions for any of the "insert,select,update,delete" and try to add column preset for that specifci permission

### Screenshots or Screencast

![console_2 12 0_permissions_builder](https://user-images.githubusercontent.com/21293048/194639841-583b96de-cf6e-4b24-ac66-d0b6577de7bc.png)

### Any possible solutions?

yea maybe we can omit extra css property`line-height:30px` to that specific element

### Can you identify the location in the source code where the problem exists?

Maybe this line from `console/src/theme/legacy-bootstrap.css` might be the one - https://github.com/hasura/graphql-engine/blob/4a321e2459cf3fc83c99af438a06d4c330d3a30f/console/src/theme/legacy-boostrap.css#L2508

### Keywords

console column presets permissions

**Comment by vijayprasanna13** [comment]
@meetzaveri this is fixed in https://github.com/hasura/graphql-engine/commit/0add59185d2969269bb130c510c4155422237e18
