### ISSUE TITLE
CLI - hasura seed create crash with postgres15

### ISSUE THREAD

**Issue by Ked57** [hasura/graphql-engine#9117]
### Version Information

Server Version: 2.13.0
CLI Version (for CLI related issue): 2.13.0

### Environment

On local machine

### What is the current behaviour?
When running pg-15 and running `hasura seed create`, pg dump crashes
```
{
  "code": "unexpected",
  "error": "error while executing pg_dump: pg_dump: error: server version: 15.0 (Debian 15.0-1.pgdg110+1); pg_dump version: 14.5 (Ubuntu 14.5-1.pgdg20.04+1)\npg_dump: error: aborting because of server version mismatch\n",
  "path": "$"
} 
```

### What is the expected behaviour?

command should not crash

### How to reproduce the issue?

1. Latest hasura version (2.13.0) with pg 15
2. Try to create seed from database
3. It should crash

### Any possible solutions?

Bump pg_dump version on the CLI

### If the bug is confirmed, would you be willing to submit a PR?

Sadly, I don't know anything about go

**Comment by SamirTalwar** [comment]
Hey @Ked57, thanks for reporting this! We needed to upgrade the version of `pg_dump` shipped with the GraphQL Engine server (the CLI just calls an endpoint on the server, which actually runs `pg_dump`). I'm hoping we get this into the next release. It's been fixed on trunk in https://github.com/hasura/graphql-engine/commit/68f4779908a1ebb6b3d3b17933f678bde808e57c.

**Comment by Ked57** [comment]
No problem, I guess I can close this 😄 

Thank you for keeping me informed
