### ISSUE TITLE
Deleting event trigger failed 

### ISSUE THREAD

**Issue by Edjevw12** [hasura/graphql-engine#9119]
### Version Information

Server Version:
CLI Version (for CLI related issue):
2.12

### What is the current behaviour?
Not possible to delete event triggers in the console. Due to this issue, metadata cannot be applied either. 

`time="2022-10-17T11:11:17+02:00" level=fatal msg="error applying metadata \n{\n  \"code\": \"not-exists\",\n  \"error\": \"event trigger \\\"temp_startWelcomeProcess\\\" does not exist\",\n  \"path\": \"$.args\"\n}"`

We tried to reset the metadata and import the metadata file where we removed the event triggers, but that doesn't work either.

### What is the expected behaviour?

The trigger should be removed.

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/37038043/196141076-5cb979b6-f21c-4632-ab94-c8581e2f0e5f.png)
![image](https://user-images.githubusercontent.com/37038043/196141874-e4cb0c54-fb7f-4ee5-858f-dfc70a5c0d0c.png)

**Comment by BenoitRanque** [comment]
@Edjevw12 you mention trying to reset the metadata, can you explain how you went about it?
The error indicates you are missing the `hdb_catalog.event_log` table, which should be created when adding triggers.
Can you also tell us what environment you are using hasura in? (self hosted OSS, Hasura Cloud, Enterprise)

**Comment by Edjevw12** [comment]
@BenoitRanque i figured if I manually export the metadata, removing the event_triggers array and import again it would remove the event but did not work.

This behaviour started locally, with hasura-console, but we applied the metadata to production last week, now same behaviour on production (Hasura Cloud)

note: we did cleanup event data locally with the following sql

```sql
DELETE FROM hdb_catalog.event_invocation_logs;

DELETE FROM hdb_catalog.event_log
WHERE delivered = true OR error = true;
```

**Comment by BenoitRanque** [comment]
@Edjevw12 could you please [create a support ticket](http://cloud.hasura.io/support) so we can get in a call and look into this issue? We'd like to resolve this problem for you, and would also like to understand how your project entered that state, both of which may best be achieved over a call. Please mention this issue in your support request.

**Comment by Edjevw12** [comment]
> @Edjevw12 could you please [create a support ticket](http://cloud.hasura.io/support) so we can get in a call and look into this issue? We'd like to resolve this problem for you, and would also like to understand how your project entered that state, both of which may best be achieved over a call. Please mention this issue in your support request.

will do, thanks!

**Comment by Edjevw12** [comment]
inconsistent metadata was the issue (missing environment variable) solved!
