### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by saimaheshtaduri** [hasura/graphql-engine#9147]
### Describe the solution you'd like
add raise an issue link in contributing.md file

add the below line in creating issue section
- you can raise an issue [here](https://github.com/hasura/graphql-engine/issues/new/choose)

**Comment by itzwow** [comment]
I would like to work on this issue

**Comment by saimaheshtaduri** [comment]
@itzwow I am actually waiting for their approval to raise pr.

**Comment by itzwow** [comment]
> @itzwow I am actually waiting for their approval to raise pr.

Alright !

**Comment by robertjdominguez** [comment]
Resolved by #9159 🎉
