### ISSUE TITLE
Modify "schema"/"manage" box in the console

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#915]
![screen shot 2018-10-29 at 5 22 18 pm](https://user-images.githubusercontent.com/24300818/47648266-87d58300-db9f-11e8-8e61-70d2d3701e96.png)

Any idea why this box was added @arvi3411301 ? Especially with the breadcrumbs also available in almost every page. This goes for the `Events` tab too.

**Comment by praveenweb** [comment]
@dsandip - I think this was added for context when the user is in SQL page, where the breadcrumbs doesn't give information on which schema is active.

But if its meddling with the UI, then we can do something else (like adding the active schema information inside SQL page itself)

**Comment by praveenweb** [comment]
This section will now have a dropdown to switch between schemas. Being tracked here - https://github.com/hasura/graphql-engine/issues/1092 Closing this.
