### ISSUE TITLE
Invalid response from authorization hook: Error in $: expected [a], encountered Object",

### ISSUE THREAD

**Issue by raheelriax** [hasura/graphql-engine#916]
Authorization through webhooks returns this error on hasura/graphql-engine:v1.0.0-alpha26 , working fine on  hasura/graphql-engine:v1.0.0-alpha25.

**Comment by shahidhk** [comment]
Hello @raheelriax, this is a know bug with alpha26. Please update to alpha27 which contains the fix. Read more at https://github.com/hasura/graphql-engine/releases/tag/v1.0.0-alpha27
