### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by unnionapp** [hasura/graphql-engine#9165]
construct@[native code]
construct@[native code]
n@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:6385150
construct@[native code]
r@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:6384483
r@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:6386240
e@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:8634729
rc@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:32629642
Pl@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:32656934
Il@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:32656859
Sl@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:32653709
Sl@[native code]
@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:32604680
@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:32680491
si@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:32604626
ui@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:32604561
xl@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:32650461
jo@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:32621946
jo@[native code]
@https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.14.0-cloud.1/vendor.js.gz:1:9211409
promiseReactionJob@[native code]

**Comment by manasag** [comment]
Hi @unnionapp , thanks for opening this issue.

Unfortunately the information provided is not enough to understand this issue. Would you be able to share what operations being done prior to this error. Console URL and screenshots would be helpful too.

**Comment by manasag** [comment]
Hi @unnionapp, we are closing this issue due to lack of information. Please feel free to reopen this with more details.
