### ISSUE TITLE
Formatting issues with Code Exporter in GraphiQL API Explorer

### ISSUE THREAD

**Issue by manasag** [hasura/graphql-engine#9169]
### Version Information

Server Version: v2.13.0-cloud.1

### Environment

Cloud

### What is the current behaviour?
The code exporter section in the API explorer shows some formatting issues. The top section overlaps with the bottom text area section.

### What is the expected behaviour?

There should be no overlap of texts. The header and main section of Code exporter should be separate.

### How to reproduce the issue?

1. Open project
2. In API tab, click on 'Code Exporter' button in the Explorer section

### Screenshots or Screencast

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/5352361/199487534-5fd8de51-981c-41ca-9a2d-cce43dbd7d66.png">

### Keywords

GraphiQL, Code Exporter

**Comment by manasag** [comment]
This issue has been prioritised and currently the fix is in-progress.

**Comment by zaqwery** [comment]
any updates on this bug? how do we toggle between JavaScript and TypeScript?
