### ISSUE TITLE
hasura action gives error on changing parameters

### ISSUE THREAD

**Issue by arush-spacetime** [hasura/graphql-engine#9174]
### Version Information
v2.14.0-cloud.1
Server Version:
CLI Version (for CLI related issue):

### Environment

Cloud
### What is the current behaviour?

Getting this error on an action, despite not setting any custom response transformation on my own. In the Actions settings tab, there isn't any added request transformation. 
This action used to work perfectly before, but started giving errors recently. Now, any new action faces the same errors.
From the logs I know that the request is properly handled at the backend (webhook that the action calls). This "Response Transformation" error started appearing out of nowhere as far as I know. 

### What is the expected behaviour?
For this to not happen, and the action to be processed properly.

### How to reproduce the issue?

1. In the account I'm using, first, make an action with say any parameters.
2. Set everything properly. Test the action. It works perfectly. Now, go to the action settings and change anything, for example, add a new parameter to the action.
3. Test the same action. would crash with this error.

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/111136776/199654437-045d51e7-a4ec-4a81-b70b-abba3be5763a.png)
Here is also a screencast of me reproducing the same issue on a new action. The code for the testingAction webhook is simple:- 
```
module.exports.testAction = async (req, res) => {
  console.log("hit")
  return res.json({
    status: "Banana"
  })
};
```
I do get a "hit" printed in the logs, even after the response doesn't show up properly on hasura.

https://user-images.githubusercontent.com/111136776/199655968-4b4d8ba6-d5b5-429f-ac00-0796eb8fd109.mp4

### Any possible solutions/workarounds you're aware of?
None

### Keywords
"Response Transformation Failed"

**Comment by tirumaraiselvan** [comment]
Thanks for reaching out. This is a bug, reported earlier here: https://github.com/hasura/graphql-engine/issues/9170

The fix will be out shortly.

**Comment by arushsharma24** [comment]
That's great to hear. What sort of timeline do you mean by shortly? It would be great if you could clarify that since we are building a service and have developed it on Hasura so far, but would have to migrate if this issue persists longer than the business timeline would allow us. Can we expect this to be solved in a few days, weeks, or months?

**Comment by manasag** [comment]
Hi @arushsharma24, we estimate to fix this within 24 hours.

**Comment by tirumaraiselvan** [comment]
@arush-spacetime We updated the console assets on the CDN with a fix. Can you try your workflow now?

**Comment by arush-spacetime** [comment]
Hey @tirumaraiselvan and @manasag , that is amazing, it works again now! Thanks a lot!!
Although the old actions don't work, but making new ones with the same endpoints works so that's great! 

I suppose I'll close this issue. Again, thanks a lot for such timely resolution of the issue guys, really glad :)

**Comment by BenoitRanque** [comment]
@arush-spacetime you can fix the old action with the following steps:

- export metadata from the console as a json file
- find the json key `response_transform` in your action metadata and remove it for all affected actions
- import the metadata from the console back into your project

This assumes you never had a response transform, which should be the case for most users.

**Comment by cheets** [comment]
This isn't fixed for CE (I don't know if EE customers have gotten a hot fix) so I wouldn't have closed this @arush-spacetime. Currently both 2.14.0 and 2.15.0-beta1 are broken and users need to downgrade to 2.14.0-beta1/2 to get actions working. Our application login is now broken because it relies on custom actions and we are waiting for a fix release. Looks like we have to downgrade unless a fix comes soon.

**Comment by tirumaraiselvan** [comment]
@cheets I think you may have to clean your old actions as mentioned in this [comment](https://github.com/hasura/graphql-engine/issues/9174#issuecomment-1303081186)
