### ISSUE TITLE
CLI: response transform metadata not exported

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#9182]
### Version Information

Server Version: 2.14.0
CLI Version (for CLI related issue): 2.14.0, 2.15.0-beta.1

### Environment

OSS

### What is the current behaviour?

Cli fails to export Action Response Transform metadata

### What is the expected behaviour?

Action Response Transform metadata should be exported.

### How to reproduce the issue?

1. Create an action with a response transform using the api
2. Export metadata using cli, response transform metadata will be missing
3. Export metadata json using the console, response transform metadata will be present

**Comment by manasag** [comment]
This has been prioritised. Thanks for raising this bug.

**Comment by manasag** [comment]
The fix has been pushed. The next release 2.16 will support this.
