### ISSUE TITLE
can't view more than 1 hours of logs

### ISSUE THREAD

**Issue by Maxhodges** [hasura/graphql-engine#9183]
### Version Information
2140cloud1
Server Version:
CLI Version (for CLI related issue):

### Environment
cloud

### What is the current behaviour?
ERror trying to view logs > 1 hour
https://cloud.japanrabbit.com/pXjXi8

### What is the expected behaviour?

should be able to see logs

### How to reproduce the issue?

1.change the filter from last hour to last 6 hours. 
2.
3.

### Screenshots or Screencast
https://cloud.japanrabbit.com/pXjXi8

### Please provide any traces or logs that could help here.

vendor.js.gz:1 Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
F @ vendor.js.gz:1
vendor.js.gz:1 console.group
vendor.js.gz:1  Sentry Tracing Enabled 
vendor.js.gz:1  Sentry Environment: cloud.hasura.io 
/project/81dacee9-f41a-4909-8e2b-7af7476e7933/console/pro/error?filters=%5B%7B%22value%22:%22Last%2012%20hours%22,%22type%22:%22time_range%22%7D%5D&groupbys=%5B%22error_code%22,%22operation_name%22,%22operation_type%22%5D:1 Refused to execute script from 'https://cloud.hasura.io/rstatic/dist/2.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
vendor.js.gz:1 Uncaught (in promise) ChunkLoadError: Loading chunk 2 failed.
(error: https://cloud.hasura.io/rstatic/dist/2.js)
    at Function.e (vendor.js.gz:1:978)
    at Object.<anonymous> (main.js.gz:1:786136)
    at 1382 (main.js.gz:1:788300)
    at c (vendor.js.gz:1:654)
    at Object.<anonymous> (main.js.gz:1:770994)
    at 1380 (main.js.gz:1:780669)
    at c (vendor.js.gz:1:654)
    at Object.<anonymous> (main.js.gz:1:752940)
    at 1378 (main.js.gz:1:766985)
    at c (vendor.js.gz:1:654)
vendor.js.gz:1 Failed fetching heroku session
(anonymous) @ vendor.js.gz:1
main.js.gz:1 TypeError: Invalid Version: undefined
    at new ee (vendor.js.gz:1:11688384)
    at ue (vendor.js.gz:1:11692237)
    at Function.pe [as gt] (vendor.js.gz:1:11692577)
    at n (main.js.gz:1:1587432)
    at Main.n (main.js.gz:1:84281)
    at main.js.gz:1:82945
n @ main.js.gz:1
error:1 Access to fetch at 'https://us-west-1-aws.metrics.pro.hasura.io/v1/graphql' from origin 'https://cloud.hasura.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
graphql:1          Failed to load resource: net::ERR_FAILED
error:1 Access to fetch at 'https://us-west-1-aws.metrics.pro.hasura.io/v1/graphql' from origin 'https://cloud.hasura.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
graphql:1          Failed to load resource: net::ERR_FAILED
error:1 Access to fetch at 'https://us-west-1-aws.metrics.pro.hasura.io/v1/graphql' from origin 'https://cloud.hasura.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
graphql:1          Failed to load resource: net::ERR_FAILED
error:1 Access to fetch at 'https://us-west-1-aws.metrics.pro.hasura.io/v1/graphql' from origin 'https://cloud.hasura.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
graphql:1          Failed to load resource: net::ERR_FAILED
error:1 Access to fetch at 'https://us-west-1-aws.metrics.pro.hasura.io/v1/graphql' from origin 'https://cloud.hasura.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
graphql:1          Failed to load resource: net::ERR_FAILED
error:1 Access to fetch at 'https://us-west-1-aws.metrics.pro.hasura.io/v1/graphql' from origin 'https://cloud.hasura.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
graphql:1          Failed to load resource: net::ERR_FAILED
error:1 Access to fetch at 'https://us-west-1-aws.metrics.pro.hasura.io/v1/graphql' from origin 'https://cloud.hasura.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
vendor.js.gz:1          POST https://us-west-1-aws.metrics.pro.hasura.io/v1/graphql net::ERR_FAILED 524

### Any possible solutions/workarounds you're aware of?
nope

**Comment by adas98012** [comment]
@Maxhodges 
We may need some additional inputs from you regarding your project, to investigate the issue.
Could you please [create a support ticket](http://cloud.hasura.io/support), with a reference to this Github Issue ?

**Comment by Maxhodges** [comment]
OK sent. If you leave this issue open I can share the result if it might help others.

**Comment by ecthiender** [comment]
Folks, is this issue resolved?

**Comment by adas98012** [comment]
@ecthiender 
I think this was resolved (via zendesk support ticket 6230). 
There was a metrics issue in the regions of us-west-1 and us-east-1 that caused this issue.
