### ISSUE TITLE
mutation where: _or does not filter at all

### ISSUE THREAD

**Issue by efstathiosntonas** [hasura/graphql-engine#9186]
### Version Information

Server Version: 2.15.0-ce

### Environment

OSS
### What is the current behaviour?

With this mutation: 

```gql
mutation SoftDeleteAll($account_id: String!, $deleted_at: timestamptz!) {
  update_notification(
    where: {
      _or: [{ sender_id: { _eq: $account_id }, recipient_id: { _eq: $account_id } }]
    }
    _set: { deleted_at: $deleted_at }
  ) {
    affected_rows
  }
}
```

I get back 0 `affected rows`.
### What is the expected behaviour?

Don't know if this is a correct mutation filter as on docs there's no `_or` filter mutation, so according to the [docs](https://hasura.io/docs/latest/mutations/postgres/update/#multiple-updates) this should be translated to this:

```gql
  update_notification_many(
    updates: [
      { where: { sender_id: { _eq: $account_id } },  _set: { deleted_at: $deleted_at } }
      { where: { recipient_id: { _eq: $account_id }}, _set: { deleted_at: $deleted_at } }
    ]
  ) {
    affected_rows
  }
```

The latter is working but why the 1st one does not work. I really can't remember if the 1st query was working in previous server versions (I'm still in development mode and I've never touched this mutation until recently).

Edit: tried `2.14.0`,`2.13.0` and the same happens, 1st mutation returns 0 `affected_rows`

### Keywords

_or where mutation

**Comment by adas98012** [comment]
This is reproducible in Hasura Cloud (v2.14.0) too.

Steps to reproduce:
1. Create the table :

```
CREATE TABLE notification
(
  id int NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
  sender_id TEXT,
  recipient_id TEXT,
  deleted_at timestamptz NULL DEFAULT now()
);
```

2. Insert some test data (through SQL in Data Tab):

```
INSERT INTO notification(sender_id, recipient_id, deleted_at)
VALUES('100', '200', now());

INSERT INTO notification(sender_id, recipient_id, deleted_at)
VALUES('200', '300', now());

INSERT INTO notification(sender_id, recipient_id, deleted_at)
VALUES('300', '400', now());
```

3. Run the following mutation on the API tab of Console:

```
mutation MyMutation($account_id: String!, $deleted_at: timestamptz!) {
  update_notification(
    where: {
      _or: [{ sender_id: { _eq: $account_id }, recipient_id: { _eq: $account_id } }]
    }
    _set: { deleted_at: $deleted_at }
  ) {
    affected_rows
  }
}
```

Query Variables:

```
{
  "account_id": "200",
  "deleted_at": "2020-01-01T01:00:00.000000+00:00"
}
```
4. Record the result:

```
{
  "data": {
    "update_notification": {
      "affected_rows": 0
    }
  }
}
```

**Comment by efstathiosntonas** [comment]
@adas98012 thank you for verifying the bug, this seems to be a serious bug and can go unnoticed since it silently "fails" to update the rows.

**Comment by SamirTalwar** [comment]
I think the bug may be in the query. Please correct me if I'm wrong.

You specify:

```
      _or: [{ sender_id: { _eq: $account_id }, recipient_id: { _eq: $account_id } }]
```

This is a single object, for which all properties are checked. I think you intended this array to have two elements, not one:

```
      _or: [
        { sender_id: { _eq: $account_id } }
        { recipient_id: { _eq: $account_id } }
      ]
```

When I change the query to this, it updates two rows in the example @adas98012 posted above.

Does this solve your issue, or have I misunderstood it?

**Comment by efstathiosntonas** [comment]
@SamirTalwar let me check and I'll get back to you. I believe you're right, there's no distinction between the objects and this might get translated badly into a query.

**Comment by efstathiosntonas** [comment]
@SamirTalwar yes you're right, this was the culprit. It's really easy to mess with curly braces on queries. Thank you.

**Comment by SamirTalwar** [comment]
Thanks for confirming! I agree, it's so easy to mix up brackets.

FWIW, when I modified it, [Prettier](https://prettier.io/) autoformatted it to be over multiple lines. (I use a plugin for my editor(s) to run Prettier on everything it can.) You might find that an autoformatter helps you find bugs like this, especially if you're liberal in sprinkling newlines everywhere.

**Comment by efstathiosntonas** [comment]
I use prettier too but the object is valid so no errors from that side. I also use codegen, no errors from that side too. It's just a curly brace hell that we must be extremely cautious about.
