### ISSUE TITLE
REST button not working on project GraphQL page 

### ISSUE THREAD

**Issue by rishibijlani** [hasura/graphql-engine#9189]
### Version Information

Server Version:
CLI Version (for CLI related issue):

### Environment
Hasura v2.15.0-cloud.1

### What is the current behaviour?
When I click on REST button to make a rest API for a query, the button does not take me to the create REST API page.
The other buttons are working as expected when clicked.

### What is the expected behaviour?
The button should redirect to create REST API page for the query

### How to reproduce the issue?

1. Write a query
2. Click on REST

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/98522217/200506078-3452c19d-96ae-40c9-b043-92abf891d3f7.png)

### Keywords
REST endpoint, REST

**Comment by manasag** [comment]
Thanks @rishibijlani for raising this issue. I can reproduce this issue with new v2.15.  We will investigate this and update soon.

**Comment by manasag** [comment]
We have identified the bug and are in the process of fixing this in cloud.

**Comment by rishibijlani** [comment]
It is working as expected, thank you!
