### ISSUE TITLE
Ability to link to specific environment variables in server config reference.

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#9201]
### Is your proposal related to a problem?

One of the most useful docs page is the server config reference, which lists (most) environment variables that can be used to customize the behavior of an instance.

One issue is that this page does not allow us to link to specific environment variables. Being able to do so would be a great asset when referencing this part of the docs.

### Describe the solution you'd like

This is a request to make it possible to link to a specific env var's documentation directly

**Comment by marionschleifer** [comment]
Tagging @robertjdominguez here because he is currently working on the environment variables page.

**Comment by robertjdominguez** [comment]
The [most recent update](https://hasura.io/docs/latest/deployment/graphql-engine-flags/reference/) to this page includes links to individual vars / flags 🎉
