### ISSUE TITLE
open web too slow

### ISSUE THREAD

**Issue by chenj133** [hasura/graphql-engine#9209]
### Version Information

Server Version:v2.15.0

### Environment

docker

### What is the current behaviour?

open hasura web slow. I find that each time I open the web, four files from https://graphql-engine-cdn.hasura.io/ will be load. the response time is very long to reach the website in China. How do I change the vendor.js.gz/main.js.gz/main.css.gz/font-awesome.min.css.gz to my own oss path?
![image](https://user-images.githubusercontent.com/55866399/201915005-b52bcedb-6f85-4bf2-8261-f614caa3803b.png)

**Comment by manasag** [comment]
Hi @chenj133 , this [guide](https://hasura.io/docs/latest/deployment/graphql-engine-flags/config-examples/#console-assets-on-server) may help you in switching your hasura to use local assets instead. In short, you have to set this environment variable `HASURA_GRAPHQL_CONSOLE_ASSETS_DIR=/srv/console-assets`.

**Comment by chenj133** [comment]
Thank you，it works.
