### ISSUE TITLE
After clicking the text extension button in Hasura Cloud, the error "Must have at least one of $set, $inc, and $mul" occurs when modifying it.

### ISSUE THREAD

**Issue by jieey1140** [hasura/graphql-engine#9218]
### Version Information

Server Version:
CLI Version (for CLI related issue): 2.15.0  (2.15.0-cloud.1)

### Environment

Cloud

### What is the current behaviour?

Click Collapse in Hasura Console to modify and save column data 

```
Edit failed!
atleast one of $set, $inc, $mul has to be present
```

An error occurs. We didn't have this problem in the past, but now we have this problem and we're having trouble putting data in.

### What is the expected behaviour?

When you insert and modify text, data should be entered in the Collapse manner normally. If you do not use Collapse, it will be corrected normally.

### How to reproduce the issue?

1.Select columns to change after accessing Hasura Cloud
2.Click Collapse on the Modify tab and enter data
3.Error when inserting data and pressing Save

### Screenshots or Screencast
![Screen Shot 2022-11-18 at 9 27 52 AM](https://user-images.githubusercontent.com/85172908/202589265-510db9f6-797f-4541-855e-e7b3eec99434.png)

When you are not using Collapse
![Screen Shot 2022-11-18 at 9 33 05 AM](https://user-images.githubusercontent.com/85172908/202589610-4d933f61-bc4d-43bc-8aed-05e7529e878e.png)

### Please provide any traces or logs that could help here.

```
Edit failed!
atleast one of $set, $inc, $mul has to be present
```

### Keywords

Hasura Cloud, Collapse

**Comment by adas98012** [comment]
@jieey1140 
Can you please share a screenshot with the error that you are seeing ?

**Comment by jieey1140** [comment]
@adas98012  Thank you. I added an error picture.

**Comment by adas98012** [comment]
@jieey1140 
Thanks for the update. I am assigning this to our engineering team. You'll be able to see updates on this issue here in this space.

**Comment by adas98012** [comment]
@jieey1140 
Our engineering team has identified the issue and deployed a code fix. I retested it and couldn't see the earlier error anymore. Can you please check and let us know ?

**Comment by jieey1140** [comment]
@adas98012 

Wow! I just put data in my production server. The data was successfully INSERTed without any errors. Thank you for your quick handling of the Hasura Team! 

Have a nice day. I think this issue has been resolved perfectly, so I think you can close this issue. Thank you. Have a nice day :)


<img width="1127" alt="Screen Shot 2022-11-22 at 2 28 18 AM" src="https://user-images.githubusercontent.com/85172908/203121766-b13f7a9d-d9d4-4c28-a624-e8cb7bbb30ac.png">
