### ISSUE TITLE
Remote schema type prefix/suffix should be removed when the request is forwarded to the remote schema

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#9219]
### Version Information

Server Version: 2.14.0

### What is the current behaviour?

To avoid type conflicts with remote schema, hasura allows the user to set type prefixes and suffixes.
This effectively namespaces the types and prevents conflicts.

Hasura maps variables to scalar or JSON values when proxied to remote schemas.
However, this mapping does not happen if the request includes enums.

This is an issue as the remote schema will not be able to process the query.

Given this schema:

```gql
enum TodoTypeEnum {
  work,
  rest
}

type Todo {
  description: String
  type: TodoTypeEnum
}

query {
  todo_by_type(type: TodoTypeEnum): Todo
}
```

And the following query:
```gql
query GetTodoByType ($todoType: TodoTypeEnum) {
  todo_by_type(type: $todoType) {
    type
    description
  }
}
```

Adding the type prefix `remote_` will result in the following query being sent to the remote schema:
```gql
query GetTodoByType ($todoType: remote_TodoTypeEnum) {
  todo_by_type(type: $todoType) {
    type
    description
  }
}
```

The remote schema does not have a type `remote_TodoTypeEnum`, so the request is rejected.

### What is the expected behaviour?

Hasura should remove prefixes as it forwards the request to the remote schema.

### How to reproduce the issue?

1. Add a type prefix to a remote schema
2. Execute a request using either an enum input variable, either directly or as part of another input type
3. The remote schema rejects the request

**Comment by BenoitRanque** [comment]
Related: #8698

**Comment by BenoitRanque** [comment]
Incidentally, when prefixes are configured, hasura does some custom mapping of arguments, deconstructing aliased types to scalar primitives and passing those individually.

This would be an issue for any user who happened to have allow lists on their prefixed remote schema, as hasura effectively rewrites the query.

**Comment by zachequi** [comment]
> Incidentally, when prefixes are configured, hasura does some custom mapping of arguments, deconstructing aliased types to scalar primitives and passing those individually.
> 
> This would be an issue for any user who happened to have allow lists on their prefixed remote schema, as hasura effectively rewrites the query.

FWIW, this affected us as well.  We run a middleware on all GQL queries that mutates inputs depending on input variable name, since hasura rewrote them we had to write some logic to re-map the hasura generated names to the actual argument name.

**Comment by codingkarthik** [comment]
Thank you folks for reporting this bug. This has been fixed now and the fix will be included in the next release.

**Comment by BenoitRanque** [comment]
I'll open a different issue for the inlining problem.
