### ISSUE TITLE
function cannot be tracked because the function does not return a table

### ISSUE THREAD

**Issue by JoeLeBaron1** [hasura/graphql-engine#9225]
### Version Information

Server Version:
v2.15.1

### Environment
Local Docker Container

### What is the current behaviour?
Error when trying to track a function
```
[
    {
        "definition": {
            "name": "search_articles",
            "schema": "public"
        },
        "name": "function search_articles in source client_portal_part",
        "reason": "Inconsistent object: in function \"search_articles\": the function \"search_articles\" cannot be tracked because the function does not return a table",
        "type": "function"
    }
]
```

### What is the expected behaviour?
Function should be tracked. 

### How to reproduce the issue?

1.  Create the table and function in Postgres
```
create table public.articles (id integer, title text, content text);

CREATE OR REPLACE FUNCTION public.search_articles(search text)
RETURNS SETOF public.articles AS $$
    SELECT *
    FROM articles
    WHERE
      title ilike ('%' || search || '%')
      OR content ilike ('%' || search || '%')
$$ LANGUAGE sql STABLE;
```
2.  Navigate through Hasura UI, track the table, and then track the function

### Keywords
Hasura function cannot be tracked

**Comment by adas98012** [comment]
@JoeLeBaron1 
As per the Hasura Docs, you need to have the table already tracked before creating the function:

https://hasura.io/docs/latest/schema/postgres/custom-functions/#pg-supported-sql-functions
