### ISSUE TITLE
Could not read undefined as a valid JSON object/array 

### ISSUE THREAD

**Issue by happyfloat** [hasura/graphql-engine#9230]
### Version Information

v2.15.0-cloud.1

### What is the current behaviour?

When I try to save a jsonb field in the "expanded" input mode (in the hasura cloud console), it will fail with this error message: "content :: could not read undefined as a valid JSON object/array ". 
I can collapse the input field again to a single line and I can save it without any problem.

### What is the expected behaviour?

Let me save my json fields in the expanded input mode again (multiline).

### Keywords

- JSON
- undefined as a valid JSON

**Comment by adas98012** [comment]
Related issue : [9218](https://github.com/hasura/graphql-engine/issues/9218)

**Comment by adas98012** [comment]
@happyfloat 
Our engineering team is looking into the issue,  we'll let you know when a fix is made and deployed.

**Comment by happyfloat** [comment]
@adas98012 Thank you. Unfortunately, the Hasura console doesn't give me much confidence recently 😞 . Every version something else is broken (pagination, filters, ordering, column titles, ...). Nevertheless Hasura engine is still the best and I recommend it to everyone! 💯 👍

**Comment by adas98012** [comment]
@happyfloat 
Sorry to hear about your sub-optimal experience with Hasura Console. Please let us know of any issues/inconsistencies you find in the Console and we'll escalate those to our engineering team.
