### ISSUE TITLE
metadata: importing cloud metadata in 2.15.1 shows athena data_connector_agent error

### ISSUE THREAD

**Issue by meetzaveri** [hasura/graphql-engine#9237]
### Version Information

Server Version: 2.15.1
CLI Version (for CLI related issue): 2.15.1

### Environment

OSS

### What is the current behaviour?

Currently, when I am importing metadata from hasura cloud (`v2.15.0-cloud.1`) to hasura CE (`v2.15.1`), then it is showing me athena data_connector_agent error. 

Full error here
```json
[
   {
        "definition": "athena",
        "name": "data_connector_agent athena",
        "reason": "Inconsistent object: Error in Data Connector backend: Connection failure",
        "type": "data_connector_agent"
    },
]
``` 

### What is the expected behaviour?

As a user who is not using AWS Athena (or not connected to Athena service), this error looks irrelevant here. Hence, metadata should be imported successfully (barring the already inconsistent objects).

### How to reproduce the issue?

1. Spin up hasura OSS version `2.15.1` 
2. Not required but - its metadata/migrations should be identical to that of hasura cloud instance (from which you are importing metadata) 
3. Click import metadata from OSS console, and select the one exported from hasura cloud instance.

### Please provide any traces or logs that could help here.

```json
{
        "definition": "athena",
        "name": "data_connector_agent athena",
        "reason": "Inconsistent object: Error in Data Connector backend: Connection failure",
        "type": "data_connector_agent"
    }
```

### Keywords
metadata athena data connector

**Comment by meetzaveri** [comment]
While team releases fix for this issue, we have a workaround for this. 

In the suspected metadata (JSON), you'll find `backend_configs` object. You'll need to remove that safely from the JSON file. To do this,
1. Export metadata via export metadata button. (console -> settings -> metadata actions)
2. This will be in JSON format. Open IDE or editor to make changes to that JSON file
3. Safely remove `backend_configs` object. 
3. After doing that change, save the JSON file. 
4. Re-import that modified metadata JSON file to your console via import metadata button ( console -> settings -> metadata actions)

**Comment by rikinsk** [comment]
Fixed via https://github.com/hasura/graphql-engine/commit/3d5fb984b0fcb71dd95dda7ae6d6777ac63e21cd
