### ISSUE TITLE
Hasura Showing Error Page after createing table entity

### ISSUE THREAD

**Issue by LeulAria** [hasura/graphql-engine#9238]
### Version Information

Server Version:
CLI Version (for CLI related issue):

### How to reproduce the issue?

1.
2.
3.

### Keywords

![image](https://user-images.githubusercontent.com/45531307/203107140-195f73ba-491c-48af-85ad-159076270524.png)

**Comment by adas98012** [comment]
@LeulAria 
Can you please add the steps to reproduce this issue and the version of the Hasura Products you are using ? That will help us troubleshoot the issue.

**Comment by rikinsk** [comment]
Closed via 1ce631132a4430d8db530c5d3caff05031f00d85

**Comment by LeulAria** [comment]
Reproduced probly by
`create table` redirect to `modify tab` from that when you click on insert some times it does
