### ISSUE TITLE
Clone row in function not working - PK constrains issues

### ISSUE THREAD

**Issue by zdenoL** [hasura/graphql-engine#9248]
### Version Information

Server Version:2.15.1-2.15.2
CLI Version (for CLI related issue):

### What is the current behaviour?

 PK constrains issues - when hitting clone button, I receive PK constraints error for mentioned errors. for 2.14.1 it is OK

### How to reproduce the issue?

1.
2.
3.

**Comment by adas98012** [comment]
@zdenoL 
Would you be able to add the steps to reproduce the issue ? Also, any screenshots with the error message will also be helpful to investigate the issue.

**Comment by adas98012** [comment]
Steps to reproduce:

1. Create a table.
2. Insert a row.
3. Clone a Row (via Data -> Browse Rows)
4. Try to Save the Data.

**Comment by adas98012** [comment]
#9253 #9254

**Comment by adas98012** [comment]
@zdenoL 
 Our engineering team is looking into the issue and working on a fix to resolve it. We'll keep you posted when the fix is deployed.

**Comment by lucarestagno** [comment]
Hi @zdenoL thanks for reporting the issue 🙌

We're planning to release the fix in the next release 2.16 that's planned to be released next week.

We hope it works well for you.

**Comment by dsandip** [comment]
Fixed in https://hasura.io/changelog/community-edition/v2.16.0.
