### ISSUE TITLE
Clone row functionality sends null value for non nullable boolean fields

### ISSUE THREAD

**Issue by harishnair96** [hasura/graphql-engine#9253]
### Version Information

Server Version: 2.15.2

### Environment

OSS

### What is the current behaviour?

When clicking on clone row button, even though the expected value is shown correctly in the UI, when clicking on the 'Save' button, null value is sent to the backend for boolean fields.  This happens even if the boolean field is non nullable resulting in the error "Not-NULL violation. null value in column "is_active" violates not-null constraint"

### What is the expected behaviour?

The value shown in the UI for boolean fields must be sent to the backend as well.

### How to reproduce the issue?

1. Create a table like `CREATE TABLE person(id INTEGER PRIMARY KEY, name TEXT, is_active BOOLEAN NOT NULL);` and track it.
2. Insert some value into the table `INSERT INTO person VALUES (1, 'John Doe', true);`
3. Click on the 'Clone row' button from 'Browse Rows' tab
4. Click 'Save'
5. Observe the error "Not-NULL violation. null value in column "is_active" violates not-null constraint"

### Screenshots or Screencast

<img width="1206" alt="Screenshot 2022-11-29 at 9 46 58 PM" src="https://user-images.githubusercontent.com/20351766/204583857-12b3087d-7bd5-409d-8990-0beb84011909.png">

### Any possible solutions/workarounds you're aware of?

The issue happens because the UI sends null value to the backend. A workaround is to select a different value from the dropdown and reselect the original value. eg. If the current value is 'true' then select 'false' and reselect 'true'. Then click on the 'Save' button. 

### Keywords

clone row

**Comment by lucarestagno** [comment]
Hi @harishnair96 thanks for reporting the issue 🙌

We're planning to release the fix in the next release 2.16 that's planned to be released next week.

We hope it works well for you.

**Comment by dsandip** [comment]
https://hasura.io/changelog/community-edition/v2.16.0
