### ISSUE TITLE
Wrong relationship tracking - Could not find target columns

### ISSUE THREAD

**Issue by emrahc** [hasura/graphql-engine#9262]
### Version Information

Server Version: v2.15.1

 

### Environment

Docker on WSL

### What is the current behaviour?

 
I am having issues with hasura array relations. To simplify i have two tables.,book and Author. An author could have many books, A book could have one author. I create them via ui.

Author Table

![authortable](https://user-images.githubusercontent.com/23315417/205377873-a8733adc-b360-4043-b30e-c42e63861f44.png)

Book Table

![booktable](https://user-images.githubusercontent.com/23315417/205377825-ba632069-81e0-4a4e-9f42-85846ded65e2.png)

I added author .id to book.author_id as a foreign key

Hasura suggests me relationships to track.

![track](https://user-images.githubusercontent.com/23315417/205378429-0bc8802d-5def-4f9d-b517-70a824b553c4.png)

I click track all. 

Than odd behavior starts. Book relation points book.author_id to again book.id

![bookrelation](https://user-images.githubusercontent.com/23315417/205378532-c14c6b19-dcbd-4e1e-b685-621b38c6b4a1.png)

And that is author table relation. It says could not find target column

![authorrelation](https://user-images.githubusercontent.com/23315417/205378999-3d70891f-1409-4d7b-a62f-2bd6b12286cd.png)

### What is the expected behaviour?
 
Hasura  should have tracked right columns. It wasnt happening before. Am i doing something wrong ? Thx.

**Comment by adas98012** [comment]
@emrahc 
We are looking into this issue. We have not been able to reproduce this on our test environments yet.

**Comment by vijayprasanna13** [comment]
@emrahc Thanks for reporting the bug. @adas98012 I've been able to replicate the bug and we'll fix it in the next release.

**Comment by vijayprasanna13** [comment]
@emrahc @adas98012 This has been fixed in https://github.com/hasura/graphql-engine/commit/941179bfee6ff167f0b79cdd63c5f145a1a6615a and should available in the next release.
