### ISSUE TITLE
Downgrade from 2.15.2 to 1.3.1 - invalid argument 'downgrade'

### ISSUE THREAD

**Issue by mrocheleau** [hasura/graphql-engine#9263]
### Version Information

Server Version:  2.15.2
CLI Version (for CLI related issue):

### Environment

Kubernetes

### What is the current behaviour?

After running a test of 2.15.2, our 1.3.1 existing deployment fails to allow admin login as it's looking for metadata with v1 in it.

### What is the expected behaviour?

Expecting to be able to sign in on the existing 1.3.1 deployment as admin login

### How to reproduce the issue?

1.  1.3.1 instance online and working
2.  Spin up a second deployment to the same database using 2.15.2 container image
3.  2.15.2 deployment works and allows logins, but the 1.3.1 deployment no longer can sign in as the admin login, errors in logs referring to v1 schema

### Please provide any traces or logs that could help here.

Admin page load/signin:  

`{"type":"http-log","timestamp":"2022-12-02T20:26:08.427+0000","level":"error","detail":{"operation":{"error":{"path":"$","error":"invalid x-hasura-admin-secret/x-hasura-access-key","code":"access-denied"},"request_id":"38921cb5-80e8-41bb-b814-6998188537d9","response_size":95,"raw_query":"{\"type\":\"select\",\"args\":{\"table\":{\"name\":\"hdb_table\",\"schema\":\"hdb_catalog\"},\"columns\":[\"table_schema\"],\"where\":{\"table_schema\":\"public\"},\"limit\":1}}"},"http_info":{"status":401,"http_version":"HTTP/1.1","url":"/v1/query","ip":"127.0.0.1","method":"POST","content_encoding":null}}}`

If I tried to start a new 1.3.1 image/deployment up:

`{"type":"startup","timestamp":"2022-12-02T20:42:23.739+0000","level":"error","detail":{"kind":"catalog_migrate","info":{"path":"$","error":"Cannot use database previously used with a newer version of graphql-engine (expected a catalog version <=37, but the current version is 47).","code":"not-supported"}}}
{"path":"$","error":"Cannot use database previously used with a newer version of graphql-engine (expected a catalog version <=37, but the current version is 47).","code":"not-supported"}`

### Any possible solutions/workarounds you're aware of?

I have tried running the 2.15.2 container with a command argument of `downgrade --to-v1.3.1` but it fails saying "downgrade" is an invalid argument.  Tried running this directly inside the running pod as well, same deal, graphql-engine doesn't have a "downgrade" argument available to it.  
Basing this off of the downgrade doc at https://hasura.io/docs/latest/deployment/downgrading/

**Comment by shahidhk** [comment]
@mrocheleau Thanks for reporting this issue. We have confirmed that this is indeed a bug. 

As workaround, I suggest that you use `hasura/graphql-engine:v2.15.2-ce` image to execute the downgrade command. i.e
```
docker run hasura/graphql-engine:v2.15.2-ce graphql-engine downgrade --to-v1.3.1
```
should work.

**Comment by mrocheleau** [comment]
@shahidhk thanks for the fast response and the workaround image!
