### ISSUE TITLE
HASURA_GRAPHQL_JWT_SECRETS (plural) environment variable ignored

### ISSUE THREAD

**Issue by tallseth** [hasura/graphql-engine#9276]
### Version Information

Server Version: v2.11.1

### Environment

OSS

### What is the current behaviour?

When I set `HASURA_GRAPHQL_JWT_SECRET` (singular), with this value, I get a working JWT integration: `{"type": "RS256", "jwk_url": "my_url", "claims_format":"stringified_json"}`.

When I set `HASURA_GRAPHQL_JWT_SECRETS` (plural), using the same value enclosed in square brackets (single element array), it breaks: `[{"type": "RS256", "jwk_url": "my_url", "claims_format":"stringified_json"}]`

I get this error when trying to use it in the second case: `x-hasura-admin-secret/x-hasura-access-key required, but not found`.  

I tried putting an array in `HASURA_GRAPHQL_JWT_SECRET` (singular), and get this error: `Fatal Error:- Environment variable HASURA_GRAPHQL_JWT_SECRET: Error in $: parsing JWTConfig failed, expected Object, but encountered Array`.

I tried putting a single object in `HASURA_GRAPHQL_JWT_SECRETS` (plural), hoping to prove it was being parsed by seeing an error.  I got no error about parsing, and got the same behavior about  `x-hasura-admin-secret/x-hasura-access-key required, but not found`.

### What is the expected behaviour?

I expect it to use the jwt secret defined in `HASURA_GRAPHQL_JWT_SECRET`

### How to reproduce the issue?

1. Get a working setup with JWTs using `HASURA_GRAPHQL_JWT_SECRET` env variable.
2. Change the env variable to `HASURA_GRAPHQL_JWT_SECRETS` plural, and enclose the value in square brackets, restart

### Any possible solutions/workarounds you're aware of?

We're trying passing in the command line instead, then trying moving onto webhooks, perhaps.

### Keywords

JWT
HASURA_GRAPHQL_JWT_SECRETS

**Comment by tirumaraiselvan** [comment]
Seems like you are using `HASURA_GRAPHQL_JWT_SECRETS` on OSS. Multiple JWT secrets works only for Cloud/EE offerings.

**Comment by tallseth** [comment]
> Seems like you are using `HASURA_GRAPHQL_JWT_SECRETS` on OSS. Multiple JWT secrets works only for Cloud/EE offerings.

That would do it, @tirumaraiselvan!  And it was staring right at me in the docs.  Thank you.
![image](https://user-images.githubusercontent.com/1015373/206200450-6b290d2e-96e3-4d04-ac2f-cc7a4f4093f4.png)
