### ISSUE TITLE
Were the v2.1.0 releases impacted by the GHSA-g7mj-g7f4-hgrg vulnerability?

### ISSUE THREAD

**Issue by JONBRWN** [hasura/graphql-engine#9278]
### Version Information

Server Version: v2.1.0

CLI Version (for CLI related issue):

### Environment

Docker images

### What is the current behaviour?

All v2.1.0 images were pulled from Dockerhub but are not listed as impacted packages in the [Critical vulnerability impacting Hasura GraphQL Engine v2.10.0 and later](https://github.com/hasura/graphql-engine/security/advisories/GHSA-g7mj-g7f4-hgrg) security report. We believe these were removed today (Dec 7th).

### What is the expected behaviour?

N/A

### How to reproduce the issue?

Attempt to pull a 2.1.0 image, such as: `docker.io/hasura/graphql-engine:v2.1.0-beta.3.cli-migrations-v3`

### Any possible solutions/workarounds you're aware of?

We'll attempt to build and host on our own until we upgrade but wanted to ensure they were not removed due to the vulnerability.

### Keywords

- docker
- v2.1.0

**Comment by shahidhk** [comment]
@JONBRWN These were deleted as a mistake while taking down the impacted images. We'll be publishing these back as soon as possible.

**Comment by JONBRWN** [comment]
@shahidhk thanks for the info!

**Comment by scriptnull** [comment]
Hi, we are still working on restoring the images. But in the meanwhile, feel free to use the `v2.1.1` images. [v2.1.1](https://github.com/hasura/graphql-engine/releases/tag/v2.1.1) is a patched version of `v2.1.0` and should have good compatibility with the workload of v2.1.0.

**Comment by scriptnull** [comment]
Completed restoring `v2.1.0` images.
