### ISSUE TITLE
Migrate create ignoring second schema

### ISSUE THREAD

**Issue by sfarley85** [hasura/graphql-engine#9282]
### Version Information

Server Version:
CLI Version (for CLI related issue): 2.16.0

### Environment

Local

### What is the current behaviour?

I have 2 schemas in my postgres database, both have previously been tracked just fine by hasura.

Recently I ran into an issue where for some reason Hasura wasn't tracking my migrations. I saw a bunch of migrations that were in the database but missing from the source. Though this was perturbing for now I decided to remedy by simply resetting migrations. So I performed:

- `hasura migrate delete --all`
- `hasura migrate create "reset" --from-server`

And it creates a new up migration, but none of the tables in the second schema are represented at all, only the first schema's tables are there. 

The aforementioned work I was doing was also in the second schema, and this all worked fine before, so my current suspicion is something in a recent version of the cli broke the cli's ability to detect the a second schema. 

### What is the expected behaviour?

Migrations can be tracked from multiple schemas. 

### How to reproduce the issue?

1. Create 2 schemas
2. Make changes to both while tracking migrations
3. Attempt to pull migrations from the server for both schemas

### Keywords

schema

**Comment by adas98012** [comment]
@SamirTalwar @dameleney 
Tagging you for visibility.

**Comment by m-Bilal** [comment]
Hi @sfarley85, thank you for raising this issue
Could you please try to run the following command: `hasura migrate create "reset" --from-server --schema $schema1, $schema2`(replace `$schema1` and `$schema2` with the name of the schemas in your db) and tell us if that solves your problem. More info regarding the `--schema` flag can be found in the [official documentation](https://hasura.io/docs/latest/hasura-cli/commands/hasura_migrate_create/#options), but the gist is - by default, `hasura migrate create "$name" --from-server` only creates migrations for `public` schema, and if you want to include more schemas, you can use  the `--schema` flag.

**Comment by sfarley85** [comment]
@m-Bilal ah I see, that indeed did the trick! Using the schema arg captured both in the up. Closing, thanks for the help!
