### ISSUE TITLE
Creating async action from UI gets created as a synchronous action

### ISSUE THREAD

**Issue by harishnair96** [hasura/graphql-engine#9286]
### Version Information

Server Version: 2.16.0 (and many previous versions)

### Environment

Any

### What is the current behaviour?

Upon creating an **asynchronous** action from the UI, it gets created as a **synchronous** action.

### What is the expected behaviour?

Creating an **asynchronous** action should create it as an **asynchronous** action.

### How to reproduce the issue?

1. Go to Actions
2. Click 'Create'
3. In the 'Execution' section, check the 'Asynchronous' radio button
4. Click on 'Create Action'

### Screenshots or Screencast

https://user-images.githubusercontent.com/20351766/206971143-0631a6e2-c6a2-493f-9745-21f57582ff60.mov

### Any possible solutions/workarounds you're aware of?

The issue is with the frontend sending the wrong value to the backend during the creation of the action. Modifying the action again by going to 'ACTIONS' -> <action name> -> 'Modify' and marking it as asynchronous and clicking on 'Save Action' works.

### Keywords

async action

**Comment by rikinsk** [comment]
closed via https://github.com/hasura/graphql-engine/commit/5726ef56fee8f4b5cc981dd974ec9aac5102364f
