### ISSUE TITLE
show relationships in console UI

### ISSUE THREAD

**Issue by eads** [hasura/graphql-engine#929]
I'm building a rather elaborate set of relationships. It would be awesome if I could see them all in one place in the Hasura console UI.

**Comment by eads** [comment]
My inclination would be option 1 for a core Hasura console feature. Graphql-voyager is cool! But feels somewhat secondary to the basic task of remembering what I just named a relationship :)

**Comment by mnlbox** [comment]
related: #1731

**Comment by manasag** [comment]
We are closing this issue, as the new Hasura V3 Console provides a new Model Explorer view which lets you view all your related models as an ER diagram. I have attached how it looks in V3 for the reference. Please follow the [guide](https://hasura.io/docs/3.0/getting-started/overview/) here for Alpha access to Hasura V3.

<img width="1405" alt="image" src="https://github.com/hasura/graphql-engine/assets/5352361/a239a07e-6b91-4aff-b8d4-37b2c698e0f9">
