### ISSUE TITLE
Hasura on heroku crashes after heroku removes unused database

### ISSUE THREAD

**Issue by reubenjh** [hasura/graphql-engine#9294]
### Environment

Hasura engine v 2.5.1
Heroku paid dyno
Railway database

### Description

Hasura has irreparably crashed, returning a 503 from any http request (the console, the graphql api, even running metadata and migrations against it from the CLI). Here's what happened

- I saw the warning that Heroku are removing their databases on the free tier awhile ago, and migrated my app to a paid dyno and a railway postgres database. 
- I left the old postgres database sitting in Heroku to be deleted by them
- They deleted the attached database (see screenshot below)
- Even though my hasura engine instance doesn't use it, it crashed the dyno
- On inspecting the logs, I see consistent 503's (see screenshot)
- I triggered a restart via `heroku restart` and see this log 
```
"level":"error","detail":{"kind":"catalog_migrate","info":{"internal":"could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?\n","path":"$","error":"connection error","code":"postgres-error"
```

It sounds like the graphql engine docker image is hardcoded to care about the heroku database that was connected when i originally deployed it via the hasura 1 click deployment guide. Any ideas how to deal with this? I have tried connecting to the hasura dyno but just get a 503... so i dont know how to actually view the files on the fs and find the issue in the docker definition.

Any clues or help would be greatly appreciated, this is a production app with ~1000 users so it's a bit of a disaster unfortunately.

### Screenshots

<img width="577" alt="Screen Shot 2022-12-13 at 10 15 22 PM" src="https://user-images.githubusercontent.com/30964768/207276654-3a2e99fc-a9c0-42ee-8740-ed7d205872ea.png">

<img width="1379" alt="Screen Shot 2022-12-13 at 10 17 28 PM" src="https://user-images.githubusercontent.com/30964768/207277123-f2744a22-2f38-4dd6-be5b-5b74abe41513.png">

<img width="1396" alt="Screen Shot 2022-12-13 at 10 21 08 PM" src="https://user-images.githubusercontent.com/30964768/207277983-c3512444-413d-49c6-a492-25b64dfec792.png">

**Comment by soorajshankar** [comment]
I can think of a scenario where you might have added new database as a `datasource`, and this way Hasura would still have been using Heroku DB for Hasura metadata configuration - which is essential for Hasura to bootup. 

Could you check the heroku app env vars and make sure you have a valid `HASURA_GRAPHQL_METADATA_DATABASE_URL`? 
[Read more ](https://hasura.io/docs/latest/deployment/graphql-engine-flags/config-examples/#add-metadata-database)

**Comment by reubenjh** [comment]
Thank you for the quick reply @soorajshankar , that's interesting, i don't have (and pretty sure i've never had) a HASURA_GRAPHQL_METADATA_DATABASE_URL env var, should I set this and point it to my new postgres database or is it too late if the metadata had been stored in the database that was deleted by heroku?

**Comment by reubenjh** [comment]
> should I set this and point it to my new postgres database or is it too late if the metadata had been stored in the database that was deleted by heroku?

Tried this and no luck, same crash logs after restarting the dyno with the new env var

**Comment by reubenjh** [comment]
I can see there's often logs like this in other people's issues `2020-03-09 19:56:50.497 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"`, and noticed the `/var/run/postgresql/.s.PGSQL.5432` is familiar to my error where that unix socket cant connect to a server. 

How does one actually interact with the files running on a heroku dyno? If i could just explore there I'm sure i could grep the problem, but `heroku ps:exec` (which seems to be the only way to ssh into it as far as I can see) just throws an error because the dyno has crashed

**Comment by soorajshankar** [comment]
> Thank you for the quick reply @soorajshankar , that's interesting, i don't have (and pretty sure i've never had) a HASURA_GRAPHQL_METADATA_DATABASE_URL env var, should I set this and point it to my new postgres database or is it too late if the metadata had been stored in the database that was deleted by heroku?

Not so sure about the recovery workflow of heroku database, but 

* if you have used Hasura CLI to manage Hasura, 
* and if you have a CLI project where you have the metadata 

you can map a new Postgres instance (or even the one that you already have) and then apply this metadata using CLI.
If everything is right, you will be able to see a schema called `hdb_catalog` as shown below 

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/8408875/207284535-e523b8c6-f1a6-4690-93f6-04f85aa65568.png">


---
Alternatively, In case if you can already see this schema on your database, you can simply pass your DB connection string as `HASURA_GRAPHQL_DATABASE_URL` or `HASURA_GRAPHQL_METADATA_DATABASE_URL` to get Hasura up without the need of CLI. 

From the error I can think of Hasura not able to reach the metadata database, AFAICT primary thing to fix would be to make sure Hasura has access to a metadata database - This could be either `HASURA_GRAPHQL_METADATA_DATABASE_URL` or `HASURA_GRAPHQL_DATABASE_URL`.

**Comment by reubenjh** [comment]
Thanks, that's helpful @soorajshankar. Unfortunately i cant interact with it via the remote CLI to explore the hdb_catalog schema since the dyno has crashed. 

I'm trying to fix hasura to have access to a metadata database, and I did manage to ssh into the dyno successfully with `heroku run bash`, but i have no idea what's going on in this filesystem. Pasted screenshot below. Does anyone know where the actual hasura files are in here? When i run grep I just get permission errors and no recognisable filenames so that hasnt helped

<img width="884" alt="Screen Shot 2022-12-13 at 11 13 11 PM" src="https://user-images.githubusercontent.com/30964768/207290937-7b230dac-7d4f-46ed-ac06-1ee2756e9e04.png">

I've no idea where the connection to that metadata database is managed in the filesystem that gets deployed. Basicallt the HASURA_GRAPHQL_METADATA_DATABASE_URL from here https://github.com/hasura/graphql-engine/blob/24a117787b877fe88944e07cbab6e529a586c7cb/install-manifests/docker-compose-https/docker-compose.yaml

Failing this, i guess I need to do a manual deployment by pulling down this repo and editing the files themselves or something?

**Comment by reubenjh** [comment]
Wow this is a perfect storm of problems... all the heroku documentation around deployment seems to have been removed as it looks like hasura is (rightfully so) ditching heroku, so there's no guide for doing a manual deploy to attempt to fix this 🤦

**Comment by reubenjh** [comment]
Fixed... for anyone else that sees this and is in the same deep water that we were, the further complication was this:
- when migrating off the heroku hobby tier database, i didn't change the `DATABASE_URL` env var, i added a new `DATABASE_[newprovider]_URL`, this was so i could connect the new database and test it out before removing the old connection
- this `DATABASE_URL` must have somehow remained set to my old heroku free tier database somehow after removing the datasource connection from the console and deleting the env var.
- that `DATABASE_URL` seems to be needed in the start script when the app restarts - see line 16 in [this file](https://github.com/hasura/graphql-engine-heroku/blob/master/Dockerfile) 
- setting the `DATABASE_URL` to my new database and restarting the dyno got it up and running again

![Screenshot 2022-12-14 at 7 06 28 AM](https://user-images.githubusercontent.com/30964768/207411139-15518576-a082-49fc-aa75-53b8355eb335.png)

**Comment by soorajshankar** [comment]
Good to know that it is fixed! 

So, the issue was that GraphQL engine was not provided with a valid `HASURA_GRAPHQL_METADATA_DATABASE_URL` database, and since Heroku provide `DATABASE_URL` as the Postgres addon database, there was a env variable mapper that translates `DATABASE_URL` -> `HASURA_GRAPHQL_METADATA_DATABASE_URL`. 

Solution can be passing a valid PostgreSQL database URL as `DATABASE_URL` and deleting Heroku Postgres addon. 

*Any databases strings provided as different env vars can only be used as datasources and not for metadata management. 
[Read more](https://hasura.io/docs/latest/deployment/graphql-engine-flags/config-examples/#add-metadata-database)
