### ISSUE TITLE
docs: Document use cases for pre update and post update checks

### ISSUE THREAD

**Issue by harishnair96** [hasura/graphql-engine#9301]
Hasura provides pre-update checks and post-update checks for authorization. This is not mentioned in the docs. It would be good to have a note on what both of these are and which one to use in which scenario along with examples.

**Comment by seanparkross** [comment]
Will do

**Comment by seanparkross** [comment]
Auth docs have recently been rewritten to include this info:
https://hasura.io/docs/latest/auth/authorization/permissions/row-level-permissions/#post-update-check-row-permissions
