### ISSUE TITLE
Hasura CLI picking up non-existing version

### ISSUE THREAD

**Issue by ZilvinasAbr** [hasura/graphql-engine#9303]
### Discussed in https://github.com/hasura/graphql-engine/discussions/9302

<div type='discussions-op-text'>

<sup>Originally posted by **ZilvinasAbr** December 14, 2022</sup>
Hi, our Hasura CLI step of Playwright github workflow is trying to run this script:
```bash
curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
```

For some reason it tries to fetch the graphql-engine version 2.16.1 from github releases, which does not yet exist:

We are blocked from building our application in Github Pull requests</div>

**Comment by povilasDadelo** [comment]
Same issue!

**Comment by rikinsk** [comment]
Hey folks. Are you still facing this issue? The v2.16.1 assets should now be published

**Comment by ZilvinasAbr** [comment]
Thanks, @rikinsk , now all works, it finds the `v2.16.1` version!
