### ISSUE TITLE
Can't override GraphQL name for field in graphql default naming 

### ISSUE THREAD

**Issue by flobaader** [hasura/graphql-engine#9306]
### Version Information

Server Version: 2.16

### Environment
OSS

### What is the current behaviour?

When the naming convention is set to default graphql, it is not possible to override a field name.

The column `access_token` is exposed via graphql as `accessToken`.

When the name is overriden in the UI, the option is ignored

<img width="863" alt="image" src="https://user-images.githubusercontent.com/16624361/207702975-9cd9af99-c06a-4426-88c0-83700074f8f9.png">

**Resulting schema**
<img width="289" alt="image" src="https://user-images.githubusercontent.com/16624361/207703105-7e4b686b-c23a-4c6b-b4fc-ddf1a143d61d.png">

### What is the expected behaviour?

If the field name is set, the option should be respected.
It should be possible to still expose certain fields with underscores in the name.

**Comment by tirumaraiselvan** [comment]
Thanks for the bug report.

**Comment by rikinsk** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/825e256523e86aa265391fc2fe6a23c0ecc421f1
