### ISSUE TITLE
Events webhook should follow the same rules as Actions werbhook

### ISSUE THREAD

**Issue by oscyp** [hasura/graphql-engine#9316]
### Describe the solution you'd like

Events webhook should allow passing env as a variable with an additional suffix as it is implemented in the actions webhook. Currently, events don't allow that.

Actions:

![obraz](https://user-images.githubusercontent.com/31035071/208200083-6e50748e-403d-48ff-bf63-c1576badd996.png)

Events:

![obraz](https://user-images.githubusercontent.com/31035071/208200251-a3acdc16-f262-4b72-9550-97ce689984f4.png)

Error:

![obraz](https://user-images.githubusercontent.com/31035071/208200712-fbdd7b32-f939-40d9-8eed-56bd9a1b425a.png)

**Comment by tirumaraiselvan** [comment]
You can already achieve this if you use "static" instead of "From env var". "From env var" expects the name of an env variable which has the whole URL.

**Comment by oscyp** [comment]
Ok, thanks. But please update that description.

**Comment by rahulagarwal13** [comment]
@oscyp  - thanks for letting know, will update that.
