### ISSUE TITLE
Undocumented Breaking Change: extra GQL params now cause validation errors

### ISSUE THREAD

**Issue by IsaacLeeWebDev** [hasura/graphql-engine#9320]
### Is your proposal related to a problem?

There's an undocumented breaking change between Hasura v1.3.4 and v2.12.1 (I don't have the time to isolate it to a smaller range right now, but I may come back and update it if I can!)

Here's the v1.3.4 behavior when you send a GraphQL request containing an operation document with an unused parameter + variable:

![image](https://user-images.githubusercontent.com/20074921/208583661-722ed7e0-8d9d-4d54-bd5d-53afe7b9cdfd.png)

Here's the v2.12.1 behavior:

![image](https://user-images.githubusercontent.com/20074921/208583677-8337496d-9658-48d2-b0fb-cdad513d5684.png)

While there's no good reason to declare more parameters than you use, I'm sure many people have implemented operations declaring too many parameters by mistake, and this will cause these operations to start failing completely.

### Describe the solution you'd like

Document this breaking change in the change log, or v2 migration guide. 

### Describe alternatives you've considered

I guess patching the behavior is possible, but that would be another breaking change to different versions, so 🤷

**Comment by meetzaveri** [comment]
Hey @IsaacLeeWebDev 

Re: the error you are seeing

As per this graphql spec - https://spec.graphql.org/June2018/#sec-All-Variables-Used , this means if you have any variable defined in operation, then that variable must be used/referenced. Otherwise, it will show you validation error.

It will throw `unexpected variables in variableValues` validation error in two cases
- variable defined by operation, but not referenced (used)
- variable defined in query variable (talking in terms of query variables section you see in GraphiQL explorer) but not referenced or defined in operation

This validation error is thrown by GraphiQL explorer which is controlled by graphiql project - https://github.com/graphql/graphiql . They throw errors based on protocols defined by graphql spec, so that's why you are seeing error upon upgrading your hasura engine version.

I hope this clears up.

**Comment by IsaacLeeWebDev** [comment]
> Hey @IsaacLeeWebDev
> 
> Re: the error you are seeing
> 
> As per this graphql spec - https://spec.graphql.org/June2018/#sec-All-Variables-Used , this means if you have any variable defined in operation, then that variable must be used/referenced. Otherwise, it will show you validation error.
> 
> It will throw `unexpected variables in variableValues` validation error in two cases
> 
> * variable defined by operation, but not referenced (used)
> * variable defined in query variable (talking in terms of query variables section you see in GraphiQL explorer) but not referenced or defined in operation
> 
> This validation error is thrown by GraphiQL explorer which is controlled by graphiql project - https://github.com/graphql/graphiql . They throw errors based on protocols defined by graphql spec, so that's why you are seeing error upon upgrading your hasura engine version (meaning in newer hasura version, there must be updated version of graphiql explorer ).
> 
> I hope this clears up.

Hey! 

Thanks for taking the time to take a look at this. It sounds like Hasura v1.3.4 is not compliant with sec-All-Variables-Used, and by making Hasura 2.x compliant, a breaking change was released. 

I know this is not due to an update to GraphiQL in the new version's Hasura Console. I actually discovered this breaking change completely outside of GraphiQL in an integration test which used a non-GraphQL HTTP client, meaning that– while this this validation error may be also thrown by newer versions of GraphiQL– I'm seeing this error thrown by hasura/graphql-engine itself.

**Comment by meetzaveri** [comment]
@tirumaraiselvan need your opinion here. 

Does this mean we should document this as breaking change for `v2.x` thereby updating this section - https://hasura.io/docs/latest/resources/upgrade-hasura-v2/#hasura-v2-behaviour-changes ?

**Comment by 0x777** [comment]
@meetzaveri Yup, this should be treated as a breaking change and documented as such.

**Comment by IsaacLeeWebDev** [comment]
Thanks for looking into this, Hasura team!

**Comment by meetzaveri** [comment]
Hey @IsaacLeeWebDev , docs is now updated with that breaking change under **"Passing extra GQL params will now throw validation error"** section

Ref - https://hasura.io/docs/latest/resources/upgrade-hasura-v2/#hasura-v2-behaviour-changes

**Comment by meetzaveri** [comment]
We can close this. Just posting a comment as an update.

**Comment by abooij** [comment]
> Hey @IsaacLeeWebDev , docs is now updated with that breaking change under **"Passing extra GQL params will now throw validation error"** section
> 
> Ref - https://hasura.io/docs/latest/resources/upgrade-hasura-v2/#hasura-v2-behaviour-changes

@meetzaveri I think the entry somehow got duplicated - I see two headings "Passing extra GQL params will now throw validation error".

**Comment by meetzaveri** [comment]
Oh, that's uncanny. Because when I checked it (post PR merge), it was having only one heading and no duplications. 

@robertjdominguez Can you assist here ?

**Comment by robertjdominguez** [comment]
Good catch @abooij and thanks for pinging me, @meetzaveri 👍 

I'll resolve this ASAP with a quick PR. Should be visible later today or midweek at the latest.

**Comment by IsaacLeeWebDev** [comment]
Thank you, Hasura team! I see the updated docs now!

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/20074921/212122108-7a645357-660b-4fce-8346-2a8006e1af51.png">

I feel good about this issue getting closed whenever the Hasura team chooses.
