### ISSUE TITLE
Event triggers section in the current implementation is managed using the name of the trigger -- change it to id

### ISSUE THREAD

**Issue by karthikvt26** [hasura/graphql-engine#933]

**Comment by wawhal** [comment]
Need the server to return trigger `id` on creation.
cc: @tirumaraiselvan

**Comment by tirumaraiselvan** [comment]
@wawhal The id will be returned with this PR https://github.com/hasura/graphql-engine/pull/1758/commits/4282b12bda94dd2299044a238a7d007bcdba83b9

**Comment by tirumaraiselvan** [comment]
`id` has been removed for good so this issue is no longer applicable.
