### ISSUE TITLE
unable to connect db with same name as a recently deleted database

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#9331]
### Version Information

Server Version: 2.16.1

### Environment

CE

### What is the current behaviour?

Deleting a database and connecting it again with the same name leads to a database already exists error. The database can only be connected after reloading metadata.

### How to reproduce the issue?

1. Connect a database on the console
2. Delete the database
3. Reconnect the database with the same name and observe the error

Note that this doesnt happen all the time but happens quite often

### Screenshots or Screencast

![Screenshot from 2022-12-23 14-51-37](https://user-images.githubusercontent.com/54616969/209309112-1064efec-0ee4-4948-b573-6af1bbecaaf9.png)

Notice there is no DB connected in the left sidebar

### Any possible solutions/workarounds you're aware of?

Relaoding the metadata fixes this.

**Comment by jflambert** [comment]
While I haven't seen this issue in particular, it reminds me of the one I logged last week, and you guys apparently already fixed

https://github.com/hasura/graphql-engine/issues/9297

**Comment by MannyNe** [comment]
Reloading the metadata as well as the database was the only way to solve this issue as far as I know. Relaunching the console also worked for me this one time. Glad reloading works, really, because without that we would've been facing a lot of issues, especially cloud users.

**Comment by rikinsk** [comment]
Fixed via 2df8589097e01a92348ea3adae9bc958db902e2d
