### ISSUE TITLE
order_by not working in REST endpoint

### ISSUE THREAD

**Issue by ravi-cogos** [hasura/graphql-engine#9350]
### Version Information

Server Version: v2.0.7
CLI Version (for CLI related issue):

### Environment
OSS

### What is the current behaviour?
I am trying to expose the graphql query as REST endpoint (GET Method).
I am able to pass where clause in the GET request body. 
But, when I try to pass order_by parameters it is giving error :
**" The variable type for the expected variable order_by was not supported. "** 

### What is the expected behaviour?
order_by clause should be accepted and data to be returned in sorted order

GraphQL Query : 

query GetAddresses($limit: Int = 20, $offset: Int = 0, $order_by: [mt_addresses_order_by!]=[{id:desc}], $where: mt_addresses_bool_exp!) {
  mt_addresses(limit: $limit, offset: $offset, order_by: $order_by, where: $where ) {
    id
    latitude
    longitude
    modern_trade_name
    modern_trade_warehouse
    org_location_id
    organisation_id
    updated_at
    updated_by
    created_by
    created_at
    address
  }
}

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/115131021/210306367-f8ef928b-329d-4f1c-9be7-baf73390f631.png)

**Comment by adas98012** [comment]
@ravi-cogos 
You are likely using a very old version of Hasura Server.  I tried "order_by" on a newer (2.16.0) version and was able to get results without issues.

Attaching a screenshot for reference

![Screen Shot 2023-01-03 at 4 47 23 PM](https://user-images.githubusercontent.com/101733366/210464705-e3f1cc81-38b6-4ff3-9558-2b4f4d46eb55.png)

Please let me know if you need any additional info.

**Comment by ravi-cogos** [comment]
@adas98012 Thankyou verymuch. I will update the Hasura version and check.
Will update you on the result.
