### ISSUE TITLE
relation "hdb_catalog.hdb_event_log_cleanups" does not exist.null

### ISSUE THREAD

**Issue by MrCox007** [hasura/graphql-engine#9362]
### Version Information

Server Version: 2.16.1
CLI Version (for CLI related issue):
2.16.1
### Environment
docker, oss 

### What is the current behaviour?

  When creating a event trigger there is created a cleanup_config which will break reset_metadata with the error 
  relation "hdb_catalog.hdb_event_log_cleanups" does not exist.null

### What is the expected behaviour?

  Resetting metadata should be reset

### How to reproduce the issue?

1. Run example from https://hasura.io/docs/latest/getting-started/docker-simple/
2. create event trigger
3. run reset metadata either from hasura cli or web console

### Any possible solutions/workarounds you're aware of?

remove cleanup_config in .yaml file

**Comment by soorajshankar** [comment]
Thanks for reporting this @MrCox007, I could reproduce the issue!

Will keep this issue updated on the investigations and fix.

**Comment by codingkarthik** [comment]
Thank you folks for reporting the issue. We are actively working on a fix for this issue. 

Meanwhile, as a workaround, you can do the following:

1. Export the metadata.
2. Remove the `cleanup_config` present in the event triggers of the `default` source.
3. Import the metadata.
4. Clear the metadata.

This is cumbersome but this should work.

**Comment by codingkarthik** [comment]
This issue has been fixed via https://github.com/hasura/graphql-engine/commit/0406cd2ef07fa3f0fadfd9c8394b725dd26112a5 and will be released soon!
