### ISSUE TITLE
Cloud and Self-hosted values for HASURA_GRAPHQL_ADMIN_SECRETS are parsed differently.

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#9363]
### Version Information

Server Version: 2.16.1

### Environment

Cloud/ OSS / EE

### What is the current behavior?

Per our [documentation](https://hasura.io/docs/latest/security/multiple-admin-secrets/#how-to-use), this is a valid value for the `HASURA_GRAPHQL_ADMIN_SECRETS` environment variable:
```json
["secret-1","secret-2"]
```

This functions as expected on self-hosted versions of hasura.
That is, this value is parsed as an array of JSON string, where both `secret-1` and `secret-2` are valid admin secrets.

However, on Hasura Cloud, the above input is parsed as a comma-separated list of strings,
so the above results in the admin secrets `["secret-1"` and `"secret-2"]`

### What is the expected behavior?

Hasura Cloud should parse environment variables in a manner consistent with the behavior of Hasura GraphQL Engine.
This would reduce confusion and requirements for separate documentation.

Additionally, differences in behavior between Hasura Cloud and Hasura GraphQL Engine should be clearly documented.

### How to reproduce the issue?

1. Create a Hasura Cloud project
2. Add the `HASURA_GRAPHQL_ADMIN_SECRETS` environment variable with this value from the [docs](https://hasura.io/docs/latest/security/multiple-admin-secrets/#how-to-use): `["secret-1","secret-2"]`
3. Test the `secret-1` admin secret from the console. It will be rejected
4. Test the `["secret-1"` admin secret. It will be successful.

**Comment by shahidhk** [comment]
Tracking internally at https://hasurahq.atlassian.net/browse/CPS-679
