### ISSUE TITLE
newline doesn't skip asking update to a new version for CLI

### ISSUE THREAD

**Issue by ochanje210** [hasura/graphql-engine#9367]
### Is your proposal related to a problem?

Skipping CLI updates by simply pressing enter or giving newline is intuitive.

However, it doesn't work here with Hasura CLI but you have to give any specific values other than `y` to skip it.

<img width="462" alt="Screenshot 2023-01-08 at 11 48 45 AM" src="https://user-images.githubusercontent.com/16204807/211215848-38e1e186-8f6e-44a8-9e2d-12a719d87aeb.png">

### Describe the solution you'd like

Can we have `fmt.Scanln` rather than `fmt.Scan` here?
https://github.com/hasura/graphql-engine/blob/master/cli/commands/update-cli.go#L147

**Comment by manasag** [comment]
Hi @ochanje210 , Thanks for raising this issue. We are currently working on improving CLI to just print out the update message and not require an action at all for the update message. I hope this will resolve your concern. I'll update once the improvement is released.

**Comment by manasag** [comment]
Hi, the change has been committed. This will make to 2.18 release planned a couple of weeks later.
