### ISSUE TITLE
Array of JSONB mutation has error while Array of JSON does not !

### ISSUE THREAD

**Issue by mostafashr** [hasura/graphql-engine#9374]
I'm attempting for days to somewhat have an update mutation that updates or inserts a field that has a type of JSONB.

What I've been trying

![127292186-136cb1cc-4a68-4eaa-8d2a-4e12b4565d78](https://user-images.githubusercontent.com/12083263/211752949-7ff80e2c-a3a0-48cf-9d4d-8a01316618cc.png)

test_field type is JSONB and when I change the type to JSON everything works flawlessly. 

if I execute the code with admin secret Hasura engine will skip double quotes in the generated SQL query and PostgreSQL says there is an invalid character \ in the query. I wrote a before trigger that removes all \ in the JSONB value and it solves the issue. it is a bug in the Hasura engine with JSONB type.

I am using Hasura version 2.16.1.

**Comment by mostafashr** [comment]
also the console get a error with this data This mutation with the following data does didn't work either if payload is jsonb . after a hasura restart it got fixed automatically:

```mutation test_request($objects: [request_insert_input!]!) {
  insert_request(objects: $objects) {
    affected_rows
    __typename
  }
}



{
  "objects": [
    {
      "action": "Reboot",
      "payload": {
        "ids": [
          "66f0e9f4-fe01-49d8-9c81-ac9a66710450",
          "bdb7c943-c712-4c44-92e2-9a48ed74515c",
          "654a4b96-2ccb-47a5-a4f8-c30c0f9c6927",
          "aa4cbc93-1d2d-490a-94cf-96055cd5bd93"
        ]
      }
    }
  ]
}```

**Comment by ejkkan** [comment]
Hey @mostafashr, does this mean that the issue resolved for you after the restart? 
I can't reproduce this behaviour.

**Comment by ejkkan** [comment]
Great! We'll continue to have this under issue in mind if anything like it would be brought up again. 
Thanks for raising the the ticket.
