### ISSUE TITLE
CLI console 2.17.0-beta.1 doesn't load in Firefox

### ISSUE THREAD

**Issue by haf** [hasura/graphql-engine#9378]
I simply can't start the console.

1. `hasura update-cli --version v2.17.0-beta.1`
2. `hasura console`
3. Hasura with config `HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets`
4. See below:
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/193115/212357638-90bbd8c4-4048-4660-a3f0-c4caa8d9e548.png">

**Comment by rikinsk** [comment]
Hey. I wasn't able to reproduce this issue. Are you still facing this?

**Comment by haf** [comment]
This happened three days ago, what changed? Have you published a new version I can test?

**Comment by rikinsk** [comment]
We had made a hotfix for the console assets but that should not impact you as you are using the local assets, but I just wanted to confirm just in case.
That being said, I haven't been able to reproduce this. You mentioned "in Firefox" in the title, so is this working fine in other browsers? if yes could you share the Firefox version for a more accurate attempt at reproduction

**Comment by haf** [comment]
No it doesn't work in Chrome either.

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/193115/212941362-3da9ea50-48ce-4aca-bd67-da39b40820f4.png">

**Comment by haf** [comment]
Like you can see, it loads from :8080 with the new version. But the server has console turned off.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/193115/212941657-cdf9bc5b-273a-4c38-bd85-d6c05122a43b.png">

**Comment by haf** [comment]
So this bug is finally fixed https://github.com/hasura/graphql-engine/issues/8482

**Comment by haf** [comment]
Then the solution to this issue is to enable the console on the Hasura container.

And another feature request might be created:

> Let the CLI Hasura Console bundle the assets itself.

How desirable this is I'm not sure of. I'll enable the console locally on the container though.

**Comment by haf** [comment]
@rikinsk Could you briefly comment on the above investigation of mine? Thank you :)

**Comment by rikinsk** [comment]
> Like you can see, it loads from :8080 with the new version. But the server has console turned off.
   Let the CLI Hasura Console bundle the assets itself.

aah interesting. i think that is a fair ask. or alternatively the server could disable the console but still serve the assets. could you raise another issue with this feature request? and thank you for your investigation :)
