### ISSUE TITLE
hasura console (cli) doesn't reach `undefined` when setting up websocket connection with new v2.17

### ISSUE THREAD

**Issue by haf** [hasura/graphql-engine#9388]
### Version Information

cc @rikinsk 

Server Version: 2.17
CLI Version (for CLI related issue): 2.17, 2.17-beta.1

### Environment

docker file at 2.17.0

### What is the expected behaviour?

to connect

### How to reproduce the issue?

1. start hasura with the version released yesterday
2. start `hasura console` with the latest CLI released yesterday
3. observe

### Screenshots or Screencast

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/193115/213432289-b958ee1b-148b-4429-a702-443d98e0f54e.png">

**Comment by haf** [comment]
With server 2.16, console 2.17 works, but has what seems to be serious errors logged:

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/193115/213433532-4ac0e898-7917-49d3-8ba8-736c7b9c72eb.png">

**Comment by rikinsk** [comment]
The error regarding `https://data.undefined/v1/graphql` has been fixed and the console assets have been updated on the CDN. Note that this does not cause the console to not load, it's just errors happening in the background. 

The issue regarding CLI console not loading in case local console assets are being used and the server console is disabled is also fixed and will be released with v2.18

**Comment by osdiab** [comment]
I'm getting this issue starting through midway today - might it have regressed?

**Comment by willtonkin** [comment]
- With `hasura-cli@^2.20.1`
- attempting to connect to Docker image `hasura/graphql-engine:v2.20.1.ubuntu`
- Docker container's endpoint expressed at localhost port `8765`, hence `endpoint` value in `config.yaml` below.
- I'm able to connect to the console at http://localhost:8765 and the GQL api at that port

I'm encountering a similar issue:

where the console is attempting to connect to `http://undefined/v1/graphql`

![image](https://user-images.githubusercontent.com/1245553/228317810-67b22c15-3c49-44ab-92c4-86e5be66a07e.png)

I am running the console via `npx hasura --project hasura console` and with a config file at `hasura/config.yaml`:
```yaml
version: 3
endpoint: http://localhost:8765
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
```
