### ISSUE TITLE
Not able to export data for a table on Hasura Cloud v2.18.0 

### ISSUE THREAD

**Issue by Who828** [hasura/graphql-engine#9424]
### Version Information

Server Version: 2.18.0-cloud-1

### What is the current behaviour?
No-op on when clicking export data for a table

### What is the expected behaviour?
Export of the table data.

### How to reproduce the issue?

1. Go to Hasura Cloud Console
2. Go to a table tab
3. Click on export button

### Screenshots or Screencast

https://user-images.githubusercontent.com/1170770/217593648-6e610036-b2d7-43c5-bc9a-6932e7f7313b.mp4

**Comment by ajohnson1200** [comment]
I was able to mostly reproduce this in 2.17 as well, in my 2.17 instance I can see a button _slightly_ below the Export button after clicking "Export data":

![Screen Shot 2023-02-08 at 4 21 45 PM](https://user-images.githubusercontent.com/683294/217682057-439b255c-d696-4a9b-8c8a-409a276c2c7e.png)

We have this filed internally and will work to get a fix ASAP.

**Comment by lucarestagno** [comment]
@Who828 this issue is currently fixed on the latest cloud version of the Console `2.18.0-cloud.1`.

Thanks for reporting this bug! 🙌
