### ISSUE TITLE
Using SQLServer / MSSQL with a Root Namespace causes rows / records to not render

### ISSUE THREAD

**Issue by kevinmichaelchen** [hasura/graphql-engine#9425]
### Version Information

Server Version: v2.17.1
CLI Version (for CLI related issue): v2.17.1

### Environment

EE — since we're using a `HASURA_GRAPHQL_PRO_KEY` env var

### What is the current behaviour?

Using a SQL Server (the `mcr.microsoft.com/mssql/server:2017-latest` Docker image) with a root namespace causes the Console UI to not render any rows under the "Browse" table tab. Records do show up if you remove the root namespace.

### What is the expected behaviour?

SQL Server records should render in the Browse tab when using a root namespace on the DB connection.

### How to reproduce the issue?

1. Connect Hasura to SQL Server, using a root namespace
2. Insert some data into a table
3. Browse the table in the Console UI

**Comment by vijayprasanna13** [comment]
@kevinmichaelchen @deinspanjer we've just merged the work for this into `main` https://github.com/hasura/graphql-engine/commit/38b3c5258db0c5ca5649b2b8516fbd3145adfa0a, it should be available in the next release
