### ISSUE TITLE
Cloud: TypeError: Cannot read properties of undefined (reading 'lds-spinner')

### ISSUE THREAD

**Issue by josephsiefers** [hasura/graphql-engine#9428]
### Version Information

Server Version: v2.18.0-cloud.1
CLI Version (for CLI related issue): N/A

### Environment
Cloud

### What is the current behaviour?
When trying to select a filter in the Operations section of the Monitoring tab, I see the Hasura Error page "TypeError: Cannot read properties of undefined (reading 'lds-spinner')" and as a result, I am unable to change filter criteria.

### What is the expected behaviour?
Filter section appears and I am able to select criteria.

### How to reproduce the issue?

1. Visit Monitoring -> Operations
2. Click the 'Filters (number)' button
3. Error page appears

Note that this issue does not happen in my other cloud instance which is running 2.17.1, so it appears to be only with 2.18.0.

### Screenshots or Screencast
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/1895065/217676807-c19c279a-64ea-40aa-9da6-f54dccfa4a8b.png">

<img width="946" alt="image" src="https://user-images.githubusercontent.com/1895065/217676688-5ea80566-312d-44f5-b033-779422fac9bb.png">

### Please provide any traces or logs that could help here.
N/A

### Any possible solutions/workarounds you're aware of?
N/A

### Keywords
lds-spinner

**Comment by ajohnson1200** [comment]
Thanks for this report, I can reproduce, we're looking to fix ASAP.
