### ISSUE TITLE
graphql-default naming convention introduces underscores somewhere between v2.10.2 and v2.18.0

### ISSUE THREAD

**Issue by AxelUlmestig** [hasura/graphql-engine#9430]
### Version Information

MacOS:
```
$ echo $OSTYPE
darwin21.0
```

Server Version:
`hasura/graphql-engine:v2.18.0.cli-migrations-v3` Docker image

CLI Version (for CLI related issue):
`hasura/graphql-engine:v2.18.0.cli-migrations-v3` Docker image

### Environment

run on local machine in Docker

### What is the current behaviour?

Settings the environment variables
```
HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: naming_convention
HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: graphql-default
```
with the `v2.18.0.cli-migrations-v3` image and then exporting the schema to a file using `gq`
```sh
gq http://127.0.0.1:8080/v1/graphql -H 'x-hasura-admin-secret: admin' --introspect > schema.graphql
```

Then the order by aggregate types are written in snake_case:
```gql
input FriendsAggregateOrderBy {
  ...
  max: friends_max_order_by
}
```

### What is the expected behaviour?

When the same is done with the `v2.10.2.cli-migrations-v2` image, then the result is in PascalCase:

```gql
input FriendsAggregateOrderBy {
   ...
   max: FriendsMaxOrderBy
}
```

I expected it to stay as PascalCase when I upgraded the image.

### How to reproduce the issue?

I have created [a repo with a script that reproduces the error](https://github.com/AxelUlmestig/hasura-naming-convention-demo)

I recommend using the script in the repo, but you can run it manually too:

- Make sure that `gq` is installed (`npm install -g graphqurl`).
- Set up a Hasura environment where there's an array relationship present
- Start the containers: `docker-compose up -d`
- Apply database migrations: `docker compose exec db sqitch --chdir db deploy`
- Apply Hasura metadata: `docker compose exec graphql-engine hasura-cli --project /hasura-config metadata apply`
- Export the graphql schema: `gq http://127.0.0.1:8080/v1/graphql -H 'x-hasura-admin-secret: admin' --introspect > schema.graphql`
- Verify that nothing has changed: `git diff schema.graphql`
- Update the hasura version:
  ```
  hasura_v210='hasura/graphql-engine:v2.10.2.cli-migrations-v2'
  hasura_v218='hasura/graphql-engine:v2.18.0.cli-migrations-v3'
  
  sed -i '' "s#$hasura_v210#$hasura_v218#g" docker-compose.yaml
  ```
- Restart the containers with to get the new version: `docker compose down; docker compose up -d`
- Export the schema again: `gq http://127.0.0.1:8080/v1/graphql -H 'x-hasura-admin-secret: admin' --introspect > schema.graphql`
- Check the diff: `git diff schema.graphql`

### Keywords

- casing
- naming_convention
- graphql-default

**Comment by manasag** [comment]
Hi folks, we are acknowledging this issue and this is currently being fixed.

**Comment by paritosh-08** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/96549b272b07d5fdb82207829104ae626f4c6cb3

**Comment by nickesk** [comment]
FYI, this ended up being a breaking change for us on Cloud, as we were relying on this "bug" for our API. This should have been released under a flag IMO, and we need a way to roll back on Cloud.
