### ISSUE TITLE
Bigquery aggregate queries fail when __typename is included

### ISSUE THREAD

**Issue by morganne-acuity** [hasura/graphql-engine#9437]
### Version Information

Server Version:
CLI Version (for CLI related issue): 2.12.1

### What is the current behaviour?

Query building fails when using an aggregation and __typename for bigquery queries.  __typename is added by default by Apollo client for caching purposes.  I believe this is a similar error to this mssql issue: https://github.com/hasura/graphql-engine/issues/7130 which was fixed.

### What is the expected behaviour?

Query should be built and run if `__typename` is included

### How to reproduce the issue?

1. Run an bigquery aggregate query
2. Add `__typename` as one of the fields

### Screenshots or Screencast

**Without __typename**
![Screen Shot 2023-02-15 at 12 53 06 PM](https://user-images.githubusercontent.com/114701728/219113013-b846a07a-c735-4614-b6f8-319f37cab6c1.png)

**With __typename**
![Screen Shot 2023-02-15 at 12 53 23 PM](https://user-images.githubusercontent.com/114701728/219113015-ad1d7323-e68b-4e39-908f-059205fb86b9.png)

### Please provide any traces or logs that could help here.

Here is the error message:
```
{
  "errors": [
    {
      "extensions": {
        "code": "unexpected",
        "internal": {
          "rest_request_non_ok": {
            "error": {
              "code": 400,
              "errors": [
                {
                  "domain": "global",
                  "location": "q",
                  "locationType": "parameter",
                  "message": "No matching signature for aggregate function SUM for argument types: STRING. Supported signatures: SUM(INT64); SUM(FLOAT64); SUM(NUMERIC); SUM(BIGNUMERIC); SUM(INTERVAL) at [2:71]",
                  "reason": "invalidQuery"
                }
              ],
              "message": "No matching signature for aggregate function SUM for argument types: STRING. Supported signatures: SUM(INT64); SUM(FLOAT64); SUM(NUMERIC); SUM(BIGNUMERIC); SUM(INTERVAL) at [2:71]",
              "status": "INVALID_ARGUMENT"
            }
          }
        },
        "path": "$"
      },
      "message": "BigQuery HTTP request failed with status 400 \"Bad Request\""
    }
  ]
}
```

**Comment by i-am-tom** [comment]
Hey! Thanks for reporting this - it should be fixed in the next release :)
