### ISSUE TITLE
Export Data hidden behind datatable

### ISSUE THREAD

**Issue by gusfune** [hasura/graphql-engine#9439]
### Version Information

Server Version:
CLI Version (for CLI related issue): 2.19.0

### Environment

OSS

### What is the current behaviour?

When clicking "Export data" the select menu is opened behind the data table below.

### What is the expected behaviour?

The select menu should be opening on top of the export data.

### How to reproduce the issue?

1 .Open Hasura Console
2. Go to Data
3. Open any table and click export data

### Screenshots or Screencast

How it shows:
<img width="411" alt="Screenshot 2023-02-16 at 12 13 53" src="https://user-images.githubusercontent.com/1147240/219362057-6a5fc023-be1f-43e4-9b93-491390298585.png">

Expected behaviour:
<img width="322" alt="Screenshot 2023-02-16 at 12 13 17" src="https://user-images.githubusercontent.com/1147240/219362134-761670cc-fbc2-4440-9f18-d2a51973a4f6.png">

### Please provide any traces or logs that could help here.

N/A

### Any possible solutions/workarounds you're aware of?

Need to change a few elements to add `position: relative` and add proper `z-index` to allow proper juxtaposition of items.

### Keywords

front-end, console, menu

**Comment by adas98012** [comment]
@manasag 
This is reproducible on 2.19.0

**Comment by gusfune** [comment]
I can confirm it's fixed in the 2.19 console @adas98012 - my bad, I had updated Hasura but not the CLI.
