### ISSUE TITLE
Curl example in docs to set metadata does not work

### ISSUE THREAD

**Issue by markpradhan** [hasura/graphql-engine#9443]
### Version Information

Server Version: v2.14.1
CLI Version (for CLI related issue):

### Environment

OSS 

### What is the current behaviour?

Curl example to set metadata errors out

### What is the expected behaviour?

Curl example should set metadata

### How to reproduce the issue?

`curl -d'{"type":"replace_metadata", "args":'$(cat hasura_metadata.json)'}' http://localhost:8080/v1/metadata`

**Comment by meetzaveri** [comment]
I was able to replicate on my end. Docs reference - https://hasura.io/docs/latest/migrations-metadata-seeds/manage-metadata/#apply-metadata

**Comment by robertjdominguez** [comment]
@meetzaveri, can you confirm this change (adding a `version` key-value pair) in the request resolves this? If so, I'll update the docs page 👍 

`curl -d'{"type":"replace_metadata", "version":< 1 || 2 > "args":'$(cat hasura_metadata.json)'}' http://localhost:8080/v1/metadata`

**Comment by meetzaveri** [comment]
Hey @robertjdominguez 

I tried what you suggested(by adding `version` key-value pair) but it's still throwing me the same error.

**Comment by robertjdominguez** [comment]
@markpradhan, thanks for raising this issue and helping us to ensure our docs are up-to-date.

Can you please share the error returned when running `curl -d'{"type":"replace_metadata", "args":'$(cat hasura_metadata.json)'}' http://localhost:8080/v1/metadata`?

And, did you first export the metadata? If not, you can run the following first to generate the `hasura_metadata.json` file and then run the original `replace_metadata` command:

```shell
curl -d'{"type": "export_metadata", "args": {}}' http://localhost:8080/v1/metadata -o hasura_metadata.json
```

Please let us know if this helps, or please share the error message 👍

**Comment by markpradhan** [comment]
@robertjdominguez

I exported metadata from the ui itself. Don't really have much time rn to do the testing... 
I just manually imported metadata without any issues (through UI).

But if you guys are stuck ping me again, i'll make some effort.

**Comment by robertjdominguez** [comment]
@markpradhan, I ran a few local tests with `2.14.1`, the version you referenced in the issue, and `2.19.0`. Both times, the curl request of `"type": "replace_metadata"` succeeded after running a curl request of `"type": "export_metadata"`.

If it's not possible for you to share the error message, I'll close this issue in the next few days.

**Comment by markpradhan** [comment]
@robertjdominguez 

```
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) unmatched brace in URL position 1:
{
```

**Comment by robertjdominguez** [comment]
This is very helpful, @markpradhan; thank you 👍 

When exporting from the Console, the shape of the JSON is different from that of the API. Below, you'll see a very simple example of what was exported when reproducing your error using `2.14.1`:

```json
{
  "resource_version": 2,
  "metadata": {
    "version": 2,
    "sources": []
  }
}
```

Whereas what's produced when executing the curl request for the `export_metadata` type:

```json
{
    "version": 2,
    "sources": []
  }
```

As the key-value pairs differ, the curl request, using `cat` to read the contents of the JSON file, doesn't produce the results you would expect. The request attempts to send along the `resource_version` key-value pair in addition to the `metadata` object.

Instead, you can make a request using the following one-liner to parse the JSON exported by the Console and isolate the `metadata` key-value pair:

```bash
curl -d '{"type" : "replace_metadata", "version": 2, "args": {"metadata": '$(jq -c '.metadata' <METADATA_FILENAME>.json)'}}' http://localhost:8080/v1/metadata
```

In this request, we're using `jq` to parse the JSON data and the `-c` flag to output the result to a single-line string, which is then inserted as the value of the `metadata` key in the request's payload.

This request returns the following - [expected - response](https://hasura.io/docs/latest/api-reference/metadata-api/manage-metadata/#responses):

```json
{"inconsistent_objects":[],"is_consistent":true}                                                                                                     
```

Please let us know if this helps resolve your issue 👍
