### ISSUE TITLE
Cron Triggers do not display year in dates

### ISSUE THREAD

**Issue by fantastiskm** [hasura/graphql-engine#9452]
### Version Information

Server Version:
CLI Version (for CLI related issue): 2.9.0

### Environment

OSS

### What is the current behaviour?

Under Events > Cron Triggers.

Logs are not displaying the year in any of the date fields Eg: "Mon, Feb 22nd 04:00:00 +01:00"

### What is the expected behaviour?

All dates should include the year Eg: "Mon, Feb 22nd 2021 04:00:00 +01:00"

### How to reproduce the issue?

1. Log in to console
2. Click on Events in top menu
3. Click on Cron Triggers in left side bar
4. Select a cron trigger that has run a few times (you may need to create one first)
5. Click on 'pending events', 'processed events' or 'invocation logs'
6. observe that none of the times include the year

### Screenshots or Screencast

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/93585768/220381997-fdceee24-b4be-41f9-bfc3-61c422a31284.png">

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/93585768/220381857-f907fd82-832d-4502-96ad-7021f5ee372d.png">

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/93585768/220381936-7782687c-9f75-418f-ae7e-ea5f50faf46e.png">

### Any possible solutions/workarounds you're aware of?

Look up the date in a calendar and see what year matches the day of month combination. Not reliable

### Keywords

cron date display year

**Comment by soorajshankar** [comment]
Hey @fantastiskm, 

Thanks for opening the issue, we have a fix and the code is merged. This fix will be available from `v2.21` - closing the issue in this regard.
