### ISSUE TITLE
Monitoring: Usage, Errors, Operations filter not interactive

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#9459]
### Version Information

Server Version: v2.19.0-cloud.1

### What is the current behaviour?

Under the Monitoring tab, the Usage, Errors, and Operations panels allow users to set filters.

However the form for said filters seem to not be interactive.

Clicking on "remove all filters" has no effect, and the same goes for clicking on any of the dropdowns

### What is the expected behaviour?

Form should be interactive.

### How to reproduce the issue?

1. Create hasura cloud project 
2. Navigate to monitoring tab in console
3. Navigate to operations panel and attempt to edit filter
4. Filter cannot be modified

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/25712958/220724254-22c4772a-8c18-4dab-a5f8-0c8e41978459.png)

**Comment by manasag** [comment]
There have been some regressions in the monitoring tab that are being fixed currently. The fix should be deployed soon.

**Comment by troyamelotte** [comment]
@manasag Any updates on this or work arounds? This feature is critical for us.

**Comment by manasag** [comment]
Hi @troyamelotte, the dropdown and filter related issues have been fixed in v2.20 (Cloud projects are already patched). There's an additional issue found related to time range picker widget that is currently being worked upon. Will provide an update soon on the same.
