### ISSUE TITLE
[docs]: update apollo-subscriptions.mdx to use graphql-ws instead of apollo-link-ws

### ISSUE THREAD

**Issue by andoks** [hasura/graphql-engine#9465]
### Version Information

Server Version: N/A
CLI Version (for CLI related issue): N/A

### Environment

OSS

### What is the current behaviour?

Currently the documentation at https://www.apollographql.com/docs/react/api/link/apollo-link-subscriptions/ describes how to use apollo-client with with apollo-link-ws, but apollo-link-ws is deprecated in favor of graphql-ws (which has been supported in hasura for a while: https://github.com/hasura/graphql-engine/issues/6264), but the documentation has not been updated to reflect this.

Two things in particular would be useful to document: How to provide the JWT token and how to set the X-Hasura-Admin-Secret in the way that Hasura expects it.

### What is the expected behaviour?

That https://hasura.io/docs/latest/subscriptions/integrations/apollo-subscriptions/ (https://github.com/hasura/graphql-engine/blob/master/docs/docs/subscriptions/integrations/apollo-subscriptions.mdx) describes how to configure apollo-client with graphql-ws, and how to provide any tokens and secrets

### How to reproduce the issue?

N/A

### Screenshots or Screencast

N/A

### Any possible solutions/workarounds you're aware of?

From https://github.com/hasura/nodejs-graphql-subscriptions-boilerplate/issues/3#issuecomment-1307690161 I spied that maybe making connectionParams return a headers object would work for setting the X-Hasura-Admin-Secret, and it seems to work
```
const wsLink = new GraphQLWsLink(
        createClient({
            url: GRAPHQL_API_WS,
            shouldRetry: () => true,
            connectionParams: () => ({
                headers: {
                    "X-Hasura-Admin-Secret": "MY_SECRET_TOKEN",
                },
            }),
        })
    );
```

**Comment by seanparkross** [comment]
An update for this page was merged recently and will be deployed soon.
