### ISSUE TITLE
Console no longer highlights errors in the GraphQL query

### ISSUE THREAD

**Issue by harishnair96** [hasura/graphql-engine#9470]
### Version Information

Server Version: v2.18.0 to v2.20.0-beta.1

### Environment

Any

### What is the current behaviour?

<img width="623" alt="Screenshot 2023-02-27 at 2 17 39 PM" src="https://user-images.githubusercontent.com/20351766/221516312-309e8754-8e42-42cc-afb4-1368f5359569.png">

### What is the expected behaviour?

<img width="623" alt="Screenshot 2023-02-27 at 2 20 00 PM" src="https://user-images.githubusercontent.com/20351766/221516826-48f78990-7935-4cf1-a85a-fd2d18209840.png">

### How to reproduce the issue?

1. Create a table like `CREATE TABLE person(id SERIAL PRIMARY KEY, name TEXT);`
2. Enter the following query in GraphiQL
    ```graphql
    query GetPeople($limit: Text = 10) {
      person(limit: $limit) {
        id
        name
        some_field_that_does_not_exist
      }
    }
    ```

### Keywords

error highlighting, graphiql

**Comment by mikejackowski** [comment]
following 👀

**Comment by manasag** [comment]
Checking up on this.

**Comment by manasag** [comment]
We are in the process of fixing this.

**Comment by rikinsk** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/fc4aec4330e42330bf0178f6da59504ef974df96

**Comment by mikejackowski** [comment]
this issue is still happening in hasura cloud (v2.19.0-cloud.1)
