### ISSUE TITLE
Subscription not working in console running locally

### ISSUE THREAD

**Issue by marcosfons** [hasura/graphql-engine#9475]
### Version Information

CLI Version: Currently using `v2.19.0`

### What is the current behaviour?

Subscriptions does not work in the API Explorer when running the console locally connected to an external Hasura instance that only support `HTTPS`/`WSS`. Query and mutations works without problems (uses `HTTPS`). But, the subscriptions does not work because they are trying to use `WS` instead of `WSS`.

### What is the expected behaviour?

Subscriptions works in the API Explorer when running the console locally connected to an external Hasura instance that does not support `HTTP`/`WS`.

### How to reproduce the issue?

1. Create the configuration files to connect to an external Hasura instance: `hasura init --endpoint "https://your-hasura-domain"`
2. Launch the Hasura console: `hasura console`
3. Create and track tables to use for subscriptions
4. Go to the API Explorer tab and create some valid subscription
5. Open the Network tab of the browser developer tools
6. Filter the url by the websocket scheme: `ws`
7. Run the subscription
8. Wait until you see some request in the network tab using `ws` instead of `wss`

### Screenshots or Screencast

The next image show in the left panel that I'm using `HTTPS`, but in the right side in the network tab it's trying to connect using `WS` instead of `WSS`.  (The image was edited just to remove the hasura instance domain).

![hasura_issue_screenshot](https://user-images.githubusercontent.com/22989734/222032504-a60b38e8-e991-41b8-93ec-cebafa1c26c7.jpg)

### Any possible solutions/workarounds you're aware of?

I searched the codebase and found a [commit](https://github.com/hasura/graphql-engine/commit/37a15c25e84db448ef7a1e010923bb623a903817) that probably introduced this "unexpected" behavior. In the code section below the url used to make the connection for the subscription executes the `getWebsocketProtocol` function using the `window.location.protocol`.

https://github.com/hasura/graphql-engine/blob/37a15c25e84db448ef7a1e010923bb623a903817/console/src/components/Services/ApiExplorer/Actions.js#L181

But when running the console locally connected to an external Hasura instance `window.location` points to `http://localhost`, with the `HTTP` protocol (that after is transformed to `WS`). And instead, it should use the GraphQL Endpoint of the external instance that uses `HTTPS`.

### Keywords

WSS, WS, websocket, subscription

**Comment by rikinsk** [comment]
Thanks for the report. Looking into this

**Comment by rikinsk** [comment]
Fixed via https://github.com/hasura/graphql-engine/commit/29b5aee03a63c89378858f1a077bc2f96f6367b8
