### ISSUE TITLE
Support for pgvector

### ISSUE THREAD

**Issue by KTruong008** [hasura/graphql-engine#9478]
### Is your proposal related to a problem?

I'd like to store and utilize OpenAI's text embeddings within a Postgres DB managed by Hasura so I can leverage vector similarity search.

### Describe the solution you'd like

Not sure, but maybe an "Extensions" tab within the Admin UI that allows for adding/removing extensions like pgvector, and support for pgvector's `vector` datatype.

### Describe alternatives you've considered

Using Supabase (just added support for pgvector last month)

https://supabase.com/blog/openai-embeddings-postgres-vector

**Comment by adas98012** [comment]
@KTruong008 
Have you tried using the SQL interface (accessed via Data tab) in Hasura Console ? You can run any sql command through this interface, which includes adding extensions.

**Comment by KTruong008** [comment]
Wasn't aware I could add extensions through there too, but I'll give it a shot!

**Comment by ajayar** [comment]
can we also do a similarity search?
