### ISSUE TITLE
Hasura fails to load Alloydb Schema when there are a large amount of partitions

### ISSUE THREAD

**Issue by IS-Josh** [hasura/graphql-engine#9487]
We're using AlloyDb  (Postgres 14),  When we switched to partitioning our tables, the query the console issues. to get metadata, takes about 3 minutes which causes a timeout on Hasura's end and causes unable to retrieve schema error.    The introduction of partitions appears to make the metadata query run much slower.  We were using V1.3.2 We're now on 2.19.0 and we still have the same issue.

This makes configuring permissions and managing the data permissions impossible,

**Comment by IS-Josh** [comment]
<img width="509" alt="Screenshot 2023-03-11 at 4 54 35 pm" src="https://user-images.githubusercontent.com/48971328/224467691-bd2306a5-ca11-4c35-bd7a-60d99be64c90.png">

**Comment by IS-Josh** [comment]
<img width="509" alt="Screenshot 2023-03-11 at 4 54 35 pm" src="https://user-images.githubusercontent.com/48971328/224467722-57c7cf6d-6639-4206-a62f-2bc0bf6e856a.png">

**Comment by adas98012** [comment]
@IS-Josh 
Thanks for reporting the issue. Our engineering team is made aware of it, we'll keep you posted on any further updates.

**Comment by adas98012** [comment]
@IS-Josh 

Our engineering team couldn't reproduce the issue you are seeing in your environment. They would like to learn more about your database structure and about the exact queries taking long time.

Could you please [create a support ticket](http://cloud.hasura.io/support) mentioning this issue? We'll share a meeting link there so we can collaborate on finding the cause of the problem.

If you do not have a hasura cloud account, you can also email support [at] hasura [dot] io.

**Comment by IS-Josh** [comment]
Thanks, will do

**Comment by vijayprasanna13** [comment]
Hey folks! We've traced this issue to the large number of introspection calls that we fire. We're working on a new UX for postgres that makes the landing page for viewing/tracking your tables much faster.  
We'll keep you updated in the related [issue](https://github.com/hasura/graphql-engine/issues/9509)

**Comment by IS-Josh** [comment]
Hi I've upgraded to the lateste version - still experiencing the same issues.  These don't take too long to run when I run via a SQL client, however they timeout for hasura UI.


[
    {
        "type": "run_sql",
        "args": {
            "source": "default",
            "sql": "SELECT\n    COALESCE(Json_agg(Row_to_json(info)), '[]' :: json) AS tables\n  FROM (\n    WITH partitions AS (\n      SELECT array(\n        WITH partitioned_tables AS (SELECT array(SELECT oid FROM pg_class WHERE relkind = 'p') AS parent_tables)\n        SELECT\n        child.relname       AS partition\n    FROM partitioned_tables, pg_inherits\n        JOIN pg_class child             ON pg_inherits.inhrelid   = child.oid\n        JOIN pg_namespace nmsp_child    ON nmsp_child.oid   = child.relnamespace\n    where ((nmsp_child.nspname='alerts'))\n    AND pg_inherits.inhparent = ANY (partitioned_tables.parent_tables)\n      ) AS names\n    )\n    SELECT\n      pgn.nspname AS table_schema,\n      pgc.relname AS table_name,\n      CASE\n        WHEN pgc.relkind = 'r' THEN 'TABLE'\n        WHEN pgc.relkind = 'f' THEN 'FOREIGN TABLE'\n        WHEN pgc.relkind = 'v' THEN 'VIEW'\n        WHEN pgc.relkind = 'm' THEN 'MATERIALIZED VIEW'\n        WHEN pgc.relkind = 'p' THEN 'PARTITIONED TABLE'\n      END AS table_type,\n      obj_description(pgc.oid) AS comment,\n      COALESCE(json_agg(DISTINCT row_to_json(isc) :: jsonb || jsonb_build_object('comment', col_description(pga.attrelid, pga.attnum))) filter (WHERE isc.column_name IS NOT NULL), '[]' :: json) AS columns,\n      COALESCE(json_agg(DISTINCT row_to_json(ist) :: jsonb || jsonb_build_object('comment', obj_description(pgt.oid))) filter (WHERE ist.trigger_name IS NOT NULL), '[]' :: json) AS triggers,\n      row_to_json(isv) AS view_info\n      FROM partitions, pg_class as pgc\n      INNER JOIN pg_namespace as pgn\n        ON pgc.relnamespace = pgn.oid\n    /* columns */\n    /* This is a simplified version of how information_schema.columns was\n    ** implemented in postgres 9.5, but modified to support materialized\n    ** views.\n    */\n    LEFT OUTER JOIN pg_attribute AS pga\n      ON pga.attrelid = pgc.oid\n    LEFT OUTER JOIN (\n      SELECT\n        nc.nspname         AS table_schema,\n        c.relname          AS table_name,\n        a.attname          AS column_name,\n        a.attnum           AS ordinal_position,\n        pg_get_expr(ad.adbin, ad.adrelid) AS column_default,\n        CASE WHEN a.attnotnull OR (t.typtype = 'd' AND t.typnotnull) THEN 'NO' ELSE 'YES' END AS is_nullable,\n        CASE WHEN t.typtype = 'd' THEN\n          CASE WHEN bt.typelem <> 0 AND bt.typlen = -1 THEN 'ARRAY'\n               WHEN nbt.nspname = 'pg_catalog' THEN format_type(t.typbasetype, null)\n               ELSE 'USER-DEFINED' END\n        ELSE\n          CASE WHEN t.typelem <> 0 AND t.typlen = -1 THEN 'ARRAY'\n               WHEN nt.nspname = 'pg_catalog' THEN format_type(a.atttypid, null)\n               ELSE 'USER-DEFINED' END\n        END AS data_type,\n        coalesce(bt.typname, t.typname) AS data_type_name\n      FROM (pg_attribute a LEFT JOIN pg_attrdef ad ON attrelid = adrelid AND attnum = adnum)\n        JOIN (pg_class c JOIN pg_namespace nc ON (c.relnamespace = nc.oid)) ON a.attrelid = c.oid\n        JOIN (pg_type t JOIN pg_namespace nt ON (t.typnamespace = nt.oid)) ON a.atttypid = t.oid\n        LEFT JOIN (pg_type bt JOIN pg_namespace nbt ON (bt.typnamespace = nbt.oid))\n          ON (t.typtype = 'd' AND t.typbasetype = bt.oid)\n        LEFT JOIN (pg_collation co JOIN pg_namespace nco ON (co.collnamespace = nco.oid))\n          ON a.attcollation = co.oid AND (nco.nspname, co.collname) <> ('pg_catalog', 'default')\n      WHERE (NOT pg_is_other_temp_schema(nc.oid))\n        AND a.attnum > 0 AND NOT a.attisdropped AND c.relkind in ('r', 'v', 'm', 'f', 'p')\n        AND (pg_has_role(c.relowner, 'USAGE')\n             OR has_column_privilege(c.oid, a.attnum,\n                                     'SELECT, INSERT, UPDATE, REFERENCES'))\n    ) AS isc\n      ON  isc.table_schema = pgn.nspname\n      AND isc.table_name   = pgc.relname\n      AND isc.column_name  = pga.attname\n    /* triggers */\n    LEFT OUTER JOIN pg_trigger AS pgt\n      ON pgt.tgrelid = pgc.oid\n    LEFT OUTER JOIN information_schema.triggers AS ist\n      ON  ist.event_object_schema = pgn.nspname\n      AND ist.event_object_table  = pgc.relname\n      AND ist.trigger_name        = pgt.tgname\n    /* This is a simplified version of how information_schema.views was\n    ** implemented in postgres 9.5, but modified to support materialized\n    ** views.\n    */\n    LEFT OUTER JOIN (\n      SELECT\n        nc.nspname         AS table_schema,\n        c.relname          AS table_name,\n        CASE WHEN pg_has_role(c.relowner, 'USAGE') THEN pg_get_viewdef(c.oid) ELSE null END AS view_definition,\n        CASE WHEN pg_relation_is_updatable(c.oid, false) & 20 = 20 THEN 'YES' ELSE 'NO' END AS is_updatable,\n        CASE WHEN pg_relation_is_updatable(c.oid, false) &  8 =  8 THEN 'YES' ELSE 'NO' END AS is_insertable_into,\n        CASE WHEN EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = c.oid AND tgtype & 81 = 81) THEN 'YES' ELSE 'NO' END AS is_trigger_updatable,\n        CASE WHEN EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = c.oid AND tgtype & 73 = 73) THEN 'YES' ELSE 'NO' END AS is_trigger_deletable,\n        CASE WHEN EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = c.oid AND tgtype & 69 = 69) THEN 'YES' ELSE 'NO' END AS is_trigger_insertable_into\n      FROM pg_namespace nc, pg_class c\n      WHERE c.relnamespace = nc.oid\n        AND c.relkind in ('v', 'm')\n        AND (NOT pg_is_other_temp_schema(nc.oid))\n        AND (pg_has_role(c.relowner, 'USAGE')\n             OR has_table_privilege(c.oid, 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER')\n             OR has_any_column_privilege(c.oid, 'SELECT, INSERT, UPDATE, REFERENCES'))\n    ) AS isv\n      ON  isv.table_schema = pgn.nspname\n      AND isv.table_name   = pgc.relname\n    WHERE\n      pgc.relkind IN ('r', 'v', 'f', 'm', 'p')\n      and ((pgn.nspname='alerts'))\n    GROUP BY pgc.oid, pgn.nspname, pgc.relname, table_type, isv.*\n  ) AS info;",
            "cascade": false,
            "read_only": true
        }
    },
    {
        "type": "run_sql",
        "args": {
            "source": "default",
            "sql": "SELECT\n\tCOALESCE(json_agg(row_to_json(info)), '[]'::JSON)\nFROM (\n\tSELECT\n\t\tq.table_schema::text AS table_schema,\n\t\tq.table_name::text AS table_name,\n\t\tq.constraint_name::text AS constraint_name,\n\t\tmin(q.ref_table_table_schema::text) AS ref_table_table_schema,\n\t\tmin(q.ref_table::text) AS ref_table,\n\t\tjson_object_agg(ac.attname, afc.attname) AS column_mapping,\n\t\tmin(q.confupdtype::text) AS on_update,\n\t\tmin(q.confdeltype::text) AS\n\t\ton_delete\n\tFROM (\n\t\tSELECT\n\t\t\tctn.nspname AS table_schema,\n\t\t\tct.relname AS table_name,\n\t\t\tr.conrelid AS table_id,\n\t\t\tr.conname AS constraint_name,\n\t\t\tcftn.nspname AS ref_table_table_schema,\n\t\t\tcft.relname AS ref_table,\n\t\t\tr.confrelid AS ref_table_id,\n\t\t\tr.confupdtype,\n\t\t\tr.confdeltype,\n\t\t\tunnest(r.conkey) AS column_id,\n\t\t\tunnest(r.confkey) AS ref_column_id\n\t\tFROM\n\t\t\tpg_constraint r\n\t\t\tJOIN pg_class ct ON r.conrelid = ct.oid\n\t\t\tJOIN pg_namespace ctn ON ct.relnamespace = ctn.oid\n\t\t\tJOIN pg_class cft ON r.confrelid = cft.oid\n\t\t\tJOIN pg_namespace cftn ON cft.relnamespace = cftn.oid\n    WHERE\n      r.contype = 'f'::\"char\"\n      AND ((ctn.nspname='alerts'))\n      ) q\n\t\tJOIN pg_attribute ac ON q.column_id = ac.attnum\n\t\t\tAND q.table_id = ac.attrelid\n\t\tJOIN pg_attribute afc ON q.ref_column_id = afc.attnum\n\t\t\tAND q.ref_table_id = afc.attrelid\n\t\tGROUP BY\n\t\t\tq.table_schema,\n\t\t\tq.table_name,\n      q.constraint_name) AS info;",
            "cascade": false,
            "read_only": true
        }
    },
    {
        "type": "run_sql",
        "args": {
            "source": "default",
            "sql": "SELECT\nCOALESCE(\n  json_agg(\n    row_to_json(info)\n  ),\n  '[]' :: JSON\n)\nFROM (\nSELECT\ntc.table_schema,\ntc.table_name,\ntc.constraint_name,\njson_agg(constraint_column_usage.column_name) AS columns\nFROM\ninformation_schema.table_constraints tc\nJOIN (\n  SELECT\n    x.tblschema AS table_schema,\n    x.tblname AS table_name,\n    x.colname AS column_name,\n    x.cstrname AS constraint_name\n  FROM ( SELECT DISTINCT\n      nr.nspname,\n      r.relname,\n      a.attname,\n      c.conname\n    FROM\n      pg_namespace nr,\n      pg_class r,\n      pg_attribute a,\n      pg_depend d,\n      pg_namespace nc,\n      pg_constraint c\n    WHERE\n      nr.oid = r.relnamespace\n      AND r.oid = a.attrelid\n      AND d.refclassid = 'pg_class'::regclass::oid\n      AND d.refobjid = r.oid\n      AND d.refobjsubid = a.attnum\n      AND d.classid = 'pg_constraint'::regclass::oid\n      AND d.objid = c.oid\n      AND c.connamespace = nc.oid\n      AND c.contype = 'c'::\"char\"\n      AND(r.relkind = ANY (ARRAY ['r'::\"char\", 'p'::\"char\"]))\n      AND NOT a.attisdropped\n    UNION ALL\n    SELECT\n      nr.nspname,\n      r.relname,\n      a.attname,\n      c.conname\n    FROM\n      pg_namespace nr,\n      pg_class r,\n      pg_attribute a,\n      pg_namespace nc,\n      pg_constraint c\n    WHERE\n      nr.oid = r.relnamespace\n      AND r.oid = a.attrelid\n      AND nc.oid = c.connamespace\n      AND r.oid = CASE c.contype\n      WHEN 'f'::\"char\" THEN\n        c.confrelid\n      ELSE\n        c.conrelid\n      END\n      AND(a.attnum = ANY (\n          CASE c.contype\n          WHEN 'f'::\"char\" THEN\n            c.confkey\n          ELSE\n            c.conkey\n          END))\n      AND NOT a.attisdropped\n      AND(c.contype = ANY (ARRAY ['p'::\"char\", 'u'::\"char\", 'f'::\"char\"]))\n      AND(r.relkind = ANY (ARRAY ['r'::\"char\", 'p'::\"char\"]))) x (tblschema, tblname, colname, cstrname)) constraint_column_usage ON tc.constraint_name::text = constraint_column_usage.constraint_name::text\n  AND tc.table_schema::text = constraint_column_usage.table_schema::text\n  AND tc.table_name::text = constraint_column_usage.table_name::text\nwhere ((tc.table_schema='alerts'))\n  AND tc.constraint_type::text = 'PRIMARY KEY'::text\nGROUP BY\n  tc.table_schema, tc.table_name, tc.constraint_name) as info;",
            "cascade": false,
            "read_only": true
        }
    },
    {
        "type": "run_sql",
        "args": {
            "source": "default",
            "sql": "SELECT\nCOALESCE(\n  json_agg(\n    row_to_json(info)\n  ),\n  '[]' :: JSON\n)\nFROM (\n\tSELECT\n\t\ttc.table_name,\n\t\ttc.constraint_schema AS table_schema,\n\t\ttc.constraint_name,\n\t\tjson_agg(kcu.column_name) AS columns\n\tFROM\n\t\tinformation_schema.table_constraints tc\n\t\tJOIN information_schema.key_column_usage kcu USING (constraint_schema, constraint_name)\n    where ((tc.constraint_schema='alerts'))\n\t\tAND tc.constraint_type::text = 'UNIQUE'::text\n\tGROUP BY\n\t\ttc.table_name,\n\t\ttc.constraint_schema,\n\t\ttc.constraint_name) AS info;",
            "cascade": false,
            "read_only": true
        }
    },
    {
        "type": "run_sql",
        "args": {
            "source": "default",
            "sql": "SELECT\nCOALESCE(\n  json_agg(\n    row_to_json(info)\n  ),\n  '[]' :: JSON\n)\nFROM (\nSELECT n.nspname::text AS table_schema,\n    ct.relname::text AS table_name,\n    r.conname::text AS constraint_name,\n    pg_get_constraintdef(r.oid, true) AS \"check\"\n   FROM pg_constraint r\n     JOIN pg_class ct ON r.conrelid = ct.oid\n     JOIN pg_namespace n ON ct.relnamespace = n.oid\n   where ((n.nspname='alerts'))\n   AND r.contype = 'c'::\"char\"\n   ) AS info;",
            "cascade": false,
            "read_only": true
        }
    }
]

**Comment by vijayprasanna13** [comment]
@IS-Josh We're working on this issue right and we're planning to release an improved version of the tracking UI which should be faster. Please follow this Github [discussion](https://github.com/hasura/graphql-engine/discussions/9727) for more details!

**Comment by manasag** [comment]
The improved UI is now available in v2.29. 

**How to enable this feature?**
Navigate to the `Settings > Feature Flags` part of the console and toggle the `Enable new Table Tracking UI for Postgres & SQL Server` feature flag to start using this feature.

**Comment by vijayprasanna13** [comment]
@IS-Josh We've added a new experimental version of the Data Tab to handle larger schemas. This is similar to the one we demoed during our discussion. You can try it out starting from `v2.33.0-beta.1` by enabling the feature flag. Please follow this [discussion](https://github.com/hasura/graphql-engine/discussions/9846) for more updates and do share your early feedback with us!
