### ISSUE TITLE
About release 2.20.1

### ISSUE THREAD

**Issue by chenrui333** [hasura/graphql-engine#9489]
👋 Just a note that the release 2.20.1 was not done completely (as there is no release notes for it). Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/125233

The latest release still points to 2.20.0
![image](https://user-images.githubusercontent.com/1580956/224517783-62c8ed85-4ff3-4692-96fe-58e2c7f830fe.png)

**Comment by manasag** [comment]
Hi, thanks for raising this. This should be resolved in next 24 hours.
