### ISSUE TITLE
Ability to choose between gen_hasura_uuid and gen_random_uuid

### ISSUE THREAD

**Issue by Alegrowin** [hasura/graphql-engine#9495]
### Is your proposal related to a problem?

Cockroachlabs.cloud now [support pgcrypto](https://www.cockroachlabs.com/docs/stable/postgresql-compatibility.html)
To fully support hasura metadata database to be hosted on the serverless cockroachlabs.cloud the function gen_hasura_uuid which is a wrapper around hdb_catalog.gen_random_uuid, is required. 

While the team at cockroachlabs is working toward solving [cross reference tracking of udf usage](https://github.com/cockroachdb/cockroach/issues/87699), it would be nice to be able to work around that limitation.

### Describe the solution you'd like

It would be nice to add a feature flag supporting the case where the postgresql backend doesn't require the gen_random_uuid function from another schema. e.g. cockroachlabs cloud serverless offering.

### Describe alternatives you've considered

I was successful with migrating our database to cockroachlabs.cloud serverless but there were some caveats

1. Create hasura in a local postgresql database e.g. using docker compose
1. Create cockroachlabs.cloud serverless database
1. Configure cockroachlabs.cloud database with `CREATE EXTENSION IF NOT EXISTS pgcrypto;`
1. Migrate the database from postgres to cockroachlabs.cloud
```bash
POSTGRES_HOSTNAME="localhost:5432"
pg_dump -n public --rows-per-insert 1000 --column-inserts postgres://postgres:postgrespassword@$POSTGRES_HOSTNAME/postgres -f public_full_backup.sql
pg_dump -n hdb_catalog --rows-per-insert 1000 --column-inserts postgres://postgres:postgrespassword@$POSTGRES_HOSTNAME/postgres -f hdb_catalog_full_backup.sql

sed -i "s/OWNER TO postgres/OWNER TO \"cockroach-user\"/" public_full_backup.sql

sed -i "s/OWNER TO postgres/OWNER TO \"cockroach-user\"/" hdb_catalog_full_backup.sql
sed -i "s/gen_hasura_uuid/gen_random_uuid/" hdb_catalog_full_backup.sql
sed -i "s/hdb_catalog.gen_random_uuid/gen_random_uuid/" hdb_catalog_full_backup.sql

cockroach-sql --url postgres://cockroach-user:postgrespassword@cluster.cockroachlabs.cloud:26257/database?sslmode=verify-full --file public_full_backup.sql
cockroach-sql --url postgresql://cockroach-user:postgrespassword@cluster.cockroachlabs.cloud:26257/database?sslmode=verify-full --file hdb_catalog_full_backup.sql
```
1. Comment CREATE FUNCTION gen_hasura_uuid
```sql
--  CREATE FUNCTION gen_hasura_uuid() RETURNS uuid
--     LANGUAGE sql
--     AS $$select gen_random_uuid()$$;
```
else you will get 
```bash
ERROR: unimplemented: usage of user-defined function from relations not supported
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/83234/v22.2
```
1. Modify hasura deployment e.g. HASURA_GRAPHQL_METADATA_DATABASE_URL & HASURA_GRAPHQL_DATABASE_URL to point to postgresql://cockroach-user:postgrespassword@cluster.cockroachlabs.cloud:26257/database?sslmode=verify-full 
1. Add root.crt to /root/.postgresql/ to ensure traffic goes out using ssl.
1. When the hasura service restarted, is complained about the metadata drift and I ask to reload both of the database and the metadata.

**Comment by SamirTalwar** [comment]
Sounds like a lovely idea but we are currently working on totally reworking the way HGE stores metadata. As such, we're not investing time in improving the current incarnation.
