### ISSUE TITLE
New relationship UI: Unable to track relationship for MS SQL views

### ISSUE THREAD

**Issue by harishnair96** [hasura/graphql-engine#9499]
### Version Information

Server Version: All versions v2.19.0 and greater

### Environment

All

### What is the current behaviour?

For MS SQL views, it is not possible to choose a source table and column (The dropdown is greyed out).
<img width="721" alt="Screenshot 2023-03-16 at 3 47 31 PM" src="https://user-images.githubusercontent.com/20351766/225586672-1844306d-0b9f-4e94-b0a4-acfefb17ad16.png">

It works in the old relationship UI -
<img width="953" alt="Screenshot 2023-03-16 at 3 49 16 PM" src="https://user-images.githubusercontent.com/20351766/225587141-99509153-7871-4671-abff-fae9cea3906f.png">

### What is the expected behaviour?

Since it works in the old UI, it should work in the new UI as well.

### How to reproduce the issue?

1. Track an MS SQL view
2. Go to relationships tab of the view
3. Try to add a relationship

### Any possible solutions/workarounds you're aware of?

Disable new relationship UI.

### Keywords

new relationship UI, view, MS SQL

**Comment by vijayprasanna13** [comment]
Thanks for reporting this @harishnair96! We'll look into it.

**Comment by vijayprasanna13** [comment]
@harishnair96 this should be fixed as of commit https://github.com/hasura/graphql-engine/commit/498d8fc9f4ad1e9cda8174d3b8afd7629f604713

**Comment by vijayprasanna13** [comment]
The fix will be available in the next CE release `2.22.0-beta.1`.
