### ISSUE TITLE
Allow custom statement_timeout per postgres data source

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#9514]
### Is your proposal related to a problem?

As [suggested by Hasura](https://hasura.io/learn/graphql/hasura-advanced/security/6-timeouts/), I want to customize `statement_timeout` for each postgres database, but only for connections that come from graphql queries.

### Describe the solution you'd like

A new input box in the connection settings:

![image](https://user-images.githubusercontent.com/11539524/226996600-dadf14a5-3b13-4c9c-be6f-a3328d90b8ef.png)

### Describe alternatives you've considered

I can't use `statement_timeout` in the connection string, and I don't want to set database-wide. I also don't want to tamper with Hasura's connections to the database for all kinds of maintenance purposes. Only for graphql queries.

**Comment by tirumaraiselvan** [comment]
Dupe of https://github.com/hasura/graphql-engine/issues/8266

If you only want a timeout for graphql queries, you can consider using Time Limits in API Security: https://hasura.io/docs/latest/security/api-limits/#time-limits (Cloud/EE only)
