### ISSUE TITLE
Analyze show's plan for only one of multiple SQL queries

### ISSUE THREAD

**Issue by guyb1997** [hasura/graphql-engine#9519]
### Version Information

Server Version: 2.8.3

### Environment

EE

### What is the current behaviour?

When using a Single GraphQL query that translates to multiple SQL queries, the analyze show's only the plan for the first query.
This is very confusing, I tried to debug a slow query, and it took me a lot of time the realize that there's another query I need to debug

### What is the expected behaviour?

Either analyze both queries, or allow selecting which part of the GraphQL query to analyze

### How to reproduce the issue?
```
example query:
query example {
    a: apps(limit: 5) {
        id
    }
  
    b: apps(limit: 5, offset: 5) {
      id
    }
}
```
Click the analyze, you'll see only the plan for the first part of the query

### Any possible solutions/workarounds you're aware of?

You can comment out parts of the query to debug it a section at a time

**Comment by rikinsk** [comment]
Hey. You should be able to choose the query for which the analyze response is being shown from the console. The queries are shown on the top left. I guess the UI here could be a little better to make this a bit more obvious.

![Screenshot from 2023-03-28 12-35-33](https://user-images.githubusercontent.com/54616969/228156052-701c0957-88ad-4b85-b22d-90b9ba7106dc.png).

Is this what you were looking for or have I misunderstood your issue?

**Comment by guyb1997** [comment]
Yes! missed it, thank you very much
