### ISSUE TITLE
Tracked tables don't show up in the GraphQL schema

### ISSUE THREAD

**Issue by vijayprasanna13** [hasura/graphql-engine#9545]
### Version Information

Server Version:
CLI Version (for CLI related issue):

### Environment

Cloud/ OSS / EE 

### What is the current behaviour?

There is a sporadic issue when tracking tables from Hasura, specifically when the track API call takes a while to resolve and gets interrupted other UI operations. The `export_metadata` lists the tables as tracked but I cannot find them in the GQL schema. Only after I reload the metadata, the GQL schema has the tracked tables and other Hasura operations can be resumed.

### What is the expected behaviour?

The `bulk` track table table API call resolves successfully and the tables appear in the GQL schema.

### How to reproduce the issue?

1. Connect a datasource and navigate to the tracking section of the UI.
2. Click on `Track All`.
3. While the call is on-going, navigate to the API tab and come back to the tracking UI again - the "track" call is still happens in the background.
4. The `export_metadata` API has all the tables that you just tracked, meaning the track operation was successful.
5. Click on any tracked table from the navigation tree - it errors out with the message "Table not found in the schema"
6. Any subsequent operations on the tables do not work.

### Screenshots or Screencast

https://user-images.githubusercontent.com/11921040/230381359-de4dbb9b-7e8b-476a-9a95-61561cb57bcd.mp4

**Comment by rikinsk** [comment]
fixed via https://github.com/hasura/graphql-engine/commit/2814735a20fa7be0ecd92181a0c207f13d83b573
