### ISSUE TITLE
Add support for manual event triggers

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#9549]
~~It would be really to have the ability to add manually trigger events using `notify` from custom triggers.~~
EDIT: my understanding was that event triggers used `pg_notify` but upon looking on how they work I realized that is not the case at all. Instead a row is inserted into `hdb_catalog.event_log` table using `hdb_catalog.insert_event_log` function and then hasura **I think** polls the table periodically for undelivered events and sends them(this is my hypothesis haven't looked at the haskell code). 
So the feature request is to have the ability to create an event trigger that is not directly tied to a table i.e. it doesn't automatically generate the notify trigger on any table instead users can just use the name to insert data into `event_log` using their own triggers and the payload is just forwarded.

**Comment by shahidhk** [comment]
@abdullah2993 Hasura Scheduled triggers are exactly for those use cases: https://hasura.io/docs/latest/scheduled-triggers/overview/
In this particular case, a one-off scheduled trigger: https://hasura.io/docs/latest/scheduled-triggers/create-one-off-scheduled-event/

Please re-open the ticket if this is not what you intended.
