### ISSUE TITLE
Import OAS Improvements -  OpenAPI 3.1 and soft failure support

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#9557]
## Feature Description

Provide automated functionalities to easily import existing REST APIs into Hasura as Actions.

## User value / outcome

Users should be able to unify their API infrastructure by wrapping their REST APIs into GraphQL.

## Current status 

**Import OpenAPI launched**

If the REST API has an OpenAPI spec then it can automatically fill all the information in the Action creation form.

<img width="472" alt="Screenshot 2023-04-17 at 11 24 20 AM" src="https://user-images.githubusercontent.com/8663570/232395310-b0c6b580-a743-4138-a860-9d01bb6163d2.png">

<img width="575" alt="Screenshot 2023-04-17 at 11 25 56 AM" src="https://user-images.githubusercontent.com/8663570/232395330-1477f96c-0811-40fa-8dce-b2582ce5445b.png">

## Next items

1. Collect more user feedback to improve the import experience of existing REST APIs into Hasura
2. Support other REST specs like JSON Schema, OData, etc

## Resources (e.g. RFCs)

RFC: https://github.com/hasura/graphql-engine/pull/9461

**Comment by soorajshankar** [comment]
More enhancements and support is being added here, some exciting updates are 
* OpenAPI 3.1 support 🪄 
* Partially import endpoints from unsupported openAPI specifications.

**Comment by soorajshankar** [comment]
Released with v2.27
https://github.com/hasura/graphql-engine/commit/5d3b0e07787bdd697b2798b0a202d8503d370c14
