### ISSUE TITLE
Event Triggers Observability

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#9558]
## Feature Description

The Event Trigger subsystem does not have much observability into its operational characteristics in a user-friendly way.
The feature is to add relevant metrics via Prometheus which helps in creating simple dashboards that give high-level as well as detailed information about Event Trigger performance.

## User value / outcome

User is able to setup dashboards/alerts and self-service (or with minimal support from Hasura) any performance issues with Event Triggers quickly.

## Current status (design, alpha, beta etc.)

Currently being implemented.

**Comment by tirumaraiselvan** [comment]
This is almost done and there will be a showcase in the upcoming community call: [registration link](https://hasura.io/community/community-call/)

**Comment by marionschleifer** [comment]
In case you missed the community call, you can watch [the recording](https://www.youtube.com/watch?v=1EMq4RVB2XA&t=1748s) to catch up on event trigger observability 🙂 . Docs can be found [here](https://hasura.io/docs/latest/event-triggers/observability-and-performace/).
