### ISSUE TITLE
Subscriptions Observability

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#9559]
## Feature Description

The subscriptions subsystem does not have much observability into its operational characteristics in a user-friendly way.
The feature is to add relevant metrics via Prometheus which helps in creating simple dashboards that give high-level as well as detailed information about subscriptions performance.

## User value / outcome

User is able to setup dashboards/alerts and self-service (or with minimal support from Hasura) any performance issues with subscriptions quickly.

## Current status (design, alpha, beta etc.)

Currently being implemented.

**Comment by tirumaraiselvan** [comment]
This is almost done and there will be a showcase in the upcoming community call: [registration link](https://hasura.io/community/community-call/)

**Comment by marionschleifer** [comment]
In case you missed the community call, you can watch [the recording]([29:08](https://www.youtube.com/watch?v=1EMq4RVB2XA&t=1748s)) to catch up on subscription observability 🙂  Docs can be found [here](https://hasura.io/docs/latest/subscriptions/observability-and-performance/).

**Comment by soorajshankar** [comment]
Quick updates: we have added more metrics in consideration of Golden Signals Monitoring philosophy and documented [here](https://hasura.io/docs/latest/subscriptions/observability-and-performance/#golden-signals-for-subscriptions). These metrics are now available for enterprise users and soon will be available to cloud users with a latest OpenTelemetry exporter feature. 

Keep your eyes on :)
