### ISSUE TITLE
Caching Improvements

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#9560]
## Feature Description

Improve documentation and provide actionable hints in the product to suggest where [caching](https://hasura.io/docs/latest/caching/overview/) can be used.

Also, remove any "simple" limitations like storage size limits, metadata configuration nuances, etc which prevents caching use-cases.

## User value / outcome

User is able to use caching in more scenarios and get helpful hints about caching.

## Current status (design, alpha, beta etc.)

Design

**Comment by tirumaraiselvan** [comment]
This is almost done and there will be a showcase in the upcoming community call: [registration link](https://hasura.io/community/community-call/)

**Comment by marionschleifer** [comment]
In case you missed the Community Call, you can watch [the recording](https://www.youtube.com/watch?v=1EMq4RVB2XA&t=1414s) to catch up on caching improvements 🙂 also, docs can be found [here](https://hasura.io/docs/latest/caching/how-it-works/) and [here](https://hasura.io/docs/latest/caching/caching-metrics/).
