### ISSUE TITLE
Enterprise SSO

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#9567]
## Feature Description

Add SSO for Hasura Console through any OAuth2/OpenID Compliant Identity Provider.

## User value / outcome

Users can configure login to Hasura Console via SSO, so that they can manage access at one place.

## Current status (design, alpha, beta etc.)

Beta with v2.24.0, available from `v2.24.0-beta.1`

## Resources (e.g. RFCs)

Docs: https://hasura.io/docs/latest/enterprise/sso/index/

**Comment by rsd1122** [comment]
This has been delivered - https://hasura.io/docs/latest/enterprise/sso/index/
