### ISSUE TITLE
Hasura Cloud on Azure (Beta)

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#9568]
## Feature Description

Create Hasura Cloud projects on Microsoft Azure regions.

## User value / outcome

Performance:
Hasura Cloud users can launch their Hasura instances right next to their databases or other data sources running on Microsoft Azure.

Compliance:
Existing Microsoft Azure users can meet their compliance needs by keeping all their Cloud infra including Hasura on Azure.

Diversity:
Providing users additional option to use Hasura on Azure in addition to AWS, GCP.

Lower TCO:
Users can leverage their Azure credits towards Hasura as well providing them with a lever to lower their costs.

## Current status 

In Progress

## Resources (e.g. RFCs)

NA

**Comment by MariusFearn** [comment]
Hi just want to let you know we are very interested in this, as the current docker solution in azure is not stable (changes ips ect)

**Comment by amit-git-account** [comment]
Hasura is now available on Azure. 
Hasura Projects can now be created on Azure in two regions - one each in the US and  EU.
