### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#9570]
## Feature Description
MySQL database support

#### Current in progress plans
- ✅ Queries
- ✅ Table relationships
- ✅ Permissions
- ✅ Mutations
- ✅ Remote relationships

#### Planned
- Subscriptions
- Event triggers
- User defined functions
- Logical models

## User value / outcome
User is able connect a MySQL database to Hasura and have a GraphQL api running instantly. 

## Current status
Alpha as of graphql-engine and graphql-data-connector v2.19.0 (Currently only MySQL 8.0+)

**Comment by rsd1122** [comment]
Happy to announce our MySQL/MariaDB connectors are now in beta - https://hasura.io/blog/introducing-instant-apis-for-mysql-mariadb-oracle/ 

Check out the video https://youtu.be/0GFVaJOxsnU to get a sneak peek into how they work

**Comment by rsd1122** [comment]
The Hasura MySQL data connector is now generally available (GA). 

Please our docs for more information:
https://hasura.io/docs/latest/databases/mysql/index/
