### ISSUE TITLE
Oracle Support

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#9571]
## Feature Description
Oracle database support

#### Current in progress plans
- ✅ Queries
- ✅ Table relationships
- ✅ Permissions
- ✅ Mutations
- ✅ Remote relationships

#### Planned
- Subscriptions
- Event triggers
- User defined functions
- Logical models

## User value / outcome
User is able connect a Oracle database to Hasura, and have a GraphQL api running instantly. 

## Current status
Alpha as of graphql-engine and graphql-data-connector v2.23.0 (Currently only Oracle 18.0+)

**Comment by rsd1122** [comment]
The Hasura Oracle data connector is now generally available (GA).

Please see our docs for more information:
https://hasura.io/docs/latest/databases/oracle/index/
