### ISSUE TITLE
Snowflake Support

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#9573]
## Feature Description
Snowflake database support

#### Current in progress plans
- ✅ Queries
- ✅ Table relationships
- ✅ Permissions
- ✅ Remote relationships
- 🚧 User defined functions

#### Planned
- Mutations
- Subscriptions
- Event triggers
- Logical models

## User value / outcome
User is able connect Snowflake to Hasura and have a GraphQL api running instantly. 

## Current status
Beta as of graphql-engine and graphql-data-connector v2.16.0

**Comment by dameleney** [comment]
Join the Hasura community call this week May 25, 2023 at 9AM PT to learn more about the SQL queries auto-generated by the Hasura integration for Snowflake. Don't bother learning how to write highly efficient SQL for Snowflake let Hasura do it for you. We work directly with Snowflake to ensure the Hasura integration works with current and future features coming to Snowflake. [registration link](https://hasura.io/community/community-call/)

**Comment by dameleney** [comment]
The Hasura Snowflake data connector is now generally available (GA).

Please see our docs for more information:
https://hasura.io/docs/latest/databases/snowflake/index/
