### ISSUE TITLE
MariaDB Support

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#9575]
## Feature Description
MariaDB database support

#### Current in progress plans
- ✅ Queries
- ✅ Table relationships
- ✅ Permissions
- ✅ Mutations
- ✅ Remote relationships

#### Planned
- Subscriptions
- Event triggers
- User defined functions
- Logical models

## User value / outcome
User is able connect a MariaDB database to Hasura and have a GraphQL api running instantly. 

## Current status
Alpha as of graphql-engine and graphql-data-connector v2.23.0 (Currently only MariaDB 10.5+)

**Comment by rsd1122** [comment]
Happy to announce our MySQL/MariaDB connectors are now in beta - https://hasura.io/blog/introducing-instant-apis-for-mysql-mariadb-oracle/

Check out the video https://youtu.be/0GFVaJOxsnU to get a sneak peek into how they work

**Comment by dameleney** [comment]
See a demo of Hasura MariaDB support during the Hasura community call this week May 25, 2023 at 9AM PT. [registration link](https://hasura.io/community/community-call/)

**Comment by rsd1122** [comment]
The Hasura MariaDB data connector is now generally available (GA).

Please see our docs for more information:
https://hasura.io/docs/latest/databases/mariadb/index/

**Comment by rohitnarayan** [comment]
How to fetch environment variables in hasura when connecting MariaDB?
