### ISSUE TITLE
New relationship UI the array relationships are not showing

### ISSUE THREAD

**Issue by amal-chandran** [hasura/graphql-engine#9595]
### Version Information

Server Version: v2.23.0
CLI Version (for CLI related issue): 2.22.0

### What is the current behavior?

- In the new relationship UI the array relationships are not showing
- In the older one, it was showing

### What is the expected behavior?

The array relationship should also show up in the ui

### How to reproduce the issue?

1. Turn on the New Relationship UI feature flag
2. Navigate to Data -> Table (has some array relationship) -> Relationship Tab 
3. Click the Relationships tab

### Screenshots or Screencast

New Relationships UI
![image](https://user-images.githubusercontent.com/29562232/233135071-b9157852-e9e5-4390-b6dc-b315d09edca1.png)

Old Relationships UI
![image](https://user-images.githubusercontent.com/29562232/233135211-ec1c36c6-294e-40d5-abbf-91b54d60d102.png)

### Any possible solutions/workarounds you're aware of?

Disable the feature flag to view the mapping

### Keywords

- relationships
- relationships views
- relationships error
-

**Comment by kbooz** [comment]
I'm facing the same issue, after I've added the suggested relationship, it shows an empty field on the list
![image](https://github.com/hasura/graphql-engine/assets/3723280/ec875723-2cd5-46b7-8561-5038fe9cdce9)

**Comment by vijayprasanna13** [comment]
@amal-chandran @kbooz We've just fixed this https://github.com/hasura/graphql-engine/commit/9179135148da4646d9f6377d1760d7cf64655b61 and should be fixed in the next release.
<img width="1125" alt="Screenshot 2023-06-26 at 3 50 09 PM" src="https://github.com/hasura/graphql-engine/assets/11921040/a908aa85-1d15-4d84-b25e-446705a0bca4">

**Comment by kbooz** [comment]
Thank you very much, @amal-chandran !

**Comment by kbooz** [comment]
Thank you, @vijayprasanna13 !
