### ISSUE TITLE
Problems using where _or in query. "_OR" does not seem to work.

### ISSUE THREAD

**Issue by pellesg** [hasura/graphql-engine#9608]
Server Version: 2.23.0

My query looks like:

```graphql
query xxx{
  ts_kv_aggregated(where: {entity_id: {_eq: "a9c39290-4dfb-11ed-9cfe-f986c2b0516e"}, **_or**: {entity_id: {_eq: "51a8cb30-5431-11ec-95a3-1d5d86f4aa22"}}}) {
    t: ts
  }
}
```

This gives me 0 records in return. 

I see in the analyser it get translated to:

```sql
    SELECT
      row_to_json(
        (
          SELECT
            "_e"
          FROM
            (
              SELECT
                "_root.base"."ts" AS "t"
            ) AS "_e"
        )
      ) AS "root"
    FROM
      (
        SELECT
          *
        FROM
          "public"."ts_kv_aggregated"
        WHERE
          (
            (
              ("public"."ts_kv_aggregated"."entity_id") = (('a9c39290-4dfb-11ed-9cfe-f986c2b0516e') :: uuid)
            )
            **AND (**
              ("public"."ts_kv_aggregated"."entity_id") = (('51a8cb30-5431-11ec-95a3-1d5d86f4aa22') :: uuid)
            )
          )
      ) AS "_root.base"
```

When I run the SQL as script I get no results. But then I change `AND` to `OR`, it works fine.

**Comment by SamirTalwar** [comment]
`_or` takes an array of options ([docs](https://hasura.io/docs/latest/queries/postgres/query-filters/#using-multiple-filters-in-the-same-query-_and-_or).

I suggest trying the following:

```graphql
query xxx{
  ts_kv_aggregated(
    where: {
      _or: [
        {entity_id: {_eq: "a9c39290-4dfb-11ed-9cfe-f986c2b0516e"}},
        {entity_id: {_eq: "51a8cb30-5431-11ec-95a3-1d5d86f4aa22"}}
      ]
    }
  ) {
    t: ts
  }
}
```

**Comment by pellesg** [comment]
Excellent. Thx for the help!

**Comment by tnrich** [comment]
@SamirTalwar the docs you link AFAICT do NOT show an example of using _or with an array.

Also, why not make _or fail if anything besides an array is passed to it? It is very confusing that we're allowed to pass an _or filter like so: 
![image](https://github.com/user-attachments/assets/0b876914-d178-4162-b169-ac6f652419e6)


Thanks!
