### ISSUE TITLE
Pairing `insert_{table_name}_one` GraphQL function is missing for the anonymous role

### ISSUE THREAD

**Issue by georgy-scifind** [hasura/graphql-engine#9610]
### Version Information

Server Version: v2.23
CLI Version (for CLI related issue): v2.23

### Environment

Cloud
### What is the current behaviour?

We have a table called `post_engagements` and two roles, `user` and `anonymous` (when the user is not logged in). The insert permissions are exactly the same for these two roles for that table. The problem is that for an API client with the `anonymous` role set, only one Graphql function is available — `insert_post_engagements` — and `insert_post_engagements_one` is missing. However, for an API client with the `user` role, both `insert_post_engagements` and `insert_post_engagements_one` are available.
### What is the expected behaviour?

We expected both `insert_post_engagements` and `insert_post_engagements_one` to be present for the anonymous role. This's how it was before since we didn't have that problem until recently.
### How to reproduce the issue?

1. Create a table
2. Add insert permissions for the "user" and "anonymous" roles.
3. Observe the bug in the API Explorer.

### Screenshots or Screencast

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/113255161/234683186-cc864a57-49f4-4b9b-b376-383acb678de0.png">
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/113255161/234683802-3bc06e15-f720-4a5a-8422-a4d367ab009d.png">
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/113255161/234683948-d707d946-0c13-4b87-823c-d4f3c042b37d.png">

### Any possible solutions/workarounds you're aware of?

Only rely on `insert_post_engagements` in our code.

### Keywords
anonymous role, insert one

**Comment by rikinsk** [comment]
Hey. From your screenshot it seems like you don't have any select permissions for the anonymous role which are required for the insert_one mutation to be exposed. See note about it in the [docs](https://hasura.io/docs/latest/mutations/postgres/insert/#insert-a-single-object)

**Comment by georgy-scifind** [comment]
Thanks. It perfectly explains the problem we faced.
