### ISSUE TITLE
Permissions role  BUG

### ISSUE THREAD

**Issue by zuohuadong** [hasura/graphql-engine#9616]
### Version Information

Server Version:
CLI Version (for CLI related issue): 2.23.0

### BUG

When i remove “user” :

![image](https://user-images.githubusercontent.com/11203929/235279571-e8887dcf-1517-4835-9321-7e3b16f854ab.png)

BUT I can see both "Users" "Users"

![image](https://user-images.githubusercontent.com/11203929/235279590-a93650b8-2223-4f33-8770-96882a358b30.png)

**Comment by rikinsk** [comment]
@zuohuadong do you happen to have permissions for the role "user" for any action or remote schema?

**Comment by zuohuadong** [comment]
@rikinsk no
