### ISSUE TITLE
Adding a suggested object relationship adds array relationship instead

### ISSUE THREAD

**Issue by kpala** [hasura/graphql-engine#9618]
### Version Information

Server Version: 2.24.1

### What is the current behaviour?

In relationships view, Hasura console suggests adding an object relationship:

![Screenshot 2023-05-05 at 8 45 38](https://user-images.githubusercontent.com/8023293/236386510-6fe71a91-d39f-4d30-84d0-c2ffd48a4b9f.png)

However, adding the suggested relationships ends up into an array relationship:

![Screenshot 2023-05-05 at 8 45 53](https://user-images.githubusercontent.com/8023293/236386550-b5daacfe-948d-40e7-8ec0-24bdf9951159.png)

(Above, the foreign key "kit_id" is defined as unique.)

### What is the expected behaviour?

Adding a suggested object relationship should end up into an object relationship.

### Any possible solutions/workarounds you're aware of?

Adding the same object relationship via "Create relationship" dialog works.

### Keywords

relationships, object

**Comment by kpala** [comment]
Sure! Here's the minimal SQL for reproducing the issue:

```sql
CREATE TABLE kit (
    id uuid DEFAULT gen_random_uuid() NOT NULL
);
ALTER TABLE kit ADD CONSTRAINT kit_pkey PRIMARY KEY (id);

CREATE TABLE registration (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    kit_id uuid NOT NULL
);
ALTER TABLE registration ADD CONSTRAINT registration_pkey PRIMARY KEY (id);
ALTER TABLE registration ADD CONSTRAINT registration_kit_id_key UNIQUE (kit_id);
ALTER TABLE registration ADD CONSTRAINT registration_kit_id_fkey FOREIGN KEY (kit_id) REFERENCES kit(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
```

**Comment by vijayprasanna13** [comment]
Thanks @kpala! I was able to replicate it. 
This seems to be a UI bug. We'll look into this and keep this thread updated!

**Comment by lucarestagno** [comment]
hi @kpala this issue has been fixed in this [commit](https://github.com/hasura/graphql-engine/commit/d0acdcf41474b4fbf333507e12b81898253efa58) and it'll be included in the next release next week.

thanks for your help! 🙌
