### ISSUE TITLE
Hasura Action OpenApi Spec importing from Valid swagger issue

### ISSUE THREAD

**Issue by BokhodirUrinboev** [hasura/graphql-engine#9619]
### Version Information

Server Version:
CLI Version (for CLI related issue):
 v2.24.1
### Environment
windows

EE 
### 
  It has to work properly with proper swagger  json  file

### Keywords
Hasura Action OpenApi Spec importing from Valid swagger issue

**Comment by dancamma** [comment]
Hello @BokhodirUrinboev, if you don't mind, could you kindly provide the complete specification? This information will greatly assist us in identifying and resolving the issue.
