### ISSUE TITLE
hasura-cli docker image

### ISSUE THREAD

**Issue by Maxpain177** [hasura/graphql-engine#962]
Please add hasura-cli to `hasura/graphql-engine` docker image or create a new one.
Needed for migrations in CI/CD process.

**Comment by shahidhk** [comment]
Duplicate of #562, already fixed in https://github.com/hasura/graphql-engine/pull/953

Latest image is `hasura/graphql-engine:v1.0.0-alpha27.cli-migrations`

**Comment by shahidhk** [comment]
@Maxpain177 You can use this docker image for cli: `hasura/graphql-engine:v1.0.0-alpha27.cli-migrations`.

Mount the hasura migrations directory at `/hasura-migrations` of this container and it will start graphql-engine after applying migrations.

**Comment by Maxpain177** [comment]
> @Maxpain177 You can use this docker image for cli: `hasura/graphql-engine:v1.0.0-alpha27.cli-migrations`.
> 
> Mount the hasura migrations directory at `/hasura-migrations` of this container and it will start graphql-engine after applying migrations.

thx
