### ISSUE TITLE
Variable latency with event triggers (higher than expected) 

### ISSUE THREAD

**Issue by elan** [hasura/graphql-engine#9623]
### Version Information

Server Version: v2.23.0

### Environment

Docker running on macOS, PostgreSQL backend.

### What is the current behaviour?

Have a simple event trigger set up to notify an HTTP endpoint when the database changes. The events *seem* to be batched or polled, there is variable latency between the state change in the database and getting hit via HTTP (0-2 seconds, roughly).

### What is the expected behaviour?

Instant update.

### How to reproduce the issue?

1. Set up an event trigger.
2. Change the data in the database via console or GraphQL.
3. Observe variable latency in the request being hit.

### Keywords

event trigger latency

**Comment by manasag** [comment]
Hi @elan. Yes, the event trigger architecture is build upon polling for changes. This [doc](https://hasura.io/docs/latest/event-triggers/event-trigger-delivery/#events-fetch-interval) talks about some tuning parameters that can help you here. Specifically, the env variable `HASURA_GRAPHQL_EVENTS_FETCH_INTERVAL` can be set with a smaller value (default is set at 1 sec), to reduce the time delay.

**Comment by elan** [comment]
Thanks for your reply. 

Are there any plans to allow for some sort of "real-time" event streaming, either via GraphQL subscription or event triggers?

Going to close this out as it's by design 😅

**Comment by tirumaraiselvan** [comment]
@elan Yeah, we are exploring few ideas here which will make event triggers faster and scale even more

**Comment by elan** [comment]
Appreciate the feedback! Otherwise Hasura has been a pleasure to work with, very fast to get up and running and great management console UI.

**Comment by ilijaNL** [comment]
> @elan Yeah, we are exploring few ideas here which will make event triggers faster and scale even more

Could you give more insights on these ideas?

**Comment by tirumaraiselvan** [comment]
@ilijaNL We are exploring ideas to use the database WAL instead of using database triggers.
