### ISSUE TITLE
Tables, with camel case column names, created through the sql page in the console, have all column characters converted to lowercase

### ISSUE THREAD

**Issue by ericwooley** [hasura/graphql-engine#9631]
### Version Information
hasura/graphql-engine:v2.24.1.cli-migrations-v3

Server Version:
CLI Version (for CLI related issue):
{"level":"info","msg":"hasura cli","time":"2023-05-09T17:16:53-06:00","version":"v2.19.0-beta.1"}

### Environment
Mac os m1, running docker with version hasura/graphql-engine:v2.24.1.cli-migrations-v3 and postgres v15

### What is the current behaviour?

Adding a table through the sql page, which has camel case column names, has their column names converted to lowercase.
![image](https://github.com/hasura/graphql-engine/assets/1930227/15b83097-b02b-47bb-8e38-2699388d1563)

![image](https://github.com/hasura/graphql-engine/assets/1930227/d5c9bbe0-90a1-43ea-8867-c1ba054b5f5d)

### What is the expected behaviour?
The table name and columns should be the same as the query specifies

### How to reproduce the issue?

1. Create a new table through the sql page
```sql
CREATE TABLE usersTest (
  _id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT,
  firstName TEXT DEFAULT '',
  lastName TEXT DEFAULT ''
);
```

2. Verify that the column names and table names is converted to lowercase.

### Screenshots or Screencast

Embedded

### Any possible solutions/workarounds you're aware of?

You can edit the column names after the fact, through the gui, and they are correct.

### Keywords
camelCase sql track migration

**Comment by rikinsk** [comment]
Hey could you try the following SQL instead. Postgres lowercases identifiers if they are not double-quoted
```sql
CREATE TABLE "usersTest" (
  "_id" TEXT PRIMARY KEY,
  "email" TEXT UNIQUE NOT NULL,
  "password" TEXT,
  "firstName" TEXT DEFAULT '',
  "lastName" TEXT DEFAULT ''
);
```
