### ISSUE TITLE
Configure isolation level for MSSQL Server

### ISSUE THREAD

**Issue by EternalDeiwos** [hasura/graphql-engine#9633]
### Is your proposal related to a problem?

We are experiencing delays in responses due to requests invoking multiple complex queries that cannot be parallelized due to the default isolation level set by Hasura for MSSQL connections

### Describe the solution you'd like

I would like to configure the transaction isolation level, as is currently possible for Postgres connections.

### Describe alternatives you've considered

N/A

**Comment by soupi** [comment]
Hi @EternalDeiwos, We've implemented this request via 653106087cccf72b69528c0593a3988b0b6ecb3d and we expect it to be released on the next version.
