### ISSUE TITLE
docs: how to configure custom claims for jwt

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#964]
- Link to the rule snippet that can be added to auth0
- How to add custom claims if you're using json-web-token

@rikinsk Perhaps this can be a separate repo with references of how to add custom claims in all kinds of different languages/frameworks? 

Currently, auth0, firebase, json-web-token seem to be the big ones. We can add more as we go along.

**Comment by Racv** [comment]
Hi can I work on this issue?? I have already worked on JWT so I think I can handle this..

**Comment by marionschleifer** [comment]
Hi @Racv 👋 this would be awesome! I assigned the issue to you. Let me know if you have any questions along the way 🙂

**Comment by seanparkross** [comment]
Hi All. This is covered now in the updated authentication docs [here](https://hasura.io/docs/latest/auth/authentication/jwt/). Closing unless there are more concerns, please re-open.
