### ISSUE TITLE
live queries

### ISSUE THREAD

**Issue by sasog23** [hasura/graphql-engine#9642]
does bellow syntax work on hasura...i'm getting error message "directive 'live' is not defined in the schema"

query @live {
  vote {
    created_at
    option {
      poll {
        question
      }
      text
    }
  }
}

**Comment by ecthiender** [comment]
Nope. Hasura doesn't support `@live`. Use subscriptions instead.

```
subscription {
vote {
created_at
option {
poll {
question
}
text
}
}
}
```
