### ISSUE TITLE
Hasua colud shows NaN when you create a new project

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#9643]
The picture explains it all
![image](https://github.com/hasura/graphql-engine/assets/5978905/f394b9b5-644c-42a8-a7f5-0694b9eed76d)

**Comment by 111mihir** [comment]
Thanks for reporting this @abdullah2993. This will be fixed soon.

**Comment by 111mihir** [comment]
@abdullah2993 This has been fixed. The issue was with new projects not having a data pass-through metric available immediately on creation. We've added a fix to handle this scenario. Let us know if there are any more concerns.
