### ISSUE TITLE
Transform Error Payload returned by REST service

### ISSUE THREAD

**Issue by tiafouroohi** [hasura/graphql-engine#9645]
### Is your proposal related to a problem?

When using REST Connectors for Actions, if the REST service throws an error, there is no way to transform the error payload returned by REST service, resulting in the need to introduce a middleware or make changes to the upstream service.

### Describe the solution you'd like

Adding "HTTP Status Code" to the context of response transforms so that based on the HTTP status code, user can write a Kriti template which can modify the origin API's error body into the Hasura Action compliant body. See below:

```
if status == 200
  then $response.body
else if status = 400
  {{ { "message": $response.body } }}
else 
  {{ { "message" : "internal error" }  }}

```

**Comment by tirumaraiselvan** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/0e6811d9dfd94cb779b1dc5a6715f42d2ca52b77

Should be part of v2.26
