### ISSUE TITLE
Event Triggers: Webhook Url should also take an env var

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#966]
This will help in keeping same migrations for different environments.

@dsandip Will need console changes.

**Comment by dsandip** [comment]
@tirumaraiselvan Add the c/console and mockup-required labels?

**Comment by dsandip** [comment]
@karthikvt26 The UI for this should be the same as the one for [this](https://github.com/hasura/graphql-engine-internal/issues/38), post your discussion with @shahidhk and @rikinsk (who have feedback on those radio buttons)
