### ISSUE TITLE
Input validation pre-hooks for tables

### ISSUE THREAD

**Issue by soorajshankar** [hasura/graphql-engine#9672]
## Feature Description

Provide a way to validate input data before inserting data to a table, this can be a webhook that respond whether the data can be inserted or not. 

## User value / outcome

Added security on the insert Mutations 

## Current status 

1. RFC is validated and implemented the first version.
2. Server Implementation is in progress.
3. Console UI development is in progress. 

## Resources (e.g. RFCs)

[RFC](https://github.com/hasura/graphql-engine/pull/9463)

**Comment by marionschleifer** [comment]
This has been completed and is live. Come to our community call this Thursday, 27th July to see a demo on it. Sign up [here](https://hasura.io/community/community-call/) ✨
