### ISSUE TITLE
Subscriptions send messages of invalid type on expired JWT

### ISSUE THREAD

**Issue by sheldonbaker** [hasura/graphql-engine#9689]
### Version Information

Server Version: 2.25.1

### Environment

OSS

### What is the current behaviour?

In response to a message of type `connection_init`, if the JWT passed in the `Authorization` header is expired, the server responds with a message of type `connection_error` is returned (`{"type":"connection_error","payload":"Could not verify JWT: JWTExpired"}`). If I'm interpreting correctly, this type is out of scope with the graphql-ws subprotocol (https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md), and seems to be a relic of the older, alternative spec (https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_connection_error)

This causes an error in the client-side `graphql-ws` library (https://the-guild.dev/graphql/ws/recipes#client-usage-with-urql), for example, as it does not expect to ever receive a message of type `connection_error`.

### What is the expected behaviour?

Presumably, a message of type `error` (https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#error) should be sent instead.

### How to reproduce the issue?

1. Construct a `graphql-ws` client that sends an expired bearer token in the `Authorization` header to graphql-engine (https://the-guild.dev/graphql/ws/recipes)
2. Observe websocket messages via devtools that include an event of type `connection_error` 

#### Message logs
{"type":"connection_init","payload":{"headers":{"Authorization":"Bearer eyJ..."}}}
{"type":"ping","payload":{"message":"keepalive"}}
{"type":"pong","payload":{"message":"keepalive"}}
{"type":"connection_error","payload":"Could not verify JWT: JWTExpired"}

**Comment by manasag** [comment]
Hi @sheldonbaker, the fix is in-progress. More updates will be provided soon on this issue.

**Comment by purugupta99** [comment]
The fix for this issue has been merged with this commit: https://github.com/hasura/graphql-engine/commit/e69d4c445f1ea2382e5348970a558a926f6fc27f

Closing the issue for now.
