### ISSUE TITLE
payload created at missing z

### ISSUE THREAD

**Issue by jcmoore0** [hasura/graphql-engine#9699]
### Version Information

Server Version: v2.26.0-cloud.1

### What is the current behaviour?

Event payload.created_at is missing 'z' for UTC and will not marshall without a z or time zone offset.
```
"payload": {
        "created_at": "2023-06-06T17:58:29.957389",
        "delivery_info": {
```

### What is the expected behaviour?

The created_at should end with a Z. 
```
"payload": {
        "created_at": "2023-06-06T17:58:29.957389Z",
        "delivery_info": {
```

### How to reproduce the issue?

1.   Review event processing log as of today.

### Any possible solutions/workarounds you're aware of?

Remove this from all consumers, don't marshall this as timestamp.

### Keywords

payload created at

**Comment by adas98012** [comment]
@jcmoore0 
This is a change to address a bug in earlier release. [changelog](https://hasura.io/changelog/enterprise-edition/v2.26.0)

**Comment by jcmoore0** [comment]
Thanks Ashok.
