### ISSUE TITLE
console warnings for header values in migrations

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#970]
Needed for event triggers and schema stitching:
The console should warn if you are using values directly instead of environment variables for webhooks and remote schema URLs. Because if you have multiple environments, the webhook URLs could be different.
This can just be a warning note between the title and the dropdown like this:

![console warning](https://user-images.githubusercontent.com/24300818/49934325-13a73280-fef4-11e8-9061-412d9d433846.png)

The text for note: 
a) event triggers:`Specifying the webhook URL via an environmental variable is recommended if you have different URLs for multiple environments.`
b) remote schemas: `Specifying the server URL via an environmental variable is recommended if you have different URLs for multiple environments.`

@shahidhk Will this work?

**Comment by gopal-virtual** [comment]
Working on this issue.
