### ISSUE TITLE
Unable to track PostgreSQL table with an array (enum): not a valid GraphQL identifier

### ISSUE THREAD

**Issue by timopulkkinen** [hasura/graphql-engine#9744]
### Version Information

Server Version: v2.29.0-beta.1-ce
CLI Version (for CLI related issue):

### Environment

OSS

### What is the current behaviour?

When trying to track a table xyz, Hasura reports the following error:

`cannot use SQL type \"xyz_type[]\" in the GraphQL schema because its name is not a valid GraphQL identifier`

### What is the expected behaviour?

Table is trackable.

### How to reproduce the issue?

1. Create the following table structure in PostgreSQL:

`
CREATE TYPE xyz_type AS ENUM ('a', 'b','c');

CREATE TABLE xyz (
    id bigserial primary key,
    my_types xyz_type[]
);
`
2. Try to track the table using Hasura UI

### Please provide any traces or logs that could help here.

`
{"detail":{"http_info":{"content_encoding":null,"http_version":"HTTP/1.1","ip":"127.0.0.1","method":"POST","status":400,"url":"/v1/metadata"},"operation":{"error":{"code":"validation-failed","error":"cannot use SQL type \"xyz_type[]\" in the GraphQL schema because its name is not a valid GraphQL identifier","path":"$.args[0].args"},"query":{"type":"bulk"},"request_id":"998044d6-2ade-4434-8e61-01cbde612b42","request_mode":"error","response_size":170,"uncompressed_response_size":170,"user_vars":{"x-hasura-role":"admin"}},"request_id":"998044d6-2ade-4434-8e61-01cbde612b42"},"level":"error","timestamp":"2023-06-30T11:23:35.312+0000","type":"http-log"}
`

### Any possible solutions/workarounds you're aware of?

No.

### Keywords

array, postgresql, 2.29

**Comment by danieljharvey** [comment]
Hi! Thanks for submitting this and including a clear reproduction. This should be fixed in the upcoming `2.29` release.
