### ISSUE TITLE
Feature request: Support access old data in upsert mutation

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#975]
In upsert mutation, is there any way to do this via graphql ?

```sql
INSERT INTO users (id, level)
VALUES (1, 0)
ON CONFLICT (id) DO UPDATE
SET level = users.level + 1;
```

The general case is to access old data in the set command.

My real world use case is to use rollup table to scale subscription. (Instead of using view to reload data)

**Comment by 0x777** [comment]
Closing this in favour of #1749
