### ISSUE TITLE
_text GraphQL type no longer exists in v2.29

### ISSUE THREAD

**Issue by ProjectFrank** [hasura/graphql-engine#9756]
### Version Information

Server Version: 2.29
CLI Version (for CLI related issue):

### Environment

Local docker 2.29 images

### What is the current behaviour?
Built-in GraphQL mutations that handle Postgres arrays of strings no longer accept a `_text` type and take a `[String!]` instead, breaking client-server compatibility. Related issue: https://github.com/hasura/graphql-engine/issues/7187

### What is the expected behaviour?
Clients using mutations that use a `_text` parameter type should continue to work.

### How to reproduce the issue?

1. Use v2.28 of the engine.
2. Via the Hasura console, create a column in a Postgres table that holds a `text[]`.
3. Examine the `insert_<schema>_<table>_one` mutation's parameters in the graphiql docs.
4. Observe that the array column on the mutation input type is of type `_text`.
5. Use v2.29 of the engine.
6. Examine the `insert_<schema>_<table>_one` mutation's parameters in the graphiql docs.
7. Observe that the array column on the mutation input type is of type `[String!]`.

### Screenshots or Screencast

(See the `permissions` field)

**v2.28**
![image](https://github.com/hasura/graphql-engine/assets/8015872/1edd7982-b893-47ad-b956-669863f6a841)

**v2.29**
![image](https://github.com/hasura/graphql-engine/assets/8015872/60834349-c307-4f83-8242-d11b7bb11e56)

### Please provide any traces or logs that could help here.

N/A

### Any possible solutions/workarounds you're aware of?

N/A

### Keywords

_text array postgres postgresql v2.29 breaking

**Comment by danieljharvey** [comment]
Hi! Thanks for the detailed report! This was changed to fix a [long-standing issue with Postgres array support](https://github.com/hasura/graphql-engine/issues/348).

Can you provide a reproduction of your client-side issue? While the type has changed, the values passed to it should continue to be accepted. If you can provide an example of a regression in a query, we can look into this further.

**Comment by ProjectFrank** [comment]
I see, that makes sense. The issue I'm having is specifically with GraphQL codegen where it is trying to validate our GraphQL queries against our Hasura schema before generating code for our application. We've updated our GraphQL queries to use `[String!]` instead of `_text`. Unfortunately, we're now stuck in a situation where we can't deploy changes to our client application because our build process can't run GraphQL codegen against our Hasura Cloud instance because it's running v2.28.2, but our dev and CI environments work just fine because they use the docker image with the `latest` tag pointing to v2.29.

Our workaround for the time being may be to simply pin our dev and CI environments to v2.28.2 and go back to using the `_text` type in our queries.

**Comment by ProjectFrank** [comment]
Actually, version pinning doesn't work for us because deploying a new Hasura Cloud preview environment creates a v2.29 instance so our preview environments don't build anymore. Is there a way to either specify the GraphQL engine version when deploying a preview environment, or manually upgrading an existing Hasura Cloud instance from v2.28 to v2.29?

**Comment by danieljharvey** [comment]
Hello! We've made a new experimental feature flag that allows you to regain the old behaviour, would you mind giving it a try and seeing if it solves your problem?

AMD64 image: `hasuraci/graphql-engine:dev-cf04916-djhparse-underscored-text-types.ubuntu.amd64`
ARM64 image: `hasuraci/graphql-engine:dev-cf04916-djhparse-underscored-text-types.ubuntu.arm64`

If you run them with the environment variable `HASURA_GRAPHQL_EXPERIMENTAL_FEATURES=disable-postgres-arrays` it should give you the `_text` type again.

**Comment by ProjectFrank** [comment]
@danieljharvey will the `HASURA_GRAPHQL_EXPERIMENTAL_FEATURES` environment variable work when deploying a Hasura Cloud Preview environment? Our main problem is that we can't deploy to a preview environment _and_ our staging environment because one uses `[String!]` and the other uses `_type`.

**Comment by danieljharvey** [comment]
Hello! Yes - you are able to set environment variables in Cloud Preview: https://hasura.io/docs/latest/cloud-ci-cd/preview-apps/#preview-apps-api

**Comment by rikinsk** [comment]
@ProjectFrank `v2.29.1-cloud.1` which has the version has not yet been rolled out to the cloud free tier where the preview apps get built. we will have this rolled out soon and then the experimental flag should work.

**Comment by danieljharvey** [comment]
@ProjectFrank `v2.29.1-cloud.1` has now been rolled out to the cloud free tier, so the flag should be available in preview apps now.

**Comment by ProjectFrank** [comment]
I wasn't able to validate because all our Hasura Cloud environments are now running v2.29.1, but I appreciate the support here. Thank you!
