### ISSUE TITLE
Console: Invalid error shown for multiple top level fields in subscription

### ISSUE THREAD

**Issue by hrj** [hasura/graphql-engine#976]
The following query shows an error in the GraphiQL console "Subscription xyz must select only one top level field".

```
subscription xyz {
  abc { id },
  pqr { id }
}
```

However, the query works fine when executed.

**Comment by coco98** [comment]
@hrj Unfortunately, multiple top level fields are not a part of the GraphQL subscription spec:
https://facebook.github.io/graphql/draft/#sec-Single-root-field

**Comment by slowr** [comment]
@coco98 yes it is for normal query but not for subscription. I know that GraphQL subscription spec does not allow multiple top levels but is there a possibility to have the aggregations inside the table instead of having a different one to achieve this subscription?

Example of what I need:
```
subscription getCountAndNames {
  profile_aggregate {
    aggregate {
      count
    }
    nodes {
      id
      name
    }
  }
}
```

**Comment by slowr** [comment]
didn't find inside the documentation that nodes exists inside the aggregate table. thanks for the help!

**Comment by revskill10** [comment]
The funny thing is that, though it shows error, you can still subscribe to multi root queries.
In this case, i recommend to use `graphqurl` if you want to consume that subscription. ApolloClient doesn't support it (yet)

**Comment by shahidhk** [comment]
@hrj Please re-open if there are further questions.

**Comment by calvinl** [comment]
Commenting here - I have a need to retrieve the total count of a particular query, but also provide pagination using `limit` and `offset`. With a normal query I can simply remove the offset/limit portion of the arguments, but with I've found that `aggregate` will return the total count constrained to the `limit` that's set - is there a way to accomplish this with limiting queries but still return the total count of the full query?

**Comment by shahidhk** [comment]
@calvinl You should make aggregate query to get total count separate from the query that selects the nodes.
```gql
query {
  profile_aggregate {
    aggregate {
      count
    }
  }
  profile (limit: 10, offset:0)
    id
    name  
  }
}
```

**Comment by calvinl** [comment]
@shahidhk this is for a subscription which only allows one top level node.
