### ISSUE TITLE
Action has wrong performance at header forwarding.

### ISSUE THREAD

**Issue by zooeywm** [hasura/graphql-engine#9762]
### Version Information

Server Version: v2.27.0
CLI Version (for CLI related issue): The same hasura server web client.

### Environment

Cloud

### What is the current behaviour?

When I'm trying to set up an action which forward graphql request to keycloak to get user information, I select the `Forward client headers to webhook` to forward user's Authorization header and I set this header in client request but it always return 401, but I cancel select this option, hardcode the authorization header, it works.

### What is the expected behaviour?

It should correctly forward client's header to the webhook. I'm not sure if it only happens on `Authorization` header.

### How to reproduce the issue?

1. Set up a simple web server and an api who can print `Authorization` http request header.
2. Request this action via hasura action, and select `Forward client headers to webhook`.
3. Set `Authorization` header and test the action.

### Keywords

Action, Header Forward

**Comment by ecthiender** [comment]
@zooeywm what is the response and status code your action webhook returns, when `forward client headers` is set?

**Comment by zooeywm** [comment]
> @zooeywm what is the response and status code your action webhook returns, when `forward client headers` is set?

It returns 401, because the request made by the action doesn't have the `Authorization Header` when forward client headers is set.
