### ISSUE TITLE
I still see the issue present using Hasura `2.30.0-beta.1` with the streaming subscription.

### ISSUE THREAD

**Issue by FraneJelavic** [hasura/graphql-engine#9785]
I still see the issue present using Hasura `2.30.0-beta.1` with the streaming subscription.
I have the field marked as `NOT NULL` in the DDL and the permissions are set to `_eq = x-hasura-customer-id`.
I've also unchecked the column permission for this field and still I have the `OR x-hasura-customer-id IS NULL` condition in the queries.

_Originally posted by @FraneJelavic in https://github.com/hasura/graphql-engine/issues/9637#issuecomment-1637478475_

**Comment by SamirTalwar** [comment]
Hey @FraneJelavic, would you mind sharing the SQL generated when you use the "Analyze" button in the Hasura Console?

(Please feel free to redact anything sensitive.)

**Comment by FraneJelavic** [comment]
Hi @SamirTalwar,
I've rechecked the query plan and it is working.
Upon first upgrade to version `2.30.0-beta.1` and changing the metadata so the field is `NOT NULL` I didn't see the changes, but now looking in the database logs of the generated queries I see that it is working as expected.

Thank you for the response and apologize for the redundant bug.

**Comment by SamirTalwar** [comment]
No worries, glad we could figure it out. ^_^
