### ISSUE TITLE
Error in the gatsby-graphql tutorial

### ISSUE THREAD

**Issue by ktan114** [hasura/graphql-engine#979]
In the following tutorial: graphql-engine/community/boilerplates/gatsby-postgres-graphql

Missing: "node-fetch": "^2.2.0" dependency in the package.json

Utilized in: gatsby-config.js: "const fetch = require('node-fetch')"

**Comment by coco98** [comment]
@karthikvt26 Please take note!

**Comment by karthikvt26** [comment]
@ktan114 did you face a `module not found` error? because this package gets installed automatically as part of other submodules.

**Comment by marionschleifer** [comment]
@ktan114 I'm closing this issue. If you would like to add anything to it, feel free to re-open 🙂
