### ISSUE TITLE
In the Relationships tab, created Array relationships have their columns reversed

### ISSUE THREAD

**Issue by BrandonWade** [hasura/graphql-engine#9802]
### Version Information

Server Version: `v2.30.1-cloud.1`
CLI Version (for CLI related issue): N/A

### What is the current behaviour?
There is a visual bug with existing Array relationships on the Relationships tab. In the table for existing relationships under the `Relationship` heading, the columns for the "source" and "target" tables are reversed.

For example, consider a schema with two tables: `feed_line` and `feed_frame`, where one `feed_line` has many `feed_frames`. The tables are connected via a foreign key: `feed_frame.feed_line_id` references `feed_line.id`. In the Relationship column, the relationship will be displayed as `feed_line.feed_line_id -> feed_frame.id`.

The actual relationships function correctly for queries, so I believe this is just a visual bug. Additionally, this does not appear to affect Object relationships, nor does it appear to affect suggested Array relationships - it only affects **created** Array relationships.

### What is the expected behaviour?
In the table for existing relationships under the `Relationship` heading, the columns for the "source" and "target" would display correctly.

Using the above example with `feed_line` and `feed_frame`, the correct behaviour would be the Relationship column displaying as `feed_line.id -> feed_frame.feed_line_id`.

### How to reproduce the issue?
1. Create two tables where one has a foreign key and a 1-to-many relationship with the other
2. In Hasura, create an Array relationship using the foreign key
3. In the Relationship column, the column names will be reversed

### Screenshots or Screencast
Example of the issue:
![image](https://github.com/hasura/graphql-engine/assets/6392478/0b5b1bdc-d497-4734-99b2-0642cf0c4158)
Note that the Object relationship does not exhibit this behaviour.

### Please provide any traces or logs that could help here.
N/A

### Any possible solutions/workarounds you're aware of?
This issue appears to be strictly visual in nature; the actual relationship functions correctly. As such, there is no workaround needed.

### Keywords
- Array
- Relationship
- Reverse
- Backwards

**Comment by vijayprasanna13** [comment]
@BrandonWade Thanks for reporting the issue! This has been fixed in https://github.com/hasura/graphql-engine/commit/1f11bd388fde103d43444bbcbe585418e283781b and the fix should be available starting from `v2.31.0-beta.1`

**Comment by vijayprasanna13** [comment]
Closing this issue as fixed. (`v2.31.0-beta.1`)
