### ISSUE TITLE
BigQuery Queries not returning more than 1000 rows

### ISSUE THREAD

**Issue by qnm** [hasura/graphql-engine#9831]
### Version Information

Server Version: 2.30.1
CLI Version (for CLI related issue):

### Environment

I am running an EE trial, but self hosted. I would consider this an OSS issue.

### What is the current behaviour?

I am using BigQuery with Hasura.

I have a tracked table which, for some query params, will return 5000-or-so rows.

When I execute the GraphQL I will only get 1000 rows returned.

### What is the expected behaviour?

I would expect Hasura to return the whole resultset, not only 1000 rows.

### How to reproduce the issue?

1. Have a BigQuery table containing more than 1000 rows.
2. Track this BigQuery table.
3. Execute a GraphQL query against the table to return all rows, no limit
4. See only 1000 rows returned

### Screenshots or Screencast

None.

### Please provide any traces or logs that could help here.

This is the source GraphQL:

```
query MyQuery {
  web_analytics_website_search_queries(where: {space_id: {_eq: 136}, date: {_eq: "2023-08-01"}}) {
    space_id
  } 
}
```

This is the generated query. I'm not sure what `@param2` refers to but it seems to apply some limit.

```
copilot/graphql/93e65baf5
{
	"detail": {
		"generated_sql": {
			"web_analytics_website_search_queries": {
				"prepared_arguments": null,
				"query": "SELECT \n`t_website_search_que1`.`space_id` AS `space_id`\nFROM `web_analytics`.`website_search_queries` AS `t_website_search_que1`\nWHERE ((((`t_website_search_que1`.`date`) = (@param0)))\n      AND (((`t_website_search_que1`.`space_id`) = (@param1))))\nLIMIT @param2"
			}
		},
		"kind": "database",
		"query": {
			"operationName": "MyQuery",
			"query": "query MyQuery {\n  web_analytics_website_search_queries(where: {space_id: {_eq: 136}, date: {_eq: \"2023-08-01\"}}) {\n    space_id\n  } \n}\n"
		},
		"request_id": "05b164a8-05db-405b-820b-8bcd3bde0afb"
	},
	"level": "info",
	"timestamp": "2023-08-14T02:53:55.233+0000",
	"type": "query-log"
}
```

And the response:

```
➜  cat test.json | jq ".data.web_analytics_website_search_queries" | jq length                                        
1000
```

### Keywords
BigQuery, limit, native query

**Comment by shahidhk** [comment]
There is a built-in protection to limit selects to 1000 by default. This can be over ridden by setting `global_select_limit` in [Big Query Configuration](https://hasura.io/docs/latest/api-reference/syntax-defs/#bigqueryconfiguration) in metadata.

**Comment by qnm** [comment]
> There is a built-in protection to limit selects to 1000 by default. This can be over ridden by setting `global_select_limit` in [Big Query Configuration](https://hasura.io/docs/latest/api-reference/syntax-defs/#bigqueryconfiguration) in metadata.

Works as intended! Thanks @shahidhk!
