### ISSUE TITLE
MySQL int column showed as string in UI

### ISSUE THREAD

**Issue by mavarazy** [hasura/graphql-engine#9854]
### Version Information

Server Version:
CLI Version (for CLI related issue): 2.32.0

### Environment

OSS

### What is the current behaviour?

string is shown as column type

### What is the expected behaviour?

should be the same as DB type

#### UI
![UI](https://github.com/hasura/graphql-engine/assets/822488/f3dde003-e239-4838-8991-53b28d4161dd)

#### CLI
![CLI](https://github.com/hasura/graphql-engine/assets/822488/1ece5cd6-06fb-4f22-b0fd-fca564cf736d)

**Comment by manasag** [comment]
Hi @mavarazy, thanks for reporting this. We have already identified working on a fix which will be available by next release v2.33
