### ISSUE TITLE
error hasura v.2.32.0

### ISSUE THREAD

**Issue by quytran0311** [hasura/graphql-engine#9855]
<img width="1871" alt="image" src="https://github.com/hasura/graphql-engine/assets/33858773/4bfcb055-6920-48ae-8d9b-bc31d9cea00e">

I have the same problem as above, if anyone has encountered it, please guide me how to solve it, I sincerely thank!!!!

**Comment by rikinsk** [comment]
Hi. I wasn't able to reproduce this. Are you still facing this?

**Comment by marionschleifer** [comment]
@quytran0311 I'm closing this issue since we haven't heard back. Please feel free to re-open should you still face this issue.
