### ISSUE TITLE
Hasura Actions seem to process only 10 requests at a time

### ISSUE THREAD

**Issue by RomansBermansRS** [hasura/graphql-engine#9856]
### Version Information

Server Version: 2.21.0

### Environment

EE

### What is the current behaviour?

We are utilising Hasura Actions for async tasks requiring long processing, but we have discovered that Hasura Actions are hardcoded to process 10 requests at a time, making a system which sends hundreds / thousands requests per second very slow.

Please see https://github.com/hasura/graphql-engine/blob/3f9abc447738b5fa0bd6b8a3ebe7faa2df55e806/server/src-lib/Hasura/GraphQL/Execute/Action.hs#L775 for the limit hardcoded to 10.

Not sure if it is related to https://github.com/hasura/graphql-engine/issues/6962

### What is the expected behaviour?

Expected behaviour would be to have an ability to change this limit via e.g. env variable. 

### How to reproduce the issue?

1. Create an async Action which takes long to complete.
2. Send e.g. 100 requests per second to the Action.

### Any possible solutions/workarounds you're aware of?

Potentially increasing concurrency limit, as right now it is hardcoded to 10, see https://github.com/hasura/graphql-engine/blob/3f9abc447738b5fa0bd6b8a3ebe7faa2df55e806/server/src-lib/Hasura/GraphQL/Execute/Action.hs#L775

Having an env variable for this limit would be very helpful.

**Comment by tirumaraiselvan** [comment]
This has been added via https://github.com/hasura/graphql-engine/commit/33bafdf4506b4101a02e168c4744d3e10a170301 and should be out in next release.
