### ISSUE TITLE
Feature request: Untrack multiple tables at once on the data page

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#986]
Currently, in order to untrack multiple tables, one must navigate each table, click on Modify tab and untrack each table.

We need a way to show tracked tables on `data` page, and there're multi checkboxes for user could untrack multiple tables at once.

**Comment by shahidhk** [comment]
@revskill10 I have added required labels for the issue. As a workaround till functionality is added on the console, you can use the [`untrack_table`](https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/table-view.html#untrack-table) API to untrack multiple tables.

**Comment by revskill10** [comment]
@shahidhk Thanks. A nodejs script is needed in this case.

**Comment by shahidhk** [comment]
@revskill10 You can include multiple `untrack` request in one singe API call using a  `bulk` query.

**Comment by sauzzon** [comment]
I started working on this issue

**Comment by vijayprasanna13** [comment]
Hey folks! We've made a couple of improvements to the tracking UI. Please follow the discussion [here](https://github.com/hasura/graphql-engine/discussions/9727).

**Comment by manasag** [comment]
The new UI in `v2.30.0` supports multi-select tables for untracking. Closing this issue.
