### ISSUE TITLE
Column Duplication Issue on Create Table 

### ISSUE THREAD

**Issue by eisau** [hasura/graphql-engine#9863]
### Environment
Cloud

### What is the current behaviour?
When a user either clicks the 'X' next to the column type or types backspace within the column type, it duplicates the columns that have been already added.

### What is the expected behaviour?
The expected behaviour is that when a user either clicks the 'X' next to the column type or types backspace within the column type, it should not duplicate the columns that have already been added and must clear the text in the column type.

### How to reproduce the issue?

1. Navigate to the Hasura console and click Create Table.
2. Input several columns.
3. Either press the backspace key or click the 'X' icon next to the column type.

### Screenshots or Screencast
https://github.com/hasura/graphql-engine/assets/53991717/e5e2560c-d300-48b9-96e9-ee7af3ef881b

### Please provide any traces or logs that could help here.

N/A

### Any possible solutions/workarounds you're aware of?

N/A

### Keywords
UI, Column, Table, Duplication

**Comment by vijayprasanna13** [comment]
Hey @eisau ! thanks for reporting the issue. We'll look into it.

**Comment by vijayprasanna13** [comment]
Hey @eisau 👋🏼 
We've traced the problem to an empty-state handling bug in the select component wrapper. It's patched as of https://github.com/hasura/graphql-engine/commit/041c63d313b2099d6d0e2f59435fb1d9d6bc0684 and should be available in the next release!

**Comment by eisau** [comment]
@vijayprasanna13 Thanks for the quick response
