### ISSUE TITLE
HTTP Actions Not Working with 4xx Status Code and Custom Response Body Transformer

### ISSUE THREAD

**Issue by mingyang91** [hasura/graphql-engine#9880]
### Version Information

Server Version: v2.31.0

### Environment

OSS running on docker

### What is the current behaviour?

HTTP actions will not work if the upstream HTTP endpoint status code is 4xx and the response body needs to be transformed using a custom template.

### What is the expected behaviour?

Actions work well in this scenario.

### How to reproduce the issue?

1. Add a actions with response body transformer
2. Create a mock server that always responds with a 4xx error.
3. When calling the query/mutation from anywhere, an error as shown in the following screenshots.

### Screenshots or Screencast

![image](https://github.com/hasura/graphql-engine/assets/6914730/ac1f4ab5-20ed-486d-8cd8-0e66765e6636)

### Please provide any traces or logs that could help here.

None

### Any possible solutions/workarounds you're aware of?

The error occurred during JSON parsing and is indicated by a message. Following the Haskell type, I found this code:

https://github.com/hasura/graphql-engine/blob/master/server/src-lib/Hasura/GraphQL/Execute/Action.hs#L689-L694

It seems that if the response code returned by the remote endpoint is `4xx`, then the engine always parses the response body to `ActionWebhookErrorResponse`. However, the body is not defined to return a `message` field, causing the action to always fail as shown in the screenshot.

This bug can be worked around by simply putting a static "message": "any string" in the body transformer.

![image](https://github.com/hasura/graphql-engine/assets/6914730/3eddd893-18e5-4689-920a-1484c50057b0)

I can see that the message will be transparently placed in the error object.

![image](https://github.com/hasura/graphql-engine/assets/6914730/55f56811-62e1-4fea-85a2-abdb87ce9dcc)

### Keywords

ActionWebhookErrorResponse

JSON parsing

Aeson

**Comment by mingyang91** [comment]
I would be very grateful if any maintainer could confirm if this is a bug or something else. I know you're busy, so please take your time. Thank you for your time and effort on this project.

**Comment by tirumaraiselvan** [comment]
@mingyang91 This is expected as the contract for errors in Actions needs to include a `message` key: https://hasura.io/docs/latest/actions/action-handlers/#returning-a-success-response

If your Action doesn't provide one, then you can use Response Transforms to add one artificially: https://hasura.io/docs/latest/actions/rest-connectors/#response-body (see an example in the Note )

**Comment by efstathiosntonas** [comment]
@tirumaraiselvan the docs around [success/error response](https://hasura.io/docs/latest/actions/action-handlers/#returning-a-success-response) are poorly written and we have to guess what we should use on our response objects.
