### ISSUE TITLE
Create an Event Trigger handler for order-status-change notifications

### ISSUE THREAD

**Issue by robertjdominguez** [hasura/graphql-engine#9907]
## Description ✍️ 

Implement an Event Trigger handler in either JavaScript or Python that monitors updates on the `orders` table and creates a new order-status-change notification. Then, write a guide explaining how to implement this handler in a project.

## Acceptance criteria 📋 

- [ ] A single-page guide for the new notification to users utilizing Event Triggers, based on the template in [this directory](https://hasura.io/docs/latest/event-triggers/recipes/index/)
- [ ] The guide should utilize the [docs sample app](https://github.com/hasura/docs-sample-app) and [Hasura Cloud](https://cloud.hasura.io)
- [ ] The guide should clearly explain what the trigger’s payload will look like based on the configuration.
- [ ] A user should easily be able to understand how to destructure / use the values passed from the trigger in their server-side logic.

**Comment by harshalkh** [comment]
@robertjdominguez @Stefmore02 I want to work on this issue.

**Comment by robertjdominguez** [comment]
Hi, @harshalkh 👋 

That's not quite correct. You'll:
- Add a new file in `event-triggers/recipes/`
- ☝️ You can base this off any of the existing files inside that directory (i.e., copy / paste and change out values as needed)
- Within that file, create an event handler that a user can replicate. An example would be like how we have [this one](https://hasura.io/docs/latest/event-triggers/recipes/new-user-welcome/#step-3-create-a-webhook-to-handle-the-request) for welcoming a new user.
- Finally, update the `event-triggers/recipes/index.mdx` to introduce the new recipe 🎉

**Comment by harshalkh** [comment]
Thanks I am initiating work on same.

**Comment by harshalkh** [comment]
@robertjdominguez I have raised PR. please go through and let me know if any suggestions.

**Comment by robertjdominguez** [comment]
@harshalkh — thanks for the effort in this. However, you need to open the PR on _this_ repository, as the issue is here. We're looking to update the docs, which live in `hasura/graphql-engine`, not the `docs-sample-app`. 

Fortunately, it would look like you can bring over the majority of your work and place it in the `event-triggers/recipes` directory. If you're confused, [this is where your changes need to be made](https://github.com/hasura/graphql-engine/tree/master/docs/docs/event-triggers/recipes).

Additionally, if you're going to create new screenshots, please follow our [contribution guidelines](https://hasura.io/docs/wiki/style/images/#screenshots) to match the style of our other assets.

Let me know if you have any other questions, and I'll be happy to review this once the PR is opened on this repository 🎉

**Comment by harshalkh** [comment]
> @harshalkh — thanks for the effort in this. However, you need to open the PR on _this_ repository, as the issue is here. We're looking to update the docs, which live in `hasura/graphql-engine`, not the `docs-sample-app`.
> 
> Fortunately, it would look like you can bring over the majority of your work and place it in the `event-triggers/recipes` directory. If you're confused, [this is where your changes need to be made](https://github.com/hasura/graphql-engine/tree/master/docs/docs/event-triggers/recipes).
> 
> Additionally, if you're going to create new screenshots, please follow our [contribution guidelines](https://hasura.io/docs/wiki/style/images/#screenshots) to match the style of our other assets.
> 
> Let me know if you have any other questions, and I'll be happy to review this once the PR is opened on this repository 🎉

Thanks for quick response. I will work on it..

**Comment by harshalkh** [comment]
@robertjdominguez I have raised new PR now - https://github.com/hasura/graphql-engine/pull/9946

**Comment by robertjdominguez** [comment]
Great @harshalkh 🙌 

I'll take a look later today or tomorrow 📆
