### ISSUE TITLE
Create a Python version of our ET Recipe for SEO Optimization

### ISSUE THREAD

**Issue by robertjdominguez** [hasura/graphql-engine#9908]
## Description ✍️ 

Take this [existing handler](https://hasura.io/docs/latest/event-triggers/recipes/product-description-chatgpt-seo/) written in JavaScript and provide a Python version.

## Acceptance criteria 📋 

- [ ] Use the `<Tabs />` component to create parity with a Python version of the handler already on this page ☝️

**Comment by Smartmind12** [comment]
@Stefmore02 I would like to work on this issue

**Comment by Stefmore02** [comment]
Hey @Smartmind12 nice to see you back! Please feel free to work on it and open a PR, first come, first served.
