### ISSUE TITLE
Create a Python version of our ET Recipe for Content Moderation

### ISSUE THREAD

**Issue by robertjdominguez** [hasura/graphql-engine#9909]
## Description ✍️ 

Take this [existing handler](https://hasura.io/docs/latest/event-triggers/recipes/moderate-user-content-with-gpt/) written in JavaScript and provide a Python version.

## Acceptance criteria 📋 

- [ ] Use the `<Tabs />` component to create parity with a Python version of the handler already on this page ☝️

**Comment by Rutam21** [comment]
Sure @robertjdominguez . Thanks.
