### ISSUE TITLE
Create a Python version of our ST Recipe for Product Reviews

### ISSUE THREAD

**Issue by robertjdominguez** [hasura/graphql-engine#9910]
## Description ✍️ 

Take this [existing handler](https://hasura.io/docs/latest/scheduled-triggers/recipes/product-review/) written in JavaScript and provide a Python version.

## Acceptance criteria 📋 

- [ ] Use the `<Tabs />` component to create parity with a Python version of the handler already on this page ☝️

**Comment by MinuraPunchihewa** [comment]
Hey @robertjdominguez,
I would like to take this up. But, I would like to know if I have understood the task correctly; is the requirement to create this same page, but replace the JS code snippets with Python?

**Comment by robertjdominguez** [comment]
Thanks, @MinuraPunchihewa! Not quite:

We don't need an entirely new page. On this page, we simply need to have the steps to create a Python handler using the [`<Tabs />` component of Docusaurus.](https://docusaurus.io/docs/markdown-features/tabs)

This way, a user can choose either JavaScript or Python when looking at the example 👍

**Comment by ashutuptiwari** [comment]
Hey @robertjdominguez,
I'd like to work on this issue.

**Comment by robertjdominguez** [comment]
Feel free to open a PR @ashutuptiwari 🤙

We'll take any PRs and merge the first one that addressed the issue after review.

**Comment by aniketh-varma** [comment]
Hey @robertjdominguez, please review the [PR](https://github.com/hasura/graphql-engine/pull/9943) whenever you get time. Thanks!

**Comment by robertjdominguez** [comment]
Close by #9940
