### ISSUE TITLE
Create a Python version of our ST Recipe for Coupon Expiration

### ISSUE THREAD

**Issue by robertjdominguez** [hasura/graphql-engine#9911]
## Description ✍️ 

Take this [existing handler](https://hasura.io/docs/latest/scheduled-triggers/recipes/check-expiration/) written in JavaScript and provide a Python version.

## Acceptance criteria 📋 

- [ ] Use the `<Tabs />` component to create parity with a Python version of the handler already on this page ☝️

**Comment by Ambareen09** [comment]
I'd like to work on this issue
