### ISSUE TITLE
Create a Python version of our ST Recipe for Daily Summary Email

### ISSUE THREAD

**Issue by robertjdominguez** [hasura/graphql-engine#9912]
## Description ✍️ 

Take this [existing handler](https://hasura.io/docs/latest/scheduled-triggers/recipes/daily-summary-email/) written in JavaScript and provide a Python version.

## Acceptance criteria 📋 

- [ ] Use the `<Tabs />` component to create parity with a Python version of the handler already on this page ☝️

**Comment by Azanul** [comment]
May I take this up?

**Comment by robertjdominguez** [comment]
Go for it @Azanul 🙌

**Comment by Azanul** [comment]
@robertjdominguez This can be closed since the PR got merged
