### ISSUE TITLE
Create a Python version of our ST Recipe for Abandoned Carts

### ISSUE THREAD

**Issue by robertjdominguez** [hasura/graphql-engine#9913]
## Description ✍️ 

Take this [existing handler](https://hasura.io/docs/latest/scheduled-triggers/recipes/abandoned-cart/) written in JavaScript and provide a Python version.

## Acceptance criteria 📋 

- [ ] Use the `<Tabs />` component to create parity with a Python version of the handler already on this page ☝️

**Comment by GautamGottipati** [comment]
@robertjdominguez I am interested to work on this issue.

**Comment by robertjdominguez** [comment]
Feel free to open a PR and tag the issue @GautamGottipati 🙌

**Comment by SoumyoPurkayastha** [comment]
@robertjdominguez Is this issue still open. I'd like to work on this

**Comment by GautamGottipati** [comment]
Hi @SoumyoPurkayastha  feel free to work on it
