### ISSUE TITLE
Support latest postgress version used by Neon.tech Postgresql for 'hasura migrate create init'

### ISSUE THREAD

**Issue by sethsnel** [hasura/graphql-engine#9918]
### Is your proposal related to a problem?
Unable to create a migrate from cloud project that is using latest Neon.tech Postgresql.

When I run:
`hasura migrate create init --from-server --endpoint https://movie-database.hasura.app --admin-secret ##### --database-name movie-database`

I receive the error:
`time="2023-10-06T17:01:58+02:00" level=fatal msg="cannot fetch schema dump: pg_dump request: 500 \n{\n  \"error\": \"error while executing pg_dump: pg_dump: error: aborting because of server version mismatch\\npg_dump: detail: server version: 16.0; pg_dump version: 15.3 (Ubuntu 15.3-1.pgdg22.04+1)\\n\",\n  \"path\": \"$\",\n  \"code\": \"unexpected\"\n}"`

Since I don't use the docker image, but try to create a migration from hasura cloud project, i'm unable to control the pg_dump version being used.

### Describe the solution you'd like

Ability to select Postgress verson that should be used by cloud project or Hasura CLI.

### Describe alternatives you've considered

None

**Comment by sethsnel** [comment]
Related issues: https://github.com/hasura/graphql-engine/issues/6943

**Comment by SamirTalwar** [comment]
This has been resolved for a number of releases. If you're still seeing this problem, please upgrade accordingly.
