### ISSUE TITLE
Create a Python version of our ET Recipe for Welcoming New Users

### ISSUE THREAD

**Issue by robertjdominguez** [hasura/graphql-engine#9925]
## Description ✍️ 

Take this [existing handler](https://hasura.io/docs/latest/event-triggers/recipes/new-user-welcome/) written in JavaScript and provide a Python version.

## Acceptance criteria 📋 

- [ ] Use the `<Tabs />` component to create parity with a Python version of the handler already on this page ☝️

**Comment by Dhoni77** [comment]
Hi @robertjdominguez I would like to work on this

**Comment by robertjdominguez** [comment]
We'd love it @Dhoni77 👍

**Comment by DhairyaMajmudar** [comment]
@robertjdominguez pls. Assign this issue to me

**Comment by robertjdominguez** [comment]
@DhairyaMajmudar — all issues are first come, first served. I'll review your PR later today @Dhoni77 👍
