### ISSUE TITLE
Metadata not consistent across cloud servers

### ISSUE THREAD

**Issue by jcmoore0** [hasura/graphql-engine#9927]
### Version Information

Server Version:
v2.33.4-cloud.1

### Environment
Cloud

### What is the current behaviour?
Metadata not replicated to horizontally scaled servers in cloud.
After adding 1 column and select permission:
get intermittent error:   "message": "field 'is_external' not found in type

When sending repeated graphql requests, 1 out of about every 4 fails with field not found.
One server has the type correct and another server doesn't yet have the type correct.

### What is the expected behaviour?
Metadata is replicated to horizontally scaled servers in cloud.

### How to reproduce the issue?
It is intermittent and is happening more frequently on our project.

Previously we have solved this issue by:
1.  reloading metadata multiple times
2. adding and removing column, permission in console
3. applying metadata changes via CLI

Reloading metadata completes after 50 seconds.

Today we are unable to resolve.

### Any possible solutions/workarounds you're aware of?
Listed above.

### Keywords
Metadata

**Comment by manasag** [comment]
Hi @jcmoore0 can you create a support ticket for this. Our CS team can then look into your project and resolve this in a better way. You can raise ticket using "Help and Support" section on your dashboard.

**Comment by manasag** [comment]
We have been consistently trying to improve our sync mechanism to avoid this situation, with better proactive monitoring on our side. Closing this issue, but feel free to re-open or create CS ticket if your issue persists.
