### ISSUE TITLE
Azure PostgreSQL <username@hostname> Not Supported

### ISSUE THREAD

**Issue by deman4ik** [hasura/graphql-engine#993]
Tried to connect to Azure PostgreSQL DB which has special username format with "@" in it
`postgres://USERNAME@HOSTNAME:PWD@HOSTNAME.postgres.database.azure.com:5432/postgres`
but got 
`Invalid database-url (HASURA_GRAPHQL_DATABASE_URL).`

**Comment by shahidhk** [comment]
@deman4ik You need to URL encode the username, use `%40` instead of `@`

`postgres://USERNAME%41HOSTNAME:PWD@HOSTNAME.postgres.database.azure.com:5432/postgres`

**Comment by shahidhk** [comment]
We're adding Azure docs soon (see #928) which covers this info.

**Comment by deman4ik** [comment]
It works. Thanks
