### ISSUE TITLE
create or replace view syntax doesn't create track table

### ISSUE THREAD

**Issue by patcito** [hasura/graphql-engine#995]
Discussed with @shahidhk on discord. Basically:

This works (as in view is being tracked by hasura)

```
create view group_by_location as 
select locality, country from "Job" group by locality, country
```

But this doesn't work (as in view is not tracked by hasura):

```
create or replace view group_by_location as 
select locality, country from "Job" group by locality, country
```

**Comment by shahidhk** [comment]
more context:
![image](https://user-images.githubusercontent.com/4124733/48138541-8fe1a100-e2ca-11e8-9610-1fe2a6b26815.png)
![image](https://user-images.githubusercontent.com/4124733/48138557-95d78200-e2ca-11e8-9330-07cb0b3477db.png)

**Comment by revskill10** [comment]
Have you tried reload metadata ?

**Comment by shahidhk** [comment]
@revskill10 Reload metadata won't work in this case since the `track` API call is not made in the first place, even though the `Track table` box is check.
