### ISSUE TITLE
Urgent: Hasura keeps subscriptions running when users close app

### ISSUE THREAD

**Issue by Code-Divine** [hasura/graphql-engine#9963]
Server Version: 2.34.0 but also present on 2.33.*
Hasura and React app running on Azure container and Azure Cosmos Postgres managed database.

The issue:
It is really strange but we've confirmed it. Hasura is running a live subscriptions even when the visitor leaves the site. We have React app, Hasura and the database. So Hasura is the only one that connects to the database

This is last hour report from our app. You can clearly see it has 0 requests.
<img width="851" alt="image" src="https://github.com/hasura/graphql-engine/assets/5454090/d5166c3e-ec21-45ef-ae38-5f78c81a336c">

And this is our database CPU usage, it has average 60% cpu usage.
![image](https://github.com/hasura/graphql-engine/assets/5454090/5a4aab2f-02a6-4574-bca5-121583cab437)

I checked the the active queries in postgres and I found this query constantly present, not stuck but re-executing. 

`SELECT  "__subs"."result_id" , "__fld_resp"."root" AS "result" FROM UNNEST(($1)::uuid[], ($2)::json[]) AS "__subs"("result_id", "result_vars") LEFT OUTER JOIN LATERAL (SELECT  json_build_object('appointment', "_appointment"."root" ) AS "root" FROM  (SELECT  coalesce(json_agg("root" ORDER BY "root.pg.start_on" DESC NULLS FIRST), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_e"  FROM  (SELECT  "_root.base"."id" AS "id", "_root.base"."start_on" AS "start_on", "_root.base"."end_on" AS "end_on", "_root.base"."created_on" AS "created_on", "_root.base"."all_day" AS "all_day", "_root.base"."status_id" AS "status_id", "_root.base"."mt_number" AS "mt_number", "_root.base"."custom_id" AS "custom_id", "_root.base"."user_id" AS "user_id", "_root.ar.root.appointment_procedures"."appointment_procedures" AS "appointment_procedures", "_root.or.service"."service" AS "service", "_root.or.client"."client" AS "client", "_root.or.invoice"."invoice" AS "invoice", "_root.or.business_location"."business_location" AS "busine....`

And that query is from a live subscription we have. It's no cron job or anything of the sort. It's a subscription that pulls realtime appointment data. And it's fine to execute when we have users present, but during off hours when as you can see from the number of requests no one is using our app. I shut down the Hasura container and the database CPU dropped to 1%. So clearly a Hasura issue.

A quick google search found me this https://github.com/hasura/graphql-engine/issues/7737 another person had the same issue.

**Comment by tirumaraiselvan** [comment]
@Code-Divine Does it go away after 3 minutes or so? We have a DB connection open for an idle timeout period (3 minutes default)

**Comment by Code-Divine** [comment]
> @Code-Divine Does it go away after 3 minutes or so? We have a DB connection open for an idle timeout period (3 minutes default)

@tirumaraiselvan No, it does not. It runs infinitely until I restart Hasura.

**Comment by akespresso** [comment]
Same here on paid cloud instance `v2.35.1-cloud.2`.  We're using the default batch=100 and refetch=1sec.

@tirumaraiselvan is there a way to reach out privately to resolve this? 

It is incredibly frustrating because the entire database grinds to a halt. One unrelated query went from 3 sec load to 24+ sec load.

I first became aware when multiple jobs started timing out (60 second Hasura limit) after the feature with subscription saw first usage. Note that the feature and schema has been around for multiple quarters and we never had any issue.

**Comment by codingkarthik** [comment]
@Code-Divine We've tried to repro this issue at our end but were not able to do it. So, can you help me repro this issue by answering the following questions:

1. Are you deploying Hasura on your own or do you use Hasura cloud?
2. Does this issue happen with a specific subscription query or any subscription query?
3. The graphql-engine uses [multiplexing](https://hasura.io/docs/latest/subscriptions/postgres/livequery/execution/#subscription-multiplexing) to run subscriptions, which means that even if one client is running a subscription, the DB will get polled as long as that client has the subscription running.

**Comment by tirumaraiselvan** [comment]
@Code-Divine Will you be able to confirm that the issue goes away with v2.32?

**Comment by soupi** [comment]
We believe this issue has been addressed by https://github.com/hasura/graphql-engine/commit/cfb7b58c90ec0c860ccfea27dfec270d81bed713 and released in [v2.40.0](https://github.com/hasura/graphql-engine/releases/tag/v2.40.0). Please let us know if this is not the case.

**Comment by matan44** [comment]
We started experiencing this recently, on a plan and currently v2.41.0-cloud.1.
We are also seeing a huge spike in the data passthrough we are billed for, and as a result removed most of the subscriptions we have.

**Comment by soupi** [comment]
Hi @matan44, could you share a bit more details about the issue you are facing? Is it a new issue that was introduced in a later version? Thanks.
