### ISSUE TITLE
Also prettify variables json when clicking prettify query button

### ISSUE THREAD

**Issue by bertyhell** [hasura/graphql-engine#9968]
### Is your proposal related to a problem?

When i click the prettify button in the web console only the query is prettified, and not the json for the variables.

![image](https://github.com/hasura/graphql-engine/assets/1710840/e84c6395-1674-4350-aa9d-d112465322d4)
![image](https://github.com/hasura/graphql-engine/assets/1710840/eff6628a-d665-4def-b43e-b224e5243e23)

### Describe the solution you'd like

Both the query and the variable json should get prettified

### Describe alternatives you've considered

You could have the user manually prettify the variable json or copy it out into an external json prettify tool. But that is less convenient

**Comment by rikinsk** [comment]
Fixed via https://github.com/hasura/graphql-engine/pull/9969
