### ISSUE TITLE
Applying existing metadata on fresh database is not creating event triggers using cli workflow

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#9976]
Events are shown in console but the backing triggers in postgres are not being created in database.

**Comment by tirumaraiselvan** [comment]
@abdullah2993 What version is this?

**Comment by abdullah2993** [comment]
latest `v2.35.0`

**Comment by tirumaraiselvan** [comment]
Does it work with v2.34?

**Comment by abdullah2993** [comment]
haven't checked, let me give it a shot...will get back to you asap

**Comment by abdullah2993** [comment]
yes, It works on `v2.34.0`

**Comment by tirumaraiselvan** [comment]
Just to be clear, you are not able to see events being generated for event triggers in v2.35?

**Comment by abdullah2993** [comment]
the events are created as in I can see them in the UI but the backing triggers that are created in postgres named `notify_hasura_*` are not created.

**Comment by tirumaraiselvan** [comment]
Can you paste the screenshot pls? Events are generated by the Postgres trigger so it's not clear what you are referring to.

**Comment by abdullah2993** [comment]
1. have a fresh database, nothing in it.
2. apply metadata using hasura-cli (that has events)
3. apply migrations using hasura-cli
4. reload metadata using hasura-cli
5. open hasura console
6. go to events tab I can see events
7. open pgadmin to to table, no `notify_hasura_` triggers

Hopefully that makes sense

**Comment by tirumaraiselvan** [comment]
> go to events tab I can see events

Do you also see events being generated inside each Event Trigger . An event basically has uuid, timestamp, etc.

**Comment by abdullah2993** [comment]
> > go to events tab I can see events
> 
> Do you also see events being generated inside each Event Trigger . An event basically has uuid, timestamp, etc.

I haven't tried firing an event, let me try

**Comment by tirumaraiselvan** [comment]
Can you share your metadata and migrations so we can repro it on our end? We are not able to reproduce this on our end with a simple setup.  If you prefer, you can mail it to `tiru@hasura.io`

**Comment by abdullah2993** [comment]
> Can you share your metadata and migrations so we can repro it on our end? We are not able to reproduce this on our end with a simple setup. If you prefer, you can mail it to `tiru@hasura.io`

no they are not firing, Pending Events, Processed Events,Invocation Logs all tabs are empty presumably because there are no triggers in postgres.
I can't really share the metadata and migrations. Let me see if I can make a reproducible sample(will take time)

**Comment by codingkarthik** [comment]
@abdullah2993 You can fix this issue temporarily by doing the following:

```bash
curl --location '<YOUR_HASURA_HOST>/v1/metadata' \
--data '{
    "type": "reload_metadata",
    "args": {
        "recreate_event_triggers": true
    }
}'
```

Meanwhile, we will figure out the issue.

**Comment by tirumaraiselvan** [comment]
@abdullah2993 Pls try 2.35.1 and let us know if it works allright now

**Comment by abdullah2993** [comment]
@tirumaraiselvan sorry for the delay(holidays 🤷🏾), it works now with `v2.35.1`
