### ISSUE TITLE
REST Endpoints page typos

### ISSUE THREAD

**Issue by corysimmons** [hasura/graphql-engine#9996]
![image](https://github.com/hasura/graphql-engine/assets/224636/b0ae7de4-d893-4072-8a24-56660f0b1bcc)

Grep project for this `No Rest Enpoints available for currect search`

This should be `No REST Endpoints available for current search`

**Comment by rikinsk** [comment]
Thanks for letting us know. Fixed  via https://github.com/hasura/graphql-engine/commit/5156703d6586b376d534a9c31923d76164a990d4
